### ISSUE TITLE
Subscription Update

### ISSUE THREAD

**Issue by qazn123** [transistorsoft/flutter_background_geolocation#10]
I purchased one subscription for the cordova-background-gelocation plugin and it's time to update. We no longer use this cordova plugin since we're switching over to using the flutter moving forwards. Would this subscription update allow us access to the flutter-background-geolocation repository going forward?

Thanks!

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
No.  Every product requires purchasing a distinct license.

https://www.transistorsoft.com/shop/products/flutter-background-geolocation
