### ISSUE TITLE
Not able to getCurrentPosition in some conditions 

### ISSUE THREAD

**Issue by chirag-chopra** [transistorsoft/flutter_background_geolocation#1002]
Wants to show a dialog of not able to get current location to the user with retry and cancel option
Show a dialog box if device is not able to get current location

## Your Environment
* Plugin version: flutter_background_geolocation: ^4.10.1, background_fetch: ^1.1.5
* Platform: iOS or Android
* OS version: Android 12
* Device manufacturer / model: Nokia T20
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.6 21G115 darwin-x64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
* Plugin config:
```
W/TSLocationManager(27361):   ⚠️  Location error: 408
I/flutter (27361): [BackgroundGeolocation onLocation] ‼️ Unhandled location error: [LocationError code: 408, message: ].
I/flutter (27361): Eg:  BackgroundGeolocation.onLocation(_onLocation, (LocationError error) {
I/flutter (27361): 	// Handle LocationError here.
I/flutter (27361): 	print("[onLocation] ERROR: $error");
W/TSLocationManager(27361): [c.t.l.a.BackgroundGeolocation _onLocationError]
W/TSLocationManager(27361):   ⚠️  Location error: 408
I/flutter (27361): [BackgroundGeolocation onLocation] ‼️ Unhandled location error: [LocationError code: 408, message: ].
I/flutter (27361): Eg:  BackgroundGeolocation.onLocation(_onLocation, (LocationError error) {
I/flutter (27361): 	// Handle LocationError here.
I/flutter (27361): 	print("[onLocation] ERROR: $error");
```

## Expected Behavior
Wants to show a dialog of not able to get current location to the user with retry and cancel option

## Actual Behavior
Getting Error in console of 408
Well, I am using `getCurrentPosition()` 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

W/TSLocationManager(27361):   ⚠️  Location error: 408
I/flutter (27361): [BackgroundGeolocation onLocation] ‼️ Unhandled location error: [LocationError code: 408, message: ].
I/flutter (27361): Eg:  BackgroundGeolocation.onLocation(_onLocation, (LocationError error) {
I/flutter (27361): 	// Handle LocationError here.
I/flutter (27361): 	print("[onLocation] ERROR: $error");
W/TSLocationManager(27361): [c.t.l.a.BackgroundGeolocation _onLocationError]
W/TSLocationManager(27361):   ⚠️  Location error: 408
I/flutter (27361): [BackgroundGeolocation onLocation] ‼️ Unhandled location error: [LocationError code: 408, message: ].
I/flutter (27361): Eg:  BackgroundGeolocation.onLocation(_onLocation, (LocationError error) {
I/flutter (27361): 	// Handle LocationError here.
I/flutter (27361): 	print("[onLocation] ERROR: $error");

``` <!-- syntax-highligting:  DO NOT REMOVE -->
try {
      bg.Location cLoc = await bg.BackgroundGeolocation.getCurrentPosition(
          timeout: 30,
          samples: 1,
          extras: {"event": "background-fetch", "headless": true});

      bool isNetWorking = await checkIfInternetWorking();
      String? finalAddress;

      if (isNetWorking == true) {
        List<Placemark> placemarks = await placemarkFromCoordinates(
            cLoc.coords.latitude, cLoc.coords.longitude);
        finalAddress =
            "${placemarks[0].name}, ${placemarks[0].subLocality}, ${placemarks[0].thoroughfare}, ${placemarks[0].locality}, ${placemarks[0].postalCode}, ${placemarks[0].administrativeArea}, ${placemarks[0].country}";
      }
} on TimeoutException {
      // dialog box
      CustomLocationError(txt: 'Unable to get location');
    } catch (e) {
       // dialog box
      CustomLocationError(txt: 'Unable to get location');
    }
```

</details>

**Comment by christocracy** [comment]
See API docs [`onLocation`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/onLocation.html) and [`getCurrentPosition`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/getCurrentPosition.html) to learn how to catch location errors.

**Comment by chirag-chopra** [comment]
```
bg.Location cLoc = await bg.BackgroundGeolocation.getCurrentPosition(
            timeout: 30,
            samples: 1,
            extras: {"event": "background-fetch", "headless": true})
        .catchError((error) {
      CustomLocationError(txt: 'Unable to get location');
    });
```


Is there anything I am missing?

**Comment by christocracy** [comment]
>Is there anything I am missing?

Yes:  the name of the method which has an "Unhandled error".  the `onLocation` method accepts **two** params:  a `success` callback and a `failure` callback.  You did not provide the 2nd param.  See the API docs `onLocation`.

>[BackgroundGeolocation onLocation] ‼️ Unhandled location error:

**Comment by christocracy** [comment]
Also, your error-handling on `.getCurrentPosition` is incorrect.

When you `await` a dart function that returns a`Future` you do not `.catchError` on it &mdash; you use a `try/catch` block.

With `dart` `Future`, you **either** `.then() / catchError()` **OR** `try / catch` with `await`.

See Dart docs [*Futures and Error Handling*](https://dart.dev/guides/libraries/futures-error-handling)

**Comment by christocracy** [comment]
```dart
try {
          // Fetch current position
          var location = await bg.BackgroundGeolocation.getCurrentPosition(
              samples: 1,
              extras: {
                "event": "background-fetch",
                "headless": false
              }
          );
          print("[location] $location");
        } catch(error) {
          print("[location] ERROR: $error");
        }
```

**Comment by christocracy** [comment]
408 means *Location Timeout*.  The device's location API failed to provide a location.  You are not guaranteed to receive a location by the device's location API.

I simulated my `408` above by turning on *Airplane Mode*.

It's up to you to determine how you handle that.

**Comment by chirag-chopra** [comment]
How I can show custom dialog box when this error occurs?

**Comment by christocracy** [comment]
I don’t provide support for your application user interface.

**Comment by christocracy** [comment]
I’m not an App developer.  User interface is not my specialty.  

My specialty is the background operation of location apis for iOS and Android.

**Comment by chirag-chopra** [comment]
We are not asking for support user interface,
At some places in our application, we are using `getcurrentposition()` method to get the current location, and when the device is unable to get the location we only wants to show a message.

**Comment by christocracy** [comment]
alert(“error”)

**Comment by chirag-chopra** [comment]
Sir we know this already, But I think so you are not getting us, we already tried Try Catch method for error handling and for showing messages but that is not working,
Is there any way to show a message whenever your plugin unable to get location

So, that I could able to check exactly where and what I am missing?

**Comment by christocracy** [comment]
The plug-in has nothing to do with your UI and showing messages.  The plug-in fires events.

What you do in those events is your responsibility.
