### ISSUE TITLE
[Question] how different between on_foot and walking in Activity types

### ISSUE THREAD

**Issue by choim4389** [transistorsoft/flutter_background_geolocation#1007]
In Activity types there are `on_foot`, `walking`. 

Are there any differences between them?

And can I track changes in activity without using the stop function using `disableStopDetection=true`

**Comment by christocracy** [comment]
I do not know if any difference or how the native APIs distinguish them.  The plug-in is merely the receiver of these values directly from the native APIs.  

> And can I track changes in activity without using the stop function using disableStopDetection=true

No.

**Comment by choim4389** [comment]
> I do not know of any difference or how the native APIs distinguish them. The plug-in is merely the receiver of these values directly from the native APIs.
> 
> > And can I track changes in activity without using the stop function using disableStopDetection=true
> 
> No.

but with `disableStopDetection=true`, onActivityChange still works for me. 

And this is the behavior I want. Is there any problem using this?

**Comment by christocracy** [comment]
> disableStopDetection=true

I misread that.  I read `disableMotionActivityUpdates: true`, which disabled motion api.
