### ISSUE TITLE
Android Q not requesting background location permissions

### ISSUE THREAD

**Issue by bwhiteTP** [transistorsoft/flutter_background_geolocation#101]
## Your Environment
* Plugin version: 1.0.12
* Platform: Android
* OS version: Android Q
* Device manufacturer / model: Pixel 2 XL
* Flutter info (`flutter doctor`): Channel stable, v1.7.8+hotfix.3
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```

## Expected Behavior / Actual Behavior
The line
bg.BackgroundGeolocation.requestPermission()
should request background location permissions for Android Q. It does not do this and only allows location to be used when the app is open. This is a new change in how Android is handling location access:
https://developer.android.com/preview/privacy/device-location

## Steps to Reproduce
Using a device with Android Q, run the static method bg.BackgroundGeolocation.requestPermission() in an app. A system dialog will appear the first time asking about location access permissions. There should be 3 options, however there are currently only 2 because of the way permissions are being requested.

## Context
Give Android Q devices background location access.

## Debug logs
n/a

**Comment by christocracy** [comment]
I rely on a [3rd-party lib](https://github.com/nishkarsh/android-permissions) for permissions.

I’m sure he’ll be providing an update soon.

**Comment by christocracy** [comment]
I’ll probably send him a donation to kick-start him.  I’ve done that in the past.

**Comment by christocracy** [comment]
Android Q support published to `1.1.0`
