### ISSUE TITLE
Headless task not working on ios after restarting the device

### ISSUE THREAD

**Issue by rajendraaeologic** [transistorsoft/flutter_background_geolocation#1010]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version:16.3.1
* Device manufacturer / model: iPhone12
* Flutter info (`flutter doctor`):
* Plugin config:

`  Future<void> _configureBackgroundFetch() async {
    BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            startOnBoot: true,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresStorageNotLow: false,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE), (String taskId) async {
      debugPrint("[BackgroundFetch] received event $taskId");

      if (taskId == 'flutter_background_fetch') {
        try {
          // Fetch current position
          var location = await bg.BackgroundGeolocation.getCurrentPosition(
              samples: 1,
              extras: {"event": "background-fetch", "headless": false});
          debugPrint("[location] $location");
        } catch (error) {
          debugPrint("[location] ERROR: $error");
        }

        // Test scheduling a custom-task in fetch event.
        BackgroundFetch.scheduleTask(TaskConfig(
            taskId: "com.transistorsoft.customtask",
            delay: 5000,
            periodic: true,
            forceAlarmManager: true,
            stopOnTerminate: false,
            enableHeadless: true));
      }
      BackgroundFetch.finish(taskId);
    });
  }
`

`  Future<void> _configureBackgroundGeolocation() async {
    // 1.  Listen to events (See docs for all 13 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onHttp(_onHttp);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.onHeartbeat(_onHeartbeat);
    bg.BackgroundGeolocation.onGeofence(_onGeofence);
    bg.BackgroundGeolocation.onSchedule(_onSchedule);
    bg.BackgroundGeolocation.onPowerSaveChange(_onPowerSaveChange);
    bg.BackgroundGeolocation.onEnabledChange(_onEnabledChange);
    bg.BackgroundGeolocation.onNotificationAction(_onNotificationAction);

    // Box deviceInfoBox = Boxes.getDeviceInfoBox();

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
      locationAuthorizationRequest: "Always",
            reset: false,
            // <-- lets the Settings screen drive the config rather than re-applying each boot.
            // Convenience option to automatically configure the SDK to post to Transistor Demo server.
            // Logging & Debug
            url:
                'https://2r4lsdid6c.execute-api.us-east-1.amazonaws.com/prod/sendneurologgerdata',
            method: 'POST',
            params: {
              "userId": PreferenceManager.getString(StringConstants.userIdText),
              "studyCode": PreferenceManager.getString(StringConstants.studyCodeText),
              "eventType": eventTypeEnumNetworkMap(EventType.userData),
            },
            extras: {
              "device_id": PreferenceManager.getString(StringConstants.deviceId),
              "device_model": PreferenceManager.getString(StringConstants.deviceModel),
              "framework": PreferenceManager.getString(StringConstants.framework),
              "version": PreferenceManager.getString(StringConstants.version),
              "os": PreferenceManager.getString(StringConstants.os)
            },
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 25,
            stopTimeout: 5,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            // HTTP & Persistence
            autoSync: true,
            // Application options
            stopOnTerminate: false,
            maxDaysToPersist: 7,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60))
        .then((bg.State state) async {
      debugPrint('[ready] ${state.toMap()}');
      debugPrint('[didDeviceReboot] ${state.didDeviceReboot}');
      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
    }).catchError((error) {
      debugPrint('[ready] ERROR: $error');
    });
  }
`

## Expected Behavior
I am using iPhone 12 when I am installing buil with testflight its should be working fine after restart the device

## Actual Behavior
After restarting the device I am not getting any location update untill I reopen the app

**Comment by rajendraaeologic** [comment]
okay thanks let me check

**Comment by neiljaywarner** [comment]
@rajendraaeologic  what did you find?
