### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by Mohit-tsg** [transistorsoft/flutter_background_geolocation#1018]
Hey There just wanted to know whether this plugin works with permission WHEN In use and can we get rid of ALWAYS ALLOW pop up  for location permission.
If yes how can we do so !! Much Appreciated for the help !!...

**Comment by christocracy** [comment]
If your app acts similar to a jogging app, where the user clicks some sort of [Start Tracking] button, you can use WhenInUse authorization in the background as long as you initiate location tracking while app is in foreground by calling:

await BackgroundGeolocation.start()
await BackgroundGeolocation.changePace(true)

Config.stopTimeout still applies:  if your app enters the stationary state in the background, location-tracking cannot automatically resume in the background with WhenInUse.
