### ISSUE TITLE
Background tracking service triggering a lot of ANR mainly on samsung devices.

### ISSUE THREAD

**Issue by MatyasK** [transistorsoft/flutter_background_geolocation#1019]
## Your Environment
* Plugin version: 4.40.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung devices
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 await bg.BackgroundGeolocation.ready(
      bg.Config(
        url: url,
        authorization: bg.Authorization(
          strategy: 'JWT',
          accessToken: token.accessToken,
          refreshToken: token.refreshToken,
          refreshUrl: refreshUrl,
          refreshPayload: {
            'refreshToken': '{refreshToken}',
            'timeZoneOffset': 0,
          },
          refreshHeaders: {
            'Content-Type': 'application/json',
          },
        ),
        extras: {
          'driverId': _userRepository.user?.id ?? '',
        },
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        enableHeadless: true,
        startOnBoot: true,
        autoSync: true,
        batchSync: true,
        httpRootProperty: 'locations',
        autoSyncThreshold: 10,
        maxBatchSize: 30,
        debug: debug,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        showsBackgroundLocationIndicator: true,
      ),
    );
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

![image](https://user-images.githubusercontent.com/15628788/232447903-8dd490d6-d88f-4872-85d2-59632ea1f5be.png)
![image](https://user-images.githubusercontent.com/15628788/232448019-44ec93c0-1b26-4cb0-a9e8-fcc779f9c0a6.png)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I will attach the related issues here from fb.
Fatal Exception: java.lang.IllegalArgumentException
Expected URL scheme 'http' or 'https' but no colon was found

Fatal Exception: android.app.RemoteServiceException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e9c0632 u0 eu.chaincode.chaincargodriver/com.transistorsoft.locationmanager.service.ActivityRecognitionService}

android.app.AlarmManager.setAndAllowWhileIdle (AlarmManager.java:876)
com.transistorsoft.locationmanager.scheduler.TSScheduleManager.oneShot (TSScheduleManager.java)
com.transistorsoft.locationmanager.service.TrackingService.beginStopTimer (SourceFile)
com.transistorsoft.locationmanager.service.TrackingService.performStopDetection (SourceFile)
com.transistorsoft.locationmanager.service.TrackingService.handleLocationResult (SourceFile)
com.transistorsoft.locationmanager.service.TrackingService.onStartCommand (SourceFile)
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4795)

android.app.AlarmManager.cancel (AlarmManager.java:1230)
com.transistorsoft.locationmanager.scheduler.TSScheduleManager.cancelOneShot (TSScheduleManager.java:129)
com.transistorsoft.locationmanager.service.TrackingService.cancelStopTimer (unavailable:14)
com.transistorsoft.locationmanager.service.TrackingService.performStopDetection (unavailable:197)
com.transistorsoft.locationmanager.service.TrackingService.handleLocationResult (unavailable:269)
com.transistorsoft.locationmanager.service.TrackingService.onStartCommand (unavailable:225)
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:5092)
```

</details>

**Comment by christocracy** [comment]
These ANR are well-known among Android developers and the plugin is not directly at fault -- it is the victim of something in your app consuming too much time on the *Main Thread*, preventing the plugin from calling `Service.startForeground` within *5 seconds* of your app launching.  

See the [Wiki about this](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-ANR-%22Context.startForegroundService()-did-not-then-call-Service.startForeground()%22)

**Comment by MatyasK** [comment]
Any idea why the first one happens then? When we run the app localy, it can refresh the url without any issue only happens on few device.
![image](https://user-images.githubusercontent.com/15628788/232820876-6250fc09-2650-4a70-906b-0586482f8df4.png)

**Comment by christocracy** [comment]
Clearly you provided the plug-in an invalid refreshUrl at some point in time.

**Comment by MatyasK** [comment]
when I use the setconfig to set the new accesstoken does it overwrite the refreshurl?
![image](https://user-images.githubusercontent.com/15628788/232828398-06389ed2-d329-41cb-beee-0c67010eb167.png)
![image](https://user-images.githubusercontent.com/15628788/232828465-491f4e19-3c8e-4668-80a1-921b459371b1.png)

**Comment by christocracy** [comment]
Why don’t you see for yourself.  Call `.setConfig` then read it back from `.state`?

**Comment by MatyasK** [comment]
We were not able to solve the ANR issues within our application.
We moved sharedpreferences to a different thread using flutter_isolate.

however, we still have diskviolations from other packages as well which we were not able to move to flutter isolates, such as (Image_picker, Image Cropper).

Do you have any suggestions, where we should look or how to attack these issue?

our strict mode logs:
https://pastebin.com/C88rzM70

our pubsec.yaml: 

https://pastebin.com/fe0iKUqP

**Comment by MatyasK** [comment]
So we were able to get an ANR while testing.
Here is the log from logcat
https://pastebin.com/zTWmTD67

**Comment by christocracy** [comment]
do this:

In a terminal window, observe the android device logs:
```bash
$ adb logcat *:S StrictMode:V TSLocationManager:V flutter:V`
```

1.  Launch app to foreground.
2. Place app in background.
3. Wait for the following log message from plugin:

```
04-21 09:53:24.450 20571 21296 I TSLocationManager: [c.t.l.scheduler.ScheduleEvent onOneShot]
04-21 09:53:24.450 20571 21296 I TSLocationManager: ╔═════════════════════════════════════════════
04-21 09:53:24.450 20571 21296 I TSLocationManager: ║ ⏰ OneShot event fired: TERMINATE_EVENT
04-21 09:53:24.450 20571 21296 I TSLocationManager: ╠═════════════════════════════════════════════
```

4.  Pull up Android "App Switch" (eg: `[|||]` button) and *swipe* the app to terminate the app.
5. While observing the logs in terminal, **Shake the device** vigorously to simulate walking.  After some time, your app will be launched headless in the background and the plugin enter the tracking state.

I want to see the entire log after the point where you terminate the app to the time where the app is relaunched.

**Comment by christocracy** [comment]
When I do this test in my `/example` app from this repo, I see about `400ms` time difference  between the time where *Android* receives the request to launch the plugin's foreground-service `ActivityRecognitionService` to the time where that service *IS* launched (where it calls `Service.startForeground()`).

```
// <----------------------- This is the Android OS receiving a request to launch one of the plugin's foreground-service
04-21 09:46:18.482  1463  1523 I ActivityManager: Start proc 20571:com.transistorsoft.flutterbackgroundgeolocationexample/u0a407 for service {com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
.
.
.
// <----------------------- This is the Android app process launched.
04-21 09:46:18.701 20571 20571 D TSLocationManager: ********************* Application.onCreate isMain? true
.
.
.
// <----------------------- This is the plugin coming alive.
04-21 09:46:18.831 20571 20602 I TSLocationManager: ╔═════════════════════════════════════════════
04-21 09:46:18.831 20571 20602 I TSLocationManager: ║ TSLocationManager version: 3.4.0 (420)
04-21 09:46:18.831 20571 20602 I TSLocationManager: ╠═════════════════════════════════════════════
.
.
.
// <----------------------- This is the service finally launched after calling Service.startForeground()
04-21 09:46:18.832 20571 20602 D TSLocationManager:   🎾  ActivityRecognitionService [eventCount: 1]
```

`09:46:18.832 - 09:46:18.482 = ~400ms`

**Comment by christocracy** [comment]
Also, show me your `android/build.gradle`

**Comment by MatyasK** [comment]
Hey, so I was not able to test stictmode yet properly, since my phone doesn't recognize the activity change if I just shake it probably, so I will test on multiple devices soon. 
However I see this in the logs: (is it something wrong?)
![image](https://user-images.githubusercontent.com/15628788/233949772-c0cf54cd-1aa2-48a6-9178-eb61dc7c3889.png)

Also yesterday I had to drive quite long distance and the app worked fine for couple of hours, and it started not responding when I drove thru a border (phone lost cellular connections).

app/build.gradle: 
https://pastebin.com/wjb5rq8h

**Comment by MatyasK** [comment]
This is the logs we are able to get after the terminate event:
https://pastebin.com/dcKPFNZy

**Comment by MatyasK** [comment]
@christocracy can you check?

**Comment by christocracy** [comment]
>Invalid Headless Callback ids

[Invalid Headless Callback ids](https://github.com/transistorsoft/flutter_background_geolocation/blob/d8cbf9238461cd286f9f8fc1ac0baa59dc2c8611/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/HeadlessTask.java#L250)

You have a problem in your headless-task setup in your `lib/main.dart`.

**Comment by MatyasK** [comment]
So after I couple weeks of more testing this issue not solved, what we could we could narrow it down a bit.

it likely to happend when the our drivers are drivering throu borderds and phone is trying to change prividers. any suggerstiong about this?

**Comment by christocracy** [comment]
> Background tracking service triggering a lot of ANR mainly on samsung devices

> likely to happend when the our drivers are drivering throu borderds and phone is trying to change prividers

Y

**Comment by christocracy** [comment]
And what *specifially* is the ANR?

have you implemented StrictMode and attempted to resolve your violations?
