### ISSUE TITLE
Gradle build failure - could not find com.transistorsoft.tsbackgroundfetch

### ISSUE THREAD

**Issue by snakebyte3d** [transistorsoft/flutter_background_geolocation#1025]
## Your Environment

* Plugin version: 
flutter_background_geolocation: ^4.10.3

* Platform: Android (it works on iOS)

* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6.3 21G419 darwin-x64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/zsolt.kovacs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/zsolt.kovacs/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/zsolt.kovacs/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)   • 009C1E22-EE64-4B5D-8880-841D28468F20 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
      (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Not relevant
```

## Steps to Reproduce

1. Use same build.gradle and AndroidManifest.xml settings as in the example
2. Use latest dart and flutter versions
3. flutter build apk --release --flavor production
4. Build failed

## Context

Wanted to build the application for Android --release --flavor production
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkProductionDebugAarMetadata'.
> Could not resolve all files for configuration ':app:productionDebugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/zsolt.kovacs/work/spectro_life/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://api.mapbox.com/downloads/v2/releases/maven/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/zsolt.kovacs/.m2/repository/com/transistorsoft/tsbackgroundfetch/
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager-v21:+ as no versions of com.transistorsoft:tslocationmanager-v21 are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - file:/Users/zsolt.kovacs/work/spectro_life/android/app/libs/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - https://api.mapbox.com/downloads/v2/releases/maven/com/transistorsoft/tslocationmanager-v21/maven-metadata.xml
       - file:/Users/zsolt.kovacs/.m2/repository/com/transistorsoft/tslocationmanager-v21/
     Required by:
         project :app > project :flutter_background_geolocation
```

</details>

**Comment by christocracy** [comment]
This has been posted dozens of times.  Search the issues before posting.

duplicate #947
