### ISSUE TITLE
iPhone GPS deviation 'snap to road'?

### ISSUE THREAD

**Issue by willemvanleeuwen** [transistorsoft/flutter_background_geolocation#1027]
## Your Environment
* Plugin version: 4.10.0
* Platform: iOS 
* OS version: iPhone iPhone14,5 16.3.1
* Device manufacturer / model: iPhone iPhone14,5 16.3.1
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.2846], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] VS Code (version 1.74.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    backgroundLocatorSetup = bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        // Logging & Debug
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,

        isMoving: true,
        allowIdenticalLocations: true,
        //update every second
        locationUpdateInterval: 1000,

        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,

        //set to 0 to get an update every second
        distanceFilter: 0.0,
        disableElasticity: true,
        locationAuthorizationRequest: "WhenInUse",

        // Activity recognition options
        stopTimeout: 60,
        backgroundPermissionRationale: bg.PermissionRationale(
          title: RallyStrings.getPermissionLabel('title'),
          message: RallyStrings.getPermissionLabel('message'),
          positiveAction: RallyStrings.getPermissionLabel('positive_action'),
          negativeAction: RallyStrings.getPermissionLabel('negative_action'),
        ),
        notification: bg.Notification(
          title: "Route active",
          channelName: "Location tracking",
          text: "Track location in background",
        ),

        // HTTP & Persistence
        autoSync: true,
        // Application options
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: false,
        heartbeatInterval: 60,
        preventSuspend: true,
      ),
    );
```

## Expected Behavior

We had 25 devices (iOS and Android) driving the exact same route.  On a specific spot, the route went from one side of the water to the other side over a small bridge. It was expected that all route/GPS tracks were showing the route going from one side of the water to the other side and later on back again.

## Actual Behavior

On all 10 Android devices all went well. However on 3 of the 15 iOS devices (various versions) we encountered a high decrease of GPS accuracy (from 4.5 to over 70 metre) when going over the bridge to the other side of the water. The GPS track showed like it was still on the first side of the water, albeit with a accuracy that could match the road on the other side.

## Steps to Reproduce

Unclear, but it seems there is some correlation with this happening when the road (in this case bridge) is non existent in Apple Maps it 'snaps' to the closest existing road and accuracy value grows.

## Context

Since we use the flutter plugin to track users driving a 'game' we need to know how they were driving. While driving, they will find checkpoints along the route. However the 3 iOS devices didn't find this checkpoint, since their GPS was still on the wrong side of the water.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
This plug-in does not reference any kind of Map code.  There is no possible way the plug-in could be magically “snapping to roads”.

**Comment by willemvanleeuwen** [comment]
![IMG-20230427-WA0003](https://user-images.githubusercontent.com/11671067/234964390-637fbc7d-0d55-4353-9f7a-41e98f6e2af8.jpg)
![IMG-20230427-WA0000](https://user-images.githubusercontent.com/11671067/234964392-249e0876-7b54-47be-bdf3-06c42f731d8e.jpg)
![IMG-20230427-WA0001](https://user-images.githubusercontent.com/11671067/234964395-c62d21c3-8aed-4e56-b428-c1966fee97a7.jpg)
![IMG-20230427-WA0002](https://user-images.githubusercontent.com/11671067/234964398-e25fd893-4884-4241-bc66-ccd8ed55f09f.jpg)

**Comment by willemvanleeuwen** [comment]
I was still uploading images while you already closed it.

I fully agree that the plugin is probably not causing this behaviour and it is something in iOS or maybe even the GPS chip. However this behaviour can impact other users of your plugin, so it's worth taking a look into it. Especially since the accuracy seems to 'feel' something is not right at that moment...

We currently use DESIRED_ACCURACY_NAVIGATION; maybe that triggers iOS to have some navigation logic like snap to road before giving the location to the flutter plugin?

**Comment by willemvanleeuwen** [comment]
> This plug-in does not reference any kind of Map code. There is no possible way the plug-in could be magically “snapping to roads”.

I was still uploading images while you already closed it.

I fully agree that the plugin is probably not causing this behaviour and it is something in iOS or maybe even the GPS chip. However this behaviour can impact other users of your plugin, so it's worth taking a look into it. Especially since the accuracy seems to 'feel' something is not right at that moment...

We currently use DESIRED_ACCURACY_NAVIGATION; maybe that triggers iOS to have some navigation logic like snap to roa

**Comment by willemvanleeuwen** [comment]
From what I understood from a native iOS developer, there is a parameter in CLLocationManager that can be set for the CLActivityType to avoid this issue;
https://developer.apple.com/documentation/corelocation/cllocationmanager

I am not sure which activity type is currently used; but we still face issues where the iOS plugin gives a different GPS locations than Android one. It seems that when it is set to **otherNavigation**; it would work for any activity

**Comment by christocracy** [comment]
I’ve never heard of anyone report this and I’ve never experienced it myself.

see api docs [Config.activityType](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/activityType.html)

**Comment by willemvanleeuwen** [comment]
Thanks; we will look into the activityType config.

To replicate the issue: find a road that is not available in Apple Maps; and drive it with the plugin.

In Europe it is the case at various locations...

**Comment by willemvanleeuwen** [comment]
Back in 2024 this issue was 'fixed' by taking ActivityType.otherNavigation in the configuration.

Now with the GeoConfig.activityType, it seems this is not working anymore as expected. Should we now take ActivityType.other instead of the ActivityType.otherNavigation?
