### ISSUE TITLE
PlatformException(Failed to start schedule. Did you configure a #schedule?, null, null, null)

### ISSUE THREAD

**Issue by sakib-shadman** [transistorsoft/flutter_background_geolocation#1029]
## Your Environment
* Plugin version: 4.6.2
* Platform:  Android
* OS version: 10,11,12,13
* Device manufacturer / model: All model
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
try {
  await BackgroundGeolocation.stop();
  await BackgroundGeolocation.stopSchedule();      
  final status = await BackgroundGeolocation.ready(
   Config(
     reset: false,
     schedule: Constants.trackingSchedule,
     scheduleUseAlarmManager: true,
     distanceFilter: Constants.locationDistanceFilter,
     isMoving: true,
     maxDaysToPersist: 7,
   ),
 );
 BackgroundGeolocation.onLocation(locationUpdateCallBack);
 if (!status.enabled) {
   await BackgroundGeolocation.start();
   await BackgroundGeolocation.startSchedule();
 }
} catch (exception) {
 Log.info(
   'EXCEPTION AT READY AT SPLASH '
   'FOR BACKGROUND TRACKING: ${exception.toString()}',
 );
 unawaited(FirebaseCrashlytics.instance.recordError(exception, null));
} 


try {
 await BackgroundGeolocation.setConfig(
   Config(
     enableHeadless: true,
     desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
     distanceFilter: 100,
     disableElasticity: true,
     stopOnTerminate: false,
     startOnBoot: true,
     isMoving: true,
     heartbeatInterval: 60,
     schedule: Constants.trackingSchedule,
     scheduleUseAlarmManager: true,
     backgroundPermissionRationale: PermissionRationale(
       message: permissionExplanationMessage,
     ),
     url: Env.value.baseUrl + ApiProvider.liveTrackingDataPostUrl,
     method: 'POST',
     autoSync: true,
     params: await getCustomParams(),
     logLevel: Config.LOG_LEVEL_VERBOSE,
     maxDaysToPersist: 7,
   ),
 );
 unawaited(BackgroundGeolocation.startSchedule());
} catch (exception) {
 Log.info(
   'EXCEPTION AT SET CONFIG AFTER LOGIN '
   'FOR BACKGROUND TRACKING: ${exception.toString()}',
 );
 unawaited(FirebaseCrashlytics.instance.recordError(exception, null));
}
```

## Expected Behavior

From our firebase crashlytics we are getting this non fatal error.
PlatformException(Failed to start schedule.  Did you configure a #schedule?, null, null, null)
This exception should not be generated through our firebase crashlytics as we are providing scheduler in our configuration. 

## Actual Behavior

From our firebase crashlytics we are getting this non fatal error.
PlatformException(Failed to start schedule.  Did you configure a #schedule?, null, null, null)

## Steps to Reproduce

We could not reproduce the issue.

## Context

In the splash screen of our app we have configured the plugin as below for the app version **1.2.0**.

Config of the plug in the app version **1.2.0** (splash screen): 

```dart
final status = await BackgroundGeolocation.ready(
  Config(
    distanceFilter: 100,
    isMoving: true,
  ),
);
BackgroundGeolocation.onLocation(locationUpdateCallBack);
if (!status.enabled) {
  await BackgroundGeolocation.start();
}

```
Config of the plug in the app version **1.2.0** (login screen): 

```dart
await BackgroundGeolocation.ready(
  Config(
    enableHeadless: true,
    desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 100,
    disableElasticity: true,
    stopOnTerminate: false,
    startOnBoot: true,
    isMoving: true,
    heartbeatInterval: 60,
    schedule: [
      '1-7 8:00-20:00', // Sun-Sat: 8:00am to 8:00pm
    ],
    scheduleUseAlarmManager: true,
    backgroundPermissionRationale: PermissionRationale(
      message: permissionExplanationMessage,
    ),
    url: Env.value.eventStreamBaseURL + ApiProvider.liveTrackingDataPostUrl,
    method: 'POST',
    autoSync: true,
    params: await getCustomParams(),
    logLevel: Config.LOG_LEVEL_VERBOSE,
  ),
).then((State state) {
  if (!state.schedulerEnabled) {
    BackgroundGeolocation.startSchedule();
  }

  if (!state.enabled) {
    ////
    // 3.  Start the plugin.
    //
    BackgroundGeolocation.start();
  }
});

```

In our app version **1.3.0** we have brought some changes to the plugin configuration to mitigate some issues of our business logic. 

Config of the plug in the app version **1.3.0** (splash screen): 

```dart
try {
 await BackgroundGeolocation.stop();
 await BackgroundGeolocation.stopSchedule();

 final status = await BackgroundGeolocation.ready(
   Config(
     reset: false,
     schedule: Constants.trackingSchedule,
     scheduleUseAlarmManager: true,
     distanceFilter: Constants.locationDistanceFilter,
     isMoving: true,
     maxDaysToPersist: 7,
   ),
 );
 BackgroundGeolocation.onLocation(locationUpdateCallBack);

 if (!status.enabled) {
   await BackgroundGeolocation.start();
   await BackgroundGeolocation.startSchedule();
 }
} catch (exception) {
 Log.info(
   'EXCEPTION AT READY AT SPLASH '
   'FOR BACKGROUND TRACKING: ${exception.toString()}',
 );
 unawaited(FirebaseCrashlytics.instance.recordError(exception, null));
}
```

Config of the plug in the app version **1.3.0** (login screen): 

```dart
try {
 await BackgroundGeolocation.setConfig(
   Config(
     enableHeadless: true,
     desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
     distanceFilter: 100,
     disableElasticity: true,
     stopOnTerminate: false,
     startOnBoot: true,
     isMoving: true,
     heartbeatInterval: 60,
     schedule: Constants.trackingSchedule,
     scheduleUseAlarmManager: true,
     backgroundPermissionRationale: PermissionRationale(
       message: permissionExplanationMessage,
     ),
     url: Env.value.baseUrl + ApiProvider.liveTrackingDataPostUrl,
     method: 'POST',
     autoSync: true,
     params: await getCustomParams(),
     logLevel: Config.LOG_LEVEL_VERBOSE,
     maxDaysToPersist: 7,
   ),
 );
 unawaited(BackgroundGeolocation.startSchedule());
} catch (exception) {
 Log.info(
   'EXCEPTION AT SET CONFIG AFTER LOGIN '
   'FOR BACKGROUND TRACKING: ${exception.toString()}',
 );
 unawaited(FirebaseCrashlytics.instance.recordError(exception, null));
}

```

In our app, after the splash screen and some flow user gets into the login screen. When a user updates the app from version **1.2.0**  to  **1.3.0**  through the google play store we have started getting the issue mentioned above through our firebase crashlytics.

After that we published another version that is **1.3.1** to the google playstore, this version has the same configuration of the plugin as in the app version **1.3.0** , but we are getting the same exception from the plugin after updating to app version **1.3.1**. 

Since we can not reproduce or generate this exception in our local environment, we are looking for assistance to find out the problem.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
> reset: false,

Do you know what this does?

> PlatformException(Failed to start schedule. Did you configure a #schedule?, null, null, null)

This is an uncaught exception raised by calling `.startSchedule()` **when you’ve not configured the plug-in with a schedule**.

why not catch exceptions from .startSchedule()?

**Comment by sakib-shadman** [comment]
@christocracy , We have caught exceptions on top of our implementation to catch any kind of exception instead of .startSchedule()
Is there any observation regarding the usage of `reset : false` parameter?

**Comment by christocracy** [comment]
If you know what you're doing with `reset: false`, it's ok to use it.

**Comment by christocracy** [comment]
Create a simple *hello_world* app which reproduces your problem.  Share it with me in a public GitHub repo.

**Comment by sakib-shadman** [comment]
> 

okay, we are working on it.

**Comment by sakib-shadman** [comment]
the simple app :
https://github.com/sakib-shadman/bg-tracking-sample-app

**Comment by christocracy** [comment]
And what are the steps to reproduce your problem with this app?

**Comment by sakib-shadman** [comment]
Unfortunately, we could not be able to reproduce the exception with this sample app too.  It will be really helpful if you can review the code and share some insights regarding the exception. According to Firebase crashlytics data, all of our users have faced this exception at least once.

**Comment by christocracy** [comment]
Your application code is calling .startSchedule() when the plug-in doesn’t have a schedule.

Your uncaught exception is not fatal.

**Comment by sakib-shadman** [comment]
We are clear about the meaning of the exception and that it is non-fatal. But we are not concerned about that. We have provided the **scheduler** in our configuration which you can see from the configuration we have provided. Our concern is about why the plugin generates the exception even after getting the scheduler.  Is it any expected behavior or we are setting the configuration in the wrong way?   What should be the expected solution in our scenario?

**Comment by christocracy** [comment]
You have problems in your own code.  Likely related to a Future which hasn’t yet resolved.

let me know exactly how to reproduce the problem.

**Comment by sakib-shadman** [comment]
@christocracy  we have found another exception recently and that is:

```dart
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Waiting for previous start action to complete, null, null, null). Error thrown null.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:117)
       at LiveTrackingHelper.setLocationConfig(live_tracking_helper.dart:98)`
 
 ```
    
We have found the entry point of this exception and that is : 
```dart
 if (!status.enabled) {
   await BackgroundGeolocation.start();
   await BackgroundGeolocation.startSchedule();
 }
 ```     
 
 But this issue is not reproduced at our regular builds (debug and release). So we have done the following changes in our code to reproduce this issue. 
 
```dart
 if (!status.enabled) {
        await BackgroundGeolocation.start();
        await BackgroundGeolocation.start();
        await BackgroundGeolocation.start();
        await BackgroundGeolocation.startSchedule();
      }
```

So we have seen that 
```dart
 await 
``` 
is not working as expected.  Is it anyhow related to **Future Not Resolved**? If this is the case then can we rely on **await**?
Please share your resolutions.

**Comment by christocracy** [comment]
You’re not **supposed to** call both .start() AND .startSchedule()!  Why would you even do that?

**Comment by sakib-shadman** [comment]
We have called both start() AND .startSchedule() in case the scheduler faces any exception and fails to start tracking. 

But why does this exception generate so randomly? Should not it happen always as we have used both and according to you, we should not use both at the same time? 

Also, our finding is the **await** is not working in this case.  So is there any possibility that **await** is not also working for the exception that we have mentioned in the issue from the beginning? 

And one more question, we have used stop() and stopSchedule(), does any one of these remove the configured schedule?

**Comment by christocracy** [comment]
The returned `State` instance contains many other attributes in addition `state.enabled`, including `State.schedule`

If you find that `State.schedule` is an empty `[ ]`, then calling `.startSchedule()` is going to raise an Exception.

It makes **absolutely no sense** to call `.start()` in addition to `.startSchedule()`.

The *Scheduler* is a robot that **automatically** calls `.start()` for you.
