### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException 

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#103]
## Your Environment
* Plugin version: 1.0.9
* Platform:  Android
* OS version: 9
* Device manufacturer / model: Samsung galaxy S8
* Flutter info (`flutter doctor`):[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024, locale en-IN)
    • Flutter version 1.7.8+hotfix.3 at /Users/adarshagnihotri/Documents/flutter
    • Framework revision b712a172f9 (3 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/adarshagnihotri/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/adarshagnihotri/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.1

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
    bg.BackgroundGeolocation.start();
bg.BackgroundGeolocation.onLocation(_onLocation);
 bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.ready(bg.Config(
       // debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: 30,
        locationUpdateInterval: 1800000,
        preventSuspend: true,
        stopOnTerminate: false,
        stopOnStationary: true,
        useSignificantChangesOnly: true,
        disableMotionActivityUpdates: true,
        startOnBoot: true,
        enableHeadless: true,
        heartbeatInterval: 1800
    )).then((bg.State state) {
      print('[ready] ${state.toMap()}');
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

## Expected Behavior

Crash should not occur.
## Actual Behavior
On firebase console this Crash has been reported---->>
"Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{xyz/com.transistorsoft.locationmanager.service.LocationRequestService}
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1872)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7045)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)"
AsyncTask #

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The first thing you ask is "am I using the [latest version](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md)?"

## [1.0.10] - 2019-06-25
[Changed] Tweaks to Android services code to help guard against error Context.startForegroundService() did not then call Service.startForeground().

**Comment by joserocha3** [comment]
@christocracy, I can confirm this still happens with version `1.0.12`. Although the message is a little different for me, mentions geofencing service.

```
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5ff0ed9 u0 com.dotdotdata.pointbee/com.transistorsoft.locationmanager.service.GeofencingService}
```

**Comment by christocracy** [comment]
Many other Android devs [are experiencing this] (https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground) periodically on some devices.

This won't affect the ability of the plugin to continue tracking.

**Comment by ADARSHAGNIHOTRI** [comment]
Ok, then tell me if the following crash in iOS are due to the same reason?
![Screen Shot 2019-07-29 at 6 02 30 PM](https://user-images.githubusercontent.com/51204005/62048949-bfa35100-b22b-11e9-92d8-0aa000fc8c3d.png)


and explaination is below
![Screen Shot 2019-07-29 at 6 02 30 PM](https://user-images.githubusercontent.com/51204005/62049021-f6796700-b22b-11e9-955d-14e83df626fd.png)

**Comment by ADARSHAGNIHOTRI** [comment]
then please tell me that the following iOS crash is due to the same reason----->>>>
![Uploading Screen Shot 2019-07-29 at 6.04.29 PM.png…]()
below is explaination ----->>>>

![Screen Shot 2019-07-29 at 6 02 30 PM](https://user-images.githubusercontent.com/51204005/62049299-87504280-b22c-11e9-8da4-6f9dade6a4bd.png)

**Comment by christocracy** [comment]
That's an iOS issue related to OpenGL rendering.  That has nothing to do with this Android issue.

**Comment by ADARSHAGNIHOTRI** [comment]
Doesn't have any plugin issue with 

> That's an iOS issue related to OpenGL rendering. That has nothing to do with this Android issue.
Not your Plugin issue?

**Comment by christocracy** [comment]
Your OpenGL issue has nothing to do with background Geolocation.

**Comment by ADARSHAGNIHOTRI** [comment]
I have found a link which is similar to the crash reported on Crashelytics.Please check the link below.
https://github.com/flutter/flutter/issues/22933
Could this be a problem of flutter framework ?

**Comment by christocracy** [comment]
This issue is related to Android.

If you have an iOS issue, post a new issue.

**Comment by ADARSHAGNIHOTRI** [comment]
@christocracy sir ,
I am getting the same crash at Firebase crashlystic  even after increasing the plugin version.
Can you please suggest me what to do now?

**Comment by DanielNovak** [comment]
If it's of any help - we are seeing the same starForeground issue in an Android project (completely unrelated to this github repo) and it's happening only on Samsung model SM-G955U, SM-G950U and SM-N950U, all on Android 9.0. This is S8 and S8+ and Note 8. We tried a lot of things but I think this is a device specific issue.

**Comment by livotov** [comment]
@christocracy strangely we still see this issue with v1.7:

As per crashlytics, this happens 100% on Samsung devices with 100% Android 9.

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4afba3 u0 io.papu.papuio/com.transistorsoft.locationmanager.service.TrackingService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by christocracy** [comment]
@livotov enable [`StrictMode`](https://developer.android.com/reference/android/os/StrictMode) in your Android `Application.java` (or `.kotlin` if applicable).

`StrictMode` will provide valuable insight into which plugins/code are blocking the main-thread while your app boots, inducing the error `Context.startForegroundService() did not then call Service.startForeground()`

In the `/example` app, copy the commented-out block [here](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/src/main/java/com/transistorsoft/flutterbackgroundgeolocationexample/Application.java#L12-L24)

**Comment by livotov** [comment]
@christocracy the problem is we can't reproduce this on our devices. The report above comes from several play store users. We'll try to arrange this mode for problematic devices and I'll let you know the results.  Thanks for the support!

**Comment by christocracy** [comment]
You should see *some* `StrictMode` violations, regardless of device.  Some particular device *may* be more susceptible to those violations than others.

Think of it like a line-up of people all trying to get into a popular pub.  The line-up is the synchronous UI Thread Queue.  Each person in the line must have their ID checked.  Somewhere in that line-up is the plugin's foreground-service.  If the employees at the door checking ID are slower than some other pub (ie: some particular device model), Android will induce this error if the plugin's foreground-service doesn't get through the door in a finite amount of time.

![](https://dl.dropbox.com/s/ir5kxrg857ef7lj/Screenshot%202020-03-30%2010.24.52.png?dl=1)

**Comment by marcoheine** [comment]
> @christocracy strangely we still see this issue with v1.7:
> 
> As per crashlytics, this happens 100% on Samsung devices with 100% Android 9.
> 
> Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4afba3 u0 io.papu.papuio/com.transistorsoft.locationmanager.service.TrackingService}
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:214)
> at android.app.ActivityThread.main(ActivityThread.java:7094)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

@livotov 
I have the same problem. Did you find a solution?

**Comment by livotov** [comment]
@marcoheine yep, we still have this issue on a set of Samsung devices. There is definitely no ANR or any heavy task as @christocracy supposed earlier (we checked against that) so the reason is still unknown. Maybe this is even kind of Samsung model+OS build specific issue.

**Comment by christocracy** [comment]
I see no ANR in past 60 days for the *example* app published to Play Store.

![](https://dl.dropbox.com/s/l3if3lrqd2eogxr/Screen%20Shot%202021-02-08%20at%2010.01.15%20AM.png?dl=1)
