### ISSUE TITLE
Google Maps marker does not follow street location accurately

### ISSUE THREAD

**Issue by guiolifer** [transistorsoft/flutter_background_geolocation#1031]
## Your Environment
* Plugin version: 4.8.1
* Platform: Android
* OS version:
* Device manufacturer / model: SM-G780M
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        persistMode: bg.Config.PERSIST_MODE_ALL,
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_OFF,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        foregroundService: true,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Permita que {applicationName} acesse a localização deste dispositivo mesmo quando o aplicativo estiver fechado ou não estiver em uso.",
            message: "Este aplicativo coleta dados de localização para permitir o registro de suas viagens ao trabalho e calcular a distância percorrida.",
            positiveAction: 'Mudar para "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancelar'),
        autoSync: true,
        url: "${AppUrl.TRACKER_HOST}/api/locations",
        heartbeatInterval: 60,
        authorization: bg.Authorization(
            strategy: bg.Authorization.STRATEGY_JWT,

            refreshPayload: {'refresh_token': '{refreshToken}'}),
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        )
```

## Expected Behavior
Google Maps marker stay on street while moving

## Actual Behavior
When adding the marker on the map of Google Maps with each update, the marker varies the direction too much

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm trying to update Google Maps Marker by location update, but I don't know the ideal setting.

I need to show on the map the updated location walking along the street as well as Google Maps Route, Waze etc..

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Here's my last week of field-testing.  It doesn't get any better than this (**NOTE**:  Not all the devices below with me during the entire period).

- *Pixel 6 @ 13*

<img width="1166" alt="Screenshot 2023-05-04 at 12 30 25 PM" src="https://user-images.githubusercontent.com/14999/236267360-87e2f1aa-89f0-49b4-9bfb-51aed4939324.png">

- *Samsung Galaxy S20 @ 13* 

<img width="1167" alt="Screenshot 2023-05-04 at 12 32 11 PM" src="https://user-images.githubusercontent.com/14999/236267718-6f80c6b1-df80-4d29-b90c-c79af2f9d79a.png">

- * - OnePlus A5010 @ 9.0.0*

<img width="1168" alt="Screenshot 2023-05-04 at 12 33 54 PM" src="https://user-images.githubusercontent.com/14999/236268078-8075aa83-5fdb-4718-95fd-134a96fc06e7.png">

- *iPhone 13 Pro @ 16.5*

<img width="1166" alt="Screenshot 2023-05-04 at 12 35 46 PM" src="https://user-images.githubusercontent.com/14999/236268689-9ac96263-5ae6-414d-8d45-4f672829badf.png">

**Comment by christocracy** [comment]
Those were all recorded using the `/example` app in this repo.

**Comment by christocracy** [comment]
No, [as I said above](https://github.com/transistorsoft/flutter_background_geolocation/issues/1031#issuecomment-1535022770)

<img width="925" alt="Screenshot 2023-05-04 at 12 45 05 PM" src="https://user-images.githubusercontent.com/14999/236270877-090fb79f-f065-440f-b40f-3930ee74e220.png">
