### ISSUE TITLE
  On Motion change and Activity Change do not works well when device is moving with vehicle or still or walking.

### ISSUE THREAD

**Issue by moh-moh-pan-phyu-mhwe** [transistorsoft/flutter_background_geolocation#1038]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):
* Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (2 months ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->


  _backgroundGeo() async {
    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    // bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            disableElasticity: true,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            startOnBoot: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            notificationTitle: "Connect GRX",
            notificationText: "Movement",
            locationAuthorizationRequest: 'Always',
            reset: true,
            stopTimeout: 0))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
  }

 void _onMotionChange(bg.Location location) {
    print('[HHH motionchange] - $location');
    setState(() {
      _activity = "${location.activity.type} in mc";
      if (location.isMoving) {
        _ismoving = 'true in mc';
      } else {
        _ismoving = 'false in mc';
      }
    });
  }

  void _onActivityChange(bg.ActivityChangeEvent event) async {
    setState(() {
      _activity = "${event.activity} in ac";
    });
  }


```

## Expected Behavior
When I drive the car, activity type should be 'in_vehicle' and location.ismoving should be true.
When I stop drive the car and stands about 3 mins or 5 mins, activity type should change to 'still' and location.ismoving should be 'false'

## Actual Behavior

When I drive the car about 10 mins, plugin sometimes shows 'in_vehicle' but sometimes still.
When I driving the car about 10 mins, location.ismoving is only show 'false' but sometime correct.
Not stable.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by moh-moh-pan-phyu-mhwe** [comment]
Is it depend on internet access for the onMotionChange event and onActivityChange event ?

**Comment by christocracy** [comment]
See https://dontkillmyapp.com
