### ISSUE TITLE
Fatal Exception:  message_loop_darwin.mm 

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#104]
## Your Environment
* Plugin version: 1.0.9
* Platform: iOS 
* OS version: 12.3.1
* Device manufacturer / model: iPhone 6
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->ASTE_YOUR_CODE_HERE
bg.BackgroundGeolocation.start();
bg.BackgroundGeolocation.onLocation(_onLocation);
bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
bg.BackgroundGeolocation.ready(bg.Config(
// debug: true,
logLevel: bg.Config.LOG_LEVEL_VERBOSE,
desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
distanceFilter: 30,
locationUpdateInterval: 1800000,
preventSuspend: true,
stopOnTerminate: false,
stopOnStationary: true,
useSignificantChangesOnly: true,
disableMotionActivityUpdates: true,
startOnBoot: true,
enableHeadless: true,
heartbeatInterval: 1800
)).then((bg.State state) {
print('[ready] ${state.toMap()}');
setState(() {
_enabled = state.enabled;
_isMoving = state.isMoving;
});
}).catchError((error) {
print('[ready] ERROR: $error');
});

```

## Expected Behavior
Should not occur any error.
## Actual Behavior

![Uploading Screen Shot 2019-07-30 at 5.22.13 PM.png…]()

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You provide no logs or context.  Closing until more info provided.  I highly doubt this has anything to do with the plugin.

**Comment by ADARSHAGNIHOTRI** [comment]
![Screen Shot 2019-07-30 at 8 24 51 PM](https://user-images.githubusercontent.com/51204005/62140206-301fa000-b308-11e9-9490-c8347594364f.png)

**Comment by christocracy** [comment]
This a crash from the Flutter SDK, not the plugin.

**Comment by ADARSHAGNIHOTRI** [comment]
It will be your highness if you can help me to solve this problem.
Any link or suggestion?

**Comment by christocracy** [comment]
Compare your code with that in the sample in the README.
