### ISSUE TITLE
 <app name> would like to access your motion&fitness activity- are there a possibility to customise the permission dialog

### ISSUE THREAD

**Issue by Dev-Paccore** [transistorsoft/flutter_background_geolocation#1040]

**Comment by christocracy** [comment]
That dialog is produced by the operating system itself.  It should automatically be localized based upon the user’s language.

**Comment by AehMGS** [comment]
From Google's developer docs: 
"The permissions dialog shown by the system when you call [requestPermissions()](https://developer.android.com/reference/androidx/core/app/ActivityCompat#requestPermissions(android.app.Activity,%20java.lang.String[],%20int)) says what permission your app wants, but doesn't say why. In some cases, the user might find that puzzling. It's a good idea to explain to the user why your app wants the permissions before you call requestPermissions()."

So we need to show an in app dialog to prepare the user for the request. Is it possible to do that ?
And is it possible to deactivate the Motion Tracking all together ?

**Comment by christocracy** [comment]
>So we need to show an in app dialog to prepare the user for the request

Many popular apps do this.  I’m sure you’ve seen it before.

>is it possible to deactivate the Motion Tracking all together ?

See api docs Config.disableMotionActivityUpdates.

**Comment by neiljaywarner** [comment]
Does anyone happen to know? If you disable it, do you still have to classified it as a health app in the Apple store? Probably not right...

Or do you not have to anyway or how does it work?

I realize it's one of the main advantages to use the motion detection, but it's confusing about the classification in the Apple store, or at least it seems like it is so far
