### ISSUE TITLE
Tracking on ferry gives inaccurate and infrequent locations

### ISSUE THREAD

**Issue by suhairhassan** [transistorsoft/flutter_background_geolocation#1042]
## Your Environment
* Plugin version: 4.10.3
* Platform: iOS 
* OS version:  16.5
* Device manufacturer / model: iPhone 13 Pro
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
final state = await bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                'Allow Tripturnal to access background location, even when not in use, for a better experience.',
            message:
                'To provide accurate information on trip routes and weather, we kindly request permission to collect location data in our app. Rest assured, your privacy is important to us and this data will only be used for these specific purposes.',
            positiveAction: 'Allow access all time',
            negativeAction: 'cancel'),
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));
    if (!state.enabled) {
      await bg.BackgroundGeolocation.start();
    }
```

## Expected Behavior
Should track the exact locations when the ferry is moving. 

## Actual Behavior
Gives inaccurate locations and tracks occasionally only

## Steps to Reproduce
This happens in smooth moving like in ferry, train, etc. Works perfectly in car.

## Context
Track the locations when moving from one island to main land using Ferry

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_

HERE
```

</details>

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/11485554/background-geolocation.log)

![IMG_3785 (1)](https://github.com/transistorsoft/flutter_background_geolocation/assets/55729104/8daf4c02-c1f1-45be-8255-87954c4fdbde)

**Comment by suhairhassan** [comment]
The locations are received in Google map and in bg plugin when the app is in foreground and location events are listened or force started the bg plugin several times. The problem is bg plugin is started for sometimes and then it stops. Is there some methods through which we can force bg plugin to track the locations no matter the plugin has detected motion or not. For example, track my locations for the next 2 hours no matter what happens. The same issue is happening in train travel also.

**Comment by christocracy** [comment]
See #1043

**Comment by christocracy** [comment]
What range of timestamp are you interested in from logs?

**Comment by suhairhassan** [comment]
Unfortunately we dont have the data for the exact time stamps. It was overwritten in the client logs. Is there a method to force the tracking of bg plugin despite the motion change for a fixed duration, say 2 hours?

**Comment by christocracy** [comment]
>Is there a method to force the tracking of bg plugin despite the motion change for a fixed duration, say 2 hours?

See API docs `Config.stopTimeout`.
