### ISSUE TITLE
The tracking under train is not acurate

### ISSUE THREAD

**Issue by nithinjith-42** [transistorsoft/flutter_background_geolocation#1043]
## Your Environment
* Plugin version: 3.4.0 (420)
* Platform:Android
* OS version: samsung SM-M215G @ 12 (flutter)
* Device manufacturer / model: Samsung SM-M215G
* Flutter info (`flutter doctor`):Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-IN)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
The app should track the exact railway line. 

## Actual Behavior

If we track with the app on the train (minimum speed of 50 km/Hr to a maximum speed of 120 km/Hr), the app is not showing correct tracking results. Please check the attached screenshot. The **Red** line is the actual railway path and the **Green** line is the current tracked path. 

## Steps to Reproduce

It happened in all train travel

## Context
Track the location of the train 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/11486012/background-geolocation.log)

![MicrosoftTeams-image](https://github.com/transistorsoft/flutter_background_geolocation/assets/119937687/7ad9eca3-b4b6-46f7-9b6a-b92e3bea4886)

**Comment by christocracy** [comment]
Train cars can act as a “faraday cage”, blocking weak satellite signals.

the plug-in doesn’t manufacture location data, the OS provides the best available location data to the plug-in, which forwards that along exactly as provided.

You are not guaranteed 100% accurate data.  The environment *can* affect the quality of data.
