### ISSUE TITLE
What means that? Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global

### ISSUE THREAD

**Issue by Rushterscom** [transistorsoft/flutter_background_geolocation#1051]
## Your Environment
* Plugin version: 4.11.0
* Platform: andriod
* OS version: 
* Device manufacturer / model: Huawei P30
* Flutter info (`flutter doctor`): [✓] Flutter (Channel stable, 3.3.10, on macOS 13.3.1 22E772610a darwin-arm, locale es-CL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.48.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
        bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
            reset: true,
            debug: false,
            stopOnTerminate: true,
            startOnBoot: false,
            enableHeadless: false,
            motionTriggerDelay: 30000,
            isMoving: FirebaseRemoteConfigService().getinitIsMoving(),
            triggerActivities: 'in_vehicle', // 'on_foot, walking, running, in_vehicle'
            logLevel: bg.Config.LOG_LEVEL_OFF,
            desiredAccuracy: Platform.isIOS
                ? bg.Config.DESIRED_ACCURACY_NAVIGATION
                : bg.Config.DESIRED_ACCURACY_HIGH,
            desiredOdometerAccuracy: 10,
            activityType: Config.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
            locationUpdateInterval: FirebaseRemoteConfigService()
                .getLocationUpdateInterval(),
            distanceFilter: FirebaseRemoteConfigService().isTimeBased()
                ? 0
                : FirebaseRemoteConfigService().getDistanceFilter(),
            locationAuthorizationRequest: "Always",
            persistMode: bg.Config.PERSIST_MODE_NONE,
            maxDaysToPersist: 2,
            locationTimeout: 15,
            stopTimeout: FirebaseRemoteConfigService().getStopTimeout(),
            heartbeatInterval: FirebaseRemoteConfigService().getHeartbeatInterval(),
            stopAfterElapsedMinutes:  FirebaseRemoteConfigService().getStopAfterElapsedMinutes(),
            notification: bg.Notification(
              title: FirebaseRemoteConfigService().getTitleCompartirUbicacionActiva(),
              text: FirebaseRemoteConfigService().getTextCompartirUbicacionActiva(),
            ),
            locationAuthorizationAlert: jsonLocationAuth,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Permita que {applicationName} acceda a la ubicación de este dispositivo incluso cuando la aplicación este en segundo plano",
                message:
                    "Esta aplicación recopila datos de ubicación para poder registrar sus viajes y calcular la distancia recorrida.",
                positiveAction: 'Cambiar a "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancelar')));
```

## Expected Behavior
i just want to know why console show this message when i start backgroundlocation

## Actual Behavior
console show:
W/Settings(10650): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It means nothing.  You do not need to worry about this.

**Comment by Rushterscom** [comment]
chris i am having a intermit  issue, sometimes API dont throw motion change trigger, to change from stacionary to in moving, this happens not all the time, sometimes works fine, but others i need to change changepace true manually, i detect when this happens, i see this logs in console.
`W/Settings(11290): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/flutter (11290): [location] - odo: 0.0, mov false , speed 0.2
I/flutter (11290): _onProviderChange [ProviderChangeEvent enabled:false, status: 3, network: false, gps: false, accuracyAuthorization: 0]`

providerChange says that a i am not connected, but i do, connected to wifi.

**Comment by christocracy** [comment]
enabled: false means you’ve disabled “Location” globally in settings, **for every app on the device**.

the logs you post “ Setting airplane_mode_on has moved” have nothing at all to do with your problem.

**Comment by Rushterscom** [comment]
is weird becouse i don't disabled location never in mi settins device, is always enable, also my internet always connected i dont know why providerchange throw this log, and when happens API dont throw the change to in moving

**Comment by christocracy** [comment]
See https://dontkillmyapp.com 

also try on a different device.

**Comment by Rushterscom** [comment]
thx @christocracy , I've been fighting with this for days, my device is HUAWEI P30, third on the list of most restrictive devices, as an anti-communist friend said, never trust the Chinese lol, btw I'll try other devices, do you recommend any Android? I could have same problem for IOS, that kill my app ?, today i make a real test driving my car , and look the behavior, the lines red with no point is the app in background with the screen off, and the red point is the app in foreground, is this the same that you mention above ?.

<img width="493" alt="Captura de pantalla 2023-05-23 a la(s) 08 53 35" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/132719719/cf7c87cd-a93a-4a49-9f42-d8c321a60826">

**Comment by Rushterscom** [comment]
the solution purposed https://dontkillmyapp.com/ for huawei works fine, i have follow the steps Phone settings > Battery > App launch and then set your app to “Manage manually” , and already receive all the events of location even if the app is in background with the screen off, i had the same behavior with lockito, when the screen is off , lockito stop moving until unlock the screen, but now works fine with that configuration (my app and lockito), i am going to change my device for some google devices.
thx for your support chris you are amazing answering to fast.

![WhatsApp Image 2023-05-23 at 09 43 33](https://github.com/transistorsoft/flutter_background_geolocation/assets/132719719/65883ef3-5c6a-4efa-aca4-ba6929342bb1)
