### ISSUE TITLE
No Location on Google Pixel 3 Android 13 CalyxOS

### ISSUE THREAD

**Issue by xunreal75** [transistorsoft/flutter_background_geolocation#1052]
## Your Environment
* Plugin version: 4.11.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google Pixel 3a
* Flutter info (flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale de-DE)
    • Flutter version 3.7.12 on channel stable at /Users/larshuth/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (vor 5 Wochen), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/larshuth/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/larshuth/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/larshuth/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/larshuth/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/larshuth/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 113.0.5672.126

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
╟─ Google Pixel 3a @ 13 (flutter)
{
"activityRecognitionInterval": 10000,
"allowIdenticalLocations": true,
"authorization": {},
"autoSync": true,
"autoSyncThreshold": 0,
"backgroundPermissionRationale": {
"title": "Location always permissions",
"message": "Location 'When in use' is selected. Warning, there is no background update enabled. Your position datas to show exact Bladnight train and share your position with your friends is only possible when the app is open in foreground. Please confirm it or change your settings to 'Allow all time'.\nFurthermore, access to the motion activity detection (physical activity) is desirable. This increases battery efficiency by intelligently turning off location tracking when your device is detected as stationary. Therefore please activate this function.",
"positiveAction": "Open operating system settings",
"negativeAction": "Cancel"
},
"batchSync": false,
"configUrl": "",
"debug": false,
"deferTime": 0,
"desiredAccuracy": -2,
"desiredOdometerAccuracy": 100,
"disableAutoSyncOnCellular": false,
"disableElasticity": false,
"disableLocationAuthorizationAlert": true,
"disableMotionActivityUpdates": false,
"disableProviderChangeRecord": false,
"disableStopDetection": false,
"distanceFilter": 0.10000000149011612,
"elasticityMultiplier": 1,
"enableHeadless": false,
"enableTimestampMeta": false,
"extras": {},
"fastestLocationUpdateInterval": -1,
"foregroundService": true,
"geofenceInitialTriggerEntry": true,
"geofenceModeHighAccuracy": false,
"geofenceProximityRadius": 1000,
"geofenceTemplate": "",
"headers": {},
"headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
"heartbeatInterval": 60,
"httpRootProperty": "location",
"httpTimeout": 60000,
"isMoving": false,
"locationAuthorizationRequest": "Always",
"locationTemplate": "",
"locationTimeout": 60,
"locationUpdateInterval": 2500,
"locationsOrderDirection": "ASC",
"logLevel": 5,
"logMaxDays": 1,
"maxBatchSize": -1,
"maxDaysToPersist": 1,
"maxRecordsToPersist": -1,
"method": "POST",
"minimumActivityRecognitionConfidence": 75,
"motionTriggerDelay": 0,
"notification": {
"layout": "",
"title": "",
"text": "Location Service activated",
"color": "",
"channelName": "TSLocationManager",
"channelId": "",
"smallIcon": "",
"largeIcon": "",
"priority": 0,
"sticky": false,
"strings": {},
"actions": []
},
"params": {},
"persist": true,
"persistMode": 2,
"schedule": [],
"scheduleUseAlarmManager": false,
"speedJumpFilter": 300,
"startOnBoot": false,
"stationaryRadius": 25,
"stopAfterElapsedMinutes": 3600,
"stopOnStationary": false,
"stopOnTerminate": true,
"stopTimeout": 5,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"url": "",
"useSignificantChangesOnly": false,
"enabled": true,
"schedulerEnabled": false,
"trackingMode": 1,
"odometer": 0,
"isFirstBoot": false,
"didLaunchInBackground": false,
"didDeviceReboot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅ ACCELEROMETER: {Sensor name="BMI160 Accelerometer", vendor="BOSCH", version=1, type=1, maxRange=156.99008, resolution=0.004790957, power=0.18, minDelay=5000}
╟─ ✅ GYROSCOPE: {Sensor name="BMI160 Gyroscope", vendor="BOSCH", version=1, type=4, maxRange=34.906555, resolution=0.0010652635, power=0.9, minDelay=5000}
╟─ ✅ MAGNETOMETER: {Sensor name="AK0991X Magnetometer", vendor="akm", version=20012, type=2, maxRange=4912.0503, resolution=0.15, power=0.9, minDelay=10000}
╟─ ✅ SIGNIFICANT_MOTION: {Sensor name="Significant Motion", vendor="Google", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.25, minDelay=-1}
╚════════════════════════════════════════════
```

## Expected Behavior
On new location a location should received in App . It's neither working in foreground  and background

## Actual Behavior
collect Geolocation Datas from device

## Steps to Reproduce

1. Install or use Google Pixel 3a with TiramisuSandbox
2. Start App
3. grant permissions
4. change location
5. wait and watch the log ...

``` W/TSLocationManager( 6978): [c.t.l.service.AbstractService startForegroundService] 
W/TSLocationManager( 6978):   ℹ️  Background FGS launch denied:  Retrying with AlarmManager...Intent { act=start cmp=de.bladenight.bladenight_app_flutter/com.transistorsoft.locationmanager.service.LocationRequestService (has extras) }
I/TSLocationManager( 6978): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager( 6978):   ⏰ Scheduled OneShot: LAUNCH_FOREGROUND_SERVICE in 0ms (jobID: -1823535195)
I/TSLocationManager( 6978): [c.t.l.scheduler.ScheduleEvent onOneShot] 
I/TSLocationManager( 6978): ╔═════════════════════════════════════════════
I/TSLocationManager( 6978): ║ ⏰ OneShot event fired: LAUNCH_FOREGROUND_SERVICE
I/TSLocationManager( 6978): ╠═════════════════════════════════════════════
I/TSLocationManager( 6978): [c.t.l.l.SingleLocationRequest startUpdatingLocation] 
I/TSLocationManager( 6978):   🔵  [SingleLocationRequest start, action: 2, requestId: 34]
W/TSLocationManager( 6978): [c.t.l.l.SingleLocationRequest finish] 
W/TSLocationManager( 6978):   ⚠️  timeout: 34
W/TSLocationManager( 6978): [c.t.l.l.TSLocationManager onLocationTimeout] 
W/TSLocationManager( 6978):   ⚠️  TSLocationManager received location timeout
W/TSLocationManager( 6978): [c.t.l.a.BackgroundGeolocation _onLocationError] 
W/TSLocationManager( 6978):   ⚠️  Location error: 408
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
05-22 20:10:45.710 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
05-22 20:10:50.586 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
05-22 20:10:50.594 INFO [c g] 
  🔵  LocationAuthorization: Requesting Background permission
05-22 20:10:50.599 INFO [c e] 
  🔵  Should show backgroundPermissionRationale? false
05-22 20:10:50.627 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.inactive
05-22 20:10:50.885 INFO [HeartbeatService start] 
  🎾  Start heartbeat (60s)
05-22 20:10:50.888 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:10:50.888 INFO [TrackingService changePace] 
  🔵  setPace: false → false
05-22 20:10:50.899 INFO [c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
05-22 20:10:50.906 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
05-22 20:10:50.909 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.resumed
05-22 20:10:50.921 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 1, requestId: 1]
05-22 20:10:50.928 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
05-22 20:10:50.937 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-22 20:10:50.945 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@c11062d
05-22 20:10:50.947 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:10:50.948 INFO [c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
05-22 20:10:50.957 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 2]
05-22 20:10:51.969 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 2
05-22 20:10:51.970 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:10:51.971 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:11:00.949 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

05-22 20:11:21.225 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@5837c37
05-22 20:11:21.229 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:11:21.231 INFO [c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
05-22 20:11:21.255 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 3]
05-22 20:11:22.263 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 3
05-22 20:11:22.263 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:11:22.264 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:11:43.646 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.inactive
05-22 20:11:43.680 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
05-22 20:11:44.145 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.paused
05-22 20:11:53.699 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

05-22 20:12:35.941 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@8a08b59
05-22 20:12:35.991 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@458415
05-22 20:12:35.993 WARN [SingleLocationRequest start] 
╔═════════════════════════════════════════════
║ ⚠️  Background location-updates forbidden (WhenInUse)
╠═════════════════════════════════════════════
╟─ Cannot initiate location requests in the background/headless with WhenInUse authorization.
╟─ Location updates must have previously been initiated with your app in the foreground.  Eg: .changePace(true).
╚═════════════════════════════════════════════
05-22 20:12:35.995 INFO [c g] 
  🔵  LocationAuthorization: Requesting Background permission
05-22 20:12:35.998 INFO [c e] 
  🔵  Should show backgroundPermissionRationale? false
05-22 20:12:53.931 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.resumed
05-22 20:12:53.934 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@2837c01
05-22 20:12:53.937 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:12:53.938 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@f048ce7
05-22 20:12:53.941 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:12:59.156 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.inactive
05-22 20:12:59.306 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 5]
05-22 20:12:59.309 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 6]
05-22 20:12:59.312 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.resumed
05-22 20:12:59.321 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@1bf52a8
05-22 20:12:59.323 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:12:59.325 INFO [c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
05-22 20:12:59.331 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
05-22 20:12:59.349 ERROR [TSLocationManager getLastLocation] 
  ‼️  Failed to get last location: com.transistorsoft.xms.g.tasks.Task$XImpl@386559f
05-22 20:12:59.349 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 7]
05-22 20:12:59.351 INFO [c h] 
  🔵  LocationAuthorization: Requesting permission
05-22 20:12:59.352 INFO [c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
05-22 20:12:59.360 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 8]
05-22 20:13:00.311 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 5
05-22 20:13:00.312 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:13:00.312 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:13:00.317 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 6
05-22 20:13:00.317 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:13:00.317 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:13:00.356 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 7
05-22 20:13:00.357 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:13:00.357 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:13:00.363 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 8
05-22 20:13:00.363 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
05-22 20:13:00.364 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
05-22 20:13:01.448 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.inactive
05-22 20:13:02.174 INFO [TSScheduleManager oneShot] 
  ⏰ Oneshot TERMINATE_EVENT is already pending
05-22 20:13:02.344 INFO [TSLog log] 
  🔵  event_info - didChangeAppLifecycleState AppLifecycleState.paused
05-22 20:13:09.339 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

```

</details>

**Comment by xunreal75** [comment]
PS: You can see the access to location in Device-Settings, but location manager does not receive any location.

**Comment by christocracy** [comment]
05-22 20:12:35.993 WARN [SingleLocationRequest start] 
╔═════════════════════════════════════════════
║ ⚠️  Background location-updates forbidden (WhenInUse)
╠═════════════════════════════════════════════
╟─ Cannot initiate location requests in the background/headless with WhenInUse authorization.
╟─ Location updates must have previously been initiated with your app in the foreground.  Eg: .changePace(true).
╚═════════════════════════════════════════════

**Comment by christocracy** [comment]
- Check your device settings (Wifi Enabled, Location enabled)
- Check your app permissions

**Comment by xunreal75** [comment]
All permissions are granted, other apps are working. Issue is replicable on AVD emulation

**Comment by christocracy** [comment]
Test on a *real* device.  I do not test on emulators.  You cannot experience the true behaviour of this plugin in Android emulator.

**Comment by xunreal75** [comment]
The request was from a real device, but the same behavior is on emulator

**Comment by christocracy** [comment]
║ ⚠️ Background location-updates forbidden (WhenInUse)

**Comment by xunreal75** [comment]
The log is from the real device

**Comment by xunreal75** [comment]
Location is always permitted. Seems a problem of your framework . Request ist seen in settings location request but does not get received on your endpoint. Why do you have a permissions request before get current location. CalyxOS is a little bit more strength privacy.

**Comment by christocracy** [comment]
> Why do you have a permissions request before get current location

Because receiving a location requires location permission.

> Seems a problem of your framework 

This plug-in is not a side-project.  It’s been supported full time for over 8 years, with tens-of-thousands of users.

**Comment by xunreal75** [comment]
I'll debug that and give you a feedback. thanks

**Comment by xunreal75** [comment]
Hi

Do you support and know

Mozilla location service on CalyxOS?

Could it be the problem of non working location?


Mozilla Location Service is an alternative to Google Location Accuracy and is enabled by default in CalyxOS. Mozilla gathers and stores your IP Address, cell phone tower information, and WiFi network information. Unlike when using Google location services, Mozilla does not get any perminant identifiers or information tied to your identity.

**Comment by christocracy** [comment]
> Mozilla location service on CalyxOS?

I’ve never heard of any of those.

**Comment by ocroquette** [comment]
I am the owner of the real device @xunreal75 was talking about. It is a standard CalyxOS installation. CalyxOS replaces the Google Play Services by microG (https://microg.org/). I suspect that an incompatibility between microG and flutter_background_geolocation, since the demo app (https://play.google.com/store/apps/details?id=com.transistorsoft.flutterbackgroundgeolocationexample) does not get any location either. All permissions are given. All other location based applications are working fine.

@christocracy Since it looks like a general compatibility issue that is reproducible with the emulator, it would be great if you could try to pinpoint and solve it.

**Comment by christocracy** [comment]
Show the result of `$ adb logcat *:S TSLocationManager:V` of your app launching from a terminated state with this "*CalyxOS*".

**Comment by christocracy** [comment]
I do not see any locations being delivered.  I have no experience with this "*CalyxOS*".  I've never even heard of it.

**Comment by ocroquette** [comment]
Indeed the applications do not get any location.

CalyxOS is basically the opensource Android OS with microG instead of the Google Play Services, to improve privacy. Like mentioned earlier, I suspect that the incompatibility is with microG (which is used in other custom ROMs). It would be great if you could have a look at the issue in an emulator with CalyxOS or microG, since there is not much I can do more on my end unfortunately.

**Comment by ocroquette** [comment]
It may well be a bug or at least an inconsistency of behavior between microG and the Google Play Services, therefore I have opened also a bug report there: https://github.com/microg/GmsCore/issues/1963

@christocracy microG is a mature OpenSource project used by tens or hundreds of thousands users. If there is a discrepancy with the Google Play Service, it would be a great help for the developers and users if you could pin-point it and provide feedback in the other report. Plus it will help also the users of apps integrating your framework and microG.

**Comment by xunreal75** [comment]
@christocracy 
Since I can't see anything from your Android code implementation and location services are running with package location2 based on Lyokone/flutterlocation, the question is whether you have implemented a network location fallback aka LocationManager.NETWORK_PROVIDER. It is currently not possible to locate the cause in your package.

**Comment by christocracy** [comment]
> the question is whether you have implemented a network location fallback aka LocationManager.NETWORK_PROVIDER

It’s using `play-services:location`

**Comment by xunreal75** [comment]
Is it possible to implement network fallback as a feature in a subsequent release in times of data protection? Where should I place this?

**Comment by christocracy** [comment]
The plug-in uses [FusedLocationProvider](https://developers.google.com/location-context/fused-location-provider) from play-services.

**Comment by xunreal75** [comment]
You can only use another Flutter package like lyokone/location. There is no workaround with this package.
