### ISSUE TITLE
Samsung galaxy s21 ultra with android 13 not working in background

### ISSUE THREAD

**Issue by omejiasq** [transistorsoft/flutter_background_geolocation#1055]
## Your Environment
* Plugin version:4.8.2
* Platform:Android
* OS version:13
* Device manufacturer / model:Samsung galaxy S21 ultra
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

It should continue recording locations after closing the smartphone. On other smartphones with other versions of android it works fine in the background, or other brands
## Actual Behavior

After a few minutes the app does not register any more locations, but if I unlock the smartphone again, it does register locations
## Steps to Reproduce

1. I enable the location of this way: Settings/Location/My app/Allow all the time
2. In Settings/Apps/My app/Battery/ i set "Unrestricted"
3. After i install the app in the Samsung galaxy S21 Ultra
4. I block the screen and I begin to transport myself
5. After a couple of minutes, it no longer continues to register more locations, if not until I unlock the smartphone again

## Context

Debugging it and trying to see if I should enable something else in android 13 or something else in the samnsung galaxy s21 that can restrict it. But I don't know what else to do

## Debug logs

<details>
	<summary>Logs</summary>
This doesn't generate error logs on my laptop because I see this happen only when I go to transport and close the screen.
``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by omejiasq** [comment]
Thank you very much.
1. I installed now the latest plug-in version:4.11.0
2. Please can you tell me if enabling "allow all the time" of the location, and setting "Unrestricted" in the smartphone battery in android 13 is a good option or which setting is the most recommended for the location and the battery, since is this not in the documentation?

**Comment by christocracy** [comment]
If you want the plug-in to be able to automatically initiate location-tracking in the background, when the device is detected to be moving, you **MUST** enable “*Always*”.

> and setting "Unrestricted" in the smartphone battery in android 13 is a good option

If you want the plug-in to actually *work*, you must do that.  This is a restriction imposed specifically by the device manufacturer.

**Comment by omejiasq** [comment]
Thank you very much!
