### ISSUE TITLE
App Identifier not available 

### ISSUE THREAD

**Issue by adn9990** [transistorsoft/flutter_background_geolocation#1056]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Ignored issue template.

I have no idea what “ App Identifier not available” means.

**Comment by adn9990** [comment]
app identifier means app id on which transistorsoft issues a license. like  app.appname.com

**Comment by adn9990** [comment]
Not available to add app from that id on apple app store, That app id is already used or apple may be not support that app id

**Comment by christocracy** [comment]
Only Android consumes license keys.  You’re free to configure any app id you wish for ios.  iOS and Android are not required to be identical.

**Comment by christocracy** [comment]
You can edit your iOS app id directly in XCode.
