### ISSUE TITLE
documentation clarification/change request re: android headless motionchange

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1057]
looking at https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode

it says 
```dart
  case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print('- Location: $location');
      break;
```

should this be 
```dart
 case bg.Event.MOTIONCHANGE:
      bg.ActivityChangeEvent motionChange = headlessEvent.event;
      print('- motionChange: $motionChange');
      break;

```

**Comment by christocracy** [comment]
No, I think this was on-purpose.  It's `print`ing __`Location`__ because that's the nature of the object provided to the event.  The `onMotionChange` event is provided an instance of `Location`.

The details of what specific event is firing is printed as the first line of `headlessTask`

```dart
void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
  .
  .
  .
}
```
