### ISSUE TITLE
lint issue in example in documentation re: async await preferred over .then()

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1058]
when setting up with https://github.com/transistorsoft/flutter_background_geolocation#-example it says to use .then()
yet lint says to use async/await.

what do you think aboaut switching to async await in the example/docs?

very minor but thanks for considering - otherwise copy/pasting into an IDE will give warning squiggly lines :)
https://dcm.dev/docs/individuals/rules/common/prefer-async-await

**Comment by christocracy** [comment]
This is a generic question about dart Futures.

You are free to use either, it doesn’t matter.  Just don’t use *both* on the same method.
