### ISSUE TITLE
Update example app to flutter 3.10.x with dart 3.x fully null safe

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1064]
Problem:
Flutter 3.10.x has been in stable for a month or so and requires full null safety, so example app has many compile time errors out of the box.

Solution: update to non nullable variablea initializing to empty string, use late or ! sometimes etc.

**Comment by christocracy** [comment]
I’m aware, thanks.

**Comment by christocracy** [comment]
Done.
