### ISSUE TITLE
Some flavors will use the location plugin, others will not

### ISSUE THREAD

**Issue by MoacirSchmidt** [transistorsoft/flutter_background_geolocation#1065]
Congratulations for the best background locator plugin for flutter!

I have just purchased a STUDIO license in order to support some of my flavors

I have hundreds of clients (one for each flavor). Some clients will use the location feature of my app, others will not

Everything works great for flavor that use the flutter_background_geolocation plugin

Unfortunately, flavors that do not need the plugin shows message "LICENSE VALIDATION FAILURE" (for those flavors I put a blank license key). I cannot spend a license for clients that will not use the feature.

Could you please provide a way to avoid this message since these flavors do not use the plugin and the location feature are even not showed there

**Comment by christocracy** [comment]
Sorry, I don’t know of any way to solve that without providing it a license key.

how many apps do you have *not* using it?

**Comment by MoacirSchmidt** [comment]
Nowadays I have about 70 flavors (clients) that probably will use the location feature and about 100 that will not

**Comment by christocracy** [comment]
I’ll double your 100 keys to 200.

**Comment by MoacirSchmidt** [comment]
Thank you very much! That will perfectly solve the problem!

**Comment by pfalbatros** [comment]
Hi @christocracy ,

I'm experiencing the exact same issue with the "LICENSE VALIDATION FAILURE" message appearing in flavors that don't use the background geolocation plugin. I have multiple flavors where some need location tracking and others don't.

I have tried commenting in app/build.gradle.kts:
`// val backgroundGeolocation = project(":flutter_background_geolocation")`
`// apply { from("${backgroundGeolocation.projectDir}/background_geolocation.gradle") }`
But still got the LICENCE message.

Currently the only way to avoid this situation is to comment flutter_background_geolocation in pubspec.yaml, but this breaks the code in multiple files which defeats the purpose of flavors and makes the code unmaintainable.

Is there any solution available to suppress this validation error for flavors that don't utilize the plugin? Or would I need to obtain additional license keys for each flavor, even those that don't use the location features?

Any guidance would be appreciated!

**Comment by christocracy** [comment]
You need additional keys.
