### ISSUE TITLE
Does the plugin supports POSTing location data in text/plain?

### ISSUE THREAD

**Issue by fatihergin** [transistorsoft/flutter_background_geolocation#1066]
Does the plugin support posting location data in `content-type` `text/plain` format?
I'm able to override `content-type` with [Config.headers](https://github.com/transistorsoft/flutter_background_geolocation/blob/e8070b4d055a96e5ba2f8b4538cf334ff4702fbd/lib/models/config.dart#L574), but don't know how to override [Config.locationTemplate](https://github.com/transistorsoft/flutter_background_geolocation/blob/e8070b4d055a96e5ba2f8b4538cf334ff4702fbd/lib/models/config.dart#L772), or even it's possible.

Below template throws JsonFormatException. I can share detailed log if necessary.

```dart
Config(
        headers: {"content-type": "text/plain"}, 
        locationTemplate: '<%= latitude %> <%= longitude %>');
```

Thanks.

**Comment by christocracy** [comment]
Tags plug-in doesn’t post text/plain, it posts text/json only

**Comment by christocracy** [comment]
application/json, rather

**Comment by christocracy** [comment]
locationTemplate renders to JSON.  You must provide commas between items

**Comment by fatihergin** [comment]
thanks for the answer and quick response.
