### ISSUE TITLE
simple example not working for me 

### ISSUE THREAD

**Issue by Abouassi98** [transistorsoft/flutter_background_geolocation#1067]
* Plugin version: 4.11.1
* Platform: iOS simulator
* OS version: 16.4
* Device manufacturer / model:   All iOS devices
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

       bg.BackgroundGeolocation.onLocation(
              (bg.Location location) => updateBGLoc(location));

          // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
          bg.BackgroundGeolocation.onMotionChange(
              (bg.Location location) => updateBGLoc(location));

  void updateBGLoc(bg.Location location) async {
      Map<String, dynamic> deviceParams = await bg.Config.deviceParams;
      await bg.BackgroundGeolocation.ready(bg.Config(
              reset: true,
              debug: true,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              autoSync: true,
              params: deviceParams,
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10.0,
              backgroundPermissionRationale: bg.PermissionRationale(
                  title:
                      "Allow yalla Delivery to access this device's location even when the app is closed or not in use.",
                  message:
                      "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                  positiveAction:
                      'Change to "{backgroundPermissionOptionLabel}"',
                  negativeAction: 'Cancel'),
              stopOnTerminate: true,
              startOnBoot: true,
              enableHeadless: true))
          .then((bg.State state) {
        print('location =${location.coords.latitude}');
      });
    }
```

## Expected Behavior
print result of new location when change it while app in background

## Actual Behavior
not found any response

## Context

this code actually run in home base screen but I didn't register any background  headless-task .
and I have made access location is always to my app .
this code was have run with from 3 months .

**Comment by christocracy** [comment]
Further to the metaphor of the *Stereo System*:
- The `.start()` and `.stop()` methods are like the power switch.

I don't see you calling `.start()` anywhere.

**Comment by christocracy** [comment]
See the [Example in the README](https://github.com/transistorsoft/flutter_background_geolocation#-example)

<img width="821" alt="Screenshot 2023-06-13 at 8 34 00 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/437f80f8-348e-4903-97ca-687ac7c9a0bc">

**Comment by Abouassi98** [comment]
thanks for ur fasting reply , I have used as like that but nothing to printing console 

     bg.BackgroundGeolocation.onLocation(
          (bg.Location location) => print('location =$location'));

      // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
      bg.BackgroundGeolocation.onMotionChange(
          (bg.Location location) => print('location =$location'));
