### ISSUE TITLE
How to execute only the onLocation callback when app is launched from background

### ISSUE THREAD

**Issue by kvenn** [transistorsoft/flutter_background_geolocation#1068]
## Your Environment
* Plugin version: `^4.8.3`
* Platform: iOS
* OS version: All
* Device manufacturer / model: iPhone 14 Pro
* Flutter info (`flutter doctor`):
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
> [✓] VS Code (version 1.78.2)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability
> 
> • No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return bg.Config(
      transistorAuthorizationToken: token,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: _distanceFilter.toDouble(), // 10
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      // Android stuff
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: bg.PermissionRationale(
        title: '"Allow all the time" required for scoring',
        message:
            'Select "Allow all the time" in app settings to get points without opening the app.',
        positiveAction: 'Continue',
        negativeAction: 'Cancel',
      ),
      locationAuthorizationAlert: {
         // ...
      },
      logLevel: bg.Config.LOG_LEVEL_DEBUG,
    );
```

## Expected Behavior
(This is mostly a question, not necessarily what I'd expect the library to do)
Only the relevant location manager (and `onLocation`) paths are executed when woken up in the background

## Actual Behavior
All of `main` is executed when app is woken up in the background

## Steps to Reproduce
1. Froce quit app
2. Move enough to leave the stationary state
3. See that flutter widget code is running

## Context
I've read the wiki and made note of this line, as it relates to my question.
> When an iOS app is launched in the background, due to a geofence event for example, the entire app is launched in the background, just as if launched from the home-screen icon.

I've attempted to use a WidgetBindingObserver, as recommended [here](https://stackoverflow.com/a/52890987/1759443), but the event comes in too late (most of my setup logic has already executed by the time I can tell the rest of my system to stop).

**Is it possible to identify in Dart the difference between a launch from background and a launch from user interaction?** The most ideal place for this would be in the main function, so I could conditionally initialize Hive / network libraries / etc. I'm trying to do as little in the background as possible to optimize for battery performance.

I know you're an expert on all things background, so was hoping you might be able to point me in the right direction. Thank you 🙏

## Debug logs
N/A

**Comment by christocracy** [comment]
See [State.didLaunchInBackground](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/State/didLaunchInBackground.html).
