### ISSUE TITLE
onPreventSuspendTimer stops firing

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#1069]
## Your Environment
* Plugin version: 4.11.1
* Platform: iOS
* OS version: 16.5
* Device manufacturer / model: iPhone 8
* Flutter info
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.23)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)  • windows            • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!

* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  bg.Config _getBgConfig(bool moving) {
    _log.info('_getBgConfig');
    var localize = GlobalContext().localize;
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      disableElasticity: false,
      elasticityMultiplier: 1.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: 60 * 24 * 5,
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      showsBackgroundLocationIndicator: true,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize
                  .dlgBackgroundLocationPermissionTitle('{applicationName}'),
              message: localize.dlgBackgroundLocationPermissionContent(
                  '{backgroundPermissionOptionLabel}'),
              positiveAction: localize.dlgBackgroundLocationPermissionAction1(
                  '{backgroundPermissionOptionLabel}'),
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior

The bg time remaining should be a reasonable number. The onPreventSuspendTimer event should keep firing periodically.

## Actual Behavior

The number is unreasonably large:
2023-06-16 06:43:16.201 🔵-[BackgroundTaskManager onPreventSuspendTimer:] Prevent-suspend timer fired! (bg time remaining: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000)

The onPreventSuspendTimer fires periodically at first, then stops firing after about 20 minutes and the app eventually terminates. I have not found any crash reports related to the termination, so I'm thinking the OS terminated the app.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Just running the app normally. Everything seems to work for an hour or two, then the app disappears. I have not found anything unusual in the log except the onPreventSuspendTimer statements, but maybe you can see something.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/11771581/background-geolocation.log.gz)

**Comment by christocracy** [comment]
>Prevent-suspend timer fired! (bg time remaining: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000

When you see that, the number essentially represents the `long` value of `Infinity`.  iOS has an API method which returns the amount of background-time remaining -- when executed in the foreground, the amount of background-time remaining is essentially *Infinite*.

`preventSuspend` is not *fool-proof* and is not guaranteed to fire at the exact rate.  See API docs [`Config.preventSuspend`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/preventSuspend.html)

<img width="735" alt="Screenshot 2023-06-19 at 9 47 43 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/a74ba869-6281-4e94-9512-572436e182db">
