### ISSUE TITLE
User geofence tracking and location tracking as different features

### ISSUE THREAD

**Issue by ilyosbekkk** [transistorsoft/flutter_background_geolocation#1072]
Hello, in my app I have to use both geofence tracking (`onGeofence`) and location tracking (`onLocation`). In a current implementation when you call `stop` both geofence and location tracking will stop, but I need to make them separate so that when I call `stop` method only location tracking should stop not geofence tracking. Is there any workaround for that? Also, how do I enable only location tracking when `start` method is called?

## Your Environment
* Plugin version: 4.11.0
* Platform: iOS or Android
* OS version: 
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    final state = await bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        debug: currentFlavor.isDevelopment,
        logLevel: bg.Config.LOG_LEVEL_OFF,
      ),
    );

 if (!state.enabled) {
      await bg.BackgroundGeolocation.start();
}
```

## Expected Behavior
When I call `bg.BackgroundGeolocation.start()` only location tracking should start, not geofence tracking
When I call `bg.BackgroundGeolocation.stop()` only location tracking should stop, not geofence tracking
There should be a way to stop geofence only, there is way to start it (`startGeofence`), but AFAIK there is no way to stop geofence only.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- .start = track location + geofences
- .startGeofences() = track geofences only.

you do not need to call .stop() to toggle between the two modes.

read the api docs “Geofencing Guide” for much more info.

**Comment by ilyosbekkk** [comment]
Thanks for the reply, it's written that geofences will be monitored forever once they are added to SDK database, but what if user wants to disable only location tracking and calls .stop() method? In this case, will both location and geofence tracking be stopped? 
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/46449085/47bacbb1-637d-41a2-a807-bfd53b712ba8)



![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/46449085/4f82990f-9e3c-4be4-82cf-da01d1bde523)

**Comment by christocracy** [comment]
Geofences will be monitored forever **while the plugin is enabled**.  Calling `.stop()` does *exactly* what you should expect:  it stops everything.  Just like pressing the power [OFF] button on your TV turns the TV off.

- Calling `.start()` or `.startGeofences()` sets `State.enabled -> true`.
- Calling `.stop()` sets `State.enabled -> false`.

**Comment by ilyosbekkk** [comment]
I do want to keep geofences active forever, but my users sometimes might want to turn off location tracking itself, so I call `.stop() ` to do that, but in this case it stops geofence as well. How can I keep geofence active while location tracking is off?

**Comment by christocracy** [comment]
Is there something you don't understand [up there in this comment](https://github.com/transistorsoft/flutter_background_geolocation/issues/1072#issuecomment-1618256382)?

**Comment by christocracy** [comment]
Read the API docs [Geofencing Guide](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/GeofenceEvent-class.html)

<img width="773" alt="Screenshot 2023-07-03 at 10 18 26 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/b8d82e82-b73c-48d3-bfa2-c51fa1493eda">

**Comment by ilyosbekkk** [comment]
okay, thank you for your kind response and patience, I replaced that stop() with startGeofence() and then printed the state on the console: it printed 0 which means now I am in `only geofence tracking` mode, but even after that,  plugin continued  monitoring location events, is it because I have active an active onLocation listener? should I remove that listener after toggling?  thanks


```
  Future<void> startBackgroundGeolocation(String status) async {
    final state = await bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter,
        stopOnTerminate: false,
        startOnBoot: true,
        // headless mode enabled but we do not have GPS tracking feature for terminated state yet
        enableHeadless: true,
        debug: currentFlavor.isDevelopment,
        logLevel: bg.Config.LOG_LEVEL_OFF,
      ),
    );

    await bg.BackgroundGeolocation.start();
    final stst = await bg.BackgroundGeolocation.state;
    print('state: ${stst.trackingMode}');
    // printed 1
  
  }
```

```
  Future<void> toggleLocationTracking() async {
    bg.BackgroundGeolocation.removeListener(bg.BackgroundGeolocation.onLocation);
    await bg.BackgroundGeolocation.startGeofences();
    final state = await bg.BackgroundGeolocation.state;
    print('state: ${state.trackingMode}');
    // printed 0
    _locationController.add(false);
  }
```

```
  void listenLocationUpdates(String status) {
    bg.BackgroundGeolocation.onLocation((bg.Location location) async {
        print('trying location updates....');
        /// this is being fired even if the state is 0
    });
  }
```

**Comment by christocracy** [comment]
>is it because I have an active onLocation listener?

No.  Event-listeners to no affect performance.  They are like speakers on a stereo system.  Removing or adding a speaker doesn't affect the state of the music playing on the stereo.

> should I remove that listener after toggling?

No.

Go outside for a nice long walk with `debug: true` after calling `.startGeofences()`.

**Comment by ilyosbekkk** [comment]
thank you, it works:). About listeners, should I start listening location/geofence updates every time when the app starts? or does the plugin remembers each listener and starts listening them automatically even after force close and opening the app again?

**Comment by christocracy** [comment]
JavaScript is like chalk on a chalkboard:  terminating the app is like an eraser that wipes the chalk clean.

Your Javascript no longer exists after the app is terminated.  you must re-register event-listeners with each launch of your app.

**Comment by ilyosbekkk** [comment]
thank you for your help:)
