### ISSUE TITLE
Offline location fetching is not working in debug mode

### ISSUE THREAD

**Issue by anoopVoyon** [transistorsoft/flutter_background_geolocation#1073]
1. Plugin version: 4.8.1
2.Platform: Android
3. OS version: all Android versions > 9.x
4.Device manufacturer / model:  samsung s21FE

Flutter info (flutter doctor):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1848], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.24)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

Plugin config:

```dart
   bg.BackgroundGeolocation.ready(bg.Config(
      reset: false,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0.0,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
              "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      autoSync: false,
      stopOnTerminate: false,
      startOnBoot: false,
      enableHeadless: false,
      heartbeatInterval: 60,
      minimumActivityRecognitionConfidence:1
    )).then((bg.State state) async {
      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }
```
Expected Behavior
 In fact we are developing an app which can be used by the marketing guys who visits the customers frequently and we would like to track their route map to calculate the distance travelled by them for every trip. We came across your package and thought of procuring it if it can work on offline mode because the mobile can go offline when they travel in remote areas. So currently we are evaluating your package in debug mode and it works perfect in online mode. 

Actual Behavior
However, we have a challenge in getting the data in offline mode.

images:
![image (1)](https://github.com/transistorsoft/flutter_background_geolocation/assets/138643670/1a221af4-8f08-464f-8edc-c46e6ffe56cf)
![image (2)](https://github.com/transistorsoft/flutter_background_geolocation/assets/138643670/8da15a24-a51f-43f7-b978-23c550e315e8)

**Comment by christocracy** [comment]
Please learn to [syntax highlight "multiline code blocks"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).  It's easy.  You don't need to post screenshots of code.

**Comment by christocracy** [comment]
>reset: false,

Do you know what this does?  If you don't, delete it from your Config.  You likely copy/pasted that from the /example app, which is the wrong thing to do.

Do you know that the plugin has its own built-in HTTP service and SQLite database?  See API docs [HTTP Guide](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/HttpEvent-class.html)

Also [see Wiki](https://github.com/transistorsoft/flutter_background_geolocation/wiki)
- Debugging
- Philosophy of Operation
- https://dontkillmyapp.com
