### ISSUE TITLE
App is getting crashed when debugging got disconnected in iOS

### ISSUE THREAD

**Issue by poorvasha-pss** [transistorsoft/flutter_background_geolocation#1074]
## Your Environment
* Plugin version: 
* Platform: iOS or Android : iOS
* OS version: 16.5
* Device manufacturer / model: iPhone SE (2nd generation)
* Flutter info (`flutter doctor`): 
<img width="657" alt="image" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/132580413/ad9c5c9e-fd25-4501-b373-74981ad74838">

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.BackgroundGeolocation.ready(bg.Config(
            reset: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            url: "${ENV.TRACKER_HOST}/api/locations",
            authorization: bg.Authorization(
                // <-- demo server authenticates with JWT
                strategy: bg.Authorization.STRATEGY_JWT,
                accessToken: token.accessToken,
                refreshToken: token.refreshToken,
                refreshUrl: "${ENV.TRACKER_HOST}/api/refresh_token",
                refreshPayload: {'refresh_token': '{refreshToken}'}),
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true))
```

## Expected Behavior
App should run even if debugging has been disconnected

## Actual Behavior
We have cloned this repository and just ran the app, it is working fine while it is connected for debugging, but when the app is disconnected from debugging it is being crashed on clicking the app icon in device home screen 

## Steps to Reproduce

1. Run the app connecting to USB  in debug mode
2. Once app launch, move to "Advance App", you can see toggle button at top right, turn on the toggle button and click on the play button at bottom right
3. Terminate the app
4. Click on "BG Geo" app in your home screen
5. The app doesn't open, it gets crashed

## Context
We are just ensuring whether the demo app is working fine for iOS as we are planning to buy the plugin

https://github.com/transistorsoft/flutter_background_geolocation/assets/132580413/3c82ef40-0f22-4963-a7e0-f77890bef7f0

## Debug logs
Can't able to debug as the issue occurs only if debug is disconnected

**Comment by christocracy** [comment]
This is a phenomenon related to Flutter debugging.  I always install iOS apps onto a device for “release”.

**Comment by poorvasha-pss** [comment]
Thank you so much! is there any other work around or solution to fix the debug mode issue?

**Comment by neiljaywarner** [comment]
@poorvasha-pss  could you run in release mode, ie flutter run --release

**Comment by poorvasha-pss** [comment]
@neiljaywarner  Yes I can able to run in release mode
