### ISSUE TITLE
Recommended ways to handle choppy/inaccurate location tracking

### ISSUE THREAD

**Issue by frankvollebregt** [transistorsoft/flutter_background_geolocation#1076]
When the users of my app are driving, their location is being recorded using the plugin (which is great, for the most part!). However, sometimes the trace becomes very choppy, sometimes going back and forth or going side-to-side.

## Your Environment
* Plugin version: 4.11.1
* Platform: Mostly Android, some iOS
* OS version: Various, mostly 13/12
* Device manufacturer / model: Various, mostly Samsung Galaxy XCover 5 and Cat S42
* Flutter info (`flutter doctor`):
```
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
  debug: false,
  logLevel: bg.Config.LOG_LEVEL_ERROR,
  stopOnTerminate: false,
  startOnBoot: false,
  authorization: bg.Authorization(accessToken: accessToken),
  url: endpoint,
  extras: ...,
  logMaxDays: 1,
  notification: ...,
  backgroundPermissionRationale: ...,
  // When the apparent movement speed was over 144 km/h, discard the location
  speedJumpFilter: 40,
  // On Android, trigger on vehicle and bicycle activities
  triggerActivities: 'in_vehicle, on_bicycle',
  // On iOS (presumably) trigger on automotive locations
  activityType: bg.Config.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
)
```

## Expected Behavior
I expect, and oftentimes get, a smooth trail of the vehicle's path, like in the image below.
<img src="https://github.com/transistorsoft/flutter_background_geolocation/assets/23523399/ce74347b-8088-4d14-9f5d-0cf939927c65" width="500px"/>

## Actual Behavior
Sometimes, however, I get a trace like the one in the screenshot below. In this case, it is inside a city (with a speed limit of 30/50 km/h).

<img src="https://github.com/transistorsoft/flutter_background_geolocation/assets/23523399/6590a254-ae88-40bb-9dd5-e792c3bf3e13" width="500px"/>

But it also occurs on highways from time to time (with speeds of around 90 km/h):

<img src="https://github.com/transistorsoft/flutter_background_geolocation/assets/23523399/d5512273-77fb-48a3-8dbc-befc36ae3f67" width="500px"/>

Now my question is, are there recommended settings that I haven't touched yet, that could help me to get a smoother trace? I understand that GIGO applies here: If the OS's location service provides poor location updates, the plugin won't be able to magically make them better. Is it likely that tweaking distance/elasticity parameters improves the experience here?

Another thing I found online is using a Kalman filter to smoothen the trace. The one in the link below looks choppy in a similar fashion to the one I'm seeing before they process it: https://maddevs.io/blog/reduce-gps-data-error-on-android-with-kalman-filter-and-accelerometer/. Is this something that the plugin can currently/could in the future/should do itself? Otherwise, I might look into applying it on the server side after my locations have been pushed.

I am aware that the `speedJumpFilter` is a very low number in my configuration (40 m/s instead of the default of 300 m/s). This was an attempt to filter out anomulous locations, and seems to work in part (it used to be worse in some/many cases). Since the users of the app will mostly drive up to 90 km/h, I do not expect this to cause issues.

## Debug logs
The examples above were taken in a version of my app that does not provide functionality to share the logs, but if it turns out that there is a specific issue causing this, I can go out and try to get some useful logs on my own device.

**Comment by christocracy** [comment]
Depending on the environment, GPS can get confused by instructions (tall buildings, bridges, tunnels, etc).

it’s up to you to filter out undesirable results.  See `Location.coords.accuracy`.

**Comment by frankvollebregt** [comment]
Thank you, that's kind of what I expected. Can I do this filtering (or other processing) in my app before the plugin sends the location to the server? I can't find info about this in the documentation.

And another small question about the documentation, I think there's no specifications for the contents of the HTTP request when locations are batched: A single location is just a single JSON object `{}` with the different properties of a `Location`, but it is nowhere stated whether batched locations are pushed as a direct JSON array of location objects `[{}, {}]` or as a map `{'locations': [{}, {}]`. While I could figure this out myself, I guess it might be useful to provide an example payload for a single and batched HTTP request in the docs. Just an idea ;)

**Comment by christocracy** [comment]
>Can I do this filtering (or other processing) in my app before the plugin sends the location to the server?

Why not just filter at the server?  Filtering cannot be done with `dart` code.

See [Config.httpRootProperty](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/httpRootProperty.html)

- `httpRootProperty` defaults the word `location`.
- `batchSync: true` *implies* *Array of object*:
```javascript
{
  httpRootProperty: [ {Location}, {Location}, {Location}, ... ]  // <-- Array of {Location}
}
```

- `batchSync: false` (default) implies *Single Object*:
```javascript
{
  httpRootProperty:  {Location} // <-- Single {Location}
}
```

**Comment by frankvollebregt** [comment]
Thank you, and that makes sense given the plugin availability on all the different platforms.
