### ISSUE TITLE
Location tracking stops working after a few days

### ISSUE THREAD

**Issue by 4A6F6F6E61** [transistorsoft/flutter_background_geolocation#1080]
## Your Environment
* Plugin version: ^4.8.1
* Platform: iOS and Android
* OS version: iOS 16.4
* Device manufacturer / model: iPhone 14 Pro Max (Simulator)
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale
    en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
* Plugin config:
```dart  <!-- syntax-highligting:  DO NOT REMOVE -->
bg.BackgroundGeolocation.onLocation((bg.Location location) async {
  log('[onLocation] $location');
  final geo = GeoFlutterFire();
  currentLocation.value = location; // this is saving the current location in my GetX state
  GeoFirePoint myLocation =
      geo.point(latitude: location.coords.latitude, longitude: location.coords.longitude);
  placemarkFromCoordinates(location.coords.latitude, location.coords.longitude,
          localeIdentifier: Get.locale?.countryCode ?? "en_US")
      .then((value) {
    log(placemarks.toString());
    placemarks(value);  // this is saving the placemark in my GetX state
  });
  if (auth.currentUser != null) {
    firebaseFirestore
        .collection('users')
        .doc(auth.currentUser!.uid)
        .update({'position': myLocation.data});
  }
}, (bg.LocationError error) {
  log('[onLocation] ERROR - $error');
});
var state = await bg.BackgroundGeolocation.ready(
  bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10.0,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_DEBUG,
  ),
);
if (!state.enabled) {
  await bg.BackgroundGeolocation.start();
}
```

## Expected Behaviour
The App should keep fetching the current location

## Actual Behaviour
The App fetches my location 1-3 times at the start of my App, but then just silently stops. My location doesn't update anymore and I get no [onLocation] printed in the terminal. I don't even get an Error-code or something that would explain why the location tracking stopped. This happened to me before, but after reinstalling MacOS and my DevTools it worked again for a few days. I checked out earlier versions of my App in Git that I know worked in the past, thinking that I may have fucked something up in the latest version but they also don't work.

## Steps to Reproduce
1. Execute my code 
2. wait a few seconds

## Context
Fetch the current location and save it as a GeoHash in my Firebase backend

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
nothing
```

</details>

**Comment by christocracy** [comment]
> Plugin version: ^4.8.1

iOS 16.4 made changes.  See the CHANGELOG and upgrade to latest

**Comment by 4A6F6F6E61** [comment]
Thanks for the info, I'll check it out.

**Comment by 4A6F6F6E61** [comment]
I didn't change my code but all of the sudden the location tracking works again as it should.
I am unable to find a reason why it sometimes worked as it should and other times only fetches the location ca 3 times at the start and then just quietly stops. Is there some way to get mote detailed logs from this package like for example why it stopped? My console is just empty when this happens.
Help would be greatly appreciated.

**Comment by christocracy** [comment]
See Wiki "Debugging".  The plugin has an incredible logger.  learn to use it.

**Comment by 4A6F6F6E61** [comment]
Thanks, I will use this the next time I encounter this issue!
