### ISSUE TITLE
Can i setting post location to server every 2min, 5min, 10min or every 100m, 200m in android and ios?

### ISSUE THREAD

**Issue by pogenz45** [transistorsoft/flutter_background_geolocation#1081]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It’s better to think in terms of distance (Config.distanceFilter).  Only Android can do time-based location updates with Config.locationUpdateInterval.

iOS is strictly distance-based.

**Comment by pogenz45** [comment]
> It’s better to think in terms of distance (Config.distanceFilter). Only Android can do time-based location updates with Config.locationUpdateInterval.
> 
> iOS is strictly distance-based.
