### ISSUE TITLE
Accessibility:Default permission dialog does not show cancel button with Android 14 max scale

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1085]
flutter_background_location: 4.11
Android Version 14
slide display size and font size all the way to the right.

The sort of default Android layout has ok and cancel vertically and you can't see the cancel.
Please consider modifying the padding just a bit or something so you can see 'cancel'.

If i recall it supports custom layout well so i can do it but i thought i'd at least mention it.
thank you
[Edit]: I just realized, my apologies, we could also just use shorter text. Do you want me to close this ticket?

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/3019617/3d07c5fa-b0b2-4279-bb84-fec934d4ae11)

**Comment by neiljaywarner** [comment]
@christocracy  how easy would it be to simply modify so if there's no title then the padding is gone?
backgroundPermissionRationale: PermissionRationale(
        title: '',
        message: 'blah',
        positiveAction: 'ok,
        negativeAction: 'cancel',
      )

**Comment by christocracy** [comment]
Why don’t you show a more concise message and produce your own dialog with a longer message *before*?

**Comment by neiljaywarner** [comment]
@christocracy  sounds like a pretty good idea.
What do you think of my idea of if the title is empty string then eliminate the space it takes up?

I could try to find time to do a PR for it if that part is available for that.. maybe it's not though.
anyway, thanks for the reply... I am proposign shorter text and obviously I could use the default, it's probably plenty short enough.
You dont localize the default per device language yet right?

**Comment by christocracy** [comment]
You’re *required* by Play Store to show a dialog where you explain why you need the background location permission you’re about to ask for *before* requesting permissions.  If you don’t, they reject your app.  “*Prominent Disclosure*”, they call it.

see **Step 5** in [my blog](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353) about this.
