### ISSUE TITLE
Probable updates for targeting Android 14

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1087]
android 14 is currently in platform stability which means they suggest/request apps to update for it. It will probably be released in August; so people will be upgrading the target API in the next 6 months.

https://developer.android.com/about/versions/14/overview
Here are some items that migth affect this plugin
https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types
https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions
etc

New apps are required to target Android 13 by Aug 2023, therefore Aug 14 by Aug 2024, which means organizations may start making these changes anytime and may be thinking about them now because of the release of Android 14

thank you for consideration

**Comment by christocracy** [comment]
Yes, the plug-in uses 5 different FG services, each with their own `android:foregroundServiceType` defined.

It’s all working great with Android 14, targetSdkVersion 34.

**Comment by christocracy** [comment]
I’ve already submitted a build of the /example app to play store with targetSdkVersion 34 and it was accepted.  It’s live now.
