### ISSUE TITLE
Background broadcasting stops unexpectedly on iOS

### ISSUE THREAD

**Issue by JordanSearle** [transistorsoft/flutter_background_geolocation#1089]
## Your Environment
* Plugin version: 4.10.2
* Platform: iOS
* OS version: 16.3.1
* Device manufacturer/model: Apple iPad Air (4th generation)
* Flutter info (`flutter doctor`): 
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
* Plugin config:
```dart
// main.dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise map caching
  FMTC.initialise(
    await RootDirectory.normalCache,
  );

  await FMTC.instance(MaptileHelper.basemapCacheName).manage.createAsync();
  await FMTC.instance(MaptileHelper.satelliteCacheName).manage.createAsync();
  await FMTC.instance(MaptileHelper.seamapCacheName).manage.createAsync();

  // Boot app
  runApp(ProviderScope(child: MyApp()));

  // Register background events for Android (WIP)
  bg.BackgroundGeolocation.registerHeadlessTask(
    PositionBroadcastHelper.updateLocation,
  );
}

// position_broadcast_helper.dart
abstract class PositionBroadcastHelper {
  static void updateLocation(bg.HeadlessEvent headlessEvent) async {
    if (!await isBroadcasting()) return;

    bg.BackgroundGeolocation.getCurrentPosition(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
      timeout: Config.locationTimeout, // 5 seconds
    ).then((bg.Location location) => _isolateCallback(location)); // makes API request via an `isolate`
  }

  static Future<bool> isBroadcasting() async {
    bg.State state = await bg.BackgroundGeolocation.state;
    return state.enabled;
  }

  // Called when friends are enabled and when the app has been started
  static Future<void> startBroadcasting() async {
    await bg.BackgroundGeolocation.start();

    registerHeartbeat();
  }

  static void registerHeartbeat() async {
    bg.BackgroundGeolocation.onHeartbeat((_) async {
      // Request a new location so the value is up to date
      bg.BackgroundGeolocation.getCurrentPosition(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
        timeout: Config.locationTimeout, // 5 seconds
      ).then((bg.Location location) => _isolateCallback(location)); // makes API request via an `isolate`
    });
  }
}

```

## Expected Behavior
* opened the app, enabled the App’s friend feature
* POST requests should be made to the client’s API at 15-minute intervals when the device is moving

## Actual Behavior
* opened the app, turned on background updates - POST made
* closed (backgrounded) the app and locked the iPad - three further POSTs were made at 15-minute intervals despite not moving
* taken the iPad, with an internet connection, down loitered >900m from the house, spending some time using the iPad, but not opening App, before walking back - no POST made over a couple of hours
* unlocked the iPad and used it a bit but not opened the app at my desk - no POST
* toggled friends off/on - POST made, position sent
* locked the iPad and left it on my desk - 7 further POSTs made at ~15-minute intervals, then they stopped (no movement)

Our assumption is we will need to add a `distanceFilter` (as mentioned in the docs), to solve the issue of it posting when no movement was made. But we are not currently sure why the background process is stopping unexpectedly. 

## Steps to Reproduce
See Actual Behavior and code above

## Context
The client has an award-winning application, which currently uses `background_locator_2` to handle background location updates. We want to switch to `flutter_background_geolocation` for iOS and eventually Android when fully tested and integrated on iOS. 

On the client's app there is a map, when enabled, that shows the current position of the user’s “friends” and is also intended to send the user’s location via a POST request to the API every 15 minutes. We have found that the background process will make a POST request a number of times and then will stop.

## Debug logs
<details>
	<summary>Logs</summary>

```
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki “Philosophy of Operation” and learn about how the plug-in operates.

**Comment by christocracy** [comment]
Also see wiki “Debugging” to learn about observing the plug-ins incredibly verbose logs.
