### ISSUE TITLE
License Validation Failure in Debug Mode (Android)

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#109]
## Your Environment
* Plugin version: 1.2.1
* Platform: Android
* Flutter info (`flutter doctor`): 

[√] Flutter (Channel master, v1.9.4-pre.37, on Microsoft Windows [Version 10.0.17763.678], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  // 2.  Configure the plugin
  gps.BackgroundGeolocation.ready(gps.Config(
          desiredAccuracy: gps.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: true,
          logLevel: gps.Config.LOG_LEVEL_VERBOSE,
          reset: true))
      .then((gps.State state) {
    if (!state.enabled) {
      // 3.  Start the plugin.
      gps.BackgroundGeolocation.start();
    }
  });
```

## Context
"The Android module requires purchasing a license. However, it will work for DEBUG builds. It will not work with RELEASE builds without purchasing a license."

"Configure your license
If you've not yet purchased a license to unlock Android, you can purchase one here. Otherwise, ignore this step (Android is fully functional in DEBUG builds without a license key so you can evaluate the plugin)."

My debug build failed validation as I haven't purchased a licence, preventing me from testing out the plugin.

[Here is a screenshot showing the validation message](https://drive.google.com/file/d/119GVhrs116sqwTlw7cWMFCXU83Vlqthl/view?usp=sharing). As you can see in the top right, I am in debug mode.

**Comment by christocracy** [comment]
The toast is normal and expected.  It means the plugin is alive.

Carry on using it in debug builds.

**Comment by christocracy** [comment]
@izkpq Not without purchasing a license.

**Comment by wazeerahmed786** [comment]
Even purchased the key it still giving license validation error . why this is happening ?

**Comment by christocracy** [comment]
> why this is happening ?

Either:
1.  you failed to completely follow all the required setup instructions linked in the readme.
2. You generated a license key for the wrong applicationId
3. You purchased the wrong license key (eg react native, Capacitor, etc).

email me the following files info (don’t post it here)

1.  Order #
2. AndroidManifest
3. Android/build.gradle
4. Android/app/build.gradle
