### ISSUE TITLE
Background location (issues on Ios)

### ISSUE THREAD

**Issue by appdeveloperSHI** [transistorsoft/flutter_background_geolocation#1091]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

on debug mode its working prefectly but at live not working BG location

**Comment by christocracy** [comment]
Ignored issue template.  Provided no logs or any other information.
