### ISSUE TITLE
Android doesn't send location request to server

### ISSUE THREAD

**Issue by dinhha** [transistorsoft/flutter_background_geolocation#11]
## Your Environment
* Plugin version: 0.1.6
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Samsung S8
* Flutter info (`flutter doctor`):

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.28.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

* Plugin config
```
geoBg.Config(
    reset: true,
    distanceFilter: 0.0,
    stationaryRadius: 25.0,
    desiredAccuracy: 1000,
    activityRecognitionInterval: 300000,
    activityType: geoBg.Config.ACTIVITY_TYPE_OTHER,
    stopOnTerminate: false,
    startOnBoot: true,
    heartbeatInterval: -1,
    preventSuspend: false,
    stopDetectionDelay: 3,
    locationAuthorizationAlert: {
      "titleWhenOff": "", 
      "titleWhenNotEnabled": "", 
      "instructions": '',
      "cancelButton": 'Ignore',
      "settingsButton": 'Update Settings'
    },
    // HTTP
    autoSync: true,
    url: "$API_URL",
    method = 'POST',
    httpRootProperty: '.',
    maxRecordsToPersist: 0,
    // ANDROID
    fastestLocationUpdateInterval: 600000,
    notificationTitle: 'Click Background Location Tracking',
    notificationSmallIcon: 'drawable/notification_small',
    locationUpdateInterval: 60000,
    activityRecognitionInterval: 120000,
    // DEBUGGING
    logLevel: geoBg.Config.LOG_LEVEL_VERBOSE
    debug: true
})
```

## Expected Behavior
It should post the request to server when the location changed

## Actual Behavior
It did not send any location request to our server

**Comment by christocracy** [comment]
- Are you watching the logs.  See wiki [Debugging](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Debugging)

```
$ adb logcat -s TSLocationManager
```

- Is your server PHP?

**Comment by christocracy** [comment]
You told the plugin to record 0 locations.  Why?  That's your problem.
```
    maxRecordsToPersist: 0,
```

Why did you do that?

The plugin's HTTP service operates by selecting records from the database.  `maxRecordsToPersist` tells the plugin to ensure that the database contains only that many records.

After each `INSERT INTO locations...', the plugin then `ℹ️  SHRINK: 0`, deleting the record that was just created.

By the time the HTTP Service is summoned, there's no records left in the database.
```
8229 I TSLocationManager:   ✅  INSERT: c45fa9a0-1967-4956-9e82-cb4efde1887f
10-18 10:15:22.592  2821  8229 D TSLocationManager:   ℹ️  SHRINK: 0
╔═════════════════════════════════════════════
10-18 10:15:22.614  2821  8229 D TSLocationManager: ║ HTTP Service
10-18 10:15:22.614  2821  8229 D TSLocationManager: ╠═════════════════════════════════════════════
```

**Comment by dinhha** [comment]
Thank you!

**Comment by christocracy** [comment]
`maxRecordsToPersist` was designed to prevent the plugin storing *too many* records (eg: 100k).

If you tell it to record `0`, well...the plugin is going to respect your wish.

**Comment by christocracy** [comment]
What were you thinking setting `maxRecordsToPersist: 0`?

**Comment by christocracy** [comment]
Your Android-only locationUpdateInterval: 600000 is a bad idea, btw.  You’re not saving battery by doing that.  iOS is going to be running with distanceFilter: 0, essentially a location every second.

Use distanceFilter for Android.  Time-based tracking is a bad idea.

**Comment by dinhha** [comment]
Actually, we have separated configs for iOS and Android.

On iOS, distanceFilter = 30, and use background task with post the location to server.

On Android, is using time-based tracking with:
<pre><code>..distanceFilter = 0.0
..locationUpdateInterval = 60000
..activityRecognitionInterval = 120000;</code></pre>

Any suggestions?

**Comment by christocracy** [comment]
My suggestion is above:  forget about time-based tracking and use distanceFilter for both iOS and Android.

**Comment by dinhha** [comment]
Thank you. I will try it

**Comment by bCliks** [comment]
@christocracy Hi.. I want to change the default request and post the request to server when the location changed. 
Where I need to customize the default request?
Just I want to add few more properties in the request.

**Comment by christocracy** [comment]
Search api docs for “HTTP Guide”.

**Comment by bytelyus** [comment]
Hi @christocracy .. regards from Spain and congrats for so nice plugin.. My company is considering buying android licensce, but first i have to make it work... 

We work with a php backend webservice and i am trying to figure out how to get the location data from the request...

I can't find POST vars in my request  .... event if try to print $_REQUEST var, which is supossed to contain all data in POST, GET, ...  i get no values there... 

So... ¿how  do you get location data on a php backend webservice? ...

This far i have tried almost everything from Dart request with Config ...

fbg.BackgroundGeolocation.ready(fbg.Config(
      reset: true,
      desiredAccuracy: fbg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 2.0, // en metros [10. normal... 3.Testeo]
      // en metros
      stopOnTerminate: false,
      startOnBoot: true,
      batchSync: true,
      debug: true,
      logLevel: fbg.Config.LOG_LEVEL_VERBOSE,
      url: _url,
      params: {
        "id_cliente": 5,
        "lat": 55.0000,
        "lon": -5.5555,
      },
      extras: {
        "id_cliente": 5,
        "lat": 55.0000,
        "lon": -5.5555,
      },
      headers: {
        "Authorization": "Basic sekret-key",
        "Token": "MikToken",
        "content-type": "application/json",
      },
      httpRootProperty: '.',
      autoSync: true,
      method: 'POST',
      enableHeadless: true,
      encrypt: false,
      autoSyncThreshold: 5,
      maxBatchSize: 50,
    )).then((fbg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        fbg.BackgroundGeolocation.start();
      }
    }).catchError((error) {
      print("FBG ERROR: ${error.toString()}");
    });

-------- 

I can get all Headers in my php .... but doesnt reach even params or extras arrays... or don't know the way to do it

Any advise?

Thanks very much in advance ...

**Comment by christocracy** [comment]
The data in php is available with:
```php
file_get_contents("php://input");
```

**Comment by bytelyus** [comment]
got them!! ... thanks very much :) .. keep on testing
