### ISSUE TITLE
android crash after update to api level 34

### ISSUE THREAD

**Issue by allenbrunson** [transistorsoft/flutter_background_geolocation#1101]
## Your Environment
* Plugin version: 4.12.0
* Platform: android
* OS version: android os version 13
* Device manufacturer / model: Pixel 5
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] Connected device (1 available)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config _config() {
    return bg.Config(debug:false,
     backgroundPermissionRationale:_configDialog(geodeConfig),
     desiredAccuracy:bg.Config.DESIRED_ACCURACY_HIGH,
     distanceFilter:10.0,
     locationAuthorizationRequest:"Always",
     logLevel:bg.Config.LOG_LEVEL_ERROR,
     stopOnStationary:false);
}
```

## Expected Behavior

the app should compile and run normally
## Actual Behavior

thie app crashes on startup
## Steps to Reproduce

1. update android studio from api level 33 to 34
## Context

build and run the app normally
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Launching lib/main.dart on Pixel 5 in debug mode...
Running Gradle task 'assembleDebug'...
[flutter_background_geolocation] Purging debug resources in release build
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
D/FlutterArchivePlugin(12444): onAttachedToEngine - IN
D/FlutterArchivePlugin(12444): doOnAttachedToEngine - IN
D/FlutterArchivePlugin(12444): doOnAttachedToEngine - OUT
D/FlutterArchivePlugin(12444): onAttachedToEngine - OUT
Debug service listening on ws://127.0.0.1:59094/lqbl1AGQjEE=/ws
Syncing files to device Pixel 5...
I/.driverwireless(12444): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
D/ProfileInstaller(12444): Installing profile for com.cargotel.driverwireless
[log] 2023-08-18 11:05:46am  screen: “large phone” 392.73 × 826.91
W/Settings(12444): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Settings(12444): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/TSLocationManager(12444): - Enable: false → true, trackingMode: 1
W/Settings(12444): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AndroidRuntime(12444): Shutting down VM
E/AndroidRuntime(12444): FATAL EXCEPTION: main
E/AndroidRuntime(12444): Process: com.cargotel.driverwireless, PID: 12444
E/AndroidRuntime(12444): java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.LocationRequestService@6f26fc5 with Intent { act=start cmp=com.cargotel.driverwireless/com.transistorsoft.locationmanager.service.LocationRequestService (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(12444): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4673)
E/AndroidRuntime(12444): 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/AndroidRuntime(12444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
E/AndroidRuntime(12444): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12444): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(12444): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(12444): 	at android.app.ActivityThread.main(ActivityThread.java:7918)
E/AndroidRuntime(12444): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12444): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(12444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(12444): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(12444): 	at com.transistorsoft.locationmanager.service.AbstractService.start(Unknown Source:33)
E/AndroidRuntime(12444): 	at com.transistorsoft.locationmanager.service.LocationRequestService.onStartCommand(Unknown Source:1)
E/AndroidRuntime(12444): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
E/AndroidRuntime(12444): 	... 9 more
E/TSLocationManager(12444): [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
E/TSLocationManager(12444):   ‼️  Uncaught Exception: Unable to start service com.transistorsoft.locationmanager.service.LocationRequestService@6f26fc5 with Intent { act=start cmp=com.cargotel.driverwireless/com.transistorsoft.locationmanager.service.LocationRequestService (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/TSLocationManager(12444): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Background Location Permission","message":"CargoTel collects location data to enable dealer notifications and delivery estimates, even when the app is closed or not in use.","positiveAction":"OK","negativeAction":"Cancel"},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":1,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
E/TSLocationManager(12444): java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.LocationRequestService@6f26fc5 with Intent { act=start cmp=com.cargotel.driverwireless/com.transistorsoft.locationmanager.service.LocationRequestService (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/TSLocationManager(12444): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4673)
E/TSLocationManager(12444): 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/TSLocationManager(12444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
E/TSLocationManager(12444): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/TSLocationManager(12444): 	at android.os.Looper.loopOnce(Looper.java:201)
E/TSLocationManager(12444): 	at android.os.Looper.loop(Looper.java:288)
E/TSLocationManager(12444): 	at android.app.ActivityThread.main(ActivityThread.java:7918)
E/TSLocationManager(12444): 	at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager(12444): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/TSLocationManager(12444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/TSLocationManager(12444): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/TSLocationManager(12444): 	at com.transistorsoft.locationmanager.service.AbstractService.start(Unknown Source:33)
E/TSLocationManager(12444): 	at com.transistorsoft.locationmanager.service.LocationRequestService.onStartCommand(Unknown Source:1)
E/TSLocationManager(12444): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
E/TSLocationManager(12444): 	... 9 common frames omitted
I/Process (12444): Sending signal. PID: 12444 SIG: 9
Lost connection to device.
```

</details>

after update to android api level 34, the app crashes on startup.

also, initially, after upgrading to the new build tools, the app would not even compile. so, based on the error messages, i had to make this change:

file: android/app/src/main/AndroidManifest.xml

original:

<service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />

edited to:

<service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location"
tools:replace="android:foregroundServiceType" />

**Comment by allenbrunson** [comment]
ugh, somehow some of my edits got cut out. i had to change this file:

file: android/app/src/main/AndroidManifest.xml

from this: <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />

to this: <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location"
tools:replace="android:foregroundServiceType" />

**Comment by allenbrunson** [comment]
okay, twice now, this editor filters out xml i post in comments or the issue itself. i give up!

**Comment by christocracy** [comment]
Learn to [syntax highlight multi line code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) with triple-backticks.

**Comment by christocracy** [comment]
If you have `<service anroid="com.transistorsoft...." />` entries in your `AndroidManifest.xml`, **DELETE THEM**.

Version [__`4.5.0`__ instructed you to do so](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#450--2022-04-29).

<img width="1056" alt="Screenshot 2023-08-18 at 3 58 14 PM (1)" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/141a2d4d-93fb-4992-a93a-d1379963303c">

**Comment by allenbrunson** [comment]
yep, i did have service entries in there. one of them was what i had to edit to get it to compile. so okay, i removed both of them. still compiles, but on running the app on my pixel 5, i get the exact same crash again.

**Comment by christocracy** [comment]
I look at it.

**Comment by allenbrunson** [comment]
you know what, my whole project setup for this app is ancient. dates back several years. something i've tried in the past, to solve errors of this type, is to re-create the whole android studio project from scratch, then go through the setup steps for all my plugins. i will try that, but it will take me quite awhile. at least a whole day.

**Comment by christocracy** [comment]
I’m sure it’s a big in the plug-in.  This version had some major refactoring.  It’s an easy bug to fix.

But it’s always a good idea to do an app refresh,

**Comment by allenbrunson** [comment]
okay, good to know! i will wait for the next version then.

**Comment by christocracy** [comment]
>     logLevel:bg.Config.LOG_LEVEL_ERROR,

I need more information:  When you have a crash, the first thing to do is use `LOG_LEVEL_VERBOSE`.

**Comment by christocracy** [comment]
Also, show me all the code where you're accessing `BackgroundGeolocation`.

**Comment by allenbrunson** [comment]
i built a new android studio project from scratch, trying to create a minimal app that would demonstrate the problem. and wouldn't you know it, this version works fine. (heh!)

while i was setting that up, i noticed a bunch of things that are outdated in my current android project: slightly older versions of libraries, and so on. so i guess i will have to go with my original troubleshooting technique: rebuild my android studio project from scratch, performing plug-in installation instructions along the way. this will take me at least a day or two. if that fixes the problem, i will come back to this issue and mark it as resolved.

while i was building that example app, though, i think i found some of your setup instructions that are outdated. in android/app/build.gradle, you specify these two lines:

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

the second line does not work, and causes the build to fail. if i remove it, the build completes successfully, and my demo app does what it is supposed to do.

(that line does in fact exist in my older, defective android studio project, and it does not cause the build to crash. i hate gradle way too much to try to figure out what is going on there. i will just blow it away and start over.)

**Comment by christocracy** [comment]
> in android/app/build.gradle, you specify these two lines:

>apply plugin: 'com.android.application'
apply from: >"$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

Show me the exact link where this is specified.

**Comment by allenbrunson** [comment]
the page is here:

https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md

i downloaded the file: lines 72 and 73

**Comment by allenbrunson** [comment]
if you create a new android project with the current version of android studio, then those two lines do not exist! your installation file says to insert your lines after the ones that, as of a few releases ago, do not exist. i know gradle to be a cranky unpleasant beast, so just putting the lines wherever is liable to get me an impenetrable error message. so your instructions are, at best, misleading.

**Comment by christocracy** [comment]
Every has at its top:

```
apply plugin: 'com.android.application'
```

**Comment by christocracy** [comment]
Your mistake, I think, was incorrectly adding lines not marked in green.
