### ISSUE TITLE
[Question] What tasks can be performed within a headless task?

### ISSUE THREAD

**Issue by paul019** [transistorsoft/flutter_background_geolocation#1104]
I wondered what type of tasks can be performed within a callback in the background, especially within a headless task on Android. In the documentation, it says:

> Within your `callback`, you're free to interact with the complete `BackgroundGeolocation` API.

I also understand that a headless task, logically, cannot access the app's UI. But what about other parts of the app? In particular, I was wondering whether I can access my own SQFlite database using the plugin [`sqflite`](https://github.com/tekartik/sqflite). My goal is to perform light database operations.

Thank you in advance and thank you for the amazing plugin!

**Comment by christocracy** [comment]
> My goal is to perform light database operations.

Of course you can

**Comment by paul019** [comment]
Is there a limitation to how extensive a headless task can be before it gets canceled by the OS? If so, is this limitation best determined by trial and error or is there some kind of "good measure" to follow?

**Comment by christocracy** [comment]
Yes, there are limits.  See api docs .startBackgroundTask.  Do your work inside one of those.

**Comment by paul019** [comment]
Thank you! Does this only work for iOS as suggested by the documentation?

> Sends a signal to iOS that you wish to perform a long-running task.

**Comment by christocracy** [comment]
No, the docs are old and need to be updated.

Android invokes a [WorkManager Task](https://developer.android.com/topic/libraries/architecture/workmanager)

**Comment by paul019** [comment]
Thank you!
