### ISSUE TITLE
Disable the Alert if "While using the App"

### ISSUE THREAD

**Issue by csarigumba** [transistorsoft/flutter_background_geolocation#1105]
Is there a way to disable the alert if location service is already "While using the App"?
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/15829299/d89e8dfb-2576-42f1-a492-cc210aa5b443)

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationRequest` and `Config.disableLocationAuthorizationAlert`.
