### ISSUE TITLE
Some android devices getting crash with message "Reply already submitted"

### ISSUE THREAD

**Issue by ndasim** [transistorsoft/flutter_background_geolocation#1107]
Some of our clients are getting crashes during the location service start on Android, here is the stacktrace of crash:

ava.lang.IllegalStateException: Reply already submitted
    at vc.c$g.a(DartMessenger.java:4)
    at id.l$a$a.a
    at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$25.onStart
    at com.transistorsoft.locationmanager.util.BackgroundTaskManager$Task$a.run
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

## Your Environment
* Plugin version: 4.11.1
* Platform: Android
* OS version: 13
* Device: SM-A326B, SM-A235F, MAR-LX1M <-- Those are the device models as far as we know
* Flutter info (`flutter doctor`):
```
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.4, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ndasim/fvm/versions/3.10.4. Consider adding /Users/ndasim/fvm/versions/3.10.4/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.registerHeadlessTask(backgroundGeolocationHeadlessTask);

    ////
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
      // locationAuthorizationAlert: {
      //   'titleWhenNotEnabled': 'Background location not enabled',
      //   'titleWhenOff': "Please enable your device's Positioning Service",
      //   'instructions': "This lets you use location when your application works "
      //       "in the background otherwise you will not be able to location features in background",
      //   'cancelButton': 'Cancel',
      //   'settingsButton': 'Settings'
      // },
      disableLocationAuthorizationAlert: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stationaryRadius: 0,
      activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION,
      locationUpdateInterval: 3 * 1000,
      //fastestLocationUpdateInterval: 3*1000,
      allowIdenticalLocations: true,
      heartbeatInterval: 60,
      enableHeadless: true,
      stopOnTerminate: true,
      preventSuspend: true,
      startOnBoot: true,
      debug: false,
      isMoving: true,
      logLevel: bg.Config.LOG_LEVEL_WARNING,
      activityRecognitionInterval: 2,
    )).then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start().catchError(onFailure);
        bg.BackgroundGeolocation.startBackgroundTask().catchError(onFailure);
      }
    });

    Future.delayed(gpsFeedbackAfterInitiateDuration).then((value) async {
      notifyLocation(await bg.BackgroundGeolocation.getCurrentPosition(samples: 1, timeout: 30, maximumAge: 10 * 1000).catchError(onFailure));
      try {
        if ((await bg.BackgroundGeolocation.state).enabled) {
          bg.BackgroundGeolocation.changePace(true).catchError(onFailure);
        }
      } catch (e) {
        _info("LocationProvider", "changePace failed");
      }
    });
```

## Expected Behavior
Must start seamless

## Actual Behavior
Crashing on some devices

## Steps to Reproduce
We are not clear on which scenario it appears in, but according to my search your method channel sending `.success` twice, I guess. [Stackoverflow result -->](https://stackoverflow.com/a/65677972)

## Context
Application trying to start background location service

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
java.lang.IllegalStateException: Reply already submitted
    at vc.c$g.a(DartMessenger.java:4)
    at id.l$a$a.a
    at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$25.onStart
    at com.transistorsoft.locationmanager.util.BackgroundTaskManager$Task$a.run
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

</details>

**Comment by ndasim** [comment]
fyi: @mfurkanyuceal

**Comment by ndasim** [comment]
I think this line needs some duplication check, somehow it triggered twice:

https://github.com/transistorsoft/flutter_background_geolocation/blob/233de81f2d1858177cef941638b9efc58c36945a/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/BackgroundGeolocationModule.java#L767

**Comment by christocracy** [comment]
Your code is *very* odd and unusual.

What are you hoping to achieve by this?

```dart
bg.BackgroundGeolocation.startBackgroundTask().catchError(onFailure);
```

You are not using this method correctly.  I suggest you re-read the API docs.  For this method it's **CRUCIAL AND REQUIRED** to receive the given `taskId` and signal to the OS when your task is complete, by calling `.stopBackgroundTask(taskId)` -- If you do not, the OS **will punish** your app for poor behaviour.


And what is this weirdness with delays:

```
Future.delayed(gpsFeedbackAfterInitiateDuration).then((value) async {
      notifyLocation(await bg.BackgroundGeolocation.getCurrentPosition(samples: 1, timeout: 30, maximumAge: 10 * 1000).catchError(onFailure));
      try {
        if ((await bg.BackgroundGeolocation.state).enabled) {
          bg.BackgroundGeolocation.changePace(true).catchError(onFailure);
        }
      } catch (e) {
        _info("LocationProvider", "changePace failed");
      }
    });
```

The plugin has an `onToggleEnabled` event-listener you can subscribe-to for learning when the `State.enabled` was toggled.

**Comment by christocracy** [comment]
>I think this line needs some duplication check, somehow it triggered twice:

No.  The underling issue is within the native SDK, not the Flutter layer.  There is some issue exposed with your incorrect and untested usage of the API.  

However, the `BackgroundTaskManager` in the SDK has been refactored in `4.12.x`, so the issue may be moot.  I will add a boolean flag to prevent this issue until I figure out how you managed to do that.

```java
public void start(Callback completionHandler) {
            if (mStarted) { // <----------------- [ADDED]:  Check if this Task has already been started.
                TSLog.warn(TSLog.warn("Calling BackgroundTaskManager.Task.start on an already started task was IGNORED"));
                return;
            }

            TSLog.logger.info(TSLog.ICON_HOURGLASS + " startBackgroundTask: " + mId);
            mCompletionHandler = completionHandler;
            if (!mDisableTimeout) {
                startTimer();
            }
            BackgroundGeolocation.getUiHandler().post(() -> mCallback.onStart(mId));
        }
```

**Comment by ndasim** [comment]
Thank you for the explanation. Actually, we have been using this library for nearly 3 years, and in that period we faced some weird cases on several devices, especially on Chinese ones :D that's why we wanted to catch possible errors by calling .catchError(). For `taskId` part we become legacy I think. We will use it for sure, thank you. 

The timeout part is also very old actually, I'm not sure if was an onToggleEnabled API while we were implementing your library. It might be causing that weird case. 

Sorry for my misleading, but I need to tell you this crash started to happen nearly 2 weeks ago, as we watched from our monitoring tool. We did not change anything on that code and we did not change our Flutter version, some weirdo android stuff is happening again I guess. We became alerted by one of the Samsung device has started to crash in each launch, however, there are lots of devices using this implementation and rarely hit other devices.

A flag will definitely help us on that crash, please inform us after your fix. We will also apply your suggestion in our implementation.

**Comment by christocracy** [comment]
See the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#4122--2023-08-24)

And fix your .startBackgroundTask implementation.  It’s completely wrong.  .startBackgroundTask will never raise an exception and you must *always* accept the returner `taskId`.  Read the api docs.

**Comment by ndasim** [comment]
Thank you, We will follow your docs and confirm that issue is resolved in next releases
