### ISSUE TITLE
Flutter background geolocation creates sound in background when device is mooving ,how to close this sound when location is changing.

### ISSUE THREAD

**Issue by pawan14325** [transistorsoft/flutter_background_geolocation#1109]
Here is code in my main file-
by this code i got live location of user while user but it creates sound while user is moving,How to close this sound?

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:moover_driver2/utils/localisations/custom_widgets.dart';
import 'package:onesignal_flutter/onesignal_flutter.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;
import 'utils/app_pages.dart';
import 'utils/app_routes.dart';
import 'utils/localisations/app_colors.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GetStorage.init();

  runApp(const MyApp());
}

void configOneSignal() async {
  await OneSignal.shared.setAppId('ae590879-074f-4e51-872b-b2c665007075');
  OneSignal.shared.setNotificationOpenedHandler(
    (OSNotificationOpenedResult result) {
      Map<String, dynamic>? additionalData = result.notification.rawPayload;

      if (additionalData != null) {
        printData('Notification opened: $additionalData');
        if (additionalData.isNotEmpty) {
          var message = additionalData['title'];
          var content = additionalData['alert'];
          Get.toNamed(AppRoutes.notification);
        }
      } else {
        printData('No additional data found for the notification.');
      }
    },
  );
}

GetStorage getStorage = GetStorage();

late IO.Socket socket;
String? _currentLocation;
bool isMoving = false;
Timer? locationTimer;

Future<void> initSocket() async {
  try {
    socket = IO.io(
      "http://103.185.212.115:5000",
      <String, dynamic>{
        'transports': ['websocket'],
        'autoConnect': true,
      },
    );

    socket.onConnect((_) async {
      GetStorage.init();

      printData("Connected: ${socket.connected}");
      var userId = getStorage.read('id');
      var token = getStorage.read('token');
      printData("userId:$userId");
      printData("token:$token");

      if (socket != null && socket.connected) {
        // socket.emit('socket_data', locationData);
        printData("SOCKET CONNECTED ");
      }
    });

    socket.on('socket_data', (data) {
      printData("Received data from server: $data");
    });

    socket.onConnectError((error) {
      printData("ERROR: $error");
    });

    socket.connect();
  } catch (e, st) {
    print("ERROR: $e");
    print("STACKTRACE: $st");
  }
}

Future<void> sendData(
    {required dynamic latitude, required dynamic longitude}) async {
  var userId = getStorage.read('id');
  var token = getStorage.read('token');
  printData("userId:$userId");
  printData("token:$token");

  printData('Latitude: $latitude');
  printData('Longitude: $longitude');

  var locationData = {
    'latitude': latitude.toString(),
    'longitude': longitude.toString(),
    'userId': userId.toString(),
  };

  if (socket != null && socket.connected) {
    socket.emit('socket_data', locationData);
    printData("$locationData");
  }
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    configOneSignal();
    initSocket();
    _currentLocation = '';

    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      if (location.isMoving) {
        isMoving = true;
        if (locationTimer != null && locationTimer!.isActive) {
          locationTimer!.cancel();
        }
        locationTimer = Timer.periodic(const Duration(minutes: 5), (_) {
          bg.BackgroundGeolocation.getCurrentPosition(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            persist: true,
            samples: 1,
          ).then((bg.Location location) {
            _onLocation(location);
          });
        });
      } else {
        isMoving = false;
        if (locationTimer != null && locationTimer!.isActive) {
          locationTimer!.cancel();
        }
        locationTimer = Timer.periodic(const Duration(minutes: 5), (_) {
          bg.BackgroundGeolocation.getCurrentPosition(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            persist: true,
            samples: 1,
          ).then((bg.Location location) {
            _onLocation(location);
          });
        });
      }
    });

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5000,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      notification: bg.Notification(
        title: "Moover Driver",
        text: "Keep Moover Driver in background",
      ),
    )).then((bg.State state) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        printData('[start] success $state');
      });
    });
  }

  void _onLocation(bg.Location location) {
    try {
      printData('[location] - $location');
      String currentLocation =
          'Lat: ${location.coords.latitude}, Lng: ${location.coords.longitude}';
      setState(() {
        _currentLocation = currentLocation;
      });

      sendData(
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
      );
    } catch (e, st) {
      printData("ERROR : $e");
      printData("ST : $st");
    }
  }

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Moovers Driver',
      theme: ThemeData(
        fontFamily: "VisbyRoundCF",
        useMaterial3: false,
        primarySwatch: Colors.deepPurple,
        inputDecorationTheme: InputDecorationTheme(
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide(width: 1.5, color: Colors.grey.shade500),
          ),
          focusedBorder: OutlineInputBorder(
            borderSide: BorderSide(width: 1.5, color: AppColors.primaryVoilet),
          ),
        ),
      ),
      getPages: AppPages.route,
      initialRoute: AppPages.initialRoute,
    );
  }
}

**Comment by christocracy** [comment]
Please [learn to syntax highlight “fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by christocracy** [comment]
(Edit your post).

**Comment by christocracy** [comment]
Ignored issue template.  Failed to syntax highlight code.
