### ISSUE TITLE
Switching from wifi to cellular closes the app from background on example app

### ISSUE THREAD

**Issue by usama-yaway** [transistorsoft/flutter_background_geolocation#1110]
## Your Environment
* Plugin version: 4.12.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung Galaxy A53 5G 
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, 3.3.1, on macOS 13.4 22F66 darwin-arm, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
I downloaded the app from playstore. 
```

## Expected Behavior

If the app is in background and wifi goes away the app should not be removed from background.
## Actual Behavior

If the app is in background and wifi goes away the app is removed from background instantly.
## Steps to Reproduce

1. Connect to wifi
2. Open advanced app from example app
3. Put app to background
4. Turn off wifi
5. Example app is killed

## Context

So we are facing this issue in our app and have been trying multiple ways to resolve it with no success. Then we decided to test out your demo application and the same behaviour was reproduced. 
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
What makes you think the app is being killed?  

I do not experience this with the `/example` app in this repo running on my *Pixel 6 @ 14*.

Are you observing `$adb logcat` when you're performing these steps?

**Comment by christocracy** [comment]
And anyway, even if you are experiencing what you say, the plugin is not responsible for the *Application LIfe-cycle*.  The plugin does not have the power to terminate the app and it certainly does *not* have any kind of code such as `System.exit(0)` or any kind of `killProcess(pid)` method.

**Comment by christocracy** [comment]
I suggest you observe the raw, unfiltered `$ adb logcat` and scan for *Exceptions*.

**Comment by usama-yaway** [comment]
Hey @christocracy, thank you for responding so swiftly. 

I downloaded the example app from playstore and ran it on a one plus device as well as Samsung A53 5g on both devices it reproduced the same result. I didn't change any settings in the that application only enabled all the permissions that were prompted and turned on the location tracking from top right toggle. After going to the background the app was killed from memory. 

However, I will debug further in light of your suggestion above and share my findings with you.

**Comment by christocracy** [comment]
> app was killed from memory

What makes you think the app is being killed?

**Comment by usama-yaway** [comment]
Because as soon as I turn off the wifi it can see it go away from the open apps tile.

**Comment by christocracy** [comment]
If it were me, the first thing I’d do is observe what happens in `adb logcat` when that happens.
