### ISSUE TITLE
App Hangs on iOS

### ISSUE THREAD

**Issue by apackin** [transistorsoft/flutter_background_geolocation#1111]
## Your Environment
* Plugin version: flutter_background_geolocation 4.12.2
* Platform: iOS
* OS version: 16.6, 16.5.1, 16.5, etc
* Device manufacturer / model: All iPhones
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return bg.Config(
      transistorAuthorizationToken: token,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: _distanceFilter.toDouble(), // 10
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      // Android stuff
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: bg.PermissionRationale(
        title: '"Allow all the time" required for scoring',
        message:
            'Select "Allow all the time" in app settings to get points without opening the app.',
        positiveAction: 'Continue',
        negativeAction: 'Cancel',
      ),
      locationAuthorizationAlert: {
         // ...
      },
      logLevel: bg.Config.LOG_LEVEL_DEBUG,
    );
```

## Expected Behavior

App should not hang while loading

## Actual Behavior

App hangs intermittently when running `await BackgroundGeoLocationManager.create();` 

## Steps to Reproduce

 We're not totally sure, it's happening to almost every user at least once. Device often shows a low memory warning before hanging at this stage.

## Context

Use this plugin

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
[Error] App hanging for at least 2000 ms.
 libsystem_kernel    0x1c81aaca4  mach_msg2_trap
  libsystem_kernel    0x1c81bdb70  mach_msg2_internal
  libsystem_kernel    0x1c81bde48  mach_msg_overwrite
  libsystem_kernel    0x1c81ab1e4  mach_msg
  libdispatch         0x1906d7208  _dispatch_mach_send_and_wait_for_reply
  libdispatch         0x1906d7598  dispatch_mach_send_with_result_and_wait_for_reply
  libxpc              0x1e907c214  xpc_connection_send_message_with_reply_sync
  Foundation          0x183543f14  __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__
  Foundation          0x1834d72c0  -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]
  Foundation          0x1834d5c20  -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:arg3:]
  Foundation          0x1834d5b40  _NSXPCDistantObjectSimpleMessageSend3
  CoreLocation        0x194bff288  CLCopyTechnologiesInUse
  CoreLocation        0x194bfde8c  CLCopyTechnologiesInUse
  CoreLocation        0x194c27a9c  CLClientStopVehicleHeadingUpdates
  Runner              0x10364d25c  MLKITx_SRLRegistrySharedInstanceForProviders
  Runner              0x1036b7e04  MLKITx_SRLRegistrySharedInstanceForProviders
  libdispatch         0x1906ba31c  _dispatch_call_block_and_release
  libdispatch         0x1906bbea8  _dispatch_client_callout
  libdispatch         0x1906ca6a0  _dispatch_main_queue_drain
  libdispatch         0x1906ca2f0  _dispatch_main_queue_callback_4CF
  CoreFoundation      0x189283c24  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x18926555c  __CFRunLoopRun
  CoreFoundation      0x18926a3e8  CFRunLoopRunSpecific
  GraphicsServices    0x1c4780358  GSEventRunModal
  UIKitCore           0x18b5f6f54  -[UIApplication _run]
  UIKitCore           0x18b5f6bb8  UIApplicationMain
  Runner              0x10280f834  <redacted>
```

</details>

**Comment by christocracy** [comment]
There is no evidence from your stacktrace that the plug-in is responsible.

the plug-ins classes are prefixed with `TS` (for Transistor Software), eg: `TSLocationManager`.

this plugin is very careful to perform its work in background-threads — it does not block the UI thread and it doesn’t consume memory.

**Comment by christocracy** [comment]
I suggest you attempt to create a simple HelloWorld app which reproduces the issue.

**Comment by christocracy** [comment]
What your stacktrace *does* seem to reference is [`MLKit`](https://developers.google.com/ml-kit), which this plug-in has nothing to do with.

**Comment by apackin** [comment]
Thanks for the quick reply! I thought the `CoreLocation` calls were from this package because it's the only one I have related to location. Thanks for the link to `MLKIT` I'll dig in on that path.

**Comment by christocracy** [comment]
```
CoreLocation        0x194c27a9c  CLClientStopVehicleHeadingUpdates
```

This would imply that some *other* plugin has initiated [`CLLocationManager startUpdatingHeading`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620558-startupdatingheading?language=objc), / [`CLLocationManager stopUpdatingHeading`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620569-stopupdatingheading?language=objc), which the plugin does not use.  The plugin gets it `heading` information provided to it with each recorded [`CLLocation.course`](https://developer.apple.com/documentation/corelocation/cllocation/1423832-course?language=objc)

**Comment by apackin** [comment]
I see. Thanks for the help!
