### ISSUE TITLE
MQTT suport

### ISSUE THREAD

**Issue by omejiasq** [transistorsoft/flutter_background_geolocation#1112]
## Your Environment
* Plugin version:4.12.2
* Platform: iOS or Android: Android 12
* OS version:
* Device manufacturer / model:Samsung galaxy S21 Ulta
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
I don`t the code for integrate MQTT
```

## Expected Behavior

Being able to send information by MQTT protocol to the server since this allows scaling to hundreds of thousands of requests, which the HTTP method that the plugin uses today does not allow more than 5 thousand requests simultaneously in a scalable and easy way
## Actual Behavior

I can`t send data by MQTT protocol
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
My development rate is $300/hour.  Let me know if you’re interested in an estimate.

**Comment by christocracy** [comment]
It’s probably ~40 hours @ $300/hour (for both iOS and Android)

**Comment by omejiasq** [comment]
and how many hours only for android?

**Comment by christocracy** [comment]
~30 hours for Android-only

**Comment by omejiasq** [comment]
Thank you Chris. I am a highly experienced programmer, would it be possible for me to make these adjustments in this plugin, and how complex would it be to do it myself or what do I need?

**Comment by omejiasq** [comment]
Hi Chris, can you only tell me please f it is possible to make these adjustments, what do I need for this?

**Comment by christocracy** [comment]
> it is possible to make these adjustments, what do I need for this?

No, it is not possible.

**Comment by omejiasq** [comment]
Ok thank you.

**Comment by omejiasq** [comment]
1. Dear, to close my questions and this ticket, can you please tell me approximately how many simultaneous users you have had in your largest implementations using your flutter plugin, or if any of your clients have heard of having a large number of simultaneous users, how many have they had? they?
2. Has a client of yours asked you to use the MQTT protocol, and for a large implementation, for example, having more than 50 thousand simultaneous users, do you also think it is necessary to adjust your plugin to allow the use of the MQTT protocol?

Thank you very much for your important answers!

**Comment by christocracy** [comment]
1.  I have no idea.  I cannot tell you about any of my customers.
2. I've been doing this for over 9 years and MQTT has not been a popular request, so no:  I don't think it's necessary.  You're free to implement MQTT in your own dart code.

**Comment by omejiasq** [comment]
Thank you very much!!!
