### ISSUE TITLE
IncompatibleClassChangeError with com.google.android.gms.location.SettingsClient

### ISSUE THREAD

**Issue by utsav-savani** [transistorsoft/flutter_background_geolocation#1115]
**Environment**:
- Flutter version: 3.10.0 (Stable channel)
- Dart version: 3.0.0 (from /usr/local/Cellar/dart/3.0.0/libexec/bin/dart)
- Android SDK version: 33.0.2
- Xcode version: 14.3
- flutter_background_geolocation version: ^4.12.2
- Device details: (mention the device details where you are testing, e.g., Samsung Galaxy S21, Android 12)

**Problem**:
Encountering an `IncompatibleClassChangeError` when using the `flutter_background_geolocation` library. The specific error is:

```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
The application should fetch the location

## Actual Behavior
It is crashing and logs are attached in the Image.

## Steps to Reproduce

1. Run The application
2. As soon as it fetches location it crashes in Android

## Context

Trying to fetch the location
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/AndroidRuntime(10886): Process: io.fleetdesk.fleetmate, PID: 10886
E/AndroidRuntine (10886): java.lang.IncompatibleClassChangeError: Found interface con.google.android. gs. location. ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gns.location.Acti
vityRecognitionClient' appears in /data/app/~~X2LMgCeBQvBxAR16xipBgw==/ 10. fleetdesk. fleetnate-WED-LCAUELKVISUY2XVRVQ==/base. apk)

E/AndroidRuntine (10886) : at con.transistorsoft.xns.g. location. ActivityRecognitionClient. requestActivityUpdates (Unknown Source:56)
E/AndroidRuntine (10886): at con.transistorsoft.locationnanager. service. ActivityRecognitionService. start (Unknown Source:78)
E/AndroidRuntine (10886): at con.transistorsoft.locationnanager. service. TrackingService. start (Unknown Source:49)

E/AndroidRuntine (10886): at con.transistorsoft.locationnanager. adapter. Backgroundéeolocation$al. run(Unknown Source:139)
E/AndroidRuntine (10886) : at java.util.concurrent. ThreadPoolExecutor. runlorker (ThreadPoolExecutor. java: 1137)

E/AndroidRuntine (10886): at java.util.concurrent. ThreadPoolExecutor$horker. run(ThreadPoolExecutor. java:637)

E/AndroidRuntine (10886) : at java.lang.Thread.run(Thread. java:1012)
E/AndroidRuntine (10886): FATAL EXCEPTION: pool-5-thread-3

E/AndroidRuntine (10886): Process: io.fleetdesk.fleetnate, PID: 10886

E/AndroidRuntine (10886): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gns. location. ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gns.location.Acti
vityRecognitionClient' appears in /data/app/~~X2LHgCeBQvBxaR16xipBaw==/ io. Fleetdesk. fleetnate-WED-1cAUELkVISUY2XVRVQ==/base. apk)

E/AndroidRuntine (10886) : at con.transistorsoft.xns.g. location. ActivityRecognitionClient. requestActivityUpdates (Unknown Source:58)
E/AndroidRuntine (10886) : at con. transistorsoft.locationnanager. service. ActivityRecognitionService. start (Unknown Source:78)
E/AndroidRuntine (10886): at con.transistorsoft.locationnanager. service. TrackingService. start (Unknown Source:49)

2 E/AndroidRuntime (10886): at com. transistorsoft.locationmanager.adapter.BackgroundGeolocation$al. run(Unknown Source:139)

: E/AndroidRuntine (10886) : at java.util.concurrent. ThreadPoolExecutor. runliorker (ThreadPool Executor. java: 1137)
E/AndroidRuntine (10886): at java.util.concurrent. ThreadPoolExecutor$liorker run (ThreadPoolExecutor. java:637)

N £/AndroidRuntine (10886): at java.lang.Thread.run(Thread. java:1812)
![WhatsApp Image 2023-09-05 at 22 56 15](https://github.com/transistorsoft/flutter_background_geolocation/assets/11181921/7fa8de80-4fc5-4537-bb3a-333c7820fe0e)

```

</details>

**Comment by utsav-savani** [comment]
Here is my android/build.gradle

buildscript {
    ext.kotlin_version = '1.7.10'

       ext {
               compileSdkVersion   = 33                // or higher
               targetSdkVersion    = 31                // or higher
               minSdkVersion       =21
               appCompatVersion    = "1.4.2"           // or higher
               playServicesLocationVersion = "20.0.0"  // or higher
           }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//        implementation "com.google.android.gms:play-services-location:21.0.1"
//        implementation "androidx.appcompat:appcompat:1.4.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()

        maven {
           // [required] flutter_background_geolocation
           url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven { url 'https://developer.huawei.com/repo/' }
        maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
        }
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:21.0.1"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Duplicate #933

**Comment by utsav-savani** [comment]
But your update says v21 will work with 4.9.0 and I am using 4.12.3, so please tell me why it still crashes?

**Comment by christocracy** [comment]
Then you have **some other** plug-in that is still importing v20.

this issue is caused by a breaking change in play-services.  All plug-in must be aligned to the same version.  When one imports v20 and another v21+, everything breaks.

**Comment by christocracy** [comment]
The answer is in your `./gradlew app:dependencies` tree

**Comment by utsav-savani** [comment]
So in the tree it shows this

+--- project :poly_geofence_service
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 -> 1.7.20 (*)
|    +--- com.google.android.gms:play-services-location:18.0.0 -> 21.0.1 (*)

This is also 21.0.1 or does this have the error?

**Comment by utsav-savani** [comment]
The version is same then why does it still give error @christocracy ?

+--- project :poly_geofence_service
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10 -> 1.7.20 (*)
|    +--- com.google.android.gms:play-services-location:21.0.1 (*)


+--- project :fl_location
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10 -> 1.7.20 (*)
|    +--- com.google.android.gms:play-services-location:21.0.1


+--- project :flutter_background_geolocation
|    +--- com.transistorsoft:tslocationmanager:+ -> 3.4.4
|    +--- org.greenrobot:eventbus:3.3.1
|    |    \--- org.greenrobot:eventbus-java:3.3.1
|    +--- com.squareup.okhttp3:okhttp:3.12.13 (*)
|    +--- com.github.tony19:logback-android:3.0.0
|    +--- org.slf4j:slf4j-api:2.0.7
|    +--- io.github.nishkarsh:android-permissions:2.1.6
|    |    +--- androidx.appcompat:appcompat:1.4.1 -> 1.4.2 (*)
|    |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.1.0 (*)
|    |    \--- org.parceler:parceler-api:1.1.12
|    +--- com.google.android.gms:play-services-location:21.0.1 (*)

**Comment by christocracy** [comment]
The plugin [poly_geofence_service](https://github.com/Dev-hwang/poly_geofence_service/blob/3606276d773ba60904e86ca06d5221c5eae1dbfe/android/build.gradle#L47) is **poorly behaved** with a **hard-coded `play-services:location` version, unlike `background_geolocation`, [which is configurable](https://github.com/transistorsoft/flutter_background_geolocation/blob/809415ba21b04892848c3b9ef65e919d8f7a66d1/android/build.gradle#L85) via `ext.playServicesLocationVersion`.  

I suggest you update your version of this "`poly_geofence_services`", whose hard-coded version seems to be at `20.0.1` now.  I suggest you post an issue over there and ask them to implement reading the version from `ext.playServicesLocationVersion` as done here for the last 4 years.
