### ISSUE TITLE
Add Config option to set limit on how many geofences are actively monitored by OS

### ISSUE THREAD

**Issue by dale-lakes** [transistorsoft/flutter_background_geolocation#1116]
## Your Environment
* Plugin version: 4.12.2
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
BackgroundGeolocation.ready(
  Config(
    notification: Notification(
      title: "VeriFi Pro is running",
      text: "Auto-connecting you to VeriFied Wi-Fi",
      smallIcon: "drawable/app_icon",
      sticky: true,
    ),
    reset: true,
    logLevel:
        (kDebugMode) ? Config.LOG_LEVEL_INFO : Config.LOG_LEVEL_ERROR,
    desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
    enableHeadless: true,
    startOnBoot: true,
    stopOnTerminate: false,
    // geofenceMonitorLimit: 50 <-- I'd like for this option to exist

  ),
).then((State state) async {
  await BackgroundGeolocation.start();
});

```

## Expected Behavior

A Config option to limit how many geofences are actively monitored by the OS. The max number of active geofences is 20 on iOS and 100 on Android. I would like to set a specific limit lower than or equal to the platform max rather than always defaulting to the platform max. The platform max should be the default.

## Actual Behavior

There is no way to configure the plugin to monitor less than the platform max number of geofences.

## Steps to Reproduce
N/A

## Context

My app is associating Wi-Fi access points using the Android Wi-Fi Suggestions API with geofences. The max number of Wi-Fi access points that can be added via this API on Android is 50, which is less than the max number of geofences, 100. I'd like to set a geofence monitoring limit of 50 rather than 100 in order to ensure that, when the geofences change, I always have the 50 nearest access points. Without this limit, it becomes very difficult to add / remove the 50 closest Wi-Fi suggestions without essentially having to query all geofences, sort, and reduce from 100 to 50 based on distance.

## Debug logs
 N/A

</details>

**Comment by christocracy** [comment]
I’m well aware of the limits for both Android and iOS.  This plugin has an “infinite geofencing” implementation when you go over the limit.  See api docs Config.geofenceProximityRadius for more information.

**Comment by christocracy** [comment]
> to add / remove the 50 closest Wi-Fi suggestions without essentially having to query all geofences, sort, and reduce

this is what the plug-in’s “infinite geofencing system” does.

**Comment by dale-lakes** [comment]
I understand the "infinite geofencing" system (which is awesome!). My issue/request is being able to configure the plugin to set a lower limit rather than the default limit of 20/100.

For example, if I add 500 geofences, only 100 of the 500 will be actively monitored by Android. I'd like to have only 50 of the 500 monitored at a time rather than 100. Then, as the infinite geofencing system adds / removes them on demand, the total number monitored would never exceed 50 (or whatever value gets configured as the max value).

Is this request reasonable?

**Comment by christocracy** [comment]
It’s easy enough.  It will have to have two separate values for ios and android then.  Or as a percentage?

**Comment by dale-lakes** [comment]
Yes, two separate values would be great!

**Comment by christocracy** [comment]
I think it will be called `maxMonitoredGeofences`

**Comment by christocracy** [comment]
Is this supposed to kick-in only when you exceed the platform maximum (eg 100 for Android)?

Eg. If you only have a total of 99 geofences, is `maxMonitoredGeofences: 50` supposed to be respected?  Or is it only respected when you exceed the platform maximum?

**Comment by dale-lakes** [comment]
It should still be respected even if the total is less than the platform maximum.

So if I have 50 geofences and set `maxMonitoredGeofences: 40`, then only 40 of the 50 are monitored by the OS, even though Android supports 100.

**Comment by christocracy** [comment]
> Shouldn't need to have two separate values

Yea, that’s where I’m going.  Supporting separate iOS/Android config would be ugly.

**Comment by christocracy** [comment]
And if you provide 60 with `maxMonitoredGeofences: 50`, the plug-in’s infinite-geofencing is going to kick-in and periodically run its geospatial query to activate the closest 50 of 60.

**Comment by dale-lakes** [comment]
That's perfect. Thanks again!

**Comment by christocracy** [comment]
I took a crack at this.  I haven't tested it *at all*, but logically it seems pretty simple with very few modifications.  It might *"just work"*

Give it a shot in the branch `maxMonitoredGeofences`:

:file_folder `pubspec.yaml`:
```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: maxMonitoredGeofences
```

**Comment by dale-lakes** [comment]
Great! I'll take it for a spin this weekend.

**Comment by dale-lakes** [comment]
I used the `maxMonitoredGeofences` branch for the past couple weeks, and haven't seen any issues or errors so far. Sorry if you were waiting on me to give a thumbs up before releasing.

**Comment by christocracy** [comment]
I believe this is merged to master and released,

**Comment by dale-lakes** [comment]
Oh yep, it is. Sorry didn't see it in the changelog, but I see the new Config parameter is in the api reference.

thank you!
