### ISSUE TITLE
How can I send location information to an external API ? 

### ISSUE THREAD

**Issue by mthahas** [transistorsoft/flutter_background_geolocation#1117]
How can I send location information to an external API ? 

## Your Environment
* Plugin version:
* 4.11.1
* Platform: iOS and Android
* OS version: 13
* Device manufacturer / model: Realme 11x
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
          url: apiURL,
          autoSync: true,
          autoSyncThreshold: 5,
          batchSync: true,
          maxBatchSize: 50,
          headers: {
            "Content-Type": "application/json",
            'Authorization': "Bearer $valueToken",
          },
          params: {"category_id": 2, "lat": 50, "lng": 8},
          extras: {"route_id": 8675309},
          locationsOrderDirection: "DESC",
          maxDaysToPersist: 14,
          heartbeatInterval: 60,
          //distanceFilter: 1,
          startOnBoot: true,
          debug: true,
          stopOnTerminate: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE))
      .then((bg.State state) {
    print("Before start");

    if (!state.enabled) {
      bg.BackgroundGeolocation.start();
    }
    print('after start success: ${state}');
  });
```

## Expected Behavior

I Want to send latitude and longitude to an external API.
From my code I want to replace lat and lng  from params
 params: {"category_id": 2, "lat": 50, "lng": 8},

## Actual Behavior

I dont' know how is this possible.

## Steps to Reproduce

1. N/A
2. N/A
3. N/A
4. N/A

## Context

I want to track the location from the background

## Debug logs

<details>
	<summary>Nothing</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Nothing
```

</details>

**Comment by christocracy** [comment]
See api docs Config.locationTemplate,  also see “HTTP guide” linked there
