### ISSUE TITLE
 location rejected 

### ISSUE THREAD

**Issue by jhonureta** [transistorsoft/flutter_background_geolocation#1118]
## Your Environment
* Plugin version:  flutter_background_geolocation: '^4.8.1'
* Platform: iOS or Android: Android
* OS version: 13
* Device manufacturer / model: Nexus

``` <!-- syntax-highligting:  DO NOT REMOVE -->
 [c.t.l.s.LocationRequestService handleLocationResult]
I/TSLocationManager( 3442): ╔═════════════════════════════════════════════
I/TSLocationManager( 3442): ║ getCurrentPosition LocationResult: 3
I/TSLocationManager( 3442): ╠═════════════════════════════════════════════
I/TSLocationManager( 3442): ╟─ 📍  Location[fused -0.249390,-79.186086 hAcc=13.712 et=+4h35m24s677ms alt=0.0 vAcc=0.5 vel=4.542043 sAcc=0.5 bear=90.0 bAcc=30.0], age: 11ms, time: 1694657975458

</details>
The location rejected me
```

![](https://github.com/transistorsoft/flutter_background_geolocation/assets/41515177/4a53adb7-d0be-4a5a-b757-2ea5661684a4)

**Comment by christocracy** [comment]
Do you have a question about something?

**Comment by jhonureta** [comment]
For Android 12 or 13, the location is not working, maybe do you know what it could be?

**Comment by christocracy** [comment]
Do you have something from the logs you'd like to ask about?

>'^4.8.1'

Have you checked the CHANGELOG to see what the latest version is?

**Comment by jhonureta** [comment]
You see, the problem is that when you run the application on Android 13 when you start it, it turns off and it is no longer possible to obtain the location. This is my log: D/EGL_emulation(10104): app_time_stats: avg=201.02ms min=1.07ms max=3891.17ms count=20
D/TSLocationManager(10104): [c.t.l.service.AbstractService b]
D/TSLocationManager(10104):   🎾  STOP [LocationRequestService startId: 4, eventCount: 1]
D/TSLocationManager(10104): [c.t.l.service.AbstractService a]
D/TSLocationManager(10104):   ⚙️︎   FINISH [LocationRequestService startId: 4, eventCount: 0, sticky: false]
D/TSLocationManager(10104): [c.t.l.service.AbstractService f]
D/TSLocationManager(10104):   ⚙️︎  LocationRequestService.stopSelfResult(4): true
D/TSLocationManager(10104): [c.t.l.service.AbstractService onDestroy]
D/TSLocationManager(10104):   🔴  LocationRequestService stopped
V/MediaPlayer(10104): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10104): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(10104): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10104): cleanDrmObj: mDrmObj=null mDrmSessionId=null
Reloaded 1 of 2324 libraries in 1,972ms (compile: 187 ms, reload: 921 ms, reassemble: 573 ms).
I/flutter (10104): null
D/EGL_emulation(10104): app_time_stats: avg=263523.38ms min=263523.38ms max=263523.38ms count=1

**Comment by christocracy** [comment]
That is a totally normal set of logs without any context.

Do you know this plugin's *Philosophy of Operation*?  Have you read the Wiki about it?  Have you tried going outside for a walk and listening to the plugin's debug SoundFX?  The plugin tracks when the device is *MOVING*.  It **doesn't** track when the device is sitting stationary.

**Comment by jhonureta** [comment]
I understand it, but how can I detect it when the movement starts? When I put the emulator in no motion and then start the movement, it does not detect it, it comes out as stopped, but if I start with the emulator in motion, it shows the latitude and longitude

**Comment by christocracy** [comment]
>When I put the emulator

You cannot experience the true behaviour of the motion-based tracking SDK *in the simulator*.  You must go outside and actually *move* to cause action in the accelerometer, gyroscope and magnetometer as well as trigger a geofence around the last known position.

I do not use emulators *at all*.

**Comment by christocracy** [comment]
You can manually toggle the plugin into the moving state by calling `.changePace(true)`.  This is the same method the plugin calls *upon itself* when movement is detected.

**Comment by jhonureta** [comment]
@override
  void initState() {
    super.initState();

    _isMoving = false;
    _enabled = false;
    _content = '';
    _motionActivity = 'UNKNOWN';
    _odometer = '0';
    //_getLocation()
    variablesInicio();
    _locationClient.init();

    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true,
        
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving!;
      });
    });

    

    //INICIAR LOCALIZACION
    _onClickGetCurrentPosition(true);
  }




void _onClickGetCurrentPosition(enabled) {
    
    if (enabled) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving!;
        });
      });
    } else {
      bg.BackgroundGeolocation.stop().then((bg.State state) {
        print('[stop] success: $state');
        // Reset odometer.
        bg.BackgroundGeolocation.setOdometer(0.0);

        setState(() {
          _odometer = '0.0';
          _enabled = state.enabled;
          _isMoving = state.isMoving!;
        });
      });
    }
  }
  


void _onLocation(bg.Location location) async {
    final socketService = Provider.of<SocketService>(context, listen: false);
    String ltd = location.coords.latitude.toString() +
        "," +
        location.coords.longitude.toString();
    SharedPreferences prefs = await SharedPreferences.getInstance();
    socketService.emit("chatmessage", "${prefs.getString("id")},$ltd");
  }

  void _onMotionChange(bg.Location location) {
    print('[motionchange] - $location');
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[activitychange] - $event');
    setState(() {
      _motionActivity = event.activity;
    });
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    print('$event');

    setState(() {
      _content = encoder.convert(event.toMap());
      print(_content);
    });
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    print('$event');
  }



In what part of the code? The one I show you is taken from the example you have in the repository.

**Comment by christocracy** [comment]
After calling `.start()`, you are free to call `.changePace(true)` at any time.

I suggest you install the `/example` app in this repo onto your device.  You do not need to look at the code.  Once launched, select the *Advanced App*.

- The toggle button on top-right toolbar calls `.start()` / `.stop()`.
- The `[ > ]` / `[ || ]` button on bottom-right toolbar calls `.changePace(state)`

It's like a music player.  You can't start playing music (`.changePace(false)`) until the power is on (`.start()`).

![Screenshot_20230914-113457](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/a7db0f90-a86b-4dfc-8865-84f08bb68a8c)
