### ISSUE TITLE
Captures the device model and version of the device and version of the mobile operating system

### ISSUE THREAD

**Issue by omejiasq** [transistorsoft/flutter_background_geolocation#1120]
## Your Environment
* Plugin version:4.12.3
* Platform: iOS or Android:13
* OS version:
* Device manufacturer / model:Samsung galaxy S21 Ulta
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

How can I capture with this plugin the smartphone model that I see in the plugin demo it is obtained?
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
There exist other plug-ins specializing in that sort of stuff but I think there might be an api here that returns what you want if you simply search the api docs for the word “device”.
