### ISSUE TITLE
Custom Authentication Header is not set in the requests

### ISSUE THREAD

**Issue by hansvn** [transistorsoft/flutter_background_geolocation#1121]
## Your Environment
* Plugin version: 4.12.3
* Platform: iOS and Android
* OS version: iOS 16
* Device manufacturer / model: Apple
* Flutter info (`flutter doctor`): 
```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.4.1 22F770820d darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```
* Plugin config:
```dart 
bg.BackgroundGeolocation.setConfig(bg.Config(
  headers: {
    HttpHeaders.acceptHeader: "application/json",
    HttpHeaders.authorizationHeader: 'Bearer $token'
  },
  autoSync: true,
))
```

## Expected Behavior
I'm expecting the authorization header to be added to the request, so the requests are authenticated.

## Actual Behavior
I'm trying to sync location updates to our back end service in order to look for POIs, it looks like the authorization header is omitted from the POST requests resulting in a 401 response (I checked the full requests on the backend service).
I've tried to use authorization entry in the Config too like this:
```
authorization: Authorization(
  strategy: "JWT",
  accessToken: token,
),
```
but unless I add some noise to the value (like `accessToken: "authToken:$token"`) the authorization header is stripped from the request too (not using actual jwt tokens so they might be validated by the package first).

## Steps to Reproduce
1. Set up background location with custom authorization header
2. Start the service
3. Let the app make requests in the background
4. See the requests fail as the authentication header is not attached on the request

**Comment by christocracy** [comment]
When the plug-in boots, it’s State to logcat.

what does the State look like in logcat?

**Comment by amarchenko25** [comment]
Hi @christocracy, I have faced with the same issue,
Seems like the issue is related to the **bg.BackgroundGeolocation.setConfig**

**Steps to reproduce:**

1. Set up background service (in particular (**ready** method with some "url" and "headers" fields)
2. At some point update headers with **setConfig**. P.S. it updates properly btw for foregrounded app
3. terminate the app and wait calling the API. You will see initial headers (from the **ready** method) but not the updated ones (from **setConfig**).

Could you please take a look?

**Comment by christocracy** [comment]
See the original post and provide more information (Plug-in version, platform: (iOS or Android), Config, code, etc

**Comment by amarchenko25** [comment]
@christocracy 

Plugin version: 4.12.3
Platform: iOS (checked at least on it)
OS version: iOS 16.4
Device manufacturer / model: Apple
Flutter info (flutter doctor):

[✓] Flutter (Channel stable, 3.13.0, on macOS 13.2.1 22D68 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

Code snippet:
```
  // when app starts
  Future<void> initialize() async {
    // Configure the plugin
    await bg.BackgroundGeolocation.ready(
      bg.Config(
          url: api_url,
        ),
      );
  }
  
  .........
  
  /// start BackgroundGeolocation when we already know the user 'token'
  Future<void> startLocationUpdateListening(String? token) async {
    bg.BackgroundGeolocation.onLocation(
      _onLocation,
      (error) => _logger.error(
          'BackgroundGeolocation.onLocation', 'error getting location: ${error.toString()}'),
    );
    await bg.BackgroundGeolocation.setConfig(
      bg.Config(
        authorization: bg.Authorization(accessToken: token),
      ),
    );
    // Start the plugin.
    final state = await bg.BackgroundGeolocation.state;
    if (!state.enabled) {
      await bg.BackgroundGeolocation.start();
    }
  }
.......
```

**Comment by christocracy** [comment]
You **must** ensure .ready resolves **before** calling .setConfig.

You likely have a race-condition calling .setConfig *before* .ready

**Comment by amarchenko25** [comment]
@christocracy 
**.ready** resolves before **.setConfig**.
It works perfectly for the foregrounded app.
As soon as it goes to the terminated state, it does not see new fields from the .setConfig (takes the config from **.ready**)

**Comment by christocracy** [comment]
Yes, of course it takes Config from ready.  You must ensure the headers provided to .ready are the current (correct) headers.

**Comment by amarchenko25** [comment]
@christocracy, yes, but we can update it with **.setConfig**, right?
Use case:
1. Login under User1
2. Logout
3. Login under User2

In that case we have to update 'access_token' in the headers. We can do it with **.setConfig** and it will be updated (while the app in foreground) and we can freely send locations to the server.
But when the app is terminated we will see incorrect header (with the old token) from **.ready**

How do we need to approach to this case?

**Comment by christocracy** [comment]
Every time .ready is called, your config is reset to default and the supplied Config is re-applied

**Comment by amarchenko25** [comment]
@christocracy We are calling **.ready** only once when app is just started (is it correct?)
And when we want to update the config -> call **.setConfig** (which updates the configuration immediately) 

Is it correct approach?

or we need to call **.ready** each time we want to update the config?

**Comment by christocracy** [comment]
.ready is to be called only once with each launch of your app.  It is a signal to the plug-in the your app is launched and "ready".

**Comment by amarchenko25** [comment]
Ok, but it doesn't says, why it is not apply the **.setConfig -> config** when app is terminated.

Lets imagine:

1.  Initially we call **.ready**
```
   await bg.BackgroundGeolocation.ready(bg.Config(
      stopOnTerminate: false,
      startOnBoot: true,
      preventSuspend: true,
      url: _url,
    )
```
2. at some point call **.setConfig**:
```
    await bg.BackgroundGeolocation.setConfig(
      bg.Config(
        authorization: bg.Authorization(accessToken: token),
      ),
) 
```

What config we are gonna have at the end? This one (excluding default fields)?
```
     bg.Config(
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true,
        url: _url,
        authorization: bg.Authorization(accessToken: token),
      ),
```

**Comment by hansvn** [comment]
In our case it turned out to be caused by a race condition that would incorrectly update the config (not setting the authentication token in some occasions).
So to give an update on the status of the original issue this can be closed.
