### ISSUE TITLE
Getting multiple location points for single odometer value. 

### ISSUE THREAD

**Issue by Pranit1804** [transistorsoft/flutter_background_geolocation#1124]
## Your Environment
* Plugin version: ^4.12.3
* Platform: Android and iOS
* OS version: Almost all OS
* Device manufacturer / model: iPhone, Xiaomi
* Flutter info (`flutter doctor`):

[!] Flutter (Channel stable, 3.7.12, on macOS 13.5.1 22G90 darwin-arm64, locale
    en-IN)
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.0/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at
      /Users/fitpage-tech/development/src/flutter. Consider adding
      /Users/fitpage-tech/development/src/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10.0,
      stopOnTerminate: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      stopTimeout: 5,
      stopOnStationary: false,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
      isMoving: true,
      speedJumpFilter: 30,
      locationAuthorizationRequest: 'WhenInUse',
      foregroundService: true,
      locationUpdateInterval: 15000,
      notification: _getNotification(showNotificationDetails),
      activityType: bg.Config.ACTIVITY_TYPE_FITNESS,
      url: "${Configuration.apiHostUrl}activities/$activityId/trackings/v2",
      autoSync: true,
      autoSyncThreshold: 120,
      batchSync: true,
      debug: true,
      maxBatchSize: 150,
      headers: {
        HttpConstants.authorization:
            '${HttpConstants.bearer} $authenticationToken'
      },
      maxDaysToPersist: 1,
    )).then((bg.State state) async {
      if (!state.enabled) {
        bg.State state = await bg.BackgroundGeolocation.start();
        return state.enabled;
      }

      return state.enabled;
    }).catchError((error, stackTrace) async {
      ExceptionLogger.track(error, stackTrace);

      await stop();
      return false;
    });
```

## Actual Behavior
I am receiving multiple points at regular intervals, all of which have the same odometer value but different latitude and longitude values. I also tried the example Background Geolocation app, and it consistently provides multiple points for a single odometer value.

## Expected Behavior
Previously, there were no multiple points for a single odometer value; it was in a continuous value manner.

The example for both old v/s new tracking data link is attached below:

Old: https://bitbucket.org/fitpage/workspace/snippets/Azjx9K
New: https://bitbucket.org/fitpage/workspace/snippets/o7A4B5 

## Context
I am trying to calculate the distance user walked/ran in that particular time period and track their activity.

**Comment by christocracy** [comment]
Is there a problem with the final result after a trip (eg 1km)?

**Comment by Pranit1804** [comment]
Yes, sometimes it shows a difference of 500 meters to 1 kilometer, but because of the constant bombardment of location points, the phone heats up significantly.

**Comment by christocracy** [comment]
> but because of the constant bombardment of location points, the phone heats up significantly.

When I’m field-testing, I use distanceFilter; 50.  I get a location twice / city block while walking (fewer when driving),

what are you doing to “bombard yourself with locations”, causing your phone to heat up?

**Comment by Pranit1804** [comment]
For testing purposes, we use mock locations that simulate GPS data. For field testing, we engage in walking or running, and our distance filter is set to 10, as frequent distance updates are necessary to calculate accurate data.

**Comment by christocracy** [comment]
You're aware that error of (`location.coords.accuracy`) is introduced with each odometer update?

For example, if 100 locations are recorded (each with an accuracy of `5` meters), you can expect an error of `100 * 5 meters` = 500 meters`.
