### ISSUE TITLE
Documentation request: Android hibernation

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1126]
Please consider documenting behaviour and suggestions around hibernation-current behaviour and suggested mitigation strategies and possible roadmap.

https://android-developers.googleblog.com/2021/09/making-permissions-auto-reset-available.html
from https://developer.android.com/topic/performance/app-hibernation see below:
--
Your app's [runtime permissions](https://developer.android.com/guide/topics/permissions/overview#runtime) are reset. This action has the same effect as if the user viewed a permission in system settings and changed your app's access level to Deny.

Your app can't run jobs or alerts from the background.

Your app can't receive push notifications, including high-priority messages that are sent through [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging).

Any files in your [app's cache](https://developer.android.com/training/data-storage/app-specific#internal-create-cache) are removed.
--
so this seems like it would cause 
1) Schedules to stop working
2) Android:old OS and/or old transistorsoft package-?
3) Android 14 and recent transistorsoft package
-- Keep working if geofences stored in app data - which seems very likely (only cache is cleared)

**Comment by christocracy** [comment]
The plug-in does not use “app cache” for anything.
