### ISSUE TITLE
Android: Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1128]
## Your Environment
* Plugin version:
* Platform: Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
should build with pubspec containing   flutter_background_geolocation: ^4.12.3

## Actual Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/neil.warner/dev/ts_tiny_demo/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/neil.warner/dev/ts_tiny_demo/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 56s
Exception: Gradle task assembleDebug failed with exit code 1

## Steps to Reproduce

1. file-new project in flutter 
2. add to pubspec    flutter_background_geolocation: ^4.12.3

3. flutter pub get
4. flutter run wituh android device installed or anything tha truns assembleDebug which runs gradle task :app:checkDebugAarMetadata
https://github.com/neiljaywarner/ts_tiny_demo/blob/master/pubspec.yaml#L38

## Context
add this plugin to an app for the first time and build the project.

**Comment by christocracy** [comment]
You did not properly implement the Setup Instructions.

this has been posted **dozens** of times before.

**Comment by neiljaywarner** [comment]
Oh that's awful I'm so sorry

....sent from my phone
