### ISSUE TITLE
onGeofencesChange not called

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/flutter_background_geolocation#113]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^3.2.0",
* Platform: Android
* OS version: Mac high sierra
* Device manufacturer / model: galaxy s10e
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
     BackgroundGeolocation.ready({
       reset: false,
       stopTimeout: 1,
       debug: true,
       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
       foregroundService: true,
       autoSync: true,
       url: TRACKER_HOST + this.state.username,
       stopOnTerminate: false,
       startOnBoot: true,
       notification: {
         title: 'react-native-background-geolocation',
         text: 'Tracking engaged'
       },
       heartbeatInterval: 60,
       enableHeadless: true,
       params: BackgroundGeolocation.transistorTrackerParams(DeviceInfo),
       maxDaysToPersist: 14
     }
```

## Expected Behavior

did addGeofence and expected onGeofencesChange to get called (I'm modifying the demo app `advanced/HomeView.tsx`)

## Actual Behavior

`onGeofencesChange` not called
`onGeofence` not called

## Steps to Reproduce

I'm adding geofences like below (because addGeofences doesn't seem to succeed) . 
And I see `- addGeofence success` in the console.

Still `onGeofencesChange` not getting called

```
   let geofences = response.data.results.map(review_meta => {

         let geofence = _.pick(review_meta, ['latitude', 'longitude', 'identifier'])
         let {latitude, longitude, identifier, ...extras} = review_meta

         let result = {
           ...geofence,
           radius: 250, /* meter */
           notifyOnEntry: true,
           notifyOnExit: true,
           extras,
         }
         return result
       })


       geofences.map(geofence => {
         BackgroundGeolocation.addGeofence(geofences, () => {
           console.log('- addGeofence success');
         }, (error) => {
           console.warn('- addGeofence error: ', error);
         })

       })
```

## Context

I'm trying to add geofences and see if `enter`, `exit` works

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Perhaps there’s something important in the logs.  Are you observing them?

**Comment by littlehome-eugene** [comment]
>- addGeofence success
> [http] -  {"responseText":"{\"success\":true}","status":200,"success":true}

not in the RN debugger. 

I also found that demo sometimes doesn't show the circle for geofence right away after you add the geofence by long-clicking. (I think I did toggle off and on , and click other buttons to make the geofence circle appear)

**Comment by christocracy** [comment]
I’m talking about naive android device logs, with adb logcat.

See the wiki Debugging.

**Comment by christocracy** [comment]
Btw, do you know this is the **Flutter** version you’re posting at?   There are 4 different ecosystems this plugin available:
- Cordova
- React Native
- Flutter
- Pure native.

Please post your issues at the appropriate repository.
