### ISSUE TITLE
Distance filter & Time Filter

### ISSUE THREAD

**Issue by Abubakarshaikh** [transistorsoft/flutter_background_geolocation#1130]
I would like to seek guidance regarding the functionality of the Distance filter when used in conjunction with the Time Filter. 
It has come to our attention that both features do not seem to work simultaneously, which is of critical importance for our application. Could you please provide instructions on how to address this matter?

**Comment by christocracy** [comment]
You can research thet behaviour of the Android Location API yourself at the Android API docs for [`LocationRequest.Builder`](https://developer.android.com/reference/android/location/LocationRequest.Builder)

- `Config.distanceFilter` = [`LocationRequest.Builder. setMinUpdateDistanceMeters`](https://developer.android.com/reference/android/location/LocationRequest.Builder#setMinUpdateDistanceMeters(float))
- `Config.locationUpdateInterval` = [`setIntervalMillis `](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.Builder#public-locationrequest.builder-setintervalmillis-long-intervalmillis)
- `Config.fastestLocationUpdateInterval` = [`setMinUpdateIntervalMillis `](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.Builder#public-locationrequest.builder-setminupdateintervalmillis-long-minupdateintervalmillis)
