### ISSUE TITLE
Merge multiple foreground service notification

### ISSUE THREAD

**Issue by Tobicloud** [transistorsoft/flutter_background_geolocation#1133]
## Your Environment
* Plugin version: ^4.11.1
* Platform: Android
* OS version: All
* Device manufacturer / model: All 
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HEREawait bg.BackgroundGeolocation.ready(bg.Config(
  notification: bg.Notification(channelId: "75418"),
        reset: true,
        debug: EnvironmentConstants.SELECTED_ENVIRONMENT == Environment.DEV
            ? true
            : false,
        notificationSmallIcon: Platform.isAndroid ? "drawable/notification_icon" : "app_icon",
        notificationChannelName: "TSLocationManager",
        notificationText: "Lib 1 Tobi services are running in background",
        notificationTitle: "TOBI",
        logLevel: bg.Config.LOG_LEVEL_OFF,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true))
    .then((bg.State state) {
  bg.BackgroundGeolocation.start().then((bg.State state) =>
      {print('Tracking is started successfully$state')});
  if (!state.enabled) {
  } else {
    print('Tracking is not started, Already running');
  }
});

## Expected Behavior
<!--- Tell us what should happen -->
We just want one single foreground service notification otherwise it will be confusing for the user to see 3 notifications.


## Actual Behavior
<!--- Tell us what happens instead -->
We have three foreground service notifications coming-
1. For Achieving floating window functionality 
2. For getting location while app is in foreground/background(when user is not moving). We are using another foreground service for this.
3. https://pub.dev/packages/flutter_background_geolocation
(for getting location while app is in foreground/background/terminated mode(when user is moving))
Three different foreground notifications are generated in notification panel.

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->
We are trying to merge all the foreground service notification to a single notification and for that we need a common notification ID but this plugin does not allow us to configure the notification ID. We are using same channelID that is described in the config code above as per documentation but its not working.

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Do not have any specific logs to share.
```

</details>

**Comment by christocracy** [comment]
You’re using deprecated notification options:
> notificationSmallIcon: Platform.isAndroid ? "drawable/notification_icon" : "app_icon",
>notificationChannelName: "TSLocationManager",
>notificationText: "Lib 1 Tobi services are running in background",
>notificationTitle: "TOBI",

Migrate all those to your `bg.Notification()` instance, noting their shortened name.  See api docs `Config.notification`

**Comment by christocracy** [comment]
Do you have the ability to configure the “notificationId” on your other service?

**Comment by Tobicloud** [comment]
Yes @christocracy, we have configured the NotificationId for other two service and they use the same notification id and channel.

private const val ONGOING_NOTIFICATION_ID = 75418
private const val CHANNEL_ID = "flutter_location_channel_01"

Similarly, we want to merge flutter_background_geolocation foreground service notification to our rest two service notifications.

**Comment by christocracy** [comment]
The plug-in’s notificationId is not configurable (it could be made so) but is hardcoded to `9942585`.  If you can align all your services to that ID, you should see only 1 notification.

**Comment by Tobicloud** [comment]
Thanks @christocracy for sharing the notificationId. This will be really helpful for us. We have one last query that what is the channelId and channel Name fir this plugin's service notification flutter_background_geolocation.

**Comment by Tobicloud** [comment]
Thanks for helping out @christocracy. All the notifications are merged now and we achieved what we wanted. We are closing this issue.
