### ISSUE TITLE
Heartbeat updates has longer interval then expected on Android 14

### ISSUE THREAD

**Issue by androidmitry** [transistorsoft/flutter_background_geolocation#1136]
## Your Environment
* Plugin version: 4.12.3
* Platform: Android
* OS version: 14
* Device manufacturer / model: Android Emulator arm64
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device
[✓] Network resources
```
* Plugin config:
```dart 
bg.Config(
    notification: bg.Notification(
        title: 'title',
        text: 'text',
        sticky: true,
        layout: 'my_notification_layout',
        smallIcon: 'mipmap/ic_notification',
        largeIcon: 'mipmap/ic_notification',
    ),
    locationAuthorizationRequest: 'always',
    disableLocationAuthorizationAlert: true,
    backgroundPermissionRationale: bg.PermissionRationale(
        title: 'title',
        message: 'message',
        positiveAction: 'positiveAction',
        negativeAction: 'negativeAction'),
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10.0,
    stopOnTerminate: false,
    preventSuspend: true,
    heartbeatInterval: 60,
    stopTimeout: 1,
    startOnBoot: true,
    foregroundService: true,
    logLevel: bg.Config.LOG_LEVEL_ERROR,
    persistMode: bg.Config.PERSIST_MODE_NONE,
)
```

## Expected Behavior
Heartbeat events received every 60 seconds

## Actual Behavior
Heartbeat events received every 90-100 seconds, however the same code works fine on Android 13 emulator

## Steps to Reproduce
1. Run the app and start background geolocation
2. Don't change devices location to start receiving heartbeat events

## Context
While this is not a big problem for me at least for now. I want you to be aware of this issue.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by androidmitry** [comment]
@christocracy Yeah, I saw that. I wonder with these new AlarmManager limitation would you consider using something like Handler or Timer to run periodic tasks during lifetime of the application? That seems reasonable to me if foreground service is running.

**Comment by christocracy** [comment]
No.  The foreground-service is **NOT** running when heartbeat is engaged.  Heartbeat runs only when the device is in the stationary state.

Your only options are:
1.  Accept the new limitation.
2.  Add the [`USE_EXACT_ALARM`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#alarmmanager-exact-alarms-optional) permission to your `AndroidManifest` and be prepared to justify that added permission with Google Play Console.

**Comment by androidmitry** [comment]
> The foreground-service is NOT running when heartbeat is engaged. Heartbeat runs only when the device is in the stationary state.
I don't know plugins design in details, but I see a persisted notification along with `onHeartbeat` callback invocations, so at least some foreground service is running I suppose.
Thanks for clarification.

**Comment by christocracy** [comment]
>least some foreground service is running I suppose.

There is no **CONSTANTLY RUNNING** foreground-service when your app is in the stationary state.  There is no possible way to `Handler` to run the heartbeat timer.  If you call `.getCurrentPosition` in your `onHeartbeat` handler, a FGS will be launched to fetch the current location then immediately stop itself.


I repeat:  Your only options are:

1.  Accept the new limitation.
2.  Add the [USE_EXACT_ALARM](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#alarmmanager-exact-alarms-optional) permission to your AndroidManifest and be prepared to justify that added permission with Google Play Console.
