### ISSUE TITLE
I want to manually push the location data. Is there a way to do that?

### ISSUE THREAD

**Issue by gamestap99** [transistorsoft/flutter_background_geolocation#1141]

**Comment by gamestap99** [comment]
> Yes. Read the api docs "HTTP Guide" (it's linked all over the place) to learn how and much more.

Thank you for your response. I have a small question: I just downloaded your sample app and tested it on iOS. When I close the app, lock the screen, and then move 200 meters, it restarts and sends data. The main issue is that after that, when I move another 50 meters, the app doesn't send the location anymore. Do I need to move another 200 meters for it to work again?

**Comment by christocracy** [comment]
Read wiki "Debugging" and "Philosophy of Operation.  Read api docs Config.distanceFilter

**Comment by gamestap99** [comment]
> Read wiki "Debugging" and "Philosophy of Operation. Read api docs Config.distanceFilter

Hello, I have read them before making changes to your sample code and running the application. Could you please take a look and evaluate where I might have misunderstood?

```
  bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      disableElasticity: true,
      distanceFilter: 2.0,
      autoSync: true,
      autoSyncThreshold: 0,
      params: {
        "user_id": "aaaaaaa",
      },
      extras: {"route_id": 8675309},
      /// Disable the stop detection completely - we handle the stop / start state by our self.
      disableStopDetection: true,
      /// As long as the Background Geolocation is started we don't need any automatic stops
      pausesLocationUpdatesAutomatically: false,
      /// Our desired GPS authorisation
      locationAuthorizationRequest: 'Always',
      maxDaysToPersist: 14,
      locationsOrderDirection: "DESC",
      backgroundPermissionRationale: bg.PermissionRationale(
        title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      ),
      url: "xxx",
      /// Activity settings
      activityType: bg.Config.ACTIVITY_TYPE_FITNESS,
      allowIdenticalLocations: true,
      preventSuspend: false,
      heartbeatInterval: 60,
      showsBackgroundLocationIndicator: true,
      stationaryRadius: 25,
      /// Don't go into background
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: false,
      enableHeadless: true,
    )).then((bg.State state) {
      bg.Logger.info("[ready] ${state.toMap()}");
      print("[ready] ${state.toMap()}");
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving!;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

```

**Comment by christocracy** [comment]
I have no idea what you're doing.  Looks at the plug-in logs to learn what's happening.

**Comment by gamestap99** [comment]
> I have no idea what you're doing. Looks at the plug-in logs to learn what's happening.

Thank you for your assistance. I think I will try moving around with my iPhone XS Max to test the location tracking from your sample app. Perhaps I will understand better to ask more accurate questions. Thank you for taking the time to help me. Sincerely and thank you!!!

**Comment by gamestap99** [comment]
I will close this topic
