### ISSUE TITLE
how to stop background task

### ISSUE THREAD

**Issue by pradhansoubhagya** [transistorsoft/flutter_background_geolocation#1142]
I have two button. in 1st button I gave one action to start the background task.

Future<void> startBackgroundTask() async {
  try {
    // Start a background task.
    viewModel.taskId.value = await bg.BackgroundGeolocation.startBackgroundTask();
    Timer.periodic(Duration(seconds: 5), (timer) {
      print(
          'Latitude:${viewModel.latitude.value}''Longitude:${viewModel.longitude.value}');
      viewModel.test!.value = viewModel.test!.value + 1;

      print(viewModel.test!.value);
      print("Background Task is running" + DateTime.now().toString());
    }); } catch (e) {
    print('Error starting background task: $e'); }} 

in every 5 second I am printing something.And in second button I gave stop action

bg.BackgroundGeolocation.stopBackgroundTask(viewModel.taskId.value);

But after calling this function still background is running. How to stop back ground task

**Comment by christocracy** [comment]
Please [learn to Syntax Highlight multi line codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by pradhansoubhagya** [comment]
I have two button. in 1st button I gave one action to start the background task.
```
Future startBackgroundTask() async {
try {
// Start a background task.
viewModel.taskId.value = await bg.BackgroundGeolocation.startBackgroundTask();
Timer.periodic(Duration(seconds: 5), (timer) {
print(
'Latitude:${viewModel.latitude.value}''Longitude:${viewModel.longitude.value}');
viewModel.test!.value = viewModel.test!.value + 1;

  print(viewModel.test!.value);
  print("Background Task is running" + DateTime.now().toString());
}); } catch (e) {
print('Error starting background task: $e'); }} 
```
in every 5 second I am printing something.And in second button I gave stop action
```
bg.BackgroundGeolocation.stopBackgroundTask(viewModel.taskId.value);
```

But after calling this function still background is running. How to stop back ground task

**Comment by christocracy** [comment]
Please learn to **EDIT** your posts instead of reposting.

**Comment by pradhansoubhagya** [comment]
just tell me how to stop the background task

**Comment by christocracy** [comment]
You misunderstand exactly what a background-task is.  It's not some function that gets magically stopped when you call `.stopBackgroundTask(taskId)` It's the guaranteed authorization to run code which is stopped.  It's up to you to stop Timer or Android will punish your app by blacklisting it from being able to run background-tasks in the future.

**Comment by pradhansoubhagya** [comment]
Ok I understood. So Can I fetch background geolocation for continuous 8 hour even if app is in background. After 8 hour can I stop that fetch???

**Comment by christocracy** [comment]
Of course not.  Background tasks give you 3 minutes on Android before they timeout.

For long-term location-tracking, use my background_location plug-in:  https://github.com/transistorsoft/flutter_background_geolocation

**Comment by christocracy** [comment]
Oh, whoops.  We are at the background_geolocation repo.

For periodic location updates, use my background_fetch plug-in.

**Comment by pradhansoubhagya** [comment]
So in this geolocation package can I start fetch in every 15sec for 8 hour?
and can I stop that by pressing button?
Please give me one example code for this requirement

**Comment by pradhansoubhagya** [comment]
my requirement is I need to fetch current location in every 15 sec for 8 hour.after 8 hour Hopw can I stop that. for this requirement which package I need to use please tell me

**Comment by christocracy** [comment]
No you can't have location every 8 seconds when the device is known to be stationary (that would be insane).  That sort of abusive behaviour is exactly what got us in this mess of https://dontkillmyapp.com.

Read the wiki "Philosophy of Operation".  When the device is detected to be moving, the plug-in tracks.  When the device is known to be stationary, the plug-in turns off location and goes to sleep.

The plug-in is not responsible for updating location when the device is known to be stationary.

**Comment by christocracy** [comment]
> my requirement is I need to fetch current location in every 15 sec for 8 hour.

Just because your client gave you some specification, it doesn't mean it's possible.  Sometimes, things are just impossible.

**Comment by pradhansoubhagya** [comment]
So what is the minimum time to fetch location even app is closed/opened?

**Comment by pradhansoubhagya** [comment]
> > my requirement is I need to fetch current location in every 15 sec for 8 hour.
> 
> Just because your client gave you some specification, it doesn't mean it's possible. Sometimes, things are just impossible.

If it is not possible How whatsapp and uber like app are doing this

**Comment by christocracy** [comment]
Did you read the wiki I told you.  You sound like you haven't.

This plug-in was originally developed for tracking emergency workers in disaster zones where life depended on it, regardless if app terminated or device rebooted
