### ISSUE TITLE
Objective-C classes should be prefixed

### ISSUE THREAD

**Issue by stuartmorgan** [transistorsoft/flutter_background_geolocation#1145]
Currently most of the Objective-C classes in this plugin have no prefix. This violates [Apple's recommended practice for library code](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html), which is very dangerous since collisions would cause undefined behavior at runtime.

Adding a specific-to-this-plugin prefix (e.g., `FBG`) to all Objective-C classes, per Apple's guidelines, would make it much less likely that someone using this plugin would end up with undefined behavior in their application.

See also https://github.com/transistorsoft/flutter_background_geolocation/issues/1144

## Your Environment
* Plugin version: N/A
* Platform: iOS
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`): N/A
* Plugin config: N/A
```dart <-- Syntax highlighting: DO NOT REMOVE -->
N/A
```

## Expected Behavior
The plugin class uses a 3-letter prefix unique to this plugin.

## Actual Behavior
No prefix on most classes.

## Steps to Reproduce
N/A

## Context
N/A

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
Fair enough.

**Comment by christocracy** [comment]
Released to `4.13.2`

**Comment by christocracy** [comment]
I'm satisfied for the time-being.

**Comment by stuartmorgan** [comment]
I would urge you to consider the fact that the new situation is significantly more dangerous than the one you fixed with the change. Previously a collision could only have happened if one of the clients of your plugin updated to a new version of Flutter and rebuilt, which means they at least would have an opportunity to discover the problem pre-release.

With this version, *existing, published applications* are subject to undefined behavior when the users of the application update to a new version of iOS, without any change by the application developer.

**Comment by stuartmorgan** [comment]
> I've been doing this for over 9 years without issue.

Yes, the nature of this class of problems is that it works fine as long as there are no collisions, and then suddenly if there are—which is impossible to predict in advance—it is likely catastrophic. I've been writing Obj-C code since before iOS existed, and have seen this happen in the wild with modules that did not follow Apple's guidelines, including cases where applications were suddenly rendered completely useless due to crashes on launch.

If you are set on not changing this, I sincerely hope for the sake of your plugin's clients and their customers that Apple doesn't ever happen to use this prefix.

**Comment by christocracy** [comment]
It'll be fine.  Relax.

**Comment by christocracy** [comment]
I’ve had a review of this thread.  I will implement a 3-letter namespace.
