### ISSUE TITLE
Error sending mail

### ISSUE THREAD

**Issue by gamestap99** [transistorsoft/flutter_background_geolocation#1146]
## Your Environment
* Plugin version: 4.13.1
* Platform: iOS 
* OS version: 16.x
* Device manufacturer / model: Iphone Xs Max
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  Future<void> _sendLogs() async{
    bg.Logger.emailLog("itchange.nw@gmail.com", bg.SQLQuery(
        start: DateTime.parse("2023-10-04 00:01"),
        end: DateTime.parse("2023-10-04 23:59"),
    ));
  }
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2023-10-04 10:41:13.951405+0700 BG Geo[5039:1254415] ⚠️-[TSLog emailLog:query:viewController:success:failure:] CANNOT_SEND_MAIL
2023-10-04 10:41:13.951554+0700 BG Geo[5039:1247291] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(CANNOT_SEND_MAIL, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      Logger.emailLog (package:flutter_background_geolocation/models/logger.dart:281:12)
<asynchronous suspension>
```

</details>

**Comment by christocracy** [comment]
You need to have a mail client installed on the device.  If you're trying to do that in the sim, there's no mail client on sims

**Comment by gamestap99** [comment]
> You need to have a mail client installed on the device. If you're trying to do that in the sim, there's no mail client on sims

Hello, is your question whether I should install Gmail or Mail on my phone, correct?

**Comment by christocracy** [comment]
Yes

**Comment by gamestap99** [comment]
> Yes

If that's the case, I would have installed them on my phone before calling your function

**Comment by christocracy** [comment]
It's never too late.  There's still hope.

**Comment by devovipul** [comment]
CANNOT_SEND_MAIL

i am getting this issue in iOS while testing this function..

**Comment by christocracy** [comment]
It means the device doesn’t have an email client installed (eg the Simulator doesn’t have an email client on installed).
