### ISSUE TITLE
android app rejected with issue SDK: Huawei com.huawei.hms:update

### ISSUE THREAD

**Issue by sijanpoudel11** [transistorsoft/flutter_background_geolocation#1149]
## Your Environment
* Plugin version: 4.8.7
* Platform: Android
* OS version: 
* Device manufacturer / model:
* Flutter info (`flutter doctor`): 
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
buildscript {
  // ext.kotlin_version = '1.5.1'                                                             
    ext.kotlin_version = '1.7.10'
     ext {
       compileSdkVersion   = 33            // or higher
       targetSdkVersion    = 33 
       minSdkVersion      = 21               // or higher
       appCompatVersion    = "1.4.2"           // or higher
       playServicesLocationVersion = "20.0.0"  // or higher
   }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath 'com.google.gms:google-services:4.3.13'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
         maven {
           // [required] flutter_background_geolocation
           url "${project(':flutter_background_geolocation').projectDir}/libs"
       }
       maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
       }
       
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
![Screenshot 2023-10-06 at 16 18 25](https://github.com/transistorsoft/flutter_background_geolocation/assets/51782501/954a01f8-def1-4ca7-910f-1489155d09f4)


task clean(type: Delete) {
    delete rootProject.buildDir
}

```

## Expected Behavior

Issue details

We found an issue in the following area(s):

Version code 7: :
SDK: Huawei com.huawei.hms:update
Additionally, follow these steps to bring your app into compliance:

You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK."

## Actual Behavior

app runs fine on both emulator and physical device , 
i have not included this piece of code  in my configuration 
"maven { url 'https://developer.huawei.com/repo/' }" still this issue persists , 
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version: 4.8.7

Why 4.8.7?

> i have not included this piece of code in my configuration

Why not?

**Comment by sijanpoudel11** [comment]
i will try with latest version of plugin and also adding this missing piece of code , it should solve this issue then ? @christocracy
