### ISSUE TITLE
Testflight Build Issue

### ISSUE THREAD

**Issue by AhmedRazaKhokhar** [transistorsoft/flutter_background_geolocation#1152]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
<key>NSMotionUsageDescription</key>
    <string>Motion usage description</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>When in use description</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Always/When in use description</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
```

## Expected Behavior
Geolocation should work in background after build/publish with this library

## Actual Behavior
Geolocation is working fine when app is directly installed from the Xcode and doesn't work when installed from testflight after build.
</details>

**Comment by christocracy** [comment]
See Wiki "Debugging".  Learn to fetch logs from the plugin using `.emailLog`.  I don't know what you're doing but there's nothing about running on TestFlight that causes this plugin "not to work".  You're doing something on your end causing it to fail.
