### ISSUE TITLE
Documentation doesn't work

### ISSUE THREAD

**Issue by petrslavotinek** [transistorsoft/flutter_background_geolocation#1155]
Link to [API Documentation](https://pub.dartlang.org/documentation/flutter_background_geolocation/latest/flt_background_geolocation/flt_background_geolocation-library.html) no longer works. Result page displays only `404 Not Found`.

**Comment by christocracy** [comment]
It's `pub.dev`'s responsibility to generate the docs.

**Comment by petrslavotinek** [comment]
Thank you and sorry, I didn't know that.

**Comment by christocracy** [comment]
I just pushed a new version `4.13.3` a few hours ago.  They doc generation is probably sitting in a queue there. 


<img width="836" alt="Screenshot 2023-10-12 at 1 32 59 PM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/38f1af66-bd69-4020-9db0-bc91b4fff7e5">

**Comment by christocracy** [comment]
The api docs are up again.
