### ISSUE TITLE
Android 14 Foreground Service types are required

### ISSUE THREAD

**Issue by luiges90** [transistorsoft/flutter_background_geolocation#1157]
## Your Environment
* Plugin version: N/A
* Platform: Android
* OS version: 14
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`): N/A
* Plugin config: N/A

## Expected Behavior
N/A

## Actual Behavior
N/A

## Steps to Reproduce

N/A

## Context
[Android 14 is now live and will be pushed to devices.](https://android-developers.googleblog.com/2023/10/android-14-is-live-in-aosp.html) One thing catch my eye that is relevant to this plugin, about foreground services (emphasis mine):
> **More consistent and reliable foreground services** - We've [collaborated with hardware manufacturers such as Samsung](https://android-developers.googleblog.com/2023/05/improving-consistency-of-background-work-on-android.html) to create both a more consistent developer experience and a more reliable user experience. *To this end, Android 14 has a new requirement to declare [foreground service types and request type-specific permissions](https://developer.android.com/about/versions/14/changes/fgs-types-required) and we have [Google Play policies](https://support.google.com/googleplay/android-developer/answer/13315670) to enforce appropriate use of these APIs.* We've also added a new [user-initiated data transfer](https://developer.android.com/about/versions/14/changes/user-initiated-data-transfers) job type, making the experience of managing large user-initiated uploads and downloads smoother by leveraging JobScheduler's constraints (e.g. [network constraints](https://developer.android.com/reference/android/app/job/JobInfo.Builder#setRequiredNetworkType%28int%29) such as unmetered WiFi).

I raise this issue to bring attention to the developers about this change.

## Debug logs
N/A

**Comment by christocracy** [comment]
> Plugin version: N/A

It is **most certainly** applicable.  And **required**.

Have you looked at the CHANGELOG?

**Comment by luiges90** [comment]
Oh sorry I should have looked at that first. 
So plugin version **4.12.0** supports it already. We will look into it

**Comment by christocracy** [comment]
There's also the blog about this.

https://transistorsoft.medium.com/android-14-support-abe4700532c7
