### ISSUE TITLE
Always Allow permission is not enough on Android

### ISSUE THREAD

**Issue by al-muammar** [transistorsoft/flutter_background_geolocation#1161]
## Your Environment
* Plugin version: 4.11.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: SM-G985F
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  locationAuthorizationRequest: 'Always',
  persistMode: bg.Config.PERSIST_MODE_LOCATION,
  distanceFilter: 10,
  stopOnTerminate: false,
  startOnBoot: true,
  disableElasticity: false,
  stopTimeout: 600,
  // 10 minutes
  // Web server reporting
  url: '<server-url-here>',
  httpRootProperty: 'location',
  // schedule — maybe disable tracking during night hours.
  reset: true,
  logLevel: bg.Config.LOG_LEVEL_ERROR,
  params: {'device_id': deviceId}
)
```

## Expected Behavior
We receive all coordinates both when the app is in background & terminated

## Actual Behavior
Even when the app is in background, we stop collecting & receiving coordinates. On most of other Android devices everything works fine

## Additional Context
Our driver had said that it seems that on an OS level something is blocking gathering coordinates. He is unable to share coordinates in background in WhatsApp as well as other apps. Are there any thoughts how to fix that?

**Comment by christocracy** [comment]
> On most of other Android devices everything works fine

It's widely known that certain Android manufacturers violate the Android API by crippling background-services in order to achieve better battery life at the expense of properly functioning APIs.

See https://dontkillmyapp.com

**Comment by al-muammar** [comment]
Amazing, thanks for the blazingly fast reply. Once I try it I'll write back here

**Comment by christocracy** [comment]
You are apparently using a custom `locationTemplate`.  When the location-provider settings on a device are changed, the plugin *automatically* records a location and posts to your `Config.url`, automatically appending `event: 'providerchange` to your `locationTemplate`.

**Comment by al-muammar** [comment]
> When the location-provider settings on a device are changed

@christocracy, what does it mean exactly? Does it mean that a user changed the settings and denied geolocation?
