### ISSUE TITLE
How does `useSignificantChangesOnly` work in the foreground vs background / terminated state? Does it work with `enableHeadless`?

### ISSUE THREAD

**Issue by dale-lakes** [transistorsoft/flutter_background_geolocation#1165]
## Your Environment
* Plugin version: 4.13.3
* Platform: Both
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`):
```bash
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg_geo.Config(
  logLevel: bg_geo.Config.LOG_LEVEL_INFO,
  desiredAccuracy: bg_geo.Config.DESIRED_ACCURACY_HIGH,
  startOnBoot: true,
  stopOnTerminate: false,
  enableHeadless: true,
  useSignificantChangesOnly: true,
  maxMonitoredGeofences: 50,
  reset: kDebugMode,
  disableLocationAuthorizationAlert: true,
),
```

## Expected Behavior

When the above config settings are set, then while the app is open, "normal" location tracking occurs (based on well-documented philosophy of operations for motion changes, elasticity, etc.). 

But when the app is terminated, only significant location changes are tracked. When a significant location change occurs, various `HeadlessEvent` events may be triggered (e.g. LOCATION, GEOFENCE, GEOFENCESCHANGE, BOOT, etc.), depending on the specific location that triggered the significant location change. At the very least, `LOCATION` is triggered for the significant location update, and so is `GEOFENCE` if a geofence is triggered while the app is terminated.
## Actual Behavior

Unsure. Opening this issue to clarify what the expected behavior should be. Does `useSignificantChangesOnly` only impact how location tracking occurs in the terminated / background state, or does it also impact how location tracking occurs when the app is in the foreground? How does `useSignificantChangesOnly` impact how `enableHeadless: true` functions?

I'd like to find a way to set the parameter `useSignificantChangesOnly` to true without disrupting how location is tracked while the app is in the foreground. After reading the documentation, I'm not sure if this is possible.

## Steps to Reproduce

See above

## Context

See above

## Debug logs

N/A

</details>

**Comment by christocracy** [comment]
useSignificantChangesOnly records a location about every 1000 meters, regardless if terminated or background.  

enableHeadless does not affect tracking functionality in any way.  It can be true or false, it doesn't matter.

**Comment by dale-lakes** [comment]
So to be clear, `useSignificantChangesOnly` will override the default location tracking while the app is in the foreground, too?

**Comment by christocracy** [comment]
With useSignificantChangesOnly: true, many Config options are no longer relevant (desiredAccuracy, distanceFilter).

A location will be recorded about every 1000 meters, **PERIOD**.  Regardless of terminated / background.  It cannot be any more clear.

**Comment by dale-lakes** [comment]
You can be more clear. There's a lot of ambiguity when you say `many Config options are no longer relevant`.

I understand how significant location changes works re: frequency of location updates. But what is unclear is which other config options are impacted.

You mentioned desiredAccuracy, distanceFilter, etc both here and in the documentation.

What is not obvious is how these specific Config options are impacted: `enableHeadless`, `stopOnTerminate`. These two options fundamentally change the lifecycle of the application, which is why I'm asking for clarification.

Additionally, from my experience, significant location updates are typically only used as as way to receive *background* location updates because of how iOS will relaunch the app in the background if a new event arrives. This is why I was asking if `useSignificantChangesOnly` overrides *foreground* location tracking behavior.

Your documentation states:
> Set true in order to disable constant background-tracking. Locations will be recorded only periodically.

This does not say it disables constant *foreground* location tracking. So if this setting impacts how location is tracked while the app is in the foreground, that is not documented.

**Comment by christocracy** [comment]
enableHeadless is nothing but an event-listener.  It has **no effect** upon the performance of the plug-in.  enableHeadless is optional.  If you don't have application logic to run when an event occurs while the Android app is terminated, then you don't need enableHeadless.

**Comment by christocracy** [comment]
`Config.useSignificantChangesOnly` contains the word "*only*" for a reason.
