### ISSUE TITLE
Logs should indicate if location is not available when device goes into flight mode

### ISSUE THREAD

**Issue by aguerola** [transistorsoft/flutter_background_geolocation#117]
## Your Environment
* Plugin version: 1.2.2
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: Google Pixel 2 XL
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (2 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_LOW,
            distanceFilter: 50.0,
            enableHeadless: true,
            url: ********,
            params: ********,
            headers: ********,
            maxBatchSize: 400,
            autoSyncThreshold: 20,
            maxDaysToPersist: 20,
            batchSync: true,
            stopTimeout: 3,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            notification: bg.Notification(
              layout: "notification_layout",
              smallIcon: "drawable/notification_icon_02",
              color: "#00FF00",
            ),
            reset: true))
        .then((bg.State state) async {
      if (!state.enabled) {
        await bg.BackgroundGeolocation.start();
        await bg.BackgroundGeolocation.sync();
      }
    });
```

## Expected Behavior

The logs should indicate when the user selects flight mode or at least the state of the location provider:
╔═════════════════════════════════════════════
║ Location-provider change: false
╠═════════════════════════════════════════════
╟─ GPS: false
╟─ Network: false

## Actual Behavior
Nothing in the logs indicates that the user enabled/disabled flight mode. Only connectivity change true or false, but nothing about the location provider

## Steps to Reproduce

1. Open the app
2. Enable flight mode from the status bar
3. See logs
4. Disable flight mode from the status bar
5. See logs

## Context

I am trying to debug an issue and I need to know when the location is not available due to flight mode activation

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
09-15 15:46:53.434 DEBUG [ActivityRecognitionService onDestroy] 
  🔴  ActivityRecognitionService destroyed
09-15 15:46:53.446 DEBUG [TrackingService onDestroy] 
  🔴  TrackingService destroyed
09-15 15:47:03.154 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

09-15 15:47:03.188 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
09-15 15:51:12.176 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? false
╠═════════════════════════════════════════════

09-15 15:51:35.373 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

09-15 15:51:35.397 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

```

</details>

**Comment by christocracy** [comment]
Gps still works in flight mode.

**Comment by christocracy** [comment]
Gps is nothing more than *really* faint radio signals emitted from far away satellites in space.  Flight mode doesn’t disable the radio receiver on the the device from *receiving* signals.

Flight mode is concerned with high power radio signals being *transmitted from* the device.

**Comment by aguerola** [comment]
What about the network and wifi location based?
Last week, after a flight, the plugin was not tracking the position anymore. It started to track again the moment I opened the app for the first time after the flight, around 1 hour after landing. During that hour I went from the airport to the city where I live, around 30 km distance.
Basically, from Palma airport in Spain to Budapest city there is no tracking

**Comment by christocracy** [comment]
I've tested this many times on flights without issue.

When I enable flight mode, I correctly see an `#onConnectivityChange` event fire, showing wifi is disabled:
```
🔵-[TSHttpService init]_block_invoke Network: No Connection | Flags: -- -------
2019-09-15 10:41:51.581095-0400 BG Geo[7794:1407207] 🔵-[TSHttpService init]_block_invoke Network: No Connection | Flags: -- -------
2019-09-15 10:41:51.582234-0400 BG Geo[7794:1407209] flutter: [connectivitychange] - [ConnectivityChangeEvent connected: false]
```

**Comment by christocracy** [comment]
Enabling *Airplane* mode does not disable location-services.  It merely disables the Cellular and Wifi radios from transmitting, leaving only the GPS location-provider enabled.

Mobile Location-services = GPS + Wifi + Cellular.

**Comment by christocracy** [comment]
Here's me landing at an airport this summer, where the plugin happily engaged my rental car ride after landing:
- Inbound flight
![](https://dl.dropbox.com/s/1ffkp9eiox12nh0/Screenshot%202019-09-15%2010.50.20.png?dl=1)

- Return flight
![](https://dl.dropbox.com/s/bx8n1mqj4k41qcb/Screenshot%202019-09-15%2010.52.23.png?dl=1)

**Comment by aguerola** [comment]
I see...
For some reason the plugin did not work for me this time. As I said, only when I opened the app started to track again. Maybe the app was killed by the SO. In that case, the plugin should track the position in the background, right?
Is there something wrong in my configuration?

I am just trying to understand what could be the cause. The app I built is supposed to be totally automatic, so opening the app after some is not a solution for me

**Comment by aguerola** [comment]
I am using android 10, I updated the description. Sorry for that

**Comment by christocracy** [comment]
>Maybe the app was killed by the OS

It doesn't matter.  The Android plugin is listening to events which launch a foreground-service in the background.

I suggest you enable `debug: true` and go outside for a nice long walk/drive/bike ride.  Reboot your device and don't relaunch the app.  You'll *hear* the plugin tracking, regardless that your app isn't event launched.

**Comment by christocracy** [comment]
Importantly, be sure to do the *initial unlock* after rebooting the device.  Then put the phone in your pocket and go outside for a nice long test.

**Comment by christocracy** [comment]
I'm primarily developing on a Pixel 3a @ 10.0.  I have an older Pixel running 10 as well.
