### ISSUE TITLE
[iOS] Incorrect activity type of the location after terminated state of the App

### ISSUE THREAD

**Issue by amarchenko25** [transistorsoft/flutter_background_geolocation#1173]
## Your Environment
* Plugin version: 4.13.3
* Platform: iOS
* OS version: 17.0.3
* Device manufacturer / model: iPhone 13
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 3.13.0, on macOS 14.1 23B74 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.84.0)
[✓] Connected device (3 available)
[✓] Network resources
```
* Plugin config:
```dart 
    return bg.Config(
      desiredAccuracy:  bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stationaryRadius: 25,
      minimumActivityRecognitionConfidence: 30,
      stopOnTerminate: false,
      heartbeatInterval: 60,
      preventSuspend: true,
      url: url,
      authorization: bg.Authorization(
        accessToken: token,
        refreshToken: refreshToken,
        refreshUrl: refreshTokenUrl,
        refreshPayload: {
          'grant_type': 'refresh_token',
          'refresh_token': '{refreshToken}',
        },
      ),
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      batchSync: true,
      autoSync: true,
      autoSyncThreshold: 10,
      maxBatchSize: 10,
    );
```

## Expected Behavior
We should receive activityType / confidence even when the app went from terminated to backgrounded state.

## Actual Behavior
The locations sends with **"activity":{"type":"unknown","confidence":100}**`

## Steps to Reproduce
1. Terminate the app
2. walk / run /drive enough to go to moving state
3. observe the results

## Debug logs
Please, check logs from **2023-11-16 15:35:44.365** (went from terminated to background)
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/13390824/background-geolocation.1.log)

Do you have any ideas how to resolve this issue? Thx

**Comment by amarchenko25** [comment]
Hi @christocracy, ok thank you.  Have you faced with this issue before?

**Comment by christocracy** [comment]
I have not experienced that ever.

I've been regularly field-testing daily for over 9 years.

**Comment by amarchenko25** [comment]
Hey @christocracy, are you able to test it on example app?
I cannot do it myself because we need to deploy the example app (to test the run from terminated state).
I would appreciate it because we need to understand wether we need to dig deeper or not

**Comment by amarchenko25** [comment]
Issue was related to another functionality which crashes app which runs from terminated state (capturing flutter widget on app start). Thx
