### ISSUE TITLE
Mass invoke of removeGeofence(id) occurs sqlite connection pool problem.

### ISSUE THREAD

**Issue by raphidlee** [transistorsoft/flutter_background_geolocation#1174]
## Your Environment
* Plugin version: 4.12.4
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Samsung Note 10 plus
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on Ubuntu 20.04.6 LTS 5.15.0-88-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "위치 엑세스 권한을 \"항상 허용\"으로 변경 해주세요.",
    "message": "보다 정확한 이벤트 알림을 위해서 필요하며, 사용자의 위치정보같은 민감정보는 외부로 공유 되지 않습니다.",
    "positiveAction": "변경하기",
    "negativeAction": "변경하지 않기"
  },
  "batchSync": false,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": 10,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 3,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxMonitoredGeofences": 97,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "위치서비스가 정상 동작 중입니다.",
    "text": "한 장소에 지속적으로 머무를때에는 이 알림이 표시 되지 않을 수 있습니다.",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": -1,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 0,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
```

## Expected Behavior

I want to remove tens of thounds of geofences with for each identifier; 
OR "removeGeofences(List<String> identifiers) " would be best;

## Actual Behavior

Mass removal of geofence makes sqlite connection leakage.
lot of sqlite connection pool error logs and  'blocking GC Alloc' started.

W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24061 (pool-6-thread-390) with flags 0x2 for 5.8700004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26577 (pool-6-thread-2906) with flags 0x1 for 5.8690004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 25739 (pool-6-thread-2068) with flags 0x1 for 6.8830004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 25754 (pool-6-thread-2083) with flags 0x1 for 6.873 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24657 (pool-6-thread-986) with flags 0x1 for 5.8710003 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24066 (pool-6-thread-395) with flags 0x2 for 5.8700004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24065 (pool-6-thread-394) with flags 0x2 for 5.8710003 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26582 (pool-6-thread-2911) with flags 0x1 for 5.872 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26575 (pool-6-thread-2904) with flags 0x1 for 5.873 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24067 (pool-6-thread-396) with flags 0x2 for 5.872 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 23714 (pool-6-thread-43) with flags 0x1 for 6.873 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26585 (pool-6-thread-2914) with flags 0x1 for 5.8700004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 24423 (pool-6-thread-752) with flags 0x1 for 6.8710003 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26583 (pool-6-thread-2912) with flags 0x1 for 5.872 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.
W/SQLiteConnectionPool(25142): The connection pool for database '+data+user+0+com_ddaysoft_lapho+databases+transistor_location_manager' has been unable to grant a connection to thread 26590 (pool-6-thread-2919) with flags 0x1 for 5.8700004 seconds.
W/SQLiteConnectionPool(25142): Connections: 0 active, 1 idle, 0 available.

I/.ddaysoft.laph(25142): Starting a blocking GC Alloc
I/.ddaysoft.laph(25142): Starting a blocking GC Alloc

## Steps to Reproduce

1. add 20,000 of geofences
2. remove 15,000 geofences with for each identifier; by 'bg.BackgroundGeolocation.removeGeofence(id)';
3.
4.

## Context

I am trying to manage groups of geofences. so, when I try to remove one of the group, I should remove many geofences that related with the group. The geofences can be tens of thounsands. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by raphidlee** [comment]
[Uploading background-geolocation.log.gz…]()

**Comment by christocracy** [comment]
Snow me the code.

**Comment by raphidlee** [comment]
`
        final filteredId = await findGeofenceIds(location.id!);//this could be tens of thounsands.
        for (var removableId in filteredId) {
          bg.BackgroundGeolocation.removeGeofence(removableId);
        }
`

**Comment by christocracy** [comment]
Use `await` with `.removeGeofence`

**Comment by raphidlee** [comment]
okay, make sense.
Is there any plan for 'removeGeofences(List<String> identifiers)', anyway?
