### ISSUE TITLE
[Android] Gaps in location data sent to server

### ISSUE THREAD

**Issue by petrslavotinek** [transistorsoft/flutter_background_geolocation#1178]
## Your Environment
* Plugin version: 4.13.5
* Platform: Android
* OS version: 11
* Device manufacturer / model: Pixel 2 XL
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3448], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.4)
X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
development with C++" workload, and include these components:
MSVC v142 - VS 2019 C++ x64/x86 build tools
- If there are multiple build tool versions available, install the latest
C++ CMake tools for Windows
Windows 10 SDK
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
await bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0.0,
      stopOnTerminate: false,
      startOnBoot: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      heartbeatInterval: 60,      
      // Android only
      enableHeadless: true,
      // auto upload to server
      url: '...',
      autoSync: true,
      maxDaysToPersist: 7,
      batchSync: true,
      maxBatchSize: 50,
    ));
```

## Expected Behavior
All collected location data is sent to server using built-in http service.

## Actual Behavior
Long periods of data is not sent to server in random intervals. Please see the [attached log](https://github.com/transistorsoft/flutter_background_geolocation/files/13451592/background-geolocation.log). The data missing on the server are:
from 10:53 to 11:55
from 13:07 to 14:03
from 14:04 to 14:42
After the period of the "outage", there's always a lot of records in the log in a very short time.

(Other devices were able to send their data at that time, so server side should be ok)

And thank you very much for all the support here. We're currently doing some extensive testing to see if we can use flutter and this plugin in production app.

**Comment by christocracy** [comment]
All your logs show the device sitting stationary, firing `onHeartbeat` and calling `.getCurrentPosition()` (apparently with `persist: false`).

Show me your `onHeartbeat` callback.

**Comment by petrslavotinek** [comment]
Headless handler looks basically like this:
```dart
@pragma('vm:entry-point')
void _backgroundLocationHandler(bg.HeadlessEvent headlessEvent) async {
  switch (headlessEvent.name) {
    case bg.Event.HEARTBEAT:
      final location = await bg.BackgroundGeolocation.getCurrentPosition(
        persist: false,
        desiredAccuracy: 10,
        timeout: 30000,
      );
      await DataService().reportPosition(location); // gRPC call to send data to server
      break;
  }
}
```

Logic in `onHeartbeat` is the same.
```dart
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) async {
      final location = await bg.BackgroundGeolocation.getCurrentPosition(
        persist: false,
        desiredAccuracy: 10,
        timeout: 30000,
      );
      await DataService().reportPosition(location); // gRPC call to send data to server
    });
```

Yes, `persist` is `false` and I send the data to the server using gRPC method.

I was now testing it with `persist: true` and there's another, but probably related, issue.
There's again a gap in the data and suddenly there are 50 records with the same timestamp - equivalent to the batch size.
There's one batch at 19:06:39 (gap between 18:16:16 and 19:06:39) and another at 20:37:25 (gap between 19:06:39 and 20:37:25).
I don't see any `INSERT` records in the [new log](https://github.com/transistorsoft/flutter_background_geolocation/files/13453218/background-geolocation.6.log) during these gaps.
