### ISSUE TITLE
Simple question about Android and license

### ISSUE THREAD

**Issue by marcsssss** [transistorsoft/flutter_background_geolocation#1179]
## Your Environment
* Plugin version: 4.12.0
* Platform: Android
* OS version: Android 13
* Device manufacturer / model: Android Studio Emulator - Pixel 5 API 33
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, 3.13.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/marcsessoms/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 months ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/marcsessoms/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 
```

## Expected Behavior

App launch in emulator without license issue

## Actual Behavior

LICENSE VALIDATION FAILURE
Invalid License key

## Steps to Reproduce

1.  App Launch
2.
3.
4.

## Context

Ask question before pushing to Google Play for alpha testing

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

I hope I have a simple question and I'm overthinking it. In the emulator, I get the "Invalid license key" message. I have quadruple-checked from the Wiki and Setup pages and compared the package name to the name used during registration.

Will the license work on a device even though I get the "Invalid license key" message in the emulator?

This package works GREAT on iOS with the tests that we have done so far and are looking to purchase several more licenses in the near future to use in our other apps. I appreciate the time and effort that has gone into it.

**Comment by christocracy** [comment]
The Android plug-in is fully functional in debug builds so you can try before you buy, in spite of license warning.

**Comment by marcsssss** [comment]
Yes, I understand that. And I have purchased a license. I'm sure it is something that I am doing wrong somewhere because I still get the message in the emulator. My question is if the license says invalid, and I have configured the app with the purchased license and followed all setup pages to the mark, should it work on a device regardless of me getting the message int he emulator?

**Comment by christocracy** [comment]
Email me the following info:
- Order #
- android/app/build.gradle

Do NOT post here in public.

**Comment by marcsssss** [comment]
Just making sure you got the email with the .txt attachment
