### ISSUE TITLE
Having problem with background on iOS

### ISSUE THREAD

**Issue by felipehbomfim** [transistorsoft/flutter_background_geolocation#1181]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version: 17.1
* Device manufacturer / model: 15 pro max
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  void initLocationThings() {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print(location);
      onData(location);
    });
    bg.BackgroundGeolocation.ready(bg.Config(
      geofenceModeHighAccuracy: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      stopTimeout: 1,
      deferTime: 5000,
      fastestLocationUpdateInterval: 5000,
      locationUpdateInterval: 5000,
      debug: false,
      reset: true,
      disableElasticity: true,
      stopOnTerminate: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    )).then((bg.State state) {
        bg.BackgroundGeolocation.start();
        startLocationUpdates();
        _startCountdownTimer();
    });
  }

  void startLocationUpdates() {
    locationUpdateTimer = Timer.periodic(Duration(seconds: 5), (timer) {
      print('oioi');
      bg.BackgroundGeolocation.getCurrentPosition(
        persist: true,
        samples: 3,
        desiredAccuracy: 10,
      );
    });
  }
```

## Expected Behavior
Get the location

## Actual Behavior
The location doesnt come on logs when in background

## Steps to Reproduce
1. Launch
2.
3.
4.

## Context
  I'm using the plugin for ios, android is working fine, I just wanna have the location every 5 seconds, but when I put my app in background on iOS, doesnt work
Just wanna have the location every 5 seconds, what's the best way that I can do it?

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version: ??

**Comment by christocracy** [comment]
>stopTimeout: 1,

Are you *sure* you want a `stopTimeout` of 1 minute?

>deferTime: 5000,

What do you think this *Android-only* option is for?

I'm not sure you know how this plugin operates.  Have you read the wiki "Philosophy of Operation".  This plugin is designed to track location when the device is detected to *be moving*.  When the device is detected to be sitting stationary, the plugin turns off location services to conserve energy.

>  debug: false,

Set this to `true` and go outside for a 1km walk.  You will hear debug sound FX from the plugin letting you know its working.

Only when the plugin is in the *moving* state will your dart `Timer` operate.  You can place the plugin into the *moving* state manually by calling `.changePace(true)` (after `.start()` has resolved).
