### ISSUE TITLE
How can I send a location fetch from every 15 minutes?

### ISSUE THREAD

**Issue by mthahas** [transistorsoft/flutter_background_geolocation#1183]
## Your Environment
* Plugin version: 4.11.1
* Platform: iOS and Android
* OS version:IOS10 + and Android 10+
* Device manufacturer/model: Apple and Realme
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
I want to capture the location fetch only for every 15 minutes. How can I implement it? 

## Actual Behavior

Now using distanceFilter we can set it based on distance. I want to generate location fetch based on time.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Implement background-fetch, already included here as a dependency.

See its readme then call .getCurrentPosition in the fetch callback.

**Comment by mthahas** [comment]
Does it work in both foreground and background mode?

**Comment by christocracy** [comment]
> Does it work in both foreground and background mode?

Yes.
