### ISSUE TITLE
Track geolocation without persist Notification in Android

### ISSUE THREAD

**Issue by thiaagodev** [transistorsoft/flutter_background_geolocation#1184]
Hi, it's possible to track location periodically in the background without showing notification?

**Comment by thiaagodev** [comment]
@christocracy I'm using this, do I have to pass the notification as null in the config? With this active, where do I get the location callback?

Another question, does the Android system have a time limit to leave the location service active in the background or can it die after a while?

**Comment by christocracy** [comment]
There is no possible way to prevent the notification periodically appearing.

To get location in the background requires on Android requires a "foreground service".

To use a foreground service requires a persistent notification.

> does the Android system have a time limit

With an activated foreground-service, there is no limit.
