### ISSUE TITLE
Inquiry on whether to use a library to obtain GPS location on Android

### ISSUE THREAD

**Issue by myksh7** [transistorsoft/flutter_background_geolocation#1186]
To obtain GPS location information on Android, Google provides FusedLocationProvider.

I am asking because I am curious about whether FusedLocationProvider can be used to obtain location information by switching between wifi, 3G/4G.

This is a case of inquiring about related technology to create a new app.

please answer about my question.

**Comment by christocracy** [comment]
> I am asking because I am curious about whether FusedLocationProvider can be used to obtain location information by switching between wifi, 3G/4G.

Yes.
