### ISSUE TITLE
Ability to send querystring via locationTemplate

### ISSUE THREAD

**Issue by AtomicRaven** [transistorsoft/flutter_background_geolocation#1187]
## Your Environment
* Plugin version: 4.12.0
* Platform: iOS 
* OS version: Ventura 13.6
* Device manufacturer / model: Dell
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.6 22G120 darwin-x64, locale en-US)
    • Flutter version 3.16.3 on channel stable at /Volumes/R/Rob/macOS/Development/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/robclarkson/Library/Android/sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.0

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.56.0)
    • VS Code at /Volumes/R/Rob/macOS/Development/apps/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (1 available)
    • Dad iPad (mobile) • 00008020-00164D6C3E80402E • ios • iOS 17.1.2 21B101

[✓] Network resources
    • All expected network resources are available.

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config config = bg.Config(
            reset: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            url: "${ENV.TRACKER_HOST + ENV.TRACKER_API}",
           locationTemplate: '?trid=$trid,data=[<%=latitude%>, <%=longitude%>, "<%=event%>", <%=is_moving%>]',         
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            },
            method: 'POST',
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true);
```

## Expected Behavior

USING [this Guide](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#locationtemplate)

Need ability to send data via querystring and not in json format:
http://{endpoint}?param1={param1},param2={param2},data={location.coords.latitude},{location.coords.longitude}

IE:
http://www.myserverendpoint.com?deviceId=123456&activity=moving,data=-42.86362,-175.14566

## Actual Behavior
Config.locationTemplate added to POST body as JSON and/or HTTP doesn't fire

## Steps to Reproduce

1. Add above locationTemplate param to bg.BackgroundGeolocation.Config
3. Run
4. request or simulate location
5. Observe:  Either HTTP call not made or data from locationTemplate is in body of request as json

## Context
POST the data to a server that I have no control over.  The server is expecting data in the format https://endpoint?data=latitude, longitude, accuracy...etc 

The endpoint is POST and all data is in querystring.  The 'Data' param needs comma separated values that are not key/value pairs

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Not possible.  That would not be a smart way of sending data to a server.

This will never be implemented
