### ISSUE TITLE
How can I fill the location parameter that I will send to the api source with current location information

### ISSUE THREAD

**Issue by NidaSns** [transistorsoft/flutter_background_geolocation#1188]
bg.Config params = new bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        //preventSuspend: true,
        stopOnTerminate: false,
        startOnBoot: true,
        url: 'http://215.244.134.125:6161/api/PostInfo',
        params: {
          "sicilno": sicilno,
          "location": *****
        },
        // Activity recognition options
        stopTimeout: 5,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        // HTTP & Persistence
        autoSync: true,
        enableHeadless: true,
        heartbeatInterval: 60);

**Comment by christocracy** [comment]
What kind of extra information are you hoping to add to the default schema?

**Comment by NidaSns** [comment]
Thank you for the quick answer. I solved it.
