### ISSUE TITLE
How do I implement Pre-Permission Checks for Background Geolocation Access in Mobile Apps

### ISSUE THREAD

**Issue by zsgithublib** [transistorsoft/flutter_background_geolocation#1195]
## Your Environment
* Plugin version: ^4.10.3
* Platform: iOS / Android
* OS version: 14.01 / mind sdk 33
* Device manufacturer / model: iPhone 14 / Pixel 8
* Flutter info (`flutter doctor`):N/A
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      geofenceInitialTriggerEntry: true,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              'Allow {applicationName} to access this device\'s location even when the app is closed or not in use.',
          message:
              'This app collects location data to enable Realtime Task Assignment & Performance Monitoring.'),
      // desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      // debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
        print('BackgroundGeolocation started');
      } else {
        print(
            'Not sure what happended. here is the BackgroudnGeolcoation state: ${state.enabled}');
      }
    });
  }
```

## Expected Behavior

I am looking for a method to verify whether location permissions have been already granted in my app. This check is necessary to decide if I should present a screen explaining the need for background geolocation permissions before actually prompting users for their consent via the background geolocation function. Is there a method to facilitate this? Android requires this functionality.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs onProviderChange and property `.providerState`
