### ISSUE TITLE
Inquiry about event handlers when Android apps are minimized

### ISSUE THREAD

**Issue by lillianho** [transistorsoft/flutter_background_geolocation#1198]
## Your Environment
* Plugin version: latest (^4.13.5)
* Platform: Android
* OS version: 13.0
* Device manufacturer / model: SM-G996B, SM-G981U, SM-G973F.
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.13.0, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.74.1)
[✓] VS Code (version 1.79.0-insider)
[✓] Connected device (3 available)
[✓] Network resources
* Plugin config:
```
bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 50.0,
    stationaryRadius: _stationaryRadius,
    geofenceProximityRadius: 20000,
    geofenceModeHighAccuracy: true,
    geofenceInitialTriggerEntry: true,
    stopOnTerminate: false,
    startOnBoot: true,
    logLevel: Environment.geofenceLogLevel,
    logMaxDays: Environment.logMaxDays,
    disableLocationAuthorizationAlert: true,
    enableHeadless: true,
    stopTimeout: 10,
    heartbeatInterval: 60,
    maxDaysToPersist: 1,
    url:
        "https://obfuscated/api/location",
    notification: bg.Notification(
      title: "Check-in locations nearby",
      text: "Tap to open app",
      channelName: "Locations",
      smallIcon: "drawable/ic_stat_name",
      largeIcon: "drawable/ic_stat_name",
    ),
  );
```

## Expected Behavior
We are expecting that when our Android app is in the background (app minimized and not terminated), that our registered event listener: bg.BackgroundGeolocation.onGeofence() will fire on geofence exit/enter. We register our event handlers on the initalization of runApp().

## Actual Behavior
Our experience is that for Android applications on OS 13, sometime after launching & minimizing our app, registered geofence event handlers stop being fired. 

We support a wide range of devices including Android devices (All sorts of vendors) on lower versions of Android OS, as low as OS 9, as well as iOS devices and have had less issues with event handlers firing, so we suspect it may have something to do with the OS of the devices. We've received increased reports of issues in the last year.

We are aware of https://dontkillmyapp.com, and understand it may be playing a factor in inhibiting app functionalities, but we wanted to make sure we are not missing something obvious because we have tried using the demo app (https://github.com/transistorsoft/flutter_background_geolocation#-demo-application) and find the event handlers to be quite responsive. 

We have also used the demo app to improve our own app - we were behind in implementing some newer recommended configurations (e.g https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md), but that hasn't improved our situation.

We only test with physical devices and are aware that movement is required for the plugin to resume tracking. Our physical tests consists of walking out/into a geofence and then holding/waiting for a geofence event (walking -> still). We walk a fair bit, at least ~200 meters beyond last stationary location.

Observing the sdk logs, we can tell that our movements are recorded accurately - we can see geofence events and they correlate to the times in which they occurred, but the associated feedback/ event handlers of those events are not fired, we are sure of this because as a result of the event handlers running, we call our own backend api services to perform a corresponding action and we can see very clearly that those actions are not occurring consistently.

What gets the event handlers functional again is terminating the app and then relaunching it, which basically just calls runApp() again, causing the event handlers to re-initialize. We also have customers who say that relaunching the app without termination also helps to kick start the event handlers - we have experienced this to be true as well.

We are currently toying with the idea of using the plugin's built in HTTPS service (hence a url is defined in our config, but its not productionized) as a fallback to perform the action we wish the event handlers were calling because we find it to be reliable in relaying geofence events, regardless of the app's state, but we would still love to understand why the app's event handlers may not be firing as expected. Best case scenario is that we don't need to rely on the plugin's built in HTTPS service.

Apologies for the detail, and we appreciate any suggestions you may have for us.
Many thanks for your attention.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You have not provided any code, especially your event listener you state you're having a problem with.

**Comment by lillianho** [comment]
Yes, sure thing,

The following is a snippet of the event listeners we are registering

```
  Future<void> registerEventListener() async {

    bg.BackgroundGeolocation.onLocation(
      (data) => enqueue(GeolocationEvent(bg.Event.LOCATION, data)),
    );
    bg.BackgroundGeolocation.onMotionChange(
      (data) => enqueue(GeolocationEvent(bg.Event.MOTIONCHANGE, data)),
    );
    bg.BackgroundGeolocation.onProviderChange(
      (data) => enqueue(GeolocationEvent(bg.Event.PROVIDERCHANGE, data)),
    );
    bg.BackgroundGeolocation.onActivityChange(
      (data) => enqueue(GeolocationEvent(bg.Event.ACTIVITYCHANGE, data)),
    );
    bg.BackgroundGeolocation.onGeofence(
      (data) => enqueue(GeolocationEvent(bg.Event.GEOFENCE, data)),
    );
    bg.BackgroundGeolocation.onGeofencesChange(
      (data) => enqueue(GeolocationEvent(bg.Event.GEOFENCESCHANGE, data)),
    );
    bg.BackgroundGeolocation.onConnectivityChange(
      (data) => enqueue(GeolocationEvent(bg.Event.CONNECTIVITYCHANGE, data)),
    );
    bg.BackgroundGeolocation.onEnabledChange(
      (data) => enqueue(GeolocationEvent(bg.Event.ENABLEDCHANGE, data)),
    );
    bg.BackgroundGeolocation.onPowerSaveChange(
      (data) => enqueue(GeolocationEvent(bg.Event.POWERSAVECHANGE, data)),
    );

    await _ensureReady(); // Configure the plugin and signal to the plugin that the app is ready
  }
```

The following is the instantiation of the event handlers

```

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();

    GeofenceService.instance.registerEventListener();
    WidgetsBinding.instance.addObserver(this);
  }
}
```

And the following is the main method that calls the app to run

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await initializeFirebase();
  await ensureHiveInitialized();

  Function onError = FlutterError.reportError;
  FlutterError.onError = (FlutterErrorDetails errorDetails) async {
    await FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
    // Forward to original handler.
    onError(errorDetails);
  };

  // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  runApp(App());

  /// Register BackgroundGeolocation headless-task.
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);

  /// Register BackgroundFetch headless-task.
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

Do let me know if there's any more detail you require.
Many thanks.

**Comment by lillianho** [comment]
Hi, @christocracy,

Re-raising as my previous response may have been missed.
Many thanks.

**Comment by christocracy** [comment]
>but the associated feedback/ event handlers of those events are not fired, we are sure of this because as a result of the event handlers running, we call our own backend api services to perform a corresponding action and we can see very clearly that those actions are not occurring consistently.

I only care if the plugin's event-handler is being called.  The performance of your own HTTP requests is not the plugin's responsibility.  Search the API docs `Logger` and learn how to insert your own custom log-messages into the plugin logs.  Add a custom log-message into your `onGeofence` event-handler to confirm the event was fired **on the device**.

**Comment by lillianho** [comment]
Hello Chris,

> The performance of your own customer HTTP requests with `dart` code is not the plugin's responsibility.

Out customer HTTP requests with `dart` code is made following the plugin's firing of an event, and we are concerned because it seems like the plugin event handler isn't being fired.

Our code looks something like:

```
 Future<void> registerEventListener() async {
    bg.BackgroundGeolocation.onGeofence(
      (data) => enqueue(GeolocationEvent(bg.Event.GEOFENCE, data)),
    );
    await _ensureReady(); // Configure the plugin and signal to the plugin that the app is ready
  }
    
  Future<void> enqueue(GeolocationEvent<dynamic> geolocationEvent) async {
    await BGLogger.info(GeofenceService, 'enqueue', geolocationEvent);
    return bg.BackgroundGeolocation.startBackgroundTask()
        .then((int taskId) async {
      // Customer HTTP request is not fired and no errors are thrown, even though the geofence event was recognised according to the sdk logs and our custom logger
      // This leads us to believe that the event handler is not being called
      await http
          .post(Uri.parse("https://obfuscated/api/event"),
              headers: {"Content-Type": "application/json"},
              body: jsonEncode({
                "eventType": "Geofence",
              }))
          .then((value) => bg.BackgroundGeolocation.stopBackgroundTask(taskId))
          .catchError((dynamic error) =>
              bg.BackgroundGeolocation.stopBackgroundTask(taskId));
    });
  }
```

We do use the logger to insert our own custom log-messages into the plugin logs, thanks for the suggestion. As mentioned in my initial comment:

> Observing the sdk logs, we can tell that our movements are recorded accurately - we can see geofence events and they correlate to the times in which they occurred, but the associated feedback/ event handlers of those events are not fired.

I have added some logs for your interest. I have masked the lat/long as that's sensitive.

## Debug logs
<details>
	<summary>Logs</summary>

```
11-10 10:20:35.365 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce
╚═════════════════════════════════════════════
11-10 10:20:35.459 INFO [TSLog log] 
  ℹ️  [GeofenceService enqueue] [GeolocationEvent name: location, data: [Location {odometer: 783978.375, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 0.88, is_charging: false}, uuid: ecdd6032-2d7e-458a-9124-bd14996cd811, age: 157, coords: {altitude: 26.8, heading: -1.0, latitude: -00.0000000, accuracy: 20.0, heading_accuracy: -1.0, altitude_accuracy: 1.7, speed_accuracy: -1.0, speed: -1.0, age: 192, longitude: 000.0000000, ellipsoidal_altitude: 26.8}, is_moving: false, timestamp: 2023-11-09T21:20:35.214Z}], id: 3b94c0d5-3356-4621-b09e-57ef8c4a9e72, isHeadless: false]
11-10 10:20:35.538 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: ca975296-c4a0-4563-be31-034a83aeac1e
11-10 10:20:35.583 INFO [TSLog log] 
  ℹ️  [GeofenceService enqueue] [GeolocationEvent name: geofence, data: [GeofenceEvent identifier: e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce, action: ENTER, timestamp: 2023-11-09T21:20:35.509Z], id: dfea72dd-e534-48dc-b62e-7feb465bd3c8, isHeadless: false]
11-10 10:20:35.757 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 27
11-10 10:20:35.759 INFO [TSLog log] 
  ℹ️  [GeofenceService _runBackgroundTask] [GeolocationEvent name: location, data: [Location {odometer: 783978.375, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 0.88, is_charging: false}, uuid: ecdd6032-2d7e-458a-9124-bd14996cd811, age: 157, coords: {altitude: 26.8, heading: -1.0, latitude: -00.0000000, accuracy: 20.0, heading_accuracy: -1.0, altitude_accuracy: 1.7, speed_accuracy: -1.0, speed: -1.0, age: 192, longitude: 000.0000000, ellipsoidal_altitude: 26.8}, is_moving: false, timestamp: 2023-11-09T21:20:35.214Z}], id: 3b94c0d5-3356-4621-b09e-57ef8c4a9e72, isHeadless: false]
11-10 10:20:35.784 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 27
11-10 10:20:35.891 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 28
11-10 10:20:35.895 INFO [TSLog log] 
  ℹ️  [GeofenceService _runBackgroundTask] [GeolocationEvent name: geofence, data: [GeofenceEvent identifier: e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce, action: ENTER, timestamp: 2023-11-09T21:20:35.509Z], id: dfea72dd-e534-48dc-b62e-7feb465bd3c8, isHeadless: false]
11-10 10:20:37.339 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 28
```
</details>

> Why are you event performing custom http requests with dart code when the plugin has a built-in http service implemented with pure native code?

We are testing the built-in http service, it's not currently used production, ideally, we wouldn't have to use it at all. The best case scenario is that we can just rely on just the event handlers to stimulate our customer HTTP requests when they are fired.

As mentioned in my initial comment:
> We are currently toying with the idea of using the plugin's built in HTTPS service (hence a url is defined in our config, but its not productionized)

Its not that the event handlers aren't registered properly, or that our customer HTTP requests are defined incorrectly or that our `dart` code is unreliable, as this seems to be platform specific to Android devices on OS 13. We have minimal issues with our iOS customers and Android customers on OS < 13.

Hopefully that answers any feedback you had.

Many thanks for your attention.

**Comment by christocracy** [comment]
I want you to forget about your http requests.

Simply add a custom log message in your onGeofence event.  Verify the event fires.  If a log message appears, the plug-in's responsibility ends.

It's not unheard of that dart-based http requests (or JavaScript in the m React Native, Cordova or Capacitor versions of this plugin) have problems in the background where the plug-in's own built-in, pure native http requests **do not**.

**Comment by lillianho** [comment]
Hello @christocracy,

Forgetting our http requests, we log a message whenever an event fires:

```
Future<void> enqueue(GeolocationEvent<dynamic> geolocationEvent) async {

    // Logged message in case of onGeofenceEvent
    await BGLogger.info(GeofenceService, 'enqueue', geolocationEvent);
    
    // Forget what's below
    return bg.BackgroundGeolocation.startBackgroundTask()
        .then((int taskId) async {
      // Customer HTTP request is not fired and no errors are thrown, even though the geofence event was recognised according to the sdk logs and our custom logger
      // This leads us to believe that the event handler is not being called
      await http
          .post(Uri.parse("https://obfuscated/api/event"),
              headers: {"Content-Type": "application/json"},
              body: jsonEncode({
                "eventType": "Geofence",
              }))
          .then((value) => bg.BackgroundGeolocation.stopBackgroundTask(taskId))
          .catchError((dynamic error) =>
              bg.BackgroundGeolocation.stopBackgroundTask(taskId));
    });
  }
```

A custom log is not always logged when we have a `Geofencing event`. 

We have a lot of evidence of this, and the logs that comes before / after Geofencing Event: ENTER/ EXIT is not always the same, but the behaviour that is consistent is that: our custom log does not follow from Geofencing Event: ENTER/ EXIT.

<details>
	<summary>Evidence of geofencing event but no corresponding custom log</summary>

```
11-03 08:55:20.552 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce
╚═════════════════════════════════════════════
11-03 08:55:20.564 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 38f4aab3-e692-4b65-a950-5e590e7b1826
11-03 08:55:32.499 INFO [TSScheduleManager cancelOneShot] 
  ⏰ Cancel OneShot: MOTION_ACTIVITY_CHECK
11-03 08:55:32.503 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 7b64bb0f-8a0f-4aa7-8f8e-2cd7447f78bf
11-03 08:55:32.504 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: MOTION_ACTIVITY_CHECK in 74999ms (jobID: -18513055)
11-03 08:56:47.520 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: MOTION_ACTIVITY_CHECK
╠═════════════════════════════════════════════

11-03 08:56:47.522 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
11-03 08:56:48.740 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🎾  ENTER: in_vehicle
╚═════════════════════════════════════════════
11-03 08:57:29.150 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: in_vehicle
╟─ 🎾  ENTER: walking
╚═════════════════════════════════════════════
11-03 08:57:59.296 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: walking
╟─ 🎾  ENTER: still
╚═════════════════════════════════════════════
11-03 08:57:59.304 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: STOP_TIMEOUT in 300000ms (jobID: 2059034116)
11-03 09:02:59.323 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: STOP_TIMEOUT
╠═════════════════════════════════════════════

11-03 09:02:59.333 INFO [HeartbeatService stop] 
  🔴  Stop heartbeat
11-03 09:02:59.336 INFO [TSLocationManager d] 
  🔴  Location-services: OFF
11-03 09:02:59.338 INFO [TrackingService changePace] 
  🔵  setPace: true → false
11-03 09:02:59.365 INFO [TSLocationManager a] 
```
</details>

We didn't get a onGeofence event log until another Geofencing Event: ENTER event was triggered a little while later

<details>
	<summary>Evidence of geofencing event firing a while later</summary>

```
11-03 09:43:20.681 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce
╚═════════════════════════════════════════════
11-03 09:43:20.682 WARN [GeofencingService a] 
  ℹ️  Replaced geofence trigger location with current location (distance: 0.6979239)
╟─ 📍  Trigger location (age: 2025690ms): Location[fused -00.000000,000.000000 hAcc=13.374 et=+7d11h51m20s271ms alt=27.100000381469727 vAcc=1.36912]
╟─ 📍  Current location (age: 22989ms): Location[fused -00.000000,000.000000 hAcc=13.147 et=+7d12h24m42s972ms alt=27.100000381469727 vAcc=1.225865 vel=0.62922776 bear=279.77307]
╚═════════════════════════════════════════════
11-03 09:43:20.685 INFO [TSLog log] 
  ℹ️  [GeofenceService enqueue] [GeolocationEvent name: location, data: [Location {odometer: 611903.6875, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 0.85, is_charging: false}, uuid: afc9ef17-8fda-4b64-af41-54a682ed0cd7, age: 22990, coords: {altitude: 27.1, heading: 279.77, latitude: -00.0000000, accuracy: 13.1, heading_accuracy: -1.0, altitude_accuracy: 1.2, speed_accuracy: -1.0, speed: 0.63, age: 22992, longitude: 000.0000000, ellipsoidal_altitude: 27.1}, is_moving: false, timestamp: 2023-11-02T20:42:57.693Z}], id: 89de60cf-ef7b-416b-83ff-5e5b7ecbe4ae, isHeadless: false]
11-03 09:43:20.686 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 2fe118c2-d15d-403e-a244-910cf1c865d0
11-03 09:43:20.687 INFO [TSLog log] 
  ℹ️  [GeofenceService enqueue] [GeolocationEvent name: geofence, data: [GeofenceEvent identifier: e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce, action: ENTER, timestamp: 2023-11-02T20:43:20.686Z], id: b4f2d68e-005e-4a1c-809a-a2dd9e8590fa, isHeadless: false]
11-03 09:43:22.092 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 15
11-03 09:43:22.136 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 16
11-03 09:43:22.137 INFO [TSLog log] 
```
</details>

Please elaborate on the following, we are just looking for a reason for why we are experiencing this phenomena, so any details are welcome.
> It's not unheard of that dart-based http requests (or JavaScript in the m React Native, Cordova or Capacitor versions of this plugin) have problems in the background where the plug-in's own built-in.

We recognise this, and our experience so far is that it's very reliable.
> pure native http requests do not.

We are apprehensive of using the http service because the http service delivers location coordinates of our users to our backend, which we want to avoid, privacy is very important to us and our customers, hence why we want to process as much as possible on the customer's device. We never post location info to our api, only that someone has exited or entered a geofence.

We only care about the GeofenceEvent? property in the http request/location body. Is there anyway to strip/mask everything but the GeofenceEvent from the http request/location body that is delivered via the http service? 

Even better: If there was a way to post to an endpoint using the plug-in's own built-in http service in the event of an onGeofenceEvent.

**Comment by christocracy** [comment]
>Plugin version: latest (^4.13.5)

>11-03 09:43:20.681 INFO [GeofencingService a] 
>╔═════════════════════════════════════════════
>║ Geofencing Event: ENTER
>╠═════════════════════════════════════════════
>╟─ e3e8f8ed-3d5d-499f-9b39-f501e1fa11ce
>╚═════════════════════════════════════════════

Your logs show a date of `11-03` but version `4.13.5` was not released until `11-16`, so your logs cannot have come from `v4.13.5`

Are you reproducing this yourself?  I suggest you attempt to reproduce using `4.12.3`.

The event-handling plumbing has not been touched *in years* and nobody has *ever* reported anything like this (in *any* version of the plugin, including React Native, Cordova and Capacitor).  The `/example` app uses the `onGeofence` event to render markers to a map.  I've never experienced missing event-markers on the map.

**Comment by lillianho** [comment]
We've been having this issue for a long time. As we are still testing the latest version of the plugin, we don't have as many logs to draw on.

The logs that I posted before were created using version 4.12.3 of the plugin, sorry, I didn't clarify this. And yes, it was produced by us.

When you say you haven't missed any event-markers, do you mean when you are observing the app whilst it is open and running in the foreground or something else?

Re-raising questions that were unanswered in my last comment:

Please elaborate on the following, we are just looking for a reason for why we are experiencing this phenomena, so any details are welcome.
> It's not unheard of that dart-based http requests (or JavaScript in the m React Native, Cordova or Capacitor versions of this plugin) have problems in the background where the plug-in's own built-in.

We are apprehensive of using the http service because the http service delivers location coordinates of our users to our backend, which we want to avoid, privacy is very important to us and our customers, hence why we want to process as much as possible on the customer's device. We never post location info to our api, only that someone has exited or entered a geofence.

We only care about the GeofenceEvent? property in the http request/location body. Is there anyway to strip/mask everything but the GeofenceEvent from the http request/location body that is delivered via the http service? 

Even better: If there was a way to post to an endpoint using the plug-in's own built-in http service in the event of an onGeofenceEvent.

Thank you again for your attention.

**Comment by christocracy** [comment]
>When you say you haven't missed any event-markers, do you mean when you are observing the app whilst it is open and running in the foreground or something else?

I take my devices out for field-testing daily in a backpack.  They run complete in the background.  I observe them when I return.

The *large* green circles are geofences.  The small `yellow`, `red` and `green` dots on the perimeter are map-markers rendered in the `onGeofence` event (*dwell, exit and enter*, respectively).

![IMG_0400](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/e5940694-276c-400d-b4c6-96718f5dff9c)

>We never post location info to our api, only that someone has exited or entered a geofence.

You should either use geofences-only mode (`.startGeofences()`) or use `Config.persistMode` to specify that only geofences are persisted to the plugin's SQLite db (the http service feeds only upon records found in SQLite).

>strip/mask everything but the GeofenceEvent from the http request/location body that is delivered via the http service?

See API docs "HTTP Guide" (linked throughout) and `Config.geofenceTemplate`

**Comment by christocracy** [comment]
I also compare with the results posted to the demo server at https://tracker.transistorsoft.com.

<img width="950" alt="Screenshot 2024-01-18 at 11 03 05 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/377f93e7-7597-4c2a-bc51-813d67ea2597">

**Comment by lillianho** [comment]
Hello @christocracy,

Thank you for responding to those questions. They were most helpful.

How do I evaluate the general accuracy of a location reading?

<details>
	<summary>Location reading</summary>

```
{
  "location": {
    "event": "geofence",
    "is_moving": true,
    "uuid": "58f98a99-7526-4239-ba7b-9011c8614d0c",
    "timestamp": "2024-01-24T20:36:17.431Z",
    "age": 473,
    "odometer": 0,
    "coords": {
      "latitude": -00.000000,
      "longitude": 000.000000,
      "accuracy": 5,
      "speed": 1.19,
      "speed_accuracy": -1,
      "heading": 243.86,
      "heading_accuracy": -1,
      "altitude": 101.1,
      "ellipsoidal_altitude": 101.1,
      "altitude_accuracy": 2.2,
      "age": 479
    },
    "activity": {
      "type": "walking",
      "confidence": 100
    }
  }
}
```
</details>

There are a few accuracy measures like the 'confidence' of the walking activity, heading/speed/altitude accuracy from coords and so on.

We have customers who work in an area that is surrounded by several telecom towers and depending on the tower that their device is connected to, their location readings will ping closer to the location of the connected tower, even if their true location is 400m away.

We were hoping that the accuracy measures can help us to evaluate if a location reading is too unlikely to be true and to ignore those location events, we just aren't sure which ones to pay attention to and unsure what values constitutes a good reading.

Many thanks for your continued support,
Lillian

**Comment by christocracy** [comment]
> There are a few accuracy measures like the 'confidence' of the walking activity, heading/speed/altitude accuracy from coords and so on.

See the api docs "Location".  Each attribute is explained there.

**Comment by lillianho** [comment]
Hello @christocracy,

Another question about the following config:
https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#motiontriggerdelay

What would be a sufficient delay in your opinion for the following in our scenario with the telecom towers?

Would 30 seconds be enough of a delay?

Many thanks,
Lillian

**Comment by christocracy** [comment]
What do you think that option is for?

**Comment by lillianho** [comment]
Hello @christocracy,

According to the documentation, setting a motion trigger delay on Android is supposed to reduce false positive motion triggering.

Our customers really aren’t moving very much to warrant moving 400m in a single second. 

Do advise if that’s not true.

Kind regards, 
Lillian

**Comment by christocracy** [comment]
>Our customers really aren’t moving very much to warrant moving 400m in a single second

**Nothing** moves at 400 m/s (1440 km/h), not even a jet at cruising speed.

That's not what `motionTriggerDelay` is for.  `motionTriggerDelay` is to prevent, for example, unwanted motion-triggering while walking around your house / office.
