### ISSUE TITLE
Purgue also runs on debug builds and may slow down compilation 

### ISSUE THREAD

**Issue by danielgomezrico** [transistorsoft/flutter_background_geolocation#1199]
## Your Environment
* Plugin version: 4.13.5
* Platform: android
* OS version: 14
* Device manufacturer / model: Pixel
* Flutter info (`flutter doctor`): 3.16.4

## Expected Behavior
The message does not appear and also a preprocess is not done on debug builds, it can slow down the builds in the day-to-day development flow

## Actual Behavior
Everytime I build, even on debug builds I see this warning:
> [flutter_background_geolocation] Purging debug resources in release build

Why is required to purge things on debug too?
It sounds confusing to me because it says "in release build" but it happens also on debug builds

## Steps to Reproduce
Add the sdk to a project and run `flutter run`

## Context
Im trying to avoid loosing time waiting for this purge to run on each debug build in my day to day work

**Comment by christocracy** [comment]
> Why is required to purge things on debug too?

It's not actually doing anything.  It's only logging a message before the actual logic is evaluated.

And the actual purging takes a couple of milliseconds.

You do not need to worry about this.  Ignore it.
