### ISSUE TITLE
Allow dynamic attributes for HTTP requests

### ISSUE THREAD

**Issue by danielgomezrico** [transistorsoft/flutter_background_geolocation#1200]
I need to have the background reporting service running and calling an HTTP server with updates and to authenticate all requests, I'm using the `Config.headers` attribute.

The issue is that this is a map, so I need to have the value the moment I will start the service, but that token may change over time and then all subsequent requests may fail.

Im currently using `Aws Cognito` and they offer a `Future` function that will return the current valid token (even when it was refreshed it returns the valid one).

## Your Environment
* Plugin version: 4.13.5
* Platform: Android
* OS version: 14
* Device manufacturer / model: Pixel
* Flutter info (`flutter doctor`): flutter 3.16.4

## Expected Behavior
I was wondering if there's any way that the background job uses a method to get the values instead of sending a map of them.

```dart
Config(
      url: url,
      headers: () async {
         final token = await fetchToken();

         return {
           'Content-Type': 'application/json',
             'Authorization': 'Bearer $token'
         }
     },
```

## Actual Behavior
You have to send only a map with the fixed values on config like:

```dart
Config(
      url: url,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer the-token' // Here
      },
```

## Context
I was trying to monitor when the AWS token changes and then restart this service with the newest value, but sadly, they don't offer a way to be notified when the token gets invalid.

I'm thinking that I will have to have a background job every hour or so checking if the token changed to restart the GPS job and seems like a lot just for this 🤔 

I could use this https://pub.dev/packages/background_fetch to do it, but I wondered if there was a way for this to make it from here.

**Comment by christocracy** [comment]
> was wondering if there's any way that the background job uses a method to get the values

No.  Await your token *before* calling .ready(config).

To update Config *after* .ready(config) has been called, use method .setConfig(newConfig)

**Comment by danielgomezrico** [comment]
@christocracy did you read the hole issue? I mention that is not that simple to "await your token before calling"

**Comment by christocracy** [comment]
> that is not that simple to 

When you have received your token, call .ready.

>"await your token before calling"

It's not "my" token, it's *your token*.

**Comment by danielgomezrico** [comment]
@christocracy I was thinking that maybe creating the job by myself using https://pub.dev/packages/background_fetch and handling this token changes from there would be better than relying on this HTTP param for my use case, WDYT? 

At the end, the background GPS job uses this to create its job and could result with the same reliability that the transistor GPS SDK offers?

**Comment by christocracy** [comment]
When your token fails, onHttp will return a failure code (probably 401).  That's your cue to refresh your token.

> At the end, the background GPS job uses this to create its job and could result with the same reliability that the transistor GPS SDK offers?

Why do you think that?  What is a "background gps job"?

**Comment by danielgomezrico** [comment]
- "Background gps job" is the background job that sends the HTTP via this SDK
- I dont see a way to get from that when it fails, I know it will retry, but I dont get the callback I can again the SDK with the new token

So I was thinking that maybe this use case is a bit extra from what the SDK handles and that I could start my own background job, listening for locations and send the HTTP request by myself using the background_fetch plugin 🤔, WDYT?

**Comment by christocracy** [comment]
iOS doesn't allow background-fetch events to fire after app terminate.

Just use background-geolocation built-in http service, listen to onHttp for failure codes.  When you get 401, refresh your token.  Easy.

**Comment by danielgomezrico** [comment]
Oh! do you mean that I can listen http requests with:

```dart
bg.BackgroundGeolocation.onHttp((e) {
    if (e.status == 401)  {
        // Refresh
      }
  });
```

O totally missed that, thanks!

**Comment by christocracy** [comment]
I suggest you read the api docs and learn about all the 13 events that are available you.
