### ISSUE TITLE
I still get the "License verification failed error even after purchasing license and adding key to AndroidManifest"

### ISSUE THREAD

**Issue by toplinegroupafrica** [transistorsoft/flutter_background_geolocation#1202]
## Your Environment
* Plugin version:
```yaml
flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
```
* Platform:
Android
* OS version:
13
* Device manufacturer / model:
SM-A225F
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.6 21G115 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        debug: true,
        enableHeadless: true,
        reset: true,
        preventSuspend: isWithinWorking,
        heartbeatInterval: 60,
        persistMode: bg.Config.PERSIST_MODE_ALL,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Promorama to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification: bg.Notification(
          title: "Topline Promoters",
          text: "Tracking your location",
          color: "#ff0000",
          smallIcon: "mipmap/ic_launcher",
          largeIcon: "mipmap/ic_launcher",
          channelName: "Topline Promoters",
        ),
        stopOnTerminate: false,
        startOnBoot: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      )
```

## Expected Behavior

Before we purchased the license, it showed a toast on app launch that said "License verification failed Invalid License Key <Enter Key Here>". We expected that the toast would leave once we purchase a license and add the key to the AndroidManifest

## Actual Behavior

The toast still comes up on app launch and now it just puts the key there in the toast. "License verification failed Invalid License Key 5fb...". However this is only the case in release, it doesn't show the toast in debug. 
![photo_2023-12-30 15 20 22](https://github.com/transistorsoft/flutter_background_geolocation/assets/135315178/e67e7489-87d3-49d3-abbf-b3eb2f1429d3)

**Comment by christocracy** [comment]
**Email me** the following info:
- Order #
- android/app/build.gradle
- AndroidManifest

Do **NOT** post here in the public

**Comment by toplinegroupafrica** [comment]
> **Email me** the following info:
> 
> * Order #
> * android/app/build.gradle
> * AndroidManifest
> 
> Do **NOT** post here in the public

Sent. 
Thanks and happy holidays

**Comment by christocracy** [comment]
Why did you not perform **ALL** the [Setup Instructions](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidappbuildgradle)?  Everything in *green* is **required.**

```gradle
buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
```

**Comment by toplinegroupafrica** [comment]
Everything works fine now, thanks so much for the help.
