### ISSUE TITLE
headless is not working in debug mode 

### ISSUE THREAD

**Issue by AniketStemmOne** [transistorsoft/flutter_background_geolocation#1203]
# I was trying to save the location data but it not saving in Firebase database 

## Here are code headless event

 case bg.Event.HEARTBEAT:
      bg.HeartbeatEvent event = headlessEvent.event;
      print('- HeartbeatEvent: $event');
      Firebase.initializeApp();
      FirebaseFirestore.instance.collection("testingTracking").add({
        "data": {
          "longitude": event.location!.coords.longitude,
          "latitude": event.location!.coords.latitude
        }
      });
      break;
      
   ###  not working please help me out

**Comment by christocracy** [comment]
The issue template is not optional, it's required,
