### ISSUE TITLE
Allow log to show the Http Request body

### ISSUE THREAD

**Issue by danielgomezrico** [transistorsoft/flutter_background_geolocation#1204]
I'm using HTTP requests to call my backend, but I see that it answers with `422 Unprocessable entity`.

I would like to see the request that this SDK sends, so I can be sure what I'm sending to them, but I see that we only have this listener that shows the response but not the request itself:

```dart
BackgroundGeolocation.onHttp((response) {});
```

How can I see what are we sending?

## Your Environment
* Plugin version: 4.13.5
* Platform: Android
* OS version: 14
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`): 
```yaml
environment:
  sdk: 3.2.3
  flutter: 3.16.4
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
      // Run setup
      autoSync: true,
      foregroundService: true,
      stopOnTerminate: false,
      startOnBoot: true,
      desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,

      // Filters
      useSignificantChangesOnly: true,
      disableElasticity: false,
      disableMotionActivityUpdates: false,
      reset: true,

      // Url Request
      url: url,
      locationTemplate: '{ "gps_datetime": "<%= timestamp %>" }'
      httpRootProperty: '.',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $authToken'
      },
      params: {
        'param1': 'value1'
      },
```

## Expected Behavior
I can see on logs or on any listener the request that has been sent

## Actual Behavior
I can see only the response

## Context
Im trying to use `autoSync` and http requests from this SDK to update the location

**Comment by christocracy** [comment]
You can inspect outgoing http in Android studio with Tools->App Inspector

**Comment by danielgomezrico** [comment]
The `Tools->App Inspector` works perfectly, thanks
