### ISSUE TITLE
Whenever background fetch is received, location is automatically read together

### ISSUE THREAD

**Issue by slowdh** [transistorsoft/flutter_background_geolocation#1206]
## Your Environment
* Plugin version: ^4.13.3
* Platform: iOS
* OS version: 14.7.1
* Device manufacturer / model: Apple / iPhone 8
* Flutter info (`flutter doctor`):
  [✓] Flutter (Channel master, 3.16.0-17.0.pre.5, on macOS 13.6 22G120 darwin-arm64, locale ko-KR)
  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
  [✓] Xcode - develop for iOS and macOS (Xcode 15.0)
  [✓] Chrome - develop for the web
  [✓] Android Studio (version 2022.2)
  [✓] VS Code (version 1.74.3)
  [✓] VS Code (version 1.74.3)
  [✓] Connected device (6 available)
  [✓] Network resources

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      reset: true,
      url: LOCATION_FUNCTION_REQUEST_URL,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20.0,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: HAS_DEBUG_FEEDBACK,
      stationaryRadius: 10.0,
      stopTimeout: 3,
      locationTimeout: 30,
      logLevel: HAS_DEBUG_FEEDBACK
          ? bg.Config.LOG_LEVEL_VERBOSE: bg.Config.LOG_LEVEL_OFF,
      autoSync: true,
      geofenceInitialTriggerEntry: true,
      params: {
        'projectId': projectId,
        'projectName': projectName,
        'userId': userId,
      })
```

## Expected Behavior

Background fetch is running and reading location even when background_fetch is not set up explicitly in iOS.
I expect background fetch to run just my own code (when not been set and init, do nothing), not any additional code which is not mine: reading location.

How can I decouple default reading location function with my own fetch function?

## Actual Behavior

Even background_fetch plugin is not explicitly imported and initiated in the code block, background fetch is received regularly in iOS devices. 
And whenever fetch is received, location is read together.

## Steps to Reproduce

This behavior happens the same in the example ‘advanced’ app with removing inside '_configureBackgroundFetch' function block .

1. start advanced example app with xcode.
2. in the xcode, run ‘Debug > Simulate Background Fetch’.
3. get location read indication (gps logo) in the device and location result is received later.
4. location read log is also properly logged.

## Context

Recent iOS shows up alert messages like ‘”THIS APP” has used your location X times in the background over the past 3 days. Do you want to continue to allow background location use?”
with location read history in the map. (I understand there is no exception to any apps, but want to minimize impact.)

We are using this plugin for purpose of automatic attendance checking & hazardous area enter checking. We mainly use Geofencing + toggling modes only inside service area.

The problem is, when background fetch (and location read) happens in user’s private location like home or travel area and gets a feedback from OS later, most of users gets strongly motivated turn off the ‘always allow’ authorization.
**We want to control when/where app reads location**. 
For example check sharedPreference boolean value and continue read location, or limit time of day fetch is active.
Or stop background fetch functionality.

For now, fetch is run regardless of how fetch code is written and location is read together. We want to deal with this.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2024-01-08 16:45:43.344358+0900 BG Geo[1129:387199] BackgroundFetch AppDelegate received fetch event
2024-01-08 16:45:43.344920+0900 BG Geo[1129:387199] [TSBackgroundFetch performFetchWithCompletionHandler]
2024-01-08 16:45:43.345597+0900 BG Geo[1129:387199] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2024-01-08 16:45:43.350018+0900 BG Geo[1129:387864] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager startMonitoringBackgroundFetch]_block_invoke Background fetch received: TSLocationManager
╚═══════════════════════════════════════════════════════════
2024-01-08 16:45:43.350410+0900 BG Geo[1129:387199] [TSBackgroundFetch finish] TSLocationManager (2 of 2)
2024-01-08 16:45:43.352384+0900 BG Geo[1129:387864] 🔵-[TSLocationManager beginStartDetection]
2024-01-08 16:45:43.352580+0900 BG Geo[1129:387864] 🎾-[LocationManager requestLocation] ONESHOT
2024-01-08 16:45:43.352783+0900 BG Geo[1129:387865] ✅-[BackgroundTaskManager createBackgroundTask] 9
2024-01-08 16:45:43.353024+0900 BG Geo[1129:387864] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════
2024-01-08 16:45:43.353649+0900 BG Geo[1129:387865] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 1
╚═══════════════════════════════════════════════════════════
2024-01-08 16:45:43.414300+0900 BG Geo[1129:387865] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════
2024-01-08 16:45:43.414355+0900 BG Geo[1129:387439] flutter: [activitychange] - [ActivityChangeEvent still (100%)]
2024-01-08 16:45:53.449612+0900 BG Geo[1129:387865] 
📍<+37.47923394,+126.95283041> +/- 65.00m (speed -1.00 mps / course -1.00) @ 2024/01/08 4:45:51 PM Korean Standard Time
2024-01-08 16:45:53.451715+0900 BG Geo[1129:387865] 🔴-[LocationManager stopUpdatingLocation] OFF
2024-01-08 16:45:53.452872+0900 BG Geo[1129:387863] 
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1 (1718 ms old)
╚═══════════════════════════════════════════════════════════
2024-01-08 16:45:53.455263+0900 BG Geo[1129:387865] ℹ️-[PolygonGeofencingService setLocation:] Already updating location <IGNORED>
2024-01-08 16:45:57.295597+0900 BG Geo[1129:387864] ℹ️-[TSDBLogger db_save] Log committed
2024-01-08 16:46:13.448317+0900 BG Geo[1129:387865] 🔵-[TSLocationManager endStartDetection]
2024-01-08 16:46:13.448733+0900 BG Geo[1129:387948] ✅-[BackgroundTaskManager
```

</details>

**Comment by christocracy** [comment]
Background Fetch has nothing at all to do with location.

background-geolocation registers a handler for the iOS "significant location changes" api, which records a location about every 1000 meters.  This helps the plug-in relaunch when terminated.

iOS will show that warning only once.  If you uninstall / re-install your app, you *will* see it again.

**Comment by slowdh** [comment]
Okay. If Fetch is not related to location at all, there seems to be an unintended bug in the implementation.

Can you check above "Steps to Reproduce" and check the log result? (Mine is in "Debug logs" section)
Just comment out inside '_configureBackgroundFetch' function block and run Xcode Simulate fetch would cause location reading.

**Comment by slowdh** [comment]
Understood users will get that warning only once, however, I still want to minimize impact to users by carefully controlling location readings. 

Seems like 'listener on BackgroundFetch where it asks "where am I?"' is triggering location read.
Is there a way that I can control / add condition to that listener?

**Comment by christocracy** [comment]
> Is there a way that I can control / add condition to that listener?

No.  It is required by the plug-in's core *Philosophy of Operation*.  This has no effect on user experience or battery life.

This is not something you need to be concerned about.
