### ISSUE TITLE
Invalid licence but only when app is on google play

### ISSUE THREAD

**Issue by bertrandgelinas** [transistorsoft/flutter_background_geolocation#1207]
First, let me just say that i have just updated my app to dart 3 and i'm using flutter 3.16.4.
Thing is, when i use app in debug on my device is works fine, no error message. But after i did released it on Google play, it says Invalid Licence key with the actual key i'm using (fba...). I tried it twice to be sure that it was not the wrong licence and i verified on my TransistorSoft account for the right key and everything is fine.

I have also tried to build on release mode in my device and it works fine.

My account email : bertrand.gelinas@gmail.com

## Your Environment
* Plugin version: 4.12.3
* Platform: iOS or Android
* OS version: 10
* Device manufacturer / model: Samsung s9
* Flutter info (`flutter doctor`): 
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [version 10.0.19041.1110], locale fr-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.1)
[√] VS Code (version 1.86.0-insider)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

      backgroundPermissionRationale: bg.PermissionRationale(
        title: tr(LocaleKeys.location_permission_title),
        message: tr(LocaleKeys.location_permission_description),
        positiveAction: tr(LocaleKeys.location_confirm_button_text),
        negativeAction: tr(LocaleKeys.dialog_cancel),
      ),
      logLevel: enableLogLevel
          ? bg.Config.LOG_LEVEL_VERBOSE
          : bg.Config.LOG_LEVEL_INFO,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      locationUpdateInterval: 10 * 1000,
      fastestLocationUpdateInterval: 10 * 1000,
      enableHeadless: true,
      deferTime: 20000,
      isMoving: true,
      locationAuthorizationRequest: "Always",
      locationAuthorizationAlert: {
        "titleWhenNotEnabled": tr(LocaleKeys.location_always_allow_title),
        "instructions": tr(LocaleKeys.location_always_allow_description),
        "cancelButton": tr(LocaleKeys.dialog_cancel),
        "settingsButton": tr(LocaleKeys.settings)
      },
      minimumActivityRecognitionConfidence: 50,
      notification: bg.Notification(
          smallIcon: 'mipmap/ic_launcher',
          channelName: "Shergo",
          largeIcon: 'mipmap/ic_launcher',
          text: tr(LocaleKeys.collecting_greenpoints),
          title: "Shergo"),
      batchSync: true,
      autoSyncThreshold: 15,
      motionTriggerDelay: 5000,
      url: uploadUrl,
      startOnBoot: true,
      speedJumpFilter: 40,
      stopOnTerminate: false,
      allowIdenticalLocations: false,
      extras: extras,
    );
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
I have added correct License key in AndroidManifest.xml
`       <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="fba..." />
        <meta-data android:name="com.transistorsoft.locationmanager.ENCRYPTION_PASSWORD" android:value="transistorsoft" />`

**Comment by christocracy** [comment]
You know you can build and test a release build locally on your device *before* uploading to play store?

You likely neglected required steps in the Android Setup Instructions from your app/build.gradle.  Every item in...
```diff
+green
```
...is **required**.

**Comment by bertrandgelinas** [comment]
@christocracy You were right. Some were missing. Thanks

**Comment by christocracy** [comment]
Why would you ignore those items?
