### ISSUE TITLE
[nice-tohave Feature request only] Please support [GET] for refreshUrl

### ISSUE THREAD

**Issue by neiljaywarner** [transistorsoft/flutter_background_geolocation#1210]
Please support [GET] for refreshUrl
1) https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-31#section-3.1 seems to indicate get is required and post is not
2) Headers may be used instead of body so no payload may be needed.
3) so many other things are configurable including get/post in other part of server config.

see:
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Authorization-class.html

Yes, i know many servers will use post with a /token endpoint and differentate with grant_type in the body, but some may have a refresh endpoint for some reason.

**Comment by christocracy** [comment]
I doubt this will be implemented soon.

You'll have to care of your own token refresh with your own http requests.

Listen to the plug-in's onHttp event for 401 errors -- that's your cue to perform your token refresh.
