### ISSUE TITLE
Possible small ambiguity in  the Android install guide

### ISSUE THREAD

**Issue by sisyfus** [transistorsoft/flutter_background_geolocation#1211]
Re android/app/build.gradle, section android | defaultConfig, if there are already values for  minSdkVersion and targetSdkVersion, I presume that I should REPLACE them with the values from the install guide - yes? I didn't put them there - they were there after doing a generation of the standard Flutter sample app. The project does build successfully if I simply install the plugin and replace these values. (along with all the other steps in the install guide) The reason I ask is that the install guide seems to suggest to ADD new lines. 
Happy to submit a formal issue using the template if required.

**Comment by christocracy** [comment]
You are free to use whatever values you wish.  The Setup Guides say `// or higher`.

**Comment by sisyfus** [comment]
Thankyou for the quick answer - closing.
