### ISSUE TITLE
location stop update after 5 minutes use

### ISSUE THREAD

**Issue by mhamdimno** [transistorsoft/flutter_background_geolocation#1213]
## You're Environment
* Plugin version:
* Platform: Android
* OS version: 13
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
g.BackgroundGeolocation.ready(bg.Config(

          reset: true,
          stopAfterElapsedMinutes: Configure().app_stopAfterElapsedMinutes == 0
              ? null
              : Configure().app_stopAfterElapsedMinutes,
       //  debug: Configure().app_debug,

      //err
      debug: true,

      locationAuthorizationRequest: 'Always',
          url: Configure().baseUrl + "PushLocation",
          extras: {
            "userId": Configure().user.userId,
            "DeviceId": Configure().user.phoneId,
            "tranDate": await kGetRealTimeUTC()
          },
          headers: {
            "Authorization": 'Bearer ${Configure().apptoken}',
            'lang': Localizations.localeOf(Get.context!).languageCode == "ar"
                ? 0
                : 1,
          },

      // distanceFilter:
      // (Platform.isAndroid && Configure().app_locationUpdateInterval != null) ? 0 : Configure().distanceFilter.toDouble(),

     // heartbeatInterval: 60,  // <-- every minute
      preventSuspend: true,
      disableElasticity:true,
    //err   locationUpdateInterval:Configure().app_locationUpdateInterval != null ? Configure().app_locationUpdateInterval! * 1000:null,
          //    activityRecognitionInterval: ,
          useSignificantChangesOnly: Configure().app_useSignificantChangesOnly,
          allowIdenticalLocations: true,
          //   showsBackgroundLocationIndicator: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
         // desiredAccuracy:  Platform.isAndroid ? -1 :-2,
//err
      locationUpdateInterval: 2000,
      distanceFilter: 0,
          forceReloadOnBoot: true,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: tru
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in is supposed to stop after a period of time.

Read the wiki "Philosophy of Operation" and API docs Config.stopTimeout.

> stopAfterElapsedMinutes

Are you sure you understand what this option does?  It's for automatically calling `.stop()` upon itself.
