### ISSUE TITLE
Diffence in behaviour with ALWAYS vs WHILE USING APP location permission

### ISSUE THREAD

**Issue by CarlosCabarcos** [transistorsoft/flutter_background_geolocation#1214]
## Your Environment 
* Plugin version: ^4.9.0
* Platform: iOS and Android
* OS version: Several on both OSs
* Device manufacturer / model: Several
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Either if the user grants the "ALWAYS" permission level or the "WHILE USING APP" I believe the App should work in the same way while running in the background. However, on many devices, it doesn't seem to do so.

## Actual Behavior

When the app is running in the background (EG: phone is blocked and in your pocket), for users that choose to only grant the "WHILE USING APP" permission, we've detected many cases where the location tracking seems to "fall asleep". 

When the App is brought to the foreground, it seems to "wake up" again and start tracking. The result is that if you're creating a route with the tracked locations, during the time the phone is asleep you just get a straight line from point A to B, since no other points are tracked on the way. However, when users grant the "ALWAYS" permission, this does not seem to happen.

Is this an expected behaviour? In many devices it works fine with both permission levels, but in several others it seems that it does not.

## Steps to Reproduce

1. Turn on location tracking.
2. Grant "WHILE USING APP" permission level.
3. Lock phone and put in your pocket.
4. Walk around.
5. Tracking will sometimes not work properly on many devices.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Turn on location tracking.

How *exactly* are you "turning on location tracking"?

Are you aware of `Config.stopTimeout`?  Have you read the wiki here "Philosophy of Operation"?

**Comment by CarlosCabarcos** [comment]
Good evening @christocracy , thank you for your reply. 

I have not modified the Config.stopTimeout value so it should be at its default 5 minutes if I'm not mistaken.

I did read the "Philisophy of Operation" and if I understood it correctly, this shouldn't cause the issue I described, right? Even if the plugin changes to "stationary" if you start moving again, shouldn't it go back to "moving"? 

In the behaviour we observed, it only went back to tracking the user locations when you opened the app and brought it to the foreground. (This only happens sometimes and in some devices, we're not able to reproduce it consistently, but it's not super rare, we've come across quite a few cases).

Also, is the "moving"-"stationary" change dependant on the level of permission granted? I might have missed something since the plugin is pretty extensive, but I don't believe I saw anything about it.

In order to "turn on location tracking" I am calling bg.BackgroundGeolocation.start() to start the process. (bg from -> import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;) and also setting up bg.BackgroundGeolocation.onLocation((bg.Location location) { ... }).

If there's any additional information I could provide, please don't hesitate to ask. Once again, thank you for your help.

**Comment by christocracy** [comment]
> if you start moving again, shouldn't it go back to "moving"?

Not with "WhenInUse" permission.

Apps are not allowed to automatically turn on location-services in the background with WhenInUse.

There are major consequences with WhenInUse vs Always.

Another consequence is that stopOnTerminate: false will no longer work.

**Comment by christocracy** [comment]
With WhenInUse, you just manually call .changePace(true) (after calling .start()) while your app is in the foreground

**Comment by CarlosCabarcos** [comment]
Ohh I see. I did not know that about the "WhenInUse" permission. Thanks for the clarification. So I guess if I want to make sure the app always works even with "WhenInUse" as I expected it too, my only option is to sacrifice the battery saving from the stationary state, correct?

What's the best way to do this? just to set a really large value for Config.stopTimeOut?

I'm already doing the "changePace(true)" whenever the app is brought back to the foreground, I guess that's why it was working fine as soon as the App was opened again.

Once more, thank you very much for your help. 

PS: Sorry if I'm missing some basic concepts about the plugin or asking something too obvious. I inherited the App I'm working on from another developer (never fun) and I'm trying to catch up as I go with how everything is setup, including the use of the plugin.

**Comment by CarlosCabarcos** [comment]
Sorry to bother you again, but just to make sure I was on the right path... I'll emphasize the question from my last post:

I guess if I want to make sure the app always works even with "WhenInUse" as I expected it to, my only option is to sacrifice the battery saving from the stationary state, correct?

What's the best way to do this? just to set a really large value for Config.stopTimeOut?

Thank you for your time once more.

**Comment by christocracy** [comment]
Correct.  Location services will remain on, burning the device battery just as if following a driving route in Google Maps, until stopTimeout expires or you manually call .changePace(false).

**Comment by CarlosCabarcos** [comment]
Thank you very much @christocracy. Great support! I'll get to modifying the app now :).
