### ISSUE TITLE
[iOS] set minimum interval between location updates

### ISSUE THREAD

**Issue by dJani97** [transistorsoft/flutter_background_geolocation#1215]
## Your Environment
* Plugin version: 4.13.5
* Platform: **iOS**
* OS version: 17.3
* Flutter info (`flutter doctor`): 3.16.6

## Context
I'm trying to limit the amount of data sent to the server by establishing a minimum amount of time that should pass between data points on iOS. For example: even if the client is moving really fast, no location update should be sent unless 5 minutes have passed.

Is this currently possible?

**Comment by christocracy** [comment]
>Plugin version: latest
>OS version: latest
>Flutter info (flutter doctor): latest

"latest" is meaningless.  Particularly so to someone in the future.

**Comment by dJani97** [comment]
@christocracy Thanks, I updated the description.
