### ISSUE TITLE
Any plans for improving operation with very poor signals?

### ISSUE THREAD

**Issue by sisyfus** [transistorsoft/flutter_background_geolocation#1216]
## Your Environment
* Plugin version: 4.13.5
* Platform: Android
* OS version: 14
* Device manufacturer / model: Pixel 6

I notice that Google Maps does a reasonable job of showing progress on a navigated route in tunnels. Just wondering whether you are doing any work to try to add similar functionality to the plugin? Has anyone suggested to Google that they expose an API for the Maps app itself, for example?

**Comment by christocracy** [comment]
Google maps is likely using snap-to-road for that and estimating the position based upon the last known speed.

No, I have no plans for anything like that.  You're free to pay Google for their snap-to-road functionality.
