### ISSUE TITLE
App rejected at AppStore due to invalid motion key's String in info.plist.

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#122]
The Apple  Rejected my App  due to invalid motion key's String in info.plist.
*****************************************************************

Below is the ScreenShot of the issue given by the Apple------->>>
  
![Screen Shot 2019-09-21 at 12 09 17 PM](https://user-images.githubusercontent.com/51204005/65369342-47746d00-dc69-11e9-9f8b-d158b985bef0.png)

And Below is the ScreenShot of my info.plist
![Screen Shot 2019-09-21 at 12 15 46 PM](https://user-images.githubusercontent.com/51204005/65369370-bce03d80-dc69-11e9-9c9c-c57824212194.png)

## Your Environment
* Plugin version:1.0.12
* Platform:iOS
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
App Rejected  at AppStore

## Actual Behavior
Should not be Rejected.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Well, your strong *is* rather vague “to work properly”.

You can remove the string and configure disableMotionActivityUpdates: true and you won’t request motion authorization,

Read the docs about it
