### ISSUE TITLE
Can I manually force ENTER OR EXIT to a geofence?

### ISSUE THREAD

**Issue by welchi** [transistorsoft/flutter_background_geolocation#1221]
## Your Environment
* Plugin version: latest
* Platform: iOS and Android
* OS version: latest
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:

## Context

We have always found the plugin useful.
In our app, we would like to be able to not only enter or exit a geofence by firing an ENTER or EXIT event with `onGeofence`, but also manually force an EXIT event to fire and manually exit a geofence, even if it is inside an ENTER geofence, for example. I would like to do this.
Similarly, we would like to fire an ENTER event on a geofence that has not yet been ENTERed, forcing it to enter the geofence.

Is it possible to use the Background Geolocation API to accomplish the above?
If it is on the Flutter/Dart layer, the above process can be implemented pseudo-statically using state management, but that would cause inconsistencies with the ENTER/EXIT states for the various geofences that Background Geolocation maintains, Therefore, we would like to use Background Geolocation's API to perform the processing described above.

Is it possible to do the above?
Please check.

**Comment by christocracy** [comment]
> also manually force an EXIT event to fire and manually exit a geofence, even if it is inside an ENTER geofence, 

You can't.  The OS handles geofence monitoring.  Only the OS can fire events.  The plug-in is merely the mailman, delivering events when the OS reports it.
