### ISSUE TITLE
Feature Request: Add Ability to get currently loaded config

### ISSUE THREAD

**Issue by AtomicRaven** [transistorsoft/flutter_background_geolocation#1222]
## Your Environment
* Plugin version: 4.13.5
* Platform: iOS or Android: iOS
* OS version: Ventura
* Device manufacturer / model: Apple iPhone 15 Pro
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.6 22G120 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.2)
[✓] VS Code (version 1.56.0)
[✓] Connected device (3 available)
[✓] Network resources
No issues found!

* Plugin config:
```
bg.Config config = bg.Config(
      reset: true,
      debug: CONFIG.DEBUG,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      //distanceFilter: 10.0,
      backgroundPermissionRationale: bg.PermissionRationale(
          title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'
        ),
      url: CONFIG.TRACKER_HOST + CONFIG.TRACKER_API,
      method: 'POST',
      params: {"trid": deviceId},
      extras: {"evt": 0},
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      httpRootProperty: 'data',
      locationTemplate: jsonTemplate,
      stopOnTerminate: false,
      startOnBoot: true,
      batchSync: true,
      autoSyncThreshold: 25,
      maxBatchSize: 25,
      enableHeadless: true,
      elasticityMultiplier: 2.0
    );
```

## Expected Behavior
Ability to retrieve currently set Config

## Actual Behavior
There is no method for retrieving the currently set config. 

## Steps to Reproduce

1. SetConfig
2. Goto Another Page
3. Retrieve currently set Config

## Context
I am building a settings page, much like [https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/lib/advanced/settings_view.dart](settings_view.dart)

You may have to copy URL above ^^ - git is shortening it

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs .getState()

Also, the callback of many methods return the State.

**Comment by AtomicRaven** [comment]
Hi Yes - thank you - I realize today I can get it from:
```
bg.BackgroundGeolocation.state.then((bg.State state) {
  bg.Config config = state;
  return config;
});
```

Amazing work by the way.  This far surpasses anything else out there.

**Comment by christocracy** [comment]
or:
```dart
bg.State state  = await bg.BackgroundGeolocation.state;
```

**Comment by AtomicRaven** [comment]
> or:
> 
> ```dart
> bg.State state  = await bg.BackgroundGeolocation.state;
> ```

Thanks!
