### ISSUE TITLE
problem getting first location

### ISSUE THREAD

**Issue by matheuskansaon** [transistorsoft/flutter_background_geolocation#1225]
*Issue Description:*
When utilizing the start() method in the Flutter background geolocation library, it seems that the last caught point is loaded. However, there might be configuration errors with the config() method, which could potentially be relevant or the cause of this behavior.

*Code Reference:*
dart
//...
    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      isMoving: true,
    ));

    bg.BackgroundGeolocation.onLocation(
      (bg.Location location) async {
        DateTime timestamp2 = DateTime.parse(timestamp).toLocal();
        final ponto = {
          'latitude': location.coords.latitude,
          'longitude': location.coords.longitude,
          'altitude': location.coords.altitude,
        };
     );       
  );

//...

                ElevatedButton(
                  onPressed: () async {

                    setState(() {
                      if (isTracking) {
                        bg.BackgroundGeolocation.stop();

                      } else {
                        bg.BackgroundGeolocation.start();
                      }
                      isTracking = !isTracking;
//...

*Expected Behavior:*
Expected the start() method to initialize the plugin and the first point to actual location of the device.

*Actual Behavior:*
The first point loaded in a new test corresponds to the last point caught in a previous test.

*Additional Information:*
- Flutter version: 3.10.5
- Device/OS information: Emulator Pixel 3a API28 / Android 9.0
- Library version: 4.11.1

*Screenshots:*
The red marker starts the route

![WhatsApp Image 2024-02-02 at 21 02 59](https://github.com/transistorsoft/flutter_background_geolocation/assets/47276287/e4840e42-7d61-4376-9d11-62ac3a9249e3)

**Comment by christocracy** [comment]
Are you testing on a real device with real movement (ie not emulator or mock location app)?

**Comment by matheuskansaon** [comment]
Yes, I tested and in both cases this error occurred.

**Comment by christocracy** [comment]
I don't understand what your image is trying to show.

**Comment by matheuskansaon** [comment]
The image highlights the following problem: when starting a new trip, the application considers the last point of the previous trip as the first point of the current trip. However, subsequently, the capture occurs normally. So the  point represented by the read marker, the first of point of this trip, is actually the last location captured in the previous trip.

Note: when testing the application on the first trip made by the device, this error does not appear; only occurs from the second trip onwards.

**Comment by christocracy** [comment]
The plug-in does not cache locations.  It provides to you locations received directly from the native location api.
