### ISSUE TITLE
Is there an api in this plugin to check if precise location is enabled?

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#1227]
## Your Environment
* Plugin version: `4.13.5`
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* Flutter info `flutter: 3.16.3`

I would like to tell whether a user has precise location turned on. I have found this section of the docs but it is iOS only. 
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/ProviderChangeEvent/accuracyAuthorization.html

Is it possible to detect it in general for android as well? 

I found another plugin with this sort of thing, which would be ideal here but I would rather not add a new plugin just for this one boolean.
https://pub.dev/documentation/geolocator/latest/geolocator/LocationAccuracyStatus.html

**Comment by christocracy** [comment]
See api docs .providerState.  Also event onProviderChange

**Comment by MilesAdamson** [comment]
I see, so `accuracyAuthorization` should also work on android and be a 1 or 0 depending on that status of that?

From the docs I interpreted it as iOS only

**Comment by christocracy** [comment]
Try it and see.  The docs are old

**Comment by MilesAdamson** [comment]
It seems to work on my phone. Should it work fine on most other android devices and iOS devices below 14 as well?

**Comment by christocracy** [comment]
There's no reason to doubt it wouldn't.

**Comment by MilesAdamson** [comment]
I mean, there is a reason to doubt it if the docs are old and only make mention of iOS14 specifically. You could just say "yes"
