### ISSUE TITLE
Duplicate data is detected by the backend database

### ISSUE THREAD

**Issue by dadaocao** [transistorsoft/flutter_background_geolocation#1228]
Location data will be uploaded repeatedly even it's at the same timestamp/ longitude/ latitude etc. . 

## Your Environment
* Plugin version: flutter_background_geolocation: ^4.12.3
* Platform: iOS or Android: both
* OS version: Mac M1
* Device manufacturer / model: iPhone 15; Redmi
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.16.5, on macOS 12.5 21G72 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.86.0)
[✓] Connected device (2 available)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void _initBackgroundLocationCheck() async {
    await _locationDataProvider.open(null);

    ////
    // 1.  Listen to events (See docs for all 12 available events).
    //

    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      safePrint('[location] - $location');
      _locationDataProvider.insert(location);
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      safePrint('[motionchange] - $location');
      _locationDataProvider.insert(location);
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      safePrint('[providerchange] - $event');
    });

    ////
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow access to this device's location in the background?",
                message:
                    "Meet Pandora collects location data to understand whether patterns in movement are associated with your mental health.",
                positiveAction: "Change to Allow all the time"),
            distanceFilter: 20.0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            // logLevel: bg.Config.LOG_LEVEL_VERBOSE)
            logLevel: bg.Config.LOG_LEVEL_ERROR))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
  }

  void _initBackgroundFetch() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    if (prefs.get("fetch-count") != null) {
      final count = prefs.getInt("fetch-count")!;
      safePrint('last fetch-count: $count');
    }

    // It seems like this is ANDROID ONLY!!
    /// Register BackgroundFetch headless-task.
    // BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

    // Configure BackgroundFetch.
    int status = await BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE), (String taskId) async {
      // <-- Event handler
      // This is the fetch-event callback.
      safePrint("[BackgroundFetch] Event received $taskId");

      try {
        var location = await bg.BackgroundGeolocation.getCurrentPosition(
            samples: 1,
            extras: {"event": "background-fetch", "headless": true});
        await _locationDataProvider.open(null);
        _locationDataProvider.insert(location);
      } catch (error) {
        safePrint("[location] ERROR: $error");
      }

      SharedPreferences prefs = await SharedPreferences.getInstance();
      int count = 0;
      if (prefs.get("fetch-count") != null) {
        count = prefs.getInt("fetch-count")!;
      }
      prefs.setInt("fetch-count", ++count);
      safePrint('[BackgroundFetch] count: $count');

      // IMPORTANT:  You must signal completion of your task or the OS can punish your app
      // for taking too long in the background.
      BackgroundFetch.finish(taskId);
    }, (String taskId) async {
      // <-- Task timeout handler.
      // This task has exceeded its allowed running-time.  You must stop what you're doing and immediately .finish(taskId)
      safePrint("[BackgroundFetch] TASK TIMEOUT taskId: $taskId");
      BackgroundFetch.finish(taskId);
    });

    safePrint('[BackgroundFetch] configure success: $status');
    setState(() {
      // _status = status;
    });

    BackgroundFetch.start().then((int status) {
      safePrint('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      safePrint('[BackgroundFetch] start FAILURE: $e');
    });

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

```

## Expected Behavior

Data should be reported when user movement is detected (I konw for iOS users, they should move more than 200 meters), and there should be no duplication. What cause the duplication?

## Actual Behavior

Upload the same data multiple times at the same timestamp/ longitude/ latitude etc. .
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/65008499/6496845a-dd31-47f1-bf8f-995fef40f802)

## Context

We use mobile phone location info to determine whether the user has stayed at the same location for a long time and infer whether the user is prone to emotional problems.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The locations are not duplicate unless Location.uuid is duplicate (which you're not showing).

**Comment by dadaocao** [comment]
Do you mean that there are other indicators that determine the data to be uploaded?

**Comment by christocracy** [comment]
Show me that same data you did but add `Location.uuid`

**Comment by dadaocao** [comment]
<img width="467" alt="image" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/65008499/0927858c-b1d9-4c4b-8902-7e0f5fe5fe48">
I don't know where can I get the uuid.

**Comment by christocracy** [comment]
You need to modify your code to *send* it then go gather data.

**Comment by christocracy** [comment]
See the api docs "Location" to learn about all the attributes available to you.

**Comment by Wdsitechteam** [comment]
Same issue occurs on my integration.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/103169437/5bebdc8f-6d94-4600-9163-af0f47807cc9)

This issue occurs, when user goes offnet with app killed state 10 mins and so, There after goes onNet without opening app.

**Comment by christocracy** [comment]
This is to be expected.  The native location api doesn't always allow the app to turn on location services (particularly on recent versions of Android) so the last known location is returned.  This is why the `Location` object includes a [`location.age` (milliseconds)](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Location/age.html) attribute, so you can know how old the location was when it was recorded.

**Comment by christocracy** [comment]
To learn more about how to control the plug-in http service, read the api docs "HTTP Guide", linked throughout.
