### ISSUE TITLE
What is the life cycle for Entry, Exit, and Dwell at a geofence?

### ISSUE THREAD

**Issue by welchi** [transistorsoft/flutter_background_geolocation#1230]
## Your Environment
* Plugin version:
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:

## Context
What is the Entry, Exit, and Dwell lifecycle at a geofence?

Do Entry and Exit events always occur in the order of Entry, Dwell, and Exit?
Or can an Exit happen without an Entry and Dwell happening, or can an Entry happen twice in a row (without going through an Exit)?

Please tell me the Entry/Dwell/Exit lifecycle to/from a geofence as described above.
I really appreciate any help you can provide.

**Comment by christocracy** [comment]
- you can't have a dwell until an entry,
- you can't have an exit without entry.

1. Entry
2. Dwell
3. Exit
