### ISSUE TITLE
license validation failure toast msg shown in the Flutter app and all setup is ok according to the doc and details

### ISSUE THREAD

**Issue by PoriyaBytez** [transistorsoft/flutter_background_geolocation#1231]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you purchased a license?

**Comment by PoriyaBytez** [comment]
Yes,We have

**Comment by christocracy** [comment]
Then your applicationId doesn't match the key it was generated for or you didn't perform ALL the required steps in the Android Setup Instructions.  Everything in... 
```+green
```
...is **required**.

**Comment by PoriyaBytez** [comment]
Even though I followed all the steps I still saw the toast message

**Comment by PoriyaBytez** [comment]
So What I need to do?
