### ISSUE TITLE
record location for a certain type of moving activity only 

### ISSUE THREAD

**Issue by Silfalion** [transistorsoft/flutter_background_geolocation#1232]
## Your Environment
* Plugin version: 4.13.7
* Platform: Android
* OS version: Android 14
* Device manufacturer / model: Xiaomi
* Flutter info (`flutter doctor`): ``` [✓] Flutter (Channel stable, 3.16.5, on Ubuntu 23.10 6.5.7-060507-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!```
* Plugin config: 
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Being able to monitor location based only on the activity, so you can track vehicle movements for example and by using a timer you stop recording the location after the activity changed or it became stationnary

## Actual Behavior
Didn't find a function that would replicate that directly

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config.triggerActivities.

Of course, that all falls apart if the use doesn't grant the "health and fitness" permission.

**Comment by Silfalion** [comment]
Exactly what I was looking for, thank you.

Yes, will have to make sure the do before proceeding.


Is there an equivalent for iOS or it has to be the manual way?

**Comment by christocracy** [comment]
> Is there an equivalent for iOS

 No.  iOS does not allow the motion api to operate in the background while the plug-in is in the "stationary state".

**Comment by Silfalion** [comment]
Ah I see, so that's why we need a stationary geo fence on iOS but not on Android. Makes sense. Thank you for your help!
