### ISSUE TITLE
How to integrate with Flutter 3.19.2 (Android and IOS)?

### ISSUE THREAD

**Issue by haykoyk** [transistorsoft/flutter_background_geolocation#1237]
Hi Support,

I just bought your library, but it seems that it's not compatible with the latest release of Flutter.
Will this work with 3.19.2 or need I revert my flutter version to a previous version to get things started?
Is there any updated guide for this because if I start a new project I would like very much to use the latest version of Flutter.

Thank you.

Best regards, Hayko.

**Comment by christocracy** [comment]
I'm not aware of any problem with latest flutter.  I'll have a look tomorrow.  If there's a problem, it's trivial to fix.

**Comment by haykoyk** [comment]
Great, thank you Chris.
They haved changed the whole structure with the build.gradle files. Plugins are defined differently etc.
I would be helped very much if you can create a new default project flutter create project with 3.19 and setup it for android and also IOS.  More info about changes:  https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
I think it will be faster for me to move on with my project instead of you writing a whole new setup guide :-)

Awaiting your response to continue with my project...

**Comment by christocracy** [comment]
Actually #358 is related.

**Comment by haykoyk** [comment]
I don't see why this is related? My question is about integrating and getting started with your library in Flutter with the latest version of flutter, 3.19? Your Android integration guide is not compatible with all the steps defined there..

**Comment by christocracy** [comment]
Actually it's `#358` on `background-fetch`:  https://github.com/transistorsoft/flutter_background_fetch/issues/358

**Comment by christocracy** [comment]
Relax...I already said I'd look at it tomorrow.

If a free plug-in works for you, use that.

**Comment by christocracy** [comment]
Or rollback your flutter version.

**Comment by christocracy** [comment]
An updated guide won't be ready until minimum next week.

**Comment by haykoyk** [comment]
I don't want to rollback my Flutter version and your lib has more features then a free background location updated lib, so I will wait for your update. Hope to hear from you soon, Thank you.

**Comment by haykoyk** [comment]
Thank you. It worked. 👍
