### ISSUE TITLE
Geofencing Events Not Triggering in Android Killed State

### ISSUE THREAD

**Issue by abbasv0786** [transistorsoft/flutter_background_geolocation#1240]
## Your Environment
* Plugin version: 4.14.0
* Platform: Android
* OS version:14.0
* Device manufacturer / model: One Plus 11R 5g
* Flutter info (`flutter doctor`): Flutter version 3.16.8
* Plugin config:
```
  Future<void> init() async {
    var config = Config(
      // HTTP Data
      url: "******", // Confidential,
      autoSync: true,
      batchSync: true,
      maxBatchSize: 50,
      headers: "******", // Confidential,
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
      geofenceModeHighAccuracy: true,
      stopOnTerminate: false,
      showsBackgroundLocationIndicator: false,
      desiredAccuracy: Platform.isIOS
          ? Config.DESIRED_ACCURACY_NAVIGATION
          : Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      enableHeadless: true,
      stationaryRadius: 10,
      pausesLocationUpdatesAutomatically: false,
      locationAuthorizationRequest: 'Always',
      geofenceProximityRadius: GeoFencingConfig.radius, // 200m
      startOnBoot: true,
      disableElasticity: true,
      allowIdenticalLocations: true,
      preventSuspend: true,
      foregroundService: true,

      disableMotionActivityUpdates: true,
      notification: bg.Notification(
        sticky: true,
        priority: Config.NOTIFICATION_PRIORITY_MAX,
      ),
    );

    await BackgroundGeolocation.ready(config);
    if (Platform.isAndroid) {
      await BackgroundGeolocation.registerHeadlessTask(headlessTask);
    }
    BackgroundGeolocation.start();
  }```

## Expected Behavior
We expect the geofencing feature to work seamlessly on Android, even when the app is in a killed state. The app should trigger geofencing events as intended.

## Actual Behavior
Currently, on Android, when the app is in a killed state, we are only receiving location moving events in the headless state, not the expected geofencing events.

## Context
We successfully integrated geofencing into our application, and it's functioning well in various scenarios except for when the app is in a killed state on Android.

## Debug logs
<details>
	<summary>Logs</summary>
```
╔═════════════════════════════════════════════
║ TSLocationManager3.5.4 (433)
╠═════════════════════════════════════════════
╟─ OnePlus CPH2487 @ 14 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": true,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
    "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": ""
  },
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": true,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": true,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {
    "authorization": "Bearer *****", //Confidential
    "Content-Type": "application\/json"
  },
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "DESC",
  "logLevel": 0,
  "logMaxDays": 3,
  "maxBatchSize": 50,
  "maxDaysToPersist": 14,
  "maxMonitoredGeofences": 97,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 2,
    "sticky": true,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 10,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "*****", //Confidential
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 3583.240234375,
  "isFirstBoot": true,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="bmi26x Accelerometer Non-wakeup", vendor="BOSCH", version=16777479, type=1, maxRange=156.9064, resolution=0.0047856453, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="bmi26x Gyroscope Non-wakeup", vendor="BOSCH", version=16777479, type=4, maxRange=34.90656, resolution=0.0010652636, power=0.9, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="ak0991x Magnetometer Non-wakeup", vendor="akm", version=146979, type=2, maxRange=4912.0503, resolution=0.15, power=1.1, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="QTI", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
╚═════════════════════════════════════════════ 
```

</details>

**Comment by christocracy** [comment]
How are you testing this?

See wiki Debugging.  See debug: true.  Place geofences outside.  Go walk into them.  Retrieve logs with .emailLog.

**Comment by kaciula** [comment]
@christocracy I am also experiencing the same thing. Geofence events are not triggered on Android when the app is terminated. I'm using a OnePlus phone with Android 11.

I've created geofences and I'm walking/driving to them. I show a notification for each geofence event from the headless callback and I am also checking the backend to see if events have been sent to it. No such events are generated when the app is terminated.
 
I will also get you the logs during another test round. (The main reason we acquired a licence was because of the promise of this functionality working while the app is terminated.)

![Screenshot 2024-04-05 at 11 25 51](https://github.com/transistorsoft/flutter_background_geolocation/assets/18688/26e4b5c3-aeea-4c45-a05b-9c9e18f44a20)

**Comment by kaciula** [comment]
Here is the config and log retrieved with .emailLog

╔═════════════════════════════════════════════
║ TSLocationManager3.5.4 (433)
╠═════════════════════════════════════════════
╟─ OnePlus BE2029 @ 11 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location in the background",
    "message": "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
    "positiveAction": "Change to {backgroundPermissionOptionLabel}",
    "negativeAction": "Cancel"
  },
  "batchSync": false,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "{ \"latitude\":<%= latitude %>, \"longitude\":<%= longitude %>, \"geofenceIdentifier\":\"<%= geofence.identifier %>\", \"geofenceAction\":\"<%= geofence.action %>\", \"timestamp\":\"<%= timestamp %>\" }",
  "headers": {
    "Authorization": "Bearer eyJhbGciOiJFUzUxMiIsImtpZCI6IjcyQjAyM0E0OTUzNDg0RDQ2RDE5RjA2RUZCQUQyRjlGIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2lkLnN0YWdpbmcua296bW96LmFwcCIsIm5iZiI6MTcxMjE2MDc2NiwiaWF0IjoxNzEyMTYwNzY2LCJleHAiOjE3MTk5MzY3NjYsImF1ZCI6Imtvem1vei5hcGkiLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwidHJhZGVzbWVuIiwiaG9tZW93bmVycyIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJleHRlcm5hbCJdLCJjbGllbnRfaWQiOiJrb3ptb3pfYXBwIiwic3ViIjoiNGYyYTY2OTUtMjhmMi00MTNhLTkzN2EtZDBmYWNhMjI4MGE2IiwiYXV0aF90aW1lIjoxNzEyMTYwNzY1LCJpZHAiOiJhdWRrZW5uaSIsInNpZCI6IkVCNTJENDYyNjJCODE2N0U0MDhDN0ZDNDA3Mzk2OEZFIiwianRpIjoiQjBCNzU4MjQxRDY1QjgwMEE0MzRDM0E5NDE2RTQxNDYifQ.AW_dmQeKXmd-YYMRczqcyGvKbXHPscEbqQxIu9I-2PX5xVPqzqoZOdiGBIKbidRz3VN-a3I-DwiAy8nbbIxAa3NnAcB-9y_GwivZ9usKybjI0D9InJLF7juYo7xvhhW0LsvszTxlZYoKBVRL8XrlxeYHYi_a--kLwOdcSUbF0-EWsh_I",
    "Kozmoz-Profile-Id": "83c2d275-f791-478a-8ed5-308a066dbbec"
  },
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": ".",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 2,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxMonitoredGeofences": 97,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": -1,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [
    "2 08:00-20:00 geofence",
    "3 08:00-20:00 geofence",
    "4 08:00-20:00 geofence",
    "5 08:00-20:00 geofence",
    "6 08:00-20:00 geofence"
  ],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/[api.staging.kozmoz.app](http://api.staging.kozmoz.app/)\/debug\/geofence",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": true,
  "trackingMode": 0,
  "odometer": 0,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="bmi160 Accelerometer Non-wakeup", vendor="BOSCH", version=50529037, type=1, maxRange=78.45318, resolution=0.0023928226, power=0.18, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="bmi160 Gyroscope Non-wakeup", vendor="BOSCH", version=50529037, type=4, maxRange=34.905556, resolution=0.001065233, power=0.9, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="mmc5603x Magnetometer Non-wakeup", vendor="memsic", version=10120052, type=2, maxRange=3000.0044, resolution=0.0976, power=1.0, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="qualcomm", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
╚═════════════════════════════════════════════



[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/14882744/background-geolocation.log)

**Comment by christocracy** [comment]
> Geofence events are not triggered on Android when the app is terminated.

The following geofence (from your logs) fired when you app was *terminated* (ie: "Headless"):

```
04-04 08:00:11.288 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER
╠═════════════════════════════════════════════
╟─ CatalinHomeId
╚═════════════════════════════════════════════
04-04 08:00:11.292 DEBUG [TSGeofenceManager setLocation] isMoving: false | stateChanged: false | timerExpired: true | elapsed: 425443 | d: 13.138009
04-04 08:00:11.306 DEBUG [HeadlessTask onHeadlessEvent] 💀 [HeadlessTask location]
04-04 08:00:11.355 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: c249fae6-4ae4-42c4-a849-21030e7965b3
04-04 08:00:11.377 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

04-04 08:00:11.389 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [GeofencingService startId: 1, eventCount: 0, sticky: false]
04-04 08:00:11.390 DEBUG [HeadlessTask onHeadlessEvent] 💀 [HeadlessTask geofence]
```

**Comment by kaciula** [comment]
@christocracy The observation was that MOST of the geofence events do not get triggered while the app is terminated. If the app was recently terminated (around 5 minutes), geofencing seems to work. More than that no.

What do you need for me in order to convince you that there is indeed an issue so you can give it your attention?

**Comment by christocracy** [comment]
> that there is indeed an issue

It’s likely an issue with *your specific device*.  See https://dontkillmyapp.com.

**Comment by kaciula** [comment]
@christocracy I understand that most Android devices have various battery and memory optimizations that kill the app. But the functionality that we are talking about here is supposed to work, according to your documentation, when the app is already killed/terminated. So it shouldn't really matter that the phones kill the app sooner than later.

My conclusion from this is that the plugin generally does not really work as expected when the app is killed/terminated. So the solution would be to keep the app alive as much as possible. Is there any other config value from the config above that I should set that would improve the behavior? Btw, I don't see a persistent foreground notification corresponding to a behind-the-scenes foreground service. How come? Having a foreground notification and service would theoretically keep the app alive.

**Comment by christocracy** [comment]
This is made possible by heavy use of foreground-services (this sdk defines about 5 separate foreground-services each dedicated to specific tasks, including geofencing.

whenever the OS detects a geofence event has occurred, it launches the plug-in’s GeofencingService to handle that event, regardless if the app is in the background or terminated.

A persistently running foreground-service is not necessary.

also see Config.geofenceModeHighAccuracy and give that a try.  And of course https://dontkillmyapp.com likely applies.
