### ISSUE TITLE
Gradle Error with exit code 1 when building in debugmode

### ISSUE THREAD

**Issue by CJBNBG** [transistorsoft/flutter_background_geolocation#1241]
## Your Environment
* Plugin version: 4.14.0
* Platform: Android
* OS version: 14
* Device manufacturer / model: SM-S918B
* Flutter info (`flutter doctor`): no issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Beweg dich!',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.amberAccent),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Beweg dich!'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
      ),
    );
  }
}

```

## Expected Behavior

I expect a build in debug mode for my device

## Actual Behavior

Gradle runs into an error with exit code 1 (see below):

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\EigeneProgramme\flutter\beweg_dich\android\app\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'flutterRoot' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 977ms
Error: Gradle task assembleDebug failed with exit code 1

## Steps to Reproduce

1. delete dependency in pubspec.yaml -> no error, app running in debug mode
2. reinstall dependency in pubspec.yaml -> error (see above)
3. delete dependency in pubspec.yaml -> no error, app running in debug mode
4.

## Context

I created a brand new flutter project in Android Studio Hedgehog 2023.1.1 Patch 2 and removed Code in main.dart to minimum. Runnin this in debug mode is working completely fine. Just adding the dependency in pubspec.yaml leads to the building error described above.
I thought downgrading the plugin into version 4.13.7 or 4.13.6 might solve the problem, but it doesn't. It produces the same building error.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
No logs available, except the output from Gradle:

Launching lib\main.dart on SM S918B in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\EigeneProgramme\flutter\beweg_dich\android\app\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'flutterRoot' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 838ms
Error: Gradle task assembleDebug failed with exit code 1
```

</details>

Can you please tell me, what I did wrong?

Claus

**Comment by christocracy** [comment]
> android\app\build.gradle' line: 6

What is this "line 6" doing?

**Comment by christocracy** [comment]
> Flutter info (flutter doctor)

It's important to provide the entire output to which version of flutter you're using.
