### ISSUE TITLE
Allow firebase performance monitoring to track HTTP Requests

### ISSUE THREAD

**Issue by danielgomezrico** [transistorsoft/flutter_background_geolocation#1243]
The idea is that all requests done by the library could be tracked using: 
- https://firebase.google.com/docs/perf-mon
- android docs: https://firebase.google.com/docs/perf-mon/network-traces?platform=android

We do use that, and it tracks all requests but not those made by this library, Im not sure why.

## Your Environment
TODO
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart
      url: "myendpoint.com",
      locationTemplate: _requestBody(),
      httpRootProperty: '.',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $authToken'
      },
      params: {
        'device_type': device,
        'reference': loadId,
        'reference_type': 'id',
        'source': 'traxporta',
      },
```

## Expected Behavior
Installing firebase performance monitor should track requests done by this library

## Actual Behavior
They are not

## Steps to Reproduce

1. Install firebase performance monitor
2. Start the SDK to do HTTP requests to any server
3. The traces do not appear on firebase performance monitor dashboards

## Context
We need to monitor the behavior of the requests done from the app, the requests sometimes are not arriving, and we need to understand why.

This library distinct and creates dashboards for requests by:
- status code
- date
- payload size
- timeouts
- custom fields

**Comment by christocracy** [comment]
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/24ffad9c-60da-487e-8537-98814292e2e9)

The plug-in does use OkHttp (`v 3.12.13`)

**Comment by danielgomezrico** [comment]
I tried adding a native network request at my flutter activity like:

```kotlin
package global.traxion.traxporta
import android.os.Bundle
import android.os.Handler
import io.flutter.embedding.android.FlutterActivity
import okhttp3.*

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        Handler().postDelayed({
            Thread(Runnable {
                val client = OkHttpClient()

                val request = Request.Builder()
                    .url("https://www.google.com")
                    .build()

                val response = client.newCall(request).execute()
            }).start()
        }, 5000)
    }
}
```

Firebase says on adb:
> 03-05 09:03:51.122 15473 15602 I FirebasePerformance: Logging network request trace: https://www.google.com/ (responseCode: 200, responseTime: 432.484ms)

And that request do work, I still do not see the requests done by transistor sdk 🤔

**Comment by christocracy** [comment]
Yes, that's a typical `OkHttp` request and exactly what the plugin does.

**Comment by christocracy** [comment]
I don't know, I doubt it.  I've never heard of this "firebase performance monitoring".

**Comment by danielgomezrico** [comment]
Got it, for us having visibility of the reliability of the GPS tracking is important, and for that, we need to monitor all request we are doing, to see how many requests:
- are done
- went bad and list by status code

Firebase performance monitoring allows us to measure all requests, do you know any other tool that may help us to monitor this? or approach? 

I was thinking that registering the headless function and track things from there may be one approach 🤔

**Comment by christocracy** [comment]
I understand what "performance monitoring" *is*, I've just never heard of this particular API or interacted with it.

>do you know any other tool that may help us to monitor this? or approach?

No.  You're the first to enquire about this in 10 years.

**Comment by danielgomezrico** [comment]
I made an example that reproduces this: https://github.com/danielgomezrico/transistor-sdk-and-firebase-performance-error-example

I'm also checking with Firebase support to see if they can help me find what is happening, is there any place where I can see where is the OKHTTP request been done in the library, so I can show to them?

**Comment by danielgomezrico** [comment]
I reported this issue on Firebase repo to see if someone finds a way to check it, is there any extra info you can share so that they can see where is the issue? Maybe a snippet?

**Comment by danielgomezrico** [comment]
I created another issue on the android Firebase repo to see if they find what is happening:
- https://github.com/firebase/firebase-android-sdk/issues/5964

**Comment by danielgomezrico** [comment]
I put the last update on the issue here just for you to know:

https://github.com/firebase/firebase-android-sdk/issues/5964#issuecomment-2138092900

**Comment by danielgomezrico** [comment]
I made a ping so the issue is not closed in: https://github.com/firebase/firebase-android-sdk/issues/5964#issuecomment-2239438522

**Comment by danielgomezrico** [comment]
Pinging again https://github.com/firebase/firebase-android-sdk/issues/5964#issuecomment-2296853982
