### ISSUE TITLE
How to know on iOS that app was started in background by plugin?

### ISSUE THREAD

**Issue by kukareku0307** [transistorsoft/flutter_background_geolocation#1248]
I have been using your plugin successfully for 2 months now for iOS devices and ran into a problem: using stopOnTerminate: false, the plugin launches the application in the background exactly as if it were launched by the user and thus my application launches a socket that shows that user is online(must to prevent this), I need to understand when the application was launched by the user, and when by a plugin. How can I check this? Sorry if there have been an answer already. Thank you very much for your work.

## Your Environment
* Plugin version:
* Platform: iOS
* OS version: 17.4
* Device manufacturer / model: iPhone iOS 14+
* Flutter info (`flutter doctor`): 3.19.1
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        maxRecordsToPersist: 5,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 15.0,
        reset: false,
        stationaryRadius: 50,
        params: {'user_id},
        url: "$url",
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        showsBackgroundLocationIndicator: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE);
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs [`State.didLaunchInBackground`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/State/didLaunchInBackground.html)

**Comment by kukareku0307** [comment]
> See API docs [`State.didLaunchInBackground`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/State/didLaunchInBackground.html)

@christocracy Thanks for the answer, I immediately tested this solution on simulators and in field testing with the real device(go for a walk) and, unfortunately, it was always **false**.
My code:
`var state = await bg.BackgroundGeolocation.state;`
`bool fromBackground = state.didLaunchInBackground;`

**Comment by christocracy** [comment]
I'll have a look.

**Comment by kukareku0307** [comment]
> I'll have a look.

@christocracy No need, now I tested with 
`  var state = await bg.BackgroundGeolocation.ready(bg.Config());
  bool fromBg = state.didLaunchInBackground;`
  and it is worked! Thanks again!)
