### ISSUE TITLE
how can I inspect database for iOS to track json request

### ISSUE THREAD

**Issue by hafeezrana** [transistorsoft/flutter_background_geolocation#1249]
On android studio there is database inspector option only for android device. My data is uploading successfully from android devices but failing from iOS emulator. I think the request body of the location is different from the android ones. Please help me out to watch iOS tracking too.
My code which is working fine with android OS but not for iOS.
 `
bg.BackgroundGeolocation.ready(
      bg.Config(
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_DEBUG,
        logMaxDays: 2,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopTimeout: 5,
        headers: {"content-type": "application/json"},
        url: EndPoints.getTracking(),
        extras: {
          "emp_no": empNo,
          // "url": "https://maps.google.com/?q=<lat>,<lng>",
          "datee": formattedTimestamp,
          "place": "Market",
          "timestamp": formattedTimestamp,
          "timee": formattedTimestamp
        },
`
'
 
        locationTemplate:
            '{"latitude": <%= latitude %>,"longitude": <%= longitude %>,"battery_charging": "<%= battery.is_charging %>","ismoving": "<%= is_moving %>","event": "<%= event %>","age": <%= age %>,"altitude": <%= altitude %>,"odometer": <%= odometer %>,"activity_type": "<%= activity.type %>","activity_confidence": <%= activity.confidence %>,"battery_level": <%= battery.level %>,"uuid":  "<%= uuid %>","heading":  <%= heading %>,"altitude_accuracy": <%= altitude_accuracy %>,"speed": <%= speed %>,"accuracy": <%= accuracy %>, "speed_accuracy": <%= speed_accuracy %>, "ellipsoidal_altitude":<%= ellipsoidal_altitude%>, "heading_accuracy": <%=heading_accuracy%>}',
        locationAuthorizationRequest: 'Always',

        backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow 𝗠𝗲𝘁𝗮 𝗦𝗮𝗹𝗲 to access this device's location even when the app is closed or not in use.",
          message:
              "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "Always"',
          negativeAction: 'Cancel',
        ),
        autoSync: true,

        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        preventSuspend: true,
        // location updates interval -- 30 seconds
        locationUpdateInterval: 30000,
        heartbeatInterval: 60, // heartbeat interval after 100 seconds

        // locationAuthorizationAlert: {
        //   'titleWhenNotEnabled': 'Yo, location-services not enabled',
        //   'titleWhenOff': 'Yo, location-services OFF',
        //   'instructions':
        //       "You must enable 'Always' in location-services to start tracking",
        //   'cancelButton': 'Cancel',
        //   'settingsButton': 'Settings'
        // },
      ),
    ).then((bg.State state) async {
      log('[ready] ${state.toMap()}');
      log('[didDeviceReboot] ${state.didDeviceReboot}');
      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
      _enabled = state.enabled;
      _isMoving = state.isMoving;
    }).catchError((error) {
      log('[ready] ERROR: $error');
    });
    `

**Comment by christocracy** [comment]
Why don't you log the received JSON at your server?

**Comment by hafeezrana** [comment]
correct. it even doesn't work for the foreground too. due to json schema difference. how can I make the json similar to android and I'm also unable to watch the iOS json body request to my server using Database inspection as achieved in Android.

**Comment by christocracy** [comment]
> it even doesn't work for the foreground 

That's not what I meant.

I'm not aware of a difference in json between Android / iOS.

!! HAVE YOUR SERVER CODE LOG THE RECEIVED JSON AND LET ME KNOW WHAT IS THE PROBLEM !!

**Comment by hafeezrana** [comment]
It doesn't return the raw json String `responseText` from SERVER CODE for IOS only:

`HTTP Response: [HttpEvent {success: false, status: 0, responseText: }]`

But for Android it returns if the json schema is invalid too.

**Comment by christocracy** [comment]
At your server, log the **received** JSON that the plug-in **sent** to your server, **in your server logs**.

**Comment by hafeezrana** [comment]
Did you make any restriction of `http` security for iOS instead of `https`?  because my url is based on `http`.

**Comment by christocracy** [comment]
No.  Did you get a response from your server **or not**?

**Comment by christocracy** [comment]
Are you observing your app logs with app launched in XCode?

**Comment by hafeezrana** [comment]
On Xcode log the http Error response is:

`⚠️-[HttpResponse handleResponse] HTTP ERROR: 0
***
* The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
*
{
    NSErrorFailingURLKey = "http://portal.sabirsgroup.com:8184/ords/sabroso_ords/HR-ADMIN/tracking-data";
    NSErrorFailingURLStringKey = "http://portal.sabirsgroup.com:8184/ords/sabroso_ords/HR-ADMIN/tracking-data";
    NSLocalizedDescription = "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1022 \"(null)\"";
    "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalDataTask <C4EF9D75-81BC-4AE0-A640-F6C48DC7395E>.<1>";
    "_NSURLErrorRelatedURLSessionTaskErrorKey" =     (
        "LocalDataTask <C4EF9D75-81BC-4AE0-A640-F6C48DC7395E>.<1>"
    );
}`

**Comment by hafeezrana** [comment]
finally fixed it. The error was because of insecure HTTP connection. for that, I followed this guide
[https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi](url)

with placing this code into info.plist file

`<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        <key>NSExceptionDomains</key>
        <dict>
            <key>yourdomain.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
       </dict>
  </dict>`

**Comment by christocracy** [comment]
It's important to boot your app in XCode and carefully observe the logs there. **when something unusual happens**, that's the **first** thing to do.  Quite often, the answer is right there.

Instead of spending 3 days wasting time and travelling down irrelevant rabbit holes.
