### ISSUE TITLE
Getting random points frequently.

### ISSUE THREAD

**Issue by nvamsi214** [transistorsoft/flutter_background_geolocation#125]
## Your Environment
* Plugin version: ^1.2.4
* Platform:Android
* OS version: All
* Device manufacturer / model:
* Flutter info (`flutter doctor`):Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN;
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
    distanceFilter: 0,
    stopOnTerminate: false,
    startOnBoot: true,
    debug: enableDebug,
    enableHeadless: true,
    reset: true,
    autoSync: true,
    batchSync: true,
    logLevel: enableDebug? 5 : null,
    foregroundService: true,
    heartbeatInterval: 120,
    extras: {
      'oid': OID,
      'uid': UID
    },
    locationUpdateInterval: 15000,
    fastestLocationUpdateInterval:  7500,
  )).then((bg.State state) {
    if(isStart == true) {
      if (state.enabled == false) {
        if(isOverlay && Platform.isAndroid) {
          _startService();
        }
        _onClickEnable(true);
      }
    } else {
      if(isOverlay && Platform.isAndroid) {
        if(enableDebug) {
          bg.BackgroundGeolocation.emailLog("support@flockone.com");
        }
        _stopService();
      }
      _onClickEnable(false);
    }
  });
```

## Expected Behavior
 Get more accurate locations with better accuracy even when user is inside building. Else ignore the points based on accuracy.

## Actual Behaviour
Getting random points which are far from current location with less accuracy values(<50).

## Steps to Reproduce

1.Initialising the plugin
2.Stay inside a building or parking lot.

## Context

Trying to update user current location depending on accuracy (i.e < 50). But getting random points when user is still and the  accuracy values <50 (frequent when user is inside building or parking lot) .  Do i need to change/add any parameters in Config so that i can get more accurate results
Attaching image with route drawn for fetched locations. ![image](https://user-images.githubusercontent.com/33240181/65761706-01be1580-e13d-11e9-9c59-6363da9bff15.png)

**NOTE :** 
All the points in the above image are with accuracy <50.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Use a distanceFilter > 0.
