### ISSUE TITLE
Geofence only mode

### ISSUE THREAD

**Issue by sunnykinger** [transistorsoft/flutter_background_geolocation#1250]
I have a question regarding the geofence only mode. Is the physical activity permission mandatory for geofence mode to work? 

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Is the physical activity permission mandatory for geofence mode to work?

No
