### ISSUE TITLE
Intervals Updates 

### ISSUE THREAD

**Issue by MaboteChobokoane** [transistorsoft/flutter_background_geolocation#1252]
## Your Environment 
* Plugin version: 4.13.5
* Platform: iOS or Android
* OS version: ios 12 > and android 9 >
* Device manufacturer / model:  flutter 3.19.3 and dart 3.3.1
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

 bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      preventSuspend: true,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      locationUpdateInterval: 120000,
      heartbeatInterval: 60,
      isMoving: false,
      foregroundService: true,
      enableHeadless: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      reset: true,
    )).then((bg.State state) async {
      final appState = FFAppState();
      await appState.initializePersistedState();

      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });

    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });
    bg.BackgroundGeolocation.onLocation((bg.Location location) async {
      bg.BackgroundGeolocation.getCurrentPosition(
              samples: 1, persist: true, timeout: 120)
          .then((bg.Location location) async {
        await locationUpdates(
          FFAppState().authToken2,
          FFAppState().appDisplayVersion2,
          FFAppState().deviceId2,
          FFAppState().driverName2,
          FFAppState().driverPhoneNumber2,
          FFAppState().checkedIntoVehicleTime2,
          FFAppState().driverRegisteredTime2,
          FFAppState().latitude2,
          FFAppState().longitude2,
          FFAppState().numberOfLoads2,
          FFAppState().vehicleRegNo2,
          FFAppState().carrierName2,
          FFAppState().blupathId2,
          FFAppState().dbLoadId2,
          FFAppState().loadId2,
          FFAppState().shipperName2,
        );
      });
    }, (bg.LocationError error) {
      print('[onLocation] ERROR: ${error}');
    });
```

### **Expected Behavior**

It currently invokes the locationUpdate function every second, but I desire to call this function every 2 minutes instead.

### **Actual Behavior**

I aim to invoke locationUpdate at intervals of two minutes by utilizing locationUpdateInterval.

**Comment by christocracy** [comment]
>  distanceFilter: 0,

The location APIs operate on *distance* not *time*.  If you set `distanceFilter: 0`, you're going to get a location about every second.

Try setting it to `100` or higher.  Also read the API docs `Config.distanceFilter`.  `distanceFilter` tells the native Location API to "*record a location every distanceFilter meters*".

However, Android *does* allow time-based location updates with `Config.locationUpdateInterval` (read the API docs).  iOS is **strictly** distance-based.

**Comment by ralon99** [comment]
i'm also trying to get the onLocation even trigger by time interval (only on android, when my tablet is connected through USB, just for debugging) but i can't make it happans.. there are so many parameters for the config that i got lost..
by reading the documentation on config.dart i thought that the combination of 'distanceFilter: 0' and 'locationUpdateInterval: 10000' will be enough for achieving my goal but it didn't..
i tried to add parameters 1 by 1 and see if something will make the onLocation execute as i expected, but nothing works.
so far this is what i got on the config func:
`bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 10000,
        fastestLocationUpdateInterval: 10000,
        allowIdenticalLocations: true,
        disableMotionActivityUpdates: true,
        isMoving: false,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        enableHeadless: true,
        disableStopDetection: true,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: PermissionRationale(
            title: "Allow {applicationName} to access to this device's location in the background?",
            message: "In order to track your activity in the background, please enable '{backgroundPermissionOptionLabel}' location permission",
            positiveAction: "Change to '{backgroundPermissionOptionLabel}'",
            negativeAction: "Cancel")
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });`
    
    no matter what i try the onLocation function only triggers once when i load the app.
    can anyone advise what should i try next?

**Comment by christocracy** [comment]
Are simulating location with a mock location app?  If so, then Config.fastestLocationUpdateInterval controls the rate received by *other* apps.

you should also read the wiki “Philosophy of Operation” and “Debugging” and learn about the method .changePace for manually toggling between “stationary” and “moving” states.
