### ISSUE TITLE
[iOS] Not pausing aggressive gps tracking in stationary - battery drain

### ISSUE THREAD

**Issue by marcslavec** [transistorsoft/flutter_background_geolocation#1253]
iOS is not stopping aggressive gps tracking even though the phone is still at one place

## Your Environment
* Plugin version: 4.14.0
* Platform: iOS
* OS version: 17.4
* Device manufacturer / model: iPhone
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.10.6, on macOS 14.3.1 23D60 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 2023.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.87.0)
[✓] VS Code (version 1.79.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Christian’s Work iPhone SE. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
        debug: false,
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 30,
        startOnBoot: true,
        stopOnTerminate: true,
        stopOnStationary: false,
        activityType: Config.ACTIVITY_TYPE_OTHER,
        elasticityMultiplier: 3,
        minimumActivityRecognitionConfidence: 80,
        showsBackgroundLocationIndicator: false,
        stationaryRadius: 150,
        stopTimeout: 3,
      );
```

## Expected Behavior
If the iPhone is still and not moving. Put the tracking into a 'sleep' mode and only start it again if exiting the set geofence area.

## Actual Behavior
As you can see in the provided screenshot, even though the phone was not moving - the battery keeps draining in a linear way. 

## Context
As you can see on the graph between 3pm(15) and around 5pm(17) there was movement (walking/going by tram), but afterwards the phone was not touched at all and always on the same place.
No other app has been installed to influence the shown battery graph of Apple.

![File](https://github.com/transistorsoft/flutter_background_geolocation/assets/5173464/a698b6d4-cab2-41de-a728-7cea94a7685e)

## Debug logs

</details>

**Comment by christocracy** [comment]
A battery graph is inconclusive and doesn't implicate the plugin.

See Wiki "Debugging" and learn to observe the logs from the plugin.  The plugin holds 3 days (by default) of logs in its SQLite database.

Also, set `showsBackgroundLocationIndicator: true` so that you can easily see when location-services are ON / OFF.

If location-services are OFF, the plugin consumes no energy.
