### ISSUE TITLE
iOS: preventSuspend = true + stopTimeout = very high value +  "While in use permission" + low battery. Unexpected behaviour

### ISSUE THREAD

**Issue by CarlosCabarcos** [transistorsoft/flutter_background_geolocation#1255]
## Your Environment
* Plugin version: ^4.14.0
* Platform: iOS
* OS version: Several
* Device manufacturer / model: Several iPhones
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
With preventSuspend = true and stopTimeout = 1440, the device should continue tracking locations when the app is running in the background, regardless of if the user stays still for a while or is constantly moving. The plugin should never enter the stationary state and the app should never be "go to sleep" in the background.

## Actual Behavior
If the **location permission is "When in use"** (as opposite to "Always") and the **battery of the device is low** (aprox. < 20%), if the **user stays still for a few minutes**, it seems that something is not working as expected and the tracking stops. If the user later moves for a while and decides to bring the app to the foreground again, the tracking will start again and he will see that no locations were tracked between the place where he stopped and the place where he turned on the app again. Basically, when drawing a route, it will make a straight line between both points.

## Steps to Reproduce

1. Turn on location tracking.
2. Grant "WHILE USING APP" permission level.
3. Lock phone and put in your pocket.
4. Walk around.
5. When the battery is low, stay still for a few minutes.
6. Continue walking around.
7. Open the app again.
8. The period after the stop in point 5 won't be tracked correctly.

## Context
We're trying to track routes when users exercise.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>With preventSuspend = true and stopTimeout = 1440

iOS `preventSuspend` requires `Always`.  It doesn't work with `WhenInUse`.

There is a major consequences in behaviour between `WhenInUse` vs `Always`.

One major consequence is that the plugin **CANNOT** automatically trigger location-tracking in the background unless manually engaged in the foreground by calling `.changePace(true)`, like a *Jogging App* where the user manually clicks a `[Start Workout]` button.

```dart
await BackgroundGeolocation.start();
// Manually tell the plugin to turn on Location Services and begin tracking.
await BackgroundGeolocation.changePace(true);
```

**Comment by CarlosCabarcos** [comment]
Hi @christocracy thanks for the fast reply. I'm really surprised at this: 

"iOS preventSuspend requires Always. It doesn't work with WhenInUse."

Since we added preventSuspend, it seemed like the issue was only happening with low battery, while before, it was happening at any time. I guess, since it's based on observations of our test users, the feedback might be missleading...

Then, on iOS, without using "Always", is there any way in which can prevent the phone from stopping the tracking while the App is in the background if motion stops?

Thank you for your help.

**Comment by christocracy** [comment]
>I'm really surprised at this:

`preventSuspend` is my own hack.  It relies on periodically turning on location-services for a brief instant in order to request another 30s of background-time from the OS (using [`beginBackgroundTaskWithExpirationHandler`](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio?language=objc).  iOS does not allow an app to *turn ON* location-services "for a brief instant" in the background with `WhenInUse`.  Thus, `preventSuspend` **requires** `Always` location authorization.

> is there any way in which can prevent the phone from stopping the tracking while the App is in the background if motion stops?

Set a *very* high `Config.stopTimeout`.

```dart
await BackgroundGeolocation.ready(Config(
  stopTimeout: 10000
));

await BackgroundGeolocation.start();
await BackgroundGeolocation.changePace(true);
```

Be sure to call `.changePace(false)` when you're done or you're going to kill the battery in a few hours.

**Comment by CarlosCabarcos** [comment]
I already set stopTimeout to a high value (1440m which is a full 24h) we are working with training sessions, so it should be way more than enough. However, we are still experiencing these situations where the tracking stops working while the phone is in the users pocket.

Example: 
1. Start workout (start tracking)
    That is: 
    await BackgroundGeolocation.start();
    await BackgroundGeolocation.changePace(true);
2. Lock the phone, app goes to background.
3. Run for 30 minutes 
4. Stop for 5 minutes 
5. Run for another 30 minutes.
6. Unlock phone, open App and stop workout (stop tracking).
    changePace(false) is called here.
7. Check results and see route of the whole workout.

When checking the route, there are no tracked locations during step 5.
This only happens on iOS and with "When in use".
- stopTimeout is set to 1440
- preventSuspend is set to true (although, from what you told me before, this does nothing since we don't have "Always" permission).
- It seems that this issue happens more often when battery is low (although I'm not 100% certain about the accuracy of this statement).

Any clue about what might be happening? Or any suggestions on how to get it to work with "When in use"?

**Comment by christocracy** [comment]
> Any clue about what might be happening?

Not without logs.  See wiki "Debugging" and search api docs "emailLog".

**Comment by CarlosCabarcos** [comment]
Ok, thank you very much, I'll try to get some logs see if they clear up something...
