### ISSUE TITLE
Facing a 5-hour timezone lag compared to system time 

### ISSUE THREAD

**Issue by hafeezrana** [transistorsoft/flutter_background_geolocation#1259]
## Your Environment
* Plugin version: 4.12.0
* Platform: iOS or Android 
* OS version: 12
* Device manufacturer / model: Pixel 6 pro
* Flutter Version: 3.16.0
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
locationTemplate:  {"timeStamp" : "<%=timestamp %>"}


```

## Expected Behavior
My System/mobile time 11:27 AM
2024-03-19T011:27:26.378Z

## Actual Behavior
Received Time from Tracking Service -- which is 5 hours behind the expected timestamp
2024-03-19T06:27:26.378Z

## Context
I'm trying to get the system timestamp instead of UTC / USA, Canada time.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in provides timestamp in UTC format, not USA/Canada.

**Comment by hafeezrana** [comment]
Whatever but The question is how can I get according to my system datetime
please

**Comment by christocracy** [comment]
By creating a new "Date" instance with your code.

For example, if I open the Javascript console in the browser and instantiate a `Date` instance with your timestamp, I get a local time of `2:27 AM`:
```
2024-03-19T06:27:26.378Z
```

<img width="665" alt="Screenshot 2024-03-19 at 8 44 13 PM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/45305690-f13a-42ed-9c05-f247f8a9ddaf">

**Comment by hafeezrana** [comment]
Fixed it.Thank you so much!

**Comment by aweiand** [comment]
> The plug-in provides timestamp in UTC format, not USA/Canada.

The timestamp it was given by the app coming from where? I ask this thinking if the user change the current date/time on the device manually. In this case, the recorded timestamp it was "wrong" too, or it's given by a trusted source?

**Comment by christocracy** [comment]
The timestamp comes from the OS’s Location API.

**Comment by phong010198** [comment]
Hi. How do you manipulate the `timestamp`?
I tried
```dart
locationTemplate:
          '{"updateTime":"${DateFormat('dd/MM/yyyy HH:mm:ss')
                    .format(DateTime.parse("<%= timestamp %>")
                    .add(const Duration(hours: 7)))}"}',
```
but the template doesn't seem to allow function.

**Comment by christocracy** [comment]
The template is rendered purely in native code.  You can’t add JavaScript to the template.

it is not possible to change the timestamp format.

**Comment by phong010198** [comment]
> The template is rendered purely in native code. You can’t add Dart code to the template.
> 
> it is not possible to change the timestamp format.

Thank you.
