### ISSUE TITLE
Android Build Modes and Code Shrinkage Question

### ISSUE THREAD

**Issue by kieranmccwayleadr** [transistorsoft/flutter_background_geolocation#1260]
Hi guys, no issues but questions before we buy licences for our apps. There is no question template to work from. 

I have the library set up and working on iOS and Android for all the states of Foreground, Background and terminated (Android). I now want to send this for testing with our QA department but have two questions to try understand how this will build in our CI/CD tool:

- When using `flutter build {OS} --release` I understand this is creating the release version of our app and we will need a licence for the app to work, but for testing before we send to the app stores, would using the `profile` build be best? Does this also require a licence to work on Android? We can send a dev build, but that isn't the best option here.
- You mention to use `shrinkResources false` in the release profile in Gradle. Is this a prereq for using this library? What happens if we don't use this. We have always shrunk of source code while building.

We want to make sure everything is working before purchasing the licences for production so these questions are quite important to progress.

**Comment by christocracy** [comment]
>would using the profile build be best?

I'm pretty sure `profile` is a release build for Android.

iOS doesn't consume keys, so you're free to use release builds.

>You mention to use shrinkResources false in the release profile in Gradle. Is this a prereq for using this library?

Yes.  This is a problem with cross-platform frameworks, such as flutter, since required resources are stripped from the compiled app binary if they're not explicitly referenced with Java code (they're referenced with `Dart` config options that translate into Java.

**Comment by kieranmccwayleadr** [comment]
@christocracy thanks for those. Yeah `profile` has release settings with devtools enabled for it. I was hoping we'd it somewhere in the middle. We just created a `dev` build for testing android.

Will see how this looks now on a production build if it has drastic size difference, doubt it will. But we are happy with everything there now and purchasing a licence. Thank you
