### ISSUE TITLE
onHeartbeat is not working in production (release mode) apk 

### ISSUE THREAD

**Issue by AniketStemmOne** [transistorsoft/flutter_background_geolocation#1263]
## Your Environment
* Plugin version:  flutter_background_geolocation: ^4.13.5
* Platform: Android
* OS version: 14
* Device manufacturer / model: CPH2381

* Flutter info (`flutter doctor`):  

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3155], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019 16.11.20)
[√] Android Studio (version 2021.3)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.87.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
distanceFilter: double.parse(radius),
enableHeadless: true,
stopOnTerminate: false,
autoSync: true,
geofenceModeHighAccuracy: false,
startOnBoot: true,
debug: false,
geofenceInitialTriggerEntry: true,
logLevel: bg.Config.LOG_LEVEL_VERBOSE,
disableStopDetection: true,
pausesLocationUpdatesAutomatically: false,
heartbeatInterval: 300,
preventSuspend: true))
.then((bg.State state) {
if (!state.enabled) {
bg.BackgroundGeolocation.start();
}
});

bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) async {
print("Heatbeat");
});

```

## Expected Behavior
Heartbeat should work in production env (in release mode) apk every 5minutes

## Actual Behavior
HeartBeat is not working in flutter release mode
but it is working in debug mode

## Context

Tracking location of user using heartbeat every 5 minutes

## Debug logs
No logs its not triggering the function 
  bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) async {
  log("in heartbeat");
  });

and cannot view logs in release apk...

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
 [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(25977):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
W/System  (25977): Ignoring header If-None-Match because its value was null.
D/TrafficStats(25977): tagSocket(113) with statsTag=0xffffffff, statsUid=-1
I/TSLocationManager(25977): [c.t.l.scheduler.ScheduleEvent a] 
I/TSLocationManager(25977): ╔═════════════════════════════════════════════
I/TSLocationManager(25977): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(25977): ╠═════════════════════════════════════════════
D/TSLocationManager(25977): [c.t.l.event.TerminateEvent$a onChange] 
D/TSLocationManager(25977):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
W/mone.traceforce(25977): Reducing the number of considered missed Gc histogram windows from 136 to 100
I/TSLocationManager(25977): [c.t.l.scheduler.ScheduleEvent a] 
I/TSLocationManager(25977): ╔═════════════════════════════════════════════
I/TSLocationManager(25977): ║ ⏰ OneShot event fired: HEARTBEAT
I/TSLocationManager(25977): ╠═════════════════════════════════════════════
I/TSLocationManager(25977): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(25977):   ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
D/TSLocationManager(25977): [c.t.l.service.HeartbeatService onHeartbeat] ❤️
W/FlutterJNI(21649): FlutterJNI.init called more than once

its in debug mode apk
```

</details>

**Comment by AniketStemmOne** [comment]
In Release mode of apk we cannot view logs 
everythings is working fine in release mode but heartbeat is not triggering

**Comment by christocracy** [comment]
> In Release mode of apk we cannot view logs

Of course you can.  Build locally for release

**Comment by AniketStemmOne** [comment]
I build locally but It was only showing normal logs not showing flutter_background_geolocation logs 
please tell me How to get all logs

**Comment by christocracy** [comment]
Read wiki “Debugging”.

I always test with release builds.  I have no issue viewing the logs.

**Comment by AniketStemmOne** [comment]
here are the logs 
<details>
 03-26 18:49:15.114 INFO [LocationAuthorization withBackgroundPermission] 
I/flutter (29774):   🔵  LocationAuthorization: Requesting Background permission
I/flutter (29774): 03-26 18:49:15.281 DEBUG [LifecycleManager onResume] ☯️  onResume
I/flutter (29774): 03-26 18:49:16.016 DEBUG [LifecycleManager onPause] ☯️  onPause
I/flutter (29774): 03-26 18:49:16.258 INFO [LocationAuthorization$j onPermissionGranted]
I/flutter (29774):   ✅  LocationAuthorization: Permission granted
I/flutter (29774): 03-26 18:49:16.284 INFO [LocationAuthorization d]
I/flutter (29774):   🔵  Should show backgroundPermissionRationale? true
I/flutter (29774): 03-26 18:49:16.292 DEBUG [LifecycleManager onResume] ☯️  onResume
I/flutter (29774): 03-26 18:49:16.548 DEBUG [TSLocationManagerActivity a] android.permission.ACCESS_BACKGROUND_LOCATION
I/flutter (29774): 03-26 18:49:17.460 DEBUG [TSLocationManagerActivity c] eventCount: 0
I/flutter (29774): 03-26 18:49:17.622 DEBUG [TSLocationManagerActivity onDestroy]
I/flutter (29774): 03-26 18:49:18.283 DEBUG [LifecycleManager onPause] ☯️  onPause
I/flutter (29774): 03-26 18:49:18.732 DEBUG [LifecycleManager onStop] ☯️  onStop
I/flutter (29774): 03-26 18:49:19.671 DEBUG [LifecycleManager onStart] ☯️  onStart
I/flutter (29774): 03-26 18:49:19
I/flutter (29774): FO [LocationAuthorization$j onPermissionGranted]
I/flutter (29774):   ✅  LocationAuthorization: Permission granted
I/flutter (29774): 03-26 18:49:19.796 INFO [TSGeofenceManager start]
I/flutter (29774):   🎾  Start monitoring geofences
I/flutter (29774): 03-26 18:49:19.818 DEBUG [LifecycleManager onResume] ☯️  onResume
I/flutter (29774): 03-26 18:49:19.838 DEBUG [HttpService startMonitoringConnectivityChanges]
I/flutter (29774):   🎾  Start monitoring connectivity changes
I/flutter (29774): 03-26 18:49:19.884 DEBUG [DeviceSettings startMonitoringPowerSaveChanges]
I/flutter (29774):   🎾  Start monitoring powersave changes
I/flutter (29774): 03-26 18:49:19.932 INFO [ActivityRecognitionService start]
I/flutter (29774):   🎾  Start motion-activity updates

03-26 18:49:19.983 INFO [HeartbeatService start]
I/flutter (29774):   🎾  Start heartbeat (300s)
I/flutter (29774): 03-26 18:49:19.992 INFO [HeartbeatService start]
I/flutter (29774):   🎾  Start heartbeat (300s)
I/flutter (29774): 03-26 18:49:20.008 INFO [TSScheduleManager oneShot]
I/flutter (29774):   ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
I/flutter (29774): 03-26 18:49:20.010 INFO [TSScheduleManager oneShot]
I/flutter (29774):   ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
I/flutter (29774): 03-26 18:49:20.036 INFO [T
I/flutter (29774): rackingService changePace]
I/flutter (29774):   🔵  setPace: false → false
I/flutter (29774): 03-26 18:49:20.039 INFO [TrackingService changePace]
I/flutter (29774):   🔵  setPace: false → false
I/flutter (29774): 03-26 18:49:20.040 INFO [TSProviderManager a]
I/flutter (29774): ╔═════════════════════════════════════════════
I/flutter (29774): ║ Location-provider change: true
I/flutter (29774): ╠═════════════════════════════════════════════
I/flutter (29774): ╟─ GPS: true
I/flutter (29774): ╟─ Network: true
I/flutter (29774): ╟─ AP Mode: false
I/flutter (29774):
I/flutter (29774): 03-26 18:49:20.061 DEBUG [HttpService a]
I/flutter (29774): ╔═════════════════════════════════════════════
I/flutter (29774): ║ 📶  Connectivity change: connected? true
I/flutter (29774): ╠═════════════════════════════════════════════

03-26 18:49:20.111 WARN [TSLocationManager onSingleLocationResult]
I/flutter (29774):   ℹ️  Failed t
I/flutter (29774): 8:49:20.112 DEBUG [TSLocationManager a] Median accuracy: 21.683
I/flutter (29774): 03-26 18:49:20.118 DEBUG [LocationAuthorization withPermission]
I/flutter (29774):   ℹ️  LocationAuthorization: Permission granted
I/flutter (29774): 03-26 18:49:20.119 INFO [TSLocationManager a]
I/flutter (29774): ╔═════════════════════════════════════════════
I/flutter (29774): ║ providerchange LocationResult: 2 (120524ms old)
I/flutter (29774): ╠═════════════════════════════════════════════
I/flutter (29774): ╟─ 📍  Location[fused 18.56****,73.92**** hAcc=21.683 et=+2h59m20s92ms alt=516.7000122070312 vAcc=1.6099865], time: 1711459039595
I/flutter (29774):
I/flutter (29774): 03-26 18:49:20.119 DEBUG [TSLocationManager a] Median accuracy: 21.683
I/flutter (29774): 03-26 18:49:20.123 DEBUG [LocationAuthorization withPermission]
I/flutter (29774):   ℹ️  LocationAuthorization: Permission granted
I/flutter (29774): 03-26 18:49:20.130 DEBUG [TSLocationManagerActivity a] locationsettings
I/flutter (29774): 03-26 18:49:20.130 DEBUG [TSConfig translateDesiredAccuracy] transla
I/flutter (29774): ificationChannel{mId='com.stemmone.traceforceTSLocationManager', mName=TSLocationManager, mDescription=, mImportance=1, mBypassDnd=false, mLockscreenVisibility=-1, mSound=null, mLights=false, mLightColor=0, mVibration=null, mUserLockedFields=0, mUserVisibleTaskShown=false, mVibrationEnabled=false, mShowBadge=false, mDeleted=false, mDeletedTimeMs=-1, mGroup='null', mAudioAttributes=null, mBlockableSystem=false, mAllowBubbles=-1, mImportanceLockedDefaultApp=false, mOriginalImp=-1000, mParent=null, mConversationId=null, mDemoted=false, mImportantConvo=false, mShowBanner=false, mFold=false, mOpush=false, mShowIcon=false, mMaxMessages=-1, mSupportNumBadge=false, mBadgeOption=0, mChangeableFold=true, mChangeableShowIcon=true, mUnimportant=true, mTempShowBadge=false}
I/flutter (29774): 03-26 18:49:20.234 DEBUG [AbstractService a]
I/flutter (29774):   🎾  start [ActivityRecognitionService  startId: 1, eventCount: 1]
I/flutter (29774): 03-26 18:49:20.236 DEBUG [ActivityRecognitionService a]
I/flutter (29774):   🚘 ️DetectedActivity [type=STILL, confidence=100]
I/flutter (29774): 03-26
I/flutter (29774): 18:49:20.241 DEBUG [AbstractService a]
I/flutter (29774):   ⚙️︎   FINISH [ActivityRecognitionService startId: 1, eventCount: 0, sticky: false]
I/flutter (29774): 03-26 18:49:20.250 DEBUG [AbstractService a]

 03-26 18:49:20.264 DEBUG [AbstractService a]
I/flutter (29774):   ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 1, sticky: true]
I/flutter (29774): 03-26 18:49:20.281 DEBUG [AbstractService a]
I/flutter (29774):   ⚙️︎   FINISH [LocationRequestService startId: 2, eventCount: 0, sticky: true]
I/flutter (29774): 03-26 18:49:20.346 DEBUG [TSLocationManagerActivity a] locationsettings
I/flutter (29774): 03-26 18:49:20.346 DEBUG [TSConfig translateDesiredAccuracy] tra
I/flutter (29774): ateDesiredAccuracy (true): 10
I/flutter (29774): 03-26 18:49:20.409 DEBUG [TSLocationManagerActivity onDestroy]
I/flutter (29774): 03-26 18:49:20.444 DEBUG [AbstractService f] 
I/flutter (29774):   ⚙️︎  ActivityRecognitionService.stopSelfResult(1): true
I/flutter (29774): 03-26 18:49:20.444 DEBUG [AbstractService onDestroy]
I/flutter (29774):   🔴  ActivityRecognitionService stopped
I/flutter (29774): 03-26 18:49:20.447 DEBUG [TSLocationManagerActivity c] eventCount: 0
I/flutter (29774): 03-26 18:49:20.515 DEBUG [TSLocationManagerActivity onDestroy]
I/flutter (29774): 03-26 18:49:20.566 INFO [GeofenceDAO create]
I/flutter (29774):   ✅  Office
I/flutter (29774): [log] success: 03-26 18:49:15.114 INFO [LocationAuthorization withBackgroundPermission]
I/flutter (29774):   🔵  LocationAuthorization: Requesting Background permission
I/flutter (29774): 03-26 18:49:15.281 DEBUG [LifecycleManager onResume] ☯️  onResume
I/flutter (29774): 03-26 18:49:16.016 DEBUG [LifecycleManager onPause] ☯️  onPause
I/flutter (29774): 03-26 18:49:16.258 INFO [LocationAuthorization$j onPermissionGranted]
I/flutter (29774):   ✅  LocationAuthorization: Permission granted
I/flutter (29774): 03-26 18:49:16.284 INFO [LocationAuthorization d]
I/flutter (29774):   🔵  Should show backgroundPermissionRationale? true
I/flutter (29774): 03-26 18:49:16.292 DEBUG [LifecycleManager onResume] ☯️  onResume
I/flutter (29774): 03-26 18:49:16.548 DEBUG [TSLocationManagerActivity a] android.permission.ACCESS_BACKGROUND_LOCATION
I/flutter (29774): 03-26 18:49:17.460 DEBUG [TSLocationManagerActivity c] eventCount: 0
I/flutter (29774): 03-26 18:49:17.622 DEBUG [TSLocationManagerActivity onDestroy]
I/flutter (29774): 03-26 18:49:18.283 DEBUG [LifecycleManager onPause] ☯️  onPause
I/flutter (29774): 03-26 18:49:18.732 DEBUG [LifecycleManager onStop] ☯️  onStop
I/flutter (29774): 03-26 18:49:19.671 DEBUG [LifecycleManager onStart] ☯️  onStart

</details>

**Comment by christocracy** [comment]
Now let it run for 15 minutes and watch your logs.
