### ISSUE TITLE
Headless works fine in debug mode and doesnt work in release mode.

### ISSUE THREAD

**Issue by zielmar** [transistorsoft/flutter_background_geolocation#1266]
## Your Environment
* Plugin version:4.15.1
* Platform: iOS or Android: Android
* OS version:
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3374], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
[√] Android Studio (version 2022.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void main() {
  runApp(const MyApp());
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
  bg.BackgroundGeolocation.ready(bg.Config(
      distanceFilter: 6,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      preventSuspend: true,
      disableLocationAuthorizationAlert: false,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      disableElasticity: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      heartbeatInterval: 4,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Zgadzasz się ...?",
          message:
          "... {backgroundPermissionOptionLabel} n...",
          positiveAction: "Zgoda na {backgroundPermissionOptionLabel}",
          negativeAction: "Anuluj")));
}
```

## Expected Behavior
headless should work

## Actual Behavior
In release mode there is an error when starting headless:
2024-03-29 23:16:19.090 26223-26223 FlutterGeolocator       pid-26223                            E  Geolocator position updates stopped
2024-03-29 23:16:19.090 26223-26223 FlutterGeolocator       pid-26223                            E  There is still another flutter engine connected, not stopping location service
2024-03-29 23:16:19.109 26223-26223 FlutterGeolocator       pid-26223                            D  Flutter engine disconnected. Connected engine count 0
2024-03-29 23:16:19.110 26223-26223 FlutterGeolocator       pid-26223                            D  Tried to stop listening when no MethodChannel had been initialized.
2024-03-29 23:16:19.129 26223-26223 FlutterGeolocator       pid-26223                            D  Unbinding from location service.
2024-03-29 23:16:19.129 26223-26223 FlutterGeolocator       pid-26223                            D  Destroying location service.
2024-03-29 23:16:19.129 26223-26223 FlutterGeolocator       pid-26223                            D  Stopping location service.
2024-03-29 23:16:19.129 26223-26223 FlutterGeolocator       pid-26223                            D  Destroyed location service.
2024-03-29 23:16:28.314 26223-26223 FlutterGeolocator       pid-26223                            D  Creating service.
2024-03-29 23:16:28.315 26223-26223 FlutterGeolocator       pid-26223                            D  Binding to location service.
2024-03-29 23:16:28.318 26223-26223 FlutterGeolocator       pid-26223                            D  Flutter engine connected. Connected engine count 1
2024-03-29 23:16:28.319 26223-28490 flutter                 pid-26223                            E  [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception:
                                                                                                    NoSuchMethodError: No top-level getter 'headlessTask' declared.
                                                                                                    Receiver: top-level
                                                                                                    Tried calling: headlessTask
                                                                                                    #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:191)
                                                                                                    #1      __getCallbackFromHandle$Method$FfiNative (dart:ui)
                                                                                                    #2      _getCallbackFromHandle (dart:ui/natives.dart:95)
                                                                                                    #3      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:74)
                                                                                                    #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543)
                                                                                                    #5      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:73)
                                                                                                    #6      _headlessCallbackDispatcher.<anonymous closure> (package:flutter_background_geolocation/models/background_geolocation.dart:1740)
                                                                                                    #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571)
                                                                                                    #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564)
                                                                                                    #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603)
                                                                                                    #10     _invoke2 (dart:ui/hooks.dart:344)
                                                                                                    #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
                                                                                                    #12     _Channel.push (dart:ui/channel_buffers.dart:135)
                                                                                                    #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
                                                                                                    #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737)
                                                                                                    #15     _dispatchPlatformMessage (dart:ui/hooks.dart:257)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You’re having an issue with your HeadlessTask and you’re not even providing that function.

**Comment by zielmar** [comment]
even empty doesnt work i release:

void headlessTask(bg.HeadlessEvent headlessEvent) async {


}

**Comment by christocracy** [comment]
I would not expect even that *empty* function to work since it doesn’t include the **REQUIRED** annotation, as documented.  Go back and read the documentation for implementing a headless task, especially the comment right above it, stating: 

>Be sure to annotate your callback function to avoid issues in release mode on Flutter >= 3.3.0

![IMG_0684](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/d5936131-8a7b-4638-a6d6-86afcec26e2e)

**Comment by zielmar** [comment]
I tried with @pragma('vm:entry-point'). No effect. :-(

**Comment by christocracy** [comment]
Create for me a simple *hello_world* which reproduces the error.  Share it with me in a public GitHub repo.

**Comment by zielmar** [comment]
ok must go sleep with @pragma('vm:entry-point') it works, sorry

**Comment by christocracy** [comment]
Pay careful attention to the documentation.  Nothing is by accident.
