### ISSUE TITLE
desiredAccuracy of coords data is not appropriate

### ISSUE THREAD

**Issue by sohamD07** [transistorsoft/flutter_background_geolocation#1268]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      bg.Config(
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter,
        stopTimeout: 15,
        heartbeatInterval: 120,
        backgroundPermissionRationale: bg.PermissionRationale(
          title: "Allow {applicationName} to access this device's location.",
          message:
              "This app collects location data to enable recording your visit to shop.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        ),
        authorization: bg.Authorization(
          strategy: bg.Authorization.STRATEGY_JWT,
          accessToken: token,
          refreshToken: refreshToken,
          refreshUrl: "${appConfig.serverConfig.baseUrl}/api/refresh_token",
          refreshPayload: {'refresh_token': '{refreshToken}'},
        ),
        params: {
          AppKeys.mobileNumber: mobileNumber,
          AppKeys.trackingRequest: auth.user.profile.email,
          AppKeys.source: kAppSource,
        },
        showsBackgroundLocationIndicator: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
      )
```

## Expected Behavior
I am expecting all the coords with accuracy near to 0 or less than 100

## Actual Behavior
sometime I'm getting coords with accuracy 0, sometime with accuracy more than 2500. As I have configured desiredAccuracy as bg.Config.DESIRED_ACCURACY_HIGH I am expecting all the coords with accuracy near to 0(minimum accuracy)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in does not *manufacture* location data. Locations are delivered by the native Location API.  There is no guarantee of location accuracy.  It totally depends on the device and the environment.

**Comment by christocracy** [comment]
GPS only works outdoors.  Indoors, the best accuracy you’ll see is 40-60 meters if the location came from a wifi access point.

if location comes from cell tower, location accuracy will be > 1000 meters.

**Comment by christocracy** [comment]
> What could be the reason of sudden increase in accuracy?

Tall buildings, mountains, lakes, forests, tunnels, bridges, etc.  The environment.

**Comment by sohamD07** [comment]
Is there any way to handle this data before posting it to configured URL? I mean, can I only upload coords with accuracy < 100 to URL?

**Comment by christocracy** [comment]
Why don’t simply have your server filter them out?
