### ISSUE TITLE
USE_EXACT_ALARM

### ISSUE THREAD

**Issue by JeanPOAlves** [transistorsoft/flutter_background_geolocation#1270]
Olá a todos,  Recentemente, ao tentar fazer upload do meu aplicativo para o Google Play, recebi uma mensagem de rejeição relacionada ao uso da permissão USE_EXACT_ALARM. O Google indicou que o aplicativo não está em conformidade com o uso autorizado dessa permissão, especificamente porque não está diretamente relacionado ao objetivo principal do aplicativo.  Gostaria de saber se alguém passou por uma situação semelhante e se há alguma orientação ou sugestão sobre como usar corretamente essa permissão de acordo com as diretrizes do Google Play.  Agradeço antecipadamente por qualquer ajuda ou insights que você possa fornecer!  Atenciosamente,
JEAN

**Comment by christocracy** [comment]
This issue template is **NOT** *optional*, it’s **required**.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by JeanPOAlves** [comment]
But it's not a code or model problem, it's an integration problem with your plugin.

**Comment by christocracy** [comment]
> But it's not a code or model problem,

Yes, it can be.  Provide all information in the issue template.

**Comment by JeanPOAlves** [comment]
Plugin version: 

- flutter_background_geolocation 4.15.1 
- background_fetch: ^1.3.2

Platform: iOS or Android

- ANDROID ( According to the question I asked, it is Google, therefore Android. )

OS version / Device manufacturer / model

- It's not a mistake.

Flutter info (flutter doctor):

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

Plugin config:



android manifest
    <uses-permission android:name="android.permission.USE_EXACT_ALARM" android:minSdkVersion="34"/>

**Comment by christocracy** [comment]
Post your `AndroidManifest.xml`

**Comment by JeanPOAlves** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"

    xmlns:tools="http://schemas.android.com/tools"

    package=“xxx”>


    

    <uses-permission
android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <uses-permission android:name="android.permission.INTERNET"/>

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
/>

    <uses-permission android:name="android.permission.RECORD_AUDIO"/>

    <uses-permission android:name="android.permission.USE_EXACT_ALARM"
android:minSdkVersion="34"/>



    <queries>

        <intent>

            <action android:name="android.speech.RecognitionService" />

        </intent>

    </queries>



    <application

        android:name=".Application"

        android:label=“xxx”

        ***@***.***/ic_launcher"

        android:usesCleartextTraffic="true"

        android:requestLegacyExternalStorage="true"

        tools:replace="android:label">

        <activity

            android:name=".MainActivity"

            android:launchMode="singleTop"

            ***@***.***/LaunchTheme"


android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"

            android:hardwareAccelerated="true"

            android:installLocation="preferExternal"

            android:windowSoftInputMode="adjustResize"

            android:exported="true"

            >

            

            <meta-data


android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"

                android:value="true" />

            <intent-filter>

                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>

            </intent-filter>

        </activity>


        <service
android:name="com.transistorsoft.locationmanager.service.TrackingService"
android:foregroundServiceType="location" />


        <meta-data
android:name="com.transistorsoft.locationmanager.license"
android:value=“xxx” />

        


        <meta-data
android:name="com.transistorsoft.locationmanager.ENCRYPTION_PASSWORD"
android:value="transistorsoft" />


        <meta-data

            android:name="flutterEmbedding"

            android:value="2" />


        <provider

            android:name="androidx.core.content.FileProvider"

            android:authorities="${applicationId}.provider"

            android:exported="false"

            android:grantUriPermissions="true">

            <meta-data

                android:name="android.support.FILE_PROVIDER_PATHS"

                ***@***.***/provider_paths"/>

        </provider>


    </application>

</manifest>




Em qua., 3 de abr. de 2024 às 18:57, Chris Scott ***@***.***>
escreveu:

**Comment by JeanPOAlves** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package=“xxx”>

    
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.USE_EXACT_ALARM" android:minSdkVersion="34"/>


    <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>
    
    <application
        android:name=".Application"
        android:label=“xxx”
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:requestLegacyExternalStorage="true"
        tools:replace="android:label">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:installLocation="preferExternal"     
            android:windowSoftInputMode="adjustResize"
            android:exported="true"
            >
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />

        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value=“xxx” />
        

        <meta-data android:name="com.transistorsoft.locationmanager.ENCRYPTION_PASSWORD" android:value="transistorsoft" />

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

    </application>
</manifest>

**Comment by christocracy** [comment]
>   `<uses-permission android:name="android.permission.USE_EXACT_ALARM" android:minSdkVersion="34"/>`

You are in-control of your own `AndroidManifest`.  If Play Store is complaining about this permission, and you don't feel like justifying it the *Play Store*, it's up to you to remove that permission.  The plugin does not require that permission.

**Comment by JeanPOAlves** [comment]
It's in the plugin documentation so I added it,

Em qua., 3 de abr. de 2024 às 19:02, Chris Scott ***@***.***>
escreveu:

**Comment by JeanPOAlves** [comment]
<img width="934" alt="Captura de Tela 2024-04-03 às 19 03 35" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/83961872/5ef0ee5e-afd7-458e-bde8-bbcf91b47081">


It's in the plugin documentation so I added it,

**Comment by christocracy** [comment]
And there's a number of warnings about it too.

<img width="1087" alt="Screenshot 2024-04-03 at 6 05 38 PM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/f7d99f6c-8c58-4403-bb71-ffea95e89aab">
