### ISSUE TITLE
An issue with 13 os version

### ISSUE THREAD

**Issue by PoriyaBytez** [transistorsoft/flutter_background_geolocation#1273]
## Your Environment
* Plugin version:flutter_background_geolocation: ^4.15.1
* Platform:  Android
* OS version: 13
* Device manufacturer/model: CPH2223
* Flutter info (`flutter doctor`): 
* Plugin config:

An issue with 13 os version my app does not call continuously  update lat long

**Comment by christocracy** [comment]
And you didn’t show any Config or code.  You don’t think your Config might be relevant?

**Comment by PoriyaBytez** [comment]
Plugin version:flutter_background_geolocation: ^4.15.1
Platform: Android
OS version: 13
Device manufacturer/model: CPH2223
Flutter info (flutter doctor):
Plugin config:

/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');
  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      bg.State state = await bg.BackgroundGeolocation.state;
      if (state.stopOnTerminate!) {
        return;
      }
      Helper.timer = Timer.periodic(const Duration(seconds: 10), (timer) async {
        try {
          await bg.BackgroundGeolocation.getCurrentPosition(
            samples: 2,
            extras: {
              "event": "background-fetch",
              "headless": true,
            },
          );
          print("[foreground  location is live]main file");
          Utils.userstatus == "offline" ? '' : startApiCall();
        } catch (error) {
          print('API Call Error: $error');
        }
      });
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1, extras: {"event": "terminate", "headless": true});
        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }

      break;
    case bg.Event.HEARTBEAT:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 2,
                timeout: 10,
                extras: {"event": "heartbeat", "headless": true});

        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      break;
  }
}

**Comment by PoriyaBytez** [comment]
here my code

**Comment by christocracy** [comment]
That is merely your HeadlessTask, an optional (not required) callback function.
