### ISSUE TITLE
Notify dismiss immediately after enter in geofence.

### ISSUE THREAD

**Issue by PierreBizzottoSTEB** [transistorsoft/flutter_background_geolocation#1274]
## Your Environment
* Plugin version:^4.14.0
* Platform: Android
* OS version:13
* Device manufacturer / model: Redmi note 11S
* Flutter info (`flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (1 available)
    ! Error: Browsing on the local area network for iPhone di Aiman. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 
 bg.BackgroundGeolocation.addGeofence(
            bg.Geofence(
              identifier: shop.id.toString(),
              latitude: shop.latitude,
              longitude: shop.longitude,
              radius: 200,
              notifyOnEntry: true,
              notifyOnExit: false,
            ),
          );


bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      debug: false,

      //logLevel: Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,

      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
              'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      //heartbeatInterval: 10,
    )).then((bg.State state) {
      bg.BackgroundGeolocation.start();
    });
```

## Expected Behavior

Present Notification when enter in geofence and don't remove it
## Actual Behavior

Dismiss immediately Notification when enter in geofence.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What notification are you talking about?

**Comment by PierreBizzottoSTEB** [comment]
When my device enter in a geofence I send a firebase notification a show them with awesome_notificatios. The notification arrive correctly, showed but immediately closed. I'm try on android and I use Lockito to simulate movement.

**Comment by christocracy** [comment]
> send a firebase notification

I don’t see how the plug-in could be involved with that.

**Comment by PierreBizzottoSTEB** [comment]
Hi Chris,

thanks for your replay. 

 

But I don’t understand if I stop the simulator of movement and I try to send firebase notify with a button it’s ok. But if I send notify onGeofence event the notify dismiss immediately.

 

Have you some cases where you send notify ongeofence?

 

Thanks

Pierre

 

 

Da: Chris Scott ***@***.***> 
Inviato: giovedì 11 aprile 2024 09:52
A: transistorsoft/flutter_background_geolocation ***@***.***>
Cc: PierreBizzottoSTEB ***@***.***>; Author ***@***.***>
Oggetto: Re: [transistorsoft/flutter_background_geolocation] Notify dismiss immediately after enter in geofence. (Issue #1274)

 

send a firebase notification

I don’t see how the plug-in could be involved with that.

**Comment by christocracy** [comment]
It sounds like you’re not creating your own  NotificationChannel for your notifications, and re-using the plug-in’s channel.

**Comment by PierreBizzottoSTEB** [comment]
Good morning Chris,

sorry to bother you, everything seems to be implemented correctly. 

 

But with the application closed it seems that every access to the geofence the task is queued in the background, but is then executed only when the app is reopened with the consequent sending of notifications, which I would like to be sent at the same time as accessing the geofence. What’s wrong?

 

Thanks in advance.

Pierre

 

Da: Chris Scott ***@***.***> 
Inviato: giovedì 11 aprile 2024 14:24
A: transistorsoft/flutter_background_geolocation ***@***.***>
Cc: PierreBizzottoSTEB ***@***.***>; Author ***@***.***>
Oggetto: Re: [transistorsoft/flutter_background_geolocation] Notify dismiss immediately after enter in geofence. (Issue #1274)

 

It sounds like you’re not creating your own NotificationChannel for your notifications, and re-using the plug-in’s channel.

**Comment by christocracy** [comment]
> But with the application closed

If by “closed” you mean “terminated”, see api docs Config.enableHeadless

**Comment by PierreBizzottoSTEB** [comment]
Hi Chris, 

 

Yes, for me closed (Italian: chiusa) mean terminated.

Ok, so I need to implement notification inside headlessTask?

For case bg.Event.GEOFENCE?

 

Thanks

 

 

 

Da: Chris Scott ***@***.***> 
Inviato: mercoledì 15 maggio 2024 17:53
A: transistorsoft/flutter_background_geolocation ***@***.***>
Cc: PierreBizzottoSTEB ***@***.***>; Author ***@***.***>
Oggetto: Re: [transistorsoft/flutter_background_geolocation] Notify dismiss immediately after enter in geofence. (Issue #1274)

 

But with the application closed

If by “closed” you mean “terminated”, see api docs Config.enableHeadless
