### ISSUE TITLE
Subject: Question about support for Crash Detection and/or any pointers

### ISSUE THREAD

**Issue by anand-github-008** [transistorsoft/flutter_background_geolocation#1275]
Apologies, for skipping the template. 

I wanted to express my appreciation for the incredible work you've done on the flutter_background_geolocation package. It has been an invaluable tool for my project.

I'm currently exploring ways to enhance the functionality of my application, and one area I'm particularly interested in is crash detection. I've been searching for solutions that integrate seamlessly with the background location tracking provided by your package.

I was wondering if you could provide some guidance or support regarding crash detection within the context of the flutter_background_geolocation package. Specifically, I'm looking for any pointers on how to implement crash detection alongside the background location tracking feature.

I understand if this falls outside the scope of your current commitments, but any assistance or direction you could provide would be greatly appreciated.

**Comment by christocracy** [comment]
Most developers seems to use [Crashalytics](https://firebase.flutter.dev/docs/crashlytics/overview/) from `FlutterFire`.

**Comment by anand-github-008** [comment]
[christocracy](https://github.com/christocracy) Sorry I meant car crash/accident detection

**Comment by christocracy** [comment]
> Sorry I meant car crash/accident detection

No, this plug-in has nothing to do with that and I have no ideas for you.
