### ISSUE TITLE
Plugin skips or not detacting some location while the app is in background or in lock screen mode - Android Real Device

### ISSUE THREAD

**Issue by anyservicein** [transistorsoft/flutter_background_geolocation#1276]
## Your Environment
* Plugin version: **flutter_background_geolocation: ^4.15.1**
* Platform: **Android**
* OS version: **10**
* Device manufacturer / model: **MI A2**
* Flutter info (`flutter doctor`): 

> **Flutter doctor : 
> [√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
>     • Flutter version 3.19.5 on channel stable at D:\Android\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
>     • Engine revision e76c956498
>     • Dart version 3.3.3
>     • DevTools version 2.31.1
>     • Pub download mirror https://pub.flutter-io.cn**

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

**//Initial configuration of plugin**

 bg.BackgroundGeolocation.ready(bg.Config(
      locationAuthorizationRequest:
          "Always",
      disableLocationAuthorizationAlert: true,
      reset: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    )).then((bg.State state) async {
      if (kDebugMode) {
        print('[ready] ${state.toMap()}');
        print('[didDeviceReboot] ${state.didDeviceReboot}');
      }

      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }

      isEnabled.value = state.enabled;
      isMoving.value = state.isMoving!;
    }).catchError((error) {
      if (kDebugMode) {
        print('[ready] ERROR: $error');
      }
    });
  }

**//Furthermore to above configuration, as soon service engineer mark as present, we set the below configuration.**

 bg.BackgroundGeolocation.setConfig(bg.Config(
        batchSync: true,
        autoSync: true,
        url:
            "https://anyapidev.any-service.in/api/Entity/EntityLocationHistorySave",
        params: {
          "vendorId": SPHelper.prefs.getInt(Constant().spVendorId),
          "servicePersonId": EntityRelationShipModel.fromJson(jsonDecode(
                  SPHelper.prefs
                      .getString(Constant().spEntityRelationShipModel)
                      .toString()))
              .entityId
        },
        headers: {
          "Authorization": SPHelper.prefs.getString(Constant().spServerToken)
        },
        activityRecognitionInterval: 30000,
        desiredOdometerAccuracy: 10)); 

```
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/154757307/293a0f68-dc28-4f38-a347-9747d0145e41)

## Expected Behavior
The plugin should detect the route based on the red line shown in the image, which represents the actual path I traveled. Please note that I manually drew the red line to provide you with an idea of the route I took using a real device (MI A2).

## Actual Behavior
The plugin fails to record certain portions of the route accurately, skipping multiple latitude/longitude detections that should have been recorded also the odometer dose not increased in some cases.

## Steps to Reproduce

1.
2.
3.
4.

## Context
Our application record the service engineer travelled through the day and we were trying to detact the realtime location along with the kilometer traveled.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Your images don’t communicate *which direction* you moved.

**Comment by anyservicein** [comment]
That doesn't matter, the importance is that it doesn't track the way it should

**Comment by anyservicein** [comment]
"I've indicated my driving route with the red line, drawn manually using MS Paint. This was done to provide a visual representation of my route, with the image edited for clarity and better understanding.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/154757307/34e1e924-44d2-47ef-a891-ed8e74ad7f78)

**Comment by christocracy** [comment]
See wiki “Debugging”.  Learn how to fetch logs from the plug-in using .emailLog.

also see https://dontkillmyapp.com

**Comment by anyservicein** [comment]
Hi,

Yesterday I travel through 586 KM approx. according to the google and as per your instruction we generated the .emailLog and we found that approx. 8.30 hrs location data missing.

Here below is the attached log for your reference.

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/14974836/background-geolocation.log)

Please guide 

Best Regards,

**Comment by christocracy** [comment]
What particular timestamps in your logs are you interested in?

**Comment by jayamsoft** [comment]
Hi,

Below is the list of records highlited in yellow that require review to identify the root cause of skipped latitude/longitude entries.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/166372705/01b0ead1-ae61-4cab-a88e-f61aded6d3be)

I've attached the file with a filter applied to column H, which filters the data for recorded time differences above 1 minute, which is the area of concern.

Regards,

**Comment by christocracy** [comment]
Here is the logs from your first record `16ff3a31-ced6-4029-8f4e-d30887c3d10d
`.  What would you like to know about it?

```
04-14 09:14:54.280 DEBUG [TrackingService c] 
╔═════════════════════════════════════════════
║ TrackingService: LocationResult
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 20.754721,73.052974 hAcc=15 et=+10d13h34m19s342ms alt=-18.100000381469727 vel=0.6718502 bear=118.8761 vAcc=3 sAcc=2 bAcc=89 {Bundle[mParcelledData.dataSize=600]}]
╟─ Age: 50ms, time: 1713066294230

04-14 09:14:54.281 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

04-14 09:14:54.281 DEBUG [TSLocationManager a] Median accuracy: 9.648
04-14 09:14:54.282 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: MOTION_ACTIVITY_CHECK in 156006ms (jobID: -18513055)
04-14 09:14:54.285 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [TrackingService startId: 1870, eventCount: 0, sticky: true]
04-14 09:14:54.290 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 16ff3a31-ced6-4029-8f4e-d30887c3d10d
04-14 09:14:54.321 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

04-14 09:14:54.378 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 1511
04-14 09:14:54.409 DEBUG [SQLiteLocationDAO allWithLocking] 
  ✅  Locked 1 records
04-14 09:14:54.410 INFO [HttpService a] 
  🔵  HTTP POST batch (1)
04-14 09:14:54.767 INFO [HttpService$f onResponse] 
  🔵  Response: 200
04-14 09:14:54.771 DEBUG [SQLiteLocationDAO destroyAll] 
  ✅  DELETED: (1)
04-14 09:14:54.798 DEBUG [SQLiteLocationDAO allWithLocking] 
```

**Comment by anyservicein** [comment]
Okay lets discuss to the point, Please ignore that id you mentioned and lets discussion on id - `f409ca29-c220-423b-a36f-1635ebe71827` and `53681229-efba-40ca-bf65-f903bce7f320`.

I was In-Vehicle and it shows still in log for all the entries between above mention two ids and even the same entry happed in database also.

**Comment by anyservicein** [comment]
Excellent find! I've checked with a few more IDs and noticed the same issue. I'm optimistic that setting `stopOnTerminate: false` will resolve this.

Furthermore, how about `e45c0e2d-e9a9-45cb-8cd0-ec04d6312436` and `12d04d1e-e85a-42e5-92a9-66794e33222b`

**Comment by christocracy** [comment]
What about it?  The user disable *Settings->Location* on that device (disabling Location-Services for every app on that device).  See `║ Location-provider change: false`:

```
04-14 22:06:02.095 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: e45c0e2d-e9a9-45cb-8cd0-ec04d6312436
.
.
.
04-14 22:07:39.061 INFO [TSProviderManager a] 
╔═════════════════════════════════════════════
║ Location-provider change: false
╠═════════════════════════════════════════════
╟─ GPS: false
╟─ Network: false
╟─ AP Mode: false
.
.
.
04-14 22:07:39.086 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ providerchange LocationResult: 4 (0ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 20.472069,72.927111 hAcc=20 et=+11d2h27m4s198ms alt=-19.700000762939453 vAcc=1 sAcc=2 bAcc=45 {Bundle[{}]}], time: 1713112659086
.
.
.
04-14 22:07:39.089 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired providerchange position
04-14 22:07:39.090 DEBUG [TSLocationManager a] Median accuracy: 17.452
04-14 22:07:39.101 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 12d04d1e-e85a-42e5-92a9-66794e33222b
```

**Comment by anyservicein** [comment]
Hi,

I've discussed the property `stopOnTerminate: true` with my development team. However, upon reviewing our configuration setup, it's evident that `stopOnTerminate: false` was already configured. This was also mentioned when raising the query.

**I am a bit confused as to why it's showing as true in the log despite being set as false in the configuration.**

**Comment by anyservicein** [comment]
I haven't disabled the location throughout my travel, so I'm curious about the reason it's still showing the same.

Here is the attached my travell log for today which is around 5km and it shows `Location-provider change: false` approx 9 time when i was in-vehicle or walking or still

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/15010126/background-geolocation.log)

**Comment by anyservicein** [comment]
Thank you for the updates. I'll reach out if I have any further questions or need clarification.

**Comment by anyservicein** [comment]
Hi,

In my observation today, the tracking abruptly stopped with the following log. Could you please provide guidance on its meaning?

`╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

04-18 08:21:12.029 DEBUG [LocationAuthorization withBackgroundPermission] 
  ℹ️  LocationAuthorization: Permission granted
04-18 08:21:12.034 DEBUG [TSLocationManager a] 
  ℹ️  Clear last odometer location
04-18 08:21:12.036 INFO [TSGeofenceManager start] 
  🎾  Start monitoring geofences
04-18 08:21:12.036 DEBUG [TSGeofenceManager stopMonitoringStationaryRegion] 
  🔴  Stop monitoring stationary region
04-18 08:21:12.039 INFO [ActivityRecognitionService stop] 
  🔴  Stop motion-activity updates
04-18 08:21:12.039 DEBUG [HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
04-18 08:21:12.039 DEBUG [TSGeofenceManager c] 
  🔴  Stop monitoring geofences
04-18 08:21:12.041 INFO [HeartbeatService stop] 
  🔴  Stop heartbeat
04-18 08:21:12.041 DEBUG [DeviceSettings startMonitoringPowerSaveChanges] 
  🎾  Start monitoring powersave changes
04-18 08:21:12.044 DEBUG [HttpService stopMonitoringConnectivityChanges] 
  🔴  Stop monitoring connectivity changes
04-18 08:21:12.045 DEBUG [DeviceSettings stopMonitoringPowerSaveChanges] 
  🔴  Stop monitoring powersave changes
04-18 08:21:12.045 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

04-18 08:21:12.063 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
04-18 08:21:12.066 INFO [HeartbeatService stop] 
  🔴  Stop heartbeat
04-18 08:21:12.068 INFO [TrackingService changePace] 
  🔵  setPace: false → false
04-18 08:21:12.086 ERROR [DeviceSettings stopMonitoringPowerSaveChanges] 
  ‼️  Receiver not registered: com.transistorsoft.locationmanager.device.DeviceSettings$a@cc22675
java.lang.IllegalArgumentException: Receiver not registered: com.transistorsoft.locationmanager.device.DeviceSettings$a@cc22675
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1429)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1543)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at com.transistorsoft.locationmanager.device.DeviceSettings.stopMonitoringPowerSaveChanges(Unknown Source:17)
	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:110)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(SourceFile:4)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.q(SourceFile:1)
	at com.transistorsoft.locationmanager.adapter.b.run(SourceFile:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

04-18 08:21:12.092 INFO [TSLocationManager setOdometer] 
  ℹ️  setOdometer: 9563.953, isMoving: false
04-18 08:21:12.092 DEBUG [TSConfig e] ℹ️   Persist config, dirty: [headers, params]
04-18 08:21:12.092 DEBUG [TSLocationManager a] 
  ℹ️  Clear last odometer location
04-18 08:21:12.095 INFO [TSLocationManager a] 
`

**Comment by christocracy** [comment]
You are doing something unusual with your code.

post **All** code where you’re interacting with the  plug-in `BackgroundGeolocation`

**Comment by anyservicein** [comment]
Hi,

Below is the code we've implemented to retrieve real-time location data for field engineers. We've addressed two scenarios:

> Start service

1. When the company needs to determine the current check-in/check-out location of field engineers, we set the variable `currentLocationTrackingOnly & realTimeTracking` value to `true & false` respectively.
2.  When the company needs to determine the realtime location of field engineers, we set the variable `currentLocationTrackingOnly & realTimeTracking` value to `false & true` respectively;

> Forther more we start and stop the services in following instances
1. When `currentLocationTrackingOnly` is set to true, we call the `bgStartService` and `bgStopService` functions based on the application lifecycle, as declared below.
2. When `realTimeTracking` location is set to true and as soon as the user logs in to the app, we initiate the `bgStartService` function to start tracking. Similarly, upon user logout, we trigger the `bgStopService` function to halt the tracking process.

Here below is the code for the same.

`
class VendorLocationController extends BaseController {
  RxBool isMoving = false.obs;
  RxBool isEnabled = false.obs;
  RxString motionActivity = "UNKNOWN".obs;
  RxString odometer = "0".obs;
  RxString content = "".obs;
  RxBool isLoadingForLocation = false.obs;
  JsonEncoder encoder = const JsonEncoder.withIndent("     ");

  Future locationInitialState() async {

    // 1.  Listen to events (See docs for all 12 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.onHttp(_onHttp);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
      locationAuthorizationRequest:
          Constant.vendorModel!.currentLocationTrackingOnly == true &&
                  Constant.vendorModel!.realTimeTracking == true
              ? "Always"
              : 'WhenInUse',
      disableLocationAuthorizationAlert: true,
      reset: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    )).then((bg.State state) async {
     
      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }

      isEnabled.value = state.enabled;
      isMoving.value = state.isMoving!;
     
    }).catchError((error) {
      if (kDebugMode) {
        print('[ready] ERROR: $error');
      }
    });
}

  void bgStartService() {
  
    bg.BackgroundGeolocation.start().then((bg.State state) {
      if (Constant.vendorModel!.currentLocationTrackingOnly == true) {
       
        bg.BackgroundGeolocation.setOdometer(0);
        bg.BackgroundGeolocation.setConfig(bg.Config(
          url: "",
          stopOnTerminate: true,
          startOnBoot: false,
          locationAuthorizationRequest: 'WhenInUse',
          disableLocationAuthorizationAlert: true,
        ));
      } 

    if (Constant.vendorModel!.realTimeTracking == true) {
            bg.BackgroundGeolocation.setConfig(
			  bg.Config(
				
				batchSync: true,
				autoSync: true,
			   
				stopOnTerminate: false,
				startOnBoot: true,
				url:
					"https://anyapidev.any-service.in/api/Entity/EntityLocationHistorySave",
				params: {
				  "vendorId": SPHelper.prefs.getInt(Constant().spVendorId),
				  "servicePersonId": EntityRelationShipModel.fromJson(jsonDecode(
						  SPHelper.prefs
							  .getString(Constant().spEntityRelationShipModel)
							  .toString()))
					  .entityId
				},
				headers: {
				  "Authorization": SPHelper.prefs.getString(Constant().spServerToken)
				},
			  
			  ),
			);
      } else {
        if (kDebugMode) {
          print("----------->Service Started UNKNOWN");
        }
      }

      isEnabled.value = state.enabled;
      isMoving.value = state.isMoving!;

    ).catchError((error) {
        bgStartService();
    });
  }

  void bgStopService() {
    bg.BackgroundGeolocation.stop().then((bg.State state) {
     
      isEnabled.value = state.enabled;
      isMoving.value = state.isMoving!;
      Constant.latitude = 0.0;
      Constant.longitude = 0.0;
     
    });
  }

  Future<void> _onLocation(bg.Location location) async {
   

    String odometerKM = "0";
    Constant.vendorModel!.currentLocationTrackingOnly =
        SPHelper.prefs.getBool(Constant().spcurrentLocationTrackingOnly);
    Constant.vendorModel!.realTimeTracking =
        SPHelper.prefs.getBool(Constant().sprealTimeTracking);
    Constant.entityRelationShipModel = EntityRelationShipModel.fromJson(
        jsonDecode(SPHelper.prefs
            .getString(Constant().spEntityRelationShipModel)
            .toString()));

    if (Constant.vendorModel!.currentLocationTrackingOnly == true &&
        Constant.vendorModel!.realTimeTracking == true &&
        Constant.entityRelationShipModel!.appUserRole !=
            EnumAppUserRole.OWNER_1_ADMIN.name) {
     
      odometerKM = location.odometer.toStringAsFixed(2);
      
      motionActivity.value = location.activity.type;
	  
    } else {
      odometerKM = "0";
      await bg.BackgroundGeolocation.destroyLocations();
    }


    Constant.latitude = location.coords.latitude;
    Constant.longitude = location.coords.longitude;
    Constant.locationUuid = location.uuid;

    content.value = encoder.convert(location.toMap());
    odometer.value = odometerKM;

  }

  void _onLocationError(bg.LocationError error) {
    if (kDebugMode) {
      print('[location] ERROR - $error');
    }
  }

  void _onMotionChange(bg.Location location) {
    if (kDebugMode) {
      print('[motionchange] - $location');
    }
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    if (kDebugMode) {
      print('[activitychange] - $event');
    }
    motionActivity.value = event.activity;
  }

  void _onHttp(bg.HttpEvent event) async {
    if (kDebugMode) {
      print('URL Event------->');
      print('------------->[${bg.Event.HTTP}] - $event');
    }
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    if (kDebugMode) {
      print('$event');
    }
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    if (kDebugMode) {
      print('$event');
    }
  }

}
`

**Comment by christocracy** [comment]
Why have you unthinkingly copy-pasted code from the /example app?

>reset: false,

Do you know what that does?

```
if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
```
If you're not using a `Config.schedule`, you **DON'T NEED THIS**.

Your logs above show you are calling both `.stop()` and `.start()` **simultaneously**.  You code above shows no reference to calling `bgStopService()` so this is not **ALL** your code.

I think you've been blindly copy/pasting code from the `/example` app without thinking about what it actually does.

**Comment by christocracy** [comment]
I suggest you add some logging to your `bgStartService` and `bgStopService` methods and observe how/when those are being called.  

I think your developers will find those are being executed in unusual and unexpected ways.

**Comment by anyservicein** [comment]
Hi,

I've reviewed the logs and identified the following errors. Can you provide clarification on their meaning and resolution?

╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

04-29 09:48:52.514 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: MOTION_ACTIVITY_CHECK in 64275ms (jobID: -18513055)
04-29 09:48:52.519 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [TrackingService startId: 271, eventCount: 0, sticky: true]
04-29 09:48:52.520 DEBUG [HeadlessTask onHeadlessEvent] 💀 [HeadlessTask location]
04-29 09:48:52.521 ERROR [HeadlessTask$TaskRunner run] 
  ‼️  Invalid Headless Callback ids.  Cannot handle headless event
04-29 09:48:52.560 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 223
04-29 09:48:52.564 DEBUG [SQLiteLocationDAO allWithLocking] 
  ✅  Locked 1 records
04-29 09:48:52.564 INFO [HttpService a] 
  🔵  HTTP POST batch (1)
04-29 09:48:52.970 INFO [HttpService$f onResponse] 
  🔵  Response: 200
04-29 09:48:52.970 DEBUG [HeadlessTask onHeadlessEvent] 💀 [HeadlessTask http]
04-29 09:48:52.971 DEBUG [SQLiteLocationDAO destroyAll] 
  ✅  DELETED: (1)
04-29 09:48:52.971 ERROR [HeadlessTask$TaskRunner run] 
  ‼️  Invalid Headless Callback ids.  Cannot handle headless event
04-29 09:48:52.976 DEBUG [SQLiteLocationDAO allWithLocking] 
  ✅  Locked 0 records
04-29 09:48:52.977 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 223
04-29 09:50:09.670 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: MOTION_ACTIVITY_CHECK
╠═════════════════════════════════════════════

04-29 09:50:09.674 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
04-29 09:50:12.430 ERROR [AbstractService c] 
  ‼️  Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
java.lang.SecurityException: Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:862)
	at com.transistorsoft.locationmanager.service.a.a(SourceFile:1)
	at com.transistorsoft.locationmanager.service.AbstractService.c(SourceFile:1)
	at com.transistorsoft.locationmanager.service.AbstractService.a(SourceFile:8)
	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.onCreate(Unknown Source:16)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2729)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2440)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1785)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15850)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11873)


04-29 09:50:12.435 DEBUG [AbstractService a] 
  🎾  start [ActivityRecognitionService  startId: 1, eventCount: 1]
04-29 09:50:12.436 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService stopped
04-29 09:50:12.436 DEBUG [ActivityRecognitionService a] 
  🚘 ️DetectedActivity [type=STILL, confidence=100]
04-29 09:50:12.441 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [ActivityRecognitionService startId: 1, eventCount: 0, sticky: false]
04-29 09:50:12.487 ERROR [AbstractService c] 
  ‼️  Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
java.lang.SecurityException: Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:862)
	at com.transistorsoft.locationmanager.service.a.a(SourceFile:1)
	at com.transistorsoft.locationmanager.service.AbstractService.c(SourceFile:1)
	at com.transistorsoft.locationmanager.service.AbstractService.a(SourceFile:8)
	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.onCreate(Unknown Source:16)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

04-29 09:50:12.494 DEBUG [AbstractService a] 
  🎾  start [ActivityRecognitionService  startId: 1, eventCount: 1]
04-29 09:50:12.496 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService stopped
04-29 09:50:12.497 DEBUG [ActivityRecognitionService a] *** wasMoving: true, nowMoving: true, startedMoving: false, justStopped; false
04-29 09:50:12.498 DEBUG [HeadlessTask onHeadlessEvent] 💀 [HeadlessTask activitychange]
04-29 09:50:12.499 ERROR [HeadlessTask$TaskRunner run] 
  ‼️  Invalid Headless Callback ids.  Cannot handle headless event
`

**Comment by christocracy** [comment]
You failed to properly implement your HeadlessTask, **exactly as documented and directed**.

**Comment by anyservicein** [comment]
And how about below error...

04-29 09:50:09.674 INFO [ActivityRecognitionService start]
🎾 Start motion-activity updates
04-29 09:50:12.430 ERROR [AbstractService c]
‼️ Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS]
java.lang.SecurityException: Starting FGS with type health callerApp=ProcessRecord{213061b 30833:net.jayamsoft.any/u0a304} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS]

**Comment by christocracy** [comment]
You decided to remove the permission `FOREGROUND_SERVICE_HEALTH` from your AndroidManifest instead of clarifying to the Play Store why that permission is required.

See api docs Config.disableMotionActivityUpdates

**Comment by anyservicein** [comment]
Thank you @christocracy, as you suggest i provided the clarification as per the need and finally, the application got approved by Play Store Team.

Thank you!
