### ISSUE TITLE
Problem to stop service and kill completely app when I close it

### ISSUE THREAD

**Issue by felipehbomfim** [transistorsoft/flutter_background_geolocation#1277]
## Your Environment
* Plugin version: 4.13.4
* Platform: Android
* OS version: 14
* Device manufacturer / model: Samsung / A54
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      checkProximityToGeofence(location);
      onData(location);
    });
    bg.BackgroundGeolocation.onGeofence(_onGeofence);

    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        locationUpdateInterval: 3000,
        stopOnTerminate: true,
        startOnBoot: false,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_OFF
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
        _startCountdownTimer();
      }
    });
```

## Expected Behavior
I want the app to stop running completly, but sometimes it looks like it keeps running in the background, even if i remove it from the background

## Actual Behavior
it seems that sometimes the app never stops running, even when i'm connected to android studio and i remove the app from the background it keeps running.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

When doesn't work:
<img width="2004" alt="Captura de Tela 2024-04-18 às 15 47 20" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/59843321/2182e83a-1b83-4041-9b3e-fc6aaff226bf">
<img width="1947" alt="Captura de Tela 2024-04-18 às 15 45 15" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/59843321/945d8800-fa7e-4648-aa00-d159ad8a6925">

When work like I want: 

<img width="1985" alt="Captura de Tela 2024-04-18 às 15 46 26" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/59843321/bc2dd676-6c67-47a8-9806-79e0359b5cba">
<img width="1960" alt="Captura de Tela 2024-04-18 às 15 43 52" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/59843321/1a25d905-ddb7-48ba-aa5a-d4b6a88afe7d">

**Comment by christocracy** [comment]
The only thing I’m in-control of and concerned  about is *does the plug-in stop tracking location and halt any running foreground-services after terminate* (witnessed by the persistent notification disappearing).

**Comment by felipebomfimdev** [comment]
This actually happens. But in another part of the application, I'm using some Bluetooth things and when I close the application the connection should be finished and this only happens when it finishes according to the last screenshots. I can't close the bluetooth connection because I don't know when it will close the app or not. I commented out the library location call and it works accordingly, as I want.

The question is: do you have any idea why sometimes it closes completely according to the last prints and sometimes it doesn't or how could I solve this??

**Comment by felipehbomfim** [comment]
This actually happens. But in another part of the application, I'm using some Bluetooth things and when I close the application the connection should be finished and this only happens when it finishes according to the last screenshots. I can't close the bluetooth connection because I don't know when it will close the app or not. I commented out the library location call and it works accordingly, as I want.

The question is: do you have any idea why sometimes it closes completely according to the last prints and sometimes it doesn't or how could I solve this??

**Comment by christocracy** [comment]
> do you have any idea why sometimes it closes completely according to the last prints and sometimes it doesn't or how could I solve this??

I don’t have a clue.

**Comment by felipehbomfim** [comment]
Is there any method in the library that I can know when the application closes?

**Comment by christocracy** [comment]
I suggest you seek assistance at the Flutter api docs:  https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html
