### ISSUE TITLE
version 13 issue

### ISSUE THREAD

**Issue by PoriyaBytez** [transistorsoft/flutter_background_geolocation#1278]
## Your Environment
* Plugin version:flutter_background_geolocation: ^4.15.1
* Platform:  Android
* OS version: 13
* Device manufacturer / model  : Oppo/CPH2223
* Flutter info (`flutter doctor`):
* [!] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4291], locale en-IN)
    • Flutter version 3.19.0 on channel stable at E:\flutter_sdk\flutter_windows_3.19.0-stable
    ! Warning: `flutter` on your path resolves to E:\flutter_sdk\flutter_windows_2.0.1-stable\bin\flutter, which is not inside your current Flutter SDK checkout at E:\flutter_sdk\flutter_windows_3.19.0-stable. Consider adding E:\flutter_sdk\flutter_windows_3.19.0-stable\bin to the front of your path.
    ! Warning: `dart` on your path resolves to E:\flutter_sdk\flutter_windows_2.0.1-stable\bin\dart, which is not inside your current Flutter SDK checkout at E:\flutter_sdk\flutter_windows_3.19.0-stable. Consider adding E:\flutter_sdk\flutter_windows_3.19.0-stable\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (9 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Addmin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34301.259
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (4 available)
    • Redmi Note 9 Pro (mobile) • 63752d26 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)         • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 123.0.6312.123
    • Edge (web)                • edge     • web-javascript • Microsoft Edge 123.0.2420.97

[√] Network resources
    • All expected network resources are available.
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
 bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        debug: true,
        foregroundService: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
              "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        ),
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
      ),
    ).then((bg.State state) {
      print("[ready] ${state.toMap()}");
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
      _onClickChangePace();
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

  /// Register BackgroundGeolocation headless-task.
  bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);

/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');
  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      bg.State state = await bg.BackgroundGeolocation.state;
      if (state.stopOnTerminate!) {
        return;
      }
      Helper.timer = Timer.periodic(const Duration(seconds: 10), (timer) async {
        try {
          await bg.BackgroundGeolocation.getCurrentPosition(
            samples: 2,
            extras: {
              "event": "background-fetch",
              "headless": true,
            },
          );
          print("[foreground  location is live]main file");
      

          Utils.userstatus == "offline" ? '' : startApiCall();
        } catch (error) {
          print('API Call Error: $error');
        }
      });
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1, extras: {"event": "terminate", "headless": true});
        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }

      break;
    case bg.Event.HEARTBEAT:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 2,
                timeout: 10,
                extras: {"event": "heartbeat", "headless": true});

        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      break;
  }
}

## Expected Behavior

=> My function need to called  every in every 10 seconds.
=> how to stop debug sound

## Actual Behavior

=>When I set debug true to false my function is not called  proper every 10 seconds it's take 20 seconds or 1 minutes when app is terminated or in background.

=> Second things is debug is true then one alert type sound play countinuesly ,I don't want that thing.How to off that sound.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Helper.timer = Timer.periodic(const Duration(seconds: 10), (timer) async {
try {

This isn’t going to work for you.  Dart Timers are unreliable in the background.

debug Sound FX are controlled by Config.debug.

Config.debug has no effect on performance.

It’s unnecessary to waste energy requesting location every 10s, even while the device is known to be stationary.  Dart timers are not the answer.

read the wiki here “Philosophy of Operation” and learn about the method .changePace and Config.stopTimeout.

**Comment by PoriyaBytez** [comment]
So how can I call the api in every 10 seconds for getting lat long.


╟─ Xiaomi Redmi Note 9 Pro @ 12 (flutter)
                                                                                                    {
                                                                                                      "activityRecognitionInterval": 10000,
                                                                                                      "allowIdenticalLocations": false,
                                                                                                      "authorization": {},
                                                                                                      "autoSync": true,
                                                                                                      "autoSyncThreshold": 0,
                                                                                                      "backgroundPermissionRationale": {
                                                                                                        "title": "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                                                                                                        "message": "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                                                                                                        "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
                                                                                                        "negativeAction": "Cancel"
                                                                                                      },
                                                                                                      "batchSync": false,
                                                                                                      "configUrl": "",
                                                                                                      "debug": true,
                                                                                                      "deferTime": 0,
                                                                                                      "desiredAccuracy": -1,
                                                                                                      "desiredOdometerAccuracy": 100,
                                                                                                      "disableAutoSyncOnCellular": false,
                                                                                                      "disableElasticity": false,
                                                                                                      "disableLocationAuthorizationAlert": false,
                                                                                                      "disableMotionActivityUpdates": false,
                                                                                                      "disableProviderChangeRecord": false,
                                                                                                      "disableStopDetection": false,
                                                                                                      "distanceFilter": 1,
                                                                                                      "elasticityMultiplier": 1,
                                                                                                      "enableHeadless": true,
                                                                                                      "enableTimestampMeta": false,
                                                                                                      "extras": {},
                                                                                                      "fastestLocationUpdateInterval": -1,
                                                                                                      "foregroundService": true,
                                                                                                      "geofenceInitialTriggerEntry": true,
                                                                                                      "geofenceModeHighAccuracy": false,
                                                                                                      "geofenceProximityRadius": 1000,
                                                                                                      "geofenceTemplate": "",
                                                                                                      "headers": {},
                                                                                                      "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
                                                                                                      "heartbeatInterval": -1,
                                                                                                      "httpRootProperty": "location",
                                                                                                      "httpTimeout": 60000,
                                                                                                      "isMoving": false,
                                                                                                      "locationAuthorizationRequest": "Always",
                                                                                                      "locationTemplate": "",
                                                                                                      "locationTimeout": 60,
                                                                                                      "locationUpdateInterval": 1000,
                                                                                                      "locationsOrderDirection": "ASC",
                                                                                                      "logLevel": 5,
                                                                                                      "logMaxDays": 3,
                                                                                                      "maxBatchSize": -1,
                                                                                                      "maxDaysToPersist": 1,
                                                                                                      "maxMonitoredGeofences": 97,
                                                                                                      "maxRecordsToPersist": -1,
                                                                                                      "method": "POST",
                                                                                                      "minimumActivityRecognitionConfidence": 75,
                                                                                                      "motionTriggerDelay": 0,
                                                                                                      "notification": {
                                                                                                        "layout": "",
                                                                                                        "title": "",
                                                                                                        "text": "Location Service activated",
                                                                                                        "color": "",
                                                                                                        "channelName": "TSLocationManager",
                                                                                                        "channelId": "",
                                                                                                        "smallIcon": "",
                                                                                                        "largeIcon": "",
                                                                                                        "priority": -1,
                                                                                                        "sticky": false,
                                                                                                        "strings": {},
                                                                                                        "actions": []
                                                                                                      },
                                                                                                      "params": {},
                                                                                                      "persist": true,
                                                                                                      "persistMode": 2,
                                                                                                      "schedule": [],
                                                                                                      "scheduleUseAlarmManager": false,
                                                                                                      "speedJumpFilter": 300,
                                                                                                      "startOnBoot": true,
                                                                                                      "stationaryRadius": 25,
                                                                                                      "stopAfterElapsedMinutes": 0,
                                                                                                      "stopOnStationary": false,
                                                                                                      "stopOnTerminate": false,
                                                                                                      "stopTimeout": 5,
                                                                                                      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                                                      "url": "",
                                                                                                      "useSignificantChangesOnly": false,
                                                                                                      "enabled": true,
                                                                                                      "schedulerEnabled": false,
                                                                                                      "trackingMode": 1,
                                                                                                      "odometer": 0,
                                                                                                      "isFirstBoot": false,
                                                                                                      "didLaunchInBackground": false,
                                                                                                      "didDeviceReboot": false
                                                                                                    }

**Comment by christocracy** [comment]
Read api docs Config.locationUpdateInterval.

Also read the wiki “Philosophy of Operation”
