### ISSUE TITLE
DeviceSettings.isPowerSaveMode returns the value false when power save mode is enabled 

### ISSUE THREAD

**Issue by ambogatyrev** [transistorsoft/flutter_background_geolocation#1280]
## Your Environment
* Plugin version: 4.11.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Xiaomi Redmi 10s
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.7.11, on macOS 14.4.1 23E224 darwin-arm64, locale ru-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

DeviceSettings.isPowerSaveMode should return true if power save mode is enabled

## Actual Behavior

DeviceSettings.isPowerSaveMode always return false

## Steps to Reproduce

1. Manually enable power save mode
2. Check value of DeviceSettings.isPowerSaveMode 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

![2024-04-24 13 39 19](https://github.com/transistorsoft/flutter_background_geolocation/assets/79789858/e9cf7f3f-78b3-49b8-975d-6baea3291822)

**Comment by christocracy** [comment]
Disconnect your device from USB when calling that function.

**Comment by ambogatyrev** [comment]
> Disconnect your device from USB when calling that function.

I've done that, but there's still no change

**Comment by christocracy** [comment]
![Screenshot_20240425-111212](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/0c9f5a7e-e700-4045-bc56-b294cf36f1a9)

![Screenshot_20240425-111122](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/5e22de24-a621-4b5a-84f1-c7a05d61efa0)

**Comment by christocracy** [comment]
You likely have a threshold configured in your Battery Settings, to only turn on power-saving when the battery goes below a certain level.

if `isPowerSaveMode` reports `false`, then battery-saving is *not* engaged.

**Comment by christocracy** [comment]
Note in my screenshots above that my battery is at `9%`.

**Comment by ambogatyrev** [comment]
I tested on Iphone and Samsung on these devices everything works well, but for some reason it doesn't work on my Xiaomi device. Thank you Chris for your attention!
