### ISSUE TITLE
When application get terminated then the callback function for teminate event is not getting executed. Please help why I am sharing code.

### ISSUE THREAD

**Issue by mishrakhushi16** [transistorsoft/flutter_background_geolocation#1281]
This is my main.dart
void main() async{
   
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
   runApp(MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => UserProvider()),
    ],
    child: const MyApp(),
  ));
}
pragma('vm:entry-point')
void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
  
  Calling headless event
  
  NOw in dashboard.dart
  defined the callback events
   bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });
     bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: true,
        enableHeadless: true, 
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        print(state);
        //// bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: true,
        enableHeadless: true, 
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        print(state);
        ////
        
        

Then why when I am pausing the app then event is not getting called??
 ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(26184): ╠═════════════════════════════════════════════
D/TSLocationManager(26184): [c.t.l.event.TerminateEvent$a onChange]
D/TSLocationManager(26184):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).

**Comment by christocracy** [comment]
The issue template is **not** optional, it's **required**.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Also see wiki ["Debugging"](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Debugging).
