### ISSUE TITLE
Difference between 'DESIRED_ACCURACY_NAVIGATION' and 'DESIRED_ACCURACY_HIGH' for iOS

### ISSUE THREAD

**Issue by slowdh** [transistorsoft/flutter_background_geolocation#1283]
## Your Environment
* Plugin version: ^4.13.3
* Platform: iOS 
* OS version: 17.4.1
* Device manufacturer / model: Apple, iPhone13
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel master, 3.16.0-17.0.pre.5, on macOS 13.6 22G120 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.74.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (6 available)
[✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
  reset: true,
  url: LOCATION_FUNCTION_REQUEST_URL,
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20.0,
  enableHeadless: true,
  stopOnTerminate: false,
  startOnBoot: true,
  debug: HAS_DEBUG_FEEDBACK,
  stopTimeout: 1,
  locationTimeout: 30,
  logLevel: HAS_DEBUG_FEEDBACK
  ? bg.Config.LOG_LEVEL_VERBOSE: bg.Config.LOG_LEVEL_OFF,
  autoSync: true,
  geofenceInitialTriggerEntry: true,
)
```

## Context

In 'desiredAccuracy' property for iOS, what is difference between 'DESIRED_ACCURACY_NAVIGATION' and 'DESIRED_ACCURACY_HIGH'? Reading the api description it seems like doing the same job.

**Comment by christocracy** [comment]
See the iOS docs [CLLocationAccuracy](https://developer.apple.com/documentation/corelocation/cllocationaccuracy).

![IMG_0797](https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/ccbc5cd2-3d8f-4a7b-bbf1-9319a1e02cb3)

**Comment by christocracy** [comment]
- DESIRED_ACCURACY_NAVIGATION = kCLLocationAccuracyBestForNavigation
- DESIRED_ACCURACY_HIGH = kCLLocationAccuracyBest

**Comment by slowdh** [comment]
I see, thanks!
