### ISSUE TITLE
Switching Pace back to automatic when necessary

### ISSUE THREAD

**Issue by millerf** [transistorsoft/flutter_background_geolocation#1286]
### Your Environment
* Plugin version: latest
* Platform: iOS or Android - both
* OS version: Any
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`): latest

### General question regarding setting Pace manually.

The documentation says regarding the Pace setting that:

```
your app must manually transition to the "moving" state while your app is in the foreground by calling .changePace(true), like a "Jogging App" would do, where the user might click a [Start Workout] button before putting the phone in their pocket.
```

Which is perfectly fine and understandable. So I rigged:

```
bg.BackgroundGeolocation.onProviderChange(
  (bg.ProviderChangeEvent event) async {
   .
   .
   .
   switch (event.status) {
        case bg.ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE:
          if( isIOS ) {
              bg.BackgroundGeolocation.changePace(true); 
          }  
          break;
```

And the pace is forced to `true`.

However, if the user switches somehow changes the authorization to `AUTHORIZATION_STATUS_ALWAYS`, I have no way to switch back to `automatic`, as the only options is `true` (forced in "moving") and `false` (forced in"stationnary" - no GPS updates?).

Is there some way to reinstate the automatic pace? Or does it switches automatically back off when Permission is updated?

Thanks!

</details>

**Comment by christocracy** [comment]
It’s always “automatic”.  When the device is detected to be moving, the plug-in is **automatically calling .changePace(true) upon itself.  When the Config.stopTimeout expires, the plug-in is automatically calling .changePace(false) **upon itself**.

**Comment by millerf** [comment]
> It’s always “automatic”. When the device is detected to be moving,

Oh. So the forced pace is always "temporary" and is overriden whenever the system has the chance to update (and therefore is in `AUTHORIZATION_STATUS_ALWAYS`. Awesome.

 Thanks!
