### ISSUE TITLE
Colored bubble to appear when the app is actively using location services.

### ISSUE THREAD

**Issue by urvashi-k-7span** [transistorsoft/flutter_background_geolocation#1287]
Colored bubble to appear when the app is actively using location services in iOS,
When I tap on this bubble, my app opens directly from Home no API calls nothing no splash screen.

This is not your plugin related but any idea about How can I manage it? To open app from start when tapping on bubble.

**Comment by christocracy** [comment]
I'm unable to determine what is your request.
- You don't *see* a "colored bubble"??
- You *do* see a "colored bubble" but it's not responding as-desired??
