### ISSUE TITLE
How can I store user id into offline SQLite schema?

### ISSUE THREAD

**Issue by urvashik-7span** [transistorsoft/flutter_background_geolocation#1288]
In my case, I have integrated this plugin as follows:
When my internet is off, it will store the location in SQLite.

I log in with one user (1) in my app and set the internet off.
When I log out after turning on the internet, and re-login with another user that is (2), It will store user(1)'s data into user(2).

I am stopping service on logout by `BG.BackgroundGeolocation.stop();`
 ```
await bg.BackgroundGeolocation.ready(
      bg.Config(
        geofenceInitialTriggerEntry: true,
        geofenceModeHighAccuracy: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 20,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        enableHeadless: true,     
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
          title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message: 'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        ),
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        url: ApiConstants.locations,
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
          'Authorization': 'Bearer $token',
        },
        extras: {
          'timezone': currentTimeZone,
        },
      ),
    )
```

Can I store my custom user_id into SQLite?

**Comment by christocracy** [comment]
See api docs Config.params

**Comment by urvashik-7span** [comment]
Service stopped working by the above config, 
We are 10-15 people who installed the app using this service and config. Without any interaction, it works perfectly for 5-6 days and suddenly not receiving any locations.

**Comment by christocracy** [comment]
This issue is titled “* How can I store user id into offline SQLite schema?*”.

is this issue solved?

**Comment by urvashik-7span** [comment]
> This issue is titled “* How can I store user id into offline SQLite schema?*”.
> 
> is this issue solved?

Yes
