### ISSUE TITLE
Geofence radius defaulting to 150?

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#1290]
## Your Environment
* Plugin version: 4.14.0
* Platform: Android
* OS version: Several
* Device manufacturer / model: Several
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        //locationUpdateInterval: 5,
        //batchSync: true,
        useSignificantChangesOnly: Platform.isAndroid,
        maxRecordsToPersist: 25,
        url: 'https://${GetIt.I.get<EnvironmentsManager>().appDomain}${Endpoints.locationFlutterReport}',
        params: {'profile_id': profileId, 'location_token': securityToken.isSuccess ? securityToken.data : ''},
        autoSync: true,
        //transistorAuthorizationToken: token,
        backgroundPermissionRationale: bg.PermissionRationale(
            title: "Allow MotorMouth to always access this device's location",
            message: 'MotorMouth collects location data to enable recording your trips,'
                ' geofence entries and exits, and to calculate distance-travelled even '
                'when the app is closed or not in use. '
                'Motormouth does not sell location data to any 3rd parties.',
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification: bg.Notification(title: 'Motor Mouth', text: 'Location Service'),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));
```

## Expected Behavior
The Geofence should be set to whatever Radius we set.
## Actual Behavior
The Radius is being defaulted to 150 if the radius is smaller 

## Steps to Reproduce

1. Create a geofence with a radius smaller than 150
2. check the Geofence radius using (await bg.BackgroundGeolocation.geofences)

**Comment by christocracy** [comment]
That’s right, the minimum functional radius is 150 meters, imposed by the OS.

**Comment by lloydelvt** [comment]
Is this a new imposition by the OS?

**Comment by christocracy** [comment]
No, the OS have always only responded to a minimum radius of 150 meters.  It doesn’t matter if you set it to 0, the OS will respond as if you set it to 150.

you cannot have a geofence on either iOS or Android with a radius < 150.

**Comment by lloydelvt** [comment]
Ok I see thank you Chris

**Comment by lloydelvt** [comment]
Chris, the family tracking and safety application Life360 applies a 250ft radius (about 76 meters) to their smallest geofence. Do you know why they are able to do this differently form the OS limitation standpoint?

**Comment by christocracy** [comment]
Both iOS and Android respond only to a minimum geofence radius is 150 meters.  Google it.
