### ISSUE TITLE
BackgroundGeolocation.getCurrentPosition() making App crash

### ISSUE THREAD

**Issue by CarlosCabarcos** [transistorsoft/flutter_background_geolocation#1293]
## Your Environment
* Plugin version: ^4.15.2
* Platform: iOS or Android
* OS version: Android 14.
* Device manufacturer / model: Several
* Flutter info (`flutter doctor`):
* [!] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Versi¢n 10.0.19045.4291], locale es-ES)
    ! The flutter binary is not on your path. Consider adding C:\Users\louen\fvm\versions\3.19.2\bin to your path.
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\Users\louen\fvm\versions\3.19.2. Consider adding C:\Users\louen\fvm\versions\3.19.2\bin to th
e front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] Network resources

flutter --version:
Flutter 3.19.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7482962148 (3 months ago) • 2024-02-27 16:51:22 -0500
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

      bg.Config(
        stopTimeout: 1440,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 5.0,
        stopOnTerminate: false,
        preventSuspend: true,
        startOnBoot: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification: bg.Notification(title: "XXX", text: "XXX está utilizando tu ubicación"),
        showsBackgroundLocationIndicator: true,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Habilita el permiso "Siempre"',
          'titleWhenOff': 'Habilita el permiso "Siempre"',
          'instructions': 'Para poder detecter tu ruta y tu actividad en segundo plano, otorga el permiso "Siempre" de la localización.',
          'cancelButton': 'Cancelar',
          'settingsButton': 'Habilitar',
        },
        locationAuthorizationRequest: 'WhenInUse',
        backgroundPermissionRationale: bg.PermissionRationale(
            title: "¿Permitir a {applicationName} utilizar la localización en segundo plano?",
            message: "Para poder detectar tu ruta y tu actividad en segundo plano, otorga el permiso {backgroundPermissionOptionLabel} de la localización.",
            positiveAction: "Cambiar a {backgroundPermissionOptionLabel}",
            negativeAction: "Cancelar"),
      ),
    );

```

## Expected Behavior

Location should be fetched.

## Actual Behavior

App crashes.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I have recently had to update many plugins, Java version, flutter version, make changes in Gradle, solve a lot of dependency issues, etc. Before all the updates, everything was working fine. No changes have been made to the code. 

Initialization (bg.Config(...)) seems to be working alright and I'm getting no errors or anything out of the ordinary.

However, since the updates, when bg.BackgroundGeolocation.getCurrentPosition() is called, the app crashes. From the log, I found online that I should perhaps add this to app/build.gradle: 

`implementation 'com.google.android.gms:play-services-location:21.2.0'. `

or in the root build.gradle.

```
        configurations.all{
            resolutionStrategy{
                force "com.google.android.gms:play-services-location:21.2.0"
            }
        }
```

However, none seem to be changing anything.

Any idea of what might be going on?

Thank you very much.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Uncaught Exception: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~2ntZvnJ69-vFDtnu_q-J0Q==/com.jizooapp-wMtPuCe8ke7M_gX21YX1ig==/base.apk!classes21.dex)
...

E/TSLocationManager( 9102): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~2ntZvnJ69-vFDtnu_q-J0Q==/com.jizooapp-wMtPuCe8ke7M_gX21YX1ig==/base.apk!classes21.dex)
E/TSLocationManager( 9102): 	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
E/TSLocationManager( 9102): 	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
E/TSLocationManager( 9102): 	at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
E/TSLocationManager( 9102): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$i.run(Unknown Source:12)
E/TSLocationManager( 9102): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/TSLocationManager( 9102): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/TSLocationManager( 9102): 	at java.lang.Thread.run(Thread.java:1012)
```
</details>

**Comment by christocracy** [comment]
Do not do stuff like this:

configurations.all{
            resolutionStrategy{
                force "com.google.android.gms:play-services-location:21.2.0"
            }
        }

you need to analyze your dependencies:

$ cd android 
$ ./gradlew app:dependencies

**Comment by CarlosCabarcos** [comment]
Hi @christocracy. I just tried that as a "brute force" attempt, to see if I got it to work. But it changed nothing. If I remove it, I'm still getting the same crash.

**Comment by christocracy** [comment]
> If I remove it, I'm still getting the same crash.

Of course you do.  You need to analyze your dependencies to see which version of play-services-location is being requested by all dependencies.

**Comment by CarlosCabarcos** [comment]
Modifying this in build.gradle:
```
ext {
        ...
        playServicesLocationVersion = "21.2.0"  // or higher
    }
```
Updating to 21.2.0 from 20.0.0, seemed to do the trick. I was unaware of this ext property being added here (inherited project). It's being used by flutter_background_geolocation, right?

 If I understood the gradle logs correctly, another plugin, "location", seemed to be asking for version 21.2.0, while "flutter_background_geolocation" was using this ext property and trying to use 20.0.0. Now both point to 21.2.0.

Still very new to doing things in Gradle, seems awfully messy...

**Comment by christocracy** [comment]
Have you looked at the Android Setup instructions linked in the readme?

it’s well-known that Google introduced a breaking change in play-services-location v21.  When one plugin imports a v20 or v21, all plugin must import that same version.

It is very fortunate that this plugin allows you to control the imported version via ext var, rather than hard-coding the imported version.

**Comment by christocracy** [comment]
Duplicate #933
