### ISSUE TITLE
LICENSE_VALIDATION_FAILURE Only in Release from PlayStore

### ISSUE THREAD

**Issue by thiaagodev** [transistorsoft/flutter_background_geolocation#1296]
* Plugin version: 4.15.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
[✓] VS Code (version 1.89.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

I'm getting License validation error in release version even though I have a license.

When I build my release version, I run it and the license is valid, but when I submit my app package to playstore and they re-sign my app with another sha256 key, the license starts to fail.

**Comment by christocracy** [comment]
Review the Setup Instructions and ensure you’ve performed every step.  Everything in green is required, not optional.

**Comment by thiaagodev** [comment]
I'm sure everything is ok in setup, because I have an app with an identical setup and another license, and it works

**Comment by christocracy** [comment]
email me the following info (do not post publicly here)

1.  Order #
2. AndroidManifest
3. android/build.gradle
4. android/app/build.gradle

**Comment by thiaagodev** [comment]
Ok, what e-mail?

**Comment by christocracy** [comment]
view my Github profile for contact info / link to company website (which has contact info).

**Comment by thiaagodev** [comment]
Sorry, I discovered the problem, it was a wrong env in the pipeline
