### ISSUE TITLE
Tracking is not stopping even after logout

### ISSUE THREAD

**Issue by sohamD07** [transistorsoft/flutter_background_geolocation#1297]
My login function calls -> await bg.BackgroundGeolocation.start()
My logout function calls -> await bg.BackgroundGeolocation.stop()

## Expected Behavior
In my app, whenever a user login to the app tracking gets started, and on logout it gets ended. But I have observed that tracking keeps happening in a one scenarios where the user is not doing logout directly instead he might doing `Clear Data` from app setting. 

Cases:

1. user 1 login at 10:00 am and logout at 2:00 pm -> Tracking ended at 2:00 pm, no tracking logs after 2:00 pm
2. user 2 logins at 10:00 am then he did `clear data` from the app setting at 11:00 am. Again he login to the app at 11:02 am and logout at 2:00 pm -> Tracking not ended after 2:00 pm

Is it possible that, previous instance of tracking not get disposed even after clearing the data from the app setting?

## Actual Behavior
Tracking to be ended after logout at 2:00 pm for user 2

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in does not record locations after .stop() is called.

> previous instance of tracking not get disposed even after clearing the data from the app setting?

There’s no such thing as “previous instances”.  There is only one instance.  The plug-in is implemented as a singleton.

I suggest you observe your logs.  See wiki “Debugging”.
