### ISSUE TITLE
Lat long not update into server

### ISSUE THREAD

**Issue by PoriyaBytez** [transistorsoft/flutter_background_geolocation#1299]
## Your Environment
* Plugin version: flutter_background_geolocation
* Platform: Android
* OS version:
* Device manufacturer/model: redmi note 9 
* Flutter info (`flutter doctor`):
[!] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4412], locale en-IN)
    • Flutter version 3.19.0 on channel stable at E:\flutter_sdk\flutter_windows_3.19.0-stable
    ! Warning: `flutter` on your path resolves to E:\flutter_sdk\flutter_windows_2.0.1-stable\bin\flutter, which is not inside your current Flutter SDK checkout at E:\flutter_sdk\flutter_windows_3.19.0-stable. Consider adding E:\flutter_sdk\flutter_windows_3.19.0-stable\bin to the front of your path.
    ! Warning: `dart` on your path resolves to E:\flutter_sdk\flutter_windows_2.0.1-stable\bin\dart, which is not inside your current Flutter SDK checkout at E:\flutter_sdk\flutter_windows_3.19.0-stable. Consider adding E:\flutter_sdk\flutter_windows_3.19.0-stable\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 months ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Addmin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34301.259
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (4 available)
    • Redmi Note 9 Pro (mobile) • 63752d26 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)         • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.4412]
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 125.0.6422.0
    • Edge (web)                • edge     • web-javascript • Microsoft Edge 124.0.2478.105

[√] Network resources
    • All expected network resources are available.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
    bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        debug: false,
        url:
            'http://roster.multitrack.in:5055/?id=${preferences.getInt('id').toString()}&lat=${location.coords.latitude.toString()}&lon=${location.coords.longitude.toString()}&speed=${location.coords.speed > 0.0 ? location.coords.speed : 0.0}',
        headers: headers,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
              "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        ),
        forceReloadOnMotionChange: true,
        forceReloadOnLocationChange: true,
        fastestLocationUpdateInterval: 10000,
        forceReloadOnBoot: true,
        allowIdenticalLocations: true,
        stopTimeout: 60,
        foregroundService: true,
        locationTimeout: 10,
        deferTime: 10000,
        activityRecognitionInterval: 10000,
        forceReloadOnHeartbeat: true,
        heartbeatInterval: 10,
        isMoving: false,
        locationUpdateInterval: 10000,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        autoSync: true,
      ),
    ).then((bg.State state) {
      bg.Logger.debug("🔔 [BackgroundFetch start]");

      print("[ready] ${state.toMap()}");
      bg.BackgroundGeolocation.start().then((bg.State state) async {
        print('[start] success $state');
        
      }).catchError((error) {
        print('[start] ERROR: $error');
      });
      _onClickChangePace();
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }
```

## Expected Behavior

Update lat long  into server 

## Actual Behavior

Same lat long  update into server 

## Steps to Reproduce

1.
2.
3.
4.

## Context

Update lat long  into server when we are moving

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>             'http://roster.multitrack.in:5055/?id=${preferences.getInt('id').toString()}&lat=${location.coords.latitude.toString()}&lon=${location.coords.longitude.toString()}&speed=${location.coords.speed > 0.0 ? location.coords.speed : 0.0}',

You cannot apply a template to the Config.url.

See api docs Config.locationTemplate.

you cannot apply data to the GET `?` params of an url.  The plug-in sends pure JSON in the *body* of the http POST.
