### ISSUE TITLE
Config.reset = true and locationTemplate does not work together

### ISSUE THREAD

**Issue by carmaa** [transistorsoft/flutter_background_geolocation#1301]
## Your Environment
* Plugin version: 4.15.3
* Platform: iOS
* OS version: 17.2
* Device manufacturer / model: iPhone 15
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6.6 22G630 darwin-x64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
      reset: true,
      url: locationsUrl,
      httpRootProperty: '.',
      locationTemplate:
          '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}', // To match our Location SQLModel
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopTimeout: 5,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
)
```

## Expected Behavior
As I'm forcing the apply supplied [Config](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config-class.html) with each application launch using the `reset` property, I'd expect the `locationTemplate` to change the rendering of data in the JSON when re-launching the app or building a new one.

## Actual Behavior
Not able to pinpoint the mechanics, but sometimes it changes, sometimes it doesn't and seem to be loading an old config from persistent storage? The only way I've been able to reliantly change the config is through deleting the app on the device (including all its data), before rebuilding and launching.

## Steps to Reproduce

1. Run the following code: 
```dart
const locationsUrl = '${const String.fromEnvironment('URL')}locations/';

class LocationService {
  LocationService() {
    _initialize();
  }

  void _initialize() async {
    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      logger.i('[location] - $location');
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      logger.i('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      logger.i('[providerchange] - $event');
    });

    bg.BackgroundGeolocation.onHttp((bg.HttpEvent response) {
      logger.i('[http] - $response');
    });

    bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      url: locationsUrl,
      httpRootProperty: '.',
      locationTemplate:
          '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopTimeout: 5,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
  }
}
```
2. Change the locationTemplate to a new one
3. Run the code again
4. Observe that the old locationTemplate is used

## Context
Reliably experiment with the config.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
reset: true is the default.  You don’t have to explicitly set it.

you like have records previously recorded with the previous template sitting in the plug-ins SQLite db.  Records are not re-rendered when template changes.

**Comment by christocracy** [comment]
>A bit off-topic perhaps, but is it possible to query the SQLite db for locations in a date range

No.  Access to the plugin's sqlite db is limited.  It's not meant to be used for your own application storage.  It's strictly designed to operate as a queue for the plugin's built-in HTTP service.  The plugin stores its data in a simple JSON blob `COLUMN`, not in a strictly relational fashion, with separate columns for each attribute.

For more advanced application storage, implement your own SQLite db.
