### ISSUE TITLE
Activity Type Airborne Missing

### ISSUE THREAD

**Issue by sikandernoori** [transistorsoft/flutter_background_geolocation#1304]
Apple has Activity type Airborne for over 3 years. [Link](https://developer.apple.com/documentation/corelocation/clactivitytype/clactivitytypeairborne?language=objc)

can we add this as well.

https://github.com/transistorsoft/flutter_background_geolocation/blob/6b4d4cccf0064ac05a1cbeff4cd5557a15b4111c/lib/models/config.dart#L67

**Comment by christocracy** [comment]
I was not aware of this.  I will implement it.

**Comment by sikandernoori** [comment]
> I was not aware of this. I will implement it.

When can we expect this ?
