### ISSUE TITLE
(OT?) Suggestions for Compose Multiplatform?

### ISSUE THREAD

**Issue by sisyfus** [transistorsoft/flutter_background_geolocation#1305]
Would I be correct in saying that if one is using Compose Multiplatform, background location tracking would be easier, because we'd be dealing with the native APIs directly, and thus, there's no real need for Transistor Software to develop any "plugins" per se? Any general advice? I'm currently learning Flutter, but I'm considering switching to Compose Multiplatform. 
Apologies if this question is too far off topic.

**Comment by christocracy** [comment]
This plug-in *IS* a pure native SDK, implementing the native iOS and Android location APIs, just like any pure native app.

in fact, the underlying pure native SDK imported by this plugin is able to be used in pure native apps.

it could be ported to this “Compose Multiplatform”, if there was enough interest, in about one month.
