### ISSUE TITLE
About the changes to CoreLocation in iOS18, will it affect the function of the plugin?

### ISSUE THREAD

**Issue by llli0v0** [transistorsoft/flutter_background_geolocation#1308]
Sorry, this issue is not about code, so I didn't use the issue template~

I have read wwdc24, Apple has made some changes to CoreLocation, may I ask how this will affect the function of this plugin? In particular, the background continuous positioning, and the app killed after the significant location move and restart the app and continue to locate, these aspects of the function.

**Comment by christocracy** [comment]
>Apple has made some changes to CoreLocation

Show me the exact link where you see specifically see "*changes to CoreLocation*".  I see nothing listed in the [iOS 18 Beta Release Notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-18-release-notes)

**Comment by christocracy** [comment]
I tested iOS 18 beta with a bike ride on an *iPhone 14* device.  Everything continues to operate as expected.

<img width="894" alt="Screenshot 2024-06-13 at 1 53 23 PM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/6ddcbd7d-60e1-428e-b0d3-c1f0c84c0754">

**Comment by llli0v0** [comment]
I saw it from this video, https://www.youtube.com/watch?v=kHAEd-YEAEw

Ok, thank you very much~😄
