### ISSUE TITLE
Persist event to database

### ISSUE THREAD

**Issue by jaykobi** [transistorsoft/flutter_background_geolocation#131]
Some events are persisted to the database (onLoaction, onProviderChange) but some are not. How can I persist onEnabledChange to the database? To track when a user manually disables tracking my app.

**Comment by christocracy** [comment]
```dart
bg.BackgroundGeolocation.onEnabledChange((enabled) {
  bg.BackgroundGeolocation.getCurrentPosition(
    persist: true,
    extras: {
      "event": "enabledchange",
      "enabled": enabled
    }
  );
});
```

You might also want to perform that in your [Headless Task](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode) if you're interested in the Android terminated case.
