### ISSUE TITLE
Distance filter is not working in demo application

### ISSUE THREAD

**Issue by nagrazr** [transistorsoft/flutter_background_geolocation#1312]
## Your Environment
* Plugin version: Latest demo application downloaded on June 19
* Platform: iOS or Android : Android
* OS version: 
* Device manufacturer / model: Nokia 7.2 
* Flutter info (`flutter doctor`): NA
* Plugin config: 
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Should not fire location updates as I have distance filter and mobile is stationary. 

## Actual Behavior

It keeps firing the heartbeat as well as location updates with debug sounds everytime it fires the event.  

## Steps to Reproduce

1. Install demo app. 
2. Set the distance filter
3.
4.

## Context

Understand the behaviour of the demo app with respect to documentation

## Debug logs

<details>
	<summary>Logs</summary>
[background-geolocation (1).log.gz](https://github.com/user-attachments/files/15909285/background-geolocation.1.log.gz)

06-19 22:37:07.314 DEBUG [TSSQLiteAppender destroyLog] 
  🔵  Destroy log success
06-19 22:37:44.208 DEBUG [LifecycleManager onPause] ☯️  onPause
06-19 22:37:54.319 DEBUG [LifecycleManager onStop] ☯️  onStop
06-19 22:37:54.357 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-19 22:37:57.335 DEBUG [LifecycleManager onStart] ☯️  onStart
06-19 22:37:57.338 INFO [TSScheduleManager cancelOneShot] 
  ⏰ Cancel OneShot: TERMINATE_EVENT
06-19 22:37:57.353 DEBUG [LifecycleManager onResume] ☯️  onResume
06-19 22:37:57.356 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

06-19 22:41:34.475 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: HEARTBEAT
╠═════════════════════════════════════════════

06-19 22:41:34.483 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
06-19 22:41:34.485 DEBUG [HeartbeatService onHeartbeat] ❤️
06-19 22:41:34.771 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 301
06-19 22:41:34.780 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 163 (280156ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683473,-122.122177 hAcc=77 et=+1d13h24m26s583ms alt=30.399999618530273 vel=0.16871144 bear=44.926777 vAcc=1 sAcc=2 bAcc=45 {Bundle[{}]}], time: 1718861814624

06-19 22:41:34.781 DEBUG [TSLocationManager a] Median accuracy: 52.528
06-19 22:41:34.791 DEBUG [LocationAuthorization withPermission] 
  ℹ️  LocationAuthorization: Permission granted
06-19 22:41:34.802 DEBUG [AbstractService a] 
  🎾  start [LocationRequestService  startId: 1, eventCount: 1]
06-19 22:41:34.806 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 163]
06-19 22:41:34.807 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 0, sticky: true]
06-19 22:41:37.348 DEBUG [AbstractService a] 
  🎾  2:163 [LocationRequestService  startId: 2, eventCount: 1]
06-19 22:41:37.350 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 163 (2355ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683396,-122.122240 hAcc=11 et=+1d13h29m6s954ms alt=30.399999618530273 vAcc=1 sAcc=2 bAcc=45 {Bundle[{}]}], time: 1718862094994

06-19 22:41:37.362 DEBUG [AbstractService b] 
  🎾  STOP [LocationRequestService startId: 3, eventCount: 2]
06-19 22:41:37.362 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 3, eventCount: 1, sticky: false]
06-19 22:41:37.406 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-19 22:41:37.406 DEBUG [TSLocationManager a] Median accuracy: 19.674
06-19 22:41:37.424 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 2, eventCount: 0, sticky: false]
06-19 22:41:37.427 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 301
06-19 22:41:37.437 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 682dd783-fcee-4947-ae76-2e2b370a7413
06-19 22:41:37.790 DEBUG [AbstractService f] 
  ⚙️︎  LocationRequestService.stopSelfResult(3): true
06-19 22:41:37.792 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService stopped
06-19 22:41:37.818 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

06-19 22:41:37.935 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 302
06-19 22:41:37.971 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
06-19 22:41:37.971 INFO [HttpService a] 
  🔵  HTTP POST: 682dd783-fcee-4947-ae76-2e2b370a7413
06-19 22:41:39.131 INFO [HttpService$f onResponse] 
  🔵  Response: 200
06-19 22:41:39.132 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: 682dd783-fcee-4947-ae76-2e2b370a7413
06-19 22:41:39.165 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 302
06-19 22:42:42.103 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-19 22:42:42.754 DEBUG [LifecycleManager onPause] ☯️  onPause
06-19 22:42:42.755 DEBUG [LifecycleManager onStop] ☯️  onStop
06-19 22:42:52.140 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-19 22:42:52.141 DEBUG [TerminateEvent$a onChange] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-19 22:46:34.512 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: HEARTBEAT
╠═════════════════════════════════════════════

06-19 22:46:34.545 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
06-19 22:46:34.548 DEBUG [HeartbeatService onHeartbeat] ❤️
06-19 22:46:34.808 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 303
06-19 22:46:34.832 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 164 (14925ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683453,-122.122236 hAcc=501 et=+1d13h33m51s866ms alt=30.399999618530273 vel=0.0 vAcc=1 sAcc=2 bAcc=??? {Bundle[{}]}], time: 1718862379906

06-19 22:46:34.837 DEBUG [TSLocationManager a] Median accuracy: 19.674
06-19 22:46:34.842 DEBUG [LocationAuthorization withPermission] 
  ℹ️  LocationAuthorization: Permission granted
06-19 22:46:34.877 DEBUG [AbstractService a] 
  🎾  start [LocationRequestService  startId: 1, eventCount: 1]
06-19 22:46:34.878 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 164]
06-19 22:46:34.880 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 0, sticky: true]
06-19 22:46:35.565 DEBUG [AbstractService a] 
  🎾  2:164 [LocationRequestService  startId: 2, eventCount: 1]
06-19 22:46:35.567 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 164 (101ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683420,-122.122235 hAcc=58 et=+1d13h34m7s424ms alt=29.799999237060547 vel=0.45830157 bear=133.67735 vAcc=1 sAcc=2 bAcc=45 {Bundle[{}]}], time: 1718862395465

06-19 22:46:35.574 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-19 22:46:35.575 DEBUG [TSLocationManager a] Median accuracy: 52.528
06-19 22:46:35.581 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 2, eventCount: 1, sticky: false]
06-19 22:46:35.588 DEBUG [AbstractService b] 
  🎾  STOP [LocationRequestService startId: 3, eventCount: 1]
06-19 22:46:35.589 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 3, eventCount: 0, sticky: false]
06-19 22:46:35.592 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 07ae9d1e-5408-49b6-8687-6f119155bb65
06-19 22:46:35.599 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 303
06-19 22:46:35.628 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

06-19 22:46:35.729 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 304
06-19 22:46:35.752 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
06-19 22:46:35.753 INFO [HttpService a] 
  🔵  HTTP POST: 07ae9d1e-5408-49b6-8687-6f119155bb65
06-19 22:46:35.797 DEBUG [AbstractService f] 
  ⚙️︎  LocationRequestService.stopSelfResult(3): true
06-19 22:46:35.798 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService stopped
06-19 22:46:36.924 INFO [HttpService$f onResponse] 
  🔵  Response: 200
06-19 22:46:36.927 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: 07ae9d1e-5408-49b6-8687-6f119155bb65
06-19 22:46:36.960 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 304
06-19 22:46:41.895 DEBUG [LifecycleManager onStart] ☯️  onStart
06-19 22:46:41.899 DEBUG [LifecycleManager onResume] ☯️  onResume
06-19 22:46:41.901 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

06-19 22:47:16.916 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-19 22:47:17.590 DEBUG [LifecycleManager onPause] ☯️  onPause
06-19 22:47:17.591 DEBUG [LifecycleManager onStop] ☯️  onStop
06-19 22:47:26.934 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-19 22:47:26.935 DEBUG [TerminateEvent$a onChange] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-19 22:47:43.253 DEBUG [LifecycleManager onStart] ☯️  onStart
06-19 22:47:43.261 DEBUG [LifecycleManager onResume] ☯️  onResume
06-19 22:47:43.264 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

06-19 22:48:23.037 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-19 22:48:23.725 DEBUG [LifecycleManager onPause] ☯️  onPause
06-19 22:48:23.726 DEBUG [LifecycleManager onStop] ☯️  onStop
06-19 22:48:33.067 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

06-19 22:48:33.068 DEBUG [TerminateEvent$a onChange] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-19 22:49:53.936 DEBUG [TSLog log] 🔔 [BackgroundFetch start] flutter_background_fetch
06-19 22:49:53.970 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 165 (5167ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683443,-122.122239 hAcc=671 et=+1d13h37m20s762ms alt=30.19999885559082 vel=0.0 vAcc=1 sAcc=2 bAcc=??? {Bundle[{}]}], time: 1718862588803

06-19 22:49:54.014 DEBUG [TSLocationManager a] Median accuracy: 57.888
06-19 22:49:54.020 DEBUG [LocationAuthorization withPermission] 
  ℹ️  LocationAuthorization: Permission granted
06-19 22:49:54.090 DEBUG [AbstractService a] 
  🎾  start [LocationRequestService  startId: 1, eventCount: 1]
06-19 22:49:54.091 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 165]
06-19 22:49:54.093 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 0, sticky: true]
06-19 22:50:01.176 DEBUG [AbstractService a] 
  🎾  2:165 [LocationRequestService  startId: 2, eventCount: 1]
06-19 22:50:01.177 INFO [LocationRequestService b] 
  ℹ️  Location availability: false
06-19 22:50:01.178 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 2, eventCount: 0, sticky: true]
06-19 22:50:08.977 DEBUG [AbstractService a] 
  🎾  2:165 [LocationRequestService  startId: 3, eventCount: 1]
06-19 22:50:08.978 INFO [LocationRequestService b] 
  ℹ️  Location availability: true
06-19 22:50:08.978 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 3, eventCount: 0, sticky: true]
06-19 22:50:11.562 DEBUG [AbstractService a] 
  🎾  2:165 [LocationRequestService  startId: 4, eventCount: 1]
06-19 22:50:11.564 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 165 (7619ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683424,-122.122270 hAcc=11 et=+1d13h37m35s904ms alt=30.19999885559082 vel=3.1590385E-5 vAcc=1 sAcc=2 bAcc=??? {Bundle[{}]}], time: 1718862603944

06-19 22:50:11.598 DEBUG [AbstractService b] 
  🎾  STOP [LocationRequestService startId: 5, eventCount: 2]
06-19 22:50:11.598 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 5, eventCount: 1, sticky: false]
06-19 22:50:11.614 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-19 22:50:11.615 DEBUG [TSLocationManager a] Median accuracy: 57.888
06-19 22:50:11.621 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 4, eventCount: 0, sticky: false]
06-19 22:50:11.630 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: d7bad688-b225-43a9-806a-8bd49679477f
06-19 22:50:11.651 DEBUG [TSLog log] 🔔 [BackgroundFetch finish] flutter_background_fetch
06-19 22:50:11.655 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

06-19 22:50:11.809 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 305
06-19 22:50:11.824 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
06-19 22:50:11.824 INFO [HttpService a] 
  🔵  HTTP POST: d7bad688-b225-43a9-806a-8bd49679477f
06-19 22:50:11.826 DEBUG [AbstractService f] 
  ⚙️︎  LocationRequestService.stopSelfResult(5): true
06-19 22:50:11.826 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService stopped
06-19 22:50:12.608 INFO [HttpService$f onResponse] 
  🔵  Response: 200
06-19 22:50:12.610 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: d7bad688-b225-43a9-806a-8bd49679477f
06-19 22:50:12.648 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 305
06-19 22:50:20.356 DEBUG [TSLog log] 🔔 [BackgroundFetch start] com.transistorsoft.customtask
06-19 22:50:20.357 DEBUG [TSLog log] 🔔 [BackgroundFetch finish] com.transistorsoft.customtask
06-19 22:51:34.583 INFO [ScheduleEvent a] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: HEARTBEAT
╠═════════════════════════════════════════════

06-19 22:51:34.597 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: HEARTBEAT in 300000ms (jobID: -1307475748)
06-19 22:51:34.599 DEBUG [HeartbeatService onHeartbeat] ❤️
06-19 22:51:34.799 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 306
06-19 22:51:34.820 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 166 (90875ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683424,-122.122270 hAcc=11 et=+1d13h37m35s904ms alt=30.19999885559082 vel=3.1590385E-5 vAcc=1 sAcc=2 bAcc=??? {Bundle[{}]}], time: 1718862603944

06-19 22:51:34.821 DEBUG [TSLocationManager a] Median accuracy: 57.888
06-19 22:51:34.826 DEBUG [LocationAuthorization withPermission] 
  ℹ️  LocationAuthorization: Permission granted
06-19 22:51:34.853 DEBUG [AbstractService a] 
  🎾  start [LocationRequestService  startId: 1, eventCount: 1]
06-19 22:51:34.854 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 166]
06-19 22:51:34.856 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 0, sticky: true]
06-19 22:51:36.975 DEBUG [AbstractService a] 
  🎾  2:166 [LocationRequestService  startId: 2, eventCount: 1]
06-19 22:51:36.976 INFO [TSLocationManager a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 166 (2005ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 47.683450,-122.122214 hAcc=11 et=+1d13h39m6s930ms alt=30.399999618530273 vAcc=1 sAcc=2 bAcc=45 {Bundle[{}]}], time: 1718862694971

06-19 22:51:37.001 DEBUG [AbstractService b] 
  🎾  STOP [LocationRequestService startId: 3, eventCount: 2]
06-19 22:51:37.001 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 3, eventCount: 1, sticky: false]
06-19 22:51:37.021 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
06-19 22:51:37.022 DEBUG [TSLocationManager a] Median accuracy: 11.476
06-19 22:51:37.030 DEBUG [AbstractService a] 
  ⚙️︎   FINISH [LocationRequestService startId: 2, eventCount: 0, sticky: false]
06-19 22:51:37.031 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 306
06-19 22:51:37.050 INFO [SQLiteLocationDAO persist] 
  ✅  INSERT: 1376cf49-eb58-47cf-8e10-428e8710ef7e
06-19 22:51:37.083 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

06-19 22:51:37.143 INFO [BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 307
06-19 22:51:37.157 DEBUG [SQLiteLocationDAO first] 
  ✅  Locked 1 records
06-19 22:51:37.158 INFO [HttpService a] 
  🔵  HTTP POST: 1376cf49-eb58-47cf-8e10-428e8710ef7e
06-19 22:51:37.234 DEBUG [AbstractService f] 
  ⚙️︎  LocationRequestService.stopSelfResult(3): true
06-19 22:51:37.235 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService stopped
06-19 22:51:38.053 INFO [HttpService$f onResponse] 
  🔵  Response: 200
06-19 22:51:38.055 DEBUG [SQLiteLocationDAO destroy] 
  ✅  DESTROY: 1376cf49-eb58-47cf-8e10-428e8710ef7e
06-19 22:51:38.081 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 307
06-19 22:54:07.532 DEBUG [LifecycleManager onStart] ☯️  onStart
06-19 22:54:07.537 DEBUG [LifecycleManager onResume] ☯️  onResume
06-19 22:54:07.540 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
How are you changing the options in the demo app?  Are you modifying the code or using the Settings screen?

**Comment by nagrazr** [comment]
Using + FAB and settings.

**Comment by nagrazr** [comment]
Sorry for using acronym, I meant FAB = Floating action button.

**Comment by nagrazr** [comment]
![Untitled](https://github.com/transistorsoft/flutter_background_geolocation/assets/39843661/4c89f8a4-9a28-4e25-9055-e55060f4ad2a)

**Comment by christocracy** [comment]
The distanceFilter is not used when the device is stationary.  Heartbeat fires only when the device is stationary.  There’s likely a call to .getCurrentPosition in the onHeartbeat event-handler.

**Comment by nagrazr** [comment]
Not clear, why would location event be triggered for calling getCurrentLocation inside onHeartbeat event handler ? 

Following seems to be code.... 
[flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation/tree/d5a82f4cd4ed7f20fc13c8872976e0e07375e8d0)/[example]

void _onHeartbeat(bg.HeartbeatEvent event) async {
    print('[${bg.Event.HEARTBEAT}] - $event');
    // In onHeartbeat, if you intend to any kind of async task, first start a background-task:
    var taskId = await bg.BackgroundGeolocation.startBackgroundTask();

    // Now that we've initiated a background-task, call .getCurrentPosition()
    try {
      bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(
        samples: 2,
        timeout: 10,
        extras: {
          "event":"heartbeat"
        }
      );
      print("[heartbeat] getCurrentPosition: $location");
    } catch(e) {
      print("[heartbeat] getCurrentPosition ERROR: $e");
    }
    setState(() {
      events.insert(0, Event(bg.Event.HEARTBEAT, event, event.toString()));
    });

    // Be sure to signal completion of your task.
    bg.BackgroundGeolocation.stopBackgroundTask(taskId);
  }

**Comment by christocracy** [comment]
> why would location event be triggered for calling getCurrentLocation

Why shouldn’t it.  Do you know what .getCurrentPosition does?  

“Get current position”

**Comment by nagrazr** [comment]
Thank you ! Few more questions. 
1) Is there a way to suppress triggering onLocation event as getCurrentPosition returns location already ? 
2) I also get samples location records (location.sample=true) in addition to the one without location.sample, and co-ordinates are different for those 2 location records. Which one is more reliable or to discard ? 
3) onHeartBeatInterval - is it exact ?

**Comment by christocracy** [comment]
> Is there a way to suppress triggering onLocation event

No.  Use getCurrentPosition extras option as a signal.

> Which one is more reliable or to discard ?

Discard sample: true

> onHeartBeatInterval

No.

**Comment by nagrazr** [comment]
Thanks a lot for the Great support!!! Appreciate it lot!
