### ISSUE TITLE
Warning: [deprecation] Registrar in PluginRegistry has been deprecated

### ISSUE THREAD

**Issue by nagrazr** [transistorsoft/flutter_background_geolocation#1313]
## Your Environment
* Plugin version: 4.15.5
* Platform: iOS or Android : Android 
* OS version: Windows
* Device manufacturer / model: NA
* Flutter info (`flutter doctor`): 
* Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.2.3)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.90.1)
[√] Connected device (4 available)
[√] Network resources
• No issues found!
dart --version
Dart SDK version: 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "windows_x64"

* Plugin config: NA
```dart <-- Syntax highlighting: DO NOT REMOVE --> 
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

1) No deprecated api. 
**Following issue may not be connected to Flutter_background_geolocation. Please ignore if it is not relevant or help if you are knowledgeble or it is connected...** 
a) Is it ok to have Connected engine count 3 ? 
**D/FlutterGeolocator(30194): Flutter engine connected. Connected engine count 3**
b) What could be possible issue ? 
W/Parcel  (  594): Expecting binder but got null!

## Actual Behavior

**D/FlutterGeolocator(30194): Flutter engine connected. Connected engine count 3**

## Steps to Reproduce

1. Create new project. Add flutter_background_geolocation depdency
2. Build with xlint option.
3.
4.

## Context
 
Clean build after adding flutter_background_geolocation depdency

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by nagrazr** [comment]
AppData\Local\Pub\Cache\hosted\pub.dev\background_fetch-1.3.5\android\src\main\java\com\transistorsoft\flutter\backgroundfetch\BackgroundFetchPlugin.java:8: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
1 warning


D/FlutterGeolocator(30194): Geolocator foreground service connected
D/FlutterGeolocator(30194): Initializing Geolocator services
D/FlutterGeolocator(30194): Flutter engine connected. Connected engine count 3

**Comment by christocracy** [comment]
Duplicate #1167 

please search before posting.
