### ISSUE TITLE
How to disable data deletion after successful sending to the server?

### ISSUE THREAD

**Issue by gicha** [transistorsoft/flutter_background_geolocation#1318]
## Your Environment
* Plugin version: 4.15.5
* Platform: iOS and Android
* OS version: Android 14
* Device manufacturer / model: Pixel 7
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
        reset: true,
        distanceFilter: 20,
        autoSync: true,
        foregroundService: true,
        stopAfterElapsedMinutes: 30,
        enableHeadless: true,
        fastestLocationUpdateInterval: 1000,
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        heartbeatInterval: 200,
        locationAuthorizationRequest: 'Always',
        stopTimeout: 5,
        stopOnTerminate: false,
        logLevel: Config.LOG_LEVEL_VERBOSE,
        debug: true,
        allowIdenticalLocations: true,
        showsBackgroundLocationIndicator: true,
        url: apiUrl,
        httpRootProperty: '.',
        authorization: Authorization(accessToken: getAuthToken()),
        locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
        locationsOrderDirection: 'DESC',
        maxDaysToPersist: 5,
        maxRecordsToPersist: -1,
        persistMode: Config.PERSIST_MODE_LOCATION,
        startOnBoot: true,
      );
```

## Expected Behavior
When moving in the background, data is sent to the backend. After running the application I can get these geolocations using BackgroundGeolocation.locations getter

## Actual Behavior
Once a geolocation is successfully sent, it is immediately deleted from the database. BackgroundGeolocation.locations returns an empty array

## Steps to Reproduce
1. Run app
2. Move the app to background
3. Change a location
4. Open the app and call BackgroundGeolocation.locations

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
 [c.t.l.d.s.SQLiteLocationDAO persist] 
I/TSLocationManager(18628):   ✅  INSERT: c356d985-1625-4ce4-93e6-8f949c9196ba
I/TSLocationManager(18628): [c.t.l.http.HttpService flush] 
I/TSLocationManager(18628): ╔═════════════════════════════════════════════
I/TSLocationManager(18628): ║ HTTP Service (count: 1)
I/TSLocationManager(18628): ╠═════════════════════════════════════════════
I/TSLocationManager(18628): [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 5
D/TSLocationManager(18628): [c.t.l.d.s.SQLiteLocationDAO first] 
D/TSLocationManager(18628):   ✅  Locked 1 records
I/TSLocationManager(18628): [c.t.l.http.HttpService a] 
I/TSLocationManager(18628):   🔵  HTTP POST: c356d985-1625-4ce4-93e6-8f949c9196ba
I/TSLocationManager(18628): [c.t.l.http.HttpService$f onResponse] 
I/TSLocationManager(18628):   🔵  Response: 201
D/TSLocationManager(18628): [c.t.l.d.s.SQLiteLocationDAO destroy] 
D/TSLocationManager(18628):   ✅  DESTROY: c356d985-1625-4ce4-93e6-8f949c9196ba
```

</details>

**Comment by christocracy** [comment]
> How to disable data deletion after successful sending to the server?

You can’t.  The plug-in desires an empty database.  If you want the location in a database, it’s up to you to implement your own SQLite database.
