### ISSUE TITLE
Found Duplicate Location But Odometer was changed

### ISSUE THREAD

**Issue by jaotct** [transistorsoft/flutter_background_geolocation#1319]
Hello,

Previously, I had reported this issue, and it still persists. On some mobile phones, we have observed that the location data and timestamps are being sent repeatedly to the server. All the data is identical except for the odometer, UUID, age, and battery level.

As shown in the image, the data is being sent at two different times. On the left, it was sent at the server time 2024-06-26 00:22:24.754327 with a total of 805 records. On the right, it was sent at the server time 2024-06-26 05:40:55.013089 with a total of 843 records.

However, notice that the odometer value on the right continues from the last record on the left, even though the timestamp overlaps with the first record. This discrepancy prevents me from accurately calculating the distance.

I'm not sure if the development team has any suggestions or comments on this matter. In my opinion, if the timestamps are the same, the odometer reading should be the same as well. This is just one case, but there are many similar cases. Currently, we have around 1,000 users using the app, and about 10-20 users are experiencing this issue. For those users, the issue recurs frequently, and it appears to be happening only on Android devices. We have not encountered this issue on iOS.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/d48b04b2-5444-442b-98d6-d923b4eb4aaa)
![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/2f734c6a-b7d6-49f9-891e-269a6b75efe2)

## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version:  11 (API Level 30)
* Device manufacturer / model:   OPPO CPH2059(OPPO A92)
* Flutter info (`flutter doctor`):
* 
[!] Flutter (Channel stable, 3.13.8, on macOS 14.1.1 23B81 darwin-arm64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
   final extra = {
      "clientID": clientID!,
      "employeeID": license!.employee!.employeeID,
      "appVersion": info.version,
      'deviceInfo': Platform.isAndroid
          ? {
              'band': androidInfo?.brand,
              'model': androidInfo?.model,
              'version': androidInfo?.version.sdkInt.toString(),
              'os': 'Android'
            }
          : {
              'band': 'Apple',
              'model': iosInfo?.utsname.machine,
              'version': iosInfo?.systemVersion,
              'os': 'iOS'
            }
    };

bg.Config(
        reset: true,
        batchSync: true,
        scheduleUseAlarmManager: true,
        foregroundService: true,
        isMoving: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        debug: false,
        autoSync: true,
        autoSyncThreshold: 5,
        url: ApiCall.writeEventLog,
        extras: extra,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        logLevel: bg.Config.LOG_LEVEL_ERROR,
        distanceFilter: 300,
        desiredOdometerAccuracy: 80,
        disableStopDetection: true,
        minimumActivityRecognitionConfidence: 25,
        triggerActivities: 'in_vehicle, on_bicycle, on_foot, running, walking',
        disableElasticity: true)

## Expected Behavior
<!--- Tell us what should happen -->

## Actual Behavior
<!--- Tell us what happens instead -->

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version: 4.9.0

Why are you using a version from a year and a half ago?

**Comment by jaotct** [comment]
you mean this issue was fixed in lastest version ?

**Comment by christocracy** [comment]
I have no idea what your issue is.  I’m just pointing out the obvious:  you’re using an old version.

**Comment by jaotct** [comment]
After updating to version 4.15.5, we are still encountering the same issue. As shown in the left image, data was sent at 2024-06-27 14:10:32.574091 with 5 records, while the right image shows data sent at 2024-06-27 14:25:26.759963 with 350 records. We found that the first record on the left is from 2024-06-27 10:37:20.429, but the odometer reading is the same as the last record on the right, which is 14588224 at 2024-06-27 14:10:30.257. These should not be the same since, according to the database, the odometer reading at 2024-06-27 10:37:20 should be 14480467, as shown in the third image. The third image contains correct and real-time data.

This issue appears on another model of the phone, and it occurs on several models, not all. I use the age value greater than 10000 and the number of records exceeding the set batch limit of 5 records to filter the data. If you need more data samples, please provide additional guidelines on configuring data collection to facilitate resolving this issue. I am willing to cooperate fully as I am unsure of the users' behavior and it is challenging to communicate directly with them. The application is in production, and our team’s devices do not encounter this issue, yet some users do.

thank you


![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/7b1e95b8-cb74-476a-a49d-2c036f10d012)

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/8555072e-2759-4e93-b5c8-f762f0ff784b)


![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/a717a3f6-7d56-400a-ad66-d7469d1a4725)

**Comment by christocracy** [comment]
You’ve not posted any code of what you’re doing with the plug-in.

**Comment by jaotct** [comment]
My application does not perform any complex operations related to the plug-in. It is used simply to send the location data back based on the configured conditions when the user starts tracking their position. When the user stops tracking, the process is cancelled.

I'm not sure which part of the code to show because there is code that is not related to the plug-in as well. However, as mentioned before, the operation works correctly for most of the users, around 1,000 users. Only 10-20 users are experiencing the issue, even though the operation is the same.

I would like to explain with accompanying images as follows:
The user presses the start trip button to start the operation of the plug-in to continuously track the position.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/72148a61-0016-4722-8669-f0512ee4e5aa)


This is the code after pressing Start Trip at line 1457.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/38554257-7bbc-4c35-aff9-8686c360bec3)

After that, the user records their activities in the app, which is not related to the plug-in. Once the work is done, the user presses End Trip to end the task.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/a36d1ce2-e8be-42a0-9515-74d2a48baae9)


This is the code after pressing End Trip at line 1578.

![image](https://github.com/transistorsoft/flutter_background_geolocation/assets/12022160/2ea93c84-32df-4afa-a4d1-199e199da886)


Points I have observed and reported:

1. Every time the issue occurs, the number of locations sent per request is significantly high, even though the autoSyncThreshold is set to just 5.
2. Whenever the issue happens, the age value is very high.
3. The plug-in sends back duplicate values repeatedly, causing the odometer readings to overlap continuously. This leads to incorrect distance calculations from Start Trip to End Trip. Sometimes, it sends duplicates up to 6 times, indicating a travel distance of 70 km but reporting odometer readings suggesting 300-400 km.
4. As mentioned, currently, the issue is observed in approximately 10-20 users, all on Android. No issues have been reported on iOS. Once a device encounters the issue, it tends to persist. I have had to write additional code to correct the odometer values in the database.
I'm not sure if this description will be helpful in resolving your issue. If you need further guidance, please let me know. 

Thank you very much.
