### ISSUE TITLE
Activity type is "STILL" but is_movig: true

### ISSUE THREAD

**Issue by LallaSEBA** [transistorsoft/flutter_background_geolocation#1323]
## Your Environment
* Plugin version: ^4.15.1
* Platform: both iOS and Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
static bg.Notification? locationNotification = bg.Notification(
      sticky: false,
      smallIcon: "mipmap/launcher_icon",
      largeIcon: "mipmap/launcher_icon",
      color: "#F68637",
      text: Lang.instance?.tr('LocAppTrck') ?? "التطبيق يستعمل خاصية الموقع");

  ///plugin config, to change have to call bg.BackgroundGeolocation.setConfig(bg.Config(updated params))
  static bg.Config config = bg.Config(
    activityType: bg.Config.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
    allowIdenticalLocations: true, //in case of stop in the same lac
    locationAuthorizationRequest: 'Always',
    disableLocationAuthorizationAlert: true,
    locationAuthorizationAlert: <String, dynamic>{
      'titleWhenNotEnabled': Lang.instance?.tr('LocationServicesOff') ??
          "إذن الموقع ما راهوش مفعّل في الإعدادات",
      'titleWhenOff': Lang.instance?.tr('LocationServicesOff') ??
          "إذن الموقع ما راهوش مفعّل في الإعدادات",
      'instructions': Lang.instance?.tr('locPermission') ??
          "من فضلك فعّل إذن الوصول إلى موقع هذا الجهاز حتى كي إكون التطبيق مغلق",
      'cancelButton': Lang.instance?.tr('cancel') ?? "إلغاء",
      'settingsButton': Lang.instance?.tr('settings') ?? "الإعدادات"
    },
    backgroundPermissionRationale: bg.PermissionRationale(
      title: Lang.instance?.tr('locPermission') ??
          "من فضلك فعّل إذن الوصول إلى موقع هذا الجهاز حتى كي إكون التطبيق مغلق",
      message: Lang.instance?.tr('LocCollectData') ??
          "يجمع هذا التطبيق بيانات الموقع لتتبع التنقل أثناء الكورسات",
      positiveAction: Lang.instance?.tr('LocChangeAlways') ??
          "التغيير إلى 'قيد الاستخدام دائمًا",
      negativeAction: Lang.instance?.tr('cancel') ?? "إلغاء",
    ),
    debug: AppEnvironment.instance().isDevelopment(),
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    logLevel: AppEnvironment.instance().isDevelopment()
        ? bg.Config.LOG_LEVEL_VERBOSE
        : bg.Config.LOG_LEVEL_ERROR,
    disableElasticity: true,
    disableMotionActivityUpdates: true,
    disableStopDetection: true,
    enableHeadless: true, //back
    isMoving: true,
    notification: locationNotification,
    persistMode: bg.Config.PERSIST_MODE_NONE,
    preventSuspend: true,
    pausesLocationUpdatesAutomatically: false,
    showsBackgroundLocationIndicator: true,
    startOnBoot:
        true, //Set true to engage background-tracking after the device reboots.
    stopOnTerminate: false,
    stopOnStationary: false,
    //stopTimeout: 10, //min
    //Time basis tracking for Android
    locationTimeout: 20,

    distanceFilter: 0,
    locationUpdateInterval: Constants.SHORT_TIME_INTERVAL, // min
    fastestLocationUpdateInterval: Constants.SHORT_TIME_INTERVAL, //  min,

    useSignificantChangesOnly: true
  );
```

## Expected Behavior
When the device is not moving I expect to get in location.map is_moving false, and activity type: still

## Actual Behavior
When I checked the server I got the activity type "STILL" In some case is_moving was true and in other is_moving  was false
<img width="867" alt="Capture d’écran 2024-07-08 à 15 45 03" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/76864075/5ac4480e-53a9-48b9-b906-6bebedcd844d">
i got these data from our app in production for both platforms android and iOS

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
07-08 16:16:39.527  6622  6622 W TSLocationManager: [c.t.f.b.BackgroundGeolocationModule ready] 
07-08 16:16:39.527  6622  6622 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
07-08 16:16:39.542  6622  6833 I flutter : [location] - [Location {odometer: 0.0, activity: {confidence: 100, **type: still**}, extras: {}, battery: {level: 0.6, is_charging: true}, **is_moving: true**, timestamp: 2024-07-08T15:13:29.645Z}]
```

</details>

**Comment by christocracy** [comment]
> disableMotionActivityUpdates: true,

You *told* the plug-in to disable the motion api.

**Comment by LallaSEBA** [comment]
Sorry i copied an old configuration, i updated it to true since a while but i'm still receiving is_moving: true while the activity type was still:
`
      disableElasticity: true,
      **disableMotionActivityUpdates: false,**
      disableStopDetection: false,
      stopOnStationary: true,
      enableHeadless: true, //back
      //httpTimeout: 20000,
      isMoving: true,
      /*logMaxDays: 1,
      maxDaysToPersist: 1,*/
      notification: locationNotification,
      preventSuspend: true,
      pausesLocationUpdatesAutomatically: false,
      //reset: false,
      showsBackgroundLocationIndicator: false,
      startOnBoot:
          true, //Set true to engage background-tracking after the device reboots.
      stopOnTerminate: false,
      //stopTimeout: 10, //min
      //Time basis tracking for Android
      locationTimeout: 20,

      ///settings.locationInterval,
      distanceFilter: 0,
      locationUpdateInterval: Constants.SHORT_TIME_INTERVAL, // min
      fastestLocationUpdateInterval: Constants.SHORT_TIME_INTERVAL, //  min,

      useSignificantChangesOnly: true,
      );`

**Comment by christocracy** [comment]
Please learn to syntax highlight codeblocks.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by LallaSEBA** [comment]
updated @christocracy can you check it again

**Comment by christocracy** [comment]
That’s a very weird config you have.  Do you realize most of those Config options are ignored with `useSignificantChangesOnly: true`?

> stopOnStationary: true

this is ignored but do you realize what this option would do?  “Is means `.stop()` on stationary”

as for motion api, it’s completely handled by the OS.  There’s nothing the plug-in can do to improve results.  The Motion API is either ON or OFF.  That’s it.

I suggest you analyze your app’s real time logs while shaking your device vigorously to simulate movement.  Do so after calling .changePace(true) upon the plug-in (to manually enter the moving state).

**Comment by christocracy** [comment]
With useSignificantChangesOnly: true, the following options are **ignored** (you can delete them from your Config):  I suggest you read the api docs very carefully.  You’re just throwing random darts.

```
disableElasticity: true,
      disableStopDetection: false,
      stopOnStationary: true,,
      isMoving: true,
      pausesLocationUpdatesAutomatically: false,
      showsBackgroundLocationIndicator: false,
      startOnBoot: true, 
      stopOnTerminate: false,
      distanceFilter: 0,
      locationUpdateInterval: Constants.SHORT_TIME_INTERVAL,
      fastestLocationUpdateInterval: Constants.SHORT_TIME_INTERVAL,
```

**Comment by giandifra** [comment]
Hey @LallaSEBA, have you found some other info? I'm trying the playConsole demo app and I have a track where` isMoving = true` but the activity is still 100% (really i was on bicycle)! @christocracy 
![Screenshot 2024-07-19 alle 11 20 47](https://github.com/user-attachments/assets/5550d407-806b-4338-b5f5-75e316cf2746)


Thanks in advance

**Comment by christocracy** [comment]
It all depends upon the quality of the device and the sensors on it (accelerometer, gyroscope, magnetometer).  There’s nothing the plug-in can do.

**Comment by LallaSEBA** [comment]
@giandifra no i didn't i'm still having the same issue with several users,
@christocracy so the exact information that we can rely on is is_moving:true, but the activity type can be not exact, right?, is there a awy to to get confidence less than 100%

**Comment by christocracy** [comment]
> is there a way to to get confidence less than 100%

No.

**Comment by LallaSEBA** [comment]
Thank you for the response @christocracy, can you confirm that the is_moving is an exact data or even is_moving can be affected by the device quality

**Comment by christocracy** [comment]
The plug-in uses a geofence around the last know position as a backup mechanism, the exit of which determines that the device `is_moving: true`
