### ISSUE TITLE
google has rejected our app, due to "health features"

### ISSUE THREAD

**Issue by allenbrunson** [transistorsoft/flutter_background_geolocation#1324]
## Your Environment
* Plugin version: 4.15.5
* Platform: Android
* OS version: any
* Device manufacturer / model: all
* Flutter info (`flutter doctor`):
``` 
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

google should accept the new version of our app.

## Actual Behavior

google does not accept the new version of our app.

## Steps to Reproduce

1. add the flutter_background_geolocation to your app
2. google rejects your app, because it is now a "health app"
3.
4.

## Context

upload a new binary to the google play store

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
[!] Google Api Error: Invalid request - You must let us know whether your app includes any health features.
```

</details>

when i tried to upload a new version of our app to the google play store, i get this error:

[!] Google Api Error: Invalid request - You must let us know whether your app includes any health features.

because the flutter_background_geolocation plugin uses the android.permission.ACTIVITY_RECOGNITION permission, google has now classified ours as a "health app." and since we are now a "health app," google insists that we declare what "health app" features we offer.

we get a whole lot of checkboxes we can select, for things like "activity and fitness," "period tracking," "sleep management," and so on. the only thing that is even remotely plausible is the "other" checkbox. obviously, none of these apply to us. ours is not a health app! if i check ANY of these boxes, i will be LYING, and google is likely to throw our app out of the store.

i have never liked that this plugin requests physical activity. the user sees a permission prompt for this, every time they install the app. we don't need this information! the fact that we are requesting it anyway makes our company look creepy. and now, google is outright rejecting our app because of it.

please, for god's sake, give us a version of this plugin that does not request the physical activity permission. this should have been made optional years ago.

**Comment by maciejbrzezinski** [comment]
It's already done: https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/disableMotionActivityUpdates.html

**Comment by christocracy** [comment]
Do you even know why the plug-in uses the Motion API?  Read the wiki here “Philosophy of Operation”. 

Also see my blog:  https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a

**Comment by christocracy** [comment]
Did you even *read* my blog?

**Comment by Charlemagnes** [comment]
Hey, @allenbrunson, Chris has shown a possible solution to your issue here https://github.com/transistorsoft/flutter_background_geolocation/issues/1324#issuecomment-2217448710
I suggest you read his blog entry. I will try it soon to see if it works as desired. 
Also, @christocracy, I don't know if this is mentioned anywhere in the Readme of the package, but it would be great to mention that it background-geolocation SDK automatically inserts these permissions into the app's `AndroidManifest.xml` file 👍

**Comment by allenbrunson** [comment]
okay, yeah, i guess that works. i will try it.

**Comment by allenbrunson** [comment]
trying workaround
