### ISSUE TITLE
Blank screen after resuming from headless mode on Android 12, 13 and 14

### ISSUE THREAD

**Issue by rairongf** [transistorsoft/flutter_background_geolocation#1326]
## Your Environment
* Plugin version: ^4.15.5
* Platform: Android
* OS version: 12, 13 and 14
* Device manufacturer / model: Pixel, Pixel 2 and Pixel 7 (Android Studio Emulators)
* Flutter info (`flutter doctor`): 
<details>
<summary>`flutter doctor -v` output</summary>
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [versÆo 10.0.22631.3880], locale pt-BR)
    • Flutter version 3.19.6 on channel stable at C:\Users\*\fvm\versions\3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\*\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\b2ml\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (2 available)
    • ***
    • Windows (desktop) • windows      • windows-x64   • Microsoft Windows [versÆo 10.0.22631.3880]

[√] Network resources
    • All expected network resources are available.

• No issues found!
</details>

* Plugin config:
```dart
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: false,
      desiredOdometerAccuracy: 10,
      logMaxDays: 0,
      motionTriggerDelay: 2000,
      persistMode: bg.Config.PERSIST_MODE_LOCATION,
      isMoving: true,
      showsBackgroundLocationIndicator: true,
      debug: kDebugMode,
      logLevel:
          kDebugMode ? bg.Config.LOG_LEVEL_VERBOSE : bg.Config.LOG_LEVEL_ERROR,
    ));
```

## Expected Behavior

App successfully resumes UI while mantaining geolocation tracking from headless mode.

## Actual Behavior

App becomes unusable due to a blank screen when opening right after starting headless mode.

**Identified using Android Emulators with versions 12, 13 and 14.**

## Steps to Reproduce

Minimal reproducible code available at this [Gist](https://gist.github.com/rairongf/be800ec402d378890176eeafc869444e).

1. `bg.BackgroundGeolocation.start()`
2. terminate app
3. wait for at least the first headless location event
4. open app

## Context

Resume location tracking from headless mode so the user can finish tracking by pressing a button that calls `bg.BackgroundGeolocation.stop()`.

## Debug logs

`adb logcat *:S TSLocationManager:V flutter:V` output available in attached file below.

## Attached files

[adb_logcat_output.txt](https://github.com/user-attachments/files/16254237/adb_logcat_output.txt)

**Comment by christocracy** [comment]
I suggest you try to reproduce this with the /example app in this repo.  I'm on vacation until July 26.

**Comment by rairongf** [comment]
I encountered the same problem when running the /example application.

**Comment by kaciula** [comment]
@rairongf How exactly are you running the example app? What changes did you make to the example app to reproduce the issue? Please give as much step-by-step details as possible.

**Comment by christocracy** [comment]
I will test this next week when I return from vacation.

**Comment by rairongf** [comment]
I was able to test the behavior on two physical devices with Android version 14 today. It was not possible to reproduce the problem on these devices.

This may indicate that the problem described only occurs in simulators, but further research would be valuable.

**Comment by christocracy** [comment]
I am unable to reproduce this issue on my test devices.
- Google Pixel 6 @ 14
- Samsung Galaxy S20 FE @ 13
- Google Pixel 3a @ 12
