### ISSUE TITLE
[help] can we simulate routes for emulators ?

### ISSUE THREAD

**Issue by Alvish0407** [transistorsoft/flutter_background_geolocation#1327]
I'm trying to simulate routes in emulator, but doesn't seem to be working. Or am i doing anything wrong here ? I have to manually change the pace `bg.BackgroundGeolocation.changePace()` to get the live location.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a8a9984f-0966-4adb-97f9-33d55a70f1ea">

**Comment by christocracy** [comment]
That’s right, as documented in the wiki “Debugging”.  The simulator fails to detect when the device is moving.  You cannot experience the true behaviour of this plug-in in the emulator.  It’s best to test on a real device with real movement.
