### ISSUE TITLE
stopTimeout not working in example app

### ISSUE THREAD

**Issue by Alvish0407** [transistorsoft/flutter_background_geolocation#1328]
## Your Environment
* Plugin version: 4.15.5
* Platform: iOS Simulator
* OS version: 17.5
* Device manufacturer / model: 15 Pro Max
* Flutter info (`flutter doctor`): 
```shell
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Example App
```

## Expected Behavior
- stopTimeout says When in the moving state, specifies the number of minutes to wait before turning off location-services and transitioning to stationary state after the ActivityRecognition System detects the device is STILL.
- But location-services is not turning off as well as stationary state is also not changing to.

## Actual Behavior
- Location service is on and the state is stuck to `unknown`

## Steps to Reproduce

1. run advance version of example app in simulator
2. toggle location service switch on
3. Simulate location to `Freeway Drive` and keep it more 1 minute
4. Simulate location to `None` and wait for 5+ minutes

## Context
Change mode to `stationary` if `stopTimeout` elapsed

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
flutter: [location] - [Location {uuid: E8C7E55C-EE3B-4C6B-857C-AFE0D6029817, odometer: 1166.8, extras: {}, mock: true, age: 7, timestamp: 2024-07-20T13:28:28.451Z, battery: {level: -1.0, is_charging: false}, coords: {speed_accuracy: 0.0, speed: 32.3, longitude: -122.04149924, ellipsoidal_altitude: 0.0, floor: 0, heading_accuracy: 0.0, latitude: 37.3344499, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 269.3}, is_moving: true, activity: {type: unknown, confidence: 100}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {uuid: 636B7054-E7D4-4C19-9FD4-C9100BE49B9E, odometer: 1268.9, extras: {}, mock: true, age: 8, timestamp: 2024-07-20T13:28:31.468Z, battery: {level: -1.0, is_charging: false}, coords: {speed_accuracy: 0.0, speed: 33.87, longitude: -122.04265083, ellipsoidal_altitude: 0.0, floor: 0, heading_accuracy: 0.0, latitude: 37.33444952, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 270.0}, is_moving: true, activity: {type: unknown, confidence: 100}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
⚠️-[TSLocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=0 "(null)"
flutter: [BackgroundGeolocation onLocation] ‼️ Unhandled location error: [LocationError code: 0, message: LOCATION_ERROR].
You should provide a failure callback as 2nd argument to BackgroundGeolocation.onLocation.
Eg:  BackgroundGeolocation.onLocation(_onLocation, (LocationError error) {
	// Handle LocationError here.
	print("[onLocation] ERROR: $error");
});
flutter: [location] ERROR - [LocationError code: 0, message: LOCATION_ERROR]
```
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/adfde2a8-961f-4eb6-acc9-119c535ecf28">
<img height="600" alt="image" src="https://github.com/user-attachments/assets/c9f31c04-3275-4222-a5b1-b042d98ff783">

</details>

**Comment by christocracy** [comment]
stopTimeout doesn’t work in the iOS simulator since the simulator doesn’t have an accelerometer or gyroscope.  You can only test stopTimeout on a real device.
