### ISSUE TITLE
Unable to send data to server even though getting all locations in logs.

### ISSUE THREAD

**Issue by nvamsi214** [transistorsoft/flutter_background_geolocation#133]
## Your Environment
* Plugin version:^1.2.4
* Platform:Android
* OS version: Oreo (8.1.0) 
* Device manufacturer / model: samsung SM-J710F
* Flutter info (`flutter doctor`):Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN;
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: desiredAccuracy,
      distanceFilter: distanceFilter,
      stopOnTerminate: false,
      startOnBoot: true,
      //url : "https://us-central1-taskcaretest2.cloudfunctions.net/orders/saveData/${UID}",
      debug: enableDebug,
      enableHeadless: enableHeadless,
      reset: true,
      autoSync: true,
      batchSync: true,
      logLevel: enableDebug? 5 : null,
      foregroundService: true,
      heartbeatInterval: heartbeatInterval,
      extras: {
        'oid': OID,
        'uid': UID
      },
    triggerActivities: "in_vehicle,on_bicycle,on_foot,running,walking",
      locationUpdateInterval: locationUpdateInterval,
      fastestLocationUpdateInterval:  fastestLocationUpdateInterval,
  )).then((bg.State state) {
    if(isStart == true) {
      if(resetOdo){
        bg.BackgroundGeolocation.setOdometer(0.0);
      }
      if (state.enabled == false) {
        _onClickEnable(true, isOverlay);
      }
    } else {
      _onClickEnable(false, isOverlay);
    }
  });
```

## Expected Behaviour

Service should be running in background (app in background / terminated) and after getting event call back for new location (on Location change or on Motion change), the new location should be sent to Firebase.

## Actual Behaviour

Service is running in background and all the new locations are getting recorded in logs too (Debug mode). But the data is not updating in firebase. This is a random behaviour happened thrice for this user in last 1 week. The same user's data is perfectly updated for today again with no changes.

## Steps to Reproduce

1. Random behaviour. One of observed situation  is that the user was travelling while punching in (initiating the background service).

## Context

Update locations to firebase when there is a Motion/Location Change and on Heart Beat to track the user movement. Background service should run in all cases (app in background or terminated).

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Debug Logs :
[locations.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/3738755/locations.txt)

```

</details>

**Comment by christocracy** [comment]
Show me your code you’re using to insert location to Firebase.  I see you’re not using the plugin #url.

**Comment by nvamsi214** [comment]
bg.BackgroundGeolocation.onLocation((bg.Location location) {
    saveOldDetails(location.odometer);
    String oid = location.extras.containsKey("oid") ? location.extras["oid"] : null;
    String uid = location.extras.containsKey("uid") ? location.extras["uid"] : null;
    if(/*(location.activity.type != 'still') &&*/ location.coords.accuracy < 50) {

      Map<String, dynamic> userTrack = new Map();

      userTrack["UID"] = uid;
      userTrack["OID"] = oid;
      userTrack["latlng"] = GeoPoint(location.coords.latitude, location.coords.longitude);
      userTrack["accuracy"] = location.coords.accuracy;
      userTrack["otherData"] = location.toMap();
      userTrack["event"] = "locationChange";

      final collRef = Firestore.instance.collection('orgs').document(OID)
          .collection("locs");
      DocumentReference docReferance = collRef.document(UID)
          .collection("xyzzz")
          .document();
      var batch = Firestore.instance.batch();
      batch.setData(docReferance, userTrack);
      batch.commit();
    }
  });

**Comment by nvamsi214** [comment]
We are not using the URL plugin.

**Comment by christocracy** [comment]
You’re not interested in the plugin’s Firebase adapter?

**Comment by nvamsi214** [comment]
We have some issue in using Firebase Adapter while updating the locations to particular path. And also we don't want to rely on cloud functions.

**Comment by christocracy** [comment]
See docs: BackgroundGeolocation.startBackgroundTask.  Put your Firebase within that.

**Comment by nvamsi214** [comment]
bg.BackgroundGeolocation.startBackgroundTask().then((va){
        String oid = location.extras.containsKey("oid") ? location.extras["oid"] : null;
        String uid = location.extras.containsKey("uid") ? location.extras["uid"] : null;
        if(location.coords.accuracy < 50) {

        Map<String, dynamic> userTrack = new Map();

        userTrack["UID"] = uid;
        userTrack["OID"] = oid;
        userTrack["latlng"] = GeoPoint(location.coords.latitude, location.coords.longitude);
        userTrack["accuracy"] = location.coords.accuracy;
        userTrack["otherData"] = location.toMap();
        userTrack["event"] = "locationChange";

        final collRef = Firestore.instance.collection('orgs').document(OID)
            .collection("locs");
        DocumentReference docReferance = collRef.document(UID)
            .collection("xyzzz")
            .document();
        var batch = Firestore.instance.batch();
        batch.setData(docReferance, userTrack);
        batch.commit();
        }
      });

**Comment by nvamsi214** [comment]
Should we send locations this way?

**Comment by nvamsi214** [comment]
Is there any other issue in above logs for not sending locations to firebase. Because this is not happening every time. Its happening very randomly few time.

**Comment by christocracy** [comment]
Please use syntax highlighting.  you surround your code with 3 backticks + optional language:

```dart
bool foo = false;
```
![](https://www.dropbox.com/s/90i35raq8towg3l/Screenshot%202019-10-17%2007.45.04.png?dl=1)

>Should we send locations this way?

Read the docs again and pay **close** attention to what it says about calling the `#finish` method.

**Comment by nvamsi214** [comment]
Yes, calling **StopBackgroundTask()** with the task ID after updating data to firebase.
