### ISSUE TITLE
registerHeadlessTask work on ios ?

### ISSUE THREAD

**Issue by AbdullahAhmed1991998** [transistorsoft/flutter_background_geolocation#1332]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> registerHeadlessTask work on ios ?

The api docs clearly state the “headless mode” is an Android-only mechanism.  Are you reading the api docs?

iOS has no such concept of “headless”.
