### ISSUE TITLE
Why haven't you uploaded the demo application to the Apple Store? Will it work in the case of terminate state or not in ios?

### ISSUE THREAD

**Issue by AbdullahAhmed1991998** [transistorsoft/flutter_background_geolocation#1333]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by AbdullahAhmed1991998** [comment]
I tried it and it worked on Android in all cases, and on iOS it worked in the foreground and background only, in Terminate it did not work. What function do I need to write in order for it to work on iOS and the application is closed?

**Comment by christocracy** [comment]
Did you carefully read the api docs Config.stopOnTerminate?

**Comment by AbdullahAhmed1991998** [comment]
yes you can send me the function do that please?
