### ISSUE TITLE
Could not resolve com.transistorsoft:tsbackgroundfetch:+.

### ISSUE THREAD

**Issue by Manoj-Madushantha** [transistorsoft/flutter_background_geolocation#1334]
## Your Environment
* Plugin version: ^4.15.5
* Platform: Android
* OS version: Android 8.1 (Oreo)
* Device manufacturer / model: lge/falcon_lgu_kr/falcon:8.1.0
* Flutter info (`flutter doctor`): flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.86.1)
[√] Connected device (4 available)
[√] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.transistorsoft.com/repository/maven-public/'
        }
    }
}
```

## Expected Behavior

Code should compile and successfully build apk files.
## Actual Behavior

What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://maven.transistorsoft.com/repository/maven-public/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.

## Steps to Reproduce

1.
2.
3.
4.

## Context

this is pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  location: ^6.0.2
  http: ^1.2.1
  workmanager: ^0.5.2
  geolocator: ^12.0.0
  provider: ^6.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.15
  flutter_background_geolocation: ^4.15.5

flutter clean
flutter pub get
flutter run

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://maven.transistorsoft.com/repository/maven-public/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://maven.transistorsoft.com/repository/maven-public/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.   
               > maven.transistorsoft.com
   > Could not resolve com.transistorsoft:tslocationmanager:+.
     Required by:
         project :app > project :flutter_background_geolocation
      > Failed to list versions for com.transistorsoft:tslocationmanager.
         > Unable to load Maven meta-data from https://maven.transistorsoft.com/repository/maven-public/com/transistorsoft/tslocationmanager/maven-metadata.xml.
            > Could not GET 'https://maven.transistorsoft.com/repository/maven-public/com/transistorsoft/tslocationmanager/maven-metadata.xml'.   
               > maven.transistorsoft.com
```

</details>

**Comment by Andres-98** [comment]
Hello. I'm experiencing the same issue, could you tell me how you solved it?

**Comment by christocracy** [comment]
This is always caused by not very carefully following the detailed Setup Instructions.
