### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#1335]
## Your Environment
* Plugin version: 4.15.5
* Platform: Android
* OS version: 13
* Device manufacturer / model: Fairphone4
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22621.3880], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (11 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.23)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)  • windows            • windows-x64    • Microsoft Windows [Version 10.0.22621.3880]
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 121.0.6167.162
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: aggressive ? 0.0 : 5.0,
      locationUpdateInterval: aggressive ? 1000 : null,
      disableElasticity: false,
      elasticityMultiplier: 1.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: 60 * 24 * 5, // 5 days
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      showsBackgroundLocationIndicator: true,
      foregroundService: true,
      locationAuthorizationRequest: 'WhenInUse', //Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize
                  .dlgBackgroundLocationPermissionTitle('{applicationName}'),
              message: localize.dlgBackgroundLocationPermissionContent(
                  '{backgroundPermissionOptionLabel}'),
              positiveAction: localize.dlgBackgroundLocationPermissionAction1(
                  '{backgroundPermissionOptionLabel}'),
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );

```

## Expected Behavior
Exception handled

## Actual Behavior
          Caused by java.lang.NumberFormatException: For input string: "∞"
       at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
       at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
       at java.lang.Double.parseDouble(Double.java:543)
       at java.lang.Double.valueOf(Double.java:506)
       at com.transistorsoft.locationmanager.location.TSLocation.a(SourceFile:6)
       at com.transistorsoft.locationmanager.location.TSLocation.<init>(SourceFile:2)
       at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation(:14)
       at com.transistorsoft.locationmanager.location.TSLocationManager.onSingleLocationResult(:394)
       at com.transistorsoft.locationmanager.location.TSLocationManager$a.onLocation(:13)
       at com.transistorsoft.locationmanager.location.TSLocationManager.a(SourceFile:11)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.transistorsoft.xms.g.utils.Utils.invokeImprecise(:39)
       at com.transistorsoft.xms.g.utils.Utils.invokeMethod(SourceFile:2)
       at com.transistorsoft.xms.g.utils.Utils.invokeMethod(SourceFile:1)
       at com.transistorsoft.xms.g.tasks.OnSuccessListener$1.onSuccess(:15)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.1.0:25)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7924)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

## Steps to Reproduce

1. Unknown
2.
3.
4.

## Context
Unknown

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What kind of bullshit is this "Fairphone" doing?  There is no [`Location`](https://developer.android.com/reference/android/location/Location#getSpeed()) attribute documented to return `Infinity`.

The plugin already guards against invalid data in a variety of ways, using `Double.isNan(value)`, `Float.isNan(value)` and the `.hasXXX()` methods for each attribute, for example:
```java
altitude = (location.hasAltitude() && !Double.isNaN(location.getAltitude())) ? Double.valueOf(twoDForm.format(location.getAltitude())) : -1;
```

What bullshit.  This "Fairphone" decided to ignore all those avenues to signal an invalid value in their custom Android fork to return `Infinity` without returning `false` for the `hasXXX` getter (eg: `location.hasAltitude()`) .

**Comment by ozzy1873** [comment]
This happened 9x only on this phone and for a single user, so I don't think this is a major concern. I just thought it would be good to let you know.
