### ISSUE TITLE
MQTT protocol support

### ISSUE THREAD

**Issue by Miamoto-Musashi** [transistorsoft/flutter_background_geolocation#134]
Would be nice if the framework could support different transmission protocol such as (S)MQTT instead of HTTP(S) which is more light, robust and quick

thank you

**Comment by christocracy** [comment]
It's possible.

**Comment by Miamoto-Musashi** [comment]
you mean it's already possible right now? if so can you point to documentation or better a demo code?
thanks

**Comment by christocracy** [comment]
Sorry, I meanK *it's possible I could look into it.*

**Comment by resfandiari** [comment]
is there any update on this topic after 5 years?
