### ISSUE TITLE
Google Play App Rejected with issue SDK: Huawei com.huawei.hms:update

### ISSUE THREAD

**Issue by LetheGameStudios** [transistorsoft/flutter_background_geolocation#1348]
## Your Environment
* Plugin version: 6.7.1
* Platform: Android, Unity
* Unity version : 2020.3.33f1
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
We removed the Huawei SDK and all codes related to Huawei from our project. We were waiting for Google Play to approve it. However, despite all our efforts, Google Play continued not to approve it for the same reason.

## Actual Behavior
Google Play App Rejected with issue SDK: Huawei com.huawei.hms:update

## Steps to Reproduce

1.
2.
3.
4.

## Context
"Google Play huawei hms update SDK com.huawei.hms:update: If your SDK provider has it, consider upgrading to a policy-compliant version of the SDK or removing the SDK."

It keeps rejecting our game with the error.

The truth is that the Huawei SDK was installed in our game but was never used. Despite completely removing the SDK from our project, we still can't fix the problem.

We keep getting this problem even though we've completely removed all Huawei-related code. We can see Huawei-related codes in analysis programs like Mobsf, but we can't find their locations. We've completely removed all Huawei-related SDKs and codes!

We still can't fix the situation.

Unity version : 2020.3.33f1

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

Unity version : 2020.3.33f1
![Google Play Rejected](https://github.com/user-attachments/assets/4c294c00-04b6-478a-b12e-fa488978b6f3)

**Comment by christocracy** [comment]
> Plugin version:

**Comment by LetheGameStudios** [comment]
> > Plugin version:

I don't understand what you mean exactly. We have already removed Huawei SDK.

We have completely removed the old version that we were using before. After Google Play continued to give Reject, we installed the latest Huawei SDK version again and solved the problem. (Although we do not use anything related to Huawei)

When we experienced this problem again after a while, we first tried to update with the latest Huawei Version. (Released 3-4 days ago) We experienced Build errors.

We want to completely remove the Huawei version now. We are constantly experiencing this problem because of an SDK that we never use.

**Comment by christocracy** [comment]
> Plugin version:

the version **OF THE PLUGIN** you’re using!

**Comment by LetheGameStudios** [comment]
> > Plugin version:
> 
> the version **OF THE PLUGIN** you’re using!

6.7.1

**Comment by christocracy** [comment]
> 6.7.1

That version does *not* exist.

See the CHANGELOG and consult your pubspec.yaml to find out which version of **THIS PLUGIN** you’re using (flutter_background_geolocation).  

It’s not hard.
