### ISSUE TITLE
[Android] getCurrentPosition timeout

### ISSUE THREAD

**Issue by millerf** [transistorsoft/flutter_background_geolocation#1352]
## Your Environment
* Plugin version: lastest
* Platform: Android 
* OS version: 13
* Device manufacturer / model: Oppo
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-ES)
    • Flutter version 3.24.1 on channel stable at /Users/millerf/Documents/repos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/millerf/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/millerf/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.
```
* Plugin config:
```dart

 bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50.0,
        enableHeadless: false,
        stopOnTerminate: false,
        allowIdenticalLocations: false,
        useSignificantChangesOnly: false,
        startOnBoot: true,
        foregroundService: true,
        autoSync: false,
        maxRecordsToPersist: 0,
        debug: settings.test,
        showsBackgroundLocationIndicator: false,
        persistMode: bg.Config.PERSIST_MODE_NONE,
        locationAuthorizationRequest: Platform.isIOS ? 'Always' : 'Any',
        disableLocationAuthorizationAlert: true,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled':
              localizations(context).locationServiceNotEnabledInTheBackground,
          'titleWhenOff': localizations(context).locationServiceOff,
          'instructions': localizations(context).locationServiceOffInstructions,
          'cancelButton': localizations(context).cancel,
          'settingsButton': localizations(context).settings,
        },
        backgroundPermissionRationale: bg.PermissionRationale(
          title: localizations(context).locationPermissionRationaleTitle,
          message: localizations(context).locationPermissionRationaleMessage,
          positiveAction:
              localizations(context).locationPermissionRationalePositiveAction,
          negativeAction: localizations(context).cancel,
        ),
        logLevel: settings.test
            ? bg.Config.LOG_LEVEL_VERBOSE
            : bg.Config.LOG_LEVEL_OFF,
        reset: true);

```

## Steps to Reproduce

1.
2.
3.
4.

## Context
 - I use `bg.BackgroundGeolocation.getCurrentPosition` when no location is available yet.

I notice a discrepancy between iOS and Android, and wanted to bring it to your attention. It might be a misperception on my side.
I default to `getCurrentPosition()` when I am starting my app and the plugin did not return a location yet.
I notice the "issue" because I thought the `timeout` was in milliseconds and used `getCurrentPosition(timeout: 3000)`. And I was not sure why my app seemed stalled.
For some reason it seems the timeout is actually a "timer", and the function does not return a location before the timer runs out: I know removed the 3000 to a 1, and the app works as expected. Also, I did only notice this on Android, and not on iOS, so I was wondering if there might be an issue with the way the timeout is handled...

Anyway, it might be nothing, but I wanted to bring it to your attention: `getCurrentPosition` doesn't seem to return anything before the timeout run out, even if a location is perfectly available...  

Thanks!

**Comment by christocracy** [comment]
> Plugin version: lastest

Please post the exact version.  Consult your pubspec.yaml.

You’re having an issue with .getCurrentPosition but you’ve not posted the code you’re using or the context of when you’re calling it relative to .ready(config).

you must wait for .ready(config) to resolve before calling any method which requests location.

**Comment by millerf** [comment]
> Plugin version

  flutter_background_geolocation: ^4.15.5

> you must wait for .ready(config) to resolve before calling any method which requests location.

Yes, there might be an issue here. I'll have a look later and otherwise post a more detailed code to replicate. Thanks!

**Comment by millerf** [comment]
It seems indeed the issue was `ready()` was not finished to be called. Thanks for your help. 

Closing this.
