### ISSUE TITLE
Package show modal "Background locations is not enabled" when i call  `bg.BackgroundGeolocation.getCurrentPosition`

### ISSUE THREAD

**Issue by KlipX** [transistorsoft/flutter_background_geolocation#1353]
## Your Environment
* Plugin version: 4.16.0
* Platform: iOS 
* OS version: 17.4
* Device manufacturer / model: IPhone 15 plus
* Flutter info (`flutter doctor`):
      Doctor summary (to see all details, run flutter doctor -v):
      [✓] Flutter (Channel stable, 3.24.1, on macOS 14.1.1 23B81 darwin-arm64, locale pl-PL)
      [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
      [✓] Xcode - develop for iOS and macOS (Xcode 15.3)
      [✓] Chrome - develop for the web
      [✓] Android Studio (version 2022.3)
      [✓] VS Code (version 1.90.0)
      [✓] Connected device (6 available)
      [✓] Network resources
      
      • No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      final state = await bg.BackgroundGeolocation.ready(
        bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10,
          disableElasticity: true,
          disableStopDetection: true,
          isMoving: true,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          autoSync: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION,
          maxDaysToPersist: 2,
          stopOnStationary: false,
          activityRecognitionInterval: 1000,
          backgroundPermissionRationale: bg.PermissionRationale(
            title: permissionRationaleTitle,
            message: permissionRationaleDescription,
          ),
          notification: bg.Notification(
            priority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
            sticky: true,
            title: notificationTitle,
            smallIcon: _notificationSmallIcon,
            text: notificationText,
          ),
        ),
      );
```

## Expected Behavior
I can read current user location when app is in foreground without 'Background location is not enabled' modal/popup

## Actual Behavior
When I try to read a single user's current location while the app is in foreground , the app displays the modal/popup “Background location is not enabled”.  
<img width="218" alt="image" src="https://github.com/user-attachments/assets/e697e8da-4e1d-427c-be19-7d2ec279b391">

## Steps to Reproduce

1. call await bg.BackgroundGeolocation.ready with provided above config 
2. call await bg.BackgroundGeolocation.getCurrentPosition() with provided above config 
3. only on iOS you can see modal
<img width="189" alt="image" src="https://github.com/user-attachments/assets/16f09af1-74c3-44d6-a1ab-3dff64778259">

## Context

image 1: 
<img width="184" alt="image" src="https://github.com/user-attachments/assets/20617b45-9f2d-4d37-ab08-655559d1e024">
image 2:
<img width="218" alt="image" src="https://github.com/user-attachments/assets/e697e8da-4e1d-427c-be19-7d2ec279b391">

In my app I have a function where I track the user in the background and it works fine. But now in another scenario I need to read only the current position of the user and when I call bg.BackgroundGeolocation.getCurrentPosition() on iOS the modal “image 2” appears. The modal only appears on iOS. I think this is incorrect behavior, because when we call getCurrentPosition, we do not need background tracking permissions. I think it should be required only when we call bg.BackgroundGeolocation.start (). Is there any way to disable this modal when we call getCurrentPosition and show only for bg.BackgroundGeolocation.start (). Of course, the modal asking for permission (image 1) should be visible in both cases.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationRequest` (the default is `Always`).  There is a lot of information there about this.

**Comment by KlipX** [comment]
its help thanks
