### ISSUE TITLE
Geofence DWELL not triggering event on IOS

### ISSUE THREAD

**Issue by ralon99** [transistorsoft/flutter_background_geolocation#1354]
## Your Environment
* Plugin version: ^4.15.5
* Platform: iOS 17.6.1
* Device manufacturer / model: iphone 15
* Flutter info (`flutter doctor`):
> [✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-IL)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2023.3)
> [✓] Connected device (4 available)
> [✓] Network resources
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      await bg.BackgroundGeolocation.ready(bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 200,
          stationaryRadius: 50,
          geofenceInitialTriggerEntry: false,
          disableMotionActivityUpdates: true,
          persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
          stopOnTerminate: false,
          startOnBoot: true,
          logLevel: bg.Config.LOG_LEVEL_OFF,
          enableHeadless: true,
          locationAuthorizationRequest: 'Always',
          notification: bg.Notification(smallIcon: 'drawable/app_launcher_icon',
              largeIcon: 'drawable/app_launcher_icon')
      ));
      await updateGeofences();
      FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);
```
* event registration:
```
bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) async {
        updateUserGeofenceEvent(event.identifier, event.action);
    });
```
* Geofence creation:
```
bg.Geofence(
        identifier: arena['uid'],
        latitude: geopoint.latitude,
        longitude: geopoint.longitude,
        radius: arena['alertRadius'].toDouble(),
        notifyOnEntry: false,
        notifyOnExit: false,
        notifyOnDwell: true,
        loiteringDelay: loiteringDelay,
      );
```
## Expected Behavior

The onGeofence event should trigger with the delay supplied at the loiteringDelay

## Actual Behavior

On android version the plugin is working as expected though the Headless task mechanism, tested on many devices.
On IOS the event is never triggers when the app is terminated.

## Steps to Reproduce

1.
2.
3.
4.

## Context

On my iphone i can only trigger the event if the phone is connected to the mackbook, if i set the 'geofenceInitialTriggerEntry: ' to 'true' and if i stop and start the service. when the app is installed with the original config and i drive around (much more than the geofence radius) with my phone, it never triggers when getting back inside the geofence.

is there anything wrong or missing in my configuration?

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> On IOS the event is never triggers when the app is terminated.

That’s correct.  iOS dwell events cannot trigger when the app is terminated.

**Comment by ralon99** [comment]
that's very disappointing.. the only need i have from the plugin is geofencing with the dwell option..
will it work as expected with the 'enter' event? even on terminated app?

**Comment by christocracy** [comment]
> will it work as expected with the 'enter' event? even on terminated app?

Terminated:  Enter and exit, yes.  Dwell no

iOS does not *natively* support dwell.  It’s my own custom implementation using timers.  When an iOS app is terminated, your app is completely removed from memory, including the plug-in’s loitering timers.  There is no possible solution to this, ever.

**Comment by ralon99** [comment]
thanks for the quick reply, i'll try to use the 'enter' as workaround in my app logic

**Comment by christocracy** [comment]
If your problem is strictly limited to the terminated case, this issue can be closed.

**Comment by ralon99** [comment]
hi, 
i'm reopening the issue because it doesn't seems to work on the 'Enter' event as well..
same configuration as in top thread description, only the geofence creation was changed to this:
```      
return bg.Geofence(
        identifier: arena['uid'],
        latitude: geopoint.latitude,
        longitude: geopoint.longitude,
        radius: arena['alertRadius'].toDouble(),
        notifyOnEntry: Platform.isIOS,
        notifyOnExit: false,
        notifyOnDwell: Platform.isAndroid,
        loiteringDelay: loiteringDelay,
      );
```
when i set the geofenceInitialTriggerEntry to 'true' and load the application (on first app installation) the trigger of the 'Enter' event is working properly. But, that's about the last trigger that i get.. i took my phone for many rounds in and out the geofence but no trigger occurred. i tried it with terminated app, app in the background and app in the foreground.
the only way i could manage to get a trigger is when restarting the service (either stop-start or installing new instance of the app).
have you encountered such case? any advices?

**Comment by christocracy** [comment]
Configure plug-in with debug: true and your geofence with notifyOnExit (just for testing)

do NOT re-enter the geofence until the exit event fires, which typically takes 100-200 meters movement outside the radius.

**Comment by ralon99** [comment]
am i looking for something in particular or is it just to test the in-out functionality?
in addition, i forgot to mention that i also changed 'persistMode' to 'bg.Config.PERSIST_MODE_NONE' but according to the documentation it shouldn't affect the behavior

**Comment by ralon99** [comment]
i've tried you suggestion. i got both exit (only when i passed about ~400 meters out of the geofence radius) and the entrance debug notifications.
when i went back to the regular code i get no 'Enter' trigger again..
the code i'm using on the trigger is suppose to update Firebase collection with current event name and event time, maybe accessing the DB is the problem? (same function is triggered by the headless event on Android and it's working fine)

**Comment by christocracy** [comment]
> i got both exit (only when i passed about ~400 meters out of the geofence radius) and the entrance debug notifications.

The OS has full responsibility to fire geofence events.  If the event fires your .onGeofence listener, that’s all I care about.  Everything else is your responsibility.
