### ISSUE TITLE
Android android.permission.ACTIVITY_RECOGNITION

### ISSUE THREAD

**Issue by csarigumba** [transistorsoft/flutter_background_geolocation#1355]
Hello,

We have been using the app, and it has been stable so far. However, after releasing a new version for Android yesterday, Android flagged it due to the `android.permission.ACTIVITY_RECOGNITION permission`. Please refer to the attached screenshot.

![image](https://github.com/user-attachments/assets/59d48b14-53ca-4269-b3e1-88aab2fa1532)
![image](https://github.com/user-attachments/assets/f22aa70a-44bc-419e-9c56-33fe714323b6)

Is there a way to resolve this issue? What would be the impact if I simply disable it in the `AndroidManifest` file?

**Comment by christocracy** [comment]
Yes, this is very well known and there are other issues already posted about it.  Please search issues before posting.

see my blog:
https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a
