### ISSUE TITLE
Cannot call event geofence on IOS when app get killed

### ISSUE THREAD

**Issue by J-DreaMy** [transistorsoft/flutter_background_geolocation#136]
## Your Environment
* Plugin version: ^1.2.0
* Platform: iOS
* OS version: 12
* Device manufacturer / model: Iphone 6 
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale id-ID)
 wqe
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.3)
[√] VS Code (version 1.39.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

* On bg_location_service.dart:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
class BackgroundService {
  void initial() async {
    bg.BackgroundGeolocation.onGeofence(onTriggerSchedule);
    bg.BackgroundGeolocation.ready(bg.Config(
      locationAuthorizationRequest: "Always",
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      forceReloadOnGeofence: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      foregroundService: true,
    )).then((bg.State state) async {
      if (!state.enabled) await bg.BackgroundGeolocation.start();
      await bg.BackgroundGeolocation.changePace(true);
    });
  }
```
* On main.dart:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

void headlessTask(bg.HeadlessEvent headlessEvent) async {
  switch (headlessEvent.name) {
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent event = headlessEvent.event;
      print("HEADLESS GEOFENCE TRIGGER (${event.identifier}): ${event.action}");
      FToast.success("BACKGROUND GEOFENCE TRIGGER (${event.identifier}): ${event.action}");
      if (event.action == 'ENTER') {
        Map data = {"idscheduler": event.identifier};
        http.post("$server/scheduler/gps/trigger", body: data);
      }
      break;
  }
}

void main() async {
  final initState = await initialState();
  final Store<AppState> store = Store<AppState>(
    appStateReducer,
    middleware: appStateMiddleware(),
    initialState: initState ?? AppState.init(),
  );
  await defineEnviroment(store);
  defineRoutes(router);
  runApp(MyApp(store: store));
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
  BackgroundService().initial();
}

Future defineEnviroment(store) async {
  if (store.state.settings?.development == false) {
    return await DotEnv().load('production.env');
  }
  await DotEnv().load('debug.env');
}

class MyApp extends StatefulWidget {
  final Store<AppState> store;

  const MyApp({Key key, this.store}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    Messaging().initial(widget.store, context);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: widget.store,
      child: MaterialApp(
        title: 'BLiving',
        theme: ThemeData(
          primaryColor: Colors.white,
          primaryIconTheme: IconThemeData(color: Colors.black),
          fontFamily: 'RedHat',
          textTheme: textTheme,
          inputDecorationTheme: InputDecorationTheme(
            focusedBorder: UnderlineInputBorder(
              borderSide: BorderSide(color: PColors.primaryColor),
            ),
            labelStyle: TextStyle(color: Colors.grey[600]),
          ),
        ),
        home: widget.store.state.user == null ? LoginScreen() : MainScreen(widget.store.state.user.id),
        routes: routes,
        onGenerateRoute: router.generator,
        debugShowCheckedModeBanner: false,
        navigatorKey: NavigatorHolder.navigatorKey,
      ),
    );
  }
}
```

## Expected Behavior
After terminating app from background, IOS / android must trigger geofence event.

## Actual Behavior
Once app is killed, and move away 200 meters it's no popup notification & i think the background location / location service is stopped. (Only on IOS)

## Steps to Reproduce

1.Open app and start background service
2. Login the app for add geofence
3. Kill the app
4. Try to Move at least 200m
5. Geofence not trigger to call http request

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
Have you tested this in the simulator?  `#ready` the plugin for `debug: true`

**Comment by J-DreaMy** [comment]
Yes, I have, using iphone 11 max emulator and ios 13.  The debug notification shows, but the callback function, that i set on **bg.BackgroundGeolocation.onGeofence(onTriggerSchedule)** not triggered. Below the callback function for the geofence event.

```dart 
void onTriggerSchedule(bg.GeofenceEvent event) {
    print("GEOFENCE TRIGGER (${event.identifier}): ${event.action}");
    FToast.info("GEOFENCE TRIGGER (${event.identifier}): ${event.action}");
    if (event.action == 'ENTER') {
      Map data = {"idscheduler": event.identifier};
      http.post("$server/scheduler/gps/trigger", body: data);
    }
  }
```

**Comment by christocracy** [comment]
And where are you listening to #onGeofence?

**Comment by J-DreaMy** [comment]
I run it on **main.dart**, and i call the **BackgroundService class**, that i create it by myself.

**main.dart**
```dart
void main() async {
  final initState = await initialState();
  final Store<AppState> store = Store<AppState>(
    appStateReducer,
    middleware: appStateMiddleware(),
    initialState: initState ?? AppState.init(),
  );
  await defineEnviroment(store);
  defineRoutes(router);
  runApp(MyApp(store: store));
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
  BackgroundService().initial();
}
```


**bg_location_service.dart**
```dart
class BackgroundService {
  void initial() async {
    bg.BackgroundGeolocation.onGeofence(onTriggerSchedule);
```

**Comment by christocracy** [comment]
Move `BackgroundService().initial();` into `MyApp`

**Comment by helipin14** [comment]
We have tested on the iPhone Emulator, that you told us to do, it runs well. But in the real device, it's not working on the background (when app is terminated) and one more, that the Debug Log for geofencing event is not showing.

**Comment by christocracy** [comment]
If it runs well in Simulator but on on real device, then the problem must be the environment.  Make sure you have Wifi enabled.  Test in different areas of your city.

**Comment by helipin14** [comment]
Sorry, we take the device out of the office to test, so it don't have a wifi connection out there, but instead, it have a mobile data connection.

Can you tell us how to solve  this problem?

**Comment by christocracy** [comment]
It doesn’t need to be *connected to* a WiFi network, just don’t disable WiFi in settings.

iOS and Android both rely on passive network geolocation for triggering geofences.
