### ISSUE TITLE
Fetch Current location with odometer and getting 0KM in odometer 

### ISSUE THREAD

**Issue by abhi9991** [transistorsoft/flutter_background_geolocation#1361]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
3.
4.
5.

## Context

we fetching current location on some events and sending that location to our server, and all location are coming without odometer. I want to show odometer also for current location, also i want to do it in a proper way so it will not disturb next location 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you testing outside with real movement on a real device?
