### ISSUE TITLE
Sync early if the batch reaches a certain "age"

### ISSUE THREAD

**Issue by frankvollebregt** [transistorsoft/flutter_background_geolocation#1365]
I searched through the existing issues, but did not manage to find this in there yet.

While running, the plugin records locations just fine (as it is expected to). On the server side, however, we would like to have a location update at least every X (say 5) minutes. So if 5 minutes have passed, and the batch has not filled up yet (maybe the user stood still at a traffic light for a few of these 5 minutes), I would still like to trigger a synchronization action (alternatively I wouldn't mind disabling `autoSync` in favour of a periodic upload, though I'd prefer to have both).

I am aware that I can use a `Future` in Dart, but that sounds like it'll break down really quickly when the app is not running in the foreground.

From what I read in the docs, the `heartbeat` event is for when the device is stationary, so wouldn't work here.

Is there a way to achieve this that I missed in the docs? If not, what would be the recommended way to do this?

## Your Environment
* Plugin version: 4.16.0
* Platform: Android and iOS
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4169], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.94.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
    debug: false,
    logLevel: bg.Config.LOG_LEVEL_INFO,
    stopOnTerminate: false,
    startOnBoot: false,
    batchSync: true,
    // With a location every 4 seconds,
    // this is expected to take about 5 minutes
    autoSync: true,
    autoSyncThreshold: 75,
    httpRootProperty: 'locations',
    maxDaysToPersist: 7,
    logMaxDays: 1,
    // When the apparent movement speed was over 144 km/h, discard the location
    speedJumpFilter: 40,
    // On Android, trigger on vehicle and bicycle activities
    triggerActivities: 'in_vehicle',
    // On iOS (presumably) trigger on automotive locations
    activityType: bg.Config.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
  );

  // When started, I add the authorization, url and autosync true
```

## Expected Behavior
If a given amount of time has passed without the batch size filling up, I would still like to trigger a push to the server

## Actual Behavior
Batches sometimes take quite long to be pushed

**Comment by christocracy** [comment]
You’re free to call .sync() any time you wish.  It will ignore autoSyncThreshold.

you’re free to implement background_fetch (already included as a dependency; see its readme) to periodically call .sync() as desired.

**Comment by frankvollebregt** [comment]
Alright, so I wasn't missing some built-in method. Thank you for the advice!
