### ISSUE TITLE
Alternatives for triggerActivities

### ISSUE THREAD

**Issue by HoseinHaqiqian** [transistorsoft/flutter_background_geolocation#1369]
Is there anyway to make the plugin only listen to `running` and `walking` activities and ignore `on_vehicle` location events?Currently plugin only supports `triggerActivities` for android, is there any other ways to make it work for iOS?

**Comment by HoseinHaqiqian** [comment]
Will the `requestPermissions` function work for getting that permission? or should be done outside of plugin?

**Comment by christocracy** [comment]
The plugin automatically requests *Physical Activity* permission.
