### ISSUE TITLE
disableLocationAuthorizationAlert still shows alert to switch from when in use to always even when set to true

### ISSUE THREAD

**Issue by emmett-deen** [transistorsoft/flutter_background_geolocation#137]
## Your Environment
* Plugin version: 1.3.0
* Platform: iOS
* OS version: 13.0
* Device manufacturer / model: iPhone 11 Pro Max
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        disableLocationAuthorizationAlert: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification: bg.Notification(
          smallIcon: "mipmap/notification_icon",
          largeIcon: "mipmap/notification_icon",
          color: "#5AC8FA"
        ),
        reset: true)
```

## Expected Behavior
When opening the app with location set to 'When In Use' to not get an alert prompting that 'Always' is required

## Actual Behavior
If location is set to anything but 'always' an alert is shown

## Context
Use our own screen to recommend to change to 'always' because the cancel option is not clear to our users that pressing that will continue on to our app.

**Comment by christocracy** [comment]
configure `locationAuthorizationRequst: "ANY"`

**Comment by emmett-deen** [comment]
@christocracy this did not change the result for me

**Comment by christocracy** [comment]
I'll look into this week.

**Comment by emmett-deen** [comment]
@christocracy I got your fix to work, the issue was part because I was not starting the plugin early enough in the lifecycle and "ANY" should be "Any" closing issue.
