### ISSUE TITLE
Issues with Location Tracking Data

### ISSUE THREAD

**Issue by rajnxgn** [transistorsoft/flutter_background_geolocation#1370]
## Your Environment
* Plugin version:   4.15.5
* Platform: iOS or Android: Android 
* OS version: All versions
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
       void startService() async { bg.BackgroundGeolocation.onLocation((bg.Location location) async { print('[onLocationChange] - $location'); }); bg.BackgroundGeolocation.onMotionChange((bg.Location location) { print('[onMotionChange] - $location'); }); bg.BackgroundGeolocation.onActivityChange((bg.ActivityChangeEvent event) { print('[onActivityChange] - $event'); }); bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) { print("[providerchange] - $event"); }); bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) async { print('[onGeofence] - $event'); await onGeofenceStatusChanged(event); }); // bg.BackgroundGeolocation.setOdometer(0.00).then((bg.Location location) { // print('[setOdometer] success: $location'); // }); bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) async { print('[onHeartbeat] - when phone is idle or data ] $event'); }); bg.BackgroundGeolocation.onHttp((bg.HttpEvent event) async { if (event.success) { print("Data sent successfully: $event"); } else { print("Failed to send data: ${event.status} - $event"); } }); final accessToken = await FlutterSecureStore().getSingleValue(Storage.accessToken); final localcheckinid = Storage.readString("checkInID"); String loctaionTrackingUrl = const String.fromEnvironment('LOCATION_TRACKING_URL'); bg.BackgroundGeolocation.ready(bg.Config( desiredOdometerAccuracy: 10, desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH, distanceFilter: 5, // Set distance filter to 10 meters stopTimeout: 10, startOnBoot: true, stopOnTerminate: false, foregroundService: true, showsBackgroundLocationIndicator: true, enableHeadless: true, heartbeatInterval: 60, // 1 minute heartbeat notification: bg.Notification( smallIcon: "drawable/launcher_icon", largeIcon: "drawable/launcher_icon", title: "Location Tracking", text: "Your location is being tracked in the background.", ), locationAuthorizationRequest: 'Always', backgroundPermissionRationale: bg.PermissionRationale( title: "Allow NxGn CRM to access your location even when the app is not in use?", message: "This supports smooth task updates and route planning during field activities.", positiveAction: "Allow all the time", negativeAction: "Cancel"), schedule: [], url: loctaionTrackingUrl, params: { "WorkCheckInID": localcheckinid, }, headers: { 'Authorization': 'Basic $accessToken', 'Content-Type': 'application/json', }, autoSync: true, autoSyncThreshold: 20, batchSync: true, maxBatchSize: 20, maxDaysToPersist: 2, locationsOrderDirection: "ASC", logLevel: bg.Config.LOG_LEVEL_VERBOSE, debug: false, reset: true, )).then((bg.State state) async { if (locations.isNotEmpty && locations.length < 10) { await bg.BackgroundGeolocation.destroyLocations(); } if (locations.length > 10) { print(" Need to think about data when greater that 10 records: "); } if (!state.enabled) { bg.BackgroundGeolocation.start(); } }); } Future<void> stopService() async { bg.BackgroundGeolocation.state.then((bg.State state) async { if (state.enabled) { bg.BackgroundGeolocation.sync().then((List<dynamic> records) { print('Location data synced to server.'); bg.BackgroundGeolocation.destroyLocations().then((each) { print('Location data has been deleted after API call.'); }).catchError((error) { print('Error deleting location data: $error'); }); }).catchError((error) { print('Error during sync: $error'); }); await bg.BackgroundGeolocation.setOdometer(0.00).then((bg.Location location) { print('[setOdometer] success: $location'); }); await bg.BackgroundGeolocation.setConfig(bg.Config( stopOnTerminate: true, startOnBoot: false, enableHeadless: false, autoSync: false, )); await bg.BackgroundGeolocation.stop().then((state) { print("BackgroundGeolocation has been stopped"); }).catchError((error) { print("Error stopping geolocation: $error"); }); await bg.BackgroundGeolocation.removeGeofences().then((state) { print("Geofences removed"); }).catchError((error) { print("Error removing geofences: $error"); }); } else { print('BackgroundGeolocation is stopped.'); } }); }
    

## Steps to Reproduce

1.
2.
3.
4.

## Context
We are encountering critical issues with the location tracking functionality of your plugin, which is impacting the accuracy of location data in our app. The main issues we are facing are as follows:

Intermittent Missing Location Data: Often, after a few hours, the plugin fails to capture location coordinates (latitude and longitude) consistently. When it eventually reconnects, it creates a straight line between two distant points, resulting in inaccurate tracking records.

Initial and Intermediate Location Loss: At times, the plugin does not capture the starting location or intermediate locations during a trip. If the user changes locations during the trip, the plugin either misses updates entirely or registers incorrect locations.

Background Data Retention After Clock-Out: After a user clocks out, the location data continues to be retained in the background rather than clearing. This results in incorrect distance and duration calculations, which is affecting the reliability of our tracking records.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Ignored issue template:

Plugin version:
Platform: iOS or Android
OS version:
Device manufacturer / model:
Flutter info (flutter doctor):
Plugin config:

**Comment by christocracy** [comment]
Also see https://dontkillmyapp.com

**Comment by christocracy** [comment]
See Wiki "Debugging" and learn how to fetch logs from the plugin using `.emailLog` (search the API docs for usage).

**Comment by christocracy** [comment]
>Platform: iOS or Android: Both
>OS version: All versions
>Device manufacturer / model: All Models

*Seriously*?  You've tested this on every Android / iOS model on earth?  What *specific* device are you testing this on?

**Comment by christocracy** [comment]
I suggest you test the `/example` app in this repo on your device.

**Comment by rajnxgn** [comment]
> > Platform: iOS or Android: Both
> > OS version: All versions
> > Device manufacturer / model: All Models
> 
> _Seriously_? You've tested this on every Android / iOS model on earth? What _specific_ device(s) are you testing this on?

Not all devices on earth. I think you  have great humour.

we have tested on main devices like majority used up to 10 brands

**Comment by christocracy** [comment]
See Wiki "Debugging" and learn to fetch logs from the plugin using `.emailLog` (search the API docs for usage).

**Comment by rajnxgn** [comment]
> I took my _iPhone 15 Pro_ and _Pixel 6_ on a trip around France this summer:
> 
> https://www.transistorsoft.com/lab/france
> 
> I field-test almost every day.
> 
> <img alt="Screenshot 2024-10-28 at 9 46 09 AM" width="1127" src="https://private-user-images.githubusercontent.com/14999/380740156-f1781ef1-f280-4ffb-aaa4-f4bc4ef5a2fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjM2MzQsIm5iZiI6MTczMDEyMzMzNCwicGF0aCI6Ii8xNDk5OS8zODA3NDAxNTYtZjE3ODFlZjEtZjI4MC00ZmZiLWFhYTQtZjRiYzRlZjVhMmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDEzNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZGQ3NDc3NWZkZDk5MDJiMDM3ZGVlOTU0MzZlM2M0YjU3MTRlYjRiZTlhMTlkM2IyMzgxMWIwNzAyOWQxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2dAtJEsofKgRXRSuFWVQeKWIfq9Y3OmML7cuzy0tCzw">

I have seen recent comments and they are also addressing same issues. After first locations, sometimes it is not taking continuous coordinates  

Then it taking last coordinates and giving straight line. See the attachment 
![Uploading IMG_5643.jpeg…]()

**Comment by christocracy** [comment]
For Android devices, see https://dontkillmyapp.com

**Comment by rajnxgn** [comment]
> For Android devices, see https://dontkillmyapp.com

Actual problem is:
Sometimes coordinates are getting. If I give full permission to app. And whatever you are sending , it might be applicable on few devices and not all devices I think

**Comment by christocracy** [comment]
>If I give full permission to app

What do you mean by "*full permission*"?

**Comment by rajnxgn** [comment]
> > If I give full permission to app
> 
> What do you mean by "_full permission_"?

Location and activity and disabled battery restrictions and location all times allow

**Comment by rajnxgn** [comment]
![IMG_5643](https://github.com/user-attachments/assets/24958b8e-5c98-4d02-8414-c0d96c1f277c)

**Comment by christocracy** [comment]
If you have problems with a specific field-test, use `.emailLog` to fetch the plugin logs.  Post the log-file here.

**Comment by rajnxgn** [comment]
> > see the straight line and showing route in a river also
> > it is a big joke
> 
> Obviously, if the Android Motion API and geofence around the last known position failed to fire, then you'll see a long straight line between two points.

I think you are not realizing…… this related to script issue.  This is our main issue.

every person posting same issue but you are not recognizing their issues.

**Comment by christocracy** [comment]
> this related to script issue

What is a "script" issue?

> every person posting same issue but you are not recognizing their issues

That's why the website https://dontkillmyapp.com exists.  The problems with the expected behaviour across different Android devices is such a problem, some guy made a website devoted to it.

**Comment by rajnxgn** [comment]
![Screenshot_2024-10-28-23-10-04-196_com nxgntech crm](https://github.com/user-attachments/assets/cb18c81f-07b5-44f8-ab9a-f010e79abe67)

What's wrong with you.. what I am explaining and you are giving wrong clarification. You are deviating issues.  

This is completely script error. And we have checked all other navigation apps. It is showing right direction and coordinates. 

Whatever you are saying  "https://dontkillmyapp.com" applicable to your script only. but all other tracking apps are working perfectly without this "https://dontkillmyapp.com" issues. 

Please come up with. Solutions. Not the argument.
