### ISSUE TITLE
im unable to get location using this method , when i install the apk its give one time location after that its not work, 

### ISSUE THREAD

**Issue by arslancs** [transistorsoft/flutter_background_geolocation#1371]
## Your Environment
* Plugin version: latest
* Platform:  Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`): not issue found
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void _startBackgroundGeolocation() {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      _connectSocketAndEmit(location.coords.latitude.toString(),
          location.coords.longitude.toString());
    });

    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
  }
```

## Expected Behavior

i need to location on after every specific time or interval , 

## Actual Behavior

when i call onLocation method first time on installing the apk it give me location perfectly but after that it failed to give me update
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>I/TSLocationManager(28697): ╟─ 📍  Location[fused 31.493771,74.417442 hAcc=15.043 et=+13d16h29m18s197ms alt=195.10000610351562 vAcc=1.0], time: 1730113515566
I/TSLocationManager(28697): [c.t.l.d.s.SQLiteLocationDAO persist] 
I/TSLocationManager(28697):   ✅  INSERT: d29176f3-7791-4774-baa2-574268285676
D/TSLocationManager(28697): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
D/TSLocationManager(28697):   🎾  Start monitoring stationary region (radius: 150.0m 31.4937708,74.4174417 hAcc=15.043)
I/TSLocationManager(28697): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager(28697):   🔵  Acquired motionchange position, isMoving: false
D/TSLocationManager(28697): [c.t.l.l.TSLocationManager a] Median accuracy: 14.037001
D/TSLocationManager(28697): [c.t.l.service.AbstractService a] 
D/TSLocationManager(28697):   ⚙️︎   FINISH [LocationRequestService startId: 4, eventCount: 0, sticky: false]
I/flutter (28697): Location emitted: Latitude: 31.4937708, Longitude: 74.4174417
I/TSLocationManager(28697): [c.t.l.d.s.SQLiteLocationDAO persist] 
I/TSLocationManager(28697):   ✅  INSERT: f2b0f873-ef90-4a17-b872-d574f1924d82
D/TSLocationManager(28697): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
D/TSLocationManager(28697):   🎾  Start monitoring stationary region (radius: 150.0m 31.4937708,74.4174417 hAcc=15.043)
D/TSLocationManager(28697): [c.t.l.service.AbstractService b] 
D/TSLocationManager(28697):   🎾  STOP [LocationRequestService startId: 6, eventCount: 1]
D/TSLocationManager(28697): [c.t.l.service.AbstractService a] 
D/TSLocationManager(28697):   ⚙️︎   FINISH [LocationRequestService startId: 6, eventCount: 0, sticky: false]
I/flutter (28697): Location emitted: Latitude: 31.4937708, Longitude: 74.4174417
D/TSLocationManager(28697): [c.t.l.service.AbstractService a] 
D/TSLocationManager(28697):   🎾  motionchange [TrackingService  startId: 1, eventCount: 1]
I/TSLocationManager(28697): [c.t.l.service.TrackingService k] 
I/TSLocationManager(28697): ╔═════════════════════════════════════════════
I/TSLocationManager(28697): ║ TrackingService motionchange: false
I/TSLocationManager(28697): ╠═════════════════════════════════════════════
D/TSLocationManager(28697): [c.t.l.service.AbstractService a] 
D/TSLocationManager(28697):   ⚙️︎   FINISH [TrackingService startId: 1, eventCount: 0, sticky: false]
D/TSLocationManager(28697): [c.t.l.service.AbstractService f] 
D/TSLocationManager(28697):   ⚙️︎  LocationRequestService.stopSelfResult(6): true
D/TSLocationManager(28697): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(28697):   🔴  LocationRequestService stopped
D/TSLocationManager(28697): [c.t.l.service.AbstractService f] 
D/TSLocationManager(28697):   ⚙️︎  TrackingService.stopSelfResult(1): true
D/TSLocationManager(28697): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(28697):   🔴  TrackingService stopped</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> its give one time location after that its not work

That’s exactly what this plug-in is designed to do.  Read the wiki “Philosophy of Operation”.

then go outside and move at least 1000 meters.

**Comment by arslancs** [comment]
So there is no method or function that returns the location after some interval whether the user changes his location or not?

**Comment by christocracy** [comment]
No.  That’s what background-fetch is for (already included as a dependency and also created by Transistor Software):

https://github.com/transistorsoft/react-native-background-fetch

**Comment by arslancs** [comment]
okay is there any method to test without buying ? in ios or android ?

**Comment by christocracy** [comment]
This plugin is fully function in DEBUG builds so you can try before you buy, as noted at the top of the [README](https://github.com/transistorsoft/flutter_background_geolocation)

<img width="918" alt="Screenshot 2024-10-28 at 9 29 41 AM" src="https://github.com/user-attachments/assets/005c9ead-4b7f-41d7-837a-a36f2d79e926">

**Comment by arslancs** [comment]
bundle of thanks !

**Comment by arslancs** [comment]
@christocracy  in debug why its showing license validation failed ?

**Comment by christocracy** [comment]
It's normal.  Ignore it.  As long as it's a DEBUG build, it's fully functional.

**Comment by arslancs** [comment]
this is my code ,   im getting location when close the app and open it , but in background im not getting location , but app showing getting location sign in background too! 
void _startBackgroundGeolocation() {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      _connectSocketAndEmit(location.coords.latitude.toString(),
          location.coords.longitude.toString());
    });

    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            disableElasticity: true,
            stopOnTerminate: false,
            enableHeadless: true,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
  }

**Comment by arslancs** [comment]
i need to test before buying it !

**Comment by christocracy** [comment]
> but in background im not getting location

What makes you think that?  Are you observing the plugin logs?  See Wiki "Debugging".  You should be observing the log stream:

```
$ adb logcat *:S TSLocationManager:V
```

The plugin is telling you *everything* it's doing in the logs.

**Comment by christocracy** [comment]
You should be *hearing* debug Sound FX.  If you hear the soundFX, it's working.

**Comment by arslancs** [comment]
what do mean by plugin logs ? im hitting socket on location change method to get bg location updates , bg.BackgroundGeolocation.onLocation((bg.Location location) {
_connectSocketAndEmit(location.coords.latitude.toString(),
location.coords.longitude.toString());
});

**Comment by christocracy** [comment]
>what do mean by plugin logs ?

Ready the Wiki ["Debugging"](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Debugging).  Learn to observe the plugin logs.  This plugin has an incredibly verbose logging system that logs absolutely everything it's doing.

>so bg.BackgroundGeolocation.onLocation method will not perform callback in bg

No, that's **NOT** true.

Are you confused about *background* vs *terminated*?  They are two completely different states.

**Comment by arslancs** [comment]
@christocracy  thanks got it , u mean it ll not work when app is terminated

**Comment by christocracy** [comment]
> u mean it ll not work when app is terminated

No, that's **NOT** what I mean.  Why do you think the plugin contains the option `stopOnTerminate: false`.

>Are you confused about background vs terminated?

Are you talking about the *terminated* **OR** *background* state?

**Comment by arslancs** [comment]
when app is terminated , its bg.BackgroundGeolocation.onLocation callback is not working, then how can i get logs of location when app is terminated ? what ll b use of stopOnTerminate: false etc!

**Comment by arslancs** [comment]
exactly what im saying! bg.BackgroundGeolocation.onLocation will not work when app is terminated!
yes i know ,background and terminated state, thanks for clearing it!

**Comment by arslancs** [comment]
thank you!
