### ISSUE TITLE
Not location detection on IOS when app is killed

### ISSUE THREAD

**Issue by gamestap99** [transistorsoft/flutter_background_geolocation#1373]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version: 17.4.1
* Device manufacturer / model: Iphone 11 Pro Max
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
          reset: true,
          debug: AppConfig.debugBgLocation,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 2.0,
          autoSync: true,
          autoSyncThreshold: 0,
          /// notification: ,
          /// Our desired GPS authorisation
          maxDaysToPersist: 14,
          backgroundPermissionRationale: bg.PermissionRationale(
            title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
            message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel',
          ),
          heartbeatInterval: 60,
          preventSuspend: true,
          showsBackgroundLocationIndicator: true,
          stationaryRadius: 25,
          url: '',
          stopOnTerminate: false,
          startOnBoot: true,
          foregroundService: false,
          enableHeadless: true,
        ));
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
![Uploading z5984877600119_4fdae333b071a02a7d5f2f748fbb951b.jpg…]()

**Comment by christocracy** [comment]
“App” does not “run”?

fix your screenshot

**Comment by gamestap99** [comment]
[
![z5986434380606_2d3d275f3552325c53ea98dcd821b54b](https://github.com/user-attachments/assets/583833b5-9ace-4978-8fdb-5ee83d1dd6ee)
](url)
Os Version

**Comment by gamestap99** [comment]
> [ ![z5986434380606_2d3d275f3552325c53ea98dcd821b54b](https://private-user-images.githubusercontent.com/43195138/382178278-583833b5-9ace-4978-8fdb-5ee83d1dd6ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzMyNTksIm5iZiI6MTczMDQzMjk1OSwicGF0aCI6Ii80MzE5NTEzOC8zODIxNzgyNzgtNTgzODMzYjUtOWFjZS00OTc4LThmZGItNWVlODNkMWRkNmVlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAzNDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYzdhOTgwOTIzYzQxOTZiNjhjZDAzNWVkYjFhNjQ4MDc2NWNjMjZlYzg5NDIyMWYzYzViN2MzZGU5ZTEyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1S11YGE1jxeSCOdJrQrjHc9VZ4pbwG5G_Zrt5YDXUf4) ](url) Os Version

@christocracy Hi, I edited it. This OS has a problem.

**Comment by christocracy** [comment]
See wiki “Debugging” and learn to observe the plug-in’s logs.

**Comment by gamestap99** [comment]
`
PlatformException(CANNOT_SEND_MAIL, null, null, null)
`

- Model name: iphone 11
- OS: ios 17.6.1

`
bg.Logger.emailLog(_emailController.text).then((bool success) {
        print('[emailLog] success');
      }).catchError((error) {
        UtilLoading.showError(content: error.toString());
      });
`
@christocracy hello, i test debug. but have error. pls help me

**Comment by christocracy** [comment]
> CANNOT_SEND_MAIL

.emailLog doesn’t work in the simulator.  It doesn’t have an email client.

**Comment by gamestap99** [comment]
> > CANNOT_SEND_MAIL
> 
> .emailLog doesn’t work in the simulator. It doesn’t have an email client.

@christocracy  I tested on real device

**Comment by christocracy** [comment]
Check your mail app and ensure it’s configured.

**Comment by gamestap99** [comment]
@christocracy How can I listen when the location is saved I want to clone the data because I want to add some properties

**Comment by christocracy** [comment]
> Not location detection on IOS when app is killed

Is this issue resolved?

**Comment by gamestap99** [comment]
@christocracy  I'm still trying to reproduce it to get the better log.
