### ISSUE TITLE
showing error in android release  license validation failure 

### ISSUE THREAD

**Issue by arslancs** [transistorsoft/flutter_background_geolocation#1378]
Plugin version: latest
Platform: Android
OS version:
Device manufacturer / model:
Flutter info (flutter doctor): not issue found
Plugin config:
```

## Expected Behavior

android key must b worked!,
## Actual Behavior
i generate android license key but its showing error in release apk ,  license validation failure ! its working fine in debug!

**Comment by arslancs** [comment]
this is my minifiest , <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="app.meinfahrer">

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/> 



    <application
        tools:replace="android:label"
        android:label="Fahrer"
        android:name="${applicationName}"
        android:icon="@mipmap/launcher_icon">
         
    <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="###" /> 
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

**Comment by arslancs** [comment]
this is my gradle file , 

plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    // END: FlutterFire Configuration
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    namespace = "app.meinfahrer"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId = "app.meinfahrer"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
        
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            shrinkResources false
            minifyEnabled true
            signingConfig = signingConfigs.release
        }
    }
}

flutter {
    source = "../.."
}

**Comment by christocracy** [comment]
Failure to fully implement required Android Setup Instructions.  Go back and *carefully* review Setup Instructions and omit **nothing**. Every step is **required**.

**Comment by christocracy** [comment]
Also pay careful attention to **Caution** messages in the Setup Instructions.

**Comment by arslancs** [comment]
can u figure out exactly what is missed ! im unable to find!

On 2024-11-11 18:23, Chris Scott wrote:

> Also pay careful attention to Caution messages in the Setup 
> Instructions.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/transistorsoft/flutter_background_geolocation/issues/1378#issuecomment-2468170024
[2]

**Comment by christocracy** [comment]
Can’t you just follow [the instructions](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidappbuildgradle) and pay attention to warning messages?
![IMG_2452](https://github.com/user-attachments/assets/beb56263-23e3-4919-a608-756f9f00871f)

**Comment by arslancs** [comment]
okay thanks , let me check !

On 2024-11-11 18:37, Chris Scott wrote:

> Can't you just follow the instructions [1] and pay attention to warning 
> messages?
> IMG_2452.jpeg (view on web) [2]
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidappbuildgradle
[2] 
https://github.com/user-attachments/assets/beb56263-23e3-4919-a608-756f9f00871f
[3] 
https://github.com/transistorsoft/flutter_background_geolocation/issues/1378#issuecomment-2468200692
[4]
