### ISSUE TITLE
Not compiling for Flutter 3.24.*

### ISSUE THREAD

**Issue by WUKS87** [transistorsoft/flutter_background_geolocation#1382]
## Your Environment
* Plugin version: 4.16.4
* Platform: Android
* OS version: Latest
* Device manufacturer / model: /
* Flutter info (`flutter doctor`):
`[✓] Flutter (Channel stable, 3.24.5, on macOS 14.5 23F79 darwin-x64, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources`

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
FAILURE: Build failed with an exception.

* Where:
Script '/Users/admin/.pub-cache/hosted/pub.dev/flutter_background_geolocation-4.16.4/android/background_geolocation.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Could not find method android() for arguments [background_geolocation_bdkha4mgdqhlhrarz1lmujq6h$_run_closure1@341faf54] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

## Expected Behavior
Should compile for Android SDK 34

## Actual Behavior
Not compiling for Android SDK 34

## Steps to Reproduce
1. flutter build apk --flavor dev --debug

**Comment by WUKS87** [comment]
This is my settings gradle (/android/settings.gradle):

`pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
  id "dev.flutter.flutter-plugin-loader" version "1.0.0"
  id "com.android.application" version "7.4.0" apply false
  id "org.jetbrains.kotlin.android" version "1.9.25" apply false
  id "com.google.gms.google-services" version "4.4.0" apply false
  id "com.google.firebase.crashlytics" version "2.9.9" apply false
}

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
`

**Comment by christocracy** [comment]
I suggest you first practice setting up the plug-in in a simple hello world app.

**Comment by WUKS87** [comment]
I've been using the plugin for a while now.

Still it's possible to setup the configuration in old way with Flutter.
The problem was in gradle version and kotlin.

Thank you.
