### ISSUE TITLE
Add polygone gefence error

### ISSUE THREAD

**Issue by ArthurKim19971001** [transistorsoft/flutter_background_geolocation#1389]
## Your Environment
* Plugin version: 4.16.5
* Platform: Android
* OS version: android 12
* Device manufacturer / model: Galaxy s10
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.95.3)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone (9). Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 if (isPolygon) {
        sdkGeofences.add(bg.Geofence(
          identifier: model.id,
          notifyOnEntry: true,
          notifyOnExit: true,
          vertices: vertices,
        ));
      } else {
        sdkGeofences.add(bg.Geofence(
          identifier: model.id,
          radius: circle.radius,
          latitude: circle.center.y,
          longitude: circle.center.x,
          notifyOnEntry: true,
          notifyOnExit: true,
        ));
      }
await bg.BackgroundGeolocation.addGeofences(sdkGeofences);
```

## Expected Behavior
Add the polygon geofence without null error 

## Actual Behavior
Error is occure when try to add ploygone geofence

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Exception has occurred.
PlatformException (PlatformException(Geofence argument error 'de01e686-d7b8-4794-8c92-06c268a2b844': invalid latitude: 174.715729, null, null, null))
```

</details>
Adding circle geofences are well. Only got this error when add ploygone geofencing without lantitude, longitude, radius

**Comment by christocracy** [comment]
What is the specific lat/lng data you’re providing?

**Comment by Arthur19971001** [comment]
> Sorry, what are the _vertices_ you’re providing?

Hi Thank you for replying. I put the value wrong way as [lng, lat] instend to [lat, lng]. My fault sorry.
It was working well. Thank you for creating and maintaining good packages!!

Recommand : The error messages are ambiguous.. hope to get directed error message for future. 👍

**Comment by christocracy** [comment]
> invalid latitude: 174.715729
> The error messages are ambiguous

I’m just echoing back what the native geofence api said.  What more is there to say in this case?

**Comment by ArthurKim19971001** [comment]
> > invalid latitude: 174.715729
> > The error messages are ambiguous
> 
> I’m just echoing back what the native geofence api said. What more is there to say in this case?

I think return to error message as a google map - "Google Maps can't find -73.6049889209514, 200.518947279987714" when try to call the wrong values.
