### ISSUE TITLE
Exception when permission not granted

### ISSUE THREAD

**Issue by jaykobi** [transistorsoft/flutter_background_geolocation#140]
## Your Environment
* Plugin version:1.3.2
* Platform: Android
* OS version: Ubuntu Bionic
* Device manufacturer / model:Xiaomi 9t
* Flutter info (`flutter doctor`): Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale de_DE.UTF-8)

## Expected Behavior
When the user denies permission after caling bg.BackgroundGeolocation.requestPermission() the dart callback should fire.

## Actual Behavior
A system exception occurs:
I/flutter (31977): [requestPermission] ERROR: PlatformException(DENIED, null, 2)
E/flutter (31977): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: [LocationError code: 1, message: null]

## Steps to Reproduce
Request permission or start().

**Comment by christocracy** [comment]
So `catchError`

**Comment by jaykobi** [comment]
Well, yeah, I was confused by the fact that the debugger always halts at this error, but I guess that's just how it is with native code included.
Thank you.
