### ISSUE TITLE
Send locations to server only on specific events

### ISSUE THREAD

**Issue by usmanzaheer1995** [transistorsoft/flutter_background_geolocation#143]
## Your Environment
* Plugin version: 1.3.2
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Xiaomi A1
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.2)

## Expected Behavior

Send locations to server only on specific events like ActivityChange.

## Actual Behavior

Sends location data on all events.

## Context

Is there a way to send locations to server only on specific events like ActivityChange?

**Comment by christocracy** [comment]
No.  The activity api depends on the user granting that permission.  What would you do if the user denied that permission?

**Comment by usmanzaheer1995** [comment]
My specific use case is that the location should only be saved when the activity type changes i.e. from walking to in_vehicle. If the user denies the location permission, they will be shown some sort of message.

**Comment by christocracy** [comment]
In Android 10, the Motion API now requires user permission, in *addition to* location permission.

The user might grant location but deny motion permission.

The plugin is now able to operate without the motion api.

**Comment by usmanzaheer1995** [comment]
I see, that is good information to have so I can handle it.

But in the case if user does grant permission, can I use the ActivityChange event to save the locations?

**Comment by christocracy** [comment]
See Config.triggerActivities.

Maybe you provide an empty array of tiggerActivities.

**Comment by usmanzaheer1995** [comment]
Yes Config.triggerActivities looks like the thing I'm looking for!

Sorry if this is a dumb question, but will providing an empty array to triggerActivities enable to only save locations when the activity type is changed? Because as per the docs:

> Configures a comma-separated list of motion-activities which are allow to trigger location-tracking.

**Comment by usmanzaheer1995** [comment]
So on each activityChange event, i can use the getCurrentPosition method to persist the data to my url instead of having it saved on each location update, am I understanding that right?

**Comment by christocracy** [comment]
Why don’t you try it and see?

**Comment by usmanzaheer1995** [comment]
Yes thank you I will. And thank you for bearing with me!
