### ISSUE TITLE
How to avoid application to force the user to select permissions "Always Allow"?

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#147]
## Your Environment
* Plugin version: 
1.3.0
* Platform: iOS or Android : 
Both
* OS version: 
All latest versions
* Device manufacturer / model:
Apple and all android manufacturers
* Flutter info (`flutter doctor`):
production issue
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE

// inside init()
    await bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            maxRecordsToPersist: 100,
            maxDaysToPersist: 1))
        .then((bg.State state) async {
      bg.ProviderChangeEvent providerChangeEvent =
          await bg.BackgroundGeolocation.providerState;

      bool enabled =
          (providerChangeEvent != null && providerChangeEvent.enabled);

      bool permissionsGranted = (enabled &&
          providerChangeEvent != null &&
          (providerChangeEvent.status ==
                  bg.ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS ||
              providerChangeEvent.status ==
                  bg.ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE));
...
...



// another function to get current Location 
 await bg.BackgroundGeolocation.getCurrentPosition(
        timeout: 30, // wait 30s before giving up.
        samples: 3, // sample 3 location before selecting best.
        //desiredAccuracy: 0, // desire best possible accuracy
        //maximumAge: 60000, // 60 seconds old is fine
      )
{
}


```

## Expected Behavior

Expecting application should work fine even if the user selects permissions to allow while app is in use. 

## Actual Behavior

Application keeps prompting the user until he/she selects the permissions to 'always allow'

## Steps to Reproduce

1. use the above configuration
2. install the app and open 
3. select permissions to ' use while app is in use'
4. close the app and reopen
5) app again prompts for permissions

(only stops when you select 'always allow'

## Context

trying to keep the chipset hot so that when user wanted a GPS location (by clicking a button to get current location), app should quickly provide a most accurate location. 
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting: 
O NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

![image003](https://user-images.githubusercontent.com/6372373/68890856-63364580-06e5-11ea-9771-4f76afcb56a8.png)

**Comment by christocracy** [comment]
The plugin **can’t possibly** operate the same if the user selects “When in Use”.  The two options are fundamentally different.

See API docs Config.locationAuthorizationRequest.

**Comment by kmusham** [comment]
Just let me know how to avoid tracking GPS when APP is terminated/killed. Customers are worried about they are being tracked in their personal time. If there is no way to stop, then unfortunately we cannot use these libraries. 
Overall, I wanted to collect GPS points ONLY when app is running either in the background or foreground, but not when app killed.
Please advice.
Thanks

**Comment by christocracy** [comment]
See API docs [Config.stopOnTerminate](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/stopOnTerminate.html)

**Comment by kmusham** [comment]
That means, my config is right (I did not set the stopOnTerminate flag assuming the default value is true). If that is the case, not sure why the application is still collecting the GPS locations.

From the documentation you mentioned that 
 - **iOS** : 
When the user moves beyond the stationary geofence (typically ~200 meters), iOS will completely reboot your application in the background, including your Flutter application and the plugin will resume tracking.

- **Android**:
the Android plugin's tracking will not pause at all when user terminates the app.

Please explain and confirm the behavior. 

We need to make a decision on using these libraries as soon as possible before our customers file a lawsuit on us. 

Please make us clear on whether we can COMPLETELY stop tracking GPS locations when app is terminated.
 Thank you.

**Comment by christocracy** [comment]
For iOS, if the user terminates the app *after* first minimizing it, the OS does not send a terminate signal to the app.  The plugin *will* re-launch *once* after terminate.  At that time, the plugin will determine it was supposed to `stopOnTerminate: true` and only then stop recording location.

Only if the user terminates an iOS app while the app is currently in the foreground will the app receive a terminate signal.

This behaviour is easily verified in the Simulator with `debug: true`.

**Comment by kmusham** [comment]
Thanks for a quick response. 
Did you check the screenshot attached to the ticket. That was from real customer's device. Their iOS device showed this warning message and they claim that they terminated the application.

Even my personal android (Pixel 2) device once in a while shows a notification saying ContinuLink application is tracking your locations in the background, tap to change the settings? I'm 100% sure that application is terminated. So it is true that the application is still tracking gps location even when it is terminated.

Could you please review my Config settings and advice the changes, if any to avoid unnecessary tracking. 

Thanks

**Comment by christocracy** [comment]
If the plugin is configured with `stopOnTerminate: false`, tracking cannot possibly continue.

I suggest you test this on your own devices and fetch logs.  See Wiki "Debugging".

**Comment by kmusham** [comment]
I do not want to set stopOnTerminate = false. I wanted to stop tracking on terminate.
Even if the stopOnTerminate: true, seem like the device (particularly iOS) is still capturing locations.

**Comment by christocracy** [comment]
>Even if the stopOnTerminate: true, seem like the device (particularly iOS) is still capturing locations.

Perhaps it's one of your other plugins?  some map components listen to iOS significant-location-changes api (eg: MapBox).

- configure the plugin for `debug: true`
- run your app in simulator.  
- Simulate location with *Freeway Driver*.
- Terminate app.

When the plugin restarts your app, you will see a local-notification telling you so.  If you don't see a notification, the plugin is not responsible.

**Comment by kmusham** [comment]
Just found on the web:
https://qz.com/1713581/what-to-do-when-an-iphone-app-is-using-your-location-in-the-background/
Seems like a new feature introduced in iOS 13.

if that is the case, I think we should allow user to select the option "Allow while using the application".

**Comment by christocracy** [comment]
Yes, I'm fully aware of that.  I [blogged about that in August](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)

It doesn't matter though.  Every iOS 13 app on earth is subject this new dialog.  If you've configured `stopOnTerminate: false`, the plugin no longer tracks the location.

**Comment by kmusham** [comment]
stopOnTerminate - is it 'true' or 'false'?

I'm assuming set to 'true' or leave it so that default value is set to 'true' so that libraries will not track you when  app is terminated.
Am I reading it wrong?

**Comment by christocracy** [comment]
Ask yourself "Do I want my app to *stop on terminate*?"  `true` or `false`?

**Comment by christocracy** [comment]
Have you [done what I asked you to do yet](https://github.com/transistorsoft/flutter_background_geolocation/issues/147#issuecomment-555160914)?

**Comment by kmusham** [comment]
Yes, I'm testing. I did not see the notification yet on my simulator.
But my Config has the 'StopOnTerminate' set to true (i.e default value)

I just followed the documentation on stopOnTerminate. That's why I set it to 'true' to stop tracking after user terminates the application. Now, you're saying set tit to 'false'. I'm totally confused now.


Here is copy paste from the documentation.

/// Controls whether to continue location-tracking after application is **terminated**.
  ///
  /// Defaults to **`true`**.  When the user terminates the app, the plugin will [BackgroundGeolocation.stop] tracking.  Set this to **`false`** to continue tracking after application terminate.

**Comment by christocracy** [comment]
>Now, you're saying set tit to 'false'. I'm totally confused now.

It was a typo.  Corrected.

As I said:  "Ask yourself "Do I want my app to stop on terminate?" true or false?

It's very logical.

**Comment by kmusham** [comment]
ok.
So my only question remain is, do you really need "Always" permission when headless = false, foregound= false, and stoponterminate=true?
Can we make the libraries little bit flexible to align with the Config?

As of today, application keeps prompting and forcing the the user to select "Always allow" even though, app really requires GPS locations while app is in use.

**Comment by christocracy** [comment]
>headless = false, foregound= false,

if you're talking about `enableHeadless` and `foregroundService`, those are **Android only** options that have nothing to do with iOS.

>Can we make the libraries little bit flexible to align with the Config?

I told you [four days ago to read the API docs for `locationAuthorizationRequest`](https://github.com/transistorsoft/flutter_background_geolocation/issues/147#issuecomment-554051626).  The "flexibility" is there.

**Comment by kmusham** [comment]
Thanks.

So, This is going to be my final Config settings. I will start testing this config today.

```
bg.Config(
            locationAuthorizationRequest: 'WhenInUse',
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            heartbeatInterval: 60,
            maxDaysToPersist: 1,
            stopOnTerminate: true,
            reset: true
)
```
Please review.
