### ISSUE TITLE
App Crashes after implementing firebase_messaging BackGround Messaging

### ISSUE THREAD

**Issue by gcervantes2005** [transistorsoft/flutter_background_geolocation#148]
## Your Environment
* Plugin version: I use reference directly to https://github.com/transistorsoft/flutter_background_geolocation.git
* Platform: Android
* OS version: 9.0.9
* Device manufacturer / model: OnePlus 5
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
package mmm.aaaa;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

## Expected Behavior
To have background_geolocation and background messages from Firebase_Messaging working on bakcground

## Actual Behavior
App crashes

## Steps to Reproduce

1. Follow steps to use Background geolocation in background mode
2. Follw steps on firebase_messaging for Background Messages
3. Send a message to app

## Context
Background geolocation was working OK on background but after I followed https://pub.dev/packages/firebase_messaging instructions to receive Background messages my app crashes. I am trying to use firebase Messaging on the Background

The error is comming from method

  public void onActivityDestroyed(Activity activity) {
        if (mRegistrar.activity() == null) {
            activity.getApplication().unregisterActivityLifecycleCallbacks(this);
            BackgroundGeolocation.getInstance(mContext).onActivityDestroy();
        }
    }

on file FLTBackgroundGeolocationPlugin.java

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
D/AndroidRuntime( 2129): Shutting down VM
E/AndroidRuntime( 2129): FATAL EXCEPTION: main
E/AndroidRuntime( 2129): Process: mdc.lertek, PID: 2129
E/AndroidRuntime( 2129): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 2129): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3689)
E/AndroidRuntime( 2129): 	at android.app.ActivityThread.access$1500(ActivityThread.java:207)
E/AndroidRuntime( 2129): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1774)
E/AndroidRuntime( 2129): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2129): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 2129): 	at android.app.ActivityThread.main(ActivityThread.java:6898)
E/AndroidRuntime( 2129): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2129): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime( 2129): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 2129): Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 2129): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
E/AndroidRuntime( 2129): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime( 2129): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:37)
E/AndroidRuntime( 2129): 	at mdc.lertek.Application.registerWith(Application.java:21)
E/AndroidRuntime( 2129): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/AndroidRuntime( 2129): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime( 2129): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3677)
E/AndroidRuntime( 2129): 	... 8 more
D/OSTracker( 2129): OS Event: crash
I/Process ( 2129): Sending signal. PID: 2129 SIG: 9
D/AbstractTracker( 2129): Event success
Lost connection to device.
Exited (sigterm)

```

</details>

**Comment by christocracy** [comment]
the error is caused by your `BarcodeScanPlugin`:
```
by: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 2129): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
```

It's a very common issue with other plugin that haven't considered the behaviour of their plugin in the "Headless" state, where no Android `Activity` exists.

Duplicate #96

**Comment by christocracy** [comment]
Also see https://github.com/apptreesoftware/flutter_barcode_reader/pull/123

**Comment by gcervantes2005** [comment]
As always, thank you very much!
    On Sunday, November 17, 2019, 03:36:52 PM CST, Chris Scott <notifications@github.com> wrote:  
 
 
the error is caused by your BarcodeScanPlugin:
by: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime( 2129): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)

It's a very common issue with other plugin that haven't considered the behaviour of their plugin in the "Headless" state, where no Android Activity exists.

Duplicate #96

**Comment by christocracy** [comment]
I can see that push request `#123` linked above has fixed your problem [here](https://github.com/apptreesoftware/flutter_barcode_reader/blob/master/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt#L19-L23).

You probably just need to update to their latest version.

**Comment by gcervantes2005** [comment]
Yes, I had to download the git, modify and use locally, for some reason I was not getting the fixed version.
Howerver there is also a problem when the configuration is triggered, I added a delay and is working.
I posted at the end of this: [firebase_messaging] background messaging documentation prob · Issue #199 · FirebaseExtended/flutterfire

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
[firebase_messaging] background messaging documentation prob · Issue #19...

Describe the bug It took me about three hours to figure out why my background message handler wasn't working. Th...
 |

 |

 |


Thanks a lot

    On Sunday, November 17, 2019, 07:59:50 PM CST, Chris Scott <notifications@github.com> wrote:  
 
 
I can see that push request #123 linked above has fixed your problem here.

You probably just need to update to their latest version.
