### ISSUE TITLE
Can we configure the parameters of Background Fetch if used with this plugin ? Basically i need background fetch to execute in case of internet available.

### ISSUE THREAD

**Issue by jogiji** [transistorsoft/flutter_background_geolocation#149]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs [BackgroundFetchConfig](https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetchConfig-class.html)

specifically, you'll be interested in `requiredNetworkType`.

**Comment by christocracy** [comment]
And please seek support for background_fetch at its own repo:  https://github.com/transistorsoft/flutter_background_fetch

**Comment by jogiji** [comment]
This is specifically related to this plugin as mentioned in docs , this plugin uses background fetch. Hence i wanted to know whether we can use the backgroundfetch config when implementing background location

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by christocracy** [comment]
`background_fetch` is a completely distinct plugin which you're free to use as documented there.

Please do not seek support for `background_fetch` here in the `flutter_background_geolocation` repo.

**Comment by jogiji** [comment]
Thank you and sorry ✌️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
