### ISSUE TITLE
Location Manager asked permission continuously when I turned off location permission

### ISSUE THREAD

**Issue by dinhha** [transistorsoft/flutter_background_geolocation#15]
## Your Environment
* Plugin version: 0.1.7
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Samsung S8
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel master, v0.11.1-pre.126, on Mac OS X 10.14 18A391, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.28.2)
[✓] Connected device (2 available)

* Plugin config
<pre><code>
{
	"activityRecognitionInterval": 120000,
	"allowIdenticalLocations": false,
	"autoSync": true,
	"autoSyncThreshold": 0,
	"batchSync": false,
	"debug": false,
	"deferTime": 0,
	"desiredAccuracy": -1,
	"desiredOdometerAccuracy": 100,
	"disableElasticity": false,
	"disableStopDetection": false,
	"distanceFilter": 30,
	"elasticityMultiplier": 1,
	"enableHeadless": false,
	"enableTimestampMeta": false,
	"extras": {},
	"fastestLocationUpdateInterval": 600000,
	"forceReloadOnBoot": false,
	"forceReloadOnGeofence": false,
	"forceReloadOnHeartbeat": false,
	"forceReloadOnLocationChange": false,
	"forceReloadOnMotionChange": false,
	"forceReloadOnSchedule": false,
	"foregroundService": false,
	"geofenceInitialTriggerEntry": true,
	"geofenceProximityRadius": 1000,
	"geofenceTemplate": "",
	"headers": {
		"authorization": "eyJ0eXAiOiJKV1QiL..."
	},
	"headlessJobService": "package com.transistorsoft.flutter.backgroundgeolocation, Unknown, version 0.0.HeadlessTask",
	"heartbeatInterval": -1,
	"httpRootProperty": ".",
	"httpTimeout": 60000,
	"isMoving": false,
	"locationTemplate": "",
	"locationTimeout": 60,
	"locationUpdateInterval": 1000,
	"locationsOrderDirection": "ASC",
	"logLevel": 5,
	"logMaxDays": 3,
	"maxBatchSize": -1,
	"maxDaysToPersist": 1,
	"maxRecordsToPersist": 10,
	"method": "POST",
	"minimumActivityRecognitionConfidence": 75,
	"notificationColor": "",
	"notificationLargeIcon": "",
	"notificationPriority": 0,
	"notificationSmallIcon": "drawable\/notification_small",
	"notificationText": "Location Service activated",
	"notificationTitle": "Click Background Location Tracking",
	"params": {},
	"persist": true,
	"schedule": [],
	"startOnBoot": true,
	"stationaryRadius": 25,
	"stopAfterElapsedMinutes": 0,
	"stopOnStationary": false,
	"stopOnTerminate": true,
	"stopTimeout": 5,
	"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
	"url": "URL",
	"enabled": false,
	"schedulerEnabled": false,
	"trackingMode": 1,
	"odometer": 0,
	"isFirstBoot": false
}

</code></pre>

## Expected Behavior
* Should stop asking Location Permission if it is not allowed
* Should have a method to get current Provider Status
* Or it should stop request the permission when I call `BackgroundGeoLocation.stop();`

## Actual Behavior
The service was continuously requesting Location Permission

## Steps to Reproduce

1. Install new app with flutter_background_geolocation started
2. When the Location Permission ask, check in the checkbox "Don't ask again"
3. Tap in "Deny" button

## Debug logs
<pre><code>
11-10 15:30:25.740  6173  6173 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
11-10 15:30:25.740  6173  6173 I TSLocationManager:   ✅  Google Play Services: connected (version code:12451000)
11-10 15:30:25.759  6173  6173 D TSLocationManager: [c.t.locationmanager.data.a.c a] 
11-10 15:30:25.759  6173  6173 D TSLocationManager:   ✅  Opened database
11-10 15:30:25.771  6173  6173 D TSLocationManager: [c.t.locationmanager.data.a.c prune] 
11-10 15:30:25.771  6173  6173 D TSLocationManager:   ℹ️  PRUNE -1 days
11-10 15:30:25.800  6173  6173 D TSLocationManager: [c.t.locationmanager.data.a.a f] 
11-10 15:30:25.800  6173  6173 D TSLocationManager:   ✅  Opened database
11-10 15:30:25.820  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/location
11-10 15:30:25.827  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/motionchange
11-10 15:30:25.835  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/activitychange
11-10 15:30:25.841  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/geofenceschange
11-10 15:30:25.847  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/geofence
11-10 15:30:25.856  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/heartbeat
11-10 15:30:25.864  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/http
11-10 15:30:25.869  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/schedule
11-10 15:30:25.877  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/connectivitychange
11-10 15:30:25.882  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/enabledchange
11-10 15:30:25.888  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/providerchange
11-10 15:30:25.893  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/powersavechange
11-10 15:30:25.899  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:49.213  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:49.235  6173  6173 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
11-10 15:30:49.690  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler onListen] http
11-10 15:30:49.707  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler onListen] providerchange
11-10 15:30:49.716  6173  6173 D TSLocationManager: [c.t.f.b.streams.StreamHandler onListen] powersavechange
11-10 15:30:49.728  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:49.728  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:50.011  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:50.011  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:50.095  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:50.140  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:50.140  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:50.164  6173  6173 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy] 
11-10 15:30:50.164  6173  6173 I TSLocationManager: ╔═════════════════════════════════════════════
11-10 15:30:50.164  6173  6173 I TSLocationManager: ║ MainActivity was destroyed
11-10 15:30:50.164  6173  6173 I TSLocationManager: ╠═════════════════════════════════════════════
11-10 15:30:50.164  6173  6173 I TSLocationManager: ╟─ stopOnTerminate: true
11-10 15:30:50.164  6173  6173 I TSLocationManager: ╟─ enabled: false
11-10 15:30:50.173  6173  6173 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c] 
11-10 15:30:50.173  6173  6173 D TSLocationManager:   🔴  Cleared callbacks
11-10 15:30:50.186  6173  6173 I TSLocationManager: [c.t.l.s.TSScheduleManager b] 
11-10 15:30:50.186  6173  6173 I TSLocationManager:   🔴  Scheduler OFF
11-10 15:30:50.383  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:50.383  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:50.549  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:50.570  6173  6173 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
11-10 15:30:50.582  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:50.582  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:50.817  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:50.817  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:51.172  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:51.221  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:51.221  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:51.435  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:51.435  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:51.864  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:51.897  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:51.897  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:52.154  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:52.154  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:52.345  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:52.375  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:52.375  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:52.591  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:52.591  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:52.819  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:52.853  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:52.853  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:53.055  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:53.055  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:53.427  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:53.448  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 
11-10 15:30:53.448  6173  6173 I TSLocationManager:   🔵  LocationAuthorization: Requesting permission
11-10 15:30:53.637  6173  6173 W TSLocationManager: [c.t.locationmanager.util.b$1 onPermissionDenied] 
11-10 15:30:53.637  6173  6173 W TSLocationManager:   ⚠️  LocationAuthorization: Permission denied
11-10 15:30:53.915  6173  6173 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
11-10 15:30:53.933  6173  6173 I TSLocationManager: [c.t.locationmanager.util.b a] 

</code></pre>

**Comment by christocracy** [comment]
You get provider status by listening to event onProviderChange.

**Comment by dinhha** [comment]
But I only get that event after calling BackgroundGeoLocation.start(), and it causes the loop. Then I can't stop it

**Comment by christocracy** [comment]
Read closely the docs for onProviderChange.  Make sure you listen *before* `#ready`

**Comment by dinhha** [comment]
OK. I will try. Thanks
