### ISSUE TITLE
Processing locations backgrounded

### ISSUE THREAD

**Issue by casper-k** [transistorsoft/flutter_background_geolocation#152]
I'm struggling to understand if I can support a specific feature.

Currently, the idea is to store all locations at the server for further processing, just like your example does with autoSync. I get questions from concerned beta users concerning their privacy. Ideally, I don't have to send all their locations to the server, but rather process the data immediately on the phone. So my thoughts are to disable the HTTP autoSync feature and read all persisted locations manually in my app, twice a day, and send a summary instead.

My questions is about doing this in the background. My app is used passively, so most of the time, the user opens the app only to sign in and then leave the app backgrounded. I don't think this is a problem with Android – I was planning to use a headless tasks for the location processing, but iOS is more strict in what is allowed to run in the background. Because your plugin can recover itself when terminated on iOS due to a geofence event, I'm wondering if your plugin is exposing a way to call a user function on iOS, which I can leverage to further process the stored locations, ideally when entering stationary state?

**Comment by christocracy** [comment]
>I'm wondering if your plugin is exposing a way to call a user function on iOS, which I can leverage to further process the stored locations, ideally when entering stationary state?

Yes.  See API docs for event `#onMotionChange`.  If you set `autoSync: false`, all the data is available from the plugin's SQLite database via `BackgroundGeolocation.getLocations`.

**Comment by casperkloppenburg** [comment]
Thanks – so no need for a headless task on Android after all? My current understanding of the plugin; when I enable (`BackgroundGeolocation.start()`), your plugin installs a hook that reacts to movements from the accelerator sensor (Android) or a geofence event (iOS), invoked by the operating system.
If such event happens and the app was terminated for some reason,
**1.** the operating system reopens the app, and thus the plugin, as if started by the user,
**2.** the app is running in the background but fully functional, and
**3.** `State.didLaunchInBackground` is true.

Thinking about this, is is also correct to assume that my app is running whilst your background service is active? Or is it limited in some way?
