### ISSUE TITLE
[iOS] Heartbeat Never Fires When App is in the Background

### ISSUE THREAD

**Issue by brandonhub** [transistorsoft/flutter_background_geolocation#154]
## My Environment
* **Version**: 1.3.2
* **Platform**: iOS or Android iOS
* **OS version**: Latest (13.1)
* **Device manufacturer / model**: iPhone 8
* **Flutter info (`flutter doctor`)**: 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.40.1)
[!] Connected device
    ! No devices available
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
      desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
      logLevel: Config.LOG_LEVEL_VERBOSE,
      url: serverUrl,
      autoSyncThreshold: 25,
      batchSync: true,
      preventSuspend: true,
      heartbeatInterval: 60,
      params: {'userID': <userID goes here>})
```

## Expected Behavior
To receive heartbeat events when the app is in the background.

## Actual Behavior
Once the app is closed, heartbeat events stop even when the phone is in motion.

## Context
I'm aware the iOS can throttle heartbeats after 2 min of the app being in the background, but the API documentation states that ` if the screen is lit up or even the slightest device-motion is detected, [BackgroundGeolocation.onHeartbeat] events will immediately resume.`. No matter if my device is in motion or it is completely still, I never get heartbeats unless the app is open and running in the **foregreound**.  Could there be something wrong with my config? Thanks for your help!

**Comment by christocracy** [comment]
Are you sure your app has *Always* location authorization?  It's required for `preventSuspend` to work.  - - Go to *Settings->Privacy->Location Services->Your App*.
- Ensure *Always* is selected.

**Comment by brandonhub** [comment]
Thanks for the quick response! I have checked and confirmed that _Always_ is indeed selected. I wonder if this could be an issue with the latest iOS (13.1) as it came out rather recently.

**Comment by christocracy** [comment]
I have other customers using `preventSuspend` with iOS 13 since September.

**Comment by brandonhub** [comment]
> I have other customers using preventSuspend with iOS 13 since September.

I'm glad to hear that, do you happen to know if they were successfully receiving heartbeat events? Do you have _any_ other tips or thoughts on what I could do to fix this? I've been fiddling around with it for a while and I'm a bit lost at this point.

**Comment by brandonhub** [comment]
🤦‍♂ I was careless and never enabled **Location Updates** and **Background Fetch** as specified in the [iOS Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-IOS.md). If anybody else is having trouble, your **Capabilities Configuration** should should look like this...
<img width="487" alt="Screen Shot 2019-11-24 at 3 58 22 PM" src="https://user-images.githubusercontent.com/2007162/69501469-406d1380-0ed3-11ea-91f7-306e78fbb024.png">

Alternatively, you can just add the following to your _Info.plist_...
```
<key>UIBackgroundModes</key>
    <array>
        <string>fetch</string>
        <string>location</string>
</array>
```

This was a non-issue.
