### ISSUE TITLE
Seeing "FORCE KILL BACKGROUND TASK" in Logs then Background Task is Killed

### ISSUE THREAD

**Issue by brandonhub** [transistorsoft/flutter_background_geolocation#155]
## My Environment
* **Version**: 1.3.2
* **Platform**: iOS or Android iOS
* **OS version**: Latest (13.1)
* **Device manufacturer / model**: iPhone 8
* **Flutter info (`flutter doctor`)**: 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.40.1)
[!] Connected device
    ! No devices available
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 Config(
      desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      autoSync: false,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      batchSync: true,
      autoSyncThreshold: 10,
      stationaryRadius: 25,
      debug: true,
      logLevel: Config.LOG_LEVEL_VERBOSE,
      heartbeatInterval: 60,
      preventSuspend: true,
      url: serverUrl,
      params: {'userID': userID})
```

## Expected Behavior
Because `preventSuspend` is enabled the background task should never quit.

## Actual Behavior
After about 15 min of the app being closed, the background task is terminated.

## Context
Everything works great for 20 min after closing the app, but then the background task stops. The only way I can get it to start again (short of opening the app myself) is to exit the ~200 meter stationary radius, but I don't think that should be an issue in the first place because `preventSuspend` is on.

**Comment by christocracy** [comment]
Don't rely on `preventSuspend: true`.  iOS has decreased the maximum allowable bakground-task time-limit to 30s from 180s (once-upon-a-time, it was 10 minutes).

Prevent suspend operates by periodically turning on location-services just before the background time-limit expires, which resets the time-limit.  This means the plugin is turning on location-services every 30s.

If, for any reason a location fails to be recorded in each of these 30s, preventSuspend *will* fail.  This is a very brittle mechanism, designed for *very* specialized use-cases.  99% of apps don't require `preventSuspend`.

**Comment by brandonhub** [comment]
Ah very interesting, thanks for letting me know. So the app I'm creating requires precision beyond the 200 meters "error" that could possibly occur with the stationary radius (think something like "Find my Friends"). Do you think that obtaining that sort of precision is pretty much impossible on iOS due to their API restrictions? If, say, the timer fired every 15 seconds instead could that fix the problem?

**Comment by christocracy** [comment]
>Do you think that obtaining that sort of precision is pretty much impossible on iOS due to their API restrictions?

Find My Friends operates by sending silent push requests to the device.  If the server wants to known where a device is, send a silent push request to it with a json payload that you decode.

```javascript
onPushRequest(payload) {
  if (payload.extras) {
    let command = extras.command;
    switch (command) {
      case 'getCurrentPosition':
        BackgroundGeolocation.getCurrentPosition();
        break;
      .
      .
      .
    }
  }
}
```

**Comment by brandonhub** [comment]
Ok, that makes sense.  I feel that in reality, your `onPushRequest` function actually would require some additional platform-specific code and/or dart isolate code in order to work. Something like `onPushRequest` is not something currently offered by the `flutter_background_geolocation` plugin correct?

**Comment by christocracy** [comment]
This SDK has nothing to do with push.  That's your responsibility.
