### ISSUE TITLE
Background Location stopped for 9 hours

### ISSUE THREAD

**Issue by noorflex** [transistorsoft/flutter_background_geolocation#156]
## Your Environment
* Plugin version: flutter_background_geolocation 1.3.2
* Platform: Android
* OS version: 9 
* Device manufacturer / model: Redmi Note 6 Pro
* Flutter info (`flutter doctor`):
* Plugin config: Set to receive location each 10 min.
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

It should keep on providing background location.
## Actual Behavior

It was working for 2 days as expected, 3rd day it provided last location at 9.12pm night. After that no locations were provided though device was not kept idle. After getting up in the morning it recorded at 6.41. When I was driving could not get any location. i.e 6.41 to 9.45 no location.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- see http://dontkillmyapp.com
- see wiki “Debugging”

**Comment by noorflex** [comment]
As per the documentation,
The BackgroundGeolocation SDK provides an Android Headless Mechanism, enabled with Config.enableHeadless: true. Doing so allows you to provide your own dart callback to receive events after your app has been terminated.

As it says even if app is terminated, we can get location callbacks. Does it still depends on manufacturer? Given that I was getting it for 2 days and stopped at 3rd day.

**Comment by christocracy** [comment]
`enableHeadless: true` isn't required for the plugin to continue tracking after terminate, only `stopOnTerminate: false`.

`enableHeadless: true` is only when *you* want to actually provide your own custom dart code to *receive* those events in the terminated state.

The Android service continue tracking and persisting locations into its own SQLite database, regardless of `enableHeadless`.  If you've provided a `Config.url`, the plugin is also going to continue uploading locations to your server in the terminated state.

>Does it still depends on manufacturer?

Probably.  I have 11 Android devices running the sample app for over a month, non-stop.  I do not interact with most of these devices.  I just throw them in my backpack and go.
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 10
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 8.0.0
