### ISSUE TITLE
Is there a way to remove the beep sound during location updates

### ISSUE THREAD

**Issue by shanazainab** [transistorsoft/flutter_background_geolocation#158]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Of course there is.  That’s there to assist during development / field testing so you don’t have to run back to your desk to see if it working.

See Config.debug

**Comment by shanazainab** [comment]
Thank you👍
