### ISSUE TITLE
how to remove Location activated Notification 

### ISSUE THREAD

**Issue by Chaithanya26** [transistorsoft/flutter_background_geolocation#168]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You can't.  It's required by Android OS for foreground-services.  Google "Android foreground service notification".

If you only need a location periodically, like every 1000 meters, you can configure `useSignificantChangesOnly: true`.  If you need a location *frequently*, according to your configured `distanceFilter`, the persistent foreground-service notification is *required*.

**Comment by Chaithanya26** [comment]
Thank you @christocracy
