### ISSUE TITLE
Location tracking when screen is off

### ISSUE THREAD

**Issue by MathiasVandePol** [transistorsoft/flutter_background_geolocation#17]
## Your Environment
* Plugin version: 0.2.2
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Samsung Galaxy S9
* Flutter info (`flutter doctor`): N/A
* Plugin config N/A

## Expected Behavior

Tracking of location works perfectly with screen that is on and even when the application is in the background (i use a foreground service).
It stops tracking when screen is off. I would expect it to keep reporting location. 
I have the same issue when using the "Advanced example".
I run the advanced example with foregroundService enabled.

## Steps to Reproduce

1. Start the Advanced Example
2. Enable and start walking with screen on so that you see some locations being marked.
3. Turn screen off, walk a bit more
4. Put screen back on and notice that it only updates location when you've put it on.

## Context

I'm creating a navigation application which should also receive location updates when screen is off.

**Comment by christocracy** [comment]
On my many test devices, including 2 samsung, I have no such problem.

Please provide logs.  See wiki “Debugging”.  The plugin holds 3 days of logs by default in its database.

**Comment by christocracy** [comment]
And in the demo's Advanced App is a convenient "Email Log" button in the FAB button menu.

**Comment by MathiasVandePol** [comment]
I tested it in the emulator and there it is working perfectly.

I recorded a session when a drove home.
You can see a line:
```
12-03 18:08:02.753 DEBUG [c destroy] 
 ✅  DESTROY: 8c2b0c15-cbc7-4b2f-ad6b-8ebb0aa128f7
```
after which recording stop for 2 minutes until I turn the screen back on.

Then at 18:11 I turn the screen back off;
```

12-03 18:11:02.252 DEBUG [c destroy] 
  ✅  DESTROY: 1e7312ca-4ed6-4d0a-a21d-e3f8563aff4f
```
You can find the log [here](https://drive.google.com/open?id=1ojCTjA4cmbE0DfdQk2eVEUEUiP3GCqUj)
In red I drew the road i used.

![](https://lh3.googleusercontent.com/GGrSPgmyhl0ZbFlpAdoaK1_OG8AAcI70je8uHEbVVWyu0kkD_bZo1giKadhC_wPcGaKiTa0nHPIn_Xe8KiLlpiK9O5B8eD5BP8AVdxfAaYwswTlMBOmZLF-2LL3IQ4mbh4Dq-ybE-I0GCX3qbOmVKTZM5H6UCJb2LG8uZkJ5VVNqSjbfAVu5-wVnoj9-XkEHqfTZcBexs8R9kYa8AlUIgW2wEf2ne31j7A1afcEdoXLQj4Hg3LHjigy2QqhTxo3zm1sQLsjJfJmOa5OCjsnv0-ZRBxla-f7V7xn40ofPREHgP5VVYWG6kcqUUtO7Bn272rVXMzglLTJHJxXT_A8OeraBGxma3_owF3xz__XICgWc519pV85Sw8TJC0Sh8zHhBFbOPMs6krAz-660zY5LjZMFHOXoKBZSIRD-w7RxDo21_KS92oFJMS90QxlJPG4NK-T-3RO90Zuu6W_JUq1nDQtohDd0yMnbsrkSNaSs1eKRbwA9TvjZnOV5lQ1CLjA7rjZgYD2YSBrt7F9_aBfvgiUbzCLlRp0uYwzuXk9xt7IEfGfSBt8tYjecWdNzUAfQQHVl-Hw868r_ADo1mHVJ2TIh_w3LNFc4fmWo9V1qWmFHiHumuDxfgM5LFlzvX4vAzCcaRPyM4TRsva7YSjMAfJVw4g=w646-h1326-no)

**Comment by christocracy** [comment]
Here's your tracking posted to the demo server.
http://tracker.transistorsoft.com/djjddjjd

I see you were toggling location-services on your device:
```
12-03 18:11:01.862 INFO [BackgroundGeolocation$g onReceive] 
╔═════════════════════════════════════════════
║ Location-provider change: false
╠═════════════════════════════════════════════
╟─ GPS: false
╟─ Network: false
```

Also, your battery level was `< 50%`.  Check Settings->Battery:  check your power-saving settings.  Android can disable GPS when level is less than a certain threshold (though `onPowerSaveChange` events should be appearing in the logs and I see none.

**Comment by MathiasVandePol** [comment]
Strange I did not toggle the location services but they might automatically trigger of.
I guess this might not be related to your library but to the phone in general.
I will test with other navigation applications and come back.

**Comment by MathiasVandePol** [comment]
I figured it out. It was indeed device related.
Seems that there was a small battery saver mode enabled which turned off gps when screen is off.
The "medium power saving" mode did not state anything about it but it seems it blocks background location tracking.
