### ISSUE TITLE
disable/enable by move 

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#170]
is there any way to disable or enable the service buy that if device moving or stay-sleep.?
to make Location activated Notification hide.

**Comment by christocracy** [comment]
- If the device is *not* moving, there is no notification.
- If the device is moving and the plugin recording location, the notification is *required* by the operating system.  It cannot be hidden.
- If you need a location only about every 1000 meters, see docs `Config.useSignificantChangesOnly`.
