### ISSUE TITLE
Crash my app when using build spk file in mobile , but it debug work fine , how can i fix this ?

### ISSUE THREAD

**Issue by vinodlee** [transistorsoft/flutter_background_geolocation#172]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1. App crash when install the apk file
2. debug app work fine
3. Am tried to build apk file and install the other device for testing 
4. am using Vivi 11 pro android mobile (Android version 9)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by joaofjunior** [comment]
I have the same problem

**Comment by christocracy** [comment]
If there's a crash, where your stacktraces?  When you experience a crash, the **FIRST** thing you do, before seeking help, is fetch the stacktrace from `logcat`.  There is *always* a stacktrace.

**Comment by joaofjunior** [comment]
The release mode error I received was this.
![erro_mapear](https://user-images.githubusercontent.com/32842904/72267805-12649f80-35f7-11ea-92f8-f155b654f999.jpeg)

**Comment by christocracy** [comment]
Review [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidappbuildgradle), particularly the part about "Proguard"

**Comment by bwhiteTP** [comment]
I'm having the same issue, when I enable proguard the app starts but crashes while using the app (only happens in release) when I disable proguard the app crashes immediately in release.  I believe proguard is removing something it shouldn't. There is no stacktrace in crashlytics. All I get is:
Crashed: Thread #1
SIGABRT 0x000027ea0000722f
libc.so (missing)

Recently Android and flutter moved to R8 instead of proguard. Maybe that has something to do with this?

**Comment by christocracy** [comment]
I have my sample all built for release and deployed to play store.  It’s updated to latest flutter api 1.12

**Comment by christocracy** [comment]
Have you included the plugin’s required proguard rules as documented in Setup?

**Comment by vinodlee** [comment]
Now working fine thanks @christocracy

**Comment by bwhiteTP** [comment]
So this was still not fully fixed for me, but I found a solution that should be shared. When I added the proguard rules I believe the proguard file was removing some things that other libraries needed. The solution was to make my own proguard file with the following:

-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**
-ignorewarnings
-keepclassmembers enum * {*;}

Everything now works in both release and debug builds.

**Comment by christocracy** [comment]
Perhaps your flutter app’s proguard file is out-of-date after upgrades?

None of this is the plugin’s responsibility.

**Comment by wemersonrv** [comment]
@christocracy good afternoon.

I'm having the same issue. In my case i'm not using proguard, so do not add any proguard rules.

It's mandatory to configure proguard to work with your plugin?

**Comment by christocracy** [comment]
> It's mandatory to configure proguard to work with your plugin?

Yes

**Comment by wemersonrv** [comment]
Ok make the changes for proguard and a new build and install it on my device. It crashes again!

**Comment by christocracy** [comment]
See #192

**Comment by wemersonrv** [comment]
> See #192

Teste release installed and run without crash! Tx
