### ISSUE TITLE
maxDaysToPersist -> Can you modify it to allow hours instead of days?

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#174]
One of our client requested not to to persist the GPS locations more than an hour. I see _Config.maxDaysToPersist_ parameter, but this takes integer value. Do you mind introducing a parameter to allow hours?

Thanks

**Comment by christocracy** [comment]
If your server returns a success response, the destroys that location from its internal SQLite database *immediately*.

maxDaysToPersist is only for cases where your server doesn’t return a success response, or does not respond.  In this case the plugin will continue attempting to upload that location until maxDaysToPersist expires and it gets deleted.

No, this will not be changed to hours.
