### ISSUE TITLE
Delayed when starting tracking

### ISSUE THREAD

**Issue by djsliders** [transistorsoft/flutter_background_geolocation#175]
## Your Environment
* Plugin version: 1.5.0
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung 7
* Flutter info (`flutter doctor`): Channel stable, v1.12.13+hotfix.5, on Linux
* Plugin config:
```bg.BackgroundGeolocation.onLocation(updateOnNewLocation);

    ////
    // 2.  Configure the plugin
    //
    Future.delayed(Duration(milliseconds: 500)).then((_) {
      bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        debug: true,
          distanceFilter: 20,
        persistMode: bg.Config.PERSIST_MODE_NONE,
        notification: bg.Notification(),
        logLevel: bg.Config.LOG_LEVEL_DEBUG,
        stopOnTerminate: true,
        startOnBoot: false,
      ));
    });
Future updateOnNewLocation(bg.Location location) async {
    print('[location] - $location');
};
```

## Expected Behavior
When starting the tracking, it should get me a position every 20 meters.

## Actual Behavior
When I start the tracking, it get a first position, then nothing for, like 50 seconds, and then it starts working correctly, getting a position every 20 meters.
I tried to play with parameters but cannot make it work correctly from the start.

## Context
Track a walking user, so I would like to get a position every 20 meters.

## Debug logs
I hide lat / long data.
As you can see with the timestamp, it starts, get a position, then wait almost one minute, and then get data correctly. Thank you for your help!

```
I/flutter (  707): [start] success [State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: -1, distanceFilter: 20.0, odometer: 240912.78125, schedulerEnabled: false, foregroundService: true]
I/flutter (  707): [location] - [Location {odometer: 240912.796875, activity: {confidence: 100, type: still}, mock: true, extras: {}, event: motionchange, battery: {level: 0.01, is_charging: true}, uuid: 1a9de496-74c1-4321-b1a4-6228ca031f54, coords: {altitude: 30.0, heading: 197.36, latitude: x.46905032565759, accuracy: 4.3, speed: 2.78, longitude: y.396229963900478}, is_moving: false, timestamp: 2020-01-15T08:34:58.015Z}]
I/flutter (  707): 4.3
I/flutter (  707): [location] - [Location {odometer: 241074.796875, activity: {confidence: 100, type: still}, mock: true, extras: {}, event: motionchange, battery: {level: 0.01, is_charging: true}, uuid: 16d3d218-e65f-45c2-bf65-80cbc53e42a1, coords: {altitude: 30.0, heading: 192.5, latitude: x.46763850440638, accuracy: 7.1, speed: 2.78, longitude: y.395705935375632}, is_moving: true, timestamp: 2020-01-15T08:35:51.016Z}]
I/flutter (  707): 7.1
I/flutter (  707): [location] - [Location {odometer: 242961.5, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 0.01, is_charging: true}, uuid: 2919a9df-c782-479f-b712-92e8a7d65760, coords: {altitude: 496.8, heading: 6.13, latitude: x.4783362, accuracy: 14.2, speed: 0.0, longitude: y.3766333}, is_moving: true, timestamp: 2020-01-15T08:35:57.060Z}]
I/flutter (  707): 14.2
I/flutter (  707): [location] - [Location {odometer: 244857.796875, activity: {confidence: 100, type: still}, mock: true, extras: {}, battery: {level: 0.01, is_charging: true}, uuid: f0c02073-77a5-4476-a9f8-1795bfc9bc5a, coords: {altitude: 30.0, heading: 192.97, latitude: x.467450940159154, accuracy: 2.5, speed: 2.78, longitude: y.395643646719716}, is_moving: true, timestamp: 2020-01-15T08:35:59.016Z}]
I/flutter (  707): 2.5
I/flutter (  707): [location] - [Location {odometer: 244878.59375, activity: {confidence: 100, type: still}, mock: true, extras: {}, battery: {level: 0.01, is_charging: true}, uuid: 74fb83b8-81fd-4603-b9bf-e0a53e8134a9, coords: {altitude: 30.0, heading: 186.11, latitude: x.46726619519235, accuracy: 3.9, speed: 2.78, longitude: y.39559701615656}, is_moving: true, timestamp: 2020-01-15T08:36:07.016Z}]
I/flutter (  707): 3.9
I/flutter (  707): [stop] success: [State enabled: false, isMoving: false, trackingMode: 1, desiredAccuracy: -1, distanceFilter: 20.0, odometer: 244878.609375, schedulerEnabled: false, foregroundService: true]
```

**Comment by christocracy** [comment]
Why are you using Future.delayed to execute `#ready`?

See wiki “debugging”.

**Comment by djsliders** [comment]
Hi,
I removed the Delayed, didn't impact anything as the start method is called later on button pressed.

I checked debugging wiki, but I have already used Lockito to test, test with real walk, put LOG_LEVEL_VERBOSE, it doesn't show more log.
I added:
```
bg.Logger.getLog().then((String log) {
      print(log);
    });
```
That gets me:
```
I/flutter (14769): 01-17 23:57:36.921 INFO [TSConfig print] 
I/flutter (14769): ╔═════════════════════════════════════════════
I/flutter (14769): ║ TSLocationManager version: 3.0.46 (346)
I/flutter (14769): ╠═════════════════════════════════════════════
I/flutter (14769): ╟─ samsung SM-G930F @ 8.0.0 (flutter)
I/flutter (14769): {
I/flutter (14769):   "activityRecognitionInterval": 10000,
I/flutter (14769):   "allowIdenticalLocations": false,
I/flutter (14769):   "authorization": {},
I/flutter (14769):   "autoSync": true,
I/flutter (14769):   "autoSyncThreshold": 0,
I/flutter (14769):   "batchSync": false,
I/flutter (14769):   "configUrl": "",
I/flutter (14769):   "debug": true,
I/flutter (14769):   "deferTime": 0,
I/flutter (14769):   "desiredAccuracy": -1,
I/flutter (14769):   "desiredOdometerAccuracy": 100,
I/flutter (14769):   "disableAutoSyncOnCellular": false,
I/flutter (14769):   "disableElasticity": true,
I/flutter (14769):   "disableLocationAuthorizationAlert": false,
I/flutter (14769):   "disableMotionActivityUpdates": false,
I/flutter (14769):   "disableStopDetection": false,
I/flutter (14769):   "distanceFilter": 20,
I/flutter (14769):   "elasticityMultiplier": 1,
I/flutter (14769):   "enableHeadless": false,
I/flutter (14769):   "enableTimestampMeta": false,
I/flutter (14769):   "encrypt": false,
I/flutter (14769):   "extras": {},
```
With adb I got the following:
```
01-18 15:55:45.879 14769 18490 I TSLocationManager: ╔═════════════════════════════════════════════
01-18 15:55:45.879 14769 18490 I TSLocationManager: ║ motionchange LocationResult: 14
01-18 15:55:45.879 14769 18490 I TSLocationManager: ╠═════════════════════════════════════════════
01-18 15:55:45.879 14769 18490 I TSLocationManager: ╟─ 📍  Location[fused x.462427,y.393219 hAcc=6 et=+16h1m8s834ms alt=30.0 vel=2.7777777 bear=205.08517 vAcc=??? sAcc=??? bAcc=??? mock {Bundle[mParcelledData.dataSize=44]}], age: 321ms, time: 1579359345556
01-18 15:55:45.883 14769 14769 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot] 
01-18 15:55:45.883 14769 14769 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
01-18 15:55:45.886 14769 18490 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
01-18 15:55:45.886 14769 18490 I TSLocationManager:   🔵  Acquired motionchange position, isMoving: false
01-18 15:55:45.887 14769 18490 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 6.086529
01-18 15:55:45.943 14769 14769 D TSLocationManager: [c.t.l.s.LocationRequestService onDestroy] 
01-18 15:55:45.946 14769 14893 I flutter : [location] - [Location {odometer: 246441.09375, activity: {confidence: 100, type: still}, mock: true, extras: {}, event: motionchange, battery: {level: 0.7, is_charging: true}, uuid: 1e7321ac-a9eb-4899-9c8c-6d645b41f41b, coords: {altitude: 30.0, heading: 205.09, latitude: x.46242660782207, accuracy: 6.1, speed: 2.78, longitude: y.393219314976242}, is_moving: false, timestamp: 2020-01-18T14:55:45.556Z}]
01-18 15:55:45.946 14769 14893 I flutter : 6.1
01-18 15:55:45.958 14769 14769 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a] 
01-18 15:55:45.958 14769 14769 I TSLocationManager:   🎾  Start motion-activity updates
01-18 15:55:45.958 14769 18490 D TSLocationManager: [c.t.l.s.LocationRequestService a] SingleLocationRequest 14 isFinished? true
01-18 15:55:45.961 14769 14769 D TSLocationManager: [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
01-18 15:55:45.961 14769 14769 D TSLocationManager:   🎾  Start monitoring stationary region (radius: 150.0m x.46242660782207,y.393219314976242 hAcc=6.086529)
01-18 15:55:46.005 14769 14769 I TSLocationManager: [c.t.l.service.TrackingService h] 
01-18 15:55:46.005 14769 14769 I TSLocationManager: ╔═════════════════════════════════════════════
01-18 15:55:46.005 14769 14769 I TSLocationManager: ║ TrackingService motionchange: false
01-18 15:55:46.005 14769 14769 I TSLocationManager: ╠═════════════════════════════════════════════
01-18 15:55:46.059 14769 14769 D TSLocationManager: [c.t.l.s.ActivityRecognitionService a] 
01-18 15:55:46.059 14769 14769 D TSLocationManager:   🚘 ️DetectedActivity [type=STILL, confidence=100]
01-18 15:55:46.265 14769 14769 D TSLocationManager: [c.t.l.service.TrackingService onDestroy] 
01-18 15:55:46.265 14769 14769 D TSLocationManager:   🔴  TrackingService destroyed
01-18 15:55:47.086 14769 14769 D TSLocationManager: [c.t.l.s.ActivityRecognitionService onDestroy] 
01-18 15:55:47.086 14769 14769 D TSLocationManager:   🔴  ActivityRecognitionService destroyed
01-18 15:55:55.945 14769 18443 I TSLocationManager: [c.t.l.scheduler.ScheduleEvent onOneShot] 
01-18 15:55:55.945 14769 18443 I TSLocationManager: ╔═════════════════════════════════════════════
01-18 15:55:55.945 14769 18443 I TSLocationManager: ║ ⏰ OneShot event fired: TERMINATE_EVENT
01-18 15:55:55.945 14769 18443 I TSLocationManager: ╠═════════════════════════════════════════════
01-18 15:55:55.950 14769 18443 D TSLocationManager: [c.t.l.event.TerminateEvent <init>] 
01-18 15:55:55.950 14769 18443 D TSLocationManager:   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
```
Then nothing more is happening in the log.


Thank you for your help.

**Comment by christocracy** [comment]
See the Wiki “Debugging” for an important note about using mock location apps, such as Lockito.

The plugin uses Motion api (accelerometer, gyroscope, magnetometer) to detect when device is moving.  

The best way to test triggering is on real device by walking outside.

**Comment by djsliders** [comment]
I have the same issue outside, without mock.
Is it possible to use this plugin as a normal background location ? I mean, to have a position every 20 meters, that's all I need. No need for fences, accelerometer etc... 
So what can I do about this issue? You want me to give you some logs from real condition?

I think it is not always possible for user to test their apps in real condition and having something to make it work with mock location is indispensable, what do you think?

**Comment by christocracy** [comment]
> No need for fences, accelerometer etc...

Read the wiki “Philosophy of Operation”.

The plugin initiates tracking when the device is detected to be *moving* and turns *off* location services when the device is detected to be *stationary*.

For this purpose, the plugin uses the motion api, in addition to a geofence around the last known position where the plugin entered the stationary state, as a secondary triggering mechanism.

If you want to simulate *motion* while mocking location, shake the device vigorously for up to 30 seconds or manually execute changePace(true).

**Comment by christocracy** [comment]
Depending on the device, it can take motion of some meters before triggering initiates.

Most of my 11 Android test devices trigger with less than 200 meters of movement beyond stationary location.

The *green* polylines in the following images represent the distance travelled before tracking engaged (where the `motionchange` event fired with `isMoving: true`)

- OnePlus A510 @ 8.0.0 (Consistently good)
![](https://dl.dropboxusercontent.com/s/ypxiv9f6cp12lw4/Screenshot%202020-01-18%2011.21.10.png?dl=1)

- Nexus 4 @ 4.4.4
![](https://dl.dropboxusercontent.com/s/ypxiv9f6cp12lw4/Screenshot%202020-01-18%2011.21.10.png?dl=1)

- Nokia TA-1027 @ 8.0.0 (this device took a long time to trigger at one point)
![](https://dl.dropboxusercontent.com/s/de3dt2o1crg47mt/Screenshot%202020-01-18%2011.22.51.png?dl=1)

- Nexus 5 @ 6.0.1 (typically performs very well)
![](https://dl.dropboxusercontent.com/s/82i17iu4l5jxzck/Screenshot%202020-01-18%2011.23.41.png?dl=1)

- XIAOMI Mi A2 Lite @ 9.0.0 (Performs consistently well)
![](https://dl.dropboxusercontent.com/s/mxet8niw3w768b6/Screenshot%202020-01-18%2011.11.17.png?dl=1)

- Huawei P20 Lite @ 8.0.0 (Huawei devices are **the worst**; very inconsistent performance)
![](https://dl.dropboxusercontent.com/s/tl9ys9zc1h5jclx/Screenshot%202020-01-18%2011.13.57.png?dl=1)

- Motorola Moto G @ 6.0.0 (Typically performs well)
![](https://dl.dropboxusercontent.com/s/eh0qithuwjrmrb9/Screenshot%202020-01-18%2011.14.57.png?dl=1)

- Samsung A510 @ 8.0.0 (consistently good triggering)
![](https://dl.dropboxusercontent.com/s/w4be9t64sgrn944/Screenshot%202020-01-18%2011.19.59.png?dl=1)

- Google Pixel @ 10.0.0 (Always great performance)
![](https://dl.dropboxusercontent.com/s/694pw3dg40ohxm1/Screenshot%202020-01-18%2011.16.24.png?dl=1)

- Google Pixel 3a @ 10.0.0 (Always great performance)
![](https://dl.dropboxusercontent.com/s/uwwamz6qvqa7eys/Screenshot%202020-01-18%2011.17.19.png?dl=1)

- iPhone 11 Pro (Consistently triggers at about 200 meters)
![](https://dl.dropboxusercontent.com/s/ivvz0jgv9gs98k1/Screenshot%202020-01-18%2011.18.35.png?dl=1)

**Comment by christocracy** [comment]
Also, for problems with any particular device model, see http://dontkillmyapp.com

**Comment by djsliders** [comment]
Thanks for the info. 
So, is there an option to ask him to fetch the position earlier at the beginning instead of waiting?
I have the option distanceFilter: 20 but obviously it is not taken into account at the beginning.

Thank you

**Comment by christocracy** [comment]
For almost 6 years, this plugin has does an amazing job automatically detecting when a device moving vs stationary.  However, the detection of *device moving* takes some distance.  It can take 200 meters.

Only when the device **is detected to be moving** will the plugin initiate tracking the location every `distanceFilter` meters.

If you want to bypass the automatic motion detection system, you’re free to execute `changePace(true)`

**Comment by 0xecute** [comment]
Hi,
Thank you for your replies. I have now my application on the stores with lot of users! But some users still have some issues.
A bit of help would be really appreciated! :)
What I basically need should be really simple for this plugin, considering all the great and crazy work that has been done.
My scenario:
A user click on "Play", it will starts to track its path. I need at that moment to add the first marker, it is important (can't wait 200 meters for example). And I need to have the IOS ask for "Always" permissions if it is not done.
I use a "onLocationUpdate" method to handle GPS position (no need to have them in sqlite DB or anything), no need to call external API, nothing. At the moment I just get the position, add to a list, and save to SharedPreference (will be update to sqlite when I have time).

Of course, the user can switch the app in background and foreground, it should not impact the tracking.

At the moment I have this:
```
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      debug: false,
      distanceFilter: 20,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      stopOnTerminate: true,
      startOnBoot: false,
    ))
```
But it is not working well:
[Tracking](https://api.play-dogs.ch/image/get/walk?src=983.jpg)
There is 2 big lines without tracking, but the rest of the walk is fine.

Can you help me to create a basic config for this specific feature? I read your doc but there are so many functionalities (headless, schedule, motion sensor, etc...) I can't find a suitable config.

Thank you so much in advance! I really appreciate your help!

**Comment by christocracy** [comment]
Yes, the plugin's performance initiating tracking in rural environments will not be nearly as good as urban environments flooded with Wifi signals.

The iOS can only detect when a device is moving when it exits a geofence around the last known position.  iOS (and Android) geofence triggers are completely handled by the OS and use only Wifi & Cell tower geolocation to trigger events (ie: not GPS).

In a rural environment, there will be low probability of a Wifi geolocation so only cell tower change event will trigger a geofence exit (1000 meters or more).

**Comment by christocracy** [comment]
>A user click on "Play", it will starts to track its path.

If you do have a UI to initiate tracking (like a Jogging app), you can explicitly place the plugin into the *moving* state via `BackgroundGeolocation.changePace(true)`, bypassing the need for *stationary geofence exit*.

```dart
await bg.BackgroundGeolocation.start();
// Force moving state immediately.  Plugin will now begin recording a location each distanceFilter meters.
await bg.BackgroundGeolocation.changePace(true);
```

**Comment by christocracy** [comment]
You should also take care to configure `stopTimeout` appropriately.  If the device remains stationary (eg: user stops to pick berries in forest) the `stopTimeout` timer will expire and the plugin will enter the *stationary* state, create a geofence around the current location and go to sleep.

**Comment by 0xecute** [comment]
Hi,
Thank you for the quick reply. 
ChangePace is better for the first marker, thanks. 
Considering the timeout you are speaking about, it may be possible that in the image I shared, it is what happened.
Can I disable completely this timeout so it never goes to sleep?
Usually user will start and stop the tracking, so no need to have GPS tracking to stop.

Thanks

**Comment by christocracy** [comment]
>Can I disable completely this timeout so it never goes to sleep?

Like I said "take care to set it appropriately".  If setting `stopTimeout` to `12*60` (12 hours) is appropriate for you, so be it.

**Comment by 0xecute** [comment]
Understood
