### ISSUE TITLE
HTTP POST Schema Batch

### ISSUE THREAD

**Issue by ptv1p3r** [transistorsoft/flutter_background_geolocation#176]
Can you please provide a example of the json post with a batch?
I got it working without using batch, after some investigation on the Schema used, but i can't find a example of the json data in a batch post.

**Comment by christocracy** [comment]
```javascript
{
  "locations": [   // <-- Config.httpRoot (default "locations")
    {Location}, {Location}, {Location}, ...
  ]
}
```

**Comment by ptv1p3r** [comment]
Hi again,
with batchSync: false all is ok, but with batchSync: true, and using as you told me a json batch post like this (on postman to eval):
{
	"locations": [
		{
		"location": {  
		    "coords": {
		        "latitude": 1.23232323,
		        "longitude": -1.37373737,
		        "accuracy": 12.0,
		        "speed": 0.25,
		        "heading": 100.0,
		        "altitude": 22.0
		    },
		    "activity": {
	            "type": "still",
	            "confidence": 99.0
        	},
		    "battery": {
	            "level": 10.0,
	            "is_charging": true
	        },
	         "odometer": 13.2,
	         "timestamp":"2015-05-05T04:31:54.123Z",
	         "event": "sdsd"
			}
		},
		{
		"location": {  
		    "coords": {
		        "latitude": 2.23232323,
		        "longitude": 2.37373737,
		        "accuracy": 12.0,
		        "speed": 0.25,
		        "heading": 100.0,
		        "altitude": 22.0
		    },
		    "activity": {
	            "type": "still",
	            "confidence": 99.0
        	},
		    "battery": {
	            "level": 10.0,
	            "is_charging": true
	        },
	         "odometer": 12.2,
	         "timestamp":"2015-05-05T04:31:54.123Z",
	         "event": "sdsd"
			}
		}
	]
}
On postman this example works fine, but by the sdk it doesn't, is there something missing on the json that i'm not including for testing ?

**Comment by christocracy** [comment]
That’s not correct.

Each {} within the enclosing [] is simply a location {Location}.

It’s not a `{location: {Location}}`

**Comment by ptv1p3r** [comment]
ah.. like this? : 
{
"locations": [
{
"coords": {
"latitude": 1.23232323,
"longitude": -1.37373737,
"accuracy": 12.0,
"speed": 0.25,
"heading": 100.0,
"altitude": 22.0
},
"activity": {
"type": "still",
"confidence": 99.0
},
"battery": {
"level": 10.0,
"is_charging": true
},
"odometer": 13.2,
"timestamp":"2015-05-05T04:31:54.123Z",
"event": "sdsd"
},
{
"coords": {
"latitude": 2.23232323,
"longitude": 2.37373737,
"accuracy": 12.0,
"speed": 0.25,
"heading": 100.0,
"altitude": 22.0
},
"activity": {
"type": "still",
"confidence": 99.0
},
"battery": {
"level": 10.0,
"is_charging": true
},
"odometer": 12.2,
"timestamp":"2015-05-05T04:31:54.123Z",
"event": "sdsd"
}
]
}

**Comment by christocracy** [comment]
Yes.

FYI to enable multi line syntax highlighting, wrap code in triple-backticks

**Comment by ptv1p3r** [comment]
Thank you for you response, we are developing a software and trying to integrate your plugin, if all goes well, we will be your customers.

**Comment by ptv1p3r** [comment]
Still no joy, one question, the coords still remain ? or should i remove them like the location ?
`{
	"locations": [
		{
		    "coords": {
		        "latitude": 1.23232323,
		        "longitude": -1.37373737,
		        "accuracy": 12.0,
		        "speed": 0.25,
		        "heading": 100.0,
		        "altitude": 22.0
		    },
		    "activity": {
	            "type": "still",
	            "confidence": 99.0
        	},
		    "battery": {
	            "level": 10.0,
	            "is_charging": true
	        },
	        "odometer": 13.2,
	        "timestamp": "2015-05-05T04:31:54.123Z",
	        "event": "sdsd"
		},
		{
		    "coords": {
		        "latitude": 2.23232323,
		        "longitude": 2.37373737,
		        "accuracy": 12.0,
		        "speed": 0.25,
		        "heading": 100.0,
		        "altitude": 22.0
		    },
		    "activity": {
	            "type": "still",
	            "confidence": 99.0
        	},
		    "battery": {
	            "level": 10.0,
	            "is_charging": true
	        },
	        "odometer": 12.2,
	        "timestamp": "2015-05-05T04:31:54.123Z",
	        "event": "sdsd"
		}
	]
}`

**Comment by christocracy** [comment]
See wiki:
https://github.com/transistorsoft/flutter_background_geolocation/wiki/Location-Data-Schema

**Comment by ptv1p3r** [comment]
yes that was exactly my starting point... without the batch it's functional, i'm just struggling with this on batch request, can really figure out what i'm doing wrong...

**Comment by christocracy** [comment]
Why don’t you just log the plugin’s batch request to your server logs and look at it?

**Comment by ptv1p3r** [comment]
cant access the server and the connection api directly... there should be a example for this exactly in the page you mention, as there's for a non batch.. the only thing there is a footnote: location is an array for batched requests ... with an example this would be way easier for me...

**Comment by christocracy** [comment]
The only difference with a batch request is the presence of a containing `[]`

**Comment by ptv1p3r** [comment]
it has something differenty then this i'm sure :
`{ "locations": [ { "coords": { "latitude": 1.23232323, "longitude": -1.37373737, "accuracy": 12.0, "speed": 0.25, "heading": 100.0, "altitude": 22.0 }, "activity": { "type": "still", "confidence": 99.0 }, "battery": { "level": 10.0, "is_charging": true }, "odometer": 13.2, "timestamp": "2015-05-05T04:31:54.123Z", "event": "sdsd" }, { "coords": { "latitude": 2.23232323, "longitude": 2.37373737, "accuracy": 12.0, "speed": 0.25, "heading": 100.0, "altitude": 22.0 }, "activity": { "type": "still", "confidence": 99.0 }, "battery": { "level": 10.0, "is_charging": true }, "odometer": 12.2, "timestamp": "2015-05-05T04:31:54.123Z", "event": "sdsd" } ] }`, because this works when i test on postman..

**Comment by christocracy** [comment]
What is the server complaining about?   What do the server logs say?

Or listen to onHttp event and log the response.

**Comment by ptv1p3r** [comment]
Í did, it gives me a 500, but i know that the problem is on the json schema, with only one location all is working...
I did come around and found this : https://github.com/transistorsoft/react-native-background-geolocation/issues/124

There it says `{
    "location": [
        {
            ...
        }
    ]
}` for batch, and `{
    "location": {
        ...
    }
}` for single, but above you sai it should be locations for batch, and location for single.. could that be the problem ?

**Comment by christocracy** [comment]
Yes.  The httpRootProperry default is “location”.  It doesn’t pluralize automatically because of batchSync.

You’re free to configure your own httpRootProperry as desired.
