### ISSUE TITLE
iOS requires "Always" to allow tracking in the Background?

### ISSUE THREAD

**Issue by fne00** [transistorsoft/flutter_background_geolocation#180]
## Your Environment
* Plugin version:   
  flutter_background_geolocation: ^1.2.4
  background_geolocation_firebase: ^0.1.0
* Platform: iOS 
* OS version: 13.3
* Device manufacturer / model: App iPhone X
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.8)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.Config bgConfigToApply;
    if (globalSharedPrefs.getBool('GPSBatSave')) {  // turn off after 10 mins
      bgConfigToApply = bg.Config(
          persistMode:
          saveToBGsqlDBandLiveTrack,
          // Set live tracking - if data is persisted to the BG SQL DB then it is uploaded
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 0.0,
          // no min distance
          locationUpdateInterval: 0,
          // no min time
          fastestLocationUpdateInterval: 200,
          // 200mS max rate of new data points - 0 is not recommended
          useSignificantChangesOnly: false,
          stopOnTerminate: true,
          // will stop recording when crash/terminate
          startOnBoot: false,
          foregroundService: true,
          // Android only - defaults to true for >Android 8.0 - mandatory
          enableHeadless: true,
          // Ignored because I have stopOnTerminate
          stopTimeout: 10,
          // 10 mins - if stationary for >10mins stops until movement is detected again
          debug: false,
          autoSync: false,
          // auto upload of track for live tracking
          url: 'http://xxxxxx:9000/locations/$username',
          params: loggingData,
          logLevel: logLevel,
          logMaxDays: 2,
          reset: true);
    } else
      {
        bgConfigToApply = bg.Config(  // more aggressive recording - no turn off
            persistMode:
            saveToBGsqlDBandLiveTrack,
            // Set live tracking - if data is persisted to the BG SQL DB then it is uploaded
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0.0,
            // no min distance
            locationUpdateInterval: 0,
            // no min time
            fastestLocationUpdateInterval: 200,
            // 200mS max rate of new data points - 0 is not recommended
            useSignificantChangesOnly: false,
            stopOnTerminate: true,
            // will stop recording when crash/terminate
            startOnBoot: false,
            foregroundService: true,
            // Android only - defaults to true for >Android 8.0 - mandatory
            enableHeadless: true,
            // Ignored because I have stopOnTerminate
            disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,

            //stopTimeout: 10,
            // 10 mins - if stationary for >10mins stops until movement is detected again
            debug: false,
            autoSync: false,
            // auto upload of track for live tracking
            url: 'http://xxxxxxxxxx:9000/locations/$username',
            params: loggingData,
            logLevel: logLevel,
            logMaxDays: 2,
            reset: true);

      }
```

## Expected Behavior

The App is an exercise App somewhat like Strava, with the addition that the App alerts the user when they have arrived at various locations and keeps score of these visits. The user, taps a Start button and the App turns off tracking when the user arrives at the finish location. No tracking is required before Start and after Finish, but the App aims to allow tracking (and alerts and scoring functions) to continue when the phone is asleep.

## Actual Behavior

It seems that to keep tracking whilst asleep requires "Always"  location permissions. My old iOS native App seems to be able to get away with "While Using". 

Does flutter_background_geolocation/background_geolocation_firebase need "Always" permission to achieve the expected behaviour (or potentially I am triggering that requirement through something I am doing in my own code(?))

## Steps to Reproduce

1. Start App with iOS location permission "Always"
2. Change permission setting to "While using"
3. Dialog appears: Background location is not enabled. To use background location, you must enable 'Always' in the Location Services settings

## Context

I am aiming to have App behaviour as described above (between Start and Stop), with no tracking after the App has been terminated.
I am trying to achieve this without the user needing to give "Always" permission (raising concerns about ongoing tracking outside of the period of direct use in the exercise period.)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationRequest`

**Comment by fne00** [comment]
Chris, thanks. Sorry I missed that one. I'll test the change to my App in the next day.

**Comment by fne00** [comment]
All good! Thanks Chris.
Peter
