### ISSUE TITLE
Best way to implement simple GPS Status Indictor

### ISSUE THREAD

**Issue by fne00** [transistorsoft/flutter_background_geolocation#184]
Suggestion please on how to achieve a simple GPS status indicator in the status bar of my App. That is, something like: Green (GPS Fix), Yellow (Searching), Red (Gps Off).

## Your Environment
* Plugin version: 1.6.1
* Platform: iOS and Android
* OS version: Any
* Device manufacturer / model: Any

```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

After doing `bg.BackgroundGeolocation.start()` have a function that updates the status of a traffic-light indicator of GPS status. This is like you have on a GPS-watch or an App like 'GPS Test' (Android).

## Actual Behavior

The approach I am considering is:
- Status is Red before .start() and after .stop()
- Otherwise I would monitor the time since the most recently received location (received in `onLocation()` ) and if greater than 2-3 seconds turn indicated to yellow (Searching), otherwise it is Green.

Is there a better way?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Can’t detect “searching”, only enabled / disabled.

See event #onProviderChange.
