### ISSUE TITLE
Use same motion-detection method on Android and iOS

### ISSUE THREAD

**Issue by casper-k** [transistorsoft/flutter_background_geolocation#185]
As far as I understand, the Android and iOS motion-detection methods are different for Android and iOS for your plugin. Android uses activity events to know if the user is moving, instead of using a geofence on iOS.

For my app, I'm detecting how the user is travelling; by car, bicycle or on foot. Most of the time, the user is at a fixed location, e.g. home or office. While testing your plugin, I found that motion tracking is also engaged when the user is walking around the office, which is not required in my case. I'm wondering if there's a more battery efficient way for my use-case (I also want to avoid displaying the notification message as much as possible). In the ideal situation, the app starts tracking when the user leaves the building. It doesn't matter much if the first 150 m is missing.

My question is as follows: is using a geofence a more battery-friendly option for this, so creating a geofence when entering stationary mode without using the activity events, and if so, how can this be accomplished reliably on Android?

**Comment by christocracy** [comment]
Yes, I've been considering a configuration to decrease false positive while roaming around the house.  I'm thinking of creating a oneshot timer of configurable delay (eg: `10000ms`) after a motion-type activity is detected (eg: 'on_foot`).  If the activity transitions back to `still` before the oneshot expires, the motionchange transition will be cancelled.

In the meantime, when `onMotionChange` event fires with `isMoving: false`, you could:
1.  `#addGeofence` around current location with `identifier: 'STATIONARY`, radius: 200`.
2.  `#startGeofences`
3.  When `#onGeofence` exit fires for that geofence, you `#start`.

**Comment by casper-k** [comment]
> In the meantime, when onMotionChange event fires with isMoving: false, you could:

Right, but what happens when the user moves outside of the stationary geofence whilst their device is turned off? I tested this with my app, and it seems that the geofence exit event doesn't fire when the device is turned on again outside of the geofence.

**Comment by casper-k** [comment]
I just tested this in the field, and this is exactly what happens. No geofence exit is happening if the phone is booted outside of the geofence area.

This following code seems to fix this. I register to the `bg.Event.LOCATION` headless event, and when I receive a location, I manually determine if the new location lies outside of the geofence radius (100 meter), if so, I switch to full tracking. This works because when the plugin it booted, it seems to always acquire a location (in both `trackingMode`'s).

Can you confirm that this is the way to go, and point me to pitfalls?
```
void handleLocation(bg.Location location) async {
  final state = await bg.BackgroundGeolocation.state;
  
  if (state.trackingMode == 0) { // 0 = Geofences-only tracking

    var startTracking = false;

    // Find the STATIONARY geofence I created before.
    final geofence = (await bg.BackgroundGeolocation.geofences)
        .firstWhere((geofence) => geofence.identifier == 'STATIONARY', orElse: null);
    if (geofence != null) {

      // Calculate the distance (latlng package) between the geofence center and the current location.
      final distance = Distance().as(
        LengthUnit.Meter,
        LatLng(geofence.latitude, geofence.longitude),
        LatLng(location.coords.latitude, location.coords.longitude),
      );

      if (distance > 100) {
        // Outside of the geofence, start full tracking.
        startTracking = true;
      }
    } else {
      // No geofence found, start full tracking anyways.
      startTracking = true;
    }
    
    if (startTracking) {
      await bg.BackgroundGeolocation.start();
      await bg.BackgroundGeolocation.changePace(true);
      await bg.BackgroundGeolocation.removeGeofences();
    }
  }
}
```

**Comment by christocracy** [comment]
Yes, it look fine until I implement something in the native end.

**Comment by GOPINATHSWAMINATHAN** [comment]
I am new to flutter. Now, i am developing driver application to update the location until reaches to destination, it must be updated to firebase. Location update to firebase must happen when the activity gets destroyed or when the app is closed. If you have any example or documentation to follow, please do provide. Thanks in advance.

**Comment by christocracy** [comment]
@GOPINATHSWAMINATHAN this issue is titled *"Use same motion-detection method on Android and iOS"*.  I don't think your question is related to this issue.

**Comment by casper-k** [comment]
> I'm thinking of creating a oneshot timer of configurable delay (eg: `10000ms`) after a motion-type activity is detected (eg: 'on_foot`). If the activity transitions back to `still` before the oneshot expires, the motionchange transition will be cancelled.

Does this feature require a lot of work on your side? And is there any way I can help to get this feature landed?

**Comment by christocracy** [comment]
Try installing from branch `android-motionTriggerDelay`:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: android-motionTriggerDelay
```

```dart
BackgroundGeolocation.ready(Config(
  motionTriggerDelay: 10000 // <-- delay in milliseconds
));
```

**Comment by casper-k** [comment]
Wow thank you so much, will test it out tomorrow 💯

**Comment by casper-k** [comment]
This is what's happening on my LG G6. I included screenshots of the logs that I captured while testing. In the first test I set the **motionTriggerDelay** to 2 minutes, and the second test I set the value to 3 minutes. In both cases you can see the **still -> walking** transition at the top of the log. You can see the MOTION_TRIGGER_DELAY event happening just a fraction of a second _before_ the activity transition (marked with blue), which is not as expected.

**2 minute delay:**

![2 minute delay](https://user-images.githubusercontent.com/44575638/78167032-0d70f880-744e-11ea-8fb9-3520a406e4eb.png)

**3 minute delay:**

![3 minute delay](https://user-images.githubusercontent.com/44575638/78167035-0e098f00-744e-11ea-8775-c5ee576e261a.png)

**Comment by christocracy** [comment]
There’s nothing wrong with seeing *any* `XxxServiceDestroyed`, it normal and expected.

**Comment by christocracy** [comment]
I see nothing unusual in your logs.  It looks exactly as expected

**Comment by casper-k** [comment]
This is what I did in both cases; I walked for 10 seconds and then placed the phone on my desk (stationary).

The walk is detected (**still -> walking**, above the red line). But the stationary event (**walking -> still**) is not. Only _after_ the MOTION_TRIGGER_DELAY, the transition to stationary (marked with blue) is reported. This happens _right after_ the motion trigger delay event.

**Comment by casper-k** [comment]
Thanks for the update, this seems to solve the issue on my LG G6.

It seems that the phone is also very slow to detect whether the user is stationary. It takes a couple of minutes before the walking -> still activity event occurs from the moment that the phone is stationary. I will test again more thoroughly and with another test device.

**Comment by christocracy** [comment]
> It seems that the phone is also very slow to detect whether the user is stationary

This is unrelated to the issue and has nothing to do with the new Config.motionTriggerDelay.  

That’s purely up to the manufacturer’s flavor of Android as well as the sensors on the device (accelerometer, gyroscope, magnetometer).

**Comment by casper-k** [comment]
You're right – this is up to the manufacturer. What's your experience with this transition speed on your own test devices? If I set the delay to, let's say, 1 minute, is this is long enough to cancel out movements of ~30 seconds?

**Comment by christocracy** [comment]
I don’t know.  This is a new option and I don’t have a lot of experience with it.  You’ll need to do your own field-testing and see what works.

**Comment by christocracy** [comment]
You’re aware the Config.motionTriggerDelay affects only the trigger from *still -> moving*, right?

It has nothing to with *moving -> still*.
