### ISSUE TITLE
Geo Fence not working with signed apk

### ISSUE THREAD

**Issue by nvamsi214** [transistorsoft/flutter_background_geolocation#186]
## Your Environment
* Plugin version: v1.12.13+hotfix.7
* Platform: Android
* OS version: All
* Device manufacturer / model:
* Flutter info (`flutter doctor`):  Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: desiredAccuracy,
    distanceFilter: distanceFilter,
    stopOnTerminate: false,
    startOnBoot: true,
    //url : "https://us-central1-taskcaretest2.cloudfunctions.net/orders/saveData/${UID}",
    debug: enableDebug,
    enableHeadless: enableHeadless,
    reset: true,
    autoSync: true,
    batchSync: true,
    logLevel: enableDebug? 5 : null,
    foregroundService: true,
    heartbeatInterval: heartbeatInterval,
    extras: {
      'id1': OID,
      'id2': MID
    },
    locationUpdateInterval: locationUpdateInterval,
    fastestLocationUpdateInterval:  fastestLocationUpdateInterval,
  )).then((bg.State state) {
    if(isStart == true) {
      if (state.enabled == false) {
        if(isOverlay && Platform.isAndroid) {
          _startService();
        }
        _onClickEnable(true);
      }
    } else {
      if(isOverlay && Platform.isAndroid) {
        if(enableDebug) {
          bg.BackgroundGeolocation.emailLog("support@flockone.com");
        }
        FLog.exportLogs();
        _stopService();
      }
      _onClickEnable(false);
    }
  });

bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event){
    try {
      if (event.extras != null) {
        Map extras = event.extras;
        String category = extras.containsKey("category")
            ? extras["category"]
            : "";
        // for visits and tasks
        updateDoc(event);
      }
    } catch(e) {
      print("excep - ${e.toString()}");
    }
  });
```

## Expected Behavior

Get events when user enters or leaves the Geo Fenced location.

## Actual Behavior

Its working fine when i run the code form android studio locally. I'm getting events properly. But when i build signed apk, the events are not triggering when the user enters or leaves the location. 

We are paid users and we have a license key for location manager. Will the Geo fence work with same key or do we need to pay for this separately? can you confirm if this Is the reason for not getting the events in signed apk. If not what else will be the possible error!

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm trying to update some data when the user enters or leaves the Geo fenced location and its failing as i'm not getting events.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
If you purchased a key for your app, geofencing works.  

If you have a problem, provide logs.  Restart the device.  I test geofencing almost every day with release build on 11 devices for over 3 years.  They never fail.

**Comment by nvamsi214** [comment]
I have tried again to simulate same situation in 2 different mobiles (one with debug app and other with signed APK). Facing the same issue. I have created same Geo fencing for both mobiles and started monitoring. Attaching the logs below for reference.

[debug Logs.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/4179463/debug.Logs.txt)


[signed APK Logs.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/4179465/signed.APK.Logs.txt)

**Comment by christocracy** [comment]
The SampleApp deployed to play store is obviously a signed apk.  Please install the SampleApp from play store and test geofencing on your device (linked in readme).

Long press on map to add geofence (“Advanced app” only).

**Comment by nvamsi214** [comment]
Its not like your API is not working. It is working great, but problem i'm facing is some issue when i build Signed APK. What i'm asking is what are the possible errors that might have caused the API to fail in case of signed APK. My debug app is working perfectly fine. Please refer the above logs if you can figure out the issue.

**Comment by christocracy** [comment]
Have you looked at your logs?

```
02-10 12:19:58.813 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: EXIT
╠═════════════════════════════════════════════
╟─ sHhdFU9AKLkryf7Kfl7C
╟─ qeiKKcPT13LViAJSVV0v
╚═════════════════════════════════════════════
Geofencing Event: EXIT
╠═════════════════════════════════════════════
╟─ sHhdFU9AKLkryf7Kfl7C
╟─ qeiKKcPT13LViAJSVV0v
╚═════════════════════════════════════════════
02-10 12:19:58.814 DEBUG [TSGeofenceManager setLocation] *** isMoving: true | stateChanged: false | timerExpired: false | elapsed: 0
02-10 12:19:58.827 INFO [b persist] 
  ✅  INSERT: 8c169aa0-da78-4cd7-8d23-4f820ec56f3b
02-10 12:19:58.835 INFO [b persist] 
  ✅  INSERT: 5ce73e0e-765d-4ad4-aee6-48939d7ae555
.
.
.
02-10 12:19:58.974 INFO [GeofenceDAO destroy] 
  ✅  sHhdFU9AKLkryf7Kfl7C
02-10 12:19:58.977 WARN [GeofenceDAO destroy] 
  ⚠️  failed to find sHhdFU9AKLkryf7Kfl7C
02-10 12:19:59.040 INFO [GeofenceDAO destroy] 
  ✅  qeiKKcPT13LViAJSVV0v
02-10 12:19:59.042 WARN [GeofenceDAO destroy] 
  ⚠️  failed to find qeiKKcPT13LViAJSVV0v
02-10 12:19:59.292 DEBUG [TSGeofenceManager$b run] evaluation buffer timer elapsed
02-10 12:19:59.296 DEBUG [TSGeofenceManager c] ℹ️  Persist monitored geofences: []
02-10 12:19:59.297 DEBUG [TSGeofenceManager$3 run] 
╔═════════════════════════════════════════════
║ TSGeofenceManager found 0/10 within 1000 meters
╠═════════════════════════════════════════════
╚═════════════════════════════════════════════
```

**Comment by christocracy** [comment]
Apparently you're not using the plugin's HTTP service.  The plugin is clearly recording locations and geofence events.  If they're not arriving at your server, that's not the plugin's fault.
