### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by daviidmorales** [transistorsoft/flutter_background_geolocation#188]
I'm trying to get current position with the method `getCurrentPosition()` and it throw me this exception `[LocationError code: 499, message: null]`
I have read the documentation and cannot find documentation about this error.

Code | Error
-- | --
0 | Location unknown
1 | Location permission denied
2 | Network error
408 | Location timeout

## Your Environment
* Plugin version: ^1.4.5

**Comment by christocracy** [comment]
499 means the location request was cancelled.

**Comment by daviidmorales** [comment]
I suggest to put the code on the documentation.

**Comment by christocracy** [comment]
Added in local copy.
