### ISSUE TITLE
Refresh token used as the access token

### ISSUE THREAD

**Issue by carlmats** [transistorsoft/flutter_background_geolocation#189]
~~We are having an issue after upgrading from plugin version 1.4.x to 1.6.1.~~ When our API returns both access and refresh token from the refresh route, the plugin starts using the refresh token for subsequent requests instead of the access token. If we only return the access token everything seem to work fine.  

The API response from the refresh:

`{

    "access_token": {
        "token": "accessTokenHere",
        "token_type": "Bearer",
        "expires_in": 1581188596
    },
    "refresh_token": {
        "token": "refreshTokenHere",
        "token_type": "Refresh"
    }
}`

~~This response has worked fine on previous versions of the plugin.~~ Only on Android.

## Your Environment
* Plugin version: 1.6.1
* Platform: iOS
* OS version: 13.1
* Device manufacturer / model: IPhone 11 Pro - emulator
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
        authorization: bg.Authorization(
          strategy: "JWT",
          accessToken: access.tokenString,
          refreshToken: refresh.tokenString,
          refreshUrl: "example.com/api/v1/auth/refresh",
          refreshPayload: {"refresh_token": "{refreshToken}"},
          expires: access.expiresIn,
        ),
```

## Expected Behavior
The plugin should apply the new access token after a refresh.

## Actual Behavior
The plugin interprets the refresh token as the access token and starts using the refresh token for subsequent requests.

## Steps to Reproduce

1. Allow the access token to expire
2. Make the plugin do another request and respond with 401
3. The plugin will try to refresh the token, the API responds with the format provided above
4. The plugin will retry the request with the refresh token.

**Comment by christocracy** [comment]
Thanks.  I'm sure there are a few kinks to fix in the new `Authorization` system.  I'll have a look.  I'm on a road-trip next week.  I'll have a look the week after.

**Comment by carlmats** [comment]
Thanks for the reply. After some further testing it seems this issue is limited to IOS, on android devices it works fine strangely enough (we have yet to test on a physical IOS device). It seems downgrading the plugin did not solve the issue, it behaves the same on 1.5.0, so you can disregard my comment about it being related to the newest version. Enjoy your roadtrip, looking forward to hearing your feedback when you get back!

**Comment by christocracy** [comment]
> on android devices it works fine strangely enough

Not strange at all.  iOS and Android are essentially 2 different plugins that *happen* share a common api.

**Comment by christocracy** [comment]
I’m going to be away all week.  Could you please ping this issue on Monday?  I may forget through the flood of emails I’m going to receive while out-of-office.

**Comment by carlmats** [comment]
*Ping*

**Comment by christocracy** [comment]
I’ll be looking at this soon.

**Comment by carlmats** [comment]
In the meantime while we wait for your feedback, is there any known api response format has been tested on IOS? We have tried a few different without much success.

**Comment by carlmats** [comment]
Additional finding: When the API only returns the access token (in the provided format), the plugin manages to refresh once. On the next refresh there is no refresh token provided with the refresh request.

**Comment by christocracy** [comment]
> is there any known api response format has been tested on IOS?

It's been a couple of months since I had my head inside the new `Authorization` system, I won't know until I have a look.  I'm busy putting finishing touches releasing refactored `background_fetch` before I can post an update for `flutter_background_geolocation`

**Comment by christocracy** [comment]
And Android is **100% OK**?

**Comment by christocracy** [comment]
- Please send me an *exact* example of your *refresh token* data.
- Your *access token* must be a JWT in the format `XXX.YYY.ZZZ`

**Comment by carlmats** [comment]
> And Android is **100% OK**?

Yes, at least during our limited tests on the emulator. I will do more testing right now.


>     * Please send me an _exact_ example of your _refresh token_ data.
**Refresh token:**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODEwMTkwNDcsImlkIjoiMSIsIm5hbWUiOiJBZG1pbiBBZG1pbiIsInJvbGUiOiJBRE1JTiJ9.I6g8W-B3hlFTDAAoffVyOxKfY4feTiQogL8EJzXBDN8`

**Refresh token decoded:**

_Header:_
`{
  "alg": "HS256",
  "typ": "JWT"
}`

_Payload:_
`{
  "iat": 1581019047,
  "id": "1",
  "name": "Admin Admin",
  "role": "ADMIN"
}`

>     * Your _access token_ must be a JWT in the format `XXX.YYY.ZZZ`
**Access token**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODIyMTY5NTIsImlhdCI6MTU4MjIxNjg5MiwiaWQiOiIxIiwibmFtZSI6IkFkbWluIEFkbWluIiwicm9sZSI6IkFETUlOIn0.4dF-zMqgbmyApFeYUZp330KO37WNyt-0H8MWolmgHw4`

**Comment by carlmats** [comment]
> And Android is **100% OK**?

I've tried multiple refreshes in both regular and headless mode and in works fine everytime.

**Comment by christocracy** [comment]
Ok, I'm pretty sure I found the problem:  error in regular-expression.

**Was:**
```obj-c
@"^[A-Za-z0-9-_=]+.[A-Za-z0-9-_=]+.?[A-Za-z0-9-_.+/=]*$"
```
**Should be: (with escaped `\\.` separating JWT chunks `XXX.YYY.ZZZ`
```obj-c
@"^[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$"
```

Android's was correct:
```java
Pattern.compile("^[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$");
```

**Comment by christocracy** [comment]
I have a native iOS test-case which reproduced your reported behaviour where I returned your response from test server:
```json
{
  "access_token": {
    "token": "accessTokenHere",
    "token_type": "Bearer",
    "expires_in": 1581188596
  },
  "refresh_token": {
    "token": "refreshTokenHere",
    "token_type": "Refresh"
}
```

The test-case passes now with fixed RE.

**Comment by christocracy** [comment]
Fix will be published today or tomorrow.

**Comment by carlmats** [comment]
Super! Thanks for all your hard work on this plugin 👍

**Comment by carlmats** [comment]
Seems like the issue is still present in 1.7.0 unfortunately

**Comment by christocracy** [comment]
You installed [from master](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/README.md#or-latest-from-git)?  1.7.0 is not yet published.

**Comment by carlmats** [comment]
Yes

**Comment by christocracy** [comment]
Fetch again from master.  Maybe I forgot to re-build the iOS lib with the change.

It should pick up ff44af2856fae1921cdd9c3178eadc7924f65eca

**Comment by carlmats** [comment]
Same result as before
resolved-ref: ff44af2856fae1921cdd9c3178eadc7924f65eca

**Comment by christocracy** [comment]
With your app running in XCode and the plugin configured with verbose `logLevel`, show me the following:

```
ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found refreshToken
2020-02-21 17:53:02.991559-0500 xctest[46485:42922062] ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found refreshToken
ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found accessToken
2020-02-21 17:53:02.991720-0500 xctest[46485:42921968] ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found accessToken
ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found expires
2020-02-21 17:53:02.991885-0500 xctest[46485:42922063] ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found expires
ℹ️-[TSConfig persist] 
2020-02-21 17:53:02.992253-0500 xctest[46485:42922062] ℹ️-[TSConfig persist] 
ℹ️-[TSAuthorization resolve:success:failure:]_block_invoke 🔑 Refreshed access-token from host localhost, {
    "access_token" =     {
        "expires_in" = 1581188596;
        token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmciOiJUU0xvY2F0aW9uTWFuYWdlclRlc3RzIiwiZGV2aWNlSWQiOjksIm1vZGVsIjoiaVBob25lMTIsMyh4ODZfNjQpIiwiaWF0IjoxNTgyMzI1NTgyLCJhdWQiOiJUU0xvY2F0aW9uTWFuYWdlclRlc3RzIiwiaXNzIjoidHJhbnNpc3RvcnNvZnQiLCJzdWIiOiJpbmZvQHRyYW5zaXN0b3Jzb2Z0LmNvbSJ9.wVsmldjYDwhz7ni3quZspd2HyrAxNSsxzGbkleedCLV_Xc1swzd7QAwphcA3gIGwBexzcvdjjTUKDcdoJhRpJFaYm_E87ADGmKGZRiAMHWFl7SSLHUWgEsRq_jbRSXYEnIyBOhS3AaY6Sblx8zODCUPkZ-AM3Q2pNGd-V7fVRabhP9N-xks2rwAaLjUNSOmN2g-uWRVcoXnwogZq6Jnh74kakHMwuxnsFT_oI5cF8l2KXxfdN0gFKLyxjfVLD87uPCVqTH-1EAXiGWfauyJ8bVaxnN47EGUiZ-8PgN_r9_NvTuPrPyfbNxqLrbHAklwyee0rAs0GCRQ007fZgPAbZg";
        "token_type" = Bearer;
    };
    "refresh_token" =     {
        token = ee94e6d741b64e3e394a97152d33f618;
        "token_type" = Refresh;
    };
}
```

**Comment by christocracy** [comment]
And if you listen to `onAuthorization`, you can log the `getState()` and read the current `state.authorization` to see what it applied to itself:

```javascript
BackgroundGeolocation.onAuthorization(async (event) => {
  let state = await BackgroundGeolocation.getState();
  console.log('*********** state.authorization: ', state.authorization);
});
```

**Comment by carlmats** [comment]
ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found accessToken
2020-02-22 00:18:16.409229+0100 Runner[83539:4949465] ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found accessToken
ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found expires
2020-02-22 00:18:16.409453+0100 Runner[83539:4949067] ℹ️-[TSAuthorization applyResponseData:data:] 🔑 Found expires
ℹ️-[TSConfig persist] 
2020-02-22 00:18:16.409689+0100 Runner[83539:4949067] ℹ️-[TSConfig persist] 
ℹ️-[TSAuthorization resolve:success:failure:]_block_invoke 🔑 Refreshed access-token from host 127.0.0.1, {
    "access_token" =     {
        "expires_in" = 1582327156;
        token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODIzMjcxNTYsImlhdCI6MTU4MjMyNzA5NiwiaWQiOiIxIiwibmFtZSI6IkFkbWluIEFkbWluIiwicm9sZSI6IkFETUlOIn0.awAyJwBuBQwO09CYbjPx8lu8ivb3H5YEP9A381NdGW0";
        "token_type" = Bearer;
    };
    "refresh_token" =     {
    2020-02-22 00:18:16.409901+0100 Runner[83539:4950510] ℹ️-[TSAuthorization resolve:success:failure:]_block_invoke 🔑 Refreshed access-token from host 127.0.0.1, {
    "access_token" =     {
        "expires_in" = 1582327156;
        token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODIzMjcxNTYsImlhdCI6MTU4MjMyNzA5NiwiaWQiOiIxIiwibmFtZSI6IkFkbWluIEFkbWluIiwicm9sZSI6IkFETUlOIn0.awAyJwBuBQwO09CYbjPx8lu8ivb3H5YEP9A381NdGW0";
        "token_type" = Bearer;
    };
    "refresh_token" =     {
        token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODEwMTkwNDcsImlkIjoiMSIsIm5hbWUiOiJBZG1pbiBBZG1pbiIsInJvbGUiOiJBRE1JTiJ9.I6g8W-B3hlFTDAAoffVyOxKfY4feTiQogL8EJzXBDN8";
        "token_type" = Refresh;
    };
}
    token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODEwMTkwNDcsImlkIjoiMSIsIm5hbWUiOiJBZG1pbiBBZG1pbiIsInJvbGUiOiJBRE1JTiJ9.I6g8W-B3hlFTDAAoffVyOxKfY4feTiQogL8EJzXBDN8";
        "token_type" = Refresh;
    };
}

**Comment by christocracy** [comment]
I see the problem.  You're using an unexpected `refresh_token` that takes a similar form to a JWT (`XXX.YYY.ZZZ`).

I was expecting just a random hash, like [here](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/)

![](https://dl.dropbox.com/s/pvvta0ov3u9rdo9/Screenshot%202020-02-21%2018.31.30.png?dl=1)

**Comment by christocracy** [comment]
The plugin is recursively iterating the returned response from you server.  It has a specific RegExp to detect "access_token" of form `XXX.YYY.ZZZ`.

```obj-c
static NSString * const JWT_ACCESS_TOKEN_PATTERN    = @"^[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$";
static NSString * const REFRESH_TOKEN_PATTERN       = @"^[A-Za-z0-9-_=]+$";
```

The plugin first search for `access_token`, then `refresh_token`.  Each of these RegExp will match either of your `refresh_token` and `access_token`.  The plugin is `access_token` iterator is capturing your `refresh_token` and saying "found it".

Can you change your `refresh_token` format to not look like a JWT `XXX.YYY.ZZZ`?

**Comment by carlmats** [comment]
> Can you change your `refresh_token` format to not look like a JWT `XXX.YYY.ZZZ`?

Ah I see, thanks! I'll change the refresh token format and see if it helps.

**Comment by christocracy** [comment]
And in my test-server, I mocked only your data-structure but not the actual data:

```javascript
    const accessToken = sign(jwtInfo);
    const refreshToken = crypto.createHash('md5').update(accessToken).digest('hex');

    let data = {
      "access_token": {
        "token": accessToken,
        "token_type": "Bearer",
        "expires_in": 1581188596
      },
      "refresh_token": {
        "token": refreshToken,
        "token_type": "Refresh"
      }
    };
```

**Comment by christocracy** [comment]
As for Android working, it's probably just luck that the iterator stumbles upon your access-token before the refresh-token, where in iOS the order is reversed.

**Comment by carlmats** [comment]
Confirmed to be working at my end aswell. Thanks for the support!

**Comment by christocracy** [comment]
The iterator *could* get some added intelligence here, to *at least* detect if both RegExp happen to match the same value.

In your case, had it detected that, it would’ve seen a difference in length and perhaps swapped the larger one into `accessToken`, but...

The docs need an update here to require that refreshToken not resemble a JWT.
