### ISSUE TITLE
Dependency on  to old device_info

### ISSUE THREAD

**Issue by fvisticot** [transistorsoft/flutter_background_geolocation#19]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: 12
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config

## Expected Behavior

No compilation error
## Actual Behavior

Because tibib depends on flutter_background_geolocation ^0.2.3 which depends on device_info ^0.2.1, device_info ^0.2.1 is required.
So, because tibib depends on device_info ^0.3.0, version solving failed

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

Because tibib depends on flutter_background_geolocation ^0.2.3 which depends on device_info ^0.2.1, device_info ^0.2.1 is required.
So, because tibib depends on device_info ^0.3.0, version solving failed

**Comment by christocracy** [comment]
In the meantime, you could clone the repo, simply edit the dependency and install from your local file-system.

**Comment by christocracy** [comment]
Published `0.2.4` with updated `device_info: `0.3.0`
