### ISSUE TITLE
Change Tracking Settings when app changes state

### ISSUE THREAD

**Issue by Thibault2ss** [transistorsoft/flutter_background_geolocation#191]
Hi ! 
I just purchased the license, and I'm posting this issue more as an "advice request" rather than an actual issue. Hence why I'm not really following your issue template (sorry for that).

For my app, I would like minimum battery consumption (obviously... ) , under those constraints:
- when app is open, I would like my user tracking to be rather precise (like on Google maps for example). To do this, I set the radius to 10 meters, works just fine.
- when app in background or killed, I want to be able to track user without needing to be that precise (300-500 meters is enough) in order to dramatically save battery (because my app tracks users all day, and if they move a lot, it can be quite expensive for the battery...)

I saw there's an option to track only significant changes. It seems perfect (instead of changing myself the radius and speedfactor), so I need to change settings when user opens the app , or when he puts it in the background or kill it. 

Questions :
- What's the best way to do that regarding your plugin's philosophy of operation ?
- Any useful advice in order to save maximum battery while tracking users with ~400 meters precision ? I've thought of limiting location records to 1 (I don't necessarily need to keep records of user paths), batchUpdates, is there anything else ?

Thanks in advance !

## Your Environment
* Plugin version: 1.6.1
* Platform: iOS and Android
* ~~OS version: ~~
* ~~Device manufacturer / model:~~
* Flutter info (`flutter doctor`):
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.6-pre.25, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.0)
[✓] Connected device (1 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
            reset: true,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: distanceFilter,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: !kReleaseMode,
            logLevel: 0,
            logMaxDays: 1,
            // firestore enpoint setup
            url: firestoreEndpoint,
            method: firestoreHttpMethod,
            params: {"userId": firebaseUser.uid},
            locationTemplate: null,
            headers: firestoreHeaders,
            encrypt: true)
```

## Expected Behavior
when app is in background or killed, use useSignificantChangesOnly: true

## Actual Behavior
Not implemented

## ~~Debug logs~~

**Comment by christocracy** [comment]
(Sorry, I missed this.  I was out on business trip then vacation in Feb.)

Simple:  listen to `AppLifecycleState` and use `BackgroundGeolocation.setConfig` as desired.
