### ISSUE TITLE
Using AWS Cognito/IAM authorized HTTP endpoint?

### ISSUE THREAD

**Issue by chris** [transistorsoft/flutter_background_geolocation#193]
This is a question or feature request...

I'm needing to send the location events to an AWS API Gateway HTTP endpoint that is protected by AWS' Cognito IAM authorization. This requires using the [AWS Signature Version 4](https://docs.aws.amazon.com/apigateway/api-reference/signing-requests/) signed requests. From what I can tell, there is no way to do this with the flutter_background_geolocation HTTP and Authorization system (currently). I am wondering if there's a way for me to provide a function that can send the events instead of using what's built in, or maybe a way to provide a custom Authorization class or similar? The AWS signing requires knowing the payload (as having a hash of that is part of their signing process), as well as setting the date header to the current time, so I can't just add the regular `headers` attribute to the `Config` to make auth work (at least in any way I know of).

I didn't include the regular issue template stuff as didn't seem applicable. But, I'm using version 4.0.4 of the plugin, and would like this for both iOS and Android. If you have any guidance or suggestions, let me know.

**Comment by christocracy** [comment]
It seems this could be done by implementing a new `Authorization.strategy: AWS`.  Currently, the only supported strategy is `JWT`.

**Comment by chris** [comment]
I will take a look. I'm presuming that none of this would be platform specific, and as such, all the code I'd need to modify/access to support it is part of this repo. I'm newer to Dart and Flutter, and this is not my primary work at the moment, so no idea when I'll get to it. If there's any documentation, guidance/suggestions, or other aspects you think may be helpful , let me know.

**Comment by christocracy** [comment]
It might be nice for the plugin to be able to accept a custom `Authorization` instance at the iOS/Android api level.

This wouldn't be dart-code.  It'd be Ojb-c & Java.
