### ISSUE TITLE
How to change location object sended

### ISSUE THREAD

**Issue by Jack74r** [transistorsoft/flutter_background_geolocation#196]
Hello,
I would like to know if it is possible to modify the location object to match my api ? 
Or it's possible to call it's own method of sending it to the server ?

**Comment by christocracy** [comment]
See API docs `Config.locationTemplate`.  Also read the "HTTP Guide" linked throughout.

**Comment by Jack74r** [comment]
Thank but i have complex object (multiple relation) to my rest API. 
I'm not comfortable with that, It's not possible to serialize object or override method ?

**Comment by christocracy** [comment]
> It's not possible to serialize object or override method ?

No.

**Comment by Jack74r** [comment]
That could be an improvement, couldn't it?
