### ISSUE TITLE
Foreground tracking service gets killed

### ISSUE THREAD

**Issue by Mantas0726** [transistorsoft/flutter_background_geolocation#20]
## Your Environment
* Plugin version: 1.0
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: OnePlus 5 A5000
* Flutter info (`flutter doctor`): `[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-GB)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Mantoska\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • ONEPLUS A5000 • 8d2fc732 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
`
* Plugin config

## Expected Behavior
Service should persist until stopped manually.

## Actual Behavior
Service gets killed in different time intervals in my case: after ~1h, ~12h

## Steps to Reproduce
I have completely killed the app and had the phone locked.

**Comment by christocracy** [comment]
Show me a screenshot of your device's `Settings->Battery` screen.

**Comment by Mantas0726** [comment]
https://m.imgur.com/i2a0Wlq

**Comment by christocracy** [comment]
Show me **Battery Optimization** screen.

**Comment by Mantas0726** [comment]
https://m.imgur.com/4FcLCpe

**Comment by christocracy** [comment]
Select the app (Flutter Background Geolocation?) and she me that screen.

**Comment by Mantas0726** [comment]
https://m.imgur.com/o38nXGA

Ok.. Will try with optimization off

**Comment by christocracy** [comment]
There you go, that should do it.  That screen is not a standard Android screen; it's provided by the manufacturer "OnePlus".  Chinese devices all do this, they're *the worst*; like a nanny state.  This behaviour even [causes music player / podcast apps to stop playing audio](https://www.google.com/search?q=OnePlus+music+player+stops&rlz=1C5CHFA_enCA816CA816&oq=OnePlus+music+player+stops&aqs=chrome..69i57.5309j1j7&sourceid=chrome&ie=UTF-8), since audio-players also run as a foreground-service.

**Comment by Mantas0726** [comment]
The service keeps on crashing even with the optimization off.

**Comment by christocracy** [comment]
This is not “crashing”, unless you have a stacktrace showing that.  It’s the Manufacturers OS terminating it.

**Comment by christocracy** [comment]
See https://dontkillmyapp.com.  I now own a OnePlus 5T.  I do not experience the foreground service being killed.

[Here's 10 days of field-testing](http://tracker.transistorsoft.com/transistor-flutter?device=Flutter-ONEPLUS-A5010-8-1-0&end=2019-2-15&start=2019-2-5)
