### ISSUE TITLE
Why are Push Notifications being requested when the plugin is initialized?

### ISSUE THREAD

**Issue by emaddoma** [transistorsoft/flutter_background_geolocation#203]
## Your Environment
* Plugin version: 1.7.0
* Platform: iOS
* OS version: 13.3
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`): 

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
    });

    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: DEBUG,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        debugPrint('BACKGROUND LOCATION READY');
        setState(() {
          _bgReady = true;
        });
      }
    });
```

## Expected Behavior
Request to authorize push notifications should not be made

## Actual Behavior
Request to authorize push notifications are made

## Steps to Reproduce

1. Initialize the plugin

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
These are not *push* notifications, they're local-notifications there to assist you during development, engaged with `debug: true`.

Obviously you won't submit your app to Apple with `debug: true`, so the plugin won't request *Notifications* permission.
