### ISSUE TITLE
Custom API call when onLocation is fired

### ISSUE THREAD

**Issue by jacobokoenig** [transistorsoft/flutter_background_geolocation#204]
Hi, I would like to know if its possible to send an API call using Firebase's SDK while getting a location on the background. My idea is that when location changes, I create a document like so:

```
bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
      Firestore.instance
          .collection('motion')
          .document()
          .setData({'createdAt': DateTime.now()});
    });
```

Is this possible?

**Comment by christocracy** [comment]
You’re free to do whatever you wish in your own callbacks.

You will, of course, need to implement a headless-task for the terminated state, if you’re using stopOnTerminate: false.
