### ISSUE TITLE
Tracking Background Service

### ISSUE THREAD

**Issue by tegarkurniawan** [transistorsoft/flutter_background_geolocation#21]
## Your Environment
* Plugin version:^0.2.4
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Vivo V9
* Flutter info (`flutter doctor`):
* Plugin config

## Expected Behavior
Tracking Background service

## Actual Behavior
no

## Steps to Reproduce
1.
2.
3.
4.

## Context
I want to run latitude and longitude tracking when the application exits or runs on the background service I have tried like this https://pastebin.com/XJ89bSRx
but just once the location is running and not running on the background service is there an example for my problem? and whether when uploading to PlayStore, must I buy the license plugin?

## Debug logs
no debug

**Comment by christocracy** [comment]
Set reset: true.  See docs for #ready on why you want to use that while developing.

**Comment by christocracy** [comment]
And yes, Android is fully functional in debug builds only until you purchase a license.

**Comment by tegarkurniawan** [comment]
ok, does this plugin support when the app kills?
