### ISSUE TITLE
Floating positions when there is no internet

### ISSUE THREAD

**Issue by joaofjunior** [transistorsoft/flutter_background_geolocation#212]
## Your Environment
* Plugin version: ^1.5.0
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung A20
* Flutter info (`flutter doctor`): 
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [versÃ£o 10.0.18362.720], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.43.2)
[√] Connected device (2 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: false,
            allowIdenticalLocations: false,
            disableElasticity: true,
            foregroundService: true,
            isMoving: true,
            logLevel: bg.Config.LOG_LEVEL_INFO,
            reset: true)
```

## Expected Behavior
Get the user's location every 10 meters. The user keeps the app open during the journey.

## Actual Behavior
By the tests performed, he takes the positions correctly while he has internet ... when he is on a road without internet the positions are fluctuating ... See attached image

Image:
[https://ap.imagensbrasil.org/image/rC2EDj](https://ap.imagensbrasil.org/image/rC2EDj)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
Gps doesn’t require a network to work.  It only needs an unobstructed view of the sky to connect to gps satellites in space.

Check device settings->location.

**Comment by joaofjunior** [comment]
The location option is active, not least because the app takes the location, but in some cases (not all) it takes points outside the route taken.

In the API documentation we have the following:
DESIRED_ACCURACY_HIGH GPS + Wifi + Cellular Highest power; highest accuracy

Is there an order for him to take it?
Is there any option for him to take only the GPS?

**Comment by christocracy** [comment]
> Is there any option for him to take only the GPS?

No.  The operating system does this automatically, providing the best available location.
