### ISSUE TITLE
How can i store locations even when device is not moving?

### ISSUE THREAD

**Issue by wemersonrv** [transistorsoft/flutter_background_geolocation#213]
## Your Environment
* Plugin version: flutter_background_geolocation: ^1.7.1
* Platform: iOS or Android
* OS version: 8
* Device manufacturer / model: Motorola Moto G 5
* Flutter info (`flutter doctor`): 

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [versÃ£o 10.0.17763.678], locale pt-BR)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.6)
> [√] VS Code (version 1.43.2)
> [√] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
        logLevel: bg.Config.LOG_LEVEL_OFF,
        disableElasticity: true,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        heartbeatInterval: 300,
        minimumActivityRecognitionConfidence: 40,
        persistMode: bg.Config.PERSIST_MODE_LOCATION,
        allowIdenticalLocations: true,
        debug: debug,
        notification: bg.Notification(
          priority: bg.Config.NOTIFICATION_PRIORITY_MIN,
          text: 'Suas horas estão sendo registradas!',
        ),
        extras: {
          'user': user, // Email do usuário
        },
      )
```

## Expected Behavior

Need to capture points even when device is not moving.

## Actual Behavior

Get location only when users walks.

## Steps to Reproduce

1. 
2. 
3.
4.

## Context

I only need to detect the user's position every X minutes, even if the device is not moving.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
implement background_fetch callback.  This plugin (also managed by Transistor Software) is already included as a dependency.

Execute BackgroundGeolocation.getCurrentPosition in your fetch callback.

**Comment by wemersonrv** [comment]
> implement background_fetch callback. This plugin (also managed by Transistor Software) is already included as a dependency.
> 
> Execute BackgroundGeolocation.getCurrentPosition in your fetch callback.

Just need to implement `background_fetch` to awake the app and run `BackgroundGeolocation.getCurrentPosition` ?

I was trying it on `heartBeat` but only works when app is working. Understand now.

One last question: We use Firestore. So need to buy license for `flutter_background_geolocation`and `background_geolocation_firebase` ?

**Comment by christocracy** [comment]
>One last question: We use Firestore. So need to buy license for flutter_background_geolocation and background_geolocation_firebase

Yes.  The `background_geolocation_firebase` adapter is optional.  You are, of course, free to manage your own firebase inserts using background-geolocation's `onLocation` event-handler in addition the a headless-task for the case where your Android app is terminated.  It just a convenience adapter to make your life easier.

**Comment by wemersonrv** [comment]
questions:

1. Headeless task can work with a normal app? or only in apps without views? Works only on Android?
2. `background_fetch` works with Android and IOS ?

**Comment by christocracy** [comment]
> Headeless task can work with a normal app? 

Any Android app that has been terminated.

>Works only on Android?

Yes, iOS has no such concept of running “headless”

**Comment by wemersonrv** [comment]
> > Headeless task can work with a normal app?
> 
> Any Android app that has been terminated.
> 
> > Works only on Android?
> 
> Yes, iOS has no such concept of running “headless”

Ok, and about `background_fetch`... solve the problem on both OS ?

**Comment by christocracy** [comment]
Fetch has similar Android headless mechanism.  If user terminates app, iOS stops firing fetch events.  You absolutely **have no ability to keep *periodically* requesting location when user explicitly terminates the app.**

However, the iOS background-geolocation plugin will automatically initiate location tracking in a terminated app when device moves about 200 meters.

**Comment by wemersonrv** [comment]
So, i cannot make my app to IOS if i expect capture user home position, if app is closed?

**Comment by christocracy** [comment]
>So, i cannot make my app to IOS if i expect capture user home position, if app is closed?

If the iOS device **is sitting stationary in the same place**, correct.  However, **once the user moves ~200 meters**, the `background_geolocation` plugin will cause the iOS app to automatically re-launch in the background and tracking will resume.  Read the API docs for `Config.stopOnTerminate`.

**Comment by wemersonrv** [comment]
Hello @christocracy  . There is a thing i don't understan.

You told me here that when device became stationary, and app closes, i can use `background_fetch` to make periodic captures in **Androi** but not in **iOS**, because `background_fetch` uses **headless** android specific feature... Ok, i understand that.

But, in background_fetch pub.dev page, it has an **iOS** badge... So, did you found a way to implement it in ios too ??

**Comment by christocracy** [comment]
Where did I tell you that?

**Comment by wemersonrv** [comment]
Here:

> If the iOS device **is sitting stationary in the same place**, correct.

**Comment by christocracy** [comment]
Where did I say:
>  to make periodic captures in Androi but not in iOS

**Comment by wemersonrv** [comment]
> Where did I say:
> 
> > to make periodic captures in Androi but not in iOS

I make a short resume about all stuffs we discuss here...  just that... 

The point is:

**Your plugin is amazing, far beyond others. This is a fact and I congratulate you for that**

But, my solution needs to capture positions every 15 (or 30) minutes even when device is in a fixed position all day. In Android is fine with `background_fetch` but in ios only when user moves ~200 meters, so i do nout found how to implement it,.. and in our interactions here i understand that is not possible in ios.

**Comment by christocracy** [comment]
iOS background_fetch *will* completely re-launch an app that was terminated by the os to service the event, just as if launched from the home-screen.  However, If the *user* terminates the app, iOS halts fetch events.  In that case, it’s *impossible* to do any time-based location tracking.

Sometimes, what you want on mobile (particularly iOS) is simply impossible.

**Comment by christocracy** [comment]
Also for iOS background_fetch, if the user doesn’t open your app daily, iOS will halt fetch events.
