### ISSUE TITLE
wrong Application.kt sample

### ISSUE THREAD

**Issue by z-dmitri** [transistorsoft/flutter_background_geolocation#215]
Application.kt file provided with sample lead to errors:

Application.kt: (16, 44): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected

Could this file be updated to the correct one?

https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode

```
package my.app.name;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
  override fun onCreate() {
    super.onCreate();
    FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
  }

  override fun registerWith(registry: PluginRegistry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**Comment by christocracy** [comment]
Show me your `AndroidManifest.xml` (redact any API keys)

**Comment by z-dmitri** [comment]
Sure

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="my.app.name">
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> 
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> 
    <application
	    tools:replace="android:label"
        android:name=".Application"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher">
		<!-- transistorsoft licence -->
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="123" />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <meta-data
              android:name="com.google.firebase.messaging.default_notification_channel_id"
              android:value="@string/default_notification_channel_id"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>			
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by christocracy** [comment]
The presence if this element means you've upgrade your app to Flutter SDK `1.12`.
```xml
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```
That means **you do not need to implement a custom `Application.kt`.  Read the [Headless Setup docs](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode#flutter--112)

![](https://dl.dropbox.com/s/xa5t6i8me5czw8s/Screenshot%202020-03-31%2010.28.57.png?dl=1)

**Delete** your `Application.kt`

**Comment by z-dmitri** [comment]
Thanks a lot,
Could I also kindly ask you why location tracking stopped in few seconds with message:
'ActivityRecognitionService destroyed'
Is there any option to continue tracking location?

```
bg.BackgroundGeolocation.onLocation((bg.Location location) {
print(location);
});
var state = await bg.BackgroundGeolocation.ready(bg.Config(
        reset: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        isMoving: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        enableHeadless: true,
        stopOnTerminate: false,
        startOnBoot: true,
      ));
      if (!state.enabled) {
        await bg.BackgroundGeolocation.start();
      }

```

**Comment by z-dmitri** [comment]
Thanks a lot,
Could I also kindly ask you why location tracking stopped in few seconds with message:
'[c.t.l.s.ActivityRecognitionService onDestroy]'
'ActivityRecognitionService destroyed'

Is there any option to continue tracking location?

```
bg.BackgroundGeolocation.onLocation((bg.Location location) {
        print(location);
});
var state = await bg.BackgroundGeolocation.ready(bg.Config(
        reset: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        enableHeadless: true,
        stopOnTerminate: false,
        startOnBoot: true,
));
if (!state.enabled) {
        await bg.BackgroundGeolocation.start();
}

```

**Comment by christocracy** [comment]
There's nothing unusual about this message:
```
[c.t.l.s.ActivityRecognitionService onDestroy] ActivityRecognitionService destroyed
```
Have you read the Wiki [Philosophy of Operation](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation)?  The plugin tracks **only when the device is moving**.

Go outside for a 1km walk.  It will track you.  When you device stops for `stopTimeout` minutes, the plugin turns of location-services and goes to sleep.

**Comment by z-dmitri** [comment]
> only when the device is moving.

**Comment by z-dmitri** [comment]
> only when the device is moving.
It is clear, I setting new location with Android emulator but BackgroundGeolocation.onLocation do nothing

**Comment by christocracy** [comment]
See the [Android section](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation#android-moving-state)

The Android plugin detects device is moving with **Motion API** (accelerometer, gyroscope, magnetometer).  It does **not** trigger from Mocked locations.  It triggers when the **Motion API** says the device is moving.  It does not care that you're mocking location, it's not even listening to them.

In emulator, you must manually change the plugin to *moving* state with `BackgroundGeolocation.changePace(true)`.

**Comment by christocracy** [comment]
The best way to test the Android plugin is on a *real* device, moving in the real world (eg: walking, car, bike).  The plugin's true *Philosophy of Operation* cannot truly be tested in the Android emulator.
