### ISSUE TITLE
iOS - Crash in SOMotionDetector.m

### ISSUE THREAD

**Issue by livotov** [transistorsoft/flutter_background_geolocation#218]
## Your Environment
* Plugin version: 1.7.0
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iPhone 7
* Flutter info:

[✓] Flutter (Channel dev, v1.15.20, on Mac OS X 10.14.6 18G1012, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] Connected device (3 available)

* Plugin config:
```dart
bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            locationUpdateInterval: 60000,
            heartbeatInterval: 60000,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            enableHeadless: true,
            logLevel: bg.Config.LOG_LEVEL_INFO,
            notification: bg.Notification(smallIcon: "drawable/ic_notification", largeIcon: "mipmap/ic_launcher", channelName: "orderStatusChanges"),
            reset: true))
```

## Expected Behavior
Crashless work

## Actual Behavior
App crashes seldom (1 user and 2 occurrences reports so far by Crashlytics for the past week) 

```
Crashed: NSOperationQueue 0x105b600f0 (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x19aac4140 objc_release + 16
1  Runner                         0x104b23874 __54-[SOMotionDetector createMotionActivityChangedHandler]_block_invoke + 240 (SOMotionDetector.m:240)
2  Foundation                     0x19b1473a0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
3  Foundation                     0x19b0510c8 -[NSBlockOperation main] + 100
4  Foundation                     0x19b149628 __NSOPERATION_IS_INVOKING_MAIN__ + 20
5  Foundation                     0x19b050d60 -[NSOperation start] + 732
6  Foundation                     0x19b14a020 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
7  Foundation                     0x19b149aec __NSOQSchedule_f + 180
8  libdispatch.dylib              0x19aa017dc _dispatch_block_async_invoke2 + 104
9  libdispatch.dylib              0x19aa4f184 _dispatch_client_callout + 16
10 libdispatch.dylib              0x19a9f7a3c _dispatch_continuation_pop$VARIANT$mp + 412
11 libdispatch.dylib              0x19a9f7190 _dispatch_async_redirect_invoke + 600
12 libdispatch.dylib              0x19aa03fa4 _dispatch_root_queue_drain + 376
13 libdispatch.dylib              0x19aa04770 _dispatch_worker_thread2 + 128
14 libsystem_pthread.dylib        0x19aa9eb48 _pthread_wqthread + 212
15 libsystem_pthread.dylib        0x19aaa1760 start_wqthread + 8
```

## Steps to Reproduce
Unknown, we were not able to get the crash on our devices. There is a single report (1 user, 2 occurrences) from the past week so far.

**Comment by livotov** [comment]
@christocracy any ideas on what can cause this?

**Comment by christocracy** [comment]
> any ideas on what can cause this?

No.  I’ve had infrequent reports of this over the past few years.  The app will relaunch and resume tracking after a crash.

However, I had a look at the code earlier in the week and made some changes which might address it.

**Comment by livotov** [comment]
@christocracy the problem this is not happening silently - the app crashes and crash error is presented. We have one user with 100% reproducibility - app collects location while he is driving the car and therefore crashes every 1...3 minute. 

We have him invited to testflight channel and can quickly supply the builds so he can test. If you have any releases/beta releases to try - we can do this.

**Comment by livotov** [comment]
it looks like both #217 and #218 are happening with this user on a constant basis
