### ISSUE TITLE
How to access this database to preview stored location List?

### ISSUE THREAD

**Issue by mohmdezeldeen** [transistorsoft/flutter_background_geolocation#219]
I want to store fetched locations in database, should i need to create local database and insert in it after on location, or i can use the database in this lib , how to access it to preview stored locations?
thanks.

**Comment by christocracy** [comment]
> should i need to create local database and insert in it after on location,

Yes.

**Comment by mohmdezeldeen** [comment]
Please let me know if i can insert fetched location by onLocation callback in my local db while app is closed, it works with my wile app working only.
thanks

**Comment by christocracy** [comment]
Are you talking about iOS or Android?  They both operate completely different in the *terminated* state.

**Comment by mohmdezeldeen** [comment]
I will implement it in both iOS and Android

**Comment by christocracy** [comment]
>Please let me know if i can insert fetched location by onLocation callback in my local db while app is closed

On Android no.  See Wiki [Android Headless Mode](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode)
