### ISSUE TITLE
notificationChannelName defaults to TSLocationManager instead of app name

### ISSUE THREAD

**Issue by artob** [transistorsoft/flutter_background_geolocation#22]
I've discovered a minor bug and/or documentation discrepancy. The `notificationChannelName` property is [documented](https://pub.dartlang.org/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/notificationChannelName.html) as:

> Defaults to your application's name from AndroidManifest.

In actuality, though, leaving this property unset makes it default to TSLocationManager, which I assume is an internal class name from the Android plugin. (See the screenshot further below.)

Setting an explicit value for the property works fine, but forgetting to set a value will produce the aforementioned surprise.

## Your Environment
* Plugin version: 0.2.4
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):  Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-US)
* Plugin config: see below

## Expected Behavior
The notification channel name should default to the app name, as [documented](https://pub.dartlang.org/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/notificationChannelName.html).

## Actual Behavior
The notification channel name defaults to "TSLocationManager".

## Steps to Reproduce

    foregroundService: true,
    //notificationChannelName: null, // no explicit channel name configured
    notificationTitle: "App name here",
    notificationText: "Sharing your location with your team.",
    notificationPriority: bg.Config.NOTIFICATION_PRIORITY_HIGH,

## Context
N/A

## Debug logs
N/A

![screenshot_20190129-145353_settings](https://user-images.githubusercontent.com/4963/51910312-85213e80-23d7-11e9-9ef6-00d3fe5aebb5.jpg)

**Comment by christocracy** [comment]
Yes, I’m aware.  There’s something about a Flutter app that prevents the lib from reading the app name from the Manifest.xml so I had to default it to TSLocationManager.

The React Native / Cordova / NativeScript versions do not have this problem.

**Comment by artob** [comment]
Thanks for clarifying, @christocracy. Not a big prob, but perhaps might be good for the docs to mention it.

**Comment by christocracy** [comment]
It was one of the first bumps I ran into while porting the Flutter version back in September.  I quickly leapt over it in favor of implementing the core functionality.

It will be revisited soon.

**Comment by DebkanchanSamadder** [comment]
I have a more major version of the issue.

the Gradle build directly throws 
```
Manifest merger failed : Attribute application@label value=(MyApp) from AndroidManifest.xml:14:9-32
	is also present at [:flutter_background_geolocation] AndroidManifest.xml:7:18-50 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:12:5-37:19 to override.
```

This is for both 0.3.4 and 1.0.0-beta.4

**Comment by christocracy** [comment]
Read carefully the Android setup docs.

**Comment by christocracy** [comment]
Specifically, [this](
https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md#androidmanifest)

**Comment by DebkanchanSamadder** [comment]
Thank you. And sorry for my negligence.
