### ISSUE TITLE
insertLocations() throws Unhandled Exception: type 'String' is not a subtype of type 'Location'

### ISSUE THREAD

**Issue by giandifra** [transistorsoft/flutter_background_geolocation#220]
## Your Environment
* Plugin version: 1.7.1
* Platform: Android 
* OS version: 10
* Device manufacturer / model: Pixel 2 XL
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B88,
    locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

## Expected Behavior
I want insert a geofence event on db with `bg.BackgroundGeolocation.insertLocation();`.

## Actual Behavior
The function throws an exception, i check the db, the record is inserted but without uuid.

## Steps to Reproduce
```
...

final map = <String, dynamic>{
      "event": "geofence",
      "is_moving": false,
      "uuid": "a6f77fd0-7438-11ea-cde6-3530e872af08",
      "timestamp": "2020-04-01T17:01:04.000Z",
      "odometer": 0,
      "coords": {
        "latitude": 42.8126475,
        "longitude": 13.7261683,
        "accuracy": 15,
        "speed": 0,
        "heading": 257.03,
        "altitude": 287.7
      },
      "activity": {"type": "still", "confidence": 100},
      "battery": {"is_charging": true, "level": 0.66},
      "geofence": {
        "identifier": "CASA",
        "action": "ENTER",
        "extras": {
          "center": {"latitude": 42.8126787, "longitude": 13.726352899999995},
          "radius": 20
        }
      },
      "extras": {}
    };

    final location = await bg.BackgroundGeolocation.insertLocation(map);
 
...

```

## Context

I trying to insert a record on db, I want save an event when user disable or enable the service.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/TSLocationManager(16875): [c.t.l.data.sqlite.b persist] 
I/TSLocationManager(16875):   ✅  INSERT: a6f77fd0-7438-11ea-cde6-3530e872af08
E/flutter (16875): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'String' is not a subtype of type 'Location'
E/flutter (16875): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:13)
E/flutter (16875): <asynchronous suspension>
E/flutter (16875): #1      BackgroundGeolocation.insertLocation (package:flutter_background_geolocation/models/background_geolocation.dart:580:33)
E/flutter (16875): #2      LocationUtils.insertFakeLocationInDb (package:diary/utils/location_utils.dart:759:53)
E/flutter (16875): #3      _MyDayAppBarState.build.<anonymous closure> (package:diary/presentation/widgets/my_day_app_bar.dart:111:33)
E/flutter (16875): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (16875): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (16875): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16875): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (16875): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (16875): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (16875): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (16875): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (16875): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (16875): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (16875): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (16875): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (16875): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (16875): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16875): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16875): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16875): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16875): #21     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (16875): #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (16875): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (16875): #24     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (16875): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (16875): 
```

</details>

**Comment by fbrus92** [comment]
> 
> ## Your Environment
> 
>     * Plugin version: 1.7.1
> 
>     * Platform: Android
> 
>     * OS version: 10
> 
>     * Device manufacturer / model: Pixel 2 XL
> 
>     * Flutter info (`flutter doctor`):
> 
>     * Plugin config:
> 
> 
> ```dart
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B88,
>     locale it-IT)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
> [✓] Android Studio (version 3.5)
> [!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
> [✓] VS Code (version 1.43.2)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> ## Expected Behavior
> 
> I want insert a geofence event on db with `bg.BackgroundGeolocation.insertLocation();`.
> ## Actual Behavior
> 
> The function throws an exception, i check the db, the record is inserted but without uuid.
> ## Steps to Reproduce
> 
> ```
> ...
> 
> final map = <String, dynamic>{
>       "event": "geofence",
>       "is_moving": false,
>       "uuid": "a6f77fd0-7438-11ea-cde6-3530e872af08",
>       "timestamp": "2020-04-01T17:01:04.000Z",
>       "odometer": 0,
>       "coords": {
>         "latitude": 42.8126475,
>         "longitude": 13.7261683,
>         "accuracy": 15,
>         "speed": 0,
>         "heading": 257.03,
>         "altitude": 287.7
>       },
>       "activity": {"type": "still", "confidence": 100},
>       "battery": {"is_charging": true, "level": 0.66},
>       "geofence": {
>         "identifier": "CASA",
>         "action": "ENTER",
>         "extras": {
>           "center": {"latitude": 42.8126787, "longitude": 13.726352899999995},
>           "radius": 20
>         }
>       },
>       "extras": {}
>     };
> 
>     final location = await bg.BackgroundGeolocation.insertLocation(map);
>  
> ...
> ```
> 
> ## Context
> 
> I trying to insert a record on db, I want save an event when user disable or enable the service.
> ## Debug logs
> Logs

In my case I want to use PERSIST_MODE_NONE to have full control of the things that are sent later., But I ran into the same error. I only managed to use the 'extras' by explicitly asking for 'getCurrentPosition'.

**Comment by fbrus92** [comment]
In my case I want to use PERSIST_MODE_NONE to have full control of the things that are sent later., But I ran into the same error. I only managed to use the 'extras' by explicitly asking for bg.BackgroundGeolocation.getCurrentPosition'.

**Comment by christocracy** [comment]
I see the problem.  
- The method isn't supposed to return a `Promise<Location>` but a `Promise<String>` (the `uuid` of the inserted location).
- The received `params` must be `Map<dynamic, dynamic>`, not `Map<String, dynamic>`

*Current*
```dart
static Future<Location> insertLocation(Map<String, dynamic> params) async {
  return await _methodChannel.invokeMethod('insertLocation', params);
}
```

*Fixed*:
```dart
static Future<String> insertLocation(Map<dynamic, dynamic> params) async {
  return await _methodChannel.invokeMethod('insertLocation', params);
}
```

Fix will likely be pushed to `master` branch today.
