### ISSUE TITLE
Location tracking streams

### ISSUE THREAD

**Issue by z-dmitri** [transistorsoft/flutter_background_geolocation#221]
It could be nice to have Location tracking events as stream instead of old-style event listeners

**Comment by christocracy** [comment]
They *are* streams, [under the hood](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/lib/models/background_geolocation.dart#L1008-L1023) and [here for iOS](https://github.com/transistorsoft/flutter_background_geolocation/tree/master/ios/Classes/streams) and [android](https://github.com/transistorsoft/flutter_background_geolocation/tree/master/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/streams)

**Comment by z-dmitri** [comment]
And how I could use streams over the hood then?

**Comment by z-dmitri** [comment]
How it could help me to listen location tracking as stream?

**Comment by z-dmitri** [comment]
Do you mean I have to take this native implementation and write own stream - based library?

**Comment by christocracy** [comment]
What are you trying to do?

Just add listeners as documented.

>Do you mean I have to take this native implementation and write own stream - based library?

No.

**Comment by z-dmitri** [comment]
I like to listen locations as stream
```dart
bg.BackgroundGeolocation.Locations.map((location) => TrackLocationEvent(location)) ***
```
Instead of
```dart
bg.BackgroundGeolocation.onLocation((bg.Location location) { ***
```

**Comment by christocracy** [comment]
>I like to listen locations as stream

Streams are expensive.  The plugin maintains *one* stream for each event (eg: `onLocation`, `onMotionChange`, etc).

There can be any number of event-handlers attached to any particular event-stream.

```
LocationStream
  - listener1
  - listener2
  - listener3
  .
  .
  .
```
Just use the API as documented.

**Comment by z-dmitri** [comment]
>Streams are expensive

**Comment by z-dmitri** [comment]
>Streams are expensive
Could I kindly ask you to provide some prove?
+ it make code readable - so even expensive will not good point to write code in bad way

**Comment by z-dmitri** [comment]
>There can be any number of event-handlers attached to any particular event-stream.
Stream could have many listeners as well

**Comment by christocracy** [comment]
Not going to happen.

**Comment by z-dmitri** [comment]
>Stream could have many listeners as well
>Not going to happen.

Already happened - just look into documentation, for example:
https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html

**Comment by christocracy** [comment]
>Not going to happen.

I have no plans to modify the event-streams.
