### ISSUE TITLE
How to test background mode in DEMO APP

### ISSUE THREAD

**Issue by tito-py** [transistorsoft/flutter_background_geolocation#223]
I want to make a test in which every X Minutes/Hours the demo updates the location independently if the app is started in mobile or not. How should I configure the DEMO APP?

## Your Environment
* Plugin version: 1.7.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Huawei / P20 (ELE-L04)
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

In the DEMO App, when closing the app, it should continue reportng in Background.

## Actual Behavior

After closing the APP, it does not keep refreshing in background.

## Steps to Reproduce

1. Open Demo App
2. Start Advanced
3. Enable Background Refresh and allow the permision
4. Close de app

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Read the wiki “Philosophy of Operation”.  The responsibility of this plugin is to track device when it is detected to be moving and conserve energy by turning of location-services while stationary.

When you move, it tracks.

Also see http://dontkillmyapp.com, especially with Huawei devices.

Also see api docs event onHeartbeat and method getCurrentPosition.  Also see included dependency background_fetch
