### ISSUE TITLE
Too many notifications in iOS

### ISSUE THREAD

**Issue by Ajit121** [transistorsoft/flutter_background_geolocation#225]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version:
* Device manufacturer / model: All iOS devices
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

iOS generating too much notification. its showing stationary notification, geofence enter exit notification. this is not in case of android.

## Actual Behavior

i don't want to show any of these notifications. How do i do that? or How to set custom text for those notification. 
## Debug logs

#<details>
![2be4792b-c374-4769-9775-dc69729b2a4b](https://user-images.githubusercontent.com/8845059/78784419-ede44d80-79c2-11ea-99d0-c205ed073bd7.jpg)

	#<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
#PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Those are there to assist you during development and field-testing so you can *see* and *hear* it working.  See api docs `Config.debug`
