### ISSUE TITLE
Background Location Updates and GeoFence Events not firing.

### ISSUE THREAD

**Issue by satenk** [transistorsoft/flutter_background_geolocation#227]
## Your Environment
* Plugin version: 1.7.1
* Platform: iOS and Android
* OS version: All
* Device manufacturer / model: 
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel master, v1.16.3-pre.56, on Mac OS X 10.15.4 19E266, locale en-IN)
    • Flutter version 1.16.3-pre.56 at /Users/ajitjaiswal/Library/flutter
    • Framework revision 8857c4cec8 (2 weeks ago), 2020-03-25 21:21:01 -0400
    • Engine revision b235233e9d
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 2323087237)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'location-services not enabled',
          'titleWhenOff': 'location-services OFF',
          'instructions': 'You must enable \'Always\' in location-services',
          'cancelButton': 'Cancel',
          'settingsButton': 'Settings'
        },
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 300.0,
        stopOnTerminate: false,
        enableHeadless: true,
        foregroundService: true,
        notificationText: "Stay Safe!",
        persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
        geofenceModeHighAccuracy: true,
        locationAuthorizationRequest: "Always",
        reset: false,
        startOnBoot: true,
        useSignificantChangesOnly: false,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });

//This is called from different function later.
 await bg.BackgroundGeolocation.addGeofence(
          bg.Geofence(
              identifier: GEOFENCE_IDENTIFIER,
              radius: radius,
              notifyOnEntry: true,
              notifyOnExit: true,
              notifyOnDwell: false,
              latitude: latitude,
              longitude: longitude));
      print('addGeofence reponse $isGeofenceAdded $radius and $latitude and $longitude');
      bg.State state = await bg.BackgroundGeolocation.startGeofences();
```

## Expected Behavior

 Device is idle and screen locked for few hours. App should send me location updates when user is moving and going out from geofence area.

## Actual Behavior

Everything is working fine after invoking these function when app is running in foreground. When Device is idle an and locked. After sometimes, no location change, no geofence enter exit event is firing even moving and getting out from geofence area..
## Steps to Reproduce

1.
2.
3.
4.

## Context

 Want to get  current device location, use geocoding plugin to get address and then upload the data to server with api call when the app in background and removed from system trey.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Provide logs.  See `BackgroundGeolocation.emailLog`

You say you’re experiencing this on **both iOS and Android**?  That’s highly unlikely.

Why are you configuring `reset: false`?

**Comment by satenk** [comment]
I calling the above function of user's registration. All those functions will be called only once until and unless user reinstall the app. The application is working fine until i remove the app from system trey and keep the phone in idle. I removed the "reset: false" from config now.
My Question is that do i need to call those two functions every time app launches or is it fine what i'm doing now?
I'm only testing in iOS devices.

**Comment by satenk** [comment]
My generated Log

{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =    {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 100;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    encrypt = 0;
    extras =    {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =    {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 1;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "You must enable 'Always' in location-services";
        settingsButton = Settings;
        titleWhenNotEnabled = "location-services not enabled";
        titleWhenOff = "location-services OFF";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = 0;
    params =    {
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = "-1";
    preventSuspend = 0;
    schedule =    (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 0;
    url = "";
    useSignificantChangesOnly = 0;
}
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/4460469/background-geolocation.log)

**Comment by christocracy** [comment]
> My Question is that do i need to call those two 

You need to call #ready **each time your app launches**.

#ready is a signal to the plugin that **your app is launched** and *ready* to start receiving events in your JavaScript.

**Comment by satenk** [comment]
BackgroundGeolocation.addGeofence
What about this?. Is this also required to call every time app launches?

Then how will i get event if the app is idle and not launched for hours or even days. Does headless function event gets called in this situation?

**Comment by christocracy** [comment]
> addGeofence. What about this?

If there were a problem with your #addGeofence, I would have said something about it above.

#addGeofence inserts a record into the plugin’s geofence database.  Once a geofence is added, the plugin knows about it forever until you #removeGeofence, where the plugin *deletes* it from its database.

If your Android app is terminated, all events flow into HeadlessTask, otherwise, events flow into the traditional event-handlers (eg #onLocation, #onGeofence, etc)

**Comment by satenk** [comment]
" If your Android app is terminated, all events flow into HeadlessTask, otherwise, events flow into the traditional event-handlers (eg #onLocation, #onGeofence, etc) "

will it happen in iOS also?

**Comment by christocracy** [comment]
>If your Android app

No, that’s why I **explicitly** stated your **Android** app.

**Comment by satenk** [comment]
what about iOS scanario ? we need first help on iOS implementation please. 

Then how will i get event if the iOS app is idle and not launched for hours or even days. Does headless function event gets called in this situation?

we really need your support on this.

**Comment by satenk** [comment]
if the app is idle for long time or not open for long time and if debug:true then everything is working but if we do debug:false the no event are firing and no data is getting uploaded in the url:"****" not even logging the events is logger. We are testing this in iOS 13.3

**Comment by christocracy** [comment]
I keep 3 demo apps running on latest iOS 13 for weeks-at-time -- without bringing them to foreground -- for *Cordova*, *React Native* and *Flutter*, all running with `debug: false` and they never fail to track and post their locations to http://tracker.transistorsoft.com.

Suggesting `debug` has anything to do with tracking behaviour is as superstitious as believing the plugin doesn't work when a black cat crosses your path.
