### ISSUE TITLE
Unhandled Exception: PlatformException(CANNOT_SEND_MAIL, null, null)

### ISSUE THREAD

**Issue by Ajit121** [transistorsoft/flutter_background_geolocation#228]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version:
* Device manufacturer / model: iPhone
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Log should be shared.
## Actual Behavior

Unhandled Exception: PlatformException(CANNOT_SEND_MAIL, null, null) in iOS only
## Steps to Reproduce

1.
2.
3.
4.

## Context

I tried to email the log using 
Logger.emailLog('foo@mail.com')// giving the valid email id in code
it throwing exception.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version:
>Platform: iOS
>OS version:
>Device manufacturer / model: iPhone

Either you're executing this from the Simulator (you've provided almost no information, so impossible to say) or your phone's default mail client is not configured.

emailLog doesn't work in the simulator, only real devices.

**Comment by Ajit121** [comment]
yes,  invoking from simulator.

**Comment by Ajit121** [comment]
Plugin version: 1.7.1
Platform: iOS
OS version: 13.3.1
Device manufacturer / model: iPhone /  iPhone 6s
Not working on real devices either.

**Comment by christocracy** [comment]
> Not working on real devices either.

The error means that the default mail client is not configured.  The plugin is trying to launch the default mail client.  If there's no default mail client configured, the plugin cannot `emailLog`.
