### ISSUE TITLE
[iOS] Background location not work when app is killed 

### ISSUE THREAD

**Issue by GBDevs** [transistorsoft/flutter_background_geolocation#229]
## Your Environment
* Plugin version: 1.7.2
* Platform: iOS / Android
* OS version: All
* Device manufacturer / model: iPhone XS
* Flutter info (`flutter doctor`): 
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (11 days ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

//IN APP.dart
BackgroundGeolocation.ready(
  Config(
    locationAuthorizationRequest: "Always",
    reset: false,
    desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1,
    stopOnTerminate: false,
    startOnBoot: true,
    //logLevel: Config.LOG_LEVEL_VERBOSE,
    enableHeadless: true,
    autoSync: false,
    //debug: true,
    heartbeatInterval: 600,
    allowIdenticalLocations: true,
    foregroundService: true,
  ),
).then((state) {
  BackgroundGeolocation.start();
});

Future<void> initPlatformState() async {
  // Configure BackgroundFetch.
  BackgroundFetch.configure(
    BackgroundFetchConfig(
      minimumFetchInterval: 15,
      forceAlarmManager: false,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      /*requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresStorageNotLow: false,
      requiresDeviceIdle: false,*/
      requiredNetworkType: NetworkType.ANY,
    ),
    (taskId) async {
      print(taskId);
      switch (taskId) {
        case 'com.transistorsoft.customtask':
          GeolocationAPI().sendCoordinates();
          break;
        default:
          print("Default fetch task");
      }
      BackgroundFetch.finish(taskId);
    },
  ).then((int status) {
    print('[BackgroundFetch] configure success: $status');
    BackgroundFetch.start();
  }).catchError((e) {
    print('[BackgroundFetch] configure ERROR: $e');
  });
  // Schedule a "one-shot" custom-task in 10000ms.
  // These are fairly reliable on Android (particularly with forceAlarmManager) but not iOS,
  // where device must be powered (and delay will be throttled by the OS).
  BackgroundFetch.scheduleTask(
    TaskConfig(
      taskId: "com.transistorsoft.customtask",
      delay: 120000, //Tempo in milliseconds, 2 min => 120000 milliseconds
      periodic: true,
      forceAlarmManager: true,
      stopOnTerminate: false,
      enableHeadless: true,
    ),
  );
  if (!mounted) return;
}


//IN MAIN.dart 
BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

BackgroundGeolocation.registerHeadlessTask(backgroundGeolocationHeadlessTask);


void backgroundGeolocationHeadlessTask(HeadlessEvent headlessEvent) async {
  if (headlessEvent.name == "heartbeat") debugLogToServer();
}

void backgroundFetchHeadlessTask(String taskId) async {
  if (taskId == 'com.transistorsoft.customtask') debugLogToServer();
}
```

## Expected Behavior
We expect that when the application is closed it will continue to record the user's location to send it to our server.

## Actual Behavior
It happens that the application never sends the location to the server, even when in the foreground.
In android everything works correctly, the problem is only on ios.

## Steps to Reproduce

1. Start app (BackgroundGeolocation.start();)
2. Close app / killed app
3. We await registration position
4. No position recorded

## Context
We are trying to create an app to record a user's location on the map even when the app is not open.

## Debug logs
We don't receive errors but the functionality doesn't work.

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
How exactly are you testing this on iOS?

**Comment by christocracy** [comment]
Have you read the iOS section in the API Docs for Config.stopOnTerminate?

**Comment by GBDevs** [comment]
> Have you read the iOS section in the API Docs for Config.stopOnTerminate?

Ok, I have read the documentation but is it possible to shorten the minimum geofence radius to 10m?

**Comment by christocracy** [comment]
> but is it possible to shorten the minimum geofence radius to 10m?

If it were possible, it would have been done already.  This is a fundamental limitation imposed by iOS that is impossible to overcome.

We are fortunate iOS even allows this at all.
