### ISSUE TITLE
The plugin returns location in the sea

### ISSUE THREAD

**Issue by brooth** [transistorsoft/flutter_background_geolocation#230]
## Your Environment
* Plugin version: 1.7.0
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iPhone X
* Flutter info (`flutter doctor`):
```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    Config(
        persistMode: Config.PERSIST_MODE_NONE,
        maxRecordsToPersist: 0,
        maxDaysToPersist: 0,
        debug: false,
        logLevel: Config.LOG_LEVEL_DEBUG,
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        autoSync: false,
      );
```

## Expected Behavior
We expect to receive only high accuracy tracks from the plugin.

## Actual Behavior
If the location permission is set to 'While In Use' [(due to the new iOS location permission policy)](https://medium.com/better-programming/understanding-new-location-permission-changes-in-ios-13-6c34dc5f54da), sometimes the plugin returns locations in the sea:
```json
{
  "id": 3860,
  "company_id": 1,
  "company_token": "UNKNOWN",
  "device_id": 1,
  "device_model": "UNKNOWN",
  "created_at": "2020-04-13T11:42:10.224Z",
  "framework": null,
  "version": null,
  "updated_at": "2020-04-13T11:53:08.278Z",
  "activity_type": "still",
  "activity_confidence": 33,
  "battery_level": 0.33000001311302185,
  "battery_is_charging": false,
  "uuid": "56F22632-9A4F-47BD-92A8-C5A216D261FE",
  "event": "motionchange",
  "extras": {},
  "odometer": 0,
  "is_moving": false,
  "timestamp": "2020-04-13T11:42:10.081Z",
  "floor": null,
  "speed": 0,
  "heading": 0,
  "accuracy": 2500,
  "altitude": 5,
  "latitude": -28.05806381758819,
  "longitude": 153.44889535050044,
  "altitude_accuracy": 4,
  "recorded_at": "2020-04-13T11:42:10.081Z"
}
```

## Steps to Reproduce
1. Install an app that uses the plugin
2. Choose 'While in Use' on the location permission dialog
3. Drive around Broadbeach, Queensland, Australia 

## Context
Confidential information, sorry.

## Debug logs
Not available

**Comment by christocracy** [comment]
It’s not unusual at all to receive poor accuracy location depending upon the device and environment.  It’s your responsibility to filter out undesired locations based upon accuracy.
