### ISSUE TITLE
What are the release details for 1.7.3 ?

### ISSUE THREAD

**Issue by livotov** [transistorsoft/flutter_background_geolocation#233]
What are the release details for 1.7.3 ?
I do see it was released yesterday to pub.dev but no release and release notes here @ gitgub

Thanks

**Comment by livotov** [comment]
Anything related to #217 and #218 there so we can try it?

**Comment by christocracy** [comment]
See [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#173---2020-04-14), as always.
