### ISSUE TITLE
Sava the location 

### ISSUE THREAD

**Issue by ammarmahafeza2** [transistorsoft/flutter_background_geolocation#238]
i need every 30 meters save the location of the User please tell me which the function in the plugin do that

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
While the device is *moving*?

**Comment by ammarmahafeza2** [comment]
yes

**Comment by christocracy** [comment]
See api docs Config.useSignificantChangesOnly

**Comment by christocracy** [comment]
Also see https://github.com/transistorsoft/flutter_background_fetch

Use BackgroundGeolocation.getCurrentPosition in your callback
