### ISSUE TITLE
Debug notifications are always shows

### ISSUE THREAD

**Issue by dmissoh** [transistorsoft/flutter_background_geolocation#242]
Debug notifications are shown in both the Simulator and on a real device (iOS) regardless of the value in the configuration (**Config.debug**).

## Your Environment
* Plugin version: 1.7.3
* Platform: iOS
* OS version: 13.4.1
* Device manufacturer / model: iPhone 11 Pro Max
* Flutter info (`flutter doctor`): all clean
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
            locationAuthorizationRequest: "Always",
            reset: false,
            stopTimeout: 1,
            autoSync: false,
            debug: false,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            heartbeatInterval: 30,
            foregroundService: true,
            startOnBoot: true,
            enableHeadless: true,
            logLevel: bg.Config.LOG_LEVEL_OFF // bg.Config.LOG_LEVEL_VERBOSE
            ))
        .then((bg.State state) {
      if (!state.enabled) {
        // start geofences only
        bg.BackgroundGeolocation.startGeofences();
      }
    });
```

## Expected Behavior
Debug notifications are not shown when Config.debug is set to **false**

## Actual Behavior
Debug notifications are always shown regardless of the value of  **Config.debug**

## Steps to Reproduce
The code is not relevant. `startGeofences` has been called and the defined geofence is entered.
1. Enter a geofence

## Context
Turning off the debug notifications

## Debug logs
Clean

</details>

**Comment by christocracy** [comment]
Do you know what this does?
```
reset: false,
```

**Comment by dmissoh** [comment]
Hi Chris. That was a fast answer. Thanks a lot for the answer. I solved the issue.

**Comment by christocracy** [comment]
Most people don't need `reset: false`.  I use it in the demo app because I want the *Settings* screen to be the ultimate authority on the current state of the plugin.  I don't want the `#ready` method to reset and re-apply the `Config` to `#ready` with each boot.

**Comment by dmissoh** [comment]
Thanks for the details Chris. It' cristal clear now.

Thank you for the amazing plugin!
