### ISSUE TITLE
With stopOnTerminate=true perform async callback after stop, before terminate

### ISSUE THREAD

**Issue by algodave** [transistorsoft/flutter_background_geolocation#243]
I have `stopOnTerminate: true` and I would like to perform a custom async callback *after* the plugin has been stopped, *before* the app is actually terminated. I've been trying to achieve that using `onEnabledChange` event listener, with no success (I've been testing on an iPhone XR with iOS 13.3.1). 

Is it possible to achieve my goal, and if so, how? 

If not, how hard would it be to extend the library to support that?

**Comment by christocracy** [comment]
There’s very little you’ll be able to do when an app is terminated, certainly no network.

You’ll only receive the app terminate signal from an app which is terminated while currently in the foreground.

If an app is terminated while in the background, you’ll get no signal of this from the os.

**Comment by christocracy** [comment]
You might try

**Comment by algodave** [comment]
Thank you for the prompt feedback @christocracy
