### ISSUE TITLE
Startup Sluggishness Question

### ISSUE THREAD

**Issue by dirjud** [transistorsoft/flutter_background_geolocation#244]
* Plugin version: git
* Platform: Android
* OS version: Android 10 
* Device manufacturer / model: Google Pixel 3 
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location loc) {
      print('[location] - $loc');
      setLoc(loc);
    });
    bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
      print('[heartbeat] - $event');
      bg.BackgroundGeolocation.getCurrentPosition(samples: 1, persist: true)
          .then((loc) {
        print('[loc] - $loc');
        setLoc(loc);
      });
    });
    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location loc) {
      print('[motionchange] - $loc');
      setLoc(loc);
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });
    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1.0,
      stopOnTerminate: true,
      startOnBoot: false,
      debug: false,//true,
      reset: true,
      heartbeatInterval: 10,
      preventSuspend: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,

      url: RPC.server + "/rest/result/Points/insert",
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 50,
      params: {"user_id": _user["id"], "participant_id":_participantId },
      extras: {"route_id": 8675309},
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
    )).then((bg.State state) {
      print("STATE: " + state.toString());
      if (!state.enabled) {
        print("STARTING");
        bg.BackgroundGeolocation.start();
      }
    });

```

## Actual Behavior

This is more of a question than a bug report. Our app tracks the users walking/running location and gives an audio tour of points of interests along the way. When first started, the locations are very slow to come in, even though I am moving a considerable distance. I cannot say definitely what makes it start working, but eventually, the locations start coming in fine and frequently enough. It seems I need to go around 0.1 miles before it really starts working. Sometimes, however, that distance is shorter, and other times it is longer. Initially, I thought maybe it was due to lack of GPS lock, but if I kill the app and restart it, it seems to have to go through the same startup process. I see similar behavior on iOS. Is this expected or am I doing something wrong? When I turn on debug mode, I get very infrequent sounds. After overcoming the startup issue, however, the sounds are regular and are able to track my movement really well. I can provide logs if this is not expected behavior. If it is expected, are there ways to 'prime the pump' so to speak?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version: git

This is information is *useless*.  From *yesterday*?  A *year ago*?  Paste the commit-hash, it's in your `pubspec.yaml`.

>Sometimes, however, that distance is shorter, and other times it is longer.

The plugin initiates tracking via motion API (accelerometer/gyroscope/magnetometer), it has nothing to do with "gps lock".

Are you testing with `debug: true` so you can *hear* the plugin working?

>If it is expected, are there ways to 'prime the pump' so to speak?

The plugin triggers tracking with *movement*.  My 2 pixels (original Pixel and Pixel 3a) are exceptionally good at triggering, requiring little more than ~10-20 meters of walking.  You can fool the plugin into triggering into *moving* state by shaking the device vigorously for 10-30s.  Then let it lay still.  Observe the sounds and watch the logs simultaneously.

Triggering within 200 meters would be perfectly acceptable to me.  Walking will typically trigger quicker than a vehicle.

**Comment by dirjud** [comment]
200 meters is not going to work for our application. We have a timed event and if people have to move 200 meters every time they stop before they start getting updates again, that is a problem.

iPhones seem worse that my Android pixel at starting. If I start another gps tracking app called Strava on iOS, it gets my location immediately and tracks flawless from the start every time. My app (using background geolocation), however, is usually quite wrong on the initial location and does not provide any updates until I have moved a good distance, sometimes as far as 0.1 miles. It sounds like this is what you expect though? If this is the expected behavior, I will need to find another solution.

**Comment by christocracy** [comment]
> If I start another gps tracking app called Strava on iOS

Without user-intevention (ie: user explicitly pressing a button `[Start Tracking me now]`), it's **100% impossible** for *Strava* to *immediately* initiate tracking while app is in the background by moving mere meters.

> It sounds like this is what you expect though?

Yes.

You're free to execute `BackgroundGeolocation.changePace(true)` to immediately initiate tracking.  If you have a "timed event", I would send a "silent server push" to the devices.  In the `onNotification` callback, I'd execute `BackgroundGeolocation.changePace(true)`.

**Comment by christocracy** [comment]
Strava will *not* start tracking you until you press the big `(Start)` button.  The equivalent in the `/example` app in this repo is the `[ > ]` button, which executes `BackgroundGeolocation.changePace(true)`.

![](https://dl.dropbox.com/s/1wowgmjbbxpxv9v/Screenshot%202020-04-24%2016.08.43.png?dl=1)

![](https://dl.dropbox.com/s/z6s8zrj8i557yzz/Screenshot%202020-04-24%2016.12.34.png?dl=1)

**Comment by dirjud** [comment]
I am fine with the user initiating tracking with a button press! Thanks for the suggestion. I'll try the changePace() now along with a user button to see how it goes.

**Comment by djmuhlestein** [comment]
Hello, I'm working on this same project and have largely got this working as expected by calling changePace(true) at our plugin initialization time.  Here is our config called when the user starts the location tracking:

     bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: true,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        startOnBoot: false,
        debug: false,
        locationAuthorizationRequest: "WhenInUse",
        reset: true,
        heartbeatInterval: 60,
        preventSuspend: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION, // don't jump to roads 
        url: RPC.server + "/rest/result/Points/insert",
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 50,
        params: {
          "user_id": _user["id"],
          "participant_id": _participantId,
          "dev_id": _deviceId,
        },
        extras: {"route_id": 8675309},
        locationsOrderDirection: "DESC",
        maxDaysToPersist: 14,
      )).then((bg.State state) {
        if (!state.enabled) {
          bg.BackgroundGeolocation.start();
        }
        bg.BackgroundGeolocation.changePace(true);
    });

I've not ever seen this behave other than intended when I build this locally and test it on a number of different iPhone models.  However, when I build this for release through and have others test this through TestFlight, we've seen that the changePace(true) call doesn't seem to always be set correctly.  Here is a portion of the log from one such instance:

    default	16:13:17.013262-0600	Runner	flutter: CHANGE PACE true
    default	16:13:17.013896-0600	Runner	
    ╔═══════════════════════════════════════════════════════════
    ║ -[TSHttpService flush:] 
    ╚═══════════════════════════════════════════════════════════
    default	16:13:17.013950-0600	Runner	
    ╔═══════════════════════════════════════════════════════════
    ║ -[TSHttpService finish:error:] Success: 1
    ╚═══════════════════════════════════════════════════════════
    default	16:13:17.014017-0600	Runner	
    ╔═══════════════════════════════════════════════════════════
    ║ -[TSLocationManager start] 
    ╚═══════════════════════════════════════════════════════════
    default	16:13:17.014066-0600	Runner	ℹ️-[TSLocationManager doStart:] trackingMode: 1
    default	16:13:17.014209-0600	Runner	ℹ️-[TSConfig persist]
    default	16:13:17.021050-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"startMonitoringSignificantLocationChanges", "self":"0x281a457f0"}
    default	16:13:17.021110-0600	Runner	🎾-[TSGeofenceManager start]
    default	16:13:17.022183-0600	Runner	nw_path_evaluator_start [D1EEA3D7-E9E0-4E90-9214-9A3907B2988F <NULL> generic, indefinite]
    	path: satisfied (Path is satisfied), interface: en0, ipv4, dns
    default	16:13:17.023056-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"location", "self":"0x281a45750"}
    default	16:13:17.023397-0600	Runner	{"msg":"Sending cached messages to daemon", "event":"activity"}
    default	16:13:17.023457-0600	Runner	🎾-[SOMotionDetector startDetection]
    default	16:13:17.023561-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"setDistanceFilter:", "self":"0x281a45750", "distance":"-1.000000"}
    default	16:13:17.023830-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"distanceFilter", "old":"1.000000", "new":"-1.000000"}
    default	16:13:17.023957-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"setDesiredAccuracy:", "self":"0x281a45750", "accuracy":"-2.000000"}
    default	16:13:17.024054-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"desiredAccuracy", "old":"-1.000000", "new":"-2.000000"}
    default	16:13:17.024432-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"setPausesLocationUpdatesAutomatically:", "self":"0x281a45750", "pausesLocationUpdatesAutomatically":0}
    default	16:13:17.024540-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"pausesLocationUpdatesAutomatically", "old":{"type":"decode failure","raw value":0,"expected type":"Generic"}, "new":{"type":"decode failure","raw value":4,"expected type":"Generic"}}
    default	16:13:17.024705-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"setAllowsBackgroundLocationUpdates:", "self":"0x281a45750", "allows":1}
    default	16:13:17.024753-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"allowsBackgroundLocationUpdates", "old":0, "new":1}
    default	16:13:17.024779-0600	Runner	🔵-[TSLocationManager setPace:] 0
    default	16:13:17.025019-0600	Runner	🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
    default	16:13:17.025065-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"setShowsBackgroundLocationIndicator:", "self":"0x281a45750", "shows":0}
    default	16:13:17.025122-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"showsBackgroundLocationIndicator", "old":0, "new":0}
    default	16:13:17.026146-0600	Runner	{"msg":"CLLocationManager", "event":"activity", "_cmd":"startUpdatingLocation", "self":"0x281a45750"}
    default	16:13:17.026236-0600	Runner	{"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x281a45750", "property":"updatingLocation", "old":0, "new":1}
    default	16:13:17.026761-0600	Runner	{"msg":"CLInternalGetAuthorizationStatus", "event":"activity"}

At the start of the log, I had added a print statement for "CHANGE PACE true".  Notice shortly thereafter that TSLocationManager printed setPace: 0.  I've worked around this by moving the changePace(true) call to a later point in our code but that seems like an incorrect way to work around the problem if we want to immediately start tracking the location.  Is there some race condition we need to be aware of between `BackgroundGeolocation.start()` and `BackgroundGeolocation.changePace(true)`?

**Comment by christocracy** [comment]
You may `#ready` the plugin with `isMoving: true` and it will immediately call `changePace(true)` upon itself.

**Comment by djmuhlestein** [comment]
Oh perfect.  I hadn't seen that property in Config.  That's much nicer than having to wait for start.

**Comment by dirjud** [comment]
iOS is now behaving as we want. This is a jogging tracking app. We only request "WhenInUse" permissions, and we set isMoving: true in the config when we start tracking. Our iOS app receives location updates and we track the user as we want, even when the screen is blacked or the user receives a phone call or puts another app in the foreground. Android, however, seems to stop calling the callbacks when we grant "WhenInUse" permissions and we black the screen or bring another app to the foreground. It does seem to track correctly when we grant "Always" permissions in Android, though, and black the screen or bring another app to the foreground. 

Strava only requests "WhenInUse" permissions on Android but still tracks when the screen is blacked or another app is in the foreground. I did a test where I tracked with Strava and our app simultaneously, both with the "WhenInUser" permissions and the screen blacked. Strava captured the track perfectly. Our app did not track anything.

Are we missing something in the config? Here is our config:

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1.0,
      stopOnTerminate: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      startOnBoot: false,
      debug: false,
      locationAuthorizationRequest: "WhenInUse",
      reset: true,
      heartbeatInterval: 60,
      preventSuspend: true,
      isMoving: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION, // don't jump to roads
      foregroundService: true, // android only

      url: RPC.server + "/rest/result/Points/insert",
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 50,
      params: {
        "user_id": _user["id"],
        "participant_id": _participantId,
        "dev_id": _deviceId,
      },
      extras: {"route_id": 8675309},
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
    ))

**Comment by christocracy** [comment]
@dirjud Add the following to your `AndroidManifest.xml`, within the `<application>` element

```xml
<application ...>
    .
    .
    .
    <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
    <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />

</application>
```

**Comment by dirjud** [comment]
That worked. Android is now tracking correctly when "When In Use" permissions are selected.

Android is still asking for the "Always" permission. Is there a way to only ask for "When In Use" permission? iOS is only asking for "When In Use" permission.

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationRequest`

**Comment by dirjud** [comment]
As you can see from our config above, we have locationAuthorizationRequest set to "WhenInUse" but Android is still asking "Always".

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/0yytw3gkm8oky3g/Screenshot%202020-05-12%2011.38.23.png?dl=1)

**Comment by dirjud** [comment]
![Screenshot_20200512-095906](https://user-images.githubusercontent.com/147964/81717152-6ceffa00-9437-11ea-9b6b-ae1d0f5aef8b.png)

**Comment by dirjud** [comment]
This is on the Pixel 3 that is fully up to date. Here is my config again. Are there other spots, such as the AndroidManifest.xml that could trigger the "Allow All The Time" question? What if I had previously granted it an Allow All the Time?

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1.0,
      stopOnTerminate: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      startOnBoot: false,
      debug: false,
      locationAuthorizationRequest: "WhenInUse",
      reset: true,
      heartbeatInterval: 60,
      preventSuspend: true,
      isMoving: true,
      stopAfterElapsedMinutes: 60*10, // automatically stop if not done in 10 hours
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION, // don't jump to roads
      foregroundService: true, // android only
      notification: bg.Notification( // android only
          title: "OYO",
          text: "Tracking your race"
      ),

      url: RPC.server + "/rest/result/Points/insert",
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 50,
      //headers: {"AUTHENTICATION_TOKEN": "23kasdlfkjlksjflkasdZIds"},
      params: {
        "user_id": _user["id"],
        "participant_id": _participantId,
        "dev_id": _deviceId,
      },
      //extras: {"route_id": 8675309},
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
    )).then((bg.State state) {
      print("STATE: " + state.toString());
      if (!state.enabled) {
        print("STARTING");
        bg.BackgroundGeolocation.start();
      }
    });

**Comment by dirjud** [comment]
In looking through settings after having done a fresh install but before calling config/start on background geolocation, I can see my app in the "Denied" list. But it is still asking for the "Allow All The Time" option when I call the config/start function on my phone.

**Comment by christocracy** [comment]
>Are there other spots, such as the AndroidManifest.xml that could trigger the "Allow All The Time" question? 

No.  Are you using some *other* 3rd-party libs that are requesting location (eg: a maps plugin).

>What if I had previously granted it an Allow All the Time?

- I changed my config to `locationAuthorizationRequest: 'WhenInUse'`
- *Device Settings->Applications->{My App}->Permissions->Location->Deny*.
- Relaunch app.  Execute `BackgroundGeolocation.start()`.

**Comment by dirjud** [comment]
I checked through our pubspec for any other plugins that may request permissions and didn't see anything. Furthermore, this permission request is being triggered when I call the config/start of the background geolocation plugin. Could it be caused by a my compileSdkVersion or any other gradle setting? I had to inc the compileSdkVersion to 29 to get your last suggestion to add the the "android:foregroundServiceType" to the AndroidManifest.xml file.

**Comment by dirjud** [comment]
And the same app on iOS is not asking for "Always".

**Comment by christocracy** [comment]
I don’t know what could be your problem.  It worked first time for me.  I’m using sdk 29.

**Comment by christocracy** [comment]
Btw, iOS `preventSuspend: true` doesn’t work with “WhenInUse”.  You might as well remove that option.

**Comment by dirjud** [comment]
I'll give your example app a try and see what it does for me.

**Comment by dirjud** [comment]
I tried your sample app and it does not show the "Always Allow..." option, even after I pasted most of my config into place. So it would seem it is something outside of the config that is causing the "Allows" option in our app. I'll move on for now and revisit this later.
