### ISSUE TITLE
contains unsafe cryptographic encryption patterns

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#245]
Google play give me a alert after upload a internal test version 

```
Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.
https://support.google.com/faqs/answer/9450925
Vulnerable classes:

l.a.a.b.a
```

so I have suspicions in  flutter_background_geolocation due to it need a key and I been correct I removed the package and upload new version without flutter_background_geolocation and alert has disappear.

**Comment by christocracy** [comment]
Ignore,  this is from a new encryption feature `Config.encrypt` that you’re not using.

**Comment by niypoo** [comment]
okay , how can ignore this alert ! and used package without alert !?

**Comment by christocracy** [comment]
Pretend you never saw it.

**Comment by niypoo** [comment]
you mean the google play alert !?

**Comment by christocracy** [comment]
Yes, I mean the play store alert.  Ignore it, forget about it!!  It is of no consequence to you since you’re not using the plugin’s encryption feature!!

**Comment by niypoo** [comment]
> Yes, I mean the play store alert. Ignore it, forget about it!! It is of no consequence to you since you’re not using the plugin’s encryption feature!!
Okay I hope you are right and google not give me a sweet suspend  :D ,
If i have another question - not issue - is here a right place. !

**Comment by christocracy** [comment]
The first place to seek tech support is exactly this, posting an issue.

**Comment by niypoo** [comment]
If I want use only `geofence class` and not use  any zgeolocation functions`  I must  integration Android  like here 
https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md

and I hope is there any "promo code" :)

**Comment by christocracy** [comment]
>If I want use only geofence class and not use any zgeolocation functions` I must integration Android like here

Yes.  Please keep your questions on topic.  This *closed* issue is titled *"contains unsafe cryptographic encryption patterns"*.

>and I hope is there any "promo code" :)

Sorry, there are no discounts.

**Comment by murven** [comment]
@christocracy 
Google review is preventing our build from going to the store because of this issue.
I have been looking inside the code to see where exactly the encryption is happening so that I can comment that code out to pass the review, since we are not using this feature. Could you please point me to the place in the code where this encryption is performed? We are using the paid version of the plugin, please let me know if you need me to pass purchase information. Thanks!

**Comment by christocracy** [comment]
Show me what Google play console said.

**Comment by murven** [comment]
Error
Errors found. Fix before releasing to production.
Security and trust
Unsafe Encryption
error
Error
Security
Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

a.a.a.b.a

**Comment by christocracy** [comment]
Show me a screenshot of this.

**Comment by murven** [comment]
![image](https://user-images.githubusercontent.com/484427/98118784-57510f80-1e71-11eb-98cb-bf0ff2377170.png)

**Comment by murven** [comment]
@christocracy Update: you were correct, in the end, Google ignored this, even when it was marked as an error and let the app go into the store. I just wanted to leave this here for anyone else reading.

**Comment by Digisolfze** [comment]
dear, 
when deploy app in google play console shows an error below :
![bluefig error](https://user-images.githubusercontent.com/79982264/147409593-03061fbc-8310-4074-9448-c8ddba3203d1.png)

**Comment by mohammadrezaberenji** [comment]
@murven I faced same issue, and we got rejection. would you tell me what did you do for publishing in console again after this message?

**Comment by akshayjain14** [comment]
@mohammadrezaberenji  : Any solution , We are also facing same issue  ?

**Comment by christocracy** [comment]
What version of the plugin are you using?  Cryptographic stuff was ripped out ages ago.

If you’re using a recent version of this plugin, then it’s not due to the plugin at all.
