### ISSUE TITLE
Android Headless Mode - Change config in real-time

### ISSUE THREAD

**Issue by robrichardson13** [transistorsoft/flutter_background_geolocation#247]
It's possible to change the BackgroundGeolocation config in real-time using `setConfig()`, but is this possible to do while in Headless Mode as well? I'm assuming you should be able to call all of the functions like `getCurrentPosition()`, but just wanted to make sure.

**Comment by christocracy** [comment]
Yes, the full `BackgroundGeolocation` API is available to you.  Just don't call `#ready` in headless-task.

**Comment by christocracy** [comment]
And don't attach event-listeners `onLocation`, `onMotionChange`, etc.  Those are all for when app is launched.
