### ISSUE TITLE
How to prevent fetching locations when the app is killed?

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#248]
## Your Environment
* Plugin version: ^1.7.2
* Platform: iOS or Android : Android
* OS version: 10
* Device manufacturer / model: Google (Pixel 2 XL)
* Flutter info (`flutter doctor`):
$: flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available 
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
            locationAuthorizationRequest: 'WhenInUse',
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            heartbeatInterval: 60,
            showsBackgroundLocationIndicator: false,
            maxDaysToPersist: 1,
            stopOnTerminate: true,
            reset: true)
```

## Expected Behavior

I was expecting to stop fetching locations when the app is killed and do not show any notifications to the user.
## Actual Behavior
 
Device shows notifications saying application is accessing location services in the background even though the app is not running and completely killed.  
## Steps to Reproduce

1. Run application with the above plugin config
2. kill the application (goto recent apps and swipe out the application)
3. wait for sometime or move around, you will see a notification saying app is accessing background location
4. Also, there is no way to clear these notifications. 

## Context

trying to fetch locations only when the app is running in foreground or background.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Observe the logs when you perform this:
```
$ adb logcat *:S TSLocationManager:V
```

**Comment by kmusham** [comment]
Any idea on this error?
$: adb logcat *:S TSLocationManager:V 
zsh: no matches found: *:S
$:

**Comment by christocracy** [comment]
See [Logcat](https://developer.android.com/studio/command-line/logcat)  docs.

**Comment by kmusham** [comment]
This worked

$: adb logcat '*:S' TSLocationManager:V

**Comment by kmusham** [comment]
Hi @christocracy 
My device is not showing the notification anymore but I saw it for sure showing lot of notifications one day when none of the applications were running in the background.
I will capture the logs if I see it again. 
Could you please review the configuration once to see if I'm missing any flag? 

Intension is stop capturing locations and show notifications when app is killed.
Thank you.

**Comment by HugoHeneault** [comment]
Same here! How could we do to help you debug this?

**Comment by christocracy** [comment]
@HugoHeneault you start by including the same information in the original post.
