### ISSUE TITLE
How to get geofence only

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#249]
I only used Geofence and Headless in android , Is there any way to only load necessary file for geoFence , and is `motion detection` permission is required in geoFence !

**Comment by christocracy** [comment]
>Is there any way to only load necessary file for geoFenc

I don't know what you mean by "necessary file".

>and is motion detection permission is required in geoFence !

No.

**Comment by niypoo** [comment]
only Geofence Library file -like geofence GitHub repository only for  geofence- .
I'm power the geofence like that
```
//start geoFence
    bg.BackgroundGeolocation.ready(
      Config(
        enableHeadless: true,
        stopOnTerminate: false,
        startOnBoot: true,
        geofenceInitialTriggerEntry: false,
      ),
    ).then(
      (state) {
        // engage geofences-only mode:
        BackgroundGeolocation.startGeofences();
      },
    );
```
and I ask to give the motion detection permission

**Comment by christocracy** [comment]
>only Geofence Library file -like geofence GitHub repository only for geofence-

No.  You import the plugin the same, regardless if only using geofences-only.

>and I ask to give the motion detection permission

See API docs `Config.disableMotionActivityUpdates`.
