### ISSUE TITLE
Major issue 

### ISSUE THREAD

**Issue by tegab** [transistorsoft/flutter_background_geolocation#25]
i am getting 
BackgroundGeolocation is disabled.

please help

## Your Environment
* Plugin version: github latest version
* Platform: Android
* OS version: 8.0
* Device manufacturer / model:
* Flutter info (`flutter doctor`):Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17763.253], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] VS Code (version 1.31.0)
[√] Connected device (1 available)
* Plugin config

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Please do not specify “version: latest”.  It’s meaningless in the future.

**Comment by christocracy** [comment]
Also, you’ve not specified “iOS or Android”, nor have you provided any code or logs.

**Comment by tegab** [comment]
> Please do not specify “version: latest”. It’s meaningless in the future.

0.3.2

**Comment by christocracy** [comment]
**edit your original post**

**Comment by tegab** [comment]
Any idea on how to proceed. i am stuck.  thank you

**Comment by christocracy** [comment]
See wiki Debugging.  Provide logs and code of what you’re doing is always the first step.

https://github.com/transistorsoft/flutter_background_geolocation/wiki/Debugging

**Comment by tegab** [comment]
here is my log

I/TSLocationManager(30947): 
I/TSLocationManager(30947): ╔═════════════════════════════════════════════
I/TSLocationManager(30947): ║ License Validation Failure
I/TSLocationManager(30947): ╠═════════════════════════════════════════════
I/TSLocationManager(30947): ╟─ BackgroundGeolocation is running in evaluation mode.
I/TSLocationManager(30947): [c.t.l.adapter.TSConfig print] 
I/TSLocationManager(30947): ╔═════════════════════════════════════════════
I/TSLocationManager(30947): ║ TSLocationManager version: 2.14.10 (291)
I/TSLocationManager(30947): ╠═════════════════════════════════════════════
I/TSLocationManager(30947): {
I/TSLocationManager(30947):   "activityRecognitionInterval": 10000,
I/TSLocationManager(30947):   "allowIdenticalLocations": false,
I/TSLocationManager(30947):   "autoSync": true,
I/TSLocationManager(30947):   "autoSyncThreshold": 0,
I/TSLocationManager(30947):   "batchSync": false,
I/TSLocationManager(30947):   "debug": true,
I/TSLocationManager(30947):   "deferTime": 0,
I/TSLocationManager(30947):   "desiredAccuracy": -1,
I/TSLocationManager(30947):   "desiredOdometerAccuracy": 100,
I/TSLocationManager(30947):   "disableElasticity": false,
I/TSLocationManager(30947):   "disableStopDetection": false,
I/TSLocationManager(30947):   "distanceFilter": 10,
I/TSLocationManager(30947):   "elasticityMultiplier": 1,
I/TSLocationManager(30947):   "enableHeadless": false,
I/TSLocationManager(30947):   "enableTimestampMeta": false,
I/TSLocationManager(30947):   "extras": {},
I/TSLocationManager(30947):   "fastestLocationUpdateInterval": 10000,
I/TSLocationManager(30947):   "forceReloadOnBoot": false,
I/TSLocationManager(30947):   "forceReloadOnGeofence": false,
I/TSLocationManager(30947):   "forceReloadOnHeartbeat": false,
I/TSLocationManager(30947):   "forceReloadOnLocationChange": false,
I/TSLocationManager(30947):   "forceReloadOnMotionChange": false,
I/TSLocationManager(30947):   "forceReloadOnSchedule": false,
I/TSLocationManager(30947):   "foregroundService": false,
I/TSLocationManager(30947):   "geofenceInitialTriggerEntry": true,
I/TSLocationManager(30947):   "geofenceProximityRadius": 1000,
I/TSLocationManager(30947):   "geofenceTemplate": "",
I/TSLocationManager(30947):   "headers": {},
I/TSLocationManager(30947):   "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
I/TSLocationManager(30947):   "heartbeatInterval": -1,
I/TSLocationManager(30947):   "httpRootProperty": "location",
I/TSLocationManager(30947):   "httpTimeout": 60000,
I/TSLocationManager(30947):   "isMoving": false,
I/TSLocationManager(30947):   "locationTemplate": "",
I/TSLocationManager(30947):   "locationTimeout": 60,
I/TSLocationManager(30947):   "locationUpdateInterval": 1000,
I/TSLocationManager(30947):   "locationsOrderDirection": "ASC",
I/TSLocationManager(30947):   "logLevel": 5,
I/TSLocationManager(30947):   "logMaxDays": 3,
I/TSLocationManager(30947):   "maxBatchSize": -1,
I/TSLocationManager(30947):   "maxDaysToPersist": 1,
I/TSLocationManager(30947):   "maxRecordsToPersist": -1,
I/TSLocationManager(30947):   "method": "POST",
I/TSLocationManager(30947):   "minimumActivityRecognitionConfidence": 75,
I/TSLocationManager(30947):   "notificationColor": "",
I/TSLocationManager(30947):   "notificationLargeIcon": "",
I/TSLocationManager(30947):   "notificationPriority": 0,
I/TSLocationManager(30947):   "notificationSmallIcon": "",
I/TSLocationManager(30947):   "notificationText": "Location Service activated",
I/TSLocationManager(30947):   "notificationTitle": "",
I/TSLocationManager(30947):   "params": {},
I/TSLocationManager(30947):   "persist": true,
I/TSLocationManager(30947):   "schedule": [],
I/TSLocationManager(30947):   "startOnBoot": true,
I/TSLocationManager(30947):   "stationaryRadius": 25,
I/TSLocationManager(30947):   "stopAfterElapsedMinutes": 0,
I/TSLocationManager(30947):   "stopOnStationary": false,
I/TSLocationManager(30947):   "stopOnTerminate": false,
I/TSLocationManager(30947):   "stopTimeout": 5,
I/TSLocationManager(30947):   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
I/TSLocationManager(30947):   "url": "",
I/TSLocationManager(30947):   "enabled": false,
I/TSLocationManager(30947):   "schedulerEnabled": false,
I/TSLocationManager(30947):   "trackingMode": 1,
I/TSLocationManager(30947):   "odometer": 0,
I/TSLocationManager(30947):   "isFirstBoot": false
I/TSLocationManager(30947): }
I/TSLocationManager(30947): ╔═════════════════════════════════════════════
I/TSLocationManager(30947): ║ DEVICE SENSORS
I/TSLocationManager(30947): ╠═════════════════════════════════════════════
I/TSLocationManager(30947): ╟─ ✅  ACCELEROMETER: {Sensor name="Goldfish 3-axis Accelerometer", vendor="The Android Open Source Project", version=1, type=1, maxRange=2.8, resolution=2.480159E-4, power=3.0, minDelay=10000}
I/TSLocationManager(30947): ╟─ ✅  GYROSCOPE: {Sensor name="Goldfish 3-axis Gyroscope", vendor="The Android Open Source Project", version=1, type=4, maxRange=11.111111, resolution=0.001, power=3.0, minDelay=10000}
I/TSLocationManager(30947): ╟─ ✅  MAGNETOMETER: {Sensor name="Goldfish 3-axis Magnetic field sensor", vendor="The Android Open Source Project", version=1, type=2, maxRange=2000.0, resolution=1.0, power=6.7, minDelay=10000}
I/TSLocationManager(30947): ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(30947): ╚═════════════════════════════════════════════
I/TSLocationManager(30947): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(30947):   ✅  Google Play Services: connected (version code:12451000)
I/zygote  (30947): Do partial code cache collection, code=57KB, data=38KB
I/zygote  (30947): After code cache collection, code=57KB, data=38KB
I/zygote  (30947): Increasing code cache capacity to 256KB
D/TSLocationManager(30947): [c.t.locationmanager.data.a.c a] 
D/TSLocationManager(30947):   ✅  Opened database
D/TSLocationManager(30947): [c.t.locationmanager.data.a.c prune] 
D/TSLocationManager(30947):   ℹ️  PRUNE -1 days
D/NetworkSecurityConfig(30947): No Network Security Config specified, using platform default
D/TSLocationManager(30947): [c.t.locationmanager.data.a.a f] 
D/TSLocationManager(30947):   ✅  Opened database
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/location
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/motionchange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/activitychange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/geofenceschange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/geofence
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/heartbeat
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/http
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/schedule
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/connectivitychange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/enabledchange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/providerchange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/powersavechange
I/FA      (30947): Tag Manager is not found and thus will not be used
D/OpenGLRenderer(30947): HWUI GL Pipeline
I/OpenGLRenderer(30947): Initialized EGL, version 1.4
D/OpenGLRenderer(30947): Swap behavior 1
D/        (30947): HostConnection::get() New Host Connection established 0xa43e4a80, tid 31007
W/OpenGLRenderer(30947): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer(30947): Swap behavior 0
D/EGL_emulation(30947): eglCreateContext: 0xa43dfa00: maj 3 min 0 rcv 3
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfa00: ver 3 0 (tinfo 0x8bcb0110)
D/EGL_emulation(30947): eglCreateContext: 0xa43dfd60: maj 3 min 0 rcv 3
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfd60: ver 3 0 (tinfo 0x92667a00)
I/Choreographer(30947): Skipped 32 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfa00: ver 3 0 (tinfo 0x8bcb0110)
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfa00: ver 3 0 (tinfo 0x8bcb0110)
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfa00: ver 3 0 (tinfo 0x8bcb0110)
D/        (30947): HostConnection::get() New Host Connection established 0xa5da4d00, tid 30995
D/EGL_emulation(30947): eglMakeCurrent: 0xa43dfd60: ver 3 0 (tinfo 0x915ba240)
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler onListen] location
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler onListen] motionchange
D/TSLocationManager(30947): [c.t.f.b.streams.StreamHandler onListen] activitychange
D/TSLocationManager(30947): [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true

**Comment by christocracy** [comment]
Everything looks good in logs,  you’ve obviously not told the plugin to start.  So far nothing is unusual.

Show me your code you’ve implemented.

**Comment by christocracy** [comment]
Closed for lack of feedback.
