### ISSUE TITLE
help - ios motion activity detection

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#250]
so as I have mentioned I only used geofence and I have talk with you and you have advice me to set `disableMotionActivityUpdates: false,`
as

```
 bg.BackgroundGeolocation.ready(
      Config(
        enableHeadless: true,
        disableMotionActivityUpdates: false,
        stopOnTerminate: false,
        showsBackgroundLocationIndicator: false,
        startOnBoot: true,
        geofenceInitialTriggerEntry: false,
        geofenceModeHighAccuracy:
            false, // <-- consumes more power; default is false.
      ),
    ).then(
      (state) {
        if (!state.enabled) {
          // engage geofences-only mode:
          BackgroundGeolocation.startGeofences();
        }
      },
    );
```

but xcode when build the app it's crashed and close due to there is a permission I used but don't put description for it `NSMotionUsageDescription` so i putted it in info.plist and run again it's open put required a `motion activity detection` , what do you think!

and If I should request it from user I try use `bg.BackgroundGeolocation.requestPermission();` but it's only request the geolocation not motion too only on ios in android required both (geolocation and motion)

sorry and last thing I have in IOS location arrow appear always and I only start geofence it's normal or I missing something !?

**Comment by christocracy** [comment]
If you don’t want motion permission, why are configuring `disableMotionActivityUpdates: false`??

> I have in IOS location arrow appear always

It *will* appear as a *hollow* icon when geofences are monitored.  That’s normal and expected.

**Comment by niypoo** [comment]
> If you don’t want motion permission, why are configuring `disableMotionActivityUpdates: false`??
 
I asked you before to disabled MotionActivity if not necessary for geofence and you advice me to use   `disableMotionActivityUpdates: false`

**Comment by niypoo** [comment]
https://github.com/transistorsoft/flutter_background_geolocation/issues/249

**Comment by christocracy** [comment]
Think about the word *”disable”* and ask yourself the question “disable motion activity updates?  True or false?”

**Comment by christocracy** [comment]
> See API docs Config.disableMotionActivityUpdates

I didn’t tell you to set it *false*.  I merely directed you to read the docs.

**Comment by niypoo** [comment]
> > See API docs Config.disableMotionActivityUpdates
> 
> I didn’t tell you to set it _false_. I merely directed you to read the docs.
ops :S sorry , I see it know it's my bad

last one thing in android also "Location Service activated" in status bar ! it's normal also with geoFence only ?

**Comment by christocracy** [comment]
> in status bar ! it's normal also with geoFence only 

Periodically, yes.
