### ISSUE TITLE
Odometer not update for each onLocation

### ISSUE THREAD

**Issue by Ballrock** [transistorsoft/flutter_background_geolocation#255]
## Your Environment
* Plugin version: 1.7.3
* Platform: iOS
* OS version: iOS 13.4 
* Device manufacturer / model: Simulator
* Flutter info (`flutter doctor`):
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

  final geo.Config _geoConfig = geo.Config(
    desiredAccuracy: geo.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: Platform.isAndroid ? 0 : 1.0,
    desiredOdometerAccuracy: 50,
    minimumActivityRecognitionConfidence: 40, // Adjust lower for low-end devices
    allowIdenticalLocations: false,
    stopOnTerminate: true,
    startOnBoot: false,
    preventSuspend: true,
    logMaxDays: 1,
    locationUpdateInterval: 1000,
    heartbeatInterval: 30,
    disableStopDetection: true,
    pausesLocationUpdatesAutomatically: false,
    useSignificantChangesOnly: false,
    foregroundService: true,
    isMoving: true,
    stopTimeout: 5,
    notification: geo.Notification(
        title: "Test en cours",
        text: "Suivi GPS activé",
        priority: geo.Config.NOTIFICATION_PRIORITY_HIGH),
    // Debug & LOG
    debug: false,
    logLevel: geo.Config.LOG_LEVEL_ERROR,
    reset: true,
  );
```

## Expected Behavior
Odometer is update for every onLocation call according to configuration.

## Actual Behavior
Odometer is not update at each location even if the `horizontalAccuracy <= desiredOdometerAccuracy`. But seems to be update by "block" instead

In logs you can see multiple locations (our debug logs is call at each onLocation) that have different coordinates (few meters away) and still same odometer value.

Odometer "blocks" :
* 48 - 49 - 50
* 51 - 52 - 53
* 54 - 55 - 56

## Steps to Reproduce

1. LocationUpdateInterval at 1s
2. Location simulator "City Run"
3. Odometer is not update for each location

## Context

First of all, thank you for your work, this plugin saves us lot of time it's truly amazing !

We try to do an extremely accurate medical app that launch short run/walk test (some minutes) for user to determine his health according to standards.

Since it's at a low speed and distance we retrieve many locations to increase accuracy.

Can you explain how works the odometer update and why it seems to be update by "block" ? Is it for avoid wrong values when we are not in a straight line ?

Thank you in advance for your answers

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
flutter: ----DEBUG----
flutter: Location (48 - 2020-04-30 17:22:21.969970):
Distance : 175.9
Speed : 3.46
Speed Average : 3.2964583333333333
Accuracy : 10.0
Accuracy Average : 9.166666666666668
Coords : coords: 37.32475426,-122.02218992, acy: 10.0, spd: 3.46
flutter: ----DEBUG----
flutter: Location (49 - 2020-04-30 17:22:22.951711):
Distance : 175.9
Speed : 3.42
Speed Average : 3.2989795918367344
Accuracy : 10.0
Accuracy Average : 9.183673469387756
Coords : coords: 37.32475443,-122.02222838, acy: 10.0, spd: 3.42
flutter: ----DEBUG----
flutter: Location (50 - 2020-04-30 17:22:23.970025):
Distance : 175.9
Speed : 3.25
Speed Average : 3.2979999999999996
Accuracy : 10.0
Accuracy Average : 9.200000000000001
Coords : coords: 37.32475483,-122.02226661, acy: 10.0, spd: 3.25
flutter: ----DEBUG----
flutter: Location (51 - 2020-04-30 17:22:24.963996):
Distance : 186.1
Speed : 3.15
Speed Average : 3.295098039215686
Accuracy : 10.0
Accuracy Average : 9.215686274509805
Coords : coords: 37.32475499,-122.02230437, acy: 10.0, spd: 3.15
flutter: ----DEBUG----
flutter: Location (52 - 2020-04-30 17:22:25.948520):
Distance : 186.1
Speed : 3.27
Speed Average : 3.2946153846153843
Accuracy : 5.0
Accuracy Average : 9.134615384615385
Coords : coords: 37.32475599,-122.02234239, acy: 5.0, spd: 3.27
flutter: ----DEBUG----
flutter: Location (53 - 2020-04-30 17:22:26.968737):
Distance : 186.1
Speed : 3.18
Speed Average : 3.292452830188679
Accuracy : 10.0
Accuracy Average : 9.150943396226415
Coords : coords: 37.32475582,-122.02238087, acy: 10.0, spd: 3.18
flutter: ----DEBUG----
flutter: Location (54 - 2020-04-30 17:22:27.852759):
Distance : 196.3
Speed : 3.19
Speed Average : 3.2905555555555557
Accuracy : 10.0
Accuracy Average : 9.166666666666666
Coords : coords: 37.32475578,-122.02241978, acy: 10.0, spd: 3.19
flutter: ----DEBUG----
flutter: Location (55 - 2020-04-30 17:22:28.969342):
Distance : 196.3
Speed : 3.2
Speed Average : 3.288909090909091
Accuracy : 5.0
Accuracy Average : 9.09090909090909
Coords : coords: 37.32475648,-122.02245914, acy: 5.0, spd: 3.2
flutter: ----DEBUG----
flutter: Location (56 - 2020-04-30 17:22:29.949515):
Distance : 196.3
Speed : 3.27
Speed Average : 3.2885714285714287
Accuracy : 5.0
Accuracy Average : 9.017857142857142
Coords : coords: 37.32475587,-122.02249983, acy: 5.0, spd: 3.27
```

</details>

**Comment by christocracy** [comment]
eg, 
- where location `A` is *very* close to `B`, the plugin will ignore that calculation.
- When location `C` arrives, the odometer will be incremented with a distance of `A->C`
```
A.B........C
```

**Comment by Ballrock** [comment]
Thanks for the explanation and the explicit exemple, seems logic :)
But, with this in head, can we lost the last distance `A->B` if we stop the GPS tracking after `B` ? (ie. the end of our timing test 😄)

Unfortunately for us, in our case of walk/run, ~10 meters is'nt that close 😞.

**Comment by christocracy** [comment]
if the accuracy of locations `A` and `B` are both `<= 10` meters and the distance between them is `10` meters, the odometer calculation would be applied.

If the average accuracy between points `A` and `B` is `100` meters and the calculated distance is `10`, you're just introducing a big error in the calculation.

**Comment by Ballrock** [comment]
Yes , i understand the problem :).
Anyways, i will refactor our code with those informations in mind.

Thank for your time 👍

**Comment by christocracy** [comment]
You have to think of locations *not* as a simple point in space but as *circles* of radius `accuracy`.
