### ISSUE TITLE
iOS location fetch not working when App is terminated (or killing App)

### ISSUE THREAD

**Issue by plizanabesa** [transistorsoft/flutter_background_geolocation#256]
## Your Environment
* Plugin version: 1.7.1
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B88, locale en-CL)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    static Future<bg.State> enableGeoLocationService({
     Function onLocation,
     Function onLocationError,
     Function onMotionChange,
     Function onActivityChange,
     Function onProviderChange,
     Function onConnectivityChange,
     Function onHttp,
     Function onAuthorization,
     double radius,
    }) async {
    bg.BackgroundGeolocation.onLocation(onLocation, onLocationError);
    bg.BackgroundGeolocation.onMotionChange(onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(onConnectivityChange);
    bg.BackgroundGeolocation.onHttp(onHttp);
    bg.BackgroundGeolocation.onAuthorization(onAuthorization);

    bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20.0,
      stopOnTerminate: false,
      stationaryRadius: radius, // 150 mts
      reset: true,
      startOnBoot: true,
      debug: DEBUG ? true : false,
      logLevel: DEBUG ? bg.Config.LOG_LEVEL_VERBOSE : bg.Config.LOG_LEVEL_OFF
    ));

    return state;
    }

    static Future<void> startGeoLocationService() async {
     await bg.BackgroundGeolocation.start();
    }

    static Future<void> stopGeoLocationService() async {
     await bg.BackgroundGeolocation.stop();
    }
```
## Expected Behavior

- When iOS App is terminated, and then leaving stationary geofence (aprox 200mts), the App should be booted to the background and then locations should be sent to Firestore.
- Note 1: Locations are not sent to the URL available in Config. Instead, they are sent to Firestore, which is configured on the onLocation function.
- Note 2: Only onLocation function reports data to Firestore.

## Actual Behavior

- When debugging, I receive the in app notification indicating that I have exited the stationary region.
- However, the App doesn't boot to background and hence I do not receive any locations in Firestore.
- When in Foreground or Background, everything works Ok and location updates are received in Firestore.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Trying to receive location updates with the App terminated in iOS. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
> I receive the in app notification indicating that I have exited the stationary region.

This *means* your app has booted.  Are you observing the logs?  See wiki *Debugging*.

**Comment by plizanabesa** [comment]
Yes. Please see line 357

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/4561458/background-geolocation.log)

**Comment by christocracy** [comment]
Are you ensuring that your application calls `BackgroundGeolocation.ready` *every time* your app launches?  `#ready` is a signal to the plugin that your app is launched and ready to receive events.

**Comment by plizanabesa** [comment]
Actually it doesn't. The user needs to press a button to activate `BackgroundGeolocation.ready`. However, I am doing tests terminating the App with the button already pressed, i.e. with `BackgroundGeolocation.ready` already activated.

I just did another test adding a URL to the .Config and now it works. We receive locations in that URL, however no locations are sent to Firestore. See line 10025 of the new attached logs. 
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/4561657/background-geolocation.log)

Could it be something related to the following scenarios?
(i) onLocation function -from which we call Firestore- only runs properly if the `BackgroundGeolocation.ready` is called everytime the App is launched. 

 or

(ii) It is only possible to send data from terminated Apps through the URL in .Config.

**Comment by christocracy** [comment]
You *must* call `#ready` **each time the app launches**.  Think of the plugin like an electronic device, such as a stereo receiver.
- `#ready` is like plugging in the AC cord.
- `#start` is the power **ON** button.
- `#stop` is the power **OFF** button.
- Adding event-listeners (eg: `onLocation`) is like wiring up a speaker.

When app boots:
- You plug the power cable in (ie: `#ready), no matter what.  Regardless if the user has logged in or not.
- When you want to track the user, you turn the power on (ie:  `#start`)
- When you want to *stop* tracking the user, you turn the power *off* (ie: `#stop`).

**Comment by christocracy** [comment]
If you're using Firestore, perhaps you're interested in [background_geolocation_firebase](https://github.com/transistorsoft/flutter_background_geolocation_firebase) adapter which will automatically relay recorded locations to firestore for you.

**Comment by plizanabesa** [comment]
Thanks, I moved the `BackgroundGeolocation.ready` to the main and now I am receiving locations both in the URL and in Firestore. 

Regarding the Firestore adapter, I didn't use it because I needed to add extra fields to the location. I just realized that BackgroundGeolocation.Location had the `extras` fields. Thanks anyways.

**Comment by christocracy** [comment]
Correct.  `#extras` allows you to add any arbitrary data to each recorded location.

**Comment by altanod0627** [comment]
@plizanabesa Hello. i need how i fetch terminated app location receive in main?

**Comment by christocracy** [comment]
Read the wiki "Philosophy of Operation" and "Debugging".

Also read api docs Config.stopOnTerminate.  Go outside for a nice long test >1km with a real device.

**Comment by altanod0627** [comment]
@christocracy android sticky notification is show and hide toggled. how i run always show notification when started that plugin?

**Comment by christocracy** [comment]
> how i run always show notification when started that plugin?

You don't need to worry about that.  Did you read what I told you to read?

**Comment by radixdt3349** [comment]
HI @plizanabesa  and @christocracy 

I have integrated the plugin into my project and it is working fine except below mentioned issues.

1. Tracking is not working in iOS after terminating the app.
2. Tracking is taking time to start tracking again in Android after termination.
3. In vivo device i have seen noisy coordinates in stationary mode.

I just want to know does this really works? if yes then how because i have did everything as shown in document
