### ISSUE TITLE
Query : Can I use the plugin sqlite database for query ?

### ISSUE THREAD

**Issue by jogiji** [transistorsoft/flutter_background_geolocation#257]
Thing is I want to persist the locations that are obtained from the plugin in headless task mode.
The database that I use some how errors out when accessed in headless task.
So my question to you is that can I utilize the plugin's internal sqlite database in some manner so that i can obtain locations that were recorded in headless task mode.

**Comment by christocracy** [comment]
The plugin’s internal database is not meant to act as a long-term, queryable database.  It merely acts as a queue for its own http service.

You should put locations into your own database.

What is the error with your current database?

**Comment by jogiji** [comment]
Problem is not with database as such. But with path_provider plugin which doesnot work under headless task. Basically if i try to persist locations under headless task I get following error :
`Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

**Comment by christocracy** [comment]
What plugin are you using for sqlite, [this one](https://pub.dev/packages/sqflite#-readme-tab-)?

**Comment by jogiji** [comment]
For database I use https://pub.dev/packages/sembast
If I may add further I utilise path_provider plugin to obtain the storage path for database. If I use the hard coded path then I am able to persist the locations in my database. Obviously this is not right solution hence path_provider comes into the picture and it works fine when app is running. But in headless task this is an issue.

**Comment by christocracy** [comment]
I just whipped up a quick hello world using [sqflite](https://pub.dev/packages/sqflite#-readme-tab-) and it successfully performs inserts in my headless-task.

**Comment by jogiji** [comment]
Ohhk.. maybe then i need to use sqflite for this purpose .. Thanks @christocracy .

**Comment by christocracy** [comment]
I just modified my simple hello world to use `semblast` and it works too.

**Comment by jogiji** [comment]
Sembast works fine on its own but when combined with path_provider it has issues.. anyways can you pls share your hello world so that I can seen what I might be missing.

**Comment by christocracy** [comment]
I *used* `path_provider`:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;
import 'package:path_provider/path_provider.dart';
import 'package:sembast/sembast.dart';

import 'package:path/path.dart';
import 'package:sembast/sembast_io.dart';


void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
  // Implement a 'case' for only those events you're interested in.
  switch (headlessEvent.name) {
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      _insertLocation(location.coords.latitude, location.coords.longitude);
      break;
    default:
      // Just fake a location on every other headless event to get a record inserted.
      _insertLocation(1.00, 1.00);
      break;
  }
}

Database _database;

Future<Database> _openDatabase() async {
  if (_database != null) {
    return _database;
  }

  // get the application documents directory
  var dir = await getApplicationDocumentsDirectory();
  // make sure it exists
  await dir.create(recursive: true);
  // build the database path
  var dbPath = join(dir.path, 'my_database.db');
  // open the database
  return await databaseFactoryIo.openDatabase(dbPath);
}

void _insertLocation(double lat, double lng) async {
  Database database = await _openDatabase();
  var store = intMapStoreFactory.store('locations');
  await store.add(database, {"lat": lat, "lng":lng});
  _getLocations();
}

void _getLocations() async {
  // Get the records
  Database database = await _openDatabase();

  StoreRef store = intMapStoreFactory.store('locations');

  final recordSnapshot = await store.find(database);
  print("[getLocations]");

  recordSnapshot.forEach((RecordSnapshot record) {
    print("[record] ${record.value}");
  });
}

void main() {
  runApp(MyApp());
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Database _database;

  @override
  void initState() {
    super.initState();

    _openDatabase().then((Database database) {
      _database = database;
    });

    ////
    // 1.  Listen to events (See docs for all 12 available events).
    //

    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) async {
      print('[location] - $location');
      _insertLocation(location.coords.latitude, location.coords.longitude);
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });

    ////
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopTimeout: 1,
        stopOnTerminate: false,
        enableHeadless: true,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //

        bg.BackgroundGeolocation.start();
      }
    });
  }

  void _incrementCounter() {
    bg.BackgroundGeolocation.getCurrentPosition(
      samples: 1
    );

    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by jogiji** [comment]
Much thanks 🙏

**Comment by jogiji** [comment]
@christocracy If its not late for you. I tried above example still it is not working.
Can you let me know the version of path_provider that you are using.
Fyi : I am testing this on an Android x86 Emulator

**Comment by christocracy** [comment]
I took whatever latest version was today.  Try it on a real device instead.

**Comment by jogiji** [comment]
Well still the same issue on device as well. `2020-05-02 08:21:36.743 20420-20487/no.keystone.mobile E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
    #2      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:76:39)
    #3      _openDatabase (package:keystone_flutter/main.dart:33:19)
    #4      _insertLocation (package:keystone_flutter/main.dart:43:29)
    #5      headlessTask (package:keystone_flutter/main.dart:20:7)
    #6      _headlessCallbackDispatcher.<anonymous closure> (package:flutter_background_geolocation/models/background_geolocation.dart:1593:15)
    #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
    #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
    #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
    #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
    #11     _rootRun (dart:async/zone.dart:1126:13)
    #12     _CustomZone.run (dart:async/zone.dart:1023:19)
    #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #14     _invoke3 (dart:ui/hooks.dart:302:10)
    #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)`

Fyi : I am using branch stable of Flutter 
Could it be that my android folder inside project has some issue. I will regenerate that and test.
Thank you for your help @christocracy

**Comment by jogiji** [comment]
@christocracy  I can confirm a fresh project runs perfectly well with your example. So may be there is an issue with Android project itself shall let you know about it soon.

**Comment by HeikoMueller** [comment]
I run into the exact same issue with path provider in headless mode. Tried both with version 1.6.7 and 1.6.8. 

2020-05-18 12:19:00.217 18715-18750/com.example.immu_v4 E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

@christocrac Have you been able to get it running inside your existing project, finally ?

**Comment by jogiji** [comment]
@HeikoMueller I was able to resolve this issue .. for me it was the flutter classic bluetooth plugin which was ultimately causing the issue..
So I modified that plugin and used that in my project to get around this issue..

**Comment by HeikoMueller** [comment]
@jogiji Thanks for your quick reply. So the classic bluetooth plugin did interfere with the path_provider plugin? How did that happen?

**Comment by jogiji** [comment]
@HeikoMueller apparently this issue can throw some light https://github.com/pauldemarco/flutter_blue/issues/187
I found similar issue with classic bluetooth plugin, which was not actively developed and hence i had to modify certain part of the code to make it work in background mode.

**Comment by HeikoMueller** [comment]
@jogiji thx!
