### ISSUE TITLE
Locations out of the way far from the device

### ISSUE THREAD

**Issue by raphaaugustosilva** [transistorsoft/flutter_background_geolocation#258]
## Your Environment
* Plugin version: 1.7.1
* Platform: Android (could not test on iOS yet)
* OS version: All
* Device manufacturer / model: Moto X4 / Nexus 5 / Moto G5
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale pt-BR)
    • Flutter version 1.12.13+hotfix.9 at /Users/raphael.silva.local/Desenvolvimento/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/raphael.silva.local/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.0
[✓] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

  bg.BackgroundGeolocation.onLocation((bg.Location location) => myOnLocation(location));

  await bg.BackgroundGeolocation.ready(
        bg.Config(
          transistorAuthorizationToken: transistorAuthorizationToken, 
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
          distanceFilter: 20, 
          activityRecognitionInterval: 3000,
          stopTimeout: 5,
          stopOnTerminate: true,
          startOnBoot: false,
          debug: (kReleaseMode) ? false : true,
          logLevel: (kReleaseMode) ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_DEBUG,
          stationaryRadius: 25,
        ),
      );

  final List<bg.Location> _realtimePositions = <bg.Location>[];
  
  void myOnLocation(bg.Location position) {
    if (position.sample) return;
    _realtimePositions.add(position);
    renderMyMap(_realtimePositions);
  }


```

## Expected Behavior
Continue to capture the user locations without these points far from him

## Actual Behavior
Sometimes (often) these locations are being received. [You can check it here](https://drive.google.com/open?id=1YhVqHdhlDJ8qKV5ia40Q9VZUUY0EkNDk)

## Context
I am capturing the locations and rendering them on a map. But sometimes there are locations that are "out of the way", far from the device.
I've captured the screen outside my app (from [transistor tracker](http://tracker.transistorsoft.com/yes4track?device=15751&end=2020-5-1&start=2020-5-1)) in order to check if is a problem with my app`s map render logic but these points are rendered into tracker transistorsoft site too.

Link of the image: [Screenshot with this behaviour](https://drive.google.com/open?id=1YhVqHdhlDJ8qKV5ia40Q9VZUUY0EkNDk)

## Steps to Reproduce
1. Configure the gb.BackgroundGeolocation as above and start moving normally
2. Frequently, the component is receiving this far away locations that I mentioned above

**Comment by christocracy** [comment]
It can happen depending on the quality of the device and the nature of the network environment.

You’re expected to filter these yourself, typically with `location.coords.accuracy`.

**Comment by christocracy** [comment]
Btw, all your links above are 404

**Comment by raphaaugustosilva** [comment]
Sorry, now the links are correct. If you open the links, this is happening because the accuracy?

**Comment by christocracy** [comment]
The plugin does not filter anything.  It’s not unusual to receive a poor location periodically,  typically, these location will have a poor accuracy (eg: `1000`).

The plugin is only the messenger delivering locations exactly as provided from the native api.  It’s your responsibility to filter as desired.

**Comment by raphaaugustosilva** [comment]
Ok. I didn`t find the accuracy in the docs. This property range is from 0 to 1000?

**Comment by christocracy** [comment]
No, it’s 0 to *anything*.  A location is not a simple point in space.  It’s a circle of radius `accuracy` (Meters).  The actual location is somewhere in that circle.

When you have an accuracy of 5 meters (typical for gps), you have a small circle of probability.

When you have an accuracy of 1000 meters (typical of location from cell tower), you have a large circle of probability of where the actual location is.
