### ISSUE TITLE
Not an issue: Question about bulk licensing of your product

### ISSUE THREAD

**Issue by wemersonrv** [transistorsoft/flutter_background_geolocation#261]
Hello, this is not an issue. I just have a question about licensing.

If i buy a 5 licence package (**VENTURE**), each license will need to be linked to a app package/name right?

Well, i'm freelance developer... so when i deliver the final product to my customers, i transfer the control of all dashboards and services to them. How can i do to proceed the transfer of `flutter_background_geolocation` because it's linked to a package name? Can i unlink my app package from my license and link it again to my customer's license? or can i transfer a single license to my customer?

**Comment by christocracy** [comment]
Please email me about license questions.
