### ISSUE TITLE
how to distinguish the offline location and online location?

### ISSUE THREAD

**Issue by liqiang1995** [transistorsoft/flutter_background_geolocation#262]
How are you?
I made app using this plugin.
Server record both phone's online and offline locations.
And when the phone is online, Server does the special treatment.
but when the phone is offline, Server have to ignore the locations and only record it.
in this case, how to distinguish the offline location and online location?
thank you.

**Comment by christocracy** [comment]
See event `onConnectivityChange`.

Use `setConfig` to add your custom flag to `Config.extras`.

**Comment by liqiang1995** [comment]
sorry, I can not understand.
please send me an example.
or reference link.
thank you

**Comment by christocracy** [comment]
See API docs (linked in table-of-contents in README)
- `onConnectivityChange`
- `setConfig`
- `Config.extras`

**Comment by liqiang1995** [comment]
the flag should be included in post data.
so, Server can distinguish them with flag.

**Comment by christocracy** [comment]
>the flag should be included in post data.

That's *exactly* what `Config.extras` does.  It allows you to append *any* arbitrary `{}` to each recorded location and posted to your server.
