### ISSUE TITLE
onActivityChange callback generates a series of events every second

### ISSUE THREAD

**Issue by cedric-clain** [transistorsoft/flutter_background_geolocation#263]
The onActivityChanged callback generates several events per second.

## Your Environment
* Plugin version: 1.6.0
* Platform: iOS
* OS version: iOS 12.4.5
* Device manufacturer / model: iPhone 6
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.13.3, on Mac OS X 10.14.6 18G103, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        preventSuspend: true,
        enableHeadless: true,
        distanceFilter: 50,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior

I would expect the onActivityChange callback to be triggered only when a change in activity has actually been detected (e.g. from still to in_vehicle), and the obtained event would indicate the new activity type.

Also, for example, if I go for a walk, I would expect the onActivityChange callback to send a "walking" event at some point after I've started walking, and a "still" event when I've finished walking.

## Actual Behavior

The onActivityChange callback is triggered several times per second. E.g. below is a log of events recorded and timestamp for when the device was still on my desk (no change in activity):

```
flutter: 2020-05-06T15:46:36.034397 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:46:38.251868 - [ActivityChangeEvent still (33%)]
flutter: 2020-05-06T15:46:41.427563 - [ActivityChangeEvent still (33%)]
flutter: 2020-05-06T15:46:42.071587 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:47:05.640722 - [ActivityChangeEvent still (33%)]
flutter: 2020-05-06T15:47:08.823837 - [ActivityChangeEvent still (33%)]
flutter: 2020-05-06T15:47:10.120756 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:47:19.928638 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:47:24.067268 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:47:57.151948 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:48:00.319670 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:05.523917 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:08.703716 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:43.054013 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:46.276061 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:48.187692 - [ActivityChangeEvent still (100%)]
flutter: 2020-05-06T15:49:51.374534 - [ActivityChangeEvent still (100%)]
```

Also, on a walk e.g., the callback returns a series of alternating events (often 2 or 3 every second), e.g. walking, still, on_foot, still, walking etc.

## Steps to Reproduce

Code to reproduce:

```
bg.BackgroundGeolocation.onActivityChange(
        (bg.ActivityChangeEvent event) async {
      print(DateTime.now().toIso8601String() + ' - ' + event.toString());
      var location = await bg.BackgroundGeolocation.getCurrentPosition();
    });
```

## Context

From reading the documentation for the callback, it says "Your callback will be executed each time the activity-recognition system receives an event". I'm assuming here that this is talking about the native activity-recognition functionality? 

I guess a question which I have is whether this is simply sending over everything which the native activity recognition system is generating, or is there a way to customise this so that less events are generated, and ideally, that the callback is triggered only when an activity change is detected?

Overall, I'm trying to build a timeline (a list of activities of the user). Each item on the timeline should be a discrete activity. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin is merely relaying to you exactly what comes out of the iOS CMMotionActivity API.
