### ISSUE TITLE
No ReadMe instructions about needing to modify the AndroidManifest for the example code

### ISSUE THREAD

**Issue by awarmfastbear** [transistorsoft/flutter_background_geolocation#265]
## Your Environment
* Plugin version: 1.3.2
* Platform: Android 8.1+
* OS version: Windows 10 Version	10.0.19041 Build 19041
* Device manufacturer / model: Pixel 3 Emulator
* Flutter info (`flutter doctor`):
```
C:\Users\Mclovin\Desktop\gps_learning_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version
    10.0.19041.207], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
```

## Expected Behavior

Running the example code here: https://pub.dev/packages/flutter_background_geolocation#-example-tab- should launch the Android app without issues. 

## Actual Behavior

The app fails to start with the example code. Instead I get the below errors. I can fix it by manually modifying the android/app/src/main/AndroidManifest.xml by adding a couple lines as seen from this gist: https://gist.github.com/awarmfastbear/7d9638a1d54d2bf7ef84a43f7342197a

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
C:\Users\Mclovin\Desktop\gps_learning_app\android\app\src\debug\AndroidManifest.xml:10:9-41 Error:
	Attribute application@label value=(gps_learning_app) from AndroidManifest.xml:10:9-41
	is also present at [com.intentfilter:android-permissions:0.1.8] AndroidManifest.xml:11:18-50 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-29:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(gps_learning_app) from AndroidManifest.xml:10:9-41
  	is also present at [com.intentfilter:android-permissions:0.1.8] AndroidManifest.xml:11:18-50 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-29:19 to override.

```

## Steps to Reproduce

1. Create a flutter app using flutter create <name>
2. Replace the main.dart file with the code from https://pub.dev/packages/flutter_background_geolocation#-example-tab-
3. Try and start the app and look at the Debug console.

## Context

Test the example code / example apps.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
It's [right there are the top of the Android Setup Guide](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md)
