### ISSUE TITLE
Persistent notification always shows for foreground service with sound whenever location is fetched. Can it be removed?

### ISSUE THREAD

**Issue by MobilyteApps** [transistorsoft/flutter_background_geolocation#266]
## Your Environment
* Plugin version:1.3.2
* Platform: Android
* OS version:10
* Device manufacturer / model:One plus 7
* Flutter info (`flutter doctor`): no issue in with device, so I am adding no info here
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
No notification should appear at background data fetching for location

## Actual Behavior
WHenever location is fetched, notification along with sound pops

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

![Screenshot_20200509-164114](https://user-images.githubusercontent.com/39619790/81605710-85d4bd00-93ef-11ea-9fb9-aba576438ca9.png)

**Comment by christocracy** [comment]
The foreground service notification is required by the os.

As for sounds, see api docs Config.debug.

**Comment by MobilyteApps** [comment]
> The foreground service notification is required by the os.
> 
> As for sounds, see api docs Config.debug.

I was trying to make it work something like google fit. It does not shows notification. That is why its concerning for me, as in docs also its provided that notification has to be shown to make it work at background

**Comment by christocracy** [comment]
Android requires a foreground service to record location in background.  Android foreground-services require a persistent notification.

**Comment by MobilyteApps** [comment]
Can sound be turn off?

**Comment by christocracy** [comment]
If you want a location only about every 1000 meters, configure see Config.useSignificantChangesOnly and a foreground-service won’t be used.

**Comment by MobilyteApps** [comment]
> If you want a location only about every 1000 meters, configure see Config.useSignificantChangesOnly and a foreground-service won’t be used.

and it will keep working after 1000 meters even after a boot? right?

**Comment by christocracy** [comment]
>Can sound be turn off?

Are you reading [what I write](https://github.com/transistorsoft/flutter_background_geolocation/issues/266#issuecomment-626922768)?

**Comment by MobilyteApps** [comment]
> > Can sound be turn off?
> 
> Are you reading [what I write](https://github.com/transistorsoft/flutter_background_geolocation/issues/266#issuecomment-626922768)?



> > Can sound be turn off?
> 
> Are you reading [what I write](https://github.com/transistorsoft/flutter_background_geolocation/issues/266#issuecomment-626922768)?

My bad, missed that line!! Anyway last concern does after 1000m even after reboot willkeep working after boot as foreground is closed for this case as I would be using this case now.

**Comment by MobilyteApps** [comment]
My concern here is why foreground service is used. Instead workmanager/jobscheduler can be used. So that it will drain less battery and there is no notification centre always shown in app. Its just a suggestion. I hope you consider

**Comment by christocracy** [comment]
>My concern here is why foreground service is use

This plugin was designed for long-term, aggressive tracking of devices for "fleet-tracking" use-cases.  It was originally designed for tracking emergency-workers in disaster zones where life depended on it.

>Instead workmanager/jobscheduler can be used

My [`background_fetch`](https://github.com/transistorsoft/flutter_background_fetch) **IS** `WorkManager/JobScheduler`.

>does after 1000m even after reboot will keep working

Yes, of course.

**Comment by christocracy** [comment]
You're completely free to use `background_fetch` to periodically execute `#getCurrentPosition`.
