### ISSUE TITLE
Counting time stationary at same position

### ISSUE THREAD

**Issue by alexlopespereira** [transistorsoft/flutter_background_geolocation#269]
I'd like some advices on how to use this plugin to measure the time the cellphone remains stationary at the same position. My goal is to measure this time even if the cellphone remains stationary for more than one day. 
I consider stationary the cellphone that remains in a circular fence, for instance, with radius of 200m (656 ft).

**Comment by christocracy** [comment]
Perhaps you’re interested in the plugin’s geofencing features?  See api docs `#addGeofence`

**Comment by alexlopespereira** [comment]
Ok. This meets half of my requirements: it identifies when the cellphone leaves the fence.
But how do you differ the stationary case (no geo points acquired) and one of the following situantions: the app was uninstalled and reinstalled after a day, was on airplane mode or was or the GPS location was disabled?

In my application I would not count such time as stationary, but as unknown.

**Comment by christocracy** [comment]
> the app was uninstalled and reinstalled after a day

What do you expect the plugin to do here?  Magic?  Obviously the plugin has nothing to offer you if the user uninstalls the app.

>  was on airplane mode or was or the GPS location was disabled?

See api docs event `#onProviderChange`.  You might also be interested in `onActivityChange`.  In fact, research all the events.
