### ISSUE TITLE
Help - Many notification location service enabled 

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#272]
I'm using only GeoFence and I have noticed The `Location Service is Enabled` notification show up many time in short period time 45 in 3 hours so I want to know what is wrong in my code or Hoe can decrement that.

OS : Android 10

```
 //start geoFence
      bg.BackgroundGeolocation.ready(
        Config(
          disableLocationAuthorizationAlert: true,
          enableHeadless: true,
          disableMotionActivityUpdates: true,
          stopOnTerminate: false,
          startOnBoot: true,
          geofenceInitialTriggerEntry: false,
          geofenceModeHighAccuracy:
              false, // <-- consumes more power; default is false.
        ),
      ).then(
        (state) {
          if (!state.enabled) {
            // engage geofences-only mode:
            BackgroundGeolocation.startGeofences();
          }
        },
      );
```

![97948518_237537230645556_3956751652370776064_n](https://user-images.githubusercontent.com/13227239/82053526-c9644b00-96bd-11ea-8796-3e4f66623042.jpg)

**Comment by christocracy** [comment]
The plugin must still periodically request a location to determine geofences in proximity.  

A foreground-service is initiated for a *brief instant* when ever a location is requested, when your app boots and when a geofence event occurs.

**Comment by niypoo** [comment]
> The plugin must still periodically request a location to determine geofences in proximity.
> 
> A foreground-service is initiated for a _brief instant_ when ever a location is requested, when your app boots and when a geofence event occurs.

so there is any way to decrement these attempts. 
45 in 3 hours it's to many an announcing

**Comment by christocracy** [comment]
If that's your development device, the number is going to be inflated because of booting your app all the time.

**Comment by christocracy** [comment]
My Pixel 3a @ 10 displays `~31 per day` with location+geofencing mode and I'm regularly out field-testing with this device.

**Comment by niypoo** [comment]
no not mine, it's device of one of tester , that noticed that and he disabled that and send informed me about that , so I don't want annoy users for make them disabled this feature

**Comment by christocracy** [comment]
Regardless of geofence-only mode, the plugin *does* launch a foreground-service periodically for a *brief instant*.

**Comment by christocracy** [comment]
You can modify the title and text of the notification via `Config.notification`

**Comment by niypoo** [comment]
> You can modify the title and text of the notification via `Config.notification`

I have used `useSignificantChangesOnly` options and set it to true and I noticing decrement that notifications shows in notification bar ! is this way right ?

**Comment by christocracy** [comment]
useSignificantChangesOnly isn’t use with `startGeofences`.

**Comment by niypoo** [comment]
> useSignificantChangesOnly isn’t used with `startGeofences`.
I have to test it again :(

**Comment by christocracy** [comment]
I've given the geofencing-only system a refactoring.  If your Android app is monitoring less than `100` geofences, the SDK will no longer initiate its *infinite geofencing* system to periodically query geofences-in-proximity.  A foreground-service will only invoke when a geofence event occurs.  Will be available in next merge to master.

**Comment by niypoo** [comment]
> I've given the geofencing-only system a refactoring. If your Android app is monitoring less than `100` geofences, the SDK will no longer initiate its _infinite geofencing_ system to periodically query geofences-in-proximity. A foreground-service will only invoke when a geofence event occurs. Will be available in next merge to master. iOS already behaves like this (though iOS' geofence maximum is only `20`).

sounds great , thank you for remember that task .
I'm waiting this release .
and please let me know if there any changes I should do to active this new feature.


```

Config(
          disableLocationAuthorizationAlert: true,
          enableHeadless: true,
          disableMotionActivityUpdates: true,
          stopOnTerminate: false,
          startOnBoot: true,
          geofenceInitialTriggerEntry: false,
          geofenceModeHighAccuracy:
              false, // <-- consumes more power; default is false.
        ),

```

**Comment by christocracy** [comment]
There’s nothing special to do.  It’s all automatic.

**Comment by niypoo** [comment]
> There’s nothing special to do. It’s all automatic.

Awesome

**Comment by christocracy** [comment]
Try installing latest `1.9.1`.  If you're upgrading from before `1.9.0`, see the CHANGELOG.
