### ISSUE TITLE
Scheduling task in order to capture geolocation in background

### ISSUE THREAD

**Issue by alexlopespereira** [transistorsoft/flutter_background_geolocation#273]
Do you thing it would be a good idea use a native code (such as this one https://www.hackingwithswift.com/example-code/system/how-to-run-code-when-your-app-is-terminated) in order to capture geolocation in background on time based triggered events on iOS?

I do not need fixed periods. I know iOS will not serve on fixed periods. My application also is able to cope with a large range of periods up to 2 or 3 hours.

**Comment by christocracy** [comment]
Your link is *exactly* what [background_fetch](https://github.com/transistorsoft/flutter_background_fetch) is.

**Comment by christocracy** [comment]
Apple uses a machine-learning algorithm to adjust the frequency of *fetch* events.
- If user doesn't open your app daily, Apple will stop firing events.
- If user explicitly terminates your app, Apple will stop firing *fetch* events.

Here's the recent events of the [*background_fetch*](https://github.com/transistorsoft/flutter_background_fetch) `/example` app (I try to take care to open the app daily):
![](https://dl.dropbox.com/s/3z7hyeeu69sijki/Screenshot%202020-05-18%2010.55.46.png?dl=1)

**Comment by alexlopespereira** [comment]
I need to have my app executed in background more often than in your image.
Something from 30 to 120 minutes. The period can vary in this range. Do you
believe this is possible using this plugin?

Thanks,
--
Alex

**Comment by christocracy** [comment]
Apple doesn’t seem to care about one’s needs.  Sometimes, what we *want* is simply *impossible*.
