### ISSUE TITLE
Galaxy S7 Not Working When Screen is Blacked

### ISSUE THREAD

**Issue by dirjud** [transistorsoft/flutter_background_geolocation#278]
## Your Environment
* Plugin version: git cc3b753
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung Galaxy S7
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1.0,
      stopOnTerminate: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      startOnBoot: false,
      debug: false,
      locationAuthorizationRequest: "WhenInUse",
      reset: true,
      heartbeatInterval: 60,
      isMoving: true,
      stopAfterElapsedMinutes: 60 * 10,      // automatically stop if not done in 10 hours
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION,      // don't jump to roads
      foregroundService: true,      // android only
      notification: bg.Notification(
          // android only
          title: "OYO",
          text: "Tracking your race"),

      url: RPC.server + "/rest/result/Points/insert",
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 50,
      params: {
        "user_id": _user["id"],
        "participant_id": _participantId,
        "dev_id": _deviceId,
      },
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
    )
```

## Expected Behavior

On other Android phones and iOS, our app runs fine when the screen is blanked. Our app is tracking a timed race.

## Actual Behavior

On a galaxy S7 we are testing with, location updates stop or only occur occasionally when the screen is blacked  (and when they occur they are not accurate). The foreground service icon is visible in the system tray, however. All other phones we have tested (S8, S9, Pixel 1 through 4) and all iPhones, work as expected and produce location updates when the screen is blacked.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See new addition to [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#android-10-and-when-in-use-location-authorization) poster yesterday for those using *When In Use* authorization.

**Comment by dirjud** [comment]
You had previously had us add those lines to our AndroidManifest.xml and as you can see from our config, we call it with isMovin: True. We do get our apps icon in the system tray, so the foreground service seems to be working, at least on Pixels and S8 and S9. We are experiencing this problem on a Galaxy S7 only.

**Comment by christocracy** [comment]
- Are you watching the logs `$ adb logcat *:S TSLocationManager:V`?
- Have you seen http://dontkillmyapp.com ?

**Comment by dirjud** [comment]
Found the problem. The S7 was in "Mid" power savings mode. The http://dontkillmyapp.com gave the clues. Thanks for the clue.
