### ISSUE TITLE
Release 0.3.4 missing from change log

### ISSUE THREAD

**Issue by artob** [transistorsoft/flutter_background_geolocation#28]
## Your Environment
N/A

## Expected Behavior
[`CHANGELOG.md`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md) should document changes in release 0.3.4.

## Actual Behavior
`CHANGELOG.md` does include release 0.3.3, but not 0.3.4.

## Steps to Reproduce
N/A

## Context
Trying to determine what changes I need to make in my apps to upgrade to release 0.3.4.

## Debug logs
N/A

**Comment by christocracy** [comment]
It's done.  It was mostly documentation.

**Comment by christocracy** [comment]
I rarely make breaking changes to the Dart API.  Most changes occur deep within the native library itself.

New config options or events will often be *added*, as in `0.3.4` with added `persistMode` (which most people won't use).

**Comment by artob** [comment]
Thanks :+1:
