### ISSUE TITLE
bg.BackgroundGeolocation.registerHeadlessTask not called when in background

### ISSUE THREAD

**Issue by shikha1992** [transistorsoft/flutter_background_geolocation#280]
When in background headless event is fired once for event named TERMINATE. After this bg.BackgroundGeolocation.registerHeadlessTask method does not perform functions that i have added in method. However bloop sounds keeps on playing(meaning location is fetched) but headless event is not fired.

## Your Environment
* Plugin version:1.3.2
* Platform: iOS or Android ANdroid
* OS version: 8.0
* Device manufacturer / model: huwaei
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
inside **main.dart** >>
```dart
void main() async{
  WidgetsFlutterBinding.ensureInitialized();

  bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0.0,
      stopOnTerminate: false,
    foregroundService: true,
    forceReloadOnLocationChange: true,
   pausesLocationUpdatesAutomatically: false,
    startOnBoot: true,
   showsBackgroundLocationIndicator: false,
      debug: true,
   enableHeadless: true,
   stopOnStationary: false,
    locationUpdateInterval: 1,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE
  )).then((bg.State state) {
    if (!state.enabled) {
      bg.BackgroundGeolocation.start();
    }
  });

TransistorAuth.registerErrorHandler();
  /// Register BackgroundFetch headless-task.
  bg.BackgroundGeolocation.registerHeadlessTask(backgroundGeolocationHeadlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

```dart
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');
  var vv = headlessEvent.name;
  print('📬 --> $vv');
  PrefsSingleton.prefs = await SharedPreferences.getInstance();

  switch(headlessEvent.name) {
    case bg.Event.TERMINATE:
      break;
  
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
    
//if user logged in then only update data in firebase
      if (PrefsSingleton.prefs.getString(PreferenceNames.token)  != null) {
        if(location.activity.type.toLowerCase() != 'still'){
_updateDataBase(location, PrefsSingleton.prefs);
        }
      }
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;

    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      bg.BackgroundGeolocation.setConfig(bg.Config(
          url: "${ENV.TRACKER_HOST}/api/locations"
      ));
      break;
  }
}
```
```dart
void backgroundFetchHeadlessTask(String taskId) async {
  // Here i am doing nothing for now
  BackgroundFetch.finish(taskId);
}
```

There is **another class**, when app is opened, function called there to add data in firebase, if there is change in activity happens when app is opened and it works fine - 
```dart
bg.BackgroundGeolocation.onLocation((bg.Location location) {
//method to add data when app is opened
}
```

## Expected Behavior
when app is in background headless task should work for case  case bg.Event.LOCATION: if there is change in activity or location

## Actual Behavior
this method is not getting called after terminate event however location fetching works fine

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
when in background - 
D/TSLocationManager: [c.t.l.service.TrackingService a] 
    ╔═════════════════════════════════════════════
    ║ TrackingService: LocationResult
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 31******,76****** hAcc=1100 et=+1d1h15m12s76ms vel=0.53144336 bear=212.90088 vAcc=??? sAcc=??? bAcc=???], age: 83ms, time: 1590511240327
2020-05-26 22:10:40.416 18484-18484/com.greenplayapp I/TSLocationManager: [c.t.l.service.TrackingService a] 
      ℹ️  Distance from stoppedAtLocation: -1142.2443
2020-05-26 22:10:40.420 18484-19117/com.greenplayapp D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
    ╔═════════════════════════════════════════════
    ║ Process LocationResult
    ╠═════════════════════════════════════════════
2020-05-26 22:10:40.422 18484-19117/com.greenplayapp D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 128.402


╔═════════════════════════════════════════════
    ║ TrackingService: LocationResult
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 31******,76****** hAcc=32 et=+1d1h15m17s620ms vel=1.4420019 bear=83.7655 vAcc=??? sAcc=??? bAcc=???], age: 122ms, time: 1590511245872
2020-05-26 22:10:45.996 18484-18484/com.greenplayapp I/TSLocationManager: [c.t.l.service.TrackingService a] 
      ℹ️  Distance from stoppedAtLocation: -43.775703
2020-05-26 22:10:45.998 18484-19808/com.greenplayapp D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
    ╔═════════════════════════════════════════════
    ║ Process LocationResult
    ╠═════════════════════════════════════════════
2020-05-26 22:10:45.999 18484-19808/com.greenplayapp D/TSLocationManager: [c.t.l.l.TSLocationManager locationIsInvalid] Distance from last location: 47.443737, apparent speed: 8.5576725
```

However this should also returned (returned when app is opened or at terminate case of app)
```
[location] - [Location {odometer: 73.69999694824219, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 0.26, is_charging: true}, uuid: 3d20da1c-b6c6-430d-b9f0-88d484ff288c, coords: {altitude: -1.0, heading: -1.0, latitude: 30.898517, accuracy: 600.0, speed: -1.0, longitude: 75.9200125}, is_moving: false, timestamp: 2020-05-26T16:20:01.118Z}]
</details>
```

**Comment by christocracy** [comment]
Please edit your issue and properly syntax-highlight your code.  You wrap code in *triple backticks*.
![](https://dl.dropbox.com/s/wtxzx53912toyyb/Screenshot%202020-05-26%2012.57.43.png?dl=1)

**Comment by shikha1992** [comment]
@christocracy updated

**Comment by christocracy** [comment]
FYI, you can add optional `language` after the first 3 backticks (eg: `dart`)

**Comment by shikha1992** [comment]
> FYI, you can add optional `language` after the first 3 backticks (eg: `dart`)

Okay, thanks for information.

**Comment by christocracy** [comment]
And fix your code.  You have multiple options on the same line.
![](https://dl.dropbox.com/s/82obcsdn44h3kog/Screenshot%202020-05-26%2013.05.39.png?dl=1)

**Comment by shikha1992** [comment]
> And fix your code. You have multiple options on the same line.
> ![](https://camo.githubusercontent.com/d9b041400f4c038665a9b897f45f22ce6e4c784f/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f38326f626373646e343468336b6f672f53637265656e73686f74253230323032302d30352d323625323031332e30352e33392e706e673f646c3d31)

Fixed that one

**Comment by christocracy** [comment]
This does not run in Android headless state:
```
bg.BackgroundGeolocation.onLocation((bg.Location location) {
//method to add data when app is opened
}
```

All events arrive in `backgroundGeolocationHeadlessTask` in the headless state.

**Comment by shikha1992** [comment]
> This does not run in Android headless state:
> 
> ```
> bg.BackgroundGeolocation.onLocation((bg.Location location) {
> //method to add data when app is opened
> }
> ```
> 
> All events arrive in `backgroundGeolocationHeadlessTask` in the headless state.

Yes this method is added at init, when app is opened. headless is added in main.dart(registered) and is not working

**Comment by christocracy** [comment]
Have you tried this on a **non-Huawei** device?  Huawei are the **worst** devices on earth for background-services.  See http://dontkillmyapp.com

**Comment by shikha1992** [comment]
I will check this in one plus. That's the only other device I have right now. 
But in huawei, it fires notification as well on location update with bloop sound at background also. Only thing that does not works is headless event method is not triggered inside my app. This can be related with device hardware only? I am afraid if I have not implemented anything wrong in main.dart

**Comment by shikha1992** [comment]
I do get these results in log whenever there is change in activity. 
`TSLocationManager: [c.t.l.service.TrackingService a] 
    ╔═════════════════════════════════════════════
    ║ TrackingService: LocationResult
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 31******,76****** hAcc=1100 et=+1d2h32m25s432ms vel=0.51429784 bear=206.61984 vAcc=??? sAcc=??? bAcc=???], age: 629ms, time: 1590515873683
2020-05-26 23:27:54.318 24558-24734/com.greenplayapp D/TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
    ╔═════════════════════════════════════════════
    ║ Process LocationResult
    ╠═════════════════════════════════════════════
2020-05-26 23:27:54.319 24558-24558/com.greenplayapp I/TSLocationManager: [c.t.l.service.TrackingService a] 
      ℹ️  Distance from stoppedAtLocation: -1231.3093`

**Comment by christocracy** [comment]
There’s nothing unusual about those logs.

Are you testing with locked locations?  Go outside for a 1km walk then fetch the logs with emailLog method.

**Comment by shikha1992** [comment]
No I am testing for shorter walks. Logs above are fine, but  ` bg.BackgroundGeolocation.registerHeadlessTask(backgroundGeolocationHeadlessTask);`
method registered here is not called. 
But I will check with longer walks. How to get **emailLogs**?

**Comment by christocracy** [comment]
See wiki *Debugging*”

**Comment by shikha1992** [comment]
Also if I set `debug : false` (as I do not want to hear bloop sound while testing), it will work fine right? In same manner its working now

**Comment by christocracy** [comment]
Headless does not require debug: true.

I suggest you clone this repo and build the /example app onto your device.

**Comment by christocracy** [comment]
And get rid of these.  They’re no longer supported:

foregroundService: true,
forceReloadOnLocationChange: true,
