### ISSUE TITLE
[Question] run ONLY in headless mode?

### ISSUE THREAD

**Issue by mpiparo** [transistorsoft/flutter_background_geolocation#281]
Is it possible for the plugin to be configured to run in ONLY a headless mode? Aside from not setting any callbacks in non-headless environment, I would like to not have any location tracking while app is running. I have experimented with toggling the start() and stop(), for example starting it within an AppLifecycleState detached trigger, however it doesn't appear to be enough time for the start() to execute. I've also tried via the background_fetch plugin, calling start() within it's own headless task callback, which does work, though I would have to wait at least 15 min for that headless callback to be called, creating a 15 min delay for this plugin to start after app shutdown. 
Any ideas would be greatly appreciated. - thanks.

**Comment by christocracy** [comment]
No.  Why would you do that?

**Comment by mpiparo** [comment]
I have a requirement for an app that only requires location based functionality in a terminated state - it's currently doing proximity searches with other users via google nearby connections, however I'm being told that the discovery mode for nearby is not available after the app is terminated - the solution being explored is to use on location change based DB queries while after the app is terminated.

**Comment by christocracy** [comment]
I suggest you configure the plugin with `useSignificantChangesOnly: true`.  See the apis docs.

If you find your app running your registered headless-task and you desire more frequent locations, check `if (state.useSignificantChangeOnly: true)`, and use `setConfig` as desired.

**Comment by mpiparo** [comment]
ah. interesting. that definitely helps. appreciate it.
