### ISSUE TITLE
Failure building with Android Gradle Plugin 4.0.0

### ISSUE THREAD

**Issue by IRIG** [transistorsoft/flutter_background_geolocation#283]
## Your Environment
* Plugin version: flutter_background_geolocation 1.8.0
* Platform: Android
* OS version: n/a
* Device manufacturer / model: n/a
* Flutter info (`flutter doctor`):

doctor --verbose
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale de)
    • Flutter version 1.17.1 
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • SM G928F         • 0515314541393733          • android-arm64 • Android 7.0 (API 24)
    • Nexus 7          • 0585e4f4                  • android-arm   • Android 6.0.1 (API 23)
    • iPhone XS • 00008020-000E719A0E42002E • ios           • iOS 13.4.1

! Doctor found issues in 1 category.
Process finished with exit code 0

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      enableHeadless: true,
      heartbeatInterval: 60 * 60, 
    )).then((bg.State state) async {

    }).catchError((error) {

    });
```

## Expected Behavior

Building Android App after
- updating to Android Studio 4
- updating to com.android.tools.build:gradle:4.0.0
- doing a flutter clean
No code changes have been done, just a rebuild.

## Actual Behavior

Build failed with the following messages:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_fetch:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /Users/xxx/Development/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.6/android/libs/tsbackgroundfetch-0.4.5.aar

## Steps to Reproduce

1. change to com.android.tools.build:gradle:4.0.0
2.
3.
4.

## Context

Rebuilding the app with new gradle plugin without doing any code changes.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by IRIG** [comment]
I was not able to provide any debug logs as it fails already during the build process.

**Comment by christocracy** [comment]
$ cd android 
$ ./gradlew clean

**Comment by IRIG** [comment]
If I do 
~~~
$ cd android
$ ./gradlew clean
~~~

then, I get the following output

~~~
Configure project :app
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
[flutter_background_geolocation] Purging debug resources in release build


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
22 actionable tasks: 1 executed, 21 up-to-date
~~~

But then if I want to run the app it is rebuild again before being transferred to the smartphone producting the same error as described above.

**Comment by IRIG** [comment]
I also tried
~~~
./gradlew clean build
~~~

But it also fails with the same message.

**Comment by christocracy** [comment]
When you upgrade Android Studio (and more importantly the gradle plugin), beyond that prescribed by a freshly generated `flutter init MyApp`, you are walking into a minefield.

Those **red warnings** on the Android Studio version update dialog didn't *scare you*?  They scare me.
![](https://dl.dropbox.com/s/eo2amdluqazbri2/Screenshot%202020-05-29%2012.10.40.png?dl=1)

**Comment by IRIG** [comment]
Well your question is a bit ... questionable.

Of course, I installed Android Studio additionally to 3.6.2 in order to be sure that I can step back.

And the problem is not Android Studio 4 because I can still build without any problems the app in Android Studio 4, if I use 

- com.android.tools.build:gradle:3.6.3 instead of com.android.tools.build:gradle:4.0.0, and
- gradle-5.6.4-all.zip instead of gradle-6.1.1-all.zip which seams to be required if I use 4.0.0

So, I can still proceed with you excellent plug-in which runs extremely well.

But sooner or later the described issue will hit others as well as soon as the latest gradle build version is used.

There is also a info [here](https://android.googlesource.com/platform/tools/base/+/7f61ff6d9d80a22322c9281da755a788fe854923) which indicates that from 3.7 on all builds will fail if they have local .aar file dependencies.

**Comment by christocracy** [comment]
I've just Updated to *Android Studio 4*.  Do not use `classpath 'com.android.tools.build:gradle:4.0.0'`.

Keep it `classpath 'com.android.tools.build:gradle:3.6.3'`.

>But sooner or later the described issue will hit others 

When Flutter supports `build-gradle:4.0.0`, so will I.  It's not the first time over the last 6 years that gradle throws a wrench into the gears.  If changes are required, they will all happen in due time.

**Comment by christocracy** [comment]
[Update] Latest version now supports `gradle:4.0.0`.  Just follow the Android *Setup Instructions*.
