### ISSUE TITLE
Upgraded to 1.8.0 and crashing

### ISSUE THREAD

**Issue by malengatiger** [transistorsoft/flutter_background_geolocation#284]
## Your Environment
* Plugin version: 1.8.0
* Platform: iOS or Android: Android
* OS version:
* Device manufacturer / model: Google Pixel
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->


```

## Expected Behavior
The app should not fail

## Actual Behavior
E/TSLocationManager(24982): [c.t.l.a.BackgroundGeolocation$s0 uncaughtException] 
E/TSLocationManager(24982):   ‼️  Uncaught Exception: No static method getNamedColorStateList(Landroid/content/res/TypedArray;Lorg/xmlpull/v1/XmlPullParser;Landroid/content/res/Resources$Theme;Ljava/lang/String;I)Landroid/content/res/ColorStateList; in class Landroidx/core/content/res/TypedArrayUtils; or its super classes (declaration of 'androidx.core.content.res.TypedArrayUtils' appears in /data/app/com.aftarobot.vehicle-2/base.apk)
E/TSLocationManager(24982): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":50,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"encrypt":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":true,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":300,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":30000,"locationsOrderDirection":"ASC","logLevel":1,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{"platform":"Android","manufacturer":"Xiaomi","framework":"flutter","uuid":"Redmi-3S-6-0-1","version":"6.0.1","model":"Redmi 3S"},"persist":true,"persistMode":2,"schedule":["1-7 1:00-23:59"],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false}
E/TSLocationManager(24982): java.lang.NoSuchMethodError: No static method getNamedColorStateList(Landroid/content/res/TypedArray;Lorg/xmlpull/v1/XmlPullParser;Landroid/content/res/Resources$Theme;Ljava/lang/String;I)Landroid/content/res/ColorStateList; in class Landroidx/core/content/res/TypedArrayUtils; or its super classes (declaration of 'androidx.core.content.res.TypedArrayUtils' appears in /data/app/com.aftarobot.vehicle-2/base.apk)
E/TSLocationManager(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
E/TSLocationManager(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
E/TSLocationManager(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal$VdcInflateDelegate.createFromXmlInner(ResourceManagerInternal.java:526)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:287)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:504)
E/TSLocationManager(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.g
E/AndroidRuntime(24982): FATAL EXCEPTION: main
E/AndroidRuntime(24982): Process: com.aftarobot.vehicle, PID: 24982
E/AndroidRuntime(24982): java.lang.NoSuchMethodError: No static method getNamedColorStateList(Landroid/content/res/TypedArray;Lorg/xmlpull/v1/XmlPullParser;Landroid/content/res/Resources$Theme;Ljava/lang/String;I)Landroid/content/res/ColorStateList; in class Landroidx/core/content/res/TypedArrayUtils; or its super classes (declaration of 'androidx.core.content.res.TypedArrayUtils' appears in /data/app/com.aftarobot.vehicle-2/base.apk)
E/AndroidRuntime(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
E/AndroidRuntime(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
E/AndroidRuntime(24982): 	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal$VdcInflateDelegate.createFromXmlInner(ResourceManagerInternal.java:526)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:287)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:504)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
E/AndroidRuntime(24982): 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
E/AndroidRuntime(24982): 	at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:647)
E/AndroidRuntime(24982): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:623)
E/AndroidRuntime(24982): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:350)
E/AndroidRuntime(24982): 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)
E/AndroidRuntime(24982): 	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate()
E/AndroidRuntime(24982): 	at android.app.Activity.performCreate(Activity.java:6357)
E/AndroidRuntime(24982): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
E/AndroidRuntime(24982): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
E/AndroidRuntime(24982): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
E/AndroidRuntime(24982): 	at android.app.ActivityThread.access$1000(ActivityThread.java:154)
E/AndroidRuntime(24982): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
E/AndroidRuntime(24982): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24982): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(24982): 	at android.app.ActivityThread.main(ActivityThread.java:5571)
E/AndroidRuntime(24982): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24982): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
E/AndroidRuntime(24982): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

## Steps to Reproduce

1. Upgrade pubspec to 1.8.0
2.Build and run app
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
This isn’t specifically caused by the plugin.

Clean your build and try again.  Check your android gradle dependencies.

**Comment by malengatiger** [comment]
**Clean your build and try again. Check your android gradle dependencies.**
How do I do this?

**Comment by malengatiger** [comment]
Solved. added following lines in project level build.gradle
maven {
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }

**Comment by christocracy** [comment]
You can easily syntax highlight code by wrapping in triple-backticks.
