### ISSUE TITLE
BackgroundTaskManager warning

### ISSUE THREAD

**Issue by HeikoMueller** [transistorsoft/flutter_background_geolocation#285]
Around 40 seconds after starting the app on iOS, I see the following warning : 

2020-06-01 14:25:01.774811+0200 Runner[2094:1151207] [TSBackgroundFetch load]: (
2020-06-01 14:25:04.832650+0200 Runner[2094:1151207] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2020-06-01 14:25:39.980852+0200 Runner[2094:1151207] [BackgroundTask] Background Task 2 ("Called by Runner, from -[BackgroundTaskManager createBackgroundTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

I assume that this background task is coming from flutter_background_geolocation. Not sure how to interpret this indication. Is this warning expected behavior and can it be ignored safely or do I need to adjust the code ? 

Environment
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (4 weeks ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.
flutter_background_geolocation: ^1.7.3 (same in 1.8.0)
iOS 13.4.1

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)
• No issues found!

* Plugin config:

bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: false,
      stopOnStationary: false,
      enableHeadless: true,
      persistMode: bg.Config.PERSIST_MODE_LOCATION,
      preventSuspend: true,
      locationAuthorizationRequest: "Always",
      stationaryRadius: 25,
      isMoving: true,
      heartbeatInterval: 20,
      foregroundService: true,
      notification: bg.Notification(
        title: 'Location Tracking',
        text: 'Started',
      ),
    ));

**Comment by sikandernoori** [comment]
Hello @HeikoMueller 
Were you able to solve this ?
