### ISSUE TITLE
Problems after upgrading to 1.8.0

### ISSUE THREAD

**Issue by malengatiger** [transistorsoft/flutter_background_geolocation#286]
## Your Environment
* Plugin version: 1.8.0
* Platform: iOS or Android: Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

A clean build
## Actual Behavior

Launching lib/main.dart on Pixel 2 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_fetch:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /Users/aubs/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.6/android/libs/tsbackgroundfetch-0.4.5.aar
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by malengatiger** [comment]
I have tried everything and all my apps that use this plugin are broken. We are on deadline and have no idea how to fix this. PLEASE help!

**Comment by christocracy** [comment]
Don’t use gradle v4 yet.

**Comment by malengatiger** [comment]
While I appreciate the fact that you have responded, the response is vague to the point of being almost useless. It  would help if you said what to change in what file.  We bought licenses for the plugin and our expectation is that there would some level of quality in the support. So far we are disappointed.

**Comment by christocracy** [comment]
Whenever you upgrade Android Studio, you can assume you’re walking into a mine-field, and config can changed beyond that prescribed by a freshly generated Flutter app.

In your app’s root build.gradle, set [this line as shown](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/build.gradle#L16)

**Comment by christocracy** [comment]
Duplicate #283
