### ISSUE TITLE
onProviderChange not triggered after hot reload

### ISSUE THREAD

**Issue by HugoHeneault** [transistorsoft/flutter_background_geolocation#287]
## Your Environment
* Plugin version: 1.8.0
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: iPhone SE (simulator) 
* Flutter info (`flutter doctor`): 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

* Plugin config:
```dart
    try {
      bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
        // Logging & Debug
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopTimeout: 1,
        stopOnTerminate: true,
        heartbeatInterval: 60,
        isMoving: true,
        disableStopDetection: true,
        preventSuspend: true,
        pausesLocationUpdatesAutomatically: false,
        //Android notification
        notification: bg.Notification(
            title: 'title',
            text: 'geolocation_notification_text',
            smallIcon: 'drawable/ic_marker'),
      ));

      print('[ready] ${state.toMap()}');
      state = await bg.BackgroundGeolocation.start();
      unawaited(bg.BackgroundGeolocation.changePace(true));
      return true;
    } catch (error) {
      print(error);
      return false;
    }
```

## Expected Behavior
`onProviderChange` callback should be called even *after* app hot restart.

## Actual Behavior
`onProviderChange` callback is called on `.ready` first call, never after (unless we change provider ofc)

## Steps to Reproduce
1. Start the app and add a breakpoint to your `onLocation` callback
2. Call `bg.BackgroundGeolocation.ready()`
3. The callback is triggered
4. Hot restart the app 
5. Call `bg.BackgroundGeolocation.ready()`
6. The callback is not triggered

## Context
It would be nice for DX to have the callback called on after `.ready()` call even after app reload.

**Comment by christocracy** [comment]
Won’t happen.

**Comment by HugoHeneault** [comment]
Hello @christocracy

I would expect a bit more explanation as a paying customer. Everything is working pretty nicely and as this is making the dev experience pretty bad (I have to completely disable GPS availability detection on iOS because of that) I'd hope you could offer us a solution.
