### ISSUE TITLE
Duplicate call _onLocation

### ISSUE THREAD

**Issue by Jack74r** [transistorsoft/flutter_background_geolocation#29]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config
 cloud_firestore: 0.8.2+1
 flutter_background_geolocation: ^0.2.4
## Steps to Reproduce

```
void _onLocation(bg.Location location) {
    LatLng ll = new LatLng(location.coords.latitude, location.coords.longitude);
    _mapController.move(ll, _mapController.zoom);
    if (location.sample) {
      return;
    }

    print("ADD LOCATION firestore");
    instance.collection('locations').document().setData({
      'userUID': _firebaseUser.uid,
      'location': location.toMap(),
    });

    // Add a point to the tracking polyline.
    _polyline.add(ll);
    // Add a marker for the recorded location.
    _locations.add(_buildLocationMarker(location));
  }
```

## Context

Every location change methode onLocation  is called but add duplicate data .

**Comment by christocracy** [comment]
I see you're detecting and ignoring *samples* with `location.sample`.  

What is your proof that you're seeing *duplicates*?
