### ISSUE TITLE
[Question] Best way to get current position

### ISSUE THREAD

**Issue by upmauro** [transistorsoft/flutter_background_geolocation#290]
I need to see current position of devices running a app using your libary, but, just when the user request. For reduce battery consume I have some ideias.

**1 -** In your opnion it's a good ideia check with "pooling" on rest API if the user requested the position and if true send de currentPosition? You worked in another project with the same situation?

**2 -** If I choose the option above, I need start and stop the service or can I call just getCurrentPosition and after that call sync?

**Comment by christocracy** [comment]
Polling is a bad idea.  Http requests consume far more energy/second than gps.

getCurrentPosition will always record a location, regardless if enabled or not.  It will not automatically upload a location to configured url when disabled, you have to provide persist: true in options to do that.

**Comment by marcosvcr84** [comment]
@christocracy about using getCurrentPosition,  when the user has no network connection, the location will be captured and persisted on SQLite (with persist: true) and, as soon as there is a network connection, will it be sent to the configured url automatically?

**Comment by christocracy** [comment]
Why don’t you try it and see, while observing the plugin logs?
