### ISSUE TITLE
can't post data to localhost url?

### ISSUE THREAD

**Issue by fehernyul** [transistorsoft/flutter_background_geolocation#291]
## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: 27
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.Config _config = bg.Config(
      // Logging & Debug
      reset: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      // Geolocation options
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      elasticityMultiplier: 1.0,
      distanceFilter: 10.0,
      stopTimeout: 1,
      // HTTP & Persistence
      autoSync: true,
      // Application options
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
      url: 'http://127.0.0.1:8088/acedat/vehicledriver/sendgps-v1',
    );

    await bg.BackgroundGeolocation.ready(_config);

```

## Expected Behavior
Send data to endpoint.

## Actual Behavior
If I post data to this url ('http://127.0.0.1:8088/acedat/vehicledriver/sendgps-v1') with Postman, everything is OK. I get HTTP 200 - OK, and stored data in database. So the endpoint is working.
But this plugin says: "**Failed to connect to /127.0.0.1:8088**"

Any other url is OK, but 'localhost' or '127.0.01' is failed. 
Why?

## Steps to Reproduce

1. Run java or other backend service in localhost and set the local url to the plugin.
2. or 
3. go tho your Example app and replace this line in ENV.dart file: 
static const TRACKER_HOST = 'http://tracker.transistorsoft.com';
wit this
static const TRACKER_HOST = 'http://127.0.0.1:8088';
4.

## Context
I change url from "localhost" to "127.0.0.1", but the problem is alive.
I change url from "localhost" to "172.43.54.55", and the problem has gone.
(but I have to run the backend service in localhost!)

## Debug logs

I/TSLocationManager( 9375): [c.t.l.http.HttpService flush]
I/TSLocationManager( 9375): ╔═════════════════════════════════════════════
I/TSLocationManager( 9375): ║ HTTP Service (count: 55)
I/TSLocationManager( 9375): ╠═════════════════════════════════════════════
I/TSLocationManager( 9375): [c.t.l.u.BackgroundTaskManager onStartJob] ⏳ startBackgroundTask: 4
D/TSLocationManager( 9375): [c.t.l.data.sqlite.b first]
D/TSLocationManager( 9375):   ✅  Locked 1 records
I/TSLocationManager( 9375): [c.t.l.http.HttpService a]
I/TSLocationManager( 9375):   🔵  HTTP POST: 420649fc-f250-42df-bc30-adb710d0c2ea
W/TSLocationManager( 9375): [c.t.l.http.HttpService$i onFailure]
W/TSLocationManager( 9375):   ⚠️  Response: 0, Failed to connect to **/127.0.0.1:8088**
D/TSLocationManager( 9375): [c.t.l.data.sqlite.b unlock]
D/TSLocationManager( 9375):   ✅  UNLOCKED: 420649fc-f250-42df-bc30-adb710d0c2ea
I/TSLocationManager( 9375): [c.t.l.u.BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 4
D/TSLocationManager( 9375): [c.t.l.s.BackgroundTaskService onDestroy]
D/TSLocationManager( 9375): [c.t.l.service.HeartbeatService onDestroy] onDestroy
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

```

</details>

![imgPostman](https://user-images.githubusercontent.com/25593792/83816171-11c1c800-a6c2-11ea-953e-4a8caedb50c8.JPG)
![imgVSCode](https://user-images.githubusercontent.com/25593792/83816180-14bcb880-a6c2-11ea-9283-22031e0c061e.JPG)

**Comment by christocracy** [comment]
127.0.0.1 would reference the **device itself**.  Is your web server running on your device?  I don’t think so.  Not unless that’s an Android emulator you’re running the app on.
