### ISSUE TITLE
Persistent notification blinks on android after calling setOdometer during onLocation, CPU use increases

### ISSUE THREAD

**Issue by HugoHeneault** [transistorsoft/flutter_background_geolocation#292]
Hi Chris! 👋 

## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Galaxy S7 Edge
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```
* Plugin config:
```dart 
// Logging & Debug
        reset: true,
        debug: false,
        locationAuthorizationRequest: "Always",
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': tr('gps_disabled_title'),
          'titleWhenOff': tr('gps_requires_always_title'),
          'instructions': tr('gps_requires_always_description'),
          'cancelButton': tr('cancel'),
          'settingsButton': tr('gps_disabled_settings')
        },
        logLevel: bg.Config.LOG_LEVEL_INFO,
        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        locationUpdateInterval: Platform.isAndroid ? 1500 : null,
        fastestLocationUpdateInterval: 1000,
        distanceFilter: Platform.isAndroid ? 0 : 2,
        stopTimeout: 1,
        stopOnTerminate: true,
        heartbeatInterval: 60,
        desiredOdometerAccuracy: 10,
        isMoving: true,
        disableStopDetection: true,
        preventSuspend: true,
        pausesLocationUpdatesAutomatically: false,
        //Android notification
        notification: bg.Notification(
            title: hike is Hike
                ? hike.contents.get('title')
                : tr('geolocation_notification_title'),
            text: tr('geolocation_notification_text'),
            smallIcon: 'drawable/ic_marker'),
      )
```

## Expected Behavior
Notification should show permanently

## Actual Behavior
Notification is always blinking

## Steps to Reproduce
1. Start the background geolocation
2. Call `setOdometer`
3. Notification icon starts to blinks
4. CPU usage increases

## Context
We are running calculation on every onLocation update and sometimes calling setOdometer. Without calling it them everything runs smoothly, but as soon as we do, the app slows down, the notification starts to blink and onLocation are triggered with a delay and when we `stop()` the notification remains for awhile and `onLocation` are still triggered until all previous locations not yet handled are handled.

## Debug logs

https://gist.github.com/HugoHeneault/ed3d9891c954afabf322172063d2ab4f

</details>

I hope you can help us go through this issue :-)

Kind regards

**Comment by HugoHeneault** [comment]
So this definitively looks like a recursive loop. `setOdometer` triggers a new `onLocation` which call a new `setOdometer` which call a `onLocation`.

Why is setOdometer sending a new location?

**Comment by christocracy** [comment]
setOdometer is basically the same as getCurrentPosition.  Yes, it requests the current location.

Knowing *exactly where* the device was when odometer is set is *crucial* to odometer calculation.

**Comment by HugoHeneault** [comment]
So we managed to only trigger setOdometer on first zone entering. Is it be possible to know what caused the onLocation event (so we could ignore location event from setOdometer)?

**Comment by christocracy** [comment]
See the api docs for setOdometer.  It should accept the same options as getCurrentPosition, including `extras`.  Ie: `extras: {setOdometer: true}`

**Comment by HugoHeneault** [comment]
Perfect. Thanks 👌
