### ISSUE TITLE
[Question] It is possible to remove extra parameter from request packet

### ISSUE THREAD

**Issue by TheAlphamerc** [transistorsoft/flutter_background_geolocation#293]
Geolocation request data contain some information which is of no use for me. Is it possible to remove some information from the request. In my plugin config I have added `autosync` to true and `maxBatchSize` to 100. If some unused information will remove from request then size of request will be reduced.

#### The info that I want to remove from the request is :-
* "battery"
* "is_moving"
* "odometer"
* "speed"
* "floor"
* "accuracy"
* "altitude_accuracy"
* "altitude"

#### Sample request data
```json
{
  "location": [
    {
      "event": "motionchange",
      "is_moving": false,
      "uuid": "14b1fb11-bf18-46cf-af27-8022898c3433",
      "timestamp": "2020-06-09T05:41:39.741Z",
      "odometer": 0,
      "coords": {
        "latitude": 50.6734806,
        "longitude": 46.849573,
        "accuracy": 11190.2,
        "speed": 0,
        "heading": 90,
        "altitude": 274.9
      },
      "activity": {
        "type": "still",
        "confidence": 100
      },
      "battery": {
        "is_charging": true,
        "level": 0.39
      },
      "extras": {}
    }
  ],
}
```

**Comment by christocracy** [comment]
See `Config.locationTemplate`.
