### ISSUE TITLE
Permission popup string localisation

### ISSUE THREAD

**Issue by TheAlphamerc** [transistorsoft/flutter_background_geolocation#294]
How to set localization string for this permission popup?
For other permission pop-ups, I have added localization string from Xcode and they are working 

![image (2)](https://user-images.githubusercontent.com/37103237/84113708-b5a3ce80-aa48-11ea-978a-e96c04898107.png)

**Comment by HugoHeneault** [comment]
Hey @TheAlphamerc 

Have you checked https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/locationAuthorizationAlert.html ?

PS: your issue should respect the given issue template if you want to get some support ;)

**Comment by christocracy** [comment]
Thanks @HugoHeneault.  He's right:  do **not** ignore the issue template.

The popup you see here is produced by the SDK, not the OS.
