### ISSUE TITLE
Mock Locations not detected

### ISSUE THREAD

**Issue by ubitechdevelopers** [transistorsoft/flutter_background_geolocation#298]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What makes you think mock locations aren’t detected?  They certainly are.

See api docs Location.mock.
