### ISSUE TITLE
UnsupportedOperationException when adding some plugins to the project

### ISSUE THREAD

**Issue by abaziz** [transistorsoft/flutter_background_geolocation#300]
We have been running the plugin for about five months without any issues. We have recently noted a crash on some devices while the Android app is in the background. The issue is only reproduced with other plugins installed, however, the call stack includes the line
`com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.run (HeadlessTask.java:88)`

## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S9
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 3.5)
[√] VS Code (version 1.46.0)
[√] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
desiredAccuracy: bg.Config.DESIRED_ACCURACY_LOW,
            activityRecognitionInterval: 10000,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            locationAuthorizationRequest: "Always",
            distanceFilter: 10,
            stopOnTerminate: false,
            startOnBoot: true,
            reset: false,
            stopTimeout: 2,
            autoSync: false,
            preventSuspend: true,
```

## Expected Behavior
The background tracking on Android should continue to run without any issues.

## Actual Behavior
The following crash is reported:
Fatal Exception: java.lang.UnsupportedOperationException
The new embedding does not support the old FlutterView.
io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view (ShimRegistrar.java:82)
io.flutter.plugins.webviewflutter.WebViewFlutterPlugin.registerWith (WebViewFlutterPlugin.java:49)
io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:62)
app.thecapture.tracker.Application.registerWith (Application.kt:41)
com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.startBackgroundIsolate (HeadlessTask.java:186)
com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.dispatch (HeadlessTask.java:94)
com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.run (HeadlessTask.java:88)

## Steps to Reproduce
1. Add and use either of the following plugins in your package: WebViewFlutterPlugin/flutter_html/webview_flutter/camera
2. Run the app with background tracking using the headless task

## Context
We use our app to sample GPS data while a user is on the move.

## Debug logs
Shared exception details above.

**Comment by christocracy** [comment]
With latest flutter sdk, there is no need of a custom Application.kt.  Paste that file here.

**Comment by abaziz** [comment]
Thanks for the quick response. Please find contents of Application.kt from our project below:

package app.thecapture.tracker

import android.annotation.SuppressLint
import android.annotation.TargetApi
import android.os.Build
import android.os.StrictMode
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin
import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin
import io.flutter.plugins.GeneratedPluginRegistrant


class Application : FlutterApplication() , PluginRegistry.PluginRegistrantCallback {

    @SuppressLint("NewApi")
    @TargetApi(Build.VERSION_CODES.GINGERBREAD)
    override fun onCreate() {
        StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectAll()
                .penaltyLog()
                .build())

        StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build())

        super.onCreate()

        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this)
        BackgroundFetchPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(p0: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(p0)
    }
}

**Comment by christocracy** [comment]
Show me your AndroidManifest.xml with any api keys redacted.

**Comment by abaziz** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="app.thecapture.tracker">

    
    <uses-sdk android:minSdkVersion="26"/>
    <application
        tools:replace="android:label"
        android:name=".Application"
        android:label="@string/app_name"
        android:icon="@mipmap/launcher_icon">
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="general"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/notification_icon" />

        
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="HIDDEN" />

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
         <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="<@string/facebook_app_id>"/>
            
             <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/fb_app_name" />
             <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
            </activity>
            <provider tools:replace="android:authorities" 
            android:authorities="@string/authorities"
            android:name="com.facebook.FacebookContentProvider"
            android:exported="true"/>
 
    </application>
</manifest>

**Comment by christocracy** [comment]
First-of-all, I want you to [upgrade your Flutter app to SDK `>= 1.12`](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).  When you do so, you'll see a new element automatically added to your `AndroidManifest`:
```xml
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

After upgrading, you will [no longer require a custom `Application.kt`](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode#flutter--112) to integrate the plugin's *headless-mode*.

You will then modify your `AndroidManifest.xml` to use the default `io.flutter.app.FlutterApplication` and *delete* your `Application.kt`

```diff
<application
+        android:name="io.flutter.app.FlutterApplication
```

**Comment by abaziz** [comment]
Thanks for your prompt assistance, the issue has been resolved following your recommendation.
