### ISSUE TITLE
[Question] Detecting contact points of users.

### ISSUE THREAD

**Issue by qzaeem** [transistorsoft/flutter_background_geolocation#305]
I'm trying to make an app which detects the positions on the map where users come into contact with each other. Keeping in mind that the plugin's code stops running when the device is stationary, what is the best way to achieve the aforementioned functionality using this plugin? Also, how will I create geofences for each user - stationary as well as moving?

**Comment by christocracy** [comment]
You would need a server to collect locations from all users.  With each location that comes into your server *from* the plugin, your server code would evaluate against the last-known location of each *other* user.  If your server code finds a user "in-contact" with another, your server might send a push-notification to the affected users.  None of this involves the plugin, aside from the location uploaded to your server *by* the plugin.

>Also, how will I create geofences for each user - stationary as well as moving?

See API docs `BackgroundGeolocation.addGeofence`.

**Comment by qzaeem** [comment]
Can't we use geofences in your plugin to detect the entry of the 'other' users to achieve this? For example, creating geofence around each user, and then upon the entry of other user into the geofence the app records the position as a contact point between the two. Is this doable?

**Comment by christocracy** [comment]
>Can't we use geofences in your plugin to detect the entry of the 'other' users to achieve this

No.  The geofence API operates relative *only* to the device it's operating upon.  It's your server's responsibility to determine if some particular device is in proximity of another device.

**Comment by christocracy** [comment]
And the maximum number of geofences that can be monitored simultaneously by the device is finite:
- iOS:  20
- Android:  100

This cannot possibly scale up.
