### ISSUE TITLE
Current lat long not getting after clean application 

### ISSUE THREAD

**Issue by abhihasabe** [transistorsoft/flutter_background_geolocation#310]
import 'dart:ui';
import 'package:background_fetch/background_fetch.dart';
import 'package:etls/screens/splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:etls/utils/SharedPreferences.dart';
import 'package:flutter/material.dart';
import 'package:etls/config/app_config.dart' as config;
import 'network/Constant.dart';
import 'network/apicall.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;

const EVENTS_KEY = "fetch_events";

void backgroundFetchHeadlessTask(String taskId) async {
  //Get current-position from BackgroundGeolocation in headless mode.
  bg.Location location =
      await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  print("[BackgroundFetch] HeadlessTask: $taskId ${location.coords.longitude}");
  SharedPreferences pref = await SharedPreferences.getInstance();
  SharedPreferences prefs = await SharedPreferences.getInstance();
  pref.setString(
      EVENTS_KEY,
      "${location.coords.latitude.toString()} ,HeadlessTask" +
          location.coords.longitude.toString());
  if ("${DateTime.now().hour}" == "9" ||
      "${DateTime.now().hour}" == "12" ||
      "${DateTime.now().hour}" == "15" ||
      "${DateTime.now().hour}" == "17") {}
  addAddress(
      DateTime.now(),
      "${location.coords.latitude.toString()} ," +
          location.coords.longitude.toString(),
      prefs.getString("token"));
  BackgroundFetch.finish(taskId);
}

void addAddress(DateTime date, String latlong, String token) {
  var jobCallsResponce = APICall.addCurrentAddressJsonData(
      Constant.recordAddress, latlong, date, token);
  jobCallsResponce.then((value) {
    print("getUpdateRespo $value");
  });
}

/// Receive events from BackgroundGeolocation in Headless state.
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.TERMINATE:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $headlessEvent, $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.HEARTBEAT:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      break;
  }
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
  SharedPrefUtils.init();

  /// Register BackgroundGeolocation headless-task.
  bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State {
  Position _currentPosition;

  @override
  void initState() {
    super.initState();
    SharedPrefUtils.init();

    initPlatformState();
  }

  Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                enableHeadless: true),
            _onBackgroundFetch)
        .then((int status) {
      print("Hey Pawan Background fetch is successful");
      print('[BackgroundFetch] SUCCESS: $status');
    }).catchError((e) {
      print('[BackgroundFetch] ERROR: $e');
    });
    SharedPreferences pref = await SharedPreferences.getInstance();

    print("getlatlongData ${pref.getString(EVENTS_KEY)}");
    if (!mounted) return;
  }

  void _onBackgroundFetch(String eventId) async {
    print('[BackgroundFetch] Event received ${DateTime.now().hour}}');

    final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;
    geolocator
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.best)
        .then((Position position) {
      setState(() {
        _currentPosition = position;
        if (_currentPosition != null) {
          addAddress(
              DateTime.now(),
              "${_currentPosition.latitude.toString()} ," +
                  _currentPosition.longitude.toString());
        }
      });
    }).catchError((e) {
      print(e);
    });

    if ("${DateTime.now().hour}" == "9" ||
        "${DateTime.now().hour}" == "12" ||
        "${DateTime.now().hour}" == "15" ||
        "${DateTime.now().hour}" == "17") {
      //addAddress(DateTime.now(), "");
    }

    BackgroundFetch.finish(eventId);
  }

  void addAddress(DateTime date, String latlong) {
    var jobCallsResponce = APICall.addCurrentAddressJsonData(
        Constant.recordAddress,
        latlong,
        date,
        SharedPrefUtils.getString("token"));
    jobCallsResponce.then((value) {
      print("getUpdateRespo $value");
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'eTLS',
      darkTheme: ThemeData(
        fontFamily: 'Raleway',
        primaryColor: Color(0xFF252525),
        brightness: Brightness.dark,
        scaffoldBackgroundColor: Color(0xFF2C2C2C),
        accentColor: config.Colors().mainDarkColor(1),
        hintColor: config.Colors().secondDarkColor(1),
        focusColor: config.Colors().accentDarkColor(1),
        textTheme: TextTheme(
          button: TextStyle(color: Color(0xFF252525)),
          headline: TextStyle(
              fontSize: 20.0, color: config.Colors().secondDarkColor(1)),
          display1: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          display2: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          display3: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w700,
              color: config.Colors().mainDarkColor(1)),
          display4: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w300,
              color: config.Colors().secondDarkColor(1)),
          subhead: TextStyle(
              fontSize: 15.0,
              fontWeight: FontWeight.w500,
              color: config.Colors().secondDarkColor(1)),
          title: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().mainDarkColor(1)),
          body1: TextStyle(
              fontSize: 12.0, color: config.Colors().secondDarkColor(1)),
          body2: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          caption: TextStyle(
              fontSize: 12.0, color: config.Colors().secondDarkColor(0.7)),
        ),
      ),
      theme: ThemeData(
        fontFamily: 'Raleway',
        primaryColor: Color(0xFF024d87),
        accentColor: Color(0xFF024d87),
        brightness: Brightness.light,
        focusColor: config.Colors().accentColor(1),
        hintColor: config.Colors().secondColor(1),
        textTheme: TextTheme(
          button: TextStyle(color: Theme.of(context).primaryColor),
          headline:
              TextStyle(fontSize: 20.0, color: config.Colors().secondColor(1)),
          display1: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          display2: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          display3: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w700,
              color: config.Colors().mainColor(1)),
          display4: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w300,
              color: config.Colors().secondColor(1)),
          subhead: TextStyle(
              fontSize: 15.0,
              fontWeight: FontWeight.w500,
              color: config.Colors().secondColor(1)),
          title: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().mainColor(1)),
          body1:
              TextStyle(fontSize: 12.0, color: config.Colors().secondColor(1)),
          body2: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          caption: TextStyle(
              fontSize: 12.0, color: config.Colors().secondColor(0.6)),
        ),
      ),
      home: Splash(),
    );
  }
}

> #310

**Comment by christocracy** [comment]
Please learn to use Github’s syntax highlighting. It’s very easy: simply wrap code in triple backicks.

Edit your post.

**Comment by abhihasabe** [comment]
- [ ]

**Comment by christocracy** [comment]
Also, you completely ignored the issue template.

In the future, **don’t ignore the issue template** and syntax highlight your code if you want a response.

And when closing an issue, add a note about how you solved your problem.
