### ISSUE TITLE
Android location fetch not working when App is terminated (or killing App)

### ISSUE THREAD

**Issue by abhihasabe** [transistorsoft/flutter_background_geolocation#311]
import 'dart:ui';
import 'package:background_fetch/background_fetch.dart';
import 'package:etls/screens/splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:etls/utils/SharedPreferences.dart';
import 'package:flutter/material.dart';
import 'package:etls/config/app_config.dart' as config;
import 'network/Constant.dart';
import 'network/apicall.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;

const EVENTS_KEY = "fetch_events";
SharedPreferences pref;

void backgroundFetchHeadlessTask(String taskId) async {
  //Get current-position from BackgroundGeolocation in headless mode.
  bg.Location location =
      await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  print("[BackgroundFetch] HeadlessTask: $taskId ${location.coords.longitude}");
  pref = await SharedPreferences.getInstance();
  SharedPreferences prefs = await SharedPreferences.getInstance();
  pref.setString(EVENTS_KEY, "HeadlessTask ${DateTime.now().second}");
  if ("${DateTime.now().hour}" == "9" ||
      "${DateTime.now().hour}" == "12" ||
      "${DateTime.now().hour}" == "15" ||
      "${DateTime.now().hour}" == "17") {}
  addAddress(
      DateTime.now(),
      "${location.coords.latitude.toString()} ," +
          location.coords.longitude.toString(),
      prefs.getString("token"));
  BackgroundFetch.finish(taskId);
}

void addAddress(DateTime date, String latlong, String token) {
  var jobCallsResponce = APICall.addCurrentAddressJsonData(
      Constant.recordAddress, latlong, date, token);
  jobCallsResponce.then((value) {
    print("getUpdateRespo $value");
  });
}

/// Receive events from BackgroundGeolocation in Headless state.
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.TERMINATE:
      bg.State state = headlessEvent.event;
      print('- State: $state');
      break;
    case bg.Event.HEARTBEAT:
      bg.HeartbeatEvent event = headlessEvent.event;
      print('- HeartbeatEvent: $event');
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print('- Location: $location');
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print('- Location: $location');
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print('- GeofenceEvent: $geofenceEvent');
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print('- GeofencesChangeEvent: $event');
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print('- State: $state');
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print('ActivityChangeEvent: $event');
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print('HttpEvent: $response');
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print('ProviderChangeEvent: $enabled');
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print('ConnectivityChangeEvent: $event');
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print('EnabledChangeEvent: $enabled');
      break;
  }
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
  SharedPrefUtils.init();

  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

  /// Register BackgroundGeolocation headless-task.
  bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State {
  Position _currentPosition;

  @override
  void initState() {
    super.initState();
    SharedPrefUtils.init();

    initPlatformState();
  }

  Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                enableHeadless: true),
            _onBackgroundFetch)
        .then((int status) {
      print("Hey Pawan Background fetch is successful");
      print('[BackgroundFetch] SUCCESS: $status');
    }).catchError((e) {
      print('[BackgroundFetch] ERROR: $e');
    });

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[onLocation] $location');
    });

    bg.BackgroundGeolocation.ready(bg.Config(
        enableHeadless: true, stopOnTerminate: false, startOnBoot: true));

    SharedPreferences pref = await SharedPreferences.getInstance();

    print("getlatlongData ${pref.getString(EVENTS_KEY)}");
    if (!mounted) return;
  }

  void _onBackgroundFetch(String eventId) async {
    print('[BackgroundFetch] Event received ${DateTime.now().hour}}');
    bg.Location location =
        await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
    print("[after15min] HeadlessTask:  ${location.coords.longitude}");
    pref.setString(EVENTS_KEY, "${location.coords.longitude} after15");
    final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;
    geolocator
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.best)
        .then((Position position) {
      setState(() {
        _currentPosition = position;
        if (_currentPosition != null) {
          addAddress(
              DateTime.now(),
              "${_currentPosition.latitude.toString()} ," +
                  _currentPosition.longitude.toString());
        } else {
          addAddress(
              DateTime.now(),
              "${location.coords.latitude.toString()} ," +
                  location.coords.longitude.toString());
        }
      });
    }).catchError((e) {
      print(e);
    });

    if ("${DateTime.now().hour}" == "9" ||
        "${DateTime.now().hour}" == "12" ||
        "${DateTime.now().hour}" == "15" ||
        "${DateTime.now().hour}" == "17") {
      //addAddress(DateTime.now(), "");
    }

    BackgroundFetch.finish(eventId);
  }

  void addAddress(DateTime date, String latlong) {
    var jobCallsResponce = APICall.addCurrentAddressJsonData(
        Constant.recordAddress,
        latlong,
        date,
        SharedPrefUtils.getString("token"));
    jobCallsResponce.then((value) {
      print("getUpdateRespo $value");
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'eTLS',
      darkTheme: ThemeData(
        fontFamily: 'Raleway',
        primaryColor: Color(0xFF252525),
        brightness: Brightness.dark,
        scaffoldBackgroundColor: Color(0xFF2C2C2C),
        accentColor: config.Colors().mainDarkColor(1),
        hintColor: config.Colors().secondDarkColor(1),
        focusColor: config.Colors().accentDarkColor(1),
        textTheme: TextTheme(
          button: TextStyle(color: Color(0xFF252525)),
          headline: TextStyle(
              fontSize: 20.0, color: config.Colors().secondDarkColor(1)),
          display1: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          display2: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          display3: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w700,
              color: config.Colors().mainDarkColor(1)),
          display4: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w300,
              color: config.Colors().secondDarkColor(1)),
          subhead: TextStyle(
              fontSize: 15.0,
              fontWeight: FontWeight.w500,
              color: config.Colors().secondDarkColor(1)),
          title: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().mainDarkColor(1)),
          body1: TextStyle(
              fontSize: 12.0, color: config.Colors().secondDarkColor(1)),
          body2: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondDarkColor(1)),
          caption: TextStyle(
              fontSize: 12.0, color: config.Colors().secondDarkColor(0.7)),
        ),
      ),
      theme: ThemeData(
        fontFamily: 'Raleway',
        primaryColor: Color(0xFF024d87),
        accentColor: Color(0xFF024d87),
        brightness: Brightness.light,
        focusColor: config.Colors().accentColor(1),
        hintColor: config.Colors().secondColor(1),
        textTheme: TextTheme(
          button: TextStyle(color: Theme.of(context).primaryColor),
          headline:
              TextStyle(fontSize: 20.0, color: config.Colors().secondColor(1)),
          display1: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          display2: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          display3: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w700,
              color: config.Colors().mainColor(1)),
          display4: TextStyle(
              fontSize: 22.0,
              fontWeight: FontWeight.w300,
              color: config.Colors().secondColor(1)),
          subhead: TextStyle(
              fontSize: 15.0,
              fontWeight: FontWeight.w500,
              color: config.Colors().secondColor(1)),
          title: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().mainColor(1)),
          body1:
              TextStyle(fontSize: 12.0, color: config.Colors().secondColor(1)),
          body2: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w600,
              color: config.Colors().secondColor(1)),
          caption: TextStyle(
              fontSize: 12.0, color: config.Colors().secondColor(0.6)),
        ),
      ),
      home: Splash(),
    );
  }
}

**Comment by christocracy** [comment]
Please learn to use Github’s syntax highlighting.  It’s very easy:  simply wrap code in triple backicks.

**Comment by abhihasabe** [comment]
location fetch not working when App is terminated or killing App

[main.dart.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/4827214/main.dart.txt)

**Comment by christocracy** [comment]
- Ignored issue template
- Learn to syntax highlight your code:
![](https://dl.dropbox.com/s/upj8ltnemoa3gy0/Screenshot%202020-06-24%2014.26.05.png?dl=1)
![](https://dl.dropbox.com/s/mmgwaogxzks7y16/Screenshot%202020-06-24%2014.26.43.png?dl=1)
![](https://dl.dropbox.com/s/x92vyf5ylprp8ca/Screenshot%202020-06-24%2014.28.00.png?dl=1)

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************
-->


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Instead of opening **another** issue #314 , you could have just **EDITED THIS ONE**.
