### ISSUE TITLE
[Question] Is changePace() the best way to deal with Play / Pause aproach?

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#315]
Hello,

I'm not sure what will be the best aproach to implement a feature that i need:

- Track a route (with polylines), be able to Pause the tracking and then Start track again registering the coordinate on the Pause and start from it when press Play.

The current aproach involves use the changePace() method (checking for movement), but i'm still getting "noise coordinates" after pause. It would be better STOP the component that START again?

Thanks.

**Comment by christocracy** [comment]
>but i'm still getting "noise coordinates"

If you're talking specifically about Android, See `Config.motionTriggerDelay`.

> It would be better STOP the component that START again?

Possibly.  Try it and see.
