### ISSUE TITLE
Unit for speed

### ISSUE THREAD

**Issue by shikha1992** [transistorsoft/flutter_background_geolocation#316]
## Your Environment
* Plugin version:1.9.0
* Platform: iOS or Android: both
* OS version:
* Device manufacturer / model:.
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Location location.coords.speed
```

## Expected Behavior
What are the units returned for speed here? is it km/hr or km/minute? 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Neither, it's *meters / second*.
