### ISSUE TITLE
bg.BackgroundGeolocation.ready configured on hot reload

### ISSUE THREAD

**Issue by kareldebedts** [transistorsoft/flutter_background_geolocation#317]
## Your Environment
* Plugin version: 1.7.1
* Platform: iOS
* OS version: 13.4
* Device manufacturer / model: Apple iPhone 11 Pro max
* Flutter info (`flutter doctor`): normal
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
      notification: bg.Notification(
          title: "myTitle", text: "Subtitle"),
      locationAuthorizationRequest: "Always",
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      stopOnTerminate: false,
      startOnBoot: false,
      url: 'https://myURL,
      debug: false,
      params: {"user_id": user.uid, "key": secretKey},
      headers: {"Authorization": "Basic my-secret-key"},
      extras: {"route_id": 8675309},
      autoSync: true,
      elasticityMultiplier: 5,
      foregroundService: true,
      stopAfterElapsedMinutes: 480,
      logLevel: bg.Config.LOG_LEVEL_ERROR,
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

// CONFIG

    bg.BackgroundGeolocation.setConfig(bg.Config(
      notification: bg.Notification(
          title: "myTitle", text: "Subtitle"),
      locationAuthorizationRequest: "Always",
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      stopOnTerminate: false,
      startOnBoot: false,
      url: 'https://myURL,
      debug: false,
      params: {"user_id": user.uid, "key": secretKey},
      headers: {"Authorization": "Basic my-secret-key"},
      extras: {"route_id": 8675309},
      autoSync: true,
      elasticityMultiplier: 5,
      foregroundService: true,
      stopAfterElapsedMinutes: selectedMinutes,
      logLevel: bg.Config.LOG_LEVEL_ERROR,
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });


```

## Expected Behavior

I've red in the documentation that bg.BackgroundGeolocation.ready only gets called on the first opening ever of the app.(So only once until the user deletes the app?).
So if a user wants to start tracking, I call setConfig (with the custom settings of the user), and assign a new secretKey. I would expect that the plugin remembers that secret key even if the user restarts the app.

## Actual Behavior
When I hot restart the app in flutter, the secret key & settings of the bg.BackgroundGeolocation.ready gets assigned (even if the location is currently being tracked). My goal is that the secret key & settings of my previous setConfig are remembered even if the user restarts the app.

## Steps to Reproduce

1. 
2.
3.
4.

## Context

Configuring the plugin with custom settings (that the user defines).

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
No relevant logs, the plugin keeps working & tracking
```

</details>

**Comment by christocracy** [comment]
> bg.BackgroundGeolocation.ready only gets called on the first opening ever

No, you must call `ready` each time the app boots.

If you don’t want `ready` to reset it’s persisted Config each time, provide `reset: false`.  The plugin will then ignore the supplied Config after every subsequent launch.  You will need to `setConfig` to change Config thereafter.

**Comment by kareldebedts** [comment]
Thanks, I rebuild my app with reset: false.

It keeps changing my secretKey.

For example:
In my function with bg.BackgroundGeolocation.ready, I assign the key "abcd". (Which I call on every launch of the app)

When I call the function to start tracking with bg.BackgroundGeolocation.setConfig, I assign the key "1234". (Which my database verifies). 

Everything works, my database receives the "1234" key, but when I hot restart the database receives the "abcd" key.

**Comment by kareldebedts** [comment]
I tried removing the params from the bg.BackgroundGeolocation.ready.

    bg.BackgroundGeolocation.ready(bg.Config(
      notification: bg.Notification(
          title: "myTitle", text: "Subtitle"),
      locationAuthorizationRequest: "Always",
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      stopOnTerminate: false,
      startOnBoot: false,
      url: 'https://myURL,
      debug: false,
     //params: {"user_id": user.uid, "key": secretKey},      //REMOVED
      headers: {"Authorization": "Basic my-secret-key"},
      extras: {"route_id": 8675309},
      autoSync: true,
      elasticityMultiplier: 5,
      foregroundService: true,
      stopAfterElapsedMinutes: 480,
      logLevel: bg.Config.LOG_LEVEL_ERROR,
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });


Now the secretKey works as it should be. But the question remains if this has an impact on other settings, because if I config stopAfterElapsedMinutes, it's necessary that it stops just that time. Or should I also remove the stopAfterElapsedMinutes in the bg.BackgroundGeolocation.ready ?
