### ISSUE TITLE
background trigger stops after after app is in background for more than 20 hours and not in  use

### ISSUE THREAD

**Issue by shikha1992** [transistorsoft/flutter_background_geolocation#318]
## Your Environment
* Plugin version: 1.9.0
* Platform: iOS or Android: Android
* OS version:
* Device manufacturer / model:Xiomi Redmi note 4
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((_){
    runApp(StoreProvider(
        store: store, child: Application(store))
    );
  }
  );

bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
//    pausesLocationUpdatesAutomatically: false,
      startOnBoot: true,
    allowIdenticalLocations: true,
//    showsBackgroundLocationIndicator: false,
      notificationTitle: "Greenplay",
      notificationText: "Fetching location",
      debug: false,
      enableHeadless: true,
    foregroundService: true,
//      locationUpdateInterval: 300,
      forceReloadOnMotionChange: true ,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      fastestLocationUpdateInterval: 1,
      isMoving: true,
//    disableElasticity: true,
  )).then((bg.State state) {
    if (!state.enabled) {
      if (PrefsSingleton.prefs.getString(PreferenceNames.token)  != null) {
        bg.BackgroundGeolocation.start();
        bg.BackgroundGeolocation.changePace(true);
      }else{
//        bg.BackgroundGeolocation.stop();
      }
    }
  });
bg.BackgroundGeolocation.registerHeadlessTask(
        backgroundGeolocationHeadlessTask);

 bg.BackgroundGeolocation.onLocation((bg.Location location) {
    print('[location] - $location');
   //add to server
  });

void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');
  var vv = headlessEvent.name;
  print('📬 --> $vv');
  PrefsSingleton.prefs = await SharedPreferences.getInstance();

  switch(headlessEvent.name) {
    case bg.Event.TERMINATE:
      try {
        //bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $headlessEvent');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.HEARTBEAT:
    /* DISABLED getCurrentPosition on heartbeat
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      */
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      //update at server
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
     //update at server
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      bg.ActivityChangeEvent location = headlessEvent.event;
      print("act_change: $location");
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      bg.BackgroundGeolocation.setConfig(bg.Config(
          url: "${ENV.TRACKER_HOST}/api/locations"
      ));
      break;
  }
}



```

## Expected Behavior
Should trigger when in movement even if app is not opened for days

## Actual Behavior
Notification appears but activity is not triggered

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I’ve got my 11 test devices running the /example app for sometimes *months* at a time without issue.

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 10
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

See http://dontkillmyapp.com

**Comment by christocracy** [comment]
Btw, the following config options are no longer used by the SDK:
```
foregroundService: true,  // This is essentially always true now.
forceReloadOnMotionChange: true // All forceReloadOnXXX are no longer used
```

**Comment by shikha1992** [comment]
While debug I did not add service in android manifest. Can this be a cause?

``
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.greenplayapp">
    
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

    <application
        android:name=".Application"
        android:label="Greenplay"
       tools:replace="android:label"
        android:icon="@mipmap/greenplay">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <service android:name="dk.cachet.activity_recognition_flutter.activity.ActivityRecognizedService" />

    </application>
</manifest>
``

**Comment by christocracy** [comment]
Are you using `locationAuthorizationRequest: ‘WhenInUse’`?  No you’re not.

**Comment by shikha1992** [comment]
> Are you using `locationAuthorizationRequest: ‘WhenInUse’`? No you’re not.

No I am not using it. I must have missed. Can you let me know where it has to be added.

**Comment by christocracy** [comment]
It’s in the *Android Setup* linked in the README.

**Comment by shikha1992** [comment]
> It’s in the _Android Setup_ linked in the README.

https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md
I checked it here. DO not find it

**Comment by christocracy** [comment]
Why are you looking at the background_fetch README for Setup related the background_geolocation, which is *this* repo you’ve posted an issue at?

**Comment by shikha1992** [comment]
> Why are you looking at the background_fetch README for Setup related the background_geolocation, which is _this_ repo you’ve posted an issue at?

checked it here as well 
https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md
Do not find location where to add locationAuthorizationRequest:true

**Comment by christocracy** [comment]
See api docs Config.locationAuthorizationRequest (default “Always”).

**Comment by shikha1992** [comment]
changing to 'whenInUse' is not making any difference

**Comment by christocracy** [comment]
I didn’t tell you to change to `WhenInUse`.

**Comment by christocracy** [comment]
You said:

> While debug I did not add service in android manifest. Can this be a cause?

Those extra entries **are only required when** using `WhenInUse`.

**Comment by shikha1992** [comment]
`  buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            shrinkResources false
            minifyEnabled true
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }`

When set to release mode, app is crashing when trying to relaunch it from background activity(recent applications) which seems to be issue related with progauard

**Comment by christocracy** [comment]
Multi-line syntax-highlighting requires **3 backticks**.  *One* backtick is for inline highlighting, `like this` and `this` and `this`.  Read [this](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

```
When
you
have 
multiple
lines,
you use 
THREE
backticks.
```

**Comment by christocracy** [comment]
>When set to release mode, app is crashing

When your app crashes, the first thing you do, *before* posting an issue, is fetch the *stacktrace* from `$ adb logcat`.  There is always a stacktrace when an app crashes, which tells you *what crashed and where*.

**Comment by MobilyteApps** [comment]
`java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to f.b.c.a.g$d`

I am getting above error. Shall I disable proguard that has to be added for your library. WHat if i add proguard default as below?
`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`
instead of 
`proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"`
 Will your library work okay with realease version.

**Comment by shikha1992** [comment]
java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to f.b.c.a.g$d

I am getting above error. Shall I disable proguard that has to be added for your library. WHat if i add proguard default as below?
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
instead of
proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
Will your library work okay with realease version.

**Comment by christocracy** [comment]
First-of-all, if you're using `minifyEnabled true`, you **must** include the SDK's `proguard-rules.pro`, as directed in the Android Setup.

Secondly, gradle accepts *multiple* `proguardFiles` declarations.

```
release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources false
            getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
            proguardFiles "foo-rules.pro"
            proguardFiles "bar-rules.pro"
        }
```

**Comment by shikha1992** [comment]
`buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            shrinkResources false
            minifyEnabled true
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
            signingConfig signingConfigs.release
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt')
        }
    }`

That's my snippet of code in gradle

**Comment by christocracy** [comment]
Have you tried [googling your error](https://github.com/flutter/flutter/issues/47635)?

**Comment by shikha1992** [comment]
> Have you tried [googling your error](https://github.com/flutter/flutter/issues/47635)?

Yes they're suggesting it related to proguard error, so I realised I only added proguard from transistor library. 
I will be checking by adding default as well

**Comment by shikha1992** [comment]
In android sessions are getting recorded at background for code above(dart). but in IOS value not triggering, what can be possible issue. below is my info.plist content. Am I missing something here?

`<dict>
	<key>BACKGROUND_GEOLOCATION_ENCRYPTION_PASSWORD</key>
	<string>transistorsoft</string>
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>com.transistorsoft.fetch</string>
	</array>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>GreenPlay</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.336786091897-aubrenep3tmcskfdjbglhnebnjg9g09p</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>Greenplay would like to access your music</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Greenplay would like to access your calender</string>
	<key>NSContactsUsageDescription</key>
	<string>Greenplay would like to access your device contacts</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Greenplay wants to know your location to know how much distance you have covered for 	challenge</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Greenplay wants to know your location to know how much distance you have covered for challenge</string>
	<key>NSMotionUsageDescription</key>
	<string>Greenplay wants to detect your motion to calculate your session</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Greenplay would like to access your gallery</string>
	<key>NSCameraUsageDescription</key>
    <string>Greenplay would like to access your camera</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>Greenplay would like to access your microphone</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Greenplay would like to access your device speech recognition</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>`

**Comment by shikha1992** [comment]
@christocracy Can you please help? I have to upload app at store. In android release is working okay but now IOS is having issue. Please assist asap.

**Comment by christocracy** [comment]
>background trigger stops after after app is in background for more than 20 hours and not in use

This issue was reported as related to *Android*.  If you're now having an *iOS* problem, post a new issue.

If your original Android issue is solved, please *close* this issue.
