### ISSUE TITLE
[Question] How to get around the 200 meter stationary geofence restriction on iOS?

### ISSUE THREAD

**Issue by qzaeem** [transistorsoft/flutter_background_geolocation#319]
My app needs to constantly track user's location. 200 meters is a large area to cover before the app resumes recording user's location. The 'prevent suspend mode' is a nice workaround, but the plugin's documentation says that it should not be enabled indefinitely. Is there a way to check that the user has moved more than 20 meters, for example, when in stationary state (basically an alternative method for reducing the default 200 meters requirement)? Or is there another way I can achieve this? I'm making a Covid tracker.

**Comment by christocracy** [comment]
Not possible.  iOS is strict.  If it were possible, it would have been done by now.  I’ve been doing this for over 6 years.

Location-tracking is not the way to do Covid-tracking.  Apple/Google’s new Bluetooth API is the way to do Covid-tracking.
