### ISSUE TITLE
Should the schedule stop the plugin if it is outside scheduled time

### ISSUE THREAD

**Issue by nattyg93** [transistorsoft/flutter_background_geolocation#32]
## Your Environment
* Plugin version: 0.3.4
* Platform: Android
* OS version: 9 (Pie)
* Device manufacturer / model: Nokie 6.1
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)
* Plugin config
``` Dart
bg.Config(
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 1.0,
  stopOnTerminate: false,
  startOnBoot: true,
  foregroundService: true,
  debug: false,
  logLevel: bg.Config.LOG_LEVEL_DEBUG,
  url: '<URLHERE>',
  autoSync: true,
  params: <String, dynamic>{'AUTHSTUFF': 'AUTHKEY'},
  schedule: ['2019-03-05-10:25 2019-03-05-10:30'],
  autoSyncThreshold: 50,
  batchSync: true,
  maxBatchSize: 50,
  maxDaysToPersist: 30,
  reset: true,
);
```

## Expected Behavior
I'm actually looking for clarification on what the expected behaviour is in this case.
The docs have:
``` Dart
  /// // Later when you want to stop the Scheduler (eg: user logout)
  /// BackgroundGeolocation.stopSchedule();
  /// // You must explicitly stop tracking if currently enabled
  /// BackgroundGeolocation.stop()
```
Does this apply to changing the schedule also?

## Steps to Reproduce

1. Start the plugin in using `bg.BackgroundGeolocation.startSchedule();` with the config above at 2019-03-05-10:28.
2. The plugin starts automatically because it is within the scheduled time (which is perfect).
3. Call `bg.BackgroundGelocation.startSchedule();` again, but this time configure it with the schedule `['2019-03-05-10:20 2019-03-05-10:25']` (i.e. a schedule that has finished in the past).
4. The foreground service will continue to run and does not terminate automatically.

Essentially I'm doing this:

``` Dart
Future<void> example() async {
  // at 2019-03-05-10:25
  bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1.0,
    stopOnTerminate: false,
    startOnBoot: true,
    foregroundService: true,
    debug: false,
    logLevel: bg.Config.LOG_LEVEL_DEBUG,
    url: '<URLHERE>',
    autoSync: true,
    params: <String, dynamic>{'AUTHSTUFF': 'AUTHKEY'},
    schedule: ['2019-03-05-10:20 2019-03-05-10:30'],
    autoSyncThreshold: 50,
    batchSync: true,
    maxBatchSize: 50,
    maxDaysToPersist: 30,
    reset: true,
  ));
  if (state.schedule.isNotEmpty) {
    await bg.BackgroundGeolocation.startSchedule();
    // The schedule starts and the foreground service starts
  }
  await Future<void>.delayed(Duration(minutes: 2), () {});

  // at 2019-03-05-10:27
  state = await bg.BackgroundGeolocation.ready(bg.Config(
    // Same config as above
    // Schedule finishes in the past
    schedule: ['2019-03-05-10:20 2019-03-05-10:25'],
    // Same config as above
    reset: true,
  ));
  if (state.schedule.isNotEmpty) {
    await bg.BackgroundGeolocation.startSchedule();
    // The schedule starts and the foreground service starts
  }
  // The foreground service remains active
}
```

So my question is, should the foreground service remain active at the end, or should it stop?

If I stop the plugin first then, run `startSchedule()` then I achieve the behaviour I'm wanting.

``` Dart
  state = await bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1.0,
    stopOnTerminate: false,
    startOnBoot: true,
    foregroundService: true,
    debug: false,
    logLevel: bg.Config.LOG_LEVEL_DEBUG,
    url: '<URLHERE>',
    autoSync: true,
    params: <String, dynamic>{'AUTHSTUFF': 'AUTHKEY'},
    // Schedule finishes in the past
    schedule: ['2019-03-05-10:20 2019-03-05-10:25'],
    autoSyncThreshold: 50,
    batchSync: true,
    maxBatchSize: 50,
    maxDaysToPersist: 30,
    reset: true,
  ));
  if (state.schedule.isNotEmpty) {
    if (state.enabled) {
      bg.BackgroundGeolocation.stop();
    }
    await bg.BackgroundGeolocation.startSchedule();
    // The schedule starts and the foreground stops
  }
```

## Debug logs
I have not included logs as I am not claiming that there is an issue or bug. I'm just trying to get some clarification on the expected behaviour.

PS happy holidays - this is by no means a blocker and is pretty low priority. Thanks for your help in advance.

**Comment by christocracy** [comment]
The logs are actually pretty clear about this situation. 

If you #startSchedule and the schedule says the plugin *should* be currently disabled, the plugin will be disabled to respect the current schedule.  After calling #startSchedule, if you choose to #start the plugin, the plugin won’t get in your way.

**Comment by christocracy** [comment]
Btw, start using 1.0.0-beta.  The foreground service is no longer active while device is stationary.

**Comment by nattyg93** [comment]
@christocracy Perhaps I haven't communicated my question well. I understand the behaviour around #startSchedule and #start. In my example, at no point have I called #start. Am I to understand that if the plugin starts due to the schedule, this is equivalent to calling #start?

Excellent to hear about the improvements while the device is stationary. Is 1.0.0-beta production ready?

**Comment by christocracy** [comment]
#startSchedule is essentially a robot that automatically executes #start / #stop according to your configured #schedule.

You need not manually execute #start / #stop with #startSchedule.

**Comment by christocracy** [comment]
You should not yet consider 1.0.0-beta to be production ready.  It needs a couple more weeks of field-testing.
