### ISSUE TITLE
Coordinates making the polylines go through buildings.

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#320]
## Your Environment
* Plugin version: 1.9.9
* Platform: Android
* OS version: 10
* Device manufacturer / model: Xiaomi Mi 9T
* Flutter info (`flutter doctor`): 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.46.1)
[√] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      locationUpdateInterval: 2,
      desiredOdometerAccuracy: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      // dev only
      reset: true,
      //motionTriggerDelay: 3000,
    )
```

## Expected Behavior
The coordinates should correspond to my exact position so the polylines could be drawn correctly.

## Actual Behavior
When I walk close to buildings, sometime the coordinates put me like if i've passed through the building.

## Context
Draw the polylines correspondent to my actual position. Sometimes it is drawn "on top" of buildings, sometimes on the street even i'm in the sidewalk.

If I use some "fake GPS" app, like GPS Joystick (that alows me control my movement through a map) the positioning is perfect, but when i apply it to the "real deal", that kind of stuff happens.

## Debug logs
Below folows an screenshot of what I reported above. The green "dot" is the start of the path that goes ok until get close to buildings. Whete the yellow path starts is the right path that should have been recorded but it kept following the rest of the red line, make the line pass trhough the buildings.

[Map screenshot](https://drive.google.com/file/d/14DlFuWqFxqrBN3UeeAmlACNF90rUP74c/view?usp=sharing)

**Comment by christocracy** [comment]
>If I use some "fake GPS" app, like GPS Joystick (that alows me control my movement through a map) the positioning is perfect

That's not surprising.

>but when i apply it to the "real deal", that kind of stuff happens.

Welcome to the *real* world.  That's not surprising, either.  You'll get a variety of results depending on the particular Android device you use along with the network environment it's operating in (eg: barriers such as tall buildings, mountains, tunnels, bridges).

Btw, your Map screenshot is not public.

**Comment by leonardoayres** [comment]
@christocracy the map screenshot is now public (thank you for point it out).

**Comment by christocracy** [comment]
You'll never get 100% perfect results all the time in every environment on every particular device model.

The plugin does not manufacture location information, it's merely the messenger providing location data exactly as given by the device's location API.  It's impossible to verify the validity of location data in real time.  Poor results only becomes apparent by a human observing the data on a map.

The only control affecting location accuracy is `desiredAccuracy` and you've configured it for the best possible accuracy `DESIRED_ACCURACY_HIGH`.  You should be testing on a variety of devices in a variety of environments.

You should *expect* periodic poor results in the *real* world.
