### ISSUE TITLE
[Question] Check whether the user has given permissions to start tracking? 

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#321]
Does this plugin offer any api to show whether the user has granted/denied the permissions required to start location tracking?

What I would like to do is make some visual indicators / buttons if the user has denied the permissions necessary to track. Currently I am using flutter permissions handler to do this, but it has a bug which incorrectly shows "location always" granted when "location when in use" is all that is granted.

**Comment by christocracy** [comment]
See API docs event `#onProviderChange`

**Comment by MilesAdamson** [comment]
Thank you. Does the permission status of sensors matter for tracking?

**Comment by christocracy** [comment]
>Does the permission status of sensors matter

What sensors?

**Comment by MilesAdamson** [comment]
I thought that it also required permission for accelerometer, gyroscope and magnetometer. On iOS I think this is all grouped under motion and fitness, Android physical activity.

Would there be any issues if the user for some reason has location always granted, but motion and fitness denied?

![image](https://user-images.githubusercontent.com/29047682/86039870-552cff00-ba00-11ea-97f9-f2cfdb5e3f05.png)

**Comment by christocracy** [comment]
- On iOS is not a big deal.
- Android will experience delayed tracking, just like iOS, where the device will need to move *at least* 200 meters or more before tracking engages.

**Comment by MilesAdamson** [comment]
If I were to get a location with `getCurrentPosition` without sensor permissions, would they still need to move 200m, or would it simply take a location the next time it can?

**Comment by christocracy** [comment]
Yes, they’ll still need to move 200 meters.

**Comment by MilesAdamson** [comment]
Sorry that this issue has digressed away from the original topic but on that note, my use case is a worker who has a device mounted on a vehicles dashboard. They work outside so the device doesn't move for long stretches (hours).

We are having issues where our readings say "location last updated 6h ago". They are still in that spot and haven't moved, however dispatchers would like to see the timestamps updated more often. For peace of mind that they are still there and haven't done something like shut the device off and move somewhere else.

Currently planning on solving this through the heartbeat, and using getCurrentLocation every 2 minutes. If they must move 200m, is sounds like this wouldn't actually work? Would they still need to move significantly if motion and fitness was turned on?

**Comment by christocracy** [comment]
I suggest you implement [react-native-backgorund-fetch](https://github.com/transistorsoft/react-native-background-fetch) for periodic updates, which is already included as a dependency.

**Comment by MilesAdamson** [comment]
Regardless of how the update is scheduled, if the user must move 200m, it sounds like a location will not be recorded and sent of the device has been still for hours on end. Is this correct, and does the status of motion and fitness effect this at all?

**Comment by christocracy** [comment]
>and does the permission status of motion and fitness effect this at all?

For Android, yes.  iOS: no.  iOS strictly engages tracking **only** when the devices moves at least 200 meters, period.

>Would this option help in this case?

No

>Just to be clear - it's perfectly fine in our case to send the exact same location again, I just want it to send periodically even if they aren't moving

Read the Wiki *Philosophy of Operation*.  When the device is stationary, the plugin is silent and conserving energy.  It's not in the plugin's mandate to "periodically update position".

Use `react-native-background-fetch` for periodic updates by calling `BackgroundGeolocation.getCurrentPosition()` in the `background-fetch` callback.  Read the README for `background-fetch`.
