### ISSUE TITLE
getCurrentPosition requires device to move before recording/sending a location

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#324]
## Your Environment
* Plugin version: 1.7.3
* Platform: iOS + Android
* Device manufacturer / model: any
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return gps.Config(
        extras: await buildExtrasMap(),
        url: 'https://$subDomain.ironsight.ca/api/v2/units/$unitId/location',
        authorization: buildAuthorization(accessToken, refreshToken, subDomain),
        desiredAccuracy: gps.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,
        allowIdenticalLocations: false,
        stopOnTerminate: false,
        disableStopDetection: true,
        startOnBoot: true,
        pausesLocationUpdatesAutomatically: false,
        maxDaysToPersist: 1,
        maxRecordsToPersist: 3,
        batchSync: true,
        stationaryRadius: 25.0,
        debug: false,
        useSignificantChangesOnly: false,
        autoSync: true,
        logLevel: gps.Config.LOG_LEVEL_ERROR,
        reset: true);
  }
```

## Expected Behavior

When I call `getCurrentPosition`, the current location is read and sent to the server, without needing the device to move. It is not mentioned in the documentation nor source code that the device will need to move for this method to record a location.

## Steps to Reproduce

1. Start tracking
2. Schedule background fetch to call `getCurrentPosition` at some interval, in our case every 5 minutes
3. Place device completely still somewhere and leave it. I did this overnight on the table
4. Check logs/server and see most recent GPS update is hours old, even though the background fetch is scheduled and being fired

## Actual Behavior

My device did not send an update every time that `getCurrentPosition` was called.

## Context

Ensure gps "update at" timestamps for dispatchers are up to date. Currently getting issues saying that they are upwards of 6h old, and only start updating again once the unit leaves the site. Recent updates are required for our uses even if the location is the same, to ensure vehicles are still where dispatchers think they are.

</details>

**Comment by christocracy** [comment]
>getCurrentPosition requires device to move before recording/sending a location

This is not true.  `#getCurrentPosition` *always* returns a location when called.

>Schedule background fetch to call getCurrentLocation at some interval, in our case every 5 minutes

If you're having an issue with `background_fetch`, you post an issue there.  This is the **`background_geolocation`** repo.

**Comment by MilesAdamson** [comment]
> This is not true. `#getCurrentPosition` _always_ returns a location when called.

> Yes, they’ll still need to move 200 meters.

You told me yesterday that under some conditions, `getCurrentPosition` will need the device to more 200m to record. Which is it? **Always** sends a location update to the POST url, or **sometimes** requires the user to move 200m?

Experimentally, I have found that my device stopped posting location updates after after I set it down, this morning showing me GPS logs which were stale.

Overnight, I scheduled a background call to use  `getCurrentPosition` every 5 minutes. I am completely certain I did this correctly and do not need to open an issue on the other repo. `background_fetch` couldn't be easier to use, it's a very handy plugin which I already had in the app doing other things.

**Comment by christocracy** [comment]
>You told me yesterday that under some conditions getCurrentPosition will need the device to more 200m to record.

No I did not.  You misunderstood.

Please read the Wiki in this repo *Philosophy of Operation*.

If you're having issues with `background_fetch`, please post an issue *there*.

**Comment by MilesAdamson** [comment]
I'm not trying to be hostile I'm sorry if this is annoying you somehow. I'm just trying to get the users location... please explain how I misunderstood it would help me a lot

![image](https://user-images.githubusercontent.com/29047682/86151909-9e428900-babc-11ea-85ff-f668c710d9cd.png)

**Comment by christocracy** [comment]
You misunderstand the plugin's *Philosophy of Operation*.

1.  `getCurrentPosition` returns a location **no matter what**.
2.  The plugin engages automatic location-tracking when the device is detected to be moving.

**Comment by MilesAdamson** [comment]
> 1. `getCurrentPosition` returns a location **no matter what**.
Does it also send the location to the post URL no matter what?

**Comment by christocracy** [comment]
- The SDK inserts **every recorded location** into its SQLite database when `state.enabled == true`
- The SDK's HTTP Service *feeds from* the database.  When there are records in the database, the HTTP Service will post them.
