### ISSUE TITLE
App Crashing on Release Build

### ISSUE THREAD

**Issue by marcosvcr84** [transistorsoft/flutter_background_geolocation#325]
## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Samsung / Galaxy A10
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.1 19B88, locale en-BR)
    • Flutter version 1.17.5 at /Users/marcosvinicius/Development/flutter
    • Framework revision 8af6b2f038 (7 hours ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcosvinicius/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/marcosvinicius/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM A105M • RX8M80BTGED • android-arm • Android 9 (API 28)

! Doctor found issues in 2 categories.

* Plugin config:
```dart 
bg.BackgroundGeolocation.ready(bg.Config(
            reset: false,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 0,
            locationUpdateInterval: 10000,
            stopTimeout: 1,
            // HTTP & Persistence
            url: "http://api.webrota.com.br:1200",
            method: "POST",
            extras: extras,
            autoSync: true,
            batchSync: true,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60))
        .then((bg.State state) {
      print('[ready] ${state.toMap()}');
```

## Expected Behavior
App should start and show login page to user, like on debug version

## Actual Behavior
App crashes on start

## Steps to Reproduce
1. Just open the app on release mode

## Context
Open the app and login screen to input username and password

## Debug logs
<details>
	<summary>Logs</summary>

``` 
2020-06-30 23:35:10.333 14020-14020/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.webrota.ipack, PID: 14020
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.a.a(Unknown Source:0)
        at e.d.a.a.G.a(:17)
        at e.d.a.a.H.onAttachedToActivity(:1)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(:10)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:6)
        at br.com.webrota.ipack.MainActivity.configureFlutterEngine(:1)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(:10)
        at io.flutter.embedding.android.FlutterActivity.onCreate(:5)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at e.d.b.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.a.<clinit>(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.a.a(Unknown Source:0) 
        at e.d.a.a.G.a(:17) 
        at e.d.a.a.H.onAttachedToActivity(:1) 
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(:10) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:6) 
        at br.com.webrota.ipack.MainActivity.configureFlutterEngine(:1) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(:10) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(:5) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

</details>

**Comment by christocracy** [comment]
Show me your `android/build.gradle`

**Comment by christocracy** [comment]
Sorry: __`android/app/build.gradle`__

**Comment by marcosvcr84** [comment]
````javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
````

**Comment by marcosvcr84** [comment]
`
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '20'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.5.1'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    def keystoreProperties = new Properties()
    def keystorePropertiesFile = rootProject.file('key.properties')
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "br.com.webrota.ipack"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    /*
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
    */
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    //androidTestImplementation 'com.android.support.test:runner:1.0.2'
    //androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.core:core:1.0.1'
}
`

**Comment by marcosvcr84** [comment]
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '20'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.5.1'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    def keystoreProperties = new Properties()
    def keystorePropertiesFile = rootProject.file('key.properties')
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "br.com.webrota.ipack"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    /*
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
    */
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    //androidTestImplementation 'com.android.support.test:runner:1.0.2'
    //androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.core:core:1.0.1'
}
```

**Comment by christocracy** [comment]
Duplicate #323.  Those green lines in the [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidappbuildgradle) are *not* optional.

**Comment by christocracy** [comment]
The SDK's Android library `tslocationmanager.aar` is *already minified*.  When you `minifyEnabled true`, Gradle will minify the already-minified library.  The plugin's [`proguard-rules.pro`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/proguard-rules.pro), which you've failed to include, tells gradle to lay off the plugin's already-minified namespaces.

**Comment by christocracy** [comment]
I **strongly** recommend you follow the advice about the `ext` variables too, and take advantage of them in your own `android/app/build.gradle`
![](https://dl.dropbox.com/s/jimrsbhhjhb6j80/Screenshot%202020-06-30%2023.18.36.png?dl=1)

Look at your `androidx.appcompat:appcompat:1.0.0`:  you've hard-coded it to `1.0.0`.  What about other plugin's, such as mine, which [also import that](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L69).  And what's my default version?  [1.1.0](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L26).

You're asking for *big trouble* with build failures importing multiple version of the same dependency.

**Comment by christocracy** [comment]
Read [this](https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties) and [this](https://medium.com/@ivan_m/use-variables-to-manage-gradle-android-dependencies-library-version-numbers-92f0e362a2fc) and [this](https://proandroiddev.com/configure-gradle-in-different-files-ecbf69bd5b56)

**Comment by christocracy** [comment]
If you open your `/android` folder in *Android Studio*, it's smart.  The IDE will notify you when there's a newer version of dependencies:

*android/build.gradle*
![](https://www.dropbox.com/s/dxkg37efx4uo8jf/Screenshot%202020-06-30%2023.33.37.png?dl=1)
*android/app/build.gradle*
![](https://dl.dropbox.com/s/dxkg37efx4uo8jf/Screenshot%202020-06-30%2023.33.37.png?dl=1)

```diff
buildscript {
    ext {
        kotlin_version     = '1.3.72'
        compileSdkVersion   = 29
        targetSdkVersion    = 29
+        appCompatVersion    = "1.1.0"  // <----- bump to 1.1.0
        playServicesLocationVersion = "17.0.0"
        removeBackgroundGeolocationDebugSoundsInRelease = false
    }
}
```

**Comment by marcosvcr84** [comment]
Ok, thank you very much.

**Comment by christocracy** [comment]
I helped popularize this strategy a few years ago in the React Native community.  Look at any popular plugin's `build.gradle` and you'll see the same thing with this [`safeExtGet`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L31-L33) method to [fetch dependency version's](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L54-L58) from your `ext` variables which *you* control, just like *this* plugin.
- [`react-native-maps` (11.2k stars)](https://github.com/react-native-community/react-native-maps/blob/master/lib/android/build.gradle#L20-L22)
- [`react-native-device-info` (4.8k stars)](https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L18-L20)
- [`react-native-push-notification` (4.9k stars)](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L20-L22)
- [`react-native-camera` (8.5k stars)](https://github.com/react-native-community/react-native-camera/blob/master/android/build.gradle#L1-L3)

The folks at Flutter haven't yet caught onto this strategy.  hard-coded dependencies everywhere.  
- [`flutter_camera`](https://github.com/flutter/plugins/blob/master/packages/camera/android/build.gradle#L38-L41)
- [`android_alarm_manager`](https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/build.gradle#L40-L41)
- [`google_maps_flutter`](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/android/build.gradle#L36)

I've been supporting my plugins for >5 years through *Cordova*, *React Native* and most recently, *Flutter*.  Gradle dependency conflicts **were a nightmare** and the number one source of support requests until developers -- and especially *plugin authors* -- began using the `ext` vars.
