### ISSUE TITLE
 Could not find any matches for com.transistorsoft:tslocationmanager:+

### ISSUE THREAD

**Issue by ptv1p3r** [transistorsoft/flutter_background_geolocation#328]
## Your Environment
* Plugin version:1.9.1
* Platform: Android
* OS version: w10
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
compile

## Actual Behavior
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Required by:
         project :app > project :flutter_background_geolocation

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#190---2020-06-15)

See [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidbuildgradle)

**Comment by ptv1p3r** [comment]
@christocracy didn't realise changes were needed, just followed the setup guide and it's all working again, ty

**Comment by christocracy** [comment]
With everyone suddenly upgrading to gradle-tools `v5`, the setup required an extra step.
