### ISSUE TITLE
Help needed - manual location upload w/ offline cache

### ISSUE THREAD

**Issue by draganjovanovic1** [transistorsoft/flutter_background_geolocation#329]
Hello,

Since built-in authorization features of the lib does not work for me I can't use built-in sync feature but instead I am subscribed to `onLocation` / `onMotionChange` / `onHeartBeat` events to manually post location data to my HTTP endpoint. This works fine. However, I need a way to reliably post all locations to server once app in online after it was moving in the offline state. 

Can you please point me in the right direction how to implement this and not reinvent the wheel. Thanks in advance.

## Your Environment
* Plugin version: 1.9.1
* Platform: iOS and Android
* OS version:
* Device manufacturer / model: 
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
```
* Plugin config:
```dart
    await bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 5.0,
        locationUpdateInterval: 15 * 1000,
        maxRecordsToPersist: 50,
        disableElasticity: false,
        enableHeadless: true,
        foregroundService: true,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true,
        autoSync: false,
        maxDaysToPersist: 5,
        allowIdenticalLocations: false,
        heartbeatInterval: 30,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification:
            bg.Notification(smallIcon: 'drawable/ic_stat_notification_icon')));
```

**Comment by christocracy** [comment]
>Since built-in authorization features of the lib does not work for me

Why not?  You're free to use your own authorization scheme by configuring `Config.headers` as desired and *still* use the SDK's built-in HTTP service.  The HTTP service doesn't require `Config.authorization`.

>I need a way to reliably post all locations to server once app in online

- Listen to `onConnectivityChange`.  
- Retrieve queued records from plugin's `SQLite` database with:

```dart
List<dynamic> locations = await BackgroundGeolocation.locations
```

For Android, you will of course have to implement that all in your Headless-task as well.

You are recording only the most recent 50 locations recorded while device is offline:
```
maxRecordsToPersist: 50,
```

**Comment by draganjovanovic1** [comment]
Thanks Chris. I am using Firebase auth, my JWT token is expiring so I have to asynchronously retrieve it once in a while via Firebase SDK. Actually I wired up everything via events and config reloads when token is changed but wasn't happy with the solution, beside that I also had to map request to match the server (I know this is possible with the lib), so I reverted to manual HTTP upload as it made my code simpler.

Will `BackgroundGeolocation.locations` give me only non-uploaded locations? How the lib is aware of the queued locations in case of manual upload? Do I have to throw exception in the callback? Thanks.

**Comment by christocracy** [comment]
>my JWT token is expiring so I have to asynchronously retrieve it once in a while

This is precisely why I added the new [Authorization](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Authorization-class.html) feature, for *automatically* refreshing expired tokens.

>Will BackgroundGeolocation.locations give me only non-uploaded locations

Since you're not using the built-in HTTP service, the SDK has no knowledge of what you've uploaded.  You must *manually* remove from the SDK's SQLite database those location which you've uploaded.

When you know your location has been uploaded, see [BackgroundGeolocation.destroyLocation](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/destroyLocation.html)

If you want to destroy *all* locations, [BackgroundGeolocation.destroyLocations](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/destroyLocations.html)

**Comment by draganjovanovic1** [comment]
> This is precisely why I added the new Authorization feature, for automatically refreshing expired tokens.

I saw the feature but unfortunately Firebase is being used via SDK and I have no knowledge about token URLs. Maybe an abstract `getToken` async function would be good solution. This is what I saw in some libraries.

Can you please confirm my solution:
1. in my `uploadLocation` implementations I have to remove uploaded location via `destroyLocation` function
2. I have to listen to `onConnectivityChange` in both app and headlessTask and do something like this
```dart
    bg.BackgroundGeolocation.onConnectivityChange(
        (bg.ConnectivityChangeEvent event) async {
      if (event.connected) {
        var locations = await bg.BackgroundGeolocation.locations;

        // TODO: upload all locations
      }
    });
```

**Comment by christocracy** [comment]
Try it out.  put a `print` stmt there in the event-handler and enable/disable Wifi/Cellular.

**Comment by draganjovanovic1** [comment]
Sure. Just wanted to confirm the idea. Thanks for your help.
