### ISSUE TITLE
Stationary time duration

### ISSUE THREAD

**Issue by LucaGabi** [transistorsoft/flutter_background_geolocation#33]
Hi,

This is  a question / feature request: can the stationary duration be also posted to the server ?

Thanks.

**Comment by christocracy** [comment]
I don’t understand your use-case.  Give me an example.

**Comment by LucaGabi** [comment]
I want to know how much time a device was in a stationary state at a certain location (well-known location and a given radius). 

Thanks.

**Comment by christocracy** [comment]
Put a geofence around it.  Measure the enter / exit time difference.

**Comment by LucaGabi** [comment]
Thanks, can you give a small example ?

**Comment by christocracy** [comment]
See example in docs for method #addGeofence.
