### ISSUE TITLE
Android notification icon does not work in release mode

### ISSUE THREAD

**Issue by draganjovanovic1** [transistorsoft/flutter_background_geolocation#330]
## Your Environment
* Plugin version: 1.9.1
* Platform: Android
* OS version: tried on Android 8, 9 and 10
* Device manufacturer / model: several devices Huawei, Essential Phone, Samsung, LG, Xiaomi
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
```
* Plugin config:
```dart 
    await bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 5.0,
        locationUpdateInterval: 15 * 1000,
        maxRecordsToPersist: 50,
        disableElasticity: false,
        enableHeadless: true,
        foregroundService: true,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true,
        autoSync: false,
        maxDaysToPersist: 5,
        allowIdenticalLocations: false,
        heartbeatInterval: 30,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification:
            bg.Notification(smallIcon: 'drawable/ic_stat_notification_icon')));

```

## Expected Behavior
Drawable icon `ic_stat_notification_icon` should be in the notification bar in both debug and release builds.

## Actual Behavior
Drawable icon `ic_stat_notification_icon` is visible in the debug build only while the default square icon is visible in the release mode.

## Steps to Reproduce
1. Add drawable resource to the Andoid app
2. Configure notification as in the config above
3. Run the app in the debug mode, the icon will be set
4. Pack the app in the release mode, the default icon will be set instead of the custom one

## Context
I would like to set custom icon to the sticky Android notification.

## Debug logs
Nothing relevant to the notification icon found in the logs. No errors or warnings.

**Comment by christocracy** [comment]
Probably due to new D8 code-shrinking, since there's no Java or AndroidManifest.xml that references that file, D8 assumes you don't need it and removes that resource from the build.

In `android/app/build.gradle`, try this:
```gradle
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
+           shrinkResources false   
           ...
        }
    }
```

**Comment by draganjovanovic1** [comment]
Thanks. Will try and post the result back.

**Comment by draganjovanovic1** [comment]
It works. Thanks Chris.
