### ISSUE TITLE
The app close when starting (release with license)

### ISSUE THREAD

**Issue by jhparisi** [transistorsoft/flutter_background_geolocation#331]
## Your Environment
* Plugin version: 1.9.1
* Platform: Android
* OS version: 29
* Device manufacturer / model: Nokia 6.1
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [VersiÃ³n 10.0.20161.1000], locale es-ES)
    • Flutter version 1.17.5 at C:\Users\humbe\Documents\flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\humbe\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\humbe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (2 available)
    • ONEPLUS A3010       • emulator-5554 • android-x86 • Android 7.1.1 (API 25)
    • AOSP on IA Emulator • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;

////
// For pretty-printing location JSON.  Not a requirement of flutter_background_geolocation
//
import 'dart:convert';
JsonEncoder encoder = new JsonEncoder.withIndent("     ");
//
////

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'BackgroundGeolocation Demo',
      theme: new ThemeData(
        primarySwatch: Colors.amber,
      ),
      home: new MyHomePage(title: 'BackgroundGeolocation Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isMoving;
  bool _enabled;
  String _motionActivity;
  String _odometer;
  String _content;

  @override
  void initState() {
    _isMoving = false;
    _enabled = false;
    _content = '';
    _motionActivity = 'UNKNOWN';
    _odometer = '0';

    // 1.  Listen to events (See docs for all 12 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    });
  }

  void _onClickEnable(enabled) {
    if (enabled) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      });
    } else {
      bg.BackgroundGeolocation.stop().then((bg.State state) {
        print('[stop] success: $state');
        // Reset odometer.
        bg.BackgroundGeolocation.setOdometer(0.0);

        setState(() {
          _odometer = '0.0';
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      });
    }
  }

  // Manually toggle the tracking state:  moving vs stationary
  void _onClickChangePace() {
    setState(() {
      _isMoving = !_isMoving;
    });
    print("[onClickChangePace] -> $_isMoving");

    bg.BackgroundGeolocation.changePace(_isMoving).then((bool isMoving) {
      print('[changePace] success $isMoving');
    }).catchError((e) {
      print('[changePace] ERROR: ' + e.code.toString());
    });
  }

  // Manually fetch the current position.
  void _onClickGetCurrentPosition() {
    bg.BackgroundGeolocation.getCurrentPosition(
        persist: false,     // <-- do not persist this location
        desiredAccuracy: 0, // <-- desire best possible accuracy
        timeout: 30000,     // <-- wait 30s before giving up.
        samples: 3          // <-- sample 3 location before selecting best.
    ).then((bg.Location location) {
      print('[getCurrentPosition] - $location');
    }).catchError((error) {
      print('[getCurrentPosition] ERROR: $error');
    });
  }

  ////
  // Event handlers
  //

  void _onLocation(bg.Location location) {
    print('[location] - $location');

    String odometerKM = (location.odometer / 1000.0).toStringAsFixed(1);

    setState(() {
      _content = encoder.convert(location.toMap());
      _odometer = odometerKM;
    });
  }

  void _onMotionChange(bg.Location location) {
    print('[motionchange] - $location');
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[activitychange] - $event');
    setState(() {
      _motionActivity = event.activity;
    });
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    print('$event');

    setState(() {
      _content = encoder.convert(event.toMap());
    });
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    print('$event');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Background Geolocation'),
        actions: <Widget>[
          Switch(
            value: _enabled,
            onChanged: _onClickEnable
          ),
        ]
      ),
      body: SingleChildScrollView(
          child: Text('$_content')
      ),
      bottomNavigationBar: BottomAppBar(
        child: Container(
          padding: const EdgeInsets.only(left: 5.0, right: 5.0),
          child: Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.gps_fixed),
                onPressed: _onClickGetCurrentPosition,
              ),
              Text('$_motionActivity · $_odometer km'),
              MaterialButton(
                minWidth: 50.0,
                child: Icon((_isMoving) ? Icons.pause : Icons.play_arrow, color: Colors.white),
                color: (_isMoving) ? Colors.red : Colors.green,
                onPressed: _onClickChangePace
              )
            ]
          )
        )
      ),
    );
  }
}
## Steps to Reproduce

1. Create the project as an example hello world
2. Follow the installation steps
3. Follow the steps to create flutter release
4. Install the app
5. Open the app (closes)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
When an app crashes, there is a stacktrace logged in logcat.

**Comment by jhparisi** [comment]
Hi, when I had installing the application from the console with the flutter install command, it works very well, but when I prove had installing the app from the release distribution it doesn't start. I need support with this fault, this is the log

I/flutter (30657): ***************** START LOG *********************
I/flutter (30657): --------- beginning of main07-08 09:57:02.400 30657 30657 E mple.eszaworke: Not starting debugger since process cannot load the jdwp agent.07-08 09:57:02.548 30657 30657 I Perf    : Connecting to perf service.07-08 09:57:02.702 30657 30681 E Perf    : Fail to get file list com.example.eszaworker07-08 09:57:02.702 30657 30681 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array07-08 09:57:02.702 30657 30681 E Perf    : Fail to get file list com.example.eszaworker07-08 09:57:02.702 30657 30681 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array07-08 09:57:02.703 30657 30681 E Perf    : Fail to get file list oat07-08 09:57:02.703 30657 30681 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array07-08 09:57:02.780 30657 30657 I AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b07-08 09:57:02.780 30657 30657 I AdrenoGLES: B
I/flutter (30657): ***************** END LOG *********************

**Comment by christocracy** [comment]
There’s nothing in the stacktrace referencing this plugin.

**Comment by jhparisi** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\humbe\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\background_fetch-0.6.0\android\local.properties'.

The plugin background_fetch could not be built due to the issue above.

**Comment by christocracy** [comment]
[background_fetch @ 0.6.0](https://github.com/transistorsoft/flutter_background_fetch/tree/0.6.0/android) doesn't have a `local.properties` file.

**Comment by christocracy** [comment]
Whenever I have an unusual Android issue, the first thing I do is:
```
$ cd android
$ ./gradlew clean
```

**Comment by christocracy** [comment]
Show me the following files:
- `android/build.gradle`
- `android/app/build.gradle`
- Please learn to [syntax-highlight your pasted code](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks), it's very easy with *triple backticks*.

**Comment by jhparisi** [comment]
I have updated the android studio (despite not using it) and the problem has been resolved.

Thank you Chris.

**Comment by christocracy** [comment]
Please close your issues when resolved.
