### ISSUE TITLE
[iOS] GeofenceEvent.EXIT not triggering

### ISSUE THREAD

**Issue by elouiestudent** [transistorsoft/flutter_background_geolocation#338]
## Your Environment
* Plugin version: 1.9.1
* Platform: iOS
* OS version: 10.15.4
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`): Normal
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
static Future<void> startBackgroundTracking() async {
bg.BackgroundGeolocation.onLocation(_locationCallback);
bg.BackgroundGeolocation.onGeofence(_geofenceCallback);
bg.BackgroundGeolocation.ready(bg.Config(
            locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Missing Location Permissions',
          'titleWhenOff': 'Missing Location Permissions',
          'instructions':
              'Go to Settings',
          'cancelButton': 'Ok',
          'settingsButton': 'Settings'
        },
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        print("backgroundGeolocationStart <");
        bg.BackgroundGeolocation.start();
      }
    });
}

static void _locationCallback(bg.Location location) async {
  // if geofence does not already exist, following code is called
  await bg.BackgroundGeolocation.addGeofence(bg.Geofence(
        identifier: id,
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
        radius: radius,
        notifyOnEntry: true,
        notifyOnDwell: true,
        notifyOnExit: true));
}

static void _geofenceCallback(bg.GeofenceEvent event) async {
  if (event.action == "EXIT") 
  // send corresponding notification
  else if (event.action == "ENTER" || event.action == "DWELL") 
  // send different notification
}
```

## Expected Behavior
Corresponding GeofenceEvents should be called upon ENTER, EXIT, and DWELL.

## Actual Behavior
Plugin's debug notifications and my notifications only show ENTER and DWELL events being fired.

## Steps to Reproduce

1.
2.
3.
4.

## Context
Sending different notifications depending on the type of GeofenceEvent.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you testing in the iOS simulator?  The iOS simulator works well for geofence testing.

**Comment by elouiestudent** [comment]
I'm using a real device.

**Comment by christocracy** [comment]
Now try in the simulator.

**Comment by elouiestudent** [comment]
It works in the simulator, but the issue still persists on the real device.

**Comment by christocracy** [comment]
It's not an "issue".  You're probably not travelling far enough outside the geofence for it to fire.

Following image shows typical distance outside of geofence before it fires.  The red markers are geofence *EXIT* events.

![](https://dl.dropbox.com/s/ztzsnoyflxmzz0m/Screenshot%202020-07-21%2015.34.55.png?dl=1)

**Comment by christocracy** [comment]
I field-test iOS geofences almost every day for the last 4 years.  They never fail.  This is my daily bike-ride yesterday:
![](https://dl.dropbox.com/s/x5dhnyhjs127j7d/Screenshot%202020-07-21%2015.36.53.png?dl=1)

**Comment by elouiestudent** [comment]
So the red triangles are when the geofence exit event actually fire? In that case you're right, I probably didn't walk far enough.

**Comment by christocracy** [comment]
- *Red Triangle*:  Location of actual event.
- *Red Circle*:  This is just a pointer to the actual geofence that fired using trigonometry.

**Comment by elouiestudent** [comment]
Thanks for the detailed response! The plugin is working great, I just needed to walk further.
