### ISSUE TITLE
Hide notification when not tracking.

### ISSUE THREAD

**Issue by kareldebedts** [transistorsoft/flutter_background_geolocation#342]
## Your Environment
* Plugin version: 1.9.2
* Platform: Android
* OS version: API 28
* Device manufacturer / model: Pixel 3 XL simulator android studio

I don't know if there are functions/methods to hide the notification, but couldn't found one in the documentation.
I tried the following:
When I stop tracking, I call this function.

```
Future<Null> configPluginForStop() async {
    await bg.BackgroundGeolocation.setConfig(
            bg.Config(useSignificantChangesOnly: true))
        .then((bg.State state) {
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }
```

This doesn't hide the notification. (To be clear: I don't mind having a notification when tracking, but when a user isn't using the tracking mechanism: no notification.).

Are there other solutions?

Thanks in advance!

**Comment by christocracy** [comment]
> but when a user isn't using the tracking mechanism: no notification.).

This *is* the behaviour of the plugin.
- When plugin is in *stationary* state (ie: `state.isMoving == false`), there is no notification.
- Only when plugin is in *moving* state (ie: `state.isMoving == true`) is there a foreground-service (and associated notification) active.

**Comment by kareldebedts** [comment]
Thanks! This is the config of my plugin. When I open my App and run this to check if the user was tracking, the notification always pop up (even if _enabled == false)

```
  Future<Null> _initPlatformState() async {
    FirebaseUser user = await FirebaseAuth.instance.currentUser();

    int taskId = await bg.BackgroundGeolocation.startBackgroundTask();

    bg.BackgroundGeolocation.ready(bg.Config(
      locationAuthorizationRequest: "Always",
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      reset: false,
      locationAuthorizationAlert: {
        'titleWhenNotEnabled': 'myText',
        'titleWhenOff': 'myText',
        'instructions':
            "instr",
        'cancelButton': 'Cancel',
        'settingsButton': 'Settings'
      },
      stopOnTerminate: false,
      startOnBoot: false,
      url: 'https://myURL',
      debug: false,
      headers: {"Authorization": "Basic my-secret-key"},
      extras: {"route_id": 8675309},
      autoSync: true,
      elasticityMultiplier: 5,
      foregroundService: true,
     stopAfterElapsedMinutes: 480,
      logLevel: bg.Config.LOG_LEVEL_ERROR,
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }
```

**Comment by christocracy** [comment]
>the notification always pop up (even if _enabled == false).

I do not have this problem with the `/example` app.  If I terminate the app with `State.enabled == false` then re-launch the app, no notification will appear.

You are likely executing `getCurrentPosition` each time your app boots.  Anytime the plugin requests a location, a foreground-service (and its corresponding notification) is launched.

**Comment by kareldebedts** [comment]
Thanks! I installed the /example app and tested it and compared it to my code.

  int taskId = await bg.BackgroundGeolocation.startBackgroundTask();

Removed this from my _initPlatformState() and behaves now the same as the /example app.

Thanks!

**Comment by christocracy** [comment]
`await bg.BackgroundGeolocation.startBackgroundTask();` starts a foreground-service.
