### ISSUE TITLE
how can i improve the location tracking in foreground and background

### ISSUE THREAD

**Issue by is10vmust** [transistorsoft/flutter_background_geolocation#343]
## Your Environment
* Plugin version: v1.8.0
* Platform: Android
* OS version:  android 10
* Device manufacturer / model: Samsung A 11

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void _configureBackgroundGeolocation() async {
    bg.BackgroundGeolocation.ready(bg.Config(
                       disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,
            triggerActivities:
                'on_foot, walking, running, in_vehicle, on_bicycle',
            useSignificantChangesOnly: false,
            allowIdenticalLocations: true,
            forceReloadOnLocationChange: true,
            preventSuspend: true,
            reset: true,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 1.0,
            locationUpdateInterval: 5000,
            stopTimeout: 1,
            autoSync: true,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60))
        .then((bg.State state) {
      if (state.schedule.isNotEmpty) {
        bg.BackgroundGeolocation.stop();
        bg.BackgroundGeolocation.startSchedule();
      }
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }
```

## Expected Behavior

i want the app to track users every 1m or every 2min give the best accurcy and send it to our api .
## Actual Behavior

the accuracy is not always give the high accrue and it not always sent it each 1m or each 2min , usually it send each 1 min or less than 1 min , also its send sometime when phone is in still (not moving).

## Code - headless
```
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print("LOCATION PLUG-IN in BACKGROUND...");
  print('[getCurrentPosition] Headless OUT:------> ${headlessEvent.name}');

  switch (headlessEvent.name) {
    case bg.Event.TERMINATE:
      print('===============------> TERMINATED!!');

      try {
        checkLocation();
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }

      break;

  }
}
```

## Code - save current location

```
Future<void> gps() async {
  try {
    bg.Location locations =
        await bg.BackgroundGeolocation.getCurrentPosition(samples: 5);
    print('[getCurrentPosition] Headless: $locations');
    print('------------------${locations.coords.latitude}');
    print('-----------------${locations.coords.longitude}');
    print('-----------------${locations.coords.accuracy}');
    print('----------------------------${locations.battery.level}');

    PreferenceUtils.setDouble('LAT', locations.coords.latitude);
    PreferenceUtils.setDouble('LONG', locations.coords.longitude);
    PreferenceUtils.setDouble('ACC', locations.coords.accuracy);
    PreferenceUtils.setString('act',locations.activity.type);

    if (PreferenceUtils.getDouble('LAT') == null) {
      PreferenceUtils.setDouble('LAT', 0.0);
    }
    if (PreferenceUtils.getDouble('LONG') == null) {
      PreferenceUtils.setDouble('LONG', 0.0);
    }
    if (PreferenceUtils.getDouble('ACC') == null) {
      PreferenceUtils.setDouble('ACC', 0.0);
    }
  } catch (e) {
    PreferenceUtils.setDouble('ACC', 0.0);
    PreferenceUtils.setDouble('LONG', 0.0);
    PreferenceUtils.setDouble('LAT', 0.0);
  }
}
```
**Thank you**

**Comment by christocracy** [comment]
Configure the plugin to [post to the demo](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/TransistorAuthorizationToken-class.html) server at http://tracker.transistorsoft.com

```dart
String orgname = "my-company-name";  // <-- CHANGEME
String usernmae = "my-username"; // <-- CHANGEME

// Fetch an authoriztion token from server.
// The SDK will cache the received token and return it if found locally.
TransistorAuthorizationToken token = await
  TransistorAuthorizationToken.findOrCreate(orgname, username);

BackgroundGeolocation.ready(Config(
  transistorAuthorizationToken: token
))
```

**Comment by is10vmust** [comment]
thank you sir , but we have our API and our data base , my question here is are there any way or an attribute i can add  to my configuration to enhance the accuracy and the timing , and how i can use the plugin to set timing i'm using TERMINATE attribute in headless function and i'm calling my own timed loop , i used HEARTBEAT but it stopped working when phone make any action are there any attribute it loop it self . thanks again

**Comment by christocracy** [comment]
> but we have our API and our data base

I’m sure you *do* but I can’t *see* that.  Apply the Config above to your app and let me know the org name you choose so *I* can see with my own eyes what you’re talking about.

**Comment by is10vmust** [comment]
hi, i config the app with the demo server setting our org and username :
orgname = "ensperity"
username = "is10vmust" 


thanks

**Comment by is10vmust** [comment]
after testing on demo server the tracks its not accurate at all , i was walked for 500m and it taked me 20min only saved 3 - 5 record instead of  20 record are there's any problem i can fix with configuration

**Comment by christocracy** [comment]
What org name did you choose?

**Comment by is10vmust** [comment]
ensperity

**Comment by christocracy** [comment]
There's nothing wrong with your config.  The problem is likely your device.

- See http://dontkillmyapp.com
- When the location authorization dialog appears, are you granting "*Always*" or "*When in Use*"?

Typical tracking looks like this:

**Pixel 3a @ 11**
![](https://dl.dropbox.com/s/c6v0fc3babnh7oh/Screenshot%202020-07-25%2010.29.35.png?dl=1)

**Xiaomi Mi-A2 Lite @ 9.0.0**
![](https://dl.dropbox.com/s/l727gf4kds0av83/Screenshot%202020-07-25%2010.30.57.png?dl=1)

**OnePlus A5010 @ 9**
![](https://dl.dropbox.com/s/cid83fmsodoz1bx/Screenshot%202020-07-25%2010.25.00.png?dl=1)

**Samsung A520 @ 8**
![](https://dl.dropbox.com/s/4xiae76lfr8jge8/Screenshot%202020-07-25%2010.27.00.png?dl=1)

**Nexus 5 @ 6.0.1**
![](https://dl.dropbox.com/s/azd1qb100mmnes8/Screenshot%202020-07-25%2010.28.08.png?dl=1)

**Comment by is10vmust** [comment]
Many thanks in advance for your test,  i picked always ,

**Comment by christocracy** [comment]
I'm testing 11 Android devices almost daily for *years*.  See http://dontkillmyapp.com and apply the recommended changes to your device settings.

**Comment by christocracy** [comment]
And check your device's data usage that it's not nearly full.

**Comment by is10vmust** [comment]
so are there any behavior that affect on accuracy when the device in still because when i leave the app running for long term it give a very wrong place e.g :
![image](https://user-images.githubusercontent.com/35732149/88482241-b9dc6a80-cf68-11ea-9853-d08e8c34bcb4.png)

**Comment by christocracy** [comment]
No.  You should expect occasional glitches like this.  You will never get perfection.
