### ISSUE TITLE
heartBeat in background failed to execute

### ISSUE THREAD

**Issue by iskifo** [transistorsoft/flutter_background_geolocation#344]
## Your Environment
* Plugin version: ^1.9.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: ONEPLUS A3003
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-ID)
    • Flutter version 1.17.4 at C:\Flutter
    • Framework revision 1ad9baa8b9 (5 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\FTD\SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\FTD\SDK
    • ANDROID_SDK_ROOT = D:\FTD\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • ONEPLUS A3003 • 4afa721b • android-arm64 • Android 9 (API 28)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      persistMode: bg.Config.PERSIST_MODE_LOCATION,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      locationUpdateInterval: 60000,
      heartbeatInterval: 60,
      stopTimeout: 1000,
      stopOnTerminate: false,
      startOnBoot: true,
      forceReloadOnBoot: true,
      debug: true,
      allowIdenticalLocations: false,
      enableHeadless: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      maxDaysToPersist: 1,
    )).then((bg.State state) async  {
      await Future.delayed(Duration(seconds: 2));
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
      });
    });
```

## Expected Behavior
onHeartBeat send getCurrentLocation when app terminated (running in backgroud)

## Actual Behavior
When app terminated it trigger heartbeat alarm, but generate error log "Uncaught Exception: io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine"

## Steps to Reproduce

1. in MainActivity.java i put this code:
`public class MainActivity extends FlutterActivity {
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
    }
}`
2. in Application.java i put the code in the step do for 'enableHeadless'
3. GeneratePluginRegistrant created
4. App running:
   a. When app opens, it triggered heartbeat.. ok
   b. When app in foreground, it triggered heartbeat.. ok
   c. When app terminated, it doesn't triggered heartbeat and log shows error above

## Context
The purpose is to send current location even when app was terminated

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Uncaught Exception: io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":0,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"encrypt":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":60,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":60000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":1,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1000,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false}
    java.lang.ClassCastException: io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine
        at id.amatech.nawexpress.Application.registerWith(Application.java:19)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:186)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.dispatch(HeadlessTask.java:94)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.run(HeadlessTask.java:88)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

</details>

**Comment by christocracy** [comment]
Read the [Android Headless Mode Setup](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode#step-1--which-flutter-sdk) carefully -- When using `Flutter >= 1.12`, there is **NO SETUP REQUIRED IN `Application.java`**

![](https://dl.dropbox.com/s/ma5bobo5kxopd5f/Screenshot%202020-07-27%2015.06.46.png?dl=1)

**Comment by iskifo** [comment]
Thank you for the reply, I did miss that step to miss that step 😆 👍
