### ISSUE TITLE
When I take the elevator the plugin consider my in the car?

### ISSUE THREAD

**Issue by suha-glal** [transistorsoft/flutter_background_geolocation#345]
When I take the elevator the plugin considers me in the car? why is that?

**Comment by christocracy** [comment]
What would you expect?

**Comment by suha-glal** [comment]
I would expect it not to recognize the context for example but sending in the car signle with 100% confidence is completely wrong.

How can this be fixed, this is a major usability issue?

**Comment by christocracy** [comment]
This plugin uses [ActivityRecognitionClient](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient) from *Google Play Services*.  This API is a black box that aggregates sensors data from *accelerometer*, *gyroscope* and *magnetometer* to output `on_foot`, `in_vehicle`, `on_bicycle`, etc and it doesn't provide a "confidence".

This API exposes little more than an *ON/OFF* switch.  It cannot be configured to ignore elevators.  You'd have to take that up with Google's engineers/physicists.
