### ISSUE TITLE
when user kill all apps by click on close all button

### ISSUE THREAD

**Issue by ammarmahafeza2** [transistorsoft/flutter_background_geolocation#349]
## Your Environment
* Plugin version: ^1.8.0
* Platform:  Android
* OS version: 10
* Device manufacturer / model: Samsung A 11 

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
          transistorAuthorizationToken: token,
          // disableStopDetection: true,
          // pausesLocationUpdatesAutomatically: false,
          triggerActivities:
              'on_foot, walking, running, in_vehicle, on_bicycle',
          useSignificantChangesOnly: false,
          allowIdenticalLocations: true,
          forceReloadOnLocationChange: true,
          preventSuspend: true,
          reset: true,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
          distanceFilter: 1, //1.0
          locationUpdateInterval: 5000,
          stopTimeout: 1,
          autoSync: true,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          heartbeatInterval: 120),
```

## Expected Behavior
my app is tracks user in foreground, background and after kill 

## Actual Behavior
it works fine with all status (foreground, background and after kill ) , however user kill app by pressing the close all button it stop running the whole functionality .

**Comment by christocracy** [comment]
- I don't seem to have this problem on my *Samsung A5 @ 8.0.0*.
- I don't have an option to `[Close All]` on my *Pixel 3a @ 11* or *Pixel @ 10*.

**Comment by ammarmahafeza2** [comment]
- This problem depend on the device ? 
- The Confgi is correct ?

**Comment by christocracy** [comment]
>This problem depend on the device ?

No idea.  If I were, I'd configure `debug: true` and observe `adb logcat` after `[Close all]` then shake the device vigorously for 10-45 seconds to simulate walking and see if the plugin comes to life.

>The Confgi is correct ?

`forceReloadOnLocationChange: true,`:  this option is deprecated and is no longer recognized by the plugin.  Get rid of it.  Other than that, your config is fine.
