### ISSUE TITLE
AndroidX - flutter build apk

### ISSUE THREAD

**Issue by cbfischer** [transistorsoft/flutter_background_geolocation#35]
Hello team,

I am trying to generate the APK, but it is giving an error.
In the simulator, debug, works perfectly.
Tks a lot for your help :)

Environment
* Plugin version: flutter_background_geolocation: ^0.3.4
* Platform: Android
* Flutter info (`flutter doctor`):
```
λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.2.1, on Microsoft Windows [versÃ£o 10.0.17763.316], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Proxy Configuration
[√] Connected device (1 available)

• No issues found!
```

My build.gradle:
```
android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "br.com.tmh.tmhmotorista"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 5
        versionName "1.0.5"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

```

When trying to build apk result a **flutter_background_geolocation:verifyReleaseResources**

```
λ flutter build apk
Initializing gradle...                                              1,2s
Resolving dependencies...                                           3,7s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\tmh_motorista\build\flutter_background_geolocation\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  C:\tmh_motorista\build\flutter_background_geolocation\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  C:\tmh_motorista\build\flutter_background_geolocation\intermediates\res\merged\release\values\values.xml:2650: error: resource android:attr/fontVariationSettings not found.
  C:\tmh_motorista\build\flutter_background_geolocation\intermediates\res\merged\release\values\values.xml:2651: error: resource android:attr/ttcIndex not found.
  error: failed linking references.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      70,3s
Gradle task assembleRelease failed with exit code 1

```

**Comment by cbfischer** [comment]
Same error using: flutter_background_geolocation: ^1.0.0-beta.4

**Comment by joserocha3** [comment]
Check [this pull request](https://github.com/transistorsoft/flutter_background_geolocation/pull/31). At the time Chris mentioned it will be a few weeks until he is able to migrate to AndroidX. You can subscribe to that pull request to get updates. 

It is mentioned to use the pull request contributor's forked repo. However, I could not get it working because of how he setup his `dependencies` to `background_fetch`. So I created [my own fork](https://github.com/joserocha3/flutter_background_geolocation.git) and it has been working thus far. I have not moved it to production yet.

```
dependencies:  
  flutter_background_geolocation:
    git:
      url: https://github.com/joserocha3/flutter_background_geolocation.git
```

**Comment by cbfischer** [comment]
> Check [this pull request](https://github.com/transistorsoft/flutter_background_geolocation/pull/31). At the time Chris mentioned it will be a few weeks until he is able to migrate to AndroidX. You can subscribe to that pull request to get updates.
> 
> It is mentioned to use the pull request contributor's forked repo. However, I could not get it working because of how he setup his `dependencies` to `background_fetch`. So I created my own [AndroidX fork of 1.0.0-beta.4](https://github.com/joserocha3/flutter_background_geolocation.git) and it has been working thus far. I have not moved it to production yet.
> 
> ```
> dependencies:  
>   flutter_background_geolocation:
>     git:
>       url: https://github.com/joserocha3/flutter_background_geolocation.git
> ```

I appreciate your help. worked perfectly.

**Comment by joserocha3** [comment]
Hi @cbfischer, glad I could help. The latest release has AndroidX implemented. If it works for you, it would be best to use that one instead of mine and close this issue.

**Comment by tlserver** [comment]
It seem that 1.0.0-beta5 is fixing this but change log have not been updated. Please update the change log.
