### ISSUE TITLE
Custom LocationTemplate not supported by batch-mode?

### ISSUE THREAD

**Issue by kengu** [transistorsoft/flutter_background_geolocation#352]
## Your Environment
* Plugin version: 1.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung Galaxy 10+
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-NO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config _toConfig({String duuid, String token}) {
    _duuid = duuid ?? _duuid;
    _token = token ?? _token;
    final bool publish = duuid != null && _token != null;
    final url = publish ? '${Defaults.baseRestUrl}/devices/$duuid/positions' : null;
    return bg.Config(
      debug: kDebugMode,
      startOnBoot: true,
      stopOnTerminate: false,
      autoSync: publish,
      batchSync: publish,
      maxBatchSize: 10,
      autoSyncThreshold: 5,
      httpRootProperty: '.',
      httpTimeout: 5000,
      method: 'POST',
      headers: {
        if (publish) "Authorization": "Bearer $_token",
      },
      url: url,
      locationTemplate: _toLocationTemplate(),
      locationUpdateInterval: _options.timeInterval,
      desiredAccuracy: _toAccuracy(_options.accuracy),
      distanceFilter: _options.distanceFilter.toDouble(),
      logLevel: kDebugMode ? bg.Config.LOG_LEVEL_VERBOSE : bg.Config.LOG_LEVEL_INFO,
    );
  }
```

## Expected Behavior
BG posts array of Location with custom template

## Actual Behavior
POST fails with log message
`"Appending #params to an HTTP Request of type {Array} is not yet supported."`

## Steps to Reproduce
1. Start plugin with config given above
2. Change position
3. Error message appears in log

## Context
I have a backend which have another schema then what BG supplies out of the box. The use case of tracking demand large amount of locations to be posted with minimum amount of power consumption. I need to use a batched approach, which currently seems impossible using BGs HTTP service since custom locationtemplates are not supported in array requests.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
Show me your `locationTemplate`

**Comment by kengu** [comment]
```dart
String _toLocationTemplate() {
    return '{'
        '"type": "Feature",'
        '"geometry": {"type": "Point", "coordinates": [<%= longitude %>, <%= latitude %>, <%= altitude %>]},'
        '"properties": {'
        '"source": "device",'
        '"timestamp": "<%= timestamp %>",'
        '"accuracy": <%= accuracy %>,'
        '"bearing": <%= heading %>,'
        '"speed": <%= speed %>'
        '}}';
  }
```

**Comment by kengu** [comment]
The backend expects an array of GeoJSON Feature Object of the the type given in the template

**Comment by christocracy** [comment]
>POST fails with log message
"Appending #params to an HTTP Request of type {Array} is not yet supported."

This is not an *error*, it's a *warning* and it won't prevent an HTTP request.  Show me these plugin logs from `logcat`

**Comment by christocracy** [comment]
>Custom LocationTemplate not supported by batch-mode?

Yes, `locationTemplate` *is certainly* compatible with `batchSync: true`.

**Comment by christocracy** [comment]
Also check that you don't have locations queued in the plugin's SQLite database that were rendered with a previous iterations of your `locationTemplate`.  See `BackgroundGeolocation.locations`, `BackgroundGeolocation.count`, `BackgroundGeolocation.destroyLocations`.

**Comment by kengu** [comment]
I'll do that, updates are posted soon

**Comment by christocracy** [comment]
- Location are rendered to JSON *only once*, when first recorded.  They are not re-rendered when `locationTemplate` is changed.
- The HTTP Service operates by selecting records from the database.
- The HTTP service will keep trying to upload locations until your server returns `200`

**Comment by kengu** [comment]
Your hunch was right. The server was receiving the default location template registered prior to the custom template was applied. Deleting all position solved the problem. The server is receiving all positions now as expected. Thanks for prompt replies and help. The issue can be closed.

**Comment by christocracy** [comment]
Please close your own issues when solved.
