### ISSUE TITLE
Usage of older (< 29) Android SDK versions

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [transistorsoft/flutter_background_geolocation#354]
* Plugin version: 1.3.2
* Platform: Flutter/Android
* OS version: Android 8.1 (Oreo), SDK version 26
* Device manufacturer / model: Samsung 5A 2017 (SM A520F)

The example in the Android installation guide states that the compileSdkVersion has to be
```compileSdkVersion   = 29                // or higher```
Is there any possibility to use your library with an older SDK version e.g. 26?

**Comment by christocracy** [comment]
You're free to set `compileSdkVersion` however you like.

**Comment by pmilic021** [comment]
@christocracy but trying to build with target 28 (for example) gives following error:
```
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/pmilic/Projects/playgrounds/flutter_background_geolocation/example/android/app/src/main/AndroidManifest.xml:40:9-135: AAPT: error: attribute android:foregroundServiceType not found.

     /Users/pmilic/Projects/playgrounds/flutter_background_geolocation/example/android/app/src/main/AndroidManifest.xml:41:9-142: AAPT: error: attribute android:foregroundServiceType not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
...
```

This was tried on the example project from this repo. Any idea how to fix it? We are still trying out this lib, but we have to support 28 API level, unfortunately.

**Comment by christocracy** [comment]
The `/example` app is configured to use [elements in its `AndroidManifest`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/src/main/AndroidManifest.xml#L40-L41) available only with `compileSdkVersion 29`.

```xml
<service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
        <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
```

Adding these elements is [documented in the Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#android-10-and-when-in-use-location-authorization)

**Comment by christocracy** [comment]
If you're not using `compileSdkVersion 29`, delete those elements from `/example` app's `AndroidManifest.xml`.

**Comment by christocracy** [comment]
If I were you, I'd simply install *Android 10.0 (Q) API Level 29* in *SDK Manager* and use `compileSdkVersion 29`.
![](https://dl.dropbox.com/s/arfclrxjywc7han/Screenshot%202020-08-05%2011.30.39.png?dl=1)

**Comment by christocracy** [comment]
It's perfectly ok to have `targetSdkVersion < compileSdkVersion`.

```gradle
buildscript {
    ext {
        compileSdkVersion   = 30
        targetSdkVersion    = 28
```

You should be compiling with the latest available `compileSdkVersion` so the compiler is *aware of* all the symbols.

**Comment by pmilic021** [comment]
Thanks for the quick reply and a tutorial! I was not aware that `compile` and `target` could be different and still make sense. This appears to have fixed the issue.
