### ISSUE TITLE
Same location and geofence updates firing repeatedly

### ISSUE THREAD

**Issue by elouiestudent** [transistorsoft/flutter_background_geolocation#355]
## Your Environment
* Plugin version: 1.9.1
* Platform: iOS
* OS version: 10.15.4
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`): Normal
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
// Called every time user logins
static Future<void> startBackgroundTracking() async {
bg.BackgroundGeolocation.onLocation(_locationCallback);
bg.BackgroundGeolocation.onGeofence(_geofenceCallback);
bg.BackgroundGeolocation.ready(bg.Config(
            locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Missing Location Permissions',
          'titleWhenOff': 'Missing Location Permissions',
          'instructions':
              'Go to Settings',
          'cancelButton': 'Ok',
          'settingsButton': 'Settings'
        },
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        print("backgroundGeolocationStart <");
        bg.BackgroundGeolocation.start();
      }
    });
}

// Called whenever user logs out
  static Future<void> stopBackgroundTracking() async {
    Logger.log("Stopping background location tracking...");
    // Stop the plugin
    await bg.BackgroundGeolocation.stop();
    await bg.BackgroundGeolocation.removeGeofences();
    await bg.BackgroundGeolocation.destroyLocations();
    Logger.log("Background location tracking stopped");
  }
```

## Expected Behavior

Background tracking should stop when user logs out and start when user logs in, with location updates and geofence events initially firing only once per id.

## Actual Behavior
Background tracking stops when user logs out, but upon logging back in geofence and location updates are firing one more time per geofence id/location update than the previous login.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What do you think *this* is going to do?

```dart
if (!state.enabled) {
        print("backgroundGeolocationStart <");
        bg.BackgroundGeolocation.start();
      }
```

**Comment by elouiestudent** [comment]
It seems like the code checks for whether state is enabled and then starts the plugin. Is the reason why duplicate updates are happening is because I call bg.BackgroundGeolocation.start(); more than once? It was my understanding that calling bg.BackgroundGeolocation.stop() upon logout would counteract this.

**Comment by christocracy** [comment]
`#start` / `#stop` are just like the power *on/off* button of any electronic device.

You've told the plugin to `start()` every time your app launches, regardless of *anything*.

**Comment by elouiestudent** [comment]
So calling bg.BackgroundGeolocation.stop() on logout doesn't power off the plugin? Is there a way to check whether the plugin is already running?

**Comment by christocracy** [comment]
>So calling bg.BackgroundGeolocation.stop() on logout doesn't power off the plugin

Calling `stop()` *always* turns off the plugin.  Calling `start()` **ALWAYS** turns *on* the plugin.

You've blindly copied this block from one of my examples without thinking:
```dart
if (!state.enabled) {
        print("backgroundGeolocationStart <");
        bg.BackgroundGeolocation.start();
      }
```

I only do that in example code to get the plugin working *immediately* for people first trying out the plugin.  You're not supposed to actually do that in your own application code, which will likely only `start()` due to some event, such as logging in) or a UI action, such as `[Start Workout]` in a *Jogging app*.

**Comment by elouiestudent** [comment]
I'm not quite sure what you mean. I call startBackgroundTracking() only when the user logs in, so I in essence call start() every time the user logs in.

**Comment by christocracy** [comment]
>I call startBackgroundTracking() only when the user logs in

You are supposed to call `#ready` **each time** the app launches, regardless of *anything*.  If you don't, you will miss out on events where your app was launched in the background.

**Comment by christocracy** [comment]
`#ready` **does not** imply `start()`.  `#ready` is a signal to the plugin that your app is launched and "ready" to receive events.

**Comment by christocracy** [comment]
```dart
onAppLaunched() {
  // ALWAYS CALL THIS -- each time your app launches, no matter what.  regardless if user isn't logged in.
  BackgroundGeolocation.ready(config);
}
onLogin() {
  BackgroundGeolocation.start();
}
onLogout() {
  BackgroundGeolocation.stop();
}
```

**Comment by christocracy** [comment]
If the plugin were a stereo receiver:
- `#ready` = plugging the device into power.
- `#start` = power on.
- `#stop` = power off.

Plugging the device into power does not imply turning on the power button.

**Comment by elouiestudent** [comment]
I see. So if BackgroundGeolocation.ready(config) is called multiple times (e.g. more than just once when the app is launched) does this spawn multiple threads causing there to be duplicate events?

**Comment by christocracy** [comment]
Further to the stereo receiver analogy, adding event-listeners (eg: `onLocation`) is like wiring up speaker wires.

You're free to wire up your speakers, regardless if user is logged in or not.  They're not going to play any audio until `start()` is called.

**Comment by christocracy** [comment]
>does this spawn multiple threads causing there to be duplicate events?

There's no such thing as multiple threads causing duplicate events.  Only duplicate event-listeners can cause multiple events.

```dart
BackgroundGeolocation.onLocation(_locationCallback);
BackgroundGeolocation.onLocation(_locationCallback);
BackgroundGeolocation.onLocation(_locationCallback);
```

**Comment by christocracy** [comment]
In your case, you will add new event-listeners when you do the following:
```dart
startBackgroundTracking();
stopBackgroundTracking();

startBackgroundTracking();
stopBackgroundTracking();

startBackgroundTracking();
stopBackgroundTracking();
```

Wire up your event-listeners and call `#ready`, regardless if user is logged in or not.

**Comment by christocracy** [comment]
When you turn on your stereo, you don't re-wire your speakers.  You just turn off the power button.

**Comment by elouiestudent** [comment]
So would the process be like this?:
```
onAppLaunched() {
  // ALWAYS CALL THIS -- each time your app launches, no matter what.  regardless if user isn't logged in.
  // Wire up listeners
  BackgroundGeolocation.ready(config);
}
onLogin() {
  BackgroundGeolocation.start();
}
onLogout() {
  BackgroundGeolocation.stop();
}
```

**Comment by christocracy** [comment]
yes.

**Comment by elouiestudent** [comment]
Thanks for your help! I really appreciate you taking the time to help me understand the underlying concepts behind the plugin's functionality and event-listeners in general.
