### ISSUE TITLE
How can i stop push notification on location change.

### ISSUE THREAD

**Issue by VatsalBhesaniya** [transistorsoft/flutter_background_geolocation#356]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
They're not *push* notifications, they're *local* notifications.  They're enabled with `Config.debug` and provided to assist you during development while field-testing.

**Comment by VatsalBhesaniya** [comment]
@christocracy  Thank you for your response.
Could you please guide me how can i remove local notification? I can't find Config.debug file in example.

**Comment by christocracy** [comment]
See API docs `Config.debug`.  The API docs are linked in the README

**Comment by aaronsamkennedy** [comment]
@VatsalBhesaniya I had this same issue and even once I updated debug to false and pushed it to test flight I couldn't get debug notifications and sounds to stop. I had to delete the test flight app off my phone and re-download it. After that everything was fine.

**Comment by christocracy** [comment]
@aaronsamkennedy were you using `reset: false` in your Config?

**Comment by aaronsamkennedy** [comment]
Yes, I had reset to false because I don't want it to "force the supplied Config to be applied with each launch of your application"(from documentation) but I needed it to reset after an app update.

**Comment by christocracy** [comment]
Well that's why changing your Config had no effect.

> force the supplied Config to be applied 

Why?
