### ISSUE TITLE
Opening app notification displays blank app screen

### ISSUE THREAD

**Issue by jweidner-mbible** [transistorsoft/flutter_background_geolocation#357]
* Plugin version: 1.9.3
* Platform: iOS
* OS version: 12.4.6
* Device manufacturer / model: iPhone 6 Plus
* Flutter info (`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```

I have reproduce this issue using an unmodified copy of the flutter_background_geolocation hello_world app.

## Expected Behavior
Opening an app's notification should display the app

## Actual Behavior
App screen opens but no text or images are displayed.  (see attached screenshot). However, app is functional and you are able to interact with UI controls even though they are not displayed.

## Steps to Reproduce
1.  Run your hello_world app
2.  tap the toggle button at the top right so that it turns blue
3.  close the app by tapping iPhone 8's home button twice and then swiping up on the app
4.  remove any existing notifications from the app
5.  move around until a notification from the app gets sent to your phone
6.  display the notification
7.  open the notification so that the app gets launched

This issue only seems to happen with the first notification that you open that was generated after the app was closed.

## Context
Originally, I was writing an app that displays a notification (using flutter_local_notifications plugin) based on entering a geofence registered with this plugin.  Opening the notification should then display the app.  Works fine on Android, but on iOS it resulted in a blank version of my app's UI.  I eventually realized the same issue happens with the debug notifications generated by your plugin in my app.  Then I was able to reproduce the problem with your example hello_world app.

## Debug logs

<details>
</details>

![IMG_2FE62D7403AB-1](https://user-images.githubusercontent.com/20305851/88977641-eacbe080-d283-11ea-9290-4a12606c9058.jpeg)

**Comment by christocracy** [comment]
I believe this is a bug with Flutter.  Somebody recently posted a link to the relevant issue at Flutter repo, but I don’t recall atm.

**Comment by jweidner-mbible** [comment]
I was not able to find the issue on https://github.com/flutter/flutter/issues.   Please drop a link here if you find it.

**Comment by christocracy** [comment]
See this: https://github.com/flutter/flutter/issues/55969 and [this comment](https://github.com/flutter/flutter/issues/55969#issuecomment-663870552) in particular.

**Comment by christocracy** [comment]
Locally, I've upgraded to Flutter sdk `1.20.0-7.3.pre` on the beta channel and booted the `/example` app on my *iPhone 12 @ 13.6*  I'll see how it goes:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Mac OS X 10.15.5 19F101, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)
```

**Comment by christocracy** [comment]
Flutter sdk `1.20.1` has just been released to *channel: stable*:

```
ford:example chris$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (4 available)
```

**Comment by TomStoffen** [comment]
I have also been having this issue the past weeks, tried both latest stable flutter and latest beta flutter.
While this seems to be a problem in flutter, there is someone mentioning geofences in a related issue over at the flutter repo:
https://github.com/flutter/flutter/issues/64558#issuecomment-683793230
Apparently _might_ be related to some background activity triggered by entering geofences.
Do you maybe have something to add there that might help them out, @christocracy ?

**Comment by christocracy** [comment]
The issue is with a Flutter app launching in the background.

A geofence is capable of re-launching a terminated iOS app in the background.

I have not experienced this in the SampleApp since upgrading to Flutter sdk 1.20.

**Comment by TomStoffen** [comment]
Right, I missed that part about terminated app - I should have said similar issue, apologies. 
It does indeed happen when the app resumes after being paused by iOS, possibly after a user has entered a geofence causing some background activity to happen.

**Comment by christocracy** [comment]
I suggest you install the SampleApp on your iOS device.  The sample app is always re-launching due to a geofence event.  That's how the iOS SDK determines the device is moving.  As I've said, I no longer see any issues since updating Flutter sdk to `1.20`.

I use to experience garbled text and missing icons.
