### ISSUE TITLE
[Question] Using only GPS provider?

### ISSUE THREAD

**Issue by Max-Might** [transistorsoft/flutter_background_geolocation#358]
Hello.

Is it possible to configure the library to only use the GPS provider and not wifi and cellular?

**Comment by christocracy** [comment]
No.  The native iOS/Android apis automatically return the best available location in under the circumstances the device is in.

- GPS is only available outdoors.  When the device is outdoors and the sky unobstructed by physical barriers (eg mountains, tall buildings, tunnels), the location will most likely come from gps.
- if the device is indoors, the location will most Kelley come from WiFi.
- when all else fails, the location will come from cellular.
