### ISSUE TITLE
How to disable de sound alerts?

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#359]
## Your Environment
* Plugin version: 1.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Xiaomi Mi9T
* Flutter info (`flutter doctor`):

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale en-GB)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
            reset: false,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 3.0,
            stopTimeout: 1,
            // HTTP & Persistence
            autoSync: true,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60)
```

## Context
I've removed all the "playSound" calls from the code, but the plugin still playing sounds when get a position and so on. There is a way to disable ALL the sounds from the plugin?

**Comment by christocracy** [comment]
See API docs `Config.debug`

**Comment by kvenn** [comment]
I see in the documentation that turning off debug disables the notifications _and_ the sounds. Is it possible to keep the notifications but turn off the sound? 

Thanks.

**Comment by christocracy** [comment]
>keep the notifications but turn off the sound?

No.  It’s for debugging purposes only.

**Comment by kvenn** [comment]
Understood. My debugging use case for sound-off with notifications:
I have the app installed on my physical device and have been testing how it works in a real-world scenario. I've been checking the notifications periodically to understand when the SDK triggers certain events (which the debug mode has been great for). The only problem is that I'm in meetings and my phone is chirping.

I've just been printing the logs to the screen with `LOG_LEVEL_DEBUG` which seems to be mostly the same as the notifications (but more verbose).
```
locationString = await Logger.getLog(SQLQuery(
            order: SQLQuery.ORDER_DESC,
            start: DateTime.now().subtract(const Duration(days: 1))));
```

Anyways, thanks for the great library.
