### ISSUE TITLE
Blank screen on start with no crash.

### ISSUE THREAD

**Issue by gopchi** [transistorsoft/flutter_background_geolocation#36]
## Environment: Windows
* Plugin version: 0.3.4
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Xiaomi / Mi A2
* Flutter info (`flutter doctor`):
`[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Lizard\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.2
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[√] VS Code (version 1.32.1)
    • VS Code at C:\Users\Lizard\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Mi A2 • 48748b8 • android-arm64 • Android 9 (API 28)`

## Expected Behavior
App should have started

## Actual Behavior
After successful installation there is a blank screen and the the app window closes with not crash or error thrown.

## Steps to Reproduce
1. Did all the setup from the docs
2. Run the app

## Context
Run the app

## Debug logs
There are no debug logs.

Here is also the Application.java file we are using to run the app as per your documentation:

```
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

**Comment by joserocha3** [comment]
Did you include `com.company.appname` at the tip of the `Application.java` file? I had to do that to get it working.

**Comment by gopchi** [comment]
@joserocha3 Doh... that was it. Thanks for the immediate response! Everything works fine now. I am resolving the issue.

**Comment by christocracy** [comment]
Thanks @jserocha3.  Is there something missing in setup doc?

**Comment by joserocha3** [comment]
Hey @christocracy, as far as I remember that was the only issue I ran into. Will let you know if I remember another.
