### ISSUE TITLE
Is logLevel's default LOG_LEVEL_VERBOSE or LOG_LEVEL_OFF?

### ISSUE THREAD

**Issue by HugoHeneault** [transistorsoft/flutter_background_geolocation#364]
According to https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/logLevel.html it's `LOG_LEVEL_VERBOSE` but [here](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Logger/getLog.html)  it is `LOG_LEVEL_OFF`

Which one's the one? ;-)

**Comment by christocracy** [comment]
The default is `LOG_LEVEL_OFF`.
