### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#366]
## Your Environment
* Plugin version: 1.9.3
* Platform: Android
* OS version: Android 10 
* Device manufacturer / model: Xiaomi Mi 9T

Is there a way to set a custom notification icon instead of using the app default icon?

**Comment by christocracy** [comment]
See API docs [`Config.notification`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/notification.html)
