### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method ready on channel com.transistorsoft/flutter_background_geolocation/methods)

### ISSUE THREAD

**Issue by Itmaxglobal** [transistorsoft/flutter_background_geolocation#368]
## Your Environment
* Plugin version:1.9.3
* Platform: iOS 
* OS version: iOS 13.6
* Device manufacturer / model: iPhone Emulator
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

@override
  void initState() {
    super.initState();
    _selectedIndex = 0;
    scrollController = ScrollController()
      ..addListener(() {
        setDialVisible(scrollController.position.userScrollDirection ==
            ScrollDirection.forward);
      });

    //
    // 1.  Listen to events (See docs for all 12 available events).
    

    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });

    //
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
  }
```

## Expected Behavior

It should start continuous location updates
## Actual Behavior

It fails at bg.ready line with MissingPluginException.
## Steps to Reproduce

1.
2.
3.
4.

## Context

Trying to find a plugin to get continuous locations updates in the Background

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Show me your `pubspec.yaml`

**Comment by Itmaxglobal** [comment]
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  sqflite: ^1.2.0
  path_provider: ^1.4.5
  pie_chart: ^3.1.1
  flappy_search_bar: ^1.4.1
  google_maps_flutter: #: ^0.5.19+2 #^0.5.21+15
  timeline_list: ^0.0.5
  masked_text: ^0.0.6
  url_launcher: ^5.4.5
  flutter_appavailability: ^0.0.21
  font_awesome_flutter: ^8.8.1
  share: #^0.6.3+5
  table_calendar: ^2.2.2
  flutter_bloc: ^5.0.0
  meta: ^1.1.8
  equatable: ^1.2.0
  intl: ^0.16.1
  geolocator: ^5.3.2+2
  flutter_speed_dial: ^1.2.5
  random_color: ^1.0.5
  image_picker: ^0.6.5+3
  mime: ^0.9.6+3
  toast: ^0.1.5
  flutter_staggered_grid_view: ^0.3.0
  flutter_sparkline: ^0.1.0
  flutter_circular_chart: ^0.1.0
  flutter_background_geolocation: ^1.9.3
  background_fetch: '^0.6.0' 
  flutter_launcher_icons:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/launcher.png'
  android: true
  ios: true

**Comment by christocracy** [comment]
- Re-visit the *iOS Setup*
- `flutter clean`
- `flutter build ios`

**Comment by christocracy** [comment]
Have you tried running the `/example` app in this repo?

**Comment by Itmaxglobal** [comment]
> Have you tried running the `/example` app in this repo?

No I didn't try. I will try and will let you know.

**Comment by Itmaxglobal** [comment]
> * Re-visit the _iOS Setup_
> * `flutter clean`
> * `flutter build ios`

**Comment by Itmaxglobal** [comment]
> > Have you tried running the `/example` app in this repo?
> 
> No I didn't try. I will try and will let you know.

Thank you Chris for your help, it worked after doing flutter clean and flutter build ios
