### ISSUE TITLE
App crashes on iPhone 10 but works in emulator

### ISSUE THREAD

**Issue by delegate-it** [transistorsoft/flutter_background_geolocation#369]
## Your Environment
* Plugin version: 1.9.3
* Platform: iOS
* OS version: 13.6
* Device manufacturer / model: iPhone X
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  @override
  void initState() {
    // TODO: implement initState
    super.initState();


    ////
    // 1.  Listen to events (See docs for all 12 available events).
    //

    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
      setState(() {
        _odometer = location.odometer;
      });
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });

    ////
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
  }

```

## Expected Behavior

Start location tracking in the background
## Actual Behavior

The app crashes at bottom line
```
bg.BackgroundGeolocation.ready(bg.Config(
```
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Where is the *stacktrace*??

**Comment by delegate-it** [comment]
2020-08-10 17:48:06.843981+0200 Runner[2053:576558] ℹ️-[TSConfig persist] 
ℹ️-[TSConfig persist] 
🔵-[TSLocationManager ready] 
2020-08-10 17:48:06.846441+0200 Runner[2053:576426] 🔵-[TSLocationManager ready] 
2020-08-10 17:48:06.930252+0200 Runner[2053:576437] flutter: [providerchange] - [ProviderChangeEvent enabled:false, status: 0, network: true, gps: true]

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════
2020-08-10 17:48:06.961842+0200 Runner[2053:576809] 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager doStart:] trackingMode: 1
2020-08-10 17:48:06.961938+0200 Runner[2053:576426] ℹ️-[TSLocationManager doStart:] trackingMode: 1
ℹ️-[TSConfig persist] 
2020-08-10 17:48:06.962031+0200 Runner[2053:576426] ℹ️-[TSConfig persist] 
🎾-[TSGeofenceManager start] 
2020-08-10 17:48:06.962496+0200 Runner[2053:576809] 🎾-[TSGeofenceManager start] 
🎾-[SOMotionDetector startDetection] 
2020-08-10 17:48:07.024920+0200 Runner[2053:576558] 🎾-[SOMotionDetector startDetection] 
🔵-[TSLocationManager setPace:] 0
2020-08-10 17:48:07.025094+0200 Runner[2053:576426] 🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
2020-08-10 17:48:07.027210+0200 Runner[2053:576809] 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════
2020-08-10 17:48:07.029453+0200 Runner[2053:576601] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚══════════════════════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚══════════════════════════════════\342═════════════════════════

╔══════════════════════════════════════════════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚══════════════════════════════════\342═════════════════════════

╔══════════════════════════════════════════════════════════\342═
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
2020-08-10 17:48:07.030089+0200 Runner[2053:576601] 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
ℹ️+[LocationAuthorization run:onCancel:] status: 0
2020-08-10 17:48:07.030203+0200 Runner[2053:576426] ℹ️+[LocationAuthorization run:onCancel:] status: 0
2020-08-10 17:48:07.030638+0200 Runner[2053:576426] 🔵+[LocationAuthorization run:onCancel:] Request: requestAlwaysAuthorization
🔵+[LocationAuthorization run:onCancel:] Request: requestAlwaysAuthorization
2020-08-10 17:48:07.035137+0200 Runner[2053:576456] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.
(lldb)

**Comment by christocracy** [comment]
>This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.

See [iOS Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md#permissions--background-modes).  You didn't add **ALL** the required strings in your `Info.plist`:

![](https://dl.dropbox.com/s/0hcybs2cwgjbs1f/Screen%20Shot%202020-08-10%20at%2011.53.58%20AM.png?dl=1)

**Comment by delegate-it** [comment]
Thank you Chris. I totally missed "Motion Usage" string, I didn't know that you need motion but now I understand how you use motion for location tracking. After adding the Motion string it worked perfectly.
