### ISSUE TITLE
Foreground service is terminated immediately after starting

### ISSUE THREAD

**Issue by Eddydpyl** [transistorsoft/flutter_background_geolocation#37]
## Your Environment
* Plugin version: 1.0.0-beta.5
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Moto G 5 Plus
* Flutter info (`flutter doctor`):

[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.648], locale en-150)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)
• No issues found!

* Plugin config

```dart
bg.BackgroundGeolocation.ready(bg.Config(
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10.0,
              stopOnTerminate: false,
              startOnBoot: true,
              foregroundService: true,
              enableHeadless: false,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              notificationTitle: "OMITTED",
              notificationText: "OMITTED",
              notificationSmallIcon: "mipmap/launcher_icon",
              notificationColor: "OMITTED",
              url: "OMITTED",
              headers: {
                "authorization": "OMITTED"
              },
            )).then((bg.State state) {
              if (!state.enabled)
                bg.BackgroundGeolocation.start();
            });
```

## Expected Behavior
Before updating to the latest version, the foreground serviced ran normally, but after updating it's destroyed as soon as it's started.

## Actual Behavior
Foreground service is terminated immediately after starting.

## Context
I have already checked for possible configurations by which the phone could be killing the service, such as battery saving, and have found nothing. 

It may be unrelated, but I'm also incapable of building a release apk that works. I can run the application in debug no problem, but once the release apk is launched, it crashes immediately. Also, it's not possible to even build it if I enable proguard (though I'll open another issue for this).

Again just in case it's relevant: I have bought the license and properly added it to the manifest.

## Debug logs
Performing hot restart...
Syncing files to device Moto G 5 Plus...
Restarted application in 4,125ms.

D/TSLocationManager( 9494): [c.t.l.g.TSGeofenceManager b] 
D/TSLocationManager( 9494):   🔴  Stop monitoring geofences
I/TSLocationManager( 9494): [c.t.l.g.TSGeofenceManager stopMonitoringSignificantLocationChanges] 
I/TSLocationManager( 9494):   🔴  Stop monitoring significant location changes
D/TSLocationManager( 9494): [c.t.l.g.TSGeofenceManager stopMonitoringStationaryRegion] 
D/TSLocationManager( 9494):   🔴  Stop monitoring stationary region
I/TSLocationManager( 9494): [c.t.l.s.ActivityRecognitionService b] 
I/TSLocationManager( 9494):   🔴  Stop motion-activity updates
I/TSLocationManager( 9494): [c.t.l.service.HeartbeatService a] 
I/TSLocationManager( 9494):   🔴  Stop heartbeat
D/TSLocationManager( 9494): [c.t.l.http.HttpService stopMonitoringConnectivityChanges] 
D/TSLocationManager( 9494):   🔴  Stop monitoring connectivity changes
D/TSLocationManager( 9494): [c.t.locationmanager.device.a d] 
D/TSLocationManager( 9494):   🔴  Stop monitoring powersave changes
D/TSLocationManager( 9494): [c.t.l.service.TrackingService onDestroy] 
D/TSLocationManager( 9494):   🔴  TrackingService destroyed
D/TSLocationManager( 9494): [c.t.l.s.ActivityRecognitionService onDestroy] 
D/TSLocationManager( 9494):   🔴  ActivityRecognitionService destroyed
D/TSLocationManager( 9494): [c.t.locationmanager.util.b a] 
D/TSLocationManager( 9494):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 9494): - Enable: false → true, trackingMode: 1
I/TSLocationManager( 9494): [c.t.l.service.HeartbeatService a] 
I/TSLocationManager( 9494):   🔴  Stop heartbeat
I/TSLocationManager( 9494): [c.t.l.service.TrackingService a] 
I/TSLocationManager( 9494):   🔵  setPace: false → false
D/TSLocationManager( 9494): [c.t.locationmanager.util.b a] 
D/TSLocationManager( 9494):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 9494): [c.t.l.s.ActivityRecognitionService a] 
I/TSLocationManager( 9494):   🎾  Start motion-activity updates
I/TSLocationManager( 9494): [c.t.l.g.TSGeofenceManager start] 
I/TSLocationManager( 9494):   🎾  Start monitoring geofences
D/TSLocationManager( 9494): [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
D/TSLocationManager( 9494):   🎾  Start monitoring connectivity changes
D/TSLocationManager( 9494): [c.t.locationmanager.device.a c] 
D/TSLocationManager( 9494):   🎾  Start monitoring powersave changes
D/TSLocationManager( 9494): [c.t.l.http.HttpService a] 
D/TSLocationManager( 9494): ╔═════════════════════════════════════════════
D/TSLocationManager( 9494): ║ 📶  Connectivity change: connected? true
D/TSLocationManager( 9494): ╠═════════════════════════════════════════════
D/TSLocationManager( 9494): [c.t.l.http.HttpService flush] 
D/TSLocationManager( 9494): ╔═════════════════════════════════════════════
D/TSLocationManager( 9494): ║ HTTP Service
D/TSLocationManager( 9494): ╠═════════════════════════════════════════════
D/TSLocationManager( 9494): [c.t.locationmanager.data.a.c first] 
D/TSLocationManager( 9494):   ✅  Locked 1 records
I/TSLocationManager( 9494): [c.t.l.http.HttpService a] 
I/TSLocationManager( 9494):   🔵  HTTP POST: d3dde321-9462-4184-bf4f-e98d3aebe1a3
I/TSLocationManager( 9494): [c.t.l.http.HttpService$b onResponse] 
I/TSLocationManager( 9494):   🔵  Response: 202
D/TSLocationManager( 9494): [c.t.locationmanager.data.a.c unlock] 
D/TSLocationManager( 9494):   ✅  UNLOCKED: d3dde321-9462-4184-bf4f-e98d3aebe1a3
D/TSLocationManager( 9494): [c.t.l.l.SingleLocationRequest$2 onLocationResult] 
D/TSLocationManager( 9494): ╔═════════════════════════════════════════════
D/TSLocationManager( 9494): ║ SingleLocationRequest: 6
D/TSLocationManager( 9494): ╠═════════════════════════════════════════════
D/TSLocationManager( 9494): ╟─ 📍  Location[fused 37.371042,-5.978074 hAcc=17 et=+11m31s545ms vAcc=??? sAcc=??? bAcc=???], age: 66ms, time: 1552680032339
I/TSLocationManager( 9494): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager( 9494):   🔵  Acquired motionchange position, isMoving: false
D/TSLocationManager( 9494): [c.t.l.l.TSLocationManager a] Median accuracy: 17.019
D/TSLocationManager( 9494): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
D/TSLocationManager( 9494):   🎾  Start monitoring stationary region (radius: 150.0 meters)
I/TSLocationManager( 9494): [c.t.locationmanager.data.a.c persist] 
I/TSLocationManager( 9494):   ✅  INSERT: 9f736bd2-409f-43d7-b41c-3c77cf0286b4
D/TSLocationManager( 9494): [c.t.l.service.TrackingService onDestroy] 
D/TSLocationManager( 9494):   🔴  TrackingService destroyed
D/TSLocationManager( 9494): [c.t.l.http.HttpService flush] 
D/TSLocationManager( 9494): ╔═════════════════════════════════════════════
D/TSLocationManager( 9494): ║ HTTP Service
D/TSLocationManager( 9494): ╠═════════════════════════════════════════════
D/TSLocationManager( 9494): [c.t.locationmanager.data.a.c first] 
D/TSLocationManager( 9494):   ✅  Locked 1 records
I/TSLocationManager( 9494): [c.t.l.http.HttpService a] 
I/TSLocationManager( 9494):   🔵  HTTP POST: d3dde321-9462-4184-bf4f-e98d3aebe1a3
I/TSLocationManager( 9494): [c.t.l.http.HttpService$b onResponse] 
I/TSLocationManager( 9494):   🔵  Response: 202
D/TSLocationManager( 9494): [c.t.locationmanager.data.a.c unlock] 
D/TSLocationManager( 9494):   ✅  UNLOCKED: d3dde321-9462-4184-bf4f-e98d3aebe1a3
D/TSLocationManager( 9494): [c.t.l.s.ActivityRecognitionService a] 
D/TSLocationManager( 9494):   🚘 ️DetectedActivity [type=STILL, confidence=100]
D/TSLocationManager( 9494): [c.t.l.s.ActivityRecognitionService onDestroy] 
D/TSLocationManager( 9494):   🔴  ActivityRecognitionService destroyed
Application finished.

**Comment by christocracy** [comment]
This is the whole point of 1.0.0-beta:  a complete re-factor of the Android service architecture, where the foreground-service (and its corresponding persistent notification) are no longer required when the plugin is in the stationary state.

**Comment by christocracy** [comment]
See https://github.com/transistorsoft/flutter_background_geolocation/pull/30

**Comment by Eddydpyl** [comment]
Whoops, I had no idea. Thanks for clearing this up for me!

**Comment by egorikem** [comment]
I still have the same issue with v1.3.2

**Comment by pavelstupka** [comment]
Confirmed, still happening with the current version - actually it is 1.8.0 (see you pubspecs.lock).

**Comment by christocracy** [comment]
@egorikem The plugin's foreground-service is **normally OFF**.  It's only activated when the device is detected to be moving.  While the device is stationary, you should expect no activate foreground-service.

**Comment by tigran-mkhitaryan** [comment]
Now we have same problem with dart and flutter new version on android devices,
 D/TSLocationManager( 4918): [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]
I/TSLocationManager( 4918): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager( 4918):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
D/TSLocationManager( 4918): [c.t.l.a.TSLocationManagerActivity onDestroy] 
I/TSLocationManager( 4918): [c.t.l.s.TSScheduleManager cancelOneShot] 
I/TSLocationManager( 4918):   ⏰ Cancel OneShot: TERMINATE_EVENT
D/TSLocationManager( 4918): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4918):   🔴  TrackingService destroyed
D/TSLocationManager( 4918): [c.t.l.service.AbstractService a] 
D/TSLocationManager( 4918):   🎾  ActivityRecognitionService [eventCount: 1]
D/TSLocationManager( 4918): [c.t.l.s.ActivityRecognitionService a] 
D/TSLocationManager( 4918):   🚘 ️DetectedActivity [type=STILL, confidence=100]
D/TSLocationManager( 4918): [c.t.l.service.AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
D/TSLocationManager( 4918): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4918):   🔴  ActivityRecognitionService destroyed

**Comment by christocracy** [comment]
It doesn’t matter that it says “service destroyed”.

the plugin uses a `PendingIntent.getForegroundService`, which will automatically relaunch the required service when required (Eg When Motion API reports the device is in-motion).

this is supposed to happen.
