### ISSUE TITLE
License validation Failure

### ISSUE THREAD

**Issue by nagarjunand** [transistorsoft/flutter_background_geolocation#373]
## Your Environment
* Plugin version: 1.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Emulator(Pixel 2)
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-10.0.pre.70, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      bg.BackgroundGeolocation.ready(bg.Config(
              enableHeadless: true,
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: 50.0,
              stopOnTerminate: false,
              startOnBoot: true,
              debug: true,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE))
          .then((bg.State state) {
        if (!state.enabled) {

          bg.BackgroundGeolocation.start();
        }
      });
```

## Expected Behavior

Already my app in live. 
Just enabling location tracker in app
I am evaluating with free version.
After configuring with ready and start process it is working. call back is calling once.
But location is continuously changing. But callback is not working. 
Sometime notfication is showing and call back is working. Most of the times its not.
Please help me. 
I am using emulator and maptogpx for location change

FYI: I have added print("AAAA...") and print (id) in callback

## Actual Behavior

It showing **License validation Failure**
Failed to find licerse key in AndriodManifest

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/flutter (21686): [location] - [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {}, event: motionchange, battery: {level: 1.0, is_charging: false}, uuid: 9cbac5cd-9a3a-4c4f-9bb4-096ae8e2f0d0, coords: {altitude: 0.0, heading: 180.0, latitude: 11.6540983, accuracy: 20.0, speed: 54.04, longitude: 78.141}, is_moving: false, timestamp: 2020-08-14T09:38:57.000Z}]
I/flutter (21686): AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
I/flutter (21686): 2
I/flutter (21686): [motionchange] - [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {}, event: motionchange, battery: {level: 1.0, is_charging: false}, uuid: 9cbac5cd-9a3a-4c4f-9bb4-096ae8e2f0d0, coords: {altitude: 0.0, heading: 180.0, latitude: 11.6540983, accuracy: 20.0, speed: 54.04, longitude: 78.141}, is_moving: false, timestamp: 2020-08-14T09:38:57.000Z}]
D/TSLocationManager(21686): [c.t.l.s.LocationRequestService b] SingleLocationRequest 1 isFinished? true
I/TSLocationManager(21686): [c.t.l.s.ActivityRecognitionService b]
I/TSLocationManager(21686):   🎾  Start motion-activity updates
D/TSLocationManager(21686): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion]
D/TSLocationManager(21686):   🎾  Start monitoring stationary region (radius: 150.0m 11.6540983,78.141 hAcc=20.0)
I/TSLocationManager(21686): [c.t.l.data.sqlite.b persist]
I/TSLocationManager(21686):   ✅  INSERT: 9cbac5cd-9a3a-4c4f-9bb4-096ae8e2f0d0
W/om.teleduce.is(21686): JNI critical lock held for 20.489ms on Thread[1,tid=21686,Runnable,Thread*=0xefc37800,peer=0x729691f0,"main"]
I/TSLocationManager(21686): [c.t.l.service.TrackingService i]
I/TSLocationManager(21686): ╔═════════════════════════════════════════════
I/TSLocationManager(21686): ║ TrackingService motionchange: false
I/TSLocationManager(21686): ╠═════════════════════════════════════════════
I/om.teleduce.is(21686): Background concurrent copying GC freed 28662(1443KB) AllocSpace objects, 4(208KB) LOS objects, 49% free, 2434KB/4869KB, paused 992us total 269.382ms
D/TSLocationManager(21686): [c.t.l.service.TrackingService onDestroy]
D/TSLocationManager(21686):   🔴  TrackingService destroyed
D/TSLocationManager(21686): [c.t.l.s.ActivityRecognitionService a]
D/TSLocationManager(21686):   🚘 ️DetectedActivity [type=STILL, confidence=100]
V/MediaPlayer(21686): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(21686): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/TSLocationManager(21686): [c.t.l.s.ActivityRecognitionService onDestroy]
D/TSLocationManager(21686):   🔴  ActivityRecognitionService destroyed
D/EGL_emulation(21686): eglMakeCurrent: 0xe49f1400: ver 2 0 (tinfo 0xd9419360)
I/TSLocationManager(21686): [c.t.l.s.TSScheduleManager oneShot]
I/TSLocationManager(21686):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
I/TSLocationManager(21686): [c.t.l.s.TSScheduleManager cancelOneShot]
I/TSLocationManager(21686):   ⏰ Cancel OneShot: TERMINATE_EVENT
E/Surface (21686): getSlotFromBufferLocked: unknown buffer: 0x4e004f
W/libEGL  (21686): EGLNativeWindowType 0xc05af008 disconnect failed
D/EGL_emulation(21686): eglMakeCurrent: 0xefc7f820: ver 2 0 (tinfo 0xd93e65a0)
D/EGL_emulation(21686): eglMakeCurrent: 0xe49f1400: ver 2 0 (tinfo 0xd9419360)
D/EGL_emulation(21686): eglMakeCurrent: 0xefc7f820: ver 2 0 (tinfo 0xd93e65a0)
D/EGL_emulation(21686): eglMakeCurrent: 0xe49f1400: ver 2 0 (tinfo 0xd9419360)
I/TSLocationManager(21686): [c.t.l.s.TSScheduleManager oneShot]
I/TSLocationManager(21686):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
```

</details>

**Comment by christocracy** [comment]
>It showing License validation Failure
Failed to find licerse key in AndriodManifest

The plugin is fully functional in **debug** builds so you can try before you buy, in spite of *License Validation Failure*.

See Wiki *Debugging* and *Philosophy of Operation*.

The plugin engages tracking when the *Motion API* (accelerometer, gyroscope, magnetometer) reports the device is moving.

The Motion API doesn't operate in Android emulator.  You need to *manually* engage tracking with `BackgroundGeolocation.changePace(true)`.

It's best to test on a real device with *real* movement (eg: walking, biking, vehicle).

**Comment by nagarjunand** [comment]
Okay.. Thank you christocaracy. This killed my time of checking with emulator.

**Comment by nagarjunand** [comment]
I have one more doubt. 
In headlessEvent, getting null for some values i am using in dart code as a global access variables. 
Can i able to access sqflite db from headlessevent. 
Because I am using API hit to send data to server, i want  to store in local db when internet is not working.

**Comment by christocracy** [comment]
You should learn more about this plugin by reading the api docs.

This sdk *already contains* its own sqlite db, persisting every recorded location.

It also has its own native http service which feeds off this database.

This sdk was originally designed for a disaster-response app, tracking emergency workers in hurricanes / earthquakes where life depends on it.  It operates under the assumption that network connectivity is destroyed and queues every recorded location as if life depends on it.

**Comment by nagarjunand** [comment]
Great. Thanks for your reply. I will look into API docs. 
I am closing this issue. 
thank you
