### ISSUE TITLE
Need help to get existing config state

### ISSUE THREAD

**Issue by nagarjunand** [transistorsoft/flutter_background_geolocation#375]
## Your Environment
* Plugin version:1.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Pixel 2
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-10.0.pre.95, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(                       
     params: {
                              'api_key': globals.api_key,
                              'actionto': 'task',
                              'customer_id': globals.customerId,
                              'env': 'test',
                              'user_id': globals.userId,
                              'locationtime': DateTime.now().toString(),
                              'address': 'null',
                            },
                            extras: {
                              'customer_id': globals.customerId,
                              'api_key': globals.api_key,
                              'user_id': globals.userId,
                              'taskid': taskid
                            },
logLevel: bg.Config.LOG_LEVEL_VERBOSE))
                        .then((bg.State state) {
}
```

## Expected Behavior

When i am reopening app after close or terminate
Need to get enabled config information. 

## Actual Behavior

I need help to achieve above

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
NO logs
```

</details>

**Comment by christocracy** [comment]
See the [Static Properties](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation-class.html#static-properties) section of `BackgroundGeolocation` in the API docs.

You'll find one of them particularly interesting to you.

**Comment by nagarjunand** [comment]
Thank you
