### ISSUE TITLE
my device only work while it connect to see logs 

### ISSUE THREAD

**Issue by is10vmust** [transistorsoft/flutter_background_geolocation#381]
## Your Environment
* Plugin version: ^1.8.0
* Platform: huawei
* OS version: 9
* Device manufacturer / model: Huawei y6 prime 2018 

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
+    bg.TransistorAuthorizationToken token =
+        await bg.TransistorAuthorizationToken.findOrCreate(orgname, username);
+    bg.BackgroundGeolocation.ready(
+      bg.Config(
 transistorAuthorizationToken: token,
         disableStopDetection: true,
         pausesLocationUpdatesAutomatically: false,
        speedJumpFilter: 100,
        forceReloadOnBoot: true,
        forceReloadOnHeartbeat: true,
        triggerActivities: 'on_foot, walking, running, in_vehicle, on_bicycle',
        useSignificantChangesOnly: false,
        allowIdenticalLocations: true,
        forceReloadOnLocationChange: false,
        preventSuspend: true,
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 10, //1.0
        locationUpdateInterval: 5000,
        stopTimeout: 1,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        heartbeatInterval: 120,
),
```

## Expected Behavior
to send location of user each 2 min for long term (8 -14 days) without stop in all foreground , background and after kill app in still , walking ...etc .

## Actual Behavior
works fine in foreground , in after kill its take 7-12 min then it back good , while sliding the app down (background) it not works ever but when i connect the device to logcat its working , im confused why it not working while it not connected to computer ?

**Comment by christocracy** [comment]
Huawei are the *absolute* worst devices on earth for background-operation.  Their OS purposely kills services in violation of their Android Manufacturer license.
- See http://dontkillmyapp.com
- [This response from Android Engineering Team](https://www.reddit.com/r/androiddev/comments/hk3hrq/were_on_the_android_engineering_team_ask_us/fxg9y4f/) on a Reddit thread discussing poor behaviour of Chinese device manufacturers.
