### ISSUE TITLE
[Question] Unit for distance

### ISSUE THREAD

**Issue by waretec** [transistorsoft/flutter_background_geolocation#382]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Actual Behavior

Is there a way to change the distance from km to miles?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
If you're talking about `odometer`, that's measurement is in meters, not kilometers.

It's your responsibility to convert units as desired.  The plugin doesn't need to take this responsibility.
