### ISSUE TITLE
Returns a location more than 500 miles away from the current location.

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#383]
## Your Environment
* Plugin version:1.10.0
* Platform: iOS or Android:  (not sure I think iOS)
* OS version: Not sure
* Device manufacturer / model: Not sure
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
 
[✓] Connected device (1 available)            

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.getCurrentPosition(
        timeout: 30,
        samples: 3
      )
```

## Expected Behavior

Expecting to return best accuracy GPS location

## Actual Behavior

Returns more than 500 miles away location from the current location

## Steps to Reproduce

1.
2.
3.
4.

## Context

When user clicks on a particular button within the app, I call the getCurrentPoisition with the criteria mentioned without desiredAccuracy value. 
 
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
`getCurrentPosition` always uses highest possible accuracy.  The problem is your device or environment.

Try it outdoors (GPS is only available outdoors).

**Comment by kmusham** [comment]
Thank you @christocracy for confirming on default accuracy.

We're using the GPS to verify EVV(Electronic Visit Verification) for federal requirement. WE need to prove that the caregiver was at the patient location while providing the service.
Caregiver could be inside a building when they click on punch-in button. 

I also have a background location listener to keep the chipset hot. 
here is the configuration I was using - 
```
bg.BackgroundGeolocation.ready(bg.Config(
            locationAuthorizationRequest: 'WhenInUse',
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            heartbeatInterval: 60,
            showsBackgroundLocationIndicator: false,
            maxDaysToPersist: 1,
            stopOnTerminate: true,
            reset: true))

```
But, I use the location retuned by getCurrentPosition method. Listener is just to keep the chipset hot.

in any case, do you have any config recommendations for us to capture a best location for EVV? 

Thank you

**Comment by christocracy** [comment]
There's nothing more you can do.  `getCurrentPosition` returns the best possible location.

- When indoors, location will typically come from Wifi (accuracy ~40-100 meters).  Otherwise Cellular (~1000 meters accuracy).
- Go outside your home/office and test in a variety of buildings.

**Comment by christocracy** [comment]
Also, I moved recently --  it took weeks before Apple/Google updated their location database that my router's ip address exists at a new latitude/longitude.  While indoors with location coming from wifi, iOS / Android devices thought I was at my old location, ~1km away.

**Comment by kmusham** [comment]
Thanks again. In my example customer reported was more than 500 miles. 
That means, it was definitely not from GPS satellites or Wifi (~100 meters) or Cellular (~1000 meters). 

Do you think of any other sources other than above? I just wanted to provide steps to the customer and explain the issue.

**Comment by christocracy** [comment]
> Do you think of any other sources other than above?

No.  The plugin is only the messenger boy relaying locations as reported by the device’s location api.
