### ISSUE TITLE
Error ocurre during APK build

### ISSUE THREAD

**Issue by Davestring** [transistorsoft/flutter_background_geolocation#386]
Hi, I have bought the plugin to unlock android and I have the following problem. When I'm trying to build an apk with "flutter build apk" I have two errors:

resource android:attr/ttcIndex and resource android:attr/fontVariationSettings are not found. error: failed linking references.

I was using API Level 28 and as the android setup docs says I need to use "compileSdkVersion" 29 or higher so at the end of the build I have this error, I think the error is related to the compile and target sdk version because every solution that I have found refers to API 28 but if I use this API I'm unable to use the plugin.

At the end maybe because this error another one ocurred:

Could not determine the dependencies of task ':compileReleaseAidl'. SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties.

I have tried a lot of stuff but I can't get to the solution, thanks for your time and hope you can help.

Btw, I have checked my Android setup and I think I didn't miss a step.

## Your Environment
* Plugin version: ^1.10.0+1
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Nokia
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale es-MX)
    • Flutter version 1.20.2 at /Users/davidmartinez/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/davidmartinez/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • TA 1025 (mobile) • PLEGAR2770217092 • android-arm64 • Android 9 (API 28)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
      _logger.wtf('MapScreen - Heartbeat: $event');
    });

    bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        preventSuspend: true,
        heartbeatInterval: 60,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
The error ocurre only when I run "flutter run --release" or "flutter build apk", the apk should be build but and error ocurre

## Actual Behavior
An error ocurre during APK build

## Context
I'm only testing the plugin using the onHeartbeat function, I have try to configure it according to the android setup in the plugin documentation.

## Debug logs
<details>
	<summary>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clipboard_manager:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/.../Documents/.../.../build/clipboard_manager/intermediates/res/merged/release/values/values.xml:171: error: resource android:attr/fontVariationSettings not found.
  /Users/.../Documents/.../.../build/clipboard_manager/intermediates/res/merged/release/values/values.xml:172: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 5m 52s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     354.1s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin background_fetch...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.0s

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/.../.pub-cache/hosted/pub.dartlang.org/background_fetch-0.6.0/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin background_fetch could not be built due to the issue above.

</summary>
</details>

I leave my android config:

## gradle.properties

```gradle
org.gradle.jvmargs=-Xmx1536M
android.enableJetifier=true
android.useAndroidX=true
android.enableR8=false
```

## build.gradle

```gradle
buildscript {
    ext.kotlin_version = '1.3.0'
    ext {
        compileSdkVersion = 29
        targetSdkVersion = 29
        appCompatVersion = "1.0.2"
        playServicesLocationVersion = "17.0.0"
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

## app/build.gradle

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "..."
        minSdkVersion 21
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources false
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by Davestring** [comment]
I found the issue, it was another library that has problems with Android X, thank you for your time :)

**Comment by AmirunAzwar** [comment]
May I know how you solved it?
