### ISSUE TITLE
Distance between coordinates?

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#387]
## Your Environment
* Plugin version: 
1.10.0
* Platform: iOS or Android 
Both
* OS version:
All
* Device manufacturer / model:
All
* Flutter info (`flutter doctor`):
$: flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 1 category.
$: 

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Need a method to calculate distance between two coordinates. 

## Actual Behavior

No method available to use.

## Steps to Reproduce

1. get one-shot location
2. use a method to calculate distance between the captured one-shot fix to the lat, long values you already have  
3. Did not find a method to perform step 2
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin provides no method to calculate distance between points.

This is easy to calculate yourself, mathematically or using [a library](https://pub.dev/packages/latlong)
