### ISSUE TITLE
help - can I get distance Between coordinates in meters

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#388]
Can I by flutter_background_geolocation get a distance Between coordinates in meters, check if GPS is enabled and place mark From Coordinates as readable address !?

I have search but I can't find source for that !

thanks.

**Comment by christocracy** [comment]
Yes.

It's completely your responsibility to place coordinates on a map.  The plugin emits location via `onLocation` event.

Please read the API docs and learn all the available events.

**Comment by christocracy** [comment]
>From Coordinates as readable address

This plugin does not perform reverse-geocoding (to discover an address from lat/lng).  That's a task best performed on the server, not on the mobile client.
