### ISSUE TITLE
How to stop iOS local notification generation?

### ISSUE THREAD

**Issue by itqualitapps** [transistorsoft/flutter_background_geolocation#389]
Hi! 
We have purchased your licence recently and working on urgent location tracking application.

01. We have noticed that there's endless notifications are generating for iOS devices. Which is really disturbance for the user and Is there any way to stop this?
02. For iOS devices, background location working fine only for the location permission type `requestAlwaysAuthorization`. Doesn't it work for the other permission type `requestWhenInUseAuthorization` as well?

* Plugin version: ^1.9.3
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model:
* Flutter info (`flutter doctor`):

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F96, locale en-LK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)
```

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 1.0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

**Comment by christocracy** [comment]
>We have noticed that there's endless notifications are generating for iOS devices. Which is really disturbance for the user and Is there any way to stop this?

See API docs `Config.debug`

>For iOS devices, background location working fine only for the location permission type requestAlwaysAuthorization. Doesn't it work for the other permission type requestWhenInUseAuthorization as well?

Of course not.  There's a reason these two different location authorization mechanisms exist.  With `WhenInUse`, the user must engage location-tracking while the app is in the foreground with the method `BackgroundGeolocation.changePace(true)`.  LIke a jogging app where the user clicks a button `[Start Workout]`.
