### ISSUE TITLE
Please provide elevation gain and loss as well when user starts tracking!

### ISSUE THREAD

**Issue by AllenSmith11** [transistorsoft/flutter_background_geolocation#391]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Why can’t you calculate this yourself?

**Comment by AllenSmith11** [comment]
Hi thanks for the reply i am preety new to flutter so thats why i purchased the plugin to make things easy i have pulled altitude from location but not able to calculate elevation gain when user end the trip. Can you please help me out.

**Comment by christocracy** [comment]
Presumably you’d keep a running total.

**Comment by AllenSmith11** [comment]
Do plugin calculates this stuff internally? I havent seen any particular comment on altitude in location class. Any code snipet or any refrence would be really appriciated.

**Comment by christocracy** [comment]
The plugin does not track altitude. 

```dart
double altitude = 0;

bg.BackgroundGeolocation.onLocation((bg.Location location) {
  altitude += location.coords.altitude;
});
```

**Comment by christocracy** [comment]
(updated code snippet above).

**Comment by AllenSmith11** [comment]
Hello first of all thank you very much for reply. So altimiter is a elevation gain?

**Comment by ggever** [comment]
@AllenSmith11 Did you find out how to calculate. I want to do samething with you. Please share your knowledge if its possible.
Many thanks in advanced
