### ISSUE TITLE
app stop tracking after turn screen off in all type of phones

### ISSUE THREAD

**Issue by ammarmahafeza2** [transistorsoft/flutter_background_geolocation#392]
**_app stop tracking after turn screen off in all type of phones_**

## Your Environment
* Plugin version: ^1.80
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung A11
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
transistorAuthorizationToken: token,
       allowIdenticalLocations: false,
       forceReloadOnHeartbeat: true,
       triggerActivities:
          'still,on_foot, walking, running, in_vehicle, on_bicycle',
       desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      reset: true,
       debug: false,
       logLevel: bg.Config.LOG_LEVEL_VERBOSE,
       distanceFilter: 10.0,
       stopTimeout: 1,
       autoSync: true,
       stopOnTerminate: false,
       startOnBoot: true,
       enableHeadless: true,
       heartbeatInterval: 60,
```

## Expected Behavior

make app working after turn off the screen not matter if the app in foreground , background or after kill app
## Actual Behavior

after i turn the screen of device off the app stop working

**Comment by christocracy** [comment]
See http://dontkillmyapp.com.

I test almost daily on 11 Android devices:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by ammarmahafeza2** [comment]
i did all the following :  http://dontkillmyapp.com step 

and still while device turn screen off not working 

are there any issue in configuration that make app works while screen off ?

**Comment by christocracy** [comment]
See wiki *Debugging* and observe `adb logcat`

**Comment by Pescador76** [comment]
This is a real problem for this otherwise great plugin. It means that for most users the background function will only work reliably if some additional settings and tricks have been done before. Most users are overwhelmed by this. And this is exactly what the plugin is supposed to avoid. Isnt' it?

There are some workarounds for Java for manufacturer specific problems with background apps. Can't you implement something like that into the app?

See:
https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it
https://stackoverflow.com/questions/48166206/how-to-start-power-manager-of-all-android-manufactures-to-enable-background-and

**Comment by christocracy** [comment]
See api docs [DeviceSettings](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/DeviceSettings-class.html)

**Comment by Pescador76** [comment]
Okay, but as a developer you are still pretty much on your own.

I mean this:
// It's your responsibility to instruct the user what exactly
    // to do here, perhaps with a Confirm Dialog:

and
 // Depending on Manufacturer/Model/OS Version, a Device may not implement
 // a particular Settings screen.

It would be good, if all this was already implementd in the plugin (or example codes), i.e. a recognition, which device is used by user and which settings have to be done and the corresponding dialogs. How am I supposed to do this for each device by myself? Impossible for a single developer.
