### ISSUE TITLE
Track"spikes" after onChangePace() change from stationary to moving

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#393]
## Your Environment
* Plugin version: 1.10.0+1
* Platform:  Android
* OS version: 10
* Device manufacturer / model: XIAOMI MI 9T
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-GB)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.48.2)
[√] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            notification: bg.Notification(smallIcon: "drawable/notificationicon", largeIcon: "mipmap-xxxhdpi/notificationicon"),
            // Logging & Debug
            reset: true,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH, 
           distanceFilter: 3.0,
            stopTimeout: 1,
            // HTTP & Persistence
            autoSync: false,
            // Application options
            stopOnTerminate: false,
            locationAuthorizationRequest: "WhenInUse",
            heartbeatInterval: 60))
```

## Expected Behavior
The user can pause the tracking and back from the exact point where it was without the "spikes" (like a little seismograph graph).

## Actual Behavior
If I press the "pause" button (that call the onChangePace) i frequently got track "spikes" that adds "dirt" to the registered track.

Below a image from the BackgroundGeolocation app:

[Screenshot](https://drive.google.com/file/d/1kXM0MacwVg0rOkdHmteen4CURIG7_Jo7/view?usp=sharing)

The Green arrow is the point where I was. The Red arrow is where I started and the Black arrow is to where the current position moved and then back to the Green arrow position drawing this straight line between the Green and Black arrows.

## Context
Register the path taken, eventually to pause and then back to the track keeping the line regular as possible.

**Comment by christocracy** [comment]
You cannot expect perfect data.  There will be anomalies.

**Comment by leonardoayres** [comment]
Ok, I understand that.

But I can not reproduce this kind of behaviour using another tracking apps like Mi Fit, for example (and in other tracking apps). There is some type of configuration that can be done to minimize this kind of behavior?

**Comment by christocracy** [comment]
You're expected to filter data as desired.  If you don't like a particular location (eg: `location.coords.accuracy`), don't render it to your map.

**Comment by leonardoayres** [comment]
I see, but what's the criteria to validate a location based only on the accuracy?

It is a single value in meters that, in my case, even without any teleport (spike) shown a variation between 3.9 and 14 (with the track line ok).

I got a spike on a test and went to see the logs, and it says something like: "Identified a teleport..." and said that the location were ignored, but is entered on the location list of the method "onLocation". How can I identify the teleport cases (spikes) to ignore the coords and not draw them? 

By the way, the onLocation method is the best place to draw the polylines or the onMotionChange would be better?
