### ISSUE TITLE
Notification keep showing every time the event happened

### ISSUE THREAD

**Issue by peternguyenxq** [transistorsoft/flutter_background_geolocation#394]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

 are there ways to stop showing notification on iOS and Android?

```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Read api docs `Config.debug`
