### ISSUE TITLE
[Q] Closing notification drawer after action click

### ISSUE THREAD

**Issue by Max-Might** [transistorsoft/flutter_background_geolocation#395]
Hello.

I use a foreground service with a custom layout and a single action button.
I configured is as described in the wiki and it works as intended.
The problem is that when I click on the action button my dart callback is executed but the notification drawer is still opened.

Question: is it possible to close the notification drawer when an action button is clicked like it happens when you click somewhere else on the notification?

**Comment by christocracy** [comment]
Congratulations, few people seem to have the guts to try out a custom layout.  I was just thinking about this today.

Show me a screenshot of what you’re talking about.  I haven’t touched this part of the sdk in a long time.

**Comment by Max-Might** [comment]
The layout is very similar to the one in the wiki.
The issue is that when I tap on the action button the callback is called but the whole notification bar does not close.
Usually when the user clicks a button on a notification they expect the notification bar to be closed and the application is brought to the foreground so that they can interact with it.
I see this happens when you click anywhere else on the notification but not on the action button.

**Comment by Max-Might** [comment]
I tried to launch the following intent when the action button on the notification is clicked:

```dart
final intent = const AndroidIntent(
  action: 'FLUTTER_NOTIFICATION_CLICK',
  category: 'android.intent.category.DEFAULT',
);
intent.launch();
```

The idea is that this will call the same code that is called when a notification is clicked and it will close the notification drawer and bring the application to the foreground. But it does not work.

**Comment by christocracy** [comment]
>I see this happens when you click anywhere else on the notification but not on the action button.

Shouldn't be difficult.  I'll look into it today.

**Comment by Max-Might** [comment]
I managed to do it by calling this to bring the application to the foreground:
```dart
final intent = const AndroidIntent(
              action: 'android.intent.action.MAIN',
              category: 'android.intent.category.LAUNCHER',
              package: 'name.of.the.package',
              componentName: 'name.of.the.package.MainActivity',
              flags: <int>[
                Flag.FLAG_ACTIVITY_CLEAR_TOP,
                Flag.FLAG_ACTIVITY_SINGLE_TOP,
              ],
            );
```

And then calling this on the native side to close the notification tray:
```kotlin
val intent = Intent(android.content.Intent.ACTION_CLOSE_SYSTEM_DIALOGS)
this@MainActivity.sendBroadcast(intent)
```

The second part can be moved to the dart side once the `android_intent` plugin supports sending broadcasts.

**Comment by christocracy** [comment]
Here's how the SDK's Android code configures the`Intent` for notification click to bring app to foreground.

- Your `flags` look weird.

```java
Intent launchIntent     = pm.getLaunchIntentForPackage(context.getPackageName());
if (launchIntent != null) {
    launchIntent.setAction(Intent.ACTION_MAIN);
    launchIntent.addCategory(Intent.CATEGORY_LAUNCHER);
    launchIntent.setPackage(null);  // <------ In my experience this is VERY important.
    launchIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT);
    context.startActivity(launchIntent);
}
```

**Comment by Max-Might** [comment]
I think these flags make sense.

According to the official documentation:
`FLAG_ACTIVITY_SINGLE_TOP` - If set, the activity will not be launched if it is already running at the top of the history stack.
`Flag.FLAG_ACTIVITY_CLEAR_TOP ` - If set, and the activity being launched is already running in the current task, then instead of launching a new instance of that activity, all of the other activities on top of it will be closed and this Intent will be delivered to the (now on top) old activity as a new Intent. (maybe this is to needed in my case since flutter apps have only 1 native activity usually)

`FLAG_ACTIVITY_BROUGHT_TO_FRONT` - This flag is not normally set by application code, but set for you by the system as described in the launchMode documentation for the singleTask mode. (so this is not meant to be set by the user)
`FLAG_ACTIVITY_NEW_TASK` - If set, this activity will become the start of a new task on this history stack. (I think we do not want to make a new stack on the history list)

So yeah, android activity flags are weird :)

**Comment by christocracy** [comment]
Test your Intent in a variety of situations, including from the terminated state if you're using `enableHeadless: true` and you've registered a headless-task.

I've honed this `Intent` over several years after problems where the `Activity` is re-launched on notification-click, even though the `Activity` is already currently running.

**Comment by christocracy** [comment]
> fueled by black magic and sorcery :)

Exactly.

**Comment by asadaltaf583** [comment]
I am developing a screen recorder application with screenshot feature. On notification bar button click notification drawer must be closed. I am failed to achieve this by close system dialogs and starting a new activity.

**Comment by asadaltaf583** [comment]
@christocracy  your solution is not working in android 13
