### ISSUE TITLE
reduce the frequency of the onLocation event

### ISSUE THREAD

**Issue by fehernyul** [transistorsoft/flutter_background_geolocation#396]
## Your Environment
* Plugin version: ^1.10.0+1
* Platform: Android
* OS version: 8 / 10
* Device manufacturer / model: Samsung S7 / Emulator
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.Config _config = bg.Config(
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,

      // Geolocation options
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      disableStopDetection: true, // never stop pingign / sending
      pausesLocationUpdatesAutomatically: false, 
      
      distanceFilter: 10.0, 
      elasticityMultiplier: 1.0,

      stopTimeout: 5, 
      geofenceProximityRadius: 1000,

      // HTTP & Persistence
      autoSync: true,
      activityRecognitionInterval: 20000, 

      // Application options
      enableHeadless: true,
      foregroundService: true,
      heartbeatInterval: 60,
      startOnBoot: true,
      stopOnTerminate: false,
    );

```

## Expected Behavior
I want to ping / executes the onLocation / onHttp event not 10-20x in a minute, but 2-3. How can I configure that?

## Actual Behavior
The plugin executes the onLocation event about 10-20 times in a minute. (see attached picture)
![image](https://user-images.githubusercontent.com/25593792/92934510-dca6dd80-f447-11ea-96e8-e0c989d94146.png)

I queried this from my stored database table group by minutes.

## Steps to Reproduce

1. Install the app with the attached Config settings.
2. Put your phone to the table
3. Go dinner
4. When you come home, query the number of records group by minutes

## Context
I need that behaviour, the app is sending the GPS coords all the time, endlessly, forever .... But not 20x in a minute, but 2x.
When travelling with 100 km/h speed, or waiting in traffic lights, or packing up / down the transportable stuffs (it is maybe 1-2 hours long). All the time, send me a GPS coord in every half minute.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```dart
distanceFilter: 10.0,   // <-- this is very aggressive tracking.  Increase it.
elasticityMultiplier: 1.0,
```
