### ISSUE TITLE
autoSyncThreshold question

### ISSUE THREAD

**Issue by dirjud** [transistorsoft/flutter_background_geolocation#398]
## Your Environment
* Plugin version: 81e589e
* Platform: both
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`): N/A
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1.0,
      stopOnTerminate: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      startOnBoot: false,
      debug: false,
      locationAuthorizationRequest: "WhenInUse",
      reset: true,
      heartbeatInterval: 60,
      //preventSuspend: true, // removed because "WhenInUse" renders this useless
      isMoving: true,
      stopAfterElapsedMinutes: 60 * 10,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      activityType: bg.Config.ACTIVITY_TYPE_OTHER_NAVIGATION,
      // don't jump to roads
      foregroundService: true,
      // android only
      notification: bg.Notification(
          // android only
          title: "OYO",
          text: "Tracking your race"),

      url: RPC.server + "/rest/result/Points/insert",
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      maxBatchSize: 50,
      params: {
        "user_id": _user["id"],
        "participant_id": _participantId,
        "dev_id": _deviceId,
      },
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,
    )).then((bg.State state) {
      print("STATE: " + state.toString());
      if (!state.enabled) {
        print("STARTING");
        bg.BackgroundGeolocation.start();
      }
    });

```

## Expected Behavior

Not sure.

## Actual Behavior

I am tracking people while running a race. I have set the autoSyncThreshold to 5, but the server usually get 1 point per transaction. Occassionally it gets 2, and rarely it gets 5 or more. I see in the documentation that the onMotionChange event can trigger an upload event, so would that be triggered continuously while a person is running? We're setting the isMoving to true and only running the plugin for the duration of their run. I want strict observance of the autoSyncThreshold and only upload when threshold is reached. Is there a way to force that?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>I want strict observance of the autoSyncThreshold and only upload when threshold is reached. Is there a way to force that?

Once the runner begins running, *after* the `onMotionChange` event fires, the plugin will collect `authSyncThreshold` records before initiating an upload.
