### ISSUE TITLE
The radius of the location in the building on iOS for most users is 65 meters

### ISSUE THREAD

**Issue by Holofox** [transistorsoft/flutter_background_geolocation#399]
##  Environment
* Plugin version: 1.10.0+1
* Platform: iOS
* OS version: 13.0-14.0
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale ru-RU)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
```
* Plugin config:
```dart
Config(
  desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
  locationAuthorizationRequest: 'Any',
  showsBackgroundLocationIndicator: true,
  disableLocationAuthorizationAlert: true,
  debug: false,
  logLevel: Config.PERSIST_MODE_ALL,
  allowIdenticalLocations: true,
  disableMotionActivityUpdates: true,
);
```

## Expected Behavior
When the user is in a building, the radius of the location should be different depending on the building, coverage, signal reflections, and other factors.

## Actual Behavior
When the user is in the building, the radius of the location on iOS devices for more users is 65 meters. 

This value will always be constant as long as I am in a certain building. If I go outside the radius will change. By the way, two devices in one building have the same radius.

## Questions
1. Why does this behavior occur and how to explain it? 
2. Why is the radius of the circle exactly 65 meters only on iOS devices?

**Comment by christocracy** [comment]
This is correct.  GPS doesn't work indoors.  While indoors, iOS / Android devices use *WiFi location provider*.

*WiFi* location provider accuracy is typically 60-100 meters accuracy.
