### ISSUE TITLE
Using the "git" scheme in the pubspec GitHub repository URL results in an error

### ISSUE THREAD

**Issue by tpberntsen** [transistorsoft/flutter_background_geolocation#4]
Hi Chris,

I think the scheme part of the URL mentioned in the manual in the section https://github.com/transistorsoft/flutter_background_geolocation#or-latest-from-git might need to be changed from "git" to "https".

Defining the dependency as: 

```
flutter_background_geolocation:
    git:
      url: git://github.com/transistorsoft/flutter_background_geolocation
```

...results in:

```
Git error. Command: git fetch
fatal: unable to access 'https://github.com/flutter/flutter.git/': Couldn't connect to server
```

Changing the url to `https://github.com/transistorsoft/flutter_background_geolocation` fixes the problem.

Best,
Thomas

**Comment by christocracy** [comment]
Docs [are live](https://pub.dartlang.org/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation-class.html)

**Comment by christocracy** [comment]
Also note:  some `getXXX` methods have been changed to `get`ters.
- `getGeofences` -> `geofences`
- `getCount` -> `count`
- `getLocations` -> `locations`
- `getState` -> `state`
- `getLog` -> `log`

**Comment by christocracy** [comment]
README updated.
