### ISSUE TITLE
Not working in android while app in killed state.

### ISSUE THREAD

**Issue by DK024-Dev** [transistorsoft/flutter_background_geolocation#402]
## Your Environment
* Plugin version: ^1.10.0+1
* Platform:Android
* OS version:  minSdkVersion 21 to targetSdkVersion 29
* Device manufacturer / model: Android emulator
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

Future backgroundGeolocationHeadlessTask(HeadlessEvent headlessEvent) async {
  final currentLocation = await BackgroundGeolocation.getCurrentPosition();
  _onLocation(currentLocation);
  switch (headlessEvent.name) {
    case Event.GEOFENCE:
      final GeofenceEvent geofenceEvent = headlessEvent.event;
      logger.d('Local $geofenceEvent');
      break;
    case Event.GEOFENCESCHANGE:
      final GeofencesChangeEvent event = headlessEvent.event;
      logger.d(event);
      break;
    case Event.SCHEDULE:
      final state = headlessEvent.event;
      logger.d(state);
      break;
  }
}
```

## Steps to Reproduce

1. when app in killed state

## Context

Fetch location of current device while moving and fire local notification

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
D/TSLocationManager(10077): [c.t.f.b.HeadlessTask onHeadlessEvent] 💀 [HeadlessTask heartbeat]
E/flutter (10077): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'MissingPluginException' is not a subtype of type 'PlatformException'
E/flutter (10077): #0      BackgroundGeolocation.getCurrentPosition.<anonymous closure> 
package:flutter_background_geolocation/models/background_geolocation.dart:497
E/flutter (10077): #1      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (10077): #2      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (10077): #3      _FutureListener.handleError  (dart:async/future_impl.dart:160:20)
E/flutter (10077): #4      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:708:47)
E/flutter (10077): #5      Future._propagateToListeners  (dart:async/future_impl.dart:729:24)
E/flutter (10077): #6      Future._completeError  (dart:async/future_impl.dart:537:5)
E/flutter (10077): #7      _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:47:15)

```

</details>

**Comment by christocracy** [comment]
show me your `import` statement for `flutter_background_geolocation`.

**Comment by DK024-Dev** [comment]
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart';

I also tried the : import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;
Still not working.

**Comment by christocracy** [comment]
Change to this:
```
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg
```
Prefix all instances of `BackgroundGeolocation` classes with `bg.`

**Comment by DK024-Dev** [comment]
@christocracy I will update that but still i have phase that issue. In previous phase i had testing. its not work for me.

**Comment by christocracy** [comment]
Once you've updated your code, post your changes here once again.

**Comment by DK024-Dev** [comment]
`import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;`

` Future backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  final Location currentLocation =
      await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  _onLocation(currentLocation);
  switch (headlessEvent.name) {
    case bg.Event.GEOFENCE:
      final bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      logger.d('Local $geofenceEvent');
      break;
    case bg.Event.GEOFENCESCHANGE:
      final bg.GeofencesChangeEvent event = headlessEvent.event;
      logger.d(event);
      break;
    case bg.Event.SCHEDULE:
      final bg.State state = headlessEvent.event;
      logger.d(state);
      break;
  }
}   `


Log:

`  D/TSLocationManager(10077): [c.t.f.b.HeadlessTask onHeadlessEvent] 💀 [HeadlessTask heartbeat]
E/flutter (10077): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'MissingPluginException' is not a subtype of type 'PlatformException'
E/flutter (10077): #0      BackgroundGeolocation.getCurrentPosition.<anonymous closure> 
package:flutter_background_geolocation/models/background_geolocation.dart:497
E/flutter (10077): #1      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (10077): #2      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (10077): #3      _FutureListener.handleError  (dart:async/future_impl.dart:160:20)
E/flutter (10077): #4      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:708:47)
E/flutter (10077): #5      Future._propagateToListeners  (dart:async/future_impl.dart:729:24)
E/flutter (10077): #6      Future._completeError  (dart:async/future_impl.dart:537:5)
E/flutter (10077): #7      _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:47:15)    `

**Comment by christocracy** [comment]
Did you try the /example app?

**Comment by gauravparvadiya** [comment]
Hello @christocracy,

I am on the same team. We did try with example application and found a similar issue.

**Comment by DK024-Dev** [comment]
Yes @christocracy  I tried your example to i got same exception in killed mode in android rest of work fine.

**Comment by chandaniBhalala** [comment]
Hello @christocracy 

If we are using `flutterEmbedding` then it's getting current location in kill mode but without flutterEmbedding we can't get current location in kill mode. flutterEmbedding is conflict with my other functionality so i can't use flutterEmbedding.

**Comment by gauravparvadiya** [comment]
@christocracy Please help. Our app is in production and it's a very critical issue for us.

**Comment by gauravparvadiya** [comment]
@christocracy Anything on this problem?

**Comment by christocracy** [comment]
`FlutterEmbedding` is required.
