### ISSUE TITLE
not able to detect idleness in location

### ISSUE THREAD

**Issue by MA171** [transistorsoft/flutter_background_geolocation#405]
## Your Environment
* Plugin version: 1.9.0
* Platform: Both
* OS version: -
* Device manufacturer / model: -
* Flutter info (`flutter doctor`):
* Plugin config:
## Expected Behavior
To execute an event when idleness detected (location haven't changed or haven't received for X seconds for example)

## Context
If in the configuration I configured distanceFilter to be X, the device will receive a new location every X meter change
is there any way to listen if there's no location received in the next Y seconds (the user haven't completed a X meter distance) and execute a function ?

**Comment by christocracy** [comment]
Have you read the Wiki *Philosophy of Operation*?
