### ISSUE TITLE
Gradle task assembleDebug failed

### ISSUE THREAD

**Issue by Sami-Annanovas** [transistorsoft/flutter_background_geolocation#408]
* What went wrong:
Execution failed for task ':background_fetch:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /Users/sami/Documents/FlutterDevelopement/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.4/android/libs/tsbackgroundfetch-0.4.2.aar

**Comment by christocracy** [comment]
- Ignored issue template.
- Search issues **before posting**.
- Duplicate #283
