### ISSUE TITLE
requestPermission is missing on the dart side

### ISSUE THREAD

**Issue by joserocha3** [transistorsoft/flutter_background_geolocation#41]
* Plugin version: flutter_background_geolocation: ^1.0.0-beta.5
* Platform: iOS
* OS version: 12.1
* Device manufacturer / model: iPhone X Simulator
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

## Expected Behavior
Method `requestPermission` is available.

## Actual Behavior
Method `requestPermission` is **not** available.

## Context
Trying to use method `requestPermission`. I see it implemented on the native side, however it is not exposed to the dart side. I want to call it because I do not want to start tracking yet, just request permission.

**Comment by christocracy** [comment]
I’ll have a look.  You can also force a permission request simply by requesting #getCurrentPosition (set {persist: false, samples: 1} in options.

**Comment by joserocha3** [comment]
Hi @christocracy, while you fix that issue maybe you can tackle `destroyLogs`. It is missing a connection to the native code.

```
flutter: [destroyLog] ERROR: MissingPluginException(No implementation found for method destroyLog on channel com.transistorsoft/flutter_background_geolocation/methods)
```

**Comment by christocracy** [comment]
Will do.

**Comment by christocracy** [comment]
Missing on iOS-only.

Done.
```obj-c
- (void) destroyLog:(FlutterResult)result {
    BOOL success = [_locationManager destroyLog];
    if (success) {
        result(@(YES));
    } else {
        result([FlutterError errorWithCode:@"UNKNOWN_ERROR" message:nil details:nil]);
    }
}

```

**Comment by joserocha3** [comment]
check pull request #44 for `#requestPermission`

**Comment by joserocha3** [comment]
This is implemented in latest release.
