### ISSUE TITLE
Does heartbeat event work in background on iOS?

### ISSUE THREAD

**Issue by jbojcic1** [transistorsoft/flutter_background_geolocation#410]
## Your Environment
* Plugin version: 1.9.3
* Platform: iOS
* OS version: -
* Device manufacturer / model: -
* Flutter info (`flutter doctor`): -
* Plugin config: -

I am trying to figure out the best way to send the current location to the remote service when the device is stationary every X time that would work in the background.  I've read the [Philosophy of Operation](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation#ios-heartbeat-event) and it says for iOS:

> iOS heartbeat Event
While in the #preventSuspend mode in the stationary state, the plugin is able to fire a heartbeat event periodically (#heartbeatInterval). The heartbeat event will fire your Javascript callback:

while in the Flutter code preventSuspend comment I see:

>   /// __`[iOS only]`__ Prevent iOS from suspending your application in the background after location-services have been switched off.
  ///
  /// Defaults to **`false`**.  Set **`true`** to prevent **iOS** from suspending your application after location-services have been switched off while running in the background.  Must be used in conjunction with a [heartbeatInterval].
  ///
  ///  **Note:** When a device is unplugged form power with the screen off, iOS will *still* throttle [BackgroundGeolocation.onHeartbeat] events about 2 minutes after entering the background state.  However, if the screen is lit up or even the *slightest* device-motion is detected, [BackgroundGeolocation.onHeartbeat] events will immediately resume.
  ///
  ///  **WARNING:** **`preventSuspend: true`** should **only** be used in **very** specific use-cases and should typically **not** be used as it *will* have a **very noticeable impact on battery performance.**  You should carefully manage **`preventSuspend`**, engaging it for controlled periods-of-time.  You should **not** expect to run your app in this mode 24 hours / day, 7 days-a-week.
  ///
  /// ## Example
  ///
  /// ```dart
  /// BackgroundGeolocation.onHeartbeat((HeartbeatEvent event) {
  ///   print('[onHeartbeat] ${event}');
  /// });
  ///
  /// BackgroundGeolocation.ready(Config(
  ///   preventSuspend: true,
  ///   heartbeatInterval: 60
  /// ));
  /// ```
  ///
  bool preventSuspend;

Also in one of the GitHub discussions, I saw [this](https://github.com/transistorsoft/flutter_background_geolocation/issues/400#issuecomment-691996280)

So now I am confused. Should the heartbeat work on iOS in the background in combination with preventSuspend, or will it be throttled or it won't work at all?

**Comment by christocracy** [comment]
When a device is unplugged form power with the screen off, iOS will still throttle `onHeartbeat` events about 2 minutes after entering the background state. However, if the screen is lit up or even the slightest device-motion is detected, [BackgroundGeolocation.onHeartbeat] events will immediately resume.

**Comment by jbojcic1** [comment]
Sorry I don't want to be rude but that's obviously not clear enough to me or I wouldn't be asking a question. 

What does it mean "will still throttle"? How often it will fire "When a device is unplugged from power with the screen off" if I set interval to one minute for example?

**Comment by jbojcic1** [comment]
This is how I understand it.

If I set preventSuspend to true, heartbeatInterval to 1 minute and onHeartbeat callback. If I am unplugged, stationary and screen is on, the callback will be invoked every minute. Once I turn my screen off, the callback will still be run every heartbeatInterval for the next two minutes. After those two minutes it will start to throttle the calls to the callback, which means it will run it every X time instead of my heartbeatInterval (if X < heartbeatInterval I provided). Once I turn screen on again it will again call it every heartbeatInterval.

If this is correct at all, my question is what is X?

**Comment by christocracy** [comment]
The iOS **strongly** desires to conserve energy.  With the device sitting completely stationary and unplugged from power, the operating system throttles your application's request for CPU time.

If the device is shaken a bit (eg: user picks up phone, puts in pocket and starts walking), the OS will un-throttle your app's requests for CPU time and heartbeat events will resume.

**Comment by christocracy** [comment]
I advise you to *avoid* using `preventSuspend: true` on iOS.  It's not required by 99% of use-cases.  It's a flakey hack of mine and consumes a lot of battery power.

**Comment by jbojcic1** [comment]
We need it for fleet tracking to know where the vehicle is even when stationary and app is in the background. In that case I guess our backend service will just need to interpret the lack of new locations as being stationary on the last location. 

Thx for the help

**Comment by christocracy** [comment]
>will just need to interpret the lack of new locations as being stationary on the last location.

That is a perfectly valid assumption.  If the iOS moves about 200 meters (a mere 2 city blocks), the plugin will *automatically* come alive and resume tracking, **without requiring `preventSuspend: true`**.

**Comment by MilesAdamson** [comment]
I have a similar use case where I would like the device to do a simple check-in, with heartbeat. As of my previous issue I opened, it's working on Android when app is killed and tracking is on, heartbeat method fires every couple minutes.

On iOS on the same branch, I am finding that the heartbeat is not firing when the phone is stationary, app killed, tracking on. I have tried turning the screen on, and moving the phone a bit (but not so much to move outside the stationary radius). Neither the heartbeat sounds plays, nor do any requests hit my server. I don't think heartbeat is firing when the app is killed on iOS for me.

I have also read the docs and am unsure what else I can do other than prevent suspend and ensure the background modes all all enabled.

I could open a separate issue if you prefer

**Comment by christocracy** [comment]
@MilesAdamson read [comment above](https://github.com/transistorsoft/flutter_background_geolocation/issues/410#issuecomment-698941751)

Do you understand what that means?

**Comment by MilesAdamson** [comment]
I do understand that comment, but it is not what I am observing. I turn on the screen, move the device around, and it has been plugged in the whole time. Heartbeats are not immediately resuming until I open the app again.

**Comment by christocracy** [comment]
> I am finding that the heartbeat is not firing when the phone is stationary, app killed, 

iOS has no such thing as "background-services", like Android, that are able to continue living after the app is terminated.

When you terminate an iOS app **EVERYTHING** terminates, including the *heartbeat*.

**Comment by MilesAdamson** [comment]
Ok there we go, that's what I needed to know. Very few people are going to know the native layers as well as you do, I sure don't. I think adding that to the docs around heartbeat or prevent suspend would be very helpful. 

Would it be possible to schedule background fetch's with your other plugin to active a "check-in" kind of feature, **with the app killed?**

**Comment by christocracy** [comment]
iOS halts `background-fetch` events when the *user* terminates the app.

**Comment by MilesAdamson** [comment]
Ok, thank you for your help
