### ISSUE TITLE
App Stop tracking , Hihg CPU , High consumption Battery

### ISSUE THREAD

**Issue by MonsterDKing** [transistorsoft/flutter_background_geolocation#412]
## Flutter doctor
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale es-419)
    • Flutter version 1.20.3 at /Users/monsterdking/development/flutter
    • Framework revision 216dee60c0 (hace 4 semanas), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/monsterdking/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

* Plugin version:   flutter_background_geolocation: ^1.10.0+1
* Platform: iOS And Android 
* OS version: 11
* Device manufacturer / model: All
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        preventSuspend: true,
        heartbeatInterval: 60,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Actual Behavior

High CPU consumption,
High battery consumption,
device stops tracking when screen is locked.

## Steps to Reproduce

1. Open the app
2 turn screen off 
3. The app Stop tracking
4. after a while the application sends a message of high CPU consumption and high battery consumption
<img width="525" alt="error1" src="https://user-images.githubusercontent.com/6463552/94644292-7c6cc400-02ae-11eb-8ba7-e3f3e8251687.png">
<img width="481" alt="error2" src="https://user-images.githubusercontent.com/6463552/94644295-7d055a80-02ae-11eb-9b2e-f9b03246d79b.png">

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
D/TSLocationManager( 9226): [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
D/TSLocationManager( 9226): [c.t.l.l.TSLocationManager onLocationResult]
D/TSLocationManager( 9226): ╔═════════════════════════════════════════════
D/TSLocationManager( 9226): ║ Process LocationResult
D/TSLocationManager( 9226): ╠═════════════════════════════════════════════
D/TSLocationManager( 9226): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 20.0
I/TSLocationManager( 9226): [c.t.l.data.sqlite.b persist]
I/TSLocationManager( 9226):   ✅  INSERT: fa196270-0e51-4ab9-898b-7bbde21f75d9
I/flutter ( 9226): 💡  TripRepository - updateLocation - Success - 127 - {driver_id: 127, unit_number: 900017, date: 2020-09-01 13:45:38.447008, grades: 0, pos: Instance of 'GeoPoint', status: 0, name: Quiality Assurance, current_journey: 2103}
D/TSLocationManager( 9226): [c.t.l.service.AbstractService a]
D/TSLocationManager( 9226):   🎾  TrackingService [eventCount: 1]
D/TSLocationManager( 9226): [c.t.l.service.TrackingService b]
D/TSLocationManager( 9226): ╔═════════════════════════════════════════════
D/TSLocationManager( 9226): ║ TrackingService: LocationResult
D/TSLocationManager( 9226): ╠═════════════════════════════════════════════
D/TSLocationManager( 9226): ╟─ 📍  Location[fused 19.702820,-101.191949 hAcc=20 et=+2h39m3s924ms alt=0.0 vel=8.040726 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 19ms, time: 1601441685000
```

</details>

**Comment by christocracy** [comment]
1.  `distanceFilter: 1.0`:  this is incredibly aggressive.
2.  For iOS `preventSuspend` docs warn that this will consume more much more energy.  99% of use-cases do **not** require `preventSuspend: true`.
3. You've provided no log information.  You should observe the raw `$ adb logcat` and provide applicable logs you find there while reproducing your issue.
4.  I've never seen this on any of my 11 Android devices (or iOS devices) running the *Sample App*.
5.  HTTP requests consume far more energy / second than location-services (eg: GPS).  The problem is likely in your own application code.

*Pixel 3a @ 11*
- *Apps are running normally.  Phone has typical background battery usage*.
![](https://dl.dropbox.com/s/rxzc89gxw3eppep/Screen%20Shot%202020-09-30%20at%209.03.35%20AM.png?dl=1)

*iPhone 11 Pro @ 14.0.1* 
- last 10 days Battery Usage
- Running 3 versions of the SampleApp for *React Native*, *Cordova* and *Flutter*.
- The SampleApps consume less energy than the national Covid Alert app (*Exposure Notifications*)
![](https://www.dropbox.com/s/o46shm8096vgmm6/Screen%20Shot%202020-09-30%20at%209.01.32%20AM.png?dl=1)
