### ISSUE TITLE
[question] Should heartbeat events fire when the app is killed, and tracking is on?

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#414]
Below is your issue template. I am trying to figure out if I have made a configuration/setup error for my heartbeat event, or if I am misunderstanding how it works.

Goal: Have my heartbeat event handler fired when the app is killed, with tracking is on. I followed the most recent version of the android setup guide.

## Your Environment
* Plugin version: 1.10.1
* Platform: Android
* Device manufacturer / model: Huawei p20 pro
* Flutter info (`flutter doctor`):
```
[√] Flutter (Channel unknown, v1.17.2, on Microsoft Windows [Version 10.0.19041.508], locale en-CA)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.49.2)
[√] Connected device (3 available)
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return gps.Config(
        extras: await buildExtrasMap(),
        // must be at least 60 seconds
        heartbeatInterval: HEARTBEAT_INTERVAL_SECONDS,
        // `preventSuspend = true` is required for heartbeat on ios
        preventSuspend: true,
        url: "${Application.apiBaseUrl(subDomain)}/units/$unitId/location",
        authorization: buildAuthorization(accessToken, refreshToken, subDomain),
        desiredAccuracy: gps.Config.DESIRED_ACCURACY_HIGH,
        // meters travelled to move to take a reading
        distanceFilter: 25.0,
        // saves battery
        allowIdenticalLocations: false,
        // run in background
        stopOnTerminate: false,
        // Location-services **will never turn OFF** if you set this to **`true`**!
        disableStopDetection: true,
        // resume tracking after device is rebooted
        startOnBoot: true,
        // [iOS only] Configure iOS location API to *never* automatically turn off.
        pausesLocationUpdatesAutomatically: false,
        // when the plugin gives up and removes the location from the database.
        maxDaysToPersist: 1,
        // Maximum number of records to persist in plugin's SQLite database.
        maxRecordsToPersist: 3,
        // Allow an array of locations to be sent in a batch,
        // if they lose cellular and things can't be sent for some time
        batchSync: true,
        // [stationaryRadius - iOS only] The minimum distance the device must move beyond
        // the stationary location for aggressive background-tracking to engage.
        // Configuring stationaryRadius: 0 has NO EFFECT. In fact the plugin
        // enforces a minimum stationaryRadius of 25 and in-practice,
        // the native API won't respond for at least 200 meters.
        stationaryRadius: 25.0,
        // debug: true will make obnoxious beeping noises
        debug: false,
        // useSignificantChangesOnly: true will provide
        // "significant power-saving at the expense of fewer recorded locations."
        useSignificantChangesOnly: false,
        // autoSync: send readings to server if the user lost internet
        // automatically when they get internet again
        autoSync: true,
        logLevel: gps.Config.LOG_LEVEL_ERROR,
        // reset: force a new config when app opens again with gps still running
        reset: true,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Set Location to "Always"',
          'titleWhenOff': 'Set Location to "Always"',
          'instructions':
              'Your phone\'s location is required to be set to "Always" while you\'re logged in. \n\n Tap update to go to your settings and change the Location to "Always"',
          'cancelButton': 'Cancel',
          'settingsButton': 'Update'
        });
```

## Expected Behavior

Heartbeat events continue to fire after the app is killed

## Actual Behavior

Heartbeat events fire when the app is running, screen is off. When I kill the app, they stop. If I open the app again, they resume.

## Context

I would like to send a simple update to my server in the heartbeat event handler, just to keep tabs on users

</details>

**Comment by christocracy** [comment]
Heartbeat fires *only* when the plugin is in the *stationary* state.

**Comment by MilesAdamson** [comment]
Can you define stationary or link me some relevant docs please?

And/or, suggest an alternative for using heartbeat here?

**Comment by christocracy** [comment]
See the wiki *Philosophy of Operation*.

Heartbeat is pointless in the *moving* state.  Your app is completely alive in the background and emitting locations to you each `distanceFilter` meters.

**Comment by MilesAdamson** [comment]
I don't believe my app is in a moving state, because it is perfectly still on my desk. Based on the philosophy operation, it sounds like what I am trying to do should work (a simple check-in when the phone is stationary from within heartbeat).

>While in the stationary state, since Android does not completely suspend apps in the background, the plugin is able to fire a heartbeat event periodically (#heartbeatInterval).  

Steps I am taking:
1. Turn on tracking. Phone is still on my desk. I can observe that heartbeat events are firing
2. Kill the app. Phone is still stationary
3. Heartbeats stop firing at this time
4. Open the app again. Heartbeats resume.

Based on what I am reading here, the heartbeats should not be stopping after step 2

**Comment by christocracy** [comment]
How is that you’re observing for evidence that heartbeat is not firing?

You should be looking them in the plugin logs via `$ adb logcat *:S TSLocationManager:V` and/or configure `debug: true` so you can *hear* the debug sound FX...*boop*....*boop*...*boop*.

See wiki *Debugging*.

**Comment by christocracy** [comment]
See api docs Config.debug for a description of debug sound fx with media-player samples.

**Comment by MilesAdamson** [comment]
Previously I was just looking at the requests hitting the server which come from the heartbeat handler. I realize now that this doesn't necessarily mean the heartbeat isn't firing. I turned the sounds on and viewed the logcat and this error whenever the heartbeat fires (it definitely is firing when the app is killed, my mistake)

```
09-30 13:56:25.531 28261 28323 E TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation]
09-30 13:56:25.531 28261 28323 E TSLocationManager:   ‼️  Failed to get last location: com.google.android.gms.tasks.zzu@c03b93e
```

**Comment by christocracy** [comment]
> Do you think this is relevant?

No.  Heartbeat does not turn on location-services.  It attempts to return the last known location.  If there is no last last known location, so be it.  If you want to request the current location in your heartbeat event-handler, it’s up to you to call `getCurrentPosition`.

**Comment by MilesAdamson** [comment]
I found my issue. I was using objects in my heartbeat handler which would not be set up properly if the app is killed. I change this handling to being a top level function with no dependencies and it now works properly.

Turning on the sounds and viewing the logs was very helpful thank you

**Comment by CHOMNANP** [comment]
@MilesAdamson, can you share which method you were using?
