### ISSUE TITLE
Question regarding scheduling

### ISSUE THREAD

**Issue by dwenderf** [transistorsoft/flutter_background_geolocation#418]
## Your Environment
* Plugin version: 1.10.0+1
* Platform: iOS and Android
* OS version: iOS 14, Android 10
* Device manufacturer / model: iPhone 7, Samsung S10+
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.49.2)
[!] Connected device
    ! No devices available

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 1;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 1;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 125;
    elasticityMultiplier = 3;
    enableTimestampMeta = 0;
    enabled = 1;
    encrypt = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =     {
        Authorization = "Token";
        "diagnostic-mode" = 1;
        "diagnostic-mode-token" = "";
    };
    heartbeatInterval = 60;
    httpRootProperty = ".";
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 1;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 75;
    odometer = "40399.74558424931";
    params =     {
        framework = flutter;
        manufacturer = Apple;
        model = "iPhone9,1";
        platform = iOS;
        uuid = "17c4f523-ebd4-4b81-9aa8-1238133fc4ff";
        version = "13.7";
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = 2;
    preventSuspend = 1;
    schedule =     (
        "2020-10-06-15:30 2020-10-06-17:00"
    );
    schedulerEnabled = 1;
    showsBackgroundLocationIndicator = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 10;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 1;
    trackingMode = 1;
    url = "https://{redacted)";
    useSignificantChangesOnly = 0;
}
```

## Expected Behavior
N/A See questions below

## Actual Behavior
N/A See questions below

## Steps to Reproduce
N/A

## Context
We are trying to use the scheduler to have the Transistor plugin automatically turn on and off at specified times. We do this by setting a `schedule` in the Config, and ensuring that we call the `startSchedule` method if a schedule has been configured. Additionally, we are setting the `url` property to point to our server, setting `autoSync = true'`, and `autoSyncThreshold = 0`.

It is also important that even if the user kills the app and/or restarts their phone, that the Transistor plugin continues to send locations as long as it is in a defined schedule period based on the Config. To do this, we are setting: `startOnBoot = true`, `stopOnTerminate = false`, and `preventSuspend = true`.

For Android, we are configuring `useAlarmManager = true`, and for iOS, we understand that the Transistor plugin will not wake up and start sending data until there has been a significant location change. We have left `enableHeadless = false` because it seems from the documentation that this is really only meant to be enabled if we want to respond to events after the app is terminated. I don't think we need this because all we need is for the plugin to continue sending locations after terminated (`stopOnTerminate = false`, `autoSync = true`).

## Questions:
* Are the settings I specified above and in our Config correctly set up to accomplish what we are trying to do?
* If we add a schedule to the Config, but the schedule start time has already passed (e.g. it is 3pm currently, but we set a schedule in the Config to start at 2:30pm and end at 4pm), will the SDK call `BackgroundGeolocation.start` immediately, or will it never call the `start` method because it never actually "passed through" a scheduled start time? 
* Is it okay to keep the schedule "on" all the time? In other words, can we call `startSchedule` and just leave it that way, or is it required/best practice to call `stopSchedule` when not needed. In general, we will always want our app to turn on/off based on a schedule. Note that sometimes in our logs we see the following: "[TSScheduler start] Scheduler #start called with an empty schedule!"
* If the phone is restarted and the scheduler was already running/started prior to the restart, will the SDK start up with the schedule already enabled, or do we need to call `startSchedule` again?
* If the app is killed and the phone is subsequently restarted, is there an event will always fire after the phone is restarted that we can listen to so that we can ensure that our schedule is set up properly on startup? 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Are the settings I specified above and in our Config correctly

Why don't you provide your `dart` config so I don't have to parse through every single option?

>If we add a schedule to the Config, but the schedule start time has already passed

Yes, if you watch the logs, you'll see the plugin clearly state when it detects this, printing something like "*should be enabled but we are not*"

>Is it okay to keep the schedule "on" all the time?

Yes.

>will the SDK start up with the schedule already enabled

Yes.   Look at the config printed out from your logs above:

```
schedulerEnabled = 1;
```

The plugin persists the config you provide and automatically loads the last known config whenever the app is launched.

>is there an event will always fire after the phone is restarted that we can listen to 

On iOS, no.  On Android, yes, if you configure `enableHeadless: true` and configure your app for *Android Headless Mode*.

>so that we can ensure that our schedule is set up properly on startup

You don't need to worry about this.  Once a `schedule` is configured and `startSchedule` called, the scheduler **is running forever**, regardless of app terminate / device reboot, until you explicitly call `stopSchedule()`.

**Comment by dwenderf** [comment]
Thank you so much for the quick reply, Chris!

And apologies for the confusion regarding the config. I was really just asking if the config values I mentioned in the Context section of my request were enough to achieve what I was looking for. That is: setting `url` to our endpoint, `autoSync: true`, `autoSyncThreshold: 0`, `startOnBoot: true`, `stopOnTerminate: false`, `alarmManager: true`, `enableHeadless: false`. 

We also set `preventSuspend: true`, but I think that perhaps we do not need to do this, and in fact probably should *not* set this to true based on your documentation.

**Comment by dwenderf** [comment]
One follow-up question:

Is there any limit to how far in advance the scheduler can be set? I understand that doing so would mean that the plugin would need to monitor significant location changes while any scheduled item exists in the future, but this should be fairly low in terms of battery use because it won't be persisting the data.

**Comment by christocracy** [comment]
>Is there any limit to how far in advance the scheduler can be set? 

No.
