### ISSUE TITLE
Android crashes 

### ISSUE THREAD

**Issue by Maleandr** [transistorsoft/flutter_background_geolocation#419]
## Your Environment
* Plugin version: 1.10.1
* Platform: Android
* OS version: all
* Device manufacturer / model: all
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
final bg.State state = await bg.BackgroundGeolocation.ready(
        bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_OFF,
          enableHeadless: true,
          disableLocationAuthorizationAlert: true,
        ),
      );
```

## Expected Behavior
App works

## Actual Behavior
App crashes

## Context
Happens only in the release mode. It works fine in debug.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Fatal Exception: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-8-thread-1
       at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:36)
       at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java)
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:27)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.a(MethodChannel.java:14)
       at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$4.onFailure(BackgroundGeolocationModule.java:3)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(BackgroundGeolocation.java:30)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

</details>

**Comment by christocracy** [comment]
Any idea how to reproduce?  The solution is easy once I know the case causing this `onFailure` callback.

**Comment by Maleandr** [comment]
We are adding and removing geofences. Dunno if this trigger onFailure.

`await bg.BackgroundGeolocation.removeGeofences();
      if (vendorIds?.isNotEmpty ?? false) {
        await addGeoFencesByVendors(vendorIds);
      }

      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }

      bg.BackgroundGeolocation.onGeofence(onGeoFence);`

**Comment by christocracy** [comment]
The above code is the only `BackgroundGeolocation` code you're using?

**Comment by Maleandr** [comment]
We use also

`bg.BackgroundGeolocation.requestPermission();`

**Comment by christocracy** [comment]
Are you able to reproduce this on your own device?

**Comment by Maleandr** [comment]
I can reproduce it, however it only happens in release mode.

**Comment by christocracy** [comment]
Great.
- In your `android/app/build.gradle`, [set `minifyEnabled false`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/build.gradle#L86)
- `BackgroundGeolocation.ready` with `logLevel: bg.Config.LOG_LEVEL_VERBOSE`
- Monitor `$ adb logcat *:S flutter:V TSLocationManager:V`
- Paste the logs here from reproducing the issue.

**Comment by Maleandr** [comment]
I get this:
 java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:779)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:144)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$4.onFailure(BackgroundGeolocationModule.java:382)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by christocracy** [comment]
Bingo [BackgroundGeolocationModule.java:382](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/BackgroundGeolocationModule.java#L382)

**Comment by Maleandr** [comment]
Do you neeed something more from our side?

**Comment by christocracy** [comment]
Yes, I want to see `LOG_LEVEL_VERBOSE` of your app booting.

```
logLevel: bg.Config.LOG_LEVEL_VERBOSE
```

**Comment by Maleandr** [comment]
adb logcat *:S flutter:V TSLocationManager:V thi command doesn't work. 

I got only LICENSE VALIDATION FAILURE: com.coderi.portito.test, but problem is not related to this, because it happens on valid license package as well

**Comment by christocracy** [comment]
> but problem is not related to this

Yes it is.  I found that the code firing the `onFailure` callback when license fails is doing do in the background-thread.

**Comment by Maleandr** [comment]
Why this happens on production builds as well? We don't get license validation failure there but it chrashes on same error.

**Comment by christocracy** [comment]
Why are you building an app for `release` without a valid license key?  That'll never work.  Give your app a valid key and boot for release.

**Comment by Maleandr** [comment]
Because we have different package for prod and test app.

**Comment by christocracy** [comment]
Boot your app for `release` with a valid key and show me the verbose logs.

**Comment by Maleandr** [comment]
Sorry it works on prod build. Client just give me wrong informations about it. How can we get another key for test builds please?

**Comment by christocracy** [comment]
The plugin allows a finite number of suffixes on the same applicationId the key was generated for:
- `.dev` / `.development`
- `.staging`
- `.test`
- `.uat`
- `.debug`

**Comment by Maleandr** [comment]
You support only these suffixes?

**Comment by christocracy** [comment]
>You support only these suffixes? 

Yes.

>If so can you add production suffix?

No.

I have found your Order and looked at your key `com.coderi.<redacted>.production`.

If you want to boot this for `.test`, your test app *must* be named:
`com.coderi.<redacted>.production.test`

**Comment by Maleandr** [comment]
That is serious limitation from your side. I understand that we need to regenerate api key, with com.coderi.<redacted>, but I don't see reason, why we cannot use .production suffix. It is pretty common and we are using this, becase we were forced from another plugin.

**Comment by christocracy** [comment]
>That is serious limitation from your side

Nobody has expressed an issue about this for the last 3 years that the plugin has allowed suffixes.

>why we cannot use .production suffix

You already have a key generated for your production app `com.coderi.<redacted>.production`.  That *is* your production key.

**Comment by Maleandr** [comment]
I see, but how I can get key for com.coderi.***.test env without paying for it? We have a ton of other things related to package and it is not feasible to change them.

**Comment by christocracy** [comment]
The typical way to generate Android build-variants is [like this](https://developer.android.com/studio/build/build-variants).

Email `chris@transistorsoft.com` and I'll manually generate a key for use with your `.test`.  Send the full `applicationId` you want a key generated for.

**Comment by Maleandr** [comment]
Done. Many thanks for help and I'm sorry for any troubles we have caused.
