### ISSUE TITLE
IOS is asking for background location permission every time on app start.

### ISSUE THREAD

**Issue by VatsalBhesaniya** [transistorsoft/flutter_background_geolocation#421]
## Your Environment
* Plugin version: flutter_background_geolocation: ^1.9.3
* Platform: iOS
* OS version: 13.7
* Device manufacturer / model: iOS simulator - iPhone 11 Pro Max
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.0)
[✓] Connected device (2 available)

• No issues found!
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
await bg.BackgroundGeolocation.ready(
    bg.Config(
      transistorAuthorizationToken: token,
      disableLocationAuthorizationAlert: true,
      reset: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      autoSync: true,
      stopOnTerminate: false,
      foregroundService: true,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
      isMoving: false,
    ),
  ).then((bg.State state) async {
    logger.d('[ready] ${state.toMap()}');
    bg.BackgroundGeolocation.start();
  }).catchError((error) {
    logger.e('[ready] ERROR: $error');
  });
}
```

## Expected Behavior
It should not ask for background location permission every time user open the app rather user denied it.

## Actual Behavior
It is asking for background location permission every time user open the app.

## Steps to Reproduce

1. Install app and initialise the library once.
2. Don't allow permission for background location.
3. Restart the app.
4. On restart it should not ask for background location permission again after user denied.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
If you don't want the plugin to ask permission, don't tell the plugin to `.start()`.

Listen to `onProviderChange` event to learn the current state of authorization.

```
then((bg.State state) async {
    logger.d('[ready] ${state.toMap()}');
    bg.BackgroundGeolocation.start();
  }).catchError((error) {
    logger.e('[ready] ERROR: $error');
  })
```

**Comment by VatsalBhesaniya** [comment]
What if i use this property in plugin config?
disableLocationAuthorizationAlert: true

**Comment by christocracy** [comment]
Why not try it and see?

**Comment by VatsalBhesaniya** [comment]
With this property in plugin config
disableLocationAuthorizationAlert: true
I found solution of my issue.
Thank you.
