### ISSUE TITLE
Background tracking issue Huawei / Xiaomi

### ISSUE THREAD

**Issue by vasilip** [transistorsoft/flutter_background_geolocation#423]
## Your Environment
* Plugin version: 1.10.1
* Platform: Android
* OS version: Android 7 Huawei P9 / Android 8.1 Xiaomi Redmi 6A / Samsung Note8/S9 Android 9
* Device manufacturer / model: Huawei / Xiaomi
* Flutter info (`flutter doctor`): 
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] VS Code (version 1.48.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
            url: "${Constants.TRACKER_HOST}/api/post-locations",
            headers: {
                "Authorization": "Bearer ${UserDataProvider.authToken}"
            },
            triggerActivities: 'in_vehicle', //'in_vehicle, on_bicycle, on_foot, running, walking'
            // Logging & Debug
            reset: false,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 10.0,
            stopTimeout: 1,
            // HTTP & Persistence
            autoSync: true,
            forceReloadOnHeartbeat:true,
            batchSync:true,
            maxBatchSize:20,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60
```

## Expected Behavior
Background tracking / activity detection should work

## Actual Behavior
I have installed my app and the flutter demo app on all devices to also compare data with the demo console site and in case something is incorrectly setup on my end. Both apps appear to behave similarly. on occasion one will wake while the other  won't.

I have tested with in_vehicle as well as all triggers. I need in_vehicle triggers for my use case.

**On Xiaomi Redme 6A (Android 8.1):** It will start tracking sometimes but a lot of times it will record a speed and moving: true but activity "still" then it will stop tracking after the beginning of the drive. If I open the app while driving it might record again for a bit then stop again.

**On Huawei P9 (Android 7):** It almost does not work at all. while driving it will make a lot of "cling" sounds (STOP_TIMER_ON) constantly. And didn't record any data. Othertimes its just completely silent (other than heartbeat) You could see the background task icon constantly flashing regularly in the status bar but not staying on.

**On Huawei P20Lite:** Had same problem with "still" while moving, but after dontkillmyapp optimization it seems to work now.

**Samsung Note8/S9:** Works perfectly.

I have followed dontkillmyapp instructions for all devices and also used DeviceManager to check the power settings through the app as well.

General issue:
I tried forceReloadOnHeartbeat:true incase the MainActivity can help keep it alive but it doesn't seem to do anything at all. I don't see the app reload on heartbeat.

The strange thing is that on both Xiaomi 6A and Huawei P9 the heartbeat beep can be heard regularly. even when stationary. So I have a feeling the problem generally is incorrect activity detection which triggers it to stop during a trip, to stop right after exiting the geofence or to never start at all.

I can email you logs from the 3 devices as well as screenshots of tracker.transistorsoft.com so you can visually see the result. I would rather not publicly post GPS data in the logs.

## Steps to Reproduce

1.

## Context
Track drivers in cars

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I can email you logs from the 3 devices as well as screenshots of tracker.transistorsoft.com so you can visually see the result. I would rather not publicly post GPS data in the logs.
```

</details>

**Comment by christocracy** [comment]
The first step when dealing with Chinese devices is to follow the instructions at http://dontkillmyapp.com.

**Comment by vasilip** [comment]
Hi Chris,

As I mentioned in the issue report above, I have double and triple checked that the dontkillymyapp measures have been taken.

**Comment by christocracy** [comment]
Chinese manufacturers purposely intercept events from Android apis in the background  and prevent them being relayed to your app, in violation of their Android OEM license.  This is a well known issue and there is no developer solution.

**Comment by vasilip** [comment]
![trips](https://user-images.githubusercontent.com/351755/96137764-b4f2db80-0f05-11eb-9fd7-98b10a41b940.jpg)

This is the Xiaomi 6A. Three consecutive trips separated by an hour or so. I monitored the phone very often to ensure that the background service was active and it was. By looking at this it seems that despite the service being alive the phone just didn't send events as you mentioned.

Aside from Samsung / Apple, do you have a list of makes / generations / android version that are likely to work so we can have a dedicated tracking solution for the ones that won't? I assume you may have more data that I can collect from the limited number of phones I have available.

**Comment by christocracy** [comment]
>do you have a list of makes / generations / android version that are likely to work

No.

FWIW, my Xiaomi *Mi A2 @ 10.0.0* is one of my best-performing test-devices.
![](https://dl.dropbox.com/s/a4cvg1ynj3op6ay/Screen%20Shot%202020-10-15%20at%2010.21.57%20AM.png?dl=1)

For my test-devices, only my *Huawei P20 Lite* performs sporadically (sometimes good, sometimes bad).

My test-devices:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0
