### ISSUE TITLE
This doesn't do what you think it does

### ISSUE THREAD

**Issue by avioli** [transistorsoft/flutter_background_geolocation#425]
https://github.com/transistorsoft/flutter_background_geolocation/blob/80973ca67fc9caa85d564227bd8598afda741971/lib/models/background_geolocation.dart#L993-L999

It probably is fine to not wait on the cancellation future, given it _is_ the current state of affairs, but if you actually want to:

```dart
   static Future<bool> removeListeners() async {
     await Future.wait(_subscriptions.map((sub) => sub.subscription.cancel()));
     _subscriptions.clear();
     return true;
   }
```

<details>
<summary>`Future.wait` details</summary>

Keep in mind that `Future.wait()` doesn't throw the first error eagerly if any future throws (what we want), but continues with them all and then throws the first caught error, and ignores the rest (possibly making them "unhandled"). If you think there is such a scenario and you still want to clear the `_subscriptions` list - then either clone it first, clear it and iterate on the clone or wrap in try/catch and rethrow after you clear.

</details>

**Comment by christocracy** [comment]
Thanks, I wrote that part of the API when I was still learning `dart`.

`removeListeners` is generally not required.  Simply calling `stop()` will halt all events from firing.

Just as we don't need to disconnect / reconnect our speakers in our stereo system when when simply want to turn the stereo off.  We just toggle to `[POWER]` button off.

**Comment by avioli** [comment]
Sure thing. We all go through the learning stage, ofc.

I'm using `removeListener`, but saw this and other methods using a curious approach at async handling and while most are fine this one was trying to wait on stuff.

Feel free to close this if you want.
