### ISSUE TITLE
Asking for location permission every time user restart the app when permission status is other than "Allow all the time".

### ISSUE THREAD

**Issue by chandaniBhalala** [transistorsoft/flutter_background_geolocation#426]
## Your Environment
* Plugin version: ^1.9.3
* Platform: Android
* OS version: Android 10 and 11
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

• No issues found!
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
await bg.BackgroundGeolocation.ready(
    bg.Config(
      transistorAuthorizationToken: token,
      disableLocationAuthorizationAlert: true,
      reset: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      autoSync: true,
      stopOnTerminate: false,
      foregroundService: true,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
      isMoving: false,
    ),
  ).then((bg.State state) async {
    logger.d('[ready] ${state.toMap()}');
    bg.BackgroundGeolocation.start();
  }).catchError((error) {
    logger.e('[ready] ERROR: $error');
  });
```

## Expected Behavior
It should not ask for location permission every time user start the app when permission status is other than "Allow all the time".

## Actual Behavior
It is asking for location permission every time user start the app when permission status is other than "Allow all the time".

## Steps to Reproduce

1. Set location permission status 'Deny' or 'Ask every time' or 'Allow only while using the app'.
2. Restart the app.
3. It will ask for location permissions again.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by chandaniBhalala** [comment]
I am facing the same issue with latest version "1.10.1" as well.
It should not ask for location permission when we use "disableLocationAuthorizationAlert: true" property in plugin config.
I am facing this issue in android only, in iOS it is working perfect.

**Comment by christocracy** [comment]
>It should not ask for location permission when we use

If you tell the plugin to `.start()`, the plugin *necessarily* must ask for location permission.  `Config.disableLocationAuthorizationAlert` merely produces an Android dialog prompting the user to enable location-services if they've disabled it.

If you don't want the plugin to request location permission from the user, don't tell the plugin to `.start()`.

**Comment by christocracy** [comment]
See API docs `Config.locationAuthorizationAlert`.
