### ISSUE TITLE
Help - is geofencing required ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by niypoo** [transistorsoft/flutter_background_geolocation#428]
Now After google had changes his polices and send to me a alert about ACCESS_BACKGROUND_LOCATION, I want to ask you
If I'm using only geofencing is that make me must request ACCESS_BACKGROUND_LOCATION ?

**Comment by christocracy** [comment]
Yes, geofencing requires background permission.

I have successfully had my demo apps for Flutter, Cordova and React Native all approved for the new policies.  It takes some work to get it all set up for approval, including a video showing Google exactly how to login to the app and trigger location permission dialogs.

**Comment by niypoo** [comment]
any advices for this question !
Why does your app need access to location in the background?

**Comment by christocracy** [comment]
> Why does your app need access to location in the background

I don’t know your app so it’s impossible for me to write that for you.  Just be honest.

**Comment by christocracy** [comment]
Also see new Android Config.backgroundPermissionRationale

**Comment by niypoo** [comment]
Okay , thanks I have made a video and I will submit it , thanks again 🥇

**Comment by christocracy** [comment]
Here's my *Policy -> App Content* I've provided for the Demo app.

### 1.  App Access

![](https://dl.dropbox.com/s/gu2dxitb6eb6ak0/Screen%20Shot%202020-10-20%20at%204.29.41%20PM.png?dl=1)

![](https://dl.dropbox.com/s/hwae8bwl04abwz9/Screen%20Shot%202020-10-20%20at%204.30.17%20PM.png?dl=1)

### 2.  Sensitive App Permissions

![](https://dl.dropbox.com/s/hkcvdsnxudh7e8b/Screen%20Shot%202020-10-20%20at%204.31.20%20PM.png?dl=1)

- [Video Instructions](https://www.dropbox.com/s/rrja63whzsk7oi0/flutter-background-geolocation.mp4?dl=0)

**Comment by christocracy** [comment]
:warning: I've found that if you update any of the above *Play Console* forms, it seems to re-initiate the review process, even if you haven't uploaded a new release.

**Comment by christocracy** [comment]
Also, I monitored my demo server `tracker.transistorsoft.com` and Google reviewers *will* actually login to your app using the provided instructions on a *real* device (not a simulator).

![](https://dl.dropbox.com/s/6v9pem9mzboi13r/Screen%20Shot%202020-10-20%20at%204.41.20%20PM.png?dl=1)

**Comment by niypoo** [comment]
> :warning: I've found that if you update any of the above *Play Console* forms, it seems to re-initiate the review process, even if you haven't uploaded a new release.

Yes i noticed that I have upload the video and resubmit then status return to being review , so I will wait how their respond will be like

**Comment by niypoo** [comment]
Thank you @christocracy your advise help me a lot 👏🏻 google have approved
