### ISSUE TITLE
Can't build ios Podfile Version 11

### ISSUE THREAD

**Issue by MonsterDKing** [transistorsoft/flutter_background_geolocation#429]
## Your Environment
* Plugin version: Last
* Platform: iOS
* OS version: Mac
* Device manufacturer / model: 
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale es-419)
                                                                                                                                     
monsterdking@iMac-de-pedro ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale es-419)
    • Flutter version 1.22.2 at /Users/monsterdking/development/flutter
    • Framework revision 84f3d28555 (hace 7 d'ias), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/monsterdking/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 3F98DE2F-C1A1-47BF-BA2F-2A762A74D5F0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 15.0,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          preventSuspend: true,
          heartbeatInterval: 60,
          locationAuthorizationAlert: {
            "titleWhenNotEnabled":
                "La ubicación en segundo plano no está habilitada",
            "titleWhenOff": "La ubicación en segundo plano no está habilitada",
            "instructions":
                "Para usar la ubicación en segundo plano, debe habilitar 'Siempre' en la configuración del servicio de ubicación",
            "cancelButton": "Cancelar",
            "settingsButton": "Configuracion"
          }),
```
Important 
if  i comment this lane  #platform :ios, '11.0'
work but i need version 11

## Steps to Reproduce

1. Change Podfile to 11 
2. Try build
3. Error

## Context
change the ios version to version 11 as a plugin needs it.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

Xcode's output:
↳
    /Users/monsterdking/Desktop/fraktalweb/tuntun/fl_tutum/ios/Runner/AppDelegate.swift:11:5: warning: setter for 'isStatusBarHidden' was deprecated in iOS 9.0: Use
    -[UIViewController prefersStatusBarHidden]
        UIApplication.shared.isStatusBarHidden = false
        ^
    /Users/monsterdking/Desktop/fraktalweb/tuntun/fl_tutum/ios/Runner/AppDelegate.swift:11:5: warning: setter for 'isStatusBarHidden' was deprecated in iOS 9.0: Use
    -[UIViewController prefersStatusBarHidden]
        UIApplication.shared.isStatusBarHidden = false
        ^
    /Users/monsterdking/Desktop/fraktalweb/tuntun/fl_tutum/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'background_fetch' not found
    @import background_fetch;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    /Users/monsterdking/Desktop/fraktalweb/tuntun/fl_tutum/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'background_fetch' not found
    @import background_fetch;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Using build description from disk
```

</details>

![image](https://user-images.githubusercontent.com/6463552/96960384-f10adb00-14c7-11eb-86f9-90ef5b7a3517.png)

**Comment by MonsterDKing** [comment]
I try : 

delete podfile.lock 
install pod 
flutter clean etc.

**Comment by christocracy** [comment]
>Plugin version: Last

What is the *exact* version.  Specifying "latest" is meaningless the next time I release a version.

**Comment by christocracy** [comment]
I cannot reproduce this in the `/example` app in this repo.  I suggest you attempt to reproduce this in the `/example` app.
