### ISSUE TITLE
Location update interval not working on Android

### ISSUE THREAD

**Issue by marcosvcr84** [transistorsoft/flutter_background_geolocation#431]
## Your Environment
* Plugin version:1.8.0
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Samsung Galaxy A10
* Flutter info (`flutter doctor`):
`
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-BR)
    • Flutter version 1.20.4 at /Users/marcosvinicius/Development/flutter
    • Framework revision fba99f6cf9 (6 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcosvinicius/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/marcosvinicius/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
`
* Plugin config:
```dart 
bg.BackgroundGeolocation.ready(bg.Config(
            reset: false,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 0,
            locationUpdateInterval: 10000,
            stopTimeout: 1,
            // HTTP & Persistence
            url: "http://api.webrota.com.br:1200",
            method: "POST",
            extras: extras,
            autoSync: true,
            batchSync: true,
            maxBatchSize: 5,
            maxDaysToPersist: 3,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            notificationText: "Sincronização de dados habilitada.",
            heartbeatInterval: 60))
```

## Expected Behavior
According to locationUpdateInterval config, the location should be captured at 10 seconds interval.

## Actual Behavior
it's capturing every 3 seconds.

**Comment by christocracy** [comment]
Why are you using `reset: false`?  Do you know what that does?

Also, the latest version is `1.10.1`

**Comment by marcosvcr84** [comment]
I know what that does and it should really be configured as false.

So, what do you suggest me? Update to the latest plugin version and check if the location update interval will work as expected?

**Comment by christocracy** [comment]
So you know that if *changed* `locationUpdateInterval` **after** your app has already been launched, that the plugin is ignoring that change?

You’re also aware that the plugin only turns on location-services and starts recording location when the motion api says the device is moving?  If the device is sitting completely still on your desk, you should expect the plugin to record no locations at all.

You’re familiar with the wiki *Philosophy of Operation*?

**Comment by marcosvcr84** [comment]
Yes, but in this case we are not changing `locationUpdateInterval` anytime, we run our app, the config is set and not changed anymore.

Our use is only with the device in movement and the locations updates are every 3 seconds and not 10 seconds as set on the configurations

**Comment by christocracy** [comment]
Are you testing this is the field or with mocked locations?

**Comment by marcosvcr84** [comment]
We are not using mocked locations

**Comment by christocracy** [comment]
If you have *another app* on your device which is recording location in the background, those locations will also be delivered to *your app* at a rate controlled by `fastestLocationUpdateInterval`.

Are you observing the plugin logs?

**Comment by marcosvcr84** [comment]
Didn't know about this, I'm gonna check.
Maybe using `fastestLocationUpdateInterval` will fix my time to get locations

**Comment by marcosvcr84** [comment]
@christocracy We fixed the interval using `fastestLocationUpdateInterval` to 15 seconds . Sometimes we got 18 seconds, or 19 seconds, and sometimes 15 seconds.
I'd like to know about this precision. In most cases, we got an interval a little bit bigger than the 15 seconds.

**Comment by christocracy** [comment]
Read about it in the Android docs.  https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setFastestInterval(long)

**Comment by marcosvcr84** [comment]
Ok, understood, so I believe that if we set 10 seconds at fastinterval and 30 seconds at setinterval, maybe we achieve our goal, is that ok?

**Comment by marcosvcr84** [comment]
`fastestLocationUpdateInterval` solved the problem
Thanks
