### ISSUE TITLE
ios: requesting 'Always' permission for background location

### ISSUE THREAD

**Issue by doruchidean-lifeishard** [transistorsoft/flutter_background_geolocation#434]
## Flutter 1.22.2 

* Plugin version: 1.10.1
* Platform: iOS 
* OS version: 13.7
* Device manufacturer / model: iphone 11

* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-RO)
    • Flutter version 1.22.2
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.0.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.0.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone (mobile) •  • ios • iOS 13.7
    ! Error: 's iPhone is busy: Processing cache files from device. Xcode will continue when Ale's iPhone is finished. (code -10)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
            reset: false,
            // <-- lets the Settings screen drive the config rather than re-applying each boot.
            // Logging & Debug
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            // Activity recognition options
            stopTimeout: 5,
            desiredOdometerAccuracy: 10,
            // HTTP & Persistence
            autoSync: false,
            // Application options
            stopOnTerminate: false,
            locationAuthorizationRequest: 'Always',
            backgroundPermissionRationale: getPermissionRationale(),
            startOnBoot: false,
            foregroundService: true,
            enableHeadless: true,
            geofenceInitialTriggerEntry: true,
            geofenceModeHighAccuracy: false,
            heartbeatInterval: 60)
```

## Expected Behavior
After allowing 'While in use...' permission the user is prompted with a modal asking to manually set the 'Always' permission grant from settings (which is normal on ios13).
The issue is that in that settings screen there is no 'always' option.
, 
## Actual Behavior
The setting screen only shows 'never', 'always ask', 'when app is running'

## Context
My info.plist file containts values for :
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription
NSLocationAlwaysAndWhenInUsageDescription

It would be nice if the location permissions would be better documented since both android and ios platforms keep updating their permissions logic. (a blog page about this issue is not enough).

**Comment by christocracy** [comment]
iOS offers the `Always` allow option in your App's settings screen purely based upon the presence of the Privacy strings in your Info.plist.  

Your Info.plist *must* have an error.

I suggest you create a fresh new *Hello World* app and walk through the iOS Setup to assure yourself that the Setup steps are valid.

**Comment by doruchidean-lifeishard** [comment]
Misspelled location usage key (NSLocationAlwaysAndWhenInUsageDescription)

I really appreciate your quick reply. 
Thank you for your help and keep up the good work.

**Comment by duduBaiao** [comment]
This post could be also useful:

https://medium.com/better-programming/handling-ios-13-location-permissions-5482abc77961

The "Always" option doesn't rely solely on the Info.plist keys. There are more things involved.

**Comment by christocracy** [comment]
>The "Always" option doesn't rely solely on the Info.plist keys. There are more things involved.

As far as *flutter_background_geolocation* is concerned, there is *nothing* else involved aside from adding the required `Info.plst` strings.  This plugin takes care of everything else.  There is nothing more involved.

**Comment by christocracy** [comment]
Everything required is documented in the [iOS Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md)

**Comment by duduBaiao** [comment]
Yep. I've just shared that link because, even if the user follows everything mentioned in the plugin's documentation, he still could not see the "Always" option in the permission dialog, for the reasons mentioned in the link above.

It seems you didn't read it before commenting. :)

**Comment by christocracy** [comment]
>for the reasons mentioned in the link above.

What specific reasons are you referring?  I [blogged about this myself in 2019](https://transistorsoft.medium.com/ios-13-and-android-q-support-beb7595d2c24)

**Comment by duduBaiao** [comment]
I was talking about the fact that we ask for the "Always" permission, but the dialog shows "While in Use". Then later the iOS shows, or not, the option to allow the background tracking all the time.

It would be helpful having a link to your article in the iOS Setup page. There is a lot  of valuable content there. ;)
