### ISSUE TITLE
location service activated notification doesn't disappear 

### ISSUE THREAD

**Issue by MoonGit-Olam** [transistorsoft/flutter_background_geolocation#439]
## Your Environment

```dart <-- Syntax highlighting: DO NOT REMOVE -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

* Plugin version: version 1.10.1
* Platform: iOS or Android 
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:

bg.Config(
          enableHeadless: true,
          reset: true,
          debug: false,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 300.0,
          stopOnTerminate: false,
          startOnBoot: true,
          stopTimeout: 5,
          logLevel: bg.Config.LOG_LEVEL_OFF,
          desiredOdometerAccuracy: 10),
```

## Expected Behavior
location service activated notification should disappear after 5 mins because    stopTimeout: 5 is set in config

## Actual Behavior
1.Sometimes in Android devices it shows geolocation activated even though the user was sitting idle without any movement .
2.In some android devices geolocation service activated notification doesn't disappear after being ideal for 5 mins . ideally it should go we are using (stopTimeout:5) in Config you can see that.

## Context

![image](https://user-images.githubusercontent.com/71000177/98077522-6e562880-1e96-11eb-9b95-15ddef0284f8.png)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by goranristic123** [comment]
I have the same problem, reported the issue #333. And nobody has answered me, so don't expect too much of it.

**Comment by christocracy** [comment]
If you have a problem like this, the answer is in the logs.  See wiki *Debugging*.

**Comment by MoonGit-Olam** [comment]
> If you have a problem like this, the answer is in the logs. See wiki _Debugging_.

Hi please See my logs updated above- odometer reading is coming zero , even though I did a walk of 1.5+ km
