### ISSUE TITLE
distanceFilter: 300.0 still getting walk notification, when user is walking around in room

### ISSUE THREAD

**Issue by MoonGit-Olam** [transistorsoft/flutter_background_geolocation#440]
## Your Environment

```dart <-- Syntax highlighting: DO NOT REMOVE -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

* Plugin version: version 1.10.1
* Platform: iOS or Android 
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:

bg.Config(
          enableHeadless: true,
          reset: true,
          debug: false,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 300.0,
          stopOnTerminate: false,
          startOnBoot: true,
          stopTimeout: 5,
          logLevel: bg.Config.LOG_LEVEL_OFF,
          desiredOdometerAccuracy: 10),
```

## Expected Behavior
Ideally users should not get notification of activity detected when the user is walking around in the room  because we are using (distanceFilter: 300.0) and  desiredOdometerAccuracy: 10).  but in our case the user gets a notification as soon as he walks continuously around in his room .

## Actual Behavior
User is getting notification walk activity detected for 0.1 km or 0.00 km .

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- See API docs [Config.motionTriggerDelay](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/motionTriggerDelay.html).
- See Wiki *Debugging*.  Use `debug: true, logLevel: bg.Config.LOG_LEVEL_VERBOSE` during development / testing.
