### ISSUE TITLE
Maximum value and accuracy of loiteringDelay

### ISSUE THREAD

**Issue by mahdi-ninja** [transistorsoft/flutter_background_geolocation#443]
## Your Environment
* Plugin version: 1.10.2
* Platform: All
* OS version: Any
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`): 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-AU)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
        Config(
          desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
          geofenceModeHighAccuracy: true,
          stopOnTerminate: false,
          startOnBoot: true,
          geofenceInitialTriggerEntry: false,
          persistMode: Config.PERSIST_MODE_GEOFENCE,
          distanceFilter: 200,
          elasticityMultiplier: 5,
          stopTimeout: 5,
          enableHeadless: true,
        ),
```

## Context
The client is asking to delay geofence enter event for a certain amount of time and my understanding is that I should use Dwell event and set the `loiteringDelay` to the desired amount.
So I have the following questions:
* Is that is there a limit on what the value of `loiteringDelay` could be? 
* How can I find the time when the phone entered the geofence? Is this an accurate measurement if I simply subtract the `loiteringDelay` from current time and assume that it was the entry time?

**Comment by christocracy** [comment]
> Is that is there a limit on what the value of loiteringDelay could be?

I'm not aware of a limit, but I would keep it to less than 2 min.

>How can I find the time when the phone entered the geofence? 

By configuring `notifyOnEnter: true` and comparing the time difference between the `ENTER` and `DWELL` events.

**Comment by mahdi-ninja** [comment]
> I'm not aware of a limit, but I would keep it to less than 2 min.

Thanks. Does it mean that if I use a bigger value (say 10 minutes), then it will be unreliable and there's a chance that it won't fire?

**Comment by christocracy** [comment]
It will be fine for Android, but `notifyOnDwell` for iOS is my own custom implementation (iOS geofences do not natively support `notifyOnDwell`.  This implementation relies on some tricky juggling [beginBackgroundTaskWithExpirationHandler](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio) and timers.

If you're going to use `10 minutes`, I suggest you thoroughly field-test.
