### ISSUE TITLE
BackgroundGeolocation.onProviderChange not called in a specific case on Android

### ISSUE THREAD

**Issue by Max-Might** [transistorsoft/flutter_background_geolocation#444]
## Your Environment
* Plugin version: 1.10.3
* Platform: Android
* OS version: 8
* Device manufacturer / model: Sony Xperia X, Pixel 2

## Expected Behavior
The `BackgroundGeolocation.onProviderChange()` callback needs to be called in the described situation.

## Actual Behavior
The `BackgroundGeolocation.onProviderChange()` is not called.

## Steps to Reproduce
This is not a very common scenario but it is possible that it happens.
The can only be reproduced the **first** time the app is started after it is installed.
Assume that you have an app that requests location permissions when it is started.

1. Install and launch the application.
2. When it is started the application requires location permissions using the API from this library.
3. **Deny** the location permission. (I think the callback is executed properly at this point.)
4. Without closing the application go to the location settings in Android and enable location for this specific application.
5. Return to the app and see that the `BackgroundGeolocation.onProviderChange()` callback is not executed when the permission was granted so the app does not know that it now has a permission.

This might not be a problem with this library but with Android or just one of the many odd things that Android does.

**Comment by christocracy** [comment]
You're free to manually request [BackgroundGeolocation.providerState](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/providerState.html) at any time.

```dart
bg.ProviderChangeEvent state = await bg.BackgroundGeolocation.providerState;
print("- current provider state: $state");
```

**Comment by Max-Might** [comment]
Yep, this works as a workaround. Thanks.
