### ISSUE TITLE
Getting License Validation Error Toast even though I don't want to use for Android

### ISSUE THREAD

**Issue by maulikhirani** [transistorsoft/flutter_background_geolocation#445]
## Your Environment
* Plugin version: 1.9.0
* Platform: Android
* OS version: 10.0.0
* Device manufacturer / model: Xiaomi Poco F1
* Flutter info (`flutter doctor`): [√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,

      logLevel: bg.Config.LOG_LEVEL_VERBOSE
  )
```

## Expected Behavior
Should not get license validation error toast message if I am not using any SDK features in Android. 

## Actual Behavior
Getting license validation error toast message on app launch even though I am not initializing for Android platform. I only want to use this plugin for iOS.

## Steps to Reproduce

Launch the android app. debug or release

## Context
I just want to use this plugin to work in iOS specific portion of the code.

</details>

**Comment by christocracy** [comment]
Why don't you want to use Android?

**Comment by Exnonull** [comment]
> Why don't you want to use Android?

For example in my case we use current plugin for iOS and another for Android.
We use 2 plugins because another plugin was configured before and we found it work not good enough for iOS in terminated state but it's free for Android.
Thats why it could be nice if there was some way to remove message about invalid license key if don't want to use current plugin for Android (besides clone repo and delete android section manually).

**Comment by christocracy** [comment]
> and another for Android.

To avoid paying for Android.

The license warning cannot be hidden.

**Comment by Exnonull** [comment]
Thanks for reply.
