### ISSUE TITLE
Is there a way to set at specific distance of the moving device from its geofence coordinate to trigger the geofence ENTER and EXIT events?

### ISSUE THREAD

**Issue by EddyKwok** [transistorsoft/flutter_background_geolocation#446]
I have tested my app on the field on iPhone 7 plus where the app was created just to track the ENTER and EXIT events to and from a single geofence coordinate. What I've noticed was that the ENTER event was triggerred a lot closer from its geofence point while the EXIT event was triggerred as further as twice or three times of the triggerred distance of the ENTER event.

* Plugin version: 1.10.1
* Platform: iOS 
* OS version: 14.1.
* Device manufacturer / model: iPhone 7 plus
* Flutter info (`flutter doctor`): _I think we shouldn't needed the flutter info here in this case._
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
        reset: false,  // <-- lets the Settings screen drive the config rather than re-applying each boot.
        debug: true, // my-TODO: Turn this to off once this app is ready to launch!
        logLevel: bg.Config.LOG_LEVEL_VERBOSE, // my-TODO: Change this to LOG_LEVEL_ERROR when submitting to production.
        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        // distanceFilter: The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
        distanceFilter: 5.0,
        // Activity recognition options
        stopTimeout: 5,
        backgroundPermissionRationale: bg.PermissionRationale(
            title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
            message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'
        ),
        // HTTP & Persistence
        autoSync: false,
        // Application options
        stopOnTerminate: true,
        locationAuthorizationRequest: 'WhenInUse', //Always, WhenInUse, Any
        startOnBoot: false,
        enableHeadless: false,
        heartbeatInterval: 60,
        persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
        geofenceInitialTriggerEntry: false
    )).then((bg.State state) async {
```

## Expected Behavior

I supposed that it was part of the design about the different distance from its geofence location for the geofence ENTER and EXIT event tobe trigerred. But I wish that there's an option to adjust that behaviour as well which seems to be no such configuration.

## Actual Behavior

The ENTER event was triggerred in a lot shorter distance than the EXIT event.

## Steps to Reproduce

N/A

## Context

I wanted to be able to specify how long the distance the device will be triggerred the ENTER and EXIT geofence event for both specified individually. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
>What I've noticed was that the ENTER event was triggerred a lot closer from its geofence point while the EXIT event was triggerred as further as twice or three times of the triggerred distance of the ENTER event.

Yes, that's correct and expected behaviour.  Geofence triggering is handled completely by OS.  The plugin is only the messenger.

![](https://dl.dropbox.com/s/6p6gjqw11ha0no3/Screen%20Shot%202020-11-13%20at%2011.56.42%20AM.png?dl=1)
