### ISSUE TITLE
Custom notification icon not working on Android 11

### ISSUE THREAD

**Issue by Timo-Noordzee** [transistorsoft/flutter_background_geolocation#447]
## Your Environment
* Plugin version: 1.10.3
* Platform: Android
* OS version: Android 11 (API level 30)
* Device manufacturer / model: Google Pixel 4
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale nl-NL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        notification: bg.Notification(
          title: 'TLN Uren actief (achtergrond)',
          text: 'Applicatie actief. Klik om te openen',
          largeIcon: 'mipmap/ic_notification',
          smallIcon: 'mipmap/ic_notification',
          sticky: true,
        ),
        locationAuthorizationRequest: 'Always',
        startOnBoot: true,
        stopTimeout: _configFacade.stopTimeout,
        desiredOdometerAccuracy: _configFacade.desiredOdometerAccuracy,
        logLevel: bg.Config.LOG_LEVEL_OFF,
        enableHeadless: true,
        debug: false,
        reset: kDebugMode,
      );
```

## Expected Behavior
I expect to see a persistent notification with the specified "mipmap/ic_notification" when the app is running in the background. 

## Actual Behavior
Instead of seeing a notification with the specified "mipmap/ic_notifcation" icon a notification with the default notification icon (a black or white dot depending on the dark/light theme) is shown (as seen in the screenshot below). This issue only occurs on my Google Pixel 4 running Android 11. On other devices, Samsung Galaxy S10+, Samsung Galaxy A70, Samsung Galaxy S8, I am not having this issue.

Google Pixel 4

![Google Pixel 4](https://user-images.githubusercontent.com/42604758/99231882-82344f80-27f1-11eb-9e61-331876d9311a.png)

Samsung Galaxy S10+ (second icon saying "uren")

![Samsung Galaxy S10+](https://user-images.githubusercontent.com/42604758/99233257-47331b80-27f3-11eb-8350-53505b4188cc.jpg)

## Steps to Reproduce

1. Create a new a new image asset as described [here](https://developer.android.com/studio/write/image-asset-studio)

![Resources folder](https://user-images.githubusercontent.com/42604758/99234801-4c916580-27f5-11eb-98ff-1fead474a797.png)

2. Configure the largeIcon and smallIcon fields in the bg.Config.notifcation to point to the newly created mipmap resource.
3. Enable headless mode, set stopOnTerminate to false
4. Open the app, and close it
5. Wait for the notification to show

## Context
I am trying to use a custom notification icon.
In the logcat I see the following exception occurring frequently:

D/skia (15037): --- Failed to create image decoder with message 'unimplemented' 

I am not sure if this is related to the issues described above, but when running the app without calling .ready() and .start() I do not see this exception in the logcat.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2020-11-16 13:07:52.378 30640-30640/com.data2track.tln_app W/TSLocationManager: [c.t.l.s.ForegroundNotification b] Failed to find notificationLargeIcon: mipmap/ic_notification
```

</details>

**Comment by christocracy** [comment]
Re-create your icon with transparency.

**Comment by Timo-Noordzee** [comment]
I've created a new icon with transparency. The issue still occurs.
The icon I originally used whilst testing had transparency too, so I don't think that that is the issue.

**Comment by christocracy** [comment]
This issue is your icon.  The text "uren" would have to be transparent cut-outs in the icon.  Recent versions of Android OS notification icons are monochromatic.

Here is the SampleApp icon on my *Pixel 3a @ 11*:

![](https://dl.dropbox.com/s/ldra811mqyumnqa/Screen%20Shot%202020-11-18%20at%209.05.06%20AM.png?dl=1)

**Comment by Timo-Noordzee** [comment]
I've managed to use a custom notification icon.
Initially, I tried using the app launcher icon and the notification icon, but since this icon isn't transparent I didn't work on my Android 11 device.

I've created a new icon as described [here ](https://developer.android.com/studio/write/image-asset-studio#create-notification )and it seems to be working fine now.
