### ISSUE TITLE
distanceFilter auto scaling

### ISSUE THREAD

**Issue by jbojcic1** [transistorsoft/flutter_background_geolocation#452]
I am looking at the docs for the distanceFilter property https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/distanceFilter.html

but two things are not clear to me and I can't find it in code to check so have to post here:

1.

> distanceFilter is auto-scaled by rounding speed to the nearest 5 m/s

if speed is 1.9 m/s will it be rounded to 0? if yes what happens in that case as multiplier is 0

2. what is the default value for the `elasticityMultipiler`? one maybe?

**Comment by christocracy** [comment]
> if speed is 1.9 m/s will it be rounded to 0? if yes what happens in that case as multiplier is 0

Of course not.  Elasticity isn't applied until speed > 5.

> what is the default value for the elasticityMultipiler

1
