### ISSUE TITLE
Reset config on app upgrade

### ISSUE THREAD

**Issue by jbojcic1** [transistorsoft/flutter_background_geolocation#460]
Since with reset: false, config passed to the ready method is only applied the first time user installs the app, does that mean that when the app is upgraded I need to manually reset/update the config if some configs are changed in the new version?

**Comment by christocracy** [comment]
>when the app is upgraded I need to manually reset/update the config if some configs are changed in the new version?

No.

**Comment by jbojcic1** [comment]
@christocracy seems different for us. On the prod for the user with id 5bf321aafda91362838cfde7

we are getting old app version in the location rq payload:

![Screen Shot 2020-12-07 at 10 15 50 AM](https://user-images.githubusercontent.com/10374826/101332457-9c53d180-3875-11eb-8ee5-77378d211693.png)

while I am sure the user has upgraded the app because I see it in our logs:

![Screen Shot 2020-12-07 at 10 16 53 AM](https://user-images.githubusercontent.com/10374826/101332541-b8f00980-3875-11eb-8463-97467be65521.png)

Here is our config after app upgrade:

```
bg.Config(
    // debug: true, // for debug purpose
    logLevel: isProd ? bg.Config.LOG_LEVEL_ERROR : bg.Config.LOG_LEVEL_VERBOSE,
    reset: false,
    url: "${EnvironmentConfig.API_URL}/api/courierLocation",
    httpRootProperty: '.',
    locationTemplate:
        '{"id":"<%= uuid %>","timeTakenUTC":"<%= timestamp %>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"speedMeters":<%= speed %>,"isMoving":<%= is_moving %>}',
    params: {
      'deviceOs':
          '${Platform.operatingSystem}:${Platform.operatingSystemVersion}',
      'appBuild': '${packageInfo.version}:${packageInfo.buildNumber}'
    },
    method: 'POST',
    desiredAccuracy: Platform.isIOS
        ? bg.Config.DESIRED_ACCURACY_NAVIGATION
        : bg.Config.DESIRED_ACCURACY_HIGH,
    stopTimeout: 5,
    stationaryRadius: 200,
    stopOnStationary: false,
    stopOnTerminate: false,
    startOnBoot: true,
    // Params were tuned using https://docs.google.com/spreadsheets/d/1iuAS1Qz87uwQrEibSk6wuNq1vymL0XKs3YKqF5yndbU#gid=1997201702
    distanceFilter: Platform.isAndroid ? 0 : 200.0,
    elasticityMultiplier: 2,
    maxRecordsToPersist: 5,
    enableHeadless: true, // android only
    notification: bg.Notification(
      sticky: true,
      smallIcon: 'mipmap/notification_icon',
      largeIcon: 'mipmap/notification_icon',
    ),
    showsBackgroundLocationIndicator: true, // ios only,
    locationAuthorizationRequest: 'Always',
  )
```

**Comment by christocracy** [comment]
>if some configs are changed in the new version?

Sorry, I misread this.  *Yes*, you will need to manually `setConfig` to apply new config options when using `reset: false`.

**Comment by jbojcic1** [comment]
Are there any drawbacks in just setting reset to true so it's reset on each app start? Will it stop the tracking if it's already started or something like that?

**Comment by christocracy** [comment]
>Are there any drawbacks in just setting reset to true

No.  Most people *should* use `reset: true` (the default).  The only reason this exists is for my `/example` app, which contains an advanced *Settings Screen*, allowing me to control the config with a UI while field-testing and not have the plugin reset to the default config supplied to `.ready` every time the app boots.

>Will it stop the tracking if it's already started or something like that?

No.

**Comment by jbojcic1** [comment]
Ok. Great. One more thing. Now that I do have it set with with reset: false in prod, do I need manual reset after the next upgrade where I will change it to reset: true?

**Comment by christocracy** [comment]
>do I need manual reset after the next upgrade where I will change it to reset: true?

With your next release, you will:

```
BackgroundGeolocation.ready({
  reset: true,  
  .
  .
  .
});
```

**Comment by jbojcic1** [comment]
Yes and if I do that it will pick up all the new configs at that moment and in the future?

**Comment by christocracy** [comment]
Of course it will.
