### ISSUE TITLE
Foreground Only Use

### ISSUE THREAD

**Issue by fne00** [transistorsoft/flutter_background_geolocation#461]
## Your Environment
* Plugin version: 1.10.3
* Platform: This issue relates to Android (but I am building for iOS as well)
* OS version: All
* Device manufacturer / model: All
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] Connected device (3 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      bgConfigToApply = bg.Config(  // more aggressive recording - no turn off
          persistMode: bg.Config.PERSIST_MODE_NONE,
          locationAuthorizationRequest: 'WhenInUse',
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 0.0,
          // no min distance
          locationUpdateInterval: 0,
          // no min time
          fastestLocationUpdateInterval: 200,
          // 200mS max rate of new data points - 0 is not recommended
          useSignificantChangesOnly: false,
          stopOnTerminate: true,
          // will stop recording when crash/terminate
          startOnBoot: false,
          foregroundService: true,
          // Android only - defaults to true for >Android 8.0 - mandatory
          enableHeadless: false,
          // Ignored because I have stopOnTerminate
          disableStopDetection: true,
          pausesLocationUpdatesAutomatically: false,
          //stopTimeout: 10,
          // 10 mins - if stationary for >10mins stops until movement is detected again
          debug: false,
          autoSync: false,
          params: loggingData,
          logLevel: logLevel,
          logMaxDays: 2,
          reset: true);
```

## Expected Behavior

I thought(was hoping) that because the App is built to target SDK 30 and does NOT have ACCESS_BACKGROUND_LOCATION in the Manifest, that I would be considered to be only using location in the foreground.
That is, using the foregroundService approach in flutter_background_geolocation, which I believe would be consistent with Google’s recommended approach  (Google sample at https://developer.android.com/training/location/request-updates (ie https://github.com/android/location-samples/tree/432d3b72b8c058f220416958b444274ddd186abd/LocationUpdatesForegroundService) for a foreground service based approach.)

## Actual Behavior

Google flagged my App as non-compliant and wanted a “Location Permissions Declaration Form” completed, which is targeted at explaining why I need background location access.

Upon examining the Android App Bundle details I see it does request android.permission.ACCESS_BACKGROUND_LOCATION, android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION

## Steps to Reproduce

Build release aab and submit for Closed Testing.

## Context

Users of the MapRunF run it for the specific purpose of recording their track and matching their location to specific control points in the sport of Orienteering. The App records their location from when they open the screen that displays the map and course, and finishes when the GPS detects they have reached the finish (or they exit the screen). The App does not record their location before or after this. During the run, the track recording (and the functions of the app) need to continue if the user opens another App (taking focus away from this App) or the screen blanks.  

Questions regarding the best way to achieve Google approval:
- Is there a way to uses flutter_background_geolocation in foreground service mode only? If so, I’m thinking that android.permission.ACCESS_BACKGROUND_LOCATION, would not be requested and so Google would be happy that I am not using location in the background
- Otherwise, and I recognise that this is a “Background Geolocation” package, I respond to Google’s Location Permissions Declaration Form. In which case, if I only request locationAuthorizationRequest: 'WhenInUse' am I correct to say:
- When using flutter_background_geolocation with ‘WhenInUse’ the App operates in a similar way to Google example of LoctiionUpdatesForegroundService
- The plugin will not be using location in the background
They want a short video, and I think all I can show is something that says… I’m not actually using background location, I’m only requesting ‘WhenInUse’ and here is the AppBar Notification being displayed by the foreground service.

Please set me straight if I am misunderstanding something or missing something. Any help would be appreciated.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you seen my [latest blog post](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353)?

Yes, the plugin does automatically include the `ACCESS_BACKGROUND_LOCATION` in your app's `AndroidManifest`.

**Comment by fne00** [comment]
Chris
Thanks for the quick response. I hadn't picked up on the remove background location item at the end of the post.

Just to clarify, the blog says remove `android.permission.BACKGROUND_LOCATION` and my App bundle is saying it is requesting:
`android.permission.ACCESS_BACKGROUND_LOCATION`. Should be using the `tools:node="remove"` on the later (or both)? Peter

**Comment by christocracy** [comment]
My blog had a mistake.  It is corrected now.

**Comment by DevanshBhatt24** [comment]
background geolocation get turned off after sometime if the app is in background even when battrey optimization is turned off in vivo and starts again when you open the app. How can i fix it?

**Comment by DevanshBhatt24** [comment]
@christocracy background geolocation get turned off after sometime if the app is in background even when battrey optimization is turned off in vivo and starts again when you open the app. How can i fix it?
