### ISSUE TITLE
Unhandled Exception: PlatformException(499, null, null, null)

### ISSUE THREAD

**Issue by FirdousNath** [transistorsoft/flutter_background_geolocation#463]
## Your Environment
* Plugin version: 1.10.3
* Platform: Android
* OS version:
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`):Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-KW)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      triggerActivities: 'on_foot, walking, running, in_vehicle, on_bicycle',
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      speedJumpFilter: 40,
      distanceFilter: 10.0,
      stopOnTerminate: true,
      startOnBoot: false,
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start().then((value) {
          initialMap().then((value) {
            polylinePoints = PolylinePoints();
            // set custom marker pins
            setSourceAndDestinationIcons();
          });
        });
      }
    });

  Future<void> initialMap() async {
      bg.Location userLocation =
      await bg.BackgroundGeolocation.getCurrentPosition(
        timeout: 30,
        // 30 second timeout to fetch location
        maximumAge: 2000,
        // Accept the last-known-location if not older than 5000 ms.
        desiredAccuracy: 10,
        // Try to fetch a location with an accuracy of `10` meters.
        samples: 3, // How many location samples to attempt.
      );
    currentLocation = userLocation.coords; 
}
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(499, null, null, null)
E/flutter (19061): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (19061): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (19061): <asynchronous suspension>
E/flutter (19061): #2      BackgroundGeolocation.changePace (package:flutter_background_geolocation/models/background_geolocation.dart:425:12)
E/flutter (19061): <asynchronous suspension>
```

</details>

**Comment by christocracy** [comment]
499 = location request cancelled.  If you don't want to see that exception, wrap your `await bg.BackgroundGeolocation.getCurrentPosition` in a `try / catch` block.

**Comment by FirdousNath** [comment]
but what causing that exception?

**Comment by christocracy** [comment]
A location was requested then told to cancel.
