### ISSUE TITLE
solution for calculate waiting time

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#464]
Is there any way to get a waiting time when traveling? 

**Example**: Imagine, there are two buttons on my app. (Trip Start and Trip End). I set 0 to `setOdometer` when starting the trip. `odometer` means total meter. right? And also I want to show the waiting time in real-time. waiting time means a driver in traffic on the road or car is stopped. I hope you can understand the mean of waiting time.

**Example2** - I think, I am looking for this kind of logic.

```
void CalculateOdometer() {
   if(odometer logic) {
      odometer += some value;
   } else {
      waitingTime += some value;
   }
}
```

**Comment by christocracy** [comment]
I don't understand.

**Comment by bhanuka96** [comment]
@christocracy Thank you for the reply, I updated my question

**Comment by bhanuka96** [comment]
@christocracy Did you have time to check it?

**Comment by christocracy** [comment]
Are you aware the plugin already calculates `odometer` at `location.odometer`.

Perhaps you're interested in the event `onActivityChange`.   See the API docs.

**Comment by bhanuka96** [comment]
yes, I already used 'odometer'. Our QA team complains there is a 100-200 meters difference on the odometer. Is there any chance to happen?


Can you give your feedback on these two methods to calculate the waiting time? (Which one is correct?)

// method 1
```
 bg.BackgroundGeolocation.onActivityChange((event) {
      //'still' mean, 
      if(event.activity == 'still' || event.activity == 'on_foot' ||event.activity == 'walking'){
        // waiting time stop watch play
      }else{
        // waiting time sop watch pause
      }
    });
```


// method 2

```
     if (userLocation?.speed <= 1.3 :  0.2) {
         // waiting time stop watch play
      } else {
        // waiting time sop watch pause
      }
```
