### ISSUE TITLE
How to push data to firebase using plugins http?

### ISSUE THREAD

**Issue by ubitechdevelopers** [transistorsoft/flutter_background_geolocation#466]

**Comment by christocracy** [comment]
Perhaps you're interested in the [plugin's Firebase Adapter](https://github.com/transistorsoft/flutter_background_geolocation_firebase)

**Comment by ubitechdevelopers** [comment]
Do I need to have a separate license for the purpose? Or the license for flutter_background_geolocation will suffice?

**Comment by christocracy** [comment]
You need to purchase a separate license for Firebase adapter.

Otherwise, it's up to you to implement your own custom Firebase code.

**Comment by ubitechdevelopers** [comment]
We already purchased five license for flutter background geolocation. Purchasing another is not fare. Can't we use one of the flutter background geolocation license for the adaptor and if not Please specify where to purchase it

**Comment by christocracy** [comment]
>Purchasing another is not fare. 

You don't have to use the optional Firebase adapter.  You're free to implement your own firebase code using existing Flutter Firebase plugins.

>Can't we use one of the flutter background geolocation license for the adaptor 

No. The firebase adapter is an optional **add-on for** `flutter_background_geolocation`

>and if not Please specify where to purchase it

See README of [flutter_background_geolocation_firebase](https://github.com/transistorsoft/flutter_background_geolocation_firebase)

![](https://dl.dropbox.com/s/beyzzii534r2q8k/Screen%20Shot%202020-12-07%20at%2011.21.22%20AM.png?dl=1)
