### ISSUE TITLE
setOdometer error

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#468]
I want to set 0 to odomoeter. But every time I got `499` error.

```
void tripStart() {
    userLocation = await getCurrentLocation();
    await setOdometer();
    await start();
}


  Future<void> start() async {
    await bg.BackgroundGeolocation.start().then((value) {
      return value;
    }).catchError((e) {
      print('start Error : $e');
      return;
    });
    return;
  }

  Future getCurrentLocation() async {
    return bg.BackgroundGeolocation.getCurrentPosition(desiredAccuracy: 10, maximumAge: 1000, timeout: 30, samples: 3, extras: {"getCurrentPosition": true}).then((value) {
      return value;
    }).catchError((e) {
      print("Get Location Error : $e");
      return;
    });
  }


  Future<void> setOdometer({double value = 0}) async {
    return bg.BackgroundGeolocation.setOdometer(value.toDouble()).then((v) {
      return v;
    }).catchError((e) {
      print('set Odometer Error : $e');
      return;
    });
  }
```

**Comment by christocracy** [comment]
Why do you do this?  Do you know that `setOdometer` executes `getCurrentPosition` internally.  It does essentially the same thing.  Read the API docs.  Get rid of this `userLocation = await getCurrentLocation()`.

```
userLocation = await getCurrentLocation();
await setOdometer();
```

**Comment by bhanuka96** [comment]
@christocracy Thanks for the reply. It's means, when I called this it's already set `0`. right?

`userLocation = await getCurrentLocation();`

**Comment by christocracy** [comment]
>Thanks for the reply. It's means, when I called this it's already set 0. right?

Why do you think that?

**Comment by bhanuka96** [comment]
> > Thanks for the reply. It's means, when I called this it's already set 0. right?
> 
> Why do you think that?

what is this meaning? `setOdometer executes getCurrentPosition internally` 

I just want to clear `odometer` when trip start

**Comment by christocracy** [comment]
>what is this meaning?

It means that when you call `setOdometer`, the plugin executes `getCurrentPosition` internally then says "this is the location where the odometer has been zeroed.

`setOdometer` = `getCurrentPosition` + reset odometer to 0.  Look at the [API docs for `setOdometer`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/setOdometer.html).

```dart
bg.Location location = await bg.BackgroundGeolocation.setOdometer(0);
print("[setOdometer] current location where odometer was set to 0: $location");
```

```

**Comment by bhanuka96** [comment]
> > what is this meaning?
> 
> It means that when you call `setOdometer`, the plugin executes `getCurrentPosition` internally then says "this is the location where the odometer has been zeroed.
> 
> `setOdometer` == `getCurrentPosition` + reset odometer to 0. Look at the [API docs for `setOdometer`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/setOdometer.html).
> 
> ```dart
> bg.Location location = await bg.BackgroundGeolocation.setOdometer(0);
> print("[setOdometer] current location where odometer was set to 0: $location");
> ```

Thank you so much
