### ISSUE TITLE
how to get location every one-second in onLocation?

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#469]
Is it possible to get every one-second location in onLocation? 

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      if(location?.coords != null){
       userLocation = location;
      }
    }, (bg.LocationError error) {
      print("Location Error : $error");
    });

```
  void configure() async {
    bg.TransistorAuthorizationToken token = await bg.TransistorAuthorizationToken.findOrCreate('myOrgName', 'myUserName', 'http://tracker.transistorsoft.com');

    bg.BackgroundGeolocation.ready(bg.Config(
      // Geolocation Options
      desiredAccuracy: Platform.isIOS ? bg.Config.DESIRED_ACCURACY_NAVIGATION : bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0.0,
      locationTimeout: 1,
      persistMode: 1,
      desiredOdometerAccuracy: 10,
      stationaryRadius: 0,
      foregroundService: true,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      transistorAuthorizationToken: token,
      debug: !(env.flavor == BuildFlavor.production),
      logLevel: env.flavor == BuildFlavor.production ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
      notificationPriority: env.flavor == BuildFlavor.production ? -2 : 1,
      //Ios Options
      showsBackgroundLocationIndicator: env.flavor == BuildFlavor.production,
    )).then((bg.State state) {
      if (!state.enabled) {
        start();
      }
    });
  }
```

```
  Future<void> start() async {
    await bg.BackgroundGeolocation.start().then((value) {
      return value;
    }).catchError((e) {
      print('start Error : $e');
      return;
    });
    return;
  }
```

**Comment by christocracy** [comment]
See API docs `Config.locationUpdateInterval`.

>locationTimeout: 1,

That's an awfully short location timeout, don't you think?

**Comment by bhanuka96** [comment]
@christocracy can you check my comment here https://github.com/transistorsoft/flutter_background_geolocation/issues/464#issuecomment-736961328. I want to calculate the waiting time when travelling, I am using method 2 for that. So, I need `speed`  every one-second for that. that's why I set 'locationTimeout : 1'

**Comment by christocracy** [comment]
You do not understand what `locationTimeout` is.  Please read the API docs.

I have no idea what your "waiting time" is.

**Comment by bhanuka96** [comment]
> You do not understand what `locationTimeout` is. Please read the API docs.
> 
> I have no idea what your "waiting time" is.

"waiting time" means, How long you wait (you are in traffic on the road or you stop the vehicle) while you were traveling.

**Comment by bhanuka96** [comment]
@christocracy how to return Location every one-second in 'onLocation'? Is it possible?

**Comment by christocracy** [comment]
As I said, see API docs `Config.locationUpdateInterval`

**Comment by bhanuka96** [comment]
@christocracy Now, it's working,

I forgot to add 'changePace'

When trip Start

```
    await bgService?.stop();
    await bgService?.start();
    bgService?.onClickChangePace(true);
    userLocation = await bgService.setOdometer();
```

When trip end

```
      userLocation = await bgService.setOdometer();
      bgService?.onClickChangePace(false);
      await bgService.stop();
```

**Comment by bhanuka96** [comment]
It's working now https://github.com/transistorsoft/flutter_background_geolocation/issues/469#issuecomment-738705115
