### ISSUE TITLE
Odometer not calculate on some devices

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#471]
The odometer is not calculated on my app, not only my app but also the demo app. Always 0. I set 1000 to `locationUpdateInterval`. And It looks like more than and equal 5000, not 1000 on this same device.

**The device Model is J700F**

My Configuration

```
    bg.BackgroundGeolocation.ready(bg.Config(
      // Geolocation Options
      desiredAccuracy:bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0.0,
      locationUpdateInterval: 1000,
      locationTimeout: 60,
      persistMode: 1,
      desiredOdometerAccuracy: 10,
      stationaryRadius: 25,//0,
      foregroundService: true,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      allowIdenticalLocations: true,
      useSignificantChangesOnly: false,
      transistorAuthorizationToken: token,
      debug: kDebugMode,
      logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
      notificationPriority: kReleaseMode ? -2 : 1,
      showsBackgroundLocationIndicator: kDebugMode,
      locationAuthorizationRequest: 'Always',

    )).then((bg.State state) {
      if (!state.enabled) {
        start();
      }
    });
```

**Comment by christocracy** [comment]
Some devices are simply bad, and the *Samsung J* series is one of them.  See [Samsung J700F](https://www.gsmarena.com/samsung_galaxy_j7-7185.php).  These devices are built to be inexpensive.  They are not well-suited to location-tracking use-cases.

This device was released in 2015 and does not have a *Gyroscope* or *Magnetometer* (only an accelerometer).

**Comment by bhanuka96** [comment]
@christocracy Thank you for the quick reply. It's mean, there is no solution for this kind of devices right?

**Comment by christocracy** [comment]
The plugin does the best it can with the hardware available on the device.  Most modern phones contain all three motion sensors (accelerometer + gyroscope + magnetometer).

**Comment by bhanuka96** [comment]
@christocracy Thank you for your comment
