### ISSUE TITLE
app reject by google play store

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#477]
I didn't add background permission on my manifest. why reject?

**Background location access not declared  We detected that your app contains at least one feature that requests  access to location in the background, however  your permission  declaration form did not reflect this. Please log in to your Play  Console to resubmit your location declaration form. You may either remove location in the background from your app or indicate that the usage is in the background.**

**my manifest**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.name.dev">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:label="@string/app_name"
        android:resizeableActivity="false"
        android:requestLegacyExternalStorage="true"
        tools:replace="android:label"
        android:icon="@mipmap/ic_launcher">
        <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
        <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="@string/bgApplicationKey"/>
        <meta-data
            android:name="com.google.firebase.ml.vision.DEPENDENCIES"
            android:value="ocr" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_maps_api_key"/>
        <!-- To use multiple models: android:value="ocr,label,barcode,face" -->
        <activity
            android:name="com.name.dev.MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by bardiauto** [comment]
If you use this package, it automatically merge ACCESS_BACKGROUND_LOCATION permission to your manifest as dependency.   My question: is it possible to build bundles without this permission, because currently we are not those kind of features (geofencing, or headless implementaion) that requires this permission? Our application's tracking is stopping on terminate.

If it's not possible, then we must fill the Google's background location form until 18 Jan.

Thank you for your answer, 
Csaba

**Comment by christocracy** [comment]
The plugin contains its own AndroidManifest, containing all its required permissions, which is automatically merged into your app's AndroidManifest.

See my latest blog:

https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353

**Comment by bhanuka96** [comment]
I followed this article and submit it again. Again rejected by google. Alert is not displayed when `start` service. I think that's why google rejected.

my config

```
  void configure() async {
    bg.TransistorAuthorizationToken token = await bg.TransistorAuthorizationToken.findOrCreate('orel', 'name', 'http://tracker.transistorsoft.com');

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy:bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0.0,
      locationUpdateInterval: 1000,
      locationTimeout: 60,
      persistMode: 1,
      desiredOdometerAccuracy: 10,
      stationaryRadius: 25,
      foregroundService: true,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      allowIdenticalLocations: true,
      useSignificantChangesOnly: false,
      transistorAuthorizationToken: token,
      debug: kDebugMode,
      logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
      notificationPriority: kReleaseMode ? -2 : 1,
      showsBackgroundLocationIndicator: kDebugMode,
      locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: PermissionRationale(
            title: "Allow MYAPP to access to this device's location in the background?",
            message: "In order to track your activity in the background, please enable \"Allow all the time\" location permission",
            positiveAction: "Change to \"Allow all the time\"",
            negativeAction: "Cancel"
        )

    )).then((bg.State state) {
      if (!state.enabled) {
        start();
      }
    });
  }
```

**Comment by christocracy** [comment]
>Again rejected by google

For what *reason*?

**Comment by bhanuka96** [comment]
@christocracy same reason

**Comment by christocracy** [comment]
So this?

>We detected that your app contains at least one feature that requests access to location in the background, however  your permission declaration form did not reflect this. Please log in to your Play Console to resubmit your location declaration form. You may either remove location in the background from your app or indicate that the usage is in the background.

**Comment by christocracy** [comment]
You are responsible for displaying **YOUR OWN** prominent disclosure alert.  The plugin does not do that.  See my blog post again where I *specifically* mention the *Prominent disclosure* alert.

The [/example app in this repo shows a simple `AlertDialog` for this](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/lib/app.dart#L136-L163)

**Comment by bhanuka96** [comment]
@christocracy Rejected 3 times after the above issue fixed. Now they said, 

<img width="610" alt="Screenshot 2020-12-21 at 09 40 55" src="https://user-images.githubusercontent.com/34953062/102738676-d9898a80-4370-11eb-9da3-c3199c6e241b.png">

**Comment by christocracy** [comment]
Your app's *privacy policy* has nothing at all to do with background-geolocation.

This is a general statement you must publicly state on your website as noted in the rejection mail.  Just follow the instructions.

My [demo app's privacy policy](https://www.transistorsoft.com/privacy_policy).

**Comment by bhanuka96** [comment]
Thank you for your help

**Comment by bhanuka96** [comment]
@christocracy Thanks for your support. the app is published it now
