### ISSUE TITLE
App asks for "Physical Activity" permissions

### ISSUE THREAD

**Issue by oggam** [transistorsoft/flutter_background_geolocation#478]
Hi,

we're using this library for almost one year and suddenly (without any version updates) our app asks for physical activity permissions on **Android**. It's definitely NOT defined in our Manifest file and the "**disableMotionActivityUpdates**" is set to true. It does happen randomly, so we are not able to reproduce it - so I have no logs, sadly. So, I kindly ask you to check if or how this could happen - maybe it's an obvious bug. Or maybe also other users experienced this issue already. 

We'll definitely keep an eye on it and I'll update my infos as soon as I can reproduce it. We're using version 1.10.1.

Thanks in advance!

**Comment by christocracy** [comment]
You must have some *other* library requesting motion permission.  With `disableMotionActivityUpdates: true`, the plugin will **not** request *Physical Activity* permission.  You can see this in the logs.

>It's definitely NOT defined in our Manifest file

The plugin has its own `AndroidManifest` which is automatically merged into your app's `AndroidManifest`.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.transistorsoft.tslocationmanager">

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.GET_TASKS" />

    <!-- device-specific permissions for DeviceSettings methods -->
    <uses-permission android:name="oppo.permission.OPPO_COMPONENT_SAFE"/>
    <uses-permission android:name="com.huawei.permission.external_app_settings.USE_COMPONENT"/>

    <uses-feature android:name="android.hardware.location.gps" android:required="false" />

    <application>

        <activity
            android:name="com.transistorsoft.locationmanager.activity.TSLocationManagerActivity"
            android:excludeFromRecents="true"
            android:launchMode="singleInstance"
            android:theme="@style/TSLocationManagerActivity" />

        <service android:name="com.transistorsoft.locationmanager.service.TrackingService" />
        <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" />
        <service android:name="com.transistorsoft.locationmanager.service.HeartbeatService" />
        <service android:name="com.transistorsoft.locationmanager.service.ActivityRecognitionService" />
        <service android:name="com.transistorsoft.locationmanager.service.GeofencingService" />
        <service android:name="com.transistorsoft.locationmanager.service.BackgroundTaskService" />

        <receiver android:name="com.transistorsoft.locationmanager.scheduler.ScheduleAlarmReceiver" android:exported="false" />
        <service android:name="com.transistorsoft.locationmanager.scheduler.ScheduleService" />
        <service android:name="com.transistorsoft.locationmanager.scheduler.ScheduleJobService" android:permission="android.permission.BIND_JOB_SERVICE" />
        <receiver android:name="com.transistorsoft.locationmanager.BootReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>

        <provider
            android:name="com.transistorsoft.locationmanager.util.LogFileProvider"
            android:authorities="${applicationId}.tslocationmanager.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/tslocationmanager_file_provider_path" />
        </provider>

    </application>
</manifest>
```

**Comment by christocracy** [comment]
> we're using this library for almost one year and suddenly (without any version updates) our app asks for physical activity

Android 10 [made change to *Physical Activity* permission](https://android-developers.googleblog.com/2019/11/privacy-protections-for-physical.html), now requiring run-time permission from the user.

![](https://dl.dropbox.com/s/sck9a245ps9l53g/Screen%20Shot%202020-12-16%20at%208.28.06%20AM.png?dl=1)

**Comment by oggam** [comment]
Thank you for your quick answer.

We checked all permissions of other libraries again but we haven't found it somewhere else. It's definitely a very very rare case (only happened once so far) but it seems to come from your library. Anyway we found a workaround to be on safe side: We're now removing the Physical Activity permission after merging Manifest. So the permission isn't shown anymore in settings of the app (on the phone) and so we're to 100% sure that it won't appear anymore.

Thanks and KR

**Comment by christocracy** [comment]
You were probably calling `requestPermission` before `ready` resolved.  The default value of `disableMotionActivityUpdates` is `false`.

If you execute `requestPermission` before your Config is applied through `ready`, the plugin will request Motion permission.

**Comment by sohamD07** [comment]
@christocracy, can we customize the popup message for physical activity permission?
