### ISSUE TITLE
Authorization via Future<String> callback instead of Authorization class config

### ISSUE THREAD

**Issue by draganjovanovic1** [transistorsoft/flutter_background_geolocation#480]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
no code, this is feature request... environment is irrelevant
```

## Expected Behavior

Could you implement authorization in the way e.g. graphql_flutter library does, by providing `Future<String> getToken` callback

GraphQL lib way:
```
    AuthLink authLink = AuthLink(
      getToken: () async {
        var token = await FirebaseAuth.instance.currentUser.getIdToken();
        return 'Bearer $token';
      },
    );
```

Example:
```
bg.BackgroundGeolocation.ready(bg.Config(
    getAuthToken: () async {
        var token = await FirebaseAuth.instance.currentUser.getIdToken();
        return 'Bearer $token';
    }));
```

## Actual Behavior

In order to use auto sync built in the library and use e.g. FIrebase Auth SDK it is not possible to configure Authorization since internals (URLs and so on) of the Firebase implementation are not known to a developer using it. 

## Context

Use auto sync feature in more simple and extendable way.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Why don't you just `await` your token *before* `ready`, and provide it to the `Config` as documented?

**Comment by draganjovanovic1** [comment]
Token can change during the execution. It expires.

**Comment by christocracy** [comment]
Listen to onHttp event for `401` response.  That's your cue to fetch new token and update with `setConfig`.

**Comment by draganjovanovic1** [comment]
Thanks for the quick reply. I knew about that approach but I wanted to propose the feature which I see more friendly and clear to use and is also more aligned with the other popular libraries approach. If you are willing to think about it, it would be nice, otherwise feel free to close the issue.

**Comment by christocracy** [comment]
It cannot be implemented as you've shown.  This plugin is designed to operate while terminated.  Your `getAuthToken` method will no longer exist in the terminated state.

**Comment by draganjovanovic1** [comment]
Understood. It is not possible by design so feature request should be closed. I will try to go with the `onHttp` approach. Is it possible to set config values partially? 

LIke this:

```
    bg.BackgroundGeolocation.onHttp((event) async {
      if (event.status == 401) {
        var token = await FirebaseAuth.instance.currentUser.getIdToken();
        bg.BackgroundGeolocation.setConfig(
            bg.Config(authorization: bg.Authorization(accessToken: 'Bearer $token')));
      }
    });
```

Doing this in the foreground as well as in the headless implementation should be sufficient to get the desired behaviour?

**Comment by christocracy** [comment]
Yes, it's fine but you need not be using the `Authorization` Config (that option is designed for automatically sending a request to a server `refreshUrl`).  Just apply it to `Config.headers`.

**Comment by draganjovanovic1** [comment]
Thanks.

**Comment by draganjovanovic1** [comment]
@christocracy I am struggling to find sample payload for the batch upload. Can you please help me with it? Thanks.

**Comment by draganjovanovic1** [comment]
Disregard, I caught it on the server side.
