### ISSUE TITLE
Getting a lot of wrong coordinates through HTTP service

### ISSUE THREAD

**Issue by alien190** [transistorsoft/flutter_background_geolocation#481]
## Your Environment
* Plugin version: 1.10.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung dreamlte
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        desiredOdometerAccuracy: 30,
        distanceFilter: 0,
        disableElasticity: true,
        stationaryRadius: 25.0,
        locationUpdateInterval: 3000,
        forceReloadOnLocationChange: false,
        forceReloadOnMotionChange: false,
        activityRecognitionInterval: 0,
        foregroundService: true,
        allowIdenticalLocations: false,
        fastestLocationUpdateInterval: 1000,
        heartbeatInterval: 60,
        pausesLocationUpdatesAutomatically: false,
        stopOnTerminate: false,
        speedJumpFilter: 30,
        stopOnStationary: false,
        logLevel: Config.LOG_LEVEL_VERBOSE,
        enableHeadless: true,
        url: "https://our_url",
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 50,
        headers: {"AUTHENTICATION_TOKEN": hash},
        locationsOrderDirection: "ASC",
        maxDaysToPersist: 14,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': LocaleKeys.locationServiceNotEnabled.tr(),
          'titleWhenOff': LocaleKeys.locationServiceOFF.tr(),
          'instructions': LocaleKeys.pleaseEnableAlwaysLocationService.tr(),
          'cancelButton': LocaleKeys.cancel.tr(),
          'settingsButton': LocaleKeys.settings.tr(),
        },
        locationAuthorizationRequest: 'Always',
        notification: Notification(
            layout: "my_notification_layout_new",
            priority: Config.NOTIFICATION_PRIORITY_MIN,
            channelName: "fitness app",
            title: "fitness_app",
            text: "",
            sticky: true,
            smallIcon: "mipmap/ic_launcher",
            largeIcon: "mipmap/ic_logo"),
      ),
);
```

## Expected Behavior
Getting coordinates through HTTP service with more accuracy, perhaps that are used to calculate odometer value.

## Actual Behavior
Here are coordinates that were recived througth HTTP service
https://drive.google.com/file/d/1Ohc8PiVke5y8D3ci9qj7nIGM4twMdCrJ/view?usp=sharing

The distance that is calculated on this track by coordinates is around 30 km. But the odometer value at the end is 7.5 km which looks right.

## Context
We try to build fitness app for runners and bicycles that calculates correct distance from start point and automatically stops tracking on a given distance to get time of activity. Also the app sends coordinates to the server to visualize routes.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Unfortunately, we don't have any logs because this was an end user device.
```

</details>

**Comment by christocracy** [comment]
Those are not "wrong" coordinates, they're the best that device could provide at that time.  You will likely see correspondingly poor `location.coords.accuracy` on those locations.

**Comment by alien190** [comment]
Thanks for the rapid reply.
As I understand the plugin's logic if on the server-side the coordinates which contain location.coords.accuracy > desiredOdometerAccuracy will be dropped, will the coordinates be the same as the plugin uses to calculate distance?

**Comment by christocracy** [comment]
>will be dropped

No, they won't be "dropped".  Those location will simply not be used to increment the odometer.

The odometer works by keeping a running total of distance from `currentLocation` to `lastLocation`

eg: (pseudo code)

```javascript
if (currentLocation.accuracy <= config.desiredOdometerAccuracy) {
  odometer += currentLocation.distanceTo(lastOdometerLocation)
  lastOdometerLocation = currentLocation
}
```

**Comment by alien190** [comment]
Thanks for the clarifications.

> will be dropped

I meant if I drop these locations on a server-side to not show on the map (https://drive.google.com/file/d/1Ohc8PiVke5y8D3ci9qj7nIGM4twMdCrJ/view?usp=sharing).

Does the plugin have the opportunity to not send coordinates via HTTP with poor accuracy like this:

```
if (currentLocation.accuracy <= config.desiredHTTPAccuracy) {
  sendViaHTTP(currentLocation)
}
```

**Comment by christocracy** [comment]
No.  The plugin will send all locations to the server for you to judge as desired.
