### ISSUE TITLE
http post URL with port

### ISSUE THREAD

**Issue by slaniado** [transistorsoft/flutter_background_geolocation#483]
## Your Environment
* Plugin version: 1.10.3
* Platform: iOS 

## Expected Behavior
That the URL accept port.

## Actual Behavior
In the configuration I am using a URL with port like this:
http://test.com:3001/locations
And the request are not getting to the server.
I tried also without the port and the locations are getting fine.

## Logs
[onHttp] status: 0, success? false, responseText:

**Comment by christocracy** [comment]
Yes, it works with port.  I often test against a dev server running on port 9000.

**Comment by slaniado** [comment]
ok Chris i will make an other test.
Thank You
