### ISSUE TITLE
how to show live tracking position live on captain  app 

### ISSUE THREAD

**Issue by heshesh2010** [transistorsoft/flutter_background_geolocation#484]
Hi , 

i want to ask , how to show and get live location on other app such as uber captain , 

you examples shows only how to get location and send it to http service , but in other hand i want to track this location live on other app as well .

**Comment by christocracy** [comment]
Sorry, that is not a relevant question to ask here.  That is a general software engineering question that would depend upon the technologies you're using in your environment.
