### ISSUE TITLE
location not moving automatically at web app demo 

### ISSUE THREAD

**Issue by heshesh2010** [transistorsoft/flutter_background_geolocation#485]
Hi ,  

i have test the free demo here : http://tracker.transistorsoft.com/topline it works , but i have to hit reload button every time to get last location for user ,  

is there is any way to make it automatically track live location when user moves ?

**Comment by christocracy** [comment]
Questions about the demo app hosted at `tracker.transistorsoft.com` are irrelevant here at the background-geolocation repo.

The demo server is a free and open-source project at https://github.com/transistorsoft/background-geolocation-console
