### ISSUE TITLE
Question: What is the most aggressive config to get most frequent locations (I don't care about the battery life)?

### ISSUE THREAD

**Issue by draganjovanovic1** [transistorsoft/flutter_background_geolocation#487]
## Your Environment
Environment irrelevant, just a question.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    await bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter < 0.1 ? 5.0 : distanceFilter,
        disableElasticity: disableElasticity,
        locationUpdateInterval: locationUpdateIntervalSec == 0
            ? 15 * 1000
            : locationUpdateIntervalSec * 1000,
        maxRecordsToPersist:
            maxRecordsToPersist == 0 ? 200 : maxRecordsToPersist,
        maxDaysToPersist: 5,
        allowIdenticalLocations: false,
        heartbeatInterval: 30,
        enableHeadless: true,
        foregroundService: true,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true,
        autoSync: true,
        url: trackingBloc.trackingUrl,
        method: 'POST',
        batchSync: true,
        maxBatchSize: UploadBatchSize,
        locationsOrderDirection: 'ASC',
        locationAuthorizationRequest: 'Always',
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification:
            bg.Notification(smallIcon: 'drawable/ic_stat_notification_icon')));
```

I searched through the properties and docs and found that this set of properties might affect:
```dart
        activityRecognitionInterval: 0,
        stopOnStationary: false,
        isMoving: true,
        stationaryRadius: 25,
        reset: true, // if I understood correctly without this config is not forced each time on ready but since I have some dynamically loaded properties from the remote config should I use this?
```

## Actual Behavior

iOS stationary geofence could lead to issues as it takes a while to detect motion sometimes leading in several hundred of meters without driver's location. This is by the docs and reflects what is written there but I am curious if I can make the tracking lib be more aggressive.

## Context

I am using the lib as a part of the driver app so the most precise and frequent location is required regardless of the battery optimization.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
If the driver wants to initiate tracking, you can offer a UI button (eg: `[Start]`) where you execute `BackgroundGeolocation.changePace(true)` to manually place the plugin into the *moving* state.

**Comment by draganjovanovic1** [comment]
My scenario is to start tracking, with the config above, as soon as driver logs in the app and the idea is to track driver as long as he is logged in the app even if it is in the background. Tracking is being stopped on logout. There should be no manual action by the driver.

My issue is that the library sometimes takes too long to react on a movement, especially on iOS which is described and understood. The library has the idea to be energy efficient and it is perfectly valid but not for my use case so I wanted to check if there are any additional flags which can make it more aggressive in terms of tracking regardless of the battery life. 

Thanks and happy holidays!

**Comment by christocracy** [comment]
- The simplest thing to do is set `Config.stopTimeout` to a very high number.
- See `Config.pausesLocationUpdatesAutomatically`, `Config.disableStopDetection`
