### ISSUE TITLE
The access token is not used if multiple jwt tokens are provided in the Authorization response

### ISSUE THREAD

**Issue by MilesAdamson** [transistorsoft/flutter_background_geolocation#488]
## Your Environment
* Plugin version: 1.10.1
* Platform: iOS + Android
* OS version: All
* Device manufacturer / model: All
* Flutter info (`flutter doctor`):

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    return gps.Config(
        extras: await buildExtrasMap(),
        headers: {"user-agent": await ApiVersion.userAgent},
        heartbeatInterval: HEARTBEAT_INTERVAL_SECONDS,
        preventSuspend: true,
        url: "${Application.apiBaseUrl()}/units/$unitId/location",
        authorization: buildAuthorization(accessToken, refreshToken, subDomain),
        desiredAccuracy: gps.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,
        allowIdenticalLocations: false,
        stopOnTerminate: false,
        disableStopDetection: true,
        startOnBoot: true,
        pausesLocationUpdatesAutomatically: false,
        maxDaysToPersist: 1,
        maxRecordsToPersist: 3,
        batchSync: true,
        stationaryRadius: 25.0,
        enableHeadless: true,
        debug: !kReleaseMode,
        useSignificantChangesOnly: false,
        autoSync: true,
        logLevel: gps.Config.LOG_LEVEL_ERROR,
        reset: true,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Set Location to "Always"',
          'titleWhenOff': 'Set Location to "Always"',
          'instructions':
              'Your phone\'s location is required to be set to "Always" while you\'re logged in. \n\n Tap update to go to your settings and change the Location to "Always"',
          'cancelButton': 'Cancel',
          'settingsButton': 'Update'
        });
```

``` dart
  gps.Authorization buildAuthorization(
      String accessToken, String refreshToken, String subDomain) {
    Map jwt = JWT.decode(accessToken);
    return gps.Authorization(
        strategy: "JWT",
        accessToken: accessToken,
        refreshToken: refreshToken,
        refreshUrl: "${Application.auth0Domain}/oauth/token",
        refreshPayload: {
          "grant_type": "refresh_token",
          "client_id": Application.clientId,
          "audience": Application.audience,
          "scope": Application.scope,
          "refresh_token": refreshToken,
          "env": subDomain
        },
        expires: jwt['payload']['exp']);
  }
```

## Expected Behavior
The access token is used for the jwt strategy `Bearer {accessToken}` after a token expires and the plugin gets a new one successfully

## Actual Behavior
The first token that matches a regex is used as the access token. [This issue appears to be related.](https://github.com/transistorsoft/flutter_background_geolocation/issues/189) If multiple tokens are provided. In our case, an `access_token` and an `id_token` are both provided from Auth0 when refreshing a token. [Here is a sample response from Auth0.](https://auth0.com/docs/api/authentication#refresh-token). The gps plugin is using the id token for future requests in place of the access token.

![image](https://user-images.githubusercontent.com/29047682/103380568-81f0ca80-4aa6-11eb-8c54-e9ddd8a91b75.png)

## Context
When an access token refreshes via this plugin, the plugin starts using the id token in place of an access token. This causes an infinite loop of getting new tokens and then getting a 401 from our server, then getting new tokens and then this repeats.

![image](https://user-images.githubusercontent.com/29047682/103380861-57ebd800-4aa7-11eb-8aab-a05c93c32e7d.png)

## Once plugin is ready and started, access token provided is used
![image](https://user-images.githubusercontent.com/29047682/103381214-61297480-4aa8-11eb-8e8b-ce977c11910f.png)

## Id Token is Used for Future Requests after Token Exipres
![image](https://user-images.githubusercontent.com/29047682/103381134-1ad41580-4aa8-11eb-9149-6f0bbbe143b2.png)

**Comment by christocracy** [comment]
If the automated `Config.Authorization` is not suitable for you, you can manage your own keys with `Config.headers` and listen to `onHttp` for `401` response as your signal to renew your authorization.

**Comment by MilesAdamson** [comment]
I would rather not manage the keys and headers myself for a paid plugin, as the auth management was a selling point here. Auth0 is commonly used, so I feel like your plugin should have a way to be used alongside it. Perhaps a callback or a json pointer, or the key we expect the token to be found at in the response. I don't think it matters much how the correct token is selected, but selecting the first string which is JWT is not going to work every time

**Comment by christocracy** [comment]
`Config.Authorization` was introduced only last year.  This is a relatively new feature in the six-year lifetime of this plugin.

This feature was requested by one of my React Native customers.  It was made to work according to his specification, where he referenced plenty of *Auth0* documentation.

I won't be modifying the `Config.Authorization` any time soon.

**Comment by MilesAdamson** [comment]
Well now one of your flutter customers is asking for a way to indicate which token is the access token. We were working off of this documentation in your code:

```
  /// When the SDK receives a response the server, it will decode the JSON and recursively iterate through the keys, performing regular expressions and other String-analysis *to "taste"* the data in search of the following 3 items:
  ///
  /// 1. "access token"
  /// 2. "refresh token"
  /// 3. "expiry time"
  ///
  /// The SDK is designed to operate with *any* response data-structure. 
```

It would have been extremely useful to know the limitations of this feature if they were already known to you

**Comment by christocracy** [comment]
If your server returns 2 keys of data containing a key that "smells" like a JWT (`xxx.yyy.zzz`), it will not work for you.  You will have to manage your key refresh on your own.
