### ISSUE TITLE
Could not find com.android.support:appcompat-v7:1.0.2

### ISSUE THREAD

**Issue by ExzaSolutions** [transistorsoft/flutter_background_geolocation#49]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: API 28
* Device manufacturer / model:
* Flutter info 
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

* Plugin config

## Expected Behavior
Should Compile

## Actual Behavior
Throws error
AILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':flutter_background_geolocation:debugCompileClasspath'.
> Could not find com.android.support:appcompat-v7:1.0.2.

implementation 'com.android.support:appcompat-v7:28.0.0'

**Comment by christocracy** [comment]
You neglected **Plugin version** in issue template.

**Comment by ExzaSolutions** [comment]
Thank you

**Comment by christocracy** [comment]
You’ve closed this issue without explanation.

**Comment by ExzaSolutions** [comment]
Hi Chris,

It seems you knew what the problem was.
I am pressed for time,to integrate the plugin.

I just created a new flutter project.
And started from scratch.
It runs,but there is a popup saying the license failed.
Do you look at the app name along with the license key?

Kind regards
Neal.

**Comment by christocracy** [comment]
>Do you look at the app name along with the license key?

Yes.  The key is bound to the app id it was generated for.

Package name is like *username*.  The key is the *password*.

**Comment by ExzaSolutions** [comment]
Hi Chris,

Is there maybe something I am missing?
Keep getting popup License Validation Failure in my flutter app.
I think I  followed the tutorial a few times now.
Not sure what else it could be?

Kind regards
Neal.

**Comment by christocracy** [comment]
Email me your AndroidManifest.xml.

chris@transistorsoft.com

**Comment by ExzaSolutions** [comment]
Hi Chris,

Thank you!

**Comment by ExzaSolutions** [comment]
Hi Chris I think I found my problem,sorry!!!
I just copied and pasted the flutter version without checking.
Changed it to 1.0.0 now it seems to be working now.

Thank you very much for the prompt response!!!!
Even over a weekend thank you!

Kind regards
Neal.
