### ISSUE TITLE
android.permission.ACCESS_LOCATION_EXTRA_COMMANDS

### ISSUE THREAD

**Issue by radvansky-tomas** [transistorsoft/flutter_background_geolocation#495]
I am seeking advice after receiving this message from Google Playstore:

<img width="1209" alt="Screen Shot 2021-01-20 at 8 44 06 AM" src="https://user-images.githubusercontent.com/12473664/105085586-d19e4100-5afc-11eb-9d9f-1304c68cd380.png">

Application does not use background location monitoring features, We only obtain stream of location changes in foreground.
Managing such state using WidgetObserver.

I've checked list of permissions we declare:
```
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />    
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>
```

And also searched for usage of `ACCESS_LOCATION_EXTRA_COMMANDS` inside projects / plugins and your repo and I did not find anything !!!

So I am not sure why they assume we are using it... So I would like to ask for advice, if those binaries https://github.com/transistorsoft/flutter_background_geolocation/tree/master/android/libs/com/transistorsoft can contain it, or if flutter_background_geolocation is using those extra commands elsewhere ? `getSystemService("location")).sendExtraCommand`

**Comment by christocracy** [comment]
The SDK has its own `AndroidManifest.xml` which is automatically merged into your app's manifest.

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.GET_TASKS" />
```

**Comment by christocracy** [comment]
I will experiment with removing this permission.  I'm not sure the SDK directly uses this or not.

You may remove it yourself by adding the following code to your `AndroidManifest.xml`:

```xml
<manifest>
  <uses-permission
    android:name="android.permission. ACCESS_LOCATION_EXTRA_COMMANDS"
    tools:node="remove" />
  .
  .
  . 
</manifest>
```

**Comment by radvansky-tomas** [comment]
@christocracy thank you for reply, we will try that and let you and community know about outcome ;)
