### ISSUE TITLE
Is it possible to store list of object(list of bg.Location) on local db or server in background?

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#496]
Is it possible to store the list of `bg.Location` on local DB or server in the background?

Now, I just store like this, 

```
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      if (location != null) {
        _locationController.add(Llocation);
      }
    }, (bg.LocationError error) {
      print("location Error : $error");
    });
```

**Comment by christocracy** [comment]
See api docs `BackgroundGeolocation.startBackgroundTask`

**Comment by bhanuka96** [comment]
@christocracy Thanks. just for clarification, can do these two on both platform?

```
BackgroundGeolocation.startBackgroundTask().then((int taskId) {
  // Perform some long-running task (eg: HTTP request)
  
  // Firestore.updateLocation(listOfLocation); 
  // updateLocalSqlite(listOfLocation);
  
  performLongRunningTask.then(() {
    // When your long-running task is complete, signal completion of taskId.
    BackgroundGeolocation.finish(taskId);
  });
});
```

**Comment by christocracy** [comment]
All methods are cross-platform.

**Comment by bhanuka96** [comment]
@christocracy not working. I added the above function when the user press start the trip button. It's working when the app running. It didn't store when the app runs in the background. (app close in the recent menu)

```
  void startBackgroundTask() {
    BackgroundGeolocation.startBackgroundTask().then((int taskId) {
      Timer.periodic(Duration(seconds: 5), (timer) async {
        LocationModel model = await getCurrentLocation();
        await db.storeTestingGeo(taskId, model);
      });
    });
  }
  
    Future<void> storeTestingGeo(int id, LocationModel list) {
    return _db.collection('testing').doc(id.toString()).set({
      'id': id,
      'geo': FieldValue.arrayUnion([list.toMap()])
    }, SetOptions(merge: true));
  }
```

**Comment by christocracy** [comment]
You can't do a periodic task within `startBackgroundTask`.  This is for a single, discrete action.  Get rid of `Timer.periodic`.

**Comment by bhanuka96** [comment]
@christocracy okay, Is there any way to store all `bg.BackgroundGeolocation.onLocation((bg.Location location) {` result on DB/local DB when app run on background?

**Comment by christocracy** [comment]
Your code above is fine, aside from the `Timer.periodic`.  Get rid of that.

**Comment by bhanuka96** [comment]
> Your code above is fine, aside from the `Timer.periodic`. Get rid of that.

but I want to store stream data every time. I mea, when location change I need to store that data on my DB. BTW, I am using firestore

**Comment by christocracy** [comment]
```dart
onLocation(Location location) {
  BackgroundGeolocation.startBackgroundTask().then((int taskId) {
    // do work
    BackgroundGeolocation.finish(taskId);
  }):
}

**Comment by christocracy** [comment]
And again -- do *not* ignore the issue template.  You have been warned twice now.

**Comment by bhanuka96** [comment]
> And again -- do _not_ ignore the issue template. You have been warned twice now.

Sorry, this question is published 7 days ago, I will not do it again.

**Comment by bhanuka96** [comment]
@christocracy I added your way, but not working on background mode. I mean, not added to the DB after close the app from the recent menu. but the notification sound is the trigger every onLocation.

```
class BgService {
  void onLocation() {
    bg.BackgroundGeolocation.onLocation((bg.Location model) {
        startBackgroundTask(model);
    }, (bg.LocationError error) {
      print("location Error : $error");
    });
  }

  void startBackgroundTask(bg.Location model) {
    BackgroundGeolocation.startBackgroundTask().then((int taskId) async {
      await db.storeTestingGeo(taskId, model);
      await BackgroundGeolocation.stopBackgroundTask(taskId);
    });
  }
}
```

**Comment by christocracy** [comment]
Of course that code doesn't work after app is *terminated*.  Your our App's dart code **no longer exists** -- it was *terminated*.

See wiki *Android Headless Mode**.

**Comment by bhanuka96** [comment]
@christocracy okay Thanks. I need to find way to store data both platform. Is it possible to do it using this plugin? https://pub.dev/packages/background_geolocation_firebase

**Comment by christocracy** [comment]
You didn't use the issue template, so how am I to know what platform(s) you're talking about?

Of course it's possible to do with the Firebase adapter.  That's what it was made for.
