### ISSUE TITLE
Can't build for iOS "TSBackgroundFetch/TSBackgroundFetch.h' file not found"

### ISSUE THREAD

**Issue by vova-beloded** [transistorsoft/flutter_background_geolocation#5]
## Your Environment
* Plugin version:0.1.2
* Platform: iOS
* OS version: 11.4
* Device manufacturer / model: emulator
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.5.4, on Mac OS X 10.13.5 17F77, locale en-UA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (1 available)
* Plugin config

## Expected Behavior
it builds & runs
## Actual Behavior
Launching lib/main.dart on iPhone X in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Running pod install...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/vovabeloded/Dev/fbh/fbh_app/ios/Runner/AppDelegate.m:3:10: fatal error: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found
    #include <TSBackgroundFetch/TSBackgroundFetch.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
## Steps to Reproduce
Followed standard guide on how to integrate to iOS

## Context
Integrate plugin to the app

## Debug logs
Included above

**Comment by christocracy** [comment]
Looking into it.

**Comment by christocracy** [comment]
Was this for the /example?

If not try the example

**Comment by vova-beloded** [comment]
/example builds just fine but with newer flutter version, this is about integrating plugin into our flutter/ios app (android version works great btw) with flutter 0.5.4

**Comment by christocracy** [comment]
Are you using XCode 10?

I'm getting this error as well in a new project.  Just skip the whole [Background Fetch](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-IOS.md#background-fetch) setup for now until I see what's up.  It's not important for now.

**Comment by christocracy** [comment]
> with flutter 0.5.4

I won't be supporting older versions of flutter (if it doesn't work as-is).  This is only my 4th week with Flutter (the native libraries I'm bringing into Flutter are ~5 years old).  The last think I'm going to do at this point is dig into the intricacies of older versions of Flutter.

**Comment by christocracy** [comment]
Ok, after removing **Background Fetch** , I got the plugin booted by pasting the [Example](https://github.com/transistorsoft/flutter_background_geolocation#large_blue_diamond-example) into a new Flutter app using `v0.8.2`.

**Comment by vova-beloded** [comment]
XCode Version 9.4.1 (9F2000)

**Comment by christocracy** [comment]
Actually, I've found a way to implement the **Background Fetch** setup stage within the plugin itself.  That whole manual step is unnecessary.  It will be removed from the iOS Setup doc.

**Comment by vova-beloded** [comment]
Here is what it displays when I removed Background Fetch from the project:

Launching lib/main.dart on iPhone X in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    While building module 'flutter_background_geolocation' imported from /Users/vovabeloded/Dev/fbh/fbh_app/ios/Runner/GeneratedPluginRegistrant.m:13:
    In file included from <module-includes>:1:
    In file included from /Users/vovabeloded/Dev/fbh/fbh_app/build/ios/Debug-iphonesimulator/flutter_background_geolocation/flutter_background_geolocation.framework/Headers/flutter_background_geolocation-umbrella.h:13:
    /Users/vovabeloded/Dev/fbh/fbh_app/build/ios/Debug-iphonesimulator/flutter_background_geolocation/flutter_background_geolocation.framework/Headers/FLTBackgroundGeolocationPlugin.h:2:9: fatal error: 'TSLocationManager/TSLocationManager.h' file not found
    #import <TSLocationManager/TSLocationManager.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/vovabeloded/Dev/fbh/fbh_app/ios/Runner/GeneratedPluginRegistrant.m:13:9: fatal error: could not build module 'flutter_background_geolocation'
    #import <flutter_background_geolocation/FLTBackgroundGeolocationPlugin.h>
     ~~~~~~~^
    2 errors generated.

**Comment by christocracy** [comment]
Paste your `ios/Podfile`

**Comment by vova-beloded** [comment]
It seems like the problem is in Podfile: for some plugins I use use_frameworks!  - and that seem to be breaking this plugin. Here is the part related to this issue:

target 'Runner' do
  # use_frameworks! # <--- add this

**Comment by christocracy** [comment]
As I suspected.  It won't work with `use_frameworks!`.

Which module are you using that requires that?

**Comment by vova-beloded** [comment]
We use contacts_service plugin ant it requires use_framework

**Comment by christocracy** [comment]
I don't see anywhere in the [README](https://github.com/clovisnicolas/flutter_contacts) where that plugin instructs you to `use_frameworks!`.

**Comment by vova-beloded** [comment]
yeah it doesn't but if you take a look at the example https://github.com/clovisnicolas/flutter_contacts/blob/master/example/ios/Podfile they use it and it appears that it doesn't work without it

**Comment by vova-beloded** [comment]
Ok there seem to be a fix for it to support use_frameworks - it requires to update flutter_background_geolocation-0.1.2/ios/flutter_background_geolocation.podspec to include 

  s.static_framework = true

if you want I can make PR

**Comment by christocracy** [comment]
try it and see.  3rd party modules should be pure Obj-c for maximum compatibility, IMO.

**Comment by christocracy** [comment]
Fixed in b16f477d209ab4dbd8eced77e582ac572463d17c.  "Background Fetch" setup is handled automatically by the plugin.

**Comment by christocracy** [comment]
`a.static_framework = true` is also added to podspec.

Please try installing from Git first.  I haven't yet published.

**Comment by vova-beloded** [comment]
I'm involved with @solid-software and we spent couple days trying to figure out this issue, yesterday checking the cocoa pods recent documentation we found that switch that seemed to help to solve that issue. We'll retry with b16f477 and we'll let you know how it goes :)
