### ISSUE TITLE
output wrong geoPoint

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#504]
I tested two trips on the same device (From Point A to B) and (From Point B to A). Point A to B is the wrong geo point. Point B to A is correct. This is my scenario.

**Point A to B** (from my home to point B) = open the app then start the trip from point A and then **minimize the app and lock the screen** and then end the trip after reach to Point B.

**Point B to A** (from point B to my home) = open the app then start the trip from point B and then **lock the screen (didn't minimize the app just lock the screen)** and then end the trip after reach to Point A.

Both trips should be equal. 

## Your Environment
* Plugin version: ^1.11.0
* Platform: Android
* OS version / Device manufacturer / model: attached screen shot below
* Flutter info (`flutter doctor`):

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-LK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)

```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.TransistorAuthorizationToken token = await bg.TransistorAuthorizationToken.findOrCreate('', '', '');
    return bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 0,
        locationUpdateInterval: 10000,
        locationTimeout: 60,
        persistMode: 1,
        desiredOdometerAccuracy: 10,
        stationaryRadius: 0,
        foregroundService: true,
        disableMotionActivityUpdates: true,
        enableHeadless: true,
        stopOnTerminate: false,
        startOnBoot: true,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        allowIdenticalLocations: true,
        useSignificantChangesOnly: false,
        transistorAuthorizationToken: token,
        debug: kDebugMode,
        logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
        notificationPriority: kReleaseMode ? -2 : 1,
        showsBackgroundLocationIndicator: kDebugMode,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: PermissionRationale(
            title: "",
            message: "",
            positiveAction: "",
            negativeAction: ""));
```

**Device Log** 
<img width="301" alt="Screenshot 2021-02-02 at 09 09 21" src="https://user-images.githubusercontent.com/34953062/106549383-d28c9500-6536-11eb-9820-1bd4e1766ba1.png">

**Point B to A (Correct GeoPoint)**
<img width="1064" alt="Screenshot 2021-02-02 at 08 52 27" src="https://user-images.githubusercontent.com/34953062/106549384-d4eeef00-6536-11eb-9724-e322a0c7246f.png">

**Point B to A (Wrong GeoPoint)** This should be same like Point B to A
<img width="1218" alt="Screenshot 2021-02-02 at 08 51 51" src="https://user-images.githubusercontent.com/34953062/106549390-d7e9df80-6536-11eb-879d-7da0d06a4ad1.png">

**Comment by christocracy** [comment]
Now go test it 10 more times.

**Comment by bhanuka96** [comment]
@christocracy This is happening to many users. That's why I test it myself. Is there any wrong my config?

**Comment by bhanuka96** [comment]
I think it's issue on the device. But my issue is why it returns correct geo points in my second scenario(point B to A).

**Comment by bhanuka96** [comment]
@christocracy I forgot to tell you, this is happing android headless event too. I tested the same scenario on this device.

**Point A to B** (from my home to point B) = open the app then start the trip from point A and then **close the app(app running on terminated mode) and lock the screen** and then end the trip after reach to Point B.

**Point B to A** (from point B to my home) = open the app then start the trip from point B and then **lock the screen (didn't minimize the app** just lock the screen) and then end the trip after reach to Point A.

**Comment by bhanuka96** [comment]
@christocracy can you give me a solution for this?

**Comment by bhanuka96** [comment]
@christocracy Have you ever encountered an issue like this before?

**Comment by bhanuka96** [comment]
@christocracy can I use `getCurrentLocation` instead of `onLocation` event? 

1. Is there any chance to fix this issue?
2. 

```
  void androidGeo(){
    Timer.periodic(Duration(seconds: 10), (timer) {
      bgService.getCurrentLocation().then(getLocation);
    });
  }
```
  
```
  Future<LocationModel> getCurrentLocation() async {
    return bg.BackgroundGeolocation.getCurrentPosition(desiredAccuracy: 10, maximumAge: 1000, timeout: 30, samples: 3, extras: {"getCurrentPosition": true}).then((value) {
      return LocationModel(
        speed: value?.coords?.speed,
        longitude: value?.coords?.longitude,
        latitude: value?.coords?.latitude,
        time: DateTime.parse(value?.timestamp).toLocal(),
        speedAccuracy: value?.coords?.speedAccuracy,
        altitude: value?.coords?.altitude,
        accuracy: value?.coords?.accuracy,
        heading: value?.coords?.heading,
      );
    }).catchError((e) {
      print("Get Location Error : $e");
      return;
    });
  }
```

**Comment by christocracy** [comment]
>can I use getCurrentLocation instead of onLocation event?

No.

>Is there any chance to fix this issue?

Your issue is specifically related to your device(s).  See http://dontkillmyapp.com.

**Comment by bhanuka96** [comment]
@christocracy thanks. But my app is not killed when I opened the app. (It's opened my previous screen)

**Comment by christocracy** [comment]
>But my app is not killed when I opened the app

It doesn't matter.  Certain Android device manufacturers throttle services when an app is operating in the *background* **OR** *termianted*.

**Comment by bhanuka96** [comment]
@christocracy okay, can I check location service enable or not?

**Comment by christocracy** [comment]
>can I check location service enable or not?

I don't know what you're talking about.

**Comment by bhanuka96** [comment]
I called this method when tap **end button**. I got 100% correct geo point.

   ` userLocation = await bgService.setOdometer();`
   
   then I store `userLocation.latitude` and `longitude` to db. this value is 100% correct but incorrect `onLocation` last value of array. btw userLocation is bg.Location
```
     Future<LocationModel> setOdometer({double value = 0.0}) async {
    return bg.BackgroundGeolocation.setOdometer(value.toDouble()).then(odometerCallback).catchError(odometerError);
  }
```

**Comment by bhanuka96** [comment]
> > can I check location service enable or not?
> 
> I don't know what you're talking about.

It doesn't matter. Certain Android device manufacturers throttle **_services_** when an app is operating in the background OR termianted. .........I mean these services

**Comment by bhanuka96** [comment]
> I called this method when tap **end button**. I got 100% correct geo point.
> 
> ` userLocation = await bgService.setOdometer();`
> 
> then I store `userLocation.latitude` and `longitude` to db. this value is 100% correct but incorrect `onLocation` last value of array. btw userLocation is bg.Location
> 
> ```
>      Future<LocationModel> setOdometer({double value = 0.0}) async {
>     return bg.BackgroundGeolocation.setOdometer(value.toDouble()).then(odometerCallback).catchError(odometerError);
>   }
> ```

is it possible to get the correct geo point if location service throttle by the system?

**Comment by christocracy** [comment]
>is it possible to get the correct geo point if location service throttle by the system?

Yes, by following the instructions at http://dontkillmyapp and *having the user modify their device settings accordingly*.

It's well known that several Android device manufacturers are **violating the Android API** to handicap Android services from doing their work and developers are pissed off.  That's why http://dontkillmyapp exists.

- See this issue thread at Google's Android Issue Tracker:  [Chinese OEMs constantly violating Android compliance](https://issuetracker.google.com/issues/122098785)
- Also see [this response from Android Engineering Team](https://www.reddit.com/r/androiddev/comments/hk3hrq/were_on_the_android_engineering_team_ask_us/fxg9y4f/) on a reddit AMA *by the AndroidEngTeam*.

>Background kills is a complicated topic that our team has been working on for awhile - it doesn’t help that each manufacturer does it differently. We feel the developer community’s pain and are committed to solving it. We’ve been in discussions with many device manufacturers to understand the reasoning behind their implementations, not just to preserve battery life, but also to protect users from misbehaving apps. At the same time, we've been working to move them away from using extreme methods such as app force-stop which renders the app unusable for users.

>With that said, we’ve made some changes that we hope will help.

>On the device manufacturer side:

>We are updating the Compatibility Definition Document (CDD) for Android 11 to make sure device manufacturers are alerting users of app restrictions in a timely manner. Not only does this help educate users about what is happening to their apps, but it also allows users to override the restriction if they choose to.

>We require that device manufacturers don’t create allow lists for top apps. It is damaging to the ecosystem as it decreases innovation and the option for new exciting developers to step up.

>We are working with device manufacturers to fix CDD violations; Top device manufacturers have fixed the violation in their latest builds on their major flagship devices.

>On the technical side:

>We’ve added a new API to allow developers to check the reason their app was terminated. This will demystify some of the cases in which developers aren’t sure if they were killed by the user, crash or an OS decision.

>We have added extra measures to prevent abusive behavior by misbehaving apps in order to make the OS more resilient and to allow device manufacturers to move away from any aggressive killing they are doing. Every measure we are adding to make the OS more resilient is deeply thought out to ensure we aren’t creating a harder life for the well behaved developers who are following our best practices.

>These don’t solve everything with background restrictions, and we are far from the finish line. But we’re committed to continue working on it, balancing making it easier for the developer community while ensuring our users get the best battery life possible.

**Comment by bhanuka96** [comment]
If I implement this kind of feature is it possible to kill app these kinds of devices from the system? [please check ](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cnet.com%2Fhow-to%2Fuse-android-get-chat-heads-by-installing-facebook-messenger%2F&psig=AOvVaw3gCTlui3QepcHsVWr57gku&ust=1612369467267000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNjr2r7Oy-4CFQAAAAAdAAAAABAD)

**Comment by bhanuka96** [comment]
@christocracy can restart(re-open) app from headless Event?

I implemented android native code to reopen the app.

Headless event function

```
void bringBackApp() async {
  try{
    const platform = const MethodChannel('name/bringBackApp');
    await platform.invokeMethod('bringBackApp');
  }catch(e){
    print('Error platform code : $e');
  }
}
```

native code
```
class MainActivity: FlutterActivity() {
    private val CHANNEL = "name/bringBackApp"

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            // Note: this method is invoked on the main thread.
            if (call.method == "bringBackApp") {
                val bringBackAppStatus = bringBackApp()
                result.success(bringBackAppStatus)
            } else {
                result.notImplemented()
            }
        }
    }

    private fun bringBackApp(): Boolean {
        val intent = Intent(context, MainActivity::class.java)
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
        startActivity(intent)
       // System.exit(0)
        return true
    }
}
```

**Comment by christocracy** [comment]
Android 10 [forbids relaunching activities in the background](https://developer.android.com/guide/components/activities/background-starts)

This is why the plugin's old `Config.forceReloadOnXXX` options are now all marked **deprecated**.

![](https://dl.dropbox.com/s/x1zg5yahha1ho38/Screen%20Shot%202021-02-02%20at%202.19.45%20PM.png?dl=1)
