### ISSUE TITLE
Permission Request Spamming

### ISSUE THREAD

**Issue by francesco-hayes** [transistorsoft/flutter_background_geolocation#505]
## Your Environment
* Plugin version: 1.11.0
* Platform: iOS or Android (both)
* OS version: Catalina 10.15.7
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`): Everything checks out
* Plugin config: 
```dart <-- Syntax highlighting: DO NOT REMOVE -->
BackgroundGeolocation.ready(
      Config(
        locationAuthorizationRequest: 'Always',
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        disableElasticity: true,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        enableHeadless: true,
        isMoving: _isMoving,
        minimumActivityRecognitionConfidence: 50,
        notification: Notification(
          title: 'Find Me',
          text: 'Currently tracking location in background',
          priority: Config.NOTIFICATION_PRIORITY_MIN,
        ),
        stopOnStationary: true,
        reset: true,
        logLevel: Config.LOG_LEVEL_VERBOSE,
      ),
    ).then((State state) {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
      _enabled = state.enabled;

      _updatePosition();
    }).catchError((error) {
      _enabled = false;

      print(error.toString());
    });
```

## Expected Behavior

I'm trying to postpone the permission requests from spamming the user once they login to the application. I put together a permissions page where they can go down the checklist manually.

## Actual Behavior

The Navigator goes to the wrong route and is stopped by the permission spamming the user.

## Steps to Reproduce

1. Open the Application with no set permissions
2.
3.
4.

## Context

Is there a way to postpone the permissions from spamming the user?

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
NO LOGS
```

</details>

**Comment by christocracy** [comment]
So don't call `start()` until you're ready for the user to accept permissions.  Typically, you're not supposed to automatically call `.start()` in the callback to `.ready()`.  Calling `.ready()` does not imply "start tracking".

```dart
if (!state.enabled) {
  BackgroundGeolocation.start();
}
```

**Comment by francesco-hayes** [comment]
I'm looking through the provided examples to figure out when it'd be best to actually start the BackgrounGeolocation. When would be the ideal time to start the location tracking if my main page is the map?

**Comment by christocracy** [comment]
Think of the plugin as an electronic device, such as a *Stereo Receiver*.

- `.ready()` = plugging in the power cord.
- `.start()` = power ON button.
- `.stop()` = power OFF button.

Plugging in the power cord (ie: `.ready()` does not imply *power ON*.

When you want to "listen to music", turn the power button ON (ie: `.start()`).

**Comment by christocracy** [comment]
The plugin *does* remember its last known `State` (eg: `state.enabled`).  When you restart your app, calling `.ready()` , the plugin will *automatically* call `.start()` upon itself if `state.enabled == true`.  Just as if a stereo receiver remembered the state of its *POWER BUTTON* should you disconnect/reconnect the power cord.
