### ISSUE TITLE
Changepace future not resolving on ios

### ISSUE THREAD

**Issue by GinoTerlouw** [transistorsoft/flutter_background_geolocation#506]
## Your Environment
* Plugin version: 1.11.0
* Platform: iOS
* OS version: 14.3 and 14.5
* Device manufacturer / model: iPhone 11 Pro (and simulator)
* Flutter info (`flutter doctor`): 
```console
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.5 19F96 darwin-x64,
    locale en-NL)
    • Flutter version 1.22.6 at /Volumes/Second_Drive/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Second_Drive/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro (mobile) • 16DAD0E1-1218-4414-A0F7-A62B13A14EE7 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```
* Plugin config: Example app (also our own app, from which I can provide the code if needed, but the bug is also reproducible in the example app.
```dart
<-- Syntax highlighting: DO NOT REMOVE -->
  // Manually toggle the tracking state:  moving vs stationary
  void _onClickChangePace() {
    setState(() {
      _isMoving = !_isMoving;
    });
    print("[onClickChangePace] -> $_isMoving");

    // promise never resolves on ios, on android it does and executes callback as expected.
    bg.BackgroundGeolocation.changePace(_isMoving).then((bool isMoving) {
      print('[changePace] success $isMoving');
    }).catchError((e) {
      print('[changePace] ERROR: ' + e.code.toString());
    });
  }

```

## Expected Behavior
 bg.BackgroundGeolocation.changePace future should resolve and return a bool after the operation is completed.

## Actual Behavior

On ios, the promise never resolves and the code inside the 'then' block (or after the await if you use async/await) will never resolve and return a value, on android it does work as expected.

## Steps to Reproduce

1. run example app on ios simulator or device
2. click start/stop button
3. look for print value as defined in the changepace callback function.

## Context
We are trying to create a bike ride tracking app and we noticed the bug when testing on ios, in our app the ui relies on the completion of that promise and because we primarily tested with android devices we never noticed it since the promise does resolves and returns as expected. Our current workaround for us is to not await the changepace Future because the method still gets executed and doesn't hinder the rest of the functionality, but we figured to notify you of this issue since this isn't documented behaviour. After trying it out in our app, we checked to confirm if this was a bug related to just us or the package so we ran the example app on ios and it gave the same result.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
logs currently not provided, but could be if you can't reproduce the bug yourself from the example app code.
```

</details>

**Comment by christocracy** [comment]
Thanks, I'll have a look.  

There's no reason to `await` this method.

**Comment by christocracy** [comment]
I think the only way this method fails is if you attempt to changePace while not enabled.

**Comment by GinoTerlouw** [comment]
Thank you for the quick reply! Backgroundgeolocation.start is run when starting our application and we are sure that backgroundgeolocatio is enabled on both our app and the example app.

**Comment by christocracy** [comment]
I found the problem.  It will be pushed soon to master.

**Comment by GinoTerlouw** [comment]
That is amazingly fast! Thank you for your great work!
