### ISSUE TITLE
Location accuracy gives a stable 65 meters for most users [iOS]

### ISSUE THREAD

**Issue by Holofox** [transistorsoft/flutter_background_geolocation#510]
## Environment
* Plugin version: 1.11.0
* Platform: iOS
* OS version: 14.4
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`):
```console
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale ru-RU)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
```
* Plugin config:
```dart
Config(
  desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
  locationAuthorizationRequest: 'Any',
  showsBackgroundLocationIndicator: true,
  disableLocationAuthorizationAlert: true,
  debug: false,
  logLevel: Config.PERSIST_MODE_ALL,
  allowIdenticalLocations: true,
  disableMotionActivityUpdates: true,
);
```

## Actual Behavior
When the phone does not pick up the `GPS`, it is usually the cell tower triangulation or WiFi location data that determines the error. If [horizontalAcuracy](https://developer.apple.com/documentation/corelocation/cllocation/1423599-horizontalaccuracy) gives ± 1414 meters, then information from the operator's base station is used. Most of the time, this value is 65 meters, which [opinion](https://stackoverflow.com/questions/7402503/what-do-horizontalaccuracy-and-verticalaccuracy-of-a-cllocation-refer-to#comment13441981_7403066) some people, is a constant when running the `CoreLocation` module.

1. https://stackoverflow.com/q/30468761
2. https://stackoverflow.com/a/4956243
3. https://evgenii.com/blog/power-consumption-of-location-services-in-ios/

App has high location accuracy (` desiredAccuracy`). `iOS` uses this desired accuracy as a clue about what hardware to use to service the location request, so the system will try to avoid activating hardware that it doesn't think is necessary to achieve the desired accuracy.

## Question
How can you avoid this and improve the accuracy (65 meters is quite common among users)?

**Comment by christocracy** [comment]
>How can you avoid this and improve the accuracy (65 meters is quite common among users)?

Go outside.

- Only when a device is outdoors is GPS available.
- When a device is indoors, only Wifi / Cellular providers are available.
