### ISSUE TITLE
Question about frequency/rate of location capture and running of callback on each platform

### ISSUE THREAD

**Issue by jasonkaruza** [transistorsoft/flutter_background_geolocation#512]
Hello,

At what frequency/rate does your plugin run to update the location and execute whatever callbacks we define on both Android and iOS? For example, the Work Manager runs at a maximum rate of every 15 minutes (https://pub.dev/packages/workmanager), while the Android Alarm Manager (https://pub.dev/packages/android_alarm_manager) should be able to run more frequently, but only works on Android.

Thanks!

**Comment by christocracy** [comment]
This plugin was designed for a disaster-response app, tracking first-responders in hurricanes and earthquakes where life depended on it.  It's going to record a location each `Config.distanceFilter` meters.  If you set `distanceFilter: 0`, you're going to record a location about *every second*, in the same manner that following a route in Google Maps app would do.

This is me walking around the neighbourhood with `distanceFilter: 50`:

![](https://dl.dropbox.com/s/ht5dodgjshvcz69/Screen%20Shot%202021-02-16%20at%202.26.34%20PM.png?dl=1)

**Comment by jasonkaruza** [comment]
Got it. So it's not time-driven, but rather distance-delta driven. So just to confirm:

1. That is for both iOS and Android? 
2. It will work when the app has been closed/minimized as well?

Thank you for the clarification!

**Comment by christocracy** [comment]
>That is for both iOS and Android?

Yes.

>It will work when the app has been closed/minimized as well?

Yes.  See API docs `Config.stopOnTerminate`, `Config.startOnBoot`, `Config.enableHeadless`.

This plugin was designed to track devices *no matter what*, regardless if app terminated or device rebooted.  Once `.start()` is called, the plugin is going to track devices everywhere they go, *forever* until told to `.stop()`.

**Comment by jasonkaruza** [comment]
Perfect. Thanks!
