### ISSUE TITLE
Not receiving location in forground, background and app is killed

### ISSUE THREAD

**Issue by hardikJoshi123** [transistorsoft/flutter_background_geolocation#519]
Hi. thanks for this great library. We are trying to retrieve user's current location after every 200 meters. We need their location while app is in background OR even killed. We are using firestore to push locations continuously. 

## Your Environment
* Plugin version:  flutter_background_geolocation: ^1.11.1
* Platform: Android
* OS version:  android 10
* Device manufacturer / model: Redmi Note 7 Pro
* Flutter info (`flutter doctor`):
 
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.1 19B88 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Volumes/Work/Nick/FlutterSDK/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hardikjoshi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Users/hardikjoshi/Desktop/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Redmi Note 7 Pro (mobile) • 72726843 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
Process finished with exit code 0

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
=> We found and already implemented this android side setup from this link : https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md

Here is my code :

=> main.dart :


final FirebaseAuth _auth = FirebaseAuth.instance;
final FirebaseFirestore _flutterFirestore = FirebaseFirestore.instance;

void saveLocation(bg.Location location) async {
if (_auth.currentUser == null) {
return;
}
final event = await _flutterFirestore
.collection('tracking')
.doc(_auth.currentUser.uid)
.collection('tracking-list')
.where('status', isEqualTo: 'active')
.get();

if (event.docs.length < 1) {
bg.BackgroundGeolocation.stop();
}

}

void headlessTask(bg.HeadlessEvent headlessEvent) async {
print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
// [BackgroundGeolocation onLocation] ‼️ Uncaught location error: PlatformException(0, LOCATION_ERROR, null, null). You should provide a failure callback as 2nd argument.
switch(headlessEvent.name) {

case bg.Event.TERMINATE:
try {
bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
print('[getCurrentPosition] Headless: $location');

} catch (error) {
print('[getCurrentPosition] Headless ERROR: $error');
}
break;
case bg.Event.HEARTBEAT:
/* DISABLED getCurrentPosition on heartbeat
try {
bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
print('[getCurrentPosition] Headless: $location');
} catch (error) {
print('[getCurrentPosition] Headless ERROR: $error');
}
*/
break;

case bg.Event.LOCATION:
bg.Location location = headlessEvent.event;
print('- Location: $location');
saveLocation(location);
break;

case bg.Event.MOTIONCHANGE:
bg.Location location = headlessEvent.event;
print(location);
break;
case bg.Event.GEOFENCE:
bg.GeofenceEvent geofenceEvent = headlessEvent.event;
print(geofenceEvent);
break;
case bg.Event.GEOFENCESCHANGE:
bg.GeofencesChangeEvent event = headlessEvent.event;
print(event);
break;
case bg.Event.SCHEDULE:
bg.State state = headlessEvent.event;
print(state);
break;
case bg.Event.ACTIVITYCHANGE:
bg.ActivityChangeEvent event = headlessEvent.event;
print(event);
break;
case bg.Event.HTTP:
bg.HttpEvent response = headlessEvent.event;
print(response);
break;
case bg.Event.POWERSAVECHANGE:
bool enabled = headlessEvent.event;
print(enabled);
break;
case bg.Event.CONNECTIVITYCHANGE:
bg.ConnectivityChangeEvent event = headlessEvent.event;
print(event);
break;
case bg.Event.ENABLEDCHANGE:
bool enabled = headlessEvent.event;
print(enabled);
break;
case bg.Event.AUTHORIZATION:
bg.AuthorizationEvent event = headlessEvent.event;
print(event);
bg.Location location = headlessEvent.event;
// bg.BackgroundGeolocation.setConfig(
// bg.Config(url: "${ENV.TRACKER_HOST}/api/locations"));
break;
}
}

Future<void> main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();

Crashlytics.instance.enableInDevMode = true; // turn this off after seeing reports in in the console.
FlutterError.onError = Crashlytics.instance.recordFlutterError;

configLoading();

bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);

bg.BackgroundGeolocation.onLocation((bg.Location location) {
print('[location normal] - $location');
saveLocation(location);
});

// Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
print('[motionchange] - $location');
saveLocation(location);
});

bg.BackgroundGeolocation.ready(bg.Config(
desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
distanceFilter: 100.0,
elasticityMultiplier: 5.0,
enableHeadless: true,
isMoving: true,
stopOnTerminate: false,
startOnBoot: true,
debug: true,
logLevel: bg.Config.LOG_LEVEL_VERBOSE
));


runApp(MainApp());
}

class MainApp extends StatefulWidget {
@override
MainAppState createState() => MainAppState();
}

class _MainAppState extends State<MainApp> {
bool _isLoggedIn = false;

@override
void initState() {
_isLoggedIn = false;
_auth.authStateChanges().listen((user) async {
// ignore: unnecessary_statements
user != null ? setState(() { _isLoggedIn = true; }) : null;
});

super.initState();
}

final routes = <String, WidgetBuilder>{
LoginPage.tag: (context) => LoginPage(),
HomePage.tag: (context) => HomePage(),
};

@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Load Market',
theme: ThemeData(
primaryColor: Colors.white,
visualDensity: VisualDensity.adaptivePlatformDensity,
scaffoldBackgroundColor: Colors.white,
),
home: _isLoggedIn ? HomePage() : LoginPage(),
routes: routes,
builder: (BuildContext context, Widget child) {
return FlutterEasyLoading(child: child);
},
);
}
}


=> Following method i am calling to start tracking in my app which is inside another dart file. (In another screen) :



void activateTrackingStatus() async {

final status = await _flutterFirestore
.collection('tracking')
.doc(_auth.currentUser.uid)
.collection('tracking-list')
.where('status', isEqualTo: 'active')
.get();

final state = await bg.BackgroundGeolocation.state;
print("State ==> $state");

if (status.docs.length > 0 && !state.enabled) {
//bg.BackgroundGeolocation.start();

if (state.trackingMode == 1) {
bg.BackgroundGeolocation.start();
} else {
bg.BackgroundGeolocation.startGeofences();
}

} else {
bg.BackgroundGeolocation.stop();
}

bg.BackgroundGeolocation.changePace(state.isMoving).then((bool isMoving) {
print('[changePace] success $isMoving');
}).catchError((e) {
print('[changePace] ERROR: ' + e.code.toString());
});

}
```

## Expected Behavior

App should receive current location in forground, background and if app is killed. 

## Actual Behavior

We are only getting user's current location when pressing "Start tracking" button in my app. But afterwords we aren't receiving their location any more! 

## Context

We need to track user's location in background, forground and even if app killed by user. We need it after every 200 meters.

## Debug logs
When pressing start tracking button in my app, here is log info : 

https://pastebin.com/bsjYnqLz

 

</details>

**Comment by christocracy** [comment]
Restart your device and try again.

**Comment by hardikJoshi123** [comment]
Hi. Thank you for quick reply. We tried with restart device. But still not working. Here is code :


    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
      saveLocation(location);
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
      saveLocation(location);
    });

**Comment by hardikJoshi123** [comment]
Hi @christocracy any help? Thanks!

**Comment by christocracy** [comment]
are you testing on multiple devices?

**Comment by hardikJoshi123** [comment]
Yes I have tested on two different devices. Redmi note 7 and redmi note 8

**Comment by christocracy** [comment]
Have you tried installing the /example app in this repo?

**Comment by hardikJoshi123** [comment]
Yes I tried installing example app in this repo. its working fine for us.

**Comment by WUKS87** [comment]
@christocracy I have created headlessTask in main.dart and initiated with:
`bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);`

Along with:
`bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100.0,
      elasticityMultiplier: 5.0,
      enableHeadless: true,
      // preventSuspend: true,
      // heartbeatInterval: 60,
      isMoving: true,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE
  ));`

Is that enough for iOS & Android tracking for all states (foreground, background, killed app)?
Of course configuration is already done.

My app is working only in foreground mode. Once it switch to background it stop recording in Firestore DB.

Here is my headless task:
`void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
  // [BackgroundGeolocation onLocation] ‼️ Uncaught location error: PlatformException(0, LOCATION_ERROR, null, null).  You should provide a failure callback as 2nd argument.
  switch(headlessEvent.name) {
    case bg.Event.TERMINATE:
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $location');

      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print('Wolf - Location: $location');
      saveLocation(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      break;
  }
}`

**Comment by christocracy** [comment]
Your headless task is not interesting to me at this time.

Are you testing with debug: true?  Go outside for a nice long test (1km or more).  Do you "hear" the debug sounds?

When you come back, fetch the logs with `emailLog` ant attach the file here,

**Comment by WUKS87** [comment]
@christocracy We did our test, attaching logs.
We tried with app in background and "killed" mode.
Plugin responded very nice in background mode, location ping was great.

When we killed the app completely (from cache), plugin required some time to recover.
But also in that mode we didn't get so many location pings as we expected. Seams to us that was not behaving the same as in both cases.

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/6076279/background-geolocation.log)

**Comment by christocracy** [comment]
On my 12 Android test devices, the plugin doesn’t perform any differently while foreground, background or terminated.

**Comment by WUKS87** [comment]
Understood, we will test much more on multiple devices.

One thing also I noticed is that simulator sometimes ping the same location multiple times, could it be because it's simulator and not real device?

I will take a look if real device is doing the same!

**Comment by christocracy** [comment]
> could it be because it's simulator and not real device?

Yes.  I never test in simulator, only real devices.  You’ll never see the true behavior of the plugin in a simulator.

simulators don’t respond to the motion api and the geofencing api hardly ever works.

**Comment by WUKS87** [comment]
@christocracy On Android we get this error:
<img width="1197" alt="Screenshot 2021-03-15 at 08 49 16" src="https://user-images.githubusercontent.com/1992520/111120325-7d976200-856b-11eb-9a97-18de1d06095c.png">

Am I missing something in setup?

Attaching full log also:
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/6139596/background-geolocation.log)

iOS behaves pretty good.

**Comment by WUKS87** [comment]
@christocracy We solved error from above by adding proguard-rules.pro in android/app/src/
We saw it here: https://github.com/transistorsoft/flutter_background_geolocation/issues/456#issuecomment-734458493

Now we tested and Android app works on Foreground only. In log we don't have any error.
We are going for out more tests :)

**Comment by francesco-hayes** [comment]
How are you tracking the location in the background after the app is killed without using BackgroundFetch? I though you had to use the BackgroundFetch package and config it separately like in the example app.

**Comment by christocracy** [comment]
>How are you tracking the location in the background after the app is killed

The only thing you need to do is configure `stopOnTerminate: false`.  That's it.  `BackgroundFetch` is not required for this.  Implementing the `BackgroundFetch` `dart` API is **optional**.

**Comment by christocracy** [comment]
`BackgroundFetch` is a *very* minor dependency used internally by `BackgroundGeolocation` for some *very minor* house-keeping tasks.  `BackgroundGeolocation` does **not** rely upon `BackgroundFetch` for its core *Philosophy of Operation*.

**Comment by francesco-hayes** [comment]
Why is it then that in your example you show your application register a BackgroundFetch and BackgroundGeolocation task?

**Comment by christocracy** [comment]
For my own testing.

**Comment by WUKS87** [comment]
Just to note that my problem is resolved.
Some other libs (most likely Firebase) I'm using in the project were in some kind of conflict with flutter_background_geolocation
After those released update problem with android is gone.

I hope that this tricky thing can help someone.
Just to note that I didn't have any error, simply didn't work.
