### ISSUE TITLE
Flutter background geolocator stops fetching coodinates

### ISSUE THREAD

**Issue by elioDeMarinis** [transistorsoft/flutter_background_geolocation#520]
First of all, thanks for this library, but I'm facing some problems in fetching coordinates. In my application, there are two buttons: the first one call the start() method of the background geolocation library and the second one call the stop() method in an asynchronous function. After starting the Android emulator, when a new route starts, the library fetches the coordinates every 10 seconds, but most of the time it returns the first couple of coordinates and it does not goes on. What is the cause of this behaviour? Thanks in advance. (P.S.: This library supports all iOS smartphones? In cases of iPhone 8 and iPhone rx, the library seems not to starts...) 

## Your Environment
* Flutter  1.22.5
* Android SDK 30.0.3
* Dart 2.10.4

## void initState()
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            //heartbeatInterval: 10,
            //locationUpdateInterval: 3000,
            preventSuspend: true,
            logLevel: bg.Config.LOG_LEVEL_OFF,
            reset: true))
        .then((bg.State state) {
      setState(() {
        isMoving = state.isMoving;
      });
      log("[ready] ${state.toMap()}");
    }).catchError((error) {
      log('[ready] ERROR: $error');
    });
```
## onStart() 

```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.start().then((bg.State state) {
      log('[start] success $state');
      setState(() {
        isMoving = state.isMoving;
      });
    });

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      log(DateTime.now().toIso8601String() +
          ', [Latitude] - ${location.coords.latitude}');
      log(DateTime.now().toIso8601String() +
          ', [Longitude] - ${location.coords.longitude}');

    }, (bg.LocationError error) {
     log('[onLocation] ERROR: $error');
  });
```

## onStop()

```dart <-- Syntax highlighting: DO NOT REMOVE -->
  void arrivedAtClient() async {
    final response = await http.post('http:/localhost/method_to_call',
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'id': widget.id,
          'timestamp': DateTime.now().toIso8601String()
        }));
    if (response.statusCode == 200) {
      bg.BackgroundGeolocation.stop();
    }
  }
```

## Expected Behavior

I'd want to fetch the coordinates until the stop button has pressed, whether the app is in foreground/background or killed.

## Actual Behavior

Most of the time, the library stops fetching coordinates and it returns only the first couple.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/TSLocationManager(16959): - Enable: false → true, trackingMode: 1
[log] [start] success [State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: -1, distanceFilter: 10.0, odometer: 107463.8828125, schedulerEnabled: false, foregroundService: true]
[log] 2021-02-25T10:17:06.867991, [Latitude] - 45.21631
[log] 2021-02-25T10:17:06.868463, [Longitude] - 9.68555
[log] Distance init ---> 5073.356025104416 m
[log] 2021-02-25T10:17:06.871710, [Latitude] - 45.21631
[log] 2021-02-25T10:17:06.871858, [Longitude] - 9.68555
[log] Distance init ---> 5073.356025104416 m
V/MediaPlayer(19653): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(19653): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(19653): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(19653): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer(19653): mediaplayer went away with unhandled events
V/MediaPlayer(19653): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(19653): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

</details>

**Comment by christocracy** [comment]
You should not expect a continuous stream of locations after calling `start()`.  You should expect a couple, maybe one, then silence.

Have you read the wiki "*Philosophy of Operation*"?

**Comment by christocracy** [comment]
Perhaps you're interested in the method `getCurrentPosition`, which doesn't require the plugin to be `start()`ed.

**Comment by elioDeMarinis** [comment]
Thanks, for your reply, but the issue remains even with ```getCurrentPosition```. The expected behaviour is this: I'd want to send, every 10 seconds, the coordinates fetched to a server, whether the app is foreground/background or it has been killed. I'm using also ```onHeartbeat``` method, with ```start()``` before it and ```heartbeatInterval: 10``` in Config, but the result is the same. Fetching coordinates will stop only when the user will press the stop button.

```
   bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
      log('getting position...');
      print('getting position...');
      var d = DateTime.now();
      print("time:");
      print(d);
      bg.BackgroundGeolocation.getCurrentPosition(samples: 1, persist: true)
          .then((bg.Location location) {
        log('[Latitude] - ${location.coords.latitude}');
        log('[Longitude] - ${location.coords.longitude}');

        sendCoordinates(location.coords.latitude, location.coords.longitude);
      });
    });
```

**Comment by christocracy** [comment]
See method `changePace`.  Adjust `stopTimeout` as desired,

**Comment by elioDeMarinis** [comment]
I'm using ```changePace``` and inside I'm calling ```bg.BackgroundGeolocation.getCurrentPosition``` with timeout, but I'm still getting just one couple of coordinates. Here's the output:
```
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
II/flutter (32207): [changePace] success false
[log] [getCurrentPosition] - [Location {odometer: 20732.30078125, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: false}, uuid: 3f8f2981-32b0-4f46-b405-e087d2e0562f, coords: {altitude: 0.0, heading: 354.0, latitude: 45.2987, accuracy: 5.0, heading_accuracy: -1.0, altitude_accuracy: 0.5, speed_accuracy: -1.0, speed: 26.32, longitude: 9.50295}, is_moving: true, timestamp: 2021-02-25T12:47:00.093Z}]
[log] [Latitude] - 45.2987
[log] [Longitude] - 9.50295
```

</details>

```

**Comment by christocracy** [comment]
Set distanceFilter: 0

**Comment by elioDeMarinis** [comment]
```changePace``` sometimes returns me ```I/flutter ( 2198): [changePace] ERROR: BackgroundGeolocation is disabled```, but the plugin is initialized in ```initState()```.

**Comment by christocracy** [comment]
Correct.  How can you tell the plugin to enter the *moving* state if the plugin is *not enabled*?

```dart
await bg.BackgroundGeolocation.start();
await bg.BackgroundGeolocation.changePace(true);
```

**Comment by christocracy** [comment]
I suggest you set `debug: true` until you learn more about this plugin.

**Comment by christocracy** [comment]
If the plugin were an electronic device, such as a *Stereo Receiver*
- `.ready()` = plugging in the AC cord
- `.start()` / `.stop()` = POWER button.
- `.changePace(true)` = clicking `[PLAY]` button; `.changePace(false)` = `[PAUSE]` button.

>[changePace] ERROR: BackgroundGeolocation is disabled

Is like clicking the `[PLAY]` button with the `[POWER]` OFF.

**Comment by christocracy** [comment]
The plugin's *Philosophy of Operation* is to detect when the device is moving and *automatically* call `.changePace` *upon itself*.

**Comment by elioDeMarinis** [comment]
Many thanks. Now it's working as I've expected, but in background is not working, yet.

**Comment by christocracy** [comment]
As long as the plugin is in the *moving* state (ie: `changePace(true)`), the plugin doesn't care if your app is in the background.  The plugin has turned on location-services and your app is completely alive just as if it were in the foreground.
