### ISSUE TITLE
com.transistorsoft.locationmanager.license  invalid

### ISSUE THREAD

**Issue by function2000** [transistorsoft/flutter_background_geolocation#521]
Where to register license?  please guide
I use the demo license as below:
        android:name="com.transistorsoft.locationmanager.license" android:value="025736af0c3b480ecc1a6fc8aea17e73cc012049ed117472072b76e5e170953d" 
        android:name="com.transistorsoft.locationmanager.ENCRYPTION_PASSWORD" android:value="transistorsoft" 

![license](https://user-images.githubusercontent.com/4005363/109387378-16a76580-793c-11eb-8d5a-65ae0c744e3c.jpg)

**Comment by christocracy** [comment]
From the top of the README, have you purchased a license?

![](https://dl.dropbox.com/s/sd0tqtm9281kd9v/Screen%20Shot%202021-02-27%20at%207.46.07%20AM.png?dl=1)

**Comment by christocracy** [comment]
The plugin is fully functional *in DEBUG builds* without a license, in spite of the error message you see.

The license key from the demo app is bound to the demo app's [Android `applicationId: "com.transistorsoft.flutterbackgroundgeolocationexample"`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/build.gradle#L64)

**Comment by function2000** [comment]
> The plugin is fully functional _in DEBUG builds_ without a license, in spite of the error message you see.
> 
> The license key from the demo app is bound to the demo app's [Android `applicationId: "com.transistorsoft.flutterbackgroundgeolocationexample"`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/build.gradle#L64)

I am not sure if the license used for store the GPS record or not. If license just for the GPS storage, then I just want to store the record to my own server, then is it OK to run without license via release mode?  Please let me know. thanks!

**Comment by christocracy** [comment]
The license is for *use of* the `BackgroundGeolocation` plugin in release builds of your Android app.  The plugin does not store your data on my servers.  You are expected to configure the `Config.url` to point to **your own** server.

If you're talking about the data at `tracker.transistorsoft.com`, that's my **demo server**.  The demo app has merely configured its `Config.url` to post locations there for demonstration purposes, so you can quickly evaluate the behaviour of the plugin.

**Comment by christocracy** [comment]
>then is it OK to run without license via release mode? 

No.  In order to use this plugin *at all* in *release* builds, you need to have purchased a license.
