### ISSUE TITLE
Question, will preventSuspend keep the app alive if location services are turned off after the plugin is started?

### ISSUE THREAD

**Issue by CTSDevelopmentTeam** [transistorsoft/flutter_background_geolocation#522]
We are currently making use of prevent suspend and we are wondering if the functionality will cease to work if the location services are turned off after the plugin has started and begun to work successfully.

**Comment by christocracy** [comment]
> if the functionality will cease to work if the location services are turned off after the plugin has started and begun to work successfully.

Yes, it will stop working.

**Comment by CTSDevelopmentTeam** [comment]
Thanks for the information.
