### ISSUE TITLE
HUAWEI kill the app in the background app when the phone is locked

### ISSUE THREAD

**Issue by dhiaIntigo** [transistorsoft/flutter_background_geolocation#523]
## Your Environment
* Plugin version:1.10.3
* Platform: Android
* OS version:5.0/6.0/7.0/8.0/9.0/10
* Device manufacturer / model: HUAWEI
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [version 10.0.18363.1379], locale fr-FR)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    // // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
            reset: true,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 0,
            locationUpdateInterval: 10,
            stopOnTerminate: true,
            disableStopDetection: true,
            startOnBoot: true,
            enableHeadless: true))
        .then((bg.State state) {
      print("[ready] ${state.toMap()}");
      setState(() {});
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
``````
## Expected Behavior

The app should keep running in the background in all phones .
## Actual Behavior

The app stop working in the background after 2 to 5 minute.

## Steps to Reproduce

1.You can try your test application deployed on play store on the HUAWEI Y5 with EMUI 3.1.
2.You can test on Huawei phones that contains EMUI 3.1 and going up to EMUI 8 .
3.
4.

## Context

We have a taxi ordering app which composed to 2 apps drivers app & clients app.The drivers app that should send driver location periodically, so the clients can see nearby drivers and track the driver in real time .
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
There is no software solution for poorly behaved Android vendors that violate the Android api.  Huawei is the **worst** offender.

- See http://dontkillmyapp.com
- [Reddit Thread](https://www.reddit.com/r/androiddev/comments/hk3hrq/were_on_the_android_engineering_team_ask_us/fxg9y4f/)
- [Android Issue Tracker “Chinese OEMs constantly violating Android compliance](https://issuetracker.google.com/issues/122098785)
