### ISSUE TITLE
Apple Review Rejects with "ITMS-90078: Missing Push Notification Entitlement"

### ISSUE THREAD

**Issue by flxwu** [transistorsoft/flutter_background_geolocation#524]
## Your Environment
* Plugin version: ^1.9.0
* Platform: iOS
* OS version: -
* Flutter info (`flutter doctor`): All green
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
_config = bg.Config(
      heartbeatInterval: 70,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      preventSuspend: true,
      stopTimeout: 1,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      locationAuthorizationRequest: 'Always',
      geofenceModeHighAccuracy: true,
    );
```

## Expected Behavior
App to be accepted.

## Actual Behavior
App got rejected with:

```
ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
```

## Context
Submitted the App to Apple Beta App Review.

**Comment by christocracy** [comment]
> Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' 

#Why are you seeking support for this here at the *Background Geolocation* repo?  Did you post this issue in the wrong place?

**Comment by flxwu** [comment]
Because the only notifications my app produces are the transistor soft ones i.e. "Authorisation status changed" or "Entering Geofence"

**Comment by christocracy** [comment]
This rejection has nothing to do with your decision to use push notifications.  Please google your rejections notices *before* coming here with unrelated problems.

**Comment by flxwu** [comment]
Yes I did, but I expected the plugin to give me some instructions on how to do this?

**Comment by flxwu** [comment]
Since this comes out of the box in the library, how am I supposed to know what to do about it?

**Comment by flxwu** [comment]
I personally didn't touch anything with push notifications. They just automatically came with the library! So no, it wasn't *my decision* at all.

**Comment by christocracy** [comment]
The plugin has nothing to do with notifications.

there is nothing in the box providing notifications support (aside from debug: true notifications)

**Comment by christocracy** [comment]
The library does nothing to *automatically* add *any* entitlement.  You the developer are responsible for manually approving entitlements.
