### ISSUE TITLE
Heartbeat event not triggering with certain configuration changes

### ISSUE THREAD

**Issue by draganjovanovic1** [transistorsoft/flutter_background_geolocation#525]
## Your Environment
* Plugin version: 1.11.1
* Platform: iOS and Android
* OS version: Android 10 & 11 / iOS 13 & 14
* Device manufacturer / model: multiple Android and iOS devices
* Flutter info (`flutter doctor`):
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on macOS 11.2.2 20D80 darwin-x64, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (1 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

    await bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter < 0.1 ? 5.0 : distanceFilter,
        disableElasticity: disableElasticity,
        locationUpdateInterval: locationUpdateIntervalSec == 0
            ? 15 * 1000
            : locationUpdateIntervalSec * 1000,
        maxRecordsToPersist:
            maxRecordsToPersist == 0 ? 200 : maxRecordsToPersist,
        maxDaysToPersist: 5,
        allowIdenticalLocations: false,
        // activityRecognitionInterval: 0,
        // stopOnStationary: false,
        // isMoving: true,
        // stationaryRadius: 25,
        // showsBackgroundLocationIndicator: true,
        heartbeatInterval: 30,
        enableHeadless: true,
        foregroundService: true,
        stopOnTerminate: false,
        startOnBoot: true,
        preventSuspend: true,
        // stopTimeout: 120,
        // pausesLocationUpdatesAutomatically: false,
        // disableStopDetection: true,
        autoSync: true,
        url: trackingBloc.trackingUrl,
        method: 'POST',
        batchSync: true,
        // reset: true,
        maxBatchSize: UploadBatchSize,
        locationsOrderDirection: 'ASC',
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow {applicationName} to access to this device's location in the background?",
            message:
                'App tracks your location while you are logged in to provide the Busability system with the most recent and precise location of the vehicle you are driving even when the app is in the background. Please enable {backgroundPermissionOptionLabel} location permission',
            positiveAction: 'Change to {backgroundPermissionOptionLabel}',
            negativeAction: 'Cancel'),
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        notification:
            bg.Notification(smallIcon: 'drawable/ic_stat_notification_icon')));

```

## Expected Behavior

Heartbeat callback should trigger.

## Actual Behavior

Heartbeat callback does not trigger.

## Steps to Reproduce

1. use configuration above, call `start()` then `changePace(true)`, heartbeat triggers
2. uncomment commented lines, call `start()` then `changePace(true)`, heartbeat does not trigger

## Context

I wanted to make the most aggressive tracking configuration since I didn't know about `changePace(true)` (if you can remember I opened an issue with question about it and you helped me). I started using `changePace(true)` and it works nice but I've left the last configuration I have tried before that. 

Recently I noticed that `onHeartbeat` callback is not being fired on all Android and iOS devices I've tried so I reverted few of my last configuration changes and it started working again (commented lines in the config section below). 

Questions:
1. Can you tell me which configuration parameter makes `onHeartbeat` callback to stop triggering? 
2. Since I am using `changePace(true)` do I even have to bother with configuration changes I've reverted at all? 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
couldn't find anything relevant in the logs, just no heartbeat event logged
```

</details>

**Comment by christocracy** [comment]
The only thing that affects heartbeat are:

- the plugin must be in stationary state.  No heartbeat in moving state.
- heartbeatInterval > 0

### iOS 
- preventSuspend: true is required.  If the device is laying completely still for 3 minutes, the os throttles heartbeat.  You won't see anymore until you pick up the device or light up the screen

**Comment by christocracy** [comment]
Nothing operates once the the plugin stopped.

that’s the point of the word “stop”.

**Comment by draganjovanovic1** [comment]
I could probably find it by uncommenting one by one but I would prefer to understand.

**Comment by christocracy** [comment]
I’ve already explained the conditions above.

**Comment by draganjovanovic1** [comment]
I had an issue with delayed transition to the moving state on iOS which was unacceptable in my use case. I solved the issue with uncommented configuration above + `changePace(true)`. It works fine now but no heartbeat. If I comment parameters above and use `changePace(true)` would I skip delay with iOS stationary radius?

**Comment by christocracy** [comment]
You cannot rely on preventSuspend.  There’s no guarantee it keeps working.  It’s a brittle hack that iOS keeps making difficult to run.

you should avoid preventSuspend.  It’s designed for 1% of use-cases.

you should accept the 200 meters it requires for the plugin to trigger.  It’s a very small distance in the grand scheme.

**Comment by draganjovanovic1** [comment]
So there is no 100% reliable way of having always on tracking on iOS? While 200m is not much sometimes it makes difference for the business requirement I have. BTW I have pretty good results with the configuration I posted (all uncommented) + manual `changePace(true)`. In addition to that I was requesting location on heartbeat event but my main concern here is that I do not have that event triggered with the configuration I use (I understand it is by design but would be very nice to enable use of it anyway, something like "I don't care about battery, give me all you have" mode).
