### ISSUE TITLE
`http.dart` 0.13.0 requires Uri instead of String for first `http.read()` parameter

### ISSUE THREAD

**Issue by pbelbin** [transistorsoft/flutter_background_geolocation#527]
I installed Flutter 2 from scratch, and tried building the 'advanced' example app. 

When I built, it complained about needing to have something added to the pubspec.yaml, so I added:

```
environment:                                                            
  sdk: '>=2.10.0 <3.0.0'
```

Then, attempting to build, (and, in VSCode), I find a compile complaint regarding `http.read()`.

https://github.com/transistorsoft/flutter_background_geolocation/blob/824763f98c8aadaa8a41a485b59677423bb6fa23/example/lib/advanced/home_view.dart#L360

It insists that the first parameter of `http.read()` should be a Uri(), which can easily be fixed by the following change:

`http.read(Uri.parse(url), headers: {` instead of what's there currently.

Looking at the change history for the `http.dart` package, it seems that 0.13.0-nullsafety.0 introduced a breaking change that requires the first parameter to now be a Uri() instead of String.

So, this is going to need to be adjusted (and other usages elsewhere too, I suppose).

**Comment by christocracy** [comment]
Thanks, this is fixed now in latest merge to master.  /example has had all its dependencies updated to latest versions.

`flutter_background_geolocation@2.0.0` is released.  nullsafety coming soon.
