### ISSUE TITLE
heartbeatInterval maximum value

### ISSUE THREAD

**Issue by PaoloP98** [transistorsoft/flutter_background_geolocation#528]
What is the maximum _heartbeatInterval_ value to make it work on ios even when the app is terminated?
At the moment I use 60 seconds but I would like to increase

**Comment by christocracy** [comment]
>What is the maximum heartbeatInterval value to make it work on ios even when the app is terminated?

There is no heartbeat when an iOS app is terminated.

The most frequent rate is `60` seconds.  There is no possibility of making it any more frequent.

**Comment by PaoloP98** [comment]
> > What is the maximum heartbeatInterval value to make it work on ios even when the app is terminated?
> 
> There is no heartbeat when an iOS app is terminated.
> 
> The most frequent rate is `60` seconds. There is no possibility of making it any more frequent.

Is it possible to get the location when the app is terminated on iOS?

**Comment by christocracy** [comment]
>Is it possible to get the location when the app is terminated on iOS?

it is **impossible** for you to do *anything* after the user terminates the iOS app.  When the iOS device moves about *200 meters*, the plugin will cause iOS to re-launch your app and tracking will resume.

**Comment by PaoloP98** [comment]
> > Is it possible to get the location when the app is terminated on iOS?
> 
> it is **impossible** for you to do _anything_ after the user terminates the iOS app. When the iOS device moves about _200 meters_, the plugin will cause iOS to re-launch your app and tracking will resume.

well, 200 meters can be fine.
To increase this value I can use distanceFilter, right?

**Comment by christocracy** [comment]
>well, 200 meters can be fine.

This behaviour is easily demonstrated in the iOS simulator with simulated location *Freeway Drive*.

This has nothing to do with `distanceFilter`.  It's related to `stationaryRadius` (and the minimum that iOS will respond to is ~200 meters.  Setting `stationaryRadius: 0` has no effect.

**Comment by PaoloP98** [comment]
Can I listen to event _onLocation_ when I get Stationary notification or it triggers some other event?

**Comment by christocracy** [comment]
Are you aware of all 13 events available to you?

**Comment by PaoloP98** [comment]
These
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Event-class.html

**Comment by christocracy** [comment]
Yes.  Isn't there one event in particular that might be more interesting to you?

**Comment by PaoloP98** [comment]
Maybe the onSchedule event, thanks. I will try

**Comment by christocracy** [comment]
Is was thinking you might like onMotionChange.

**Comment by PaoloP98** [comment]
In order to save battery I would like to take the position every X minutes.  Scheduled events might be fine
