### ISSUE TITLE
Continue tracking when app is killed / device is turned off and on again.

### ISSUE THREAD

**Issue by flxwu** [transistorsoft/flutter_background_geolocation#530]
## Your Environment
* Plugin version: ^1.9.0
* Platform: both
* OS version: - 
* Flutter info (`flutter doctor`): all green
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
_config = bg.Config(
      heartbeatInterval: 70,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      preventSuspend: true,
      stopTimeout: 1,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      locationAuthorizationRequest: 'Always',
      geofenceModeHighAccuracy: true,
    );
```

## Expected Behavior
Background location tracking (geofences & heartbeat) should continue when app is killed, and automatically resume when device is rebooted.

## Actual Behavior
Tracking stops when app is killed.

## Steps to Reproduce

1. Open App, start location tracking (works)
2. Kill App
3. Now, location tracking stopped.

## Context
We're building an app that tracks you crossing the border, which it should also do when the app is killed.

</details>

**Comment by christocracy** [comment]
> Background location tracking (geofences & heartbeat) should continue when app is killed

This is the behavior of the plugin.

However, iOS and Android operate completely different in these cases.

See the api docs Config.stopOnTerminate for more information.

- it is impossible for iOS heartbeat to remain running after terminate.  Android will.
- iOS requires the device move at least 200 meters after terminate / device reboot before tracking resumes.  Android is unaffected.  You must simply unlock the device after reboot before heartbeat will restart.

**Comment by flxwu** [comment]
Thanks a lot for the reply! By "tracking resumes", you mean the geofences? (since you said heartbeat is impossible)

**Comment by christocracy** [comment]
Yes, "tracking resumes" implies geofence-monitoring.

When you terminate an iOS app, keep moving.  Enable `debug: true` so you can *hear* and *see* the plugin come alive.  This is easily demonstrated in the iOS simulator.

**Comment by flxwu** [comment]
Hi Chris,

so we've been trying this out over the past week, however it didn't seem to work reliably. Do you have any ideas why that could be?  Also, as a more general question: Aside from geofences, how can we keep tracking the user's location after app kill? We've found some other apps like queuewisely.com that seem to achieve this without geofences.

Appreciate the help, thanks!

**Comment by christocracy** [comment]
>so we've been trying this out over the past week, however it didn't seem to work reliably

I've been testing this for over 6 years and it never fails to track me anywhere I go.  I suggest you try out the `/example` app in this repo.

>Aside from geofences, is there any way we can keep tracking the user's location after app kill on iOS?

No.  There's no possible way to awaken a terminated app and resume tracking, in spite of what you may think of this `queuewisely.com`, other than a geofence.  There's no secret magic trick with iOS that somebody is aware of that I'm not.
