### ISSUE TITLE
Can not register app.

### ISSUE THREAD

**Issue by VatsalBhesaniya** [transistorsoft/flutter_background_geolocation#532]
## Your Environment
* Plugin version: 1.10.0+1/2.0.0
* Platform: iOS and Android
* OS version: 14.4
* Device manufacturer / model: Simulator/Emulator/iPhoneX
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (1 available)
• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      transistorAuthorizationToken: token,
      reset: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      autoSync: true,
      stopOnTerminate: false,
      foregroundService: true,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
      isMoving: false,
    ),
```

## Expected Behavior
Library should be initialised on app start.

## Actual Behavior
Could not find or create token.

## Steps to Reproduce

1. Open app.
2. Initialise library.

## Context
We are building an app that track location of user and send notification if user is within the radius.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I have no idea what you mean.

You've not provided any logs to show what you're talking about,

See wiki *Debugging*.

**Comment by VatsalBhesaniya** [comment]
I am calling this function to get token and it is throwing exception.
`static Future<TransistorAuthorizationToken> findOrCreate(
      String orgname, String username,
      [String url = _DEFAULT_TRANSISTOR_URL]) async {
    Completer completer = new Completer<TransistorAuthorizationToken>();
    _methodChannel.invokeMethod(
        'getTransistorToken', [orgname, username, url]).then((dynamic data) {
      completer.complete(TransistorAuthorizationToken(data[FIELD_ACCESS_TOKEN],
          data[FIELD_REFRESH_TOKEN], data[FIELD_EXPIRES], url));
    }).catchError((error) {
      print("[TransistorAuthorizationToken findOrCreate] ERROR: $error");
      if (error.code != "403") {
        completer.complete(
            TransistorAuthorizationToken(_DUMMY_TOKEN, _DUMMY_TOKEN, -1, url));
      } else {
        throw error;
      }
    });
    return completer.future;
  }`

**Comment by christocracy** [comment]
What does $ adb logcat say?

**Comment by christocracy** [comment]
And what params are you providing the create the token?

You know that is only for sending locations to my test/demo server?  In production, you won't be using that.

**Comment by VatsalBhesaniya** [comment]
This is the function to register app.
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Future<TransistorAuthorizationToken> registerApp() async {
  await TransistorAuthorizationToken.destroy(trackerHost);
  final TransistorAuthorizationToken token =
      await bg.TransistorAuthorizationToken.findOrCreate(
          'startTrack', 'K8SLLC', 'http://tracker.transistorsoft.com');

  bg.BackgroundGeolocation.setConfig(
      bg.Config(transistorAuthorizationToken: token));

  return token;
}
```

**Comment by christocracy** [comment]
You know you can't use my demo/test server tracker.transistorsoft.com for your production app, right?

TransistorAuthorizationToken is only for short-term developer debugging/testing.

**Comment by christocracy** [comment]
Your chosen org `startTrack` has been **banned** from the demo server for posting too many locations over a long period of time.  The org `startTrack` has registered **195 devices** and *hundreds of thousands* of records.  `tracker.transistorsoft.com` is closely monitored for suspicious activity.

I suggest you deploy your own instance of the demo server on your own infrastructure:
https://github.com/transistorsoft/background-geolocation-console

**Comment by VatsalBhesaniya** [comment]
Thank you for your support.
It was our mistake. We were doing it wrong way.
I should refer this [](https://github.com/transistorsoft/background-geolocation-console) to authorise my app, right?

**Comment by christocracy** [comment]
I don't provide support for `background-geolocation-console`.  If you want to use that as your server, you're on your own.

But **DO NOT** use `tracker.transistorsoft.com` as your production server.
