### ISSUE TITLE
com.transistorsoft:tsbackgroundfetch:+ as no versions

### ISSUE THREAD

**Issue by ghermezkon** [transistorsoft/flutter_background_geolocation#538]
hi
when i want to run app with plugin i catch this error:
Launching lib/main.dart on SM N920C in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/mehdi/AndroidStudioProjects/new_faloop_app/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/home/mehdi/AndroidStudioProjects/new_faloop_app/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
You didn't perform the [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation#-setup-guides)
