### ISSUE TITLE
Wrong timestamp location event.

### ISSUE THREAD

**Issue by cbfischer** [transistorsoft/flutter_background_geolocation#54]
I need the timestamp to be stored in each location event. When the device runs out of the internet, all events are stored on the device itself - so far it works perfectly. However, when the internet link becomes active again, all events that were stored on the devices are updated with the current time. I need the timestamp of the event to represent the time of the recording on the device and not the time when the internet link was reestablished. It is possible? In Android and Iphone? 

## Your Environment
* Plugin version: flutter_background_geolocation: ^1.0.0-rc.4
* Platform: iOS and Android
* OS version: Windows 10
* Device manufacturer / model: Motorola
* Flutter info (`flutter doctor`): 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.4.7, on Microsoft Windows [versÃ£o 10.0.17763.437], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Proxy Configuration
[√] Connected device (1 available)

• No issues found!
```

* Plugin config

## Expected Behavior
timestamp represents the time the event was stored.

## Actual Behavior
timestamp represents the time that was sent POST

## Steps to Reproduce
1. Start Location Service
2. Put the smartphone on "Flight Mode"
3. Wait some time
4. Turn off the "Flight mode". 
5. All timestamp events in the log buffer will be sent at the wrong time.

**Comment by christocracy** [comment]
>all events that were stored on the devices are updated with the current time.

Once a location is recorded in the plugin's SQLite database, it's data is *immutable*.  `location.timestamp` is never modified.

**Comment by cbfischer** [comment]
> > all events that were stored on the devices are updated with the current time.
> 
> Once a location is recorded in the plugin's SQLite database, its data is _immutable_. `location.timestamp` is never modified.


I also believed it to be _immutable_. So what am I doing wrong? Because timestamp is coming wrong on POST.

```
{
	"location": {
		"is_moving": false,
		"uuid": "6ba54624-d5dd-43a2-bd30-7edec2608046",
		"timestamp": "2019-04-03T19:14:10.969Z",
```

**Comment by christocracy** [comment]
I don't know.  This is the `timestamp` as reported by the device's location API.

The plugin is just the mailman, delivering the mail to you exactly as it received it.

**Comment by joserocha3** [comment]
I was having a similar issue here https://github.com/transistorsoft/flutter_background_geolocation/issues/43#issuecomment-475048978.

My issue was I was setting some listeners after calling #ready. Changed to code to set all listeners before ready and it fixed the issue.

**Comment by cbfischer** [comment]
Wonderful. I think I understood the problem. Thank you ;)
