### ISSUE TITLE
Best config for only hearbeart event

### ISSUE THREAD

**Issue by dangfe** [transistorsoft/flutter_background_geolocation#543]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.BackgroundGeolocation.onHeartbeat(onHeartbeat);
    bg.BackgroundGeolocation.ready(bg.Config(
            disableMotionActivityUpdates: true,
            showsBackgroundLocationIndicator: false,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            stopOnTerminate: false,
            disableElasticity: true,
            startOnBoot: true,
            distanceFilter: 0,
            heartbeatInterval: 420,
            reset: true,
            enableHeadless: true,
            notificationPriority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
            fastestLocationUpdateInterval: 420000,
            debug: false,
            preventSuspend: true,
            stationaryRadius: 500,
            useSignificantChangesOnly: true,
            notification: bg.Notification(
              sticky: false,
              priority: bg.Config.NOTIFICATION_PRIORITY_LOW,
            ),
            logLevel: bg.Config.LOG_LEVEL_INFO))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
        stateApp = state;
      }
    });
```

## Expected Behavior
I just want after a period of time ( 7 mins), the app sends location to server. I read the document and thought I should use the hearbeart event.
And here is the config in my application.
Let me ask if this is the best config and save battery life the most.
</details>

**Comment by christocracy** [comment]
If you're interested in battery-life, don't use heartbeat (and especially *don't* use ios `preventSuspend: true`, which is a **battery killer**.

This plugin is designed to track location only when the device is *moving*.

For periodic location updates, use `background_fetch`.

**Comment by christocracy** [comment]
> fastestLocationUpdateInterval: 420000,

This doesn't save battery life at all.

You cannot develop an app that constantly records the location *every x minutes*, even when the device is *stationary*.
