### ISSUE TITLE
Android can't build after update to flutter_background_geolocation 2.0.1 

### ISSUE THREAD

**Issue by WUKS87** [transistorsoft/flutter_background_geolocation#544]
## Your Environment
* Plugin version: 2.0.1
* Platform: Android
* OS version: SDK 30
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`):

<img width="633" alt="Screen Shot 2021-04-10 at 9 56 30 AM" src="https://user-images.githubusercontent.com/1992520/114262964-17272780-99e3-11eb-852a-b163aaf1d36e.png">

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 100.0,
        // elasticityMultiplier: 5.0,
        enableHeadless: true,
        // preventSuspend: true,
        // heartbeatInterval: 60,
        triggerActivities: 'in_vehicle',
        isMoving: true,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    ));
```

## Expected Behavior
Android build to pass: flutter build apk --release

## Actual Behavior
It throws an error:
<img width="1381" alt="Screen Shot 2021-04-10 at 10 00 12 AM" src="https://user-images.githubusercontent.com/1992520/114263074-b9470f80-99e3-11eb-8557-f8eb3a7a6f23.png">

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you tried the usual things?
- flutter clean
- .gradlew clean

**Comment by WUKS87** [comment]
Yes, I tried that. The same error appears.
Could it be related to gradle version?

<img width="550" alt="Screen Shot 2021-04-11 at 8 32 17 AM" src="https://user-images.githubusercontent.com/1992520/114294686-8ca4fd80-9aa0-11eb-98c5-3b9852e61f8b.png">

**Comment by WitAlex** [comment]
Solution that worked for me: 
- edit _android/gradle.properties_, enabled R8 compiler: 

```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
```

**Comment by WUKS87** [comment]
@WitAlex Yup, that worked for me too :)
Thank you for sharing.

Closing this issue!
