### ISSUE TITLE
How to change some Configs on the fly and get current configurations?

### ISSUE THREAD

**Issue by aweiand** [transistorsoft/flutter_background_geolocation#545]
## Your Environment
* Plugin version: 2.0.1
* Platform: Android
* OS version: 11.0 (API 30)
* Device manufacturer / model: Pixel XL (Android Studio Emulator)
* Flutter info (`flutter doctor`):
 ```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale pt-BR)
    • Flutter version 2.0.4 at /Users/aweiand/flutter
    • Framework revision b1395592de (9 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/aweiand/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
Process finished with exit code 0
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 static const LOCATIONS_URL = "https://wwww/api/locations";
  static const HEARTBEAT_URL = "https://wwww/api/heartbeats";

  static bg.Config bgConfig = bg.Config(
      url: LOCATIONS_URL,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      notification: bg.Notification(
        title: "wwww",
        text: "Captura de Localização Ativa",
        channelName: "Captura de localização",
        smallIcon: "mipmap/ic_launcher_foreground",
        largeIcon: "mipmap/ic_launcher_foreground",
        sticky: true,
      ),
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      autoSync: true,
      autoSyncThreshold: 10,
      batchSync: true,
      maxBatchSize: 50,
      locationsOrderDirection: "ASC",
      maxDaysToPersist: 2,
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Permitir que o www App acesse a localização do dispositivo mesmo quanto está fechado e não em uso.",
          message:
          "Este aplicativo coleta dados de localização para cálculo de pagamento de KM.",
          positiveAction: 'Alterar para Sempre',
          negativeAction: 'Cancelar'),
      locationAuthorizationAlert: {
        "titleWhenNotEnabled": "A captura em segundo plano não está habilitada",
        "titleWhenOff": "A captura em segundo plano não está habilitada",
        "instructions":
        "Para usar o aplicativo em segundo plano, deves marcar sempre na caixa de seleção de permissão.",
        "cancelButton": "Cancelar",
        "settingsButton": "Configuração"
      },
      enableHeadless: true,
      // params: {"itinerary_id": 1},

      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      // debug: true,
      // logLevel: bg.Config.LOG_LEVEL_VERBOSE,
  );
```

## Expected Behavior

I`m was trying to change some configuration parameters on the fly, with this code:
```dart
  static void heartbeatMode(){
    bg.Config _bgConfig = bgConfig;
    _bgConfig.url = HEARTBEAT_URL;
    _bgConfig.distanceFilter = 100.0;
    _bgConfig.maxBatchSize = 10;
    bgConfig = _bgConfig;
    bg.BackgroundGeolocation.setConfig(_bgConfig).then((bg.State state) {
      bg.BackgroundGeolocation.sync();
    });

    Hive.box('wwww').put('location-capture', false);
  }
```

## Actual Behavior

This is the correct way? 
And, how I get the current config? The URL for example?

## Steps to Reproduce

1. Call heartbeatMode() method during the execution of the app.
2. After close and reopen the app, the changes is fixed?
3. I don't know how to get the current Config in execution

## Context

I`m have a app that capture user position and sendo to server, but, when the user clicks on a button, whe change the way of connection the dots (to create a path) to just heartbeats of positions of the user. In this way we need to know how is the current URL (and other configs) to allow correct UI changes.
Currently we store every change in a Hive Box, but apparently is not the better way because some times we have a bug...

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Don't have
```

</details>

**Comment by christocracy** [comment]
See api docs.

- BackgroundGeolocation.setConfig
- BackgroundGeolocation.state

**Comment by aweiand** [comment]
Work's. 
But, sometimes the plugin duplicates the sended points. We are change many times the configs (basically URL and distancefilter), with `BackgroundGeolocation.setConfig(_bgConfig);` mentioned in the docs/above.
Sometimes the plugin send the points to the two configs. Looking in the App Inspection on Android Studio and transistor_logback.bd I'we found a strange data... there are 50 records duplicates, is this correct?

![Captura de tela de 2021-11-29 21-45-38](https://user-images.githubusercontent.com/1443817/143965250-0cbb5b7e-0144-4271-9094-2e814485099d.png)

**Comment by christocracy** [comment]
Every time you change `distanceFilter`, the plugin emits a new location immediately.

>App Inspection on Android Studio and transistor_logback

Why are you looking at the raw log database?

**Comment by aweiand** [comment]
But, why are duplicating locations? 
In our backend we are receiving events in the two URLs (the two configs changing in app), but not always, and not with the same device...
I'm looking at all the my code to find why this occurs. In one of this searches I'we found these records, and appears strange, because they are duplicated many times, and, maybe this is the problem, no?

**Comment by christocracy** [comment]
I don't see anything unusual for n that screenshot.

**Comment by aweiand** [comment]
> I don't see anything unusual for n that screenshot.

The mapped_key "VERSION_CODE" have 5 times, is this correct?

**Comment by christocracy** [comment]
Looking at the logback database is pointless.

It's not just location events that are logged there.

**Comment by aweiand** [comment]
Ok. But, how debug the duplicated points? Is there a problem change many times the url and distancefilter (almost 8 times per day)?
My app starts the plugin on the morning and end at night. In this interval, changes the config by 3 at 10 times, sometimes...

**Comment by christocracy** [comment]
See the api docs TransistorAuthorizationToken to post your data to the demo server.
