### ISSUE TITLE
Android Notification Id

### ISSUE THREAD

**Issue by bliq-ai** [transistorsoft/flutter_background_geolocation#546]
Would it be possible to customize the Android Notification id?

We would like to run another (unrelated to tracking) service in parallel, but share the same notification already in use by the Background Geolocation plugin.

For now, it would be helpful if you just tell us what is the current notification id used by the plugin, so we can experiment to confirm if that notification sharing is possible.

Thanks in advance!

**Comment by christocracy** [comment]
>Would it be possible to customize the Android Notification id?

No.  It's hard-coded.

>For now, it would be helpful if you just tell us what is the current notification id used by the plugin,

It's my phone number:

```java
public static final int NOTIFICATION_ID = 9942585;
```

**Comment by bliq-ai** [comment]
Thanks!
