### ISSUE TITLE
Confusion surrounding disableStopDetection

### ISSUE THREAD

**Issue by nattyg93** [transistorsoft/flutter_background_geolocation#55]
## Your Environment
* Plugin version: 1.0.1
* Platform: Android
* OS version: 9
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config

## Expected Behavior
I am trying to understand the behaviour of `disableStopDetection`. My understanding was that if `disableStopDetection` is set to true, then on Android the foreground service would not stop. But even with this set to true, after the `stopTimeout` duration has been exceeded the persistent notification disappears and the plugin stops. Is this the expected behaviour?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Fixed in 1.0.8.
