### ISSUE TITLE
Android Notification Channel

### ISSUE THREAD

**Issue by bliq-ai** [transistorsoft/flutter_background_geolocation#552]
Sorry for bothering you again.

This is just a follow-up for this ticket:
https://github.com/transistorsoft/flutter_background_geolocation/issues/546

Could you share with us what Channel Id are you using?

**Comment by christocracy** [comment]
I posted the channel id in that thread.

**Comment by christocracy** [comment]
Oh, wait that was *notification id*.  I think you want to see the API docs `Config.Notification`.

The channel id is configurable.

**Comment by bliq-ai** [comment]
@christocracy we can configure the channel name there, but not the channel id.

**Comment by christocracy** [comment]
```java
String channelId = context.getPackageName() + BackgroundGeolocation.TAG;
```
- `context.getPackageName()` is your applicationId (eg: `com.foo.bar`).
- `BackgroundGeolocation.TAG` = `TSLocationManager`

eg:  `com.foo.barTSLocationManager`

**Comment by bliq-ai** [comment]
Thank you!
