### ISSUE TITLE
feature request to handle location data upload mechanism through callback function instead of https

### ISSUE THREAD

**Issue by Husnain-Asharf** [transistorsoft/flutter_background_geolocation#554]
> 

## Expected Behavior
I want a feature to get locations data in callback function not through http url. If callback function return true then discard from DB else saved and try to send again like it's currently doing with http mechanism.

## Actual Behavior
Currently locations record uploaded to server and discard from DB through http mechanism.

## Context
 In my application I need location data in callback function with same mechanism because I want to handle upload locations to server like:
- lock location to upload
- send location to callback
- if return true then discard from DB

</details>

**Comment by christocracy** [comment]
This is not possible to perform 2 way communication between dart and native.

I suggest you use the built-in http service.

Otherwise, you are on your own.
