### ISSUE TITLE
Unhandled Exception: type 'Future<void>' is not a subtype of type 'FutureOr<List<dynamic>>'

### ISSUE THREAD

**Issue by kightsonsanom** [transistorsoft/flutter_background_geolocation#555]
## Description
  Cast type exception thrown when trying to  sync background location. The exact place where the cast is performed is line 629 in `background_geolocation.dart` file : 
```
   static Future<List> sync() async {
    return (await _methodChannel.invokeListMethod('sync')) as FutureOr<List>;
  }
```

I suggest checking all the places when casts to `FutureOr` are performed - this is something that the dart null-safety migration tool adds by default and it usually causes cast exceptions.

## Your Environment
* Plugin version: 

```
flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: nullsafety-DeviceInfo
```

* Platform: both
* OS version: all
* Device manufacturer / model: all
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (2 available)

• No issues found!

```

## Expected Behavior
No cast exception thrown

## Actual Behavior
Cast exception is thrown

## Steps to Reproduce and Context
Use `BackgroundLocation.sync()` method

## Debug logs

``` 
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<void>' is not a subtype of type 'FutureOr<List<dynamic>>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
#3      Future._completeError (dart:async/future_impl.dart:547:5)
#4      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#5      BackgroundGeolocation.sync (package:flutter_background_geolocation/models/background_geolocation.dart)


```

**Comment by christocracy** [comment]
I don't seem to have problem with `sync`.  Show me the code you're using to execute this.

**Comment by christocracy** [comment]
I think the problem is in your  own code. 

When I paste your code into *Android Studio* I see warnings:

1.  `sync`
![](https://dl.dropbox.com/s/3dtx5hxv74pphmt/Screen%20Shot%202021-04-27%20at%2010.00.09%20AM.png?dl=1)

2. `getCurrentPosition`:
![](https://dl.dropbox.com/s/uxazxcnm5f5ua0y/Screen%20Shot%202021-04-27%20at%2010.01.24%20AM.png?dl=1)

**Comment by kightsonsanom** [comment]
@christocracy thanks! didn't notice that I have these analyzer warnings ignored in the project. It seems to work fine after I applied changes. However on Android 9, Redmi Note 4 I receive `LocationError` with 499 error code 
![image](https://user-images.githubusercontent.com/24854180/116258761-8471e100-a775-11eb-96db-6804b38c80ef.png)

I don't see this code described in [wiki](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Error-Codes), should I create a separate issue for this?

**Comment by christocracy** [comment]
Wiki updated.  `499` = location request cancelled.

*One* example where this could happen is call `.start()` and immediately calling `.stop()`.

**Comment by kightsonsanom** [comment]
I was able to reproduce the issue regarding `sync` method. It happens only on iOS, I used iOS Simulator iPhone Pro Max 13.0.


```
flutter: [syncLocations] Syncing 2 items.
flutter: [onLocation] [syncLocations] Sync completed with ERROR: PlatformException(3, Sync failure, null, null)
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<List<dynamic>>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
#3      Future._completeError (dart:async/future_impl.dart:547:5)
#4      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#5      BackgroundGeolocation.sync (package:flutter_background_geolocation/models/background_geolocation.dart)
```

this is my current code that uses `BackgroundGeolocation.sync`

```
 final List<dynamic> syncedItems =
        await bg.BackgroundGeolocation.sync().catchError((Object syncError) {
      _log('$logPrefix [syncLocations] Sync completed with ERROR: $syncError');
    });
```

**Comment by christocracy** [comment]
Your `dart` code is incorrect.

If you want to catch errors while using `await`, you must do it like this:

```dart
// 1.  With await
try {
  List rs = await bg.BackgroundGeolocation.sync();
  print("sync: $rs");
} catch(error) {
  print("ERROR: $error");
}

// 2.  Or without await
bg.BackgroundGeolocation.sync().then((List rs) {
  print("sync 2: $rs");
}).catchError((error) {
  print("ERROR 2: $error");
});

```

**Comment by kightsonsanom** [comment]
you are correct, I guess the issue can be closed
