### ISSUE TITLE
[Android] ProviderChange gps is false even though it's turned on again

### ISSUE THREAD

**Issue by jlabeit** [transistorsoft/flutter_background_geolocation#557]
## Your Environment
* Plugin version: 2.0.5
* Platform: Android
* OS version: 10.0.0
* Device manufacturer / model: Huawei SNE-LX1
* Flutter info (`flutter doctor`): X
* Plugin config: Default config from [Playstore](https://play.google.com/store/apps/details?id=com.transistorsoft.flutterbackgroundgeolocationexample) advanced app version 2.0.5
```dart <-- Syntax highlighting: DO NOT REMOVE -->
// Default code from advanced example app for android
```

## Expected Behavior
`ProviderChangeEvent.gps` should be true if the GPS / Location service is turned back on.

## Actual Behavior
The onProviderChange evnet is triggered hower `ProvideChangeEvent.gps` remains false even though the Location service has been turned on again.

## Steps to Reproduce
1. Listen to the onProviderChange event.
2. Turn off location services on the phone.
3. See an `onProviderChange` event this `gps = false` is being recorded.
4. Turn on location services on the phone.
5. See another `onProviderChange` event is being recorded (though with `gps = false`).

Note: When terminating the foreground task and then listening to `HeadlessEvent` and performing the same steps the `HeadlessEvents` work like expected (one event is triggered wth `gps = false` when turning locatoin services off and one with `gps = true` when turning it on again.

Video of the issue reproduced with the playstore example app:
https://user-images.githubusercontent.com/2670732/116537194-33352f00-a8e6-11eb-938a-3e851cc8820e.mp4

## Context
Within our app I am trying to implement a warning screen that warns the user if some device settings are not done properly and thus the tracking might not work. One of these settings are if the user simply disables location services. This warning works correctly however once the user has enabled location services I want to remove the warning again.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Huawei has a problem with this event.

Test with a different device.

Huawei are the worst devices on earth.

**Comment by christocracy** [comment]
You can query the current state of location-service via [`BackgroundGeolocation.providerState`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/providerState.html)

**Comment by jlabeit** [comment]
> You can query the current state of location-service via [`BackgroundGeolocation.providerState`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/providerState.html)

Thanks that solves a few of my problems :+1:
