### ISSUE TITLE
No Background activity on IOS

### ISSUE THREAD

**Issue by chitwoob** [transistorsoft/flutter_background_geolocation#56]
Hello, 
I'm having problems with the plugin while in background. It seems go go completely dormant on my Iphon6. I've tested it three times now.  All three times I've traveled at least a mile with the phone.  Each time I see no events in the logs. I attached the logs from my last test 9:39AM - 9:44AM. As you can see the plugin didn't do anything during my trip. I did hear a few beeps from the phone, but nothing showed up in the logs. 

## Your Environment
* Plugin version: Current Master
* Platform: iOS 
* OS version: 12.2
* Device manufacturer / model: IPhone 6

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.5-pre.17, on Mac OS X 10.14.4 18E226, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

```
void initState() {
    super.initState();
    setBackGroundLocation();
}
Future<Null> setBackGroundLocation() async {
    bg.BackgroundGeolocation.onLocation(_handleCurrentLocationUpdate);

    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            startOnBoot: true,
            foregroundService: true,
            url: ApiHelper.RootUrl,
            autoSync: true,
            method: 'POST',
            maxDaysToPersist: 2,
            notificationChannelName: 'MyLocationService',
            notificationTitle: 'Test',
            notificationText: 'Test Monitoring',
            notificationPriority: bg.Config.NOTIFICATION_PRIORITY_MIN,
            headers: {
              "Content-Type": "application/json",
              "Authorization": "Bearer " 
            },
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            reset: true))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    }).catchError((error) {
      print(‘ [ready] ERROR: $error');
```

## Expected Behavior
I expect it to transmit the current location while the device is moving.

## Actual Behavior
Plugin is inactive.

## Steps to Reproduce
1) Open the app. 
2) Click Home Button. 
3) Double Click home Button, 
4) Swipe away test app. 
5) Hop in the Jeep with the phone. 
6) Drive around for a while.
7) Note the time and download the logs. 

## Debug logs
2019-04-26 09:34:38.740 ℹ️-[TSDBLogger db_save] Log committed

2019-04-26 09:34:40.713 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 09:34:43.872 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 09:34:44.505 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 09:35:39.591 ℹ️-[TSDBLogger db_save] Log committed

2019-04-26 09:45:23.965 ℹ️-[TSLocationManager init] {

**Comment by christocracy** [comment]
- Have you tested in iOS simulator with `Debug->Location->Freeway Drive`?
- Is WIfi Enabled?
- Did you authorize "Always" (you must)?

**Comment by chitwoob** [comment]
Wow! That was a quick response!

I haven't tested in a simulator yet. I'll do that now. I checked the access settings. Location is set to always with both Motion & Fitness and Background App Refresh enabled. Wifi is enabled. 

I should also add that this phone doesn't have a sim card in it. I'm using WIFI only. On my drive it's not connected to wifi or a network.

**Comment by christocracy** [comment]
>I should also add that this phone doesn't have a sim card in it. I'm using WIFI only. On my drive it's not connected to wifi or a network.

That's fine.  As long as Wifi is *enabled*.

And make sure that your app is **always** calling `BackgroundGeolocation.ready` when the app boots, **no matter what**.  You cannot hide the call to `BackgroundGeolocation.ready` within some view that the user must first click.

**Comment by chitwoob** [comment]
That's really helpful. I am doing that. I'll update the code an try again.

**Comment by christocracy** [comment]
I wrote this to someone using the Cordova version yesterday:

Yes.  Think of the plugin as a stereo receiver:
- `#ready` = plugging in the AC cord to to the wall.
- `#start` = turning on the power button.
- `#stop` = turning off the power button.

The plugin does, of course, *remember* the last state of the *power button* (ie: `#start`), so if you unplug the receiver's AC cord from the wall then plug it in again (ie: terminate and reboot app), it's going to power up automatically if the power button was **ON** when you yanked the cord from the wall.

If you unbox the receiver the *first time* and plug in the power cord (ie: first install of you app), the power button is in the default **OFF** position --  Calling `#ready` at first launch will *not* cause the plugin to automatically `#start`.

**Comment by chitwoob** [comment]
I copied my setBackGroundLocation() method into the main statefull widget
main() => runApp(MainApp()) -> MainApp -> MainAppState -> void initStat{...}

I didn't see an improvement in the behavior. The app did make some beeps mid way through my drive, but nothing was added to the logs at that time. I drove from 11:19 to 11:24. As you can see it didn't log anything during that time. It's odd, because it did beep during that time. I don't have any other logic that work with bg other than a button that transmits the logs to my server and an onLocation listener.

2019-04-26 11:16:54.511 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 11:16:57.673 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 11:16:57.992 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 11:17:02.410 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-04-26 11:26:22.747 ℹ️-[TSLocationManager init] {

**Comment by christocracy** [comment]
- Show me XCode logs of your app booting in the Simulator.

**Comment by chitwoob** [comment]
Note: The simulator seems far more active that the phone was during my drive. 

Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...                                          
Xcode build done.                                            9.5s
Configuring the default Firebase app...
5.15.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
5.15.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50400000 started
5.15.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Syncing files to device iPhone Xʀ...                            
5.15.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:

https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging

to ensure proper integration.

Configured the default Firebase app __FIRAPP_DEFAULT.

	Connected Path: satisfied (Path is satisfied), interface: en1

	Duration: 1.582s, DNS @0.001s took 0.024s, TCP @0.027s took 0.041s, TLS took 0.800s

	bytes in/out: 4691/1029, packets in/out: 10/9, rtt: 0.045s, retransmitted packets: 0, out-of-order packets: 0

ℹ️-[TSConfig persist]

🔵-[TSLocationManager ready]

flutter: MAPDOTDBG Main START



╔═══════════════════════════════════════════════════════════

║ -[TSLocationManager start] 

╚═══════════════════════════════════════════════════════════

ℹ️-[TSLocationManager doStart:] trackingMode: 1

ℹ️-[TSConfig persist]

🎾-[TSGeofenceManager start]

🔵-[TSLocationManager setPace:] 0

🎾-[TSLocationManager startUpdatingLocation] Location-services: ON



╔═══════════════════════════════════════════════════════════

║ -[TSHttpService flush:error:] 

╚═══════════════════════════════════════════════════════════



╔═══════════════════════════════════════════════════════════

║ -[TSHttpService finish:error:] Success: 1

╚═══════════════════════════════════════════════════════════

ℹ️+[LocationAuthorization run:onCancel:] status: 0

🔵+[LocationAuthorization run:onCancel:] Request: requestAlwaysAuthorization

[TSBackgroundFetch addListener]: TSLocationManager

🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON

[TSBackgroundFetch start]
Syncing files to device iPhone Xʀ...                             2,936ms (!)

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone Xʀ is available at: http://127.0.0.1:59881/1Sg9JNxG7Io=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
ℹ️-[TSConfig persist]
🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 3
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
ℹ️+[LocationAuthorization run:onCancel:] status: 3

📍<+37.33036720,-122.02923067> +/- 10.00m (speed 7.18 mps / course 118.94) @ 4/26/19, 11:56:19 AM Eastern Daylight Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 65.3s
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...

📍<+37.33036720,-122.02923067> +/- 10.00m (speed 7.18 mps / course 118.94) @ 4/26/19, 11:56:23 AM Eastern Daylight Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 61.3s
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager locationManager:didUpdateLocations:] Received stale motionchange location.  Retrying...

📍<+37.33023490,-122.02383693> +/- 10.00m (speed 7.51 mps / course 87.77) @ 4/26/19, 11:57:25 AM Eastern Daylight Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 0.0s
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+37.33023490,-122.02383693> +/- 10.00m (speed 7.51 mps / course 87.77) @ 4/26/19, 11:57:25 AM Eastern Daylight Time
🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 25
🔴-[TSLocationManager stopUpdatingLocation]
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 10.0
🎾-[TSLocationManager startMonitoringSignificantLocationChanges]
✅-[TSLocationManager persistLocation:]_block_invoke INSERT: C9213C86-8DC6-4F6D-93B3-6C4AF53BEA97

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════
✅-[BackgroundTaskManager createBackgroundTask] 2
✅-[TSHttpService schedulePost:] LOCKED: C9213C86-8DC6-4F6D-93B3-6C4AF53BEA97
🔵-[TSHttpService doPost:] HTTP Response: 200
✅-[TSHttpService post:error:] DESTROY: C9213C86-8DC6-4F6D-93B3-6C4AF53BEA97

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 1
╚═══════════════════════════════════════════════════════════
✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 2 OF (
    2
)
	[C7.1 D7BD2AB5-05C1-46F3-BC1A-9F8FC4A314AA 192.168.1.12:59908<->172.217.6.14:443]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 0.306s, DNS @0.000s took 0.001s, TCP @0.002s took 0.021s, TLS took 0.073s
	bytes in/out: 3880/814, packets in/out: 9/9, rtt: 0.026s, retransmitted packets: 1, out-of-order packets: 0
	[C8.1 E417E5AF-5787-42DE-8175-5E895116DC86 192.168.1.12:59909<->172.217.6.14:443]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 0.127s, DNS @0.000s took 0.001s, TCP @0.004s took 0.020s, TLS took 0.067s
	bytes in/out: 3597/1201, packets in/out: 9/9, rtt: 0.020s, retransmitted packets: 0, out-of-order packets: 0
🔵-[TSLocationManager onSuspend:] enabled? 1)
ℹ️-[TSDBLogger db_save] Log committed
[TSBackgroundFetch onAppTerminate]
ℹ️-[TSDBLogger db_save] Log committed
Lost connection to device.
[TSBackgroundFetch stop]

**Comment by christocracy** [comment]
In simulator, start `Debug->Location->Freeway Drive`.

Then terminate the app.  It should re-launch a few seconds later.

**Comment by chitwoob** [comment]
I found the issue. My API service was throwing errors when the heading was a decimal. I had it as a type int. Running the simulator helped to point that out. I just tried a real world test again. It's working as expected. It did take a bit longer than I wanted to start monitoring, but that might just be a setting or an IOS limitation. 

I still don't see any TSLocator logs during that time period, but It's clearly working. That gap in the log's made me think is wasn't my code causing the issue. I did find it really odd that I was getting the debug notifications and beeps, but no logs. You might have a bug in your logging logic. Based on my observation the logging goes completely dark when it's in background mode. 

Thanks again for your help.

**Comment by christocracy** [comment]
First working version of Firebase Adapter for BackgroundGeolocation is pushed to the Git repo (Not yet published to pub.dev).
https://github.com/transistorsoft/flutter_background_geolocation_firebase

You must install from Git until it's published.
