### ISSUE TITLE
Need help about location updates

### ISSUE THREAD

**Issue by Husnain-Asharf** [transistorsoft/flutter_background_geolocation#560]
How can I achieve following :

- When in moving state I want location updates based on distance filter
- When in stationary state I want location updates every 30s.

Currently I can get either interval base location updates or either distance filter wise updates.

**Comment by christocracy** [comment]
>When in moving state I want location updates based on distance filter

There's nothing to do here but set `Config.distanceFilter` as desired.

>When in stationary state I want location updates every 30s.

The plugin is not responsible for updating location when the device is stationary.  This plugin tracks only when the device is moving.  A location update every 30s while stationary would be an incredible drain on the user's battery.  Developing apps that waste battery like that is precisely why device manufacturers have become so strict with location-services and the reason that Android manufactures in particular have become draconian with background-services, requiring the existence of http://dontkillmyapp.com.

For periodic location updates while the device is stationary, use [flutter_background_fetch](https://github.com/transistorsoft/flutter_background_fetch), already included as a dependency.

**Comment by Husnain-Asharf** [comment]
But flutter_background_fetch can run after minutes

**Comment by christocracy** [comment]
You don't own the users's device.  On mobile "*You can't always get what you want*".  The OS is guarding the user's battery against poorly behaved apps.

**Comment by christocracy** [comment]
This plugin *knows* when the device is moving vs stationary. 
- When the device is moving, the plugin will automatically start recording location.
- When the device is stationary, you can be sure it's still sitting at the last location the plugin reported.

**Comment by Husnain-Asharf** [comment]
Hi @christocracy 

I am facing one issue some time locations recording are very less as you can see in attached picture. What can be issue. I am using distance meter 10. I highlighted the recordings with red marker.

![Screenshot 2021-05-08 200247](https://user-images.githubusercontent.com/40805304/117547520-a5211d00-b038-11eb-81da-797be3289abb.png)

**Comment by christocracy** [comment]
The plugin takes some distance beyond the "stationary" position before tracking initiates.  Typically 200 meters.  Can take longer depending on environment / device.

In the screenshot below:
- Big red circles = location where plugin entered "stationary" state.
- Green polylines = where the plugin detected device is moving and initiates tracking.  This is the distance between your "1" and "2" in your screenshot above.

![](https://dl.dropbox.com/s/9p5hy6wc8mmfy3x/Screen%20Shot%202021-05-08%20at%201.40.06%20PM.png?dl=1)

**Comment by Husnain-Asharf** [comment]
ok thanks so it is normal behavior also low battery can also be issue.
