### ISSUE TITLE
Can't get lat/long when in background (iOS)

### ISSUE THREAD

**Issue by raphaaugustosilva** [transistorsoft/flutter_background_geolocation#561]
## Your Environment
* Plugin version: 2.0.0
* Platform: iOS
* OS version: 14.4.2
* Device manufacturer / model: Apple
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.3 20E232 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[✓] VS Code (version 1.56.0)
[✓] Connected device (1 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  @override
  Future<void> configure({EGeolocationAccuracy geolocalizationAccuracy = EGeolocationAccuracy.bestForNavigation, Function onLocation, Function onGeofence, String currentUserIdentify}) async {
    
    // 1.  Listen to events
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      try {
        TrackCoordinateEntity _currentCordinate = TrackCoordinateEntity(
          dateTime: DateTime.tryParse(location.timestamp),
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
          speedKmh: location.coords.speed?.convertMpsToKmh(),
          altitudeMeter: location.coords.altitude,
          bearing: location.coords.heading,
        );
        navigationAdventureViewmodel?.setCurrentCoordinate(_currentCordinate);
      } catch (e, s) {
        AppAnalytics.instance.logError(e, s, errorMessage: "Error at NavigationAdventurePresenter ->configureBackgroundGeolocation.execute->onLocation");
      }
    });
        
    bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent geofenceEvent)  async {
      try {
            //Shows snackbar
            GeofenceSnackbar(
              message: geofence.extras["title"],
              subtitle: geofence.extras["subtitle"],
              icon: Image.asset(geofence.extras["iconAssetPath"], width: 18, height: 18, color: AppThemeColors.white),
            ).show();

            //Plays geofencing sound
            playGeofenceSound.execute();

            waypointControl?.achieveWaypoint(persistAtLocalDatabase: true, latitude: geofence.extras["latitude"], longitude: geofence.extras["longitude"]);
          } catch (e, s) {
            AppAnalytics.instance.logError(e, s, errorMessage: "Error at NavigationAdventurePresenter ->configureBackgroundGeolocation.execute->onGeofence");
          }
    });

    bg.TransistorAuthorizationToken transistorAuthorizationToken = (AppConfig.geolocalization.trackSiteTransistorsoftEnabled && currentUserIdentify?.isNotEmpty == true) ? await bg.TransistorAuthorizationToken.findOrCreate('xxxxxx', currentUserIdentify) : null;

    await bg.BackgroundGeolocation.destroyLocations();
    await bg.BackgroundGeolocation.removeGeofences();

    // 2.  Configure the plugin
    await bg.BackgroundGeolocation.ready(
      bg.Config(
        transistorAuthorizationToken: transistorAuthorizationToken, 
        desiredAccuracy: geolocalizationAccuracy.toBgDesiredAccuracy(),
        desiredOdometerAccuracy: 10, 
        distanceFilter: 10,
        activityRecognitionInterval: 1500,
        stopTimeout: 5,
        stopOnTerminate: true,
        startOnBoot: false,
        stopOnStationary: false,
        debug: (kReleaseMode) ? false : true,
        logLevel: AppConfig.geolocalization.logEnabled == true ? bg.Config.LOG_LEVEL_VERBOSE : bg.Config.LOG_LEVEL_OFF,
        notification: bg.Notification(text: "Status: em movimento", largeIcon: "mipmap/icone_app_android_push", smallIcon: "mipmap/icone_app_android_push"),
        stationaryRadius: 25,
        locationAuthorizationRequest: "Any",
        backgroundPermissionRationale: bg.PermissionRationale(
          title: "Permitir {applicationName} acessar a localização deste device.",
          message: "Este aplicativo captura os dados de sua localização para ajudar na navegação de suas aventuras.",
          positiveAction: 'Mudar para "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancelar',
        ),
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Serviço de localização não habilitado',
          'titleWhenOff': 'Serviço de localização desligado',
          'instructions': 'Este aplicativo precisa usar sua localização para ter a experiência de navegação com GPS',
          'cancelButton': 'Cancelar',
          'settingsButton': 'Preferências',
        },
      ),
    );
  }


  @override
  Future start() async {
    await bg.BackgroundGeolocation.start();
    await bg.BackgroundGeolocation.changePace(true);
  }

  @override
  Future stop() async {
    try {
      if ((await bg.BackgroundGeolocation.state).isMoving) await bg.BackgroundGeolocation.changePace(false);
    } catch (e) {}
    await bg.BackgroundGeolocation.stop();
  }
```

## Expected Behavior

Even in background mode, we want to receive the user's location.

## Actual Behavior

When the app is in background, fetch background logs are received, but the user`s location is not received.

## Steps to Reproduce

1. Call ready();
2. Call start();
3. after await start, user puts the app in background mode;

## Context

One of our app's feature uses flutter_background_geolocation in order to capture user`s locomotion (latitude/longitude) and draws it in realtime on map (Mapbox)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Email-log:

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/6443607/background-geolocation.log)

```

</details>

**Comment by christocracy** [comment]
Now go outside for a walk (eg 1km) with debug: true.

**Comment by raphaaugustosilva** [comment]
My fault, doing it right now.
We realized that when the app is in the background and enter at stationary status, the lat/long is not being received, but I`ll do it with debug: true and upload the log

**Comment by christocracy** [comment]
Read the wiki "Philosophy of Operation"

**Comment by raphaaugustosilva** [comment]
The flag "stopOnStationary" is with value = false.
Even at stationary, the location receives are stopped?

**Comment by raphaaugustosilva** [comment]
I tested it by driving the car for 1 km now, and after ready() and await start(), I`ve put the app in background mode and start driving. After 1 km, (about 3 minutes driving) I`ve resumed the app (foreground) again.

The log is attached here.
Are we doing something wrong?
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/6443777/background-geolocation.log)

**Comment by christocracy** [comment]
stopOnStationary doesn't do what you think it does.  You are probably not at all interested in that.

The plugin tracks **ONLY** when the device is detected to be moving.  When the device is detected to be stationary, the plugin turns off location-services to conserve battery.

**Comment by raphaaugustosilva** [comment]
Chris, but I think that the problem is that with the scenario above, the plugin is not detecting that the user is moving (but the user is moving). 

stopTimeout property is with the value 5 minutes, but when I await the "start" code and almost immediately put the app in background (this process take less than 10 seconds), the plugin is not sending location updates.

I drove by 1 km, 3 minutes, and only start receiving again when I resumed the app.

**Comment by raphaaugustosilva** [comment]
Why using the config above this is happening? (and just for iOS, Android is not with this behavior)

Are we doing something wrong?

**Comment by christocracy** [comment]
I suggest you install the Demo app, linked in the readme, and compare its performance to your own app.  Do not look at the code.  Just clone the demo repo and install on your device.

**Comment by raphaaugustosilva** [comment]
Ok, I'll do it today.
