### ISSUE TITLE
iOS background launched app  does not get/process geofence event

### ISSUE THREAD

**Issue by pratikrana** [transistorsoft/flutter_background_geolocation#562]
## Your Environment
* Plugin version: 2.0.3
* Platform: iOS
* OS version: 14.4.2
* Device manufacturer / model: iphone 11
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
return BackgroundGeolocationFirebase.configure(
            BackgroundGeolocationFirebaseConfig( 
                locationsCollection: "locations",
                geofencesCollection: "geofences",
                updateSingleDocument: false))
        .then((value) {
      return bg.BackgroundGeolocation.ready(config).then((state) {
        bg.BackgroundGeolocation.onGeofence((event) {
          if (event.action == 'DWELL') onLocationEnter(event);
          if (event.action == 'EXIT') onLocationExit(event);
        });
        return bg.BackgroundGeolocation.startGeofences().then((state) {
          if (!state.enabled || state.trackingMode != GeoFencesTracking)
            return false;
          return true;
        });
      });
    });


onLocationEnter(...) {
   If Operation succeeds {
     // Switch to location updates
     bg.BackgroundGeolocation.start();
  }
}

onLocationExit(...) {
   If Operation succeeds {
     // Switch back to geofencess
     bg.BackgroundGeolocation.startGeofences();
  }
}
```

## Expected Behavior
When iOS app is pushed to background (or terminated and launched in background on geofence enter/exit), onLocationEnter/onLocationExit should get called. This should happen always as long as geofence is registered with the plugin

## Actual Behavior
Sometimes (1 out of 5 times) I see that the app wakes up in background but plugin callbacks are not called. The scenario triggering this behavior could be long duration within the geofence (for e.g. overnight stay within geofence), but this is not 100% verified.

Evidence that app is launched in background: 
1. Heartbeat is configured to be sent every 5 minutes to firestore as long as app  code is executing. As soon as the device enters the geofence, I see a heartbeat in the firestore recording a new PID (for terminated app) and existing PID (for app which is not terminated). But the geofence event related updates to the firestore database hasn;t happened
2. Also, using flutter_background_geolocation_firebase, its been verified that the "geofences" or "locations" also do not get updated in firestore even though as per the aforementioned heartbeat the app is actually awaken in background.

## Steps to Reproduce
1. Add geofence DWELL and EXIT handlers. These handlers make firestore updates.
2. In DWELL handler, switch location monitoring, and in EXIT handler, switch back to geofence monitoring (using start() and startGeofences() call respectively). This is strictly NOT needed for the app to function but was put in as an experiment to see if that alleviates this "missing geofence event" issue.
3. After DWELL processing happens, be in the geofence for hours. And then exit the Geofence later. On Exit, the geofence EXIT handler is not invoked even if app seems to be in background. This seems to happen in both cases - App is terminiated or App is simply not in foreground. And the same behavior is seen on both EXIT/DWELL processing
4. I don't think this issue happens always though as noted above. I am guessing something to do with Apple Machine learning ??

## Context
Verify app functionality where on Dwell and Exit , firestore database should get updated with business data - even if the app is terminated or not in foreground for long hours

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The issue template is not optional.  **Edit** your issue and provide all the requested info.

**Comment by pratikrana** [comment]
I have updated the template. Can you please review?

**Comment by christocracy** [comment]
See wiki "Debugging" and fetch and observe logs from the plugin.
