### ISSUE TITLE
 How to set a message for permission to receive locations in Android?

### ISSUE THREAD

**Issue by AlexKenbo** [transistorsoft/flutter_background_geolocation#563]
![photo_2021-05-15_12-39-52](https://user-images.githubusercontent.com/14903011/118355956-93c99a80-b57b-11eb-9d0c-12b3f3e6568a.png)

**Comment by christocracy** [comment]
See api docs Config.backgroundPermissionRationale

**Comment by AlexKenbo** [comment]
Thank you!

https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/backgroundPermissionRationale.html
