### ISSUE TITLE
calling getCurrentPosition requires "Always" permission in location services

### ISSUE THREAD

**Issue by benwilder** [transistorsoft/flutter_background_geolocation#57]
## Your Environment
* Plugin version: 1.0.1
* Platform: iOS 
* OS version: 12.2
* Device manufacturer / model: phone 8 plus
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)
No issues found!

* Plugin config
desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
distanceFilter: 10.0,
stopOnTerminate: false,
startOnBoot: true,
debug: true,
logLevel: bg.Config.LOG_LEVEL_VERBOSE,
reset: true

## Expected Behavior

Im building an app that needs to send GPS data to my cloud APIs every 5 seconds, and very little else (apart for a few bits of meta data etc), and to be toggled on and off by the user.  This should be able to run when backgrounded (in your pocket etc).

When testing your module, i'm configuring the plugin (as above) and then calling "bg.BackgroundGeolocation.getCurrentPosition".  I have set the "While using the app" permission and would expect to be able to trigger a retrieval of GPS data on a button click.

## Actual Behavior

I'm prompted that i need to enable the "Always" allow location access for this app. Once this has been enabled it works but i am wondering why i need to add this additional permission. The reason i ask is that apps like "Run keeper" that log GPS for running etc only need the "While using the app" permission and not the "Always" permission - but still manage to log and track GPS data in the background. My issue is likely to highlight my miss understanding of the app ecosystem / architecture - but any pointers are greatly received. 

## Context
Im building an app that needs to send GPS data to my cloud APIs every 5 seconds, and very little else (apart for a few bits of meta data etc), and to be toggled on and off by the user.  This should be able to run when backgrounded (in your pocket etc).

## Debug logs
NA

**Comment by christocracy** [comment]
Read the [Philosophy of Operation](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation)

This sdk *knows* when the device is *moving* vs *stationary*, automatically toggling location-services on to engage tracking accordingly, **without user intervention**.  On iOS, this is possible **only** with `Always` authorization.

If your app engages tracking only when the user clicks a UI button while your app is in the foreground (like *Run Keeper*), eg: `[Start Workout]`, then use `WhenInUse` authorization (see `Config.locationAuthorizationRequest`).

This SDK was initially designed for tracking first-responders in disaster-zones, where life depended on it.  It had to track devices *without user intervention*, no matter what (eg: OS terminates app, user terminates app, device rebooted).
