### ISSUE TITLE
Flutter how to properly use background service

### ISSUE THREAD

**Issue by ATHUL3120** [transistorsoft/flutter_background_geolocation#571]
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: Class 'MissingPluginException' has no instance getter 'details'.
E/flutter ( 4653): Receiver: Instance of 'MissingPluginException'
E/flutter ( 4653): Tried calling: details
E/flutter ( 4653): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 4653): #1 BackgroundFetch.start. (package:background_fetch/background_fetch.dart:460:13)
E/flutter ( 4653): #2 _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 4653): #3 _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 4653): #4 _FutureListener.handleError (dart:async/future_impl.dart:172:20)
E/flutter ( 4653): #5 Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
E/flutter ( 4653): #6 Future._propagateToListeners (dart:async/future_impl.dart:740:24)
E/flutter ( 4653): #7 Future._completeError (dart:async/future_impl.dart:550:5)
E/flutter ( 4653): #8 _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
E/flutter ( 4653): #9 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 4653):

**Comment by christocracy** [comment]
*WARNING:  DO NOT IGNORE THIS TEMPLATE*


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
