### ISSUE TITLE
Odometer value resets to 0 automatically

### ISSUE THREAD

**Issue by codemycompany** [transistorsoft/flutter_background_geolocation#573]
Are there any conditions that cause the odometer value to reset to zero automatically?

**Comment by christocracy** [comment]
Only by calling `setOdometer`, `resetOdometer`.

**Comment by codemycompany** [comment]
Any chance that the plugin calls resetOdometer in certain circumstances?

**Comment by christocracy** [comment]
>Any chance that the plugin calls resetOdometer in certain circumstances?

There is no chance the plugin calls `resetOdometer` upon itself.

**Comment by codemycompany** [comment]
Thanks for clarifying
