### ISSUE TITLE
  Plugin doesn't run on real device (Android and iOS) in debug build nor in iOS simulator

### ISSUE THREAD

**Issue by ManuPulido27** [transistorsoft/flutter_background_geolocation#577]
## Your Environment
* Plugin version:  4.0.2
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
void main() async {
  runApp(MyApp());
  flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  var initializationSettingsIOS = IOSInitializationSettings();
  var initializationSettingsAnd =
      AndroidInitializationSettings('@mipmap/ic_launcher');
  var initializationSettings = new InitializationSettings(
      android: initializationSettingsAnd, iOS: initializationSettingsIOS);
  await flutterLocalNotificationsPlugin.initialize(initializationSettings);
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String geomes;

  void _addGeofence() {
    bg.BackgroundGeolocation.addGeofence(bg.Geofence(
      identifier: 'Casa',
      radius: 10,
      latitude: 38.544180,
      longitude: -8.849864,
      notifyOnEntry: true,
      notifyOnExit: true,
      notifyOnDwell: false,
      loiteringDelay: 30000, // 30 seconds
    )).then((bool success) {
      print('[addGeofence] success');
    }).catchError((error) {
      print('[addGeofence] FAILURE: $error');
    });
  }

  void _onGeofence(bg.GeofenceEvent event) {
    print('onGeofence llamado esto pasó $event');
    var platformChannelSpecifics = NotificationDetails(
        iOS: IOSNotificationDetails(),
        android: AndroidNotificationDetails(
            'channelId', 'channelName', 'channelDescription'));
    flutterLocalNotificationsPlugin
        .show(0, 'You arrived to the destination!',
            'Don\'t forget to wash your hands!', platformChannelSpecifics)
        .then((result) {})
        .catchError((onError) {
      print('[flutterLocalNotificationsPlugin.show] ERROR: $onError');
    });
  }

  @override
  void initState() {
    super.initState();

    _addGeofence();

    bg.BackgroundGeolocation.onGeofence(_onGeofence);

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
    });

    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });

    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });

    bg.BackgroundGeolocation.ready(bg.Config(
            locationUpdateInterval: 10000,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true, // true
            logLevel: bg.Config.LOG_LEVEL_VERBOSE // bg.Config.LOG_LEVEL_VERBOSE
            ))
        .then((bg.State state) {
      if (state.enabled) {
        bg.BackgroundGeolocation.start();
      }

      
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'appggeo',
            ),
            // ignore: deprecated_member_use
            RaisedButton(
              onPressed: null,
              child: Text('Add geofence'),
            )
          ],
        ),
      ),
    );
  }
}

```

## Expected Behavior
Plugin should run and listen/inform on geofence events

## Actual Behavior
Plugin doesn't do anything when run on real devices on debug mode

## Steps to Reproduce

1.
2.
3.
4.

## Context
Trying to get plugin to trigger notifications when user enters a geofence while in background

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
An Observatory debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:50791/uvtGIP_x_JE=/
flutter: [addGeofence] success                                          
flutter: [providerchange] - [ProviderChangeEvent enabled:false, status: 0, network: true, gps: true, accuracyAuthorization: 0]
Activating Dart DevTools...                                         6.5s
The Flutter DevTools debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A50791%2FuvtGIP_x_JE%3D%2F

Performing hot restart...                                               
Restarted application in 316ms.
flutter: [addGeofence] success
```
This is the log when running on iOS simulator
</details>

**Comment by christocracy** [comment]
>Plugin doesn't run on real device (Android and iOS) in debug build nor in iOS simulator

Your logs show that your app is receiving events from the plugin.  It most certainly *is* running.

```
flutter: [addGeofence] success                                          
flutter: [providerchange] - [ProviderChangeEvent enabled:false, status: 0, network: true, gps: true, accuracyAuthorization: 0]
flutter: [addGeofence] success
```

I suggest you boot your app in *XCode* and observe the native logs.

**Comment by christocracy** [comment]
>radius: 10.

Unrelated , but the minimum geofence radius the iOS & Android will respond to is ~200 meters.

You can set your `radius: 10`, it won't matter, but the native APIs are going to respond as if it's actually `200`.

**Comment by ManuPulido27** [comment]
Hi again Chris, we cannot make the plugin run on real device in debug mode ( not in Android nor iOS) and not in iOS simulator. We need this for a project ASAP, we followed your instructions step by step but still with no results.

If you show us how to solve this and we confirm it is reliable we'll buy your license straight away because we need to add it to a production ready app.


Here i send you the native Xcode logs as requested, the problem seems to be in the ''enabled status''


> 2021-06-11 18:11:49.019806+0100 Runner[9812:127716] [TSBackgroundFetch load]: (
)
2021-06-11 18:11:49.020155+0100 Runner[9812:127716] [TSBGAppRefreshSubscriber load]: {
}
2021-06-11 18:11:49.189495+0100 Runner[9812:127716] Metal API Validation Enabled
2021-06-11 18:11:49.281627+0100 Runner[9812:128088] ℹ️-[TSDBLogger db_delete] maxAge: 259200
2021-06-11 18:11:49.282101+0100 Runner[9812:128088] ℹ️-[TSLocationManager init] 
╔═════════════════════════════════════════════
║ TSLocationManager (build 377)
╠══════════════════════════════════════════════
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didDeviceReboot = 0;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 0;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = 0;
    params =     {
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = "";
    useSignificantChangesOnly = 0;
}
2021-06-11 18:11:49.294210+0100 Runner[9812:128091] ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay DOUBLE NOT NULL DEFAULT 0, extras TEXT)
2021-06-11 18:11:49.294348+0100 Runner[9812:128091] ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);
2021-06-11 18:11:49.330339+0100 Runner[9812:128094] 🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 0
2021-06-11 18:11:49.333128+0100 Runner[9812:128094] 🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 0
2021-06-11 18:11:49.334557+0100 Runner[9812:128094] 🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 0
2021-06-11 18:11:49.335460+0100 Runner[9812:128094] 🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 0
2021-06-11 18:11:49.351593+0100 Runner[9812:128117] flutter: Observatory listening on http://127.0.0.1:53575/O0BQqVDAHIw=/
2021-06-11 18:11:49.877727+0100 Runner[9812:128089] 🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 0
2021-06-11 18:11:50.152990+0100 Runner[9812:128089] ℹ️-[GeofenceDAO doInsert:geofence:] Casa
2021-06-11 18:11:50.154866+0100 Runner[9812:128089] ℹ️-[TSGeofenceManager onGeofence:]
2021-06-11 18:11:50.155005+0100 Runner[9812:128089] ℹ️-[TSLocationManager on:success:failure:] location
2021-06-11 18:11:50.155132+0100 Runner[9812:128089] ℹ️-[TSLocationManager on:success:failure:] motionchange
2021-06-11 18:11:50.155233+0100 Runner[9812:128089] ℹ️-[TSLocationManager on:success:failure:] providerchange
2021-06-11 18:11:50.167675+0100 Runner[9812:128086] ℹ️-[TSConfig persist]
2021-06-11 18:11:50.169728+0100 Runner[9812:128086] ℹ️-[TSConfig persist]
2021-06-11 18:11:50.171410+0100 Runner[9812:128086] 🔵-[TSLocationManager ready]
2021-06-11 18:11:50.373787+0100 Runner[9812:128104] flutter: [addGeofence] success
2021-06-11 18:11:50.379212+0100 Runner[9812:128104] flutter: [providerchange] - [ProviderChangeEvent enabled:false, status: 0, network: true, gps: true, accuracyAuthorization: 0]

>

**Comment by christocracy** [comment]
> the problem seems to be in the 'enabled status'

Look *very closely* at your code.  The problem is clear as day to me.

```dart

if (state.enabled) {
  bg.BackgroundGeolocation.start();
}

**Comment by ManuPulido27** [comment]
Thank you so much Chris it works now, i'm really embarrassed , been working on this on extra hours after a long time and I was burnt out so i didn't even check.
I'll talk to my boss to buy your license.
Have a great weekend!
