### ISSUE TITLE
After changing [locationTemplate]. The old template continues to come to the server.

### ISSUE THREAD

**Issue by AlexKenbo** [transistorsoft/flutter_background_geolocation#578]
After changing [locationTemplate]. The old template continues to come to the server.

Only after removing the application and installing it again, the data goes to the new locationTemplate.

**Comment by christocracy** [comment]
You have to understand that the plugin renders the json just once when a location is first recorded and inserted into its SQLite db.  

Existing records in db don't get the-rendered when you change your template,

See api docs destroyLocations to clear the SQLite db.
