### ISSUE TITLE
License is invalid

### ISSUE THREAD

**Issue by tkkhy** [transistorsoft/flutter_background_geolocation#58]
I got error with license. i do in version 1.0.1 and i follow the step already. and when i do run my app it show me my license is invalid

**Comment by christocracy** [comment]
Paste your AndroidManifest.xml

**Comment by tkkhy** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.bongtk.bloc_operation" xmlns:tools="
http://schemas.android.com/tools">

    
    <uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission
android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission
android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission
android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application tools:replace="android:label"
        android:name=".Application"
        android:label="BLOC Operation"
android:usesCleartextTraffic="true"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"

android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data

android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
</activity>
        <meta-data
android:name="com.transistorsoft.locationmanager.license"
android:value="c65358ea8a0d290f6e3db8bbaedbdf6e35ad7979c22e807fd9b8a4fe938cd8b4"
/>
    </application>
</manifest>

**Comment by christocracy** [comment]
Show me `logcat` of your app booting.  I want to see this block, including the "License Validation Failure"

```
05-07 07:26:30.574  9743  9743 I TSLocationManager: [c.t.l.adapter.TSConfig print]
05-07 07:26:30.574  9743  9743 I TSLocationManager: ╔═════════════════════════════════════════════
05-07 07:26:30.574  9743  9743 I TSLocationManager: ║ TSLocationManager version: 3.0.14 (314)
05-07 07:26:30.574  9743  9743 I TSLocationManager: ╠═════════════════════════════════════════════
05-07 07:26:30.574  9743  9743 I TSLocationManager: {
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "activityRecognitionInterval": 10000,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "allowIdenticalLocations": false,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "autoSync": true,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "autoSyncThreshold": 0,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "batchSync": false,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "debug": true,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "deferTime": 0,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "desiredAccuracy": -2,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "desiredOdometerAccuracy": 100,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "disableElasticity": false,
.
.
.
```

**Comment by tkkhy** [comment]
I/flutter ( 5482): [location] - [Location {odometer: 0.0, activity:
{confidence: 100, type: still}, provider: {gps: true, enabled: true,
network: true, status: 3}, extras: {}, event: providerchange, battery:
{level: 1.0, is_charging: true}, uuid:
1135bb59-221f-4ce6-8e39-d773e82dc1db, coords: {altitude: -1.0, heading:
-1.0, latitude: 11.5620983, accuracy: 20.0, speed: 5.0, longitude:
104.9129983}, is_moving: false, timestamp: 2019-05-06T21:38:01.000Z}]
I/TSLocationManager( 5482): [c.t.locationmanager.data.a.c persist]
I/TSLocationManager( 5482):   ✅  INSERT:
3769d1db-570b-4293-a947-646d288f2fcf
D/TSLocationManager( 5482): [c.t.l.g.TSGeofenceManager
startMonitoringStationaryRegion]
D/TSLocationManager( 5482):   🎾  Start monitoring stationary region
(radius: 150.0 meters)
I/flutter ( 5482): [location] - [Location {odometer: 0.0, activity:
{confidence: 100, type: still}, extras: {}, event: motionchange, battery:
{level: 1.0, is_charging: true}, uuid:
3769d1db-570b-4293-a947-646d288f2fcf, coords: {altitude: -1.0, heading:
-1.0, latitude: 11.5620983, accuracy: 20.0, speed: 5.0, longitude:
104.9129983}, is_moving: false, timestamp: 2019-05-06T21:38:01.000Z}]
I/flutter ( 5482): [motionchange] - [Location {odometer: 0.0, activity:
{confidence: 100, type: still}, extras: {}, event: motionchange, battery:
{level: 1.0, is_charging: true}, uuid:
3769d1db-570b-4293-a947-646d288f2fcf, coords: {altitude: -1.0, heading:
-1.0, latitude: 11.5620983, accuracy: 20.0, speed: 5.0, longitude:
104.9129983}, is_moving: false, timestamp: 2019-05-06T21:38:01.000Z}]
I/TSLocationManager( 5482): [c.t.l.s.ActivityRecognitionService a]
I/TSLocationManager( 5482):   🎾  Start motion-activity updates
D/TSLocationManager( 5482): [c.t.l.s.BackgroundTaskService onDestroy]
D/TSLocationManager( 5482): [c.t.l.service.TrackingService onDestroy]
D/TSLocationManager( 5482):   🔴  TrackingService destroyed
D/TSLocationManager( 5482): [c.t.l.s.ActivityRecognitionService a]
D/TSLocationManager( 5482):   🚘 ️DetectedActivity [type=STILL,
confidence=100]
D/TSLocationManager( 5482): [c.t.l.s.ActivityRecognitionService onDestroy]
D/TSLocationManager( 5482):   🔴  ActivityRecognitionService destroyed
D/EGL_emulation( 5482): eglMakeCurrent: 0x9f685900: ver 3 0 (tinfo
0x9f6835b0)
D/TSLocationManager( 5482): [c.t.l.a.BackgroundGeolocation c]
D/TSLocationManager( 5482):   🔴  Cleared callbacks

**Comment by christocracy** [comment]
`#stop` the plugin and reboot your app.  Don't show me anything until you find this log:
```
05-07 07:26:30.574  9743  9743 I TSLocationManager: [c.t.l.adapter.TSConfig print]
05-07 07:26:30.574  9743  9743 I TSLocationManager: ╔═════════════════════════════════════════════
05-07 07:26:30.574  9743  9743 I TSLocationManager: ║ TSLocationManager version: 3.0.14 (314)
05-07 07:26:30.574  9743  9743 I TSLocationManager: ╠═════════════════════════════════════════════
05-07 07:26:30.574  9743  9743 I TSLocationManager: {
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "activityRecognitionInterval": 10000,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "allowIdenticalLocations": false,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "autoSync": true,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "autoSyncThreshold": 0,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "batchSync": false,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "debug": true,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "deferTime": 0,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "desiredAccuracy": -2,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "desiredOdometerAccuracy": 100,
05-07 07:26:30.574  9743  9743 I TSLocationManager:   "disableElasticity": false,
```

**Comment by tkkhy** [comment]
hi i just reboot. and do flutter clean and then flutter run.
now it working
