### ISSUE TITLE
Android App "TERMINATE" event doesnt report the accurate results.Sometime plugin shows the app terminated while using the app, Sometime event ignore even when we killed the app. 

### ISSUE THREAD

**Issue by AllenSmith11** [transistorsoft/flutter_background_geolocation#582]
## Your Environment:-1.22.4
* Plugin version:1.11.1
* Platform:  Android
* OS version: Android 10,11
* Device manufacturer / model:Samsung s7,Redmi note 9 pro max,Redmi k20pro
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I don't know where you're seeing this event.

Provide plugin logs and always provide your plugin Config, as requested by issue template.
