### ISSUE TITLE
difference between onLocationChange and onMotionChange

### ISSUE THREAD

**Issue by Faloopit** [transistorsoft/flutter_background_geolocation#583]
hi, What difference is really between the two method onLocationChange and onMotionChange? 

## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: Samsung galaxy
* Flutter info (`flutter doctor`):2.13.1
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

```
  bg.BackgroundGeolocation.onMotionChange(_generateGpsData);
  bg.BackgroundGeolocation.onLocationChange(_generateGpsData);
```

```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
They are no similar at all.

OnMotionChange fires when the plugin changes state from stationary->moving and moving->stationary.

It tells when the device started moving and when it became stationary.

**Comment by christocracy** [comment]
Read the wiki *Philosophy of Operation*.
