### ISSUE TITLE
[Help] Retrieve data from Notifications when app is opened from push notification .

### ISSUE THREAD

**Issue by pr-1** [transistorsoft/flutter_background_geolocation#584]
## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android
* OS version: iOS 14 , Android 11
* Device manufacturer / model: iPhone12  , Samsung M30
* Flutter info (`flutter doctor`): No Issues Found
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_INFO,
        enableHeadless: true,
      ),
    ).then((bg.State state) {
      print('configuring plugin complete');
      if (!state.enabled) {
        bg.BackgroundGeolocation.startGeofences();
      }
    }).catchError((onError) {
      print('configuring plugin error');
    });
```

## Expected Behavior
There should be a way to retrieve the data passed in extras, identifier.

## Actual Behavior
Currently there is a onGeofence callback which gets fired as soon as the notification is recieved. 
Want something similar to track if the notification is clicked and hence app is opened from this notification.

**Comment by christocracy** [comment]
The plugin doesn't create clickable notifications.

**Comment by pr-1** [comment]
Thanks for the answer @christocracy  Are there any future plans on making it clickable ? 

And is there any way we can setup custom title for the iOS notifications ? just like we have custom layout for Android ?? 

Currently once I reach a Geofence. A notification pops up saying "**Enter Geofence: ${identifier}**" Is there any way we can change it to **"You have reached this place"** 

![Screenshot 2021-06-29 at 4 56 38 PM](https://user-images.githubusercontent.com/26018750/123789699-14a9df00-d8fb-11eb-9a70-8135538a5fe0.png)

**Comment by timgrossmann** [comment]
Hi @christocracy, I'm associated with @pr-1 :)
Maybe I can give you some context on the exact use case.

Basically we want to geo-fence a location (e.g. a restaurant) with a radius of e.g. 100m. Once the user enters this geofence, we want to provide a notification to the user that says "You have reached the Restaurant XYZ, check out the Video". 
Opening the Notification directs the User to the specific screen in the app that holds the information for that specific restaurant.

Hope that makes sense. We are currently evaluating purchasing your framework for our app.
Is this possible with it?

Thanks

**Comment by christocracy** [comment]
Those are merely **debugging** notifications to assist you during development.  See api docs Config.debug.

You are responsible for posting your own local-notifications using a third party lib that specializes in notifications.
