### ISSUE TITLE
Real time location tracking is not working on continuous basis when Geo-fences are added and starts the geo-fence monitoring.

### ISSUE THREAD

**Issue by parthmangi-ss** [transistorsoft/flutter_background_geolocation#587]
## Your Environment
* Plugin version: 2.1.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung / MI / LG / Motorola
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
return BG.Config(
      disableAutoSyncOnCellular: false,
      fastestLocationUpdateInterval: 200,
      allowIdenticalLocations: false,
      stopOnStationary: false,
      stopTimeout: 1,
      stationaryRadius: 5,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      useSignificantChangesOnly: false,
      locationTimeout: 5,
      desiredOdometerAccuracy: 10,
      activityRecognitionInterval: 0,
      desiredAccuracy: BG.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 4.0,
      disableElasticity: true,
      // Activity recognition options
      enableHeadless: false,
      stopOnTerminate: true,
      startOnBoot: true,
      debug: true,
      logLevel: BG.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      showsBackgroundLocationIndicator: true,
      backgroundPermissionRationale: BG.PermissionRationale(
        title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      ),
      // HTTP & Persistence
      url: ApiConstants.acUpdateLiveRawLocations(tripInstanceId: tripInstanceId),
      method: 'POST',
      headers: {"content-type": "application/json;charset=utf-8", "Authorization": "Bearer $token", "locale": "en"},
      autoSync: true,
      autoSyncThreshold: 0,
      batchSync: true,
      maxBatchSize: 1,
      locationsOrderDirection: "DESC",
      httpTimeout: 3000,
      maxDaysToPersist: 1,
    );
```

## Expected Behavior

Real time location tracking should work and recorded location should get fired in HTTP event also same time if application user reaches in any per-defined Geo-fence area then Geo-fence listeners and on Location listener should work and behave properly as independent services.

## Actual Behavior
If packages Geo-fences are added and real time monitoring is going on then real time location tracking and HTTP event works unpredictably so sometimes proper locations are getting record and getting upload to server and for some time location recording just stops and no location update event occurs on _on-location method of plugin.

## Context
I have configured the plugin to give me location update on on-location method also I have added Geo-fences using addGeofences method of plugin. Now on the start of Map screen I am starting plugin using start() method and starting goefences using startGeofences() method. Now if startGeofences() is called then plugin don't give real time location tracking a priority and I am not receiving location updated in the callback of on-Location listener.

I want plugin's real time location tracking and geo-fence monitoring to work as parallel so on my map screen I can do separate UI tasks based on Geofence listener methods and based on on-Location listener methods.

**Comment by christocracy** [comment]
You are showing only the Config, not any method-calls.

Are you observing logs from the plugin?  See wiki *Debugging*.

**Comment by parthmangi-ss** [comment]
Let me add method calls and logs here for you.
