### ISSUE TITLE
license not valid

### ISSUE THREAD

**Issue by flutteresbolivia** [transistorsoft/flutter_background_geolocation#589]
I bought a license a couple of hours ago
I have followed all the steps to configure in android and when I debug my application, it appears that my license is not valid, any more steps I am forgetting?

I need help

https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md

**Comment by christocracy** [comment]
Email me your Order # and AndroidManifest.xml

**Comment by flutteresbolivia** [comment]
este es el correo verdad? 
info@transistorsoft.com

**Comment by flutteresbolivia** [comment]
@christocracy  Where do I find the email to send this problem?

**Comment by christocracy** [comment]
See transistor software home page for Contact information.

**Comment by flutteresbolivia** [comment]
> See transistor software home page for Contact information.

Thank you so much!!!
I already sent him an email to info@transistorsoft.com
