### ISSUE TITLE
Distance Calculation not Accurate when stationary state change to moving state distance automatically Jumps

### ISSUE THREAD

**Issue by Ravish1** [transistorsoft/flutter_background_geolocation#591]
## Your Environment
* Plugin version:4.0.0
* Platform: Android
* OS version:Android 10
* Device manufacturer / Redmi Note 9 pro max:
* Flutter info (`flutter doctor`):Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.BackgroundGeolocation.ready(bg.Config(
        reset: false,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        persistMode: bg.Config.PERSIST_MODE_NONE,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
            title: "Allow access to this device’s location in the background?",
            message:
            "SpeedSlip requires permission to access your device's location in the background. This will allow background tracking if the SpeedSlip App is closed while you're tracking an activity.Please select 'Change to allow all the time’ to ensure this feature is enabled. ",
            positiveAction: "Change to Allow all the time",
            negativeAction: "Cancel"),
        preventSuspend: true,
        distanceFilter: 5,
        fastestLocationUpdateInterval: 1,
        isMoving: true,
        notification: bg.Notification(
            priority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
            sticky: true,
            layout: "my_notification_layout",
            // <-- custom layout xml file
            title: "The Notification Title",
            text: "The Notification Text",
            smallIcon: "mipmap/logo",
            // <-- defaults to app icon
            largeIcon: "mipmap/logo",
            strings: {
              'notificationTitle': 'SpeedSlip',
            }))).then((bg.State state) async {
      print('[ready] ${state.toMap()}');

      setState(() {});
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
```

## Expected Behavior
Whenever i start tracking distance needs to be in sequence .During the tracking if device detect the moving state stationary and again detect the moving so distance needs to be in sequence not with huge jump.
**This is how i am pulling distance and converting to mile**
   mile = ((location.odometer / 1000.0) / 1.609);
      mile = dp(mile, 2);

## Actual Behavior

Everytime distance jumps like 0.01 then 0.20 etc.During my last trip i have taken a break after 80 mile and left the app running in dle postion after 1 hour when i have start drive again distance jumps from 80 to 177.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```D/TSLocationManager(11572): [c.t.l.service.AbstractService a] 
D/TSLocationManager(11572):   🎾  TrackingService [eventCount: 1]
I/TSLocationManager(11572): [c.t.l.service.TrackingService h] 
I/TSLocationManager(11572): ╔═════════════════════════════════════════════
I/TSLocationManager(11572): ║ TrackingService motionchange: true
I/TSLocationManager(11572): ╠═════════════════════════════════════════════
D/TSLocationManager(11572): [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
D/TSLocationManager(11572): [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
I/TSLocationManager(11572): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(11572):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/TSLocationManager(11572): [c.t.l.a.TSLocationManagerActivity onDestroy] 
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
I/TSLocationManager(11572): [c.t.l.s.TSScheduleManager cancelOneShot] 
I/TSLocationManager(11572):   ⏰ Cancel OneShot: TERMINATE_EVENT
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/TSLocationManager(11572): [c.t.l.service.AbstractService a] 
D/TSLocationManager(11572):   🎾  LocationRequestService [eventCount: 0]
I/TSLocationManager(11572): [c.t.l.s.LocationRequestService a] 
I/TSLocationManager(11572):   ℹ️  Location availability: true
D/TSLocationManager(11572): [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/AudioManager(11572): getStreamVolume isRestricted mode = 0
D/TSLocationManager(11572): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(11572):   🔴  LocationRequestService destroyed


</details>

**Comment by christocracy** [comment]
You need to provide detailed logs.  See wiki *Debugging*.

Once you have detailed logs, you need to provide the exact timestamps from those logs that you're concerned with.

**Comment by Ravish1** [comment]
Hey first of all thanks for the reply.I will paste my trip location logs here.Can i attach a video as well?

**Comment by christocracy** [comment]
Video is uninteresting and not required.

**Comment by Ravish1** [comment]
Not able to post my entire trip log here

**Comment by Ravish1** [comment]
[the_gap.log](https://github.com/transistorsoft/flutter_background_geolocation/files/6809057/the_gap.log)

**Comment by Ravish1** [comment]
i have attached the files above where you can see the timestamp and other all detail

**Comment by christocracy** [comment]
Timestamps from logs where the "jump" occurred.

**Comment by Ravish1** [comment]
![Screenshot 2021-07-13 at 6 42 32 PM](https://user-images.githubusercontent.com/20064209/125457749-029f992e-99e0-4a77-aade-28bc62f56274.png)

**Comment by Ravish1** [comment]
the above screen array number 642 has distance :2.11 but after the next location update distance jumped to 2.92

**Comment by christocracy** [comment]
Post the text of timestamps so they can by copied.

**Comment by Ravish1** [comment]
[642] => Array
                (
                    [avg_speed] => 11.3
                    [top_speed] => 27.74
                    [latitude] => 21.2691307
                    [longitude] => -157.8161083
                    [tripid] => 2021-07-12 – 21:11:21
                    [speed_gps] => -2.237414543194531
                    [ended] => 03:46:53
                    [distance] => 2.11
                    [elevation] => 42.9
                    [temp] => 
                    [current_time] => 2021-07-13 24:58:14
                    [current_timestamp] => 1626152294711
                )

            [643] => Array
                (
                    [avg_speed] => 11.28
                    [top_speed] => 27.74
                    [latitude] => 21.269774
                    [longitude] => -157.8111649
                    [tripid] => 2021-07-12 – 21:11:21
                    [speed_gps] => 2.2821628340584215
                    [ended] => 03:48:41
                    [distance] => 2.92
                    [elevation] => 41.0
                    [temp] => 
                    [current_time] => 2021-07-13 01:00:02
                    [current_timestamp] => 1626152402392
                )

**Comment by christocracy** [comment]
Your attached log file is *not* from the plugin.  I'm not interested in your own custom logs.  I'm only interested in logs **from the plugin**.  See Wiki *Debugging* and learn to fetch logs from the plugin's internal SQLite database via `emailLog` method.

**Comment by Ravish1** [comment]
[background-geolocation (1).log](https://github.com/transistorsoft/flutter_background_geolocation/files/6821400/background-geolocation.1.log)
Hey i have attached the logs.These logs are generated with your Email logging method.

**Comment by Ravish1** [comment]
As per i can these logs "Odometer" Jumps .These logs i have collected approx. for 1.6 mile and i left app in stationery position   for 1 hour.Please let me know if you need more logs.Thanks.

**Comment by christocracy** [comment]
Let me what what specific timestamps you're interested in from your latest logs.
