### ISSUE TITLE
The odometer is always increasing

### ISSUE THREAD

**Issue by erayhamurlu** [transistorsoft/flutter_background_geolocation#593]
My Environment
* Plugin version: ^2.1.0 
* Platform: iOS or Android
* OS version: 14
* Device manufacturer / model: Iphone6s / Iphone11 / SamsungJ6+

When location changed i send odometer value to database , value always gathering and increasing ,not distance traveled
I explain with example:
when i moved 200 meters i sending database 200 meters,
then
i moved 200 meters i sending database 400 meters,
what i want , when i moved 200m i want to send 200 meters to database

**Comment by christocracy** [comment]
![image](https://user-images.githubusercontent.com/14999/125608697-25622829-7350-45d7-9425-dadf6a6d3ce4.jpeg)

**Comment by erayhamurlu** [comment]
Okay. How can i reset after sending database?
