### ISSUE TITLE
Plugin not getting high speeds

### ISSUE THREAD

**Issue by erayhamurlu** [transistorsoft/flutter_background_geolocation#594]
My Environment

Plugin version: ^2.1.0
Platform: iOS or Android
OS version: 14
Device manufacturer / model: Iphone6s / Iphone11 / SamsungJ6+

```dart 
case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      var data = json.encode(
        {
          "Speed": location.coords.speed,
        },
      );
```

When i in vehicle driving around 100m/s
but plugin recording my speed  around 20m/s

**Comment by christocracy** [comment]
![image](https://user-images.githubusercontent.com/14999/125608355-965157a8-d855-403e-8787-ab381276ca33.jpeg)

**Comment by erayhamurlu** [comment]
Ohh sorry. thanks.
