### ISSUE TITLE
How can you avoid "Waiting for previous start action to complete" when changing tracking modes?

### ISSUE THREAD

**Issue by danieltai** [transistorsoft/flutter_background_geolocation#597]
## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung SM-A705GM
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel unknown, 2.0.3, on macOS 11.4 20F71 darwin-x64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.1)
[✓] Connected device (3 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
static final bg.Config _config = bg.Config(
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 50.0,
  geofenceInitialTriggerEntry: true,
  stopOnTerminate: false,
  startOnBoot: true,
  logLevel: _logLevel,
  logMaxDays: 3,
  disableLocationAuthorizationAlert: true,
  enableHeadless: true,
  notification: bg.Notification(
    title: "Check-in locations nearby",
    text: "Tap to open app",
    channelName: "Locations",
    smallIcon: "drawable/ic_stat_name",
    largeIcon: "drawable/ic_stat_name",
  ),
);
```

## Expected Behavior

Ability to change tracking mode (using `start` or `startGeofences`) without running into the "Waiting for previous start action to complete" platform exception.

## Actual Behavior

Plugin will occasionally throw a platform exception with message "Waiting for previous start action to complete" when changing tracking modes.

## Steps to Reproduce

This is my function for changing tracking modes:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
static Future<void> _changeTrackingModeIfNeeded(int trackingMode) async {
  await _logInfo('_changeTrackingModeIfNeeded', 'trackingMode=$trackingMode');
  try {
    final state = await bg.BackgroundGeolocation.ready(_config);
    await _logInfo('_changeTrackingModeIfNeeded', 'state=$state');
    if (state.enabled && state.trackingMode == trackingMode) {
      await _logInfo(
        '_changeTrackingModeIfNeeded',
        'Plugin is already enabled with same tracking mode.',
      );
      return;
    }
    switch (trackingMode) {
      case TrackingMode.geofences:
        await _logInfo(
          '_changeTrackingModeIfNeeded',
          'Switching to geofence-only tracking...',
        );
        await bg.BackgroundGeolocation.startGeofences();
        return;
      case TrackingMode.location:
        await _logInfo(
          '_changeTrackingModeIfNeeded',
          'Switching to active location tracking...',
        );
        await bg.BackgroundGeolocation.start();
        return;
    }
  } catch (error, stack) {
    await FirebaseCrashlytics.instance.recordError(error, stack);
    await _logInfo(
      "_changeTrackingModeIfNeeded",
      "error=$error, stack=$stack",
    );
  }
```

I understand that you do not need to call `start` when `state.enabled == true` in the callback to `ready`, but is there another way to change the tracking mode?

How can I properly await the previous start action?

I used `ready` in the hopes that it will await the start action before the callback. I used `state` previously with the same result.

## Context

I'm using active location tracking (trackingMode=1) to implement polygon geofences (large circular geofence surrounds polygon, when a user enters the geofence, switch from geofence-only tracking to location + geofence tracking and use the frequent location updates to determine if they are inside the polygon).

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
07-18 09:40:14.546 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] trackingMode=0
07-18 09:40:14.548 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
07-18 09:40:14.553 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] state=[State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: -1, distanceFilter: 50.0, odometer: 3672.334716796875, schedulerEnabled: false, foregroundService: true]
07-18 09:40:14.554 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] Switching to geofence-only tracking...
07-18 09:40:14.561 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] error=PlatformException(Waiting for previous start action to complete, null, null, null), stack=#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
```

```
07-18 17:54:50.769 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] trackingMode=1
07-18 17:54:50.771 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
07-18 17:54:50.788 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] state=[State enabled: true, isMoving: false, trackingMode: 0, desiredAccuracy: -1, distanceFilter: 50.0, odometer: 4291.05029296875, schedulerEnabled: false, foregroundService: true]
07-18 17:54:50.790 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] Switching to active location tracking...
07-18 17:54:50.800 INFO [TSLog log] 
  ℹ️  [GeolocationService _changeTrackingModeIfNeeded] error=PlatformException(Waiting for previous start action to complete, null, null, null), stack=#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
```

</details>

**Comment by christocracy** [comment]
.ready() is to be called *only once* for each run of your app.  Are you calling it more than once?

**Comment by danieltai** [comment]
Yes, `_changeTrackingModeIfNeeded` could be called on a geofence or location event (foreground and headless) - will change to use `.state()`. 

But I believe I will still run into the same exception using `.state()`.

**Comment by christocracy** [comment]
.ready is a signal to the plugin that your app has launched and *"ready"*.  Edit your code and ensure that .ready() is called only once per app launch.

> I believe I will still run into the same exception using

It is not an exception.  It is a warning and does not affect plugin performance.  It is a signal that your code is doing something weird.

**Comment by danieltai** [comment]
I have updated `_changeTrackingModeIfNeeded` to check the current plugin state using `.state` instead of `.ready` now.

Does `.ready` need to be called in headless mode? Before the addition of `_changeTrackingModeIfNeeded`, my app never called `.ready` in headless mode, only in the `initState` of my root widget and in two functions triggered by user actions (which I will fix to ensure ready is only called once per app launch), but I was still getting reports of this warning.

If this PlatformException is thrown, does the tracking mode still get changed?

How can I await any pending "start action" to ensure that I am able to change the tracking mode using `start`/`startGeofences`?

**Comment by christocracy** [comment]
>If this PlatformException is thrown, does the tracking mode still get changed?

Probably.  Check `State.trackingMode`.  `1 = location + geofences`; `0 = geofences-only`.

**Comment by christocracy** [comment]
I changed my mind.  Polygon geofencing is coming soon. I’m using c++ libraries to calculate the “minimum enclosing circle” around the polygon (used to create the traditional native Circular geofence). Once the circular geofence is entered, a foreground-service is launched to initiate fast location-updates used to “hit test” the polygon with another c++ library.
