### ISSUE TITLE
The App does'nt compile with compileDebugJavaWithJavac error

### ISSUE THREAD

**Issue by CBWanderer** [transistorsoft/flutter_background_geolocation#6]
I'm trying to run the example app provided. It does'nt compile.

## Your Environment
* Plugin version: '^0.1.0'
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: RCA RLTP5567
* Flutter info (`flutter doctor`):
```
[√] Flutter (Channel master, v0.5.8-pre.152, on Microsoft Windows [VersiÃ³n 10.0.16299.637], locale es-US)
    • Flutter version 0.5.8-pre.152 at C:\Data\dev\flutter\sdk
    • Framework revision 8b05629658 (10 weeks ago), 2018-07-26 19:12:04 -0700
    • Engine revision 6f7bdc9fab
    • Dart version 2.0.0-dev.69.3.flutter-937ee2e8ca

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Data\dev\android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Data\dev\android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • RLTP5567 • 0123456789ABCDEF • android-arm • Android 6.0 (API 23)
```

• No issues found!
* Plugin config

## Expected Behavior

The app should coompile and run in the phone.

## Actual Behavior

The app fails to compile with an error.

## Steps to Reproduce

1. Download the plugin
2. Get packages (flutter packages get)
3. Execute (flutter run)
4. Wait for it...

## Debug logs
`Launching lib/main.dart on RLTP5567 in debug mode...`
`Initializing gradle...                                       2.8s`
`Resolving dependencies...                                    7.0s`
`Running 'gradlew assembleDebug'...`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:18: error: cannot find symbol`
`import io.flutter.view.FlutterCallbackInformation;`
`                      ^`
`  symbol:   class FlutterCallbackInformation`
`  location: package io.flutter.view`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:22: error: cannot find symbol`
`import io.flutter.view.FlutterRunArguments;`
`                      ^`
`  symbol:   class FlutterRunArguments`
`  location: package io.flutter.view`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:62: error: cannot find symbol`
`            FlutterCallbackInformation callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(sRegistrationCallbackId);`
`            ^`
`  symbol:   class FlutterCallbackInformation`
`  location: class HeadlessTask`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:62: error: cannot find symbol`
`            FlutterCallbackInformation callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(sRegistrationCallbackId);`
`                                                      ^`
`  symbol:   variable FlutterCallbackInformation`
`  location: class HeadlessTask`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:68: error: constructor FlutterNativeView in class FlutterNativeView cannot be applied to given types;`
`            sBackgroundFlutterView = new FlutterNativeView(context, true);`
`                                     ^`
`  required: Context`
`  found: Context,boolean`
`  reason: actual and formal argument lists differ in length`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:77: error: cannot find symbol`
`            FlutterRunArguments args = new FlutterRunArguments();`
`            ^`
`  symbol:   class FlutterRunArguments`
`  location: class HeadlessTask`
`C:\Users\User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_background_geolocation-0.1.5\android\src\main\java\com\transistorsoft\flutter\backgroundgeolocation\HeadlessTask.java:77: error: cannot find symbol`
`            FlutterRunArguments args = new FlutterRunArguments();`
`                                           ^`
`  symbol:   class FlutterRunArguments`
`  location: class HeadlessTask`
`7 errors`
``
`FAILURE: Build failed with an exception.`
``
`* What went wrong:`
`Execution failed for task ':flutter_background_geolocation:compileDebugJavaWithJavac'.`
`> Compilation failed; see the compiler error output for details.`
``
`* Try:`
`Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
``
`* Get more help at https://help.gradle.org`

`BUILD FAILED in 10s`
`Gradle build failed: 1`

**Comment by christocracy** [comment]
I’ll be looking into this ASAP.

**Comment by christocracy** [comment]
FYI:  To syntax highlight multi-line comment, wrap the entire blob in triple-backticks.

**Comment by christocracy** [comment]
Here's my `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected devices (4 available)
```

I think you need to be on `flutter v0.8.2`

**Comment by CBWanderer** [comment]
It solved it! Thanks for your quick response! You are doing a great work. I'll try the plugin and will let contact you if finally suits my project. Thanks again!
