### ISSUE TITLE
GeoFence Enter Exit not firing

### ISSUE THREAD

**Issue by liveaffiliates** [transistorsoft/flutter_background_geolocation#60]
## Your Environment
* Plugin version:
flutter_background_geolocation: '^0.3.4'

* Platform: iOS or Android
Android

* OS version:
Oreo: Versions 8.0.0

* Device manufacturer / model:
Samsung Galaxy S9

* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.33.0)
[!] Connected device
    ! No devices available

* Plugin config
```dart
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
      if (!state.enabled) {
        // 3.  Start the plugin.
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
geoFence Event triggers

## Actual Behavior
Nothing

## Steps to Reproduce
This is the main.dart it only contains the examples from the documentation. This is all the code that is running.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  void initState() {
    
    //1.  Listen to geofence events
    bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) {
      print('onGeofence ${event}');
    });
    
    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
      if (!state.enabled) {
        // 3.  Start the plugin.
        bg.BackgroundGeolocation.start();
      }
    });

    bg.BackgroundGeolocation.setConfig(bg.Config(
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      print("Changed logLevel success");
    });
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Geo Location Test',
      theme: ThemeData(
         primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Geo Location Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[

            RaisedButton(
              child: Text('Add Geofence'),
              onPressed:() {
                 bg.BackgroundGeolocation.addGeofence(bg.Geofence(
                    identifier: 'MainFence',
                    radius: 200,
                    latitude: -31.950260,
                    longitude: 115.851840,
                    notifyOnEntry: true,
                    notifyOnExit: true,
                    extras: {
                      "route_id": 0
                    }
                )).then((bool success) {
                  print('[addGeofence] success');
                }).catchError((dynamic error) {
                  print('[addGeofence] FAILURE: $error');
                });
              },

            ),
         ],
        ),
      ),
    );
  }
}
```

## Context
Have event triggered when user enters a geofence (preferably if they have been there for 30s)

## Debug logs
- Android: $ adb logcat
05-14 21:41:34.580 25462 25462 I TSLocationManager:
05-14 21:41:34.580 25462 25462 I TSLocationManager: ╔═════════════════════════════════════════════
05-14 21:41:34.580 25462 25462 I TSLocationManager: ║ License Validation Failure
05-14 21:41:34.580 25462 25462 I TSLocationManager: ╠═════════════════════════════════════════════
05-14 21:41:34.580 25462 25462 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
-->

**Comment by christocracy** [comment]
You've declared your `Myapp extends StatelessWidget`.  I don't think `initState` runs there.

```dart
class MyApp extends StatelessWidget {

  @override
  void initState() {
    // I don't think this method is running.
  }
```

**Comment by liveaffiliates** [comment]
Awesome that was the problem. I will continue to try and implement it.

 Thank you very much Chris

**Comment by christocracy** [comment]
You can get rid of this:
```dart
bg.BackgroundGeolocation.setConfig(bg.Config(
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      print("Changed logLevel success");
    });
```

**Comment by liveaffiliates** [comment]
Deleted.

I just tried and it seem to be working great.

Not sure how to contact you other than here, please let me know if there is a better way to ask like email. If I wanted it to be accurate with the location (address) that they are at, rather than the 200m and to see if they are there for 30 seconds is this possible?

Thanks again.

**Comment by christocracy** [comment]
>Not sure how to contact you other than here 

I prefer technical questions to be sent to Github issues, here.  I get dozens of emails / day and my email is not searchable *by others*.

>If I wanted it to be accurate with the location (address) that they are at, rather than the 200m and to see if they are there for 30 seconds is this possible?

Native geofence API minimum reliable radius is 150-200 meters.  Use the native geofence as a cue to start running your own custom algorithm.

>see if they are there for 30 seconds is this possible?

Use `notifyOnDwell` with `loiteringDelay: 30000`.

Btw, if you're only monitoring geofences, use `#startGeofences` instead of `#start`.

You can use `onGeofence` to switch between `#start` / `#startGeofences`.

Maybe the user enters a geofence *then* you `#start` aggressively monitoring where they go within the geofence (eg: `distanceFilter: 0`) and use a custom algorithm to ask if the user is within some smaller region.

When they *exit* the geofence, you switch back to *geofences-only* mode with `#startGeofences`.

**Comment by liveaffiliates** [comment]
Will implement that. 

Thanks!

**Comment by sravankumar27n** [comment]
HI 
I'm getting continuous notification while using BackgroundGeolocation method.

Please tell me how to handle those notifications?

**Comment by christocracy** [comment]
> I'm getting continuous notification while using BackgroundGeolocation method.

I don’t see how that relates to this issue titled *“GeoFence Enter Exit not firing”*
