### ISSUE TITLE
After launching the app 408 location error came

### ISSUE THREAD

**Issue by gautamenbake** [transistorsoft/flutter_background_geolocation#601]
![image](https://user-images.githubusercontent.com/73814526/126983163-6777f75f-d8a9-4263-b583-8c08efb2b093.png)

## Your Environment
* Plugin version:
* Platform:  Android
* OS version: MIUI 12
* Device manufacturer / model: Redmi Note 8
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Location should be send on server

## Actual Behavior

Location error came

## Context

- My device location was On
- Internet had good connectivity

**Comment by christocracy** [comment]
Do you know what a 408 error means?
