### ISSUE TITLE
is Location Service Enabled

### ISSUE THREAD

**Issue by flutteresbolivia** [transistorsoft/flutter_background_geolocation#603]
Hello, how are you?
I am looking in the documentation and I can not find something about, verify if my phone has the gps service activated.

What I do is 
```
var status = await BackgroundGeolocation.requestPermission ();
      if (status == ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS || status == ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE) {
        var location = await BackgroundGeolocation.getCurrentPosition (persist: false);
}

```
is there any method to verify this before?

**Comment by christocracy** [comment]
See api docs:

https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/providerState.html
