### ISSUE TITLE
Unable to build due to Jcenter deprecated

### ISSUE THREAD

**Issue by grahamsmith** [transistorsoft/flutter_background_geolocation#605]
## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`): N/A
* Plugin config: N/A

## Expected Behavior
The Plugin should build with the app. 

## Actual Behavior
We have made no changes and build have started failing, likely due to Jcenter being taken down. Upgraded from 4.0.0 to 4.0.2 in case.

![Screenshot 2021-07-30 at 14 19 51](https://user-images.githubusercontent.com/1571527/127659060-ebafa5e8-a1e2-41c5-a33a-4041cd0ac59c.png)

## Steps to Reproduce
N/A

## Context
Build a debug version of the app via CI.

## Debug logs
See image above.

**Comment by christocracy** [comment]
Show me your `android/build.gradle`

**Comment by grahamsmith** [comment]
Thanks here it is.

```buildscript {
    ext.kotlin_version = '1.4.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}```

**Comment by christocracy** [comment]
The [author of android-permissions](https://github.com/nishkarsh/android-permissions/issues/20) has migrated to *MavenCentral* (expedited by a $300 donation).  However, [jCenter will be available indefinitely for existing artifacts](https://developer.android.com/studio/build/jcenter-migration).

In the next release, the plugin will update its `build.gradle` to import `android-permissions` from *MavenCentral*, but there's no reason that existing artifacts at jcenter should not be served, as long as you've declared `jcenter()` in your `repositories` section.  


```gradle
implementation 'io.github.nishkarsh:android-permissions:0.1.8'
```

**Comment by christocracy** [comment]
Your logs show problems with a number of dependencies, including `flutter` ones.

**Comment by christocracy** [comment]
Here is a reference to [android-permissions:0.1.8 as jcenter](https://mvnrepository.com/artifact/com.intentfilter/android-permissions/0.1.8)

**Comment by grahamsmith** [comment]
It's weird as we haven't changed anything.

I followed the links to the pom files and they 403 so unsure on the route to fixing this.

It could be a CodeMagic issue but I doubt it given the 403s locally.

**Comment by christocracy** [comment]
Could be a muck-up at jCenter currently.

- Open your app's `/android` folder in *Android Studio*
- Edit the `build.gradle (Module: flutter_background_geolocation`).
- Change the `android-permissions` dependency as shown:
```
implementation 'io.github.nishkarsh:android-permissions:0.1.8'
```

![](https://dl.dropbox.com/s/mwpfxt55kukuso2/Screen%20Shot%202021-07-30%20at%209.49.24%20AM.png?dl=1)

**Comment by christocracy** [comment]
*jCenter* seems to be back-in-action.  The [aar](https://mvnrepository.com/artifact/com.intentfilter/android-permissions/0.1.8) doesn't return `403` for me anymore.

**Comment by grahamsmith** [comment]
Awesome. Thanks for the help 👍😎
