### ISSUE TITLE
Update Android android-permissions to import from MavenCentral instead of deprecated jCenter

### ISSUE THREAD

**Issue by flutteresbolivia** [transistorsoft/flutter_background_geolocation#608]
in the new version of 4.2.1 there is an update, which says the following:

`[Changed][Android] Update Android android-permissions to import from MavenCentral instead of deprecated jCenter`

I went to the link for android settings, but it is still out of date.
Someone would be kind to pass the configuration and update in the graddles? Thank you.

**Comment by christocracy** [comment]
There is nothing you need to do.
