### ISSUE TITLE
ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE throws platform exception

### ISSUE THREAD

**Issue by arefay** [transistorsoft/flutter_background_geolocation#61]
## Summary
When issuing a .requestPermissions() call and responding with "Only while using the App", the callback throws a platform exception. Here's the code which I've basically taken from the intellisense example of the method:

```
bg.BackgroundGeolocation.requestPermission()
                      .then((int status) {
                    print("[requestPermission] STATUS: $status");
                    switch (status) {
                      case bg.ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS:
                        print(
                            "[requestPermission] AUTHORIZATION_STATUS_ALWAYS");
                        break;
                      case bg
                          .ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE:
                        print(
                            "[requestPermission] AUTHORIZATION_STATUS_WHEN_IN_USE");
                        break;
                    }
                  }).catchError((dynamic error) {
                    print("[requestPermission] ERROR: $error");
                  });
```

## Your Environment
* Plugin version: ^1.0.5
* Platform: iOS
* OS version: Simulator Version 10.2.1, also tried on physical iOS/iphone device
* Device manufacturer / model:
* Flutter info :

`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

• No issues found!
`

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        autoSync: false,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        /// Start the plugin.
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
When I click "Only when in use" i would expect it to return status of AUTHORIZATION_STATUS_WHEN_IN_USE

## Actual Behavior
Hits the catchError instead and returns platform exception "ERROR: PlatformException(DENIED, null, 4)"

## Steps to Reproduce
see above - 

## Context
I'm trying to build an onboarding flow where we ask the user for location permissions, when they click "Allow always" it returns the right status as expected, same for when they don't allow, but when they click "Only when using the App" it throws the above mentioned exception.

**Comment by arefay** [comment]
Ok - seems I'm probably using this wrong - I'm calling .requestPermissions BEFORE starting the plugin. I will read the docs more closely but seems I haven't yet found a way to prevent the plugin from auto-requesting permissions on startup and instead waiting on me to issue a .requestPermissions call later on in onboarding.

**Comment by arefay** [comment]
Per the docs it seems .start() will automatically request permissions, I guess I'm not yet clear how to setup the plugin and only .start() it after requesting permissions has been manually called and received...

**Comment by christocracy** [comment]
I’ll look into it, but yes. #start automatically requests permission.

You typically don’t need to use requestPermission.

**Comment by arefay** [comment]
Thanks for the quick reply - I believe I have it working now by simply 'starting' the plugin as part of the onboard flow in the place where one would ask for permission. On subsequent app -starts using the bg.State to start the app from a global container if it wasn't previously started during onboarding (e.g. when onboard was completed and app re-starts another time) -

**Comment by christocracy** [comment]
It's perfectly fine to `#ready` the plugin *before* users are on-boarded.

The plugin persists its "started" state.  If you `#start` the plugin, terminate the app and re-launch, `#ready` automatically calls `#start` upon itself, since `state.enabled == true`.

When users logout, you call `#stop`.

**Comment by arefay** [comment]
Just to confirm, there's currently no way to 'ready' (or start) the plugin
without it automatically prompting the user for permissions. I assume
there's some reason for that but wondering if there's any value in having a
way to 'suppress' the ask-dialog and then instead letting the developer
place a .getPermissions in some other place.

Or, if the above is not desired, is there currently  a way to 'trigger' the
connectivity check which is automatically done in .start() - ?

Thanks again - this is a great plugin!
