### ISSUE TITLE
Reverse locations reported.

### ISSUE THREAD

**Issue by varunverma-sdd** [transistorsoft/flutter_background_geolocation#612]
Hii, I am facing a weird problem while sending live locations on the server by plugin. whenever i stops and slow down my speed less than 7 or something it starts sending locations in reverse. by doing this it looks like i am going to reverse direction without going anywhere in real. IDK why this issue is coming please let me know why this issue is coming and how to get rid from this. i need when i stops plugin should not send any locations. it should send locations again when i start driving. Thanks!

**Comment by christocracy** [comment]
I don't know what you're talking about and you ignored the issue template.
