### ISSUE TITLE
How reset odometer?

### ISSUE THREAD

**Issue by erayhamurlu** [transistorsoft/flutter_background_geolocation#614]
I want to show weekly sum kilometers and monthly sum kilometers to my users.

but odometers always summing.

Example:
User total distance traveled is 10km
Next day user total distance 10km(during the day) but odometer shows 20km. 
I think i have to reset odometer after saved distance but how i do it i don't know.

**Comment by christocracy** [comment]
Have you tried searching the api docs for methods containing the word *"odometer"*?
