### ISSUE TITLE
Could not find any matches for com.transistorsoft:tsbackgroundfetch

### ISSUE THREAD

**Issue by cbalmeida** [transistorsoft/flutter_background_geolocation#617]
Scenario:

I have created this package called "geolocation" to be used inside my application (the plugin in only declared on the package's pubspec, in order of not allowing any other classes to deal with the geolocation/maps external plugins).

==================

Issue:  I'm having this error while compiling/building:

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/christian/StudioProjects/fv_c2/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/christian/StudioProjects/fv_c2/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

==================

Package's pubscpec:

name: geolocation
description:
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background_geolocation: ^4.2.1
  google_maps_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

===========================

App's pubspec:

name: *****
description: *****2

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.10
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: 5.0.5955-rc.1
  path_provider: ^2.0.2
  flutter_archive: ^4.0.1
  intl: ^0.17.0
  substring_highlight: ^1.0.33
  permission_handler: ^8.1.4+2

  framework:
    path: packages/framework

  datamodels:
    path: packages/datamodels

  businessmodels:
    path: packages/businessmodels

  feature_framework:
    path: packages/feature_framework

  resources:
    path: packages/resources

  widgets:
    path: packages/widgets

  utils:
    path: packages/utils

  geolocation:
    path: packages/geolocation

dev_dependencies:
  build_runner: ^2.0.4
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: kanit
      fonts:
        - asset: fonts/kanit/Kanit-Regular.ttf
        - asset: fonts/kanit/Kanit-Bold.ttf
          weight: 700
    - family: saira_extra_condensed
      fonts:
        - asset: fonts/saira_extra_condensed/SairaExtraCondensed-Regular.ttf
        - asset: fonts/saira_extra_condensed/SairaExtraCondensed-Bold.ttf
          weight: 700
    - family: average_sans
      fonts:
        - asset: fonts/average_sans/AverageSans-Regular.ttf

**Comment by christocracy** [comment]
You did not perform the Setup Instructions for background-fetch.

Re-visit the Setup Instructions and carefully follow exactly as directed.

**Comment by christocracy** [comment]
Duplicate https://github.com/transistorsoft/flutter_background_fetch/issues/204
