### ISSUE TITLE
Unable to get locations when choosing "Allow Only While using the app", deny Physical Activty and app is in background

### ISSUE THREAD

**Issue by TMSfirst-App** [transistorsoft/flutter_background_geolocation#618]
Unable to get locations when the application is in background (Showing in recent apps) user denied Physical activity permission and opted for "While in use" for location services.
Same behaviour is observed in multiple devices:
Google Pixel 4a
Nokia 6.1
Samsung Note 10

## Your Environment
* Plugin version: 4.2.1
* Platform: Android
* OS version: 11
* Device manufacturer / model: Google
* Flutter info (`flutter doctor`):
* [✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/nanda/Developer/flutter
    • Framework revision c5a4b4029c (6 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nanda/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
* Plugin config:

```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      url: 'https://myProductionUrl/Locations',
      method: 'POST',
      autoSync: true,
      enableHeadless: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20,
      stopOnTerminate: false,
      startOnBoot: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      backgroundPermissionRationale: bg.PermissionRationale(
          title: "Allow app name to access to this device's location in the background?",
          message: "In order to track your route accurately, please enable 'Allow all the time' location permission",
          positiveAction: "Change to Allow all the time",
          negativeAction: "Cancel"
      ),
      notification: bg.Notification(title: notificationTitle, text: notificationContent, channelName: 'Location Services')
  ))
```

## Expected Behavior
Application should post locations to the server until application is removed from the background when "While In Use" is opted by the user
## Actual Behavior
No locations are getting posted to the server when While In Use is selected by the user
## Steps to Reproduce

1. Use the above config and create a application
2. Deny Physical activity permission and choose "Allow Only While using the app"
3. Start the tracking
4. Observe that location service is getting turned off when home button is clicked. But the tracking notification is still getting displayed but locations are not being pushed

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Logs obtained from logger.getLog()

I/flutter (12943): 08-18 14:05:22.328 DEBUG [LoggerFacade$a a] ℹ️   Persist config, dirty: []
I/flutter (12943): 08-18 14:05:22.335 INFO [LoggerFacade$a a] 
I/flutter (12943):   ✅  Google Play Services: connected (version code:12451000)
I/flutter (12943): 08-18 14:05:22.337 INFO [LoggerFacade$a a] 
I/flutter (12943):   🎾  Start monitoring location-provider changes
I/flutter (12943): 08-18 14:05:22.339 DEBUG [BackgroundGeolocation a] 
I/flutter (12943):   🔴  Cleared callbacks
I/flutter (12943): 08-18 14:05:22.340 DEBUG [a onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, data BLOB, encrypted BOOLEAN NOT NULL DEFAULT 0, locked BOOLEAN NOT NULL DEFAULT 0);
I/flutter (12943): 08-18 14:05:22.341 DEBUG [StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/location
I/flutter (12943): 08-18 14:05:22.344 DEBUG [StreamHandler register] com.transistorsoft/flutter_background_geolocation/events/motionchange
I/flutter (12943): 08-18 14:05:22.345 DEBUG [a onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL
```

</details>

**Comment by christocracy** [comment]
What do you think "When in use" means?

**Comment by TMSfirst-App** [comment]
Location services can be accessed when application is in foreground (User is interacting with it) and in background (Application is in memory along with recent apps)

**Comment by christocracy** [comment]
After calling .start(), you must execute .changePace(true).


Also Read the wiki *Philosophy of Operation*.

**Comment by TMSfirst-App** [comment]
Yep this resolved our issue. Closing the issue.
Thanks for the quick replies
