### ISSUE TITLE
how to listen to event

### ISSUE THREAD

**Issue by netwrkx** [transistorsoft/flutter_background_geolocation#62]
how can i listen/stream events like in ionic3

```
  on(event, callback) {
    this.events.subscribe(event, callback);
  }
  this.bgService.on('onLocation', (position) => {})
```

whats the equivalent of this in flutter

**Comment by christocracy** [comment]
It's [in the docs](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation-class.html)

**Comment by netwrkx** [comment]
Can you pls point it out, I've check and I can't find anything like that.

**Comment by christocracy** [comment]
It's right there in the docs?  `onLocation`, `onMotionChange`, etc.

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/uqzxl1yrvrzwcde/Screenshot%202019-05-20%2007.20.26.png?dl=1)

**Comment by christocracy** [comment]
With Cordova, it wouldn't be:
```javascript
this.bgService.on('onLocation', (position) => {})
```
It would be:
```javascript
this.bgService.onLocation((position => {});
```
Just like Flutter.
