### ISSUE TITLE
Doubt about package flutter background geolocation

### ISSUE THREAD

**Issue by wellson-fleetdesk** [transistorsoft/flutter_background_geolocation#620]
## Your Environment
* Plugin version: **flutter_background_geolocation version 1.9.3**, license adquired by Fleetdesk
* Platform:  Android
* OS version:
* Device manufacturer / model: Redmi Note 8 PRO
* Flutter info (`flutter doctor`):
* Plugin config:

## Context

 Hello, after reading the documentation and we raised some doubts where we have in our project, the flutter_background_geolocation version 1.9.3, which we use to do the monitoring of geographic fences and fence point that does the distance check to check if the position is correct. We use BackgroundGeolocation.ongeofence() and adding the fence points with BackgroundGeolocation.addGeofence() with setting set:

1.1
``` <!-- syntax-highligting:  DO NOT REMOVE -->
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;
   

    bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) async {
      print('[geofence] ${event.identifier}, ${event.action}');
      if (event.action == 'ENTER') {
        insideGeofence = true;
      } else if (event.action == 'EXIT') {
        insideGeofence = false;
      }

   bg.BackgroundGeolocation.ready(
        bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 0,
          desiredOdometerAccuracy: 100,
          stopOnTerminate: false,
          startOnBoot: true,
          logMaxDays: 3,
          locationUpdateInterval: 60000,
          preventSuspend: true,
          heartbeatInterval: 120,
          disableStopDetection: true,
          pausesLocationUpdatesAutomatically: false,
          useSignificantChangesOnly: false,
          foregroundService: true,
          stopTimeout: 5,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_ERROR,
          ),
          );
```
 1.2 - In another point of the project we need to add using BackgroundGeolocation.addGeofences() and sculpt with BackgroundGeolocation.ongeofence() several geofences, monitoring and checking if it entered the 200 m radius or left the electronic fence, if it entered it will trigger a single alert saying that it has entered the 200 m radius, when it leaves this 200 m radius it issues another single alert saying that it has left the radius. Given the information I would like to know if I can use the configuration above (1.1) of BackgroundGeolocation.ready(bg.Config( )), in this situation mentioned or do I have to create for each different configuration or can I only use one? given this scenario mentioned in 1.2 which recommendation?

I made this configuration:
``` <!-- syntax-highligting:  DO NOT REMOVE -->
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;
   
bg.BackgroundGeolocation.ready(
        bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 200,
          //10
          desiredOdometerAccuracy: 100,
          // minimumActivityRecognitionConfidence: 40,
          // Adjust lower for low-end devices
          // allowIdenticalLocations: false,
          stopOnTerminate: false,
          startOnBoot: true,
          // preventSuspend: true,
          logMaxDays: 3,
          locationUpdateInterval: 0,
          preventSuspend: true,
          //5000
          heartbeatInterval: 60,
          disableStopDetection: true,
          pausesLocationUpdatesAutomatically: false,
          useSignificantChangesOnly: false,
          foregroundService: true,
          isMoving: true,
          stopTimeout: 5,
          //speedJumpFilter: 300,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_ERROR,
          locationAuthorizationRequest: 'Always',
          geofenceInitialTriggerEntry: true
          ),
          );
```

1.3 - Using the method bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) async {}, event.action it will fire several events, with an ENTER response, instead of sending just an event saying that it entered the 200m radius and left it fires a single EXIT event, instead of multiple events saying it left the 200m radius, which is a recommendation for this scenario?.

1.4 - Removing Geofence
 
 When removing BackgroundGeolocation.removeGeofence() electronic fences, will it remove all other past or just created geofences?
 
 Because there is today BackgroundGeolocation.removeGeofence() and BackgroundGeolocation.removeGeofences(), all of which exclude the existing fences?.

1.5  - Does this event in case of vehicle movement at a speed of 40 to 60 km/h  apply to need?
``` <!-- syntax-highligting:  DO NOT REMOVE -->
// Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print('[location] - $location');
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });

```

## Expected Behavior

An array of geofences, in which the plugin sends a single alert when it enters a radius of 200 meters and when it leaves the radius of 200 meters it sends a single alert warning that it has left the geofence.
## Actual Behavior

the plugin sends multiple Enter and Exit alerts at the same time. How the vehicle is moving. The alert gets many responses.
## Steps to Reproduce

1.Geofences -ENTER
2.Geofences -ENTER
3.Geofences -ENTER
4.Geofences -ENTER

1.Geofences -EXIT
2.Geofences -EXIT
3.Geofences -EXIT
4.Geofences -EXIT

**Comment by christocracy** [comment]
Please edit your post and [apply syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to your code-blocks.

**Comment by christocracy** [comment]
You are likely listening to onGeofence *multiple times*.  The geofence itself is firing just once to your multiple listeners.

You can see the plugin's geofences firing in its own logs.  See wiki *Debugging* to learn how to observe the plugin logs.

**Comment by wellson-fleetdesk** [comment]
I can use various settings in the project as mentioned above in 1.1 in the enunciated with bg.BackgroundGeolocation.ready(); method. Today I currently have the method setting with distanceFilter: 0, and I need to check in another part of the project the distance of 200 m. Can I use multiple Config? and set distanceFilter .

**Comment by christocracy** [comment]
> Can I use multiple Config? and set distanceFilter .

No.

**Comment by christocracy** [comment]
You can, of course, change Config with method .setConfig

**Comment by wellson-fleetdesk** [comment]
> You can, of course, change Config after .ready() has run, with method .setConfig

**Comment by wellson-fleetdesk** [comment]
So for me to check the 200 m radius, if it entered or left, I use distanceFilter, with .setConfig configuration?

And using .addGeofence and .addGeofences the lists are all in the same place? if I need remove if I run the .removeGeofences() method, I will remove all joints added in the addGeofence and addGeofences methods.

**Comment by christocracy** [comment]
>So for me to check the 200 m radius, if it entered or left, I use distanceFilter

You're imaging this to be far more complex than it actually is.  `distanceFilter` has nothing to do with geofence monitoring.  Geofences are monitored and fired *automatically* by the operating system.  The only thing you need to do is `addGeofences` and listen for them to trigger in `onGeofence`.

>And using .addGeofence and .addGeofences the lists are all in the same place?

You're making this more complex than it actually is.  `addGeofence` is for adding a single geofence.  `addGeofences` add *multiple* geofences.  At the end of the day, geofences are inserted into a SQLITE database `INSERT INTO geofences ...`.  `addGeofence` adds *one record* to the database.  `addGeofences` is merely a convenience method to add *multiple* records.

- `removeGeofences` will delete all records:  `DELETE FROM geofences`
- `removeGeofence` will delete **ONE** record.  `DELETE FROM geofences WHERE identifier=?`.

It is not complex.

**Comment by wellson-fleetdesk** [comment]
Okay, test here I did as reported I noticed a delay when the event appears, I made a video for you to analyze https://drive.google.com/file/d/12WmfTBBc3Se-szlf_-r2Uz6GRmRQl3rB/view?usp=sharing, when I enter a event it sends ENTER event, then it stays quiet when it left the event, it takes time to send the Exit event. Then I go to another location when I enter location 2 passes nothing appears, then when it left there is no event and when I go to another location 3, it downloads the events that did not appear at once.

**Comment by christocracy** [comment]
> debug: false,

Set it to `true`.

It can take movement of 100-200 meters outside a geofence before it fires.

**Comment by wellson-fleetdesk** [comment]
I understand, I did another test measuring the distance until it triggered the first alarm that entered the geofence marked 116 meters to trigger ENTER event and when leaving it measured 700 meters until it triggers the EXIT event alert. Is correct?

**Comment by christocracy** [comment]
Geofences are managed by the operating system.

If you're using geofencing-only mode with .startGeofences() instead location+geofencing mode with .start(), geofence triggering will be delayed.

**Comment by wellson-fleetdesk** [comment]
> Geofences are managed by the operating system.
> 
> If you're using geofencing-only mode with .startGeofences() instead location+geofencing mode with .start(), geofence triggering will be delayed.

 state = await bg.BackgroundGeolocation.start();

**Comment by christocracy** [comment]
Have you applied the suggestions to your device settings at http://dontkillmyapp.com?

There's nothing the plugin can do to improve the performance of your particular device.

I experience exceptional geofence triggering performance on my test devices:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by wellson-fleetdesk** [comment]
> > Geofences are managed by the operating system.
> > If you're using geofencing-only mode with .startGeofences() instead location+geofencing mode with .start(), geofence triggering will be delayed.
> 
> am i using like this? it's wrong? state = await bg.BackgroundGeolocation.start();

Can you explain more about this? I was unsure if I should use BackgroundGeolocation.start() or .startGeofences() in this case.

You referred there about:

instead location+geofencing mode with .start(), geofence triggering will be delayed.

**Comment by christocracy** [comment]
`.start()` = track geofences + location.

![](https://dl.dropbox.com/s/wiyxpchczdxsfsi/Screen%20Shot%202021-08-20%20at%205.22.30%20PM.png?dl=1)

`.startGeofences()` = track geofences only.

![](https://dl.dropbox.com/s/ljagngsn6jftj5z/Screen%20Shot%202021-08-20%20at%205.23.34%20PM.png?dl=1)

**Comment by wellson-fleetdesk** [comment]
> Have you applied the suggestions to your device settings at http://dontkillmyapp.com?
> 
> There's nothing the plugin can do to improve the performance of your particular device.
> 
> I experience exceptional geofence triggering performance on my test devices:
> 
> * Nexus 4 @ 4.4.4
> * Nexus 5 @ 6.0.1
> * Motorola Moto G @ 6.0.0
> * Google Pixel @ 10
> * Google Pixel 3a @ 12
> * Samsung Galaxy S20 FE @ 11.0.0
> * Samsung J @ 6.0.1
> * Samsung A510 @ 8.0.0
> * Huawei P20 Lite (ANE-LX3) @ 8.0.0
> * XIAOMI MI A2 Lite @ 10.0.0
> * Nokia TA-1027 @ 8.0.0
> * OnePlus A5010 @ 9.0.0

Okay, how many geofencing was the test run? Because today we are waiting for the test with 1000 geofences. Last week I did the test with 35 geographic fences with alert, cell phone overheated.

**Comment by christocracy** [comment]
Have you applied the suggestions to your device settings at http://dontkillmyapp.com?  YES OR NO?

**Comment by wellson-fleetdesk** [comment]
Yes

**Comment by wellson-fleetdesk** [comment]
Set  in project ->  locationUpdateInterval: 60000

**Comment by wellson-fleetdesk** [comment]
> > o celular superaqueceu e o GPS parou de funcionar e voltou.
> 
> Você está usando um insanamente rápido `locationUpdateInterval: 0`, que diz ao plug-in para registrar os locais o mais rápido que o seu dispositivo puder.

Definir no projeto -> locationUpdateInterval: 60000
