### ISSUE TITLE
Why the minimal radius of Geofence is 200m? Is it unnecessarily too big for small-scope projects? 

### ISSUE THREAD

**Issue by pflee2002** [transistorsoft/flutter_background_geolocation#621]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It's a limitation of the native apis.
