### ISSUE TITLE
Background_geolocation's url (for location uploading)

### ISSUE THREAD

**Issue by pflee2002** [transistorsoft/flutter_background_geolocation#622]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
Is it possible to dynamically turn on/off  URL for location uploading when the system is on the fly. My scenario is to let users decide if they wish to upload their real-time locations. You say using your url method is better than our own http request but is your method dynamic or just set once when the app launches.

**Comment by christocracy** [comment]
There a number of way to do this using .setConfig.
- simply set `url` to empty string `""`
- however that won't prevent locations being inserted to SQLITE (removed with `.destroyLocations()`.  See api docs Config.persistMode.

**Comment by pflee2002** [comment]
Thanks, is it possible to specify a port like "https://192.168.1.1:80".

**Comment by christocracy** [comment]
> possible to specify a port like 

Yes, of course.
