### ISSUE TITLE
More URL questions

### ISSUE THREAD

**Issue by pflee2002** [transistorsoft/flutter_background_geolocation#623]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
Is it possible place a url like "https://192.168.1.1:8080"? 
also, could you please confirm if my understanding is correct? 
thanks
                        params: {"user_id": 1234},
                        headers: {"Authorization": "Basic my-secret-key"},<--"password"?**_****
                        extras: {"agent_id": '$agentId', 'trip_id': '$tripId'},<--additional** information the app can send out ?** 
</details>

**Comment by pflee2002** [comment]
Is it possible place a url like "https://192.168.1.1:8080"?
also, could you please confirm if my understanding is correct?
thanks
params: {"user_id": 1234},
headers: {"Authorization": "Basic my-secret-key"},<--"password"?_****
extras: {"agent_id": '$agentId', 'trip_id': '$tripId'},<--additional information the app can send out ?**

**Comment by christocracy** [comment]
Yes

**Comment by pflee2002** [comment]
about the location and geofence events? Can these two types of events (location vs. geofence enter/exit/dwell) be reported at the same time? I use background. start() but seems no geofence events are being captured. 

Thanks

**Comment by christocracy** [comment]
> Can these two types of events (location vs. geofence enter/exit/dwell) be reported via http event at the same time?

Yes.

**Comment by pflee2002** [comment]
thanks. I didn't succeed. I use backgroundgeolocation.start() and used.
"bg.BackgroundGeolocation.onGeofence(_onGeofence)" but it seems no geofence
can be captured anye geofence events as I entered a predefined geofence.

The function of "_onGeofence"
  void _onGeofence(bg.GeofenceEvent event) {
    String identifier = event.identifier;
    String action = event.action;
    Map<String, dynamic> extras = event.extras;
    bg.Location location = event.location;
    //To determine if a trip ID should be automatically added on;
    if (event.action == "ENTER") {
....

**Comment by christocracy** [comment]
This post is about the "url".

For problems with geofencing, open a new issue.  Do not ignore the issue template as you did here in this issue.
