### ISSUE TITLE
how to know if the motion state is manually change to moving.

### ISSUE THREAD

**Issue by nirbar89** [transistorsoft/flutter_background_geolocation#626]
how to know if the motion state is manually change to moving with changePace method. 

## Your Environment
* Plugin version: latest
* Platform: iOS and Android 
* OS version: all
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```

## Expected Behavior
any way to know if the motion state is triggered by BackgroundGeolocation.changePace(true);

## Actual Behavior
there is no way to know.

## Steps to Reproduce

1. add new boolean to location object or BackgroundGeolocation.state
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> there is no way to know.

Yes, there is.  State.isMoving

**Comment by nirbar89** [comment]
But state.isMoving is true when the device is in motion for example if user start running 

it’s not true only when moving is triggers manually. I am wrong?

**Comment by christocracy** [comment]
When the plugin is in the "moving state", where location-services are ON and the plugin is tracking location, State.isMoving is `true`.  It's very simple.

**Comment by nirbar89** [comment]
I know, as I said it doesn’t indicate the the pluguin is manually turn on the location service and change motion.

I only need to know if the motion state was manually change or due user activity change for example start driving.

**Comment by christocracy** [comment]
> I only need to know if the motion state was manually change or due user activity

This makes absolutely no sense.  If it was changed manually, via `changePace(true)` you will know that you did that.

Not interested.
