### ISSUE TITLE
On Terminating the app in iOS, It kills the app while working perfectly in android + Plus can we provider heartbeat function to iOS?

### ISSUE THREAD

**Issue by anmolbindra10** [transistorsoft/flutter_background_geolocation#627]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
That's correct.  And when the iOS device continues to move about 200 meters, the OS automatically relaunches the app in the background and tracking resumes. Read the api docs Config.stopOnTerminate for more information.

**Comment by christocracy** [comment]
For iOS heartbeat, read the api docs Config.heartbeatInterval.

I suspect you're not reading the api docs at all.
