### ISSUE TITLE
Speed so quickly changed - not working well

### ISSUE THREAD

**Issue by erayhamurlu** [transistorsoft/flutter_background_geolocation#631]
My Environment--
Plugin version: ^2.1.0
Platform: iOS or Android
OS version: 14
Device manufacturer / model: Iphone6s / Iphone11 / SamsungJ6+

1.Request speed 25.14 m/s
2.Request speed 64.74 m/s
Problem: Speed so quickly changed. those between them difference just 6 seconds.

{s:8:"Latitude";d:39.63237136112687;s:9:"Longitude";d:27.638812715595698;s:5:"Speed";d:25.14;s:12:"ActivityType";s:10:"in_vehicle";s:18:"ActivityConfidance";i:100;s:8:"Odometer";d:365250.1;s:7:"Battery";d:0.18000000715255737;s:8:"DeviceId";s:36:"";}-2021-08-27 09:59:45

{s:8:"Latitude";d:39.63121101729537;s:9:"Longitude";d:27.632398316662414;s:5:"Speed";d:64.74;s:12:"ActivityType";s:10:"in_vehicle";s:18:"ActivityConfidance";i:100;s:8:"Odometer";d:366488.4;s:7:"Battery";d:0.18000000715255737;s:8:"DeviceId";s:36:"";}-2021-08-27 09:59:51

**Comment by christocracy** [comment]
Speed is provided directly by the device's gps chip.  The plugin has no control over reported speed.
