### ISSUE TITLE
Refresh token without the Bearer prefix key

### ISSUE THREAD

**Issue by andreadelfante** [transistorsoft/flutter_background_geolocation#633]
## Your Environment
* Plugin version: 4.2.0
* Platform: iOS
* OS version: All
* Device manufacturer / model: both simulators and devices
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale it-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
  backgroundPermissionRationale: permissionRationale,
  desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 300.0,
  //meters
  stopOnTerminate: false,
  startOnBoot: true,
  debug: kDebugMode,
  enableHeadless: true,
  preventSuspend: true,
  logLevel: kDebugMode ? Config.LOG_LEVEL_VERBOSE : Config.LOG_LEVEL_OFF,
  reset: true,
  autoSync: true,
  url: "${config.baseUrl}/set_coordinates",
  method: 'POST',
  httpRootProperty: '.',
  locationTemplate: '{"lat": <%=latitude%>,"lng": <%=longitude%>}',
  geofenceTemplate: '{"lat": <%=latitude%>,"lng": <%=longitude%>}',
  authorization: Authorization(
    strategy: Authorization.STRATEGY_JWT,
    accessToken: user.accessToken,
    refreshToken: user.refreshToken,
    refreshUrl: "${config.baseUrl}/refresh_token",
    refreshPayload: {
      "refresh_token": "Bearer {refreshToken}",
      "grant_type": "refresh_token",
    },
  ),
),
```

## Expected Behavior

When the refreshUrl endpoint is called, server side we should receive a refresh token with the Bearer prefix key.

## Actual Behavior

Server side we get only the JWT value, which is invalid for us. The plugin strips out the Bearer prefix key even if I specify it in the Authorization field `refreshToken`.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2021-09-01 10:15:29,667  root  140625976720712 DEBUG: Refresh token with: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyYV9pZCI6NSwicnVfaWQiOjV9.EWyr8WU_Rj17NyKzEUaUh4uS_Wa0RAH4oyh59mOu8lc'
```

</details>

**Comment by christocracy** [comment]
Testing on Android-only currently:

```dart
bg.BackgroundGeolocation.ready(bg.Config(
  reset: true,
  authorization: bg.Authorization(
    strategy: bg.Authorization.STRATEGY_JWT,
    accessToken: token.accessToken,
    refreshToken: token.refreshToken,
    refreshUrl: "${ENV.TRACKER_HOST}/api/refresh_token",
    refreshPayload: {
      'refresh_token': 'Bearer {refreshToken}'  // <------- Added Bearer prefix.
    }
  )
));
```

At my Node JS server, I observe the posted *urlencoded* `FORM` that the plugin POSTed:

```bash
POST /api/test/status/401 401
********* req.body:  { 
  refresh_token: 'Bearer b89a6e4fecca42fae0db839079344ed0' 
}
```

I observe that the `Bearer` prefix is indeed included in the FORM POST.

Inspecting the *Java* code which renders the `refresh_token` FORM data:

```java
private static final String REFRESH_TOKEN_TEMPLATE  = "{refreshToken}";
.
.
.
if (value.contains(REFRESH_TOKEN_TEMPLATE)) {
    // replace {refreshToken} with actual refreshToken value.
    value = value.replace(REFRESH_TOKEN_TEMPLATE, mRefreshToken);
}
```

This *Java* code above is essentially the same as the *Javascript* `String.replace`:

![](https://dl.dropbox.com/s/0ao3mq6lm8sdj3y/Screen%20Shot%202021-09-01%20at%2010.34.50%20AM.png?dl=1)

**Comment by andreadelfante** [comment]
Hi, thanks for the quick response. After a more accurate test I get the error only on iOS. I'll edit the issue.

Maybe the refreshToken template is not replaced with the correct value on the iOS side of the plugin??

**Comment by christocracy** [comment]
Now that you've provided more specific information that this applies to *iOS only*, I investigate iOS.

**Comment by christocracy** [comment]
Where `value` looks like `"Bearer {refreshToken}"` I found the iOS code was doing this:
```obj-c
value = _refreshToken;
```
Instead of this:
```obj-c
value = [value stringByReplacingOccurrencesOfString:PAYLOAD_REFRESH_TOKEN withString:_refreshToken];
```

Fix is released to version `4.2.3` now.

**Comment by andreadelfante** [comment]
Hi @christocracy , i think there is a regression with the latest version on iOS platform

**Comment by christocracy** [comment]
> i think there is a regression with the latest version on iOS platform

This is true.  I have no idea how this happened.  I'm due to push a new version today or tomorrow.

**Comment by christocracy** [comment]
Can you please try installing from `master` branch before I publish?

```
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
```

**Comment by andreadelfante** [comment]
> Can you please try installing from `master` branch before I publish?
> 
> ```
> dependencies:
>   flutter_background_geolocation:
>     git:
>       url: https://github.com/transistorsoft/flutter_background_geolocation.git
> ```

Now on iOS is working correctly! Thank you!
