### ISSUE TITLE
Correct Exception Handling

### ISSUE THREAD

**Issue by nblum37** [transistorsoft/flutter_background_geolocation#637]
## Your Environment
* Plugin version: 4.2.3
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung A21
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)

* Plugin config: See below
```dart <-- Syntax highlighting: DO NOT REMOVE -->
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;

import '../utils/locator.dart';
import 'api.dart';
import 'auth_service.dart' as auth;

Future<Map<String, dynamic>?> getLocationMap({bool runSafe = false}) async {
  print('Get location');
  Map<String, dynamic> locationMap = {};

  bg.State state = await bg.BackgroundGeolocation.state;
  if (!state.enabled && runSafe) return {};

  bg.Location? position;
  try {
    position = await bg.BackgroundGeolocation.getCurrentPosition(
      timeout: 5, // 5 second timeout to fetch location
      maximumAge: 600000, // Accept the last-known-location if not older than 60 .
      desiredAccuracy: 50, // Try to fetch a location with an accuracy of `50` meters.
      samples: 3, // How many location samples to attempt.
    );
  } catch (e, st) {
    print('Unable to get current location: $e, $st');
    return null;
  }

  if (position.mock ?? false) throw Exception('Position is mocked');

  locationMap['lat'] = position.coords.latitude;
  locationMap['lon'] = position.coords.longitude;
  locationMap['alt'] = position.coords.altitude;
  locationMap['acc'] = position.coords.accuracy;
  locationMap['vel'] = position.coords.speed;
  locationMap['hea'] = position.coords.heading;

  print('    $position');
  return locationMap;
}

Future<void> startBackgroundLocationService() async {
  String? token = await locator<Storage>().read(key: 'accessToken');
  token ??= '';
  if (token == '') {
    auth.checkAuthState();
  }

  ////
  // 1.  Listen to events (See docs for all 12 available events).
  //

  // Fired whenever a location is recorded
  bg.BackgroundGeolocation.onLocation((bg.Location location) {
    print('[location] - $location');
  }, (bg.LocationError locationError) {
    print('[location-error] - $locationError');
  });

  // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
  bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
    print('[motionchange] - $location');
  });

  // Fired whenever the state of location-services changes.  Always fired at boot
  bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
    print('[providerchange] - $event');
  });

  ////
  // 2.  Configure the plugin
  //

  bg.BackgroundGeolocation.ready(bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 50.0,
          stopOnTerminate: true,
          startOnBoot: true,
          debug: false,
          url: restApi.url + restApi.endpointLocation,
          headers: {'Authorization': 'Bearer $token'},
          maxRecordsToPersist: 1,
          logLevel: bg.Config.LOG_LEVEL_INFO))
      .then((bg.State state) {
    if (!state.enabled) {
      ////
      // 3.  Start the plugin.
      //
      bg.BackgroundGeolocation.start();
    }
  });
}

Future<void> stopBackgroundLocationService() async {
  await bg.BackgroundGeolocation.stop();
}
```

## Expected Behavior

The exception of the package in the function getLocationMap gets caught and the attached debugger does not run into a breakpoint during developing in debug mode.

## Actual Behavior

The debugger run into an exception breakpoint even though the Exception of the plugin should be caught in getLocationMap. There is an additional Exception raised somewhere deeper in the plugin, causing the debugger to pause the app.

## Steps to Reproduce

1. Disable GPS at the phone
2. Run the App with the debugger attached
3. Call getLocationMap

## Context

We currently face the problem that the plugin (probably the nativ code part) causes debugger exception even though they would be catched in the proved code file (usually in the message_codes.dart file). The problem is, that this exception leads the debugger to pause the app causing some other critical services to timeout, if there is e.g. no GPS signal at the office desk and the exception breakpoints are activated. At this point it's not able to continue debugging with the main task.
Is there any solution to catch also the internal exception? Or do you have any idea how to improve the currently impaired debugging process of the app? The current quick-fix solution is to increase these timeouts to have enough time to resume the app, but that feels like a very ugly solution and disable testing of the correct timeout behavior of the other tasks.

Thank you for the support!

![Bildschirmfoto 2021-09-10 um 10 40 30](https://user-images.githubusercontent.com/82163574/132826201-ef8bc86b-a336-453a-a723-5fcd191f4e5f.png)

![Bildschirmfoto 2021-09-10 um 10 44 40](https://user-images.githubusercontent.com/82163574/132826717-e2e425b8-c09c-404d-93a2-4b27afd1e297.png)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
```
</details>

**Comment by christocracy** [comment]
See *Error Codes* for *error code `1`* at API docs [getCurrentPosition](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/getCurrentPosition.html)

**Comment by nblum37** [comment]
Thank you! But the question is not about what the error means but more how to catch the error properly to avoid the debugger to get stuck at the exception. Try&Catch around getCurrentPosition is, as the sample shows, not enough.

**Comment by christocracy** [comment]
>but more how to catch the error properly to avoid the debugger to get stuck at the exception

I don't know.
