### ISSUE TITLE
backgroundPermissionRationale - does not work. Shows only the standard message.

### ISSUE THREAD

**Issue by AlexKenbo** [transistorsoft/flutter_background_geolocation#640]
## Your Environment
* Plugin version: ^4.3.0
* Platform: Android
* OS version: 10
* Device manufacturer / model: android-arm64 emulator
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale
    ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.BackgroundGeolocation.ready(
    bg.Config(
      httpRootProperty: 'locations',
      locationTemplate:
          '{"lat":<%= latitude %>,"lng":<%= longitude %>, "time": "<%= timestamp %>", "batteryLevel": "<%= battery.level %>"}',
      batchSync: true,
      autoSyncThreshold: 3,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 60.0,
      stopOnTerminate: false,
      startOnBoot: true,
      reset: true,
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        'titleWhenNotEnabled': 'You, location-services not enabled',
        'titleWhenOff': 'You, location-services OFF',
        'instructions': 'You must enable "Always" in location-services, buddy',
        'cancelButton': 'Cancel',
        'settingsButton': 'Settings'
      },

      schedule: ['1-7 07:00-24:00'],
      url: 'https://api.logistica.com/tracking/addList',
      headers: {"Authorization": 'Bearer <FAKE_TOKEN>'},
      logLevel: bg.Config.LOG_LEVEL_ERROR,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow ZAS Driver to access to this device's location in the background, when the app is closed or not in use.?",
          message:
              "This app collects location data to enable you to receive orders near you, even when the app is closed or not in use. To track your activity in the background, enable location permission {backgroundPermissionOptionLabel}",
          positiveAction: "Change to Allow all the time",
          negativeAction: "Cancel"),
    ),
  ).then((bg.State state) {
    if (!state.enabled) {
      ////
      // 3.  Start the plugin.
      //
      bg.BackgroundGeolocation.start().then((value) {
        print('started!');
      });
    }
  });
```

## Expected behavior
At the request of Google Play, the following message should appear in the permission window for collecting coordinates:
              "This app collects location data to enable you to receive orders near you, even when the app is closed or not in use. To track your activity in the background, enable location permission {backgroundPermissionOptionLabel}",

## Actual Behavior
<img width="275" alt="Снимок экрана 2021-09-21 в 21 26 30" src="https://user-images.githubusercontent.com/14903011/134228033-7752b9bf-4d04-4be3-bc01-5011f06656d1.png">

## Actions to play
<! --- reproduce this problem; enable code to play if needed ->
1. Added backgroundPermissionRationale to the config
2. Removed the previous application
3. Launched the application

## Context
Below code runs setConfig:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.setConfig(
        bg.Config(
          headers: {
            "Authorization": await tokenInterceptor.getToken(),
          },
        ),
      );
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The `backgroundPermisionRationale` appears only on *Android 11* with `targetSdkVersion 30` (or higher).

**Comment by AlexKenbo** [comment]
Google Play require us to display this message.

What is the best way for us to do this? By own means before starting BG?

> Prominent disclosure not found
> Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.
> 
> Please add a prominent disclosure before the runtime permission.
> 
> Remember, your prominent disclosure must:
> Appear before your app’s location runtime permission.
> Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
> Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

**Comment by AlexKenbo** [comment]
> The `backgroundPermisionRationale` appears only on _Android 11_ with `targetSdkVersion 30` (or higher).

Google Play require us to display this message.

What is the best way for us to do this? By own means before starting BG?

> Prominent disclosure not found
> Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.
> 
> Please add a prominent disclosure before the runtime permission.
> 
> Remember, your prominent disclosure must:
> Appear before your app’s location runtime permission.
> Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
> Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

**Comment by christocracy** [comment]
>What is the best way for us to do this? By own means before starting BG?

You are responsible for showing your own "prominent disclosure".  See [my blog](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353)

`Config.backgroundPermissionRationale` is **not** "prominent disclosure".
