### ISSUE TITLE
 About the plugin's operation in offline mode.

### ISSUE THREAD

**Issue by wellson-fleetdesk** [transistorsoft/flutter_background_geolocation#642]
## Your Environment
* Plugin version: flutter_background_geolocation version 1.9.3, license adquired by Fleetdesk
* Platform: iAndroid
* OS version:
* Device manufacturer / model: Redmi Note 8 PRO
* Flutter info (`flutter doctor`):
* Plugin config:

## Expected Behavior

Hello I would like to clear a question, about the offline plugin it needs some authentication to work offline. I have the plugin license in version 1.9.3.

**Comment by christocracy** [comment]
> it needs some authentication to work offline.

No.  This plugin was explicitly designed to work in earthquakes and hurricanes where the cell network is assumed to be destroyed (ie offline).
