### ISSUE TITLE
HeadlessEvent NOTIFICATIONACTION

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#643]
## Your Environment
* Plugin version: 4.3.0
* Platform:  Android
* OS version: 10
* Device manufacturer / model: SAmsumg s10 plus
* Flutter info (`flutter doctor`): correct all

I have placed a button in the permanent notification, it works when the application is in the foreground.
But when I close the application I am listening to background

```
 switch (headlessEvent.name) {
    case bg.Event.NOTIFICATION ACTION:
      var data = headlessEvent.event;
      print (data);
      break;
```

but it returns me this result:

`� --> [HeadlessEvent name: notificationaction, event: null]`

I would like it to happen as it happens when it is in the foreground.

```
bg.BackgroundGeolocation.onNotificationAction((buttonId) {
        print('[onNotificationAction] - $buttonId');
        switch (buttonId) {
          case 'notificationButtonFoo':
          break:
```

**Comment by christocracy** [comment]
Please don't ignore the issue template.  Particularly the "*Plugin Version*".

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************
-->


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by flutteresbolivia** [comment]
> I have placed a button in the permanent notification, it works when the application is in the foreground. But when I close the application I am listening to background
> 
> ```
>  switch (headlessEvent.name) {
>     case bg.Event.NOTIFICATION ACTION:
>       var data = headlessEvent.event;
>       print (data);
>       break;
> ```
> 
> but it returns me this result:
> 
> `� --> [HeadlessEvent name: notificationaction, event: null]`
> 
> I would like it to happen as it happens when it is in the foreground.
> 
> ```
> bg.BackgroundGeolocation.onNotificationAction((buttonId) {
>         print('[onNotificationAction] - $buttonId');
>         switch (buttonId) {
>           case 'notificationButtonFoo':
>           break:
> ```

**Comment by flutteresbolivia** [comment]
> Please don't ignore the issue template. Particularly the "_Plugin Version_".
> 
> * WARNING:  DO NOT IGNORE THIS TEMPLATE
> 
> -->
> 
> ## Your Environment
> * Plugin version:
> * Platform: iOS or Android
> * OS version:
> * Device manufacturer / model:
> * Flutter info (`flutter doctor`):
> * Plugin config:
> 
> ```dart
> PASTE_YOUR_CODE_HERE
> ```
> 
> ## Expected Behavior
> ## Actual Behavior
> ## Steps to Reproduce
> 
> ## Context
> ## Debug logs
> Logs


@christocracy  that's it, sorry

**Comment by flutteresbolivia** [comment]
@christocracy 
or maybe you can pass parameters to the button?

**Comment by flutteresbolivia** [comment]
help pls U.u

**Comment by christocracy** [comment]
The problem is likely within the native library.  If so, a fix will come next week.

**Comment by flutteresbolivia** [comment]
> The problem is likely within the native library. If so, a fix will come next week.

and you could somehow pass parameters to the button, it would be great if you were like that!

**Comment by christocracy** [comment]
I see the problem.  It's an easy fix.  Try testing the fix with branch `headless-notificationaction`.

*pubspec.yaml*
```yaml
dependencies:
  flutter_background_geolocation:
    git: 
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: headless-notificationaction
```

**Comment by flutteresbolivia** [comment]
> I see the problem. It's an easy fix. Try testing the fix with branch `headless-notificationaction`.
> 
> _pubspec.yaml_
> 
> ```yaml
> dependencies:
>   flutter_background_geolocation:
>     git: 
>       url: https://github.com/transistorsoft/flutter_background_geolocation.git
>       ref: headless-notificationaction
> ```

@christocracy 
Thank you so much!
i will try it
