### ISSUE TITLE
SET CONFIG: does not update in real time Headless and foreground

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#645]
## Your Environment
* Plugin version: 4.3.0
* Platform:  Android
* OS version: 10
* Device manufacturer / model: SAmsumg s10 plus
* Flutter info (`flutter doctor`): correct all

when I refresh with RefreshIndicator
this is my configuration

I want to update only the notification data

```
 await bg.BackgroundGeolocation.setConfig(bg.Config(
          notification: bg.Notification(
            smallIcon: "drawable/ic_launcher_notification",
            priority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
            sticky: true,
            title:
                user.profile?.firstName?.trim() != null ? '${user.profile?.firstName?.trim()} tienes una operación en curso' : "Operación en curso",
            strings: {'notificationButtonFoo': taskCurrent.name.toString()},
            layout: "my_notification_layout",
            actions: ["notificationButtonFoo"],
            text: 'Recuerda completar todas tus tareas.',
          ),
        ));
```
I want to update these:

> since at some point the user will not have tasks or will have some, and I want to remove the button or show him with the name of the task that he has.

```
strings: {'notificationButtonFoo': taskCurrent.name.toString()},
  layout: "my_notification_layout",
  actions: ["notificationButtonFoo"],
```

since I need to update the task every time I change or actuate the user, I just want to change the name.

in the console it throws me this log:
`D/TSLocationManager(28667): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [notification, notification.strings]
`

**Comment by flutteresbolivia** [comment]
@christocracy could you see it or is there no solution?

**Comment by christocracy** [comment]
Try this again after installing branch as directed in #643.
