### ISSUE TITLE
Complaints about deprecations throughout sample apps

### ISSUE THREAD

**Issue by pbelbin** [transistorsoft/flutter_background_geolocation#647]
## Your Environment
* Plugin version: 4.3.0
* Platform: iOS or Android both
* OS version: macOS 11.2.3
* Device manufacturer / model: doesn't matter
* Flutter info (`flutter doctor`): 
```
flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (1 available)

• No issues found!
```

* Plugin config: not relevant, since this is within the source tree.* 

## Expected Behavior
No deprecated code should be in the codebase

## Actual Behavior
Warnings throughout regarding deprecations (at least in the examples)

```dart
@override
  Widget build(BuildContext context) {
    const labelStyle = TextStyle(color: Colors.blue, fontSize: 16.0);

    return new Scaffold(
        appBar: new AppBar(
            brightness: Brightness.light,   <--- complaint that it's deprecated
            leading: IconButton(
```

![Screen Shot 2021-10-03 at 9 20 36 PM](https://user-images.githubusercontent.com/10079005/135784243-9ca6bd5a-bd11-414b-92b4-46e3dd591913.png)

## Steps to Reproduce

1. Open the code using VSCode with flutter 2.5.2 
2. Examine the 'Problems' pane of VSCode, you'll see a lot of complaints about deprecations

## Context
I'm trying to build the sample apps.

## Debug logs
not needed, this is in the editor, not a runtime problem.

**Comment by christocracy** [comment]
Is there some particular warning you'd like to show?

**Comment by christocracy** [comment]
I see your little screenshot now.

The /example UI code hasn't been looked at in a while.

Those warnings are not related to the plugin api itself.

The /example code will be updated soon.

**Comment by pbelbin** [comment]
Has the 'will be updated soon' happened?

**Comment by pbelbin** [comment]
It's been a while since this issue was opened.  Has the concern been addressed?

**Comment by pbelbin** [comment]
Flutter has moved on to 3.3, are there other updates that should be expected too, as a result?
