### ISSUE TITLE
Background location not working in battery saving mode.

### ISSUE THREAD

**Issue by Mmisiek** [transistorsoft/flutter_background_geolocation#648]
## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung 10
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
        bg.BackgroundGeolocation.ready(bg.Config(
                desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
                distanceFilter: _gpsInterval,
                disableElasticity: true,
                stopOnTerminate: false,
                startOnBoot: false,
                debug: false,
                logLevel: bg.Config.LOG_LEVEL_DEBUG,
                reset: true))
```

## Expected Behavior
I tested plugin in two modes with Battery Saving on and off.
'I expected to get updated about location in both modes, or force/inform user about battery saving mode.
Some apps like MapMyRun shows such dialog and forces used to turn Battery Saving off.

## Actual Behavior
When app goes to background with Battery Saving off, locations are updated.
If Baterry Saving is on the location update do not trigger. 

## Steps to Reproduce

1. 
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See the api docs event onPowerSaveChange

**Comment by Mmisiek** [comment]
Thanks, I need to check this flag and show dialog accordingly so user turns Power Saving off.
