### ISSUE TITLE
Sent timestamp in location template

### ISSUE THREAD

**Issue by tengl** [transistorsoft/flutter_background_geolocation#655]
## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung Galaxy Tab  A7 10.1
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, 2.5.1, on Pop!_OS 21.04 5.13.0-7614-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.61.0)
[✓] Connected device (1 available)
No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.setConfig(bg.Config(
        url: "theurl",
        autoSync: true,
        httpRootProperty: ".",
        locationTemplate: '''{ 
        "sessionId": $sessionId,
        "latitude": <%= latitude %>,
        "longitude": <%= longitude %>,
        "accuracy": <%= accuracty %>,
        "recordedAt": "<%= timestamp %>,
        "sentAt": "<%= sent_timestamp %>
        }
      '''));
```

## Feature request
Is there a way to get the time when the location is sent from the client? 

E.g. a `sent_timestamp` template tag like in the template above. Since the recorded (GPS) position timetamp and sent time doesn't have to be the the same (can be stored in SQLite for a while etc.) it can be useful to have the timestamp when the requests is sent. 

Currently I set it on the server but it would be useful on the client as well. When a device is not moving we get the same timestamp all the time, even in heartbeats and even if we call `getCurrentPosition()`. That is not entirely bad, since it is in fact the same position. But the server does not know that the position is still the same without an up to date timestamp. 

I've seen `timestampMeta` but I'm not sure when that time is recorded and it is an object, not a single timestamp.

**Comment by vishal767** [comment]
I've also seen `timestampMeta` , Please explain how it is stored and what it means , since its a object
