### ISSUE TITLE
Flutter plugin crashes when iOS app is in background.

### ISSUE THREAD

**Issue by imogavsp** [transistorsoft/flutter_background_geolocation#657]
Flutter plugin crashes in production when iOS app is in background. 
We do not have other details or logs since we weren't able to reproduce it.
We're using flutter dart package "flutter_background_geolocation: 1.10.1"

Here is the Google Crashlytics reporting for this issue:

**Fatal Exception: NSInvalidArgumentException
Invalid number value (infinite) in JSON write**

**Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x129708 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  Foundation                     0x1bfab8 _writeJSONNumber
3  Foundation                     0x1c085c ___writeJSONObject_block_invoke
4  CoreFoundation                 0x8da18 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
5  CoreFoundation                 0x34f0 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]
6  Foundation                     0x1bfd5c _writeJSONObject
7  Foundation                     0x1c085c ___writeJSONObject_block_invoke
8  CoreFoundation                 0x8da18 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
9  CoreFoundation                 0x21b8 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
10 Foundation                     0x1bfd5c _writeJSONObject
11 Foundation                     0x1bdd98 -[_NSJSONWriter dataWithRootObject:options:]
12 Foundation                     0x67558 +[NSJSONSerialization dataWithJSONObject:options:error:]
13 Runner                         0x277bc8 -[TSLocation toJson:]
14 Runner                         0x27c23c -[LocationDAO create:error:]
15 Runner                         0x273fd4 __37-[TSLocationManager persistLocation:]_block_invoke
16 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release
17 libdispatch.dylib              0x481c _dispatch_client_callout
18 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain
19 libdispatch.dylib              0xcc00 _dispatch_lane_invoke
20 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread
21 libsystem_pthread.dylib        0x37a4 _pthread_wqthread
22 libsystem_pthread.dylib        0xa74c start_wqthread**

**Comment by LocaTrackGitHub** [comment]
Like I said on a test device so its hard to give you more info latest version of you plugin he has a iPhone 12 Pro. My flutter doctor has no issues and it does not crash on testflight it just does not track the whole route accurately and I set it from high to navigate to see if that will make a difference.
