### ISSUE TITLE
[Question] How to create a persistent notification on iOS as well?

### ISSUE THREAD

**Issue by ehhc** [transistorsoft/flutter_background_geolocation#66]
Hi,
i configured the plugin to show a persistent notification on android (by setting it to be a foreground service). Alas, there is no such notification on iOS. 
Is it possible to get a persistent notification on iOS while the plugin works as well?
Or do i have to use a different plugin to create such a notification myself?

Thanks

**Comment by christocracy** [comment]
>i configured the plugin to show a persistent notification on android

Android *requires* this persistent notification for its foreground service.  A persistent notification is shown, regardless if you configure the `notification` or not (it will use default text).

iOS has no such requirement of persistent notification.

You should have to use a 3rd party library to do that.

**Comment by ehhc** [comment]
okay. thanks for the quick answer :)
