### ISSUE TITLE
AutoSyncCallback instead of url

### ISSUE THREAD

**Issue by a7mdragab** [transistorsoft/flutter_background_geolocation#664]
Hello,
I am suggesting making AutoSyncCallback instead of url. This will be more familiar for custom usage and easier merging with current codes.
`
url: localhost   **remove

autoSyncCallback: (Location loc){
     //My code to send the request or svr it locally or do anything
}
`
Thanks

**Comment by christocracy** [comment]
What are you trying to do that you can use existing events for this, such as `onLocation` event?

**Comment by a7mdragab** [comment]
> What are you trying to do that you can use existing events for this, such as `onLocation` event?

That is right and also the url strategy can be done with it.
but they say in the docs it is recommended to use autosync with url to get the best results

**Comment by christocracy** [comment]
Why don't you want to use the plug-in's built-in http service?

**Comment by a7mdragab** [comment]
> Why don't you want to use the plug-in's built-in http service?

I want to use web-sockets. Can I?

**Comment by christocracy** [comment]
You're free to do whatever in your own event-listeners.

Good luck maintaining your connection.  I have nothing to offer in support for sockets.

**Comment by a7mdragab** [comment]
> You're free to do whatever in your own event-listeners.
> 
> Good luck maintaining your connection. I have nothing to offer in support for sockets.

Thanks for your effort
