### ISSUE TITLE
Android 12 MotionChange Event Problem

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#666]
My phone recently updated to Android 12 and now the MotionChange event reports sporadically and inaccurately.

## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Google Pixel 3
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: "Allow {applicationName} to access to this device's "
                  "location in the background?",
              message:
                  'In order to track your activity while the screen is off or '
                  'while using other apps, '
                  'please enable the "{backgroundPermissionOptionLabel}" '
                  'location permission.',
              positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
              negativeAction: 'Cancel'),
    );
  }
```

## Expected Behavior
Motion change event reports not-still when moving.

## Actual Behavior
The motion change event is very inconsistent after updating to Android 12. This happens in my app and also in the transistorsoft demo app. My app has a Google map control that tilts and rotates as I move. Interestingly, when the motion change event reports "still", the tilt and rotation instantly gets reset even though I am actually still moving 15-20 mph. The tilt and rotation instantly resumes when the motion change event reports something other than "still".  This makes me think this is not actually a problem with your library, but rather an OS problem, but I want to report it just in case you didn't already know about it or you have some info about it that you can share.

![ts_android_12](https://user-images.githubusercontent.com/8699636/140622192-980a4203-90f9-41e9-89af-8889ee13574e.png)

## Steps to Reproduce

1. Run the transistorsoft demo app while riding a bike. 
2. Examine the recorded data in the console.
3.
4.

## Context
Record my activity while biking.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I will try to get the logs if you still want them.
```

</details>

**Comment by christocracy** [comment]
The ActivityRecognition API from Google Play Services is nothing more than a black box with an ON/OFF switch.  The plugin turns it ON and receives events.  

Try rebooting your device.  If that doesn't work, there's nothing you can do but raise an issue with Google.

**Comment by ozzy1873** [comment]
For anyone else encountering this problem, rebooting/reinstalling the app has no effect. This is a problem with the Android 12 ActivityRecognition API.

Closing.

**Comment by christocracy** [comment]
*666* &mdash; The Issue of the Beast.

![](https://www.dropbox.com/s/h4u4m860jagzhmn/Screen%20Shot%202021-11-06%20at%205.41.08%20PM.png?dl=1)

**Comment by ozzy1873** [comment]
LOL!!!
