### ISSUE TITLE
Notification Icon Issue

### ISSUE THREAD

**Issue by zubairehman** [transistorsoft/flutter_background_geolocation#668]
## Your Environment
* Plugin version: ^0.4.1
* Platform: Android
* OS version: 12
* Device manufacturer / model: Google Pixel
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      ////
      // 2.  Configure the plugin
      //
      bg.BackgroundGeolocation.ready(
        bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          foregroundService: true,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          notification: bg.Notification(
            largeIcon:"drawable/app-icon",
            smallIcon: "drawable/app-icon",
          ),
          backgroundPermissionRationale: bg.PermissionRationale(
            title: AppLocalizations.of(context)!
                .translate('home_tv_permission_title')!,
            message: AppLocalizations.of(context)!
                .translate('home_tv_permission_desc')!,
            positiveAction:
                AppLocalizations.of(context)!.translate('home_btn_positive')!,
            negativeAction:
                AppLocalizations.of(context)!.translate('home_tab_cancel')!,
          ),
        ),
      ).then((bg.State state) {
        if (!state.enabled) {
          ////
          // 3.  Start the plugin.
          //
          bg.BackgroundGeolocation.start();
        }
      });
```

## Expected Behavior
The notification icon is not showing on Android 12 devices. However, it works perfectly fine on Android 11 and below devices.

## Actual Behavior
The notification icon is not showing on Android 12 devices.

## Context
I am using a transistor soft plug-in in my application for geo-fencing and background location fetch. The foreground service is working fine but on some devices, the notification icon is not showing up instead, it's showing a grey square. I followed the documentation on how to show a custom icon and pasted my code above. Could you please take a look and let me know what's the issue?

## Debug logs

![mauro](https://user-images.githubusercontent.com/7915601/141723994-684f5a7e-7109-4188-8772-4f370256e151.png)
![zubair](https://user-images.githubusercontent.com/7915601/141724158-263e2c29-eb60-4303-8cd9-0b2171295504.JPEG)
<details>
	<summary>Logs</summary>
</details>

**Comment by christocracy** [comment]
See this:  https://stackoverflow.com/questions/30795431/android-push-notifications-icon-not-displaying-in-notification-white-square-sh
