### ISSUE TITLE
ActivityChangeEvent and isMoving only triggered on new location

### ISSUE THREAD

**Issue by Babwenbiber** [transistorsoft/flutter_background_geolocation#669]
## Your Environment
* Plugin version: 4.3.1
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Pixel 6
* Flutter info (`flutter doctor`): 
<details>
	<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale de-DE)
    • Flutter version 2.5.3 at /Users/frederikfroling/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/frederikfroling/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/frederikfroling/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Pixel 6 (mobile) • 18161FDF6001RL • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

</details>

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            desiredOdometerAccuracy: 10,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0.0,
            stopOnTerminate: true,
            stopOnStationary: false,
            startOnBoot: false,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
```

## Expected Behavior

When I am moving everything works fine. `ActivityChangeEvent` tells me, that I am moving and the last `position.isMoving` is true. 
However, when I am standing still no location is recorded (maybe because `desiredOdometerAccuracy=10`?).
Therefore, no `onActivityChange` and `onMotionChange` is not fired.

## Actual Behavior

I expect, that `onActivityChange` and `onMotionChange` get fired as soon as I stand still.

## Steps to Reproduce

1. Init Plugin as shown above
2. Display current `ActivityChangeEvent` and `isMovingState`
3. Start app and start walking
4. Stop walking and check the display

## Context

Simple display of the state and record of "time in motion" vs. "time standing".

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> get fired as soon as I stand still.

Why do you expect this?  See Config.stopTimeout.

ActivityChange events are fired by the PlayServices api.  The plugin has no control over "when" they fire.

**Comment by Babwenbiber** [comment]
Ok.
So when I want to track the total time tracked vs. the total time STILL, I have to use `changePace` manually in order to have an up to date state of the motion, right?

**Comment by christocracy** [comment]
Have you read the Wiki *Philosophy of Operation*?  The plugin has two states:  *moving* and *stationary*.  The plugin automatically calls `changePace(isMoving)` upon itself when the device is detected to be moving.

You are free to override the automatic behaviour and call `changePace(true|false)` at any time you wish.

**Comment by Babwenbiber** [comment]
I understand that and I read the Wiki.
However, the `stopTime` is in minutes.
Suppose I have a running app and want to track the pace. Of course the time should stop when I am standing still (traffic light or something). One minute of timeout is way to long then.

**Comment by christocracy** [comment]
>Suppose I have a running app and want to track the pace

Running apps  typically have `[Start Workout]` / `[Stop Workout]` buttons, which would execute `.changePace(value)`.

>Of course the time should stop when I am standing still

You don't want the plugin to enter the *stationary* state while "stopped at a traffic light", particularly on iOS, because the OS suspends the app immediately after location-services are turned off.  The device would need to move at least 200 meters before iOS re-awakens your app and tracking resumes.

It's up to your own application code to listen to `onActivityChange` and make your own decisions to start/stop your "timer".

**Comment by Babwenbiber** [comment]
Like I said:
> I expect, that onActivityChange and onMotionChange get fired as soon as I stand still.
I understand now, that `onMotionChange` is a bad way of tracking a timer.
However, `onActivityChange` doesn't get fired either.

**Comment by christocracy** [comment]
I suggest you test on a number of devices.  You'll notice a wide range of behaviour across devices.  The ActivityRecognition API on some devices, like my *Pixel 3a* , is very prompt.  On others, like my *Huawei P20 lite*, it sucks.

**Comment by Babwenbiber** [comment]
Ok, thank you. 
I will test that and see.
Closing this
