### ISSUE TITLE
[Question] How to START the plugin if it's terminated?

### ISSUE THREAD

**Issue by WUKS87** [transistorsoft/flutter_background_geolocation#676]
I added background_fetch (part of flutter_background_geolocation) for Android only, as a background task. It will trigger every 15 minutes. When it triggers I want to do some checks and if the condition is ok to START flutter_background_geolocation again.

But this doesn't seem to work:
`bg.BackgroundGeolocation.start();`

* Plugin version: 4.3.1
* Platform: Android
* OS version: Any
* Device manufacturer / model: Any
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
if (Platform.isAndroid) {
  BackgroundFetch.configure(BackgroundFetchConfig(
    minimumFetchInterval: 15,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    forceAlarmManager: true
  ), (String taskId) async {
    scheduleCustomTask(taskId);
  }, (String taskId) async {
    // This task has exceeded its allowed running-time.
    BackgroundFetch.finish(taskId);
  });

  BackgroundFetch.scheduleTask(TaskConfig(
    taskId: 'com.load-market.task',
    delay: 5000,
    forceAlarmManager: true,
    periodic: true
  ));

  // Register to receive BackgroundFetch events after app is terminated.
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}


void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;
  bool isTimeout = task.timeout;
  if (isTimeout) {
    BackgroundFetch.finish(taskId);
    
    return;
  }
  
  bg.Logger.notice('[BackgroundFetch] Headless event received: $taskId');
  
  scheduleCustomTask(taskId);

  BackgroundFetch.finish(taskId);
}


void scheduleCustomTask(String taskId) async {
  final state = await bg.BackgroundGeolocation.state;
  if (state.enabled) {
    BackgroundFetch.finish(taskId);

    return;
  }

  await Firebase.initializeApp();
  final FirebaseAuth _authTask = FirebaseAuth.instance;
  final FirebaseFirestore _flutterFirestoreTask = FirebaseFirestore.instance;

  if (_authTask.currentUser == null) {
    BackgroundFetch.finish(taskId);

    return;
  }
  
  // check if any tracking is active on task fired
  if (some_condition_check) {
    bg.BackgroundGeolocation.start();
  } else {
    bg.BackgroundGeolocation.stop();
  }

   BackgroundFetch.finish(taskId);
}
```

## Expected Behavior
When background task is triggered I would like to wake up flutter_background_geolocation plugin.

## Actual Behavior
flutter_background_geolocation is not waking up from terminated state.

## Context
The reason I want to have this is because sometimes on Android we lose tracking, main assumption is that Android OS kill the plugin process due to battery restrictions.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by WUKS87** [comment]
@christocracy Can you help me on this one? Thanks

**Comment by christocracy** [comment]
Where are you logs?

**Comment by christocracy** [comment]
See wiki *Debugging*.

**Comment by WUKS87** [comment]
I don't have logs since I can't recreate this app stop on my Android device.
How can flutter_background_geolocation be started after Android OS kills the app (let's say due to battery restrictions, like Samsung)?

**Comment by christocracy** [comment]
> How can flutter_background_geolocation be started after Android OS kills the app (let's say due to battery restrictions, like Samsung)?

There are no software solutions for Android manufacturers that violate the Android api.   http://dontkillmyapp.com.  

I

**Comment by WUKS87** [comment]
But you told me that I can use AlarmManager in 15min schedule in case if app gets terminated.
It's crucial for me to locate user somehow, 15min is ok for Android cases.

**Comment by christocracy** [comment]
If you’re attempting to use AlarmManager to circumvent specific Android manufacturers violation of the Android api as documented at http://dontkillmyapp.com, you are doomed to fail.

**Comment by christocracy** [comment]
The plugin is perfectly capable of continuing to operate if the app is terminated by the OS (see api docs Config.stopOnTerminate).  

However, there are no software solutions to manufacturers who violate the Android api by preventing foreground services from operating.
