### ISSUE TITLE
Play Store - Multiple ANR

### ISSUE THREAD

**Issue by MickaelHrndz** [transistorsoft/flutter_background_geolocation#678]
## Your Environment
* Plugin version: 4.3.0

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          startOnBoot: true,
          logLevel: bg.Config.LOG_LEVEL_ERROR
```
* Platform: Android

First phone :
* OS version: 10 (SDK 29)
* Device manufacturer / model: Samsung Galaxy S10+

Second phone :
* OS version: 11 (SDK 30)
* Device manufacturer / model: Xiaomi Mi 11 Pro

## Expected Behavior
No ANR

## Actual Behavior
Multiple ANR on both devices

## Steps to Reproduce
It's not clear what causes the issue and how to reproduce it. It happens sometimes when starting the app, sometimes after a while.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Happened 10 times :
executing service com.redacted.name/com.transistorsoft.locationmanager.service.TrackingService

Happened 4 times (only on the Samsung) :
Broadcast of Intent { act=TERMINATE_EVENT flg=0x14 cmp=com.redacted.name/com.transistorsoft.locationmanager.scheduler.ScheduleAlarmReceiver (has extras) }
```

</details>

**Comment by christocracy** [comment]
Duplicate #549

**Comment by MickaelHrndz** [comment]
Could you reopen that one then please ? As I mentioned, this is happening with the v4.3.0.

**Comment by christocracy** [comment]
This is not a plugin issue.  See the linked issue for details about using Android StrictMode to determine where your app is blocking the main-thread.

**Comment by MickaelHrndz** [comment]
Alright, I'll look into it, thank you for the quick answer !
