### ISSUE TITLE
Android build getting HTTP 502 (Bad Gateway)

### ISSUE THREAD

**Issue by kokofoot** [transistorsoft/flutter_background_geolocation#679]
Received the following error when doing an Android build:

```
[flutter_background_geolocation] Purging debug resources in release build
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
What went wrong:                                                      
Could not determine the dependencies of task ':app:collectReleaseDependencies'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tslocationmanager:+.          
     Required by:                                                       
         project :app > project :flutter_background_geolocation         
      > Failed to list versions for com.transistorsoft:tslocationmanager.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/transistorsoft/tslocationmanager/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/transistorsoft/tslocationmanager/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tslocationmanager/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

## Your Environment
* Plugin version: 1.10.3
* Platform: Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.6.1 20G224 darwin-x64, locale en-AU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Build should succeed

## Actual Behavior
Build failed with the exception in description

## Steps to Reproduce

1. Run command "flutter build appbundle --no-shrink"

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by kokofoot** [comment]
@christocracy here is android/build.gradle

`buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 30
        targetSdkVersion    = 30
        appCompatVersion    = "1.0.2"           
        playServicesLocationVersion = "17.0.0"  
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by christocracy** [comment]
Please learn to use [Syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by kokofoot** [comment]
Thanks @christocracy , hopefully it looks better now.

**Comment by christocracy** [comment]
First-of-all, have you heard that [jcenter is dead](https://blog.gradle.org/jcenter-shutdown)?

Observe the `repositories` section of a freshly generated Flutter app.  `jcenter` is replaced by `mavenCentral`

```gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by kokofoot** [comment]
@christocracy, updated _jcenter_ to _mavenCentral_. Still getting the same error when building. Here is the updated android/build.gradle.

```
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 30
        targetSdkVersion    = 30
        appCompatVersion    = "1.0.2"           
        playServicesLocationVersion = "17.0.0"  
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
Open your /android folder and edit your gradle tools version:

`classpath 'com.android.tools.build:gradle:4.1.0'`

**Comment by jeen0404** [comment]
@christocracy  this also is not resolving the issue. I'm facing the same problem with build. 

here is my android/build.gradle

``` gradle
buildscript {
    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 29                // or higher
        targetSdkVersion    = 29                // or higher
        appCompatVersion    = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
   }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        //classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
           // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
           // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by kokofoot** [comment]
@christocracy, followed your advice and set `classpath 'com.android.tools.build:gradle:4.1.0'`. Also updated `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip` in `gradle-wrapper.properties`. Still getting the same error. Please see the latest android /build.gradle below.

```groovy
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 30
        targetSdkVersion    = 30
        appCompatVersion    = "1.0.2"           
        playServicesLocationVersion = "17.0.0"  
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by kokofoot** [comment]
@christocracy, tried a lot of things, at the end this worked:

Change the following line in the plugin's **android/build.gradle**

`api(group: 'com.transistorsoft', name:'tslocationmanager', version: '+')`

to

`api(group: 'com.transistorsoft', name:'tslocationmanager', version: '3.1.19')`

Didn't have to update to the latest plugin version (our app is still in Flutter 1) nor update the Gradle tool version (it breaks a few other plugins we are currently using).

**Comment by christocracy** [comment]
> Plugin version: 1.10.3

It’s a very bad idea to use such an ancient version of the plugin.  Only recent versions of the plugin are designed for lastest iOS / Android.

your app will be having problems with iOS 15 / Android 12.

upgrade your Flutter version asap.

**Comment by MonsterDKing** [comment]
> @christocracy, tried a lot of things, at the end this worked:
> 
> Change the following line in the plugin's **android/build.gradle**
> 
> `api(group: 'com.transistorsoft', name:'tslocationmanager', version: '+')`
> 
> to
> 
> `api(group: 'com.transistorsoft', name:'tslocationmanager', version: '3.1.19')`
> 
> Didn't have to update to the latest plugin version (our app is still in Flutter 1) nor update the Gradle tool version (it breaks a few other plugins we are currently using).



> > Plugin version: 1.10.3
> 
> It’s a very bad idea to use such an ancient version of the plugin. Only recent versions of the plugin are designed for lastest iOS / Android.
> 
> your app will be having problems with iOS 15 / Android 12.
> 
> upgrade your Flutter version asap.

@christocracy  hi i cant upgrade the application is very old i have the same version to  @kokofoot  but if u change 

> `api(group: 'com.transistorsoft', name:'tslocationmanager', version: '3.1.19')`


> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.transistorsoft:tslocationmanager:3.1.19.
     Required by:
         project :app > project :flutter_background_geolocation
      > Skipped due to earlier error

I comment the application had given me no problem and it worked perfectly but recently wanting to release a new version of the app and run it gives me the error of the one mentioned above (I understand that it is because of the jcenter) but I need to solve it without upgrading the app for the moment
