### ISSUE TITLE
Cant build example

### ISSUE THREAD

**Issue by nsmith1024** [transistorsoft/flutter_background_geolocation#68]
Hello,

I was trying to build the example and i got the errors below, can anybody help?

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Build the example

## Actual Behavior

Build failed
## Steps to Reproduce

Build
## Context

Build the example
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\HotelDev\flutter_background_geolocation\example>flutter clean
.packages does not exist.
Did you run "flutter packages get" in this directory?

D:\HotelDev\flutter_background_geolocation\example>flutter packages get
Running "flutter packages get" in example...
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_background_geolocation_example depends on flutter_map >=0.5.3 which requires SDK version >=2.2.2 <3.0.0, version solving failed.
pub get failed (1)

D:\HotelDev\flutter_background_geolocation\example>

</details>

**Comment by christocracy** [comment]
>Because flutter_background_geolocation_example depends on flutter_map >=0.5.3 which requires SDK version >=2.2.2 <3.0.0, version solving failed.

**Comment by christocracy** [comment]
You need to upgrade your Flutter SDK.

**Comment by nsmith1024** [comment]
How to do that?

**Comment by christocracy** [comment]
```
$ flutter doctor

$ flutter help

Available commands:
  .
  .
  .
  upgrade                  Upgrade your copy of Flutter.
```

**Comment by nsmith1024** [comment]
Trying to upgrade but its failing....trying to figure it out

Because flutter_tools requires SDK version >=2.2.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_tools requires SDK version >=2.2.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_tools requires SDK version >=2.2.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_tools requires SDK version >=2.2.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

**Comment by christocracy** [comment]
No idea.  Go seek help at http://flutter.io.

See Flutter setup docs
