### ISSUE TITLE
Plugin working irregularly (when the app is terminated) after upgrade to iOS 15.1

### ISSUE THREAD

**Issue by alexnavarrogarcia** [transistorsoft/flutter_background_geolocation#680]
## Your Environment
Plugin version: ^4.3.0
Platform: iOS
OS version: 15.1
Device manufacturer / model: iPhone 8
Flutter info (flutter doctor):
MacBook-Air-de-Alejandro:wityu alejandroalbertonavarrogarcia$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.5.2 20G95 darwin-x64, locale es-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;
import 'managers/location_manager.dart';

class TestScreen extends StatefulWidget {
  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  @override
  void initState() {
    super.initState();
    _initPlatformState();
  }

  void _initPlatformState() async {
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      enableHeadless: true,
      startOnBoot: true,
      stopOnTerminate: false,
      locationAuthorizationRequest: "Always",
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "¿Permitir que la app acceda a tu ubicación aún cuando esté cerrada?",
          message:
              "app de seguridad familiar que te mantiene en contacto con tus seres queridos en caso de una posible emergencia. "
              "conocer tu ubicación aún cuando se haya cerrado la app. Por favor habilita los servicios a 'Permitir todo el tiempo'",
          positiveAction: "Permitir todo el tiempo",
          negativeAction: "Cancelar"),
      locationAuthorizationAlert: {
        'titleWhenNotEnabled':
            'Los servicios de ubicación no están habilitados',
        'titleWhenOff': 'Los servicios de ubicación se deshabilitaron',
        'instructions':
            'Para que la app funcione y estés protegido, es necesario que habilites los servicios de ubicación',
        'cancelButton': 'Cancelar',
        'settingsButton': 'Configuración'
      },
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_INFO,
      enableTimestampMeta: false,
      reset: true,
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
  }

  void _onLocation(bg.Location location) {
    bg.Logger.warn("++++++++ ENTRÉ A ONLOCATION() ++++++++++");
    bg.Logger.warn("++++++++ Datos: $location");

    LocationManager.registerLocation(
        56,
        DateTime.parse(location.timestamp)
            .toLocal()
            .toString()
            .substring(0, 19),
        location.coords.latitude,
        location.coords.longitude);
  }

  void _onLocationError(bg.LocationError error) {
    bg.Logger.error("[onLocation] ERROR: $error");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          bg.Logger.emailLog('alexnavarrogarcia@gmail.com')
              .then((bool success) {
            print('[emailLog] success');
          }).catchError((error) {
            print('[emailLog] FAILURE: $error');
          });
        },
        child: const Icon(
          Icons.group_add,
          size: 35.0,
        ),
        backgroundColor: Colors.black,
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      body: Center(
        child: Text("Bienvenidos"),
      ),
      bottomNavigationBar: ClipRRect(
        borderRadius: const BorderRadius.only(
          topLeft: const Radius.circular(25.0),
          topRight: const Radius.circular(25.0),
        ),
        child: BottomNavigationBar(
          currentIndex: 0,
          backgroundColor: Colors.amber,
          unselectedItemColor: Colors.white,
          selectedItemColor: Colors.black,
          type: BottomNavigationBarType.fixed,
          items: [
            BottomNavigationBarItem(
              icon: const Icon(Icons.home_rounded),
              label: "Principal",
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.alternate_email),
              label: "Notificaciones",
            ),
            BottomNavigationBarItem(
              icon: const Icon(Icons.contact_mail_rounded),
              label: "Contactos",
            ),
            BottomNavigationBarItem(
              icon: const Icon(Icons.info_outline_rounded),
              label: "Información",
            )
          ],
        ),
      ),
    );
  }
}
```

## Expected Behavior
When the app is terminated, the plugin should continue working

## Actual Behavior
Plugin was working as expected in iOS 14.8 (plugin working when app was terminated). Once the user upgraded to iOS 15.1, plugin works irregularly. Please, see log attached... there is activity between 2021-12-10 19:45:41.261 and 2021-12-11 11:20:06.327 that the plugin did not recognize.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
[background-geolocation.log (007).txt](https://github.com/transistorsoft/flutter_background_geolocation/files/7697535/background-geolocation.log.007.txt)

**Comment by christocracy** [comment]
>logLevel: bg.Config.LOG_LEVEL_INFO

When having a problem, use `LOG_LEVEL_VERBOSE`

**Comment by alexnavarrogarcia** [comment]
Ok.... I will use debug: true as well and will get back to you... thanks

**Comment by alexnavarrogarcia** [comment]
Chris,
As requested, I changed to LOG_LEVEL_VERBOSE and debug:TRUE, so I could visually check if the plugin was being executed. I installed the same version of my app on two different devices: iPhone 8 iOS 15.1 and iPhone XS iOS 14.8.1 and ran the same experiment. Please see the attached logs. The test trip started 2021-12-12 10:45 aprox....
[iPhone XS iOS 14.8.1.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/7699218/iPhone.XS.iOS.14.8.1.txt)
[iPhone 8 iOS 15.1.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/7699219/iPhone.8.iOS.15.1.txt)

**Comment by christocracy** [comment]
Try rebooting your iOS 15 device and do another field-test outside (at least 1km).

**Comment by alexnavarrogarcia** [comment]
Chris,

I reinstalled the app (so we could have a fresh new log) in both devices and then rebooted both devices as well. Then I started the field test (around 2021-12-12 21:33, 8+ km). Plugin in iOS 15 did not wake up in the whole trip (debug is true, no notifications were shown). 

This morning, the iOS 15 device went out  in a short trip, and this time the plugin worked. 

See logs attached.

[iPhone 8 iOS 15.1 Second Test.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/7705392/iPhone.8.iOS.15.1.Second.Test.txt)

[iPhone XS iOS 14.8.1 Second Test.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/7705391/iPhone.XS.iOS.14.8.1.Second.Test.txt)

**Comment by christocracy** [comment]
iOS 15.2 was released today.  Can you upgrade and test again?  Googling, I see a lot of people complaining about geofences not firing with iOS 15.1.

**Comment by alexnavarrogarcia** [comment]
Ok, I just saw the update was available. I'll complete the upgrade and then will make another test trip. I'll keep you posted.
Thanks.

**Comment by alexnavarrogarcia** [comment]
Hi Chris,
Yesterday, I upgraded to 15.2 and made a couple of test trips... the plugin worked excellent again, it seems that the upgrade fixed the issue. I will continue testing for a few days and then confirm all is 100% again.
I'll keep you posted.
Thanks.

**Comment by alexnavarrogarcia** [comment]
The issue has not been fixed in iOS 15.2: location services failed again this morning on a test trip. Making some research, it seems that the problem is escalating very fast; hopefully Apple can provide a solution ASAP.

https://discussions.apple.com/thread/253295564
https://www.howtoisolve.com/gps-location-services-not-working-ios-11-iphone-ipad/
https://www.iphonetricks.org/find-my-location-not-updating-in-ios-15/

**Comment by christocracy** [comment]
Everything is good here on my end on the four demo apps I test daily for *Cordova*, *React Native*, *Flutter* and *Capacitor*.

**Comment by alexnavarrogarcia** [comment]
Hola,
I've been following up this issue for several days and so far, Apple hasn't responded/provided a solution. The last piece of information from a couple of developers was that they have been testing iOS 15.3 beta and geofencing and location services were working ok again; however we'll neet to see: https://discussions.apple.com/thread/253247480?answerId=256538243022&login=true&page=3
As this problem isn't related with the plugin, I will proceed and close the issue. Chris, if you know or receive any information regarding this problem, we'd highly appreciate it.
Thanks.
