### ISSUE TITLE
Multiple Firebase Project 

### ISSUE THREAD

**Issue by iDeliverWilhem** [transistorsoft/flutter_background_geolocation#683]
## Your Environment
* Plugin version: 1.11.1
* Platform: iOS and Android
* OS version: Mac M1
* Device manufacturer / model: iphone 13 and android emulators
* Flutter info (`flutter doctor`):
`[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-arm, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (2 available)`

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```
`bg.Config config = bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 3,
      logLevel: bg.Config.LOG_LEVEL_WARNING,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Allow {applicationName} to access to this device's location in the background?",
          message:
              "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
          positiveAction: "Change to {backgroundPermissionOptionLabel}",
          negativeAction: "Cancel"),
      useSignificantChangesOnly: true,
      extras: {
        "secret": globalVariables.getSecret(),
        "user-id": userId,
        "distributor-id": globalVariables.getDistributorId(),
        // Set the default event-type, which is sent when pushing in the background.
        // When we explicitly send an event it the event-type should be overridden.
        "event-type": "location"
      });
`

## Expected Behavior

Will be able to switch Firebase projects and and save location to which ever firebase app is active

## Actual Behavior

It uses the firebase storage from the google-services.json file only

## Steps to Reproduce

1. 
2.
3.
4.

## Context

Switch firebase app in dart on the fly and record location

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

Any advise on using multiple firebase app is highly appreciated. 

Thanks
-Wil

**Comment by christocracy** [comment]
Please post firebase-specific issues at the fire base adapter repo.
