### ISSUE TITLE
Getting error for android plz help me to solve this issue 

### ISSUE THREAD

**Issue by Shradak** [transistorsoft/flutter_background_geolocation#684]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.transistorsoft:tslocationmanager:+.
     Required by:
         project :app > project :flutter_background_geolocation
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
Exception: Gradle task assembleDebug failed with exit code 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.transistorsoft:tslocationmanager:+.
     Required by:
         project :app > project :flutter_background_geolocation
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by Shradak** [comment]
group 'com.transistorsoft.flutter.backgroundgeolocation'
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 29                // or higher
        targetSdkVersion    = 29                // or higher
        appCompatVersion    = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
       }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:7.0.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Generate a fresh flutter app and compare the generated android/build.gradle with yours.

Copy the freshly generated build.gradle into your own app and re-apply the plug-in’s setup steps.

**Comment by Shradak** [comment]
now i am getting this error

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Admin/AndroidStudioProjects/app-flutter/android/app/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
