### ISSUE TITLE
[GOOGLE PLAY POLICY] App gets rejected due to a policy violation

### ISSUE THREAD

**Issue by Babwenbiber** [transistorsoft/flutter_background_geolocation#686]
## Your Environment
* Plugin version: 4.3.1
* Platform: Android
* OS version: - 
* Device manufacturer / model: -
* Flutter info (`flutter doctor`): -
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            desiredOdometerAccuracy: 10,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0.0,
            stopOnTerminate: true,
            stopOnStationary: false,
            startOnBoot: false,
            debug: false,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    AppLocalizationsDelegate.languageInstance?.permissionTitleGpsTrackingLocation,
                message:
                    AppLocalizationsDelegate.languageInstance?.permissionTextGpsTrackingLocation,
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            stopTimeout: 1,
            preventSuspend: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        _ready = true;
      }
    });

```

## Expected Behavior
I need help modifying my app in a way that google accepts the procedure of handling the location permissions.

## Actual Behavior
My App violates the policy.
<details>
	<summary>Policy violation</summary>

Prominent disclosure not found

Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission. 

Please add a prominent disclosure before the runtime permission.

Remember, your prominent disclosure must:

Appear before your app’s location runtime permission.
Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.
If portions of your app are restricted, please share a link to a video of your app that demonstrates the in-app feature’s functionality requesting location in the background and how a user would trigger the prominent disclosure and runtime permission (with user consent).

</details>

## Steps to Reproduce
You can't reproduce this, since my app is not open source. But I prepared a bunch of screenshots which can show you the current workflow.

1. When navigating to "GPS TRACKER" and the permissions are not set to "always" the user will see this alert to warn him about the permissions necessary and why they are needed:
![WhatsApp Image 2022-01-01 at 3 09 51 PM (5)](https://user-images.githubusercontent.com/15171332/147852636-e5c4f502-e082-4ab4-b367-1c0482ddcf02.jpeg)
2. The user has to accept this dialog or he will get directed to the previous page. If he accepts, than the native permissions will get queried:
![WhatsApp Image 2022-01-01 at 3 09 51 PM (4)](https://user-images.githubusercontent.com/15171332/147852655-1a679c34-69f7-4d5d-881b-a14fcd1b063f.jpeg)
![WhatsApp Image 2022-01-01 at 3 09 51 PM (3)](https://user-images.githubusercontent.com/15171332/147852656-40ef5406-815b-406f-a11c-6fa1216f967c.jpeg)
3. If the user doesn't choose "allow" and "while using the app" the user will once again get navigated back the previous page. If he did, then he will get to the relevant settings page:
![WhatsApp Image 2022-01-01 at 3 09 51 PM (2)](https://user-images.githubusercontent.com/15171332/147852691-64f38100-8e8c-4d4a-8ba2-dfd2f5b7fbec.jpeg)
4. If he chooses "always" then the `BackgroundGeolocation.ready` will get called and the plugin gets prepared. If not, the user gets back to the previous page. Now, the user can start using the GPS TRACKING functionality.

The policy states:
- Appear before your app’s location runtime permission. ✅
- Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use._” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”_✅ (adds is not the case)
- Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible. ✅
- If portions of your app are restricted, please share a link to a video of your app that demonstrates the in-app feature’s functionality requesting location in the background and how a user would trigger the prominent disclosure and runtime permission (with user consent). ✅  (shared a yt video)

## Context
Use this plugin in my app

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See my blog;  https://link.medium.com/9M7yAuoTsmb

**Comment by Babwenbiber** [comment]
> See my blog; https://link.medium.com/9M7yAuoTsmb

Thanks. I carefully read this guide and found out, that I already met every single of your requirements mentioned. Your **Step 5: Prominent Disclosure for Background Location Access** is already met with my alert (as you can see in the screenshots above).

Is this just a wording thing or am I missing something?

**Comment by christocracy** [comment]
Carefully Read Google Guide and take care with the text on your buttons.

https://support.google.com/googleplay/android-developer/answer/11150561?hl=en#zippy=%2Cuser-experience

**Comment by Jihadik** [comment]
@christocracy, one question that I have after reading your article and the documentation. If I **don't** need to access location after termination, but need it in background, do I still need all of these dialogues and permissions?

**Comment by christocracy** [comment]
If you're not interested in having the plugin *automatically* initiate location tracking when the device is detected to be moving, you can request *When In Use* location authorization and remove the permission `android.permission.ACCESS_BACKGROUND_LOCATION` from your `AndroiManifest` (as documented in the blog post).

In that case, the only way your can track location in the background is by executing `.changePace(true)` while in the foreground.  Your app would function like a *Jogging App* where the user initiates tracking by pressing a button, such as `[Start Workout]`.

**Comment by Jihadik** [comment]
@christocracy, oh, wow, is that true for an iOS as well?

**Comment by christocracy** [comment]
Yes, of course.
