### ISSUE TITLE
Unable to get lat longs when screen is lock on android 11

### ISSUE THREAD

**Issue by amelioratesolutions** [transistorsoft/flutter_background_geolocation#688]
void BackgroundLocation() {

    bg.Config params = new bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 2,
      heartbeatInterval: 60,
      url: "https://dev-api.saido.eu/api/v1/test-lat-long",
      params: {
        'Uid': sharedPrefs.id,
      },
      headers: {
        'Content-type': 'application/json',
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + sharedPrefs.access,
      },
      autoSync: true,
      startOnBoot: true,
    );
    bg.BackgroundGeolocation.onHttp((bg.HttpEvent httpEvent) => {
      print("$httpEvent.responseText"),
      print( "$httpEvent.status"),
    });

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      double lat = location.coords.latitude;
      double lng = location.coords.longitude;
      print("++++++++++++++++++++");
      print(lng);
      print("[onLocation] $location");
    });

    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      if (location.isMoving) {
        print('[onMotionChange] Device has just started MOVING ${location}');
      } else {
        print('[onMotionChange] Device has just STOPPED:  ${location}');
      }
    });
    bg.BackgroundGeolocation.ready(params).then((bg.State state) {
      print('[ready] BackgroundGeolocation is configured and ready to use');
      bg.BackgroundGeolocation.start();
    });

    bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
      print('[onHeartbeat] ${event}');
      // You could request a new location if you wish.
      bg.BackgroundGeolocation.getCurrentPosition(
          samples: 1,
          persist: true
      );
    });
  }

**Comment by christocracy** [comment]
What makes you think that’s the case?

how are you attempting to test that?

See wiki *Debugging* and go outside for a 1km field test with a real device.

**Comment by amelioratesolutions** [comment]
We have test on real device on android 11 by going outside for 1 km and how to test using wiki debugging.

**Comment by christocracy** [comment]
Did read the wiki Debugging?

**Comment by amelioratesolutions** [comment]
Can u plz share the link for wiki debugging we are new to this concept

**Comment by christocracy** [comment]
The “Wiki”!is in the main menu, up there in this GitHub repo.
