### ISSUE TITLE
Android Error: Could not find any matches for com.transistorsoft:tsbackgroundfetch:+

### ISSUE THREAD

**Issue by KaiBroeker** [transistorsoft/flutter_background_geolocation#689]
Hi,

I started a new projekt and added the dependencies as discribed. I imported it and ran it without any other code.
If I then build the code I get the following error:
```
Launching lib/main.dart on SM G991B in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/kai/AndroidStudioProjects/gpsops/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/home/kai/AndroidStudioProjects/gpsops/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
```

Maybe I missed some points, but I was thinking, that it should build if I follow the instruktions.

## Your Environment
* Plugin version: 4.3.2
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung S21 5G
* Flutter info (`flutter doctor`): no issues

## Expected Behavior
normaly the build should work.

## Actual Behavior
Build failure

## Steps to Reproduce
1. create new project
2. set up dependencies
3. get dependencies
4. run build/"Run main.dart"

</details>

**Comment by christocracy** [comment]
Post you android/build.gradle

**Comment by KaiBroeker** [comment]
Like in the instructions I didn't change anythink:
```
buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
You mean [these instructions](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md), linked in the readme?

**Comment by KaiBroeker** [comment]
Oh, my mistake. I overlooked the link in the readme.
Sorry for my mistake.

**Comment by saeedanwar855** [comment]
i also got the same error though i already setup from readme still get this error

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by saeedanwar855** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
       ext {
               compileSdkVersion   = 33
               targetSdkVersion    = 33
               appCompatVersion    = "1.4.2"
               playServicesLocationVersion = "20.0.0"
           }


repositories {
        google()
        mavenCentral()
    maven {
                   // [required] flutter_background_geolocation
                          url "${project(':flutter_background_geolocation').projectDir}/libs"
    }

           maven {
                   // [required] background_fetch
                           url "${project(':background_fetch').projectDir}/libs"
              }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'


    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by saeedanwar855** [comment]
App/build.gradle

**Comment by zolo1985** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/zolo/qgo/qgo_user/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/zolo/qgo/qgo_user/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited.

/////////////////////////////////////////////////// BUILD GRADLE //////////////////////////////////////
buildscript {
    ext.kotlin_version = '1.7.10'
    ext {
        compileSdkVersion   = 33
        targetSdkVersion    = 32
        minSdkVersion       = 19
        appCompatVersion    = "1.4.2"
        playServicesLocationVersion = "20.0.0"
    }
    repositories {
        google()
        mavenCentral()
        // [required] flutter_background_geolocation
        maven { url "${project(':flutter_background_geolocation').projectDir}/libs" }
        maven { url 'https://developer.huawei.com/repo/' }
        // [required] background_fetch
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
//////////////////////////////////////////////// ANDROID/APP/GRADLE   //////////////////////////////////////////
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
    namespace "com.example.qgo_user"
    compileSdkVersion rootProject.ext.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.qgo_user"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            shrinkResources false
            // background_geolocation requires custom Proguard Rules with minifyEnabled
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {}

**Comment by christocracy** [comment]
**`allprojects/repositories`**

**Comment by Pradeeptharu100** [comment]
i got also same error?

**Comment by Sud2024** [comment]
I also got the same error
[Fatal Error] tsbackgroundfetch-1.0.0.pom:2:10: Already seen doctype.
[Fatal Error] arm64_v8a_debug-1.0.0-36335019a8eab588c3c2ea783c618d90505be233.pom:2:10: Already seen doctype.
[Fatal Error] x86_debug-1.0.0-36335019a8eab588c3c2ea783c618d90505be233.pom:2:10: Already seen doctype.
[Fatal Error] x86_64_debug-1.0.0-36335019a8eab588c3c2ea783c618d90505be233.pom:2:10: Already seen doctype.
[Fatal Error] tslocationmanager-1.0.0.pom:2:10: Already seen doctype.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:1.0.0.
     Required by:
         project :app
      > Could not resolve com.transistorsoft:tsbackgroundfetch:1.0.0.
         > Could not parse POM https://transistorsoft.jfrog.io/artifactory/transistorsoft-libs-release/com/transistorsoft/tsbackgroundfetch/1.0.0/tsbackgroundfetch-1.0.0.pom
            > Already seen doctype.
   > Could not resolve com.transistorsoft:tslocationmanager:1.0.0.
     Required by:
         project :app
      > Could not resolve com.transistorsoft:tslocationmanager:1.0.0.
         > Could not parse POM https://transistorsoft.jfrog.io/artifactory/transistorsoft-libs-release/com/transistorsoft/tslocationmanager/1.0.0/tslocationmanager-1.0.0.pom
            > Already seen doctype.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://transistorsoft.jfrog.io/artifactory/transistorsoft-libs-release/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://landing.jfrog.com/reactivate-server/transistorsoft'. Received status code 409 from server: Conflict
   > Could not resolve com.transistorsoft:tslocationmanager:+.
     Required by:
         project :app > project :flutter_background_geolocation
      > Failed to list versions for com.transistorsoft:tslocationmanager.
         > Unable to load Maven meta-data from https://transistorsoft.jfrog.io/artifactory/transistorsoft-libs-release/com/transistorsoft/tslocationmanager/maven-metadata.xml.
            > Could not GET 'https://landing.jfrog.com/reactivate-server/transistorsoft'. Received status code 409 from server: Conflict

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 50s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
Post your two gradle files.

**Comment by SAFALInfosoft** [comment]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/dipakmakwana/StudioProjects/Formezy/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/dipakmakwana/StudioProjects/Formezy/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://developer.huawei.com/repo/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Error: Gradle task assembleDebug failed with exit code 1


i got this error

**Comment by SAFALInfosoft** [comment]
this is my android/gradle file 

buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by Sud2024** [comment]
@christocracy I have stopped using the package 
Now I am using flutter_background_service package for enabling background location permission and so now I don't have the code for gradle files.
