### ISSUE TITLE
Tracking stops while in background

### ISSUE THREAD

**Issue by max-ringel** [transistorsoft/flutter_background_geolocation#690]
## Your Environment
* Plugin version:
flutter_background_geolocation: ^4.2.1
* Platform: iOS or Android:
iOS/Android
* OS version:
several
* Device manufacturer / model:
several
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.63.0)
[✓] Connected device (1 available)
* Plugin config: 

```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        heartbeatInterval: 300,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        foregroundService: true,
        activityRecognitionInterval: 5000,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        preventSuspend: true,
        isMoving: true,
        logLevel: bg.Config.LOG_LEVEL_ERROR,
        logMaxDays: 3,
        locationAuthorizationRequest: 'Always',
        enableHeadless: true,
        fastestLocationUpdateInterval: 5000,
        autoSyncThreshold: 5,
        batchSync: true,
        maxBatchSize: 10,
        url: postUrl.toString(),
        headers: {
          ...
        },
        params: {...},
        autoSync: true,
        backgroundPermissionRationale: new bg.PermissionRationale(
            title:
                "...",
            message:
                "...",
            positiveAction: '...',
            negativeAction: '...'));
```

## Expected Behavior
The tracking should continue for longer periods even when the app is closed in the background.

## Actual Behavior
From time to time again, the tracking just stops.
There was just a case where tracking was happening just fine from 3rd Dec 2021 to 31st Dec 2021 and then just stopped working.

## Steps to Reproduce
Run the plugin in the background while app is closed.

## Context

Wanted the plugin to run on the device even when the app is closed to further send locations to the server.

## Debug logs
We didn't receive any error-level logs from the plugin.

<details>
	<summary>Logs</summary>
``` <!-- syntax-highligting:  DO NOT REMOVE -->

```
</details>

**Comment by christocracy** [comment]
>Platform: iOS or Android:
>OS version:
>Device manufacturer / model:

**Comment by max-ringel** [comment]
Platform: iOS OS version: 14.8.1
Device manufacturer / model: iphone 12 pro

**Comment by max-ringel** [comment]
@christocracy do you have any insight on why this is happening or maybe some tips and tricks on how one could tackle this problem/prevent the app from stopping tracking in the background?

**Comment by christocracy** [comment]
Are you reproducing this **yourself** on *iOS 14.8.1*?

**Comment by max-ringel** [comment]
We actually reproduced the issue on: iphone 12 promax, currently running 15.1.1

**Comment by christocracy** [comment]
Google [iOS 15 geofencing not working](https://www.google.com/search?q=ios+15+geofencing+not+working&oq=ios+&aqs=chrome.0.69i59j69i57j69i61l3j69i65l3.1536j0j4&sourceid=chrome&ie=UTF-8).

There are reports from *all over the place* (including from consumers, not just developers) that iOS 15 broke geofencing / significant location changes API.  The iOS code relies upon a geofence exit event to determine when the device is moving.  I hear rumours of a fix coming in *iOS 15.3*.

**Comment by christocracy** [comment]
Since iOS 15, I've been experiencing periodic tracking issues *randomly* myself on my four demo apps for *Cordova*, *Capacitor*, *React Native* and *Flutter*.  It is *very* unusual for these 4 apps to not perform *identically* (since they all share the same iOS library `TSLocationManager.xcframework`).  Since iOS 15, sometimes, one or two won't work for a particular trip (I run my four demo apps on my main phone all the time).  Often they all work fine.

**Comment by jonasfeld** [comment]
@christocracy is this resolved now?

**Comment by christocracy** [comment]
In iOS 15.4 beta, I hear from other customers that their similar issues are fixed.

**Comment by Shahmirzali-Huseynov** [comment]
not working when app is killed :/ ios 15.5 iPhone 8

**Comment by Shahmirzali-Huseynov** [comment]
@max-ringel  did you solve problem?

**Comment by christocracy** [comment]
@Shahmirzali-Huseynov this issue is solved.  Post a new issue,  provide detailed info as will be requested in issue template.

**Comment by Shahmirzali-Huseynov** [comment]
@christocracy  this package is working even app is killed ?

**Comment by christocracy** [comment]
Yes.  It will even work if the device is rebooted, as soon as unlocked.
