### ISSUE TITLE
Plugin Usage without Background-Service

### ISSUE THREAD

**Issue by Babwenbiber** [transistorsoft/flutter_background_geolocation#693]
I want to use this plugin with the foreground-service only. This means, that the user needs permissions 'while in use' only.
Every function works for me perfectly (btw. Thanks for this awesome plugin).
Still I couldn't find an option to turn off the background-service request.
When the user wants to use the app, he always gets asked to activate the location 'always'.
He can just ignore this request and continue with 'while in use' only and everything works just fine.

Still, I don't want this dialog and I couldn't find an option to turn it off.

P.S. This template was for bugs, since this is not a bug or device/app specific I freestyled here.

**Comment by christocracy** [comment]
See api docs Config.locationAuthorizationRequest
