### ISSUE TITLE
Pull and push/post geofence data to server's database

### ISSUE THREAD

**Issue by TolgaYld** [transistorsoft/flutter_background_geolocation#694]
Hi,

I would like to know if I can write the geofence points (with radius) to my server's database and then always pull them from the database (even if the app is terminated).
I read in the docs that the geofences are always written to the SDK database. But I would like to keep the geofence data auto-syncronized with the geofence data in my database from my server.

For example:

When I write BackgroundGeolocation.addGeofence, I want to push/post the geofence-data to my server's database.
And the SDK's database should be always an auto-syncronous copy of my server's database.

Is that possible?

Thanks in advance!

**Comment by christocracy** [comment]
I don’t see how the plugin needs to be involved with this.  This is your own custom app logic.
