### ISSUE TITLE
What is the difference between the tracking modes?

### ISSUE THREAD

**Issue by kamami** [transistorsoft/flutter_background_geolocation#695]
In the documentation is written:

`The BackgroundGeolocation SDK allows you to optionally monitor only geofences without constant location-tracking. To engage geofences-only mode, use the method BackgroundGeolocation.startGeofences instead of BackgroundGeolocation.start.`

What is the disadvantage of only tracking the geofences and not the location? What is the difference between those two modes?

**Comment by christocracy** [comment]
Tracking location everywhere the device goes obviously consumes more energy.

`start()` = *track location + geofences*.
![](https://dl.dropbox.com/s/c7lda98fj0xljn7/Screen%20Shot%202022-01-18%20at%2012.50.32%20PM.png?dl=1)

`startGeofences()` = *track geofences only*.
![](https://dl.dropbox.com/s/vv8rat33scu811o/Screen%20Shot%202022-01-18%20at%2012.51.31%20PM.png?dl=1)

**Comment by kamami** [comment]
So the entry of the device in a geofence is still triggering `onGeofence` when using `startGeofences()` right?

**Comment by christocracy** [comment]
Yes.  
- start() = track geofences + location 
- startGeofences() = track geofences only.

I don’t know how this could be any more clear.

**Comment by kamami** [comment]
As someone who is new to geofencing, I thought you would always need to track the location of the device to trigger a geofence. I did not know that this is not necessary. Thanks for clarification!
