### ISSUE TITLE
Hey thanks for the amazing plugin worked really great.Can you please tell me how to get only moving time the time where location captured not idle .(Help Wanted)

### ISSUE THREAD

**Issue by Ravish1** [transistorsoft/flutter_background_geolocation#696]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Use the onMotionChange event to record start time / end time?

**Comment by Ravish1** [comment]
Thanks for the revert.I have already elapsed time overall a timer when user start tracking and end tracking.Just want moving time for whole trip where user actually moved .

**Comment by christocracy** [comment]
Perhaps you’re interested in the onActivityChange event.

**Comment by Ravish1** [comment]
void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[activitychange] - $event');

    _motionActivity = event.activity;
    if (_motionActivity == "still") {
      activitytype = "Still";
    } else if (_motionActivity == "on_foot") {
      activitytype = "On Foot";
    } else if (_motionActivity == "walking") {
      activitytype = "Walking";
    } else if (_motionActivity == "running") {
      activitytype = "Running";
    } else if (_motionActivity == "on_bicycle") {
      activitytype = "On Bicycle";
    } else if (_motionActivity == "in_vehicle") {
      activitytype = "Tracking on vehicle";
    }
    setState(() {});

    print('[activitychange] - $event');

  }
Yes that's how I am handling on Activity change event .if activity type  is still then no need to start the timer right.thats the correct way to detect moving time?

**Comment by christocracy** [comment]
That is the only way, yes.

you will find a wide range of performance of the motion-activity api across various Android devices, from poor to excellent.  There is nothing to be done about poor performing Android devices.
