### ISSUE TITLE
Erratic GPS speed

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#700]
## Your Environment
* Plugin version: 4.3.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: King Kong Mini 2 
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.8.1 at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior
The speed should not be erratic.

## Actual Behavior
The speed is not correctly indicated and very often remains on zero. 

## Steps to Reproduce
1. Start the app and start riding a bike.
2. Monitor the speed.
3.
4.

## Context
This is a customer's phone, so I do not have much to go on. The same customer is running the same version of my app on Xiaomi with Android 12 and iPhone 6s without issues. I myself run the same version of the app on Samsung with Android 9 and Pixel 3 with Android 12 with no issues. So it seems the problem is isolated to this one phone. However, this phone also runs the Jepster bike computer app, which is similar to my own, and the speed readout is normal, so that makes me think it's my app that has a problem on this phone. The customer has tried reinstalling the app, but the behavior did not change.

Do you have any ideas as to what might be wrong?

Things that have changed recently in my app that may be related:
1. The plugin was updated to 4.3.3
2. appCompatVersion was changed from 1.3.1 to 1.4.1.

    ext.kotlin_version = '1.6.10'
    ext {
        compileSdkVersion   = 31
        targetSdkVersion    = 31
        minSdkVersion       = 23
        appCompatVersion    = "1.4.1"
        playServicesLocationVersion = "18.0.0"
    }

## Debug logs
Logs are not available

**Comment by christocracy** [comment]
The plugin does not *calculate* speed.  Speed is provided by the GPS chip on the device.  The plugin is only the messenger, delivering Speed exactly as provided by GPS.

there’s nothing the plugin can do to “improve” values provided by some particular device.

**Comment by ozzy1873** [comment]
Yes, I understand that. I am just wondering if you have run into this problem before and if you had any ideas on what might be wrong or if there is something I might try. The fact that another similar app runs fine makes me wonder if I have a configuration problem somewhere. This is a pre-release version of my app, so I do not have a ton of people using it and it would be nice to be able to track down some reason for this behavior before I release it.

**Comment by ozzy1873** [comment]
This appears to be a problem with the customer's phone. Closing.
