### ISSUE TITLE
ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#703]
## Your Environment
NOTE: This exception is occurring with the previous stable version of flutter. This "flutter doctor" was generated after upgrading to Flutter 2.10. 
* Plugin version: 4.3.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Galaxy A52s 5G, OPPO A74 5G, Galaxy S21 5G, Pixel 6, Pixel 4, Galaxy S20 FE 5G, Galaxy S10+, Galaxy A72, Pixel 5, Galaxy S20 Ultra 5G, Galaxy A52 5G, Pixel 5a 5G
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.10.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:/Users/john/AppData/Local/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:/Users/john/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)  • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior
No exception

## Actual Behavior
This exception is thrown in the field fairly often, always in the background.

Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.osborntech.supercycle/com.transistorsoft.locationmanager.service.LocationRequestService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3333)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
       at android.os.Parcel.createException(Parcel.java:2409)
       at android.os.Parcel.readException(Parcel.java:2392)
       at android.os.Parcel.readException(Parcel.java:2334)
       at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5971)
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
       at com.transistorsoft.locationmanager.service.AbstractService$a.run(AbstractService.java:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:691)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:616)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:11850)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2519)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
## Steps to Reproduce

1. I am unable to reproduce this issue.
2.
3.
4.

## Context
I don't know the context.

## Debug logs

<details>
	<summary>Logs</summary>
No logs available.

</details>

**Comment by ozzy1873** [comment]
This exception is happening quite often, but only on Android 12. I am running your plugin in foreground only mode:
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:node="remove" />

I see that the following permission is now required for foreground services, but I have not added it in my project:
<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/> 

If that permission is missing, a SecurityException is supposed to be thrown but I never see that happen. Are you adding that permission automatically or do I need to add it?

**Comment by christocracy** [comment]
I see you're using `WhenInUse` location authorization.  I'll do some testing with that on my local devices.

Android 12 has radically changed the nature of foreground-services.  It used to be that foreground-services could launch in the background but that is no more.  They must be launched only with the app in the foreground or at device boot.  The foreground services must then be kept alive rather than being launched only when needed.

**Comment by christocracy** [comment]
Perhaps.

**Comment by ozzy1873** [comment]
Do you think setting Config.stopTimeout to a large value could prevent this?

**Comment by ozzy1873** [comment]
My app tracks a bicycle ride and configures your library as a foreground service. When the ride begins, the user presses a start button to begin recording GPS data (which calls changePace(true)). When the ride ends, the user presses a stop button to stop recording GPS data (which calls changePace(false)). 

Often but not always, the user will exit the app soon after pressing the stop button. It seems to be at that point that the exception most often occurs.

**Comment by christocracy** [comment]
`changePace(false)` causes the plugin to request a high-accuracy location, requesting several location samples before it settles upon the most accurate.  This can take some seconds to complete.  

If the bike trip is done, why are you not simply calling `.stop()` instead?

**Comment by ozzy1873** [comment]
Thanks, I will try that.

**Comment by lielvan** [comment]
@ozzy1873 have you found a solution? Currently experiencing a similar issue with my app.
In my case, while the app is open, it continuously checks a user's location every 30 seconds with locationAuthorization set to 'WhenInUse'. When in the background, it continues to do so.

It never calls `changePace(false)` since it always seeks to find your location. Calling `stop()` only during logout.
So any solution or guidance would be wonderful.

**Comment by christocracy** [comment]
>setting Config.stopTimeout to a large number

It won't help.  The plugin purposely keeps foreground-services permanently alive due to drastic changes in Android 12, regardless if in *stationary* or *moving* state.  It doesn't matter if location-services are turned off.

Before Android 12, the plugin could let foreground-services terminate and activate them in the background only when required (eg: when the Motion API detects the device is moving).

To get this error means that the plugin's foreground-service is no longer active, either because:
- the plugin is been told to `stop()`
- The OS has decided to terminate the plugin's foreground-service.

I do not yet know how to reproduce this.  I have the /example app running on my *Pixel 3a @ 12* and field-test all the time.  It doesn't fail to track me.

**Comment by lielvan** [comment]
@christocracy I've been able to reproduce this on my end, at least for the most part (doesn't always occur but just enough)

* When the app is first started with GPS turned ON, everything is fine and working.
* Then navigating outside the app to Android's Settings and turning GPS OFF.
* After a few seconds I turn GPS back ON and redirect to Android's Home, and that's is when the `startForegroundServiceException` is thrown.
* Notably, a FlutterJNI error is thrown around the same time:
     `Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send.`

Another undesirable effect is when I toggle the GPS ON/OFF - With every toggle, the Android OS "kills" the app and it enters a `detached` lifecycle state, forcing the user to have to restart the app. This happens if the app starts with GPS ON then toggled OFF and vice versa.

Error log:
```
I/flutter (23209): [_onProviderChange] [ProviderChangeEvent enabled:false, status: 3, network: false, gps: false, accuracyAuthorization: 0]
...
I/flutter (23209): [_onProviderChange] [ProviderChangeEvent enabled:true, status: 3, network: true, gps: true, accuracyAuthorization: 0]
I/flutter (23209): >>> bg enabled: true | provider enabled: true | gps: true
I/flutter (23209): lifecycle changed to AppLifecycleState.detached
W/FlutterJNI(23209): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 215
W/FlutterJNI(23209): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 214
W/System  (23209): A resource failed to call release. 
I/BpBinder(23209): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
D/AndroidRuntime(23209): Shutting down VM
E/AndroidRuntime(23209): FATAL EXCEPTION: main
E/AndroidRuntime(23209): Process: *****, PID: 23209
E/AndroidRuntime(23209): android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service *****/com.transistorsoft.locationmanager.service.LocationRequestService
E/AndroidRuntime(23209): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
E/AndroidRuntime(23209): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
E/AndroidRuntime(23209): 	at android.os.Parcel.readParcelable(Parcel.java:3333)
E/AndroidRuntime(23209): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
E/AndroidRuntime(23209): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime(23209): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime(23209): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime(23209): 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6028)
E/AndroidRuntime(23209): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
E/AndroidRuntime(23209): 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
E/AndroidRuntime(23209): 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
E/AndroidRuntime(23209): 	at com.transistorsoft.locationmanager.service.AbstractService$a.run(Unknown Source:10)
E/AndroidRuntime(23209): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(23209): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23209): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(23209): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(23209): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(23209): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23209): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(23209): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(23209): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(23209): 	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:692)
E/AndroidRuntime(23209): 	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:617)
E/AndroidRuntime(23209): 	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:11876)
E/AndroidRuntime(23209): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2542)
E/AndroidRuntime(23209): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2516)
E/AndroidRuntime(23209): 
```

bg.Config:
```
        bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: true,
          startOnBoot: false,
          autoSync: false,
          maxRecordsToPersist: 1000,
          persistMode: bg.Config.PERSIST_MODE_NONE,
          logMaxDays: 0,
          locationAuthorizationRequest: 'WhenInUse',
          // locationAuthorizationAlert: ,

          // autoSyncThreshold: 0,
          // url: _serverUrl,
          // enableHeadless: ,

          foregroundService: true,
          backgroundPermissionRationale: bg.PermissionRationale(
            title: t('Allow {applicationName} to access to this device\'s location in the background?'),
            message: t(
                'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission'),
            positiveAction: t("Change to {backgroundPermissionOptionLabel}"),
            negativeAction: t("Cancel"),
          ),
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_OFF,
          reset: true,
        ),
```

**Comment by christocracy** [comment]
> With every toggle, the Android OS "kills" the app

This is well-known standard behavior of the Android OS.  When the permission model of the app changes, the Activity must be restarted into the new permission environment.

**Comment by lielvan** [comment]
@christocracy Understandable, but it still doesn't explain the `ForegroundServiceNotAllowedException`. I was toggling GPS for the sake of simulating a No-Service scenario. Toggling GPS manually probably disables/enables permissions, fine, but going from having cell service to having none and then on again, shouldn't affect permissions and thus I see no reason why a restart should occur.

This crash has been occurring ever since we updated our app to use Android 31, before that the app and this package were working fine. It is quite unreasonable, that now my users can't place the app in the background, go in-and-out of cell service (normal case for my users), and not have the app still "alive" and functioning with no sudden foreground-service exceptions.

All signs (as I see them) indicate this exception originates from this package. The use-case I just described was working just fine with earlier versions of Android (pre-Android API 31).

**Comment by christocracy** [comment]
>Then navigating outside the app to Android's Settings and turning GPS OFF.

I cannot reproduce this phenomenon on my *Pixel 3a @ 12*.

The foreground service stays active after disabling *Location Services*.

<img width="399" alt="Screen Shot 2022-03-17 at 9 33 24 AM" src="https://user-images.githubusercontent.com/14999/158819820-f878e794-973c-4cbe-99d5-387ad5154fe0.png">

**Comment by poqueque** [comment]
Same problem here, lots of Crashlytics reports after publishing a new version with target API 31 (it was 30). All crashes occurs in background and on Android 12 devices.

**Comment by yaroslav13** [comment]
Do some updates there?

**Comment by christocracy** [comment]
With Android 12, you must be careful to not do things like call `.start()` while your app is in the background.

You can also not call `.getCurrentPosition()` in the background while the plugin has had `.stop()` called upon it (ie where `State.enabled == false`.

With Android 12, [a foreground-service can only be started while an app is in the foreground](https://developer.android.com/about/versions/12/behavior-changes-12#performance).

**Comment by christocracy** [comment]
Yes

**Comment by yaroslav13** [comment]
Thanks!

**Comment by christocracy** [comment]
You can reproduce this error with *Android 12* by registering the [WidgetsBindingObserverClass](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) in you `Widget`.

```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print("didChangeAppLifecycleState] : $state");
    if (state == AppLifecycleState.paused) {
      // Attempt to start() the plugin in the background.  Android seems to allow about 10s of leeway
      // before throwing this error so you need to set a timer for 15s.
      new Timer(Duration(seconds: 15), () {
        bg.BackgroundGeolocation.start();
      });
    }
  }
```
- In a terminal window, observe `$ adb logcat *:S ActivityManager`.
- With your app in the foreground, call `BackgroundGeolocation.stop()`.
- Put app in background.
- Wait 15s.

```
05-03 10:07:33.153  1128  7032 W ActivityManager: startForegroundService() not allowed due to mAllowStartForeground false: service com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.service.ActivityRecognitionService
05-03 10:07:33.154  1128  7032 W ActivityManager: Unable to send startService intent
05-03 10:07:33.154  1128  7032 W ActivityManager: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.service.ActivityRecognitionService
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:771)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.ActivityManagerService$LocalService.startServiceInPackage(ActivityManagerService.java:18536)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:582)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:331)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:6214)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5216)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3030)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at android.os.Binder.execTransactInternal(Binder.java:1215)
05-03 10:07:33.154  1128  7032 W ActivityManager: 	at android.os.Binder.execTransact(Binder.java:1179)
```

**Comment by christocracy** [comment]
Ok, I've discovered something **very** interesting.  If instead of a *Dart* `Timer*, I use `BackgroundFetch.scheduleTask` (`background_fetch is a dependency of `background_geolocation`, also created by me), then the OS *will* allow a foreground-service to be launched in the background.  It is crucial to provide `forceAlarmManager: true`, since Android allows foreground-service to be launched by `AlarmManager`, as described in [*Exemptions from background start restrictions*](https://developer.android.com/guide/components/foreground-services?authuser=4#background-start-restriction-exemptions)
- *Your app invokes an [exact alarm](https://developer.android.com/training/scheduling/alarms?authuser=4#exact) to complete an action that the user requests.*

```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print("didChangeAppLifecycleState] : $state");
    if (state == AppLifecycleState.paused) {
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 15000,
          periodic: false,
          forceAlarmManager: true          
      ));
    }
  }
  
  Future<void> initPlatformState() async {
    ...   

    BackgroundFetch.configure(BackgroundFetchConfig(
      minimumFetchInterval: 15,
      startOnBoot: true,
      stopOnTerminate: false,
      enableHeadless: true,
      requiresStorageNotLow: false,
      requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresDeviceIdle: false,
      requiredNetworkType: NetworkType.NONE
    ), (String taskId) async {
      print("[BackgroundFetch] received event $taskId");
      // Here is our scheduleTask handler when app went to background.
      if (taskId == 'com.transistorsoft.customtask') {
        print("********* CUSTOM TASK FIRED");
        // Test calling .start() while app is in the background <--------------------------
        bg.BackgroundGeolocation.start();
      }   
      BackgroundFetch.finish(taskId);
    });
  }    
```

I will research integrating this strategy directly within `background_geolocation` where required, when the app is detected to be in the background.

**Comment by christocracy** [comment]
Ok, I have a working implementation integrating the above strategy within `background_geolocation`.

While the plugin is `State.enabled == false` and the app in the background, it will be safe to call both `.start()` and `.getCurrentPosition()`.

It will be released soon.

**Comment by christocracy** [comment]
days

**Comment by christocracy** [comment]
Ok, I've pushed this to branch `android-ForegroundServiceStartNotAllowedException`

Please test it by installing the plugin from Git:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: git://github.com/transistorsoft/flutter_background_geolocation.git
      ref: android-ForegroundServiceStartNotAllowedException
```

Logs of executing `.getCurrentPosition()` in the background while the plugin is `State.enabled == true`:

```
05-06 12:06:39.926 29301 29301 D TSLocationManager: [c.t.l.adapter.LifecycleManager onPause]
05-06 12:06:39.927 29301 29301 D TSLocationManager: [c.t.l.adapter.LifecycleManager onStop]

05-06 12:06:40.066  1128  1375 D ActivityManager: Received BROADCAST intent 0x1913dc0 Key{broadcastIntent pkg=com.google.android.gms/com.google.android.gms.location_base intent=act=com.google.android.location.ALARM_WAKEUP_LOCATOR flags=0x4000000 u=0} requestCode=0 sent=0 from uid 1000
05-06 12:06:40.171  1128  1197 I ActivityManager: Changes in 10080 5 to 15, 8 to 0


05-06 12:06:44.885 29301 29399 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot]
05-06 12:06:44.885 29301 29399 I TSLocationManager:   ⏰ Scheduled OneShot: GET_CURRENT_POSITION in 1ms (jobID: -1291368648)


05-06 12:06:49.892  1128  1375 D ActivityManager: Received BROADCAST intent 0x159773d Key{broadcastIntent pkg=com.transistorsoft.flutterbackgroundgeolocationexample intent=act=GET_CURRENT_POSITION cmp=com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.scheduler.ScheduleAlarmReceiver flags=0x2000000 u=0} requestCode=-1291368648 sent=0 from uid 1000

05-06 12:06:49.907 29301 29399 I TSLocationManager: [c.t.l.scheduler.ScheduleEvent onOneShot]
05-06 12:06:49.907 29301 29399 I TSLocationManager: ╔═════════════════════════════════════════════
05-06 12:06:49.907 29301 29399 I TSLocationManager: ║ ⏰ OneShot event fired: GET_CURRENT_POSITION
05-06 12:06:49.907 29301 29399 I TSLocationManager: ╠═════════════════════════════════════════════
05-06 12:06:49.912 29301 29399 D TSLocationManager: [c.t.locationmanager.util.c h]
05-06 12:06:49.912 29301 29399 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted

05-06 12:06:49.959  1128  7235 I ActivityManager: Background started FGS: Allowed [callingPackage: com.transistorsoft.flutterbackgroundgeolocationexample; callingUid: 10366; uidState: LAST; intent: Intent { act=2:2 cmp=com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.service.LocationRequestService (has extras) }; code:LOCATION_PROVIDER; tempAllowListReason:<null,reasonCode:LOCATION_PROVIDER,duration:20000,callingUid:10236>; targetSdkVersion:31; callerTargetSdkVersion:31; startForegroundCount:0; bindFromPackage:null]
05-06 12:06:49.959  1128  7235 I ActivityManager: Changes in 10366 15 to 4, 0 to 8

05-06 12:06:49.962  1128  7235 D ActivityManager: Received SERVICE intent 0x9421dd7 Key{startForegroundService pkg=com.transistorsoft.flutterbackgroundgeolocationexample intent=act=2:2 cmp=com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.locationmanager.service.LocationRequestService flags=0x2000000 u=0} requestCode=0 from uid 10236

05-06 12:06:49.984 29301 29301 D TSLocationManager: [c.t.l.service.AbstractService a]
05-06 12:06:49.984 29301 29301 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
05-06 12:06:49.988 29301 29399 I TSLocationManager: [c.t.l.s.LocationRequestService b]
05-06 12:06:49.988 29301 29399 I TSLocationManager: ╔═════════════════════════════════════════════
05-06 12:06:49.988 29301 29399 I TSLocationManager: ║ getCurrentPosition LocationResult: 2
05-06 12:06:49.988 29301 29399 I TSLocationManager: ╠═════════════════════════════════════════════
05-06 12:06:49.988 29301 29399 I TSLocationManager: ╟─ 📍  Location[fused 45.518807,-73.600653 hAcc=12.679 et=+3d2h19m54s160ms alt=44.70000076293945 vAcc=1.0 {Bundle[EMPTY_PARCEL]}], age: 33ms, time: 1651853209952
```

**Comment by christocracy** [comment]
Take special note of this log, where the fg-service launch request is evaluated by the OS — This is where the exception was previously thrown but now is “*Allowed*”:

“FGS” = foreground service
> ActivityManager: Background started FGS: Allowed

This is a very sweet little trick to take advantage of `AlarmManager` 1ms one-shots to bypass new launch restrictions.  In reality, though, the one-shot takes about 3-5s to fire, which is reasonable.

the plugin already implements a versatile and easily extendable `AlarmManager` one-shot mechanism already used throughout (Eg `stopTimeout` timer, scheduler), so it was a very easy feature to add without affecting much.  Basically identical to .scheduleTask() from `background_fetch`.

**Comment by mikehardy** [comment]
Wow, what a mess - 🤞 this persists in Android 13, we have another 6 months or so of runway at least before the next batch of "it's your device but one rotten apple means we'll lock it down so you can't use it the way you want" changes come through

**Comment by christocracy** [comment]
@mikehardy should be good for at least 3 years.  Yea, It’s like inflation for permissions.  

Some of these restrictions seem only to make things more difficult while being less energy efficient.

**Comment by christocracy** [comment]
@mikehardy The good news for Android 12 is keeping fg services alive will prevent the old “*Service failed to call startForeground in time*” error.

**Comment by ozzy1873** [comment]
This appears to be fixed. Closing.
