### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#705]
## Your Environment
NOTE: This exception is occurring with the previous stable version of flutter. This "flutter doctor" was generated after upgrading to Flutter 2.10. 
* Plugin version: 4.3.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Galaxy S21 5G
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.10.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:/Users/john/AppData/Local/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:/Users/john/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)  • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
This Exception always occurs in the background.
  bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior
No Exception

## Actual Behavior
Fatal Exception: java.lang.IllegalArgumentException: com.xxx.xxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
       at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
       at com.intentfilter.androidpermissions.PermissionManager.notificationDismissIntent(PermissionManager.java:32)
       at com.intentfilter.androidpermissions.PermissionManager.showPermissionNotification(PermissionManager.java:23)
       at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:52)
       at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:38)
       at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:2)
       at com.transistorsoft.locationmanager.util.c$i.run(c.java:15)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

1. I am unable to reproduce this issue.
2.
3.
4.

## Context
I don't know the context.

## Debug logs

<details>
	<summary>Logs</summary>
No logs available.

</details>

**Comment by christocracy** [comment]
I've never experienced this myself on my *Pixel 3a @ 12* (I've been developing on Android 12 since last summer).

However, I see an issue posted at the [android-permissions](https://github.com/nishkarsh/android-permissions/issues/25) repo referencing this as few days ago.

**Comment by ozzy1873** [comment]
I found this:
https://stackoverflow.com/questions/70121129/flutter-app-targeting-android-12-crashes-flag-immutable-or-flag-mutable-to-be

**Comment by christocracy** [comment]
Yes, of course.  That's the first thing that thing that crashed for me when I first configured my `targetSdkVersion` for *Android S* last summer.

Whenever this BackgroundGeolocation SDK creates a `PendingIntent`, it uses a helper method to apply the appropriate flags.

```java
public static int getPendingIntentFlags(int flag) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            return (flag | PendingIntent.FLAG_MUTABLE);
        } else {
            return flag;
        }
    }
```

The error is not caused by BackgroundGeolocation, it's caused by one of its dependencies, [`android-permissions`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L69)

Can you tell me how to reproduce it?  I test on two Android 12 devices here and I've never received this error.

**Comment by ozzy1873** [comment]
It happens in the field and I have never seen it myself. I have not been able to reproduce it. Fortunately, I have only seen it happen a couple times. I will make the change described in that link I sent and see what happens.

**Comment by christocracy** [comment]
> I will make the change described in that link I sent and see what happens.

You can't make that change in that link.  We have to wait for `android-permissions` to release a new version.

**Comment by ozzy1873** [comment]
Ah ok, thanks!

**Comment by christocracy** [comment]
I plan to push another release this week with updated `android-permissions` version.  It requires some slight modifications in the plugin to support it.

**Comment by ozzy1873** [comment]
@christocracy Any word on when this might be fixed?

**Comment by ozzy1873** [comment]
This appears to be fixed. Closing.
