### ISSUE TITLE
Is there a way to disable the many notification sounds while in background?

### ISSUE THREAD

**Issue by gudkjon** [transistorsoft/flutter_background_geolocation#709]
## Your Environment
* Plugin version: 4.3.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S8
* Flutter info (`[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-IS)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.0)
[✓] Connected device (2 available)

• No issues found!`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
            title: "Allow {applicationName} to access to this device's location in the background?",
            message: "In order to track your location in the background, please enable {backgroundPermissionOptionLabel} location permission",
            positiveAction: "Change to {backgroundPermissionOptionLabel}",
            negativeAction: "Cancel"
        )
    )
```

## Expected Behavior

That while in background, the app would not be making many notification sounds.
## Actual Behavior

While in background, the app makes many notification sounds.
## Steps to Reproduce

1. Activate background location tracking
2. Put app in background
3. Move around

## Context

While track background location, since the background tracking is intended to be in use for long periods of time by a driver, the sounds might become annoying.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
No relevant logs
```

</details>

**Comment by christocracy** [comment]
Duplicate #356.  See API docs `Config.debug`.
