### ISSUE TITLE
geofence Exit event is not triggered

### ISSUE THREAD

**Issue by yashshah16** [transistorsoft/flutter_background_geolocation#71]
We are using geofence.In this, first of all we are adding geofence of one location and after adding it only enter and dwelling events are triggering.As per documentation exit event should be triggered but it does not.

## Your Environment
* Plugin version: ^0.3.4
* Platform: Android
* OS version: Mac
*Flutter version 1.2.1 and dart version 2.1.2

*plugin configuration:
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;

My CODE for add geofence: 

 //set event
    bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) {
      print('geofence event');
      print(event);
      if (event.identifier == 'GYM_ZONE') {
        if (event.action == 'ENTER') {
          print("here is enter condition");          
        } else if (event.action == 'EXIT') {
          print("here is exit condition");
        } else {
          print("here is dwelling condition");
        }
      } else {
        ToastMessage.toastMessage("You are not at gym.", false);
      }
    });

    //add geofence
    bg.BackgroundGeolocation.addGeofence(bg.Geofence(
        identifier: "GYM_ZONE",
        radius: 200,
        latitude: locationLatitude,
        longitude: locationLongitude,
        notifyOnEntry: true,
        notifyOnExit: true,
        notifyOnDwell: true,
        loiteringDelay: 10000,
        extras: {}));

    //geofence ready function
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            url: 'http://your.server.com/locations',
            stopOnTerminate: false,
            startOnBoot: true,
            autoSync: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            reset: true))
        .then((bg.State state) {
     

      bg.BackgroundGeolocation.start();

      bg.BackgroundGeolocation.startGeofences();
    });

## Expected Behavior
All events (ENTER, EXIT, DWELL) should be triggered.

## Actual Behavior
But only ENTER and DWELL events are triggered.Exit event is not triggered.

So, can you please go through with our problems and let us know what should we have to do for solve this problems.

Thank you.

**Comment by christocracy** [comment]
You do not execute both `#start` and `#startGeofences`.  You chose 1 or the other.  

`#start` = track location + geofences
`#startGeofences` = geofences only.

Also, the latest version is [`1.0.7`](https://pub.dev/packages/flutter_background_geolocation/versions/1.0.7).  You should upgrade ASAP.

**Comment by Vish88781** [comment]
is there any to purchase lincense key to run this service

**Comment by Vish88781** [comment]
any**any need

**Comment by christocracy** [comment]
This plugin is fully functional in debug builds so you can try before you buy.

**Comment by Vish88781** [comment]
Its not working(ongeofence ) in my Samsung phone Android 11 and My Samsung
model is A30 ..please check it out

**Comment by christocracy** [comment]
You are posting on a closed issue from over two years ago.  Post a new issue.  See wiki *Debugging*.

This plugin is tested daily on the following devices:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by Vish88781** [comment]
I understand that you want to say that  your plugin work in every mobile
device but i check by myself that it will not work in my device Samsung A30
while the same code work in my friend device it takes me 7 days to find out
this unsupporting plugin issue in some devices

**Comment by christocracy** [comment]
This two year old issue is closed.

**Comment by Vish88781** [comment]
Thanks for your timely response
