### ISSUE TITLE
android12 notification

### ISSUE THREAD

**Issue by Kimhyunsu92** [transistorsoft/flutter_background_geolocation#714]
## Your Environment
* Plugin version: 4.3.4
* Platform: Android
* OS version: 12
* Device manufacturer / model: samsung note 20
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
* Plugin config:
```
bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            stopOnTerminate: false,
            startOnBoot: true,
            preventSuspend: true,
            enableHeadless: true,
            debug:
                false,
            motionTriggerDelay:
                5000, 
            stopTimeout: 1,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
)
```

## Expected Behavior
notification does not disappear after updating to Android 12.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you observing the logs for anything unusual?

Are you calling `.start()`?

**Comment by Kimhyunsu92** [comment]
```
bg.BackgroundGeolocation.ready(
        bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            stopOnTerminate: false,
            startOnBoot: true,
            preventSuspend: true,
            enableHeadless: true,
            debug:
                false, 
            motionTriggerDelay:
                5000,
            stopTimeout: 1,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      ).then((bg.State state) {
        if (!state.enabled) {
          bg.BackgroundGeolocation.start();
        }
      });
```

Of course, it's the full code for the 'BackgroundGeolocation.ready()' function. Nothing has been confirmed for log, and notification is always being output after updating Android 12 version. Notification was output only when 'isMoving' was true in Android version 11, but notification continues to be shown in Android version 12.

**Comment by christocracy** [comment]
> notification does not disappear after updating to Android 12.

I misread your description.

Yes, this is the new behavior required by changes in Android 12.
