### ISSUE TITLE
Error 408 with Cellphone Data with no Internet Conection App Freeze

### ISSUE THREAD

**Issue by smlertek** [transistorsoft/flutter_background_geolocation#716]
## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version:  7
* Device manufacturer / model: Motorola e4 Plus
* Flutter info (`flutter doctor`): Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  state = await bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        url: "",
        params: null,
        extras: null,
        enableTimestampMeta: true,
        forceReloadOnBoot: true,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        heartbeatInterval: intervaloGps,
        enableHeadless: true,
        preventSuspend: true,
        autoSync: true,
        autoSyncThreshold: 0,
        maxBatchSize: 0,
        batchSync: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_OFF,
        reset: true,
      ),
    );
```
After this part of code its freezees and the returns the 408 

## Expected Behavior
It should continue giving Gps positions even if the user doesn´t have cellphone data balance

## Actual Behavior
- App gets freeze
- No Locations Updates
- Error 408

## Steps to Reproduce
1. Start the App with cellphone data ON but with no balance $$$ so we have no internet connection available.

## Debug logs
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
First this was the log 
I/flutter (27324): [BackgroundGeolocation onLocation] ‼️ Uncaught location error: PlatformException(408, null, null, null).  You should provide a failure callback as 2nd argument.

Then we add the callback function
 03-01 11:44:46.397 19431-19554/mdc.lertek I/flutter: [LocationError code: 408, message: ]
```

</details>

**Comment by christocracy** [comment]
See Api docs LocationError.

https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/LocationError-class.html

**Comment by smlertek** [comment]
Is there a way i can make that the app doesn´t freeze?, i added the failure fuction on bg.BackgroundGeolocation.onLocation() to print the error but it still the same

**Comment by christocracy** [comment]
See the onLocation docs and provide the onError callback as 2nd arg.
