### ISSUE TITLE
enable or disable gps hangs the touch of all applications.

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#717]
## Your Environment
* Plugin version: 4.3.4
* Platform: Android 11
* OS version: 
* Device manufacturer / model: SAMSUMG A70 ANDROID 11
 
I do not have any log report, what happens is the following.

in a samsumg a50, a70 model, when i deactivate the gps or activate it, the touch stops in all my applications, but in other phone models it does not happen, I have my XIAOMI mi 11t and this problem does not happen.

I don't know what it could be, but when I uninstall the application it doesn't happen anymore, so does it mean that it has something to do with my application, precisely with the GPS that the touch hangs, could it be affecting the library?

**Comment by miguelflores1993** [comment]
https://user-images.githubusercontent.com/67565934/156581378-c362e905-29ea-488b-9d0e-f2e8fccb8cf0.mp4

Here I have a video of more or less what happens in an A70.

I activate the GPS and the touchpad is disabled and I can no longer click.

I have to do a back, to get it working again, and I'm having these problems on several phones. but in other models it does not happen.

**Comment by miguelflores1993** [comment]
@christocracy pls help urgent

Please I need urgent help, I just replied with your sample application.
and the same problem happens, here I have a video

https://user-images.githubusercontent.com/67565934/156598282-cb774c80-89f3-4326-b361-4e83f778cb25.mp4

photo cell 
![Screenshot_20220303-114010_Settings](https://user-images.githubusercontent.com/67565934/156598849-112f4871-95b7-4372-9ad4-8179f245fd5d.jpg)

**Comment by christocracy** [comment]
I’m on vacation until next week.

try Config.disableLocationAuthorizationAlert `true`

**Comment by miguelflores1993** [comment]
> I’m on vacation until next week.
> 
> try Config.disableLocationAuthorizationAlert `true`

could you verify this problem?

**Comment by christocracy** [comment]
You have not posted your Config as requested in the issue template
