### ISSUE TITLE
Error: License Validation Failure

### ISSUE THREAD

**Issue by rbarbosas** [transistorsoft/flutter_background_geolocation#718]
Hello, we are having problems publishing the APP with the initial ApplicationID that we registered with the library, because of that we need to make the change, but we start to receive a license error message, how can we solve it? 

* Plugin version: 1.10
* Platform: iOS or Android: ANDROID
* OS version: 11
* Device manufacturer / model: Samsung A51

**Comment by christocracy** [comment]
Please email info@transistorsoft.com for licensing questions.
