### ISSUE TITLE
[Question] [iOS] Automatically set the location permission level to always

### ISSUE THREAD

**Issue by ehhc** [transistorsoft/flutter_background_geolocation#72]
If i use your plugin the user is asked to set the location permission to `Always`. Therefore, he is required to manually go to the settings page and change the permission. 
Wouldn't it be possible to set the `Always` permision directly from the plugin?
Alas, i don't have any iOS experience... but to me this: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization#2926833 sounds like it should be possible..

Would it?

**Comment by christocracy** [comment]
Do you have some other plugin (eg: map module) which is requesting location permission before you `BackgroundGeolocation.start()`?

**Comment by ehhc** [comment]
yes, i access the current location previously. Is that the reason why the user has to change the settings later manually?

**Comment by christocracy** [comment]
Yes.

**Comment by ehhc** [comment]
okay. thanks for the quick reply. I'll have a look :)
