### ISSUE TITLE
How to disable locationAuthorization alert on ready()?

### ISSUE THREAD

**Issue by HugoHeneault** [transistorsoft/flutter_background_geolocation#723]
## Your Environment
* Plugin version: `4.3.4`
* Platform: Android
* OS version:  ` macOS 12.2.1 21D62 darwin-arm`
* Device manufacturer / model: Apple  macbook pro M1 Max
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```
* Plugin config:
```dart 
await bg.BackgroundGeolocation.ready(bg.Config(
        // Logging & Debug
        reset: true,
        debug: false,
        locationAuthorizationRequest: 'WhenInUse',
        locationAuthorizationAlert: {
          'titleWhenNotEnabled':
              'Veuillez activer votre GPS pour suivre votre trace',
          'titleWhenOff': 'Veuillez activer votre GPS pour suivre votre trace',
          'instructions':
              'Vous devez autoriser le GPS pour afficher votre position sur la carte et enregister votre trace',
          'cancelButton': 'Annuler',
          'settingsButton': 'Ouvrir les paramètres'
        },
        logLevel: kReleaseMode
            ? bg.Config.LOG_LEVEL_WARNING
            : bg.Config.LOG_LEVEL_DEBUG,
        // Geolocation options
        activityType: bg.Config.ACTIVITY_TYPE_FITNESS,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        showsBackgroundLocationIndicator: true,
        distanceFilter: 1,
        stopTimeout: 1,
        stopOnTerminate: true,
        heartbeatInterval: 60,
        desiredOdometerAccuracy: desiredOdometerAccuracy,
        isMoving: true,
        disableStopDetection: true,
        preventSuspend: true,
        pausesLocationUpdatesAutomatically: false,
        foregroundService: true,
        disableLocationAuthorizationAlert: true,
      ));
```

## Expected Behavior
App should ask for authorization on `start` call instead of `ready` call, or provide a way to trigger authorization manually.

## Actual Behavior
On first boot the plugin waits for `ready` to be called before showing `locationAuthorization` alert.
On next boots, as soon as the app boots (*before* `ready` is called), when app doesn't have authorization, it shows `locationAuthorization` alert.

## Context
We'd like to show the native alert during onboarding so we can explain user why we need location before opening alert

Thanks for this great plugin Chris!

**Comment by christocracy** [comment]
Show me a screenshot of what you think is “locationAuthorizationAlert”.

**Comment by HugoHeneault** [comment]
<img width="327" alt="CleanShot 2022-03-14 at 14 04 59@2x" src="https://user-images.githubusercontent.com/4112256/158177709-fa28269f-3540-4576-be1b-4d2a39412919.png">

**Comment by christocracy** [comment]
This is not `locationAuthorizationAlert`.  This is the OS permission dialog.  The plugin will automatically request location permission whenever `state.enabled` is true and the plugin asked to request a location.

The plugin's `state.enabled` **is persisted** between app restarts / device reboots.

If you launch your app and call `start()`, then next time your app launches:

```dart
BackgroundGeolocation.ready(config).then((State state) {
  print('*** state.enabled: ${state.enabled}');  // <-- will be true
});
```

**Comment by christocracy** [comment]
- Calling `.start()` persists `state.enabled -> true`.
- Calling `.stop()` persists `state.enabled -> false`.
- Calling `.ready()` with `state.enabled == true` and location permission denied will necessarily cause the plugin to request permission so it can operate.

**Comment by HugoHeneault** [comment]
Oh great. Thanks for these details. 

Do I have a way to set `enabled` to false before calling `ready`? Calling `stop` before `ready` shouldn't work?

**Comment by christocracy** [comment]
Why would you do that??

**Comment by HugoHeneault** [comment]
We'd like to show a custom screen when authorizations are not given before showing the `OS` alert. 
If `state` is true we will immediately got the `OS` alert.
