### ISSUE TITLE
bg.Logger.uploadLog throws an exception without error details

### ISSUE THREAD

**Issue by cto-seak-global** [transistorsoft/flutter_background_geolocation#724]
## Your Environment
* Plugin version: 4.3.4
* Platform: Android
* OS version: 11
* Device manufacturer / model: Ulefone Armor 11 5G
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    final config = bg.Config(
      reset: true,
      debug: _appConfig.debugMode,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      disableStopDetection: true,
      preventSuspend: true,
      backgroundPermissionRationale: bg.PermissionRationale(
        title: permissionRationale.titleKey.tr(),
        message: permissionRationale.messageKey.tr(),
        positiveAction: permissionRationale.positiveActionKey.tr(),
        negativeAction: permissionRationale.negativeActionKey.tr(),
      ),
      distanceFilter: 18.0,
      activityRecognitionInterval: 20000,
      stopOnTerminate: false,
      useSignificantChangesOnly: device.useSignificantChangesOnly,
      startOnBoot: true,
      url: '${_appConfig.appEngineUrl}/location/update',
      authorization: bg.Authorization(
        accessToken: credentials.accessToken,
        refreshToken: credentials.refreshToken,
        refreshUrl: _appConfig.refreshTokenUrl,
        refreshPayload: <String, String>{
          'refresh_token': '{refreshToken}',
          'grant_type': 'refresh_token',
        },
      ),
      params: <String, dynamic>{
        'device': {
          'deviceTypeCode': device.typeCode,
          'deviceId': device.deviceId,
          'deviceName': device.name,
          'locationAuthorisation': describeEnum(device.locationAuthorisation),
          'accuracyAuthorisation': describeEnum(device.accuracyAuthorisation),
        }
      },
      logLevel: _getLogLevel(device.locationLogging),
      enableHeadless: true,
      heartbeatInterval: 60 * heartbeatIntervalMinutes,
    );
    await bg.BackgroundGeolocation.ready(config);
```

## Expected Behavior
When uploading logs, I expect the upload either to succeed or to fail with a helpful error code

## Actual Behavior
A platform exception is generated, containing no error information (status code and all other exception parameters are null or empty).

## Steps to Reproduce

1. At any point in the code, make a call to `bg.Logger.uploadLog()` with a valid URL.
2.
3.
4.

## Context

I was trying to upload logs to our server in response to a silent push notification.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Not currently available -- will attempt to add
```

</details>

**Comment by cto-seak-global** [comment]
I'm trying to get hold of that now

**Comment by cto-seak-global** [comment]
--------- beginning of crash
--------- beginning of system
--------- beginning of main
03-15 14:12:38.115 19139 19309 I TSLocationManager: - Enable: true → true, trackingMode: 1

**Comment by christocracy** [comment]
Ensure verbose logging

**Comment by christocracy** [comment]
And don’t provide a filter to logcat (-s, *:S)

**Comment by cto-seak-global** [comment]
Looks like it's some kind of file permission denial

**Comment by christocracy** [comment]
It works here on my *Google Pixel 3a @ Android 12*.

Can you try on a different device?

**Comment by christocracy** [comment]
```
BackgroundGeolocation.uploadLog('http://192.168.11.40:9000').
```
I see the request arrive at my demo server running on my localhost.

**Comment by cto-seak-global** [comment]
Will try on my iPhone. I note that the `emailLogs` function works correctly, so whatever that does to access the log.gz file works correctly.

**Comment by christocracy** [comment]
Your reported problem was from Android.  It’s pointless to test ios.

**Comment by cto-seak-global** [comment]
OK. I can't connect using am emulator, so until I can get hold of another device I'm stuck with my Ulefone.

I'll see if I can run the example.

**Comment by christocracy** [comment]
The example uses emailLog.  You have to manually change the code to uploadLog

**Comment by cto-seak-global** [comment]
I've done some digging, and found a few things:

-- When I remove authentication from the endpoint at the back end, the call succeeds.
-- There do not appear to be any authentication headers passed to the endpoint.

The lack of errors appears to be because my back end is not sending the correct error messages back, but I would expect the call to the back end to have the same authentication headers as the location update URL.

**Comment by christocracy** [comment]
It might be true that the plugin is neglecting to add Authorization headers to the request.

**Comment by cto-seak-global** [comment]
Also, `req.body` is coming up as empty on my server.

**Comment by christocracy** [comment]
It’s a multi part form submission.  The log file is a file attachment.

you won’t find it in req.params

**Comment by christocracy** [comment]
req.params

**Comment by cto-seak-global** [comment]
I didn't find it in `req.params`, but the metadata isn't necessary for my use case. Using formidable, the file was available from the multipart form.

Is there a way to include the authorisation headers manually, as those are necessary in order to get a full audit?

**Comment by christocracy** [comment]
You could try adding directly to Config.headers.

**Comment by cto-seak-global** [comment]
Just for reference, there are also no auth headers sent from iOS. The code comes back as "0" in that case.
