### ISSUE TITLE
Callback methods not working  

### ISSUE THREAD

**Issue by Teja-Batchu** [transistorsoft/flutter_background_geolocation#725]
My application not getting callbacks from the library. 

## Your Environment
  Plugin Version: flutter_background_geolocation: ^4.3.4
  Android
 Version:  Android 11
 Device Model: Samsung SM-A217F

Flutter info:
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/teja/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/teja/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

bg.BackgroundGeolocation.ready(bg.Config(
        enableHeadless: true,
        stopOnTerminate: false,
        startOnBoot: true,
        reset: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 3.0,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel')))
        .then((bg.State state) {

      print("[ready] ${state.toMap()}");

      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('CLUTestPrint [start] success started $state');
        _enabled = state.enabled;
        // _isMoving = state.isMoving;
      }).catchError((error) {
        print('CLUTestPrint [start] starting failed ERROR: $error');
      });

    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
```

## Expected Behavior

I am expecting the below methods will trigger based on movement.

  void _onLocation(bg.Location location) {
    print(' onLocation - $location');

    String odometerKM = (location.odometer / 1000.0).toStringAsFixed(1);
    print("Data inJson ${location.toMap()}");
    print("ODO meter InKm ${odometerKM}");

  }

  void _onLocationError(bg.LocationError error) {
    print('ERROR - $error');
  }

  void _onMotionChange(bg.Location location) {
    print('motion change - $location');

    print('[motionchange] - $location');
    
  }

## Actual Behavior
callback methods not trigging.

## Context
Whenever user start tracking i am calling this 

bg.BackgroundGeolocation.start().then((bg.State state) {
      print('[start] success started $state');
      _enabled = state.enabled;
      // _isMoving = state.isMoving;
    }).catchError((error) {
      print('[start] starting failed ERROR: $error');
    });

Here I am getting success. After successfully BackgroundGeolocation started I am expecting callback function will trigger when the user moves. but here it is not happening.

## Debug logs

╔═════════════════════════════════════════════
║ TSLocationManager version: 3.1.37 (393)
╠═════════════════════════════════════════════
╟─ samsung SM-A217F @ 11 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
    "message": "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": "Cancel"
  },
  "batchSync": false,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": false,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 129769.8125,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSL Accelerometer", vendor="STM", version=1, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.15, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSL Gyroscope", vendor="STM", version=1, type=4, maxRange=17.45326, resolution=6.1086525E-4, power=0.65, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918C Magnetometer", vendor="Asahi Kasei Microdevices", version=1, type=2, maxRange=4899.9976, resolution=0.06, power=1.1, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.16, minDelay=-1}
╚═════════════════════════════════════════════
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/8302330/background-geolocation.log)

**Comment by christocracy** [comment]
Show me in your code where you have registered to the plug-in’s `onLocation` event.

**Comment by Teja-Batchu** [comment]
Please find the below code for your ref

```

  @override
  void initState() {
  super.initState();
  
    _initPlatformState();
  }

  Future<Null> _initPlatformState() async {
    // 1.  Listen to events (See docs for all 12 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
            enableHeadless: true,
            stopOnTerminate: false,
            startOnBoot: true,
            reset: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 3.0,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow Clu to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel')))
        .then((bg.State state) {
      print("[ready] ${state.toMap()}");
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
  }

  void _onLocation(bg.Location location) {
    print(' CLUTestPrint onLocation - $location');

    String odometerKM = (location.odometer / 1000.0).toStringAsFixed(1);
    print("Data inJson ${location.toMap()}");
    print("ODO meter InKm ${odometerKM}");

    print('[motionchange] - $location');
    int timeStamp = (DateTime.now().millisecondsSinceEpoch ~/ 1000).toInt();

    Globals.updateLiveLocationToServer(
      timeStamp,
      location.coords.latitude,
      location.coords.longitude,
      location.coords.accuracy,
      location.coords.heading,
      location.coords.altitude,
      location.coords.speed,
      location.coords.speedAccuracy,
    );
    Globals.saveDataInFile(
        "onMotionChange change Triggered battery: ${location.battery.level}, timeStamp: ${location.timestamp}, latitude: ${location.coords.latitude}, longitude: ${location.coords.longitude}, gpsAccuracy: ${location.coords.accuracy}, heading: ${location.coords.heading}, altitude: ${location.coords.altitude}, speed: ${location.coords.speed}, speedAccuracy: ${location.coords.speedAccuracy}");
  }

  void _onLocationError(bg.LocationError error) {
    print('CLUTestPrint ERROR - $error');
  }

  void _onMotionChange(bg.Location location) {
    print('CLUTestPrint motion change - $location');

    print('[motionchange] - $location');
    int timeStamp = (DateTime.now().millisecondsSinceEpoch ~/ 1000).toInt();

    Globals.updateLiveLocationToServer(
      timeStamp,
      location.coords.latitude,
      location.coords.longitude,
      location.coords.accuracy,
      location.coords.heading,
      location.coords.altitude,
      location.coords.speed,
      location.coords.speedAccuracy,
    );
    Globals.saveDataInFile(
        "onMotionChange change Triggered battery: ${location.battery.level}, timeStamp: ${location.timestamp}, latitude: ${location.coords.latitude}, longitude: ${location.coords.longitude}, gpsAccuracy: ${location.coords.accuracy}, heading: ${location.coords.heading}, altitude: ${location.coords.altitude}, speed: ${location.coords.speed}, speedAccuracy: ${location.coords.speedAccuracy}");
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[activitychange] - $event');
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    print('$event');
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    print('$event');
  }

```

Once initilisation done I will start tracking service based on user actions 

 ```
callStartServiceInNative() async {
    ////
    // 3.  Start the plugin.
    //

    bg.BackgroundGeolocation.start().then((bg.State state) {
      print('CLUTestPrint [start] success started $state');
      _enabled = state.enabled;
      // _isMoving = state.isMoving;
    }).catchError((error) {
      print('CLUTestPrint [start] starting failed ERROR: $error');
    });
  }
```

**Comment by christocracy** [comment]
How are you testing your app?  Are you going outside for at least 1km walk?

**Comment by Teja-Batchu** [comment]
Yes, i went more than 1.5 km.

**Comment by christocracy** [comment]
See https://dontkillmyapp.com

**Comment by Teja-Batchu** [comment]
In this application, continuously i am getting blip sound (location updated). I tested more than 1hour, application not killed, it continuously recorded my location but callback methods are not fired.

**Comment by christocracy** [comment]
The plugin doesn’t fail to call events.  When the blip is heard, the callback (if you’re listening to it) is called.

Check your code carefully.  You’re doing something wrong.  Simplify.

**Comment by Teja-Batchu** [comment]
I am using the below dependencies in my app maybe some dependency creating an issue. Please check and help  us

`dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.4
  provider: ^6.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  progress_dialog: ^1.2.4
  url_launcher: ^6.0.0-nullsafety
  get_version: ^0.2.2
  syncfusion_flutter_gauges: ^19.3.47
#  syncfusion_flutter_charts: ^19.3.47
  charts_flutter: ^0.12.0
  fl_chart: ^0.40.2
  image_picker: ^0.8.4+3
  flutter_native_image: ^0.0.6+1
  syncfusion_flutter_charts: ^19.3.47
  pin_entry_text_field: ^0.1.4
  shimmer: ^2.0.0
  google_maps_flutter: ^2.1.0
  maps_launcher: ^2.0.1
  email_validator: ^2.0.1
  #  firebase_core : ^0.5.0
  flutter_voip_push_notification: ^0.0.3
  pie_chart: ^5.1.0
  flutter_local_notifications: ^9.0.1
  rxdart: ^0.27.2
  fluttertoast: ^8.0.8
  flutter_svg: ^0.23.0+1
  geocoder: ^0.2.1
  multi_image_picker2: ^5.0.2
  flutter_absolute_path: ^1.0.6
  geolocator: ^8.0.3
  workmanager: ^0.4.1
  location: ^4.3.0
  geocoding: ^2.0.1
  firebase_analytics: ^8.3.4
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  firebase_crashlytics: ^2.2.4
  flutter_background_geolocation: ^4.3.4
  permission_handler: ^8.3.0
  foreground_service: ^2.0.1+1
  battery: ^2.0.3
  device_info_plus: ^3.2.1

  path_provider: ^2.0.8
  syncfusion_flutter_calendar: ^19.4.55

`

**Comment by christocracy** [comment]
I suggest you generate a new flutter hello world and test the plugin a simple test-case

**Comment by Teja-Batchu** [comment]
Now I am getting callbacks,

`foreground_service: ^2.0.1+1` library creating an issue in my app. After I commented that library. Everything working fine
