### ISSUE TITLE
Request on refreshUrl doesn't apply provided headers

### ISSUE THREAD

**Issue by gadishimwe** [transistorsoft/flutter_background_geolocation#727]
## Your Environment
* Plugin version: 4.3.4
* Platform: Android
* OS version: 10
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0.1 21A559 darwin-x64, locale en-RW)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        maxDaysToPersist: 1,
        maxRecordsToPersist: 3,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        heartbeatInterval: 60,
        httpRootProperty: '.',
        url: '${baseUrl}/location',
        locationTemplate:
            '{"latitude":"<%= latitude %>","longitude":"<%= longitude %>"}',
        headers: _headers,
        authorization: bg.Authorization(
          accessToken: _accessToken,
          refreshToken: refreshToken,
          refreshUrl: '${baseUrl}/token',
          refreshPayload: {
            refreshToken: '{refreshToken}',
          },
          expires: _accessToken != null
              ? JwtDecoder.getRemainingTime(_accessToken).inSeconds
              : null,
        ),
      )
```

## Expected Behavior

I expect the headers I provide to be applied to the refreshing token requests(on refreshUrl) the same way they are applied to the location update request.

## Actual Behavior

The refreshing token request use its own headers instead of using provided headers

## Context

I transfer the refresh token through the secure cookie and the plugin expects the refresh token to be in the request body. That's why it's important for me to send every request to the server with configured headers that contains the refresh token cookie.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It is correct that the token-refresh request does not currently append your configured `headers`.  

Show me an example of what your `Config.headers` actually look like.

**Comment by christocracy** [comment]
Try testing with branch `authorization-refresh-headers`:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: authorization-refresh-headers
```

**Comment by gadishimwe** [comment]
Thanks for the fast response. I'm testing it right now.
My headers that are relevant are:
```
{ 'Content-Type': 'application/json',
'cookie': 'refreshToken=THE_TOKEN;Domain=example.com;Expires=Sat;Path=/;SameSite=None',
    }

**Comment by gadishimwe** [comment]
But the key `refreshToken` in the cookie could be different

**Comment by gadishimwe** [comment]
Hey @christocracy, now it's working without providing `refreshPayload` and the headers are being sent

**Comment by gadishimwe** [comment]
So when are you planning to release this changes?

**Comment by christocracy** [comment]
It's perfectly fine to install this from GitHub in the meantime.

**Comment by gadishimwe** [comment]
Alright, thanks for the help and quick responses I appreciate🙏

**Comment by christocracy** [comment]
This fix is published to `4.3.5` now.

**Comment by gadishimwe** [comment]
Hey @christocracy, why can't the plugin make a request on `refreshUrl` even if you don't provide `refreshPayload`?

**Comment by christocracy** [comment]
If you read the docs carefully, the default (and only currently) Authorization Strategy is JWT (JSON web token).

That strategy requires a token provided in a form upload.

The refreshPayload is required since it defines the structure of the form, regardless if your server doesn't happen to be using it.

**Comment by gadishimwe** [comment]
Oh, I see. Thank you

**Comment by christocracy** [comment]
You shouldn't use Cookies with a mobile app.

Cookies are a web browser mechanism.

**Comment by gadishimwe** [comment]
I understand. I didn't have a choice. I had to use the same API endpoints as the ones web apps are using.
