### ISSUE TITLE
Heartbeat event fires at random time interval in Headless Mode

### ISSUE THREAD

**Issue by gadishimwe** [transistorsoft/flutter_background_geolocation#728]
## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung SM-G965F

* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0.1 21A559 darwin-x64, locale
    en-RW)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.0)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        maxDaysToPersist: 1,
        maxRecordsToPersist: 3,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true,
        heartbeatInterval: 60,
      ),
```

## Expected Behavior

Heartbeat event should be fired at provided `heartbeatInterval` even in headless mode(After the app is terminated).
## Actual Behavior

The heartbeat event is being fired randomly in headless mode. He's the comparison when the app is in FOREGROUND vs TERMINATED
![Screen Shot 2022-03-31 at 15 17 25](https://user-images.githubusercontent.com/52411901/161067409-266d4786-b9f6-4f11-b874-72177529b49c.png)
## Context

I was trying to make an HTTP call to the server every minute regardless of whether the app is opened or closed.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The heartbeat is subject to the OS constraints.  The OS does not want you to kill the user's battery.

**Comment by gadishimwe** [comment]
Oh, okay. Thanks.
So what's your suggestion if you want to constantly make some calls?

**Comment by christocracy** [comment]
Don't *expect* to constantly keep the CPU spinning.

Developers preventing the device CPU from sleeping is precisely why certain device manufacturers have responded with draconian measures to limit background-services from functioning according to the public Android API.  

This is why https://dontkillmyapp.com exists.
