### ISSUE TITLE
flutter_background_geolocation_helloworld.dart does not run

### ISSUE THREAD

**Issue by buntmeapp** [transistorsoft/flutter_background_geolocation#729]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android
* OS version: 
* Device manufacturer / model:
* Flutter info (`flutter doctor`): 
* helloworld> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.1)
[√] VS Code, 64-bit edition (version 1.66.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
As per Android Setup Guide
```

## Expected Behavior
app should run on emulator

## Actual Behavior
helloworld> flutter run --debug
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering
with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Wyn\Flutter\helloworld\android\app\build.gradle' line: 25
_<line 25 is: apply plugin: 'kotlin-android'>_
* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleDebug'...                             17.2s
Exception: Gradle task assembleDebug failed with exit code 1

## Steps to Reproduce

1. Created new application called helloworld
2. Copied and pasted the contents of flutter_background_geolocation_helloworld.dart into an empty main.dart
3. Added flutter_background_geolocation: ^4.4.0 to pubspec.yaml
4. Modified various configuration files as per Android Setup guide
5. flutter run --debug

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Show me your android/build.gradle

**Comment by buntmeapp** [comment]
`buildscript {
    ext.kotlin_version = '1.3.0'

    ext {
       compileSdkVersion   = 29                // or higher
       targetSdkVersion    = 29                // or higher
       appCompatVersion    = "1.0.2"           // or higher
       playServicesLocationVersion = "17.0.0"  // or higher
   }
    repositories {
        google()
        mavenCentral()
        jcenter() //added by WO
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven {
        // [required] flutter_background_geolocation
        url "${project(':flutter_background_geolocation').projectDir}/libs"
       }
       maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
       }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by christocracy** [comment]
This plugin does not use Kotlin at all.  Errors related to Kotlin have nothing to do with this plugin.

**Comment by buntmeapp** [comment]
Remove the Kotlin classpath from android\build.gradle? (It is one of the auto created parameters)

**Comment by christocracy** [comment]
You should not remove anything which is auto-generated, since those items would presumably be required by Flutter itself.

**Comment by christocracy** [comment]
I suggest you start from scratch again, with a freshly generated app.  First boot your app *without* installing the plugin.

Once it successfully boots, install the plugin and follow the installation steps.

**Comment by christocracy** [comment]
> jcenter() //added by WO

What is this?  [jcenter is deprecated](https://blog.gradle.org/jcenter-shutdown)

Jcenter should never exist in one's gradle files.

**Comment by buntmeapp** [comment]
jcenter() is mentioned in your Android Setup Guide ;-)

I did: First boot your app without installing the plugin.
Once it successfully boots, install the plugin and follow the installation steps.

I'm going around in circles re kotlin and gradle versions. arrrgggh

**Comment by christocracy** [comment]
> jcenter() is mentioned in your Android Setup Guide ;-)

The Setup Docs were written over two years ago.  Jcenter was deprecated last year.

The Setup docs instruct you to add **only the lines in green**.  It is assumed that the lines not in green already exist in your file.

**Comment by buntmeapp** [comment]
Thank you for your help.
