### ISSUE TITLE
Question: How to get location triggered by bluetooth?

### ISSUE THREAD

**Issue by vikramkapoor** [transistorsoft/flutter_background_geolocation#73]
I need to record and send location to a server when a Bluetooth button is clicked even when Android and iOS is in standby. Is there a recommended way to support this with flutter_background_location?

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Sorry, that’s not within the scope of this plugin.  You’d have to use some third party Bluetooth component.  If that component is able to respond in your desired states, you would execute #getCurrentPosition upon this plugin (or any other location plugin).

This is a location-tracking library, designed to automatically trigger location tracking when the device is moving (regardless of state; background, foreground, terminated)

**Comment by vikramkapoor** [comment]
OK. I will look into integrating Background Bluetooth. I already have an android:name=".App" in my application. Do I need to replace it with  android:name=".Application" for the following step?

**Comment by christocracy** [comment]
If you want to be able to respond to Android plugin events when your app is terminated, you would implement the [Android Headless Mode](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode)

**Comment by vikramkapoor** [comment]
Thanks. That works.
