### ISSUE TITLE
I am not able to display notfication popup on screen when app is open and screen is lock any solution

### ISSUE THREAD

**Issue by amelioratesolutions** [transistorsoft/flutter_background_geolocation#730]
FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        // viewShowRide == true;
        if (message.data != null &&
            message.data['title'] != null &&
            message.data['body'] != null) {
          var title = message.data['title'];
          var body = message.data['body'];
          print('************Push Listen*************');
          print("SOCKET");
          print(title.toString());
          print(body.toString());
          // Parse the message received
          PushNotification _notificationInfo = PushNotification(
            title: title,
            body: body,
          );

          showSimpleNotification(
            Text(_notificationInfo.title,
                  style: Theme
                      .of(context)
                      .textTheme
                      .headline3
                      .copyWith(color: whiteColor)),

            subtitle: Text(
              _notificationInfo.body,
              style: Theme
                  .of(context)
                  .textTheme
                  .headline2
                  .copyWith(color: whiteColor),
            ),
            background: textLight,
            duration: Duration(seconds: 5),
          );
        } else {

          // show popup when value is true

          setState(() {
            bookingArrive == true ? viewShowRide = true : false;
          });

          PushNotification _notificationInfo = PushNotification(
            title: message.notification?.title,
            body: message.notification?.body,
          );
          print('************Push Listen*************');
          if (_notificationInfo != null) {
            // For displaying the notification as an overlay
            showSimpleNotification(
              Text(_notificationInfo.title,
                    style: Theme
                        .of(context)
                        .textTheme
                        .headline3
                        .copyWith(color: whiteColor)),

              subtitle: Text(
                _notificationInfo.body,
                style: Theme
                    .of(context)
                    .textTheme
                    .headline2
                    .copyWith(color: whiteColor),
              ),
              background: textLight,
              duration: Duration(seconds: 5),
            );
          }
        }
      });

This is condition for displaying widget

  viewShowRide ? bottomRiderView() : Container(),

I  am new to flutter plz give me solution to show popup if screen is lock and app is open in flutter

**Comment by christocracy** [comment]
Please do not ignore the issue template.  it is required.

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
