### ISSUE TITLE
The plugin does not work as expected on Android & iOS

### ISSUE THREAD

**Issue by Habil24** [transistorsoft/flutter_background_geolocation#732]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android & iOS
* OS version:
* Device manufacturer / model: Samsung A10S & iPhone 7
* Flutter info (`flutter doctor`):   ```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale
    en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability
```

• No issues found!
* Plugin config:
bg.Config getBackgroundLocationConfig(
      String androidNotificationTitle, String androidNotificationMsg) {
    return bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: Platform.isIOS ? 5 : 0,
        stopOnTerminate: true,
        startOnBoot: true,
        debug: true,
        reset: true,
        locationUpdateInterval: LOCATION_INTERVAL_MOVING_SEC * 1000,
        disableMotionActivityUpdates: false,
        notification: bg.Notification(
            title: androidNotificationTitle,
            text: androidNotificationMsg,
            smallIcon: notificationIconName,
            sticky: true,
            color: notificationColor),
        showsBackgroundLocationIndicator: true,
        logLevel: bg.Config.LOG_LEVEL_DEBUG);
  }

## Expected Behavior on Android
On Android, the device should send the background location every 10 seconds if the location interval and distance filter(0) are provided.

## Actual Behavior on Android
If activity motion detection is disabled, the behavior does not work. Moreover, the top notification fades away after a second and nothing works.

## Expected Behavior on Android
on iOS, the background location indicator should appear and the device should send the location according to the provided distance filter.

## Actual Behavior on iOS
The behavior does not work. Moreover, the background location indicator never appears and the background location is not retrieved according to the distance filter.

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1. Could be easily reproducible with the provided config in both iOS and Android.


## Context
Currently, we are trying to verify the plugin(functionality) before purchasing. It is important for us actively get the
location of the user

## Note
In all scenarios, the device was in the background and it was not killed. Any help or direction is appreciated. Thanks in advance.

**Comment by christocracy** [comment]
Read the wiki *philosophy of operation*.

You need to physically move with a real device (not emulator) about 200 meters before tracking engages.

You need to go outside for a 1km walk to test it.

**Comment by Habil24** [comment]
> Read the wiki _philosophy of operation_.
> 
> You need to physically move with a real device (not emulator) about 200 meters before tracking engages.
> 
> You need to go outside for a 1km walk to test it.

Thanks for the explanation. All checks were done with a real device previously. I would really appreciate it if you could answer my last three questions(just for verification):

1.  Is it possible to use it without motion activity? Basically, motion activity updates ask for `physical activity permission` which we don't want in our app. However, location retrieval in a specified interval with `distanceFilter: 0` does not work if `disableMotionActivityUpdates: true`.
2. Even if motion activity is enabled and the config in the top comment is provided. All location updates are received from `onMotionChange` listener instead of `onLocation` listener. Is it normal?
3. For iOS, will the applied` distanceFilter` value be applied after `200 meters` ?

**Comment by christocracy** [comment]
>s it possible to use it without motion activity?

Yes.  The plugin uses a geofence-based system as a fallback mechanism to detect when the device is moving.  This typically requires movement of 200 meters or more before the device is detected to be moving.

>All location updates are received from onMotionChange listener instead of onLocation

You do not understand what the `onMotionChange` event is.  This event is fired when the plugin changes state from *stationary -> moving* and *moving -> stationary*.  By default, the plugin starts in the *stationary* state, creates a geofence around the device, fires the `onMotionChange` event then goes to sleep to conserve energy.

When the device exits the "stationary geofence" (requiring movement of at least 200 meters from last known position), the plugin re-awakens your app in the background, fires the `onMotionChange` event and begins tracking the location according to configured `distanceFilter`.  This is all described in the wiki *Philosophy of Operation*.

>For iOS, will the location updates be retrieved according to the distanceFilter value after 200 meters

Yes.  You can easily test iOS in the *Simulator* with location simulated to *Freeway Drive*.  I suggest you install the `/example` app in this repo (Select *Advanced App* in UI).

**Comment by Habil24** [comment]
Thanks for the detailed information @christocracy 

I have verified that it works in iOS as expected (with `disableMotionActivityUpdates: true`), with the location simulated to Freeway Drive.

However, on Android (with `disableMotionActivityUpdates: true`), it did not work through "Play Route" from the emulator location options.

Could you please let me know if it could be tested through a simulator also?

**Comment by christocracy** [comment]
The emulator does not play well with simulated location.  It’s best to test on a real device.  Location tracking will engage after moving about 200 meters.

With simulated location, you must manually engage tracking by calling .changePace(true)
