### ISSUE TITLE
Plugin stops working after 5 to 10 mins of start in Vivo phones 

### ISSUE THREAD

**Issue by Intellitrack2017** [transistorsoft/flutter_background_geolocation#733]
Plugin stops working after 5 to 10 mins of start tracking in Vivo phones (Working fine in Samsung mobiles). I am using the purchased license key.

## Your Environment
* Plugin version:   flutter_background_geolocation: ^4.3.4
* Platform: Android
* OS version: Android 11 and Android 12
* Device manufacturer / model: Vivo/ Vivo Y21A
* Flutter info (`flutter doctor`): [✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/teja/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

* Plugin config:

  `void initState() {
    WidgetsBinding.instance.addObserver(this);
    _enabled = false;

    ////
    // 1.  Listen to events (See docs for all 12 available events).
    //

    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      print("Locatiom $location");

    

    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      // print(location);
      print("Locatiom $location");      

    });

    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[Location Test App] - $event');
    });

    configFlutterBackGroundService();

  }

  configFlutterBackGroundService() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    ////
    // 2.  Configure the plugin
    //
    bg.BackgroundGeolocation.ready(bg.Config(
        url: Apis.BASEURL + Apis.locations,
        autoSync: true,
        // deferTime: 3000,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 3000,
        autoSyncThreshold: 5,
        batchSync: true,
        enableHeadless: true,
        stopOnTerminate: false,
        foregroundService: true,
        debug: false,
        headers: {
          "Content-Type": "application/json",
          "Authorization": 'our Token'
        },
        params: {
          'organizationId': prefs.getString(Globals.organizationId),
          'userId': prefs.getString(Globals.userIdPrefKey)
        },
        locationsOrderDirection: "DESC",
        // maxDaysToPersist: 14
    )).then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        _enabled = state.enabled;

      }    });

  }

  callStartServiceInNAtive() async {
    
    ////
    // 3.  Start the plugin.
    //
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success started $state');
        _enabled = state.enabled;
        // To modify config after #ready has been executed, use #setConfig
        bg.BackgroundGeolocation.setConfig(bg.Config(
            isMoving: true,
        )).then((bg.State state) {
          bg.BackgroundGeolocation.sync();
        });
      }).catchError((error) {
        print('[start] starting failed ERROR: $error');
      });
   
  }

  callStopServiceInNative() async {
    
    if (_enabled) {
      bg.BackgroundGeolocation.stop()
          .then((bg.State state) => {

          bg.BackgroundGeolocation.setOdometer(0.0)

      })
          .catchError((error) {
        print('[stop] stoping failed ERROR: $error');
      });
    }
  }`

## Expected Behavior
Once tracking is enabled by the user it should run until the user stop.
## Actual Behavior
after 5 to 10 minutes service is automatically stoping/killed by the system.

## Steps to Reproduce

1. Run this code in vivo phones.
2. Go for a drive for at least 15 mins 
3. within 5 to 10 mins tracking will disable 

## Context
Our application is for tracking agents when agents enable tracking, we will start a plugin for tracking them. Will send coordinates to our server at 3 or 5 sec intervals.

**Comment by Intellitrack2017** [comment]
sorry, I didn't get you, Do we need to navigate users to enable autostart?

**Comment by christocracy** [comment]
>Do we need to navigate users to enable autostart manually?

Yes.

Also see the API docs [DeviceSettings](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/DeviceSettings-class.html)

**Comment by Intellitrack2017** [comment]
`checkBatteryOptimization() async {
    // Is Android device ignoring battery optimizations?
    bool isIgnoring = await bg.DeviceSettings.isIgnoringBatteryOptimizations;
    print("- isIgnoring? ${isIgnoring}");

    if (!isIgnoring) {
      bg.DeviceSettings.showIgnoreBatteryOptimizations().then((bg.DeviceSettingsRequest request) {
        print("- Screen seen? ${request.seen} ${request.lastSeenAt}");
        print("- Device: ${request.manufacturer} ${request.model} ${request.version}");

        // If we've already shown this screen to the user, we don't want to annoy them.
        if (request.seen) {
          return;
        }

        // It's your responsibility to instruct the user what exactly
        // to do here, perhaps with a Confirm Dialog:

        showConfirmationDialog(request);
        // bg.DeviceSettings.showMyConfimDialog(
        //     title: "Settings request",
        //     text: "Please disable battery optimizations for your device"
        // ).then((bool confirmed) {
        //   if (confirmed) {
        //     // User clicked [Confirm] button.  Execute the redirect to settings screen:
        //     bg.DeviceSettings.show(request);
        //   }
        // });
      }).catchError((dynamic error) {
        // Depending on Manufacturer/Model/OS Version, a Device may not implement
        // a particular Settings screen.
        print(error);
      });
    }

// Is iOS/Android device in power-saving mode?
    bool isPowerSaving = await bg.DeviceSettings.isPowerSaveMode;

    print("Power saving mode ${isPowerSaving}");
// Show Android vendor-specific "Power Manager" device settings screen (eg: Huawei)
    bg.DeviceSettings.showPowerManager();
  }`



I tried with the above code, I am getting the below exception. Please help me out to solve this 


`[  +90 ms] I/flutter (27840): Power saving mode false
[        ] E/flutter (27840): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(0, Failed to find POWER_MANAGER screen for device vivo V2149@11, null, null)
[        ] E/flutter (27840): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] E/flutter (27840): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] E/flutter (27840): <asynchronous suspension>
[        ] E/flutter (27840): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:43)
[        ] E/flutter (27840): <asynchronous suspension>
[        ] E/flutter (27840): #3      DeviceSettings.showPowerManager (package:flutter_background_geolocation/models/device_settings.dart:292:10)
[        ] E/flutter (27840): <asynchronous suspension>
[        ] E/flutter (27840): `

**Comment by christocracy** [comment]
It means that it's unknown how to open that screen on Vivo devices (as the exception says).

You simply need to catchError.

**Comment by Intellitrack2017** [comment]
Yes, I did.  But how to solve this issue?

**Comment by christocracy** [comment]
If Vivo is unknown, there is no solution.

**Comment by christocracy** [comment]
The way the plugin's `showPowerManager()`  method works is a [commonly known hack](https://stackoverflow.com/questions/48166206/how-to-start-power-manager-of-all-android-manufactures-to-enable-background-and) to iterate over a known list of manufacturer-specific `Intent` and attempt to launch each within a `try / catch` block.

Up until now, that list of `Intent` has been:

```java
new Intent().setComponent(new ComponentName("com.miui.securitycenter", "com.miui.permcenter.autostart.AutoStartManagementActivity")),
            new Intent().setComponent(new ComponentName("com.letv.android.letvsafe", "com.letv.android.letvsafe.AutobootManageActivity")),
            new Intent().setComponent(new ComponentName("com.huawei.systemmanager", "com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity")),
            new Intent().setComponent(new ComponentName("com.huawei.systemmanager", "com.huawei.systemmanager.optimize.process.ProtectActivity")),
            new Intent().setComponent(new ComponentName("com.huawei.systemmanager", "com.huawei.systemmanager.appcontrol.activity.StartupAppControlActivity")),
            new Intent().setComponent(new ComponentName("com.coloros.safecenter", "com.coloros.safecenter.permission.startup.StartupAppListActivity")),
            new Intent().setComponent(new ComponentName("com.coloros.safecenter", "com.coloros.safecenter.startupapp.StartupAppListActivity")),
            new Intent().setComponent(new ComponentName("com.oppo.safe", "com.oppo.safe.permission.startup.StartupAppListActivity")),
            new Intent().setComponent(new ComponentName("com.iqoo.secure", "com.iqoo.secure.ui.phoneoptimize.AddWhiteListActivity")),
            new Intent().setComponent(new ComponentName("com.iqoo.secure", "com.iqoo.secure.ui.phoneoptimize.BgStartUpManager")),
            new Intent().setComponent(new ComponentName("com.vivo.permissionmanager", "com.vivo.permissionmanager.activity.BgStartUpManagerActivity")),
            new Intent().setComponent(new ComponentName("com.samsung.android.lool", "com.samsung.android.sm.battery.ui.BatteryActivity")),
            new Intent().setComponent(new ComponentName("com.samsung.android.lool", "com.samsung.android.sm.ui.battery.BatteryActivity")),
            new Intent().setComponent(new ComponentName("com.htc.pitroad", "com.htc.pitroad.landingpage.activity.LandingPageActivity")),
            new Intent().setComponent(new ComponentName("com.asus.mobilemanager", "com.asus.mobilemanager.MainActivity")),
            new Intent().setComponent(new ComponentName("com.transsion.phonemanager", "com.itel.autobootmanager.activity.AutoBootMgrActivity"))
```

Googling "*Android POWERMANAGER_INTENTS*" (all these hacks have settled on this common `const` name `POWERMANAGER_INTENTS`, making it easy to search for), [I've found a gist containing some new known entries](https://gist.github.com/p32929/41e7af650f6a2c11e9306ab600fb9b03#file-manufacturerbatteryoptimization-java-L49-L71) which I've now added to the plugin.

Try installing the plugin from the branch `update-android-powermanager-intents`.  In your `pubspec.yaml`, modify your `flutter_background_geolocation` dependency as follows:

```yaml
dependencies:   
     flutter_background_geolocation:
       git:
         url: https://github.com/transistorsoft/flutter_background_geolocation.git
         ref: update-android-powermanager-intents
```

**Comment by Vish88781** [comment]
@christocracy  is this below line of code work for all vivo device.
  new Intent().setComponent(new ComponentName("com.vivo.permissionmanager", "com.vivo.permissionmanager.activity.BgStartUpManagerActivity")),

**Comment by christocracy** [comment]
No idea.  I don’t know anything about Vivo..

**Comment by Vish88781** [comment]
Is that possible if everything is fine in debug mode but in release, mode plugin doesn't fire any event

**Comment by christocracy** [comment]
> but in release, mode plugin doesn't fire any event

Have you purchased a license?

**Comment by Vish88781** [comment]
Yes!

**Comment by Vish88781** [comment]
Maybe I forget to mention it only happens in vivo devices with other devices everything is fine as per my research

**Comment by christocracy** [comment]
Your question about release build doesn’t seem related to the title of this issue “* Plugin stops working after 5 to 10 mins of start in Vivo phones*”.

post your gradle files:
- android/build.gradle
- android/app/build.gradle

**Comment by christocracy** [comment]
Have you modified your Vivo device Settings according to https://dontkillmyapp.com?

**Comment by Vish88781** [comment]
i use your hello world setting and my gradle version is 7.6 , no issue with battery optimization permission

**Comment by raosan** [comment]
is there any fix update on vivo device issue @vishw8878 @Intellitrack2017 ?
