### ISSUE TITLE
SomeTime and Some Device Resend Old Data to server But odometer has changed that increase from last data but another data same old record 

### ISSUE THREAD

**Issue by jaotct** [transistorsoft/flutter_background_geolocation#734]
SomeTime and Some Device Resend Old Data to server But odometer has changed that increase from last data but another data same old record Example
![image](https://user-images.githubusercontent.com/12022160/165227350-e632de88-38fb-4eab-a9a4-ae685087c11e.png)

Plugin version: 4.4.0
Platform: Android
OS version: 31
Device manufacturer / model: samsung s20 ultra
Flutter info (flutter doctor):
• Flutter version 2.10.5 at /Users/kung/Development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 5464c5bac7 (9 days ago), 2022-04-18 09:55:37 -0700
• Engine revision 57d3bac3dd
• Dart version 2.16.2
• DevTools version 2.9.2
Plugin config:
reset: true,
scheduleUseAlarmManager: true,
foregroundService: true,
isMoving: true,
stopOnTerminate: false,
startOnBoot: true,
enableHeadless: true,
debug: false,
autoSync: true,
autoSyncThreshold: 10,
url: ApiCall.writeEventLog,
desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
logLevel: bg.Config.LOG_LEVEL_ERROR,
distanceFilter: 300```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
<!--- Tell us what should happen -->

## Actual Behavior
<!--- Tell us what happens instead -->

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version:
>Platform: iOS or Android
>OS version:
>Device manufacturer / model:
>Flutter info (flutter doctor):
>Plugin config:

**Comment by jaotct** [comment]
Plugin version: 4.4.0
Platform: Android
OS version: 31
Device manufacturer / model: samsung s20 ultra
Flutter info (flutter doctor):
    • Flutter version 2.10.5 at /Users/kung/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (9 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
Plugin config:
        reset: true,
        scheduleUseAlarmManager: true,
        foregroundService: true,
        isMoving: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        debug: false,
        autoSync: true,
        autoSyncThreshold: 10,
        url: ApiCall.writeEventLog,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        logLevel: bg.Config.LOG_LEVEL_ERROR,
        distanceFilter: 300

**Comment by jaotct** [comment]
I've found that sometimes the data sent, whether it's time, coordinates, speed is the same, but it's retransmitted to the api at different times, but the odometer returns to the last number, causing the distance to be multiplied from reality. The number of laps retransmitted if calculated from an odometer.
