### ISSUE TITLE
Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'.

### ISSUE THREAD

**Issue by basnetjiten** [transistorsoft/flutter_background_geolocation#735]
## Your Environment
* Plugin version:flutter_background_geolocation: ^4.4.0
* Platform: Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`): Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

apk should be build normally, however if i change the plugins android build.gradel to def DEFAULT_COMPILE_SDK_VERSION                 = 29 // changing it to 31 works and compile fine

## Steps to Reproduce

1. updated to flutter_background_geolocation: ^4.4.0
2. try to build release apk
3.
4.

## Context

Trying to build release apk

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/ebpearls/.gradle/caches/transforms-2/files-2.1/bd45d8ae8a89089aac4c40676e4fcbed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

```

</details>

**Comment by christocracy** [comment]
> DEFAULT_COMPILE_SDK_VERSION = 29

You're not supposed to edit the plug-in's gradle files.  You can control the compileSdkVersion via `ext.compileSdkVersion` in your root `android/build.gradle`.

See the Android Setup instructions linked in the readme for more information.
