### ISSUE TITLE
onLocation called multiple times

### ISSUE THREAD

**Issue by jaydeepktridhya** [transistorsoft/flutter_background_geolocation#737]
When I start tracking the onLocation method is called multiple times like 3/4 times and Http method is called only 1 time. Can you please help

**Comment by christocracy** [comment]
This is supposed to happen.  It is explained right at the top of the api docs for onLocation.

https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/onLocation.html

**Comment by jaydeepktridhya** [comment]
Then how I can record the count of the location that has been fetched and
sent to server. Can you please explain

**Comment by christocracy** [comment]
Location.sample.

https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Location/sample.html

**Comment by jaydeepktridhya** [comment]
I am not getting sample value.

[location] - [Location {odometer: 0.0, activity: {confidence: 100, type:
still}, extras: {eventCode: GHGG, userDisplayName: , userEmail:
***@***.***, userId: lCXfFBv69TcZ7cFLqMZjnOKCmb53},
battery: {level: 0.91, is_charging: true}, uuid:
838ab8f9-630b-4743-8f39-89c883f4930d, coords: {altitude: 9.8, heading:
-1.0, latitude: 23.0255522, accuracy: 11.2, heading_accuracy: -1.0,
altitude_accuracy: 1.0, speed_accuracy: -1.0, speed: -1.0, longitude:
72.4774541}, is_moving: false, timestamp: 2022-05-04T03:52:34.504Z}]

**Comment by christocracy** [comment]
Then it’s not a sample

**Comment by christocracy** [comment]
Samples only occur during motionchange event, when plugin changes state from *stationary -> moving* and vice versa.

**Comment by jaydeepktridhya** [comment]
Thank you for the clarification.

What if I call only OnLocation Method and does not call on Motion change
method and I am tracking currently for 10 hours in my app because we are
tracking sports event.

**Comment by jaydeepktridhya** [comment]
Right now I am getting location 3 times and only 1 time it is uploaded to
my server.

**Comment by christocracy** [comment]
You don’t “call” these methods, you *subscribe* to them.  They are event-listeners.

those events are emitted whether you choose to subscribe to them or not.

the plugin has 13 events you can subscribe to.

**Comment by christocracy** [comment]
2 of the 3 will be samples.  The plugin does not accept the first location that arrives when changing state.

When the plugin turns on location-services, it waits for the gps to “warm up” before settling upon the most accurate.

those first few locations will be tagged as sample: true.

the plugin has been doing this for over 7 years.

**Comment by jaydeepktridhya** [comment]
I am getting sample value false in all of them.

**Comment by christocracy** [comment]
Then you are calling onLocation MULTIPLE TIMES.

Every time you call onLocation, you add ANOTHER event listener.

**Comment by jaydeepktridhya** [comment]
void configureBackgroundFetch() {
  // Fired whenever a location is recorded
  bg.BackgroundGeolocation.onLocation(onLocation);
  bg.BackgroundGeolocation.onHttp(onHttp);
  // Fired whenever the plugin changes motion-state
(stationary->moving and vice-versa)
  bg.BackgroundGeolocation.onMotionChange(onMotionChange);
  // Fired whenever the state of location-services changes.  Always
fired at boot
  //bg.BackgroundGeolocation.onProviderChange(onProviderChange);

  bg.BackgroundGeolocation.onSchedule(onSchedule);

  bg.BackgroundGeolocation.ready(bg.Config(
    reset: true,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter:  distanceFilterRange.value == 0 ? 10 :
distanceFilterRange.value,
    disableElasticity: true,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: false,
    backgroundPermissionRationale: bg.PermissionRationale(
        title:
        "Allow {applicationName} to access this device's location even
when the app is closed or not in use.",
        message:
        "This app collects location data to enable recording of your
location for the sporting events you participate in.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'),
    schedule: [
      startTime.value + " " + endTime.value // <-- track for 1 year
    ],
    url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
    extras: {
      "eventCode": eventCodeController.text,
      "userId": Get.find<FirebaseController>().id!,
      "userDisplayName": name.value,
      "userEmail": Get.find<FirebaseController>().user!
    },
  )).then((bg.State state) {
    // if (!state.enabled) {
    //   ////
    //   // 3.  Start the plugin.
    //   //
    //   bg.BackgroundGeolocation.start();
    // }
    // enable.value = state.schedulerEnabled;
    onClickEnable(true);
  });
}



I am calling this method on my press event.

**Comment by christocracy** [comment]
Please learn to syntax highlight code blocks.  Edit your last comment

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by jaydeepktridhya** [comment]
'''

void configureBackgroundFetch() {
  // Fired whenever a location is recorded
  bg.BackgroundGeolocation.onLocation(onLocation);
  bg.BackgroundGeolocation.onHttp(onHttp);
  // Fired whenever the plugin changes motion-state
(stationary->moving and vice-versa)
  bg.BackgroundGeolocation.onMotionChange(onMotionChange);
  // Fired whenever the state of location-services changes.  Always
fired at boot
  //bg.BackgroundGeolocation.onProviderChange(onProviderChange);

  bg.BackgroundGeolocation.onSchedule(onSchedule);

  bg.BackgroundGeolocation.ready(bg.Config(
    reset: true,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter:  distanceFilterRange.value == 0 ? 10 :
distanceFilterRange.value,
    disableElasticity: true,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: false,
    backgroundPermissionRationale: bg.PermissionRationale(
        title:
        "Allow {applicationName} to access this device's location even
when the app is closed or not in use.",
        message:
        "This app collects location data to enable recording of your
location for the sporting events you participate in.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'),
    schedule: [
      startTime.value + " " + endTime.value // <-- track for 1 year
    ],
    url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
    extras: {
      "eventCode": eventCodeController.text,
      "userId": Get.find<FirebaseController>().id!,
      "userDisplayName": name.value,
      "userEmail": Get.find<FirebaseController>().user!
    },
  )).then((bg.State state) {
    // if (!state.enabled) {
    //   ////
    //   // 3.  Start the plugin.
    //   //
    //   bg.BackgroundGeolocation.start();
    // }
    // enable.value = state.schedulerEnabled;
    onClickEnable(true);
  });
}

'''

This is method which I am calling.

**Comment by christocracy** [comment]
```dart
void learnToSyntaxHighlight() {
  /// with the link above
}
```

**Comment by jaydeepktridhya** [comment]
'''

void configureBackgroundFetch() {

'''dart
  // Fired whenever a location is recorded
  bg.BackgroundGeolocation.onLocation(onLocation);
  bg.BackgroundGeolocation.onHttp(onHttp);
  // Fired whenever the plugin changes motion-state
(stationary->moving and vice-versa)
  bg.BackgroundGeolocation.onMotionChange(onMotionChange);
  // Fired whenever the state of location-services changes.  Always
fired at boot
  //bg.BackgroundGeolocation.onProviderChange(onProviderChange);

  bg.BackgroundGeolocation.onSchedule(onSchedule);

  bg.BackgroundGeolocation.ready(bg.Config(
    reset: true,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter:  distanceFilterRange.value == 0 ? 10 :
distanceFilterRange.value,
    disableElasticity: true,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: false,
    backgroundPermissionRationale: bg.PermissionRationale(
        title:
        "Allow {applicationName} to access this device's location even
when the app is closed or not in use.",
        message:
        "This app collects location data to enable recording of your
location for the sporting events you participate in.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'),
    schedule: [
      startTime.value + " " + endTime.value // <-- track for 1 year
    ],
    url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
    extras: {
      "eventCode": eventCodeController.text,
      "userId": Get.find<FirebaseController>().id!,
      "userDisplayName": name.value,
      "userEmail": Get.find<FirebaseController>().user!
    },
  )).then((bg.State state) {
    // if (!state.enabled) {
    //   ////
    //   // 3.  Start the plugin.
    //   //
    //   bg.BackgroundGeolocation.start();
    // }
    // enable.value = state.schedulerEnabled;
    onClickEnable(true);
  });

'''
}

'''

Please check now!!!!!

**Comment by christocracy** [comment]
It’s messed up.

stop replying to issues via email!!  Use GitHub.com to interact with issues.
