### ISSUE TITLE
onLocation called multiple times

### ISSUE THREAD

**Issue by jaydeepktridhya** [transistorsoft/flutter_background_geolocation#739]
This is the method I am calling but I am getting onLocation value 3 times. What's the issue.
'''
void configureBackgroundFetch() {
    // Fired whenever a location is recorded
    bg.BackgroundGeolocation.onLocation(onLocation);
    bg.BackgroundGeolocation.onHttp(onHttp);
    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange(onMotionChange);
    // Fired whenever the state of location-services changes.  Always fired at boot
    //bg.BackgroundGeolocation.onProviderChange(onProviderChange);

    bg.BackgroundGeolocation.onSchedule(onSchedule);

    bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter:  distanceFilterRange.value == 0 ? 10 : distanceFilterRange.value,
      disableElasticity: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: false,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
          "This app collects location data to enable recording of your location for the sporting events you participate in.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      schedule: [
        startTime.value + " " + endTime.value // <-- track for 1 year
      ],
      url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
      extras: {
        "eventCode": eventCodeController.text,
        "userId": Get.find<FirebaseController>().id!,
        "userDisplayName": name.value,
        "userEmail": Get.find<FirebaseController>().user!
      },
    )).then((bg.State state) {
      // if (!state.enabled) {
      //   ////
      //   // 3.  Start the plugin.
      //   //
      //   bg.BackgroundGeolocation.start();
      // }
      // enable.value = state.schedulerEnabled;
      onClickEnable(true);
    });
  }
'''

**Comment by christocracy** [comment]
Still messed up.  You don’t engage syntax highlighting with Single Quotes…they’re backticks.  

Go read the link I posted again

**Comment by jaydeepktridhya** [comment]
'''
void configureBackgroundFetch() {

    bg.BackgroundGeolocation.onLocation(onLocation);
    bg.BackgroundGeolocation.onHttp(onHttp);
    bg.BackgroundGeolocation.onMotionChange(onMotionChange);
    bg.BackgroundGeolocation.onSchedule(onSchedule);

    bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter:  distanceFilterRange.value == 0 ? 10 : distanceFilterRange.value,
      disableElasticity: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: false,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
          "This app collects location data to enable recording of your location for the sporting events you participate in.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      schedule: [
        startTime.value + " " + endTime.value // <-- track for 1 year
      ],
      url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
      extras: {
        "eventCode": eventCodeController.text,
        "userId": Get.find<FirebaseController>().id!,
        "userDisplayName": name.value,
        "userEmail": Get.find<FirebaseController>().user!
      },
    )).then((bg.State state) {
      onClickEnable(true);
    });

  }
'''

**Comment by christocracy** [comment]
I don’t think you understand the difference between single quotes and backticks.

- single quote:  ‘
- backtick:  `

**Comment by jaydeepktridhya** [comment]
```
void configureBackgroundFetch() {
   
    bg.BackgroundGeolocation.onLocation(onLocation);
    bg.BackgroundGeolocation.onHttp(onHttp);
    bg.BackgroundGeolocation.onMotionChange(onMotionChange);
    bg.BackgroundGeolocation.onSchedule(onSchedule);

    bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter:  distanceFilterRange.value == 0 ? 10 : distanceFilterRange.value,
      disableElasticity: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: false,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
          "This app collects location data to enable recording of your location for the sporting events you participate in.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      schedule: [
        startTime.value + " " + endTime.value // <-- track for 1 year
      ],
      url: "http://ingest-au1-test.timing.onetimesystem.com/ingest?messageType=gps-mobile",
      extras: {
        "eventCode": eventCodeController.text,
        "userId": Get.find<FirebaseController>().id!,
        "userDisplayName": name.value,
        "userEmail": Get.find<FirebaseController>().user!
      },
    )).then((bg.State state) {
      onClickEnable(true);
    });
  }
```

**Comment by christocracy** [comment]
And stop repo-posting the same thing over and over.  I keep deleting them.  You can EDIT your previous posts!!  

I
![Uploading 854A0E9B-2595-4AD2-AF8F-A08DE1EA06CA.png…]()

**Comment by christocracy** [comment]
I suggest you create a simple hello world app and learn to use this plugin in isolation.

you’re clearly just copy/pasting code from the example without understanding what you’re doing.

Also see the wiki *Debugging*.

**Comment by jaydeepktridhya** [comment]
My whole app is working I just don't know why onLocation is called multiple times. I worked on demo first after that I have implemented it in my project.

**Comment by christocracy** [comment]
Duplicate #737

**Comment by jaydeepktridhya** [comment]
onLocation is called multiple times with sample value false
