### ISSUE TITLE
Android 12 Error 

### ISSUE THREAD

**Issue by joaofjunior** [transistorsoft/flutter_background_geolocation#742]
## Your Environment
* Plugin version: 1.9.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`):  Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [versÃ£o 10.0.22610.1], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Ferramentas de Build do Visual Studio 2019 16.11.5)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.2)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 2.0,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: false,
            allowIdenticalLocations: false,
            disableElasticity: true,
            foregroundService: true,
            isMoving: true,
            logLevel: bg.Config.LOG_LEVEL_INFO,
            reset: true))
        .then((bg.State state) {
      print('[ready] - ${state}');
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
```

## Expected Behavior
The plugin is working, the problem is only installing (and publishing on the PlayStore) on android version 12

## Actual Behavior
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl602339546.tmp/base.apk (at Binary XML file line #96): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on sdk gphone64 x86 64.

## Steps to Reproduce

1.
2.
3.
4.

## Context
How to resolve this error? I know it has to do with android:exported, I already put it in my manifest

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Version 1.9.0 is incompatible with Android 12.

you need to upgrade.

Android 12 compatibility was introduced last summer.

See the CHANGELOG.

https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md
