### ISSUE TITLE
Support for poly geofence

### ISSUE THREAD

**Issue by srinivaspalchuri-saven** [transistorsoft/flutter_background_geolocation#743]
Need support to create geo fences using polygon

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Native geofencing apis support only circular.

**Comment by iloads** [comment]
We want to implement Polygon in Geofencing as well. 
Read your explanation on "you should create a circular geofence that encompasses your polygon"
Unluckily I am not able to understand how to do it. 
Can you please explain me further with an example or a picture?
Thanks in advance

**Comment by christocracy** [comment]
![Untitled-2023-04-17-1229](https://user-images.githubusercontent.com/14999/232551656-2f9160dd-b9c6-4040-90b0-2ce8f5c78b20.png)

**Comment by iloads** [comment]
Thanks a ton this really helps. 

one question though on implementing the proposed solution
Transistor plug-in will consider those lats long as well which will be falling under 
#1. Lat Longs outside the Square and within the Circle.

Will the Transistor plug-consider  #1 Lat / long as well as Geofenced?
if yes, isn't incorrect to consider these Lat/longs as Geofenced?

**Comment by christocracy** [comment]
In have no idea what you’re talking about.

**Comment by christocracy** [comment]
Polygon geofencing is coming soon.  I’m using c++ libraries to calculate the “minimum enclosing circle” around the polygon (used to create the traditional native Circular geofence).  Once the circular geofence is entered, a foreground-service is launched to initiate fast location-updates used to “hit test” the polygon with another c++ library.
