### ISSUE TITLE
Notification not received when i was came inside geofence in your demo code

### ISSUE THREAD

**Issue by JALTESHGJ** [transistorsoft/flutter_background_geolocation#749]
## Your Environment
* Plugin version: version: 4.6.2
* Platform: Android 
* OS version: Android 10,11,12
* Device manufacturer / model: Android Simulator/ POCO F1
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel unknown, 2.10.2, on macOS 12.3 21E230 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Android Studio (version 2021.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
flutter_background_geolocation: '^1.9.0' (As Mentioned in the documentation in git)

## Expected Behavior
When i reach or came inside geofence i want notification that shows me that i came inside the geofence area.

## Actual Behavior

Notification was not triggered.

## Steps to Reproduce

1. Created Geofence
2. Go Outside the geofence area like 1 mile away then come back inside the geofence
3. Waiting for 15 mins in geofence area
4. Notification not triggered.

**Comment by bajjajjrajjesh** [comment]
Hi @christocracy can you please help us on this please?
