### ISSUE TITLE
[Feature Request] - Ability to disable foreground service if only using geofencing on Android >8.0

### ISSUE THREAD

**Issue by AndrewPetrovics** [transistorsoft/flutter_background_geolocation#75]
From my understanding, this plugin forces the foregroundService property to true on Android >8.0 devices.

We would love the ability to turn this off if we're only using geofencing.

**Comment by christocracy** [comment]
`#startGeofences` does not use a persistent foreground-service.

**Comment by christocracy** [comment]
With plugin version `>1.0.0`, that is.

**Comment by AndrewPetrovics** [comment]
Ah, okay. We had the `isMoving` property set to `true`, which was keeping the foreground service going.

Once, we took `isMoving` out it went away.

Thanks!

**Comment by christocracy** [comment]
That doesn’t make sense.  Are you using #start or #startGeofences?

**Comment by AndrewPetrovics** [comment]
#startGeofences

**Comment by AndrewPetrovics** [comment]
version `^1.0.8`
