### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Benkhouds** [transistorsoft/flutter_background_geolocation#752]
## Your Environment
* Plugin version: 4.6.2
* Platform: Android
* OS version: 11
* Device manufacturer / model: android emulator
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Context
I'm just trying to run the example, i cloned the repo and i ran flutter pub get and then flutter run

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
../../../../../Documents/flutter_windows_2.10.4-stable/flutter/.pub-cache/hosted/pub.dartlang.org/unicorndial-1.1.5/lib/unicorndial.dart:276:15: Error: No named parameter with the name 'overflow'.
              overflow: Overflow.visible,
              ^^^^^^^^
../../../../../Documents/flutter_windows_2.10.4-stable/flutter/packages/flutter/lib/src/widgets/basic.dart:3708:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^
../../../../../Documents/flutter_windows_2.10.4-stable/flutter/.pub-cache/hosted/pub.dartlang.org/unicorndial-1.1.5/lib/unicorndial.dart:298:11: Error: No named parameter with the name 'overflow'.
          overflow: Overflow.visible,
          ^^^^^^^^
../../../../../Documents/flutter_windows_2.10.4-stable/flutter/packages/flutter/lib/src/widgets/basic.dart:3708:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^


FAILURE: Build failed with an exception.

```

</details>

**Comment by christocracy** [comment]
> [✓] Flutter (Channel stable, 3.0.0

I’ve not yet tested on Flutter 3.

**Comment by christocracy** [comment]
It seems to be puking on a 3rd party ui plugin the example uses.

**Comment by Benkhouds** [comment]
It works when i downgraded, for now this is okay, but i'm assuming there are update plans so i'll close the issue thanks

**Comment by christocracy** [comment]
>  i'm assuming there are update plans

Yes, of course.  I was going to `flutter upgrade` earlier today but got sidetracked.

I’m sure there’ll be little/no problems with the plugin itself, which does not depend on UI components.

**Comment by christocracy** [comment]
The /example has replaced the offending [`unicorndialer`](https://github.com/tiagojencmartins/unicornspeeddial) (deprecated) with new [`flutter_speed_dial`](https://pub.dev/packages/flutter_speed_dial)

The /example now boots with *Flutter 3*

```bash
$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
