### ISSUE TITLE
Question: What is the sort order of geofences in GeofencesChangeEvent?

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#753]
What is the sort order of the geofences in the GeofencesChangeEvent **_on_** property?

**Comment by christocracy** [comment]
if you have greater than the platform maximum geofences (Android: 99, iOS: 19), the sort order is by distance from current location.

If you have less than the platform maximum, there is no `ORDER BY` on the query..

**Comment by ozzy1873** [comment]
Thanks. Closing.
