### ISSUE TITLE
When to call ready and consequences of resetting the config

### ISSUE THREAD

**Issue by al-muammar** [transistorsoft/flutter_background_geolocation#758]
It's not clear from the documentation when should one call `ready` and how it will affect the app.

1. Should one call `ready` ASAP? What if I want to show location request message only after a user is logged in?
2. How calling `ready` will affect the app that is already tracking coordinates while terminated if not called ASAP?
3. What's the problem of always calling `ready` with `reset: true` instead of `setConfig`? Why is it recommended only during the developement? It seems to me less error prone.

**Comment by christocracy** [comment]
>Should one call ready ASAP? 

`.ready()` is a signal to the plugin that your Flutter `App` has launched and the plugin may now start firing events to you.  If there were no way to tell the plugin that your `App` code is "*ready*", the plugin would start firing events before your code had a chance to exist.

>What if I want to show location request message only after a user is logged in?

Calling `.ready(config)` does **not** imply "start tracking", nor does calling `.ready(config)` request permissions.

```dart
// This does not cause the plugin to start tracking, nor does it request permission.
bg.State state = await bg.BackgroundGeolocation.ready(config);
```

Only calling `.start()` will cause the plugin request permission and start tracking.

You are not required to call `.start()` immediately after calling `.ready()`.  

>What's the problem of always calling ready with reset: true instead of setConfig

`reset: true` is the default.  The only reason `Config.reset` even exists is for my own personal reasons in the `/example`, where I wanted the *Settings* screen to drive the `Config` and not be *reset* with each launch of the app.  Typical apps do not allow the users to modify the plugin's config in a fine-grained way by exposing the plugin's `Config` like this.  You should completely forget about `reset: true`.  99% of use-cases do not use `reset: false`, like the `/example` app does.  **Just delete it from your `Config` and forget you ever learned about `reset: true` (the default).

<img width="339" alt="Screen Shot 2022-05-25 at 12 54 31 PM" src="https://user-images.githubusercontent.com/14999/170318598-defce11f-78c9-48d9-bed8-efbe113a0b43.png">

>instead of setConfig

As I said above, "*`.ready()` is a signal to the plugin that your Flutter `App` has launched and the plugin may now start firing events to you.  If there were no way to tell the plugin that your `App` code is "*ready*", the plugin would start firing events before your code had a chance to exist.*".

**Comment by christocracy** [comment]
>What if I want to show location request message only after a user is logged in?

```dart
bg.State state = await bg.BackgroundGeolocation.ready(yourConfig);

bool myPermissionResult = await myOwnCustomRequestPermissionAction();

if (myPermissionResult) {
  // If you are happy with the result of your own custom permission request, tell the plugin to .start()
  bg.BackgroundGeolocation.start();
}
```

**Comment by christocracy** [comment]
Yes, that’s fine.  But use `await`.  The plug-in’s method calls are asynchronous.  There’s no guarantee .setConfig() will complete before .start() unless you `await`.

Think of executing plugin methods like an http request to a remote server:  they don’t run instantaneously.

the remote server in this case is the native Obj-c / Java code of the plugin.
