### ISSUE TITLE
MissingPluginException(No implementation found for method ready on channel com.transistorsoft/flutter_background_ge

### ISSUE THREAD

**Issue by vikramkapoor** [transistorsoft/flutter_background_geolocation#76]
## Your Environment
* Plugin version:  flutter_background_geolocation: '^1.0.8'
* Platform: Android
* OS version: Android P (9.0)
* Device manufacturer / model: Android Virtual Device - Nexus 5X API 28 x86
* Flutter info (`flutter doctor`):  
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.113], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.0)
[√] Connected device (1 available)
• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
      bg.BackgroundGeolocation.ready(bg.Config(
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: true,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          reset: true))
          .then((bg.State state) {
        if (!state.enabled) {
          ////
          // 3.  Start the plugin.
          //
          bg.BackgroundGeolocation.start();
        }
      });

      // Manually fetch the current position.

      bg.BackgroundGeolocation.getCurrentPosition(
          persist: false, // <-- do not persist this location

          desiredAccuracy: 0, // <-- desire best possible accuracy

          timeout: 30000, // <-- wait 30s before giving up.

          samples: 3 // <-- sample 3 location before selecting best.

      )
          .then((bg.Location location) {
        //_location = location;
        print('[getCurrentPosition] - $location');
        print("Lat: ${location.coords.latitude} Long: ${location.coords
            .longitude}");

```

## Expected Behavior
The call should return location like it does on iOS

## Actual Behavior
Leads to MissingPluginException.

## Steps to Reproduce

1. Run the code above from background isolate
2.
3.
4.

## Context

Above code works from UI isolate but I need to get location in background. I spawned an isolate and copied the code above to it. It worked on iOS but on Android I get Missing Plugin Exception on bg.BackgroundGeolocation.ready 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
I/flutter ( 7121): Another exception was thrown: MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/location)
I/flutter ( 7121): Another exception was thrown: MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/motionchange)
I/flutter ( 7121): Another exception was thrown: MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/providerchange)
I/flutter ( 7121): Another exception was thrown: MissingPluginException(No implementation found for method listen on channel plugins.pauldemarco.com/flutter_blue/state)
I/flutter ( 7121): [BackgroundGeolocation registerHeadlessTask] ‼️ MissingPluginException(No implementation found for method registerHeadlessTask on channel com.transistorsoft/flutter_background_geolocation/methods)
Error -32601 received from application: Method not found
</details>

**Comment by christocracy** [comment]
The issue template is *not optional.*.

You have neglected crucial info.  Particularly **Plugin version**.  Edit you issue and provide the **Required info**.

**Comment by vikramkapoor** [comment]
I found the issue. There was an error during plugin registration for the background Isolate. The problem went away after fixing that.

**Comment by christocracy** [comment]
In the future, *never* ignore the issue template.

**Comment by stijnie2210** [comment]
@vikramkapoor Any chance you can tell me how you solved this?
