### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by haukepribnow** [transistorsoft/flutter_background_geolocation#760]
First of all: Thanks for releasing this to the world. Now to my issue: I find two conflicting license provisions in this repository.

The README file says that the code is under the MIT license:
https://github.com/transistorsoft/flutter_background_geolocation/blob/ee329a9444a9f8fdb8d8f993990ee68d357a1491/README.md?plain=1#L156-L179

The LICENSE file however contains a different (custom?) license:
https://github.com/transistorsoft/flutter_background_geolocation/blob/ee329a9444a9f8fdb8d8f993990ee68d357a1491/LICENSE

So which one is it? :)

**Comment by christocracy** [comment]
The second one.

you need to purchase a license key to use this.
