### ISSUE TITLE
The app crashes on start in release in Android

### ISSUE THREAD

**Issue by Habil24** [transistorsoft/flutter_background_geolocation#761]
The app crashes on start in production. Basically during the development, the plugin was working without a problem. However, when we made a test release, the app did not start and crashed. When we tried to get a release apk the verification of release resources fails with task `Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'` . On crashlitytics the stack trace for the error was:
```
java.lang.ExceptionInInitializerError: 
  at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance
  at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.ready (BackgroundGeolocationModule.java:345)
  at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onMethodCall (BackgroundGeolocationModule.java:223)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:262)

```
## Your Environment
* Plugin version: 4.6.3
* Platform: Android
* OS version: Any Android version
* Flutter info (`flutter doctor`):

* Plugin config: Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!

```dart <-- Syntax highlighting: DO NOT REMOVE -->
  desiredAccuracy: bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: Platform.isIOS ? DISTANCE_FILTER : 0,
      debug: false,
      reset: true,
      disableMotionActivityUpdates: true,
      locationUpdateInterval: LOCATION_INTERVAL_MOVING_MS,
      notification: bg.Notification(
        title: androidNotificationTitle,
        text: androidNotificationMsg,
        smallIcon: notificationIcon,
        sticky: true,
        color: notificationColor,
      ),
      showsBackgroundLocationIndicator: true,
    )
```

## Expected Behavior
The plugin should not cause an app crash

## Actual Behavior
The plugin causes the app to crash on start

#### gradle.properties:
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableDexingArtifactTransform=false
```
#### android/app/build.gradle.

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 32

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "example.someexample.app"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.appcompat:appcompat:1.4.1"
}

apply plugin: 'com.google.firebase.crashlytics'
```
#### android/build.gradle:
```
buildscript {
    ext.kotlin_version = '1.6.10'

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

1.  With the configs above running `flutter build apk path/to/lib/main_prod.dart --release --verbose` will fail for the verification of release resources as it was mentioned above.

## Context
Trying to get a release with the newly implemented plugin

## Debug logs
The logs of `flutter build apk path/to/lib/main_prod.dart --release --verbose`  for failed task were provided below:
<details>
	<summary>Logs</summary>
``` <!-- syntax-highligting:  DO NOT REMOVE -->
> Task :app:packageRelease
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'.
 > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
  > Android resource linking failed
     ERROR:/Users/hq/.gradle/caches/transforms-3/f3d45056847818752b9a313ae43affe3/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```

</details>

**Comment by christocracy** [comment]
> AAPT: error: resource android:attr/lStar not found.

Have you googled this

did you purchase a license?

i run release builds every day with /example app

**Comment by christocracy** [comment]
the plugin respect the `ext` Var `appCompatVersion`.

I believe the plugin’s recent update of its Dependency `android-permissions` requests 1.4.1

**Comment by Habil24** [comment]
@christocracy  we have managed to solve the issue by directly changing the config according to the `example app (ext)`.

However, there is one issue, when the app goes to the background by pressing the 'middle button in android' the app goes to the background which is expected. However, when the 'right' button of the phone is pressed(where we can see the apps in memory), the app is not there anymore. The user should go to the app library and click on the icon again to open the app. The log just before this action is:

```
⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager( 7826): ╠═════════════════════════════════════════════
D/TSLocationManager( 7826): [c.t.l.event.TerminateEvent <init>] 
D/TSLocationManager( 7826):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
```
Do you have information regarding this? (Note that this does not happen when the app goes to the background when it was in foreground.) 

The issue happened on all 4 test devices with the test release(Also in some, the service is killed together with the app in the background).

**Comment by christocracy** [comment]
>⏰ OneShot event fired: TERMINATE_EVENT

this is merely a 10s timer firing when the app goes to background , when the plugin asks “*is the app terminated?*” (ie MainActivity no longer alive).

in the logs you posted, the answer is yes.

> ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).

**Comment by christocracy** [comment]
Android provides no 100% guaranteed callback when an app is terminated.

the plugin needs to know this, so it can fire events into your registered HeadlessTask when configured.

**Comment by christocracy** [comment]
The plugin also uses this to determine if it should `stopOnTerminate`

**Comment by Habil24** [comment]
Thanks for the info @christocracy 

The thing is that the app was not terminated at this stage. It is in memory but in the background. 
We don't use headlessTask(same config in the issue) and benefit from only background location updates.
Interestingly, the view can not be seen when the android phone 'right' button is pressed where we can see
the apps that were put into the background. However, clicking on the background notification retrieves the app state from the same view that it was left before.

Interestıngly, this does not happen if I don't start the location updates with `bg.BackgroundGeolocation.start()`. Only starting the location updates causes this issue
