### ISSUE TITLE
[IOS] it's not worked when the app is killed.

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [transistorsoft/flutter_background_geolocation#762]
## Your Environment
* Plugin version: 4.6.3
* Platform: iOS 
* OS version: 15.5
* Device manufacturer / model: iPhone 8
* Flutter info (`flutter doctor`): 
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

## Expected Behavior
work when the app is killed 
## Actual Behavior
when I close the app it's not working.

**Comment by christocracy** [comment]
You’ve not posted your code.

**Comment by christocracy** [comment]
Then boot the app in iOS simulator.

simulate location with *Freeway Drive*

Terminate app.  Wait and watch app relaunch.  You will begin to see the plug-in’s debug notification.

also read api docs Config.stopOnTerminate to understand why the device must keep moving about 200 meters before the app automatically relaunches in the background to resume tracking.

**Comment by Shahmirzali-Huseynov** [comment]
@christocracy  200 meters is required for working when the app is killed situation?

**Comment by christocracy** [comment]
Yes.  After terminate, the plugin isn’t going to resume tracking until the device moves about 200 meters (about one city block).

there is no way around this.  We’re fortunate that Apple even allows this.

**Comment by Shahmirzali-Huseynov** [comment]
thanks, it's working when I choose Freeway Drive.
