### ISSUE TITLE
Flavors license key invalid

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#764]
## Your Environment
* Plugin version: 4.6.3
* Platform: Android
* Device manufacturer / model: Xiami

I have a license to buy an application id.

But I want it to work on all my flavors, but there is something weird, when I run the command to release: `Licence validation failure`

for dev and staging, I don't get the message: `Licence validation failure`

but when I compile production in release I get this message, it seems quite strange to me, because settings do not change anything, only the application id and my apis change.

Some advice, to pass release applications with flavors
```
 flavorDimensions "app"
    productFlavors {
        staging {
            dimension "app"
          
            versionNameSuffix ".staging"
            applicationId "applicationId.staging"
        }
        dev {
            dimension "app"
        
            versionNameSuffix ".dev"
            applicationId "idapplicationId.dev"
        }
        production {
            dimension "app"
            versionNameSuffix ".production"
            applicationId "applicationId.prod"
        }
    }
```

**Comment by christocracy** [comment]
.production suffix is not recognized.

If you have a **production** app named `com.foo.bar`, the allowed suffixes are:
- `com.foo.bar.dev`
- `com.foo.bar.staging`

Your production app shouldn’t have a suffix.

**Comment by miguelflores1993** [comment]
> No se reconoce el sufijo .production.
> 
> Si tiene una aplicación de **producción** llamada `com.foo.bar`, los sufijos permitidos son:
> 
> * `com.foo.bar.dev`
> * `com.foo.bar.staging`
> 
> Su aplicación de producción no debe tener un sufijo.

of course the one for my play store application does not have suffixes, I just want to compile flavors to make a `pre production`.

Thanks, I did not know about this case, because it did not recognize `.prod and neither did .production.`

So I could use any, except production?

`could use .qa?`

**Comment by christocracy** [comment]
Following are also recognized:
- `.qa`
- `.uat` (*User acceptance testing*)
