### ISSUE TITLE
Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml' (This happens when i am trying to create release build)

### ISSUE THREAD

**Issue by Ravish1** [transistorsoft/flutter_background_geolocation#768]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- Issue template ignored.
- No information provided (eg: `android/build.gradle`, `android/app/build.gradle`
- Wrong repo: `transistorsoft/tsbackgroundfetch/`.  This has [been posted before](https://github.com/transistorsoft/flutter_background_fetch/issues?q=could+not+GET+bintray+)
