### ISSUE TITLE
ERROR:/Users/imac/Desktop/wynd/build/flutter_background_geolocation/intermediates/merged_res/release/values/values.xml:2571: AAPT

### ISSUE THREAD

**Issue by FirdousNath** [transistorsoft/flutter_background_geolocation#770]
## Your Environment
* Plugin version:^4.6.3
* Platform:  Android
* OS version: 10
* Device manufacturer / model: emulator
* Flutter: 3.0.1

 What went wrong:
Execution failed for task ':flutter_background_geolocation:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/imac/Desktop/wynd/build/flutter_background_geolocation/intermediates/merged_res/release/values/values.xml:2571: AAPT: error: resource android:attr/lStar not found.

**Comment by yaroslav13** [comment]
@christocracy same

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by yaroslav13** [comment]
decrease  classpath 'com.android.tools.build:gradle:7.0.0’  from 7.0.0 to 4.0.0  helps

**Comment by christocracy** [comment]
can someone please confirm that simply upgading `ext.appCompatVersion` fixes it as well.

**Comment by AndrewsMlab** [comment]
Sorry but i don't use appCompatVersion var. Because AppCompart dependency doesn't imply on build and functionality. How can it be? . But in issue case i tied to add it to. It didn't help(as well as add tests dependencies)

**Comment by christocracy** [comment]
>Sorry but i don't use appCompatVersion 

It doesn't matter.  The [**plugin does**](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L73)

**Comment by christocracy** [comment]
Just go to your `android/build.gradle` and [type that in exactly](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/build.gradle#L6)

**Comment by FirdousNath** [comment]
releasing app through android studio is working fine but through flutter its still happening after updating [ext.appCompatVersion](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/build.gradle#L6)  as well.

**Comment by FirdousNath** [comment]
> decrease classpath 'com.android.tools.build:gradle:7.0.0’ from 7.0.0 to 4.0.0 helps

why downgrade if If everyone is upgrading

**Comment by christocracy** [comment]
Why do you not have compileSdkVersion, targetSdkVersion in your ext vars??

that allows all other plugins (including mine) to align themselves to globally,

otherwise, there’s no choice but to use its own defaults which can break things

**Comment by FirdousNath** [comment]
I have those in app's build.gradle

**Comment by christocracy** [comment]
Please read the plug-in’s *Android Setup* doc and define the recommended ext vars.

don’t hardcode your compileSdkVersion, targetSdkVersion in app/build.gradle where 3rd party plugin have no access to them.  

do it like [this](https://github.com/transistorsoft/flutter_background_geolocation/blob/ee329a9444a9f8fdb8d8f993990ee68d357a1491/example/android/app/build.gradle#L38)

**Comment by FirdousNath** [comment]
worked now after declaring global

**Comment by christocracy** [comment]
We’ve been doing it this way for several years in react-native.  The react-native app template does it this way automatically.  Flutter hasn’t come around yet but they will.

And [recommended here](https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties) in the Android Developer docs.
