### ISSUE TITLE
battery draining 

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/flutter_background_geolocation#772]
## Your Environment
* Plugin version: 4.6.3
* Platform:  Android
* OS version: 12
* Device manufacturer / model: pixel 4a
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
      reset: false,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopTimeout: 5,
      backgroundPermissionRationale: bg.PermissionRationale(
          title:
          "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
          message:
          "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel'),
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      heartbeatInterval: 60,
    )).then((bg.State state) async {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
```

## Expected Behavior

i want battery to drain less
## Actual Behavior

my device use to last 48 hours with normal usage nor with this app it last 7-8 hours at Max. More over my app goal is to just use geo fence and nothing else 
## Steps to Reproduce

1. create geo fence 

## Context

I am just trying to understand which config chnage will help me save the battery drain 
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Install the latest pre-release from branch `release-4.7.0`

```yaml
dependencies:
  flutter_background_geolocation:
    git: 
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: release-4.7.0
```

If you're only tracking geofences, why are you calling `.start()` and not `.startGeofences()`.  Read the API docs.

**Comment by christocracy** [comment]
If you’re tracking Geofences only, you need only call `.startGeofences()`, where desiredAccuracy is not even used.
