### ISSUE TITLE
ISSUE WITH VERSIONS IN THE PLUGIN

### ISSUE THREAD

**Issue by pavanmsgit** [transistorsoft/flutter_background_geolocation#774]
## Your Environment
* Plugin version: flutter_background_geolocation: ^4.6.3
  background_fetch: ^1.1.0

* Platform: Android
* OS version: MAC MONTEREY VERSION 12.3.1

* Device manufacturer / model: APPLE MACBOOK PRO - M1 CHIP 2020

* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[!] Android Studio
    ✗ Android Studio not found at /Users/ravanan/Applications/JetBrains Toolbox/Android Studio.app/Contents
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.transistorsoft:tsbackgroundfetch:1.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/1.1.0/tsbackgroundfetch-1.1.0.pom
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/1.1.0/tsbackgroundfetch-1.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/1.1.0/tsbackgroundfetch-1.1.0.pom
       - file:/Users/ravanan/AndroidStudioProjects/swiftanttestproject/android/app/libs/com/transistorsoft/tsbackgroundfetch/1.1.0/tsbackgroundfetch-1.1.0.pom
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/1.1.0/tsbackgroundfetch-1.1.0.pom
     Required by:
         project :app > project :background_fetch
   > Could not find com.transistorsoft:tslocationmanager:4.6.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/4.6.3/tslocationmanager-4.6.3.pom
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/4.6.3/tslocationmanager-4.6.3.pom
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/4.6.3/tslocationmanager-4.6.3.pom
       - file:/Users/ravanan/AndroidStudioProjects/swiftanttestproject/android/app/libs/com/transistorsoft/tslocationmanager/4.6.3/tslocationmanager-4.6.3.pom
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/4.6.3/tslocationmanager-4.6.3.pom
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You have references to the [deprecated `jCenter`](https://blog.gradle.org/jcenter-shutdown) repository in you gradle files (`android/build.gradle`, `android/app/build.gradle`).

**Comment by pavanmsgit** [comment]
Here is my android/build.gradle

<-- 
buildscript {
    ext.kotlin_version = '1.6.20'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
-->

**Comment by christocracy** [comment]
Now open your app in AndroidStudio and analyze the `build.gradle` of each of your added plugin.  Someone registering jcenter.

**Comment by pavanmsgit** [comment]
I changed in all the plugins. It says the below error now.

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/ravanan/AndroidStudioProjects/swiftanttestproject/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/ravanan/AndroidStudioProjects/swiftanttestproject/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
`

**Comment by christocracy** [comment]
You did not follow the *Setup Instructions* linked in the readme.

**Comment by christocracy** [comment]
There is far more to installing this plugin than simply adding to your `pubspec.yaml`.

**Comment by pavanmsgit** [comment]
I followed the instructions. Right now I'm just trying to build the application, just after adding it in **pubspec.yaml**.  I went through readme, I'm not sure what else has to be done. I've given all the necessary permissions in the Manifest file as well. Please help me out.

**Comment by christocracy** [comment]
Your `android/build.gradle` is missing required entries instructed to be added by the [Setup Guides](https://github.com/transistorsoft/flutter_background_geolocation#-setup-guides)
