### ISSUE TITLE
getCurrentPosition does not emit any location Android 11

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#778]
## Your Environment
* Plugin version:  4.6.3
* Platform: Android 11
* OS version: 
* Device manufacturer / model: SM- A032 / SAMSUM A32
* Flutter info (`flutter doctor`):

## Expected Behavior
I have a version of android 12 and the application works well, it returns GPS correctly.

But I did a test on Android 11 and it never returns a location nor does it even issue a TimeOut that it has by default.
I have tried in an emulator with android 11 and the same thing happens, it does not return any location.
Not if it happens in other versions of android

## Context
```
  try {
      emit(state.copyWith(taskGpsSuccess: true));
      var taskModified = state.stages!.indexWhere((element) => element.id == event.idStage);
      var task = state.stages![taskModified].tasks!.indexWhere((element) => element.id == event.idTask);
      state.stages![taskModified].tasks![task].action.add(op.Action(dateAction: DateTime.now(), name: event.task?.name ?? "", idTask: event.task?.id ?? ""));
      var data = await bg.BackgroundGeolocation.providerState;
      if ((data.status == bg.ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS || data.status == bg.ProviderChangeEvent.AUTHORIZATION_STATUS_WHEN_IN_USE) && data.gps) {
        var location = await bg.BackgroundGeolocation.getCurrentPosition(persist: false, samples: 1);
        // throw Exception();
        addTaskLocalMultipointUseCase(
          idTasks: event.idTask,
          task: event.task,
          idStage: event.idStage,
          finish: state.finishedLoad!,
          comment: textComments.text.isNotEmpty ? textComments.text : null,
          loadingOrderId: event.loadingOrderId,
          file: event.file,
          lat: location.coords.latitude,
          lng: location.coords.longitude,
          state: 1,
        );
        textComments.clear();
        addLogEventFirebase(name: 'tareas_realizadas_chofer_multipunto');
        add(CheckCompletedTasks());
      } else {
        emit(state.copyWith(
          taskGpsError: true,
          loading: false,
          taskGpsSuccess: false,
        ));
        return;
      }
    } catch (e, s) {
      Sentry.captureException(e, stackTrace: s);
      emit(state.copyWith(
        taskGpsError: true,
        loading: false,
        taskGpsSuccess: false,
      ));
    }
```

**Comment by miguelflores1993** [comment]
LOGS
```
06-24 23:56:43.649  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:56:43.682  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:56:43.682  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:56:43.684  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:56:43.684  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 9]
06-24 23:56:43.703  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:57:32.344  4066  4066 W TSLocationManager: [c.t.f.b.BackgroundGeolocationModule ready]
06-24 23:57:32.344  4066  4066 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
06-24 23:57:32.365  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:57:32.365  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:57:32.379  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:57:32.379  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:57:32.382  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:57:32.382  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 10]
06-24 23:57:32.391  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:57:53.388  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot]
06-24 23:57:53.388  4066  4066 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-24 23:57:53.470  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onPause] ☯️  onPause
06-24 23:57:53.471  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStop] ☯️  onStop
06-24 23:57:56.266  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStart] ☯️  onStart
06-24 23:57:56.273  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager cancelOneShot]
06-24 23:57:56.273  4066  4066 I TSLocationManager:   ⏰ Cancel OneShot: TERMINATE_EVENT
06-24 23:57:56.282  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onResume] ☯️  onResume
06-24 23:57:56.401  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:57:56.401  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:57:56.434  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:57:56.434  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:57:56.436  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:57:56.436  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 11]
06-24 23:57:56.439  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:58:42.591  4066  4066 W TSLocationManager: [c.t.f.b.BackgroundGeolocationModule ready]
06-24 23:58:42.591  4066  4066 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
06-24 23:58:42.604  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:58:42.604  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:58:42.617  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:58:42.617  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:58:42.618  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:58:42.618  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 12]
06-24 23:58:42.621  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:58:45.600  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot]
06-24 23:58:45.600  4066  4066 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-24 23:58:45.666  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onPause] ☯️  onPause
06-24 23:58:45.667  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStop] ☯️  onStop
06-24 23:58:47.481  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStart] ☯️  onStart
06-24 23:58:47.490  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager cancelOneShot]
06-24 23:58:47.490  4066  4066 I TSLocationManager:   ⏰ Cancel OneShot: TERMINATE_EVENT
06-24 23:58:47.503  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onResume] ☯️  onResume
06-24 23:58:47.614  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:58:47.614  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:58:47.622  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:58:47.622  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:58:47.625  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:58:47.625  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 13]
06-24 23:58:47.626  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:59:05.522  4066  4066 W TSLocationManager: [c.t.f.b.BackgroundGeolocationModule ready]
06-24 23:59:05.522  4066  4066 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
06-24 23:59:05.537  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:59:05.537  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:59:05.547  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:59:05.547  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:59:05.549  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:59:05.549  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 14]
06-24 23:59:05.552  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 23:59:21.841  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot]
06-24 23:59:21.841  4066  4066 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
06-24 23:59:21.945  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onPause] ☯️  onPause
06-24 23:59:21.947  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStop] ☯️  onStop
06-24 23:59:27.292  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onStart] ☯️  onStart
06-24 23:59:27.298  4066  4066 I TSLocationManager: [c.t.l.s.TSScheduleManager cancelOneShot]
06-24 23:59:27.298  4066  4066 I TSLocationManager:   ⏰ Cancel OneShot: TERMINATE_EVENT
06-24 23:59:27.315  4066  4066 D TSLocationManager: [c.t.l.l.LifecycleManager onResume] ☯️  onResume
06-24 23:59:27.401  4066  4584 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 23:59:27.401  4066  4584 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 23:59:27.432  4066  4066 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 23:59:27.432  4066  4066 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 23:59:27.438  4066  4584 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 23:59:27.438  4066  4584 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 15]
06-24 23:59:27.449  4066  4584 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]

```

**Comment by miguelflores1993** [comment]
**### LOGS ANDROID 12.
THIS IF WORKS returns a location**

`06-24 20:12:21.212 32222 32316 I TSLocationManager: ║ ⏰ OneShot event fired: TERMINATE_EVENT
06-24 20:12:21.212 32222 32316 I TSLocationManager: ╠═════════════════════════════════════════════
06-24 20:12:21.213 32222 32316 D TSLocationManager: [c.t.l.event.TerminateEvent$a a]
06-24 20:12:21.213 32222 32316 D TSLocationManager:   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
06-24 20:12:21.226 32222 32222 D TSLocationManager: [c.t.l.l.LifecycleManager onPause] ☯️  onPause
06-24 20:12:21.227 32222 32222 D TSLocationManager: [c.t.l.l.LifecycleManager onStop] ☯️  onStop
06-24 20:12:30.245 32222 32222 D TSLocationManager: [c.t.l.l.LifecycleManager onStart] ☯️  onStart
06-24 20:12:30.252 32222 32222 D TSLocationManager: [c.t.l.l.LifecycleManager onResume] ☯️  onResume
06-24 20:12:30.318 32222 32316 D TSLocationManager: [c.t.locationmanager.util.c h]
06-24 20:12:30.318 32222 32316 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
06-24 20:12:30.351 32222 32222 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 20:12:30.351 32222 32222 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 20:12:30.352 32222 32316 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation]
06-24 20:12:30.352 32222 32316 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 2, requestId: 5]
06-24 20:12:30.353 32222 32316 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
06-24 20:12:32.263 32222 32222 D TSLocationManager: [c.t.l.service.AbstractService start]
06-24 20:12:32.263 32222 32222 D TSLocationManager:   🎾  LocationRequestService [eventCount: 1]
06-24 20:12:32.274 32222 32316 I TSLocationManager: [c.t.l.s.LocationRequestService handleLocationResult]
06-24 20:12:32.274 32222 32316 I TSLocationManager: ╔═════════════════════════════════════════════
06-24 20:12:32.274 32222 32316 I TSLocationManager: ║ getCurrentPosition LocationResult: 5
06-24 20:12:32.274 32222 32316 I TSLocationManager: ╠═════════════════════════════════════════════
06-24 20:12:32.274 32222 32316 I TSLocationManager: ╟─ 📍  Location[fused -17.841495,-63.246967 hAcc=10.7 et=+5d22h41m59s922ms alt=462.8999938964844 vAcc=4.18486 vel=1.6146836 sAcc=2.9 bear=316.0 bAcc=64.5 {Bundle[EMPTY_PARCEL]}], age: 235ms, time: 1656115952054
06-24 20:12:32.306 32222 32316 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult]
06-24 20:12:32.306 32222 32316 I TSLocationManager:   🔵  Acquired current position
06-24 20:12:32.309 32222 32316 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 22.505
06-24 20:12:32.325 32222 32222 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
06-24 20:12:32.340 32222 32316 D TSLocationManager: [c.t.l.s.LocationRequestService handleLocationResult] SingleLocationRequest 5 isFinished? true
06-24 20:12:32.341 32222 32316 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
06-24 20:12:32.350 32222 32222 D TSLocationManager: [c.t.l.service.AbstractService onDestroy]
06-24 20:12:32.350 32222 32222 D TSLocationManager:   🔴  LocationRequestService stopped`

**Comment by miguelflores1993** [comment]
@christocracy help pls!

**Comment by christocracy** [comment]
Why are you doing that you keep calling `.ready()` multiple times?

>⚠️  #ready already called.  Redirecting to #setConfig

`.ready()` is designed to be called once, when your app launches.

**Comment by miguelflores1993** [comment]
> ¿Por qué haces eso y llamas `.ready()`varias veces?
> 
> > ⚠️  #listo ya llamaron. Redirigir a #setConfig
> 
> `.ready()`está diseñado para ser llamado una vez, cuando se inicia su aplicación.

every time it enters the screen the ready() is executed, is that ok?

**Comment by christocracy** [comment]
No, it’s not ok.

.ready() does not imply “*start tracking*”.  Only .start() initiated tracking.

.ready() is a signal to the plugin that your app is launched and “ready”.

.ready() is designed to be called *once* when your app is launched.

**Comment by christocracy** [comment]
You do not need to call .start() immediately after .ready() resolves.

**Comment by miguelflores1993** [comment]
> No, no está bien.
> 
> .ready() no implica " _comenzar a rastrear_ ". Solo .start() inició el seguimiento.
> 
> .ready() es una señal para el complemento de que su aplicación se inició y está "lista".
> 
> .ready() está diseñado para llamarse _una vez_ cuando se inicia la aplicación.

I understand, but why is this happening? that it works on `android 12` and on `Android 11` it doesn't work?. 

get location

**Comment by christocracy** [comment]
Works fine with the /example app on both Android 11 and 12.

I really have no clue what it is you’re doing.

create for me a simple “Hello World” app that demonstrates what you’re experiencing.

**Comment by miguelflores1993** [comment]
> Works fine with the /example app on both Android 11 and 12. I test every day.
> 
> I really have no clue what it is you’re doing.
> 
> create for me a simple “Hello World” app that demonstrates what you’re experiencing. Post to a public GitHub repo.

before it worked fine, now not since I updated to 4.7.0
I will see what I can do, thanks.

**Comment by christocracy** [comment]
You’re likely doing something unusual.  I await your *hello world* app.
