### ISSUE TITLE
Debug sound is heard whenever background fetch operates after 4.7.0 version update.

### ISSUE THREAD

**Issue by Taeila92** [transistorsoft/flutter_background_geolocation#779]
## Your Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: SM-N981N
* Flutter info (`flutter doctor`):
* [✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
          disableLocationAuthorizationAlert: false,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          allowIdenticalLocations: false,
          stopOnTerminate: false,
          startOnBoot: true,
          preventSuspend: true,
          enableHeadless: true,
          speedJumpFilter: 250, 
          debug:
              false,
          motionTriggerDelay:
              5000,
          stopTimeout: 5,
          logLevel: bg.Config.LOG_LEVEL_ERROR,)
```

## Expected Behavior

Debug sound should not be heard.

## Actual Behavior

I set debug sound to false, but when I look at the log, I hear debug sound whenever background fetch is operated.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Did you copy/paste code from the `/example` app?

**Comment by Taeila92** [comment]
yes, I did

**Comment by christocracy** [comment]
That’s why.  The example app purposely uses an undocumented method of background-geolocation to play sound effects which are not controlled by `Config.debug`.
