### ISSUE TITLE
how can I change the (200-500 meters) distance at which the tracking system starts?

### ISSUE THREAD

**Issue by mhdkadi** [transistorsoft/flutter_background_geolocation#783]
how can I change the (200-500 meters) distance at which the tracking system starts?

## Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: samsung a20
* Flutter info (`flutter doctor`):
 [√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 2021.2)
[√] VS Code
[√] Connected device (3 available)
[√] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      geofenceProximityRadius: 1,
      geofenceModeHighAccuracy: true,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      isMoving: true,
      allowIdenticalLocations: true,
      desiredOdometerAccuracy: 10,
      disableStopDetection: true,
      disableMotionActivityUpdates: ,
      enableHeadless: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      reset: true,
      locationUpdateInterval: 1000,
    )
```

## Expected Behavior
I want the motion state (onMotionChange) to change when the device moves 10m

## Actual Behavior
The state of motion does not change until a long-distance has been traveled

**Comment by christocracy** [comment]
You're free to *manually* engage location-tracking by manually calling `.changePace(true)` after `.start()` has been called.

`Config.stopTimeout` still applies with `.changePace(true)`.  Once the device has been detected to be stationary for `Config.stopTimeout` minutes, the plugin will automatically call `.changePace(false)` **upon itself** and re-enter the stationary-state.

```dart
void _startTracking() async {
  await BackgroundGeolocation.start();
  await BackgroundGeolocation.changePace(true);
}
```

**Comment by mhdkadi** [comment]
flutter background geolocation is it a one-time payment or i should pay yearly?
