### ISSUE TITLE
Is there a way to detect location once every N hours on iOS?

### ISSUE THREAD

**Issue by jeffzwang** [transistorsoft/flutter_background_geolocation#784]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS or Android iOS
* OS version: 13
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_LOW,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: true,
            locationUpdateInterval: 10000,
            heartbeatInterval: 60,
            activityRecognitionInterval: 20000,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))

```

## Expected Behavior

n/a

## Actual Behavior

n/a
## Steps to Reproduce

n/a
## Context

I followed the template but I really just have a question - is there a way to trigger detecting location every N hours? I see that it is possible to do via Android because of the `LocationUpdateInterval` setting, but I don't know how to do this in iOS. Have read every field in the config docs and still don't know if this would be possible. Thanks!

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Use background_fetch, also created by me and already included as a dependency.

execute `BackgroundGeolocation.getCurrentPosition()` in your fetch callback.

that is the *only* way to execute periodic code on iOS.

see the readme for background_fetch.
