### ISSUE TITLE
We do not recive any location upload for the time when user is underground or in metro.

### ISSUE THREAD

**Issue by erluxman** [transistorsoft/flutter_background_geolocation#793]
#### Following is my config of plugin

```dart
Config get config => Config(
      desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      logLevel: Config.LOG_LEVEL_ERROR,
      locationAuthorizationRequest: "Always",
      locationAuthorizationAlert: {
        "titleWhenNotEnabled": tr(LocaleKeys.location_always_allow_title),
        "instructions": tr(LocaleKeys.location_always_allow_description),
        "cancelButton": tr(LocaleKeys.dialog_cancel),
        "settingsButton": tr(LocaleKeys.settings)
      },
      notification: Notification(
        smallIcon: 'mipmap/ic_notification',
        channelName: "Greenplay Tracking",
        largeIcon: 'mipmap/ic_notification',
        text: 'Collecting Locations',
        title: "Greenplay",
        priority: Config.NOTIFICATION_PRIORITY_HIGH,
      ),
      activityType: Config.ACTIVITY_TYPE_OTHER_NAVIGATION,
      preventSuspend: true,
      forceReloadOnBoot: true,
      forceReloadOnGeofence: true,
      forceReloadOnHeartbeat: true,
      forceReloadOnLocationChange: true,
      forceReloadOnMotionChange: true,
      forceReloadOnSchedule: true,
      isMoving: true,
      foregroundService: true,
      distanceFilter: 10, //10 meters
      stopTimeout: 5,
      batchSync: true,
      url: uploadUrl,
      locationUpdateInterval: 10 * 1000, //10 seconds
      activityRecognitionInterval: 10 * 1000, //10 seconds
      persistMode: Config.PERSIST_MODE_LOCATION,
      backgroundPermissionRationale: PermissionRationale(
          title: tr(LocaleKeys.location_permission_title),
          message: tr(LocaleKeys.location_permission_description),
          positiveAction: tr(LocaleKeys.location_confirm_button_text),
          negativeAction: tr(LocaleKeys.dialog_cancel)),
      maxRecordsToPersist: 2000,
      reset: true,
      enableHeadless: true,
      allowIdenticalLocations: false,
      minimumActivityRecognitionConfidence: 50,
      heartbeatInterval: 60,
    );

```

#### Expected behavior : 

Collect location and upload it later to the server.  like it is regularly done before 18:21 and after 18:30 (Please refer to the screenshot attached at the end) 

#### Real behavior: 

It collects before and after the user is inside the tunnel/underground/metro but doesn't during the time user is inside.
(User was in metro between 18:21 to 18:30) 

#### Operating systems: both Android and iOS
![CleanShot 2022-07-06 at 19 08 57](https://user-images.githubusercontent.com/6260014/177560568-56035e87-ff2e-49f4-9c1d-c996589da940.png)

**Comment by christocracy** [comment]
Here's a metro ride I did 3 days ago.  Completely typical behaviour for a metro ride.

<img width="1814" alt="Screen Shot 2022-07-06 at 10 23 32 AM" src="https://user-images.githubusercontent.com/14999/177574614-72297b0d-cd72-4553-9b3c-bc2788b7ce05.png">

**Comment by bertrandgelinas** [comment]
Is there anything we could get from the package if we don't have GPS of wifi? Like odometer or activity Type?

**Comment by christocracy** [comment]
>Like odometer

No.  The odometer is the summation of the distance of the `currentLocation` to `lastLocation`.  If no location is received, the odometer is not updated.

```
odometer += currentLocation.distanceTo(lastLocation);
```

> activity Type?

Yes.  Listen to `onActivityChange` event.

**Comment by christocracy** [comment]
BTW, the following `Config` options no longer exist.  You can delete all these.

>forceReloadOnBoot: true,
>forceReloadOnGeofence: true,
>forceReloadOnHeartbeat: true,
>forceReloadOnLocationChange: true,
>forceReloadOnMotionChange: true,
>forceReloadOnSchedule: true,
>foregroundService: true,
>minimumActivityRecognitionConfidence: 50,

**Comment by christocracy** [comment]
> will the event from onActivityChange also be uploaded?

No.  The plugin only does http requests for recorded locations.

If you want to upload motion-activity events, you’ll need to manage that yourself with your own custom code.

**Comment by erluxman** [comment]
The problem of doing that from dart world is that we cannot sync the data as we can with native( the upload process plugin uses right now). Will it be possible to add a flag in the config to include activityChange to be uploaded?

**Comment by christocracy** [comment]
> possible to add a flag in the config to include 

Sorry, no.
