### ISSUE TITLE
bg.Location always return "still 100%" but TSLocationManager at the startup gives the good activity

### ISSUE THREAD

**Issue by bulgarian-beast** [transistorsoft/flutter_background_geolocation#795]
I noticed that if the location service is started while driving, only the "Still" activity at 100% is shown by your plugin while for example the logs show:
```TSLocationManager(14200):   🚘 ️DetectedActivity [type=IN_VEHICLE, confidence=96]```

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on SM A217F is available at:
http://127.0.0.1:52467/5ZjAXZ6qGTg=/
W/DynamiteModule(14200): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule(14200): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(14200): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
I/ultimsoft.eroa(14200): The ClassLoaderContext is a special shared library.
I/ultimsoft.eroa(14200): The ClassLoaderContext is a special shared library.
V/NativeCrypto(14200): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...
W/ultimsoft.eroa(14200): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/ProviderInstaller(14200): Installed default security provider GmsCore_OpenSSL
I/ultimsoft.eroa(14200): Background concurrent copying GC freed 86168(5691KB) AllocSpace objects, 16(528KB) LOS objects, 49% free, 5088KB/10177KB, paused 174us total 126.909ms
The Flutter DevTools debugger and profiler on SM A217F is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:52467/5ZjAXZ6qGTg=/
W/ultimsoft.eroa(14200): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/ultimsoft.eroa(14200): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/ultimsoft.eroa(14200): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
I/Gralloc4(14200): mapper 4.x is not supported
W/Gralloc3(14200): mapper 3.x is not supported
I/gralloc (14200): Arm Module v1.0
W/ultimsoft.eroa(14200): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/ultimsoft.eroa(14200): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/ultimsoft.eroa(14200): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
I/SurfaceView(14200): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@4fa2b57 surfaceControl = Surface(name=SurfaceView - com.ultimsoft.eroad/com.ultimsoft.eroad.MainActivity@4bd2509@0)/@0x4032644 frame = 1
I/ViewRootImpl@d186344[MainActivity](14200): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@c746a7c[MainActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@c746a7c[MainActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
V/InputMethodManager(14200): Starting input: tba=com.ultimsoft.eroad ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(14200): startInputInner - Id : 0
I/InputMethodManager(14200): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(14200): Input channel constructed: 'ClientS', fd=129
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@c746a7c[MainActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
V/InputMethodManager(14200): Starting input: tba=com.ultimsoft.eroad ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(14200): startInputInner - Id : 0
I/SurfaceControl(14200): nativeRelease nativeObject s[545242947680]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242947680]
I/SurfaceControl(14200): nativeRelease nativeObject s[545242947584]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242947584]
D/TSLocationManager(14200): [c.t.f.b.streams.StreamHandler onListen] location
D/TSLocationManager(14200): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [backgroundPermissionRationale, backgroundPermissionRationale.title, backgroundPermissionRationale.message, backgroundPermissionRationale.positiveAction, backgroundPermissionRationale.negativeAction, batchSync, desiredAccuracy, disableStopDetection, distanceFilter, enableHeadless, headlessJobService, logLevel, notification, notification.title, notification.text, startOnBoot, stopOnTerminate]
W/Settings(14200): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager(14200): [c.t.locationmanager.util.c g] 
D/TSLocationManager(14200):   ℹ️  LocationAuthorization: Permission granted
W/Settings(14200): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/TSLocationManager(14200): - Enable: true → true, trackingMode: 1
D/TSLocationManager(14200): [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
D/TSLocationManager(14200):   🎾  Start monitoring connectivity changes
D/TSLocationManager(14200): [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
D/TSLocationManager(14200):   🎾  Start monitoring powersave changes
D/TSLocationManager(14200): [c.t.locationmanager.util.c h] 
D/TSLocationManager(14200):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager(14200): [c.t.l.service.HeartbeatService stop] 
I/TSLocationManager(14200):   🔴  Stop heartbeat
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager(14200): [c.t.l.l.SingleLocationRequest startUpdatingLocation] 
I/TSLocationManager(14200):   🔵  [SingleLocationRequest start, action: 1, requestId: 1]
I/TSLocationManager(14200): [c.t.l.s.ActivityRecognitionService start] 
I/TSLocationManager(14200):   🎾  Start motion-activity updates
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
D/TSLocationManager(14200): [c.t.l.a.TSLocationManagerActivity execute] locationsettings
D/TSLocationManager(14200): [c.t.l.adapter.TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
I/DecorView(14200): [INFO] isPopOver=false, config=true
I/DecorView(14200): updateCaptionType >> DecorView@8ff4341[], isFloating=true, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
D/DecorView(14200): setCaptionType = 0, this = DecorView@8ff4341[]
W/ultimsoft.eroa(14200): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ultimsoft.eroa(14200): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/InputTransport(14200): Input channel constructed: '6a6a4b9', fd=142
I/ViewRootImpl@bcb54ed[TSLocationManagerActivity](14200): setView = com.android.internal.policy.DecorView@8ff4341 TM=true
I/SurfaceControl(14200): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x519e07a / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@bcb54ed[TSLocationManagerActivity](14200): Relayout returned: old=(0,68,720,1574) new=(360,821,360,821) req=(0,0)0 dur=33 res=0x7 s={true 542173392896} ch=true fn=-1
I/flutter (14200): [ready] ERROR: PlatformException(Waiting for previous start action to complete, null, null, null)
I/ViewRootImpl@d186344[MainActivity](14200): MSG_WINDOW_FOCUS_CHANGED 0 1
I/SurfaceControl(14200): nativeRelease nativeObject s[547786553376]
I/SurfaceControl(14200): nativeRelease nativeObject e[547786553376]
I/SurfaceControl(14200): nativeRelease nativeObject s[547786551648]
I/SurfaceControl(14200): nativeRelease nativeObject e[547786551648]
I/SurfaceControl(14200): nativeRelease nativeObject s[547786553280]
I/SurfaceControl(14200): nativeRelease nativeObject e[547786553280]
I/ViewRootImpl@bcb54ed[TSLocationManagerActivity](14200): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@8ff4341[TSLocationManagerActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@8ff4341[TSLocationManagerActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
V/InputMethodManager(14200): Starting input: tba=com.ultimsoft.eroad ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(14200): startInputInner - Id : 0
I/InputMethodManager(14200): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(14200): Input channel constructed: 'ClientS', fd=144
D/InputTransport(14200): Input channel destroyed: 'ClientS', fd=129
D/TSLocationManager(14200): [c.t.l.a.TSLocationManagerActivity stop] eventCount: 0
I/SurfaceControl(14200): nativeRelease nativeObject s[545242948064]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242948064]
I/SurfaceControl(14200): nativeRelease nativeObject s[545242947968]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242947968]
I/SurfaceControl(14200): nativeRelease nativeObject s[547786553472]
I/SurfaceControl(14200): nativeRelease nativeObject e[547786553472]
I/SurfaceControl(14200): nativeRelease nativeObject s[545164091232]
I/SurfaceControl(14200): nativeRelease nativeObject e[545164091232]
I/SurfaceControl(14200): nativeRelease nativeObject s[547787624800]
I/SurfaceControl(14200): nativeRelease nativeObject e[547787624800]
I/SurfaceControl(14200): nativeRelease nativeObject s[547786553568]
I/SurfaceControl(14200): nativeRelease nativeObject e[547786553568]
I/ViewRootImpl@d186344[MainActivity](14200): stopped(false) old=false
I/ViewRootImpl@bcb54ed[TSLocationManagerActivity](14200): stopped(true) old=false
I/SurfaceControl(14200): nativeRelease nativeObject s[542580519936]
I/SurfaceControl(14200): nativeRelease nativeObject e[542580519936]
I/TSLocationManager(14200): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(14200):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
D/TSLocationManager(14200): [c.t.l.a.TSLocationManagerActivity onDestroy] 
W/libEGL  (14200): EGLNativeWindowType 0x7e3c0d7010 disconnect failed
I/ViewRootImpl@bcb54ed[TSLocationManagerActivity](14200): dispatchDetachedFromWindow
D/InputTransport(14200): Input channel destroyed: '6a6a4b9', fd=142
E/ViewRootImpl(14200): sendUserActionEvent() mView returned.
I/ViewRootImpl@d186344[MainActivity](14200): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@c746a7c[MainActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
D/InputMethodManager(14200): prepareNavigationBarInfo() DecorView@c746a7c[MainActivity]
D/InputMethodManager(14200): getNavigationBarColor() -855310
V/InputMethodManager(14200): Starting input: tba=com.ultimsoft.eroad ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(14200): startInputInner - Id : 0
I/InputMethodManager(14200): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(14200): Input channel constructed: 'ClientS', fd=140
D/InputTransport(14200): Input channel destroyed: 'ClientS', fd=144
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager(14200): [c.t.l.s.LocationRequestService handleLocationAvailability] 
I/TSLocationManager(14200):   ℹ️  Location availability: true
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
I/SurfaceControl(14200): nativeRelease nativeObject s[545242947680]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242947680]
I/SurfaceControl(14200): nativeRelease nativeObject s[545242947584]
I/SurfaceControl(14200): nativeRelease nativeObject e[545242947584]
W/ultimsoft.eroa(14200): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
I/TSLocationManager(14200): [c.t.l.scheduler.ScheduleEvent onOneShot] 
I/TSLocationManager(14200): ╔═════════════════════════════════════════════
I/TSLocationManager(14200): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(14200): ╠═════════════════════════════════════════════
D/TSLocationManager(14200): [c.t.l.event.TerminateEvent$a a] 
D/TSLocationManager(14200):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager(14200): [c.t.l.s.LocationRequestService handleLocationAvailability] 
I/TSLocationManager(14200):   ℹ️  Location availability: false
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  ActivityRecognitionService [eventCount: 1]
D/TSLocationManager(14200): [c.t.l.s.ActivityRecognitionService handleActivityRecognitionResult] 
D/TSLocationManager(14200):   🚘 ️DetectedActivity [type=IN_VEHICLE, confidence=96]
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
D/TSLocationManager(14200): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(14200):   🔴  ActivityRecognitionService stopped
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager(14200): [c.t.l.s.LocationRequestService handleLocationResult] 
I/TSLocationManager(14200): ╔═════════════════════════════════════════════
I/TSLocationManager(14200): ║ motionchange LocationResult: 1
I/TSLocationManager(14200): ╠═════════════════════════════════════════════
I/TSLocationManager(14200): ╟─ 📍  Location[fused 43,439279,-0,645149 hAcc=40 et=+14h27m20s438ms alt=140.89255918488362 vel=32.07 bear=101.0 vAcc=56 sAcc=1 bAcc=7 {Bundle[mParcelledData.dataSize=52]}], age: 63ms, time: 1657974418000
I/TSLocationManager(14200): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager(14200):   🔵  Acquired motionchange position, isMoving: false
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  LocationRequestService [eventCount: 2]
I/TSLocationManager(14200): [c.t.l.s.LocationRequestService handleLocationAvailability] 
I/TSLocationManager(14200):   ℹ️  Location availability: true
D/TSLocationManager(14200): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 39.5
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 1, sticky: true]
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/TSLocationManager(14200): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(14200):   🔴  LocationRequestService stopped
D/TSLocationManager(14200): [c.t.l.s.LocationRequestService handleLocationResult] SingleLocationRequest 1 isFinished? true
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/TSLocationManager(14200): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
D/TSLocationManager(14200):   🎾  Start monitoring stationary region (radius: 150.0m 43.4392791,-0.6451494 hAcc=39.5)
D/TSLocationManager(14200): [c.t.l.service.AbstractService start] 
D/TSLocationManager(14200):   🎾  TrackingService [eventCount: 1]
I/TSLocationManager(14200): [c.t.l.service.TrackingService handleMotionChangeResult] 
I/TSLocationManager(14200): ╔═════════════════════════════════════════════
I/TSLocationManager(14200): ║ TrackingService motionchange: false
I/TSLocationManager(14200): ╠═════════════════════════════════════════════
D/TSLocationManager(14200): [c.t.l.service.AbstractService finish] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]
I/flutter (14200): ________________________________________________
I/flutter (14200): {odometer: 71595.5, activity: {confidence: 100, type: still}, extras: {}, event: motionchange, battery: {level: 0.66, is_charging: true}, uuid: c9206472-3c80-42d1-89e9-0f6e135fcf79, coords: {altitude: 140.9, heading: 101.0, latitude: 43.4392791, accuracy: 39.5, heading_accuracy: 6.8, altitude_accuracy: 55.7, speed_accuracy: 0.69, speed: 32.07, longitude: -0.6451494}, is_moving: false, timestamp: 2022-07-16T12:26:58.000Z}
I/flutter (14200): ________________________________________________
I/flutter (14200): **********************************************************************
I/flutter (14200): COMPUTING...
I/flutter (14200): [Location {odometer: 71595.5, activity: {confidence: 100, type: still}, extras: {}, event: motionchange, battery: {level: 0.66, is_charging: true}, uuid: c9206472-3c80-42d1-89e9-0f6e135fcf79, coords: {altitude: 140.9, heading: 101.0, latitude: 43.4392791, accuracy: 39.5, heading_accuracy: 6.8, altitude_accuracy: 55.7, speed_accuracy: 0.69, speed: 32.07, longitude: -0.6451494}, is_moving: false, timestamp: 2022-07-16T12:26:58.000Z}]
I/flutter (14200): **********************************************************************
D/TSLocationManager(14200): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(14200):   🔴  TrackingService stopped

## Your Environment
* Plugin version:
```
    flutter_background_geolocation:
        git:
            url: https://github.com/transistorsoft/flutter_background_geolocation.git

```
* Platform: iOS or Android
* OS version:
* Device manufacturer / model: SM A217F (Samsung Android)
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Future<void> initPlatformState(UserInfos user) async {
  Timer? timer;
  user.currentTrip["isRecording"] = false;
  Map<dynamic, dynamic> locMap = {};

  bg.BackgroundGeolocation.onLocation((bg.Location loc) async {
    locMap = correctMssingDriving(loc.toMap());

    print("________________________________________________");
    print(locMap);
    print("________________________________________________");
    // print(locMap["activity"]);

    // print(locMap["coords"]);

    print(
        "**********************************************************************");
    print("COMPUTING...");

    user = await compute(timer, locMap, user);
    print(loc);
    print(
        "**********************************************************************");
  }, (error) {
    print("on location error");
    print(error);
  });

  await bg.BackgroundGeolocation.ready(
    bg.Config(
      preventSuspend: true,
      foregroundService: true,
      notification: bg.Notification(
        title: "hello",
        text: "world",
      ),
      reset: true,
      debug: false,
      batchSync: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0.0,
      locationAuthorizationRequest: 'Always',
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
    ),
  ).then((bg.State state) async {
    await bg.BackgroundGeolocation.start();
  }).catchError((error) {
    print('[ready] ERROR: $error');
  });
}

```

**Comment by bulgarian-beast** [comment]
@transistorsoft-pkg @christocracy Any update on that ?

**Comment by alexb007** [comment]
I'm also facing this issue on Xiaomi Note 7 Android 10 and Samsung A6 (2016)
