### ISSUE TITLE
Start the event listeners, when app in background or minimize state

### ISSUE THREAD

**Issue by iloads** [transistorsoft/flutter_background_geolocation#799]
## Your Environment
* Plugin version: 4.4.0
* Platform: iOS and Android
* OS version: Android 10 and IOS 13
* Device manufacturer / model: Samsung s9 plus and IOS 13
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
    • Flutter version 2.5.2 at D:\Flutter_SDK\Flutter_2.5.2_Stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (10 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
static bg.Config config= bg.Config(
      preventSuspend: true,
      enableHeadless: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      disableElasticity: false,
      elasticityMultiplier: 4.0,
      stopOnTerminate: false,
      stationaryRadius: 10.0,
      startOnBoot: true,
      debug: false,
      stopTimeout: 5, // min
      disableStopDetection: Platform.isIOS? true:false,
      pausesLocationUpdatesAutomatically: false,
      heartbeatInterval:60, //1 min
      logLevel: (Flavor.get() == FlavorsType.iex || Flavor.get() == FlavorsType.ca) ? bg.Config.LOG_LEVEL_INFO
          :bg.Config.LOG_LEVEL_VERBOSE, // Common
      notification: bg.Notification(
          channelName: AppStrings.get()!.locBgNotificationChannelName,
          title:Flavor.isCA()?StringConstant.TRACKING_NOTIFY_TITLE_CA:StringConstant.TRACKING_NOTIFY_TITLE_IEX,
          text:StringConstant.TRACKING_NOTIFY_BODY,
          priority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
          sticky: true
      ),
      geofenceModeHighAccuracy: true,
      showsBackgroundLocationIndicator: true

  );

Future<void> startLocationUpdates(String fromWhere) async {
   
     bg.State state=await bg.BackgroundGeolocation.state;
      print('=====STATE===========$state');
      if(!state.enabled || fromWhere=='from Re-Enter to App' || fromWhere=='from Foreground Notification'||
          fromWhere=='from Background Notification') {
        await LocationTrackByTransistor.registerEventListeners().then((value)
        async => await LocationTrackByTransistor.startLocationTrack());
      }
  }

  static Future<void> registerEventListeners() async{
   
    bg.State state=await bg.BackgroundGeolocation.state;
    if(state.enabled){
      print("===========REMOVE LISTENERS============");
      await bg.BackgroundGeolocation.removeListeners().whenComplete(() async => await startEventListeners());
    } else
      await startEventListeners();
  }

  static Future<void> startEventListeners() async{
    print("===========START LISTENERS============");

    bg.BackgroundGeolocation.onActivityChange((p0) async{

      print('===ON_ACTIVITY_CHANGE_FOREGROUND===$p0');
    });
    bg.BackgroundGeolocation.onConnectivityChange((p0){
      print('===ON_CONNECTIVITY_CHANGE_FOREGROUND===$p0');

    });
    bg.BackgroundGeolocation.onEnabledChange((p0){
      print('===ON_ENABLED_CHANGE_FOREGROUND===$p0');
    });

    bg.BackgroundGeolocation.onPowerSaveChange((p0){
      print('===ON_POWER_CHANGE_FOREGROUND===$p0');
    });

    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('===ON_PROVIDER_CHANGE_FOREGROUND===$event');
    });

    bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent heartbeatEvent) async {
      print('===ON_HEART_BEAT__FOREGROUND===$heartbeatEvent');
      if(heartbeatEvent.location!=null){
        heartbeatEvent.location!.sample=true;
        await updateDriverStatusByTransistor(heartbeatEvent.location!.coords.latitude, heartbeatEvent.location!.coords.longitude,
            heartbeatEvent.location!.isMoving,heartbeatEvent.location!.activity.type,heartbeatEvent.location!.battery.isCharging,
            heartbeatEvent.location!.battery.level.toString(),heartbeatEvent.location!.coords.speed.toString(),
            heartbeatEvent.location!.event,'Foreground');
      } else{
        print('===FOREGROUND_HEARTBEAT_LOCATION_NULL===');
        bg.BackgroundGeolocation.getCurrentPosition(
          samples: 1,
        ).then((Location location) async{
          print('===GET_CURRENT_LOCATION_FOREGROUND===${location}');
        });
      }
    });

    bg.BackgroundGeolocation.onLocation((bg.Location location) async {
      location.sample=true;
      print('==LOCATION_FOREGROUND==$location');
      await updateDriverStatusByTransistor(location.coords.latitude, location.coords.longitude,
          location.isMoving,location.activity.type,location.battery.isCharging,
          location.battery.level.toString(),location.coords.speed.toString(),location.event.isNotEmpty?location.event:'location','Foreground');
    });

    bg.BackgroundGeolocation.onMotionChange((bg.Location location) async{
      location.sample=true;
      print('===ON_MOTION_CHANGE_FOREGROUND===$location');
    });
  }

  static Future<void>  startLocationTrack() async {
    bg.BackgroundGeolocation.ready(config).then((bg.State state) {
      if (!state.enabled) {
        print('===BACKGROUND LOCATION GOING TO START===');
        bg.BackgroundGeolocation.start();
      }else
        print('===BACKGROUND LOCATION ALREADY STARTED===');
    });
  }

```

## Expected Behavior
When receiving the push notification, The Plugin need to start the event listeners, when app in the Background or Minimize the State 
## Actual Behavior
Event Listeners are not waking up. Getting MissingPluginException.

## Steps to Reproduce

1. Move the app to the background
2. Send the notification
3. 
4.

## Context
In my app, I have made a provision of sending a Notification via FCM to the respective Mobile Device when the App has not sent Lat / long updates for more than 1 hour during any of the following conditions

1. Mobile Device can be in any state -  Still or Moving
2. App can be in any state Foreground or Background or App killed

Now upon receiving a backend notification that the Lat / Lng has not been updated for more than 1 hour, I want to start the plugin again to send the Lat Lng to the backend server, 

I have achieved the same but in one scenario I am not able to send the Lat / Lng

The scenario is when the App is in the Minimize or Background state.

Please  help to set the appropriate config settings for android and ios

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/activitychange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/activitychange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/connectivitychange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/connectivitychange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/enabledchange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/enabledchange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/powersavechange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/powersavechange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================
I/flutter (17138): ===BACKGROUND LOCATION ALREADY STARTED===

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/providerchange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/providerchange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/heartbeat:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/heartbeat)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/location:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/location)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel com.transistorsoft/flutter_background_geolocation/events/motionchange:
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/motionchange)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================
I/TSLocationManager(17138): [c.t.l.scheduler.ScheduleEvent onOneShot] 
I/TSLocationManager(17138): ╔═════════════════════════════════════════════
I/TSLocationManager(17138): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(17138): ╠═════════════════════════════════════════════
D/TSLocationManager(17138): [c.t.l.event.TerminateEvent <init>] 
D/TSLocationManager(17138):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).

D/TSLocationManager(17138): [c.t.l.service.AbstractService a] 
D/TSLocationManager(17138):   🎾  HeartbeatService [eventCount: 1]
D/TSLocationManager(17138): [c.t.l.s.HeartbeatService$a run] ❤️
D/TSLocationManager(17138): [c.t.l.service.AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
D/TSLocationManager(17138): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(17138):   🔴  HeartbeatService destroyed

D/TSLocationManager(17138): [c.t.l.service.AbstractService a] 
D/TSLocationManager(17138):   🎾  HeartbeatService [eventCount: 1]
D/TSLocationManager(17138): [c.t.l.s.HeartbeatService$a run] ❤️
D/TSLocationManager(17138): [c.t.l.service.AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
D/TSLocationManager(17138): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(17138):   🔴  HeartbeatService destroyed

D/TSLocationManager(17138): [c.t.l.service.AbstractService a] 
D/TSLocationManager(17138):   🎾  HeartbeatService [eventCount: 1]
D/TSLocationManager(17138): [c.t.l.s.HeartbeatService$a run] ❤️
D/TSLocationManager(17138): [c.t.l.service.AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
D/TSLocationManager(17138): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(17138):   🔴  HeartbeatService destroyed
```

</details>

**Comment by christocracy** [comment]
There are three possible states for an app.
1.  Foreground
2. Background (likely what you call "*minimized*")
3. Terminated ("Headless")

Are you talking about the *terminated* (ie: *"Headless"*) state?

**Comment by iloads** [comment]
As asking for ( 2. Background (likely what you call "minimized" ). I can able to start the plugin in Foreground and Terminated state.

**Comment by christocracy** [comment]
> Now upon receiving a backend notification

Show me this code.

**Comment by iloads** [comment]
Fine code below. In this, we call the method "startLocationUpdates('from Background Notification')", when notification received.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
 

  final NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  /// Note: permissions aren't requested here just to demonstrate that can be
  /// done later
  final IOSInitializationSettings initializationSettingsIOS =
      IOSInitializationSettings(
          requestAlertPermission: false,
          requestBadgePermission: false,
          requestSoundPermission: false,
          onDidReceiveLocalNotification:
              (int id, String? title, String? body, String? payload) async {
            didReceiveLocalNotificationSubject.add(ReceivedNotification(
                id: id, title: title, body: body, payload: payload));
          });
  const MacOSInitializationSettings initializationSettingsMacOS =
      MacOSInitializationSettings(
          requestAlertPermission: false,
          requestBadgePermission: false,
          requestSoundPermission: false);
  final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
      macOS: initializationSettingsMacOS);
  await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: (String? payload) async {
    if (payload != null) {
      debugPrint('notification payload: $payload');
    }
    selectNotificationSubject.add(payload);
  });

  try {
    await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
    FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);
    runApp(CourierAlliance(config));
    print('Working BG Task ------------------------------------>');
  } catch (e) {
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
    print('Exception ---------------------------------------->' + e.toString());
  }







Future<dynamic> myBackgroundMessageHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("================BACKGROUND NOTIFICATION======================");
  if (message.notification != null) {
    print('*****************************************');
    print("Background Notification received ");
    print('Msg DATA: ${message.data}');
    print('Msg Notification: ${message.notification!.body}');
    print('*****************************************');
    if(message.data['notificationType'].toString()=='12'){
      CustomSharedPrefs customSharedPrefs = CustomSharedPrefs();
      CustomLocationUpdates? locationUpdatesNotification=new CustomLocationUpdates(customSharedPrefs);
      locationUpdatesNotification.startLocationUpdates('from Background Notification');
    }
    
  }else{
  FirebaseMessaging.instance.getInitialMessage().then((RemoteMessage? message) {
    if (message != null) {
      print('*****************************************');
      print("Background Message called when terminated");
      print('*****************************************');
      String aNotificationType = message.data['notificationType'].toString();
      String orderID = message.data['orderId'].toString();
      selectNotificationSubject.add('$aNotificationType,$orderID');
    }
  });
  AndroidInitializationSettings android = new AndroidInitializationSettings(
      '@mipmap/ic_launcher'); //@mipmap/ic_launcher
  IOSInitializationSettings ios = new IOSInitializationSettings(
    onDidReceiveLocalNotification: (id, title, body, payload) {

    },);
  var initSettings = new InitializationSettings(android: android, iOS: ios);
  var flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
  flutterLocalNotificationsPlugin.initialize(initSettings);

  String? val = '';
  String? aNotificationType = '';
  String? OrderID = '';
  String? mTitle = '';
  print('${message}');

  val = message.data['message'];
  aNotificationType = message.data['notificationType'];
  OrderID = message.data['orderId'];
  mTitle = message.data['title'];

  print("================BACKGROUND NOTIFICATION======================");
  print('**************************************');
  print("Notification Message:" + val.toString());
  print("Notification OrderID:" + OrderID.toString());
  print("Notification Type BG:" + aNotificationType!);
  print('**************************************');

  CustomSharedPrefs customSharedPrefs = CustomSharedPrefs();
  bool isTrackingEnabled = await customSharedPrefs.getTrackUser();
  CustomLocationUpdates? locationUpdatesNotification=new CustomLocationUpdates(customSharedPrefs);

  if (aNotificationType == '8' || aNotificationType == '9') {
    int aCount = await customSharedPrefs.getNotificationCount();
    aCount++;
    customSharedPrefs.setNoticationCount(aCount);
  }else if(aNotificationType=='12'){
    //Non Trackable Notification
    locationUpdatesNotification.startLocationUpdates('from Background Notification');
  }

  var androidPlatformChannelSpecifies = new AndroidNotificationDetails(
      Utils.getChannelID(aNotificationType), "Courier Alliance",
      channelDescription: "Courier Alliance",
      importance: Importance.max,
      groupKey: 'iex',
      groupAlertBehavior: GroupAlertBehavior.all,
      priority: Priority.max,
      visibility: NotificationVisibility.public,
      color: Colors.blue,
      channelShowBadge: true,
      autoCancel: true,
      enableVibration: true,
      styleInformation: BigTextStyleInformation(''),
      largeIcon: DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
      playSound: true,
      sound: Utils.getSound(aNotificationType));
  var iOSPlatformChannelSpecifics = new IOSNotificationDetails(
      presentAlert: true, presentSound: true, presentBadge: true);
  var platformChannelSpecifics = new NotificationDetails(
      android: androidPlatformChannelSpecifies,
      iOS: iOSPlatformChannelSpecifics);
  int random = new Random().nextInt(1000);
  if (Platform.isAndroid) {
    await flutterLocalNotificationsPlugin.show(
        random, mTitle, val, platformChannelSpecifics,
        payload: '$aNotificationType,$OrderID');
  }
}
  return ;
}

**Comment by christocracy** [comment]
Please learn to [syntax highlight codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by iloads** [comment]
```
void main() {
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);
}

 
Future<dynamic> myBackgroundMessageHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  startLocationUpdates('from Background Notification');
}

```

**Comment by christocracy** [comment]
```diff
Future<dynamic> myBackgroundMessageHandler(RemoteMessage message) async {
+  DartPluginRegistrant.ensureInitialized();
  await Firebase.initializeApp();
  startLocationUpdates('from Background Notification');
}
```

**Comment by iloads** [comment]
Hi @christocracy , Actually, we currently using Flutter SDK 2.5.2 stable

Flutter info (flutter doctor):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19044.1706], locale en-IN)
• Flutter version 2.5.2 at D:\Flutter_SDK\Flutter_2.5.2_Stable
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 3595343e20 (10 months ago), 2021-09-30 12:58:18 -0700
• Engine revision 6ac856380f
• Dart version 2.14.3

This method we can use only above version 3+.
,,,
DartPluginRegistrant.ensureInitialized();
,,,

So, I try to register plugin manually like this, 
,,,
public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {

    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
     
    }

    @Override
    public void registerWith(PluginRegistry registry) {

        if(!registry.hasPlugin("com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin")) {
            BackgroundFetchPlugin.registerWith(registry.registrarFor("com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin"));
        }
        if(!registry.hasPlugin("com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin")) {
            FLTBackgroundGeolocationPlugin.registerWith(registry.registrarFor("com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin"));
        }
    }
}

//JAVA

public class MainActivity extends FlutterActivity {
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

//KOTLIN

class MainActivity: FlutterActivity() {
    fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine?) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
,,,

But again we getting the same exception.

**Comment by iloads** [comment]
@christocracy waiting for your suggestions

**Comment by christocracy** [comment]
I suggest you investigate if you have this problem with *all* plugins (Eg `shared_preferences`)
