### ISSUE TITLE
Location authorization alert 

### ISSUE THREAD

**Issue by vova-beloded** [transistorsoft/flutter_background_geolocation#8]
## Your Environment
* Plugin version: 0.6.1
* Platform: iOS or Android
* OS version: 11.4
* Device manufacturer / model: iPhone X emulator, iPhone 6s
* Flutter info (`flutter doctor`):

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.4 17E199, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

* Plugin config
```
//pluginInitializationCounter is global counter that increments when method initPlatfromState is called
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled' : 'Title text $pluginInitializationCounter',
          'titleWhenOff' : "Title when off $pluginInitializationCounter",
          'instructions' : "Instrunction text $pluginInitializationCounter",
          'cancelButton': "Cancel$pluginInitializationCounter",
          'settingsButton': "Settings$pluginInitializationCounter"
        },
        reset: true,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        foregroundService: true,
        stopTimeout: 1,
        debug: true,
        autoSync: true,
        url: 'http://tracker.transistorsoft.com/locations/$username',
        params: deviceParams,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    ))
```

## Expected Behavior

The authorization alert message should fully update every time plugin configuration updated

## Actual Behavior

titleWhenNotEnabled, titleWhenOff, instructions fields updated successfully, but cancelButton and settingsButton does not update until application restart

## Steps to Reproduce

Modify example app:

1. Add some changing value to locationAuthorizationAlert strings
2. Initialize plugin 
3. Make locationAuthorizationAlert values change
4. Reinitialize plugin 
5. Some values of this alert will not change

## Context

We are trying to localize our app using intl_helpers plugin but this bug makes impassable to translate this message, because some values not changing

![simulator screen shot - iphone x - 2018-10-12 at 16 48 34](https://user-images.githubusercontent.com/41615621/46877212-fbaa2880-ce48-11e8-8635-d79e91f7e7d1.png)
![simulator screen shot - iphone x - 2018-10-12 at 16 48 51](https://user-images.githubusercontent.com/41615621/46877211-fbaa2880-ce48-11e8-896d-f7c6b9344a81.png)

**Comment by christocracy** [comment]
Thanks, I see the problem:
```obj-c
+(UIAlertController*) getAlertController
{
    TSConfig *config = [TSConfig sharedInstance];
    NSDictionary *strings = [config getLocationAuthorizationAlertStrings];
    CLAuthorizationStatus status = [CLLocationManager authorizationStatus];
    NSString *title = (status == kCLAuthorizationStatusDenied) ? strings[@"titleWhenOff"] : strings[@"titleWhenNotEnabled"];
    
    if (!alertController) {
        alertController = [UIAlertController alertControllerWithTitle:title message:strings[@"instructions"] preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction* cancelAction = [UIAlertAction actionWithTitle:strings[@"cancelButton"] style:UIAlertActionStyleDefault handler:^(UIAlertAction* action) {
            [self hide];
        }];
        [alertController addAction:cancelAction];
        UIAlertAction* settingsAction = [UIAlertAction actionWithTitle:strings[@"settingsButton"] style:UIAlertActionStyleDefault handler:^(UIAlertAction* action) {
            NSURL *settingsURL = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
            [[UIApplication sharedApplication] openURL:settingsURL];
        }];
        [alertController addAction:settingsAction];
    } else {
        // alertController instance already exists here.  
        // TODO Need to fetch references to the buttons here and update their text.
        [alertController setTitle:title];
        [alertController setMessage:strings[@"instructions"]];
    }
    return alertController;
}
```

Carry on with your testing.  This will be fixed soon.

**Comment by vova-beloded** [comment]
@christocracy any way this can be fixed today/tomorrow? we need to make sure that languages are ok before pushing to the App Store and this issue is one of few remaining.

**Comment by illia-romanenko** [comment]
any updates on this?

**Comment by christocracy** [comment]
In the meantime, you can always disableAuthorizationAlert and implement your own alert in the `onProviderChange` event.

**Comment by vova-beloded** [comment]
I've tried this approach recently and it is not working correctly. onProviderChange event triggers only after changing settings, but not after plugin initialization and thus we cannot show alert directly after plugin initialization like default alert message.

**Comment by christocracy** [comment]
Listen to `onProviderChange` *before* `#ready`.

`#ready` causes a `providerchange` event to fire.  If you're not listening to the event *before* `#ready`, you'll miss the event.

**Comment by vova-beloded** [comment]
I've checked this one. And it doesn't work too. #ready does not make onProviderChange event to fire even if I add this listener before #ready method

**Comment by christocracy** [comment]
@vova-beloded Show me your code where you're executing `#ready` and `#onProviderChange`

**Comment by christocracy** [comment]
I see you viewing /locations/username in the browser.

It’s just /username

**Comment by christocracy** [comment]
`locationAuthorizationAlert` Should be fixed in `0.1.7`

**Comment by christocracy** [comment]
Confirmation please.

**Comment by christocracy** [comment]
@vova-beloded **Confirmation please**.

**Comment by illia-romanenko** [comment]
confirmed

**Comment by TheAlphamerc** [comment]
> In the meantime, you can always disableAuthorizationAlert and implement your own alert in the `onProviderChange` event.

I was looking for a property to disable built-in authorization alert and see I found it.
