### ISSUE TITLE
Upcoming new policies

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#800]
I got an email from Google today about upcoming new policies. Are we affected by this change concerning the Exact Alarm API?

`•	We’re introducing a new restricted permission requirement for Exact Alarm API, stating that apps must only declare this permission if their core functionality requires an exact alarm. Apps declaring the new restricted permission that do not meet these criteria will not be permitted on Google Play. `

**Comment by christocracy** [comment]
The plugin uses a number of exact alarms (Eg `stopTimeout`) and declares the newly required permission for EXACT_ALARM in its AndroidManifest.  

We will have to wait and see under what criteria Google will judge acceptance of this permission.

the plugin will fallback to inexact alarms if that permission is explicitly removed from one’s AndroidManifest.

**Comment by christocracy** [comment]
I just received this email myself.  After carefully reading the linked [*Exact Alarm Policy Update*](https://support.google.com/googleplay/android-developer/answer/12253906#exact_alarm_preview):

>A new permission, USE_EXACT_ALARM, will be introduced that will grant access to [exact alarm functionality](https://developer.android.com/about/versions/13/features#use-exact-alarm-permission) in apps starting with Android 13 (API target level 33).

>If you have a use case for exact alarm functionality that’s not covered above, you should evaluate if using SCHEDULE_EXACT_ALARM as an alternative is an option

<img width="803" alt="Screen Shot 2022-07-27 at 4 25 53 PM" src="https://user-images.githubusercontent.com/14999/181365718-a80b8e2e-86c7-4930-a89d-2f3fce51badf.png">

In fact, the plugin **does not** include the permission __`USE_EXACT_ALARM`__, it already uses `SCHEDULE_EXACT_ALARM`:

### *AndroidManifest.xml*

```xml
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
```

**Comment by ozzy1873** [comment]
Sounds like we should be ok then, thanks!
