### ISSUE TITLE
When app is in background (iOS only) does not register all positions and it "jumps"

### ISSUE THREAD

**Issue by ehajredini** [transistorsoft/flutter_background_geolocation#802]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS
* OS version: 15.5
* Device manufacturer / model: iPhone 13 pro max
* Flutter info (`flutter doctor`):
* Plugin config:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```dart <-- Syntax highlighting: DO NOT REMOVE -->
import 'package:irte_engine_core/irte_engine_core.dart';

/// Background Geolocation Config
class BgGeolocationConfig {
  /// Current config
  static Config? currentConfig;

  /// Desired accuracy
  static const desiredOdometerAccuracy = 70.0;

  /// Speed jump filter
  static final speedJumpfilter = 35.kmhToMps().toInt();

  /// Distance filter
  static const distanceFilter = 10.0;

  /// Default config
  static Config get defaultConfig => getConfig();

  /// Warmup config
  static Config get warmup => getConfig(isWarmup: false);

  /// Returns a config.
  ///
  /// Modifies the config with [extras] provided based on if it [isWarmup]
  /// and if it should produce [debug] logs
  static Config getConfig({
    bool isWarmup = false,
    bool debug = false,
    Json? extras,
  }) {
    extras ??= {};
    if (isWarmup) {
      extras['warmup'] = true;
    }

    return Config(
      /// Disable this otherwise will continuously call "pause" and
      /// "resume" events on Android
      ///
      /// See link below for a related issue
      /// https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1073
      disableLocationAuthorizationAlert: Platform.isAndroid,

      // we need the highest possible accuracy
      desiredAccuracy: Config.DESIRED_ACCURACY_NAVIGATION,

      // make odometer only use locations with accuracy above desired for its calculations / updates
      desiredOdometerAccuracy: desiredOdometerAccuracy,

      // Ignore locations that have moved greater than or equal to this speed
      // from the previous location (in m/s).
      speedJumpFilter: speedJumpfilter,

      /// deliver a location each ...
      /// from remote config it is 10 (meters) for both ios and android
      distanceFilter: distanceFilter,

      /// Disable the stop detection completely - we handle the stop / start state by our self.
      disableStopDetection: true,

      /// As long as the Background Geolocation is started we don't need any automatic stops
      pausesLocationUpdatesAutomatically: false,

      /// Debug when debugging is enabled
      /// (Way more logs and some sounds)
      debug: debug,

      /// Loglevel
      logLevel: debug ? Config.LOG_LEVEL_VERBOSE : Config.LOG_LEVEL_ERROR,

      /// Our desired GPS authorisation
      locationAuthorizationRequest: 'Always',

      backgroundPermissionRationale: PermissionRationale(
        title: 'Allow {applicationName} to access this device\'s location '
            'even when the app is closed.',
        message:
            'In order to track your activity in the background while in a run '
            'and the app is closed, please enable "Allow all the time" '
            'location permission.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      ),

      /// Activity settings
      stopTimeout: 1,
      activityType: Config.ACTIVITY_TYPE_FITNESS,
      preventSuspend: false,
      heartbeatInterval: 10,

      stationaryRadius: 5,
      disableElasticity: true,

      activityRecognitionInterval: 5000,
      minimumActivityRecognitionConfidence: 75,

      /// Don't go into background
      stopOnTerminate: isWarmup ? true : false,
      startOnBoot: false,
      foregroundService: false,

      // Persistence
      persistMode:
          isWarmup ? Config.PERSIST_MODE_NONE : Config.PERSIST_MODE_ALL,
      maxDaysToPersist: isWarmup ? 0 : 5,
      maxRecordsToPersist: isWarmup ? 0 : -1,

      // Mark locations as extras
      extras: extras,
    );
  }

  /// Returns the [defaultConfig] with the provided [extras]
  static Config withExtras(Json extras) {
    final config = getConfig();
    config.extras = extras;
    return config;
  }
}

```

## Expected Behavior
It should fire/register all gps positions and do not stop.

## Actual Behavior
During the ride, when app is in background we do not take all positions. This happens only on iOS. Android works properly. 

## Steps to Reproduce
1. Start a ride
2. Put app in background

## Context
We are having this issue when we get the default config before starting the ride. So, on the above config `isWarmup` is set to `false`. 

We have tried to change some properties (list below), but getting the same results:

```
reset: true
stopOnTerminate: false
preventSuspend: true
```

**Comment by christocracy** [comment]
I test every day for years.  I do not have this problem of “stopping”.

see wiki *Debugging* and learn to fetch logs from the plugin using `.emailLog` method.

**Comment by christocracy** [comment]
> reset: true

this is the default value.  Just delete that from your Config.

>preventSuspend: true

this is only for **very specialized** use cases and has nothing at all to do with your issue.  This option is not required by 99% of use-cases.  Delete that from your Config.

**Comment by ehajredini** [comment]
Thanks for quick answer. Below values are not on the config. I added as an example what we tried on attempt to make it work.

P.S. we are building a cycling app. do you see something wrong with config above?

**Comment by christocracy** [comment]
The answer is in the plugin logs.

when something unexpected occurs, the first thing to do is enable debug: true and configure for verbose logging.  Then fetch your logs.

**Comment by LocaTrackGitHub** [comment]
We are finding the same with 4 min and 2 second gaps in the location logs whilst driving on iPhone 13  on software versions 15.6. Not sure if it could be battery related but the battery was 70-80% and it seems to be very intermittend some days it does it and other days it does not. I can confirm that the gaps does not hit our server so its not like its getting to us and not entering the data correct. 
here is the route plotted...
<img width="543" alt="image" src="https://user-images.githubusercontent.com/90172721/184382736-858f077b-c2d8-4c0b-8f35-bc463f1e9ecf.png">
here is the server logs...
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/90172721/184383135-bc37abc2-3515-43e7-9a7e-a622312b966f.png">

**Comment by christocracy** [comment]
@LocaTrackGitHub 

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

**Comment by LocaTrackGitHub** [comment]
@christocracy 
Your Environment

Plugin version:4.7.0
Platform: iOS
OS version:15.6
Device manufacturer / model: iPhone 13 pro max
Flutter info (flutter doctor):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.5 21G72 darwin-x64, locale af-ZA)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
Plugin config:
bg.BackgroundGeolocation.ready(bg.Config(
desiredAccuracy: logAccuracyLevel,
allowIdenticalLocations: false,
distanceFilter: 10.0,
stopOnTerminate: false,
enableHeadless: true,
startOnBoot: true,
stationaryRadius: 50,
speedJumpFilter: 100,
maxDaysToPersist: 30,
debug: false,
reset: true,
disableLocationAuthorizationAlert: true,
autoSync: true,
foregroundService: true,
url: constants.baseServiceUrlH +
'/locatrack/user/location/transistorsoft/insert/',
params: {
"myParams": {"deviceId": deviceId, "user":sequence}
},
logLevel: bg.Config.LOG_LEVEL_ERROR,
locationAuthorizationRequest: 'Always',
backgroundPermissionRationale: bg.PermissionRationale(
title: "Allow LocaTrack to access to this device's location in the background?",
message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
positiveAction: "Change to always allow.",
negativeAction: "Cancel"
),
)).then((bg.State state) {
if (!state.enabled) {
////
// 3. Start the plugin.
//
bg.BackgroundGeolocation.start();
print('Started bg.BackgroundGeolocation');
}
});

**Comment by christocracy** [comment]
Now set debug: true, go out for a field-test and use .emailLog method to fetch your logs.  

See wiki Debugging.

**Comment by LocaTrackGitHub** [comment]
[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/9350626/background-geolocation.log)

**Comment by christocracy** [comment]
When you see this in the logs, it means your app has been re-launched.

```
2022-08-16 12:02:01.153 ℹ️-[TSLocationManager init] 
╔═════════════════════════════════════════════
║ TSLocationManager (build 385)
╠══════════════════════════════════════════════
{
  ...
}
```

Between `11:53:17` and `12:02:01`, your app was either *terminated* or it *crashed*.

**Comment by LocaTrackGitHub** [comment]
What is that maxage 86400 is it not the culprit as we do not experience app crashes as such?

Here is another log for today I dont see the TSLocationManager init by them although the log is full of them 

Today it logged worse than ever?

<img width="540" alt="image" src="https://user-images.githubusercontent.com/90172721/185227158-9f922dc5-4dd7-4b42-9779-7098f4f0667b.png">

Here is the log:

[background-geolocation.log](https://github.com/transistorsoft/flutter_background_geolocation/files/9365598/background-geolocation.log)

<img width="637" alt="image" src="https://user-images.githubusercontent.com/90172721/185225898-fd64d6a6-d0cd-4747-9204-6b03141ba93c.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/90172721/185226504-c36ad091-1ab0-4ef5-9b55-b672acfcfb26.png">
<img width="918" alt="image" src="https://user-images.githubusercontent.com/90172721/185226785-20a76c56-fe2d-4e32-8c2f-ae615100525f.png">

**Comment by christocracy** [comment]
I suggest you install the /example app in this repo in order to test using the same app that I use.

**Comment by LocaTrackGitHub** [comment]
Hi we did and you were right the app fails silently and then carries on we do seem to see gaps every so often like the one in green below...
<img width="704" alt="image" src="https://user-images.githubusercontent.com/90172721/185919938-b2a44d9f-95c6-4bbf-bb1b-7f54bcd455d0.png">

We have installed sentry but not getting the exact error we expected what else can you suggest to find memory or silent crash errors. I suspect the app uses too much memory and then iOS kills it and then it restarts but not sure...?

Also the lines you colour green in the image above how can I not have them on the map as they are incorrect values and I am also not sure what causes them?

**Comment by LocaTrackGitHub** [comment]
We have  stationaryRadius: 25 and what I thought may also help  speedJumpFilter: 100
Nobody went to that position is what I am saying its a wrong GPS position captured looks like its the 200m radius on iOS and then it got a wrong point and then corrected itself at 9.

Any good software you can recommed to find the other errors which looks like memory or app restart?

**Comment by christocracy** [comment]
There can be poor locations initially when the plugin changes state while the gps “warms up” and connects to satellites.  The plugin attempts to alleviate this during state changes by capturing several “samples” before settling but it’s not always perfect.

It’s up to you to filter your data as desired (possibly using location.coords.accuracy)

**Comment by LocaTrackGitHub** [comment]
Well everytime you make a line green its seems to be the case was hoping there is another way but thanks will look into that then. So on the app crashing dont you know any software we can try to find the issue other than sentry which does not pick up the problem?

**Comment by LocaTrackGitHub** [comment]
Todays log seems different we are getting gaps but no restarts and it still seem to  just be happening on high end iOS devices e.g. iPhone 13 and up. This particular test was done without data on so the inserts was suppose to fail.

[background-geolocation.zip](https://github.com/transistorsoft/flutter_background_geolocation/files/9442570/background-geolocation.zip)

Plugin version:4.7.0
Platform: iOS
OS version:15.6
Device manufacturer / model: iPhone 13 pro max
Flutter info (flutter doctor):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.5 21G72 darwin-x64, locale af-ZA)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!

Here is the route with the gaps:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/90172721/187151576-814a9852-48f0-403c-b586-48083c542665.png">

Here is the log pont where there is a gap from 07:54:18 to 07:58:21.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/90172721/187153176-6fd0e953-3416-4163-8d1f-e66a9ef8493b.png">


Here is the log pont where there is a gap from 08:04:18 to 08:08:22
<img width="752" alt="image" src="https://user-images.githubusercontent.com/90172721/187152776-70df892a-1d53-419b-8e37-84aa51db749d.png">

Here is the log pont where there is a gap from 08:09:19 to 08:13:22
<img width="852" alt="image" src="https://user-images.githubusercontent.com/90172721/187152492-633913f3-fd6f-4c84-8b74-fd4646e4bff8.png">

Here is the log point where there is a gap from 08:14:20 to 08:18:23  

![image](https://user-images.githubusercontent.com/90172721/187151813-c9292c69-ed6a-458d-af4b-82429d479c81.png)

**Comment by christocracy** [comment]
I took a long road-trip last week.  I do not experience any issue with the `/example` app.

<img width="1696" alt="Screen Shot 2022-08-29 at 8 28 13 AM" src="https://user-images.githubusercontent.com/14999/187201193-c51b30cd-ec8a-47f1-a5cf-ad871560d314.png">

**Comment by christocracy** [comment]
I suggest you simplify your config.  Disable the following:
>speedJumpFilter: speedJumpfilter,
>persistMode: isWarmup ? Config.PERSIST_MODE_NONE : Config.PERSIST_MODE_ALL,
>maxDaysToPersist: isWarmup ? 0 : 5,
>maxRecordsToPersist: isWarmup ? 0 : -1,

>stopTimeout: 1,

You should *never* use `stopTimeout: 1` in production.  Use a minimum of `5` minutes.

**Comment by LocaTrackGitHub** [comment]
Thats the other guys config on this thread...here is ours again we made stopTimeout less as it missed some short stops...do you see anyting wrong here? It definately works on Android and up to iOS 11....

bg.BackgroundGeolocation.ready(bg.Config(
          desiredAccuracy: logAccuracyLevel,
          allowIdenticalLocations: false,
          distanceFilter: 10.0,
          elasticityMultiplier: 1,
          disableElasticity: false,
          stopOnTerminate: false,
          heartbeatInterval: 60,
          enableHeadless: true,
          startOnBoot: true,
          stationaryRadius: 25,
          activityType: bg.Config.ACTIVITY_TYPE_OTHER,
          speedJumpFilter: 100,
          stopTimeout: 3,
          stopAfterElapsedMinutes: -1,
          desiredOdometerAccuracy: 100,
          maxDaysToPersist: 30,
          persistMode: bg.Config.PERSIST_MODE_ALL,
          debug: true,
          reset: true,
          disableLocationAuthorizationAlert: true,
          autoSync: true,
          foregroundService: true,
          url: constants.baseServiceUrlH +
              '/locatrack/user/location/transistorsoft/insert/',
          params: {
            "myParams": {"deviceId": deviceId, "user": sequence}
          },
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          //logMaxDays: 1,
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: bg.PermissionRationale(
              title: "Allow LocaTrack to access to this device's location in the background?",
              message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
              positiveAction: "Change to always allow.",
              negativeAction: "Cancel"
          ),
        )).then((bg.State state) {
          if (!state.enabled) {
            ////
            // 3.  Start the plugin.
            //
            bg.BackgroundGeolocation.start();
            print('Started bg.BackgroundGeolocation');
          }
        });

**Comment by christocracy** [comment]
iOS device doesn’t matter much.  iOS had bugs with earlier versions of iOS 15 that they later fixed (around spring time).

**Comment by LocaTrackGitHub** [comment]
Ok will do that for iOS, but it sometimes looks bad also even in android like this green line......
![image](https://user-images.githubusercontent.com/90172721/187222977-edaa7a13-30f0-4c5c-87dd-a208524e6ecf.png)

**Comment by christocracy** [comment]
And as always for *Android* devices, see https://dontkillmyapp.com

**Comment by guns28** [comment]
I have the same issues with iOS it sometimes jumps : 
here is my configuration : 

bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 1.0,
        autoSync: true,
        stopOnTerminate: true,
        startOnBoot: false,
        enableHeadless: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });

Flutter doctor : 

✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.1 20G224 darwin-x64, locale fr)
    • Flutter version 3.0.5 at /Users/macbook/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/11460453/189848288-898413c9-7cbd-4f96-aec2-a1a9aeee4dfd.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/11460453/189848315-d32d725e-4e3c-4526-94cc-5815989828cd.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/11460453/189848339-6818e15a-6a22-43e6-bffc-b98667ef606f.png)

Any idea ? thx
