### ISSUE TITLE
Is device location required?

### ISSUE THREAD

**Issue by rxPrachi** [transistorsoft/flutter_background_geolocation#807]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS or Android
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Is there any way to manage the geofencing stuff using the device OS's activity tracker service?

## Actual Behavior
Currently, this SDK is asking for location permission and no fixed time to trigger even after applied [loiteringDelay](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Geofence/loiteringDelay.html) of 60 seconds but still no work as expected

## Context
Notify the user if he/she is in the geofence for more than a minute, it would be appreciated if guide me if I can achieve it with an os tracker without location permission as well as with permission to get notified in the above situation!

Thank you!  😊

**Comment by christocracy** [comment]
Yes, device location is required.  As documented in the [Android Developer Docs](https://developer.android.com/training/location/geofencing)

![4AF35062-DAF1-486B-B4BF-EDC19C15A4EE](https://user-images.githubusercontent.com/14999/182850331-f5be8933-2c98-4954-9c7a-c1f75f459f1b.jpeg)
