### ISSUE TITLE
Application stops working in background due to battery optimization

### ISSUE THREAD

**Issue by chirag-chopra** [transistorsoft/flutter_background_geolocation#809]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS or Android
* OS version: ANDROID 12
* Device manufacturer / model: Moto g22
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
* Plugin config:

## Expected Behavior
App should work in background without any issue.

## Actual Behavior
There are 3 things in battery optimization:
- Restricted
- Optimization      ( This is by default. )
- Unrestricted [  Here application is working smoothly without any issue  ]

I manually changed it from Optimization to Unrestricted. Then app works in background. But it should also work on optimization too. Normal users or customers are not aware of these things. They just want things to work.

## Context
I am trying to store location updates of users in background.

**Comment by christocracy** [comment]
The plugin doesn’t do anything different under battery optimization.  If there is a change in behaviour, it’s due to the OS.

the plugin does report when battery optimization is engaged via event `onPowerSaveChange`.

**Comment by chirag-chopra** [comment]
When we switched from Optimization to Unrestricted then app started sending location in every min. We have tested this for 5 hours then we again switched back to Optimization mode and again it stopped and vice versa we tested it many times.
Please look into this matter.

**Comment by christocracy** [comment]
Every single Android manufacturer has the capability to do implement their own custom behaviour for battery optimization.

the plugin does not do anything when battery optimization kicks in, other than fire an event that says when it did.

there is nothing to investigate.

I suggest you test upon a variety of devices.  You will witness a variety of different behaviours.

also see https://dontkillmyapp.com

**Comment by christocracy** [comment]
There are obviously consequences to *Battery Optimization*.  One of those consequences is turning off power hungry radios involved in location-services (GPS, Wifi).

How else would you expect a device to conserve energy when the battery is low?
