### ISSUE TITLE
Getting direction using the magnetometer

### ISSUE THREAD

**Issue by noorbakerally** [transistorsoft/flutter_background_geolocation#810]
Is it possible to get the direction or angle from the device magnetometer using this plugin?

I am trying to use the motion change, but if I understand this will not work given that the device can remain stationery but change direction. 

Also, when the motion change event is triggered, I get the following:

[MotionChange] - [Location {odometer: 31008.30078125, activity: {confidence: 100, type: still}, extras: {}, event: motionchange, battery: {level: 0.33, is_charging: true}, uuid: 53e3f7e3-5353-493d-93a7-5b47f4d51073, coords: {altitude: 418.0, heading: -1.0, latitude: -20.3058235, accuracy: 20.0, heading_accuracy: -1.0, altitude_accuracy: 1.1, speed_accuracy: -1.0, speed: -1.0, longitude: 57.4826696}, is_moving: false, timestamp: 2022-08-11T09:15:57.998Z}]

Even if I change the direction of the device, the `heading` value remains the same. To confirm, my device is well equipped with a magnetometer.

**Comment by christocracy** [comment]
`heading` comes from the gps chip on the device.  GPS only works outdoors.

magnetometer tells you nothing about which direction the device is *moving* — it tells you only which direction the device is *pointing*.

if I am driving north in a car, and my device happens to be pointed north, the compass coincidentally match my heading.

however, if I rotate my device 90 degrees clockwise, now my compass says *east* while my heading remains *north*.

**Comment by noorbakerally** [comment]
to rephrase my question, is it possible to get the magnetometer readings, that is the direction the device is pointing using this plugin?

**Comment by christocracy** [comment]
Use a 3rd party plugin specializing in that.

this plugin does not interact with the magnetometer.

**Comment by noorbakerally** [comment]
Ok thanks, that answer the question.
