### ISSUE TITLE
Running app - Need location updates every few seconds regardless of moving or stop

### ISSUE THREAD

**Issue by xweng1016** [transistorsoft/flutter_background_geolocation#811]
## Your Environment
* Plugin version: Lastest
* Platform: iOS or Android
* OS version: Lastest
* Device manufacturer / model: All
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  newGeoloactionTracking() async {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      // print('[location] - $location');
      // print('onLocation - ${location.toString(compact: true)}');
      longitude = (location.coords.longitude);
      latitude = (location.coords.latitude);
      state.odometer = location.odometer;
      state.speedometer = location.coords.speed * 3.6;
      meterPersecond = location.coords.speed;
      update();
    });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      // print('[motionchange] - $location');
      // print('onMotionChange - ${location.toString(compact: true)}');
      longitude = (location.coords.longitude);
      latitude = (location.coords.latitude);
      state.odometer = location.odometer;
      state.speedometer = location.coords.speed * 3.6;
      meterPersecond = location.coords.speed;
      update();
    });
    ////
    // 2.  Configure the plugin
    //
    await bg.BackgroundGeolocation.ready(bg.Config(
        disableElasticity: true,
        activityType: bg.Config.ACTIVITY_TYPE_FITNESS,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 3,
        stopOnTerminate: true,
        startOnBoot: false,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_INFO));
  }

  trackingStart() async {
    await bg.BackgroundGeolocation.start();
    await bg.BackgroundGeolocation.changePace(true);
  }

  trackingStop() async {
    bg.BackgroundGeolocation.changePace(false);
    bg.BackgroundGeolocation.setOdometer(0);
    bg.BackgroundGeolocation.stop();
  }
```

## Expected Behavior

Steady updates with GPS location, speed, and distance every 3 seconds regardless of the current movement.

## Context

Im trying to make a running app. Get constant updates of user location every 3 seconds (or max at 5) seconds interval while in both foreground and background.
i had to use BackgroundGeolocation.changePace(true) to start receiving location updates, and BackgroundGeolocation.onLocation for event callbacks. but since onLocation only fires when user is moving, for example:
there is a speedometer on the screen showing the speed provided by this onLocation.
if user running at 10m/s, app will receive updated event from onLocation with the speed 10m/s displayed on the screen.
but if the user stopped at a traffic light, onLocation will not fire an event with 0m/s speed since the user isn't moving to trigger onLocation, so the screen will still show 10m/s when the user isn't moving at all. also I think due to the use of .changePace(true), onMotionChange never triggers when the user stop moving, tho without .changePace(true) the running session won't even start rightaway.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Steady updates with GPS location, speed, and distance every 3 seconds regardless of the current movement.

The [*Philosophy of Operation*](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation) of this plugin is to track location only when the device is detected to be moving and to conserve energy while the device is detected to be stationary. 

The plugin does not record location when the device is stationary.

To receive periodic locations while the device is stationary, use [`background_fetch`](https://github.com/transistorsoft/flutter_background_fetch), already included as a dependency.

- If you wish to place the plugin into the *moving* state, you can do so via `.changePace(true)`.
- If you wish to prevent the plugin automatically returning to the *stationary* state, you can use `Config.disableStopDetection` and `Config.pausesLocationUpdatesAutomatically`
- iOS location-services API is strictly *distance-based*.

**Comment by xweng1016** [comment]
> 
> The [_Philosophy of Operation_](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation) of this plugin is to track location only when the device is detected to be moving and to conserve energy while the device is detected to be stationary.


Could you approximate does it consume more energy if I use .getCurrentLocation() to call once every 5 seconds, compare to onLocation which fires every second if I set it that way?

**Comment by christocracy** [comment]
Mobile location-services are a combination of radios, including GPS, Wifi and Cellular.

every time location-services are turned on, battery is consumed, regardless if from .getCurrentPosition, .changePace(true) or the plugin automatically turning location-services from it *Philosophy of Operation*.

**Comment by xweng1016** [comment]
Containing class: BackgroundGeolocation  Type: Future<Location> Function({int? desiredAccuracy, Map<String, dynamic>? extras, int? maximumAge, bool? persist, int? samples, int? timeout})  
Retrieves the current Location.
**This method instructs the native code to fetch exactly one location using maximum power & accuracy.** 

I know they will consume energy, but I'm just thinking which one is more power efficient comparing .getCurrentLocation()  called once every 5 seconds vs .onLocation() fires every second, if its possible to tell

**Comment by christocracy** [comment]
It will be worse, turning off the radios and forcing them all to reconnect to gps satellites.

Don’t even think about trying to save energy by using your own timers to call .getCurrentPosition.  You will run into all sorts of other issues, particularly on iOS which automatically suspends your app (and freezes any timers) the moment location-services are turned off with your app in the background.

you might as well not even use this plugin if you’re just going to run a timer to call .getCurrentPosition().
