### ISSUE TITLE
Geofences are not getting triggered

### ISSUE THREAD

**Issue by gembancud** [transistorsoft/flutter_background_geolocation#812]
## Your Environment
* Plugin version: 4.7.0
* Platform:  Android
* OS version: 12
* Device manufacturer / model: Xiaomi mi10T pro
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.60.2)
[√] VS Code (version 1.71.0-insider)
[√] Connected device (3 available)
[√] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10.0,
    stopOnTerminate: false,
    startOnBoot: true,
    debug: true,
    enableHeadless: true,
    geofenceModeHighAccuracy: true,
    geofenceInitialTriggerEntry: true,
    foregroundService: true,
    logLevel: bg.Config.LOG_LEVEL_VERBOSE,
  )).then((bg.State state) {
    if (!state.enabled) {
      bg.BackgroundGeolocation.startGeofences();
    }
  });
}
```

## Expected Behavior
Get geofence event triggers
## Actual Behavior
Geofence triggers not being called upon 

## Steps to Reproduce
1. Create geofences
2. Start the trip

## Context
Trying both geofence+tracking, and geofence only.
Trying both my app and the demo app. 
Trying on in-app, foreground, and background states
There are only 2 cases of it triggered, both of which were added during the trip.
Even when I enter an expected geofence and ping my current location manually, geofence events are still not fired.
Location sampling works fine and provides a "heartbeat" of how fast I move.
I have a 99% feeling it could be the device, so Im just ironing out possible overlooks
What am I missing?

Site logs: [here](https://tracker.transistorsoft.com/memrytest)
Demo app screenshots
<img src="https://user-images.githubusercontent.com/29444872/184870219-25d3affb-09d7-45c2-9c08-804febb81bc9.jpg" width="300" height="600" />   <img src="https://user-images.githubusercontent.com/29444872/184872111-8910a556-24cb-4fb4-8a2d-ee8ccef173a6.jpg" width="300" height="600" />

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.2.0 (406)
╠═════════════════════════════════════════════
╟─ Xiaomi M2007J3SG @ 12 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {
    "strategy": "jwt",
    "accessToken": "eyJhb<redacted>",
    "refreshToken": "46a79<redacted>",
    "refreshUrl": "https:\/\/[tracker.transistorsoft.com](http://tracker.transistorsoft.com/)\/api\/refresh_token",
    "refreshPayload": {
      "refresh_token": "{refreshToken}"
    },
    "expires": -1
  },
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
    "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": ""
  },
  "batchSync": false,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 0,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": false,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/[tracker.transistorsoft.com](http://tracker.transistorsoft.com/)\/api\/locations",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 0,
  "odometer": 0,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="lsm6dso Accelerometer Non-wakeup", vendor="STMicro", version=142854, type=1, maxRange=78.4532, resolution=0.0023928226, power=0.17, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="lsm6dso Gyroscope Non-wakeup", vendor="STMicro", version=142854, type=4, maxRange=17.452517, resolution=6.1084726E-4, power=0.55, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="ak0991x Magnetometer Non-wakeup", vendor="akm", version=146965, type=2, maxRange=4912.0503, resolution=0.15, power=1.1, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="qualcomm", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
╚═════════════════════════════════════════════
```

</details>

**Comment by christocracy** [comment]
Did you authorize *always* authorization in the permission dialog.  Geofences don’t work with “*When in use*”

you haven’t provided any logs during the time you moved through the geofence.

Also see https://dontkillmyapp.com.

**Comment by christocracy** [comment]
I regularly field test on 11 different Android devices.  Geofences don’t fail for me.

**Comment by gembancud** [comment]
Did a run today, first on geofences only, then tracking+geofences going back. None of the geofences I set up beforehand were fired. You can also check it in the site tracker at OP. I'm slogging through the logs rn, but its cryptic for me. maybe you'll have a clue on the issues I'm having.
<img src="https://user-images.githubusercontent.com/29444872/185058761-203aa0a8-32f0-4977-ae9d-74cadeb705a8.jpg" width="300" />

Actual logs start @ 8-17
[background-geolocation.log_6.gz](https://github.com/transistorsoft/flutter_background_geolocation/files/9357313/background-geolocation.log_6.gz)

**Comment by christocracy** [comment]
I suggest you configure the plugin to upload data to the demo server at `http://tracker.transistorsoft.com` so that I can see the uploaded data.  See API docs [`Config.transistorAuthorizationToken`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/TransistorAuthorizationToken-class.html).  Then let me know the "`orgname`" name you choose so that I can view the results on the demo server.

Also, I suggest you reboot your device and see https://dontkillmyapp.com.

And test upon a variety of different devices.

**Comment by gembancud** [comment]
Did one long run back and forth after restart. The only geofence I triggered was my final destination, and I believe the only reason I was able to trigger it was because I had to circle around, looking for a parking spot, and then walk to my destination. Even more, leaving the geofence wasn't at all triggered. All other geofences, even stoplight intersections, don't get triggered,i believe I was just moving. What options can I tweak to increase sensitivity? 

At this point, I may default to geofence radius >2km, then do an adaptive switch to tracking manual measure distances for checkpoints, similar to the example in the documentation. What do you think?
<img src="https://user-images.githubusercontent.com/29444872/185561218-2b8e4ab8-e750-4596-b471-f74fbf10a574.jpg" width=300 />

**Comment by gembancud** [comment]
Did a 50 km test with geofence radius set to all different sizes. Geofences dont work when moving in vehicles even 5 km radius ones. App was 99% foreground the whole time.
I see document tests for cycling and walking, but none for vehicles. I am quite confident that the plugin doesnt work in this particular use case.

**Comment by christocracy** [comment]
The OS is responsible for firing geofences.  The plugin merely registers those geofences with the OS.  The plugin merely registers event-listeners.
