### ISSUE TITLE
provider state is not always included in location request

### ISSUE THREAD

**Issue by gadishimwe** [transistorsoft/flutter_background_geolocation#815]
## Your Environment
* Plugin version: 4.7.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung SM-G965F
* Flutter info (`flutter doctor`): 
``` 
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.4 21F79 darwin-x64, locale en-RW)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (1 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        maxDaysToPersist: 1,
        maxRecordsToPersist: 3,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        heartbeatInterval: 60,
        httpRootProperty: '.',
        url: server_url,
        locationTemplate: '{"latitude":"<%= latitude %>","longitude":"<%= longitude %>","batteryLevel":"<%= battery.level %>","isMockLocation":"<%= mock %>"}',
        // WHAT I'M TRYING TO ACHIEVE ----------------------------------------------------
        // locationTemplate:  '{"latitude":"<%= latitude %>","longitude":"<%= longitude %>","batteryLevel":"<%= battery.level %>","locationAccessStatus":"<%= provider.status %>","isLocationServiceEnabled":"<%= provider.enabled %>","isGpsEnabled":"<%= provider.gps %>","isMockLocation":"<%= mock %>"}',
      )
```

## Expected Behavior

I should be able to access this object on every location request along with other data sent to the server
```
 provider: {
    network: true,
    gps: true,
    enabled: true,
    status: 3,
    accuracyAuthorization: 0,
    airplane: false
  }
```

## Actual Behavior

I've seen that sometimes this is included in the request but occasionally. For example, look at those requests I logged at a time
![Screen Shot 2022-08-18 at 19 25 02](https://user-images.githubusercontent.com/52411901/185457400-bd60a9e9-46a7-4cfc-9fe6-48b328a31a55.png)

## Context

I tried to include those values into the `locationTemplate` but the HTTP requests stopped being sent. I was wondering if there is a way to achieve this. Thanks

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
That is from the onProviderChange event.

if you add the “event” property to your location template, you will find `event: “providerchange”`.

the Android plugin records a location whenever the onProviderChange event fires.

**Comment by gadishimwe** [comment]
Thanks for your fast response @christocracy. So it's not possible to have those data on `onLocation` events? Or the better question would be, how can I get those provider data on every location request from onLocation event?

**Comment by christocracy** [comment]
>how can I get those provider data on every location request from onLocation event?

You can't.

Whenever the user changes the location provider on device (eg: Disable Wifi, Disable location-services), the Android plugin records a location to say to you "*Here is where the device was located when the location provider changed" and fires the `onProviderChange` event.

**Comment by christocracy** [comment]
What would be the point in attaching the same `provider` data to each and every recorded location when it hasn't changed from the previous location?

**Comment by christocracy** [comment]
You are, of course, free to attach any arbitrary `extras` to each recorded location (or `params` to each HTTP request).  If you want use `.setConfig` method to apply `provider` to `extras` or `params`, you're free to do that.

**Comment by christocracy** [comment]
But if it were me, I would simply add the `"event": "<%= event %>"` to the `locationTemplate`.

On my server, when I see `data.event == "providerchange"` and see undesirable data there (eg:  GPS disabled), I would react only at that time (eg: send a push request to that device warning them to turn on GPS).

There's no point sending the **same data** over and over again when the plugin is perfectly capable of only reacting when a change in provider data occurs.

**Comment by christocracy** [comment]
>So, I'll call .setConfig every time location changes in onLocation

**NO!**

you would listen to `onProviderChange` and use `.setConfig` there.  See the API docs `onProviderChange`

**Comment by gadishimwe** [comment]
> > So, I'll call .setConfig every time location changes in onLocation
> 
> **NO!**
> 
> you would listen to `onProviderChange` and use `.setConfig` there. See the API docs `onProviderChange`

Oh, I see. Thanks for the explanation

**Comment by gadishimwe** [comment]
> You don't even _need_ to react to this on your server. You could use `onProviderChange` event and know _in real-time_ when the user has, for example, disabled GPS and immediately fire a _local notification_ in the `onProviderChange` event.

Yeah but there are some cases you might need to remotely monitor it

**Comment by christocracy** [comment]
That’s fine, but you still don’t need that provider data attached to *each* upload, needlessly consuming extra bandwidth.

your server merely needs to use simple logic to check for the presence of `event == “location”` and respond accordingly, only when the data is present.

**Comment by gadishimwe** [comment]
Yeah, sure thing

**Comment by gadishimwe** [comment]
> > > So, I'll call .setConfig every time location changes in onLocation
> > 
> > 
> > **NO!**
> > you would listen to `onProviderChange` and use `.setConfig` there. See the API docs `onProviderChange`
> 
> Oh, I see. Thanks for the explanation

I tried this but it's one event behind. For example, if I disable location, `gps` and `enabled` will still be `true` in the recorded event(Http). I'll get updated data in the next recorded event when it becomes available.
