### ISSUE TITLE
The always access to location request pop-up should not rises

### ISSUE THREAD

**Issue by MuhammadEhsanMirzaei** [transistorsoft/flutter_background_geolocation#819]
* Plugin version: 4.7.1
* Platform: Android
* OS version: Android 11 RKQ1.210503.001 11 (MIUI 12.5.14)
* Device Xiaomi 11 Lite 5G NE:
* Flutter info (`flutter doctor`):
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!`
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        pausesLocationUpdatesAutomatically: false,
        reset: true,
        locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Enable location',
          'titleWhenOff': 'Enable location service',
          'instructions':
              'Your location is needed to communicate the progress'
                  ' Please allow this app to access your location information.',
          'cancelButton': 'Done',
          'settingsButton': 'Settings'
        },
        locationAuthorizationRequest: 'WhenInUse',
        stopOnStationary: false,
        disableMotionActivityUpdates: true,
        stopTimeout: 0,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 100,
        persistMode: 0,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
The first dialog for background location authorization should appear, and the always one should not.

## Actual Behavior
But when users let to use their location while using the app, the pop-up for always access rises on the app immediately after accept while using the app by the user.

## Steps to Reproduce
1. Open the app
2. Location permission request appears
3. User select while using the app
4. Access or not access while using the app appears
5. User select access
6. Always access pop-up appears

## Context
Just show location requests while using the app

**Comment by christocracy** [comment]
You are likely calling .getCurrentPosition before .ready resolves.

the plugin doesn’t consume your Config until .ready has resolved.

If you execute .getCurrentPosition(), for example, before you’ve provided your desired Config, the plugin has no option but to use its default Config (which requests Always authorization)

**Comment by christocracy** [comment]
```dart
// NO:  Do not request location before calling .ready
location = await BackgroundGeolocation.getCurrentPosition();
await BackgroundGeolocation.ready(config);

// YES:  Wait until after your Config is provided.
await BackgroundGeolocation.ready(config);
location = await BackgroundGeolocation.getCurrentPosition();
```

**Comment by MuhammadEhsanMirzaei** [comment]
No, I don't have this `.getCurrentPosition ` in my code, but I have this
`await BackgroundGeolocation.requestPermission();`
And I try to pass it after ready but .ready doesn't resolve until the user gives permission.

**Comment by christocracy** [comment]
Same problem.  `.getCurrentPosition()` was just an example.

If you execute *any* code *before* the plugin has received its `Config`, it has no option but to use its existing *default Config*, which has `locationAuthorizationRequest: 'Always'`.

The plugin is not *aware of* your desired `Config` until `.ready(config)` has received it.

```dart
// NO:  Do not request permission before calling .ready
await BackgroundGeolocation.requestPermission();
await BackgroundGeolocation.ready(config);

// YES:  Wait until after your Config is provided.
await BackgroundGeolocation.ready(config);
location = await BackgroundGeolocation.requestPermission();
```
