### ISSUE TITLE
Extras object sometimes briefly empty after config update on iOS

### ISSUE THREAD

**Issue by frankvollebregt** [transistorsoft/flutter_background_geolocation#821]
## Your Environment
* Plugin version: 4.7.1
* Platform: iOS
* OS version: 15.5
* Device manufacturer / model: Apple iPhone XR
* Flutter info (`flutter doctor`):
<details><summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale nl-NL)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cocoapods.org'
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'maven.google.com'
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'pub.dev'
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cloud.google.com'

! Doctor found issues in 3 categories.
```
</details>

* Plugin config:
From:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 6.0,
    stopOnTerminate: false,
    startOnBoot: false,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_INFO,
)
```
To:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 6.0,
    stopOnTerminate: false,
    startOnBoot: false,
    debug: true,
    logLevel: bg.Config.LOG_LEVEL_INFO,
    url: locationEndpoint,
    authorization: bg.Authorization(
      accessToken: accessToken,
    ),
    extras: {
      'itemsid': items.first.itemsid,
  }
)
```

## Expected Behavior
When I initialize the plugin, I pass it the (temporary) configuration, as the `accessToken` and `itemsid` are not known yet. Once the user has logged in, my start function will first update the config (and await this), then enable the plugin (if it isn't enabled yet).

I expect the plugin to start once the new config is set, and start collecting locations, POSTing each to my `locationEndpoint`.

## Actual Behavior
On iOS, occassionally (I haven't been able to tell what causes it yet, unfortunately) the extras object sent to the server will be empty. It seems to be the first request after the configuration has been updated.

It _seems_ like the endpoint and access token are added, but the extras object isn't yet... Though whether this is really what happens is uncertain.

## Steps to Reproduce

1. Initialize the plugin and set a config without an endpoint
2. Update the config, adding an endpoint and extras, and start the plugin (async)
3. The first request _might_ arrive with an empty extras object

## Context
I'm developing the app for Android and iOS on my Windows machine, run Android from this machine and iOS from an Intel Mac Mini. This works perfectly on Android, but somehow goes wrong sometimes on iOS.

## Debug logs

I haven't managed to reproduce this with the flutter console still attached to the Mac Mini, but can see the object sent on the server side arrives with an empty `extras` object (`{}`). I'll add logs if I do get them.
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

I hope there is an explanation why this behavior occurs. Thank you in advance.

**Comment by christocracy** [comment]
And once you have your `accessToken`, you can update the `Config` (if you've already called `.ready(config)`) using method `.setConfig(newConfig)`.

**Comment by frankvollebregt** [comment]
> Each location is rendered to JSON and inserted into SQLite immediately. They are not re-rendered when `Config.extras` changes.

I suspected as much, but thanks for confirming the locations and config are separate in that sense.
> If you don't have a valid `accessToken`, why call `.start()`?
> 
> Wait until you have an `accessToken` before calling `.start()`.



I'm calling `.ready` when the app initializes, and `.setConfig` followed by `.start` once the `accessToken` becomes available (the idea being that the plugin initializes with the app initialization, and only the config update needs to be done when actually starting).

**Comment by frankvollebregt** [comment]
to rephrase my problem, I call start _after_ I have updated the config with the required extras, but still somehow a location is sometimes sent on iOS that does not contain the extras.

**Comment by christocracy** [comment]
Are you sure you don't simply have an old location "stuck" in the plugin's database?

The plugin doesn't delete locations from its database until your server returns a `20x` response.

It will keep trying and trying to post that record.  When the plugin receives an error from the server, it stops posting.  It will not proceed to the next record until your server returns `20x`.

I suggest you inspect the locations in the plugin's database with `.getLocations()`.  Use `.deleteLocations()` to clear the database.

**Comment by christocracy** [comment]
>The plugin doesn't delete locations from its database until your server returns a 20x response.

Or `Config.maxDaysToPersist` expires.

**Comment by frankvollebregt** [comment]
There were currently no locations in the database. I've added a line to automatically clear all the locations when tracking stops (i.e. when the user logs out in my app), to make sure this is not causing any trouble. I'll close the issue for now and reopen it if anything still happens. Thanks for your help!

ps: `.getLocations` does not exist. There is `.locations`, which returns a `Future<List<dynamic>>`, where I couldn't parse dynamic to a `Location` (but I could `.length` them :)). To delete them it's `.destroyLocations()` instead of `.deleteLocations()`, for future reference/other people that may stumble upon this issue.

**Comment by christocracy** [comment]
>ps: .getLocations does not exist. There is .locations

Correct for the *Flutter* version.  It's `.getLocations()` for *Cordova*, *Capacitor* and *React Native* versions.  Sometimes I forget where I'm talking.
