### ISSUE TITLE
How can I trigger http requests?

### ISSUE THREAD

**Issue by tyypgzl** [transistorsoft/flutter_background_geolocation#822]
## Your Environment
* Plugin version:4.1
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `BackgroundGeolocation.sync()`.
