### ISSUE TITLE
Foreground service notification - integrate with already running fgs notification

### ISSUE THREAD

**Issue by typexy** [transistorsoft/flutter_background_geolocation#828]
I have an app running which needs a foreground service notification anyways. With your app integrated, I have the issue that two foreground notifications are shown. 

## Your Environment
* Plugin version: 4.6.2
* Platform: Android
* OS version: Android 12 / 13; Android 8+
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: distanceFilter,
              stopOnTerminate: false,
              startOnBoot: true,
              debug: false,
              allowIdenticalLocations: false,
              preventSuspend: true,
              heartbeatInterval: 60,
              logLevel: bg.Config.LOG_LEVEL_OFF),
```

## Context
Is it somehow possible to use only the notification provided by my app and to switch off yours? Or are we running into trouble then? What would you suggest?

</details>

**Comment by christocracy** [comment]
This plugin's notificationId is `5149942585`.

If you set both services to use the `notificationId`, they will share the same notification.

**Comment by christocracy** [comment]
> preventSuspend: true,

Don't abuse this iOS-only option.  99% of use-cases do not require that battery-kiling option.
