### ISSUE TITLE
"Location Services Activated" popups continuouslly  in system tray.

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#83]
Hi sir,
As many times my getcurrentpostion called it pops up accordingly.
I have also used "usesignificantchangesonly:true" but its not stoping.

## Your Environment
* Plugin version:1.0.9
* Platform:  Android
* OS version:Mac os
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
   bg.BackgroundGeolocation.start();
 //   bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    //bg.BackgroundGeolocation.onNotificationAction(_onNotificationAction);
    bg.BackgroundGeolocation.ready(bg.Config(
//      debug: true,
    reset: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 100,
     //   locationUpdateInterval: 5000,
      stopOnTerminate: false,
      //  preventSuspend: true,
        startOnBoot: true,
     useSignificantChangesOnly: true,
     //   heartbeatInterval: 2
    )).then((bg.State state) {
      bg.BackgroundGeolocation.stop();
      print('[ready] ${state.toMap()}');
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

## . getcurrentpostion method -->
     bg.BackgroundGeolocation.getCurrentPosition(
        ). then((bg.Location location) {
          print('adarshaaaaaa');
          widget.store.dispatch(new UpdateCurrentLocationAction(WrappLocation.fromLocation(location)));

          updateLocation(location.coords.latitude, location.coords.longitude);
          // Fluttertoast.showToast( msg: 'LOCATION UPDATING -$location');
        }).catchError((error) {
          print('[getCurrentPosition] ERROR: $error');
        });

## Expected Behavior
"location services activated" poping continuouslly
## Actual Behavior
should not behave like above.
## Steps to Reproduce

1.
2.
3.
4.

## Context
I have tried   "useSignificantChangesOnly: true,"

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
That’s correct.  #getCurrentPosition launches a foreground-service to ensure completion of the request.

**Comment by ADARSHAGNIHOTRI** [comment]
then please give me an alternate to hit my updateLocation api without that popup.
actually it's frequency of that one(popup) is very high.

**Comment by christocracy** [comment]
Why are you executing #getCurrentPosition at “high frequency”?

**Comment by ADARSHAGNIHOTRI** [comment]
if ((state.profile.provider ?? false) && (state.profile.status ?? 1) > 1 ){
        bg.BackgroundGeolocation.getCurrentPosition(
          persist: false,
          timeout:30
        ). then((bg.Location location) {
          print('adarshaaaaaa');
          widget.store.dispatch(new UpdateCurrentLocationAction(WrappLocation.fromLocation(location)));

          updateLocation(location.coords.latitude, location.coords.longitude);
          // Fluttertoast.showToast( msg: 'LOCATION UPDATING -$location');
        }).catchError((error) {
          print('[getCurrentPosition] ERROR: $error');
        });
This is the one i have to perform.Just a Profile condition checking.Suggest me if you get an idea.
thankyou.

**Comment by ADARSHAGNIHOTRI** [comment]
Actually popup occurs wherever i call getcurrentPostion . So please give me atleast one solution for which "Location Service activated" should not occur.

**Comment by christocracy** [comment]
>So please give me atleast one solution for which "Location Service activated" should not occur.

There is no solution.  You can edit the content of the notification as desired though with [Notification](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Notification-class.html) config.

**Comment by nikhiljuneja** [comment]
I am also, getting the same issue @christocracy, it is very annoying to see it pop up very frequently in the system tray. Is there any way to minimize/limit the occurrence to 1 per day or something.

Otherwise, it will drive the user mad and user at the end may uninstall the app.

Please assist @christocracy

**Comment by christocracy** [comment]
>Otherwise, it will drive the user mad and user at the end may uninstall the app.

Why are you executing `#getCurrentPosition` so often as to see it "pop up very frequently"?

**Comment by christocracy** [comment]
@nikhiljuneja Show me the config you're using.
