### ISSUE TITLE
Background service stopped in release mode working in debug mode

### ISSUE THREAD

**Issue by sheetalghori** [transistorsoft/flutter_background_geolocation#830]
## Environment
* Plugin version: 4.0.2

* Platform:  Android

* OS version: All

* Device manufacturer/model: All model

* Flutter info :

[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/macbook/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/macbook/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] VS Code (version 1.70.0)
    • VS Code at /Users/macbook/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (5 available)
    • CPH2179 (mobile)           • S4LFMF75IRQOS8RK                     • android-arm64  • Android 10 (API 29)
    • CPH2239 (mobile)           • UGTKB6BMVGFYKJWK                     • android-arm64  • Android 11 (API 30)
    • iPhone 14 Pro Max (mobile) • B8312249-1458-478A-B37A-A0788813254E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

* Plugin config:
```dart 
bg.BackgroundGeolocation.ready(bg.Config(
    reset: true,
    debug: false,
    logLevel: bg.Config.LOG_LEVEL_OFF,
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
    // distanceFilter: 10.0,
    // disableElasticity: true,
    disableLocationAuthorizationAlert: false,
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: bg.PermissionRationale(
        title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"', //Change to Allow all the time
        negativeAction: 'Cancel'),
    url: "${ENV.trackerHost}/api/locations",
    authorization: bg.Authorization(
        // <-- demo server authenticates with JWT
        strategy: bg.Authorization.STRATEGY_JWT,
        accessToken: token.accessToken,
        refreshToken: token.refreshToken,
        refreshUrl: "${ENV.trackerHost}/api/refresh_token",
        refreshPayload: {'refresh_token': '{refreshToken}'}),
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    forceReloadOnLocationChange: true,
    foregroundService: true,
  )).then((bg.State state) {
    logPrint("BACKGROUND SERVICE DATA LOG:-----> [ready] ${state.toMap()}");
    if (!state.enabled) {
      startStopBackGroundLocation(true);
    }
  }).catchError((error) {
    logPrint('BACKGROUND SERVICE DATA LOG:-----> [ready] ERROR: $error');
  });





void startStopBackGroundLocation(isStart) async {
  // bg.BackgroundGeolocation.playSound(util.Dialog.getSoundId("BUTTON_CLICK"));
  if (isStart) {
    Function(bg.State) callback = (bg.State state) {
      logPrint('[start] success: $state');
      bg.BackgroundGeolocation.changePace(isStart).then((bool isMoving) {
        logPrint('[changePace] success $isMoving');
         });
    };
    bg.State state = await bg.BackgroundGeolocation.state;
    if (state.trackingMode == 1) {
      bg.BackgroundGeolocation.start().then(callback);
    } else {
      bg.BackgroundGeolocation.startGeofences().then(callback);
    }
  } else {
    dynamic callback = (bg.State state) {
      logPrint('[stop] success: $state');
    };
    bg.BackgroundGeolocation.stop().then(callback);
  }
}
```

## Expected Behavior
Socket should to reconnect and have to send data in terminate state 

## Actual Behavior
The socket is not connected again while the app is in release mode. It's working in debug mode

## Context
set
```dart
stopOnTerminate : true/false
debug:  true/false

set same build config as per debug build
```

## Debug logs
W/FlutterJNI(11946): FlutterJNI.prefetchDefaultFontManager called more than once
E/flutter (11946): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Waiting for previous start action to complete, null, null, null)
E/flutter (11946): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter (11946): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
E/flutter (11946): <asynchronous suspension>
E/flutter (11946): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499)
E/flutter (11946): <asynchronous suspension>
E/flutter (11946): #3      BackgroundGeolocation.start (package:flutter_background_geolocation/models/background_geolocation.dart:274)
E/flutter (11946): <asynchronous suspension>
E/flutter (11946): 
E/FlutterGeolocator(11946): Geolocator position updates stopped
D/FlutterGeolocator(11946): Stopping location service.
D/FlutterLocationService(11946): Unbinding from location service.
D/FlutterLocationService(11946): Destroying service.
E/flutter (11946): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:flutter_background_geolocation/flutter_background_geolocation.dart' not found.
E/flutter (11946): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (11946): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter (11946): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (11946): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
W/FlutterJNI(11946): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 36

**Comment by christocracy** [comment]
You can easily reproduce your exception by calling `.start()` twice in a row (without `await`).

```dart
bg.BackgroundGeolocation.start();
bg.BackgroundGeolocation.start();
```

**Comment by sheetalghori** [comment]
Hey @christocracy  I tried both the solution but it's still not working for me

I just need background service for send data using socket in background

**Comment by christocracy** [comment]
The exception you see is not causing the plugin to “not work”.  The plugin is just saying “I’m already starting”.

it is a harmless exception.

**Comment by christocracy** [comment]
It is 100% sure that you are calling .start() or .ready *twice*.  

Check your code.  I suspect you are just pasting code found in the /example and not really thinking about what you’re doing.

**Comment by christocracy** [comment]
I suggest you learn to use the plugin in a freshly generated *hello world* project, without copy/pasting from /example.

just follow the simple example in the readme.

**Comment by sheetalghori** [comment]
Yes, you are correct. I was calling that service twice 


But still, the issue is service not working in release mode.


```dart

E/FlutterGeolocator( 2272): Geolocator position updates stopped
D/FlutterGeolocator( 2272): Stopping location service.
D/FlutterLocationService( 2272): Unbinding from location service.
D/FlutterLocationService( 2272): Destroying service.
E/flutter ( 2272): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:flutter_background_geolocation/flutter_background_geolocation.dart' not found.
```

**Comment by christocracy** [comment]
Those logs you posted there are not from this plugin.

**Comment by christocracy** [comment]
> service not working in release mode.

Did you purchase a license?

**Comment by sheetalghori** [comment]
Yes, I purchased the license @christocracy 

Everything works file in debug mode but tired with release mode

**Comment by christocracy** [comment]
I suggest you review the Android Setup Docs.  Do not omit any step.

**Comment by christocracy** [comment]
> library 'package:flutter_background_geolocation/flutter_background_geolocation.dart' not found.

Flutter thinks you don't have the plugin installed in your `pubspec.yaml`.

**Comment by sheetalghori** [comment]
I got the solution It's because flutter updated version 3.3.*  

I just downgrade it and It's working

**Comment by christocracy** [comment]
Maybe you simply need to `flutter pub get` after upgrading.

**Comment by sheetalghori** [comment]
I tried to flutter pub get but it was not working for me @christocracy
