### ISSUE TITLE
Sporadically stops sending background location updates and app reinstall seems to fix it

### ISSUE THREAD

**Issue by usamaaslam101** [transistorsoft/flutter_background_geolocation#833]
User feedback and testing as well has revealed that the background location automatically stops sending location updates sporadically. Usually it is being fixed by our users by reinstalling the application. We don't have get any logs that can help us figure out what's is wrong. 

Important to note here is that we can see in the notification bar that the app is accessing the background location but the location update is not sent.

## Your Environment
* Plugin version: 4.7.1
* Platform: Android
* OS version: tested only on 11 and 12 (it was reproduced on both these version but after reinstalling it worked.)
* Device manufacturer / model: 
* Flutter info (`flutter doctor`): 
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: Platform.isIOS ? DISTANCE_FILTER : 0,
      stopOnTerminate: true,
      debug: false,
      reset: true,
      preventSuspend: true,
      disableMotionActivityUpdates: true,
      locationUpdateInterval: LOCATION_INTERVAL_MOVING_MS,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      notification: bg.Notification(
        title: androidNotificationTitle,
        text: androidNotificationMsg,
        smallIcon: notificationIcon,
        sticky: true,
        color: notificationColor,
      ),
      showsBackgroundLocationIndicator: true,
    );
```

## Expected Behavior

The location sending should work and not stop sending location to the server automatically
## Actual Behavior

The location sending sporadically stops 
## Steps to Reproduce

Usually it is noticed while switching networks but the behavior is not consistent

**Comment by christocracy** [comment]
I have never experienced or heard of this.  I run the /example app on some of my test devices untouched for months at-a-time.

It's possible the problem is in your own code.

Let me know when you know how to reproduce it.
