### ISSUE TITLE
Background GeoLocation stops sending to server on terminate

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#834]
Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung s21 Ultra
**Flutter Info**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**PlugIn Config**

    /***
    registering headless task specifically for android [_headlessTask]
    headless task is needed to perform dart code when the app is in kill state
    In our case we want to continue receiving location updates even if the app is fully terminated:
     ***/
    bg.BackgroundGeolocation.registerHeadlessTask(_headlessTask);

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      _updateLocation(location);
    });

    /*** onGeofence is fired the the object enters/exits/dwells within the given radius ***/
    bg.BackgroundGeolocation.onGeofence((geofenceEvent) async {
      _updateGeofence(geofenceEvent);
    });
    bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));

    if (!state.enabled) {
      await bg.BackgroundGeolocation.start();
    } else {
      return;
    }
  }

## Expected Behavior
Expect the Geolocation to still be broadcasted to the server even if the application is terminated

## Actual Behavior
As soon as the application is terminated the location stops broadcasting to the server

## Steps to Reproduce
1.  Start application
2. receive location through foreground
3. terminate app
4. stop receiving location

**Comment by christocracy** [comment]
> the location stops broadcasting to the server

I see you're not using the plugin's built-in HTTP Service (See API docs `Config.url`.) so you're responsible for you own HTTP requests.

Are you aware that `onLocation` does not fire in the terminated state (ie: "Headless State").

Are you observing the plugin's logs?  See Wiki *Debugging*.

**Comment by lloydelvt** [comment]
This is the headless task we have defined. We know the _updateLocation() method call works because it is used when the application is in foreground state. 

if (headlessEvent.name == bg.Event.LOCATION) {
      await initBackgroundIsolate();
      final location = headlessEvent.event;
      _updateLocation(location);
    } else if (headlessEvent.name == bg.Event.GEOFENCE) {
      await initBackgroundIsolate();

      final geofenceEvent = headlessEvent.event;
      _updateGeofence(geofenceEvent);
    } else if (headlessEvent.name == bg.Event.BOOT) {
      /// add boot to make sure headless task is running
      /// location
      // final geofenceEvent = headlessEvent.event;
      // _updateGeofence(geofenceEvent);
    }
  }

**Comment by christocracy** [comment]
Logs please…

man’s post your *entire* lib/main.dart

**Comment by lloydelvt** [comment]
Thank you for your timely response. When I tried to email/print the log it was empty. Before the Android OS updates the code was behaving exactly as expected. I was wondering if other users were reporting errors with the new android OS updates?

**Comment by christocracy** [comment]
> I was wondering if other users were reporting errors with the new android OS updates?

none.  I develop primarily on Pixel 6 @ android 13.

**Comment by christocracy** [comment]
The plugin is responsible only for firing the headless events.

it is not responsible for the code you implement there (ie custom http requests).  That’s between you and Flutter.

I suggest you use the plug-in’s built-in http service.

**Comment by lloydelvt** [comment]
Thank you for your help. We realized the issue was not with anything in the actually code. I am taking over for another flutter developer and when he built the APK for Android using the same code it worked as expected. Is there any extra permissions or licensing issues that you can give insight into that could be causing this? Is there anything I need to do?
