### ISSUE TITLE
Battery percentage is in negative IOS

### ISSUE THREAD

**Issue by sheetalghori** [transistorsoft/flutter_background_geolocation#836]
## Your Environment
* Plugin version: 4.7.2
* Platform: iOS 
* OS version: All
* Device manufacturer / model: In all IOS Device
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] VS Code (version 1.70.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
    enableHeadless: true,
    stopOnTerminate: false,
    logLevel: bg.Config.LOG_LEVEL_OFF,
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
    disableLocationAuthorizationAlert: false,
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: bg.PermissionRationale(
        title: "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"', //Change to Allow all the time
        negativeAction: 'Cancel'),
  ));
```

## Expected Behavior
Battery percentage should be really value

## Actual Behavior
battery: -1.0
It's in a negative value

Added all required permission from Xcode
![image](https://user-images.githubusercontent.com/55200363/192714338-d4e8b55b-d566-4055-b09c-7fda073a1817.png)

**Comment by christocracy** [comment]
Are you observing that in the simulator?  The sim doesn’t have a battery.

**Comment by sheetalghori** [comment]
No, I'm testing it in (Real device) iPhone XS with SIM.

**Comment by christocracy** [comment]
Are you using some other plugin that monitors battery?  Battery-monitoring for an App is **global** — If any other plugin toggles battery-monitoring, it’s disabled for your entire app.

`-1` is the default value when there is no battery info available.

**Comment by sheetalghori** [comment]
Nope, There's no other plugin for monitoring the battery and if it is the issue, I guess it should also be in Android. But it's working fine on the android device

**Comment by christocracy** [comment]
Let me know how to reproduce it.  I have *years* of historical data from my *iPhone* (currently *13 Pro*), which is tracking me every day via the the `/example` app in this repo.  I don't see any case where battery level `-1`.

I suggest you install the `/example` app see if you can reproduce your problem.  Use the *Advanced App*.  You can modify *Config* via the *Settings* screen (eg: Disable `debug` to turn off sound FX).

Show me your `pubspec.yaml`

<img width="1101" alt="Screen Shot 2022-09-29 at 9 27 27 AM" src="https://user-images.githubusercontent.com/14999/193045018-b0e056ac-2647-4edd-bca0-356e65cf5b36.png">

**Comment by sheetalghori** [comment]
It's working now  in the real device
