### ISSUE TITLE
Can we track user without 'Always Allow' location permission in kill state as well?

### ISSUE THREAD

**Issue by iphonedev4radixweb** [transistorsoft/flutter_background_geolocation#838]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS or Android
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
• No issues found!

## Expected Behavior
Is there any way to manage the geofencing stuff using the motions and without Location "Always Permission" in the killed state as well?

## Context
I want to track geofencing stuff without Location "Always Permission" in the killed state & want to manage on motions if possible. means on moving state & stationary state or any other way.

Please guide me.
Thanks in advance 😊

**Comment by christocracy** [comment]
> Can we track user without 'Always Allow' location permission in kill state as well?

No.  By definition, when an app is terminated, it is certainly *no longer in use.*

**Comment by christocracy** [comment]
Answer this question:  “*when your app is terminated, is it in use?*”.

**Comment by iphonedev4radixweb** [comment]
@christocracy, Yes, App is using physical activity as the plugin is managing the moving state. So I am asking if can we manage through physical activity.

**Comment by christocracy** [comment]
> Yes, App is using physical activity 

Doesn’t matter.

answer the question from the *user’s* perspective, not yours.

**Comment by christocracy** [comment]
Are trying to find a way work around location restrictions and track the location regardless of the permission granted by the user?

**Comment by iphonedev4radixweb** [comment]
No, we were only attempting to minimize the privileges needed to be accepted by the user to still achieve full functionality in all scenarios.

**Comment by christocracy** [comment]
Full functionality = “always” authorization.

WhenInUse, for example, is used for a jogging app, where the UI has a [Start Workout] / [Stop Workout] button.

to automatically trigger location-tracking in the background, Always is required.
