### ISSUE TITLE
How to update location to my server after every 30 min automatically in kill state

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#84]
****************************************************************
*
I want to send my location to my server after every 30 min automatically in kill state.
*****************************************************************

## Your Environment mac
* Plugin version:1.0.9
* Platform: iOS and Android
* OS version:12.2
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
  bg.BackgroundGeolocation.getCurrentPosition(
         
        ). then((bg.Location location) {
          widget.store.dispatch(new UpdateCurrentLocationAction(WrappLocation.fromLocation(location)));   updateLocation(location.coords.latitude, location.coords.longitude);//(my api to send loc to server)
          // Fluttertoast.showToast( msg: 'LOCATION UPDATING -$location');
        }).catchError((error) {
          print('[getCurrentPosition] ERROR: $error');
        });
## Expected Behavior
there should be a reasonable interval for which it execute in forground, backgound and kill state.
## Actual Behavior
Dont have any interval for execution neither i got anything to control its execution.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You should implement [flutter_background_fetch](https://github.com/transistorsoft/flutter_background_fetch), already included as a dependency.

**Comment by ADARSHAGNIHOTRI** [comment]
I have done this but still didn't get anything worthy------>>>>>
  BackgroundFetch.configure(BackgroundFetchConfig(
          minimumFetchInterval: 15,
          startOnBoot: true,
          stopOnTerminate: false,
          enableHeadless: true
      ), () async {
        print('[BackgroundFetch] received event');
        print('eeee');
        bg.BackgroundGeolocation.getCurrentPosition(samples: 1).then((bg.Location location){
          widget.store.dispatch(new UpdateCurrentLocationAction(WrappLocation.fromLocation(location)));
          updateLocation(location.coords.latitude, location.coords.longitude);
        });
        BackgroundFetch.finish();
      });


void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');
  bg.BackgroundGeolocation.getCurrentPosition().then((bg.Location location){
    updateLocation(location.coords.latitude, location.coords.longitude);
    print('background fetch succesful');

  });
  BackgroundFetch.finish();
}

void main() {
  final store = new Store<GlobalAppStore>(appStateReducer, initialState: new GlobalAppStore(new Profile(), null, new List<TefillinWrapp>(), null, null, null));
  final FirebaseMessaging _firebaseMessaging = new FirebaseMessaging();


  //LocationPicker.initApiKey(globals.GOOGLE_MAPS_API_KEY);
  runApp(new TefillinWrappStore(store: store, firebaseMessaging: _firebaseMessaging,));
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

}

**Comment by ADARSHAGNIHOTRI** [comment]
my app stop working after killing my app after some time.

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by ADARSHAGNIHOTRI** [comment]
So my code is ok or not to fetch location in kill state?

**Comment by christocracy** [comment]
>So my code is ok

Yes.

**Comment by ADARSHAGNIHOTRI** [comment]
Is it because i am using debug mode?

**Comment by christocracy** [comment]
However, you should `await bg.BackgroundGeolocation.getCurrentPosition()` before calling `bg.BackgroundFetch.finish()`.

**Comment by christocracy** [comment]
>Is it because i am using debug mode?

No

**Comment by ADARSHAGNIHOTRI** [comment]
Is there any other method to solve my problem?(updaing location in kill state with some interval)
any link for solution please suggest me.

**Comment by christocracy** [comment]
> Is there any other method to solve my problem?

No.  I field-test daily on 11 Android devices running untouched for weeks.  I have no such problem except on my Huawei P20, which is the vendor's fault.  

Your problem is likely related to the OS vendor (which you chose to ignore providing in the issue template.)
![](https://dl.dropbox.com/s/mp0splk6dqqnaqy/Screenshot%202019-06-24%2009.42.12.png?dl=1)

http://dontkillmyapp.com

**Comment by ADARSHAGNIHOTRI** [comment]
It is samsung s6

**Comment by christocracy** [comment]
And you're *simulating* background fetch events, as directed in the background_fetch README?

**Comment by ADARSHAGNIHOTRI** [comment]
I have added Application.java file according to background geolocation plugin which is differ to background fetch android setup.So does it effect the functionality?

**Comment by ADARSHAGNIHOTRI** [comment]
> And you're _simulating_ background fetch events, as directed in the background_fetch README?

Is it necessary?

**Comment by christocracy** [comment]
If you want to be an efficient developer and test the functionality in seconds instead of waiting 15 minutes, yes.

**Comment by ADARSHAGNIHOTRI** [comment]
> I have added Application.java file according to background geolocation plugin which is differ to background fetch android setup.So does it effect the functionality?

What about this sir?

**Comment by ADARSHAGNIHOTRI** [comment]
> If you want to be an efficient developer and test the functionality in seconds instead of waiting 15 minutes, yes.

Ok sir, Point to be noted.  Thankyou for advice.

**Comment by ADARSHAGNIHOTRI** [comment]
Still not working Don't know what to do now?

**Comment by ADARSHAGNIHOTRI** [comment]
Actually it update in killed state only when i run adb command to force run.
15 min fetch interval does not working anymore.

**Comment by ADARSHAGNIHOTRI** [comment]
When i run this command in kill state then this appears----->>>



ADARSHs-Mac-mini:platform-tools adarshagnihotri$ ./adb shell cmd jobscheduler run -f  com.lightuptheworld.tefillinwrap 999
Could not find job 999 in package com.lightuptheworld.tefillinwrap / user 0

**Comment by ADARSHAGNIHOTRI** [comment]
My Application.java file---->>>>
package com.lightuptheworld.tefillinwrap;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;
import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
    BackgroundFetchPlugin.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}

**Comment by christocracy** [comment]
Are you not actually watching $ adb logcat, as directed in the README?
