### ISSUE TITLE
Machine licensing for android?

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#842]
## Flutter/Android Studio
* Plugin version: 4.7.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: All Android devices
* Flutter info (`flutter doctor`): 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
/***
    registering headless task specifically for android [_headlessTask]
    headless task is needed to perform dart code when the app is in kill state
    In our case we want to continue receiving location updates even if the app is fully terminated:
     ***/
    bg.BackgroundGeolocation.registerHeadlessTask(_headlessTask);

    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      _updateLocation(location);
    });

    bg.BackgroundGeolocation.onActivityChange((actChangeEvent) {
      _activityChange(actChangeEvent);
    });

    /*** onGeofence is fired the the object enters/exits/dwells within the given radius ***/
    bg.BackgroundGeolocation.onGeofence((geofenceEvent) async {
      _updateGeofence(geofenceEvent);
    });
    bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));

```

## Expected Behavior
In headless task, We are expecting to receive location updates as it calls the same update location function as the onLocation call and it works as expected. I am taking over programming for another programmer and am wondering if there is anything I need to do differently during the build process.

## Actual Behavior
The code works as expected but only when the old developer builds the app/appbundle for release. When I build the app/appbundle the terminated state does not work correctly. We both built the same code and it only worked when the old programmer built it. We both included the same license and encryption_password in the android manifest for your client MOTORMOUTH. Is there something I need to add to my machine to make sure it is working properly?

**Comment by lloydelvt** [comment]
Ok...Do you have any advice as to what could be causing the problem at all?

**Comment by christocracy** [comment]
I have no idea.

**Comment by christocracy** [comment]
I suggest you build yourself a fresh new *hello world* app using the applicationId and license key and a very simple implementation with a release build.
