### ISSUE TITLE
Geofencing event not fired in android flutter version.

### ISSUE THREAD

**Issue by RGiVcardo** [transistorsoft/flutter_background_geolocation#843]
## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Xiaomi Redmi Note 11
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.19044.2006], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
    • No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
            reset: false,
            transistorAuthorizationToken: token,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 10.0,
            stopTimeout: 5,
            autoSync: true,
            stopOnTerminate: true,
            locationAuthorizationRequest: 'Always',
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60))
        .then((bg.State state) async {
      if (state.schedule.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
```

## Expected Behavior
Get geofence event triggers

## Actual Behavior
Geofence triggers not being called upon in any devices

## Steps to Reproduce

1. Create geofence
2. Start trip
3. Geofence will only return ENTER Call
4. After changing many locations it's keep giving ENTER event

## Context

Same code working in **Pixel 4** and not working in **Pixel 6, Moto G7, Samsung Galaxy M32 and Realme 8** devices. Can you please help me out?

Site Logs [click here](https://tracker.transistorsoft.com/iVcardo_driver)

**Comment by christocracy** [comment]
>Plugin version: 1.8.0

The latest version is [4.8.0](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md)
