### ISSUE TITLE
getCurrentPosition

### ISSUE THREAD

**Issue by ivangoluuk** [transistorsoft/flutter_background_geolocation#845]
Hi, is there a way to avoid calling the "OnLocation" listener when I call the "getCurrentPosition" method... I just want the coords

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> is there a way to avoid calling the "OnLocation" listener when I call the "getCurrentPosition" method

no.  Add a flag to `extras` (Eg: `getCurrentPosition: true` and add logic to `onLocation` to ignore as desired.
