### ISSUE TITLE
TSLocationManager/TSLocationManager.h' file not found when IOS app build in Xcode

### ISSUE THREAD

**Issue by pgeon-dev** [transistorsoft/flutter_background_geolocation#846]
## Your Environment
* Plugin version: 4.8.0
* Platform: iOS or Android: iOS
* Mac OS version: 12.6
* Device manufacturer / model: Any iOS Device(arm64)
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.6 21G115 darwin-arm, locale
    en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.72.0)
[✓] Connected device (2 available)
* Plugin config:
This Plugin is working perfectly in android but in IOS app build we are getting below errors :

`/Users/afiq/dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_background_geolocation-4.8.0/ios/Classes/streams/StreamHandler.h:2:9: 'TSLocationManager/TSLocationManager.h' file not found`

## Actual Behavior

<img width="255" alt="Screenshot 2022-10-10 at 4 30 27 PM" src="https://user-images.githubusercontent.com/70680567/194826653-a25489f0-f1cd-4fec-8e26-4a3723cf5078.png">

Plugins used are like below
![Screenshot 2022-10-10 at 4 36 54 PM](https://user-images.githubusercontent.com/70680567/194827499-240527aa-cf6c-4f34-b655-64f2de713713.png)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>[✓] Xcode - develop for iOS and macOS (Xcode 13.4)

The latest version `4.8.0` was built with *XCode 14*.  Try upgrading to *XCode 14*.

**Comment by pgeon-dev** [comment]
Thank you! After upgrading to XCode 14 its finally working now.

**Comment by christocracy** [comment]
I've got both *XCode 13 & 14* installed now.  I'll probably rebuild `TSLocationManager.xcframework` with *XCode 13.4.1* and release to `4.8.1`.  I've done this in the past.

It always causes mayhem when I build `TSLocationManager.xcframework` with the latest XCode.
