### ISSUE TITLE
Unable to build for ios : Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Samuel310** [transistorsoft/flutter_background_geolocation#847]
Unable to build for ios.
Error: Undefined symbols for architecture arm64
Unable to run on real device (arm64) but runs in emulator.

## Your Environment
* Plugin version: ^4.8.0
* Platform: iOS
* OS version: 12.2.1
* Device manufacturer / model: MacBook Air (M1, 2020)
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2.1 21D62 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
* Plugin config:

1.  add dependency,
  flutter_background_geolocation: ^4.8.0
  background_fetch: ^1.1.1

2. Followed ios installation guide mentioned in,  https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md

## Steps to Reproduce

1. add dependency,
  flutter_background_geolocation: ^4.8.0
  background_fetch: ^1.1.1
2.  Followed ios installation guide mentioned in,  https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Check attachment

```

</details>

[error_log.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/9746188/error_log.txt)

**Comment by christocracy** [comment]
The latest version of the plugin `4.8.0` was built with *XCode 14*.

Try upgrading to *XCode 14*.

**Comment by Samuel310** [comment]
It worked. After updating XCode and Flutter.
