### ISSUE TITLE
Android headless mode, no notification on geofence events

### ISSUE THREAD

**Issue by dinonovak** [transistorsoft/flutter_background_geolocation#848]
## Your Environment
* Plugin version: 4.8.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung A03
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-HR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
* Plugin config:
```
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        notification: bg.Notification(
            sticky: false,
            title: "You hit geofence",
            text: "You have just hit geofence"),
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_ERROR));
```

## Expected Behavior
In headless mode, event is firing, but how can user get notification on event?

void headlessTask(bg.HeadlessEvent headlessEvent) async {
```
  switch (headlessEvent.name) {
case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print('- GeofenceEvent: $geofenceEvent');
      break;
  }
}
```
## Actual Behavior
Headless mode, no geofence event notification triggered in foreground when app closed

## Steps to Reproduce
-
## Context
- show notification in system bar of geofence event, enable user to open app on speficif page depending on geofence triggered

**Comment by christocracy** [comment]
Use a flutter notification plugin to generate a notification.
