### ISSUE TITLE
Plugin seems to be providing new location updates only when WiFi is off

### ISSUE THREAD

**Issue by noorbakerally** [transistorsoft/flutter_background_geolocation#851]
## Your Environment
* Plugin version:4.8.1
* Platform: Android
* OS version: 12
* Device manufacturer / model: HUAWEI
* Flutter info (`flutter doctor`): Flutter (Channel stable, 3.3.2
* Plugin config:
```
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1,
        stopOnTerminate: true,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
Get location updates whether using WiFi or GPS Sensor, this should be transparent to the user

## Actual Behavior
It seems as if the plugin is using WiFi first, as im getting new location updates only after disabling WiFi

## Steps to Reproduce

1. Provide a callback to `bg.BackgroundGeolocation.onLocation`
2. Ensure both WiFi & GPS is on
3. Trying to walk away from WiFi, there will not be any location updates
4. Just to repeat the same, come at the same initial place, turn off wifi, there will be location updates

## Context
I need to have location update as soon as it is possible to get them, preferably as soon as user moves, independently of whether they are using GPS or WiFi

## Debug logs
I don't have any such logs

**Comment by christocracy** [comment]
I have never heard of this.

Location services always works best with wifi enabled,

I see you’re reporting this for a Huawei device,

try on a different device.

**Comment by christocracy** [comment]
Also, this plugin requires *Google Play Services*.  It does not support Huawei's "*HMS*".
