### ISSUE TITLE
Plugin not responding properly to motion change

### ISSUE THREAD

**Issue by noorbakerally** [transistorsoft/flutter_background_geolocation#852]
## Your Environment
* Plugin version:4.8.1
* Platform: Android
* OS version: 12
* Device manufacturer / model:HUAWEI
* Flutter info (`flutter doctor`):Flutter (Channel stable, 3.3.2
* Plugin config:
```
bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1,
        stationaryRadius: 1,
        minimumActivityRecognitionConfidence: 1,
        isMoving: true,
        stopTimeout: 0,
        stopOnTerminate: true,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
Device should trigger onMotionChange callback when moving

## Actual Behavior
Device not triggering onMotionChange callback even after moving 10 metres

## Context
My application is responsive in the sense that it keeps the user informed. Initially, when starting, the application is in 'Paused' state. As soon as the user starts walking, it should enter 'Moving' state, this isn't happening even after walking around 10 metres. To force this, i've tried to set `minimumActivityRecognitionConfidence` to 1 so that a motion change event generates but still nothing.

**Comment by christocracy** [comment]
> Device manufacturer / model:HUAWEI

Huawei are the most unreliable device on earth.

see https://dontkillmyapp.com

**Comment by christocracy** [comment]
> minimumActivityRecognitionConfidence

this option is *deprecated* and no longer used.

the native Motion api is a black box with on an on/off switch.  There is no way to control the sensitivity.

It either works or it doesn’t.  It is largely affected by restrictions built into the os by particularly poorly behaved device manufacturers which violate the Android api.
