### ISSUE TITLE
[Android 13] Location Permission dialogs make other permission dialog unresponsive

### ISSUE THREAD

**Issue by frankvollebregt** [transistorsoft/flutter_background_geolocation#853]
## Your Environment
* Plugin version: 4.8.1
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google Pixel 6, Google Pixel 7
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 6.0,
      stopOnTerminate: false,
      startOnBoot: false,
      debug: isDev,
      logLevel: isDev ? bg.Config.LOG_LEVEL_DEBUG : bg.Config.LOG_LEVEL_WARNING,
      url: locationEndpoint,
      authorization: bg.Authorization(
        accessToken: accessToken,
      ),
      extras: {
        'itemsid': items.first.itemsid,
      },
      // only track location while in a vehicle
      triggerActivities: 'in_vehicle',
      speedJumpFilter: 1,
)
```

## Expected Behavior
Either the BG plugin dialog suppresses (or shows on top of) the existing notification permision dialog (as is the case on iOS), or the BG plugin dialog only appears after the existing dialog has been dismissed.

## Actual Behavior
The existing notification permission dialog hangs when the BG plugin starts requesting permissions too

## Steps to Reproduce

1. Request notification permissions (without having permissions yet)
2. Initialize BG plugin (without having permissions yet) at the same time

## Context
I was trying to initialize the BG plugin and Firebase messaging after the user has logged into the app

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
10-18 16:26:03.249  1737  2743 I ActivityTaskManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.permissioncontroller cmp=com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10272
10-18 16:26:03.299  1737  2743 D CoreBackPreview: Window{4b3711a u0 com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@9f31e28, mPriority=0}
10-18 16:26:03.314  1737  1758 I ActivityTaskManager: Displayed com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity: +63ms`
10-18 16:26:03.797  9977  9977 I TSLocationManager:   ­ƒöÁ  LocationAuthorization: Requesting Background permission
10-18 16:26:03.804  1737  2743 I ActivityTaskManager: START u0 {act=[android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION, android.permission.ACTIVITY_RECOGNITION] flg=0x10000000 cmp=MY_PACKAGE/com.intentfilter.androidpermissions.PermissionsActivity (has extras)} from uid 10272
10-18 16:26:03.849  1737  1776 I ActivityTaskManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.permissioncontroller cmp=com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10272
10-18 16:26:03.870  1737  1776 D CoreBackPreview: Window{87f28a0 u0 MY_PACKAGE/com.intentfilter.androidpermissions.PermissionsActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@3b4001e, mPriority=0}
10-18 16:26:03.894  1737  1776 D CoreBackPreview: Window{f51f4f6 u0 com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@9818b64, mPriority=0}
10-18 16:26:03.910  1737  1758 I ActivityTaskManager: Displayed com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity: +105ms
10-18 16:26:05.428  1737  1919 W InputDispatcher: Not sending touch gesture to 29adf6e ActivityRecordInputSink MY_PACKAGE/com.intentfilter.androidpermissions.PermissionsActivity because it is not responsive
```
The last line is repeated every time I tap the dialog (which still shows for notifications)

</details>

**Comment by frankvollebregt** [comment]
My apologies if this has nothing to do with the Flutter Background Geolocation package. I'm not sure what else to go off of here. I'm currently requesting the permissions at separate times as a temporary workaround.

**Comment by christocracy** [comment]
Maybe you shouldn’t call .start() until your other permissions requests have resolved.

**Comment by frankvollebregt** [comment]
Is this, in that sense, expected behavior? I.e. can I not request multiple permissions from different places and expect each dialog to show after the previous one has resolved on Android (13)? 

I don't mind writing some code to use `PermissionHandler` and request permissions sequentially to work around this issue if that's the case.

**Comment by christocracy** [comment]
> can I not request multiple permissions from different places and expect each dialog to show after the previous one has resolved on Android (13)?

The plugin is capable of doing it own permission requests for all its necessary permissions when you call .start().

if you’re using some other plugin to request permissions simultaneously, bad things are bound to happen.  

When you are satisfied that your 3rd party permissions plugin has attained all your desired permissions, only the call .start()

**Comment by frankvollebregt** [comment]
Fair enough, thank you.

I was mainly posting this on the off-chance that the behavior could be explained by some specific way you handle requesting permissions (where this 'new' notification permission wasn't taken into account yet as a dialog to 'wait for')

Thank you for the clarification :)

**Comment by christocracy** [comment]
> where this 'new' notification permission wasn't taken 

Foreground-services are exempt from requiring the new Android runtime notification.

if you are seeing a runtime permission dialog for notification, where you’re not explicitly requesting that permission, simply use targetSdkVersion 33 and you will no longer see that permission request.
