### ISSUE TITLE
How to get lat long continuously when device moving and vice versa

### ISSUE THREAD

**Issue by naelcharis** [transistorsoft/flutter_background_geolocation#859]
## Your Environment
* Plugin version: 4.8.1
* Platform: Android
* OS version:
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by naelcharis** [comment]
Thank you, already done it.  Could you please help me of How to update lat long variable when location lat long change. Thank you

**Comment by naelcharis** [comment]
i tried this but it doesnt work this way

 bg.BackgroundGeolocation.changePace(true).then((bool isMoving) {
      bg.BackgroundGeolocation.getCurrentPosition(
          persist: false,     // <-- do not persist this location
          desiredAccuracy: 0,
          maximumAge: 10000,  // <-- desire best possible accuracy
          timeout: 30000,     // <-- wait 30s before giving up.
          samples: 3          // <-- sample 3 location before selecting best.
      ).then((bg.Location location) {
        if(lat != location.coords.latitude.toString()){
          lat = location.coords.latitude.toString();
          long = location.coords.longitude.toString();
          userTrackData.doc(widget.userId).collection(DateFormat('dd-MMM-yyyy').
          format(date)).doc(DateFormat('HH:mm:ss').format(DateTime.now())).set({
            'Geopoint' : GeoPoint(location.coords.latitude, location.coords.longitude),
            'IsMock': location.mock
          });
        }
        print('[getCurrentPosition] - $location');
      }).catchError((error) {
        print('[getCurrentPosition] ERROR: $error');
      });
      print('- BackgroundGeolocation is now in the tracking (moving) state');
    });

**Comment by christocracy** [comment]
Please learn to syntax highlight code blocks:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by naelcharis** [comment]
Thanks for informing

...

void _onClickChangePace() {
    setState(() {
      _isMoving = !_isMoving!;
    });
    print("[onClickChangePace] -> $_isMoving");
    bg.BackgroundGeolocation.changePace(_isMoving!).then((bool isMoving) {

        bg.BackgroundGeolocation.getCurrentPosition(
            persist: false,     // <-- do not persist this location
            desiredAccuracy: 0,
            maximumAge: 10000,  // <-- desire best possible accuracy
            timeout: 30000,     // <-- wait 30s before giving up.
            samples: 3          // <-- sample 3 location before selecting best.
        ).then((bg.Location location) {

          if(lat != location.coords.latitude.toString()){
            lat = location.coords.latitude.toString();
            long = location.coords.longitude.toString();
            userTrackData.doc(widget.userId).collection(DateFormat('dd-MMM-yyyy').
            format(date)).doc(DateFormat('HH:mm:ss').format(DateTime.now())).set({
              'Geopoint' : GeoPoint(location.coords.latitude, location.coords.longitude),
              'IsMock': location.mock.toString() + 'onclickchangepace'
            });
          }
          print('[getCurrentPosition] - $location');
        }).catchError((error) {
          print('[getCurrentPosition] ERROR: $error');
        });

      print('[changePace] success $isMoving');
    }).catchError((e) {
      print('[changePace] ERROR: ' + e.code.toString());
    });
  }

...

**Comment by christocracy** [comment]
Please learn to syntax highlight code blocks:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

You create code with *backtick* characters, not periods.
