### ISSUE TITLE
time-based location updates on iOS

### ISSUE THREAD

**Issue by ilyosbekkk** [transistorsoft/flutter_background_geolocation#860]
I am building an app that tracks the user's location even if the app is in the background and according to the client's requirement the device should send location updates every 5 seconds in the moving state. In Philosophy of Operation, you mentioned that in iOS CLLocationManager is strictly distance-based, but I have found out that there are some workarounds to implement this functionality natively on iOS (https://www.xamboy.com/2020/10/19/battery-efficient-background-time-based-location-updates-on-ios/). I am not an iOS expert but I believe that there must be a really good reason behind why you didn't implement time-based location update functionality to this plugin. So, I just want to know your opinion about implementing a time-based location update feature natively and adding it to this plugin.Thank you

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer/model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Timers are not battery efficient.

Time-based location updates are not battery efficient (what’s the point of updating location every 5s when you’re in a traffic jam?)

iOS doesn’t provide built-in time-based updates, so I’m not interested.

If you want time-based updates iOS updates, run your own Dart timer.
