### ISSUE TITLE
CMAltimeter Support within the plugin

### ISSUE THREAD

**Issue by iliraga** [transistorsoft/flutter_background_geolocation#864]
Hi, sorry for ignoring the template, but this is rather a question than a bug report.

Does the plugin support the fetching of the elevation / altitude per location by the `CMAltimeter` class or something similiar? We are currently building an app where the elevation data is crucial, and after some digging I found out that both operating system provide dedicated APIs to do so. After digging through the documentation of the plugin, I wasn't able to find anything in that direction.

If the answer is no: Would it make sense to implement it on plugin-level or is this something which would cause a conflict with the current `TSLocationManager`-Implementation?

https://developer.apple.com/documentation/coremotion/cmaltimeter

**Comment by christocracy** [comment]
No, the plugin does not get altitude from `CMAltimeter`.  

It gets it from [`CLLocation.altitude`](https://developer.apple.com/documentation/corelocation/cllocation/1423820-altitude) and [`ellipsoidalAltitide`](https://developer.apple.com/documentation/corelocation/cllocation/3861801-ellipsoidalaltitude)

**Comment by iliraga** [comment]
Is there a chance to get such a feature where the altimeter data is merged in the location data as well? Or is this completly out of the scope and we have to figure something on our end? Since it's a custom feature we could pay for that as well.

**Comment by christocracy** [comment]
What’s wrong with the altitude already provided?

**Comment by iliraga** [comment]
The accuracy is usually not that high, after running some tests with the barometer-based altimeter it seems that that one is wqy more accurate. We're building an app where the altitude is crucial.

**Comment by christocracy** [comment]
Show me your test results.

**Comment by iliraga** [comment]
Find the differences between the column `altitude` (which is retrieved from the geolocation altitude property) and the `calculatedAltitude` column.

https://files.irte.ch/XjtJudW8

**Comment by christocracy** [comment]
Are you aware of the newly added [`Location.coords.ellipsoidalAltitude`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Coords/ellipsoidalAltitude.html) ?  Do another test and provide another spreadsheet with *that* attribute added.

**Comment by christocracy** [comment]
iOS docs:  [`CLLocation.ellipsoidalAltitude`](https://developer.apple.com/documentation/corelocation/cllocation/3861801-ellipsoidalaltitude?language=objc)

**Comment by iliraga** [comment]
Implemented an own solution through the CMAltimeter API.

**Comment by christocracy** [comment]
How do the results compare with location.coords.altitude?
