### ISSUE TITLE
Does BackgroundGeolocation.stop() halt all background processes?

### ISSUE THREAD

**Issue by elouiestudent** [transistorsoft/flutter_background_geolocation#868]
## Your Environment
* Plugin version: 4.3.4
* Platform: iOS
* OS version: 15.5
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.5, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
// Register plugin with corresponding callbacks
    bg.BackgroundGeolocation.onLocation(_locationCallback,
        (bg.LocationError error) async {
      // 0 - Location unknown, 1 - Location permission denied,
      // 2 - Network error, 408 - Location timeout
      Logger.log('[onLocation] ERROR: $error');
      if (error.code == 1) await stopBackgroundProcesses();
    });
    bg.BackgroundGeolocation.onGeofence(_geofenceCallback);
    bg.BackgroundGeolocation.onProviderChange((event) async {
      // If app is not given "Always" permission, stop background tracking
      if (event.status != bg.ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS) {
        // await Storage.setNotificationsFrequency(NotificationFrequencies.NEVER);
        await stopBackgroundProcesses();
      }
      // Starts background processes outside of app if permissions are given
      else {
        if (await Storage.getSetupComplete() &&
            (await Storage.getConsentTimestamp() != null) &&
            (await Storage.getNotificationsFrequency() !=
                NotificationFrequencies.NEVER)) {
          startBackgroundTracking();
        }
      }
    });
    // Configure settings
    await bg.BackgroundGeolocation.ready(bg.Config(
        locationAuthorizationRequest: 'Always',
        disableLocationAuthorizationAlert: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: distanceFilter,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        persistMode: bg.Config.PERSIST_MODE_NONE,
        logLevel: bg.Config.LOG_LEVEL_OFF));
  }
```

## Expected Behavior
Once `BackgroundGeolocation.stop()` is called, all background processes relating to the plugin are stopped, resulting in less battery drain than when the background processes are enabled.

## Actual Behavior
The callbacks are no longer triggering after `BackgroundGeolocation.stop()` is called, but users are reporting that the battery drain persists.

## Steps to Reproduce

1. Start the plugin with geofences and background location tracking callbacks registered.
2. Evaluate the percentage of battery drained over the day.
3. Stop the processes using (`BackgroundGeolocation.stop()`).
4. Evaluate the percentage of battery drained over the day.

## Context
We have a notification functionality that sends a notification whenever the user enteres a geofence with some additional logic to create the geofences using the user's background location. We expect this to have some amount of battery drain. However, when the user turns off the notifications, this battery drain should stop. Does `BackgroundGeolocation.stop()` halt all background processes?

</details>

**Comment by christocracy** [comment]
.stop() stops everything.

**Comment by elouiestudent** [comment]
Just to confirm, `BackgroundGeolocation.stop()` stops the following:

- Stops listening for callbacks of all types (e.g. geofence and location callbacks)
- Stops the background threads continuing to fetch information including the user's real-time location

And this should result in decreased battery usage after `BackgroundGeolocation.stop()` is called?

**Comment by christocracy** [comment]
The plugin doesn’t consume energy after calling .stop().

Any perceived consumption of energy after calling .stop() is not the plug-in’s fault.

**Comment by elouiestudent** [comment]
Thanks for the quick response! One final question: do you know what would happen if `BackgroundGeolocation.start()` was called multiple times before `BackgroundGeolocation.stop()` is called?

**Comment by christocracy** [comment]
> do you know what would happen if BackgroundGeolocation.start()

Yes.  Nothing.  There is only one instance of the native plugin.  It’s a singleton.  No, there will not be multiple instance of the plugin hiding in memory.
