### ISSUE TITLE
Is there a way to stop the headless task from reporting location after it has been started?

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#869]
## Your Environment
* Plugin version: 4.7.0
* Platform: iOS or Android
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5 21G72 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
        url: "https://app.motormouth.io/v2/user/location/flutter",
        autoSync: true,
        transistorAuthorizationToken: token,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 25.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));
```

Is there a way to stop the headless task from reporting location after it has been started? Can we use a HTTP error status code or something similar?

**Comment by christocracy** [comment]
Isn’t your question “is there a way to stop the plugin?”.

Yes, by calling `.stop()`.

and yes, the plugin will analyze http responses for a particular json payload, where you can execute methods upon the plugin “rpc style”.

See the api docs for “http guide”, then search that page for “RPC”.
