### ISSUE TITLE
Plugin toggles AppLifecycleState between inactive and resume on start

### ISSUE THREAD

**Issue by shantaly** [transistorsoft/flutter_background_geolocation#872]
## Your Environment
* Plugin version: 4.8.3
* Platform: Android 
* OS version: 12
* Device manufacturer / model: One Plus 8 Pro
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
          locationAuthorizationRequest: 'Always',
          reset: true,
          debug: true,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          backgroundPermissionRationale: bg.PermissionRationale(
              title:
                  "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
              message:
                  "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
              positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
              negativeAction: 'Cancel'),
          url: "$_baseUrl/tracking",
          authorization: bg.Authorization(
              strategy: bg.Authorization.STRATEGY_JWT,
              accessToken: tokens.accessToken,
              refreshToken: tokens.refreshToken,
              refreshUrl: "$_baseUrl/user/refresh",
              refreshHeaders: {
                "Authorization": "Bearer ${tokens.refreshToken}"
              },
              refreshPayload: {
                "refresh_token": "{refreshToken}"
              }),
          stopOnTerminate: false,
          startOnBoot: false,
          enableHeadless: false)
```

## Expected Behavior
While the app is in the foreground, when `bg.BackgroundGeolocation.start();` is called ApplifecycleState should not change and stay `AppLifecycleState.resumed`

## Actual Behavior
Once the plugin is configured and started the AppLifecycleState goes to `AppLifecycleState.inactive` and then back to the `AppLifecycleState.resumed` state while being in the foreground.

## Context
This issue constrains developers from using the app's natural App Lifecycle States to implement other business logic.

**Comment by christocracy** [comment]
The plugin is using an Android mechanism to ensure the user has their settings configured sufficiently for location updates.  This requires an invisible activity to be run, which is what you experience.

See api docs Config.disableLocationAuthorizationAlert.

**Comment by shantaly** [comment]
Thank you for your response. What if I want to enable location authorization alert (disableLocationAuthorizationAlert=false) and use the AppLifecycleState for other business logic in my application? It seems like a huge constraint.

**Comment by christocracy** [comment]
Then you would have to reevaluate your business logic there to accept that your app can go into the background for this reason.
