### ISSUE TITLE
Apple rejected submission tell that our app doesn't use location service.

### ISSUE THREAD

**Issue by iporsut** [transistorsoft/flutter_background_geolocation#873]
## Your Environment
* Plugin version: 4.8.1
* Platform: iOS
* OS version: 
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
It should passed review from Apple since we already used library and tested on Testfight and it works corectly.

## Actual Behavior
Apple rejected our submission with detail that describe like we haven't use the location feature in our app.
<img width="1150" alt="Screen Shot 2565-11-03 at 16 34 25" src="https://user-images.githubusercontent.com/216396/199688255-f25cbfd0-1b9c-4bfc-a3bc-b53ca59ea64c.png">

## Steps to Reproduce

1.
2.
3.
4.

## Context
Summit application to review with Apple.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Apple doesn't feel that your app's use-case for location-services *deserves* to have this checkbox enabled in XCode:

<img width="854" alt="Screen Shot 2022-11-03 at 9 13 30 AM" src="https://user-images.githubusercontent.com/14999/199730424-e9263105-f418-4ea6-a978-a3b1ef6bd5f2.png">

If that is the case, you must *disable* that checkbox and configure the plugin with `useSignificantChangesOnly: true`.  Your app will receive a location update only about ever 500-1000 meters.  `Config.distanceFilter` will no longer apply.

What is the purpose of you app?

**Comment by iporsut** [comment]
@christocracy 
> What is the purpose of your app?
Our app would like to tracking the current location of our driver that sending product from distributed center to front store.

We need our app still send location in background even though driver active on other app.

**Comment by christocracy** [comment]
> on other app

What do you mean “other app”?

why does Apple feel your app doesn’t deserve *background location* capability?

**Comment by iporsut** [comment]
@christocracy I'm not sure why Apple feel like that too. We just try our best to fix and resubmit again and wait reviewing response. Thanks for supporting.

**Comment by christocracy** [comment]
If you feel that Apple is incorrect, that this rejected app of yours actually *does* require background location-tracking, then it’s up to you to object to Apple and explain to them exactly why.
