### ISSUE TITLE
Any plan to support HMS (Huawei) location service?

### ISSUE THREAD

**Issue by sjoudi** [transistorsoft/flutter_background_geolocation#874]
Currently, the plugin supports android devices with Google Play Services (requires Google Mobile Services: GMS). However, there are users who use the new Huawei devices like P50 Pro that are Android based but use Huawei Mobile Services instead (location, IAP, etc.).

I checked HMS location APIs and they are very much similar to Google location APIs in many aspects. It seems Huawei plan is to provide alternative services with the minimum learning curve and they used same naming for methods and classes.

Huawei even released their huawei_location plugin for Flutter on pub.dev with background feature.

Any plan to support HMS and enable the Plugin to work on the new Huawei devices? This will save developers a lot of time and issues mingling with a third platform.

Regards

**Comment by sjoudi** [comment]
Answered in #879 Feature Request - [Android only] Force the use of Android LocationManager instead of Google's FusedLocationProvider

**Comment by christocracy** [comment]
Huawei support is coming soon.

**Comment by sjoudi** [comment]
This is really great...

Thanks Chris for the update.

Will it be part of flutter_background_geolocation, or a sandalone plugin like React Native and Cordova editions?

**Comment by christocracy** [comment]
It will be integrated into the existing library.

**Comment by sjoudi** [comment]
This will be a great value add to the exisiting library 👍

**Comment by christocracy** [comment]
> It will be integrated into the existing library.

However, it *will* require a separate license key to unlock for Huawei devices, since there will be an unknown support cost to maintaining the HMS adapter as both HMS and GMS evolve.  It will be priced at a fraction of the BGGeo license (Eg $99) and I’ll give away some free licenses to early adopters.

I’ve ordered a *Huawei P40* to test it out.  It should arrive next week.

**Comment by christocracy** [comment]
My first Huawei HMS phone (*Nova 9 SE @ EMUI 12.0.1*) arrived today and the plugin worked on first boot of the demo app.

**Comment by christocracy** [comment]
Who wants to be *the first* to test it?

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: hms
```

Unfortunately, I discovered *after purchase* that my `$650` *Nova 9 SE* does not have a *Gyroscope* and HMS `ActivityRecognition` API doesn't work when *Gyroscope* is missing.  *Google Play Services'* `ActivityRecognition` API will still work with at least an *accelerometer*.

```
TSLocationManager: ╔═════════════════════════════════════════════
TSLocationManager: ║ DEVICE SENSORS
TSLocationManager: ╠═════════════════════════════════════════════
TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="acc_s004_002 Accelerometer Non-wakeup", vendor="Kionix", version=132096, type=1, maxRange=78.45318, resolution=0.0023928226, power=0.145, minDelay=2500}
TSLocationManager: ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="mag_s004_001 Magnetometer Non-wakeup", vendor="QST", version=258, type=2, maxRange=4912.0, resolution=0.1, power=1.1, minDelay=10000}
TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="qualcomm", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
TSLocationManager: ╚═════════════════════════════════════════════
```

**Comment by sjoudi** [comment]
Hi Chris.

I have downdloaded the example project, installed it on my P50 and currently testing it.

Will update you soon.

So far it looks it's working as expected.

💪 Well done!

**Comment by christocracy** [comment]
Any idea where I could order a P50 to be shipped to Canada?  It's difficult to find Huawei devices here.

**Comment by sjoudi** [comment]
Checked Amazon Canada but didn't see it.

I found it on Amazon US here:
[HUAWEI P50 Pro Global Model EU/UKVersion Dual SIM JAD-LX9 Factory Unlocked - International Version - Black](https://www.amazon.com/HUAWEI-UKVersion-JAD-LX9-Factory-Unlocked/dp/B09QT4YLPH/ref=sr_1_1?crid=25U5W9QD268SI&keywords=huawei+p50+pro&qid=1676985944&sprefix=huawei%2Caps%2C294&sr=8-1)

By the way, mine is P50 Pro which is same like this.

**Comment by ShaunBrassell** [comment]
Hi Chris

I have a number of clients here in South Africa using Huawei devices (e.g. P30) where the tracking is being put to sleep after around 10min of activity, so very keen to test. Am running your Capacitor version.

**Comment by christocracy** [comment]
> where the tracking is being put to sleep

Typical Huawei bullshit.  These are the worst devices.  I'm not sure if the behaviour will be any different.

Huawei's OS *purposely* does stuff like that.
