### ISSUE TITLE
Question/issue: Can I have a couple configurations of BackgroundGeolocation in one moment for different goals?

### ISSUE THREAD

**Issue by yaroslav13** [transistorsoft/flutter_background_geolocation#875]
@christocracy  Can I have a couple configurations of BackgroundGeolocation in one moment for different goals?

**Comment by christocracy** [comment]
You’re free to call .setConfig and change the Config in real-time, as desired.

**Comment by yaroslav13** [comment]
what if I need to create a couple of geofences that will be alive all time and don't depend on another algorithm in my app which also uses BackgroundGeolocation (change the config in real-time and change the way of tracking .start .startGeofences)?

**Comment by christocracy** [comment]
Why don’t you try it and see?

**Comment by yaroslav13** [comment]
What must I check? I don't see a way to have a couple of configs in one moment.

**Comment by christocracy** [comment]
See api docs “Geofencing Guide”

**Comment by yaroslav13** [comment]
Checked but still. For example, I have one algorithm for tracking location with some configurations (geofenceProximityRadius property for example). 

for example, 
```
return bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        geofenceInitialTriggerEntry: true,
        reset: true,
        preventSuspend: false,
        stationaryRadius: 25,
        debug: debug mode,
        geofenceModeHighAccuracy: true,
        geofenceProximityRadius: 1000000,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        stopOnStationary: false,
        allowIdenticalLocations: false,
        isMoving: false,
        enableHeadless: true,
        stopTimeout: 1,
        heartbeatInterval: 60,
        disableLocationAuthorizationAlert: true,
        backgroundPermissionRationale: bg.PermissionRationale(
          message: LocaleKeys.backgroundLocationPermissionMessage.tr(),
        ),
        notificationSmallIcon: _notificationIconProvider.iconPath,
        autoSync: true,
        autoSyncThreshold: 10,
        url: backupUrl,
        params: await createLocationExtraParam(),
        batchSync: true,
        maxBatchSize: 1000,
        disableStopDetection: false,
        pausesLocationUpdatesAutomatically: true,
        extras: <String, String>{'type': name});
  }
```

These algorithm use geofences. But I wanna create a couple of geofences with other bg.Config without effect on an algorithm that already exists. Because these geofences don't relate to the algorithm.  These geofences have other purposes. if I just call setConfig somewhere algorithm starts to use other geofenceProximityRadius, for example. or if I in algorithm call setConfig with other geofenceProximityRadius it will affect these separated geofences. Don't found in docs about this case.

**Comment by christocracy** [comment]
I don’t think you understand what geofenceProximityRadius is.  This is very unusual:  `1000000`.  I don’t think you know what you’re doing with that.

Android can only listen to 100 simultaneous geofences (iOS 20).

**Comment by yaroslav13** [comment]
It's a random value, just for example to clarify a goal why i need to have a couple of configs in parallel.

**Comment by christocracy** [comment]
Do you know what geofenceProximityRadius is?  It has nothing to do with a geofence event firing.

there’s no such thing as “parallel Config”.

**Comment by yaroslav13** [comment]
The radius around current location to query for geofences to activate monitoring upon.

**Comment by yaroslav13** [comment]
@christocracy Do you mean that distanceFilter and other don't affect on geofence tracking?

**Comment by yaroslav13** [comment]
Thanks
