### ISSUE TITLE
How we can get the callback either asked permission is allowed or deny?

### ISSUE THREAD

**Issue by iphonedev4radixweb** [transistorsoft/flutter_background_geolocation#876]
Flutter info (flutter doctor):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
• No issues found!

## Context
I want to check whether users allowed ’Always Location’ & ‘Motion Activity’ permission or not using your plugin as your plugin is asking for all permissions.

**Comment by christocracy** [comment]
See event onProviderChange.

the plugin doesn’t provide a way to determine any information on motion permission.  That permission is optional,  the plugin can operate without it.
