### ISSUE TITLE
BackgroundGeolocation.destroyLocation throw exception without any error message 

### ISSUE THREAD

**Issue by HammadBukhari** [transistorsoft/flutter_background_geolocation#878]
## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Android emulator
* Flutter info (`flutter doctor`):
* [✓] Flutter (Channel stable, 3.3.7, on
    macOS 13.0 22A380 darwin-arm, locale
    en-PK)
[✓] Android toolchain - develop for Android
    devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS
    (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    final state = await bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      logLevel: bg.Config.LOG_LEVEL_OFF,
      distanceFilter: 10,
      logMaxDays: 0,
      persistMode: bg.Config.PERSIST_MODE_ALL,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      preventSuspend: true,
      stopTimeout: 5,
      heartbeatInterval: 5 * 60,
      disableLocationAuthorizationAlert: true,
      debug: false,
      params: deviceParams,
    ));
```

## Steps to Reproduce

```dart
 bg.BackgroundGeolocation.locations.then((value) {
      try {
        final uuid = (value.first['uuid']);
        bg.BackgroundGeolocation.destroyLocation(uuid);
      } catch (e) {
        print(e);
      }
    });
```
Just sending the exact UUID from the plugin's location data to the destoryLocation results in PlatformException with no error message 
```dart
PlatformException(, , null, null)
```
## Context
When my app process the location data into useful information, it destroy that location data as it is no longer needed.

**Comment by christocracy** [comment]
I just tried your code.  I cannot reproduce your issue.  The error you receive can only mean you're trying to destroy a location that doesn't exist.  The error message is admittedly poor.

```dart
bg.BackgroundGeolocation.locations.then((value) async {
  try {
    final uuid = (value.first['uuid']);
    print("**** uuid: $uuid");
    await bg.BackgroundGeolocation.destroyLocation(uuid);
    print("*** [destroyLocation] SUCCESS");
  } catch (e) {
    print("Caught error: $e");
  }
});
```

I implemented that code in one of my UI buttons.  I load up my database with several records by calling `.getCurrentPosition()` then delete each each location by successively clicking my button.  One location is deleted with each press, until the database is empty.

```
11-10 10:39:41.009  7573  7611 I flutter : **** uuid: 81b43c18-34ec-4dec-abb0-d42b82164e3c
11-10 10:39:41.011  7573  8868 D TSLocationManager: [c.t.l.data.sqlite.b a]
11-10 10:39:41.011  7573  8868 D TSLocationManager:   ✅  DESTROY: 81b43c18-34ec-4dec-abb0-d42b82164e3c
11-10 10:39:41.018  7573  7611 I flutter : *** [destroyLocation] SUCCESS

11-10 10:43:02.650  7573  7611 I flutter : **** uuid: 3ee9a035-ee7d-4a83-bd10-f9d134bbe60c
11-10 10:43:02.652  7573  9333 D TSLocationManager: [c.t.l.data.sqlite.b a]
11-10 10:43:02.652  7573  9333 D TSLocationManager:   ✅  DESTROY: 3ee9a035-ee7d-4a83-bd10-f9d134bbe60c
11-10 10:43:02.655  7573  7611 I flutter : *** [destroyLocation] SUCCESS

11-10 10:43:07.470  7573  7611 I flutter : **** uuid: 242fe48c-ccbd-4fc4-9c8f-7d7fd9cf17ef
11-10 10:43:07.470  7573  9333 D TSLocationManager: [c.t.l.data.sqlite.b a]
11-10 10:43:07.470  7573  9333 D TSLocationManager:   ✅  DESTROY: 242fe48c-ccbd-4fc4-9c8f-7d7fd9cf17ef
11-10 10:43:07.472  7573  7611 I flutter : *** [destroyLocation] SUCCESS

11-10 10:43:11.111  7573  7611 I flutter : **** uuid: b09d849e-dad5-42eb-9903-9163d79e4355
11-10 10:43:11.113  7573  9333 D TSLocationManager: [c.t.l.data.sqlite.b a]
11-10 10:43:11.113  7573  9333 D TSLocationManager:   ✅  DESTROY: b09d849e-dad5-42eb-9903-9163d79e4355
11-10 10:43:11.118  7573  7611 I flutter : *** [destroyLocation] SUCCESS

11-10 10:43:14.141  7573  7611 I flutter : **** uuid: a1635a1c-53e9-41bc-acbf-b849ac733544
11-10 10:43:14.142  7573  9333 D TSLocationManager: [c.t.l.data.sqlite.b a]
11-10 10:43:14.142  7573  9333 D TSLocationManager:   ✅  DESTROY: a1635a1c-53e9-41bc-acbf-b849ac733544
11-10 10:43:14.143  7573  7611 I flutter : *** [destroyLocation] SUCCESS

```

**Comment by HammadBukhari** [comment]
I was using `await` for `destroyLocation` in actual use case. but, what I have identified is that the destroyed location is only throwing exception for the location points that were manually added using `insertLocation` function. That function is not well documented so maybe I'm using it incorrectly but what I'm doing is passing the `bg.Location.toMap()` function to `insertLocation`. 

> One thing to note, is I added `await` to my call to `.destroyLocation(uuid)`.
> 
> If you're executing your code within a loop (as a test), that would be responsible for your error, since the plugin's SDK methods execute _asynchronously_ (like sending an HTTP request to a server, you should wait for the response before sending another request).

**Comment by christocracy** [comment]
Why are you using `insertLocation`?

**Comment by HammadBukhari** [comment]
> Why are you using `insertLocation`?

We get location data externally too outside the app's GPS.

**Comment by christocracy** [comment]
From where?  Show me.
