### ISSUE TITLE
Feature Request - [Android only] Force the use of Android LocationManager instead of Google's FusedLocationProvider

### ISSUE THREAD

**Issue by sjoudi** [transistorsoft/flutter_background_geolocation#879]
I have ignored the template because this is a feature request.

**Use case:**
We want to limit location updates to GPS provider only in Android, by strictly depending on LocationManager which is the system location services, rather than the FusedLocationProvider.

**Challenge**
Currently, we can observe provider changes but we can't control which provider to use. Although we can choose the highest accuracy which usually invloves GPS provider, but these GPS location updates will come from FusedLocationProvider, not LocationManager, imposing the use of FusedLocationProvider.

**Proposal:**
With this feature, it would be possible to configure the plugin to do so through the Config, by for example:

```
 bg.BackgroundGeolocation.ready(bg.Config(
        ....
        forceAndroidLocationManager: true //This setting has no effect on iOS devices.
        ....
    ))
```
In this scenario, it is the responsibility of the developer to make sure the app consumes battery efficiently by configuring the plugin to get location updates less often.

**Comment by christocracy** [comment]
So you'd rather have no location when GPS is unavailable?  eg:  device indoors, travelling in subway, driving in tunnel.

I see no need for using `LocationManager` instead of `FusedLocationProvider`.

`FusedLocationProvider` is just an automatically grabs the best location available.  If the device is outdoors, the location will most likely come from GPS with an accuracy of `6-10` meters.

**Comment by sjoudi** [comment]
Thanks Chris.

Agree with that, but the point is `FusedLocationProvider` is part of `Google Mobile Services` which is nowadays not available for all Android devices (e.g. new `Huawei` phones).

If we need to use one plugin for the background location on all Android devices, the only solution to make it possible to configure the plugin to restrict location updates to `LocationManager`. Although this means the location update will be less often and consumes more power, it is much better than adding another solution on top of the plugin.

Unless you want to extend `Flutter Background Location` plugin to optionally use `FusedLocationService` which is part of `Huawei Mobile Services`.

**Comment by christocracy** [comment]
This plugin relies on play-services for more than just location updates.  It also requires the motion and geofencing apis.

**Comment by sjoudi** [comment]
Thanks Chris.

Then it would be great if you consider HMS in the future. It has fused location, motion detection, and geofencing API, and the API's are very much identical.

You can take a look on the Flutter APIs version on pub.dev [here](https://pub.dev/documentation/huawei_location/latest/huawei_location/huawei_location-library.html).

**Comment by christocracy** [comment]
Eventually, Huawei will release a post-processor to automatically convert Google GMS libs to HMS, just as [jetifier](https://developer.android.com/studio/command-line/jetifier) does for *Android X* conversion.

**Comment by christocracy** [comment]
>Then it would be great if you consider HMS in the future

I've been playing with the [Huawei Convertor](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/convertor-0000001050147221):  Huawei support is coming soon.

**Comment by Sardor-art** [comment]
> This plugin relies on play-services for more than just location updates. It also requires the motion and geofencing apis.

We have purchased a license to use this library on Android. But this library did not work as expected for us. The point is that the location has not changed during the tracking. Who should I ask to fix this error, and it is a similar error to the one we got when we used FusedLocation.

**Comment by christocracy** [comment]
>But this library did not work as expected for us

If you have a specific problem, post a new issue.  Also see https://dontkillmyapp.com
