### ISSUE TITLE
Document the com.google.android.gms.version requirement

### ISSUE THREAD

**Issue by artob** [transistorsoft/flutter_background_geolocation#88]
## Your Environment
* Plugin version: 1.0.10
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung Galaxy A7
* Flutter info (`flutter doctor`): N/A
* Plugin config: N/A

## Expected Behavior
Following the instructions in [docs/INSTALL-ANDROID.md](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md) should suffice to install the product in a Flutter app.

## Actual Behavior
The app crashes on startup, indicating an additional undocumented step is required:

    java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

## Steps to Reproduce
1. Create a new Flutter app
2. Install the plugin as per [docs/INSTALL-ANDROID.md](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md)
3. Execute `flutter run`

## Context
`flutter run` after following the instructions in [docs/INSTALL-ANDROID.md](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md)

## Debug logs
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
D/AndroidRuntime(12098): Shutting down VM
E/AndroidRuntime(12098): FATAL EXCEPTION: main
E/AndroidRuntime(12098): Process: com.example.helloworld, PID: 12098
E/AndroidRuntime(12098): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.helloworld/com.example.helloworld.MainActivity}: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
E/AndroidRuntime(12098): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
E/AndroidRuntime(12098): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
E/AndroidRuntime(12098): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(12098): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
E/AndroidRuntime(12098): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(12098): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(12098): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(12098): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12098): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(12098): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(12098): Caused by: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
E/AndroidRuntime(12098): 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:17)
E/AndroidRuntime(12098): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
E/AndroidRuntime(12098): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:94)
E/AndroidRuntime(12098): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:3)
E/AndroidRuntime(12098): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:93)
E/AndroidRuntime(12098): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:304)
E/AndroidRuntime(12098): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
E/AndroidRuntime(12098): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:17)
E/AndroidRuntime(12098): 	at com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin.<init>(FLTBackgroundGeolocationPlugin.java:108)
E/AndroidRuntime(12098): 	at com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin.registerWith(FLTBackgroundGeolocationPlugin.java:90)
E/AndroidRuntime(12098): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
E/AndroidRuntime(12098): 	at com.example.helloworld.MainActivity.onCreate(MainActivity.java:15)
E/AndroidRuntime(12098): 	at android.app.Activity.performCreate(Activity.java:7183)
E/AndroidRuntime(12098): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
E/AndroidRuntime(12098): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
E/AndroidRuntime(12098): 	... 9 more
```

</details>

**Comment by christocracy** [comment]
That tag is not a requirement for the plugin, it’s a [requirement when using Google Maps](https://stackoverflow.com/questions/21014222/a-required-meta-data-tag-in-your-apps-androidmanifest-xml-does-not-exist).

This plugin doesn’t require Google Maps.

I guess you’re using some google maps plugin?  If so, you should post this issue there.

**Comment by artob** [comment]
@christocracy No, I'm not using Google Maps. This is a brand new Flutter project without other relevant plugins. If you examine the stack trace, you'll be able to confirm that this issue is triggered from `com.transistorsoft.locationmanager.adapter.BackgroundGeolocation`.

**Comment by artob** [comment]
I should add also that this didn't use to happen back when I was using the 0.3.x release several months ago, with an otherwise identical stack.

**Comment by christocracy** [comment]
Show me the dependencies in your pub spec.yaml

Also show me:
- android/build.gradle
- android/app/build.gradle

**Comment by christocracy** [comment]
I have never used or even heard of this element in >5 years.  I will `flutter create` a new Hello World app and run through the setup.  I doubt this element is required for the plugin.

**Comment by christocracy** [comment]
With a fresh new Flutter app, following the published setup steps, the plugin successfully requests location permission and boots into the stationary state.

```
$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (3 available)
```
