### ISSUE TITLE
Android App crash without error in android version 8.1.0

### ISSUE THREAD

**Issue by harshitwe360** [transistorsoft/flutter_background_geolocation#881]
Hi, I am new in flutter and want to create an app with background geolocation, I have downloaded the code and run the example. App just load and get crash.

## Device Environment
* Plugin version: 
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Samsung SM-G610F
* Plugin config: Example code

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```dart <-- Issue print in console -->
Build fingerprint: 'samsung/on7xeltedd/on7xelte:8.1.0/M1AJQ/G610FDDS1CTE6:user/release-keys'
Revision: '3'
ABI: 'arm'
pid: 23093, tid: 23093, name: locationexample  >>> com.transistorsoft.flutterbackgroundgeolocationexample <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
**Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1265)] Check failed: fml::jni::CheckException(env). 
'
    r0 00000000  r1 00005a35  r2 00000006  r3 00000008
    r4 00005a35  r5 00005a35  r6 ff93d26c  r7 0000010c
    r8 00000000  r9 ff93d380  sl 00000031  fp e73bbd90
    ip ea26992d  sp ff93d258  lr e93e7e6f  pc e93e1528  cpsr 20070030
backtrace:
    #00 pc 0001a528  /system/lib/libc.so (abort+63)
    #01 pc 00000cfb  /data/app/com.transistorsoft.flutterbackgroundgeolocationexample-qTyDJ5UN9tpaiA_EWwCF0A==/lib/arm/libflutter.so (offset 0x12c5000)**


## ######################
I have tried in new version devices of android, it work fine..

Thanks in advance for support.

**Comment by christocracy** [comment]
> * Plugin Version: 
> * Flutter info (`flutter doctor`):

**Comment by harshitwe360** [comment]
Flutter info (flutter doctor):

Doctor summary (to see all details, run flutter doctor -v):

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19045.2130], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability


Plugin Version:  flutter_background_geolocation: ^4.8.3

**Comment by harshitwe360** [comment]
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19045.2130], locale en-IN)
    • Flutter version 3.0.5 at C:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by harshitwe360** [comment]
Still the same issue..

**Comment by christocracy** [comment]
I suggest you generate a simple *HelloWorld* app and attempt to reproduce in a freshly generated flutter app.
