### ISSUE TITLE
Possible to use iOS only?

### ISSUE THREAD

**Issue by typexy** [transistorsoft/flutter_background_geolocation#886]
## Your Environment
* Plugin version: ^4.6.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google Pixel 6
* Flutter info (`flutter doctor`): everthing's fine
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
```

## Expected Behavior
When android app starts - without initializing this plugin - do not show a toast with missing license key in release mode.

## Actual Behavior
When android app starts - without initializing this plugin - a toast is shown with missing license key in release mode.

## Steps to Reproduce

1. youre example can be used.

## Context
Use plugin on iOS only without toast of missing license key in android app - when plugin is not used. (in release mode)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Why should you want to use the plugin with iOS only?

**Comment by typexy** [comment]
Due to business logic only. I only need background location in iOs because the I intend to do is possible with ble on android with a foreground service, were I don't need to use the location on a regular basis.

**Comment by christocracy** [comment]
No, it’s not possible.
