### ISSUE TITLE
Apple store reject becase UIBackgroundModes

### ISSUE THREAD

**Issue by numairunumao** [transistorsoft/flutter_background_geolocation#887]
Hello, 
I created an application about sending the driver's location but I got rejected from an apple review because of UIBackgroundModes. I gave reasons but it was rejected twice.
Can you help me?

<img width="1261" alt="Screenshot 2565-11-22 at 23 25 57" src="https://user-images.githubusercontent.com/10969957/203376791-5f7052fa-e9aa-44b3-962a-ef81c6066c6e.png">

**Comment by christocracy** [comment]
That’s means that Apple doesn’t feel that your app deserves to have the [*Background Mode [Location]*](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md#using-xcode) checkbox to be enabled.

If you can’t convince Apple that your app deserves *[x] Location Updates* checked, then you must disable it and configure `Config.useSignificantChangesOnly` (see the api docs).  Your app will receive a location only about every 1000 meters.

**Comment by numairunumao** [comment]
> That’s means that Apple doesn’t feel that your app deserves to have the [_Background Mode [x] Location_](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-IOS.md#using-xcode) checkbox to be enabled.
> 
> If you can’t convince Apple that your app deserves _[x] Location_ Background Mode checked, then you must disable it and configure `Config.useSignificantChangesOnly` (see the api docs). Your app will receive a location only about every 1000 meters.

That means if I set useSignificantChangesOnly: true, ios will still work in a headless mode but I will receive a location only about every 1000 meters right?

**Comment by christocracy** [comment]
> ios will still work in a headless mode

Headless mode is an Android concept.

**Comment by christocracy** [comment]
Yes.  This is easily verified in the iOS simulator with *Freeway Drive*

**Comment by numairunumao** [comment]
> Yes. This is easily verified in the iOS simulator with _Freeway Drive_

Thank you
