### ISSUE TITLE
New phone, location bounces around

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#889]
I got a new Pixel 7, and the location accuracy is, frankly, terrible. It often does not track closely to the road I am on and jumps wildly when I stop. I have checked all the settings for GPS accuracy, and everything appears to be set correctly. The same app behaved normally on my Pixel 3.

The odd thing is that your sample app continues to work great, so I cannot really fault the phone. 

Any idea what might be going on? Could you share the plugin configuration you use for your sample app?

## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.15)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 bg.Config _getBgConfig(bool moving) {
    var localize = GlobalContext().localize;
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: 60 * 24 * 5,
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

</details>

![Screenshot_20221125-162719](https://user-images.githubusercontent.com/8699636/204060252-0f68e978-706c-4204-9544-1229c877a706.png)

**Comment by christocracy** [comment]
The only option that matters is desiredAccuracy.  Most plugin options are related to http/persistence which doesn’t affect accuracy.

i suggest you reboot your device.

**Comment by christocracy** [comment]
You’ve posted a small snapshot of data.  I suggest you go for a nice long ride (Eg 5k)

**Comment by ozzy1873** [comment]
I have rebooted my device multiple times to no avail. That screenshot was at near the end of a 5 mile drive. I'll try reinstalling the app.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by christocracy** [comment]
> end of a 5 mile drive. I'll try reinstalling the app.

Why not show the whole trip then?

**Comment by ozzy1873** [comment]
I'll run another test in the morning and post the entire trip.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ozzy1873** [comment]
I ran a couple more tests and captured some more screenshots. This time I saw some of the same behavior with your sample app. This jumping/bouncing behavior appears to happen most often when moving between 3 and 10 mph, or with stop/start traffic. I travelled the same route twice at approximately the same speeds, once with my app and once with the sample app. It seems to be worse with my app than the sample app. On this trip, the bad behavior happened mostly in an area with buildings that could affect the GPS, but on previous trips this has happened in more open spaces.

![Screenshot_20221126-135402](https://user-images.githubusercontent.com/8699636/204107320-f9a4158f-1076-4a0b-8e67-0a07d24ce8a9.png)
![Screenshot_20221126-135331](https://user-images.githubusercontent.com/8699636/204107331-1501a192-71c4-4cf5-8144-2decf34a9a1a.png)
![Screenshot_20221126-134029](https://user-images.githubusercontent.com/8699636/204107352-aea22dd4-3584-49d7-b8e0-5da57e104f94.png)
![Screenshot_20221126-133951](https://user-images.githubusercontent.com/8699636/204107362-5db3facc-6555-4f4d-986c-49490530d11d.png)
![Screenshot_20221126-133906](https://user-images.gith
![Screenshot_20221126-134009](https://user-images.githubusercontent.com/8699636/204107396-527ccd00-5252-4f4a-9c3e-220ffa7143c7.png)
ubusercontent.com/8699636/204107364-67606376-6a27-4b30-a7dd-67687562dd53.png)

**Comment by christocracy** [comment]
There’s nothing the plugin can do to cure poor behaviour of some particular device.

**Comment by ozzy1873** [comment]
Ok, so it appears to you too that there is something wrong with the device. FWIW, I can run the same app on an old Samsung S8 without a SIM card and the performance is much better. I don't know if I should wait for an update from Google or exchange the phone. Boo :(

**Comment by ozzy1873** [comment]
I finally resolved this. The "Google Location Accuracy" setting was initially ON when I got the phone and was experiencing this problem. With nothing left to try, I finally toggled that setting OFF, then back ON. Now everything works normally.

I'm going to close this.
