### ISSUE TITLE
Background services are not invoking automatically

### ISSUE THREAD

**Issue by krishnaji-yedlapalli** [transistorsoft/flutter_background_geolocation#890]
We configured the background geolocation plugin as per the documentation, but a few of our customers facing issues with tracking, while he is travelling background services are automatically stopping and not at all invoking,  so due to this reason it is not recording the locations at all, attached a log of one of my customers kindly check for date 30-Nov.

## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model:  vivo 1807
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```
 var state = await bg.BackgroundGeolocation.ready(bg.Config(
          reset: true,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          disableStopDetection: true,
          url: "${pluginService.getBaseUrl}${Urls.UPDATED_LOCATION_TRACKER}",
          headers: {"Authorization": 'Bearer ${pluginService.token}'},
          extras: {
            'contactId': commonService.id,
            'companyId': commonService.companyId,
            'deviceId': deviceId
          },
          httpRootProperty: 'trackInfo',
          batchSync: true,
          autoSyncThreshold: 30,
          stopOnTerminate: false,
          forceReloadOnBoot: true,
          forceReloadOnGeofence: true,
          forceReloadOnHeartbeat: true,
          forceReloadOnLocationChange: true,
          forceReloadOnMotionChange: true,
          forceReloadOnSchedule: true,
          httpTimeout: 240000,
          pausesLocationUpdatesAutomatically: false,
          desiredOdometerAccuracy: 10,
          stopTimeout: 10,
          heartbeatInterval: 1800,
          geofenceInitialTriggerEntry: true,
          schedule: [schedulerDate],
          scheduleUseAlarmManager: true,
          startOnBoot: true,
          geofenceModeHighAccuracy: true,
          enableHeadless: true));
```

## Expected Behavior
Background services need to be enabled for all the time

## Debug logs
Attached Android Logs for reference

![service image](https://user-images.githubusercontent.com/49545948/204961254-01753b51-05ff-4d1f-98f4-64a873a5c090.png)

[background-geolocation (1) (1).log](https://github.com/transistorsoft/flutter_background_geolocation/files/10129070/background-geolocation.1.1.log)

**Comment by christocracy** [comment]
Is there a specific range of timestamps (start/end) that you're interested in from your logs?

**Comment by christocracy** [comment]
For issues with particular devices, see https://dontkillmyapp.com

**Comment by krishnaji-yedlapalli** [comment]
> schedulerDate

yes, User manually initiates the tracker in the morning, it will be considered as the start date, and the end time will be 11:30 for that day as shown  "2022-11-29-09:32 2022-11-29-23:30"

**Comment by adirgan** [comment]
hi @krishnaji-yedlapalli is Alejandro of Promaster, I really don't understand why they use that configuration, there are many things that cause the functionality to break.

Please use the following configuration.

`var state = await bg.BackgroundGeolocation.ready(bg.Config(
  reset: true,
  logLevel: bg.Config.LOG_LEVEL_VERBOSE,
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20.0,
  elasticityMultiplier: 2,
  motionTriggerDelay: 10000,
  stopAfterElapsedMinutes: -1,
  stationaryRadius: 25,
  activityType: bg.Config.ACTIVITY_TYPE_OTHER,
  url: "${pluginService.getBaseUrl}${Urls.UPDATED_LOCATION_TRACKER}",
  headers: {"Authorization": 'Bearer ${pluginService.token}'},
  extras: {
    'contactId': commonService.id,
    'companyId': commonService.companyId,
    'deviceId': deviceId
  },
  httpRootProperty: 'trackInfo',
  batchSync: true,
  autoSyncThreshold: 30,
  stopOnTerminate: false,
  httpTimeout: 240000,
  desiredOdometerAccuracy: 100,
  stopTimeout: 5,
  heartbeatInterval: 60,
  startOnBoot: true,
  enableHeadless: true));`
