### ISSUE TITLE
Sometimes Location.Battery.level returns -1

### ISSUE THREAD

**Issue by komineyuki** [transistorsoft/flutter_background_geolocation#893]
I'm trying to get battery level and physical speed in background and headless.
But sometimes those numbers can be -1.

```
bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);

void headlessTask(bg.HeadlessEvent headlessEvent) async {
    var location = headlessEvent.event as bg.Location;
    print(location.battery.level.toString());
    print(location.coords.speed.toString());

    ....
}
```

Also, the user's current location (location.coords.latitude and location.coords.longitude) is retrieved correctly.
This bug is rare and random.

Also It seems to occur more often on iPhone devices than on Android devices.

[API reference](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Battery/level.html) says,  this property won't be -1 so do you think I am accidentally overwriting the value?

**Comment by christocracy** [comment]
Your HeadlessTask is going to cause an infinite loop calling .getCurrentPosition like that.

**Comment by christocracy** [comment]
Calling .getCurrentPosition() begets headless  `location` events begets `location` events begets `location` events, into infinity.

you need to wrap your headless .getCurrentPosition() call within logic to only execute for a particular headless event (Eg `terminate`, `heartbeat`.

**Comment by komineyuki** [comment]
Thank you. Sorry for late comment. I was looking for other reasons.
Is this relate to `location.activity.type` is sometimes `"unknown"` by `BackgroundGeolocation.onLocation((bg.Location location))` on iPhone? I can't find why this String returns "unknown". This is not `headless`.

**Comment by christocracy** [comment]
> location.activity.type is sometimes "unknown"
> Sometimes Location.Battery.level returns -1

This issue is related to battery level.
