### ISSUE TITLE
Get background location ping at higher frequency

### ISSUE THREAD

**Issue by kunatastic** [transistorsoft/flutter_background_geolocation#895]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 12
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  BackgroundFetchConfig(
          minimumFetchInterval: 1, // This is set to 1 minutes
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ),
```

## Expected Behavior
I wish to get the background location ping every 15-20 seconds

## Actual Behavior
Currently all I can see is the minimum fetch interval is 60 seconds. 

## Context

I want to get the location in background at higher frequency (4-5 pings every minute). So is there any good way to get the location's in background with greater frequency. Or I can think of a hack where I get as many location pings I want every seconds by adding appropriate timeout in the headless callback.

**Comment by christocracy** [comment]
Android BackgroundFetch will *never* fire faster than 1min.

**Comment by christocracy** [comment]
> forceAlarmManager: false

And to get it to fire once/min, you need forceAlarmManager: true

**Comment by kunatastic** [comment]
Just curious, why does this plugin doesn't support higher pings. Is it due to Android resources bottleneck or some plugin related limitations

**Comment by christocracy** [comment]
BackgroundFetch doesn’t operate faster due to Android limitation.

btw, background_geolocation itself can track up to once/second when the device is detected to be moving.

you can also call BackgroundGeolocation.changePace(true) to manually put it into the *moving* state.  Read the wiki *Philosophy of Operation* for more info on that.

**Comment by christocracy** [comment]
Also, for questions specific to BackgroundFetch, you should post issues in its GitHub repo.  

This is the background_geolocation repo.  They are two completely separate plugins.
