### ISSUE TITLE
Misbehaving of package

### ISSUE THREAD

**Issue by sushrutnaik** [transistorsoft/flutter_background_geolocation#898]
Misbehaving of package

## Your Environment
* Plugin version:4.7.1
* Platform: Android
* OS version:9
* Device manufacturer / model:moto 
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
bg.BackgroundGeolocation.onLocation(( location) async {
    //    if(SharedPrefs().getIsLoggedIn()==true){
         
    //   await Future.delayed(Duration(seconds: 5));
    //    controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

    //    }
    //   print('[location] - $location');

    // });

    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    // bg.BackgroundGeolocation.onMotionChange((location) async {
    //   if(SharedPrefs().getIsLoggedIn()==true){
    //     await Future.delayed(Duration(seconds: 5));
    //   controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

    //    }
    //   print('[motionchange] - $location');
    // });

    // // Fired whenever the state of location-services changes.  Always fired at boot
    // bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
    //   print('[providerchange] - $event');
    // });

    ////
    // 2.  Configure the plugin
    //
    // bg.BackgroundGeolocation.ready(bg.Config(
    //     desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    //     distanceFilter: 10.0,
    //     stopOnTerminate: false,
    //     startOnBoot: true,
    //     debug: true,
        
    //     locationUpdateInterval: 60000,
    //     fastestLocationUpdateInterval: 30000,
    //     logLevel: bg.Config.LOG_LEVEL_VERBOSE
    // )).then((bg.State state) {
    //   if (!state.enabled) {
    //     ////
    //     // 3.  Start the plugin.
    //     //
    //     bg.BackgroundGeolocation.start();
    //   }
    // });
## Expected Behavior

Location should be sent if user logged in 
## Actual Behavior

1)Even when there was moment or motion location was not updating.
2)Sometime if there was no motion or location change it was updating. 
3)To test we travelled for around 4miles initially for few minutes location was updating then it suddenly stopped 
4)It sends location only once when app boots and after that it won't send even if there is motion or location change

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It’s not the plugin “misbehaving”, it’s likely your device misbehaving.

- see wiki *Debugging* and learn the fetch logs from the plug-in’s database.
- See https://dontkillmyapp.com

**Comment by sushrutnaik** [comment]
We checked on multiple device all the devices are behaving the same.Even when we restarted the app the plugin is still not sending the location

**Comment by christocracy** [comment]
I suggest you have a look at the plug-in’s logs.  See wiki *Debugging*.

I also suggest you test the /example in this repo.

I regularly field test upon the following devices:
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Google Pixel 6 @ 13
- Samsung Galaxy S20 FE @ 13
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by christocracy** [comment]
See wiki “Debugging” and fetch the plugin logs with .emailLog method

**Comment by sushrutnaik** [comment]
RROR: Failed to get callback id: Check whetever the callback is a op-level or static function
D/TSLocationManager(27161): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [debug, desiredAccuracy, enableHeadless, extras, fastestLocationUpdateInterval, headers, headlessJobService, heartbeatInterval, isMoving, locationUpdateInterval, logLevel, params, schedule, startOnBoot, stopOnTerminate]
E/TSLocationManager(27161):   ‼️  Invalid Headless Callback ids.  Cannot handle headless event
E/TSLocationManager(27161): [c.t.f.b.HeadlessTask$TaskRunner run]
D/TSLocationManager(27161): [c.t.f.b.HeadlessTask onHeadlessEvent] 💀 [HeadlessTask terminate]
D/TSLocationManager(27161): ║ ☯️  HeadlessMode? true
E/TSLocationManager(27161):   ‼️ 


I am getting this error and when app is killed from background location is not updating can you tell me why?

**Comment by christocracy** [comment]
-  $ flutter doctor
- Post your lib/main.dart

**Comment by sushrutnaik** [comment]
@pragma('vm:entry-point')
// void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
//   print('📬 --> $headlessEvent');

//   switch (headlessEvent.name) {
//     case bg.Event.BOOT:
//       bg.State state = await bg.BackgroundGeolocation.state;
//       print("📬 didDeviceReboot: ${state.didDeviceReboot}");
//       break;
//     case bg.Event.TERMINATE:
//       try {

//         bg.Location location =
//             await bg.BackgroundGeolocation.getCurrentPosition(
//                 samples: 1,
//                 extras: {
//                   "event": "terminate",
//                   "headless": true
//                 }
//             );
//                        controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//         print("[getCurrentPosition] Headless: $location");
//       } catch (error) {
//         print("[getCurrentPosition] Headless ERROR: $error");
//       }

//       break;
//     case bg.Event.HEARTBEAT:

     
//       try {
//         bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(
//           samples: 1,
//           extras: {
//             "event": "heartbeat",
//             "headless": true
//           }
//         );
//         print('[getCurrentPosition] Headless: $location');
//                                controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//       } catch (error) {
//         print('[getCurrentPosition] Headless ERROR: $error');
//       }
      
//       break;
//     case bg.Event.LOCATION:
//       bg.Location location = headlessEvent.event;
//       print(location);
//              controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//       break;
//     case bg.Event.MOTIONCHANGE:
//       bg.Location location = headlessEvent.event;
//       print(location);
//              controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//       break;
//     case bg.Event.GEOFENCE:
//       bg.GeofenceEvent geofenceEvent = headlessEvent.event;
//       print(geofenceEvent);
//       break;
//     case bg.Event.GEOFENCESCHANGE:
//       bg.GeofencesChangeEvent event = headlessEvent.event;
//       print(event);
//       break;
//     case bg.Event.SCHEDULE:
//       bg.State state = headlessEvent.event;
//       print(state);
//       break;
//     case bg.Event.ACTIVITYCHANGE:
//       bg.ActivityChangeEvent event = headlessEvent.event;
//       print(event);
//       break;
//     case bg.Event.HTTP:
//       bg.HttpEvent response = headlessEvent.event;
//       print(response);
//       break;
//     case bg.Event.POWERSAVECHANGE:
//       bool enabled = headlessEvent.event;
//       print(enabled);
//       break;
//     case bg.Event.CONNECTIVITYCHANGE:
//       bg.ConnectivityChangeEvent event = headlessEvent.event;
//       print(event);
//       break;
//     case bg.Event.ENABLEDCHANGE:
//       bool enabled = headlessEvent.event;
//       print(enabled);
//       break;
   
//   }
// }

// /// Receive events from BackgroundFetch in Headless state.
// @pragma('vm:entry-point')
// void backgroundFetchHeadlessTask(HeadlessTask task) async {
//   String taskId = task.taskId;

//   // Is this a background_fetch timeout event?  If so, simply #finish and bail-out.
//   if (task.timeout) {
//     print("[BackgroundFetch] HeadlessTask TIMEOUT: $taskId");
//     BackgroundFetch.finish(taskId);
//     return;
//   }

//   print("[BackgroundFetch] HeadlessTask: $taskId");

//   try {
//     var location = await bg.BackgroundGeolocation.getCurrentPosition(
//         samples: 1,
//         extras: {
//           "event": "background-fetch",
//           "headless": true
//         }
//     );
//     print("[location] $location");
//            controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//   } catch(error) {
//     print("[location] ERROR: $error");
//   }


//   BackgroundFetch.finish(taskId);
// }
// //     location.enableBackgroundMode(enable: true);
// //     location.changeSettings(
// //         interval: 6000,
// //         distanceFilter: 3000
// //     );
// //     Timer? locationUpdateTimer;

// //     locationUpdateTimer = Timer.periodic(const Duration(seconds: 6), (Timer t) {
// //         location.onLocationChanged.listen((LocationData currentLocation) async {
// //   // Use current location
// //   if(SharedPrefs().getIsLoggedIn()==true){
         
// //       // await Future.delayed(Duration(seconds: 5));
// //        controller.sendLocation(userController.user.value!.vehicleId!, currentLocation.latitude!, currentLocation.longitude!);

// //        }
// // });
// //     });
//  bg.BackgroundGeolocation.onLocation(( location) async {
//        if(SharedPrefs().getIsLoggedIn()==true){
         
//       await Future.delayed(Duration(seconds: 5));
//        controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//        }
//       print('[location] - $location');

//     });

//    // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
//     bg.BackgroundGeolocation.onMotionChange((location) async {
//       if(SharedPrefs().getIsLoggedIn()==true){
//         await Future.delayed(Duration(seconds: 5));
//       controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

//        }
//       print('[motionchange] - $location');
//     });

//     // Fired whenever the state of location-services changes.  Always fired at boot
//     bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
//       print('[providerchange] - $event');
//     });
// bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
//   print('- heartbeat event received');
// });
//     //
//    // 2.  Configure the plugin
    
//     bg.BackgroundGeolocation.ready(bg.Config(
//         desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
//         distanceFilter: 10.0,
//         stopOnTerminate: false,
//         startOnBoot: true,
//         debug: true,
//         heartbeatInterval: 60000,
//         locationUpdateInterval: 60000,
//         fastestLocationUpdateInterval: 30000,
//         enableHeadless: true,
//         logLevel: bg.Config.LOG_LEVEL_VERBOSE
        
//     )).then((bg.State state) {
//       if (!state.enabled) {
//         //
//         //3.  Start the plugin.
        
//         bg.BackgroundGeolocation.start();
//       }
//     });
//     bg.BackgroundGeolocation.registerHeadlessTask(
//       backgroundGeolocationHeadlessTask);

//   /// Register BackgroundFetch headless-task.
//   BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  
//   }


This code is written in init() function

**Comment by christocracy** [comment]
Please learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).  Edit your post

**Comment by sushrutnaik** [comment]
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      try {

        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1,
                extras: {
                  "event": "terminate",
                  "headless": true
                }
            );
//sending location to cloud 
          controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }

      break;
    case bg.Event.HEARTBEAT:
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(
          samples: 1,
          extras: {
            "event": "heartbeat",
            "headless": true
          }
        );
        print('[getCurrentPosition] Headless: $location');
//sending location to cloud 
         controller.sendLocation(userController.user.value!.vehicleId!,location.coords.latitude,location.coords.longitude);

      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
//sending location to cloud 
controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
//sending location to cloud 
controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
   
  }
}

/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;

  // Is this a background_fetch timeout event?  If so, simply #finish and bail-out.
  if (task.timeout) {
    print("[BackgroundFetch] HeadlessTask TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] HeadlessTask: $taskId");

  try {
    var location = await bg.BackgroundGeolocation.getCurrentPosition(
        samples: 1,
        extras: {
          "event": "background-fetch",
          "headless": true
        }
    );
    print("[location] $location");
//sending location to cloud 
    controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

  } catch(error) {
    print("[location] ERROR: $error");
  }


  BackgroundFetch.finish(taskId);
}
 bg.BackgroundGeolocation.onLocation(( location) async {
//sending location to cloud 
       if(SharedPrefs().getIsLoggedIn()==true){
         
      await Future.delayed(Duration(seconds: 5)); 
       controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

       }
      print('[location] - $location');

    });

   // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((location) async {
//sending location to cloud 
      if(SharedPrefs().getIsLoggedIn()==true){
        await Future.delayed(Duration(seconds: 5));
      controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

       }
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
  print('- heartbeat event received');
});
    //
   // 2.  Configure the plugin
    
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        heartbeatInterval: 60000,
        locationUpdateInterval: 60000,
        fastestLocationUpdateInterval: 30000,
        enableHeadless: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
        
    )).then((bg.State state) {
      if (!state.enabled) {
        //
        //3.  Start the plugin.
        
        bg.BackgroundGeolocation.start();
      }
    });
    bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);

  /// Register BackgroundFetch headless-task.
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  
  }

this is written in init() function

**Comment by sushrutnaik** [comment]
```` 
   @pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      try {

        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1,
                extras: {
                  "event": "terminate",
                  "headless": true
                }
            );
//sending location to cloud 
          controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }

      break;
    case bg.Event.HEARTBEAT:
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(
          samples: 1,
          extras: {
            "event": "heartbeat",
            "headless": true
          }
        );
        print('[getCurrentPosition] Headless: $location');
//sending location to cloud 
         controller.sendLocation(userController.user.value!.vehicleId!,location.coords.latitude,location.coords.longitude);

      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
//sending location to cloud 
controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
//sending location to cloud 
controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
   
  }
}

/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;

  // Is this a background_fetch timeout event?  If so, simply #finish and bail-out.
  if (task.timeout) {
    print("[BackgroundFetch] HeadlessTask TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] HeadlessTask: $taskId");

  try {
    var location = await bg.BackgroundGeolocation.getCurrentPosition(
        samples: 1,
        extras: {
          "event": "background-fetch",
          "headless": true
        }
    );
    print("[location] $location");
//sending location to cloud 
    controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

  } catch(error) {
    print("[location] ERROR: $error");
  }


  BackgroundFetch.finish(taskId);
}
 bg.BackgroundGeolocation.onLocation(( location) async {
//sending location to cloud 
       if(SharedPrefs().getIsLoggedIn()==true){
         
      await Future.delayed(Duration(seconds: 5)); 
       controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

       }
      print('[location] - $location');

    });

   // Fired whenever the plugin changes motion-state (stationary->moving and vice-versa)
    bg.BackgroundGeolocation.onMotionChange((location) async {
//sending location to cloud 
      if(SharedPrefs().getIsLoggedIn()==true){
        await Future.delayed(Duration(seconds: 5));
      controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);

       }
      print('[motionchange] - $location');
    });

    // Fired whenever the state of location-services changes.  Always fired at boot
    bg.BackgroundGeolocation.onProviderChange((bg.ProviderChangeEvent event) {
      print('[providerchange] - $event');
    });
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
  print('- heartbeat event received');
});
    //
   // 2.  Configure the plugin
    
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        heartbeatInterval: 60000,
        locationUpdateInterval: 60000,
        fastestLocationUpdateInterval: 30000,
        enableHeadless: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE
        
    )).then((bg.State state) {
      if (!state.enabled) {
        //
        //3.  Start the plugin.
        
        bg.BackgroundGeolocation.start();
      }
    });
    bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);

  /// Register BackgroundFetch headless-task.
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  
  }
````
This code is written in init() function

**Comment by christocracy** [comment]
You are implementing the plugin completely wrong

the only thing that belongs in main.dart are the headless tasks.

everything else belongs in your App component (widgets).

please go review the example in the readme.

**Comment by sushrutnaik** [comment]
D/TSLocationManager(18023): [c.t.l.l.LifecycleManager onStart] ☯️  onStart
V/FA      (18023): Activity resumed, time: 2528821317
I/TSLocationManager(18023): [c.t.l.s.TSScheduleManager cancelOneShot]
I/TSLocationManager(18023):   ⏰ Cancel OneShot: TERMINATE_EVENT
D/TSLocationManager(18023): [c.t.l.l.LifecycleManager onResume] ☯️  onResume
V/FA      (18023): Connecting to remote service
D/FA      (18023): Connected to remote service
V/FA      (18023): Processing queued up service tasks: 1
V/FA      (18023): Inactivity, disconnecting from the service


I am getting this error on app background and location is not updating

**Comment by christocracy** [comment]
What is it you *think* is an error?  There is no error in the logs you posted.

**Comment by sushrutnaik** [comment]
I/TSLocationManager(21740): [c.t.l.s.TSScheduleManager oneShot]
I/TSLocationManager(21740):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
V/FA      (21740): Activity paused, time: 2529223657
D/TSLocationManager(21740): [c.t.l.l.LifecycleManager onPause] ☯️  onPause
D/TSLocationManager(21740): [c.t.l.l.LifecycleManager onStop] ☯️  onStop
2
W/Settings(21740): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/FA      (21740): Application going to the background
2
W/Settings(21740): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
V/FA      (21740): Inactivity, disconnecting from the service
2
W/Settings(21740): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/TSLocationManager(21740): [c.t.l.scheduler.ScheduleEvent onOneShot]
I/TSLocationManager(21740): ╔═════════════════════════════════════════════
I/TSLocationManager(21740): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(21740): ╠═════════════════════════════════════════════
D/TSLocationManager(21740): [c.t.l.event.TerminateEvent$a a]
D/TSLocationManager(21740):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
4
W/Settings(21740): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.

When this happens there is no update in location happening even when there is change in location 
Please let me what may be issue if it is there

**Comment by christocracy** [comment]
There is nothing unusual about the plugin logs you post.

**Comment by sushrutnaik** [comment]
Then even after there is change in location nothing is getting triggered is it something expected ?

**Comment by christocracy** [comment]
I suggest you test the /example app in the repo on a real device, outside with real movement.

**Comment by sushrutnaik** [comment]
/// Receive events from BackgroundGeolocation in Headless state.
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }
      break;
    case bg.Event.HEARTBEAT:
      /* DISABLED getCurrentPosition on heartbeat
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      */
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      bg.BackgroundGeolocation.setConfig(
          bg.Config(url: "${ENV.TRACKER_HOST}/api/locations"));
      break;
  }
}


How are you sending location from headless state to the cloud ?

**Comment by christocracy** [comment]
See api docs “HTTP Guide”

**Comment by sushrutnaik** [comment]
Will heartbeat fetch location and send if app is killed from background?
