### ISSUE TITLE
Suspend location logging

### ISSUE THREAD

**Issue by magnatronus** [transistorsoft/flutter_background_geolocation#9]
Not really an issue more of a feature request. It would be great if there were a 

   bg.BackgroundGeolocation.suspend()

or similar, just to stop logging of locations  temporarily. 

I have not found a way to do this except to turn the except with 

   bg.BackgroundGeolocation.start()

and 

   bg.BackgroundGeolocation.stop()

I am using the plugin in a walk tracking app and want to allow the user to suspend location logging temporarily when, for instance, they stop their journey to do something. I still want to map their current location (and display it) but do not want it recorded in the list of locations.

**Comment by christocracy** [comment]
If the user explicitly clicked a [Suspend] button, why would they have the expectation to keep showing their location on the map, even in the background.

If in the *foreground*, you're free to execute `#getCurrentPosition` or `#watchPosition` at any time (after calling `#stop`).

**Comment by magnatronus** [comment]
I was 'worried' about a few points, which may not be relevant, so maybe a simple use case might explain.

A user wants to track a walk they are doing, but half way round they stop for a drink. I want to track the complete walk, but not record their movements during their drink break as they maybe wandering around.

So I guess my question related to the .start() . and .stop() - is it fine to just do a .stop() then a .start() again ?  My worry was that the .stop() disconnected from GPS monitoring and after .start() there would be a lag in re-establishing tracking/position and by that time they may have walked on. Therefore it might be easier to just not record location while suspended and leave background location running.

**Comment by magnatronus** [comment]
OK that's great - thank you.
