### ISSUE TITLE
receiving records while device is still in the same place

### ISSUE THREAD

**Issue by AbdrahmanKafo96** [transistorsoft/flutter_background_geolocation#901]
## Your Environment
* Plugin version:4.8.5
* Platform: iOS or Android
* OS version:Android
* Device manufacturer / model:Xiaomi MI A2
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```bg.BackgroundGeolocation.ready(bg.Config(
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10,
          //    disableElasticity: true, we will check this line...
              isMoving: true,
             // elasticityMultiplier: 10,
              allowIdenticalLocations:false,
              forceReloadOnGeofence: true,
              forceReloadOnSchedule: true,
              stopOnTerminate: false,
              method: 'post',
              foregroundService: true,
              httpRootProperty: '.',
              enableHeadless: true,
              locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"time":"<%= timestamp %>",speed:<%= speed %>}',
              url: 'http://ettsq.ly/api/update_position',
              headers: {
                'Accept': 'application/json',
                'Authorization': 'Bearer $token',
                'content-type': 'application/json',
              },
              params: {
                'sender_id': UserInfo.get('user_id'),
                'beneficiarie_id': int.parse(UserInfo.get('beneficiarie_id')),
               
              },
              autoSync: true,
              //batchSync: true,
            maxDaysToPersist: 1,
              startOnBoot: true,
              forceReloadOnBoot: true,
              stopTimeout: 5,
              //  stationaryRadius: ,
              debug: true,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              reset: true))
          .then((bg.State state) {
        setState(() {
          _enabled = state.enabled;
          //  _isMoving = state.isMoving;
        });
      });

## Expected Behavior
<!--- Tell us what should happen -->
It is expected that it sends the user's location for the first time, then waits for the user to move and automatically starts sending the user's location, but what happens is that he sends the user's location while he is in the same place, and he does not stop doing that until after the timer has expired

## Actual Behavior
<!--- Tell us what happens instead -->
When I turn on the tracking while it is still in the same place, it sends the user's locations automatically, although I would like you to send it the first time, and then wait until it moves and starts sending the recent locations after traveling a distance of 10 meters.
## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->
I have put the code that I am using
## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I do not understand your problem description.

> When I turn on the tracking while it is still in the same place, it sends the user's locations automatically, although I would like you to send it the first time, and then wait until it moves and starts sending the recent locations after traveling a distance of 10 meters.

**Comment by AbdrahmanKafo96** [comment]
Am trying to achieve the idea of having records get sent by the device when the device in actual moving state but what is happening is the records are being sent even if the device is not moving  for example the device is still in a room let us say i dont want the records to get sent when the device is just around the same area

**Comment by christocracy** [comment]
See api docs Config.motionTriggerDelay

**Comment by AbdrahmanKafo96** [comment]
I have another problem, which is that when I close the screen and the service runs in the background, since the application is closed, the user's location becomes random, sometimes inaccurate

**Comment by christocracy** [comment]
> receiving records while device is still in the same place

Is your original issue solved?

**Comment by AbdrahmanKafo96** [comment]
Yes, but as soon as I close the phone screen or make an application run in
the background, there is another problem. It fetches sites that are very
far from my current location while I am driving in a car.

**Comment by christocracy** [comment]
>there is another problem

If you have an unrelated problem, then post a new issue.  Issues are not open-ended support threads.
