### ISSUE TITLE
Why is `bg.BackgroundGeolocation.requestPermission` callled 4 times in a row in the example

### ISSUE THREAD

**Issue by mongjong59** [transistorsoft/flutter_background_geolocation#902]
`bg.BackgroundGeolocation.requestPermission` callled 4 times in a row in [the example](https://github.com/transistorsoft/flutter_background_geolocation/blob/f2684cc2c2490dd8e2ccd9051414315bc0e2f7f4/example/lib/advanced/main_menu_button.dart#L88-L91) without no explanatory comment.

## Expected Behavior
- `bg.BackgroundGeolocation.requestPermission` callled 1 time in the example, or
-  Explanatory comment about this abnormal pattern is provided

## Actual Behavior
- `bg.BackgroundGeolocation.requestPermission` callled 4 times in a row in the example, and
-  No explanatory comment about this abnormal pattern

## Steps to Reproduce
1. Visit the [advanced example code](https://github.com/transistorsoft/flutter_background_geolocation/blob/f2684cc2c2490dd8e2ccd9051414315bc0e2f7f4/example/lib/advanced/main_menu_button.dart#L88-L91)

## Context
- Read and imitate the example

## Debug logs
N/A

**Comment by christocracy** [comment]
Just some test code I forgot to remove.  Ignore it.
