### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/geofence)

### ISSUE THREAD

**Issue by yaroslav13** [transistorsoft/flutter_background_geolocation#903]
```
@pragma('vm:entry-point')
void geolocationHeadlessTask(bg.HeadlessEvent headlessEvent) {
  headlessGeolocationCallback(headlessEvent);
}

@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) {
  final taskId = task.taskId;
  BackgroundFetch.finish(taskId);
}

void main() {
  runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      setupPrintLogger(
        enableLogs: BuildConfig.getCurrentBuildType().enableLogs,
      );

      await Firebase.initializeApp();

      await initCrashlytics();
      initAppsflyer();

      final getIt = await initDependencies();

      getIt.get<LocationTrackingCubit>().onCreate();
      runApp(_buildAppWidgetTree());

      bg.BackgroundGeolocation.registerHeadlessTask(geolocationHeadlessTask);
      BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    },
    CrashObserver.instance.onAsyncError,
  );
}
```

Have the following error: 

I/flutter ( 7465): MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/geofence)
I/flutter ( 7465): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
I/flutter ( 7465): <asynchronous suspension>
I/flutter ( 7465): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637)
I/flutter ( 7465): <asynchronous suspension>
I/flutter ( 7465): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

@christocracy Do you have a suspicion why it can be? Flutter 3.3.6. It happened after bumping the library version from 4.7.1 to 4.8.3. Release mode only (OS Android)

**Comment by christocracy** [comment]
> headlessGeolocationCallback

You likely need to use `@pragma('vm:entry-point')` that function as well

**Comment by yaroslav13** [comment]
Thanks

**Comment by yaroslav13** [comment]
Unfortunately, after that crashed with I/flutter (16018): MissingPluginException(No implementation found for method listen on channel com.transistorsoft/flutter_background_geolocation/events/location)
I/flutter (16018): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
I/flutter (16018): <asynchronous suspension>
I/flutter (16018): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637)
I/flutter (16018): <asynchronous suspension>
I/flutter (16018): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (16018):

**Comment by christocracy** [comment]
You ignored the issue template.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
