### ISSUE TITLE
Adding geofences from a for loop not working.

### ISSUE THREAD

**Issue by Tristannos** [transistorsoft/flutter_background_geolocation#904]
When i add geofences normally it works but when i add them in a for loop for some reason it will not register.
When i do `print(await bg.BackgroundGeolocation.geofences);` the geofences are there;

**Working**
<img width="426" alt="Screenshot 2022-12-19 at 15 48 54" src="https://user-images.githubusercontent.com/55278228/208452584-5000208e-f2cd-40e2-87fc-a4416328377d.png">

**Not working**
<img width="417" alt="Screenshot 2022-12-19 at 15 49 31" src="https://user-images.githubusercontent.com/55278228/208452761-2d081dce-24f5-4a64-a41e-c0d4c0452c59.png">

## Your Environment
* Plugin version: 4.8.5
* Platform: iOS
* OS version: ios 16.1
* Device manufacturer / model: Iphone
* Flutter info (`flutter doctor`): 
* Plugin config: 
  bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        locationAuthorizationRequest: 'Always',
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true,
        geofenceInitialTriggerEntry: true,
        notification: bg.Notification(
            title: "The Title",
            text: "The Text",
          channelId: 'testChannel',
          channelName: "channel name1",
        ),
    )

## Expected Behavior
The geofences working.

## Actual Behavior
They are in the geofence list but not registering for some reason.

## Context
Adding al my projects as a geofence so i know when my employees are at the working site.

**Comment by christocracy** [comment]
>Plugin version: Newest

This is meaningless to someone in the future.  You must provide the **exact** version.

**Comment by christocracy** [comment]
Why do you `await generateGeofences()`?  Your method does not return a `Future`.

I suggest you `print` the result of that function and observe the results.

**Comment by Tristannos** [comment]
Yes the await is pointless but i tried it anyways i thought maybe the for loop was not done by the time it was trying to add it.
I already tried that, but unfortunately it's returning the list but not adding.
    
flutter: [
[Geofence identifier: 109, radius: 200.0, 51.08979679999999 / 51.08979679999999, notifyOnEntry:true, notifyOnExit:true, notifyOnDwell: null], 
[Geofence identifier: 121, radius: 200.0, 52.3565966 / 52.3565966, notifyOnEntry:true, notifyOnExit:true, notifyOnDwell: null], [Geofence identifier: 122, radius: 200.0, 52.3720655 / 52.3720655, notifyOnEntry:true, notifyOnExit:true, notifyOnDwell: null]]

**Comment by christocracy** [comment]
You don't see the problem?  It's quite clear to me.  What do you notice about your reported `latitude` and `longitude`?

**Comment by Tristannos** [comment]
Ahh Thankyou very much, i completely overlooked it. took me the whole day....
