### ISSUE TITLE
The background service does not accurately fetch the user's location and sometimes jumps too far

### ISSUE THREAD

**Issue by AbdrahmanKafo96** [transistorsoft/flutter_background_geolocation#905]
## Your Environment
* Plugin version:4.8.5
* Platform: iOS or Android
* OS version:Android
* Device manufacturer / model:Xiaomi MI A2
* Flutter info (`flutter doctor`):
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
X Visual Studio not installed; this is necessary for Windows development.
Download at https://visualstudio.microsoft.com/downloads/.
Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
````bg.BackgroundGeolocation.ready(bg.Config(
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: 10, 

              allowIdenticalLocations:false,
              forceReloadOnGeofence: true,
              forceReloadOnSchedule: true,
              stopOnTerminate: false,
              method: 'post',
              foregroundService: true,
              httpRootProperty: '.',
              enableHeadless: true,
              locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>,"time":"<%= timestamp %>",speed:<%= speed %>}',
              url: '/update_position',
              headers: {
                'Accept': 'application/json',
                'Authorization': 'Bearer $token',
                'content-type': 'application/json',
              },
              params: {
                'sender_id': UserInfo.get('user_id'),
                'beneficiarie_id': int.parse(UserInfo.get('beneficiarie_id')),
               
              },
              autoSync: true,
              //batchSync: true,
            maxDaysToPersist: 1,
              startOnBoot: true,
              forceReloadOnBoot: true,
        
              //  stationaryRadius: ,
              debug: true,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              reset: true))
          .then((bg.State state) {
        setState(() {
          _enabled = state.enabled;
          //  _isMoving = state.isMoving;
        });
      });

## Expected Behavior
<!--- Tell us what should happen -->
The expectation is that I get the last current location of the user every time he moves a distance of only 10 meters
In the event that the application is running or in the background and the screen is locked, or even if the application is closed
Also, if it moves a limited distance inside the shop, I don't want it to send me the user's location.
## Actual Behavior
<!--- Tell us what happens instead -->
What happened is that if an application was working, it would send me locations accurately, and this is good, but as soon as I turn off the screen or make the application in the background or close the application and start the background service, I get locations for the user that are somewhat inaccurate and sometimes it jumps to very far distances and considers it the last location of the user.
## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I need to see evidence.  Eg map screenshot and corresponding logs from the plugin (see wiki *Debugging.*).

**Comment by AbdrahmanKafo96** [comment]
I have deleted and reinstalled the app several times so I no longer have a copy of that snapshot but I will send you the path I stored in the server.
The black dots show the sites that the service picked up while it looked at the beginning, it was picking up sites close to the street, not the real sites, and then it jumped a long distance and usually again, and then it jumped to far places
While in the other picture, I drew a path manually to show the real path that was supposed to appear.

![Screenshot 2022-12-20 011701](https://user-images.githubusercontent.com/73119428/208546780-75fc049f-f1fb-4c16-8e42-5662ddf1b532.png)

![Screenshot 2022-12-20 010458](https://user-images.githubusercontent.com/73119428/208547123-9c17e82a-f595-45d2-b493-0402255b165b.png)

However, I will try it again and provide you with more details

**Comment by christocracy** [comment]
> model:Xiaomi MI A2

Also see https://dontkillmyapp.com

**Comment by christocracy** [comment]
> OS version:Android

This is not an Android **OS Version**

**Comment by AbdrahmanKafo96** [comment]
> > OS version:Android
> 
> This is not an Android **OS Version**

U mean Android One ?

**Comment by christocracy** [comment]
What is the version of the OS installed on your problem device.  This seems like a valid and important piece of information.

**Comment by AbdrahmanKafo96** [comment]
> What is the version of the OS installed on your problem device.  This seems like a valid and important piece of information.

It's Android 10 , my apologies to you

**Comment by AbdrahmanKafo96** [comment]
> > model:Xiaomi MI A2
> 
> Also see https://dontkillmyapp.com

I followed the instructions from that link and it worked fine
Now I get more accurate locations than before when the service is running in the background or when the application is closed
But part of the problem has not been solved yet, and sometimes it brings a user's location completely far from the current user's location while the service is in the background or when the application is closed and the screen is closed

**Comment by christocracy** [comment]
> sometimes it brings a user's location completely far from the current user's location 

See api docs Config.transistorAuthorizationToken to learn how to have the plugin upload locations to the demo server.  Share your selected `orgname` here so I can observe your tracking.

**Comment by AbdrahmanKafo96** [comment]
sorry this method "findOrCreateTransistorAuthorizationToken" It does not exist using Flutter 
bg.BackgroundGeolocation.findOrCreateTransistorAuthorizationToken()

**Comment by christocracy** [comment]
What makes you think that?

**Comment by AbdrahmanKafo96** [comment]
The method 'findOrCreateTransistorAuthorizationToken' isn't defined for the type 'BackgroundGeolocation'.
![Screenshot 2022-12-20 161503](https://user-images.githubusercontent.com/73119428/208687257-345082c6-0328-48f3-874c-c3b2f978ebc8.png)

**Comment by AbdrahmanKafo96** [comment]
My apologies, I copied this code from the API documentation. It's a little different from Flutter , btw I will complete other instructions and send you soon...

**Comment by christocracy** [comment]
> I copied this code from the API documentation

From what api docs?  Why you use other docs but the Flutter docs?

**Comment by AbdrahmanKafo96** [comment]
I made a mistake when I copied it from the ReactِAPI  documentation. i found it in Flutter docs Now everything is fine. I will continue with it I will test it and let you know.

**Comment by AbdrahmanKafo96** [comment]
I have sent user locations to the demo server , CompanyName:CeramicsCompany .

**Comment by christocracy** [comment]
Looks wonderful.

<img width="1228" alt="Screen Shot 2022-12-20 at 11 15 13 AM" src="https://user-images.githubusercontent.com/14999/208714100-31d207a9-0ffa-4eb5-a0de-11c8d74eb3be.png">

**Comment by AbdrahmanKafo96** [comment]
I tried it while walking Indeed, it has become amazing
But now I tried it again while I was driving, still the same previous problem, sometimes it jumps to very far distances...
![Screenshot 2022-12-21 120709](https://user-images.githubusercontent.com/73119428/208880214-82929efd-e6c7-4dc2-8463-c36cd5b045c9.png)
I'll try it out and send it to a demo server and will let you know when I do

**Comment by AbdrahmanKafo96** [comment]
I've already send locations to demo server while app is cloese and the screen phone is off, the Company Name: CeramicsCompany

**Comment by christocracy** [comment]
Your tracking looks fine.  The plugin can take some distance of movement (typically ~200 meters) before your device is recognized to be moving, where tracking initiates.  This distance is denoted by the *green polyline*.  Red dots represent locations where the device was determined to be stationary, where the plugin turned **OFF** location services.  Whenever the plugin changes state, the `onMotionChange` event is fired.  If you field-test with `debug: true`, the plugin will emit debug soundFX, letting you know what the plugin is doing.

Your tracking reported here is perfectly acceptable.

<img width="1286" alt="Screen Shot 2022-12-21 at 9 44 01 AM" src="https://user-images.githubusercontent.com/14999/208932073-40eca650-0662-4c61-8870-86539572615d.png">

**Comment by christocracy** [comment]
For more information, see wiki [Philosophy of Operation](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation)

**Comment by AbdrahmanKafo96** [comment]
Indeed, it works great when I send it to a demo server, and it also works great for me when I send it to my server while an application is running.
But I don't quite know why it doesn't work well in the background
I've already done everything you told me earlier BUT
I will attach two pictures of what it looks like on the server
The first picture is in the case of the application running while I am walking
The other case is a closed application. I want you to notice the pen icon, which means the locations that have been registered and sent to the server
There is a time difference between each location and the next one, in addition to that, some locations are quite far away
this pic while app running 
![Screenshot 2022-12-21 202420](https://user-images.githubusercontent.com/73119428/209019589-f10caa4a-5406-4d24-9741-b492dc767e4a.png)

this picture while im driving the car and App is close 
![Screenshot 2022-12-21 125409](https://user-images.githubusercontent.com/73119428/209019668-9b65ab87-b04d-49b0-a81f-106bd65526fc.png)

It should have looked like this
![Screenshot 2022-12-22 010714](https://user-images.githubusercontent.com/73119428/209020117-90099397-1480-4b06-a0ba-0fdf542646e9.png)

**Comment by christocracy** [comment]
For me, on the devices I test upon, the plugin doesn’t operate any differently between foreground, background or terminated.

**Comment by AbdrahmanKafo96** [comment]
> For more information, see wiki [Philosophy of Operation](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Philosophy-of-Operation)

My problem was that I used the .changePace() method incorrectly
I made some adjustments and now it's much better
I will attach some pictures for you in different cases, including the screen is off, the service is in the background, and the service while the application is closed ,On foot also with driving the car
thamks MR.Chris
![scsh](https://user-images.githubusercontent.com/73119428/209451146-8952eff0-1b40-4b68-adaf-ef2085f4698b.png)
![Screenshot 2022-12-24 202901](https://user-images.githubusercontent.com/73119428/209451150-f9125d2f-6476-4bca-8192-9eb11da8ab31.png)
![Screenshot 2022-12-24 202809](https://user-images.githubusercontent.com/73119428/209451152-8ec9a5df-5f1d-46f9-a6b0-aacb12c4c5cf.png)
![Screenshot 2022-12-24 222725](https://user-images.githubusercontent.com/73119428/209451195-a2a5ad01-3f40-47f8-aff4-fb2dfe5812ec.png)

**Comment by AbdrahmanKafo96** [comment]
I have tried it on several Huawei and Xiaomi devices and it works great
with them, but only with the Samsung Galaxy S8. It does not work at all in
the background or if the application is closed.
Are there any hints

**Comment by christocracy** [comment]
https://dontkillmyapp.com

**Comment by AbdrahmanKafo96** [comment]
I would like to check if the process is still running in the background
because I would like to close it in case the user decides to log out of the
system. Is there a hint?

**Comment by christocracy** [comment]
See api docs `State.enabled`
