### ISSUE TITLE
After terminate event location reporting stops

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#908]
## Your Environment
* Plugin version: 4.7.0
* Platform: Android
* Flutter info (`flutter doctor`):
/Users/lloydabernathy/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.3.5 on channel stable at /Users/lloydabernathy/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (9 weeks ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lloydabernathy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
        url: "https://app.motormouth.io/v2/user/location/flutter",
        params: {
          "profile_id" : AppData.currentProfile!.id
        },
        autoSync: true,
        //transistorAuthorizationToken: token,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));
```

## Expected Behavior
Terminate event should fire and then location and motion change reporting should continue. 

## Actual Behavior
Sometimes on several different real android devices it seems like terminate event causes location reporting to stop completely. This issue is inconsistent and works the majority of the time. I have attached the logs for the relevant device. 

## Steps to Reproduce

1. Begin application
2. Confirm location reporting
3. Terminate application

## Context
The relevant date and time period is 12-21 12:20 to 12-21 15:00. The user was moving and expected location reporting to happen. 
[background-geolocation 2.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10289604/background-geolocation.2.log)

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
12-21 12:20:32.575 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-21 12:20:32.836 DEBUG [LifecycleManager onPause] ☯️  onPause
12-21 12:20:32.837 DEBUG [LifecycleManager onStop] ☯️  onStop
12-21 12:20:42.595 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-21 12:20:42.596 DEBUG [TerminateEvent$a a] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
12-21 15:00:01.079 DEBUG [LifecycleManager onStart] ☯️  onStart
12-21 15:00:01.088 DEBUG [LifecycleManager onResume] ☯️  onResume
12-21 15:00:01.097 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

12-21 15:00:26.391 DEBUG [TransistorAuthorizationToken$b run] 🔑 Found cached token for tracker.transistorsoft.com
12-21 15:00:26.393 WARN [BackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
12-21 15:00:26.396 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [isMoving, params]
12-21 15:00:26.399 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

12-21 15:00:26.401 DEBUG [c h] 
  ℹ️  LocationAuthorization: Permission granted
12-21 15:00:26.409 DEBUG [AbstractService start] 
  🎾  LocationRequestService [eventCount: 1]
12-21 15:00:26.409 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 5]
12-21 15:00:26.410 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
12-21 15:00:27.799 DEBUG [AbstractService start] 
  🎾  LocationRequestService [eventCount: 1]
12-21 15:00:27.800 INFO [LocationRequestService handleLocationResult] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 5
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 27.462307,-80.304524 hAcc=9.544 et=+10d22h7m40s96ms alt=-26.200000762939453 vAcc=15.760526 vel=0.041991513 sAcc=0.4816638], age: 56ms, time: 1671652827743
```

</details>

**Comment by lloydelvt** [comment]
Is there any logic that causes the location reporting to stop? (Such as failed API calls, poor network service, any errors?)

**Comment by christocracy** [comment]
No.  The plugin is very robust.

see https://dontkillmyapp.com

**Comment by lloydelvt** [comment]
Ok was there anything you saw in the configuration that may have caused that to happen?

**Comment by christocracy** [comment]
No.  The only thing that can cause what you experience would be stopOnTerminate: true.

Have you adjusted your device settings according to https://.dontkillmyapp.com and gone outside for a field test yet?
