### ISSUE TITLE
iOS ProviderChangeEvent enabled is false when it is actually enabled

### ISSUE THREAD

**Issue by joserocha3** [transistorsoft/flutter_background_geolocation#91]
## Your Environment
* Plugin version: 1.0.10
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: Simulator and iPad
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (2 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
      geofenceProximityRadius: 100000, // about 62 miles
      logLevel: bg.Config.LOG_LEVEL_ERROR,
      stopOnTerminate: false,
      enableHeadless: true,
      startOnBoot: true,
      autoSync: true,
      reset: _reset ?? true,
      // Do not record location event if more than 300 meters/second since last
      // recorded event - Android only, iOS does not allow mock locations on device
      speedJumpFilter: 300,
      foregroundService: true,
      disableLocationAuthorizationAlert: true,
      notification: bg.Notification(
        title: 'Zone Tracker',
        text: 'Search underway',
        channelName: 'Zone Tracker',
        color:
            '#${Constants.colors.primary.value.toRadixString(16).substring(2)}',
        smallIcon: 'drawable/ic_notification',
        largeIcon: 'drawable/ic_notification',
        priority: bg.Config.NOTIFICATION_PRIORITY_MIN,
      ),
    );
```

## Expected Behavior
`ProviderChangeEvent` `enabled` should be true even before location permissions are granted.

## Actual Behavior
`ProviderChangeEvent` `enabled` is false before location permissions are granted. 

## Steps to Reproduce
1. Enable device location-services
2. Install and launch app
3.`enabled` is false
4. Prompt for permissions
5. Permissions granted
6. Now enabled is `true`

## Context
Show the user a visual indicator that location permission has not been granted OR location-services are off. 

Currently on app install there is no way to tell if location-services are off because `enabled` is false even if device location-services are on. **This could just be an iOS limitation**, maybe we cannot know the devices's overall location-services status unless permissions have been granted. If so, I will have to handle this differently.

## Debug logs
NA

**Comment by christocracy** [comment]
I think you'll be interested in the [ProviderChangeEvent.status](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/ProviderChangeEvent/status.html).

**Comment by joserocha3** [comment]
Hi @christocracy, I am looking at `status` to determine if we have permissions. But `enabled` comes back `false` until permissions are granted, even if the _global_ device's location services are enable in the device settings. So on first app start we do not now whether to tell the user "please grant us permission" or "hey you need to turn on your device's location service".

Is it not possible to get `enabled` as true even before permissions are granted?

**Comment by christocracy** [comment]
>Is it not possible to get enabled as true before permissions are granted?

No.

**Comment by christocracy** [comment]
And if you don't do this for Android `disableLocationAuthorizationAlert: true,`, Android will automatically show a Dialog offering the the user to make all the necessary settings changes in one click of [OK] button.  See Android note in [disableLocationAuthorizationAlert](https://transistorsoft.github.io/cordova-background-geolocation/interfaces/_cordova_background_geolocation_.config.html#disablelocationauthorizationalert)

**Comment by joserocha3** [comment]
Gotcha, thank you for the clarification.
