### ISSUE TITLE
Getting redunt `onProviderChange` and `onConnectivityChange` callback event in headless

### ISSUE THREAD

**Issue by kunatastic** [transistorsoft/flutter_background_geolocation#910]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.onProviderChange(onProviderChange);
bg.BackgroundGeolocation.onConnectivityChange(onConnectivityChange);

bg.Config(
...,
      distanceFilter: isAndroid ? 0 : 200,
      locationUpdateInterval: 600000,
      fastestLocationUpdateInterval: 60000,
...
)

  static void onProviderChange(bg.ProviderChangeEvent event) {
      print(">>> event: $event")
  }

  static void onConnectivityChange(bg.ConnectivityChangeEvent event) {
      print(">>> event: $event")
  }
```

## Expected Behavior
I expect callback to be present when they are mean't to be.

## Actual Behavior
I am getting callback redunduntly and with exact same values.

## Context

I need to log and process some process on the basis of the callback.

**Comment by christocracy** [comment]
>bg.BackgroundGeolocation.onProviderChange(onProviderChange);
>bg.BackgroundGeolocation.onConnectivityChange(onConnectivityChange);

You are not to use these in headless mode.

Your registered HeadlessTask in main.dart receives all headless events.

**Comment by kunatastic** [comment]
I have also registered them seperately also

```dart
    bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask,
    );
```

```dart

/// Receive events from BackgroundGeolocation in Headless state.
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(
  bg.HeadlessEvent headlessEvent,
) {
  switch (headlessEvent.name) {
    case bg.Event.LOCATION:
      LocationCallbackHandler.onLocation(headlessEvent.event);
      break;

    case bg.Event.CONNECTIVITYCHANGE:
      LocationCallbackHandler.onConnectivityChange(headlessEvent.event);
      break;

    case bg.Event.PROVIDERCHANGE:
      LocationCallbackHandler.onProviderChange(headlessEvent.event);
      break;

    case bg.Event.TERMINATE:
// something
      break;
  }
}
```

**Comment by christocracy** [comment]
- `bg.BackgroundGeolocation.registerHeadlessTask` **MUST** be placed in `main.dart`
- You do not use `BackgroundGeolocation.onXXX` in `main.dart`

**Comment by christocracy** [comment]
I suggest you have a look at the /example app in this repo.

**Comment by kunatastic** [comment]
> * You do not use `BackgroundGeolocation.onXXX` in `main.dart`
Couldn't follow you here. Could you kindly elaborate a bit further.

**Comment by christocracy** [comment]
Look at the [Example](https://github.com/transistorsoft/flutter_background_geolocation#-example) in the README.

Everything except `.registerHeadlessTask` belongs **INSIDE** a Flutter `Widget`.
