### ISSUE TITLE
Geofencing issue

### ISSUE THREAD

**Issue by sushrutnaik** [transistorsoft/flutter_background_geolocation#916]
Plugin version:4.7.1 
Platform: Android OS
version:9 
Device manufacturer / model:moto 
Flutter info (flutter doctor):
 Plugin config:

```
bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) {
  print('[geofence] ' + event.toString());
  if (event.identifier == 'DANGER_ZONE') {
    if (event.action == 'ENTER') {
      // Entering the danger-zone, we want to aggressively track location.
      bg.BackgroundGeolocation.start();
    } else if (event.action == 'EXIT') {
      // Exiting the danger-zone, we resume geofences-only tracking.
      bg.BackgroundGeolocation.startGeofences();
    }
  }
});
bg.BackgroundGeolocation.addGeofence(bg.Geofence(
  identifier: "DANGER_ZONE",
  radius: 1000,
  latitude: 15.735510115877354,
  longitude: 74.49495533186614,
  notifyOnEntry: true,
  notifyOnExit: true,
));

// Ready the plugin.
bg.BackgroundGeolocation.ready(bg.Config(
  desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  url: '/locations/',
  autoSync: true
)).then((bg.State state) {
  bg.BackgroundGeolocation.startGeofences();
});
```
I am trying to start geofence but it is not working as expected sometimes its starting and other times its not can you tell why?

**Comment by christocracy** [comment]
I have no idea.  You've not provided much information.  I suggest you see Wiki *Debugging* and fetch logs from the plugin.  Be sure to configure `logLevel` for verbose logging.

**Comment by sushrutnaik** [comment]
D/TSLocationManager(23528): ╔═════════════════════════════════════════════
D/TSLocationManager(23528): ║ TSGeofenceManager monitoring 1/1
D/TSLocationManager(23528): ╠═════════════════════════════════════════════
D/TSLocationManager(23528): ╟─ 🎾  DANGER_ZONE
D/TSLocationManager(23528): ╚═════════════════════════════════════════════
D/TSLocationManager(23528): [c.t.l.service.AbstractService onDestroy]
D/TSLocationManager(23528):   🔴  LocationRequestService stopped
D/TSLocationManager(23528): [c.t.l.s.LocationRequestService handleLocationResult] SingleLocationRequest 1 isFinished? true
D/TSLocationManager(23528): [c.t.l.g.TSGeofenceManager setLocation] isMoving: false | stateChanged: false | timerExpired: false | elapsed: 0
D/TSLocationManager(23528): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]


These are the logs when I enter danger zone its not working as expected

**Comment by christocracy** [comment]
Are you testing this in a physical device and moving outside to field test this?  This sort of thing cannot be tested sitting in your office.
