### ISSUE TITLE
How to stop Popups in iOS for motion activities

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#92]
Continues pop-ups in system tray about SPEED, ACCURACY ETC 

## Your Environment
* Plugin version:1.0.9
* Platform: iOS 
OS version:Mac OS
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
    bg.BackgroundGeolocation.start();
 bg.BackgroundGeolocation.onLocation(_onLocation);
 bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
// bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
// bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
// bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.ready(bg.Config(
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 0,
        locationUpdateInterval: 5000,
        preventSuspend: true,
        stopOnTerminate: false,
        stopOnStationary: true,
       // useSignificantChangesOnly: true,
        startOnBoot: true,

        enableHeadless: true,
        heartbeatInterval: 60
    )).then((bg.State state) {
      print('[ready] ${state.toMap()}');
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
void _onLocation(bg.Location location) async{

 print('[location] - $location');
 final prefs = await SharedPreferences.getInstance();
 bool _provider= prefs.getBool("provider1234");
 if (_provider != null && _provider == true) {
   updateLocation(location.coords.latitude, location.coords.longitude);
   Fluttertoast.showToast(msg: (_provider.toString() + "  mmmm"));

 }
 }
 void _onMotionChange(bg.Location location) async{
 print('[motionchange] - $location');
 final prefs = await SharedPreferences.getInstance();
 bool _provider= prefs.getBool("provider1234");
 if (_provider != null && _provider == true) {
   updateLocation(location.coords.latitude, location.coords.longitude);
   Fluttertoast.showToast(msg: (_provider.toString() + "  mmmmm"));

 }
 }

## Expected Behavior

Should not occur Continues popups while moving .
## Actual Behavior

popup should occur after some significant interval
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See docs `disableMotionActivityUpdates`
