### ISSUE TITLE
[IOS] onHeartbeat not working after terminating app

### ISSUE THREAD

**Issue by AliEasy** [transistorsoft/flutter_background_geolocation#920]
## Your Environment
* Plugin version: 4.8.5
* Platform: iOS
* OS version: 12.5.6
* Device manufacturer / model: iphone 5s
* Flutter info (`flutter doctor`):
* Plugin config:
```
    BackgroundGeolocation.onHeartbeat(
      (p0) async {
        await MovementTrackingServiceIosHandler().onEvent();
      },
    );

    await BackgroundGeolocation.ready(Config(
        desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: false,
        debug: true,
        logLevel: Config.LOG_LEVEL_VERBOSE,
        heartbeatInterval: 60
        preventSuspend: true,
        reset: true));

    BackgroundGeolocation.start();
```

Inside  `await MovementTrackingServiceIosHandler().onEvent();`, getting new location is happening like this:

```
var location = await BackgroundGeolocation.getCurrentPosition(
              samples: 1, persist: true);
```
And then upload in with http post.

## Expected Behavior
As stated in the documentation, this callback must work event after terminating (closing app from recent apps).

## Actual Behavior
The callback is working fine when app is in foreground and event in background (app exists in recent apps). but after swiping up and closing it from recent apps, it stops working.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
On iOS, **everything** stops when the app is terminated, including `onHeartbeat` events.  Your app will not re-awaken until the device moves about 200 meters, when the OS automatically relaunches your app in the background.

See API docs `Config.stopOnTerminate`.
