### ISSUE TITLE
unable to receive Background Location on IOS, flutter 3.3.7

### ISSUE THREAD

**Issue by arnoorani** [transistorsoft/flutter_background_geolocation#921]
unable to receive Background Location on IOS, flutter 3.3.7 

## Your Environment
* Plugin version:4.8.5
* Platform: iOS or Android: IOS
* OS version:15.5
* Device manufacturer / model: iphone 12
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.4 21F79 darwin-x64, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->


 bg.BackgroundGeolocation.ready(
        bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: "Always",
            distanceFilter: 15,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: Constants.debug,
            logLevel: bg.Config.LOG_LEVEL_DEBUG,
            autoSync: true,
            reset: true,
            geofenceInitialTriggerEntry: true,
            persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
            backgroundPermissionRationale: bg.PermissionRationale(
                title: "Allow {applicationName} to access to this device's location in the background?",
                message:
                    "We need your location data to ensure your timer starts when you enter your workplace or exit your workplace. No location outside of pre set Geo Circle provided by your employer is recorded and or shared. Please enable always so that we can show the time you enter work and time you leave work for proper time collection on your timesheet.",
                positiveAction: "Change to {backgroundPermissionOptionLabel}",
                negativeAction: "Cancel")),
      ).then((bg.State state) {
        if (!state.enabled) {
          bg.BackgroundGeolocation.start();
        }






 bg.BackgroundGeolocation.onLocation((bg.Location location) {
        LocalNoticeService().triggerNotification('On Location:');
        print('[onLocation] success: ${location}');
      }
```

## Expected Behavior
The app should return location changes in the background and trigger a local notification

## Actual Behavior

not receiving background location

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you observing the logs?  Testing in the iOS simulator with *freeway drive*?  See wiki *Deugging*.

**Comment by arnoorani** [comment]
yup, that is what I'am using.

**Comment by christocracy** [comment]
Use verbose logging.  What makes you thing that location is not being tracked?

**Comment by arnoorani** [comment]
its supposed to trigger a local notification and update the backend, does not seem to be triggering, it works when the app is in the background

**Comment by christocracy** [comment]
I’m not concerned about your notifications.  That doesn’t involve this plugin.

I suggest you observe the logs.
