### ISSUE TITLE
Disable License Validation Error Toast

### ISSUE THREAD

**Issue by AliEasy** [transistorsoft/flutter_background_geolocation#922]
## Your Environment
* Plugin version: 4.8.5
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung
* Flutter info (`flutter doctor`):
* Plugin config:

## Steps to Reproduce

1.
2.
3.
4.

## Context
Im importing this package on my project which has both android and ios modules. but Im intending to use this package only on ios.
So there is no use from this package in android module and it is being handled by `if(Platform.isIOS)` above the code line which runs this service.
The problem is even though Im not using this package on android, **License Validation Error Toast** is being showed anyway.
Is it possible to turn this toast off?

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Is it possible to turn this toast off?

Yes, by purchasing a license.

**Comment by AliEasy** [comment]
Thanks for your quick response.
Yes purchasing a license is a solution but the matter is its not being used on android and the package is free for ios.
Also this service will not work on android release unless by purchasing a license, so at least the toast must not show on release.
