### ISSUE TITLE
Timestamp are from the future. 

### ISSUE THREAD

**Issue by unYannickFrechette** [transistorsoft/flutter_background_geolocation#923]
## Your Environment
* Plugin version: 
    4.8.5
* Platform:
      Android
* OS version: 
     12
* Device manufacturer / model: 
    Google Pixel 3
* Flutter info (`flutter doctor`):
   Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-CA)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
   I have this problem also with you example app ! 
```

## Expected Behavior
Get a timestamp that fits my device datetime. 

## Actual Behavior
I get timestamp that are 5 hours later than actual time. 
At midnight in Montreal,  timestamp is : 2023-01-20T05:09:46.728Z

## Steps to Reproduce
I just ran the example app on my phone. 

Maybe I keep missing the setting to fix this, but I'm not sure...

**Comment by christocracy** [comment]
The timestamps are UTC.  Montreal timezone js GMT-5.
