### ISSUE TITLE
Plugin always ask for Always permission while requested WhenInUse

### ISSUE THREAD

**Issue by CeesJanNolen** [transistorsoft/flutter_background_geolocation#925]
## Your Environment
* Plugin version: 4.8.5
* Platform: Android and iOS
* OS version: 12
* Device manufacturer / model: OnePlus 8 Pro
* Flutter info (`flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2486], locale nl-NL)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] VS Code (version 1.74.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
    bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        // <-- lets the Settings screen drive the config rather than re-applying each boot.
        // Convenience option to automatically configure the SDK to post to Transistor Demo server.
        // transistorAuthorizationToken: token,
        // Logging & Debug
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        isMoving: true,
        allowIdenticalLocations: true,
        //update every second
        locationUpdateInterval: 1000,
        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        //set to 0 to get an update every second
        distanceFilter: 0.0,
        disableElasticity: true,
        locationAuthorizationRequest: "WhenInUse",

        // Activity recognition options
        stopTimeout: 60,
        backgroundPermissionRationale: bg.PermissionRationale(
          title: RallyStrings.getPermissionLabel('title'),
          message: RallyStrings.getPermissionLabel('message'),
          positiveAction: RallyStrings.getPermissionLabel('positive_action'),
          negativeAction: RallyStrings.getPermissionLabel('negative_action'),
        ),
        notification: bg.Notification(
          title: "Route active",
          channelName: "Location tracking",
          text: "Track location in background",
        ),

        // HTTP & Persistence
        autoSync: true,
        // Application options
        stopOnTerminate: false,
        startOnBoot: true,
        //todo configure for android.
        enableHeadless: false,
        heartbeatInterval: 60,
        preventSuspend: true,
      ),
    ).then((bg.State state) async {
      print('[ready] ${state.toMap()}');
      print('[ready - enabled] ${state.enabled}');
      print('[didDeviceReboot] ${state.didDeviceReboot}');
      if (state.schedule?.isNotEmpty == true) {
        bg.BackgroundGeolocation.startSchedule();
      }
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
```

## Expected Behavior
Upon start of the locator, we want to request the user just once for always location permission.
We've developed it like so;
```dart
  Future<void> startLocator() async {
    await bg.BackgroundGeolocation.start();
    await Future.delayed(Duration(milliseconds: 500));
    await bg.BackgroundGeolocation.changePace(true);
    _upgradeAlwaysAllow();
  }

  void _upgradeAlwaysAllow() async {
    print("Will upgrade");
    if (!SharedPrefs.instance.hasAskedAlwaysAllowLocationPermission()){
        print("did not get notification yet");
        bg.BackgroundGeolocation.setConfig(bg.Config(
          locationAuthorizationRequest: 'Always',
        ));
        SharedPrefs.instance.setAskedAlwaysAllowLocationPermission();
    }else{
      print("Already asked for always permissions once");
    }
  }
```

```dart
Shared preferences part:
  bool hasAskedAlwaysAllowLocationPermission(){
    print("askedAlwaysAllowLocationPermission = ${_pref.getBool(_keyAskedAlwaysLocationPermission)}");
    return _pref.getBool(_keyAskedAlwaysLocationPermission) ?? false;
  }

  void setAskedAlwaysAllowLocationPermission(){
    print("setting asked permission");
    _pref.setBool(_keyAskedAlwaysLocationPermission, true);
  }
```

We expect this to just run once and if the user got the dialog once, it will not return anymore. 
So that the user doesn't get the always location request all the time

## Actual Behavior
What is actually happening is that upon every start, the always location permission pops up.
This shouldn't be happening as we set it to WhenInUse

## Steps to Reproduce

To reproduce use the above provided config, together with the start method.
The SharedPrefs is a small class we've created for accessing the shared preferences; This can be a direct call to shared preferences for testing of course.

## Context
We are trying to give the user the best experience in the app without requesting the always location permission all the time after he ignores the dialog

## Debug logs

<details>

	<summary>Logs down below will show both logs from plugin as well as the native prints which are in the _upgradeAlwaysAllow function. </summary>

First time start:
``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/flutter (25235): PlatformException(PERMISSION_DENIED, Background location permission denied, null, null)
D/EGL_emulation(25235): app_time_stats: avg=57.08ms min=7.54ms max=334.94ms count=19
D/TSLocationManager(25235): [c.t.l.l.LifecycleManager onPause] ☯️  onPause
D/EGL_emulation(25235): app_time_stats: avg=500.97ms min=263.96ms max=737.99ms count=2
D/EGL_emulation(25235): app_time_stats: avg=506.37ms min=263.76ms max=748.99ms count=2
D/TSLocationManager(25235): [c.t.l.l.LifecycleManager onResume] ☯️  onResume
I/TSLocationManager(25235): [c.t.locationmanager.util.c g] 
I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting Background permission
D/EGL_emulation(25235): app_time_stats: avg=7467.38ms min=2720.74ms max=12214.02ms count=2
W/lly.rallywerel(25235): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/lly.rallywerel(25235): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/TSLocationManager(25235): [c.t.l.l.LifecycleManager onPause] ☯️  onPause
I/TSLocationManager(25235): [c.t.locationmanager.util.c$j onPermissionGranted] 
I/TSLocationManager(25235):   ✅  LocationAuthorization: Permission granted

I/TSLocationManager(25235): [c.t.locationmanager.util.c h] 
I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting permission

I/flutter (25235): Will upgrade
I/flutter (25235): askedAlwaysAllowLocationPermission = null
I/flutter (25235): did not get notification yet
I/flutter (25235): setting asked permission

I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting Background permission
I/TSLocationManager(25235): [c.t.locationmanager.util.c e] 
I/TSLocationManager(25235):   🔵  Should show backgroundPermissionRationale? true

D/TSLocationManager(25235): [c.t.l.a.TSLocationManagerActivity execute] android.permission.ACCESS_BACKGROUND_LOCATION
```

Second time start:
``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/TSLocationManager(25235): [c.t.locationmanager.util.c g] 
I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting Background permission
I/TSLocationManager(25235): [c.t.locationmanager.util.c e] 
I/TSLocationManager(25235):   🔵  Should show backgroundPermissionRationale? true
D/TSLocationManager(25235): [c.t.l.a.TSLocationManagerActivity execute] android.permission.ACCESS_BACKGROUND_LOCATION

I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting permission
I/TSLocationManager(25235): [c.t.l.service.TrackingService changePace] 
I/TSLocationManager(25235):   🔵  setPace: false → false
I/TSLocationManager(25235): [c.t.locationmanager.util.c$j onPermissionGranted] 
I/TSLocationManager(25235):   ✅  LocationAuthorization: Permission granted

I/TSLocationManager(25235): [c.t.locationmanager.util.c h] 
I/TSLocationManager(25235):   🔵  LocationAuthorization: Requesting permission

I/TSLocationManager(25235): [c.t.locationmanager.util.c$j onPermissionGranted] 
I/TSLocationManager(25235):   ✅  LocationAuthorization: Permission granted


I/flutter (25235): Will upgrade
I/flutter (25235): askedAlwaysAllowLocationPermission = true
I/flutter (25235): Already asked for always permissions once
```
</details>

**Comment by christocracy** [comment]
You are likely calling some method which requests the location or permission **BEFORE** `.ready(config)` has resolved.

The following code would reproduce your problem:

```dart
bg.BackgroundGeolocation.getCurrentPosition();
// OR
bg.BackgroundGeolocation.start();
// OR
bg.BackgroundGeolocation.requestPermission();
.
.
.
bg.BackgroundGeolocation.ready(config);
```

Your `Config` provided to ready is not consumed until `.ready(config)` resolves.  The default `locationAuthorizationRequest` is `Always`.

```dart
await bg.BackgroundGeolocation.ready(config);
// NOW you may call methods with request location or permission.
bg.BackgroundGeolocation.getCurrentPosition();
```

**Comment by christocracy** [comment]
The method name "`.ready`" is named *precisely* to communicate that the plugin is not "*ready*" to use *until* it resolves.

**Comment by christocracy** [comment]
It is 100% certain that the problem is in your code.  You are definitely telling the plugin to .start() *before* your Config has been provided to .ready.

**Comment by christocracy** [comment]
If you’re not using Config.schedule, why do you have this code?

```dart
if (state.schedule?.isNotEmpty == true) {
        bg.BackgroundGeolocation.startSchedule();
      }
```
This looks like a blind copy/paste from the /example app.

**Comment by CeesJanNolen** [comment]
> If you’re not using Config.schedule, why do you have this code?

I did indeed copy over code from the example app. 
I left this part in here to later on use the app for scheduling as well. I did just remove that part but it still asks for the always permission. Not sure if that one is one of the possible causes?!




> It is 100% certain that the problem is in your code. You are definitely telling the plugin to .start() _before_ your Config has been provided to .ready.

I just did some tests, added some more logging to our code. See the details below;

<details>

```dart

),  //config before here
    ).then((bg.State state) async {
      print(
          "RallyLocator -- ${DateTime.now().toIso8601String()} -- Plugin is now ready to be used");
      print('[ready] ${state.toMap()}');
      print('[ready - enabled] ${state.enabled}');
      print('[didDeviceReboot] ${state.didDeviceReboot}');
      // if (state.schedule?.isNotEmpty == true) {
      //   bg.BackgroundGeolocation.startSchedule();
      // }
    }).catchError((error) {
      print(
          "RallyLocator -- ${DateTime.now().toIso8601String()} -- Plugin loading error");
      print('[ready] ERROR: $error');
    });
```

```dart
  Future<void> startLocator(int interval) async {
    print(
        "RallyLocator -- ${DateTime.now().toIso8601String()} -- Plugin Will now start");

    await bg.BackgroundGeolocation.start();
    await Future.delayed(Duration(milliseconds: 500));
    await bg.BackgroundGeolocation.changePace(true);
    _upgradeAlwaysAllow();

    print(
        "RallyLocator -- ${DateTime.now().toIso8601String()} -- Plugin is started");
  }
```

```dart
  Future<void> stopLocator() async {
    print(
        "RallyLocator -- ${DateTime.now().toIso8601String()} -- Plugin will now be stopped");

    await bg.BackgroundGeolocation.stop();
  }
```
</details>

**Results:**
This resulted in the following;
```
I/flutter (14220): RallyLocator -- 2023-01-20T18:17:03.314052 -- Plugin is now ready to be used
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:33.012112 -- Plugin Will now start
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:35.925685 -- Plugin is started
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:44.231661 -- Plugin will now be stopped
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:47.303273 -- Plugin Will now start
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:52.440040 -- Plugin is started
I/flutter (14220): RallyLocator -- 2023-01-20T18:18:55.010799 -- Plugin will now be stopped

``` 

In those results we can see that the config is really loaded before. We've read through some of the other issues, and saw those items earlier, therefore we made sure our config is really loaded before.

I've just debugged one extra line in the startlocator;
`print((await bg.BackgroundGeolocation.state).locationAuthorizationRequest);`

This does print (as expected)
`I/flutter (14220): WhenInUse`

Any idea what can be a cause for this?

**Comment by christocracy** [comment]
> Any idea what can be a cause for this?

The plugin is being told to request location permission *before* your Config has been provided to .ready.

I suggest you experiment within a simple, freshly generated HelloWorld app using the simplest possible implementation of the plugin, as shown in the readme.

**Comment by CeesJanNolen** [comment]
Yeah but the strange thing is that the config is loaded before, and this does only happen once the user press the start button which will then perform the start action on the plugin. (this can be seen in those timestamps). Nowhere else in our app do we request the location using the plugin before the config. 

But I will perform some tests on a simple app to see if there is any difference in there. Will keep you up to date.

**Comment by CeesJanNolen** [comment]
After debugging I've found out the issue.

So our start & upgrade function looks like this:
```dart
  Future<void> startLocator(int interval) async {
    await bg.BackgroundGeolocation.start();
    await Future.delayed(Duration(milliseconds: 500));
    await bg.BackgroundGeolocation.changePace(true);
    _upgradeAlwaysAllow();
  }

  void _upgradeAlwaysAllow() async {
    if (!SharedPrefs.instance.hasAskedAlwaysAllowLocationPermission()) {
      bg.BackgroundGeolocation.setConfig(bg.Config(
        locationAuthorizationRequest: 'Always',
      ));
      SharedPrefs.instance.setAskedAlwaysAllowLocationPermission();
    }
  }
```
On the first time of the app launch the config will be set due to the fact that the shared preferences will return false. This will cause the config to be overridden to always. 
After pressing stop and then start again it will therefore have the config to be always again and thus show up the always alert dialog. This also happened in the simple app I've created. This is more or less caused by a bug on our side like you mentioned. 
Thanks for you support.

However, as mentioned in the docs;
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/locationAuthorizationRequest.html
The android 11+ part. 
In there the description says;
> Android will offer the [Config.backgroundPermissionRationale](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/backgroundPermissionRationale.html) dialog just once. Once the user presses the positiveAction on the dialog, it will not be shown again (pressing [Cancel] button does not count).
This would mean that if we would press the cancel button in the always allow location request dialog, it will always show again. But if we would press the positiveAction, which would be the allow acces button, which then redirect to the settings, it would not show again. This however does happen. 

This can be easily reproduced by creating a config and setting it to always.
Then upon pressing start the dialog for android will show, if you will press `change to always allow` and then ignore the settings and go back to the app. then stop the locator and start it again, the dialog will show up again. 
According to the docs which is highlighted above, this should not happen right? Is this device specific or might this be a bug?

Thanks for the help so far!

**Comment by christocracy** [comment]
Once per app launch.

**Comment by CeesJanNolen** [comment]
I didn't close the app in between. So I would assume this is still the same app launch then right? Or is going to settings and going back to the app also seen as an app launch?

**Comment by christocracy** [comment]
I really don’t know.  Is there a problem?

**Comment by CeesJanNolen** [comment]
For now we've created a work around. I will try to show you the issue we've faced in a video. Maybe that explains it better. Will do so after the weekend. Thanks for the help again!~

**Comment by xunreal75** [comment]
Hi 

it seems to be a huge problem. When only whileInUse permitted - every 5 seconds the flutter_background_geolocation Always use request will popped in 4.10.3.
It's really disturbing und should not drive by the package.

The expected behavior is to show it once after start geolocation and not after every new position.

**Comment by christocracy** [comment]
Have you read the api docs Config.locationAuthorizationRequest?
