### ISSUE TITLE
Location template don't work after offline. 

### ISSUE THREAD

**Issue by unYannickFrechette** [transistorsoft/flutter_background_geolocation#927]
## Your Environment
* Plugin version : 4.8.5
* Platform: Android
* OS version: 12
* Device manufacturer / model: Pixel3 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale
    en-CA)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      reset: true,
      headers: {"User-Agent": "TQT (${_appConfig.getVersionNumber()}) ${Platform.isAndroid ? 'Android' : 'iOS'}"},
      url: _currentSyncUrl, //nullable
      httpRootProperty: "journey",
      locationTemplate: '{"latitude":"<%= latitude %>00", "longitude":"<%= longitude %>00"}',
      authorization: bg.Authorization(
        accessToken: accessToken,
        expires: _httpService?.melcc?.accessToken?.expiresIn,
        refreshToken: _httpService?.melcc?.melccLogin?.refreshToken,
        refreshUrl: "$baseUrl/login/access-token?charset=UTF-8&format=json&version=v1",
        refreshHeaders: {},
        refreshPayload: {
          "refresh_token": "{refreshToken}",
          "client_id": "${_httpService?.melcc?.melccLogin?.clientId ?? ''}",
          "redirect_url": "$baseUrl/rest",
          "application_id": "${httpHost.appId}",
          "response_type": "token",
          "scope": "all"
        },
      ),
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      autoSync: true,
      autoSyncThreshold: 5,
      distanceFilter: 100,
      isMoving: false,
      enableHeadless: true,
      stopOnTerminate: false,
      stopOnStationary: false,
      startOnBoot: true,
      disableMotionActivityUpdates: true,
      showsBackgroundLocationIndicator: true,
      debug: _appConfig.isDebug,
      stationaryRadius: 25,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    );


 Then, I use setConfig on each onLocation event to override the default timestamp 

bg.BackgroundGeolocation.setConfig(
          bg.Config(
            extras: {
              "url": _currentSyncUrl,
              "timestamp": DateTime.now().toIso8601String(),
            },
          ),
        );

```

## Expected Behavior
If the value are saved to the database (offline or autoSync is false) and sent to server later, the plugin should not try to send its recorded timestamp since it's not in the locationTemplate, it's should append the extras to coordinates and that's it. I would expect that the 'extras' and 'locationTemplate' be used in the same manners as when autoSync is true. 

## Actual Behavior
The extras locationTemplate don't seems to get used when the location was saved to the database while offline or not auto-synching. Because the original timestamp is sent and the one in the extras is ignored because the server refuse them since they are 5 hours later than the actual time. 

## Context
Since there is not mechanism in the plugin to adjust the value of timestamp, I'm trying to override the timestamp to send one that represent the time on the our server. 

I tried to remove the default timestamp by omitting it from my locationTemplate, I'm also providing extras with a custom timestamp for each Location, I would be able to pass my own timestamp value to my server.  Since "[Config.extras] are appended to each recorded location and persisted to the database record".    It's not perfect because I actually have the timestamp corresponding the le last onLocation event, my that would be good enough if it was working as expected. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version : latest

You must provide the *exact* version you're using.  "*lastest*" is meaningless for future visitors of this issue.

**Comment by christocracy** [comment]
By the time the `onLocation` event fires, the plugin has already rendered the current `locationTemplate` and inserted that JSON into its SQLite database.  Those `extras` you're applying to `setConfig` will only apply to the **NEXT** recorded location, some time in the future.

Why are you even manually apply a `timestamp`?  The `locationTemplate` already includes a `<%= timestamp >%>` variable.

**Comment by unYannickFrechette** [comment]
I know the extras will apply to the next one, and that's alright for me.  I forgot to mention I set the first timestamp just before the start() method is triggered.  

> Why are you even manually apply a timestamp? The locationTemplate already includes a <%= timestamp >%> variable.

But if I use the locationTemplate to provide the timestamp,  I get the plugin default timestamp that does not correspond to the server timezone.  I need a timestamp  that fits a specific timezone,  that's just how the backend was build and it seems like a no-go to ask for change. 

I ask in another issues if there was a way to have a modified timestamp and from the answer I had, I assumed it to be impossible.  

But why the plugin try to force its timestamp after a couple of location where sent to the local database, that the question because my workaround was playing alright until I delayed the autosync or went offline ?

**Comment by christocracy** [comment]
>I get the plugin default timestamp that does not correspond to the server timezone

It's not the "Plugin timestamp" -- it's the timestamp of where in the world *the device* is.  What you need to do is provide the **timezone** *of the device* in `Config.params`.  Your server will then be able to compute its desired timestamp relative to the device's timezone.

The plugin is not "forcing" any timestamp.  You've not provided `timestamp` in your `locationTemplate`.

The only timestamp I see being generated is from your own code:

```javascript
bg.Config(
            extras: {
              "url": _currentSyncUrl,
              "timestamp": DateTime.now().toIso8601String(),
            },
          ),
```

**Comment by unYannickFrechette** [comment]
ok, so after more investigation in the database record and the result of the sync() method, I found out the the geofence I use to detect the arrival of the vehicle was saved without custom timestamp.  

 So setting the persistence to only location seems to fix the issues where some http call are sent with the wrong format of timestamp. 

Does it make sense ?  I didn't think geofence event were sent as location to the url.  

( By the way, I think the doc needs a refresh for the sync method , there's no call back as parameter anymore right? )

**Comment by christocracy** [comment]
Perhaps you’re interested in Config.geofenceTemplate?

**Comment by unYannickFrechette** [comment]
I guess that would also have fixed the problem yes.  But I don't think I need to persist the geofence anyway.  But I'll make sure to take a look if I found out we need the geofence. 

Thanks.
