### ISSUE TITLE
How to check http request body?

### ISSUE THREAD

**Issue by choim4389** [transistorsoft/flutter_background_geolocation#929]
* Plugin version: 4.8.7
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung/s20

Is there a way to check request body when using custom `locationTemplate`?
`onHttp()` shows only response, so It's hard to debug when receive response with status 400.

or

Is there a way to send data via formData?

**Comment by christocracy** [comment]
Network requests can easily be inspected in *Android Studio App Inspector*.

1.  Run your app with `flutter run`
2.  Open your Flutter app's `/android` folder with *Android Studio*.
3. Open *App Inspection* (*View -> Tool Windows-> App Inspection*)
<img width="743" alt="Screenshot 2023-01-26 at 2 11 22 PM" src="https://user-images.githubusercontent.com/14999/214928559-5bef3321-2bad-4d6f-ac75-755d0894f042.png">

4. Connect the *App Inspector* to your running app.

<img width="976" alt="Screenshot 2023-01-26 at 2 13 45 PM" src="https://user-images.githubusercontent.com/14999/214928755-e41e19a8-278b-483e-bfd8-43c2090041d8.png">

5.  Select the *Network Inspector* tab.  Click the *Attach to Live* button on the right-hand side of toolbar.

<img width="1065" alt="Screenshot 2023-01-26 at 2 18 33 PM" src="https://user-images.githubusercontent.com/14999/214929411-61133544-d39d-4b48-8fd1-ebcb5f394f2e.png">

6.  Observe network requests in the timeline.  Click the timeline where network activity occurred -- the requests during that period will appear in another pane.  **NOTE**:  it can take some clicking in the timeline before the requests pane gets populated.

<img width="1729" alt="Screenshot 2023-01-26 at 2 21 26 PM" src="https://user-images.githubusercontent.com/14999/214931413-9e93dba4-fa52-49d1-a834-e80e06e23167.png">
