### ISSUE TITLE
SetConfig throws - HttpService Busy exception -- Is it normal

### ISSUE THREAD

**Issue by yashhema** [transistorsoft/flutter_background_geolocation#931]
## Your Environment
* Plugin version:4.8.5
* Platform: iOS or Android -IOS
* OS version: Windows Emulator
* Device manufacturer / model: Emulator - Pixel 4 xl
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
    • Flutter version 3.3.0 on channel stable at D:\SMSBApp\.fvm\flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (5 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\bhard\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.74.1)
    • VS Code at C:\Users\bhard\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.76
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
Initial Config - 
Normal Config -- Dont want tracking or want 

var conf =bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_LOW,

        backgroundPermissionRationale: bg.PermissionRationale(
            title:
            "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
            message:
            "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        distanceFilter: 500.0,
        stopOnTerminate: true,
        startOnBoot: false,

        foregroundService: false,
        debug: true,
        autoSync: false,
        maxDaysToPersist: 0,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE);
  
      bg.BackgroundGeolocation.ready(conf)
          .then((bg.State state) {
        if (!state.enabled) {
          bg.BackgroundGeolocation.start();
          curstate.curstatus = ObjectStateStatus.ACTIVE;
        } else {
          curstate.curstatus = ObjectStateStatus.ACTIVE;
        }
      });
      bg.BackgroundGeolocation.onLocation((bg.Location location) {
        curstate.curstatus = ObjectStateStatus.ACTIVE;
        curstate.lastknownlongi =location.coords.longitude;
        curstate.lastknownlati=location.coords.latitude;
        //updatelocationPerson(location);
      });

//Now want to update configuration 

newconf = conf = bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,

        backgroundPermissionRationale: bg.PermissionRationale(
            title:
            "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
            message:
            "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        //locationUpdateInterval: 5000,
        activityType: Config.ACTIVITY_TYPE_OTHER_NAVIGATION,
        distanceFilter: distance,
        stopOnTerminate: true,
        startOnBoot: false,
        heartbeatInterval: 300,
        debug: true,
        autoSync: true,
        autoSyncThreshold: 1,
        locationsOrderDirection: "DESC",
        maxDaysToPersist: 1,
        url: serverurl,
        httpTimeout: 160000,
        params: httpcallableformat,
        headers: {
          "Authorization": "Bearer ${authtoken}"
        },

        logLevel: bg.Config.LOG_LEVEL_VERBOSE);

//await BackgroundGeolocation.stop();
    var s = await bg.BackgroundGeolocation.setConfig(newconf);
    bg.BackgroundGeolocation.sync();

// With a second exception - platform execption is thown

E/flutter (18514): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(timeout, null, null, null)
E/flutter (18514): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (18514): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (18514): <asynchronous suspension>
E/flutter (18514): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:485:35)
E/flutter (18514): <asynchronous suspension>
E/flutter (18514): #3      BackgroundGeolocation.sync 
## Expected Behavior

No exception should be thrown

## Actual Behavior

Exception is thrown on at the time of setting new configuration

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
D/TSLocationManager(18514): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [autoSync, desiredAccuracy, distanceFilter, headers, maxDaysToPersist, params, url]
I/TSLocationManager(18514): [c.t.l.http.HttpService flush] 
I/TSLocationManager(18514): ╔═════════════════════════════════════════════
I/TSLocationManager(18514): ║ HTTP Service (count: 1)
I/TSLocationManager(18514): ╠═════════════════════════════════════════════
D/TSLocationManager(18514): [c.t.l.service.AbstractService start] 
D/TSLocationManager(18514):   🎾  BackgroundTaskService [eventCount: 1]
I/TSLocationManager(18514): [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 3
D/TSLocationManager(18514): [c.t.l.data.sqlite.b first] 
D/TSLocationManager(18514):   ✅  Locked 1 records
I/TSLocationManager(18514): [c.t.l.http.HttpService a] 
I/TSLocationManager(18514):   🔵  HTTP POST: f58f92e3-1040-482c-b7d4-8378b061a181
I/TSLocationManager(18514): [c.t.l.scheduler.ScheduleEvent onOneShot] 
I/TSLocationManager(18514): ╔═════════════════════════════════════════════
I/TSLocationManager(18514): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager(18514): ╠═════════════════════════════════════════════
D/TSLocationManager(18514): [c.t.l.event.TerminateEvent$a a] 
D/TSLocationManager(18514):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
W/TSLocationManager(18514): [c.t.l.http.HttpService$h onFailure] 
W/TSLocationManager(18514):   ⚠️  Response: 0, timeout
D/TSLocationManager(18514): [c.t.l.data.sqlite.b unlock] 
D/TSLocationManager(18514):   ✅  UNLOCKED: f58f92e3-1040-482c-b7d4-8378b061a181
I/TSLocationManager(18514): [c.t.l.u.BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 3
D/TSLocationManager(18514): [c.t.l.service.AbstractService finish] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
D/TSLocationManager(18514): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(18514):   🔴  BackgroundTaskService stopped
I/TSLocationManager(18514): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(18514):   ⏰ Oneshot http_flush is already pending
I/TSLocationManager(18514): [c.t.l.http.HttpService flush] 
I/TSLocationManager(18514): ╔═════════════════════════════════════════════
I/TSLocationManager(18514): ║ HTTP Service (count: 1)
I/TSLocationManager(18514): ╠═════════════════════════════════════════════
I/flutter (18514): [onHttp] status: 0, success? false, responseText: timeout
I/flutter (18514): [onHttp] status: 0, success? false, responseText: timeout
D/TSLocationManager(18514): [c.t.l.service.AbstractService start] 
D/TSLocationManager(18514):   🎾  BackgroundTaskService [eventCount: 1]
I/TSLocationManager(18514): [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 4
D/TSLocationManager(18514): [c.t.l.data.sqlite.b first] 
D/TSLocationManager(18514):   ✅  Locked 1 records
I/TSLocationManager(18514): [c.t.l.http.HttpService a] 
I/TSLocationManager(18514):   🔵  HTTP POST: f58f92e3-1040-482c-b7d4-8378b061a181
W/TSLocationManager(18514): [c.t.l.http.HttpService$h onFailure] 
W/TSLocationManager(18514):   ⚠️  Response: 0, timeout
I/flutter (18514): [onHttp] status: 0, success? false, responseText: timeout
I/flutter (18514): [onHttp] status: 0, success? false, responseText: timeout
D/TSLocationManager(18514): [c.t.l.data.sqlite.b unlock] 
D/TSLocationManager(18514):   ✅  UNLOCKED: f58f92e3-1040-482c-b7d4-8378b061a181
I/TSLocationManager(18514): [c.t.l.u.BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 4
D/TSLocationManager(18514): [c.t.l.service.AbstractService finish] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
D/TSLocationManager(18514): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager(18514):   🔴  BackgroundTaskService stopped
I/TSLocationManager(18514): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager(18514):   ⏰ Oneshot http_flush is already pending
E/flutter (18514): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(timeout, null, null, null)
E/flutter (18514): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (18514): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (18514): <asynchronous suspension>
E/flutter (18514): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:485:35)
E/flutter (18514): <asynchronous suspension>
E/flutter (18514): #3      BackgroundGeolocation.sync (package:flutter_background_geolocation/models/background_geolocation.dart:628:13)
E/flutter (18514): <asynchronous suspension>
E/flutter (18514): 

</details>

**Comment by christocracy** [comment]
Yes it’s normal.  There’s nothing wrong with the http service being busy.  The problem is your server not responding.  You don’t seem to have a network connection.

> : ⚠️ Response: 0, timeout
