### ISSUE TITLE
java.lang.IncompatibleClassChangeError - Found interface com.google.android.gms.location.h,

### ISSUE THREAD

**Issue by ivangoluuk** [transistorsoft/flutter_background_geolocation#934]
I'm having this issue

## Your Environment
* Plugin version: 48.7
* Platform: just Android
* OS version: Android 13
* Device manufacturer / model: any model
* Flutter info (`flutter doctor`): Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.1 22C65 darwin-arm, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Actual Behavior

Fatal Exception: java.lang.IncompatibleClassChangeError
Found interface com.google.android.gms.location.h, but class was expected (declaration of 'com.google.android.gms.location.h' appears in base.apk)

## Steps to Reproduce

1.
2.
3.
4.

## Context

location updates using this package

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Like I said:  “search the issues **first**”

duplicate #933

**Comment by ivangoluuk** [comment]
sorry Chris
