### ISSUE TITLE
Flutter 3.7.0 update bug

### ISSUE THREAD

**Issue by osama450** [transistorsoft/flutter_background_geolocation#935]
the working fine befoir im update to 3.7 and get this error now , and app is closed

Process: com.air2o.timetracker, PID: 10159
E/AndroidRuntime(10159): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~UNUwpc7RqWJC_IIbQ11dWA==/com.air2o.timetracker-u7BMISbeWyDsPJHi4P2Smg==/base.apk!classes2.dex)
E/AndroidRuntime(10159): 	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.checkLocationSettings(Unknown Source:29)
E/AndroidRuntime(10159): 	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.execute(Unknown Source:49)
E/AndroidRuntime(10159): 	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:14)
E/AndroidRuntime(10159): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(10159): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(10159): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(10159): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(10159): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(10159): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(10159): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(10159): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(10159): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(10159): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10159): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10159): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10159): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10159): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10159): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (10159): Sending signal. PID: 10159 SIG: 9
Lost connection to device.

**Comment by christocracy** [comment]
Duplicate #933
