### ISSUE TITLE
does maxRecordsToPersist = 1 means that it will sync only latest one?

### ISSUE THREAD

**Issue by choim4389** [transistorsoft/flutter_background_geolocation#936]
I wonder how to sync with server only latest location.
And I found maxRecordsToPersist config. 

To make maxRecordsToPersist = 1 will work expected?
(PERSIST_MODE_LOCATION and url are set.)

**Comment by christocracy** [comment]
It means the plugin will maintain a meme org of only one location,

If the user disabled cellular data while driving for a period of time, you’d lose all that location data, except for the last recorded location.

**Comment by choim4389** [comment]
@christocracy thanks. So the point I wonder is the last recorded location will be overridden with new one or won't. (when cellular disabled but location service keep updating.)

**Comment by christocracy** [comment]
> So the point I wonder is the last recorded location will be overridden

Yes.  Old is deleted.  New is inserted.
