### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [transistorsoft/flutter_background_geolocation#94]
Does onLocation and onMotionchange works in background state for ios

## Your Environment
* Plugin version:1.0.9
* Platform: iOS 
* OS version:Mac OS
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```
    bg.BackgroundGeolocation.start();

bg.BackgroundGeolocation.ready(bg.Config(
       // debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: 30,
        locationUpdateInterval: 1800000,
        preventSuspend: true,
        stopOnTerminate: false,
        stopOnStationary: true,
        useSignificantChangesOnly: true,
        disableMotionActivityUpdates: true,
        startOnBoot: true,
        enableHeadless: true,
        heartbeatInterval: 1800
    )).then((bg.State state) {
      print('[ready] ${state.toMap()}');
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
void _onLocation(bg.Location location) async{

 print('[location] - $location');
 final prefs = await SharedPreferences.getInstance();
 bool _provider= prefs.getBool("provider1234");
 if (_provider != null && _provider == true) {
   updateLocation(location.coords.latitude, location.coords.longitude);
//   Fluttertoast.showToast(msg: (_provider.toString() + "  mmmm"));
}
 }
 void _onMotionChange(bg.Location location) async{
 print('[motionchange] - $location');
 final prefs = await SharedPreferences.getInstance();
 bool _provider= prefs.getBool("provider1234");
 if (_provider != null && _provider == true) {
   updateLocation(location.coords.latitude, location.coords.longitude);
  // Fluttertoast.showToast(msg: (_provider.toString() + "  mmmmm"));

 }
 }

## Actual Behavior

Not getting things as expected ex:   print('[location] - $location');
not printed
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Does onLocation and onMotionchange works in background state for ios

Yes.  I just tested this on my *real* iPhoneX, by playing a debug sound effect in my `onLocation` event-handler.  

```dart
void _onLocation(bg.Location location) {
    print('[onLocation] - $location');

    bg.BackgroundGeolocation.playSound(1503);  // <-- play a debug sound-effect        
  }
```

I set `distanceFilter: 0`, execute `changePace(true)` and walked around the house with the screen off (ie: app in background).

The sound-effect plays each time a location is recorded.
