### ISSUE TITLE
Can't run the app on android in debug mode : LICENSE VALIDATION ERROR

### ISSUE THREAD

**Issue by achrafroui** [transistorsoft/flutter_background_geolocation#942]
## Your Environment
* Plugin version: ^4.8.7
* Platform:  Android
* OS version: 
* Device manufacturer / model: OPPO
[✓] Flutter (Channel stable, 3.7.0, on macOS 11.7.2 20G1020 darwin-x64, locale fr-TN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ Cannot execute bin/java to determine the version
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[!] Android Studio
    ✗ Android Studio not found at /Users/admin/Library/Android/sdk/Contents
[✓] VS Code (version 1.74.3)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Running the plugin on android in Debug Mode
## Actual Behavior

I am running the app on android in debug mode but a notification tells me LICENSE VALIDATION ERROR - failed to find license key
## Steps to Reproduce

1. run without debugging 
2.
3.
4.

## Debug logs
Launching lib/main.dart on CPH2203 in debug mode...
lib/main.dart:1
[flutter_background_geolocation] Purging debug resources in release build
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
D/FlutterGeolocator(11017): Attaching Geolocator to activity
D/FlutterGeolocator(11017): Creating service.
D/FlutterGeolocator(11017): Binding to location service.
D/FlutterLocationService(11017): Creating service.
D/FlutterLocationService(11017): Binding to location service.
D/FlutterGeolocator(11017): Geolocator foreground service connected
D/FlutterGeolocator(11017): Initializing Geolocator services
D/FlutterGeolocator(11017): Flutter engine connected. Connected engine count 1
E/AndroidRuntime(11017): FATAL EXCEPTION: pool-12-thread-2
E/AndroidRuntime(11017): Process: com.winou.android.app, PID: 11017
E/AndroidRuntime(11017): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~Vu5SaYk9MeXicwqnPd_iTg==/com.winou.android.app-pAXGxA60QXVRwTQjqZfAkA==/base.apk)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.location.TSLocationManager.removeLocationUpdates(Unknown Source:41)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:100)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
E/AndroidRuntime(11017): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(11017): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(11017): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(11017): 	at java.lang.Thread.run(Thread.java:1012)
getVM: (112) Service has disappeared
Exited
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It’s nothing to do with license warning.  That’s expected.

please search issues first before posting.

duplicate #933

also see the CHANGELOG (updated today.)
