### ISSUE TITLE
FATAL EXCEPTION: pool-21-thread-5

### ISSUE THREAD

**Issue by Vish88781** [transistorsoft/flutter_background_geolocation#943]
I am using your plugin for 2 years with flutter, but just a few days back when i update flutter  3.7.0 ,    gradle version 7.6 , and  JDK --19.0.2the above exception terminate the app.  and i also downgrade all the things but error not gone

## Your Environment
* Plugin version:  4.8.7
* Platform: Android
* Device  Samsung A30
* Flutter info (`flutter doctor`): Flutter  version detail [√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-VG)
    • Flutter version 3.7.0 on channel stable at C:\flutter_windows_3.3.10-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (9 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

## Expected Behavior
Data insert through plugin 

## Steps to Reproduce

1.
[flutter_background_geolocation] Purging debug resources in release build
*****************************************************
* [WARNING] background-geolocation requires a maximum googlePlayServicesLocationVersion of 20.0.0 due to breaking changes in v21
* googlePlayServicesLocationVersion has been overridden to 20.0.0
*****************************************************

2.
I/flutter (21956): ********* startBackgroundTask: 1
I/ViewRootImpl@bfb6527[MainActivity](21956): MSG_WINDOW_FOCUS_CHANGED 0 1
I/flutter (21956): [start] success: [State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: 0, distanceFilter: 10.0, odometer: 0.0, schedulerEnabled: false, foregroundService: true]
D/AppCompatDelegate(21956): Checking for metadata for AppLocalesMetadataHolderService : Service not found
I/g.ubitech.sale(21956): Background young concurrent copying GC freed 55055(2692KB) AllocSpace objects, 18(1780KB) LOS objects, 46% free, 5137KB/9528KB, paused 685us total 175.884ms

3.

FATAL EXCEPTION: pool-21-thread-5
E/AndroidRuntime( 8251): Process: Package Name, PID: 8251
E/AndroidRuntime( 8251): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~n0waUNnew-vDP6AtRcPjkQ==/Package Name-CkbyWG4_MCPOE9S-swqAXQ==/base.apk)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
E/AndroidRuntime( 8251): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8251): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8251): 	at java.lang.Thread.run(Thread.java:923)
D/AppCompatDelegate( 8251): Checking for metadata for AppLocalesMetadataHolderService : Service not found
D/AndroidRuntime( 8251): Shutting down VM
E/AndroidRuntime( 8251): FATAL EXCEPTION: main
E/AndroidRuntime( 8251): Process: Package Name, PID: 8251

**Comment by christocracy** [comment]
Duplicate #933 

please *search* issues *before* posting.

**Comment by Vish88781** [comment]
@christocracy Thanks !!
