### ISSUE TITLE
[Question] Is it possible to turn on/off background location service on push notification received?

### ISSUE THREAD

**Issue by HadiHassan22** [transistorsoft/flutter_background_geolocation#945]
First of all sorry for not adhering to the issue template but since this is question and not a bug report I don't think the template is necessary.

As the title states, I'm wondering if its possible to turn on/off the background geolocation service through a push notification received callback. I know this can be done if the notification is tapped since it brings the app to the foreground but I'm wondering if the service can be toggled in the background by just receiving a notification.

**Comment by christocracy** [comment]
You're free to execute `BackgroundGeolocation.stop()` within any context of your own application code.

```dart
void yourOnPushNotificationMethod(notification) {
  bool someCondition = true;  // <-- your logic here
  if (someCondition) {
    BackgroundGeolocation.stop();
  }
}
```

**Comment by HadiHassan22** [comment]
Thanks for the swift reply very much appreciated!

**Comment by dJani97** [comment]
@HadiHassan22 I was wondering about the same thing - could you implement this, and does it work without tapping the notification?

**Comment by HadiHassan22** [comment]
> @HadiHassan22 I was wondering about the same thing - could you implement this, and does it work without tapping the notification?

I did not implement this since we're currently using onesignal for push notifications and onesignal does not support this functionality within their flutter SDK. We are planning on moving to Firebase Cloud Messaging which supports push notification received handlers. So if you're using using FCM check [this](https://firebase.google.com/docs/cloud-messaging/flutter/receive#background_messages) out. Specifically the background messages section. Then you can implement your own logic similar to to this issue's answer.

**Comment by christocracy** [comment]
>onesignal does not support this functionality within their flutter SDK

Doesn't support what?  Executing a `callback` function?
