### ISSUE TITLE
Could not find any matches for com.transistorsoft:tsbackgroundfetch

### ISSUE THREAD

**Issue by iBuaSpaz** [transistorsoft/flutter_background_geolocation#947]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: Windows 11
* Device manufacturer / model: - testing device
* Flutter info (`flutter doctor`): 
* 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22621.1105], locale da-DK)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.75.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

* Plugin config: build.cradle
```dart <-- Syntax highlighting: DO NOT REMOVE -->

buildscript {
    ext.kotlin_version = '1.6.10'
    ext {
        compileSdkVersion   = 31                // or latest
        targetSdkVersion    = 31                // or latest
        appCompatVersion    = "1.4.2"           // or latest
    }    
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }        
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

## Expected Behavior
Should compile

## Actual Behavior
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/D:/Flutter programmer/mytestapp/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/D:/Flutter programmer/mytestapp/android/app/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
     Required by:
         project :app > project :flutter_background_geolocation

## Steps to Reproduce

Unsure why it happens to me at all, so dont know how to reproduce.

## Context
Building a app thats important it can run/update in background

**Comment by christocracy** [comment]
You pasted the required `maven` url in the **wrong place**.  it goes within **`allProjects`**.

Carefully review the [Setup Guide](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidbuildgradle)
