### ISSUE TITLE
Crash in application

### ISSUE THREAD

**Issue by iBuaSpaz** [transistorsoft/flutter_background_geolocation#948]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: Windows 11
* Device x64 pixel 6, API 31 (crash on phone too)
* Flutter info (`flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale da-DK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.75.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
* Plugin config:
```dart 
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    as bg;
import 'dart:async';

class GpsControl {
  final StreamController<bg.Location> locationStreamController =
      StreamController<bg.Location>();
  Stream<bg.Location> get locationStream => locationStreamController.stream;

  void initGpsData() {
    bg.BackgroundGeolocation.onLocation((bg.Location location) {
      locationStreamController.add(location);
    });

    bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
      locationStreamController.add(location);
    });

    bg.BackgroundGeolocation.onProviderChange(
        (bg.ProviderChangeEvent event) {});

    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 10.0,
            stopTimeout: 5,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            enableHeadless: true,
            heartbeatInterval: 60,
            foregroundService: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });
  }

  void disposeGpsData() {}
}
```

## Expected Behavior
Should work ? 👍 
Im considering buying a license for this for my app, if it works.

## Actual Behavior
App closes on crash

## Steps to Reproduce

1.
2.
3.
4.

## Context

Init the GPS, it worked before on older version of flutter.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
D/TSLocationManager(23303): [c.t.f.b.streams.StreamHandler onListen] location
D/TSLocationManager(23303): [c.t.f.b.streams.StreamHandler onListen] motionchange
D/TSLocationManager(23303): [c.t.f.b.streams.StreamHandler onListen] providerchange
W/DynamiteModule(23303): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
W/Settings(23303): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager(23303): [c.t.locationmanager.util.c g] 
D/TSLocationManager(23303):   ℹ️  LocationAuthorization: Permission granted
W/Settings(23303): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/DynamiteModule(23303): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(23303): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
I/ample.myapp(23303): Background concurrent copying GC freed 49289(2803KB) AllocSpace objects, 2(104KB) LOS objects, 49% free, 5980KB/11MB, paused 821us,62us total 202.119ms
I/Ads     (23303): This request is sent from a test device.
W/ample.trafikap(23303): ClassLoaderContext shared library size mismatch. Expected=3, found=4 (PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*2058259660]#PCL[/system/framework/com.android.media.remotedisplay.jar*3472798122]#PCL[/system/framework/com.android.location.provider.jar*3633238673]} | PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*2058259660]#PCL[/system/framework/com.android.media.remotedisplay.jar*3472798122]#PCL[/system/framework/com.android.location.provider.jar*3633238673]#PCL[/system_ext/framework/androidx.window.sidecar.jar*3539530913]})
D/nativeloader(23303): classloader namespace configured for unbundled product apk. library_path=/product/priv-app/PrebuiltGmsCore/lib/x86_64:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64:/product/lib64:/system/product/lib64
D/FirebaseAuth(23303): Notifying id token listeners about user ( ....... ).
I/WebViewFactory(23303): Loading com.google.android.webview version 91.0.4472.114 (code 447211487)
V/NativeCrypto(23303): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...
W/ample.trafikap(23303): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/ample.trafikap(23303): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/ample.trafikap(23303): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/ample.trafikap(23303): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/ample.trafikap(23303): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/ample.trafikap(23303): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
I/ProviderInstaller(23303): Installed default security provider GmsCore_OpenSSL
I/cr_VariationsUtils(23303): Failed reading seed file "/data/user/0/com.example.myapp/app_webview/variations_seed_new"
I/cr_VariationsUtils(23303): Failed reading seed file "/data/user/0/com.example.myapp/app_webview/variations_seed"
I/cr_VariationsUtils(23303): Requesting new seed from IVariationsSeedServer
I/cr_LibraryLoader(23303): Loaded native library version number "91.0.4472.114"
I/cr_CachingUmaRecorder(23303): Flushed 5 samples from 5 histograms.
W/ample.trafikap(23303): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
D/GASS    (23303): Clearcut logging disabled
D/zzaqe   (23303): File /data/user/0/com.example.myapp/cache/1658186039475.dex not found. No need for deletion
W/ample.trafikap(23303): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
I/TSLocationManager(23303): - Enable: true → true, trackingMode: 1
zw==/base.apk!classes6.dex)
E/TSLocationManager(23303):     at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:123)
E/TSLocationManager(23303):     at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:74)
E/TSLocationManager(23303):     at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
E/TSLocationManager(23303):     at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
E/TSLocationManager(23303):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TSLocationManager(23303):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TSLocationManager(23303):     at java.lang.Thread.run(Thread.java:920)
I/Process (23303): Sending signal. PID: 23303 SIG: 9
Lost connection to device.
```

</details>

**Comment by christocracy** [comment]
What are you doing with this "`NativeCrypto`"?

>V/NativeCrypto(23303): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...

I suspect you're doing something in one of the plugin's event-handlers that's causing this crash.

Show me your code.

**Comment by christocracy** [comment]
And what's this?

>W/ample.trafikap(23303): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)

**Comment by christocracy** [comment]
Show me what you're doing with this `locationStreamController`

**Comment by iBuaSpaz** [comment]
> Show me what you're doing with this `locationStreamController`

nothing yet, im only calling GpsControl().initGpsData();

later i would add it to get the latitude/longitude from the map class, but its not in yet, only does this one call to the GpsControl class.

NativeCrypto i think is part of Firebase, not sure, but it was also crashing before i added firebase.
Accessing hidden method Ljava/security.... appears to also be Firebase, just Firestore im also using this.

**Comment by christocracy** [comment]
Show me a full, unfiltered `$ adb logcat` of this crash

**Comment by iBuaSpaz** [comment]
you can find it here:

https://webeta.dk/storage/log.txt

**Comment by iBuaSpaz** [comment]
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  circular_menu: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  package_info: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_background_geolocation: ^4.9.0
  background_fetch: ^1.1.4
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_local_notifications: ^13.0.0
  flutter_map_location_marker: ^5.2.0+2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  device_info_plus: ^8.0.0
  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

**Comment by christocracy** [comment]
Also see the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#490--2023-02-01) for `v4.9.0`

**Comment by christocracy** [comment]
One of your plugin's is importing `play-services-location:21.+`.  You can see which one by running this:

```
$ cd android
$ ./gradlew app:dependencies
```
search for `play-services-location` in any of the output trees.


`play-services-location` did a **breaking change** in `v21`.  You must configure the `ext` var in your `android/build.gradle` with `playServicesLocationVersion = "21.0.1"`

**Comment by iBuaSpaz** [comment]
Adding playServicesLocationVersion = "21.0.1" did the trick, thanks.

After the app is finished i will come buy a license if its truely saves power in background tasks, as this is important for my app.

I must say i dont think i would have ever found this, so thanks again.

**Comment by christocracy** [comment]
When you have a crash, you always view the unfiltered `$ adb logcat` to get the full stacktrace.

Once you have a stracktrace, you search the issues here for the reason, where you'd find `java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient`.

Searching the issues here, you'd find this issue posted [a number of times](https://github.com/transistorsoft/flutter_background_geolocation/issues?q=java.lang.IncompatibleClassChangeError%3A+Found+interface+com.google.android.gms.location.FusedLocationProviderClient)
