### ISSUE TITLE
Geofence Exit event not capturing properly

### ISSUE THREAD

**Issue by saranyalekshmanan** [transistorsoft/flutter_background_geolocation#953]
## Your Environment
* Plugin version: 4.8.7
* Platform: iOS or Android : Both
* OS version: 
* Device manufacturer/model: Nokia and IPhone
* Flutter info (`flutter doctor`): 
* Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22623.1255], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.13)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development
      with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.3)
[√] Connected device (5 available)
[√] HTTP Host Availability
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void initBackgroundCapture() async {
    // 2.  Configure the plugin
    //

    EmployeeInfo user = await fetchUser();

    PreferenceManager prefs =
        Get.find<PreferenceManager>(tag: (PreferenceManager).toString());
    String accessToken = await prefs.getString(Constants.token);
    String refreshToken = await prefs.getString(Constants.refreshToken);
    BackgroundGeolocation.onAuthorization((p0) {
      log('On Authorize : ${p0.toString()}');
    });
    BackgroundGeolocation.onHttp((HttpEvent event) {
      int status = event.status;
      bool success = event.success;
      String responseText = event.responseText;

      log('[onHttp] status: ${status}, success? ${success}, responseText: ${responseText}');
    });
    BackgroundGeolocation.ready(Config(
            reset:
                true, // <-- lets the Settings screen drive the config rather than re-applying each boot.
            // Convenience option to automatically configure the SDK to post to Transistor Demo server.
            //transistorAuthorizationToken: token,
            // Logging & Debug
            debug: true,
            persistMode: -1,
            logLevel: Config.LOG_LEVEL_VERBOSE,
            locationAuthorizationRequest: "WhenInUse",
            // Geolocation options
            url: "http://api.hammaem.com/api/MidTimeSheet",
            authorization: Authorization(
                strategy: "JWT",
                accessToken: accessToken,
                refreshToken: refreshToken,
                refreshUrl:
                    "${BuildConfig.instance.config.systemPortalUrl}v1/Identity/Refresh",
                refreshPayload: {
                  "token": accessToken,
                  "refreshToken": refreshToken
                }),
            method: 'POST',
            // Activity recognition options
            stopTimeout: 5,
            backgroundPermissionRationale: PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            // HTTP & Persistence
            autoSync: true,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: false,
            preventSuspend: true,
            geofenceProximityRadius: 100,
            geofenceInitialTriggerEntry: true,
            notificationText: 'Hammadi Notification',
            notificationTitle: 'Hammadi',
            allowIdenticalLocations: false,
            disableMotionActivityUpdates: true,
            disableLocationAuthorizationAlert: true,
            httpRootProperty: '.',
            params: {"employeeId": user.staffId},
            geofenceTemplate:
                '{ "latitude":"<%= latitude %>", "longitude":"<%= longitude %>", "deviceType":"<%= geofence.action %>","updatedAt" : "<%= timestamp %>","uuid" : "<%= uuid %>" }'))
        .then((var state) async {
      log(state.toMap().toString());
    });
  }

void addGeoFenceAndStart(double latitude, double longitude) async {
    
      BackgroundGeolocation.addGeofence(Geofence(
        identifier: "HammadiHome",
        radius: 100,
        latitude: latitude,
        longitude: longitude,
        notifyOnEntry: true,
        notifyOnExit: true,
      )).then((bool success) {
        log('[addGeofence] success');
      }).catchError((onError) {
        log('Error While Adding Geo-fence : ${onError.toString()}');
      });
    

    BackgroundGeolocation.startGeofences().then((var state) async {
      log('Geo Fence started ${state.toString()}');
    });
  }

  void stopGeoFence() async {
    BackgroundGeolocation.removeGeofence("HammadiHome");
  }
```

## Expected Behavior
When we go out geo fence, Exit event should fire.

## Actual Behavior
1. Android: Exit event not firing correctly, it is firing after 1000 meters only in Android
2. IOS: The exit event sometimes fires if we went out of the geofence 200 meters and that also with the wrong location(it is firing exit event with the geofence center location - I have attached the data, Please check.).
3. IOS - Sometimes Exit event not firing correctly, it is firing after 1000 meters only

## Steps to Reproduce

1.  Please test with above configuration using Android and IPhone
2.
3.
4.

## Context
Testing GeoFence with Android and IOS

Please find the attached image for the logs

- ios XCode 
![image](https://user-images.githubusercontent.com/32639374/218254796-d922c6c5-7a73-4abe-a1d0-e7819d8203d8.png)
logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> locationAuthorizationRequest: "WhenInUse

Geofencing **requires** *Always* authorization.

> Android: Exit event not firing correctly, it is firing after 1000 meters only in Android

There is no guarantee of when a geofence will fire.  If it fires, it fired correctly.  Different Android devices fire better / worse.  Nokia tend to be worse.  See https://dontkillmyapp.com

> radius: 100,

The minimum reliable radius is 200 meters.

> IOS: The exit event sometimes fires if we went out of the geofence 200 meters

This is normal and expected iOS performance.

> geofenceProximityRadius: 100,

You do not understand this option.  Read the api docs.  The plugin won’t even allow you to set it below `1000` in order to prevent you “shooting yourself in the foot”.  This option isn’t even used when the number of registered geofences is below the OS maximum (100 for Android; 20 for iOS).

**Comment by christocracy** [comment]
Also, geofences are handled completely by the OS.  The plugin has nothing to do with the accuracy of when / if a geofence fires.  The plugin merely provides an api to *register* those geofences with the OS.  If a geofence fires at all, that Is all the verification you need that it worked.

**Comment by saranyalekshmanan** [comment]
Understood. But Enter Event is capturing perfectly. I closed the app, went out of the geofence, and entered nearer to the geofence center location at that time it is capturing correctly.

**Comment by christocracy** [comment]
- It is normal for *ENTER* event to fire almost exactly at the edge of the geofence. 
- It is normal for the *EXT* event to fire about 200 meters outside the geofence.

As I wrote above:
>geofences are handled completely by the OS. The plugin has nothing to do with the accuracy of when / if a geofence fires. The plugin merely provides an api to register those geofences with the OS. If a geofence fires at all, that Is all the verification you need that it worked.

(*red = EXIT, *green* = ENTER, *yellow = DWELL*)

<img width="1144" alt="Screenshot 2023-02-13 at 9 12 33 AM" src="https://user-images.githubusercontent.com/14999/218481504-f5cea700-4461-44b4-bc45-2c5d5784ce0a.png">
