### ISSUE TITLE
Location Issues

### ISSUE THREAD

**Issue by adn9990** [transistorsoft/flutter_background_geolocation#954]
## Your Environment
* Plugin version: 4.8.1
* Platform: Android
* OS version: 12
* Device manufacturer / model: Nothing Phone 1
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Should send location on certain meters when driving or walking

## Actual Behavior
Sending heartbeat location when still on a location

## Steps to Reproduce

  1. Getting multiple duplicate locations like this, Is there any way to stop this
  ![image](https://user-images.githubusercontent.com/89911955/218273960-f49b7072-7472-4844-9c3d-6a0b9e15b2ef.png) 
  2. Applied Distance filter :10,  MOTIONCHANGE,  ACTIVITYCHANGE, is enabled but only logs are showing no location is sending while driving even heartbeat is not working while driving, When stop heartbeat get start

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Device manufacturer / model: Nothing Phone 1

What does this mean?  see https://dontkillmyapp.com

Are you observing the plugin logs?  See wiki “Debugging”.

**Comment by adn9990** [comment]
Can you please tell me solution of my first problem.
Application is working in background even i am getting logs regularly but location update is not sending to server

**Comment by christocracy** [comment]
I have no idea what your problem is.  You’re not providing any information (logs, device model).

**Comment by adn9990** [comment]
Can you please tell me how can i stop duplicate location on same time

**Comment by christocracy** [comment]
> how can i stop duplicate location on same time

I have no idea.  You’ve not provided any Config or code.  This is not magic.
