### ISSUE TITLE
Unresolved reference : Java to Kotlin Project 

### ISSUE THREAD

**Issue by yzengin** [transistorsoft/flutter_background_geolocation#957]
Hello, I am editing the java part in the flutter_background_geolocation example project according to kotline.
But after fully integrating the relevant parts into my kotlin project, I am getting these errors.

Please help me!

![image](https://user-images.githubusercontent.com/41122625/218764283-27b2ee95-ec20-4558-8fb9-d5753da9f6a8.png)

Application file 
![image](https://user-images.githubusercontent.com/41122625/218764429-87fc85fa-bbaa-4035-8a80-5075a1c0e28b.png)

MainActivity File
![image](https://user-images.githubusercontent.com/41122625/218764494-a6199dc0-b084-422d-82e1-c23fe5aa6418.png)

**Comment by christocracy** [comment]
Code / logs can easily be marked up.  See [Github Syntax Highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by yzengin** [comment]
## Your Environment
* Plugin version: 4.8.2+44
* Platform: Android
* OS version: 12
* Device manufacturer / model: Nothing Phone
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2486], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 4.1)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

I am editing the java part in the flutter_background_geolocation example project according to kotline.
But after fully integrating the relevant parts into my kotlin project, I am getting these errors.

Please help me!

## Actual Behavior

I'm getting errors even though I converted the java package in the Flutter background geolocation Example file to Kotlin.

## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (20, 9): 'onCreate' hides member of supertype 'FlutterApplication' and needs 'override' modifier
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (25, 36): Unresolved reference: Builder
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (31, 32): Unresolved reference: Builder
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (10, 33): Unresolved reference: NonNull
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (11, 48): Type mismatch: inferred type is FlutterEngine? but FlutterEngine was expected
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (19, 9): 'onFlutterUiDisplayed' hides member of supertype 'FlutterActivity' and needs 'override' modifier

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 59s
Exception: Gradle task assembleDebug failed with exit code 1

</details>

**Comment by christocracy** [comment]
To implement Android's optional `StrictMode`, see the [API docs](https://developer.android.com/reference/kotlin/android/os/StrictMode) for the *Kotlin* example

**Comment by yzengin** [comment]
**Added Strict Code**
`
import android.Manifest
import android.content.ComponentName
import android.content.Intent
import android.location.Location
import android.os.StrictMode
import android.util.Log
import androidx.core.content.ContextCompat
import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation
import com.transistorsoft.locationmanager.adapter.TSConfig
import com.transistorsoft.locationmanager.adapter.callback.TSBeforeInsertBlock
import com.transistorsoft.locationmanager.device.DeviceSettings
import com.transistorsoft.locationmanager.location.TSLocation
import org.json.JSONObject
import io.flutter.app.FlutterApplication

class Application : FlutterApplication() {

    @Override
    public void onCreate() {
        StrictMode.setThreadPolicy(new <code><a docref="android.os.StrictMode.ThreadPolicy.Builder">StrictMode.ThreadPolicy.Builder</a></code>()
                .detectDiskReads()
                .detectDiskWrites()
                .detectNetwork()   // or .detectAll() for all detectable problems
                .penaltyLog()
                .build());
        StrictMode.setVmPolicy(new <code><a docref="android.os.StrictMode.VmPolicy.Builder">StrictMode.VmPolicy.Builder</a></code>()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build());
        super.onCreate();
    }
}`



**Error Build Code**

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 12): Expecting member declaration
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 17): Expecting member declaration
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 25): Expecting member declaration
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 26): Expecting member declaration
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 28): Expecting member declaration
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 55): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 56): Expecting ','
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 133): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 135): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 137): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 142): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 51): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 52): Expecting ','
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 121): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 123): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 125): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 130): Expecting an element
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (21, 28): Function declaration must have a name
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 36): Unresolved reference: new
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 41): Unresolved reference: code
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 47): Unresolved reference: a
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 56): Too many arguments for public open fun setThreadPolicy(p0: StrictMode.ThreadPolicy!): Unit defined in android.os.StrictMode
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (22, 125): Classifier 'Builder' does not have a companion object, and thus must be initialized here
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 32): Unresolved reference: new
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 37): Unresolved reference: code
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 43): Unresolved reference: a
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 52): Too many arguments for public open fun setVmPolicy(p0: StrictMode.VmPolicy!): Unit defined in android.os.StrictMode
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\Application.kt: (28, 113): Classifier 'Builder' does not have a companion object, and thus must be initialized here
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (10, 33): Unresolved reference: NonNull
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (11, 48): Type mismatch: inferred type is FlutterEngine? but FlutterEngine was expected
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (19, 9): 'onFlutterUiDisplayed' hides member of supertype 'FlutterActivity' and needs 'override' modifier

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1`





@christocracy

**Comment by yzengin** [comment]
If I remove Strict Mode, I won't have a problem with the background service, right? That's why I'm removing it.

The current error is only in the MainActivity file.
Can you look at this?

MainActivity File Code


`import android.os.Build
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity() {
    @Override
    fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine?) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }

    /**
     * This is required to solve Flutter bug booting my old Nexus 4 @4.4.4
     * https://github.com/flutter/flutter/issues/46172#issuecomment-569525397
     */
    @Override
    fun onFlutterUiDisplayed() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            reportFullyDrawn()
        }
    }
}`



**Error Build Log:**
`Parameter format not correct -
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (10, 33): Unresolved reference: NonNull
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (11, 48): Type mismatch: inferred type is FlutterEngine? but FlutterEngine was expected
e: C:\Users\Rich Design\Desktop\FlutterApps\SincapScooterProject\SincapScooterFlutter\android\app\src\main\kotlin\com\sincapscooter\MainActivity.kt: (19, 9): 'onFlutterUiDisplayed' hides member of supertype 'FlutterActivity' and needs 'override' modifier

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by christocracy** [comment]
Dude, what are you doing?  You're posting html into your Kotlin code.


```kotlin
    StrictMode.setThreadPolicy(new <code><a docref="android.os.StrictMode.ThreadPolicy.Builder">StrictMode.ThreadPolicy.Builder</a></code>()
```

`ThreadMode` is for debugging.  If you can't figure it out, just remove it all.
