### ISSUE TITLE
How to check whether distance between source and destination locations are said to be  inside or outside the circle?

### ISSUE THREAD

**Issue by Sarat-1997** [transistorsoft/flutter_background_geolocation#959]
For example if the radius is 2000m, I took source location as New york and destination as California which is about 10000m. How to  check  whether the distance between source and destination are said to be inside the circle or outside the circle?

**Comment by christocracy** [comment]
I don't think this is a question specifically for this library.  You can find a number of methods for determining this by searching the terms "*circle contains location latitude and longitude*".  It is relatively simple trigonometry.
