### ISSUE TITLE
ask: vm:entry-point

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#963]
Is 

```
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
```
important in the application in both headless functions, is it important that I enter it? or is it not negotiable?

what is its operation?

**Comment by christocracy** [comment]
It's **required** by Flutter.

If you don't declare it, the method won't exist and your app will crash,
