### ISSUE TITLE
FAILURE: Build failed with an exception 

### ISSUE THREAD

**Issue by LuisEgusquiza** [transistorsoft/flutter_background_geolocation#965]
FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #14 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > Cannot lock execution history cache (C:\laragonnew\www\flutter\flutter\milasol\appmilasol\android\.gradle\7.4\executionHistory) as it has already been locked by this process.

* Try:

**Comment by christocracy** [comment]
Your issue has nothing to do with this plug-in.

I’m not here to solve general app development problems and I’m not here to train you.
