### ISSUE TITLE
Android: Several ANRs being reported by crashlytics

### ISSUE THREAD

**Issue by viplavrawal** [transistorsoft/flutter_background_geolocation#967]
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.2 22D49 darwin-arm (Rosetta), locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config: 
* Version 4.8.3
```dart
geofenceModeHighAccuracy: true,
enableHeadless: true,
desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
distanceFilter: 0,
stopOnTerminate: false,
scheduleUseAlarmManager: true,
startOnBoot: true,
autoSync: true,
debug: false,
logLevel: Config.LOG_LEVEL_ERROR,
reset: true,
disableMotionActivityUpdates: true,
schedule: [1-7 0:01-1:00],
```

## Expected Behavior

There should be no ANRs or crashes due to operations on main thread

## Actual Behavior

Crashlytics is reporting several ANRs and crashes happening due to operations in main thread.

## Steps to Reproduce

1. Purchase the plugin and release app
2. Tested app locally on release and debug version and didn't see this issue
3. Getting several ANR issues in crashlytics due to slow operations in main thread

## Context

In most cases, these seem to be happening in the background thread on scheduler.
Please find all four logs recorded by crashlytics below.

## Debug logs

Due to the logs being too big, I had to upload files:

* Logs 1 (ANR)
[logs1.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10821602/logs1.log)

* Logs 2 (ANR)
[logs2.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10821612/logs2.log)

* Logs 3 (ANR)
[logs3.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10821654/logs3.log)

* Logs 4 (ANR)
[Logs4.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10821660/Logs4.log)

This is different, but seems to be happening due to code running in loop similar to the 4 logs above:
* Logs 5 (Crash)
[Logs5.log](https://github.com/transistorsoft/flutter_background_geolocation/files/10821665/Logs5.log)

**Comment by christocracy** [comment]
Your logs show you're inducing an infinite loop in your onError callback.

If you can't call .start(), .getCurrentPosition(), .changePace(true) in an onError callback.

The error condition that caused onError to fire isn't going to be solved by constantly requesting another location, causing onError, into infinity.

**Comment by viplavrawal** [comment]
Hi @christocracy 
I'm not sure what you mean by onError callback.
We are not using any orError callback. We do have some try/catch in place, but the sole purpose of that is to record exception in crashlytics.

Here is our pseudocode for the headless task:

```dart
switch (headlessEvent.name) {
    case Event.GEOFENCE:
      await initialiseDependencies()
      GeofenceEvent geofenceEvent = headlessEvent.event;
      if (geofenceEvent.action == 'ENTER') {
        var result = await callAPI();
        if (result != null) {
          if (checkConditionsForNotification()) {
            showNotificationForCurrentUserAndGeofence();
            trackNotificationAction();
          }
        }
      }
      break;
    case Event.SCHEDULE:
      await initialiseDependcies();
      callAPIAndUpdateGeofences();
      final location = await BackgroundGeolocation.getCurrentPosition(
          desiredAccuracy: 40, timeout: 30, samples: 3);
      bool didShowNotification = checkUsersCountryAndShowNotification(location);
      if(didShowNotification){
        trackNotificationAction();
      }
      break;
  }
```

In all most of the methods that you see above, we have try/catch surrounding some logic and there's crashlytics logging enabled in them. We are not retrying getCurrentPosition ourselves. Can you confirm if there's a default implementation in place which might be causing this issue.
Or, how exactly we can make use of this onError callback, perhaps that would be a better way to log errors.

**Comment by christocracy** [comment]
On vacation until next week.

**Comment by viplavrawal** [comment]
Hi @christocracy 
I hope you're back now, can you please check and help us in identifying if we are doing something wrong.
Thanks

**Comment by christocracy** [comment]
What is the device information from these ANR (manufacturer, model, OS version)?

**Comment by christocracy** [comment]
Also, you neglected to provide the plugin version used where these ANR came from:

## Your Environment
* Plugin version:

**Comment by christocracy** [comment]
I think there is an edge-case not handled by the plugin where:
1.  Motion-activity permission is not granted (you have `disableMotionActivityUpdates: true`)
2. Android 12/13 device in the background with only `WhenInUse` permission attempts to engage location-tracking (the OS no longer allows this).

I will address this in the next plugin update coming soon.

**Comment by choim4389** [comment]
@christocracy 

> Android 12/13 device in the background with only WhenInUse permission attempts to engage location-tracking (the OS no longer allows this).

what is this means?
It works well my Android 13 device with `WhenInUse` permission and foreground service. 
As far as I know, Android judges foreground while a foreground service is running.
