### ISSUE TITLE
[BUG?] Opening Location Permission from the inside of App

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#970]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Xioami 11 T
* Flutter info (`flutter doctor`): all right

CONFIG:
```
bg.Config(
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: bg.PermissionRationale(
              title: '************',
              message: '************',
              positiveAction: 'Cambiar a "Permitir todo el tiempo"',
              negativeAction: "Cancelar"),
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 20.0,
          disableElasticity: false,
          isMoving: true,
          stopOnTerminate: false,
          startOnBoot: true,
          reset: true,
        )
```

explanation:
1. I open the application for the first time, it asks me for a location "ALWAYS".
2. I give cancel
3. I ask the user again to activate the location "ALWAYS".
4. I click the button change location forever
5. I get the list of permissions ->
6. I don't click on any, I just go back, go back to the application.
7. It asks me again for step  Number 1.
8. but the ask for location dialog no longer appears "ALWAYS".

I don't know if it's an error, or that's how it works, but the application never asks for a location again forever.
 **that is, it no longer opens the location permissions section**

https://user-images.githubusercontent.com/67565934/222249310-ec21911c-62ff-4fe4-a499-8fa5de241d93.mp4

**Comment by christocracy** [comment]
The OS limits how many times that dialog is shown in order to not make users angry.

to learn the current state of permission, see event `onProviderChange` and method `.providerState`.
