### ISSUE TITLE
Inconsistent geofence triggers since adding maxRecordsToPersist

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#974]
## Your Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: 
* Device manufacturer / model: 
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.3, on macOS 12.5 21G72 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart-sdk/2.18.0/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/lloydabernathy/flutter. Consider adding
      /Users/lloydabernathy/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Connected device (3 available)
[✓] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.State state = await bg.BackgroundGeolocation.ready(bg.Config(
      //locationUpdateInterval: 5,
      //batchSync: true,
      //useSignificantChangesOnly: true,
      //persistMode: -1,//Only geofences are persisted
      maxRecordsToPersist: 25,
        url: "https://staging.motormouth.io/v2/user/location/flutter",
        params: {
          "profile_id" : AppData.currentProfile!.id
        },
        autoSync: true,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));

    if (!state.enabled) {
      await bg.BackgroundGeolocation.start();
      await BackgroundFetch.start();
    } else {
      return;
    }
```

## Expected Behavior
The geofence events should fire anytime a geofence is entered or exited. 

## Actual Behavior
The geofence events seem to be inconsistent when android devices are in the background state. We have consistent geofences set up at favorite locations for exit and entry alerts. Sometimes the alerts do not fire until the application has been opened by the user. Sometimes the events do not fire at all until the next time another geofence is triggered. Sometimes when a user dwells int he geofence a random entry and exit alert are fired at the same time. These issues started happening once we added the maxRecordsToPersist parameter to the config file. Could this be causing the inconsistencies we are seeing?

</details>

**Comment by lloydelvt** [comment]
![image](https://user-images.githubusercontent.com/114176300/223155523-280ce4fc-339c-4faf-bbbd-382927f17213.png)

This is an example of the strange behavior, one of our devices reported a bunch of geofence entries at the same time. No exits or other location reports in that time frame so it's not like the app thought he left and came back in.

**Comment by christocracy** [comment]
>maxRecordsToPersist parameter to the config file. Could this be causing the inconsistencies we are seeing?

No.  `maxRecordsToPersist` is purely related to `SQLite` database management, controlling the maximum number of records that can exist in the `locations` table.  It has nothing to do with geofencing / location api.

See Wiki *Debugging* and analyze your logs from the `.emailLog` method.
