### ISSUE TITLE
Question: does this package keeps whole app alive in background?

### ISSUE THREAD

**Issue by xweng1016** [transistorsoft/flutter_background_geolocation#978]
## Your Environment
* Plugin version: 4.8.7
* Platform: iOS or Android
* OS version: Any
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`): 
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 await bg.BackgroundGeolocation.ready(bg.Config(
            locationAuthorizationAlert: {
          'titleWhenNotEnabled': 'Enable location',
          'titleWhenOff': 'Enable location service',
          'instructions': 'Your location is needed to start a running session'
              ' Please allow this app to access your location information.',
          'cancelButton': 'Done',
          'settingsButton': 'Settings'
        },
            locationAuthorizationRequest: 'WhenInUse',
            disableLocationAuthorizationAlert: true,
            disableElasticity: true,
            activityType: bg.Config.ACTIVITY_TYPE_FITNESS,
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            desiredOdometerAccuracy: 10,
            distanceFilter: 0,
            // locationUpdateInterval: 3000,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: false,
            heartbeatInterval: 60,
            preventSuspend: true,
            disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,
            stopOnStationary: false,
            logLevel: bg.Config.LOG_LEVEL_INFO))
        .catchError((err) {
      print('[ready] ERROR - ${err.message}');
    });
```

## Expected Behavior

Currently, I'm using a timer that calls the api every 10 seconds while the app is minimized/display off, I want to send the latest location points to the backend. Seems working fine without any other configs right now but I'm not very sure what's causing the app to actually stay alive and continuously sending those api calls, I did notice there is always blue GPS status on the top left of the iPhone. Little insights on the possibilities would be great, thanks!

</details>

**Comment by christocracy** [comment]
> locationAuthorizationRequest: 'WhenInUse',

The only way your app stays alive in the background is if location-services are currently turned on.

Since you're using `WhenInUse`, you may only turn location-services on while your app is in the foreground via method `.changePace(true)`.

Only with `Always` authorization is the plugin able to automatically turn on location-services while the app is in the background, when the device is detected to be moving.
