### ISSUE TITLE
bg.BackgroundGeolocation.setOdometer error

### ISSUE THREAD

**Issue by omejiasq** [transistorsoft/flutter_background_geolocation#983]
## Your Environment
* Plugin version:current version
* Platform: iOS or Android: Android
* OS version:
* Device manufacturer / model:Samsung galaxy S23 Ultta
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.setOdometer(0.0);
```

## Expected Behavior

To reset the odometer value
## Actual Behavior

generates the error and does nothing
## Steps to Reproduce

1.After of this line bg.BackgroundGeolocation.setOdometer(0.0); the the program jumps to the page message_codecs.dart to this line:  throw PlatformException(code: errorCode, message: errorMessage as String?, details: errorDetails, stacktrace: errorStacktrace);
2. After of debug and run the next line jumps to platform_channel.dart page and it stop in this line:final Map<dynamic, dynamic>? result = await invokeMethod<Map<dynamic, dynamic>>(method, arguments);
3. After it jumps to bacakground_geolocation.dart page and stop in the below code:
  static Future<Location> setOdometer(double value) async {
    Map data = (await _methodChannel.invokeMapMethod('setOdometer', value))!;
    return new Location(data);
  }

## Context

only debug the program
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
setOdometer returns a Promise.  Catch the error.

**Comment by omejiasq** [comment]
How i can to do this? of this way? 
      bg.BackgroundGeolocation.setOdometer(1234.56).then((laglng) {
        print('[setOdometer] success: ');
      });

**Comment by christocracy** [comment]
That's not catching your error.

https://dart.dev/codelabs/async-await

**Comment by omejiasq** [comment]
I have this code to get the error;
      bg.BackgroundGeolocation.setOdometer(0.0).then((value) {
        print(value); // 
      }).catchError((error) {
        print('error: $error'); 
      });
So after of run this code, this return this error: I/flutter (27320): error: PlatformException(1, null, null, null) 
How can fix it?

**Comment by christocracy** [comment]
![image](https://user-images.githubusercontent.com/14999/224877837-94b33d1c-33e2-4bd8-9ba8-2a4c2a0e9f17.jpeg)

**Comment by omejiasq** [comment]
Christ, but how i can fix this? In the below code do i need to put a vale with latitude and longitude? based in the basic example of your demo, where in the code can I place this setOdometer function? maybe after the start function or at some special time?
bg.BackgroundGeolocation.setOdometer(0.0).then((value) {
print(value); //
}).catchError((error) {
print('error: $error');
});

**Comment by christocracy** [comment]
Do you know what "location permission denied" means?

Have you read what the api docs for .setOdometer say?

**Comment by omejiasq** [comment]
1. Yes, "location permission denied" is when the user not accept location permissions, but this is not the case because it has them enabled.
2. Yes i read the docs for .setOdometer , i see this link but is very short the documentation: https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/setOdometer.html. Only tell me please which requirements do i need to set to run .setOdometer or where can i to find more documentation with more examples?

**Comment by christocracy** [comment]
As the api docs say, `setOdometer` is basically the same as calling `.getCurrentPosition`.

You *think* you have location permission, but you do not.

**Comment by omejiasq** [comment]
Thank you very much by your help. Excellent!!!

**Comment by omejiasq** [comment]
Hello, is the odometer value that the plugin has by default in meters? If, for example, I want to pass this value to kilometers, should I multiply this value by 1000? And on the contrary, if a vehicle, for example, has traveled 10 thousand kilometers, should I divide 10,000/1000 thousand to convert it to meters?

**Comment by christocracy** [comment]
> is the odometer value that the plugin has by default in meters? 

Yes.  

>I want to pass this value to kilometers, should I multiply this value by 1000?

What do you *think*?  The prefix "*kilo*" *means* *thousand*.

- *kilo*meter = 1000 meters.
- *kilo*gram =  1000 grams
- *kilo*watt = 1000 watts.
- *kilo*byte = 1000 bytes.
