### ISSUE TITLE
Huawei mate 20 lite with android 12 does not work in the background

### ISSUE THREAD

**Issue by omejiasq** [transistorsoft/flutter_background_geolocation#984]
## Your Environment
* Plugin version:Current version
* Platform: iOS or Android: Android 12
* OS version:12
* Device manufacturer / model:Huawei mate 20 lite
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
N/A
```

## Expected Behavior

continue working the sending of data to the platform in the background.
## Actual Behavior

When the smartphone is blocked after a few seconds it no longer sends more data to the platform. It only sends data when the smartphone is unlocked.
## Steps to Reproduce

1. I enabled the execution in the background in the android settings in the battery part of the application, and it improved a bit, but it still does not send the data after the smartphone has been blocked for a while
2.

## Context

Enable background execution in the device settings in the battery part of the app.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Huawei are well known to be the worst offenders for violating the Android api.  They're the worst devices on earth.

There is no software solution for these poor devices.

See https://dontkillmyapp.com
