### ISSUE TITLE
Scheduled Task for all 3 states are getting delay even after set "forceAlarmManager=true". Why is it happening ?

### ISSUE THREAD

**Issue by prachishukla007** [transistorsoft/flutter_background_geolocation#987]
## Your Environment
* Plugin version: flutter_background_fetch:  ^4.9.0 , background_fetch:  ^1.1.1
* Platform: Android
* OS version: 12
* Device manufacturer / model: 21091116I , SM-M135FU
* Flutter info (`flutter doctor`): [✓] Flutter (Channel stable, 3.7.0, on Ubuntu 22.04.1 LTS 5.19.0-32-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

flutter_background_geolocation:-
bg.BackgroundGeolocation.ready(bg.Config(
          backgroundPermissionRationale: bg.PermissionRationale(
              title:
                  "Allow {applicationName} to access to this device's location in the background?",
              message:
                  "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
              positiveAction: "Change to {backgroundPermissionOptionLabel}",
              negativeAction: "Cancel"),
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          enableHeadless: true,
          locationUpdateInterval: 600000,
          distanceFilter: 0,
          heartbeatInterval: 60,
          disableElasticity: true,
          stopOnTerminate: false,
          startOnBoot: true,
          debug: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE))
      .then((bg.State state) {
    if (!state.enabled) {
      // 3.  Start the plugin.
      bg.BackgroundGeolocation.start();
    }
  });

background_fetch:-
          BackgroundFetchConfig(
              minimumFetchInterval: 15,
              forceAlarmManager: true,
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              requiresBatteryNotLow: false,
              requiresCharging: false,
              requiresStorageNotLow: false,
              requiresDeviceIdle: false,
              requiredNetworkType: NetworkType.NONE),
          _onBackgroundFetch,
          _onBackgroundFetchTimeout);
      debugPrint('[BackgroundFetch] configure success: $status');

      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "flutter_background_fetch",
          delay: 600000,
          periodic: true,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true));

```

## Expected Behavior
After putting the "forceAlarmManager = true" and assigning value to "delay: 600000", app should awake in every 600000 milliseconds(10 minutes).

## Actual Behavior
It works for few times(in all the states) and after an hour or more plugin stops waking up the app. Specially when I turn the screen off I face a lot of data loss.

## Steps to Reproduce

1. Install the app and login
2. Put your device still for few hours
3. Or turn the screen off for few hours(in any state)
4. Again open the app and check data. You will observe that there are so many data that has been lost.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Particular device manufacturers' version of the Android OS can *and will* throttle events when the screen is off.

See https://dontkillmyapp.com

Some devices simply don't behave and violate the Android API.
