### ISSUE TITLE
android headless task not running

### ISSUE THREAD

**Issue by sijanpoudel11** [transistorsoft/flutter_background_geolocation#988]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: 10 
* Device manufacturer / model: pocophone f1
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, 3.0.5, on macOS 13.0 22A380 darwin-arm, locale en-NP)
    • Flutter version 3.0.5 at /Users/sijanpoudel/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/sijanpoudel/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.App/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
<-- main.dart --> 

@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');
  var box = Hive.box('userData');
  box.put('headless entry1', " headless entry ");
  switch (headlessEvent.name) {
    case bg.Event.GEOFENCE:
      {
        var box = Hive.box('userData');
        box.put('headless entry', "${DateTime.now()} headless entry ");
      }

      

      break;
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await Hive.initFlutter();
  await Hive.openBox('mybox');
  await Hive.openBox('userData');

  FirebaseMessaging.instance.subscribeToTopic('general');

  FirebaseMessaging.onBackgroundMessage(backgroundHandler);

  ///record error on firebase crashlytics

  //TODO : commented just for test purpose
  //FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      // systemNavigationBarColor: Colors.blue, // navigation bar color
      statusBarColor: Colors.transparent, // status bar color
      statusBarBrightness: Brightness.light, // dark text
      statusBarIconBrightness: Brightness.dark));

  // ! uncomment later
  // Register BackgroundGeolocation headless-task.
  await bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);
  // allow the app to run only on portrait orientation
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).then(
    (_) {
      runApp(const ProviderScope(child: MyApp()));
    },
  );
}


<!-- splashscreen --> 
inside initState :

  bg.BackgroundGeolocation.addGeofences([
      bg.Geofence(
        notifyOnDwell: true,
        notifyOnExit: true,
        identifier: "Home",
        radius: 100,
        latitude: 27.7165,
        longitude: 85.2454,
        notifyOnEntry: true,
      ),
      bg.Geofence(
          notifyOnDwell: true,
          notifyOnExit: true,
          identifier: "Work",
          radius: 200,
          latitude: 27.71895,
          longitude: 85.34283,
          notifyOnEntry: true),
      bg.Geofence(
          notifyOnDwell: true,
          notifyOnExit: true,
          identifier: "Hospital",
          radius: 1000,
          latitude: 27.73774,
          longitude: 85.33150,
          notifyOnEntry: true)
    ]).then((bool success) {
      if (kDebugMode) {
        print('[addGeofences] success');
      }
    }).catchError((dynamic error) {
      if (kDebugMode) {
        print('[addGeofences] FAILURE: $error');
      }
    });

    bg.BackgroundGeolocation.onGeofence((bg.GeofenceEvent event) async {
      if (kDebugMode) {
        print('[geofence] ${event.identifier}, ${event.action}');
      }

      bg.BackgroundGeolocation.startBackgroundTask().then(
        (int taskId) async {
          bg.Location location =
              await bg.BackgroundGeolocation.getCurrentPosition(
                  samples: 2, persist: false, desiredAccuracy: 10);
          String? token = await FirebaseMessaging.instance.getToken();
          var body = {
            "firebase_id": await _getId(),
            "firebase_token": token.toString(),
            "locale": "en",
            "latitude": location.coords.latitude.toString(),
            "longitude": location.coords.longitude.toString(),
          };
          http
              .post(
                  Uri.parse(
                    "${Data.baseUrl}${Data.baseRoute}/firebase-users",
                  ),
                  body: body)
              .then(
            (value) {
              print('request geofence body ${body.toString()}');
              print('response geofence ${value.request.toString()}');
              bg.BackgroundGeolocation.stopBackgroundTask(taskId);
            },
          ).catchError((dynamic error) {
            if (kDebugMode) {
              print("[http test] failed: $error");
            }
            bg.BackgroundGeolocation.stopBackgroundTask(taskId);
          });
        },
      );
    });

    bg.BackgroundGeolocation.ready(bg.Config(
     
      enableHeadless: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    )).then((bg.State state) {
      // listen only for geofence events

      bg.BackgroundGeolocation.startGeofences();
    });
```

## Expected Behavior
Android app should run the headless function while terminated .

## Actual Behavior
Android app calls the api defined when in foreground or background on geofence entry exit  , but headless task in not called in terminated state . while terminated geofence entry exit sound  come but headless does not run . 

## Context
i am trying to call custom api in headless state as same as the foreground state . 

## Debug logs

  when app in foreground   
  

I/TSLocationManager( 2690): [c.t.l.scheduler.ScheduleEvent onOneShot]
I/TSLocationManager( 2690): ╔═════════════════════════════════════════════
I/TSLocationManager( 2690): ║ ⏰ OneShot event fired: TERMINATE_EVENT
I/TSLocationManager( 2690): ╠═════════════════════════════════════════════
D/TSLocationManager( 2690): [c.t.l.event.TerminateEvent$a a]
D/TSLocationManager( 2690):   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
I/flutter ( 2690): app locale en_US
I/flutter ( 2690): location taken true
Reloaded 1 of 1943 libraries in 2,964ms.
I/flutter ( 2690): app locale en_US
I/flutter ( 2690): location taken true
Reloaded 1 of 1943 libraries in 2,681ms.
D/TSLocationManager( 2690): [c.t.l.service.AbstractService start]
D/TSLocationManager( 2690):   🎾  GeofencingService [eventCount: 1]
I/TSLocationManager( 2690): [c.t.l.s.GeofencingService handleGeofencingEvent]
I/TSLocationManager( 2690): ╔═════════════════════════════════════════════
I/TSLocationManager( 2690): ║ Geofencing Event: ENTER
I/TSLocationManager( 2690): ╠═════════════════════════════════════════════
I/TSLocationManager( 2690): ╟─ Home
I/TSLocationManager( 2690): ╚═════════════════════════════════════════════
D/TSLocationManager( 2690): [c.t.l.g.TSGeofenceManager setLocation] isMoving: false | stateChanged: false | timerExpired: true | elapsed: 326442 | d: 2.644552
I/TSLocationManager( 2690): [c.t.l.data.sqlite.b persist]
I/TSLocationManager( 2690):   ✅  INSERT: 069d8b3c-66a6-4e70-8323-c0f43b4ddfb9
D/TSLocationManager( 2690): [c.t.l.service.AbstractService finish] ⚙️︎  finish GeofencingService [eventCount: 0, sticky: false]
I/flutter ( 2690): [geofence] Home, ENTER
D/TSLocationManager( 2690): [c.t.l.service.AbstractService start]
D/TSLocationManager( 2690):   🎾  BackgroundTaskService [eventCount: 1]
I/TSLocationManager( 2690): [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 1
D/TSLocationManager( 2690): [c.t.locationmanager.util.c h]
D/TSLocationManager( 2690):   ℹ️  LocationAuthorization: Permission granted
D/TSLocationManager( 2690): [c.t.l.service.AbstractService start]
D/TSLocationManager( 2690):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 2690): [c.t.l.l.SingleLocationRequest startUpdatingLocation]
I/TSLocationManager( 2690):   🔵  [SingleLocationRequest start, action: 2, requestId: 2]
D/TSLocationManager( 2690): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
D/TSLocationManager( 2690): [c.t.l.service.AbstractService onDestroy]
D/TSLocationManager( 2690):   🔴  GeofencingService stopped
V/MediaPlayer( 2690): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 2690): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer( 2690): mediaplayer went away with unhandled events
D/TSLocationManager( 2690): [c.t.l.service.AbstractService start]
D/TSLocationManager( 2690):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 2690): [c.t.l.s.LocationRequestService handleLocationResult]
I/TSLocationManager( 2690): ╔═════════════════════════════════════════════
I/TSLocationManager( 2690): ║ getCurrentPosition LocationResult: 2
I/TSLocationManager( 2690): ╠═════════════════════════════════════════════
I/TSLocationManager( 2690): ╟─ 📍  Location[fused 27.716481,85.245365 hAcc=21 et=+1d23h4m25s321ms alt=1420.800048828125 vAcc=1 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=568]}], age: 1197ms, time: 1679640257061
D/TSLocationManager( 2690): [c.t.l.g.TSGeofenceManager setLocation] isMoving: false | stateChanged: false | timerExpired: true | elapsed: 326888 | d: 1.5540589
D/TSLocationManager( 2690): [c.t.l.service.AbstractService start]
D/TSLocationManager( 2690):   🎾  GeofencingService [eventCount: 1]

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> D/TSLocationManager( 2690): ℹ️ TERMINATE_EVENT ignored (MainActivity is still active).

Your app is not *terminated*.  It is only in the background.  Terminated is when the MainActivity is terminated.

**Comment by christocracy** [comment]
In a terminal window, execute the command `$ adb logcat *:S TSLocationManager:V`

**Comment by sijanpoudel11** [comment]
> In a terminal window, execute the command `$ adb logcat *:S TSLocationManager:V`

i get this , 
 $ adb logcat *:S TSLocationManager:V                                                                                                                                                                            ─╯
zsh: no matches found: *:S

**Comment by christocracy** [comment]
https://developer.android.com/studio/command-line/logcat

![IMG_0326](https://user-images.githubusercontent.com/14999/227483162-5b6ec19b-19f3-45fa-9f1f-a2012d77c37a.jpeg)

**Comment by christocracy** [comment]
The docs to the `adb` command (Android Developer Bridge) are linked above.

please learn how to use this crucial development command, which streams logs from a device connected to USB into your terminal.

As a mobile developer, it’s assumed you *know *how to do this.

**Comment by sijanpoudel11** [comment]
> The docs to the `adb logcat` command (Android Developer Bridge) are linked above.
> 
> please learn how to use this crucial development command, which streams logs from a device connected to USB into your terminal.
> 
> As a mobile developer, it’s assumed you _know_ how to do this.

sorry to bother , 
but when my phone needs to be disconnected to the mac for testing geofences , how will this work in this scenario ?

**Comment by sijanpoudel11** [comment]
do you see anything wrong with my headless setup above ?

**Comment by christocracy** [comment]
Get your logs.

**Comment by sijanpoudel11** [comment]
sure , i'll get back with the logs ,
