### ISSUE TITLE
How to configure Geofence only

### ISSUE THREAD

**Issue by zorro2b** [transistorsoft/flutter_background_geolocation#991]
## Your Environment
* Plugin version: 4.9.0
* Platform: iOS
* OS version: 15.6.1
* Device manufacturer / model: iPhone 11
* Flutter info (`flutter doctor`): 
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-AU)

* Plugin config:
```dart
  static var config = bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_OFF);

    var state = await bg.BackgroundGeolocation.ready(config);

    if (!state.enabled) {
      await bg.BackgroundGeolocation.startGeofences();
    }
```

## Expected Behavior
Only geofence permissions requested

## Actual Behavior
Crash:
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.

## Context
Set up with geofence only permissions.

**Comment by christocracy** [comment]
See api docs Config.disableMotionActivityUpdates.
