### ISSUE TITLE
Android Error:  Crash from error in background/terminated state, Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by lloydelvt** [transistorsoft/flutter_background_geolocation#992]
## Your Environment
* Plugin version: ^4.9.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung (SM-G991U)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      //locationUpdateInterval: 5,
      //batchSync: true,
      useSignificantChangesOnly: Platform.isAndroid ? true : false,
      //persistMode: -1,//Only geofences are persisted
      maxRecordsToPersist: 25,
        url: "https://staging.motormouth.io/v2/user/location/flutter",
        params: {
          "profile_id" : AppData.currentProfile!.id
        },
        autoSync: true,
        //transistorAuthorizationToken: token,
        backgroundPermissionRationale: bg.PermissionRationale(
            title:
                "Allow Motor MotorMouth to access this device's location even when the app is closed or not in use.",
            message:
                "This app collects location data to enable recording your trips and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'),
        notification:
            bg.Notification(title: "Motor Mouth", text: "Location Service"),
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50.0,

        /*** stop receiving location updates when the app is terminated ***/
        stopOnTerminate: false,
        startOnBoot: true,

        /*** set to true to star location tracking immediately ***/
        isMoving: true,

        /*** enable headless mode for android, must be set to true! ***/
        enableHeadless: true,

        /*** et to false in release mode ***/
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE));
```

## Expected Behavior
We expect the application to run a simple sync in the background periodically handled by the work manager. 

## Actual Behavior
We are seeing a crash in the application from one of our beta testers. We believe it is happening when we call a SYNC in a background periodic task. Could this error be caused by power save mode enabled from our users? And if so how do we handle?

## Context
We would like the application to run a simple sync in the background periodically handled by the work manager. It is being handled well by other devices. 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
I am attaching the logs where we saw the error happening. please advise. 
[logs (Samsung Device Crash).txt](https://github.com/transistorsoft/flutter_background_geolocation/files/11091836/logs.Samsung.Device.Crash.txt)

</details>

**Comment by christocracy** [comment]
Your crash is caused by some other plug-in named `flutter_background_service.BackgroundService`

**Comment by ewa-radomska-codeclusive** [comment]
Hello, we have quite similar error when trying to SYNC on headless mode: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c1fe552 u0 com.yepic/com.transistorsoft.locationmanager.service.BackgroundTaskService}

env:
plugin version: 4.10.1
Platform: Android
OS version: 13
Device manufacturer / model: Galaxy S20+ 5G (y2s) (SM-G986B), Galaxy S22+ (g0s) (SM-S906B), Galaxy S21 Ultra 5G (p3s) (SM-G998B)

Plugin config:
`Config(
      autoSync: false,
      autoSyncThreshold: 20,
      desiredAccuracy: Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      elasticityMultiplier: 4,
      geofenceModeHighAccuracy: true,
      stopOnTerminate: false,
      startOnBoot: true,
      logLevel: Config.LOG_LEVEL_INFO,
      logMaxDays: 5,
      reset: kDebugMode,
      debug: kDebugMode,
      locationAuthorizationRequest: 'Always',
      enableHeadless: true,
      url: yepic_config.Config.LOCATION_API_URL,
      headers: headers,
      batchSync: true,
      maxBatchSize: 500,
      maxRecordsToPersist: 100000,
      maxDaysToPersist: 7,
      backgroundPermissionRationale: PermissionRationale(
        title: "Allow {applicationName} to access this device's location even when closed or not in use?",
        message: 'This enables the automatic logging of visits for your jobs',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: '',
      ),
    );`
    
    We are seing this crash from more than one of our beta testers (only Samsung Galaxy users). Is it the problem with external library or different plugin?
