### ISSUE TITLE
I'm getting more than 3 location updates 

### ISSUE THREAD

**Issue by ivangoluuk** [transistorsoft/flutter_background_geolocation#993]
I have the following issue.

so when I enable the updates (BackgroundGeolocation.start()) I receive 3 or more location data from the location callback

## Your Environment
* Plugin version: 4.8.7
* Platform: 
Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 10000,
        stopOnTerminate: true,
        startOnBoot: true,
        debug: false,
        allowIdenticalLocations: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
          title:
              "Permitir a {applicationName} acceder a la ubicación de este dispositivo, incluso cuando la app esté en segundo plano.",
          message:
              "{applicationName} recopila datos de ubicación para habilitar la asignación autómatica de pedidos, soporte en ruta y el registro de entrega de pedidos incluso cuando la aplicación está en segundo plano.",
          positiveAction: 'Cambiar a "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancelar',
        ),
      ),
    ).then((bg.State state) {
      _enabled = state.enabled;
      _isMoving = state.isMoving ?? false;
    });
```

## Expected Behavior

I just want to receive one update no more.

## Actual Behavior

I'm receiving more location updates

## Steps to Reproduce

1.  use bg.BackgroundGeolocation.start() then
2. bg.BackgroundGeolocation.stop() 
3. bg.BackgroundGeolocation.start()

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

<img width="1336" alt="Captura de pantalla 2023-03-28 a la(s) 14 54 25" src="https://user-images.githubusercontent.com/107516247/228364507-a3ac17dc-58c2-4946-ba36-23edbb43262c.png">
<img width="1316" alt="Captura de pantalla 2023-03-28 a la(s) 14 54 38" src="https://user-images.githubusercontent.com/107516247/228364509-5bb46b08-918b-4d93-a59f-7f887deb8625.png">

2 updates at the same time

<img width="1326" alt="Captura de pantalla 2023-03-28 a la(s) 15 06 18" src="https://user-images.githubusercontent.com/107516247/228367069-327e29e2-37e0-40f8-84c4-5e70fa4fe08a.png">
<img width="1366" alt="Captura de pantalla 2023-03-28 a la(s) 15 06 31" src="https://user-images.githubusercontent.com/107516247/228367071-b0f78d25-d51b-453f-9406-d390ca7893c0.png">

**Comment by christocracy** [comment]
That’s not at all unusual.

the plug-in doesn’t just request one location when you call .start(), the plug-in will “sample” up to 5 locations.  See api docs Location.sample.  

the final location settled upon is fired to the onMotionChange event (see api docs).
