### ISSUE TITLE
Can't publish to Google Playstore

### ISSUE THREAD

**Issue by devadrianapostol** [transistorsoft/flutter_background_geolocation#995]
Tried to publish to Playstore with the new update 4.10.0,  but I get:

Issue with your app
--
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK SDK which contains code to download or install applications from unknown sources outside of Google Play.Given the nature of the SDK, please remove it from the version of your app submitted to the Play Store.

because of Huawei dependencies.
 I suggest using different flavours in graddle file: https://stackoverflow.com/a/71588455

**Comment by devadrianapostol** [comment]
I don't hsve it. The issue is with "implementation" com.huawei...blabla". That is why you need flavours to not add the dependency at all. I'll use 4.9.0

**Comment by devadrianapostol** [comment]
I don't have hmsLocationVersion in my graddle. Niw it seems Playstore has a bug I cant remove the old version which wasn't accepted and all other subsequent releases are rejected even if I used old plugin version. And the client is upset I can't publush new version.

**Comment by christocracy** [comment]
Google Play Store just accepted my app update with `4.10.0` and `hmsLocationVersion  = "6.9.0.300"`.

<img width="770" alt="Screenshot 2023-03-30 at 1 36 25 PM" src="https://user-images.githubusercontent.com/14999/228920070-e18ad51f-25af-4dc7-abe2-53d27d0fecf7.png">

**Comment by christocracy** [comment]
Another app published and live (*React Native* version)

<img width="840" alt="Screenshot 2023-03-30 at 6 53 15 PM" src="https://user-images.githubusercontent.com/14999/228982427-6719c899-02e0-43b5-9f1b-c3683306ad59.png">

**Comment by christocracy** [comment]
Third app published and live (*Cordova* version)
<img width="774" alt="Screenshot 2023-03-31 at 10 49 34 AM" src="https://user-images.githubusercontent.com/14999/229154478-9d609495-d53b-4fe3-845d-61952e4ecc5c.png">
