### ISSUE TITLE
App rejected by Google Play because of Huawei HMS SDK

### ISSUE THREAD

**Issue by frankvollebregt** [transistorsoft/flutter_background_geolocation#999]
## Your Environment
* Plugin version: 4.10.0
* Platform: Android

## Expected Behavior

When I submit my app to the Play Store, I expect it to upload and get released. Note that I am *not* using any Huawei/HMS functionality of the 4.10 release.

## Actual Behavior

After updating, when I uploaded my app bundle to the Google Play Console, I got notified that I needed to provide a reason for using the `android.permission.REQUEST_INSTALL_PACKAGES` permission. I figured it was some functionality unused by me of one of the dependencies. I ended up manually removing this permission from my `AndroidManifest` like so:

```xml
<!-- remove the REQUEST_INSTALL_PACKAGES permission -->
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/>
```

But now, when I submit my Android app to Google Play, it gets rejected. I receive the following message (screenshot):
![image](https://user-images.githubusercontent.com/23523399/228866787-84689940-498b-4c26-bdf4-854040899cda.png)
The inclusion of the Huawei SDK makes Google Play reject my app.

See also https://support.google.com/googleplay/android-developer/answer/9888379/

## Steps to Reproduce

1. Include bg 4.10 in your Flutter app
2. Upload a release version to the Google Play Console
3. Submit it
4. ...
5. After a while, it gets rejected for violating policy

## Thoughts
While the error message suggests that the inclusion of the SDK is causing the error, perhaps the specific `permission`s for installing apps could simply be disabled from the `AndroidManifest` in this package?

**Comment by christocracy** [comment]
I'm investigating

**Comment by HadiHassan22** [comment]
Same issue here

**Comment by christocracy** [comment]
I found that `4.10.0` was using an out-dated default version of `hmsLocationVersion = "6.0.0.302"`
```diff
buildscript {
    ext {
        .
        .
        .
+       hmsLocationVersion  = "6.9.0.300"   // <-- updated version
```

I just submitted an update with `4.10.0` and `hmsLocationVersion` as above to *Play Store* and my update was accepted.

I will release `4.10.1` with default `hmsLocationVersion  = "6.9.0.300"`.

<img width="770" alt="Screenshot 2023-03-30 at 1 36 25 PM" src="https://user-images.githubusercontent.com/14999/228919536-a6cb0ce5-2420-4fd4-8445-add55eb12b1e.png">

**Comment by christocracy** [comment]
Another app published and live (*React Native* version)

<img width="840" alt="Screenshot 2023-03-30 at 6 53 15 PM" src="https://user-images.githubusercontent.com/14999/228982526-05fb04f3-d0be-4eb7-8267-0857a0f458eb.png">

**Comment by frankvollebregt** [comment]
Awesome! I trust it'll work for me too then, so I'll close this issue (and reopen it should it somehow not work when I push out my next app update)

**Comment by christocracy** [comment]
Third app published and live (*Cordova* version)
<img width="774" alt="Screenshot 2023-03-31 at 10 49 34 AM" src="https://user-images.githubusercontent.com/14999/229154478-9d609495-d53b-4fe3-845d-61952e4ecc5c.png">

**Comment by frankvollebregt** [comment]
My own app also published successfully with the new package version 👍 thanks for the quick turnaround on this issue!
